### ISSUE TITLE
It doesn't start maximized even though I have set that every program starts maximized in kde.

### ISSUE THREAD

**Issue by Toadfield** [dosbox-staging/dosbox-staging#1001]
**Describe the bug**
Normally,every program that is capable of being maximized should start maximized.

**To Reproduce**
Install Kde,go to System Settings>Window Behavior>Advanced and select Window Placement=Maximized.

**Expected behaviour**
That it starts maximized like any other program

**Environment (please complete the following information):**
- OS and version: Arch with Kernel 5.11.16 and kde and wayland
- Relevant hardware info: radeon Sapphire Rx 580 8gb and Ryzen 5 3600
**Version of dosbox-staging:**
1:0.76.0-3

**Configuration parameters:**
Standard Configuration

**Comment by kcgen** [comment]
DOSBox's window size is controlled by the resolution setting in your conf file.  Try setting `fullscreen = true`.

**Comment by Toadfield** [comment]
But I don't want it in fullscreen,I want it maximized (so with borders,just that it fills the whole screen).

**Comment by kcgen** [comment]
try a bigger `windowresolution`, like your desktop resolution or a 4:3 equivalent.

**Comment by Toadfield** [comment]
that works.
