### ISSUE TITLE
Disable (capture) the default macOS system shortcuts

### ISSUE THREAD

**Issue by Burrito78** [dosbox-staging/dosbox-staging#1006]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when i try to use F11 in a game but it is already used by macOS as a system shortcut (Show Desktop).

**Describe the solution you'd like**
Dosbox-Staging should attempt to capture macOS hotkeys that will interfere with games, like F11 or Ctrl+arrowkeys,  ensuring the keypresses go to the DOS game instead of triggering system shortcuts.

**Describe alternatives you've considered**
Manually disabling the Shortcuts in macOS in Settings -> Keyboard -> Shortcuts.

The wonderful but also abandoned macOS app "Boxer" does have this functionality:
https://github.com/alunbestor/Boxer/issues/30

**Comment by kcgen** [comment]
@alunbestor, @madthesane - Do you know what's involved, code-wise, to _"allow an apps to control your computer"_, like you've done for Boxer?

![68747470733a2f2f662e636c6f75642e6769746875622e636f6d2f6173736574732f3137373432322f313332323232322f32643533616338612d333431622d313165332d393631312d3437393664633631346436322e706e67](https://user-images.githubusercontent.com/1557255/117848390-1bd83900-b238-11eb-85a2-095022f98e43.png)

At a minimum, it would be nice to import/absorb this aspect into DOSBox Staging, so its basic hotkeys (and those used by a DOS game) don't conflict with the OS's own hotkeys.

**Comment by kcgen** [comment]
Thank you @MaddTheSane!

This indeed looks like a non-trivial amount of ObjC / Swift wrapping that needs to capture the key strokes.  I also see that SDL2 itself has no handling for this capture-mode.

I will add this to our backlog, in need of real hardware to investigate this further.

**Comment by MaddTheSane** [comment]
I think most of the code is C, using Core Graphics (`CGGetEventTapList`) and Application Services (the `AXIsProcessTrustedWithOptions` function is in HIServices framework, which is in ApplicationServices); it's just easier to use Cocoa/Objective-C for most Apple developers.

**Comment by Burrito78** [comment]
This is out-of-scope currently as we have no idea how to do it properly with nice code.
