### ISSUE TITLE
windows/vs2019 master build with libmt32emu does not work

### ISSUE THREAD

**Issue by LowLevelMahn** [dosbox-staging/dosbox-staging#1012]
i did update vcpkg with update/upgrade but still vcpkg is telling me that libmt32emu is not available, i just copied the vcpkg install line from the readme.md

as a result the headers etc. are missing for compilation

**Comment by kcgen** [comment]
Here's a couple steps to try:

1. Ensure your VCPKG is up-to-date:

    ``` shell
    cd c:\vcpkg
    git pull
    .\bootstrap-vcpkg.bat
    ```

1.  Attempt to install all dependencies:

    ``` shell
    vcpkg install --triplet x64-windows libpng sdl2 sdl2-net libmt32emu opusfile fluidsynth
    ```

1.  Integrate the installed packages

    ``` shell
    vcpkg integrate install
    ```

Hopefully that takes care of it - let me know.

**Comment by LowLevelMahn** [comment]
removed completely my manualy installed vcpkg version 2021.04.30 and switched over to git

mt32 stuff is now found 
but vcpkg git master and latest release tag: 2021.05.12 (release 3 days ago) failed while installing glib

```
...
Starting package 8/16: glib:x64-windows
Building package glib[core]:x64-windows...
-- Downloading https://ftp.gnome.org/pub/gnome/sources/glib/2.66/glib-2.66.4.tar.xz -> glib-2.66.4.tar.xz...
-- Extracting source D:/tools_NEW/vcpkg/downloads/glib-2.66.4.tar.xz
-- Applying patch use-libiconv-on-windows.patch
-- Applying patch fix-libintl-detection.patch
-- Using source at D:/tools_NEW/vcpkg/buildtrees/glib/src/glib-2-b84205c786.clean
-- Configuring x64-windows
-- Using msys root at D:/tools_NEW/vcpkg/downloads/tools/msys2/50864d9fae363d6e
-- Configuring x64-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:105 (message):
    Command failed: D:/tools_NEW/vcpkg/downloads/tools/python/python-3.9.2-x64/python.exe D:/tools_NEW/vcpkg/downloads/tools/meson/meson-753954be868ed78b3e339e8811fd1d29eb2af237/meson.py -Dbuild_tests=false -Dinstalled_tests=false -Dseli
    Working Directory: D:/tools_NEW/vcpkg/buildtrees/glib/x64-windows-dbg
    Error code: Exit code 0xc0000135



    See logs for more information:

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_meson.cmake:455 (vcpkg_execute_required_process)
  ports/glib/portfile.cmake:42 (vcpkg_configure_meson)
  scripts/ports.cmake:142 (include)


Error: Building package glib:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: glib:x64-windows
  Vcpkg version: 2021-05-05-9f849c4c43e50d1b16186ae76681c27b0c1be9d9

Additionally, attach any relevant sections from the log files above.
```

**Comment by kcgen** [comment]
Well,. that's frustrating. Sorry it didn't work. If you still have the full log for the entire vcpkg run (from the top, including all the early smaller packages), I'd like to compare it to our current run, which I see also builds glib-2.66.4:

https://pipelines.actions.githubusercontent.com/RDKYnb9yFkXPfcXINdFWH3mzDaNqlgzrXM4kV8rnx6PJBbLLEF/_apis/pipelines/1/runs/34019/signedlogcontent/3?urlExpires=2021-05-17T08%3A51%3A10.4149634Z&urlSigningMethod=HMACV1&urlSignature=aJ2BmYEIeBPySHo8jI%2F8URQsUq2j3Bw12Hx%2FVYo7M1I%3D

Another small difference is the CI machines lag in time slightly from the latest vcpkg - so it's highly likely you've hit a real and new bug in vcpkg, which we will also his when GitHub updates their VMs this coming Wednesday. 

As a double-check, I'd also run through the install steps okn my vanilla Win10 install and see if it also fails.

**Comment by kcgen** [comment]
@LowLevelMahn , 

The builds are working on my Win10 system; and I suspect the vcpkg team (who are Microsoft employees) will recommend you upgrade from Windows 7 to 10, given 7 fell out of support more than 14 months ago. 

That said - I I can't see why Win7 should have any problems, given all the dependencies are in-place (VS2019, Git, vcpkg.. ).  I will install Windows 7 from scratch and see if we can figure out where it's going off the rails.

In the meantime, trembyle here has setup a build environment on Windows too.
@trembyle, I forgot which OS you were using - did you have good luck? Thank for the help.

**Comment by LowLevelMahn** [comment]
'ive filed an issue https://github.com/microsoft/vcpkg/issues/17981 - maybe its related to my very latest cmake version?

**Comment by kcgen** [comment]
> 'ive filed an issue [microsoft/vcpkg#17981](https://github.com/microsoft/vcpkg/issues/17981) - maybe its related to my very latest cmake version?

Could be - especially if it's in your global PATH. 

I hit a bunch of snags in setting up my VM; PowerShell under Windows 7 is too old so bootstrap threw unrecognized syntax errors.. so had to upgrade some manger service to 5.1, then PowerShell to 7.x, and reboot-strapped, but then during the vcpkg build I was getting 'the linker stopped running' errors repeatedly.  After attempting a reinstall of vs2019 my VM was running too low on disk space (24 GB total wasn't enough!?), And the installer refused to proceed. so I've dumped it and will start fresh again tomorrow.

**Comment by LowLevelMahn** [comment]
there is no real need for Powershell (not required according to the vcpkg github page), and a VS2019 C/C++ only installation should be enough (i can't remember if i skipped all the .NET, Web Stuff on installation or just didn't installed it afterwards)

**Comment by kcgen** [comment]
Thanks for the tips, @LowLevelMahn - that'll make setup quicker (and use less disk space)!

**Comment by kcgen** [comment]
I constantly get this:

![2021-05-18_09-26](https://user-images.githubusercontent.com/1557255/118694408-e647c880-b7c0-11eb-85a2-daba8df3e39b.png)

 I've tried multiple re-installations of vs2019, selecting the major "C++/C" category (leaving all default sub-options as-is), and still get it.  I've also tried enabling other C++ options, but it doesn't change anything.

Will open a vcpkg bug for it.

Not sure if it's VM-related or Windows-7 specific; my physical machine (where this works) is Windows 10.

**Comment by LowLevelMahn** [comment]
from the vcpkg issue: 

https://github.com/microsoft/vcpkg/issues/17981#issuecomment-843525761
> As @Neumann-A stated, Python 3.9 (used to build glib) is not supported on Windows 7.

that means more or less: no win7 support for dosbox staging, or?

**Comment by kcgen** [comment]
Very interesting; PEP11's rationale is very reasonable: https://www.python.org/dev/peps/pep-0011/#id12

Given this involves a vcpkg-built FluidSynth dependency, I can imagine many options to work around this:
1. Build a binary on a platform that python 3.9 supports, and then carry  the binary back to Win7. 
2. Transplant FluidSynth libraries and headers from a platform where it can be built, and drop those into your vcpkg area in Win7.
3. Forgo FluidSynth by disabling it in the vs/config.h file (and then run an external MIDI synthesizer). 
4. Attempt some other Linux-like mechanism to install dependencies and perhaps use Meson to manage your build: msys2, WSL, cygwin(?).

None of those are great; although simply knocking out FluidSynth seems like the most reasonable option to have a working dev environment. 

Perhaps running the binaries from GitHub CI is the best choice to give you all the features.

**Comment by LowLevelMahn** [comment]
> None of those are great; although simply knocking out FluidSynth seems like the most reasonable choice to not get bogged down and at least get a working dev environment.

its ok for me as long MT32 emulation still works without

> Perhaps running the binaries from GitHub CI is the best choice to give you all the features (from a non-dev angle).

im playing around with the debugger implementation to find any code (in an game) that reads 4 unknown bytes :)
so i need to debug in VS2019 at least (missing the good old SoftIce Memory read breakpoint feature)

**Comment by LowLevelMahn** [comment]
leaving out FluidSynth works - thx

**Comment by kcgen** [comment]
Thanks for getting to the bottom of this - it will surely help other Win7 users!
Let's keep this open until we document this nuance in either readme or build instructions.

**Comment by LowLevelMahn** [comment]
first time hearing MT32 sound - wonderfull :)
