### ISSUE TITLE
MT32: std::vector end exceed in void MidiHandler_mt32::Render()->Process...

### ISSUE THREAD

**Issue by LowLevelMahn** [dosbox-staging/dosbox-staging#1023]
Source:
git master, lastest commit is
Commit date:	9 hours ago (21.05.2021 00:13:03)
Commit hash:	77b480b1d871456a7338b4d4f0b46c912bfd2b3c

config.h:

```
#define C_DEBUG 1
#define C_HEAVY_DEBUG 1
#define C_FLUIDSYNTH 0

```
System:
Win7 x64, VS2019 (lastest as of 21.5.2021), x64 Debug build run in debugger

dosbox config:

default git config with mt32 config based on mame roms + using model=mt32_old
and core=normal (to ease debugging)

```
mididevice=mt32

[mt32]
romdir=D:\mame_mt32_cm32l_roms\all

# models
# https://github.com/dosbox-staging/dosbox-staging/pull/965#issue-608311889
model=mt32_old

```
Issue:
assert in std::vector "cannot seek vector iterator after end"

Cause:
```
template <int8_t channel>
void SoftLimiter::ScaleOrCopy(const std::vector<float> &in,
                              const uint16_t samples,
                              const float prescalar,
                              const in_iterator_t precross_peak_pos,
                              const in_iterator_t zero_cross_pos,
                              const float global_peak,
                              const float tail,
                              std::vector<int16_t> &out)
{
	assert(samples >= 2); // need at least one frame
	auto in_start = in.begin() + channel;
	const auto in_end = in.begin() + channel + samples; <-- exceeds vector end by 1
```

happens on startup of dosbox

![source](https://user-images.githubusercontent.com/580819/119097528-22736700-ba15-11eb-8c3d-d8a52a870bb4.png)
![stack](https://user-images.githubusercontent.com/580819/119097531-23a49400-ba15-11eb-856c-aa6b25650a15.png)
![assert](https://user-images.githubusercontent.com/580819/119097533-243d2a80-ba15-11eb-9b80-5839a3fccdbe.png)

**Comment by LowLevelMahn** [comment]
how did that error sliped through the auto testing? or is the mt32 stuff not part of the multi-config/... testing?

**Comment by kcgen** [comment]
Thank you for this report @LowLevelMahn.

The second-channels end-offset is only used as a `!=` boundary condition and is never actually read or written to; therefore it actually passes our static and dynamic memory analysis. 

That said - it _is_ an invalid address - and the warning from Visual Studio is helpful. I've made a small adjustment in branch `kc/soft-limiter-bounds-1` (and made a draft PR).

It passes unit tests and static and dynamic analysis in Linux.  Curious if this passes for you.

**Comment by LowLevelMahn** [comment]
seems to be fixed
