### ISSUE TITLE
Use vcpkg/Binary Caching to speed up the CI build?

### ISSUE THREAD

**Issue by LowLevelMahn** [dosbox-staging/dosbox-staging#1030]
i just saw how long the MSVC build takes - could vcpkg Binary Caching help?

https://github.com/microsoft/vcpkg/blob/master/docs/users/binarycaching.md

**Comment by kcgen** [comment]
Every run on GitHub's CI machines are brand new virtual machines without any prior data. 
But GitHub does let us save files to to cache, so we're caching all of vcpkg (we also cache all build results across the CI runs). However, for Windows we regenerate the cache once per day, to allow for new packages to be used in vcpkg. 
If you go back in the actions run today, you'll see other Windows builds only took a couple minutes. 
It just happens that the date cross over happened, and your run was first one today 😌.

Subsequent pushes will go ripping fast 🚀
