### ISSUE TITLE
vcpkg installation etc.

### ISSUE THREAD

**Issue by LowLevelMahn** [dosbox-staging/dosbox-staging#1034]
from my expirience:

-you need to have the VS2019 "English language pack" installed or else you will get strange errors
that seem total unrelated to languge packs (ninja did not get found and others)
--> there is a yellow warning in the console output that warns you about the missing language pack
under Win7 x64 and Win10

-do not put vcpk in pathes with blanks

uses  --triplet x86-windows if you want x86 libs

more?

**Comment by kcgen** [comment]
Thanks @LowLevelMahn! I'm working on another small update to the unit tests and will add these notes. 

Regarding the language pack - I'm having a hard time finding where or how this is installed: is it part of the VS2019 Installer program?  Any notes or pointers would be a big help.

**Comment by LowLevelMahn** [comment]
you can reach the language pack installation directly from the IDE or by starting the installer

![in_installer1](https://user-images.githubusercontent.com/580819/120097090-f485d500-c12e-11eb-90ab-6af512490659.png)
![in_installer2](https://user-images.githubusercontent.com/580819/120097091-f51e6b80-c12e-11eb-902a-71c952982910.png)
![from_ide](https://user-images.githubusercontent.com/580819/120097092-f51e6b80-c12e-11eb-9fa4-e97e5b51ccda.png)

**Comment by LowLevelMahn** [comment]
to make it clear - it its only needed because im using a german version of VS2019 - if english is your installation language every should work out of the box
