### ISSUE TITLE
Add Clang-Tidy as a static/style/code checker

### ISSUE THREAD

**Issue by kcgen** [dosbox-staging/dosbox-staging#1040]
Thanks for this recommendation, @LowLevelMahn!

Areas we can employ it in:
 - Checking PRs against [Staging's coding-style guidelines](https://github.com/dosbox-staging/dosbox-staging/blob/master/CONTRIBUTING.md#coding-style)
    We took the most common style found in upstream and used that. Hope is that the code here is "eyeball compatible" across projects, so contributors can use/patch/share between projects. 
 - Employing best-practices: security, safety, and performance improvements.
 - Recommending replacements for syntax that it knows are deprecated in future C++ specs (like 17 or 20).
 - Performing "uplift" when nicer syntax is available. 

We just want to be able to avoid over-blowing the excessive C++'isms that bloat the source (like using stringstreams instead of format-strings, or some of the more exotic constructs that border on unreadable).

A starting point would be figuring out how to configure and run it - and get useful recommendations from it.

Next step would be to write a script similar to `./scripts/format-commit.sh` that produces fixes (or recommendations) for only the changed-code: so developers can use it as part of their daily routine.

**Comment by kcgen** [comment]
@LowLevelMahn , do you know how to run it and get recommendations (or fixes) from it? 
I can run it - but it doesn't generate any output for me.

**Comment by LowLevelMahn** [comment]
> @LowLevelMahn , do you know how to run it and get recommendations (or fixes) from it?
> I can run it - but it doesn't generate any output for me.

because the staging source base is already perfect :)

i will check my customers setting tomorrow

**Comment by kcgen** [comment]
> > @LowLevelMahn , do you know how to run it and get recommendations (or fixes) from it?
> > I can run it - but it doesn't generate any output for me.
> 
> because the staging source base is already perfect :)

:joy: 

> i will check my customers setting tomorrow

:100:

**Comment by LowLevelMahn** [comment]
my customer only uses clang-tidy on per file basis like in the first tip in this link: https://developers.redhat.com/blog/2021/04/06/get-started-with-clang-tidy-in-red-hat-enterprise-linux#integrate_clang_tidy_into_your_build_system

but i think using a compile database is better (meson seems to support that too)

https://blog.jetbrains.com/clion/2021/01/working-with-meson-in-clion-using-compilation-db/

**Comment by Burrito78** [comment]
@kcgen Still happening? Outdated?
