### ISSUE TITLE
Wrong code page loading with `keyb` command

### ISSUE THREAD

**Issue by Kappa971** [dosbox-staging/dosbox-staging#1062]
By inserting the command "keyb it" to load the Italian translation, it is loaded but with the wrong code page (code page 437 is loaded instead of 850). This causes problems with some fonts. The solution is to run the command "keyb it 850" but I don't find it very immediate, especially for inexperienced people.
The solutions could be:
1. Tie a language and code page together, in the event a code page isn't provided.
    Example: "keyb it" will load the Italian translation with code page 850, as no code page is specified, so the default one for the 
    language in question is loaded.
2. DOSBox automatically executes the "keyb" command, choosing the right code page, based on the specified translation file.

**Comment by Burrito78** [comment]
I just noticed that i can't enter the tilde character with "right alt" + "+" if i load the german keyboard layout using keyb gr only. 

I have to also specify codepage 437 using "keyb gr 437" to have proper special characters. 

Don't know if thats expected, a bug or just poor usability. :)

**Comment by Kappa971** [comment]
This problem I believe affects all languages except English. Each language has its DOS code page, in this case the wrong code page is loaded, I think it can be considered as a bug.

![Immagine 2021-06-28 155958](https://user-images.githubusercontent.com/62349018/123649300-f1fbc580-d829-11eb-9958-4ce4e9a1baee.png)

In the Windows command prompt I discovered the correct code page (in this case for Italian)

**Comment by Burrito78** [comment]
I need to clarify my statement above. I was wrong. "keyb gr" loads codepage 858 which seems to be right for the german special characters. Ä, Ü,ß, € are working correctly as is z and y (they are switched on german keyboards).

But special characters like the graphical symbols Norton Commander uses or edit.com for their window frames are wrong.

But if i load "key gr 437" specifically, everything is working right 100% (ok, i'm loosing the Euro-Symbol but who cares).

So maybe using 437 for german is the "more correct" codepage for running old DOS programs and should be the default.
