### ISSUE TITLE
Frontier: First Encounters not working

### ISSUE THREAD

**Issue by HW-Scanno** [dosbox-staging/dosbox-staging#1071]
As the title says the game Frontier: First Encounter is working and playable on ECE albeit with some minor hiccups during the full motion video played in the communication screens directly from the mounted iso.
The behavior in Staging instead is more severe making 1 second of the game like 3 seconds in real life between all the stutterings.

Reproducing the bug is simple because the game begins stuttering from the intro, so no playtime is required.
Also an increased loading time is also noticed and it is visible the blank cursors blinking slowly in top left.

The expected behavior is to be able to play it more or less like SVN

My PC: W10 Pro, Ryzen 3600, RTX 3060, 16gb RAM 3600Mhz

DOSBox Staging Version: 0.77.0-alpha-871-gbd01

[Frontier - First Encounters (1995).conf.txt](https://github.com/dosbox-staging/dosbox-staging/files/6619500/Frontier.-.First.Encounters.1995.conf.txt)

**Comment by kcgen** [comment]
Bisected the issue to commit 0e0934b9

649a428d   7 days ago Dynamic core support for W^X systems
0e0934b9   7 days ago Dynamic core support for W^X systems
baba5ab9   8 days ago Eliminate existing poll-throttling counters
ff42c8e4   8 days ago Process SDL's event queue prior to each host video frame
9fd81a79   8 days ago Use a lookup table to convert 8-to-16 bit samples
5e120466   8 days ago Don't shift negative values (undefined behavior)
4aac3e9e   8 days ago Ensure input is focused when fullscreen to avoid stranding
42a09f5e   8 days ago Fix shifting of negative samples in DB OPL

Thanks for this report @HW-Scanno! 

I will try to find you a binary just prior to the bisection point.

**Comment by kcgen** [comment]
@HW-Scanno,

Here are three Windows builds from our CI system at different points:

1. This first one is just prior to the issue appearing on Linux; here's the Windows-build of that.  This should perform on-par with ECE and SVN: https://github.com/dosbox-staging/dosbox-staging/suites/2875191330/artifacts/64283370

2. Here's a Windows build of the bisected commit.  We know this commit _has_ the issue on Linux but we're not sure if Windows is affected. Will be very curious what you find with this one: https://github.com/dosbox-staging/dosbox-staging/suites/2882756877/artifacts/64496221

3. Finally, here's a Windows build that very likely _has_ the issue, similar to the very latest build from CI: https://github.com/dosbox-staging/dosbox-staging/suites/2920828624/artifacts/65561974

The results of these three will help @kklobe and I proceed to address it; thanks @HW-Scanno!

**Comment by HW-Scanno** [comment]
@kcgen ,

As you suggested, 1. and 2. had same performances on par with ECE.
The 3. has the problems we talked about.

You are right about it, the fix will elevate the status of Frontier: First Encounters from unsupported to playable. Thanks everyone!

**Comment by kklobe** [comment]
@HW-Scanno I have a potential fix that worked well on my Windows system, please try https://github.com/dosbox-staging/dosbox-staging/suites/2950587619/artifacts/66373556

**Comment by HW-Scanno** [comment]
I can confirm that the stuttering and hiccups are no more, it is returned to normal and expected behaviour.
You can close this issue as solved at this point! Thanks!

**Comment by kcgen** [comment]
That's great news @HW-Scanno - thanks for the extremely far fix for this @kklobe !

We'll tie this issue to @kklobe 's (soon-to-be) PR, which will automatically close it once the PR's merged.

**Comment by grapeli** [comment]
Under Linux, this difference was small. Hard to notice on the first try. Over the 50 seconds of loading and the intro flow, it was approximately 5 seconds. This hotfix fixes.

My other note - the intro for this game is not displayed correctly in dosbox-staging with `machine=svga_s3` configuration. Clearly visible (screen flashes).
Sample screenshot.
![dosbox-staging svga_s3](https://user-images.githubusercontent.com/452325/121538101-09e2e500-c9f4-11eb-9560-a16da9728f47.png)

Dosbox-X renders correctly with `machine=svga_s3` configuration.
![dosbox-x svga_s3](https://user-images.githubusercontent.com/452325/121538162-15361080-c9f4-11eb-87f5-334a3b7b7a34.png)

Dosbox-staging renders correctly with `machine=vgaonly` configuration.
![dosbox-staging vgaonly](https://user-images.githubusercontent.com/452325/121538237-254df000-c9f4-11eb-8eb8-b8c9daec67e1.png)
