### ISSUE TITLE
Hammer of the Gods - NetBIOS multiplayer doesn't work

### ISSUE THREAD

**Issue by GranMinigun** [dosbox-staging/dosbox-staging#1077]
**Describe the bug**
Hammer of the Gods for some reason doesn't detect loaded Novell NetBIOS driver. From the game's installation manual:
> Network play is supported solely with a **NETBIOS** driver loaded. Novell users can type **netbios** at the command line to load this driver, if their network drivers are on path and fully installed.

![hamgam_001](https://user-images.githubusercontent.com/11149380/121770785-daafad80-cb84-11eb-85d0-6d12eaaaf588.png)

**To Reproduce**
1) Enable IPX and load `IPXNET`;
2) Load `NETBIOS`;
3) Launch the game;
4) Proceed to network session setup.

**Expected behaviour**
The game creating network session and waiting for clients to connect.

**Environment (please complete the following information):**
Arch Linux.

**Version of dosbox-staging:**
v0.77.0-alpha-888-g920c1db6 (and earlier).

**Configuration parameters:**
`ipx = true`

**Additional context**
Using Novell NetBIOS 3.17 from 1995. Upstream and -X also have that problem. The only other NetBIOS games that I tried were Heroes of Might and Magic 1 and 2, and these work fine, although transfer speed is ridiculously low.

![netbios](https://user-images.githubusercontent.com/11149380/121771467-f917a800-cb88-11eb-990d-0b878b67abb4.png)

**Comment by kcgen** [comment]
Solved by ripsaw8080 [on vogons.org](https://www.vogons.org/viewtopic.php?p=948712#p948712):

> Before the game checks NETBIOS it checks for a network, a seemingly unusual extra step. It is actually the network check that fails, so the error message about NETBIOS is misleading. The attached workaround program will satisfy the network check; just run it in DOSBox before starting the game.
>
> A patch is being considered to support the network check in DOSBox when ipx=true, but there is a concern that it could cause issues to indicate the presence of a network when there really is none.
>
> [netcheck.zip](https://github.com/dosbox-staging/dosbox-staging/files/6642359/netcheck.zip)

**Comment by GranMinigun** [comment]
Confirmed, four player game, all good.
