### ISSUE TITLE
Dedicated IPXNET server

### ISSUE THREAD

**Issue by GranMinigun** [dosbox-staging/dosbox-staging#1081]
Suppose there are n number of people behind ISP's NAT and just one with dedicated address. That one generous person could host `IPXNET` server for others to play. Currently they'll need to keep DOSBox window around, wasting some precious resources along the way without playing anything.

It would be nice to either have a command line option(s) to launch DOSBox's `IPXNET` server only, without emulation and graphics, or even provide possibility to build just `IPXNET`.

**Comment by kcgen** [comment]
Breaking the server out from the binary would also free the code to use other languages, for example, Rust, Go, etc..  and leverage their forte's, such as asynchronous communication and stronger/safer code.

**Comment by arrowgent** [comment]
this is true, i do this for a dedicated IPXNET server also
some kind of -command interpreter to allow starting as -ipxserver could be very useful
pull the specifications you want from dosbox.conf

on linux it would be interesting if connects/disconnects, ect could be stdout to the terminal aswell.

**Comment by NicknineTheEagle** [comment]
There's currently a third party tool that does this called ipxbox: https://github.com/fragglet/ipxbox. It also has multiple useful features such as bridging to physical network (which allows DosBox to connect to a real DOS machine). There are no compiled binaries, though, and it doesn't work properly on Windows (only on Linux).

**Comment by Burrito78** [comment]
@kcgen Out-of-scope much?

**Comment by kcgen** [comment]
Could/should be a separate repo.
