### ISSUE TITLE
tests/soft_limiter crashes if GLIBCXX_ASSERTIONS is enabled

### ISSUE THREAD

**Issue by oturpe** [dosbox-staging/dosbox-staging#1085]
**Describe the bug**
If dosbox-staging is compiled with `GLIBCXX_ASSERTIONS` in `CXXFLAGS`, test suite tests/soft_limiter` crashes with the following error during test case _SoftLimiter.InboundsProcessTooManyFrames_:

```
/usr/include/c++/11/bits/stl_vector.h:1063: std::vector<_Tp, _Alloc>::const_reference std::vector<_Tp, _Alloc>::operator[](std::vector<_Tp, _Alloc>::size_type) const [with _Tp = short int; _Alloc = std::allocator<short int>; std::vector<_Tp, _Alloc>::const_reference = const short int&; std::vector<_Tp, _Alloc>::size_type = long unsigned int]: Assertion '__n < this->size()' failed.
Aborted (core dumped)
```

**To Reproduce**
Configure, compile and run the test as follows:

```
CXXFLAGS='-Wp,-D_GLIBCXX_ASSERTIONS'
export CXXFLAGS
meson --buildtype=plain -Duse_mt32emu=false build
meson compile -C build -j 4
build/tests/soft_limiter
```

**Expected behaviour**
Test suite runs and passes.

**Environment (please complete the following information):**
- OS and version: Fedora 34 (originally encountered in the Fedora Rawhide package build environment)
- Relevant hardware info: x86_64

**Version of dosbox-staging:**
Commit b8efb8c842b7bbf9ec6ac94cf8c68000767e9660

**Configuration parameters:**
n/a, this is a build failure

**Additional context**
This was encountered when attempting to enable the test suite in Fedora package build.

**Comment by kcgen** [comment]
That test case, processtoomanyframes, is deliberately trying to process too many frames.  The expected output in the Google test suite is a debug crash: 

https://github.com/dosbox-staging/dosbox-staging/blob/b8efb8c842b7bbf9ec6ac94cf8c68000767e9660/tests/soft_limiter_tests.cpp#L58

Somehow this debug assertion flag is letting the vector's assertion trump the Google test wrapper's ability to handle the assertion failure (which we expect).

**Comment by LowLevelMahn** [comment]
the _GLIBCXX_SANITIZE_VECTOR define is also very interesting - activates ASan for std::vector capacity etc.
https://gcc.gnu.org/onlinedocs/libstdc++/manual/using_macros.html

**Comment by kcgen** [comment]
@oturpe , thanks for this report.  If you can help get to the bottom of this - any help would be much appreciated!

We absolutely want to drive the code-base toward being able to build and run clean amidst additional checking libraries like you've suggested here, or Microsoft's checked-STL library, as @LowLevelMahn mentioned here: https://github.com/dosbox-staging/dosbox-staging/issues/1023).

**Comment by oturpe** [comment]
@kcgen @LowLevelMahn thank you for the quick responses, I really appreciate that!

@kcgen's research put on the right path. This is actually caused by combination of `GLIBCXX_ASSERTIONS`, `buildtype=plain` and `EXPECT_DEBUG_DEATH`. Note the word _DEBUG_ in the last one, and indeed from [gtest documentation](https://google.github.io/googletest/reference/assertions.html#EXPECT_DEBUG_DEATH):

> In debug mode, behaves the same as EXPECT_DEATH. When not in debug mode (i.e. NDEBUG is defined), just executes statement.

Initially, I did not realize the buildtype was important at all when I filed the issue. It just happened to remain in the reproducer that I though was clear enough to report and did not bother to try to minimize further by trying without it. But it is required to reproduce this bug.

I tried some combinations. `GLIBCXX_ASSERTIONS` are on in all of these:
* plain build + `EXPECT_DEBUG_DEATH` → crash. Plain build disables the debug expectation as well as the `assert` macro ([according to C++ reference](https://www.cplusplus.com/reference/cassert/assert/) it is only used for debug builds). `GLIBCXX_ASSERTIONS` remain in force even for non-debug builds and make it crash.
* debug build + `EXPECT_DEBUG_DEATH` → success. `assert` and `EXPECT_DEBUG_DEATH` do their job.
* plain build + `EXPECT_DEATH` → success. `assert` is disabled, but `GLIBCXX_ASSERTIONS` and `EXPECT_DEATH` cause the expected behavior.

The first question to ask is, it is intended that the test suite can be run for a release build as well as a debug build? If not, then Fedora, who does that anyhow, need to disable or patch this test case.

If yes, the I suppose the test case could be conditionalized with `#ifdef` so that it will `EXPECT_DEATH` instead of `EXPECT_DEBUG_DEATH` if the glib assertions are used.

What do you think?
