### ISSUE TITLE
Clang

### ISSUE THREAD

**Issue by Ajaja** [dosbox-staging/dosbox-staging#1088]
Is ```clang``` supported for building ```dosbox-staging```?
I have some audio issues with ```msys2/clang64``` builds of ```dosbox-staging``` but I'm not sure if it's a bug or ```dosbox-staging``` is not supposed to be built with ```clang```.

**Comment by kcgen** [comment]
Yes, Clang should be able to build the code on supported platforms - like Windows 8.1+, modern macOS versions, and modern Linux OSes. 

Release builds on Windows are currently generated by VS2019, however our Config-Heavy CI run uses msys2 (and GCC 10.3) - latest run is here: <https://github.com/dosbox-staging/dosbox-staging/runs/2877050813?check_suite_focus=true>

I'm closing this (as the question is answered).

Feel free to fill in an issue report, which includes providing steps to reproduce the problem. Thanks!
