### ISSUE TITLE
[msys2/clang64] OGG CD-DA tracks audio distortions

### ISSUE THREAD

**Issue by Ajaja** [dosbox-staging/dosbox-staging#1089]
I'm trying to use new ```msys2``` subsystem ```clang64``` and clang v12 compiler to build ```dosbox-staging``` and noticed strong audio distortions while playing OGG CD-DA tracks  ( https://dosbox-staging.github.io/v0-75-0/#cdda ) from games (e.g. , GOG-vesion of Heroes of Might and Magic 2) and with MS-DOS CD-players too.
There is no such problem with ```msys2/mingw64/gcc``` builds with the same versions of libraries and ```dosbox-staging``` (I'm  using the latest git-version of ```dosbox-staging```). 
Maybe there are issues with some ```msys2/clang64``` prebuilt  libraries (libogg/libSDl2/etc.).  I don't know.
Could someone please test playing of OGG CD-DA tracks in clang-compiled ```dosbox-staging``` under other systems (Linux/MacOS/etc.) and [dis]confirm the issue?

**Comment by kcgen** [comment]
Clang is used as the primarily compiler on macOS and folks report no CDDA issues.  I routinely build with clang in release and debug modes on Linux ,and have no issues. 

Can you please share your exact meson commands , game files, and conf settings so we can try to reproduce this? 

Also, I can recommend our discord group. Members of the staging team are successfully running this series, and possibly further improvements you might be interested in.

**Comment by Ajaja** [comment]
I've been using clang-build version of ```dosbox-staging``` under Windows 10 for some time now and didn't have any problems till swiching the music in HMM2 from MIDI to CD. 

The command is:
```
meson setup -Dprefix=$mingw_prefix -Ddefault_library=static -Dtry_static_libs=opusfile,png,sdl2,sdl2_net,fluidsynth -Dbuildtype=release build 
ninja -C build
```
I've uploaded the complete build folder here: https://0x0.st/-9dE.zip

And a small sample is here: https://0x0.st/-9dU.zip   (conf+cue+few *.ogg + CDPLAY.EXE).

**Comment by Ajaja** [comment]
Did some more digging. MP3/FLAC/OPUS/WAV  work fine. Only OGG sounds awful.

**Comment by kcgen** [comment]
Thanks for this very interesting report, @Ajaja.

It seems to be a bug in Clang's -O2 and -O3 optimization levels.

Try add `-Dc_args=-Ofast -Dcpp_args=-Ofast` to your build (just as a proof). 

I was able to isolate the chunk of code it struggles on, and mitigated it with this small change:

Isolated the issue to this: https://github.com/dosbox-staging/dosbox-staging/commit/d2cc06296d2ed1c4de81357a60ba919417e558fc

Can you try branch `kc/clang-vorbis-1`, and see if that give you a working build?

**Comment by kklobe** [comment]
would this be a good excuse to bump to the latest stb_vorbis as well? looks like a few minor fixes from 1.19 to 1.20. https://github.com/nothings/stb/commits/master/stb_vorbis.c

**Comment by Ajaja** [comment]
> Can you try branch `kc/clang-vorbis-1`, and see if that gives you a working build?

It's OK! 
Thank you for fixing it so fast.

**Comment by kcgen** [comment]
> would this be a good excuse to bump to the latest stb_vorbis as well? looks like a few minor fixes from 1.19 to 1.20. https://github.com/nothings/stb/commits/master/stb_vorbis.c


Yup, the bump is in the 3rd commit on this fix branch.
1.20 is still missing many cleanups we've previously fixed (https://github.com/nothings/stb/issues/created_by/kcgen), so could only bring in a couple changes from 1.20; still, better than nothing though!

**Comment by kcgen** [comment]
Clang's optimizer specifically has trouble with the while loop's content inside the `imdct_step3_inner_s_loop_ld654` function.

 This no-inline mitigation introduces a small speedbump that sufficiently disrupts the optimizer.  Another alternative is to set the 'optnone' attribute on the function, but this gets rid of all optimization.. so I felt that was too heavy of a hit. 

I suspect that refactoring the while loop's step-wise array rotation using a temporary array might help the optimizer.  It's certainly some mental gymnastics to follow it!

**Comment by kcgen** [comment]
Ref: https://github.com/nothings/stb/issues/1152

**Comment by kklobe** [comment]
FWIW, not noticing any issues with the small sample on macOS (Apple clang version 12.0.5 (clang-1205.0.22.11))

**Comment by kcgen** [comment]
> FWIW, not noticing any issues with the small sample on macOS (Apple clang version 12.0.5 (clang-1205.0.22.11)), but, this is an M1 (arm64).

Very interesting, @kklobe. Maybe this only affects clang's x86-64 bit routines? I haven't checked on my Pi yet.

**Comment by kklobe** [comment]
> Thanks - updated my comment on the STB issue to note this affects x86-64.

Yeah, I don't have great ears, so here's a capture:

[cdplay_001.wav.zip](https://github.com/dosbox-staging/dosbox-staging/files/6705285/cdplay_001.wav.zip)
