### ISSUE TITLE
Improve "pause on lost focus" behaviour

### ISSUE THREAD

**Issue by dreamer** [dosbox-staging/dosbox-staging#109]
Continuation of discussion from: https://www.vogons.org/viewtopic.php?p=813297#p813297

Basically, dosbox-staging behaviour when losing focus is inconsistent and needs to be improved. In DOSBox 0.74-3 (and SVN) it was impossible to Alt-tab when in-game, so the problem was "hidden" this way (at the cost of usability).

The behaviour right now is different depending on OS, and inconsistent when losing focus, e.g.:

- on Windows 10 emulation is paused when the window loses focus
- on Linux it does not (when in windowed mode)
- on Linux video display is stopped, but emulation runs in the background (when alt-tabbing from fullscreen)

**aaronp** made a very good suggestion in Vogons thread:

> You probably want this behavior to be configurable, because it depends on the game. I know I've seen this as an option in other emulators, so it's pretty standard. If you're playing an action game, you almost certainly want the emulation to pause. If you're playing a more slow-paced strategy or simulation game — SimCity for example — you may want the game to continue running in the background.
>
> Also, you may need the emulator to continue running if you're playing some online game like Warcraft, though I've never experimented with that so I'm not sure.

I agree with this - but (at least according to documentation) there is already a pref for it:

```
[sdl]
priority = normal,pause
```
So, there are two actions for this issue:

1) Test if existing setting works the way it is supposed to in all situations.
2) Perhaps replace it with a different setting, which would be easier to discover, e.g.

```
[dosbox]
lost_focus_pause = never / always / fullscreen_only
```
?

**Comment by BPaden** [comment]
run_in_background might be more familiar to users because it is used in other emulators.

**Comment by johnnovak** [comment]
Can we close this @kcgen now that we have the configurable pause/mute when inactive settings?

**Comment by kcgen** [comment]
> Can we close this @kcgen now that we have the configurable pause/mute when inactive settings?

:+1:
