### ISSUE TITLE
"Unexpected Control Character:" while installing german Monkey Island

### ISSUE THREAD

**Issue by Burrito78** [dosbox-staging/dosbox-staging#1090]
**Describe the bug**
While installing "The secret of Monkey Island" German EGA from floppy disk images, the above error is displayed several times.

The install works in the end, so this is only cosmetic but very distracting.

**To Reproduce**
Run attached INSTALL.BAT

**Expected behaviour**
Don't display error messages because under DOS they aren't shown either.

**Environment (please complete the following information):**
- macOS Big Sur
- Relevant hardware info: Macbook Pro

**Version of dosbox-staging:**
0.77.0-alpha-905-g689b2930

**Configuration parameters:**
fresh config

<img width="670" alt="Bildschirmfoto 2021-06-23 um 23 08 23" src="https://user-images.githubusercontent.com/61995128/123169026-0f6f0f00-d479-11eb-8bf5-bc33e63daf32.png">

[INSTALL.BAT.TXT](https://github.com/dosbox-staging/dosbox-staging/files/6704898/INSTALL.BAT.TXT)

**Comment by kcgen** [comment]
This was a fix from https://github.com/dosbox-staging/dosbox-staging/issues/555

Perhaps we can further exclude possible german characters, but retain the message to help with actually-corrupt batch files.

**Comment by kcgen** [comment]
Potential fix under branch: `kc/debug-log-illegal-chars-1`
@Burrito78 , macOS build underway here: https://github.com/dosbox-staging/dosbox-staging/actions/runs/966326608

**Comment by Burrito78** [comment]
The provided branch fixes this issue. Installer runs through without any weirdness and installed game works. Thanks!
