### ISSUE TITLE
Empty Dosbox window after switching back from fullscreen

### ISSUE THREAD

**Issue by Burrito78** [dosbox-staging/dosbox-staging#1094]
**Describe the bug**
Exiting fullscreen results in an empty Dosbox window.

It looks to me as if the proper output resolution for the command prompt is not switched (window stays in 320x200 size).

![Bildschirmfoto 2021-06-24 um 12 16 43](https://user-images.githubusercontent.com/61995128/123246416-0ff1bf00-d4e6-11eb-88f1-6f3fd74df6ba.png)

**To Reproduce**
1. Start a 320x200 game (Doom, Quake, Monkey Island) in window mode
2. Switch to full screen (Alt+Enter)
3. Exit the game to the command prompt
4. Exit full screen (Alt+Enter)

The error happens with output=opengl (default on macOS) and surface.
Doesn't happen when using texturepp.
Output can be fixed by opening the keyboard mapper!

**Expected behaviour**
An empty dosbox window shouldn't happen while on the command prompt.

**Environment (please complete the following information):**
- OS and version: macOS Big Sur
- Relevant hardware info: Macbook Pro 2014

**Version of dosbox-staging:**
0.77.0-alpha-905-g689b2930

**Configuration parameters:**
fresh config + output=opengl/surface/texturepp

**Comment by kklobe** [comment]
Confirmed on macOS 11.4 with an M1 MacBook Pro. I only use `texture` variants so hadn't see this. I also run a fixed resolution to avoid window size flipping, and that makes it work for me on `opengl`, e.g. `windowresolution = 640x480`, does that help on your config?

**Comment by Burrito78** [comment]
> Confirmed on macOS 11.4 with an M1 MacBook Pro. I only use `texture` variants so hadn't see this. I also run a fixed resolution to avoid window size flipping, and that makes it work for me on `opengl`, e.g. `windowresolution = 640x480`, does that help on your config?

Setting a fixed resolution like 640x480 is a workaround, yes. Tested with 'opengl' of course.

**Comment by kcgen** [comment]
Reported by @GranMinigun during the 0.75 timeframe:
 — 
04/19/2020
It still preserves window size before going fullscreen.
1) While windowed, launch a game (Catacomb 3-D in my case);
2) Go fullscreen;
3) Exit game;
4) Go windowed.
We get perfectly black 320x240 window.
Master branch.
Going back fullscreen gets picture back.
Doesn't depend on windowresolution or glshader. output = opengl.
