### ISSUE TITLE
riscv64 backend for core_dynrec

### ISSUE THREAD

**Issue by iamgreaser** [dosbox-staging/dosbox-staging#1095]
In preparation for the Year Of The RISC-V Desktop (har har), it would be worth having a riscv64 dynrec backend. I have a HiFive Unmatched running Debian Unstable and I want this enough to actually have a go at implementing it myself.

I'm *currently* working on this and making my way through it and probably breaking all the style rules at this point in time so sorry in advance. (And thanks for setting up some clang-format rules, that should make conforming less painful once I have it working.)

It's getting to the point where I might actually be able to get back to the command prompt after typing `core dynamic` and hitting Enter once I find out why I'm overflowing the dynrec cache buffer.

I'll fork this and set up a branch for now so people can have a look, but I'm not comfortable with making a draft PR until at least some things work with it. ( EDIT: Pushed, it's the `gm/riscv64-dynrec` branch on my fork. )

**Comment by kcgen** [comment]
This is exciting stuff, @iamgreaser!

On the topic of exercising the CI workflows, GitHub doesn't have RISC-V hardware yet, but it's possible we can add our own hardware to run CI jobs. We want to one day do this with an Apple M1 too. 

Some notes here: https://docs.github.com/en/actions/hosting-your-own-runners/about-self-hosted-runners

There is a security concern mentioned where all forks can run on the projects CI, but we've already limited CI runs to just members of the Staging team. So this concern is not an issue here.

**Comment by Burrito78** [comment]
@iamgreaser You can continue this anytime, just reopen.
