### ISSUE TITLE
Improvements for packagers

### ISSUE THREAD

**Issue by kcgen** [dosbox-staging/dosbox-staging#1102]
- Write `PACKAGING.md`
 - Automate the generation of the  `metainfo` file to make it easier to generate flatpak releases.

**Comment by Burrito78** [comment]
@kcgen Old ticket is old. Still relevant?

**Comment by kcgen** [comment]
It was something @dreamer was interested in. 

We have some hindsight now: it's been almost two years and four major releases since then, and no packagers have come asking for guidance, so I will err on the side of saying "I don't think it's needed" and tentatively close it.

But if there is still a strong need or want from our side, I suggest re-opening with the 0.81 project set as the target.
