### ISSUE TITLE
Deprecate `texturepp` and `openglpp` in favour of new, user-friendly setting name.

### ISSUE THREAD

**Issue by kcgen** [dosbox-staging/dosbox-staging#1103]

**Comment by kcgen** [comment]
One of the strange things with opengl, openglnb, openglpp is that they mix API type versus scaling method. This means that as the number of APIs grow, the number of options multiplies.

One approach is to disconnect these aspects:

``` ini
output = opengl / texture / metal / vulkan / ...
scaling = rounded / nearest-neighbour / pixel-perfect
```

**Comment by Burrito78** [comment]
Done deal, no need for double tickets.
