### ISSUE TITLE
Introduce tests to explore success/error codes used for file handling.

### ISSUE THREAD

**Issue by kcgen** [dosbox-staging/dosbox-staging#1105]
See #722 for one regression that was caused by lack of such tests.

They can be quite small / easy to write - tiny binary written in NASM or Turbo Pascal, verified on real DOS.

**Comment by Burrito78** [comment]
@kcgen Still in 0.78 release, move to backlog or 0.81 release?

**Comment by kcgen** [comment]
Yes, now have them in the unit tests:
 - Host file-based tests -- https://github.com/dosbox-staging/dosbox-staging/blob/main/tests/fs_utils_tests.cpp
 - DOS file-based tests  https://github.com/dosbox-staging/dosbox-staging/blob/main/tests/dos_files_tests.cpp
 - DOS shell file-based redirection tests - https://github.com/dosbox-staging/dosbox-staging/blob/main/tests/shell_redirection_tests.cpp
