### ISSUE TITLE
Test and consider more shaders for inclusion

### ISSUE THREAD

**Issue by kcgen** [dosbox-staging/dosbox-staging#1106]
- crt-lottes-fast.subtle+gain.glsl
- crt-guest-dr-venom
- crt-guest-sm
- pixel_perfect-scanlines.glsl

**Comment by kcgen** [comment]
## crt-guest-sm

Latest version is `2021-05-20-release1`: https://forums.libretro.com/t/new-crt-shader-from-guest-crt-guest-advanced-updates/25444/1142 , however its format (`.slang and .slangp`) is incompatible with our GLSL format.

The most recent GLSL version of crt-guest-sm I could find is more than a year old: https://github.com/libretro/glsl-shaders/tree/master/crt/shaders/guest

 This is accepted by DOSBox when `output = opengl*`:
``` text
OPENGL: Pixel buffer object extension: available
RENDER: Using GLSL shader 'crt-guest-sm.glsl'
...
```

However the output is black.  This is true at various resolutions up to 4k.

**Comment by kcgen** [comment]
## crt-guest-dr-venom

The most recent GLSL version of crt-guest-dr-venom I could find is more than a year old: https://github.com/libretro/glsl-shaders/blob/master/crt/shaders/guest/crt-guest-dr-venom.glsl

 This is accepted by DOSBox when `output = opengl*`, however it fails to compile:
``` text

Error compiling shader: 0:635(20): error: `brightboost1' undeclared
0:635(9): error: no matching function for call to `mix(float, error, float)'; candidates are:
0:635(9): error:    float mix(float, float, float)
0:635(9): error:    vec2 mix(vec2, vec2, float)
0:635(9): error:    vec3 mix(vec3, vec3, float)
0:635(9): error:    vec4 mix(vec4, vec4, float)
0:635(9): error:    vec2 mix(vec2, vec2, vec2)
0:635(9): error:    vec3 mix(vec3, vec3, vec3)
0:635(9): error:    vec4 mix(vec4, vec4, vec4)

SDL:OPENGL:Failed to compile shader, falling back to default
```

The compiler warns about `brightboost1` being undefined - and indeed, it's not defined. (are these tested before they're posted?).  Defining this allows the code to carry on.

``` text 
OPENGL: Pixel buffer object extension: available
RENDER: Using GLSL shader 'crt-guest-dr-venom.glsl'
```
 
However the output is black.  This is true at various resolutions up to 4k.

**Comment by kcgen** [comment]
## crt-lottes-fast.subtle+gain

4k: 
![2021-05-20_17-42](https://user-images.githubusercontent.com/1557255/119073872-dab3f780-b9a2-11eb-91a4-a410c9b3a2bf.png)

**Comment by kcgen** [comment]
## pixel_perfect-scanlines

4k:
![2021-05-20_17-44](https://user-images.githubusercontent.com/1557255/119073914-ec959a80-b9a2-11eb-86e4-6b468967dd9c.png)

**Comment by dreamer** [comment]
I would love to include more cool shaders out of the box (and we'll probably do it). However…

Every new shader increases technical debt and makes it a bit harder to provide equivalent functionality when implementing OpenGL ES or Vulkan backends. (!!!)

Also, many of GLSL shaders are *extremely* slow - thus unacceptable for inclusion. Every single one needs to be tested on range of hardware before being included OOTB.

**Comment by Burrito78** [comment]
I can't find any high-res photos of real CRTs using VGA 320x200 (time period around 1990-95).
Would it help if i took some high resolution photos to get a reference for setting these shaders up?

**Comment by arrowgent** [comment]
a line doubling (scanline) removal shader

https://www.gog.com/forum/phantasmagoria_series/workaround_for_black_scanlines_in_phantasmagoria_2
https://www.gog.com/forum/d_the_game/line_doubling_shader_for_dosbox
https://imgur.com/a/9TwCD

used way back in daum, a custom build with the shader

would be really cool for games that enforce those horrible scanlines!

```
Copyright (C) 2015 Ove Kaaven

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.
```


some other shaders
https://krystof.io/dosbox-shaders-comparison-for-modern-dos-retro-gaming/


can agree, i dont use filters/shaders.  only a simple normal2x scalar
post processing increases cpu/gpu demand on the systems

**Comment by tyrells** [comment]
Hi everyone. I wanted to add a couple of comments around libretro shader compatibility in DOSBox. Currently, DOSBox only supports a single shader pass, whereas many of the more advanced shaders in libretro use multiple shader passes. To use multi-pass shaders, changes to the DOSBox code would be required. There is also an issue with some shaders requiring texture images (these are loaded in the parameter files using `textures = [texture names]`. An example of this can be seen in https://github.com/libretro/glsl-shaders/blob/master/crt/crt-guest-dr-venom.glslp. This is also not currently supported in DOSBox.

The number of shader passes for a particular shader can be identified in the libretro `.glslp` shader parameter files. There will be a line in each file that says `shaders = [number of shader passes]`. These parameter files also reference the indivudal `.glsl` shaders that are loaded for each pass.

For any single-pass shaders (which don't use textures) that are currently not in https://github.com/tyrells/dosbox-svn-shaders, or are out of date, I am happy to adapt/update them for DOSBox  - this requires some small changes to the uniform variable names and the `gl_Position` calculation. The basic code for this can be seen by comparing the libretro shaders to the dosbox-svn-shaders versions, or by looking at https://github.com/tyrells/dosbox-svn-shaders/blob/master/template.glsl for the basic code.

**Comment by johnnovak** [comment]
For what it's worth, I'm using [crt-caligari](https://github.com/tyrells/dosbox-svn-shaders/blob/master/crt/crt-caligari.glsl) to emulate scalines in 320x200 EGA games, and a tweaked version of [crt-aperture](https://github.com/tyrells/dosbox-svn-shaders/blob/master/crt/crt-aperture.glsl) for subtle scanlines at 640x350 resolution.

By the way, Guest's shaders are a work of art, they are the very best I've seen so far. They all require at least 2x vertical [oversampling](https://github.com/dosbox-staging/dosbox-staging/issues/1533), though. I'm using his tweaked `CRT-A2080-HiRes-SmartRes` shader in WinUAE (it handles different Amiga resolutions and pixel ratios automatically -- very cool for games and demos switching between resolutions, or games that split the screen vertically and use *different* screen modes on the two splits, a very cool feature of the original Amiga chipsets). It would be super nice to bribe him to port his shaders to DOSBox (his WinUAE originals are for DirectX 9/11, by the way).

Download the images and view them at 100% magnification in an image viewer, the browser scaling ruins the effect. Oh, and they're all at 1920x1080.

**crt-caligari**

![loom1](https://user-images.githubusercontent.com/698770/150232849-cbeebd3e-e407-49cf-96ce-5d96f4c60eb7.png)
![loom2](https://user-images.githubusercontent.com/698770/150232857-dd5026b8-c31b-4b14-9892-b29c593a7ef4.png)

**tweaked crt-aperture**

![sc201-1](https://user-images.githubusercontent.com/698770/150232866-e79375a8-3a85-4978-a66a-0a4f4eb79c3f.png)
![sc201-2](https://user-images.githubusercontent.com/698770/150232884-494603a5-10e4-49a6-905b-278f6fbfab54.png)

**Guest's CRT-A2080-HiRes-SmartRes in WinUAE (tweaked to max out the sharpness settings)**

![a2800-sharp](https://user-images.githubusercontent.com/698770/150233332-9b21a987-50ad-4157-bb82-ca661c683c5d.png)

**Comment by Jkapp76** [comment]
I use a simple shader with 386box called (dotmask). I think it looks great but will not work with dosbox.

**Comment by tyrells** [comment]
@Jkapp76 do you have a link to the dotmask shader? If so, I can try and create a version for DOSBox.

**Comment by Jkapp76** [comment]
https://u.pcloud.link/publink/show?code=XZHzzrXZgN4EJRkbtHBQTIeIoDzcoFbFR4p7

Here's a link to all the glsl shaders I use with 86Box. You'll see dotmask in there. crt-hyllian-3d.glsl is another good one.

**Comment by johnnovak** [comment]
For reference, I've found the holy-grail (to my eyes) of (S)VGA CRT emulation:

https://forums.libretro.com/t/new-crt-shader-from-guest-crt-guest-advanced-updates/25444/48

I think it looks spectacular, it has just the right amount of subtle detail. It really requires at least 1440p, though; I tried downscaling the images to 1080p and most of the effect is lost.

It uses a tweaked version of Guest's `crt-guest-advanced-hd` shader (written in slang), available from here:

https://forums.libretro.com/t/new-crt-shader-from-guest-crt-guest-advanced-updates/25444

It would be nice to include a port of this in the future.

**Comment by johnnovak** [comment]
Closing this as I've added Tyrells SVN shaders (the good ones) in this PR; it's part of the 0.80.0 release:
https://github.com/dosbox-staging/dosbox-staging/pull/2137

If things go to plan, we'll get RetroArch shader support as part of the graphics pipeline modernisation work:
https://github.com/dosbox-staging/dosbox-staging/issues/2131
