### ISSUE TITLE
Rename default branch to `main`

### ISSUE THREAD

**Issue by kcgen** [dosbox-staging/dosbox-staging#1108]
Git introduced this ability one year ago, and since then all default branches are `main` on GitHub and GitLab. 

References:
 - https://github.com/github/renaming
 - https://about.gitlab.com/blog/2021/03/10/new-git-default-branch-name/

Many existing projects have already renamed their branches, and GitHub offers zero-risk easy steps to do so.

The only notable work needed on our side is renaming any hardcoded instances of `master`, which should be straight forward to `grep` out.

Through actions and communication, the Staging project will always side with opposing forms of oppression (*isms), and making this change shows where the project stands (no matter how small of a gesture this is). 

Suggest we do this near-term given the start of the 0.78 cycle, instead of waiting another 6+ months.

**Comment by kcgen** [comment]
@dreamer, this looks pretty rote given the instructions out there. Can you think of any unwritten gotcha lurking in Staging?

**Comment by dreamer** [comment]
Yes, scripts importing from SVN to Git. I think we have master branch hardcoded in other scripts as well, but those are easier to change.

Please don't rush with this - branch with "better import script" was not merged into master because of non-trivial changes and missing functionality - switching the name of master branch without resolving those first will cause problems to me.

**Comment by kcgen** [comment]
Thanks @dreamer.

 I'll identify any changes on a branch, including changes to the the better-import-script-branch version of the script with the goal of simply
maintaining 1:1 functionality, without regressions. 

Unless that script relies on locally built-up repos (than your system would still be using master) or there are some other actions/aliases/tools on your side that are also using master - and would cause mix-ups?

Point is, I'd rather this rename just get is back to par to keep this scope minimum (if possible).

**Comment by kcgen** [comment]
On this proposed branch, assuming we don't have to change functionality, I will addresses instances inside DOSBox with the more appropriate `primary` and `secondary` designations.
