### ISSUE TITLE
Disabling controller input

### ISSUE THREAD

**Issue by GranMinigun** [dosbox-staging/dosbox-staging#1111]
A while back I made a proposal to completely disable controller input when `joysticktype` is `none` (#294). Turned out this was a mistake - currently there is no way to map controller inputs to mouse/keyboard without setting the option to anything else.

Proposal: either add an option value `disabled` (or something) to completely disable controller input, and revert the behaviour of `none` value (read controller inputs, thus allowing to map controller buttons to keyboard and mouse, but do not report any joystick device to games); or just revert the behaviour of `none` value.

**Comment by arrowgent** [comment]
oh that was an interesting change
i had my controller mapped in 0.75.1 on raspberry pi for exactly what you say
let me look at my conf and mapper

`joysticktype  = 2axis`


```
jaxis_0_1- "stick_0 axis 1 0" 
jaxis_0_1+ "stick_0 axis 1 1" 
jaxis_0_0- "stick_0 axis 0 0" 
jaxis_0_0+ "stick_0 axis 0 1" 

jaxis_0_2- "key 92" "stick_0 axis 2 0" 
jaxis_0_2+ "key 94" "stick_0 axis 2 1" 
jaxis_0_3- "key 96" "stick_0 axis 3 0" 
jaxis_0_3+ "key 90" "stick_0 axis 3 1" 
```

buttons also setup for things like ESC, SPACE, CTRL, etc.

yep 0.77.0 all inputs and buttons are obsolete... controller does nothing
maybe im misunderstanding what i had setup

**Comment by kcgen** [comment]
> 0.77.0 all inputs and buttons are obsolete... controller does nothing

I was able use 0.76 to create a d-pad-to-arrow-keys and button to enter/ctrl/alt/esc, and then loaded that mapper file in both 0.77 and 0.78-alpha, and all mappings worked as expected (tested in Jazz Jackrabbit). 

Suggest backup your current mapping file, start up 0.78-alpha (if you're building from latest source), and re-do your joystick pad and button maps:

Then: `awk '/stick/ && /key/' mapper.map` to just see your joystick-to-keyboard maps. 

For example, here are mine:

``` text
key_enter "stick_0 button 0" "key 40" 
key_lctrl "stick_0 button 2" "key 224" 
key_lalt "stick_0 button 1" "key 226" 
key_space "stick_0 button 3" "key 44" 
key_kp_8 "stick_0 axis 1 0" "key 96" 
key_kp_4 "stick_0 axis 0 0" "key 92" 
key_kp_6 "stick_0 axis 0 1" "key 94" 
key_kp_2 "stick_0 axis 1 1" "key 90" 
```

**Comment by kcgen** [comment]
Some joysticks have a switch that lets the d-pad emulate an analog-stick vs d-pad.  

In both cases, the d-pad is active, but it changes the event labels.

Here's how the two differ:
``` text
key_kp_8 "stick_0 hat 0 1" "key 96" 
key_kp_4 "stick_0 hat 0 8" "key 92" 
key_kp_6 "stick_0 hat 0 2" "key 94" 
key_kp_2 "stick_0 hat 0 4" "key 90" 
```

versus

``` text
key_kp_8 "stick_0 axis 1 0" "key 96" 
key_kp_4 "stick_0 axis 0 0" "key 92" 
key_kp_6 "stick_0 axis 0 1" "key 94" 
key_kp_2 "stick_0 axis 1 1" "key 90" 
```

In both cases, I mapped the same d-pad to the same keypad numbers.  But the mode on the joystick was switched.  Maybe your Hori has a similar toggle.

**Comment by kcgen** [comment]
@arrowgent , any luck with your joystick map?

**Comment by arrowgent** [comment]
oh, no i havent used it.
my horipad doesnt have any kind of switches feature, its just a regular 2 stick

maybe youre right backup my mapper config and try re-inputting the buttons with 0.77.x or 0.78-alpha
i dont have the alpha compiled

looks like youve been making some progress with this
