### ISSUE TITLE
RealMagic support

### ISSUE THREAD

**Issue by GranMinigun** [dosbox-staging/dosbox-staging#1112]
There are some games in the wild that support - or even require - RealMagic (ReelMagic), e.g. The Lord of the Rings Enhanced CD-ROM MPEG Version (1994). The game just refuses to run when it doesn't detect needed drivers.

@kcgen's idea is to write some sort of a driver wrapper, which would pass the video for decoding to a backend like ffmpeg.

The request is of no big importance: mentioned game differs from its earlier non-MPEG counterpart in video resolution and inclusion of manuals directly in-game; and there are not many games that support the hardware anyway.

![title_000](https://user-images.githubusercontent.com/11149380/124390329-7c4d9900-dd04-11eb-8d43-1e3c24c8a0e9.png)

**Comment by arrowgent** [comment]
ha, didnt realize it was a duplicate.  good deal

**Comment by LowLevelMahn** [comment]
someone forked dosbox SVN and started adding ReelMagic support: https://www.vogons.org/viewtopic.php?f=32&t=86635

**Comment by arrowgent** [comment]
tested dosbox-staging 0.80.1 and can say the current support from dosboxrm for Return to Zork is fantastic
upstreaming any issues should go there:
https://github.com/jrdennisoss/dosboxrm/issues

depending how staging wants to support this as an upstream patch, backporting fixes to DBRM, or staging developers handle issues and fixes.
