### ISSUE TITLE
Shell CPU consumption

### ISSUE THREAD

**Issue by GranMinigun** [dosbox-staging/dosbox-staging#1121]
Currently, DOS prompt uses all the available cycles, thus leading to (almost) full CPU core utilization. This behaviour can be mitigated by using DOSidle program, but from my testing it interferes with other software (like setup/installation utilities) and often break them.

Is there any reason to keep that behaviour? I am aware that on real machines it's the same, but it doesn't look like a "feature" that should be kept.

**Comment by dreamer** [comment]
> Currently, DOS prompt uses all the available cycles, thus leading to (almost) full CPU core utilization.

That's not true? With default setting, right after start, DOSBox utilizes ~15% of a single CPU on my machine. We're a low-level emulator after all…

Please post your .conf file.

**Comment by GranMinigun** [comment]
It depends on a current `cycles` value. Crank it up to `max` - boom, fan starts spinning. Forgot to mention that in the first post. I know that most games do the same and eat up all the cycles, but still.

**Comment by dreamer** [comment]
> Crank it up to max - boom, fan starts spinning

… then don't crank it up to `max` :smile: . Use `auto` with values that you're comfortable with.

For example:

    cycles = auto 5000 max 80%

Will use 5000 cycles on start (including shell) and crank it up to 80% once you'll run the game.

**Comment by kcgen** [comment]
The shell's command prompt is actually a 'running' program, just like any other program in the emulator.  The shell doesn't have special access to the internals of DOSBox (and vice-versa).

Even if we could use some hacks to differentiation when the user is in the shell versus other programs (and then drop the cycle count), we'd also have to know the shell launches other programs and re-instate the cycle settings.

Happy if someone wanted to a deep dive in the shell and execution state, and report back - or trying some hacking.

**Comment by kcgen** [comment]
Comment deleted due to condescending tone toward author.
