### ISSUE TITLE
Help answer Staging-specific conf questions

### ISSUE THREAD

**Issue by kcgen** [dosbox-staging/dosbox-staging#1129]
Some questions (received outside of GitHub):

1. Is  `fullresolution = 0x0` still valid? It typically works better than `desktop`: is this still valid in Staging?

2. Is there any detailed info online regarding staging output modes? I don't know what these texture modes are and how they compare to `opengl`, Are they similar to `openglpp` is the pixel perfect from ECE?

3. As above, same questions for `texture_renderer`, as I'm unfamiliar with it. It has direct3d but this was an output method in Daum.

4. You've eliminated ECE's `glfullvsync`?

5. Is a `scaler` needed or ignored if using `windowresolution=large` ?

6. How can I tell what CM32 rom file version I have so I can select correct for `model=`?

7. `oplrate` and `gusrate` are gone? I assume this means everything except `pcrate` and `tandyrate` is controlled by the mixer `rate` value? 

8. Does the `ver` setting just do the same thing as typing `ver` inside dos?

**Comment by Wengier** [comment]
Try to answer some of the questions..

According to the source code (line 2294 to 2312 of sdlmain.cpp), I think the setting `fullresolution = 0x0` and `fullresolution = desktop` and supposed to be equivalent. Both `sdl.desktop.full.height` and `sdl.desktop.full.width` will become 0 in these cases.

The available output modes are surface, texture, texturenb, texturepp, opengl, openglnb, openglpp. Outputs like `opengl` or `openglpp` should be similar to other DOSBox builds, e.g. `openglpp` for pixel-perfect mode. When set to a texture mode, then the mode specified by "texture_renderer" will be used, such as "direct3d" or "opengl". This is provided by the SDL2 driver.

The `ver` setting generally functions the same as `ver set`. The `ver` command itself shows the DOS version, whereas `ver set` will set a DOS version. With the `ver` setting you can specify a DOS version at start.

**Comment by Python-Exoproject** [comment]
Does that mean output=texturenb with texture_renderer=opengl is the same as just having output=openglnb? :-)

Looking forward to a breakdown of what each texture_renderer mode is and how they might compare to each other, i.e. whats considered the best generic choice (im thinking its still output=openglnb or output=openglpp?)

**Comment by kcgen** [comment]
### Looking forward to a breakdown

Here's Staging's video pipeline:

DOS video mode > SW Scaler > HW Processing `output=` > Host output `texture_renderer=`

1. **DOS video mode**: this is an emulated video mode used by the game. For example, the game might be drawing a 320x200 pixel image of VGA data to the emulated video card, thinking it's running on CRT at 70 Hz.  But really its just writing to a 320x200 memory block in DOSBox.
2. **SW Scaler**: historically, the next step scaled up the image using software routines. Using things like `normal2x` are no longer needed because the next step can do that in hardware.
3.  ** HW Processing**: will use accelerated routines to scale the image to the desired window size.  The `output` setting also lets us fine-tune the type of scaling - be it "soft", nearest-neighbour (`nb`), or pixel-perfect (`pp`).
    If we're processing the image using OpenGL routines (`output = opengl*`) then the configured `glshader = ` will also be applied. 
    If we're processing using SDL's accelerated routines (`output = texture*`), then we forfeit the ability to apply GL shaders, however we still get accelerated scaling by handled by the host in the next step.
4. **Host output**: Finally we have the interface to the host, and deciding what hardware API should be used tohand over the processed image.  This is best left to `auto` to let SDL pick the best choice (be it OpenGLES2 on the Raspberry Pi, Vulkan on macOS, OpenGL on Linux, or Direct3D on Windows).


### Whats considered the best generic choice

If you don't care about glshaders and prefer sharp pixels, the most universally compatible choice is output = texturenb and  texture_renderer = auto.  This works great on every platform. 

If you want shaders, then output = openglnb, texture_renderer = auto.

Switch those from nb to pp, if you want pixel perfect (in both scenarios). 

### Does that mean output=texturenb with texture_renderer=opengl is the same as just having output=opengnb

 - Both images will be scaled to nearest neighbour, so that aspect is the same.

 - `output = opengl` means the DOS output will be processed using OpenGL routines, and the selected `glshader` will be applied.

 - `output = texture` means the DOS output will be processed using SDL's routines, so glshaders won't be applied.

**Comment by kcgen** [comment]
> Is a scaler needed or ignored if using windowresolution=large ?

For standard scaling, set `scaler = none` and let it be done in hardware instead (The only remaining use for `scaler` is for people who still want to use things like 2xsai, super2xsai, supereagle, etc..).

> How can I tell what CM32 rom file version I have so I can select correct for model=?

A console message will describe the version of ROM being used, for example:

```
MT32: Initialized CM-32L/LAPC-I Control v1.02
```

> oplrate and gusrate are gone? I assume this means everything except pcrate and tandyrate is controlled by the mixer rate value?

Correct. Eventually we will get rid of those too; but need to do the work to confirm we can and that there are no audio regressions.

**Comment by kcgen** [comment]
Before we close this out, let's find a way to roll these answers into the project documentation (expand the conf descriptions? more wiki content? add to README?).

**Comment by Wengier** [comment]
I think some conf descriptions may be expanded, such as a short description of output options, whereas more detailed descriptions and/or comparisons of different options will probably go to Wiki (or README).

**Comment by Burrito78** [comment]
@kcgen See, even maintainers are confused about the documentation.

Wiki all the way! Integrate Readme and conf descriptions into the wiki too in the long run, imho.

**Comment by arrowgent** [comment]
the new mt32 and fluidsynth mixer options is great
the output of `mixer /listmidi` is extremely helpful to see what options there are 

> default fluidsynth
```
MIDI: Using SoundFont '/home/catbox/.config/dosbox/soundfonts/FluidR3_GM-SC.sf2'
MIDI: Opened device: fluidsynth
MIXER: FM channel operating at 49716 Hz without resampling
FSYNTH: Peak amplitude reached 100% of max
```

**i can change on the fly inside dosbox**

> config -set "mididevice=mt32"

```
MT32: Initialized CM-32L/LAPC-I Control v1.02 from /home/catbox/.config/dosbox/mt32-roms/
MIXER: MT32 channel operating at 49716 Hz without resampling
MIDI: Opened device: mt32
MT32: Peak amplitude reached 28% of max
MT32: If it should be louder, use: mixer MT32 357
```

play a midi

>config -set "mididevice=fluidsynth"
```
MIXER: FSYNTH channel operating at 49716 Hz without resampling
MIDI: Using SoundFont '/home/catbox/.config/dosbox/soundfonts/FluidR3_GM-SC.sf2'
MIDI: Opened device: fluidsynth
```

play a midi

i would prefer if im explicitly stating a folder or file using the config
`soundfont = /home/catbox/.config/dosbox/soundfonts/x.sf2`
that its not also duplicating my results by reading `/usr/share/sounds/sf2`
too many files here results in excessive scrolling (yes i have a lot of sf2 for testing)


https://github.com/dosbox-staging/dosbox-staging/pull/969
https://github.com/dosbox-staging/dosbox-staging/issues/1003

**Comment by kcgen** [comment]
Excellent point: if an absolute path is provided, then we should not go digging elsewhere as this could silently load a soundfont having the same filename but with different content - and the results would be confusing (a simple error is more help to let the user get their file paths sorted).

**Comment by kcgen** [comment]
FM refers to frequency modulation, which is a catch all for the OPL music synthesizers (opl2, opl3, dual opl2s..).  This is only needed when a game is configured to play music via Adlib or SoundBlaster.

**Comment by kcgen** [comment]
You can also change the MT32 model on the fly, to load a different ROM:

`config -set "mt32 model=mt32_old"`

**Comment by arrowgent** [comment]
yes i did change MT32 models inside dosbox, i only have two rom models for it.

also you notice the output uses double slashes `/usr/share//mt32-rom-data/`
this seems to be an issue, it shouldnt show that and should regex to Error or Fix the output

**Comment by kcgen** [comment]
> you notice the output uses double slashes `/usr/share//mt32-rom-data/` this seems to be an issue

Using one or more slashes between file name or directory components of a file path is legal in all known Windows, all BSDs, all prior *nix systems, and Linux OSes. 

What issue is this causing on your system? 

> should regex or Fix the output

PRs are welcome!

**Comment by nemo93** [comment]
I've added a [FAQ](https://github.com/dosbox-staging/dosbox-staging/wiki/FAQ) entry to the wiki and added some Q/A there.

**Comment by kcgen** [comment]
Thank you @nemo93  - looks great!
(closing)
