### ISSUE TITLE
Let executables take precedence over internal commands

### ISSUE THREAD

**Issue by kcgen** [dosbox-staging/dosbox-staging#1136]
Reported by @SmilingSpectre:

We have interesting problem in hand. Particularly, it's Inspector X game that isn't in eXoDOS yet, but I believe, problem can be more common. Game relies on file HELP.EXE (naturally) to run in-game help. But it calls it as simply HELP, it seems, and it triggers internal DOSBox help command. I imagine that similar problem can arise in some other situations too. Can it be fixed somehow?

**Comment by Wengier** [comment]
I think this issue is similar to LS command, which was fixed earlier by making it external command rather than a shell command. Perhaps the HELP command can be fixed in a similar way.

**Comment by kcgen** [comment]
@Wengier, great memory.  I think we should do this for all of the DOSBox-specific shell commands, in addition to `HELP`.   

This may harm expected functionality for users - for example, if a game provides its own `exit.com` or `imgmount.exe` commands - but care can be taken to run those commands prior-to or after the game's files are mounted (or unmounted).  If a game needs some specific (and clashing) executables to work properly, then so be-it.

**Comment by Wengier** [comment]
@kcgen I think IMGMOUNT command is always an external command that appears on Z drive, so it does not have this issue. As for EXIT command, it is always an internal command in any DOS, so I doubt any DOS program would name itself EXIT.COM (but feel free correct me if I am wrong). Perhaps we can make the DOSBox commands symmetric to those of MS-DOS, then I assume everything will work as expected?

**Comment by Wengier** [comment]
I think @dreamer also suggested this idea sometime earlier. I will try to find it.

**Comment by kcgen** [comment]
Nice digging - this is great it's been wanted for a while. 

> Perhaps we can make any existing commands in DOSBox symmetric to those of MS-DOS, then I assume everything will work as expected?

Sounds perfect.

> https://github.com/dosbox-staging/dosbox-staging/issues/504#issuecomment-720016675

:+1: 

Looks like we're all in agreement!

**Comment by kcgen** [comment]
@Wengier, any help implementing the program stubs, like [PR#711](https://github.com/dosbox-staging/dosbox-staging/pull/711/) would be much appreciated!

**Comment by Wengier** [comment]
@kcgen Definitely! I am working on it at this time, and will send PR shortly.

**Comment by Burrito78** [comment]
Solid solution but maybe help will become obsolete anyway if we merge documentation some day.

**Comment by Wengier** [comment]
@Burrito78 Not really. DOSBox Staging has plans to add internal help information for more DOS commands, so the HELP command will of course stay. External documentation is very useful but cannot completely replace internal help information.

**Comment by Burrito78** [comment]
Oh, i didn't know that. Maybe my wording made it sound a little too radical :). Of course someone without an internet connection should be able to find their way around in Dosbox. At the moment documentation just lives in too many places.

**Comment by arrowgent** [comment]
this takes precedence for something like a TSR loaded for **win3.1**
when you launch "exit to dos" a TSR should be in memory for typing `exit` to return to windows
however when you type exit it closes dosbox


possibly changing some dosbox commands so they arent possibly duplicates of other program commands?

help = help-db, help-dosbox, db-help ?
exit = exitdb, exit-db, exit-dosbox ?

its complicated deciding to change a LONG standing command UI

i can give an example similar command structure
in a linux terminal; ssh into another computer changes that enviornment
typing exit doesnt close the terminal window, it only exits that ssh connection


i also agree having "help" inside dosbox with enough documentation INSIDE the application is more useful than external documents or having to go to a website for commands
although the linux way has both `command -?` , `command --help` and `man` for `man command`
the man shows extended help documentation sometimes more extensive than the -? or -h or --help

thats an idea though,  using command interpreter to suppliment default applications or running applications
`help -dosbox` would open dosbox's help, but just typing `help` would use whatever loaded application's info
same goes for `exit -dosbox`
again, adding complexity to check if `exit` is loaded or not.. might be too difficult to implement

**Comment by Wengier** [comment]
@arrowgent FYI: The EXIT command has exactly the same function everywhere in DOS and Windows, that is, to exit from the current command shell. If it is the first command shell, then typing EXIT will exit the first command shell and close the system (or DOSBox). On the other hand, if it is a secondary command shell, then typing EXIT will only close the current command shell and return the parent environment (Windows when it is active). There is no difference between the actual function of the EXIT command in either case.
