### ISSUE TITLE
[linux-0.77.0] ? Disabled resizable window, only compatible with OpenGL output, & "windowresolution outside of desktop"

### ISSUE THREAD

**Issue by arrowgent** [dosbox-staging/dosbox-staging#1139]
### Linux
https://github.com/dosbox-staging/dosbox-staging/issues/1129

at my first testing of 0.77.0 i was taken by the output forced to 640x480 windowed mode
i am used to my windowed mode taking up a 4:3 ratio of my screen at 1400x1050 (because reasons)
two monitors at 1920x1080, one with 1920x1024 surface area and the other with 1920x1080 area
i pulled out the `config -wcd` to check whats different

nothing (critically) changed, thats good
```
output           = texturenb
texture_renderer = opengl
```

texturenb, opengl.  as it was
so trying some settings like openglpp, openglnb, etc  now its declaring that i cant "scale" the window to my desired height and forces it down to 1280x960 window
or it complains that my second monitor is only 1920x1024, which its not.  thats the main monitor area, not even the area or monitor that it opens onto.

```
MAIN: windowresolution '1400x1050' outside of desktop '1920x1024', using 640x480 instead
MAIN: Sized window to 640x480 with nearest-neighbour scaling and stretched pixels

```

```
MAIN: Disabled resizable window, only compatible with OpenGL output
MAIN: Sized window to 1280x960 with nearest-neighbour scaling and stretched pixels

```

while in openglpp then going full screen its even worse,  the screen is totally wrong
wait so its forcing 640x400 no matter what in fullscreen mode?
where is the right side of the screen?  its missing entirely.  the left is all black border?
full screen means widescreen area inside a 4:3 surface?

```
MAIN: Disabled resizable window, only compatible with OpenGL output
MAIN: Sized window 960x800 with pixel-perfect scaling and stretched pixels
MAIN: Pixel-perfect scaling (2x2): 640x480 (PAR 1.00) -> 1280x960 (PAR 1.00)
SDL: Using driver "opengl" for texture renderer
MAIN: Draw resolution: 640x400, pixel aspect ratio: 1.20
SDL: Using driver "opengl" for texture renderer

```

???

id like my window to be 1400x1050 at all times even if its destroying the pixel aspect!
this is how i have all my dosbox forks setup.
when i put in the config
`fullresolution   = 1440x1080`
`windowresolution = 1400x1050`
thats exactly what i expect the output size to be

must be user error, not understanding the new changes in settings, wrestling with a configuration that doesnt accept my preferences?
this may seem like a lot of ranting and disorganization, im tired, i gave 0.77 no less than 25 minutes of my time to "test" the new release and settings changes..
i know, you want photos.  documentation of my settings compared to the output
_i will do that later_
if that is even relevant

**i love the idea of HW PP aspect and agree its the way forward**
making it so that i cant choose an alternative resolution really made me symlink 0.76.0 and move backwards for now

**Comment by kcgen** [comment]
Sorry @arrowgent ,

Can you try branch: [`kc/dont-adjust-WxH-1`](https://github.com/dosbox-staging/dosbox-staging/tree/kc/dont-adjust-WxH-1)?

The change: when the user asks for an exact window size, then give it to them, even if exceeds the desktop resolution. It now simply mentions this fact:

``` text
MAIN: Requested windowresolution '5000x3000' is larger than the desktop '3840x2133'
MAIN: Sized window to 4000x3000 with nearest-neighbour scaling and stretched pixels
```

Can you also try the canned sizes? (they _will_ always fit within your desktop bounds:

``` ini
windowresolution = small
windowresolution = medium
windowresolution = large
windowresolution = desktop
``

With the various scaling types? (opengl, openglnb, and openglpp?)  Thank you!

**Comment by arrowgent** [comment]
compiling this still only detects the 'main' monitor area, not the area that its expected to open in
*desktop*

```
windowresolution = desktop
output           = openglnb
texture_renderer = auto

```

`MAIN: Sized window to 1366x1024 with nearest-neighbour scaling and stretched pixels
`

its detecting 1920x1024 (left) as the area size. it should detect the full 1920x1080 (right) without top & bottom panel


setting to

```
windowresolution = 1400x1050
output           = openglnb
texture_renderer = auto

```

```
MAIN: Requested windowresolution '1400x1050' is larger than the desktop '1920x1024'
MAIN: Sized window to 1400x1050 with nearest-neighbour scaling and stretched pixels

```

**great that works as expected**

the other issue is openglpp changing monitor resolution

```
windowresolution = desktop <-- setting irrelevant
output           = openglpp
texture_renderer = auto

```

```
MAIN: Sized window to 1280x1000 with pixel-perfect scaling and stretched pixels
OPENGL: Pixel buffer object extension: available
MAIN: Pixel-perfect scaling (2x2): 640x480 (PAR 1.00) -> 1280x960 (PAR 1.00)
##alt+enter fullscreen
MAIN: Draw resolution: 640x400, pixel aspect ratio: 1.20

```

~[.](https://i.imgur.com/s6dTvZC.png) 1280x800? or 640x400?
thats exactly the size of the window,  border on the left, missing area on the right

running Doom the monitor changes resolution again, PP is correct
exiting doom the fullscreen is now showing the full resolution centered correctly

other: opengl

`output = opengl
`

```
MAIN: Requested windowresolution '1400x1050' is larger than the desktop '1920x1024'
MAIN: Sized window to 1400x1050 with stretched pixels
OPENGL: Pixel buffer object extension: available
MAIN: Draw resolution: 640x400, pixel aspect ratio: 1.20
```



**NEXT *the build error***
python3.6 vs python3.8
note most of my system does not work correctly with python3.7, python3.8

> meson setup -Dbuildtype=release build

```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 574, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 892, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 783, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.VersionConflict: (meson 0.53.1 (/usr/local/lib/python3.6/dist-packages), Requirement.parse('meson==0.53.2'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/meson", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3088, in <module>
    @_call_aside
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3072, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3101, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 576, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 589, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 778, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'meson==0.53.2' distribution was not found and is required by the application

```
>sudo update-alternatives --config python3

```
There are 3 choices for the alternative python3 (providing /usr/bin/python3).

  Selection    Path                Priority   Status
------------------------------------------------------------
  0            /usr/bin/python3.6   1         auto mode
* 1            /usr/bin/python3.6   1         manual mode
  2            /usr/bin/python3.7   1         manual mode
  3            /usr/bin/python3.8   1         manual mode

Press <enter> to keep the current choice[*], or type selection number: 3
update-alternatives: using /usr/bin/python3.8 to provide /usr/bin/python3 (python3) in manual mode

```

the fluidsynth failure
yes i have fluidsynth-dev installed

> ninja -C build

```
[204/206] Compiling C++ object 'src/midi/08c63a5@@midi@sta/midi_fluidsynth.cpp.o'.
FAILED: src/midi/08c63a5@@midi@sta/midi_fluidsynth.cpp.o 
ccache c++ -Isrc/midi/08c63a5@@midi@sta -Isrc/midi -I../src/midi -I../include -I. -I../ -Isubprojects/munt-libmt32emu_2_5_0/include -I../subprojects/munt-libmt32emu_2_5_0/include -I/usr/include/SDL2 -fdiagnostics-color=always -DNDEBUG -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wnon-virtual-dtor -std=c++14 -O3 -Weffc++ -fPIC -D_REENTRANT -MD -MQ 'src/midi/08c63a5@@midi@sta/midi_fluidsynth.cpp.o' -MF 'src/midi/08c63a5@@midi@sta/midi_fluidsynth.cpp.o.d' -o 'src/midi/08c63a5@@midi@sta/midi_fluidsynth.cpp.o' -c ../src/midi/midi_fluidsynth.cpp
../src/midi/midi_fluidsynth.cpp: In member function ‘virtual void MidiHandlerFluidsynth::PlayMsg(const uint8_t*)’:
../src/midi/midi_fluidsynth.cpp:365:3: error: ‘fluid_synth_key_pressure’ was not declared in this scope
   fluid_synth_key_pressure(synth.get(), chanID, msg[1], msg[2]);
   ^~~~~~~~~~~~~~~~~~~~~~~~
../src/midi/midi_fluidsynth.cpp:365:3: note: suggested alternative: ‘fluid_synth_channel_pressure’
   fluid_synth_key_pressure(synth.get(), chanID, msg[1], msg[2]);
   ^~~~~~~~~~~~~~~~~~~~~~~~
   fluid_synth_channel_pressure
ninja: build stopped: subcommand failed.
```

>meson --reconfigure -Duse_fluidsynth=false -Dbuildtype=release build

build completed (which is how i did further testing with `dont-adjust-WxH-1.zip` )

**Comment by arrowgent** [comment]
reason for it being 1400x1050
here is a full screenshot of 1920x1080 on the second monitor (right)

![.](https://i.imgur.com/gNMh2wL.png)

title bar, borders, window manager, etc are my preferred choice
(the border isnt really but i cant find the config to make it smaller)
thats a reduction of 30pixels top and bottom

**Comment by kcgen** [comment]
@arrowgent , can you pull the updates on the branch and retry?

Updates:
 - Reports the display-number being used / queried
 - Uses the full desktop bounds instead of the usable bounds (this will give you the full 1080 instead of a bit less, which previous considered taskbar sizes.  This means that `windowresolution = desktop` will cobber your taskbar).
 - Reports when the DOS (source) resolution changed

Here's an example:

```
MAIN: Sized window on desktop 0 to 2016x1512 with stretched pixels
OPENGL: Pixel buffer object extension: available
SDL: Mouse will move seamlessly without being captured.
MEMORY: Base address: 0x6827000
MEMORY: Using 4096 DOS memory pages (16 MiB)
MIXER: Negotiated 2-channel 48000-Hz audio in 1024-frame blocks
MT32: Initialized CM-32L/LAPC-I Control v1.02 from /usr/share//mt32-rom-data/
MIXER: MT32 channel operating at 48000 Hz without resampling
MIDI: Opened device: mt32
MIXER: CMS channel operating at 48000 Hz without resampling
MAPPER: Found one joystick
MAPPER: Initialized Logitech Gamepad F310 with 6 axes, 11 buttons, and 1 hat(s)
MAPPER: Loaded default key bindings
MOUNT: Path '.' found
MAIN: Source resolution changed to 640x400, (PAR 1.20)
SDL: Window has been shown
MAIN: Source resolution changed to 320x200, double-width, double-height, (PAR 1.20)
```

**Comment by arrowgent** [comment]
sure.

```
fullresolution   = 1440x1080
#windowresolution = 1400x1050
windowresolution = desktop
output           = openglnb
texture_renderer = opengl
```

```
MAIN: Sized window on display-1 to 1440x1080 with nearest-neighbour scaling and stretched pixels
OPENGL: Pixel buffer object extension: available
x
MAIN: Source resolution changed to 640x400, (PAR 1.20)
```

looks like it opens correctly,  the bottom of the border is missing, not sure if this is an issue really since thats a window management detail

works with
`windowresolution = 1400x1050`
no issue also.

`MAIN: Sized window on display-1 to 1400x1050 with nearest-neighbour scaling and stretched pixels`


openglpp is where the next issue arrives

```
fullresolution   = 1920x1080
windowresolution = desktop
output           = openglpp
texture_renderer = opengl
```

```
MAIN: Sized window on display-1 to 1280x1000 with pixel-perfect scaling and stretched pixels
OPENGL: Pixel buffer object extension: available
MAIN: Pixel-perfect scaling (2x2): 640x480 (PAR 1.00) -> 1280x960 (PAR 1.00)
x
MAIN: Source resolution changed to 640x400, (PAR 1.20)
```


my monitor Info is reporting 1280x800, via OSD on the monitor physically.
but the screen image is not centered as seen previously 

> ![.](https://camo.githubusercontent.com/f40fbd8515edef31d41107249101d8f4870ae470c7589c2a6db08a48b4700ecf/68747470733a2f2f692e696d6775722e636f6d2f73366454765a432e706e67)

**Comment by kcgen** [comment]
> my monitor Info is reporting 1280x800, via OSD on the monitor physically.

And you're telling SDL2 to set `fullresolution = 1920x1080`? 

What happens with `fullresolution = 0x0` (or with that line commented out).

**Comment by arrowgent** [comment]
ah, setting a resolution in
fullresolution =
is causing that?

> #comment out
works correctly

and `fullresolution = 0x0` works correctly

the screen stays at 1920x1080 and is scaled, centered, and pixel perfect is maintained.

>xrandr

```
DP-1-3 connected 1920x1080+1920+0 (normal left inverted right x axis y axis) 543mm x 302mm
   1920x1080     60.00*+ 143.99   119.98   109.95    99.93    50.00    59.94  
   1680x1050     59.95  
   1600x900      60.00  
   1280x1024     60.02  
   1440x900      59.89  
   1280x800      59.81  
   1280x720      60.00    50.00    59.94  
   1024x768      60.00  
   800x600       60.32  
   720x576       50.00  
   720x480       60.00    59.94  
   640x480       60.00    59.94  
   720x400       70.08  

```

**Comment by arrowgent** [comment]
thanks for all the help KC

i hope WxH is something you consider for the `Main`
https://github.com/dosbox-staging/dosbox-staging/tree/kc/dont-adjust-WxH-1

**Comment by arrowgent** [comment]
something i blatantly overlooked the whole time

`display          = 1`
was set the whole time

and it was working as it should, opening on monitor=1 (the right)

**Comment by kcgen** [comment]
Thanks for report this @arrowgent and helping debug this 👍, we will definitely be moving the results of this to main.  

When you brought up the second monitor, that's what prompted me to adding logging for it; it's definitely a sleeper settings that can slip by amung all the others!

**Comment by arrowgent** [comment]
is 0.78.0-alpha still considering this?
https://github.com/dosbox-staging/dosbox-staging/tree/kc/dont-adjust-WxH-1

i notice it wasnt pushed for 0.77.1 maintenance

**Comment by arrowgent** [comment]
new 0.78.0 works as expected!
