### ISSUE TITLE
[Pi4] pacing strategy edge case

### ISSUE THREAD

**Issue by nemo93** [dosbox-staging/dosbox-staging#1195]
Might be a duplicate of #1167. If that's the case I'll close that one off.

**Describe the bug**
The new pacing strategy does wonder especially on low-end devices like Raspberry Pis. There's a situation though where it doesn't work well and impact emulation: whenever there's a still image or frame to display for several seconds, the pacing will make the sound to stutter or has it heavily deformed. This happens during FMV sequences too.

**To Reproduce**
The easiest way to reproduce is with **Dungeon Keeper**. Get to the map screen/mission briefing. The map zooms out and you'll get a speech detailing your next mission. On Pi4 the zoom in/out is fullspeed. However as soon as the zoom is complete (still image) emulation will slow down to the point the speech is impossible to hear. As soon as you click on something the map zooms in and emulation is back to fullspeed. 

Atlantis, 11th Hour, Colonization - where's there's a lot of FMV and still frames - does suffer from the same behaviour. I could also mention Destruction Derby 2 or Crusader no Remorse as both does have FMV intro sequences which are stuttering but during gameplay emulation is fullspeed.

**Expected behaviour**
Emulation to be "fullspeed" even during FMV sequences or for still image/frame. If there's a way to get at leat a minimum number of cycles during those still images/FMV sequences that would be great. Perhaps there's a way to do that already?

**Environment:**
- Raspbian OS 32bit (Buster)
- Pi4, no overclock, fKMS (fake mode, default), stock kernel

**Version of dosbox-staging:**
version 0.78.0, compiled from master (last commit 85cfebdc879594d3ba224c2c435e156326d2e30e)

**Configuration parameters:**
In the `dosbox-staging.conf` file I've set `vsync = true`. 
```
[sdl]
fullscreen       = true
display          = 0
vsync            = true
vsync_skip       = 7000
fullresolution   = desktop
windowresolution = default
output           = texturenb
texture_renderer = opengles2
capture_mouse    = onstart middlerelease
sensitivity      = 100
raw_mouse_input  = false
waitonerror      = true
priority         = auto,auto
mapperfile       = /home/pi/RetroPie/roms/pc/maps/+mapper.map
screensaver      = auto
```

My **Dunger Keeper** `.conf`:
```
[dosbox]
machine = svga_s3

[cpu]
cycles = 65000

[joystick]
joysticktype  = none

[autoexec]
imgmount d /home/pi/RetroPie/roms/pc/isos/dk/KEEPER.CUE -t cdrom
mount c /home/pi/RetroPie/roms/pc/games
C:
CD DK
KEEPER.EXE
EXIT
```

I haven't noticed anything suspicious in the log.

**Comment by kcgen** [comment]
Thanks for the detailed reports @nemo93 - some questions that will help narrow this down:
 - If you lower cycles to ~30k (leaving everything else as-is), does that change/improve the FMV speed and tlhe slow down / speech dropout in DK?
 - if you disable vsync, does that return behavior the 'normal'?
 - If you adjust vsync_skip upward or downward to ~3k or up to 15k - how does that change?

**Comment by nemo93** [comment]
@kcgen thanks as always. I feel terrible as the solution was simple: `cycles = auto` is the key. I was so used to precisely tuning my cycles count that I forgot about that value. With `auto` no more issue and games are now fullspeed all the time whatever being rendered.

I have to state again the performance improvement is quite impressive, at least on pi4. Thanks.

**Comment by kcgen** [comment]
Im

**Comment by nemo93** [comment]
I was unable to find a satisfactory fixed value. It was either you have smooth gameplay and FMV stuttering or the other way around. Obviously for games without FMV (Quake, Doom, etc) this was a simpler choice to make!

For 3D/demanding titles it is acceptable to set `cycles = 60000` as a middle ground ((ie Dungeon Keeper but with the speech issue aforementioned though FMV+gameplay were smooth). Yet for games with intro FMV those will stutter or play like a slideshow. All other FPS (id and Build engines) were running smooth with that value (the short intro in Duke3D with the nuclear sign "exploding" before main menu was stuttering). With this value Destruction Derby 2 intro FMV was stuttering but smooth gameplay. Descent is ok too.

For 2D games (eg. Crusader No R*) the acceptable value was around 30000 (like before). Setting a higher value made the FMV to stutter like a slideshow and even during gameplay there wer some hiccups (character will freeze while moving for a fraction of a second).

Definitely with the pacing mechanism it is possible to go way above the previous fixed value (30-35000) on pi4 like with your fps-pacing branch. There's just an issue in that case with FMV and/or still frames.

**Comment by nemo93** [comment]
For sake of completeness, there are only 2 games I can't make to properly work: Mad Dog McCree 2 and Tekwar. Both suffer from heavy slow down irrespective of the cycles count. You'll have to play a bit in Mad Dog 2 to get the slow down but it's almost from the beginning. Fixed/auto makes no difference.

Worth noting than Tekwar is working fine just the FMV where W. Shatner tells you some story is like a slideshow (after just a few seconds).

**Comment by kcgen** [comment]
> Mad Dog McCree 2 and Tekwar. 

If vsync = false, does that improve those slowdown events?

Also, we should  set the Pi4's `scaling_governor` to ensure it is running in performance mode:

```
sudo systemctl disable ondemand
sudo apt install linux-tools-raspi

sudo nano /etc/default/cpufrequtils
```
* insert:
```
GOVERNOR="performance"
```

Reboot

`sudo cpupower frequency-info`
* should show that the CPU is running in performance mode, at maxiumum clock speed


Third question, when you have a minute to follow up on the segfaults, those are very important and we'd like to tackle those ASAP.  I've posted a couple steps to perform a debug build in the ticket: 
https://github.com/dosbox-staging/dosbox-staging/issues/1196

**Comment by nemo93** [comment]
`vsync = false` doesn't improve slowdown/slideshow unfortunately. I've tried many combinations, values of the various settings (core, cpu, cycles, etc) without success so far. On Retropie the governor is always set to `performance` (default) whenever an emulator is being run. After the emulation stops governor is automatically sets back to `ondemand`. I do confirm the performance governor is activated when I launch Dosbox Staging via my frontend (via `cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor`).

**Comment by nemo93** [comment]
For Tekwar the issue was related to dos/32 extender. Reverting back to dos4gw lets FMV to play properly. Game is running flawless. I'll open a separate issue for Mad dog 2. Thanks.
