### ISSUE TITLE
Missing frames

### ISSUE THREAD

**Issue by nemo93** [dosbox-staging/dosbox-staging#1197]
Let me know if this is related to either #1167 or #1195 as I don't want to create duplicates.

**Describe the bug**
Some screens/frames are not properly rendered. You either got a black screen or a mess with random characters. This until you press a key or move the mouse.

**To Reproduce**
**BattleChess CD** will always go straight to a black screen (sometimes with random characters). This should have been the main screen. Hitting a key will start a game normally.
**Bioforge** is a bit trickier as more random. You have to press the "i" key in-game to open your log terminal. You should get a black screen from time to time until you move the mouse or press a key.
**Conquest Earth**. Run the game and click again on Play the game. You should have a bunch of logos in FMV and then a screen asking you to insert Disc 2. Yet in that case Staging is not properly refreshing the screen and instead of getting the "insert disc 2" message you either have a black screen or the last frame from the Data Design logo (or a mix of both).
**Cybermage** like Battlechess CD will go straight to black screen.
**Descent 1 & 2** will miss some lines in option/main menu

**Expected behaviour**
Screen to be properly refreshed with the right screen/frame.

**Environment:**
- Raspbian OS 32bit (Buster)
- Pi4, no overclock, fKMS (fake mode, default), stock kernel

**Version of dosbox-staging:**
version 0.78.0, compiled from master (last commit 85cfebdc879594d3ba224c2c435e156326d2e30e)

**Configuration parameters:**
In the `dosbox-staging.conf` file I've set `vsync = true`. 
```
[sdl]
fullscreen       = true
display          = 0
vsync            = true
vsync_skip       = 7000
fullresolution   = desktop
windowresolution = default
output           = texturenb
texture_renderer = opengles2
capture_mouse    = onstart middlerelease
sensitivity      = 100
raw_mouse_input  = false
waitonerror      = true
priority         = auto,auto
mapperfile       = /home/pi/RetroPie/roms/pc/maps/+mapper.map
screensaver      = auto
```

**Comment by kcgen** [comment]
Does disabling vsync or adjusting the vsync_skip value (try a simple range 2000, 4000, 10000, 15000) change or alleviate the problem?

**Comment by nemo93** [comment]
@kcgen apologize for not responding earlier. It's indeed related to the `vsync_skip` value. On a Pi4 definitely the default value (**7000**) is _not appropriate_. I've found an acceptable trade-off to be around **~8500**. With this value there are **still** "missing frames" sometimes but very less often and mostly during setup/install process. Raising this value too high and a "doppler" effect will occur in-game (eg. with 10000 in Alone in the Dark, the in-game action menu will slow-down + audio "glitches" can be heard).

The best way to test different values is clearly with Battlechess CD - to check if the intro screen is being shown. Also good candidate for testing is MK Trilogy as the 4 first screens when launched are still images (logos). When `vsync_skip` is too low some of these logos won't be displayed (black screen instead). Also the speed at which the DOS prompt "blinks" is a good indication of what's going on (with lower value the prompt will not exactly blink - hard to describe though).

I'm unable to test on a Pi3 but I suspect 7000 would produce those "missing frames" as well. 

Note: I'll have to provide a fixed `vsync_skip` value for Retropie default config file + ensure `vsync = true`.

**Comment by kklobe** [comment]
@nemo93 how does it work with `vsync = false`? The vsync options were a fairly dirty hack to work around a forced vsync state that happened on my MacBook with an external monitor connected over HDMI which made certain apps unusable. The logic to prevent that specific issue is controlled by `vsync_skip`, and it's somewhat separate from `vsync`, which I decided to just add quickly as an experiment. I would be interested to see your results with `vsync = false`, and see then how the various `vsync_skip` values affect the "missing frames".

**Comment by nemo93** [comment]
@kklobe as far as I can tell Staging is unusable on Pi4 with `vsync = false`. Irrespective of the `vsync_skip` value. Tearing will be too important + performance takes a nosedive. I'll do some further testing to be sure and report back.

This "dirty hack" is definitely nice for Raspberry Pi users 😄

**Comment by kcgen** [comment]
@nemo93 , curious if you can try a fresh pull and build of `kc/4mb-video-memory-1`. 

Try it with vsync = false, but with a new setting (in the SDL section):

```ini
[sdl]
refresh_rate = host
```

This says "use the host's current refresh rate".  
Other options are `dos`,which uses the refresh rate prescribed by the DOS video mode, and setting an exact value, such as: `59.987`, `60`, etc.

I'm specifically curious if any of these offer any change on your Pi (especially when vsync is off), because I understand the problem on the Pi4 is that the video subsystem jams up when it's fed more video frames than anticipated, which is typically true in our case:  DOS is (usually) a 70 Hz source feeding a 60 Hz video pipeline.

If any of these three show any promise, then we'll keep it.  But if all of them are useless, then I will scrap the refresh_rate feature.

**Comment by nemo93** [comment]
@kcgen sure thing. I'm just a bit short on time lately! I gave your branch a try with the recommended setting. For clarity here's what I got in my "default" conf file:

```ini
[sdl]
fullscreen       = true
display          = 0
fullresolution   = desktop
windowresolution = default
refresh_rate     = host   <====
vsync            = false  <====
vsync_skip       = 9000
output           = texturenb
texture_renderer = opengles2
capture_mouse    = onstart middlerelease
sensitivity      = 100
raw_mouse_input  = false
waitonerror      = true
priority         = auto,auto
mapperfile       = /home/pi/RetroPie/roms/pc/maps/+mapper.map
screensaver      = auto

[dosbox]
language          = 
machine           = svga_s3
captures          = capture
memsize           = 16
vmemsize          = 4
vesa_modes        = compatible <====
startup_verbosity = quiet
```

Note: by default the `vmemsize` was set to `0`. Was this expected? 

Anyhow I had only time to test with a handful of games so far mostly Build engine. The outcome is not positive: heavy tearing and still plenty of "missing" frames. With the above situation is worse than with `vsync = true`.

**Comment by nemo93** [comment]
Unfortunately I couldn't find a good setting for `refresh_rate`. It works poorly than with `vsync = true`. True that `dos` or user-specified value (50, 59.987, 60, 70 or 80) work better than with `host` yet still far from perfect (again compared to `vsync = true`).

For the record, log when `refresh_rate = host`:
2021-09-13 10:33:05.771 | CONF: Using a refresh rate of 60.0 Hz

**Rayman** is of great help here as the display issue will happen right from the start (eg. during loading there's UBI Soft blinking in yellow should everything be fine and if gameplay is not fluid). Worth noting than if I pick `50` (as frequency) in the in-game menu the screen will then be stretched a bit. Not the case with `MAX` or `60` values.

**Comment by nemo93** [comment]
The S3 patch is now merged in and offer great result. The `refresh_rate` parameter has been dropped. On Pi4 as of typing best performance with almost no tearing nor "missing" frames can be obtained with:
 
```
[sdl]
vsync        = true
vsync_skip = 9000
```

**Comment by kcgen** [comment]
Thanks for all your testing of the S3 patch on the Pi @nemo93 !
This is great news if the missing frames issue is solved too?

**Comment by nemo93** [comment]
@kcgen least I can do given the impressive work you've done for implementing such patch. I'm still fine-tuning the values but unfortunately the "missing" frames are still there. It's not that critical and with my current setting not that frequent hence my decision to close this ticket. Feel free to reopen and this time I won't close it unless you ask me to.

I got a new variation though: as I'm testing Theme Park lately, the (nice) Bullfrog's logo after the FMV intro sometimes is cut in half until I press a key (half black screen half logo).

**Comment by kcgen** [comment]
Maybe we can include a note about this in the vsync setting? 

_"Note: Enabling vsync can improve frame-rates but may also cause some frames to be not be fully shown. You can try adjusting the skip timing to reduce its occurance."_

**Comment by kcgen** [comment]
>  given the impressive work you've done for implementing such patch

vsync is @kklobe's excellent work :rocket:

**Comment by nemo93** [comment]
> Maybe we can include a note about this in the vsync setting?
> 
> _"Note: Enabling vsync can improve frame-rate but may also cause some frames to be not fully shown. Try adjusting the skip timing via vsync_skip to reduce this occurrence."_

=> that'd be great please.

Oh I was refering to the S3 patch you just merged in a couple of days ago (fixing flickering etc). Either way for sure I'm truly thankful to @kklobe for all the work done and for keeping the RPi community happy!
