### ISSUE TITLE
Graceful way to disable GM in case of crash?

### ISSUE THREAD

**Issue by nemo93** [dosbox-staging/dosbox-staging#1204]
I've found two games (**Privateer 2** and **Shellshock**) which crash hard during intro/FMV. With Privateer 2 even Ctrl+F9 is useless. Only "kill -9" will allow to exit Staging. There's a third game with similar behaviour (Hi-Octane) but there's a [patch](https://github.com/dosbox-staging/dosbox-staging/wiki/Games-issues#hi-octane) which fixes it.

The reason of such crashes is due to General MIDI being selected as music card in the setup. Picking a Sound Blaster (ie. SB16) will prevent any freeze. The "funny" thing is those games allow you to pick up such MIDI card during setup without complaining. In case of Privateer 2 you can even test and hear music!

I'm not sure if this is a bug in the games themselves or some incompatibility with Dosbox/Staging. I wonder if there would be a graceful way to automatically disable GM (or to fallback to SB16) in such case? Assuming it's possible to detect a crash... Objective here would be to simply avoid freezing Staging.

It's a tricky ask and I understand there might be no way to detect a crash but those 2 games are crashing exactly at the same spot on every run. I don't see anything in the log. It's not related specifically to Staging as other people report the same issue with SVN ([here](https://www.wcnews.com/techsupport.shtml#p2) or [here](https://www.vogons.org/viewtopic.php?t=38222)).

To reproduce:
**Privateer 2** (with or without the 17.0e (Buffalo Wings) patch): will crash at the very beginning of the game intro where you could see Privateer 2 logo spinning. Pressing "ESC" will freeze the game instantly.
**Shellshock**: will crash right after the first logo. There might be some "dump" on screen before Staging exits but can't read as it's too fast.

Note: feel free to close that ticket off if it's too unrealistic. In the meantime I'll create an entry in the wiki. Also I was unsure about the ticket title...

**Comment by exoscoriae** [comment]
This issue was solved over at vogons. 

The problem is the length of the mpu401 driver. The patch for hi-octane simply pads the driver with zeros to make it the same length as the fm driver.

This same fix works for privateer 2.

I don't deserve any credit for this. I'm just passing along the fix I received from them.

**Comment by nemo93** [comment]
@exoscoriae thanks for that. I'll give it a try then and update the wiki accordingly. For sure the patch for Hi Octane does fix the issue hopefully it will be the same for Privateer2 and Shellshock. Definitely it's a software bug and nothing to do with Staging. I'll close that ticket off soon.

**Comment by nemo93** [comment]
Confirmed for Privateer2: using the updated midi driver fixes definitely the issue. For Shellshock issue was (again) related to dos/32 extender. Switching back to dos4gw prevented the game from crashing.

Thanks @exoscoriae for pointing me to the right direction.
