### ISSUE TITLE
[Mad Dog 2] choppy FMVs

### ISSUE THREAD

**Issue by nemo93** [dosbox-staging/dosbox-staging#1208]
I'm still having issue with **Mad Dog Mc Cree 2**. I did try various settings and parameters (cycles, memory, video card, soundcard, etc). The game is now patched to version 2.0 and still the FMVs after a couple of seconds will become choppy to the point it's a slideshow. Note that after a while playback is back to normal but not for long before choppiness hits back. There's no DOS/32A extender here.

Has anyone successfully got that game to properly work?

I've noticed something weird in the log though. A (really) massive amount of the following lines is present:
```
SB16: Speaker-output has been toggled on
SB16: Speaker-output has been toggled off
SB16: DSP was reset
```

Check [there](https://pastebin.com/WVQeY1An) for the full log.

**Environment:**
- Raspbian OS 32bit (Buster)
- Pi4, no overclock, fKMS (fake mode, default), stock kernel

**Configuration parameters:**
In the `dosbox-staging.conf` file I've set `vsync = true`. 
```
[sdl]
fullscreen       = true
display          = 0
vsync            = true
vsync_skip       = 7000
fullresolution   = desktop
windowresolution = default
output           = texturenb
texture_renderer = opengles2
capture_mouse    = onstart middlerelease
sensitivity      = 100
raw_mouse_input  = false
waitonerror      = true
priority         = auto,auto
mapperfile       = 
screensaver      = auto

[dosbox]
machine           = vesa_nolfb

[cpu]
core      = dynamic
cputype   = auto
cycles    = auto

[midi]
mididevice = none
midiconfig = 
mpu401     = none

[sblaster]
sbtype  = sb16
sbbase  = 220
irq     = 7
dma     = 1
hdma    = 5
sbmixer = true
oplmode = auto
oplemu  = default

[gus]
gus      = false

[joystick]
joysticktype  = none

[dos]
xms            = true
ems            = false
umb            = true
ver            = 5.0
```

**Mad Dog 2** .conf :
```
[cpu]
cycles = 5000

[autoexec]
imgmount d /home/pi/roms/pc/isos/maddog2/maddog2.iso -t cdrom
mount c /home/pi/roms/pc/games
C:
CD MADDOG2
CALL MADDOG2.BAT
EXIT
```

**Comment by kcgen** [comment]
Looking back at my notes on discord from December, setting cycles to 8000 and configuring the game to use sbpro1 produced acceptable performance and prevented a crash at some point in the game. 
 
After changing your sound card, confrim that this content exists in the tail end your Mad Dog II CFG:
``` 
U
D:MADDOG2D.LIB
D:MADDOG2.SCN

MOUSE
A220 I7 D1 T2
D:
```

Curious if that does the trick!

**Comment by nemo93** [comment]
Confirmed it's now fully working (even with 1.0 release of the game) with the aforementioned settings. Thanks @kcgen!

My `MADDOG2.CFG`:
```
U
D:MADDOG2D.LIB
c:\maddog2\MADDOG2.SCN

MOUSE
A220 I7 D1 T6
c:\maddog2\
```
