### ISSUE TITLE
[Down in the Dumps] installer crashes

### ISSUE THREAD

**Issue by nemo93** [dosbox-staging/dosbox-staging#1209]
It's actually impossible to install that game provided there's a divide-by-zero error (thrown by DOS4GW). I've just found out [the reason](https://www.vogons.org/viewtopic.php?p=160371#p160371) and it's quite interesting.

In short, this is due to the installer trying to guess the CD drive speed. Given I'm using an iso image it's way faster than expected hence the crash.

Is there a way to mitigate that issue without having to rely on some TSR as explained on the forum? Like having a `C:\>SET CDSPEED` command for instance?

Note: the game will run just fine straight from the CD but you won't be able to save progress...

**Comment by nemo93** [comment]
FYI there's another game I'm aware of with such CD check: **Fade To Black**. Yet it's possible to bypass the check by passing the `-2` parameter to the game executable. [[reference](https://www.vogons.org/viewtopic.php?t=17847)]

**Comment by kcgen** [comment]
This is one of those judgment calls - we could inject emulated (ticks) and actual (pause) delays until the installer measures a time that sums to a value greater than zero - and no longer divides by zero.

No doubt hardware at the time of the game's release behaved this way: however, at some point CDROMs and/or Windows 95/XP virtual CD drives sped up to a similar point to where we are today: the installer's time measurements round or truncate to zero (for example, if the game is measuring milliseconds).

Changing the passage of time is an area in DOSBox that has wide-reaching impact. What we do know is that emulated CDROM timing works good in-game: and in this case ripsaw's provided a perfectly good work-around to pacify an installer - which is the best of both worlds: eliminates all of the risk of making timing adjustments in DOSBox while keeping the game happy.

If ripsaw saw an clear solution on the DOSBox side - he would have taken it, so this is certainly the safe and robust path to take.

Thanks for adding this issue - surely it will pop up in google searches along w/ the existin vogons link - and hopefully anyone else can benefit from ripsaw's solution!
