### ISSUE TITLE
[Instant launch] quiet verbosity still shows stdout

### ISSUE THREAD

**Issue by nemo93** [dosbox-staging/dosbox-staging#1213]
I realize that Staging still **shows pre-executable stdout** when configured with `startup_verbosity = quiet`. Is this expected on Raspberry platform? 

I'm not talking `.BAT` (batch) execution here. This occurs for `.EXE` file specified in the `[autoexec]` section. Examples: Alone in the Dark (INDARK.EXE), Crusader no Remorse (CRUSADER.EXE), Destruction Derby (DD.EXE),  Duke1 (dn1.exe), etc.

**Expected behaviour**
No stdout at all when `startup_verbosity = quiet` is set (boot straight in game) as explained [here](https://github.com/dosbox-staging/dosbox-staging/wiki/Instant-Launch#usage).

**Environment:**
- Raspbian OS 32bit (Buster)
- Pi4, no overclock, fKMS (fake mode, default), stock kernel

**Configuration parameters:**
In the `dosbox-staging.conf` file I've set `vsync = true`. 
```
[sdl]
fullscreen       = true
display          = 0
vsync            = true
vsync_skip       = 7000
fullresolution   = desktop
windowresolution = default
output           = texturenb
texture_renderer = opengles2
capture_mouse    = onstart middlerelease
sensitivity      = 100
raw_mouse_input  = false
waitonerror      = true
priority         = auto,auto
mapperfile       = /home/pi/RetroPie/roms/pc/maps/+mapper.map
screensaver      = auto
```

**Comment by kcgen** [comment]
Good question @nemo93 ; you're right - the quieting takes place for all of DOSBox's own messages it normally writes into the shell during startup.

When the launch process cuts over to the program being launched (ie: .exe/.com/.bat), be it via `[autoexec]`, commandline line launch: `dosbox mygame.exe`, or manual shell launch: `C:> mygame.exe`, then that output is not silenced. 

I originally planned for `quiet` to silence _all_ the startup console output - even from programs (like putting `> NUL` behind every command), however I was unable to differentiate the startup phase from run phase. For example, if a batch file enters a choice.com menu, then sending the batch file to > NUL hid the choice menu. I should also say that quiet is pretty "strong" in that the prompt itself `C:\>` is also hidden during the block phase.  So overall, this approach felt like it went too far. 

On the flip side, my own goal for 100% blocked console output was to skip the initial text-mode video change, and instead have DOSBox go straight into the game's video mode.  Startup in these cases is basically instant, and very pleasing. Perhaps we do need a console-less launch line to achieve this?

**Comment by nemo93** [comment]
It was just me worrying about missing something, no worries. The current `quiet` mode is working very nicely. It saved me quite a lot of time already during extensive testing session. I'd say don't waste time with it. 

Closing ticket off. Thanks!
