### ISSUE TITLE
soft-limiter unit-test failure on i586 and armv7l openSUSE Tumbleweed

### ISSUE THREAD

**Issue by IlyaIndigo** [dosbox-staging/dosbox-staging#1230]
After switching to messon and running tests on 64-bit architectures, 1 non-critical test does not pass, the test log can be obtained.
But on 32-bit architectures, critical tests do not pass and, unfortunately, it is impossible to get a complete full test log, the script ends immediately after the tests, preventing the log from being output.

Can you see what's the matter?

package: https://build.opensuse.org/package/show/Emulators/dosbox
spec-file: https://build.opensuse.org/package/view_file/Emulators/dosbox/dosbox.spec?expand=1

**Comment by kcgen** [comment]
Thanks @IlyaIndigo , 

Regarding the non-critical failure, it's actually an expected failure to "check-the-checker", ie: we're causing a test to fail and checking that the GoogleTest suite marks it as a failure. 

The name of unit test is called `ExampleFailingTest`:
``` text
[  106s] [ RUN      ] DriveIndexTest.ExampleFailingTest
[  106s] ../tests/example_tests.cpp:105: Failure
[  106s] Expected equality of these values:
[  106s]   42
[  106s]   drive_index('C')
[  106s]     Which is: '\x2' (2)
[  106s] [  FAILED  ] DriveIndexTest.ExampleFailingTest (0 ms)
...
```

In the summary, we expect a single failure which indeed was met, so the overall test passes:

``` text
[  105s] ninja: no work to do.
[  105s] 1/7 gtest example      EXPECTEDFAIL    0.01s   exit status 1
[  105s] 2/7 gtest fs_utils     OK              0.01s
[  105s] 3/7 gtest soft_limiter OK              0.04s
[  105s] 4/7 gtest string_utils OK              0.03s
[  105s] 5/7 gtest setup        OK              0.02s
[  105s] 6/7 gtest support      OK              0.01s
[  106s] 7/7 gtest rwqueue      OK              0.50s
[  106s] 
[  106s] 
[  106s] Ok:                 6   
[  106s] Expected Fail:      1   
[  106s] Fail:               0   
[  106s] Unexpected Pass:    0   
[  106s] Skipped:            0   
[  106s] Timeout:            0   
```

If this expected-failure actually passed, then we would have and `Unexpected Pass: 1` and that would cause the overall result to fail.

Regarding the soft-limiter unit-test failure on i586, it has also been reported to fail on VS2019 running a checked-version of the STL library.

My guess is that openSUSE's i586 C/C++ libraries are compiled with additional diagnostic/checked-STL features that aren't enabled on x86-64.

The soft-limiter performs sequential iterator comparisons where the last compared iterator is outside the given container's limits: however, it's only a comparison and is never actually used. Unfortunately, even the comparison is enough to cause these checking-STL versions to fail.

Unfortunately I cannot reproduce it on my system using the same flags and meson setup:

[meson-test-error-on-i586-linux-openSUSE-Tumbleweed.html.gz](https://github.com/dosbox-staging/dosbox-staging/files/7072709/meson-test-error-on-i586-linux-openSUSE-Tumbleweed.html.gz)

For even stricter testing, you can turn on UBSAN and ASAN instrumentation with these flags:

``` shell
CFLAGS="-fomit-frame-pointer -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -Werror=return-type -g"
export CFLAGS
CXXFLAGS="-fomit-frame-pointer -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -Werror=return-type -g"
export CXXFLAGS
meson setup -Dbuildtype=debug -Db_sanitize=address,undefined -Doptimization=0 -Db_lundef=false -Dc_args=-fsanitize-recover=all -Dcpp_args=-fsanitize-recover=all build/asan-ubsan
meson compile -C build/asan-ubsan/ --verbose
build/asan-ubsan/tests/soft_limiter
```

And you will see the test passes - meaning invalid or illegal addresses are not used.

I do plan to refactor the soft-limiter one day and try to make it compatible with these checked STLs, however I'm not sure when, as it's not a trivial bit of code.

In the meantime, maybe you can disable the specific unit test on the i586 build? (know that you're exercising the code on the x86-64 system anyway?).

**Comment by IlyaIndigo** [comment]
> If this expected-failure actually passed, then we would have and `Unexpected Pass: 1` and that would cause the overall result to fail.
> Regarding the soft-limiter unit-test failure on i586, it has also been reported to fail on VS2019 running a checked-version of the STL library.

Thank you, I'm understand.

 > In the meantime, maybe you can disable the specific unit test on the i586 build?
 
How to do it?
I am specifying% meson_test --no-suite soft_limiter (/ usr / bin / meson test -C x86_64-suse-linux --num-processes 4 --print-errorlogs --no-suite soft_limiter)
But the test is not skipped.

**Comment by IlyaIndigo** [comment]
> meson setup -Dbuildtype=debug -Db_sanitize=address,undefined -Doptimization=0 -Db_lundef=false -Dc_args=-fsanitize-recover=all -Dcpp_args=-fsanitize-recover=all build/asan-ubsan
> meson compile -C build/asan-ubsan/ --verbose
> build/asan-ubsan/tests/soft_limiter

[  129s] 5/7 gtest soft_limiter FAIL            0.02s   killed by signal 6 SIGABRT
[  129s] >>> /home/abuild/rpmbuild/BUILD/dosbox-staging-0.77.1/i586-suse-linux/tests/soft_limiter
[  129s] ――――――――――――――――――――――――――――――――――――― ✀  ―――――――――――――――――――――――――――――――――――――
[  129s] stdout:
[  129s] Running main() from /home/abuild/rpmbuild/BUILD/googletest-release-1.10.0/googletest/src/gtest_main.cc
[  129s] [==========] Running 18 tests from 1 test suite.
[  129s] [----------] Global test environment set-up.
[  129s] [----------] 18 tests from SoftLimiter
[  129s] [ RUN      ] SoftLimiter.InboundsProcessAllFrames
[  129s] [       OK ] SoftLimiter.InboundsProcessAllFrames (0 ms)
[  129s] [ RUN      ] SoftLimiter.InboundsProcessPartialFrames
[  129s] [       OK ] SoftLimiter.InboundsProcessPartialFrames (0 ms)
[  129s] [ RUN      ] SoftLimiter.InboundsProcessTooManyFrames
[  129s] [       OK ] SoftLimiter.InboundsProcessTooManyFrames (0 ms)
[  129s] [ RUN      ] SoftLimiter.OutOfBoundsLeftChannel
[  129s] stderr:
[  129s] free(): invalid pointer

**Comment by kcgen** [comment]
Can you try the UBSAN and ASAN build on x86-64? I should have clarified that it will/should pass on there.

(We already know that the unit test's fail on openSUSE's i586 libs without the extra checks that UBSAN and ASAN add).

Regarding excluding the test, unfortunately GTest can only exclude at the 'suite' level and not the individual test level. 

One option we have is to outright disable the soft-limiters unit tests - however, I'm reluctant to do that because they still work (and provide value) on the vast majority of systems.  

For now, I would suggest manually snipping them out of your i586 buildbot prior to building:

``` shell
sed -i 's/.*soft_limit.*//' tests/meson.build
```

**Comment by IlyaIndigo** [comment]
> Can you try the UBSAN and ASAN build on x86-64? I should have clarified that it will/should pass on there.

```
[  346s] + build/asan-ubsan/tests/soft_limiter
[  346s] Running main() from /home/abuild/rpmbuild/BUILD/googletest-release-1.10.0/googletest/src/gtest_main.cc
[  346s] [==========] Running 18 tests from 1 test suite.
[  346s] [----------] Global test environment set-up.
[  346s] [----------] 18 tests from SoftLimiter
[  346s] [ RUN      ] SoftLimiter.InboundsProcessAllFrames
[  346s] [       OK ] SoftLimiter.InboundsProcessAllFrames (0 ms)
[  346s] [ RUN      ] SoftLimiter.InboundsProcessPartialFrames
[  346s] [       OK ] SoftLimiter.InboundsProcessPartialFrames (0 ms)
[  346s] [ RUN      ] SoftLimiter.InboundsProcessTooManyFrames
[  346s] [       OK ] SoftLimiter.InboundsProcessTooManyFrames (5 ms)
[  346s] [ RUN      ] SoftLimiter.OutOfBoundsLeftChannel
[  346s] [       OK ] SoftLimiter.OutOfBoundsLeftChannel (0 ms)
[  346s] [ RUN      ] SoftLimiter.OutOfBoundsRightChannel
[  346s] [       OK ] SoftLimiter.OutOfBoundsRightChannel (0 ms)
[  346s] [ RUN      ] SoftLimiter.OutboundsBothChannelsPositive
[  346s] [       OK ] SoftLimiter.OutboundsBothChannelsPositive (0 ms)
[  346s] [ RUN      ] SoftLimiter.OutboundsBothChannelsNegative
[  346s] [       OK ] SoftLimiter.OutboundsBothChannelsNegative (1 ms)
[  346s] [ RUN      ] SoftLimiter.OutboundsBothChannelsMixed
[  346s] [       OK ] SoftLimiter.OutboundsBothChannelsMixed (0 ms)
[  346s] [ RUN      ] SoftLimiter.OutboundsBigOneReleaseStep
[  346s] [       OK ] SoftLimiter.OutboundsBigOneReleaseStep (0 ms)
[  346s] [ RUN      ] SoftLimiter.OutboundsBig600ReleaseSteps
[  346s] [       OK ] SoftLimiter.OutboundsBig600ReleaseSteps (1 ms)
[  346s] [ RUN      ] SoftLimiter.OutboundsSmallTwoReleaseSteps
[  346s] [       OK ] SoftLimiter.OutboundsSmallTwoReleaseSteps (0 ms)
[  346s] [ RUN      ] SoftLimiter.OutboundsSmallTenReleaseSteps
[  346s] [       OK ] SoftLimiter.OutboundsSmallTenReleaseSteps (1 ms)
[  346s] [ RUN      ] SoftLimiter.OutboundsPolyJoinPositive
[  346s] [       OK ] SoftLimiter.OutboundsPolyJoinPositive (0 ms)
[  346s] [ RUN      ] SoftLimiter.OutboundsPolyJoinNegative
[  346s] [       OK ] SoftLimiter.OutboundsPolyJoinNegative (0 ms)
[  346s] [ RUN      ] SoftLimiter.OutboundsJoinWithZeroCross
[  346s] [       OK ] SoftLimiter.OutboundsJoinWithZeroCross (0 ms)
[  346s] [ RUN      ] SoftLimiter.ScaleAttenuate
[  346s] [       OK ] SoftLimiter.ScaleAttenuate (0 ms)
[  346s] [ RUN      ] SoftLimiter.ScaleAmplify
[  346s] [       OK ] SoftLimiter.ScaleAmplify (0 ms)
[  346s] [ RUN      ] SoftLimiter.RangeMultiply
[  346s] [       OK ] SoftLimiter.RangeMultiply (0 ms)
[  346s] [----------] 18 tests from SoftLimiter (9 ms total)
[  346s] 
[  346s] [----------] Global test environment tear-down
[  346s] [==========] 18 tests from 1 test suite ran. (9 ms total)
[  346s] [  PASSED  ] 18 tests.
```

**Comment by IlyaIndigo** [comment]
> ```shell
> sed -i 's/.*soft_limit.*//' tests/meson.build
> ```

```
%prep
%if "%{?_lib}" == "lib"
sed -i 's/.*soft_limit.*//' tests/meson.build
%endif
```
Thank you, it's work. :-)

**Comment by nemo93** [comment]
I'm closing this issue then. If you disagree feel free to reopen.

**Comment by kcgen** [comment]
Overcome by events: replaced w/ improved compressor.
