### ISSUE TITLE
Games w/ vertical lines

### ISSUE THREAD

**Issue by nemo93** [dosbox-staging/dosbox-staging#1231]
**Describe the bug**
At least 2 games do have vertical lines making them unplayable: [Carmageddon](https://github.com/dosbox-staging/dosbox-staging/wiki/Games-issues#carmageddon) and [Motor Mash](https://github.com/dosbox-staging/dosbox-staging/wiki/Games-issues#motor-mash). Here's a picture which illustrates the problem (taken from that [thread](https://www.vogons.org/viewtopic.php?t=23521)):

![carma](https://user-images.githubusercontent.com/8100500/131256393-151d6015-7494-47fc-b082-3afba019b652.jpg)

This is a rather well-known issue present also on SVN. According to Qbix: "on non-x86 we emulate the fpu using doubles which are 64 bit". [[Reference](https://www.vogons.org/viewtopic.php?p=188733#p188733)]

**To Reproduce**
Launch the games on a non-x86 (eg. Pi) or 64-bit system.

**Expected behaviour**
No lines at all. Clear and crisp display :-)

**Environment:**
- Raspbian OS 32bit (Buster)
- Pi4, no overclock, fKMS (fake mode, default), stock kernel

**Additional context**
Both games do rely on the same game engine: [BRender](https://en.wikipedia.org/wiki/Argonaut_Games#BRender).

**Comment by kcgen** [comment]
I wonder if @cimarronm 's [FPU improvements](https://github.com/joncampbell123/dosbox-x/pulls?q=is%3Apr+is%3Aclosed+author%3Acimarronm+fpu) correctly handle this?

**Comment by arrowgent** [comment]
ive seen this before in carmageddon,  i figured it was the settings i was using or version from GOG (i had some old versions with different DRM "fixes")
doesnt seem to happen in all settings
`voodo2c -hires -novoodoo`
doesnt seem to have this issue

**Comment by nemo93** [comment]
Thanks for this @arrowgent! Indeed the `-hires` parameter does improve the situation a bit as with it, vertical lines are not visible during gameplay. However there are still there at loading screen and on various elements in the menus (like on the "faces" from the drivers selection screen). 

I must add "hires" mode is too much for such a low-spec device like RPi 😢

**Comment by arrowgent** [comment]
https://github.com/dosbox-staging/dosbox-staging/releases/tag/v0.77.1

tested on linux x86_64 again, no issues
cant test on RPI4 right now, will have to wait a day.

other files provided by the CD/ISO/GOG:

3DFX.EXE
CARMA.EXE
CARMAV.EXE

these are the older versions, i had done testing with these checking DRM (cd check) and compatibility
one of these settings also damages the skybox...otherwise was preferred over voodo2c
i found that the voodoo2 patch `voodo2c -hires -novoodoo` was the best medium for performance and compatibility
`-hires` also slows down my FPS performance on `max 100%` on a 3.0GHZ intel i7
but.....compare to a pc you had in the 90s, similar effect (probally engine limitation vs a CPU/GPU limitation)
you can do just` voodoo2c -novoodoo` instead for lower resolution

even playonlinux uses `-novoodoo` in their gog setup:
https://github.com/Translator5/GOG-PlayonLinux/blob/master/carmageddon_max_pack-gog

**VOODO2C.EXE is the only game executable in my folder**
i have deleted the other files after testing

you can check options with `voodo2c -?`


_im not trying to discredit if FPU on linux/rpi might be an issue or that this has been a problem for **over 10 years** in dosbox_

**Comment by arrowgent** [comment]
ok testing on raspberry pi 4b armhf

**dosbox v0.74-2-3+deb10u1** (standard repo from raspbian 10)
`voodo2c -novoodoo`
yes the lines are there
https://i.imgur.com/viDYNlB.png (example)
typical crash at the end of the game...its pretty much always done this
```
Illegal write to a3266602, CS:IP      828:  1e5a92
Illegal write to a3266603, CS:IP      828:  1e5a92
Illegal write to a3266604, CS:IP      828:  1e5a92
Illegal write to a3266605, CS:IP      828:  1e5a92
Illegal write to 40a16604, CS:IP      828:  1e5a9d
Illegal write to 40a16605, CS:IP      828:  1e5a9d
Illegal write to 40a16606, CS:IP      828:  1e5a9d
Illegal write to 40a16607, CS:IP      828:  1e5a9d
Illegal read from 1f00000, CS:IP      828: 1f00000
Illegal read from 1f00001, CS:IP      828: 1f00000
Illegal read from 1f00002, CS:IP      828: 1f00002
```
`voodo2c -hires -novoodoo`
same lines on all surfaces at higher resolution
https://i.imgur.com/kmGtBX0.png


**dosbox-staging 0.77.0**
`voodo2c -novoodoo`
lines 100% of the time
https://i.imgur.com/viDYNlB.png
typical carmageddon crash
```
Illegal write to 8ee08ec0, CS:IP      828:  225a88
Illegal write to 8ee08ec1, CS:IP      828:  225a88
Illegal write to 8ee08ec2, CS:IP      828:  225a88
Illegal write to 8ee08ec3, CS:IP      828:  225a88
Illegal write to 33c18e23, CS:IP      828:  225a98
Illegal write to 33c18e24, CS:IP      828:  225a98
Illegal write to 33c18e25, CS:IP      828:  225a98
Illegal write to 33c18e26, CS:IP      828:  225a98

```
`voodo2c -hires -novoodoo`
lines only on flat textures, lines on loading screen, not on all screens, not in 3d models, lines in sky and in top left "portrait"
https://i.imgur.com/0nNF8qa.png
https://i.imgur.com/otAGXPl.png
-hires doesnt crash

**dosbox-staging 0.77.1** latest stable compiled today
`voodo2c -novoodoo`
same, lines on all surfaces
https://i.imgur.com/viDYNlB.png
`voodo2c -hires -novoodoo`
same, lines only on flat surface textures, not in 3d
https://i.imgur.com/0nNF8qa.png
https://i.imgur.com/otAGXPl.png
-hires doesnt crash

interestingly, cockpit view (C) doesnt show lines on the skybox with -hires


comparison: Linux x86_64
**dosbox-svn**
`voodo2c -hires -novoodoo`
no issues (other than end game crash)
`voodo2c -novoodoo`
no issue

**dosbox-x 0.83.1** (old version) x86_64
`voodo2c -hires -novoodoo`
`voodo2c -novoodoo`
no issues

**dosbox-ece r4465** x86_64
`voodo2c -hires -novoodoo`
`voodo2c -novoodoo`
no issues

**Comment by arrowgent** [comment]
testing other games BRender engine

raspberry pi 4 armhf
```
uname -a
Linux raspberrypi 5.10.17-v7l+ #1421 SMP Thu May 27 14:00:13 BST 2021 armv7l GNU/Linux
```

**dosbox staging 0.77.1**

**FX Fighter (1995) BRender engine**
no apparent issue;  cinematic, menu, in-game.
no options changed: 320x200

**Motor Mash (1998) BRender engine**
cinematic no issue
language select no issue
main menu:  _Vertical Lines_
in-game:  _Vertical Lines_


only dos games i can find

**Comment by arrowgent** [comment]
another step:
fresh compile of `dosbox-x v 0.83.17`
**ARMHF raspberry pi 4 raspbian 10**
_no modification to the dosbox-x.conf_

### no vertical lines
voodo2c.exe -novoodoo
voodo2c.exe -hires -novoodoo


while dosbox  from raspbian's repo has lines
& dosbox-stating has lines
**dosbox-x does not**

... i could also attempt dosbox-ece on raspberry pi,  possibly another test

**Comment by Burrito78** [comment]
Can confirm on Apple M2 using eXoDOS version running default 320x200 resolution on latest DEV version.

**Comment by Grounded0** [comment]
With this kind of performance available on Apple silicon there should be at least configurable option to enable quadruple-precision (128-bit) on those systems that can handle it without issues:

<img width="916" alt="283057823-dee3543c-e20c-4f99-b2da-f2311dcbe22a" src="https://github.com/dosbox-staging/dosbox-staging/assets/48192273/d3e7d521-a646-4e19-81fd-d3cef750787e">

**Comment by Grounded0** [comment]
We are now fairly confident this is _**NOT**_ an FPU extended precision related issue:

https://github.com/dosbox-staging/dosbox-staging/issues/3125#issuecomment-1823747614
