### ISSUE TITLE
[issue feature] add issue form schema for github

### ISSUE THREAD

**Issue by arrowgent** [dosbox-staging/dosbox-staging#1233]
moving forward with features on github, "Form Schemas"
previously offered was template when creating issues.

form schemas attempt to ensure the person creating issues inputs useful data:
version
describe behavior
os
gpu/renderer
etc

i saw another github using this (they were using template previously) and found it more intuitive and fluid
if you want an example:
https://github.com/obsproject/obs-studio/issues/new?assignees=&labels=&template=bug_report.yaml

GitHub documentation for new feature:

https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms
https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-githubs-form-schema

recent Beta release!:
https://github.blog/changelog/2021-06-23-issues-forms-beta-for-public-repositories/

of course, maybe this interferes with your current backend for handling issues. maybe you use other bug-tracking internally
either way its something to consider moving forward for any project

thanks

**Comment by kcgen** [comment]
Very nice! Will try to put this to use.

**Comment by arrowgent** [comment]
great.  im testing it myself and created one form that works

im considering making a PR if i can figure out some other things

**Comment by arrowgent** [comment]
there must be some workflow ability to setup **version** dropdown
like
`{{release}}`

but im not sure how to setup config.yaml etc to manage this with workflows?
