### ISSUE TITLE
Composite mode fails for pcjr and tandy machines

### ISSUE THREAD

**Issue by Jkapp76** [dosbox-staging/dosbox-staging#1237]
**Describe the bug**
When loading a CGA composite game and tapping F12 to switch to composite video the emulator only works when in CGA mode. PCJr fails to enter into composite mode and so does Tandy. 

**To Reproduce**
Load the game "Below the Root," this game supports PCJr 3-voice sound with composite video. Tapping F12 does nothing. However when using CGA mode composite works, but without the 3-voice sound.

**Expected behaviour**
I tried using DOSBox ECE and also DOSBox Optionals and both correctly enter PCJr into 16 color composite mode with the 3-voice music.

**Environment (please complete the following information):**
-Windows 10 on modern Gaming PC.
**Version of dosbox-staging:**
77.1
- Run `dosbox --version`
- Type `ver` command inside DOSBox shell; If the version is reported as `git`
  (meaning you compiled it yourself), use `git describe` command.

**Configuration parameters:**
Share the config file(s) you've been using to run the program.
pcjr mode
**Additional context**
Add any other context or details about the problem you might found relevant
(e.g. screenshots, other dosbox versions impacted, etc).
Both Dosbox optionals and Dosbox ECE have the code for pcjr composite mode, it just needs added.

**Comment by kcgen** [comment]
Thanks for testing the composite modes and sharing your findings, @Jkapp76.
We're still completing the work to add both NewRisingSun's PCjr and reengine's generalized CGA composite patches plus making composite mode configutable via the conf file.

Would you mind testing this build?
 - https://github.com/dosbox-staging/dosbox-staging/suites/3660331667/artifacts/88929981

It's from this pull request: https://github.com/dosbox-staging/dosbox-staging/pull/1214

You can use conf settings:
``` ini
[composite]
#   composite: Enable composite mode on start. 'auto' lets the program decide.
#              Possible values: auto, on, off.
#         era: Era of composite technology: 'new' is more vivid than 'old'.
#              Possible values: old, new.
#         hue: Appearance of RGB palette. For example, adjust until sky is blue. 0-100%, default is 50%.
#  saturation: Intensity of colors, from vivid to washed out. 0-100%, default is 50%.
#    contrast: Ratio between the light and dark. 0-100%, default is 50%.
#  brightness: Luminosity of the image, from overall light to dark. 0-100%, default is 50%.
# convergence: Convergence of subpixel elements, from focused to deconverged. 0-100%, default is 50%.

composite   = on
era         = old
hue         = 50
saturation  = 50
contrast    = 50
brightness  = 50
convergence = 50
```

As well as the hotkeys:
 F12 - enable/disable/auto
 F10 - select the next CRT knob to adjust (see console output)
 F11 / Alt+F11 - rotate the current CRT knob (from 0% to 100%, default is "in the middle, 50%").

**Comment by Jkapp76** [comment]
I tested the build. Composite mode works for both PCJr and Tandy machines.

Tandy composite looks good, but some colors seem wrong. The green monkey at the beginning of Below the Root is yellow on every other composite emulation i've seen.

PCJr composite uses some wrong colors. Comparing to "DOSBox Optionals" build the brown tree trunks are green just like the leaves. And the monkey is green too. 

I could be wrong, but I thought PCJr is the one with a different composite pallette and Tandy uses the standard CGA composite colors.

Aside from the wrong color this composite emulation looks better than probably every other emulation I've seen. Less double-vision effect.

I also own a real Tandy1000ax pc. I just don't have a good method to make disks from images right now to test many games.

But, composite emulation is looking good so far.

**Comment by kcgen** [comment]
Thanks @Jkapp76,

Regarding the hue, if you adjust it (either via hotkey or conf value), can you find a sweet spot that suits the game?

The default hue seems "correct" when tested on other games know to support composite modes: kq2, BC quest for tires, ultima 2, seven cities of gold (although some of these only support Tandy or PCjr but not both). 

For PCjr, I offset it's starting position to try to match the CGA palette, just as a convenience for users (so they don't have to hit the hue key 20 times to rotate the palette to suite). 

But if you think it's incorrect, maybe you can find a better starting position for it? We'd want to test as many games as possible to find an overall sweet spot.

**Comment by kcgen** [comment]
@Jkapp76 , 

A bit more progress - here's a new build:
https://github.com/dosbox-staging/dosbox-staging/suites/3673589620/artifacts/89388635

![2021-09-03_01-14](https://user-images.githubusercontent.com/1557255/131978653-016d1e8d-f8e8-41f7-9119-5bccecf3d70a.png)

That's with:

``` ini
[dosbox]
machine = pcjr
memsize = 1
startup_verbosity = quiet

[composite]
composite  = on
era        = old
saturation = 53
brightness = 20
contrast   = 90

[speaker]
pcspeaker = true
tandy = on
disney = off
```

Or with Tandy and CGA (but without the nice music):

![2021-09-03_00-58_1](https://user-images.githubusercontent.com/1557255/131979600-be1c036c-14e5-44ab-b082-781a83fa2116.png)

**Comment by Jkapp76** [comment]
The Tandy looks very good. PCJr is still rough. I attached a couple snapshots from (DOSBox Optionals) build. this emulator gets the player white and monkey less green. I can get the (staging) emulator's Tandy mode to look pretty good, but the PCJr I can't get it right.

However, BC's quest for tires looks perfect in PCJr mode.

Jumpman Booter version looks good... I need to press F11 about twice to make the ladders a proper blue shade and his shirt the correct purple. But then it's perfect; even the level 2 robots are the correct yellow.

If we can get the colors right I think (staging) will have the best composite mode ever. I'm not sure why the colors are perfect on some games but wrong on Below the Root... but other DOSBox builds get that right. DOSBox-X gets these colors all right as well on all games. I wonder if dosbox-x and dosbox optionals use the same code for pcjr composite? They manage to get all these colors perfect. But, with them I still need to tap F11 (twice) to get those Jumpman colors right.

![loader_005](https://user-images.githubusercontent.com/89743985/132062263-9243e19a-f94d-47a3-8095-d57193cffd2c.png)
![loader_002](https://user-images.githubusercontent.com/89743985/132062311-c0f4c2f8-aab5-4ecd-a314-b92e29c45521.png)

**Comment by Jkapp76** [comment]
Would it be possible to make Tandy emulation report as PCJr to games? maybe create a (tandy-pcj) machine?

And also a (pcjr-t) to report pcjr as tandy? I'm thinking this could allow certain games to make use of the 3-voice sound with a different pallette. 

Also, Space Quest 2 fails in Composite mode. crashes. Works in dosbox-x and optionals. I actualls prefer the composite colors on this game when it works, changes all the pink to a nice orange, which is how the Amiga version looks.

Hope this helps.

**Comment by Jkapp76** [comment]
This latest version is good enough to include, but I'm not sure why the other dosbox builds get the pcjr colors right on more games. It seems like the palette itself is off somehow. I can't adjust it in perfect.

**Comment by Jkapp76** [comment]
Tandy composite video: Some colors seem wrong. The game Zork Quest 2 has the land and the sea both the same color. With CGA composite the land is green and the sea blue.

I always thought Tandy had the exact same cga palette as all CGA PCs. Maybe I'm wrong but I thought only PCJr had the couple different cga colors. Anyway, land and sea are both blue on zork-quest2.

**Comment by Jkapp76** [comment]
I do like all the settings to fine-tune the composite video. Very nice. I just can't get those colors in on some games like I can on dB Optionals or db-x.

**Comment by kcgen** [comment]
Thanks for these details -  now switching to fixing PCjr mode.  These games will be very useful to check against. Will keep you posted when an update is ready.

**Comment by kcgen** [comment]
@Jkapp76 , 

When you have a chance to try `machine = pcjr` composite with this binary:

https://github.com/dosbox-staging/dosbox-staging/actions/runs/1234963830

This branch doesn't have the conf settings yet (so will need to press F12 to activate it). 
We're just trying to ensure we have PCjr composite correct at this point.

**Comment by Jkapp76** [comment]
I tested the build...
Everything looks perfect. I only had about 30 minutes to work on this but all looks great.

Gamma Force - Fails, but also fails on every PCJr emulation I've tried
Lane Mastedon - Same - These might not work with PCJr?
zork quest 1 & 2 - Same - These three are all the same type of game from Infocom.

Winnie the pooh - crashed - I'll test more later, I thought I remembered 3-voice music with composite color but I can't get anything to load this game right now, except CGA with pc speaker.

Jungle hunt - perfect
Alley Cat - Perrfect
Below the Root - Perfect
BC's Quest for Tires - Perfect

Everything I would actually use PCJr for works. (Winnie the pooh is bothering me)

**Comment by kcgen** [comment]
@Jkapp76 , new binary here: https://github.com/dosbox-staging/dosbox-staging/actions/runs/1239367383
Composite _should_ be working for all three again: `pcjr`, `cga`, and `tandy`.
The hotkey adjustments should work for all three.
The conf settings (per: https://github.com/dosbox-staging/dosbox-staging/pull/1267) should also work.

Indeed, some (many?) games don't entirely work correctly - but usually at least one of these composite modes works.  Winnie the pooh needs: `loadfix -88 winnie`, however it only seems to run in 16-color non-composite.

**Comment by Jkapp76** [comment]
I tried it...
I mostly like the colors from the last version. Black is very grey.

Gamma Force, the flames are pink instead of red. All the Infocom games play in CGA composite, but the colors are weird. and pale. I also noticed the Infocom games play in Tandy CGA mode. but I can't get Tandy into Composite mode to check further. 

Bc's Quest for Tires = The sky is a very nice blue. (maybe too nice of a blue? I'm used to that green-blue)

Troll's tale on CGA looks like it has the wrong colors now. The troll has blue skin on the PCJr 16 color booter version. The last version You posted Had the correct blue skin even in cga composite mode. Now he's green in composite CGA, which looks okay, but I'm pretty sure it's supposed to be blue.

Castle Wolfenstein's loading screen has colors I've never seen before on CGA composite. I've always seen different colors on PCJr, but these colors look better to me. green army clothes. Blurry and pale though.

Beyond Castle Wolfenstein has a composite cga loading screen. I have no idea what the colors should be, but it looks strange. I like how all those dots and misaligned lines pull together to make a clean picture. (The game won't start on last version it locks but plays on this newest version) The colors looked much better on last version though.

The PCJr 16 color games look perfect. The Tandy 16 color games look perfect too. I have booter images for every type of game.


*I like just about everything better in the last version. Except Beyond Castle Wolfenstein hung on that version. I don't see composite CGA in Tandy mode yet either.

**Comment by kcgen** [comment]
Thank you for all the tests!

The big difference between this latest build and the prior PCjr-fix build is that this new one uses reengine's improved CGA composite patch.  Where as the prior PCjr-fix has his first incarnation patch (common on many other forks). 

If you can grab a handful of good vs bad screenshots, and the machine type used - that would be a big help.  (Can drag PNGs into the edit box here). 

Also, if you share some of the games too, so we're comparing apples to apples, that would be very appreciated. (Can zip and attach here if below 20MB). 

We'll get it right 🚀

**Comment by Jkapp76** [comment]
[booters.zip](https://github.com/dosbox-staging/dosbox-staging/files/7174386/booters.zip)

Here's Just my Booter disk collection. I made the Telarium games booters by making the DOS 2.1 disks myself for an old computer project.

I've been playing a different non-booter version of below the root, it's cracked and easy to find online. I can send more later.

**Comment by Jkapp76** [comment]
[COMPOSIT.zip](https://github.com/dosbox-staging/dosbox-staging/files/7174440/COMPOSIT.zip)

Here's pretty much all of my Composite CGA games. some look better on different machines. I'll dig for more tomorrow, I probably have a few more somewhere.

**Comment by Jkapp76** [comment]
![sta_br](https://user-images.githubusercontent.com/89743985/133710150-77200da7-df78-4730-9927-2afd4145fdd5.png)
Here's the latest DOSBox Staging. green Rabbit, pink water. blurry.

![opt_br](https://user-images.githubusercontent.com/89743985/133710154-5bd28d52-6f0d-4d4a-9464-266ef1a87b58.png)
Here's DOSBox Optionals. One thing they do great is their Composite modes. Best I ever saw so far.

**Comment by Jkapp76** [comment]
Wait a second. I just deleted the Composite settings completely from the CONF file and the colors look perfect. No more 50 or 92 or anything, just gone. This picture is using NEW cga mode where the last two were OLD cga mode. If I used old with this version it would look the same as the last two pics so I used NEW mode to show how good it looks. I prefer NEW.

![onelast](https://user-images.githubusercontent.com/89743985/133714186-17a6145b-b3c9-4e1c-a09a-78cb8b27f43f.png)

**Comment by Jkapp76** [comment]
This latest test build is in fact the best so far. Sorry for not realizing the composite section sooner.

**Comment by kcgen** [comment]
This is great news - yes, one of the things I changed but forgot to mention is that the conf settings now uses 'magnitiudes' of the adjustable values instead of percentages (like I did in a prior attempt). 

I found that the code was getting quite messy dealing with the conversions - and even worse when trying to add the PCjr adjustables as well (which would have had separate conversions to and from percentages). 

I didn't have time to spend on the composite this morning - but glad you've cleared /reset your settings. 

Regarding using machine = cga and machine = tandy, in composite modes: are the colors OK there?

**Comment by kcgen** [comment]
> This latest test build is in fact the best so far. Sorry for not realizing the composite section sooner.

Entirely my fault!

**Comment by kcgen** [comment]
You can write a fresh conf file when at the DOS prompt: "z:\> config -wc", and you will get all the current settings and comments. 
(WC meaning write-config). 

You can use: `dosbox -editconf`

To pop open your conf file in an editor (notepad++ or notepad, which ever is available).

**Comment by Jkapp76** [comment]
I ran through a list of CGA and Tandy composite games. BC, Winnie, Infocom (which work on Tandy but not PCJr) 

I can't find any issues. It all looks great so far. Are there new composite options I can add to the conf file?

**Comment by kcgen** [comment]
Yup, see my comment just above yours.
(Messages crossed in the ether 😅 )

**Comment by Jkapp76** [comment]
Is there a command within dosbox to adjust the hue? Jumpman really needs "hue 25" on CGA to look right. But not all games need this so I wouldn't recommend 25 as a default. 

I made a batch file to start the jumpman booter. "Boot jumpman.img" after setting cycles to 380. The ability to set hue and other composite settings by command line would be great for these finicky games. But I don't really see many games that need adjusting either.

**Comment by kcgen** [comment]
> Is there a command within dosbox to adjust the hue? Jumpman really needs "hue 25" on CGA to look right. But not all games need this so I wouldn't recommend 25 as a default.

You've got it right: `hue 25`

For example, to set cycles to 380, enable composite, and set hue to 25:

**jumpman.bat**
``` bat
cycles 380
composite on
hue 25
jump.com
exit
```

**Comment by kcgen** [comment]
One option I like to do is provide each game with a local `dosbox.conf`, inside the game's directory.
This lets you tailor things like the machine type, disable memory extensions, disable audio devices (like SB and MIDI), disable the mouse, and others that can only be adjusted on startup.

``` ini
[sdl]
capture_mouse = nomouse            

[dosbox]
machine = pcjr
memsize = 1
startup_verbosity = quiet

[cpu]
cycles=380

[composite]
composite = on
hue = 25

[dos]
xms = false
ems = false
umb = false

[gus] 
gus = false

[sblaster]
sbtype = none
oplmode = none

[midi]
mpu401 = none
mididevice = none
midiconfig = none

[autoexec]
mount c .
c:
launch-game-here.bat
exit
```

That's a template I use for really old games. 

Then in that last `[autoexec]` section, you can call the game's original `.bat` (or executable). 
This approach helps keep the DOSBox-specific stuff in it's own conf file, while keeping the `.bat` file agnostic of the environment in which it's running.  For example, you could copy the folder to a real Tandy and launch the .bat without errors.

**Comment by kcgen** [comment]
A nice wiki page also showing per-game config files:
 - https://github.com/dosbox-staging/dosbox-staging/wiki/Config-file-examples

**Comment by Jkapp76** [comment]
I like how you set the default composite settings as PCJr using NEW and Tandy using OLD. If PCJr uses OLD the red and brown are so nearly the same color you can't tell them apart. (Like in the below the root intro). Tandy doesn't do this with OLD so this setup IMO, works best.

For a long time I considered Below the Root to be the most difficult composite game to get perfect, with it's 3-voice music and all. It's working great. And I can't find another game that has issues yet. Winnie works on Tandy without the loadfix thing.

It seems that adding a dosbox.conf file to the game folder will not change the machine type. Maybe that was too much to hope for? But you've turned me on to something I haven't been making use of anyway.

I'll keep on testing later to see what I can find, but so far I'm pretty impressed with the latest build.

**Comment by Jkapp76** [comment]
I'm thinking about opening another bug report.  I just noticed Joystick support isn't working. 
I loaded Jumpman and also BC's Quest for Tires on PCJr and CGA. The joystick does not work. I did get jumpman to run to the right and even jump with some struggling. And somehow got BC to jump one time. But it seems no good.

I tried these two games with the same joystick settings and machine (both PCJr and CGA) on DOSBox ECE and both worked with identical settings.

I also tried Space Quest 2 with same results. No go on Staging, works fine on ECE.

**Comment by Jkapp76** [comment]
[booters.zip](https://github.com/dosbox-staging/dosbox-staging/files/7198036/booters.zip)

Here's an updated Zip collection of my Booter games. I added about 10 here. Thanks to Retrograde Station for about 6 of these, and theoldcomputer site for the rest.

**Comment by Jkapp76** [comment]
[COMPOSIT.zip](https://github.com/dosbox-staging/dosbox-staging/files/7198318/COMPOSIT.zip)

And here's an updated collection of all my Composite CGA\PCJr\T1K games. I added about 12 or so. This is almost a complete collection of Composite CGA games. Let me know if you ever find one I missed.

**Comment by Jkapp76** [comment]
![mess_000](https://user-images.githubusercontent.com/89743985/134228132-e7fba07f-b356-4d50-8caf-40a10fdf278c.png)
MESS gets the CGA colors a bit different. They look better to me. Not sure if they're correct.
![boot_000](https://user-images.githubusercontent.com/89743985/134228226-1ac0c818-4878-4389-8694-965ed7cb6326.png)
Here is the colors from Staging.
![mess_002](https://user-images.githubusercontent.com/89743985/134228305-a6bc5d52-fe3b-41d2-96f4-406b526ea7b0.png)
Mess makes the skin tones better.
![boot_001](https://user-images.githubusercontent.com/89743985/134228393-66035a2a-ea94-4c09-89ff-86b9bc50ea63.png)
Staging has orange skin here in Donkey Kong.

![boot_000](https://user-images.githubusercontent.com/89743985/134228486-7ea0f893-9b86-44bd-abfd-4c3190eb1cfb.png)
For whatever it's worth, Tandy Composite mode Has probably the best colors of all. Great gameplay too.

**Comment by kcgen** [comment]
Thanks for these continued details and help!

Regarding the latest builds and how they handle conf files - Please see this short description of the layered approach'

<https://github.com/dosbox-staging/dosbox-staging/blob/11b444343081a8178d44c3379715a151f1448559/README#L393>

And the notes here expand this into practical examples:

<https://github.com/dosbox-staging/dosbox-staging/wiki/Config-file-examples>

When you start up, look at the CONFIG: log entries to see the load-order of conflig files, and how settings are being layered on top of eachother. 

Hope it helps 👍

**Comment by Jkapp76** [comment]
In the newer 0.78 480 release.
![cw_78 480](https://user-images.githubusercontent.com/89743985/134249512-06c8b94e-bc85-43cc-b7da-7e4267c17f02.png)
The Castle Wolfenstein logo isn't in the normal colors.


![cw_77](https://user-images.githubusercontent.com/89743985/134249569-1f15aa8d-80cc-49b9-8d6e-73e742cb79ac.png)
Here is how the title screen looks in the 0.77, and also (0.78 410)

I can't seem to get the cycles set like I could in earlier versions. I can slow it down after launching. I'm not sure why we seem to have the old CGA colors now on PCJr, which always had this greenish clothes.

**Comment by kcgen** [comment]
From Wolfenstein, can you copy and paste your console log output, and attach the conf files mentioned in the log's `CONFIG:` lines?

**Comment by Jkapp76** [comment]
C:\Users\jkapp.LAPTOP-UFK3EMEQ\Desktop\DosBox\DOSBox-Staging v0.78.0-alpha-480>dosbox -conf PCjr.conf
date       time         |
2021-09-21 18:16:29.037 | arguments: dosbox -conf PCjr.conf
2021-09-21 18:16:29.038 | Current dir: C:\Users\jkapp.LAPTOP-UFK3EMEQ\Desktop\DosBox\DOSBox-Staging v0.78.0-alpha-480
2021-09-21 18:16:29.038 | stderr verbosity: 0
2021-09-21 18:16:29.038 | -----------------------------------
2021-09-21 18:16:29.039 | dosbox-staging version 0.78.0-alpha-480-g11b44
2021-09-21 18:16:29.039 | ---
2021-09-21 18:16:29.053 | CONFIG: Loaded primary conf file C:\Users\jkapp.LAPTOP-UFK3EMEQ\AppData\Local\DOSBox\dosbox-staging.conf
2021-09-21 18:16:29.054 | CONFIG: Loaded custom conf file PCjr.conf
2021-09-21 18:16:29.054 | CONFIG: Deprecated option 'blocksize'
2021-09-21 18:16:29.054 | CONFIG: This property is deprecated, use latency instead.
2021-09-21 18:16:29.055 | CONFIG: Deprecated option 'prebuffer'
2021-09-21 18:16:29.055 | CONFIG: This property is deprecated, use latency instead.
2021-09-21 18:16:29.055 | CONFIG: Loaded local conf file dosbox.conf
2021-09-21 18:16:29.056 | DISPLAY: Disabled resizable window, only compatible with 'sharp' and 'none' glshaders
2021-09-21 18:16:29.056 | DISPLAY: Initialized 1280x800 window-mode on 1920x1080 display-0
2021-09-21 18:16:29.683 | OPENGL: Pixel buffer object extension: available
2021-09-21 18:16:30.865 | SDL: Mouse will move seamlessly without being captured and middle-click will uncapture the mouse.
2021-09-21 18:16:30.896 | MEMORY: Base address: 0000023EB5F44040
2021-09-21 18:16:30.897 | MEMORY: Using 4096 DOS memory pages (16 MiB)
2021-09-21 18:16:30.898 | VIDEO: Initialized S3 Trio64 (VESA 2.0) compatible modes with 4 MiB of FP DRAM
2021-09-21 18:16:31.886 | MIXER: SDL changed the playback rate from 44100 to 48000 Hz
2021-09-21 18:16:31.886 | MIXER: SDL changed the blocksize from 661 to 480 frames
2021-09-21 18:16:31.887 | MIXER: Negotiated 2-channel 48000-Hz 10ms-latency audio in 480-frame blocks
2021-09-21 18:16:32.089 | MIDI: Opened device: win32
2021-09-21 18:16:32.089 | MIXER: FM channel operating at 48000 Hz without resampling
2021-09-21 18:16:32.089 | MIXER: SB channel operating at 22050 Hz and upsampling to the output rate
2021-09-21 18:16:32.090 | SB16: @SET BLASTER=A220 I7 D1 H5 T6
2021-09-21 18:16:32.091 | MIXER: SPKR channel operating at 18939 Hz and upsampling to the output rate
2021-09-21 18:16:32.091 | MIXER: DISNEY channel operating at 10000 Hz and upsampling to the output rate
2021-09-21 18:16:32.108 | MAPPER: Found no joysticks
2021-09-21 18:16:32.108 | MAPPER: Loaded default key bindings
2021-09-21 18:16:32.109 | MOUNT: Path '..\dos' found
2021-09-21 18:16:32.110 | MOUNT: Path '..\SUPP' found
2021-09-21 18:16:32.117 | SDL: captured the mouse
2021-09-21 18:16:32.121 | DISPLAY: Bilinear scaling source 640x400 (PAR 1.00) by 2.7x2.7 -> 1728x1080 (PAR 1.00)
2021-09-21 18:16:43.444 | SDL: released the mouse

Can't attach the conf file. but I see it's loading another local one. None of the other older builds are loading the other one.

**Comment by Jkapp76** [comment]
This 480 version is creating a conf file in APPData. No older versions do this. I've been using a dosbox.conf local in the install directory for every version because I don't want this file created in APPData.

But 480 insists on creating it and using it.

**Comment by Jkapp76** [comment]
It looks like PCJr does get all the colors very good, except the yellow is now orange. 

![cw_000](https://user-images.githubusercontent.com/89743985/134256974-f523001e-58ce-40bf-ad6a-c3ef5cccb719.png)

**Comment by kcgen** [comment]
Please read the content again here - https://github.com/dosbox-staging/dosbox-staging/issues/1237#issuecomment-924356536.  It describes the layered config approach,

``` text
2021-09-21 18:16:29.053 | CONFIG: Loaded primary ..  AppData\Local\DOSBox\dosbox-staging.conf
2021-09-21 18:16:29.054 | CONFIG: Loaded custom conf file PCjr.conf
```

> This 480 version is creating a conf file in APPData. No older versions do this. But 480 insists on creating it and using it.

If you delete this file, it will populate it with the default settings.  DOSBox has always uses default settings (embedded inside the executable) no matter what, so you can think of this file simply as holding those defaults. 

> I launch dosbox with several BAT files. These are all made to choose a different conf file. I don't want dosbox using any other file.  

 - `dosbox -conf PCjr.conf` looks good.
 - The settings in `PCjr.conf` override everything in your primary conf (which is just default at this point anyway).

Can you zip or add a `.txt` extension to:

 `C:\Users\jkapp.LAPTOP-UFK3EMEQ\Desktop\DosBox\DOSBox-Staging v0.78.0-alpha-480\ PCjr.conf` 

And attach it here? That's the file where all the settings are coming from. 

Here's `machine = cga`, non-composite:

![2021-09-21_15-47](https://user-images.githubusercontent.com/1557255/134258111-507af2af-eb91-4613-a83f-3fc01d66749f.png)

And  `machine = cga`, composite:

![2021-09-21_15-47_1](https://user-images.githubusercontent.com/1557255/134258110-d1248965-b703-4f73-976c-66b0125ced24.png)

Here's `machine = pcjr`, non-composite:

![2021-09-21_15-47_3](https://user-images.githubusercontent.com/1557255/134258107-e5c52537-145b-4af5-868c-011e305cb393.png)

Here's `machine = pcjr`, composite:

![2021-09-21_15-48](https://user-images.githubusercontent.com/1557255/134258106-9e88e164-27cc-412d-a340-a3e85b4cc37c.png)

Here's `machine = pcjr`, composite with hotkey adjustments:

![2021-09-21_15-49](https://user-images.githubusercontent.com/1557255/134258104-609305c2-b8d3-4cdb-83fb-8c38360f9797.png)

I used the hotkeys to get the last settings, and then I entered them into my conf file:

**wolf.conf**

``` ini
[dosbox]
machine = pcjr

[cpu]
cycles = 60

[composite]
composite = on
era = new
hue = 360
saturation = 55
contrast = 205
brightness = 0

[autoexec]
imgmount a CASWOLF.IMG -t floppy
a:
cw.exe
```


I'm assuming you know how to use the hokeys to turn up and down hue / brightness / contrast / saturation and toggle between new-and-old?

**Comment by kcgen** [comment]
I would suggest an approach like this:

Top-level batch file: Select between CGA, Tandy, or PCJR
The top-level choice calls a second level batch with a list of respective games for that video type.
Finally, the second-level choice does this:
 - `cd`'s into the individual game's directory that has its own `dosbox.conf` 
 - The game's `dosbox.conf` has fine-tuned cycles and composite settings just like I've listed above, including mounting the image and running the game.
 - It launches `dosbox -conf ../pcjr.conf`.  Staging will automatically find the local `dosbox.conf` and layer that on last.

**Comment by Jkapp76** [comment]
I have BAT files for each machine. PCJr, CGA, EGA, and a couple more.
I start DOSBox with one of them and they start up a file manager like Volkov Commander.
Then I browse for the game.

I have many versions of DOSBox installed. None of them create a conf file in APPData if there is already one in the dosbox folder.
Only this newest alpha version does this. I keep a dosbox.conf in the older 410 version and it won't create another one.

I've never experimented with placing a conf file in each game folder until a couple days ago. 

This is how I've been using DOSBox. I mount a couple folders as drive C and D. C has windows 3.11 and all my games.
In C I have folders for CGA games, Composite, which I've shared, Booters, and other games I use with the different machine's BAT files.

**Comment by kcgen** [comment]
Thanks ; I think it makes sense to adjust the creation of rhe primary conf to match the existing behavior: if other conf's have been read, then don't create a new primary.  Only create a new primary if no other conf's have been read.

**Comment by Jkapp76** [comment]
That sounds great. And that is what I'm used to.

**Comment by kcgen** [comment]
> That sounds great. And that is what I'm used to.

Can you see if this new build has the desired conf behavior? thanks @Jkapp76 -

https://github.com/dosbox-staging/dosbox-staging/actions/runs/1262914551

**Comment by Jkapp76** [comment]
"Can you see if this new build has the desired conf behavior? thanks @Jkapp76 -"

This does not create a new file in APPData if there is one in the Install folder.
But, Every machine runs at 7000 cycles now. I don't see a new conf file anywhere, but it ignores the local conf.

Lemmings 2 audio sounds funny when beginning a level, the "let's go!" voice is distorted.

No Composite video options.

**Comment by Jkapp76** [comment]
![482_1](https://user-images.githubusercontent.com/89743985/134410197-164d098f-de54-4972-b9c7-846186264083.png)

It now seems to load the dosbox.conf which is also local and that file seems to be a higher priority.

**Comment by kcgen** [comment]
> Lemmings 2 audio sounds funny when beginning a level, the "let's go!" voice is distorted.

This is a know issues in the latest sources: <https://github.com/dosbox-staging/dosbox-staging/issues/1257>

**Comment by kcgen** [comment]
Third try's a charm? -- can you try this: https://github.com/dosbox-staging/dosbox-staging/actions/runs/1263737713

        DOSBox Staging uses a layered configuration approach, as follows:

        1. The primary configuration file is loaded first, which comes
           from the operating system's user configuration directory.
           This can be thought of as your "global" configuration file.
           Adding -noprimaryconf avoids loading your primary conf file.

        3. Second, if the local directory contains a dosbox.conf file,
           these settings are added.
           Adding -nolocalconf avoids loading the local dosbox.conf file.

        2. Finally, custom configurations are layered on, in order,
           using one or more -conf <filename> arguments. For example:
           dosbox -conf myshader.conf -conf myaudio.conf

        This layered approach means you can start with the most general
        settings (from your primary conf) and increasingly fine-tune them
        for a specific game.

**Comment by Jkapp76** [comment]
I'm looking forward to trying all this out. And I might prefer the -no options once I get my feet in it.

I'm away until tomorrow afternoon. But I'll be on it.

**Comment by Jkapp76** [comment]
If I start dosbox with -nolocalconf it does not create a conf in APPData. Everything seems great.

I expected it to create a conf in APPData if I didn't use -noprimaryconf.

If there is no local conf file in the dosbox directory one is created in APPData. This seems good.

If I have several conf files in the install directory but none are named "dosbox.conf" one is created in APPData.

If I let dosbox create a default conf in APPData and then load my own local pcjr conf the pcjr settings are now used! This fixed my issue I had before and seems good to me.

I can't see much use for "-noprimaryconf". If there is a dosbox.conf in the dosbox directory the primary isn't created anyway. And if I load my own pcjr.conf the primary isn't used. But, I believe if I had a limited conf with only a few settings this option might be useful? I didn't test that, but it seems useful.

**Comment by kcgen** [comment]
Thanks for trying all those scenarios @Jkapp76; I really appreciate your feedback.

I think this is a good layered approach, as it still appears to be functionally compatible,  and yet is more aligned with "standard" configuration layering in Windows (system-hive, user-hive, custom settings) and Unix systems (/etc, then ~/local, and then custom flags). 

Regarding the `-no` options: these two let users quickly figure if a conf file is causing some problems.  (There are even some users who say DOSBox doesn't even start; usually it's due to an incompatible video output setting, and these settings will help us quickly help them).

**Comment by Jkapp76** [comment]
I let dosbox create the APPData conf file.

Then I loaded a PCJr conf with only machine type = pcjr and cycles = 275.

The machine was set to pcjr, but the cycles = 275 was ignored.

**Comment by kcgen** [comment]
> I let dosbox create the APPData conf file.
> 
> Then I loaded a PCJr conf with only machine type = pcjr and cycles = 275.
> 
> The machine was set to pcjr, but the cycles = 275 was ignored.

Double check the categories in your conf - cycles lives within [cpu]:


```ini
[dosbox]
machine = pcjr

[cpu]
cycles = 275
```

**Comment by Jkapp76** [comment]
My mistake. I deleted the "[cpu]" text about those settings. 

This is indeed working correctly. sorry.

**Comment by kcgen** [comment]
No worries 👍

**Comment by kcgen** [comment]
Thanks for all the help here @Jkapp76!
Will close this ticket for now; feel free to open new ones for new issues/concern.

**Comment by Jkapp76** [comment]
@kcgen 

The latest 527 build will not load shaders for me if I load the dosbox.conf that is in the dosbox install folder.
Any other conf I load from a BAT file has shaders, but not the one named "dosbox.conf". the ones with names like cga.conf load fine.

Also, Tandy machine now hangs at startup using the simple conf file I have used for ages.

**Comment by Jkapp76** [comment]
Actually, I can't get shaders to work on svgs_s3 at all. I get vertical lines of some kind if I look closely, but not like normal horizontal.
