### ISSUE TITLE
LFN Long File Name Support

### ISSUE THREAD

**Issue by Jkapp76** [dosbox-staging/dosbox-staging#1238]
**Is your feature request related to a problem? Please describe.**
Long File name support such as Dosbox-x has is very good for use with file managers that support it such as DOSZip. 

**Describe the solution you'd like**
Long File Name support helps to read the game names when you have many in your local drive.

**Describe alternatives you've considered**
DOSBox-X has this feature and it's very nice.

**Additional context**
A simple LFN=True\False works fine for DOSBox-x

**Comment by kcgen** [comment]
@Jkapp76 , thanks for the suggestion.

We have on two occasions attempted this, however the volume of changes is non-trivial - see both prior attempts here:
 - https://github.com/dosbox-staging/dosbox-staging/pull/467
 - https://github.com/dosbox-staging/dosbox-staging/pull/476

Considerable time and effort was put into this, especially by @Wengier.  The second PR generated over 100 separate discussion threads among the three of us.

If this were a make-or-break feature for some number of DOS or Windows 3.1 games - then yes (just like adding Voodoo is still a wish); but unfortunately LFN is not make-or-break for DOS/Win3.1 gaming.  

See our goals here:

https://dosbox-staging.github.io/about/

LFN specifically falls into the bottom item - and unfortunately we were unable to pass the highlighted condition:

![2021-09-01_12-35](https://user-images.githubusercontent.com/1557255/131733353-bf775a10-f6eb-4577-b3a9-71f267f5498f.png)

If adding LFN were a trivial - then absolutely! And no doubt DOSBox SVN upstream would likely have done this too. 

Closing this tick for now.  Perhaps one day, with refactoring and/or language improvements, adding LFN might be made easy enough that we can reconsider it.
