### ISSUE TITLE
Mortal Kombat Trilogy will hang if `joysticktype=none`

### ISSUE THREAD

**Issue by nemo93** [dosbox-staging/dosbox-staging#1241]
**Describe the bug**
Mortal Kombat Trilogy gave me a headache... Indeed the game was always hanging at the same spot (the dragon head logo right after the bunch of company logos). The game hangs there forever yet you can still hear the sound of the next screen (which is normally a text scrolling with Goro's cave as background). You can only Ctrl+F9.

I realize I was facing the issue only when my xbox controller was switched **ON**. When switched **OFF** no problem whatsoever. 

This is an annoying bug though as I can't properly use the mapper as I must declare a joystick in my conf file otherwise game will hang. Here's the exact behaviour in various scenarii:

1. game **will** freeze if => `joysticktype=none` + controller **ON** (with or without a mapper file)
2. game will **NOT** freeze if => `joysticktype=none` + controller **OFF**
3. game will **NOT** freeze if => `joysticktype=disabled` + controller **ON**
4. game will **NOT** freeze if => `joysticktype=auto` (or any other value except none ) + controller **ON**

**To Reproduce**
Have the game running with a controller switched **ON** and with `joysticktype=none` then wait for the "dragon head logo". Please note it's the only game tested so far doing this.

**Expected behaviour**
Game to work as expected + being able to set `joysticktype=none` while a controller is **ON** in order to bind it with the mapper.

**Environment:**
- Raspbian OS 32bit (Buster)
- Pi4, no overclock, fKMS (fake mode, default), stock kernel

**Additional context**
Issue: https://github.com/dosbox-staging/dosbox-staging/issues/1111
Change: https://github.com/dosbox-staging/dosbox-staging/pull/1166

**Comment by kcgen** [comment]
@nemo93 - sorry for delay on this one.
Reproduced on my side, and now should be working in the latest sources.

**Comment by nemo93** [comment]
No need to apologize. Take all time you need, no rush. Good you were able to reproduce. I've just tested with this "morning" master but unfortunately this time no mappings are working whatsoever. With any games I've tested with and despite these mappings were working fine before. 

It's like `joysticktype=disabled` is being set even if I do have set `joysticktype=none`. If you need anything please let me know. Thanks.

**Comment by kcgen** [comment]
Thank you, @nemo93 - reproduced on my side. 

Unrelated - but given we're in `alpha` and touching the code: `joysticktype = none` and `disabled` are very ambiguous terms, so if possible, I'd like to make them more intuitive.  None  means _"invisible to DOS but still mappable"_ --> Is there an short and sweet way to say it? "only_mappable",  "hidden_to_dos", ...

**Comment by kcgen** [comment]
@nemo93 - hopefully better results in the PR. Thankful for any further testing you can do on the `kc/joystick-use-doubles-1`.

**Comment by nemo93** [comment]
@kcgen this time it works flawless. I haven't had time to go through an extended testing session yet MKT works perfectly and as expected. The few other mappings tested with other games have no issue at all. I'm closing this one off.

I agree `none` is not that great value in that case while `disabled` makes immediate sense. The best term would be `invisible` although a bit long. What about `hidden` then?

**Comment by kcgen** [comment]
@nemo93 - more candidate names for the mapping-only / invisible in DOS mode:
 - invisible : +2, @nemo93 , @kcgen 
 - hidden : +0
 - passive +1, @MasterO2 
 - transparent +0
 - host +1, @GranMinigun 
 
Feel free to add a vote and your name :+1:
