### ISSUE TITLE
`IO:IOBUS: Unexpected read from 0278h; blocking` warnings on startup?

### ISSUE THREAD

**Issue by LowLevelMahn** [dosbox-staging/dosbox-staging#1245]
git build/Win7/x64

using latest git version i get these unexpected read "warnings" on dosbox startup (i don't think that these are new warnings) i just want to understand why these warnings occure - without even loading a game

i delete my default config an used a freshly recreated 

```
MIXER: DISNEY channel operating at 10000 Hz and upsampling to the output rate

         0: IO:IOBUS: Unexpected read from 0278h; blocking

         0: IO:IOBUS: Unexpected read from 0279h; blocking

         0: IO:IOBUS: Unexpected read from 03bch; blocking

         0: IO:IOBUS: Unexpected read from 03beh; blocking
```

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by LowLevelMahn** [comment]
Its something with Covox or parallel port according to ralp browns port list: https://github.com/cirosantilli/ralf-brown-interrupt-list/blob/master/inter61d/PORTS.B

**Comment by kcgen** [comment]
These blocked port logs are only turned on when the debugger is enabled.  Otherwise for non-debugger builds they should be omitted.  

So my guess is this is a debugger build?

Staging is using loguru now, so if this is a debugger build, maybe loguru is also sending a copy of these logs to stdout.

**Comment by arrowgent** [comment]
are all git builds defaulted to debug versions instead of release versions?
i never looked into the specifics of compile time settings for those flags

**Comment by LowLevelMahn** [comment]
@kcgen 
> These blocked port logs are only turned on when the debugger is enabled. Otherwise for non-debugger builds they should be omitted.

you talk about my config.h settings?
```
#define C_DEBUG 1
#define C_HEAVY_DEBUG 1
```
yes its a x64 Release build with dosbox-debugger enabled

so what does these blocked accesses mean? no parallel Port enabled? and whos is accessing these ports?

@arrowgent

i think kcgen is talking about the integrated debugger in dosbox - not a Debug (ala Release) Build

**Comment by LowLevelMahn** [comment]
i also got some of these starting Alpha Waves (https://www.mobygames.com/game/continuum) in Hercules Mode

```
       178: IO:IOBUS: Unexpected write of 15 to 03d4h; blocking

       180: IO:IOBUS: Unexpected read from 03d5h; blocking

       183: IO:IOBUS: Unexpected write of 102 to 03d5h; blocking
```

game runs fine

**Comment by LowLevelMahn** [comment]
`	0: IO:IOBUS: Unexpected read from 0278h; blocking`
  
  from class BIOS ctor
  
```
  BIOS(Section* configuration):Module_base(configuration){
  ...
    
			ppindex++;
			if((IO_Read(0x278)!=0xff)|(IO_Read(0x279)!=0xff)) {
				// this is our LPT2
        
  ...

```

so these "blocked" reads happen in the Bios initalization - but why do we try to read ports that are definitily not
available?

**Comment by kcgen** [comment]
Hi @LowLevelMahn , sorry for the late reply. 

Yes, these are entirely expected and normal: applications "knocking on doors" to see if a device or service is available. 

When building with the debugger enabled, these log messages are enabled so it's easy to see what (possible) port handler is needed - especially if something isn't behaving as expected or just prior to failing. 

Fortunately for gaming purposes, DOSBox has long since implemented almost all important port handlers (and those that aren't implemented have no consequences/impact).

**Comment by LowLevelMahn** [comment]
Yes, these are entirely expected and normal: applications "knocking on doors" to see if a device or service is available.

Thats 100% clear, but why is dosbox own init code accessing ports that never can work, due to missing initialization in code, far before any program gets started

**Comment by kcgen** [comment]
>  why is dosbox own init code accessing ports that never can work, due to missing initialization in code, far before any program gets started

Great question; this is an area of DOSBox that I'm unfamiliar with. My guess is that this is some common DOS-compatible/compliant initialization routine(s) - be it BIOS/ROM/or initial DOS instructions that get loaded into the emulator and "executed" just like any other program.

**Comment by LowLevelMahn** [comment]
> > why is dosbox own init code accessing ports that never can work, due to missing initialization in code, far before any program gets started
> 
> Great question; this is an area of DOSBox that I'm unfamiliar with. My guess is that this is some common DOS-compatible/compliant initialization routine(s) - be it BIOS/ROM/or initial DOS instructions that get loaded into the emulator and "executed" just like any other program.

No its in the Bios class ctor in pure C++

**Comment by kcgen** [comment]
Thanks for finding that @LowLevelMahn -- Ok to close this?

**Comment by LowLevelMahn** [comment]
> Thanks for finding that @LowLevelMahn -- Ok to close this?

Already found and posted that 4 days ago :)

Question is still there: why is dosbox doing stuff in its own initialization that could never work (according to my, maybe wrong analysis) 
adding a LPT_STILL_NOT_SUPPORTED define could flag that part of the code better

**Comment by kcgen** [comment]
Because it likely mimicks original startup behavior. 
TSRs can provide software-based port handling, so perhaps a user has some printer driver that expects to be pinged on bootup. 

Perhaps this exact case is moot and without consequence (if we disabled it), but if it matches original behavior then I see no harm here. 

Afterall, there are some games that let the user print stuff, so an emulated printer submodule would be pinged on startup without someone having to figure out the BIOS details (imagine if the DOSBox BIOS author opted to not write that printer call because they didn't have a printer module at the time).

**Comment by LowLevelMahn** [comment]
ok - so its just code that do nothing (by now) but if we get someday is LPT support available at that stage if will just to the right thing
