### ISSUE TITLE
DualShock 4 custom LED settings are discarded when Dosbox Staging is launched

### ISSUE THREAD

**Issue by maxigaz** [dosbox-staging/dosbox-staging#1248]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### What Operating System are you using?

Linux x86_64

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

By default, the DualShock 4's LED is fairly bright and drains the battery rather quickly, so I have its brightness lowered to the minimum. When Dosbox Staging is launched, my custom LED settings are discarded.

### Steps to reproduce the behaviour.

Explain how to reproduce

1. Connect the DualShock 4 via Bluetooth.
2. Set the LED colour/brightness (see below for more details).
3. Run `dosbox-staging` with an empty config file.
4. The LED colour/brightness values of the controller are reset to their original values.

---

Setting the LED: To my knowledge, the easiest way of doing this under Linux is either through Steam or a bash script I found on [StackExchange Gaming](https://gaming.stackexchange.com/questions/336934/how-to-set-default-color-and-brightness-of-leds-of-the-dualshock-4-controller-on/336936#336936).

I prefer using the latter, so I have the script set up to be applied automatically at system startup. (Calling the script manually also works.) I followed the instructions written on the website closely, with the only difference being that I use the colour `000001`, which is the hexadecimal value for dark blue.

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by kcgen** [comment]
@maxigaz -- thanks for the report, and sorry for the delay. I believe our of of most of us, you probably have one of the most advanced/modern controllers out there. Will add this to the 0.78 queue!

**Comment by maxigaz** [comment]
No problem. Let me know if you need any help with testing.

**Comment by maxigaz** [comment]
I can still reproduce it in v0.78.0.

**Comment by kcgen** [comment]
@maxigaz , yes - this unfortunately wasn't implemented.

Can you try building branch `kc/joystick-led-1`?

This feature is conditionally enabled only when building with SDL version 2.0.14, so you will need to check for that first. If you're on Ubuntu / Debian / Retropie / Raspbian, you can run: `dpkg --list libsdl2-dev:amd64` and look for: 

``` text
||/ Name              Version        Architecture Description
+++-=================-==============-============-=====================
ii  libsdl2-dev:amd64 2.0.14+dfsg2-3 amd64        Simple DirectMedia Layer development files
```

Our CI systems build binaries target the earliest in-support OS versions, and therefore the Linux release binaries will not be at 2.0.14 for some years still - so the only way to get this (on Linux) is to build your own binary.

Windows and macOS users will get it out of the box though, as their package managers both are running SDL 2.0.15+.

**Comment by maxigaz** [comment]
Thank you for looking into this! I've just tried that branch and here's what I've noticed:

- When DOSBox Staging is launched, the LED colour turns green even if it has been set to blue.
- When I exit DOSBox Staging, the LED turns off completely. This makes it hard to tell if the controller is powered on or not.

(This is on Manjaro Linux with SDL 2.0.18.)

**Comment by kcgen** [comment]
That's all expected behaviour, thanks for testing it @maxigaz. 

SDL doesn't let us get the color state of the controller - we can only set colors.

I followed the international standard for illuminated indicators, as applied to industrial equipment.  Industrial equipment needs to be usable by workers world-wide, so I figured it would be a good starting point.

Red means a fault occurred
 - we don't use.

Orange means a marginal state
 - we set this during the joystick setup phase before knowing if we're going to use the controller or not
 
Green means on and active
 - we set this on the joystick that's picked for active use.
 - if the LED is green then the joystick is "live" and can be used or mapped.

We shut off the LED when closing access to the controller, similar to turning the lights off when not in a room (or turning a phone off when not in use). 

Most battery powered controllers should? enter a standby state when all of their features (buttons/pads/sticks/rumblers/LEDs) are inactive.  I can't see a scenario where _turning on_ the LED after quitting is a good thing (I can already see future tickets telling me that someone quit Staging and then their joystick's battery drained because we turned the LED on when exiting). 

You even mentioned this too: _"By default, the DualShock 4's LED is fairly bright and drains the battery rather quickly"_

Given you're on Linux, I would suggest using a shell alias or script to set the LED color after a program quits.

**Comment by GranMinigun** [comment]
How other SDL2-based programs and games behave? If they discard your settings as well, then you might want to open a ticket on SDL2's bugtracker.

**Comment by maxigaz** [comment]
@GranMinigun I've just tried it with DevilutionX and I get the same behaviour, indeed. Sorry for not checking sooner.

@kcgen Thank you for the detailed explanation! Here are my thoughts (in case they are still relevant):

> SDL doesn't let us get the color state of the controller - we can only set colours.

I see. Well, in that case, I suppose either green or blue is fine as long as the brightness level is retained (or reapplied in this case).

However, I disagree with the idea of turning the LED off completely on quit. I can imagine a situation when I leave the controller on after playing with DOSBox Staging (because, for example, I suddenly have to leave the room for a few minutes) and later not notice that the controller is still connected through Bluetooth and (ironically) draining battery. In other words, the LED indicates not whether a particular piece of software is using the DualShock 4 at the moment but whether it's connected to the computer through Bluetooth or a USB cable or not.

Having said that, I only have experience with the DualShock 4 and the XBox 360 Controller, so I honestly don't know how other wireless gamepads work.

> I can't see a scenario where turning on the LED after quitting is a good thing (I can already see future tickets telling me that Staging drained their their joystick's battery).

Are there any gamepads whose LEDs are *off* by default, even when powered on, and then you can turn them on manually? If there are any, then I can see your point.

> Given you're on Linux, I would suggest using a shell alias or script to set your desired LED color after Staging quits.

Something like that has actually crossed my mind, but running such a script would require root priviledges every time.

**Comment by kcgen** [comment]
Good call @GranMinigun; thanks for passing this SDL @maxigaz.

Good device power management will wait for user demand to cease, enter an idle countdown, and then switch to standby mode.  Like vibration, we know the LED itself is part of how PS4 games interact with the user to indicate team affiliation, role changes, etc.

So when I see that, it tells me the LED is part of the "active duty" that signals (along with vibration and polling) that the controller should stay awake.  On the flip side: if all of the active-duty demands stop, that's the software telling the controller it's safe to start its idle countdown.

... but apparently, Sony has decided to keep the LED on all the time (from the documents I've read)? This has angered users enough that some have physically modified their controllers to permanently cut power to the LED - and they've more than doubled their battery lifespans:

![2022-01-21_13-09](https://user-images.githubusercontent.com/1557255/150605258-ff295127-9dbc-475c-9942-26a5ff66ff5c.png)

https://www.neogaf.com/threads/dualshock-4-leds-effect-on-battery-life-test.723148/

My F710 has an LED, but it's more of a status indicator- and it automatically goes dark when in standby, which the controller will automatically do after some idle period. (the batteries can last over a year, and it doesn't even have a power-off switch, standby is good enough).
