### ISSUE TITLE
Batch files handling: sound setup freeze

### ISSUE THREAD

**Issue by nemo93** [dosbox-staging/dosbox-staging#1249]
### Relevant hardware info

Pi4, no overclock, fKMS (fake mode, default), stock kernel

### A clear description of the bug

I'm facing an issue on exiting some sound setup during game installation process. Complete freeze (`CTRL+F9` will not work) no segfault and therefore no log. I didn't face such issue in the past (say over the past 6 months perhaps?). 

Scenario is always the same: mount a CD image, run the setup, have it to copy files to hdd, go to sound utility, select card and on exit (Done or Quit etc) Staging will freeze. 

I thought it was happening only with the Miles Sound System but it's not true. I got a freeze with other sound systems too. Note that it happens only during the setup phase, should I run `setsound.exe` or equivalent afterwards then no freeze. This might also occur at the very beginning of sound setup - especially true with Miles this time. When it happens I can just see the typical grey background and none of the blue boxes listing the card and options.

Other games impacted as well (crash/freeze during install):
* Mechwarrior 2: Mercenaries

**Micro Machines 2 Special Edition** will always freeze at the end of the install process:
1. mount CD image as D drive
2. run `INSTALL.BAT`
3. follow the process and let it copy files
4. sound setup will show up
5. configure card (eg. SB16 w/ proper DMA/IRQ)
6. on exit => freeze

### Your configuration

https://gist.github.com/nemo93/e1e8f020e75c87c0b1e3c6a17581225b

### Provide a Log

https://gist.github.com/nemo93/222453313a4cb85a7a7657969c524aec

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by GranMinigun** [comment]
Referenced issue is unrelated.

Confirmed on x86_64 and ARM Linux, and on ARM64 macOS. The problem seems to be in the way batch files are currently handled. 0.77.x is unaffected. Bisected regression to commits 67dee0b93a3ff1d0e967c045b8697cf0e21ab626 and f5fa20bdc142ca6ac1eee2cf74ac38a113279526.

**Comment by kcgen** [comment]
Thanks for the report @nemo93 and bisection @GranMinigun!
Fix inbound shortly.
