### ISSUE TITLE
Fast-forward doesn't affect audio

### ISSUE THREAD

**Issue by GranMinigun** [dosbox-staging/dosbox-staging#1251]
Fast-forwarding emulation (by holding Alt+F12 by default) doesn't speed-up audio, which leads to desync. The only way to sync video and audio outputs back is to restart DOSBox. Introduced by #1184.

Either speeding audio up (as it was in old implementation) or muting it during fast-forward as solutions are good.

**Comment by arrowgent** [comment]
tested with `0.77.1` on `linux x86_64`

with GSP, a midi player
and MBF, a doom port
and BLOOD, just vanilla blood

sound speeds up fine
audio returns to normal fine
no buffering issues or echoes etc



**some more details on your hardware?**

**Comment by GranMinigun** [comment]
Referenced pull request isn't in 0.77.x, only on master branch. So, the bug is only present there. The team is well aware of it, and @kklobe mentioned that he might be able to fix it.

**Comment by kcgen** [comment]
@arrowgent , thanks for the running those tests against 0.77.1 👍 

This will be solved with the speedup issue, as they're linked to how we deal with "overage" of samples in the new low-latency push audio mechanism (latest sources).

**Comment by GranMinigun** [comment]
Closing, as the new API was reverted.
