### ISSUE TITLE
Hang on close when some ALSA conf files aren't present

### ISSUE THREAD

**Issue by pellcorp** [dosbox-staging/dosbox-staging#1252]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Different version than latest?

0.77.1

### What Operating System are you using?

Linux x86_64

### Whats your question and how can we help?

Ubuntu 21.04 Desktop

Im not sure how to report this, but I was playing around with setting up alsa for dosbox, and I had backed up the /usr/share/alsa/alsa.conf and deleted it.

Then dosbox would start but it would not exit, without being killed  forcefully via the kill command.

As soon as I restored the alsa.conf file all worked again.

But the thing that really bugged me, is there were no errors from dosbox, it just did not exit, almost like it silently crashed.

Would it be possible to add some debugging around this, and can anyone else reproduce it?

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by arrowgent** [comment]
no issue here... ubuntu 18.04

note, my version of dosbox is 0.78.x from a WxH branch, but it was essentially 0.77.0 when compiled

```
/usr/share/alsa $ sudo mv alsa.conf alsa.alsa
[sudo] password for catbox:      
/usr/share/alsa $ dosbox-st
dosbox-staging version 0.78.0
---
CONFIG: Loading primary file /home/catbox/.config/dosbox/dosbox-staging.conf
CONFIG: Deprecated option 'oplrate'
CONFIG: oplrate is deprecated. The OPL waveform is now sampled
        at the mixer's playback rate to avoid resampling.
MAIN: Sized window on display-1 to 1400x1050 with nearest-neighbour scaling and stretched pixels
OPENGL: Pixel buffer object extension: available
SDL: Mouse will be captured after clicking and middle-clicks will be sent to the game.
Memory sizes above 31 MB are NOT recommended.
Stick with the default values unless you are absolutely certain.
MEMORY: Base address: 0x7f94ec713010
MEMORY: Using 8192 DOS memory pages (32 MiB)
MIXER: Negotiated 2-channel 49716-Hz audio in 1024-frame blocks
MIXER: FSYNTH channel operating at 49716 Hz without resampling
MIDI: Using SoundFont '/usr/share/sounds/sf2/FluidR3_GM.sf2'
MIDI: Opened device: fluidsynth
MIXER: FM channel operating at 49716 Hz without resampling
MIXER: SB channel operating at 22050 Hz and upsampling to the output rate
MIXER: SPKR channel operating at 48000 Hz and upsampling to the output rate
MAPPER: Loaded 146 key bindings from /home/catbox/.config/dosbox/mapper-v2.map
MOUNT: Path '/home/catbox/Games/dosbox' found
MAIN: Source resolution changed to 640x400, (PAR 1.20)
FSYNTH: Peak amplitude reached 100% of max
/usr/share/alsa $ sudo mv alsa.alsa alsa.conf
```
exited dosbox no issue

**Comment by kcgen** [comment]
Thanks for this report @pellcorp and trying to repro this @arrowgent.

My system (Ubuntu 21.04) had a couple more `alsa.conf(.*)` files, and was able to reproduce it after doing the following:

```shell
sudo mv /usr/share/alsa/alsa.conf /usr/share/alsa/alsa.conf-bak
sudo mv /usr/share/alsa/alsa.conf.d /usr/share/alsa/alsa.conf.d-bak
sudo mv /etc/alsa/conf.d /etc/alsa/conf.d-bak
```

Eventually I boiled down the problem to purely SDL2:

```c++
#include <stdio.h>
#include <stdlib.h>

#include <SDL2/SDL.h>

int main(int argc, char** argv) {

    SDL_Log("Initializing SDL");
    if (SDL_Init(SDL_INIT_EVERYTHING) != 0) {
        fprintf(stderr, "Failed to initialize SDL:  %s\n", SDL_GetError());
        return 1;
    }

    SDL_Log("Registering SDL_Quit() to run at-exit");
    atexit(SDL_Quit);

    SDL_AudioSpec want;
    SDL_zero(want);

    want.freq = 48000;
    want.format = AUDIO_S16;
    want.channels = 2;
    want.samples = 1024;
    want.callback = NULL;

    SDL_AudioSpec have;

    SDL_Log("Opening the audio device");
    SDL_AudioDeviceID dev = SDL_OpenAudioDevice(
        NULL, 0, &want, &have, SDL_AUDIO_ALLOW_FORMAT_CHANGE);

    // Failure check
    if (dev == 0) {
        SDL_Log("Failed to open the audio device: %s", SDL_GetError());
        return 1;
    }

    // Report format changes
    if (have.format != want.format) {
            SDL_Log("Received a different audio format (OK!)");
    }

    SDL_Log("Unpausing the audio device");
    SDL_PauseAudioDevice(dev, 0);

    SDL_Log("Playing 3 seconds of silence");
    SDL_Delay(3000);

    SDL_Log("Pausing the audio device");
    SDL_PauseAudioDevice(dev, 1);

    SDL_Log("Closing the audio device");
    SDL_CloseAudioDevice(dev);

    SDL_Log("Exiting");
    return 0;
}
```

Save that to `hangtest.c`, then: `g++ -g test_sdl.c -lSDL2 -o hangtest`
![2021-09-11_17-49](https://user-images.githubusercontent.com/1557255/132967106-f5c6f06c-46b8-4c17-8528-7476973826a4.png)

(tagging with External, and will find time to submit this to SDL.)

**Comment by arrowgent** [comment]
SDL fixes!!!

good find that.

**Comment by kcgen** [comment]
Added to SDL's GitHub tracker (see link above)

**Comment by nemo93** [comment]
Closing that one for now as external to Staging. @kcgen did report to SDL as well after narrowing the issue down. Thanks!

**Comment by kcgen** [comment]
We're tracking it with the external tag (and it's not solved yet), so prefer we keep it open.

**Comment by pellcorp** [comment]
Wow, impressive thank you.

**Comment by Burrito78** [comment]
Ticket is closed as completed on SDL GitHub, closing here too.
