### ISSUE TITLE
Sporadic digital audio speed-ups

### ISSUE THREAD

**Issue by GranMinigun** [dosbox-staging/dosbox-staging#1257]
Sometimes games might play audio at a faster rate, with noticeable distortion. This behaviour seems to persist until the next DSP reset (i.e., restart the game or run another sound test), although rarely multiple resets needed. MIDI is unaffected.

Introduced by #1184. Confirmed to happen on Linux and Windows. Games that are known to have caught the bug at least once:
- Metaltech: Battledrome;
- Doom;
- Duke Nukem 3D (reported by @MasterO2).

Most reliable way to reproduce so far:
1) Launch Metaltech: Battledrome's sound setup utility (`SOUNDSET.EXE`);
2) Configure digital sound driver as desired (Sound Blaster 16 will do);
3) Repeatedly run audio test.

Being lucky enough, one might hit it on the first run.

Examples of proper output and the bug:

https://user-images.githubusercontent.com/11149380/133043448-47f409d8-da15-486b-b868-00514efcbbeb.mp4

https://user-images.githubusercontent.com/11149380/133043459-360e1abe-fdad-4167-8ceb-42bcd9a9ccc5.mp4

**Comment by nemo93** [comment]
Confirmed on Pi4 as well. Extremely difficult to reproduce on-demand, very random issue. Usually occurs during sound setup while testing "Digital Sound card" for instance. For the ref I've faced it earlier this morning while configuring Xwing (CD version) soundcard. On testing the digital sound effect, speedup occured... once. On second and third tries no problem.

**Comment by nemo93** [comment]
I realized there were also video speedups occuring only during FMV cutscenes/intro. Again very difficult to replicate on-demand but games with an intro FMV (eg. Firestorm Thunderhawk 2 or Tomb Raider) are good candidates with higher chances to trigger the bug.

On the audio speedup side, you have 2 ways to easily replicate:
1. from @smileymattj: if you start and close windows 3.11.  You have 2 chances for it to happen.  And win 3.11 open/close doesn't take too long to do.  It should happen at between 3-5 times of opening win.com on either the startup or close sound.  Should take less than 2 mins to test.
2. Terminal Velocity (1.2): Go to `Options` > `Sound` and from there change the "freq" and "playback" values. You'll hit the "speedup" issue in a few seconds. Also to confirm the log msgs: `Suppressed initial 4-byte 8-bit PCM transfer` and `Suppressed initial 2-byte 8-bit PCM transfer` when the bug occurs.

I just hope those audio and video "speedups" are related and originate from the same bug.
