### ISSUE TITLE
Add DEBUG stub or bundle FreeDOS debug

### ISSUE THREAD

**Issue by kcgen** [dosbox-staging/dosbox-staging#1258]
from @Burrito78:

I have come across one real-world example where a missing DOS program prevents the correct installation of a game: Tie Fighter floppy version needs debug.

In that case I'd suggest we either need:

1. A little debug program shipped inside Dosbox-Staging that gets the job done regarding Tie Fighter.
2. A debug stub that outputs "This program needs debug to work properly! Get it here: ..." and pause the screen. Could be that this message isn't seen however because it would be executed in the background without output maybe. Would need to test that.

**Comment by Jkapp76** [comment]
Nice find.

**Comment by Burrito78** [comment]
https://github.com/FDOS/debug
https://github.com/Baron-von-Riedesel/DOS-debug
Dosbox-X's debug.com

Would any of these work from a programming and license perspective?

**Comment by nemo93** [comment]
Following games do currently require external programs to install properly:

`XCOPY.EXE` (works fine with FreeDOS [version](https://www.ibiblio.org/pub/micro/pc-stuff/freedos/files/distributions/1.2/repos/pkg-html/xcopy.html)):
1. Flashback CD (and perhaps the disks version)
2. GTA "London" (base GTA is fine)

`for` loop:
1. Colonization CD (Europe release with English/French languages)
from `HDINSTAL.BAT`:
```
cd MPS.CD
for %%L in (%1 c: d: e: f: g: h: i: j: k: l: m: n: o: p:) do if exist %%L\mps.cd\colinsth.bat %%L\mps.cd\colinsth.bat
```

**Comment by Burrito78** [comment]
This is the version of Tie Fighter i am talking about.
https://archive.org/details/star-wars-tie-fighter-german-floppy-ibm-pc

It's the german release and i don't know if other versions also need 'debug' to install. 'debug' is used here to patch a mission file. 

This is in the fix.bat that the installer is calling:

`debug mission\b2m4gw.tie < fix.key > fix.out`

**Comment by kcgen** [comment]
Closing as we now recommend using a utility drive populated using the FreeDOS package manager.

**Comment by Burrito78** [comment]
The problem with this is, that the install finishes without patching the mission file this way. And the user never knows that.

Wouldn't a stub debug.com that outputs "This program called "Debug" but its not included with DOSBox Staging out of the box. Use the FreeDOS package manager from here: xxx to install it." and waiting for a keypress be a better idea?

**Comment by LowLevelMahn** [comment]
Should be easy to do, just a derive from the program class, but the problem is that debug is also the command to invoke the internal dosbox debugger (when enabled for the build)

**Comment by kcgen** [comment]
PR added - please fee free to expand/improve the wording!
