### ISSUE TITLE
[BUG] mesa warnings on Wayland

### ISSUE THREAD

**Issue by rderooy** [dosbox-staging/dosbox-staging#1273]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Different version than latest?

0.78.0-alpha-413-g0dcf59e8+

### What Operating System are you using?

Linux x86_64

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Start dosbox-staging in Wayland mode and press Ctrl-F1 for the mapper editor and the following warnings are printed on the console:
```
mesa: for the --simplifycfg-sink-common option: may only occur zero or one times!
mesa: for the --global-isel-abort option: may only occur zero or one times!
mesa: for the --amdgpu-atomic-optimizations option: may only occur zero or one times!
mesa: for the --structurizecfg-skip-uniform-regions option: may only occur zero or one times!
```
The same warnings are printed again when closing the mapper editor.

### Steps to reproduce the behaviour.

Explain how to reproduce
1. SDL_VIDEODRIVER=wayland dosbox-staging
2. Press CTRL-F1
3. Look at the console output

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by kcgen** [comment]
Thanks @rderooy. 

Here's what I get:

![2021-09-18_09-39](https://user-images.githubusercontent.com/1557255/133896013-cc949801-5be0-41c1-a4c6-e45a490c7a15.png)

My guess is it's some interaction between SDL2, MESA, and Wayland? 

It's mentioned here too: https://lists.freedesktop.org/archives/mesa-dev/2017-November/175721.html

I'm running a pretty recent version of MESA and SDL2 (both only a couple days old):

![2021-09-18_09-43](https://user-images.githubusercontent.com/1557255/133896090-4a707b7a-4ee8-4f77-8ec7-2ba910de66d8.png)
![2021-09-18_09-39](https://user-images.githubusercontent.com/1557255/133896093-cf8ab837-6b63-4c55-8d19-24be90cf5eec.png)

Hopefully the fix is just winding its way through the stable repo process.

**Comment by kcgen** [comment]
@rderooy - I'm going to close this, only because it appears to be fixed in the latest libraries as well as being out of our control and benign. 

Good news is it will be in the ticket history for search-matches, should anyone else hit it.  Thanks for this heads up @rderooy !

**Comment by rderooy** [comment]
This is on Fedora 34. My wayland is actually newer than yours, but indeed your Mesa is newer.
```
$ rpm -qa|grep "mesa\|wayland\|SDL2"|sort
gnome-session-wayland-session-40.1.1-1.fc34.x86_64
libwayland-client-1.19.0-1.fc34.i686
libwayland-client-1.19.0-1.fc34.x86_64
libwayland-cursor-1.19.0-1.fc34.i686
libwayland-cursor-1.19.0-1.fc34.x86_64
libwayland-egl-1.19.0-1.fc34.i686
libwayland-egl-1.19.0-1.fc34.x86_64
libwayland-server-1.19.0-1.fc34.i686
libwayland-server-1.19.0-1.fc34.x86_64
mesa-dri-drivers-21.1.8-1.fc34.i686
mesa-dri-drivers-21.1.8-1.fc34.x86_64
mesa-filesystem-21.1.8-1.fc34.i686
mesa-filesystem-21.1.8-1.fc34.x86_64
mesa-libEGL-21.1.8-1.fc34.i686
mesa-libEGL-21.1.8-1.fc34.x86_64
mesa-libEGL-devel-21.1.8-1.fc34.x86_64
mesa-libgbm-21.1.8-1.fc34.i686
mesa-libgbm-21.1.8-1.fc34.x86_64
mesa-libGL-21.1.8-1.fc34.i686
mesa-libGL-21.1.8-1.fc34.x86_64
mesa-libglapi-21.1.8-1.fc34.i686
mesa-libglapi-21.1.8-1.fc34.x86_64
mesa-libGLU-9.0.1-4.fc34.x86_64
mesa-libOSMesa-21.1.8-1.fc34.i686
mesa-libOSMesa-21.1.8-1.fc34.x86_64
mesa-libxatracker-21.1.8-1.fc34.x86_64
mesa-vulkan-drivers-21.1.8-1.fc34.i686
mesa-vulkan-drivers-21.1.8-1.fc34.x86_64
qt5-qtwayland-5.15.2-11.fc34.x86_64
SDL2-2.0.16-2.fc34.i686
SDL2-2.0.16-2.fc34.x86_64
SDL2-devel-2.0.16-2.fc34.x86_64
SDL2_net-2.0.1-13.fc34.x86_64
SDL2_net-devel-2.0.1-13.fc34.x86_64
SDL2-static-2.0.16-2.fc34.x86_64
xorg-x11-server-Xwayland-21.1.2-1.fc34.x86_64
```

**Comment by kcgen** [comment]
Interesting.. maybe the issue/incompatibility lies inside Mesa given your comparison. 
We'll keep an eye out - curious if/when this eventually disappears on your side.
