### ISSUE TITLE
[BUG] Joystick support issues with all machines 

### ISSUE THREAD

**Issue by Jkapp76** [dosbox-staging/dosbox-staging#1274]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Different version than latest?

I have also tried the two latest alpha builds, latest is 410

### What Operating System are you using?

Windows 10

### Relevant hardware info

_Geforce ti video card.

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

I just noticed Joystick support isn't working.
I loaded Jumpman and also BC's Quest for Tires on PCJr and CGA. The joystick does not work. I did get jumpman to run to the right and even jump with some struggling. And somehow got BC to jump one time. But it seems no good.
I tried these two games with the same joystick settings and machine (both PCJr and CGA) on DOSBox ECE and both worked with identical settings. DOSBox Optionals had some issues too I notice.
I also tried Space Quest 2 with same results. No go on Staging, works fine on ECE.

Same results with svga_s3 machine. Works on ECE, no good on Staging.

I used the key-mapper to assign key strokes to the joystick and the joystick does nothing mapped.

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Attach a gamepad or joystick
2. Load a game, like below the root
3. Choose Joystick in-game and try. It has some movement, but it's not good. I've experimented with timed, circular, and the deadzone options with no luck. DOSBox ECE seems to work perfect even with these options modified.

### Your configuration

```ini
I am using Opengl
```

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by Jkapp76** [comment]
I'm using no mapper file.
I tried a fresh install with default conf. Same issue.
I loaded Champ MS Pacem because Champ has a nice joystick calibration. When I press LEFT the the x goes to the top left corner. When I press RIGHT the x goes to the bottom right corner. Pressing UP or DOWN does nothing.

This is also what other game seem to do. On Jumpman pressing LEFT makes him go up and left.

I get the same results no matter what I adjust. I have this issue with 77, and the two 78 alpha builds. But not with other DOSBox builds. Except DOSBox Optionals, which does the exact same thing.

I've tested other gamepads too, no better luck.

**Comment by Jkapp76** [comment]
[dosbox-staging-v0.78.0-410.zip](https://github.com/dosbox-staging/dosbox-staging/files/7190848/dosbox-staging-v0.78.0-410.zip)

Okay. Here we go.

I made a fresh install and only edited the conf file enough to mount the game folder and launcg the game.
Here is my setup and one game that doesn't work for me.
I have now tried this same copy of staging on multiple pc's with the same results.

**Comment by kcgen** [comment]
Thanks @Jkapp76 - I've reproduced the issue with a Hori Pokken Tournament DX joystick, recognized on the console as:
``` text
2021-09-18 18:57:12.445 | MAPPER: Initialized Nintendo Switch Pro Controller with 6 axes, 16 buttons, and 0 hat(s)
```

I will move my Logitech F310 from my Linux PC to Windows 10 machine and try that.

**Comment by Jkapp76** [comment]
DOSBox Optionals seems to have the same issue, but none of the other builds I've tried (and I've got them all) seem to do this for me.

**Comment by kcgen** [comment]
Some frustrating news - after plugging in the Logitech F310 and rebooting, the joystick is recognized, completes perfect calibration in Ms Pac-Em, per the steps you've described and using you archive and conf as-is. 

I took an Obs video:

[2021-09-18 19-25-45.zip](https://github.com/dosbox-staging/dosbox-staging/files/7190906/2021-09-18.19-25-45.zip)

The F310 has a "mode" button on it that lets you toggle from the D-pad to the analog stick.  I used it with the mode-on, so I could use the D pad.  However, I also confirmed that the analog stick also works (when mode is off).

I tracked down some joystick testing tools:

[joyutils.zip](https://github.com/dosbox-staging/dosbox-staging/files/7190913/joyutils.zip)

One of the tools shows that I could even use the right-hand analog stick on the F310 as the second controller. 

Another strange thing is that on Windows 10, the Logitech F310 is recognized as an XBox controller. I'm not sure if this is Windows doing this or SDL2 ... but on Linux, it's recognized perfectly.  Here's what SDL2 calls it:

``` text
2021-09-18 19:57:10.925 | MAPPER: Initialized Controller (XBOX 360 For Windows) with 6 axes, 11 buttons, and 1 hat(s)
```

**Comment by kcgen** [comment]
Update: figured out the XBOX thing - the controller has a small switch on its underside that toggles the entire device from X-Input mode (XBox-mode) to normal 'Logitech' mode.  I must have accidentally toggled that carrying it around.

I switched it over to normal Logitech-mode, and it's now correctly recognized:

``` text
MAPPER: Initialized Logitech Dual Action with 4 axes, 12 buttons, and 1 hat(s)
```

In this mode, both the D-pad and analog stick still continue to work in Ms Pac-Em just like before.

**Comment by Jkapp76** [comment]
I found an XBox 1 controller and I have the same issue. No go yet.

**Comment by Jkapp76** [comment]
I just noticed if I set the game to use keyboard and map the keystrokes to gamepad buttons the game still does the same thing. Jumpman for example can only run in the diagonal corners. It's still no good.

**Comment by kcgen** [comment]
> I found an XBox 1 controller and I have the same issue. No go yet.
> 
> *I grabbed my big Arcade stick console and plugged it in. same issue. can only get the corners.

I'm out of ideas, and I can try adding some debug code tomorrow.

I would expect at least the Xbox one controller to work; give my Logitech worked in it's own Xbox compatibility mode. 

I know this is far fetched, but maybe try unplugging all usb devices except for just your keyboard, mouse, and Xbox controller: then reboot, and see if that changes anything? (Just trying to rule out a machine issue).

**Comment by Jkapp76** [comment]
I tested the joyutils. Very nice utilities!
Same results though. up and down do nothing, left and right go to the upper left and lower right corners.

I sent away for a modern, yet old-school joystick from ebay called a "Hyperkin Trooper 2". It looks very similar to the old atari 2600 joystick but has 6 buttons and usb plug. This is my reason for trying joystick support and getting ready for it to arrive. 

I wonder why I have no issue on DOSBox ECE, or X? I hope we can get this worked out. I'd like Staging to be my only DOSBox version.

**Comment by Jkapp76** [comment]
Okay. I was wrong about DOSBox-X working for me. It seems only DOSBox ECE works. 
ECE do advertise using a different Joystick patch. Maybe this is what lets it work for me. 

I do find it very strange that this happens on both of my PC's I'm not sure if these computers have anything in common other than both being gaming PC's with Nvidia cards?

**Comment by Jkapp76** [comment]
My first successful joystick attempt.
I found this old joystick I paid 3 bucks for new several years ago. It works perfectly on all Staging versions. I can rule out lots of things now. Staging must not like many joysticks? ECE has a different joystick patch that seems to accept all of my sticks if that information helps.


![cheap-js](https://user-images.githubusercontent.com/89743985/133939642-f4e9c82a-5fab-4009-a4cf-d4e813656ac5.jpg)

**Comment by kcgen** [comment]
@Jkapp76 - glad you're up and running (a bit anyway!)
I forgot to mention that Optionals and Staging both use SDL 2.0.x, where as ECE uses the prior SDL 1.2.x, as does DOSBox (proper, such as 0.74.3 and SVN).

This appears to be an unfortunate regression in the legacy 'joystick' handling area.  In SDL2 parlance, there are 'joysticks' and 'game controllers'.

Right now, Staging and Optionals are still using the original 'joystick' API from SDL2 -- however we want to add support for game controllers, as it will allow for more consistent mapping of the d-pad, analog-stick, and four (or more) buttons.

**Comment by kcgen** [comment]
I've added a tiny bit of controller detection code in this branch:
 - https://github.com/dosbox-staging/dosbox-staging/actions/runs/1251413773 (build in progress)

The zip file contains a expanded controller database file, 'gamecontrollerdb.txt', from this project:  https://github.com/gabomdq/SDL_GameControllerDB

You can unzip and run it, and it will report if your controller is indeed part of those in the supported database:

``` text
2021-09-19 13:05:11.698 | SDL: Loaded 153 controller mappings from database 'gamecontrollerdb.txt'
2021-09-19 13:05:11.751 | JOYSTICK: Initialized HORI POKKEN CONTROLLER with 4 axes, 13 buttons, and 1 hat(s)
2021-09-19 13:05:11.751 | CONTROLLER: The Hori Pokken Tournament DX Pro Pad game controller is supported
```

Here you can see my  Hori Pokken is first detect using SDL2 using the older Joystick API - and then it's detected using the controller API (and the name printed is nicer too, from the database).

I'm curious what it will say for all of your joysticks/controllers!

**Comment by Jkapp76** [comment]
So far this new build immediately exits right after launch.

**Comment by kcgen** [comment]
> So far this new build immediately exits right after launch.

Thanks for trying; will work on this more in the coming days.

**Comment by Jkapp76** [comment]
I loaded this build on my HP desktop PC. It works. So I used my Gamepad that wouldn't calibrate to test.

The results are the same. Left and Right just go to the corners, up and down do nothing. 

![460_a](https://user-images.githubusercontent.com/89743985/134041994-4b537049-ae73-4650-a9a5-ebd8b88c46f1.jpg)

**Comment by kcgen** [comment]
Thank @Jkapp76  - there are no functional changes; only the addition of game-controller detection. 
In this case, we see SDL2's joystick API only sees your device as a 'USB Gamepad' (sounds pretty generic).
But it's idenitified as a 'Retro Controller' by the game-controller datatabase - which bodes well for the controller being useful when we eventually make use of SDL2 'controller' API.

**Comment by kcgen** [comment]
This issue is with SDL2 not supporting the same suite of joysticks SDL1 supports. 
Moving to SDL2's controller API is a big ticket item we want to undertake. Until then, we are at the mercy of SDL2's joystick support and therefore will close this for now.

**Comment by Jkapp76** [comment]
![retro_stik](https://user-images.githubusercontent.com/89743985/134784850-762f1140-7d15-45a0-b2c7-453f1221abbf.jpg)

I just got my new joystick for dosbox in the mail. I'm happy to say it works in all versions of DOSBox.

I'm still interested in testing the SDL2 support for more joysticks. When you're ready for that, tag me.

**Comment by kcgen** [comment]
Thanks for sharing that; really nice setup!
Will keep you posted when we tackle the new controller API in earnest.  It's likely year(s) away, but time tends to fly!

**Comment by Torinde** [comment]
> Moving to SDL2's controller API is a big ticket item we want to undertake. Until then, we are at the mercy of SDL2's joystick support and therefore will close this for now.

Is that API adopted now?

@Grounded0, if the API is not yet adopted and/or the problem still persists, then this ticket should be changed to "not planned" or reopened and added to #3075?

**Comment by johnnovak** [comment]
> > Moving to SDL2's controller API is a big ticket item we want to undertake. Until then, we are at the mercy of SDL2's joystick support and therefore will close this for now.
> 
> Is that API adopted now?
> 
> [@Grounded0](https://github.com/Grounded0), if the API is not yet adopted and/or the problem still persists, then this ticket should be changed to "not planned" or reopened and added to [#3075](https://github.com/dosbox-staging/dosbox-staging/issues/3075)?

It's not adopted.

This is a very old ticket, probably the issue is gone. If the issue is still present, please open a new ticket.

**Comment by Grounded0** [comment]
@Torinde 

If you open a ticket for adopting SDL2's controller API, I will add it to the mapper megaticket. These things get lost in the noise unless there's a ticket specifically for it.

**Comment by johnnovak** [comment]
> [@Torinde](https://github.com/Torinde)
> 
> If you open a ticket for adopting SDL2's controller API, I will add it to the mapper megaticket. These things get lost in the noise unless there's a ticket specifically for it.

Not really necessary because we know we need to start using the controller API and SDL's ControllerDB anyway. That's the best way for new SDL code that deals with any controllers, it's common knowledge.

Same deal for all the old weird issue tickets about controller support; the new implementation will be totally different, most old bugs and quirks will just automatically go away.
