### ISSUE TITLE
Trouble installing utilities from the FreeDOS Bonus CD

### ISSUE THREAD

**Issue by Burrito78** [dosbox-staging/dosbox-staging#1284]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### What Operating System are you using?

Mac OS

### Whats your question and how can we help?

Hi,

i tried installing debug.com from the FreeDOS Bonus CD as described here:
https://github.com/dosbox-staging/dosbox-staging/wiki/Add-Utilities

That didn't end well, i'm lost. :)

What did i do and what didn't work:

1. Trouble downloading the right file: A direct link to the download file in the Wiki would be nice as i had to look back and forth what to download exactly. Found and downloaded FD13-BonusCD.zip.

2. Couldn't locate fdimpels.exe on the CD! Had to mount the ISO on macOS to look into it. Its not on the CD! But searching for fdimples alone found this file: /packages/apps/fdimples.zip! This was the first real WTF moment right there.

3. I can't extract a ZIP in DOSBox because i have no unzip installed (thats what the CD i just mounted is for!) so i'm back on macOS to copy the fdimples.zip inside DOSBox and extract. It's another folder structure! fdimples.exe doesn't run on its own! So i place the folder structure inside DOSBox and launch fdimples.exe and it flips another error message: unable to locate package manager FDINST.

4. I close DOSBox and delete everything. 

1. Can someone point me to directions, how this would actually work?
2. Can the wiki be updated to include these directions directly?

This is pretty basic stuff i'm trying to do here. How can this be made so complicated?

Thanks for reading!

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by nemo93** [comment]
Hello @Burrito78! Thanks for reporting back. The "Utilities" section of the wiki is still rather new and it's not fully achieved yet. As I haven't tested myself `FDIMPLES` I can't provide any assistance at this stage. I just quickly saw on Discord that utilities downloaded via this packager manager can't be installed in a user-defined directory (to be confirmed). If true then this is something to be specified in the doc indeed.

About downloading the CD it's specified on the wiki that you need the BonusCD which is easily found after clicking the download button on the linked page. I can't link directly to the zip file as whenever a new version will be released the wiki will have to be as well. Which is for sure something that will be overlooked and will lead to further issue. I prefer to link to the official Freedos download page as it is today.

My actual plan - apart from testing FDIMPLES - is to add a smaller section about getting the utilities straight from [ibiblio](https://www.ibiblio.org/pub/micro/pc-stuff/freedos/files/distributions/1.2/repos/pkg-html/group-base.html). I didn't do it as of typing for the same reason as above, I'm unsure the links to ibiblio will remain consistent (apparently they are). I may have time today to update that utilities section. Feel free to recheck regularly to see if the updated page is clearer.

**Comment by kcgen** [comment]
If anyone wants to help script the downloading, extraction, launching of the FreeDOS package manager, organizating `U_Drive` content, and adding-PATH entries to the (as a cross-platform script), this help is very welcome and would have a place in the `contrib` area of the repo.  Help wanted!

**Comment by Burrito78** [comment]
The way forward would be to include XCOPY and DEBUG from FreeDOS as discussed on Discord. Closing.
