### ISSUE TITLE
can not compile dosbox-staging if slirp is set to true

### ISSUE THREAD

**Issue by legluondunet** [dosbox-staging/dosbox-staging#1286]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Hello,
I just tried to compile dosbox-staging on Linux Arch.
It compiled ok with standard options:

`meson setup     -Dbuildtype=release     -Ddefault_library=static     -Db_asneeded=true     -Dtry_static_libs=png     -Dfluidsynth:enable-floats=true     -Dfluidsynth:try-static-deps=true   build/release`

but if I add this option:  -Duse_slirp=true
compilation failed.

Thank you for your help.

### Provide a Log

```text
$ meson compile -C build/release
ninja: Entering directory `build/release'
[2/4] Compiling C++ object src/hardware/libhardware.a.p/ne2000.cpp.o
FAILED: src/hardware/libhardware.a.p/ne2000.cpp.o 
ccache c++ -Isrc/hardware/libhardware.a.p -Isrc/hardware -I../../src/hardware -I../../include -I. -I../.. -I../../submodules/loguru -I/usr/include/libpng16 -I/usr/include/SDL2 -I/usr/include/slirp -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -fdiagnostics-color=always -DNDEBUG -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wnon-virtual-dtor -Wextra -Wpedantic -std=c++17 -O3 -Weffc++ -Wextra-semi -D_REENTRANT -MD -MQ src/hardware/libhardware.a.p/ne2000.cpp.o -MF src/hardware/libhardware.a.p/ne2000.cpp.o.d -o src/hardware/libhardware.a.p/ne2000.cpp.o -c ../../src/hardware/ne2000.cpp
../../src/hardware/ne2000.cpp: In constructor ‘bx_ne2k_c::bx_ne2k_c()’:
../../src/hardware/ne2000.cpp:129:1: warning: ‘bx_ne2k_c::s’ should be initialized in the member initialization list [-Weffc++]
  129 | bx_ne2k_c::bx_ne2k_c(void)
      | ^~~~~~~~~
../../src/hardware/ne2000.cpp: At global scope:
../../src/hardware/ne2000.cpp:1390:38: error: expected identifier before ‘,’ token
 1390 | uint16_t dosbox_read(io_port_t port, , io_width_t width)
      |                                      ^
../../src/hardware/ne2000.cpp: In constructor ‘NE2K::NE2K(Section*)’:
../../src/hardware/ne2000.cpp:1492:9: warning: ‘NE2K::load_success’ should be initialized in the member initialization list [-Weffc++]
 1492 |         NE2K(Section* configuration):Module_base(configuration) {
      |         ^~~~
../../src/hardware/ne2000.cpp:1688:86: error: cannot convert ‘uint16_t(io_port_t, int, io_width_t)’ {aka ‘short unsigned int(short unsigned int, int, io_width_t)’} to ‘io_read_f’ {aka ‘std::function<unsigned int(short unsigned int, io_width_t)>’}
 1688 |                         ReadHandler8[i].Install((i + theNE2kDevice->s.base_address), dosbox_read, io_width_t::word);
      |                                                                                      ^~~~~~~~~~~
      |                                                                                      |
      |                                                                                      uint16_t(io_port_t, int, io_width_t) {aka short unsigned int(short unsigned int, int, io_width_t)}
In file included from ../../src/hardware/ne2000.cpp:37:
../../include/inout.h:82:32: note:   initializing argument 2 of ‘void IO_ReadHandleObject::Install(io_port_t, io_read_f, io_width_t, io_port_t)’
   82 |                      io_read_f handler,
      |                      ~~~~~~~~~~^~~~~~~
ninja: build stopped: subcommand failed.
```

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by GranMinigun** [comment]
Both slirp and pcap are not finished or supported, unfortunately. These options were left as development placeholders and are not intended for end-users.

**Comment by kcgen** [comment]
> if I add this option: `-Duse_slirp=true`, compilation failed.

Thanks for the report @legluondunet! We'll get that options removed.

**Comment by legluondunet** [comment]
Thank you for your quick answers, but that's not the objective of my issue. Slirp connection worked well in dosbox-staging several months ago, I even tested it with Windows 3.1 and  Windows 95/98, I compiled it on Ubuntu 20.04 with sccess. What's happened since? Why we can no more compile this feature in Dosbox (even if it is experimental)? This feature is no more plan in a future release?

**Comment by kcgen** [comment]
Sorry @legluondunet, my fault. 
I didn't realize this was useable (in some capacity) given the PR effort to include Slirp and NE2000 hasn't been completed yet. 

I will work on fixing up this existing functionality and will let you know. Following that, we can work on finishing up the NE2000 PR.

**Comment by legluondunet** [comment]
sorry, I just found I confused with dosbox-x...
https://github.com/joncampbell123/dosbox-x/issues/320

I remembered now that Jookia never finished slirp implementation in dosbox-staging.
