### ISSUE TITLE
The Way Things Work (Jak to działa?) on Windows 3.1 - problem with ATTRIB

### ISSUE THREAD

**Issue by karol-kiersnowski** [dosbox-staging/dosbox-staging#1288]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### What Operating System are you using?

Linux x86_64

### If Other OS, please describe

Linux Mint 20.2

### Relevant hardware info

Core 2 Duo E8500

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

During the installation of the program "The Way Things Work" (actually the Polish version of "Jak to działa?" on Windows 3.1 the error appears: "Cannot change properties of the file named: C:\WINDOWS\WIN31PL\SYSTEM\WIN32.DLL".

There is a workaround on the Compatibility page:
[https://www.dosbox.com/comp_list.php?showID=3954&letter=T](https://www.dosbox.com/comp_list.php?showID=3954&letter=T)
Unfortunately, it doesn't work for me anyway.

The OP wrote that this is related to the **ATTRIB** command, which is a dummy in DOSBox.

> The Way Things Works set up (1.0) returns errors because it is trying to make many of the files it is copying from the CD to the HDD read only however DOSBOX deliberately replaced FreeDos' attrib with a dummy version so it could not create problems for the host OS. Manually making each new file setup creates read only in the host OS makes the program think all is well and it continues.

Is it possible to resolve this issue?

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by nemo93** [comment]
@karol-kiersnowski thanks for reporting. What's happening after you install the `ATTRIB` command as described [here](https://github.com/dosbox-staging/dosbox-staging/wiki/Add-Utilities#manually) please?

**Comment by karol-kiersnowski** [comment]
Thanks for answer.

1. I checked the English version of The Way Things Work. However, it was able to install without any problems. So now there is only a problem with the Polish version.

2. I have already used the ATTRIB command from FreeDOS in DOSBox. Unfortunately, in DOSBox the ATTRIB command is probably an internal command. Whenever I try to execute the ATTRIB command from FreeDOS, it always runs the command from DOSBox.

I can only run the ATTRIB command from FreeDOS if I rename it and there is no conflict with ATTRIB from DOSBox.

```
attrib /?
Does nothing. Provided for compatibility.
```

**Comment by kcgen** [comment]
Make sure that the path where your real attrib exists is listed before (to the left of) Z: in your PATH statement.

**Comment by karol-kiersnowski** [comment]
> Make sure that the path where your real attrib exists is listed before (to the left of) Z: in your PATH statement.

Of course, the path was listed in the PATH variable. As I wrote before: it looks like ATTRIB is an internal command in DOSBox.

**Comment by kcgen** [comment]
@karol-kiersnowski,

When you have a chance, please grab the latest build as-of today: https://dosbox-staging.github.io/downloads/devel/, or fetch and build the latest sources.

It uses a new placeholder program for both `ATTRIB.COM` and `DEBUG.COM`.

For example, if the placeholder is run, you will get this message:

![attrib_000](https://user-images.githubusercontent.com/1557255/134812660-e445a90b-86c5-410b-8c8c-058fe85ab57a.png)

In your case, you mentioned installing FreeDOS's ATTRIB. 

Provided the FreeDOS ATTRIB executable **_comes first in your PATH_**, then it will be used instead of the placeholder.  See the example in the screenshot for help.

If this doesn't work, please post your `[autoexec]` section.

**Comment by karol-kiersnowski** [comment]
Unfortunately, it did not help. I keep getting the same error in "Jak to działa?":
> "Cannot change properties of the file named: C:\WINDOWS\WIN31PL\SYSTEM\WIN32.DLL"

I tried to use the `ATTRIB` command and change the file properties, but no changes were made at all. To be sure, I started FreeDOS and checked how `ATTRIB` works in FreeDOS - it works, changes are remembered.

So the `ATTRIB` command doesn't work at all in DOSBox (both from FreeDOS and MS-DOS 6.22). 


My `[autoexec]` section
```
PATH=C:\COMMANDS;C:\COMMANDS\FREEDOS;C:\COMMANDS\MS-DOS;C:\COMMANDS\UNIXLIKE;C:\CONFIG;C:\GAMES;C:\PROGRAMS;C:\WINDOWS;%PATH%;
SET TEMP=C:\TEMP
mount c ~/DOS
c:
```
`ATTRIB.COM` is located in `C:\COMMANDS\FREEDOS` and `C:\COMMANDS\MS-DOS`

**Comment by arrowgent** [comment]
is there a requirement for emulating the dosbox enviornment VER for freedos?
https://www.dosbox.com/wiki/VER
ive rarely had to use VER for changing the dos enviornment version

```
Using the FreeDOS VERSION command
If you use FreeDOS, it doesn’t include the SETVER command. But you can issue the VERSION command in config.sys to make FreeDOS report certain version numbers. Simply add the following line to config.sys:

version=6.22
Unlike MS-DOS or PC DOS, in FreeDOS, this command is global. Use a setting of 6.22 to imitate DOS 6.2, 5.0 to imitate DOS 5.0, or 7.1 to imitate Windows 98 in DOS mode. This will allow you to run programs that expect those versions, including utilities copied from that particular Microsoft version of DOS. That’s helpful if you like FreeDOS but prefer specific functionality from one of Microsoft’s DOS tools.
```
quick search:
https://dfarq.homeip.net/incorrect-dos-version-how-to-fix-it/

again, not sure if that would help you get freedos working in dosbox.

**Comment by Burrito78** [comment]
MS-DOS 6.22 ATTRIB.EXE doesn't work in DOSBox Staging for me too, it seems that DOSBox Staging doesn't support changing file attributes at the moment.

DOSBox-X added this feature but Staging hasn't yet and maybe won't for some time!
https://github.com/joncampbell123/dosbox-x/issues/1469

@kcgen What do you think? Easy to implement or too much work/not important enough/too risky? Backlog?

**Comment by Grounded0** [comment]
ATTRIB support has been added to DOSBox Staging. Closing as completed.
