### ISSUE TITLE
[BUG] can't boot PC Booter M.U.L.E

### ISSUE THREAD

**Issue by LowLevelMahn** [dosbox-staging/dosbox-staging#1289]
dosbox staging git, Win7/VS2019

dosbox svn [autoexec] in config
```
mount d .
boot d:\mule.img -l a
```

works out of the box

with dosbox staging

dosbox-staging git [autoexec] in config
```
mount d .
imgmount a d:\mule.img -t floppy 
boot -l a
```

just did nothing - dosbox-staging starts and sitting on Z: thats it, no additional log output etc. 

im using for dosbox svn and dosbox staging freshly created configs with the 1 or 2 lines in the autoexec section

**Comment by LowLevelMahn** [comment]
blanks in path, sorry

**Comment by kcgen** [comment]
> blanks in path, sorry

This is pretty subtle: is there anything we can due to trim the blanks to help users? (I can't actually we're where the blanks exist in the two text blocks - can you add more detail?)

**Comment by Jkapp76** [comment]
@LowLevelMahn 

Where can I find a copy of mule.img for testing?

**Comment by LowLevelMahn** [comment]
> > blanks in path, sorry
> 
> This is pretty subtle: is there anything we can due to trim the blanks to help users? (I can't actually see where the blanks exist in the two text blocks listed above - can you add more detail?)

It was just a path with blanks

c:\mule 1983\
  dosbox.conf
  mule.img

VS2019 Debug commandline -conf c:\mule 1983\dosbox.conf

And in dosbox.conf only "mount d ."

So the d mount was just the workdir of VS2019 and mule.img was not available in that folder

Just stupid mistake ive made

**Comment by LowLevelMahn** [comment]
> @LowLevelMahn
> 
> Where can I find a copy of mule.img for testing?

GOG selling it, but its already working

**Comment by Jkapp76** [comment]
Actually, I have the img file. It's dino eggs that I'm looking for. I collect booter games and disk images.
