### ISSUE TITLE
Include FreeDOS XCOPY, DEBUG and DELTREE commands

### ISSUE THREAD

**Issue by Burrito78** [dosbox-staging/dosbox-staging#1296]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### What Operating System are you using?

Mac OS

### Is your feature request related to a problem? Please describe.

Some game installers depend on Xcopy and Debug commands. These games don't install properly out of the box with DOSBox Staging.

### Describe the solution you'd like

Include FreeDOS versions of Xcopy and Debug in DOSBox Staging.

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by Burrito78** [comment]
https://github.com/dosbox-staging/dosbox-staging/issues/993

**Comment by Burrito78** [comment]
References:

DEBUG
Tie Fighter
https://github.com/dosbox-staging/dosbox-staging/issues/993

XCOPY
Flashback CD
GTA "London"
https://github.com/dosbox-staging/dosbox-staging/issues/1258#issuecomment-919058590

**Comment by Grounded0** [comment]
I'm backing this proposition as DOSBox Staging should install and run all popular games out of the box. As a user of FreeDOS i think most of the userland is of really good quality and a worthwhile inclusion.

**Comment by Burrito78** [comment]
XCOPY
DELTREE
Grand Theft Auto
https://discord.com/channels/514567252864008206/626653390830698516/905997014603558954
https://discord.com/channels/514567252864008206/626653390830698516/906000618236284979

**Comment by Grounded0** [comment]
Our Z: drive now supports easy inclusion of files so maybe we should do this now.

Here's the relevant files pulled from FreeDOS 1.3 install:

[freedos13files.zip](https://github.com/dosbox-staging/dosbox-staging/files/9331052/freedos13files.zip)

**Comment by kcgen** [comment]
Moving into the 0.79 release.
