### ISSUE TITLE
Window resolution not respected for texturenb or openglnb

### ISSUE THREAD

**Issue by qwertfisch** [dosbox-staging/dosbox-staging#1320]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### What Operating System are you using?

Windows 7

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

The config parameter `windowresolution` is not respected if the output is set to either `texturenb` or `openglnb`.

## Predefined(?) possible resolutions
There are two problems. First, only specific resolutions are possible at all. These are:
1. 640x400
2. 800x500
3. 1024x640
4. 1280x800

(There might be higher resolutions, but I only have a 1920x1080 monitor, which gives a maximum of 1040 lines for me to test).

Even if these should be sharp scaling factors, from the basic resolution of 320x200, I am still missing resolutions like 960x600 (factor 3) or 1120x700 (factor 3.5). And why is there a 1024x640 resolution (factor 3.2)? I am not using aspect ratio correction here, as it (a) complicates the matter and (b) the actual game I am testing with does not need AR correction.

## Not respecting resolution setting

The second problem is that even when restricting to the resolutions above, I have to set a much higher vertical resolution before one of these are set:

| Minimum resolution set | resulting resolution |
| --: | --: |
| all below | 640x400 |
| 800x600 | 800x500 |
| 1024x768  | 1024x640 |
| 1280x960 | 1280x800 |

How to read: e.g. for the window having 800x500 pixels, I would need to have at least 800x600 as `windowresolution`.

In the example of `windowresolution = 960x600`, the window would open with 800x500 and have sharp but not uniform pixels (as the factor is not integer). __Fun fact:__ using `openglnb` allows resizable windows and allows me to manually change the window size afterwards to match exactly 960x600. So __it is__ technically possible, DOSBox just does not start with the intended resolution.

## Conclusion

The window resolution parameter is not working as expected in the output modes `texturenb` or `openglnb`. I would at least expect 960x600 pixels (factor 3) to be available. Also some higher resolution needs to be set, which is neither intuitive nor understandable.

On fullscreen (1920x1080) though, the scaling works perfectly sharp on 1728x1080 pixels.

Using `texture` or `opengl` instead would give me an exact (and sharp for 960x600) window resolution, but at a loss of sharpness when switching to fullscreen. So this is not a solution.

### Steps to reproduce the behaviour.

Explain how to reproduce
1. 
2.
3.

### Your configuration

```ini
# default configuration, only differ in these lines:
[sdl]
windowresolution = 960x600
output           = texturenb

[render]
aspect             = false
```

### Provide a Log

```text
MAIN: Disabled resizable window, only compatible with OpenGL output
MAIN: Sized window to 800x500 with nearest-neighbour scaling and square pixels
SDL: Using driver "direct3d" for texture renderer
MAIN: Draw resolution: 320x200, double-width, double-height, pixel aspect ratio: 1.00
```

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by qwertfisch** [comment]
Thanks for pointing to the PR, this is quite interesting and gives new ideas for playing games in windowed mode without losing immersion.

> Yes, depending on the mode and resolutions, sometimes black-bars will exist above (or to the sides) of the window to achieve the aspect ratio or to hold the window to a given size.

That is to be expected for OpenGL output, as one can resize the window manually, whereas for texture / texturenb output the window is by default set to the given window size.

> 640x480 ensures that these users aren't given a postage stamp.

Yes, I noticed that in texture output modes this might happen … 640x480 is fine as minimum size. I just wanted to say, for `aspect=false` the minimum window size is **still** 640x480 instead of 640x400, which gives black bars right from the start (in OpenGL output), even when it’s not necessary here.

Should I move this finding to a new issue? It’s just a minor thing.

**Comment by kcgen** [comment]
@qwertfisch , when you have a chance, a new Windows binary to test: https://github.com/dosbox-staging/dosbox-staging/actions/runs/1324040852

**Comment by kcgen** [comment]
@qwertfisch , when you have a chance, I've pushed a potential fix for `output = opengl` here:
 -https://github.com/dosbox-staging/dosbox-staging/actions/runs/1324121114

**Comment by qwertfisch** [comment]
@kcgen The behaviour seems now to be correct. The text window is resized correctly to 640x400 without black bars for `aspect=false`, if the `windowresolution' is 400 or less.

Another thing changed in the new alpha build: When changing display mode, e.g. switch from text mode to VGA mode when starting a game, the window is now resize and respecting the value in `windowresolution`. A 320x200 game for example might then be displayed smaller or in original resolution, but I think this is a more consistent behaviour.

So this issue is resolved, but then I found an obscure edge case while testing, sorry for that … How to reproduce the behaviour:
- set `windowresolution` to less than 640x400
- DOSBox opens in text mode with 640x400
- resize the window (doesn’t matter to what, even the minimum of 640x400 is fine)
- start a game with low resolution

__Expected:__ on mode change, the window resizes to `windowresolution`.  
__Actual:__ the window stays momentarily in its last size *until* I try to move it on the screen. Then it suddenly resizes to the set window resolution.

Am I being pedantic? This is a case no one will ever discover in real life or if so, would find annoying.

**Comment by qwertfisch** [comment]
There is a run, but no artifact was published. Can you try again?

Also to be clear: the window resizing is intended behaviour? I’m just asking because either way it might be reasonable.
> When changing display mode, e.g. switch from text mode to VGA mode when starting a game, the window is now resized and respecting the value in `windowresolution`

**Comment by kcgen** [comment]
Sorry @qwertfisch , here's the run: <https://github.com/dosbox-staging/dosbox-staging/actions/runs/1329758066>

**Comment by qwertfisch** [comment]
I wasn’t having a particular expectation, I just wanted to check what the intended behaviour should be. Because it kept changing from build to build …

> I believe with the latest change, which includes @dreamer 's suggestions, it should hold to a 640x400 window (unless manually resized).

Yes, I can confirm that. On any graphic mode change, the initial minimal window size is 640x400 (or 480), but manual resizing to smaller window is still possible. Your commit in eed7f9f restricts the minimal size and results essentially in this log output:
```
DISPLAY: Requested windowresolution '400x300' is not valid, falling back to '640x400' instead
DISPLAY: Initialized 640x400 window-mode on 1920x1080 display-0
[…]
DISPLAY: Bilinear scaling VGA-320x200,256c #13h PAR-1.00 by 2.0x2.0 -> 640x400 PAR-1.00
```

If the need for a smaller draw resolution arises, the new options from #1272 (`maxresolution`) should be sufficient. In my opinion this is an acceptable and consistent solution. Also I could not reproduce any resizing glitches. Looks good now. :+1:
