### ISSUE TITLE
[Dark Forces] Installer > Audio Test Crash

### ISSUE THREAD

**Issue by brandonrobertz** [dosbox-staging/dosbox-staging#1344]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Different version than latest?

f03e24acbceb7e1d7e18c01eb71f45a8f1dd24ad

### What Operating System are you using?

Mac OS/x86-64 

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

The Dark Forces Installer crashes when running the audio test while DOSBox is running in ubsan mode. The crash is exclusive to ubsan mode, I've confirmed it does not happen in current release, or f03e24acbceb7e1d7e18c01eb71f45a8f1dd24ad release build.

### Steps to reproduce the behaviour.

1. Get the Dark Forces Installer CD-ROM image (https://archive.org/details/msdos_Star_Wars_-_Dark_Forces_1995)
2. Mount the CD-ROM
3. Run the installer.
4. When prompted about audio, do [E]xpress install and test the sound. The sound test will halt midway through and a segfault will appear on the DOSBox screen. The CLI doesn't indicate a crash unlike other ubsan failures.

### Your configuration

```ini
Using stock dosbox-staging-git.conf, imgmount the Dark Forces CD-ROM.
```

### Provide a Log

```text
Here's the on-screen segfault: https://bxroberts.org/files/Screen%20Shot%202021-10-22%20at%207.50.13%20PM.png

Here's the CLI logs during the session (crash marked by me):
2021-10-23 12:08:08.710 | IMGMOUNT: Path '/Users/brandon/tmp/drk.bin' found
2021-10-23 12:08:12.029 | DOSBox has switched to max cycles, because of the setting: cycles=auto.
If the game runs too fast, try a fixed cycles amount in DOSBox's options.
2021-10-23 12:08:46.151 | SB16: DSP was reset
2021-10-23 12:08:46.153 | SB16: DSP was reset
2021-10-23 12:08:46.156 | SB16: DSP was reset
2021-10-23 12:08:46.158 | SB16: DSP was reset
2021-10-23 12:08:46.159 | SB16: DSP was reset
2021-10-23 12:08:46.161 | SB16: DSP was reset
2021-10-23 12:08:55.582 | SB16: DSP was reset
2021-10-23 12:08:55.584 | SB16: Speaker-output has been toggled on
[BRANDON'S NOTE: Crash happened around here]
2021-10-23 12:09:00.824 | SDL: The window manager requests that the window be closed
2021-10-23 12:09:00.824 | SDL: Exit requested
2021-10-23 12:09:00.824 | SDL: Exit requested
2021-10-23 12:09:00.825 | DISNEY: Shutting down
2021-10-23 12:09:00.854 | IOBUS: Releasing 52 read and 50 write 8-bit port handlers
2021-10-23 12:09:00.854 | IOBUS: Releasing 33 read and 35 write 16-bit port handlers
2021-10-23 12:09:00.854 | IOBUS: Releasing 33 read and 35 write 32-bit port handlers
2021-10-23 12:09:00.854 | IOBUS: Handlers consumed 11664 total bytes
2021-10-23 12:09:00.966 | atexit
```

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by kcgen** [comment]
This transfer issue has been reported in a couple places too:
 - https://www.flickr.com/photos/150156540@N02/sets/72157681587836973/
 - https://steamcommunity.com/app/32400/discussions/0/1291817837622583725/
 - https://www.vogons.org/viewtopic.php?t=19143

On Linux, UBSAN builds report no issue - however the installer's express audio tester still generates the stack-transfer crash and soft-locks itself.  Ctrl+F9 cleanly exits, and UBSAN reports no violations.

Perhaps on macOS with this instrumentation is revealing how this bug in the installer is having a strong enough impact on DOSBox's core/paging that the host decides to segfault/terminate the executable.

Can you try this:

``` ini
[cpu]
core = dynamic
cycles = 45000

[midi]
mididevice = none

[sblaster]
sbtype = sbpro2
irq = 5

[gus]
gus = false

[speaker]
pcspeaker   = false
tandy       = off
disney      = false
ps1audio    = false

[dos]
xms = false
ems = false
umb = false
```

**Comment by kcgen** [comment]
On a tangent now, besides this issue, the game is great w/ General MIDI using the custom config:

![2021-10-23_18-51](https://user-images.githubusercontent.com/1557255/138577795-446f08fc-d37a-459b-89fa-b8c2a9df6d3e.png)

With this local `dosbox.conf`:

``` ini
[cpu]
core = dynamic
cycles = 45000

[midi]
mididevice = fluidsynth

[fluidsynth]
soundfont = AudioGen 66

[sblaster]
sbtype = sbpro2
irq = 5
oplmode = none

[gus]
gus = false

[speaker]
pcspeaker   = false
tandy       = off
disney      = false
ps1audio    = false

[dos]
xms = false
ems = false
umb = false
```

@HW-Scanno composed the AudioGen soundfont (https://kcgen.duckdns.org/AudioGen.sf2), which you can place in a `soundfonts/` directory within your usual DOSBox config directory.

**Comment by brandonrobertz** [comment]
> This transfer issue has been reported in a couple places too:
> 
>     * https://www.flickr.com/photos/150156540@N02/sets/72157681587836973/
> 
>     * https://steamcommunity.com/app/32400/discussions/0/1291817837622583725/
> 
>     * https://www.vogons.org/viewtopic.php?t=19143
> 
> 
> On Linux, UBSAN builds report no issue - however the installer's express audio tester still generates the stack-transfer crash and soft-locks itself. Ctrl+F9 cleanly exits, and UBSAN reports no violations.
> 
> Perhaps on macOS with this instrumentation is revealing how this bug in the installer is having a strong enough impact on DOSBox's core/paging that the host decides to segfault/terminate the executable.
> 
> Can you try this:
> 
> ```ini
> [cpu]
> core = dynamic
> cycles = 45000
> 
> [midi]
> mididevice = none
> 
> [sblaster]
> sbtype = sbpro2
> irq = 5
> 
> [gus]
> gus = false
> 
> [speaker]
> pcspeaker   = false
> tandy       = off
> disney      = false
> ps1audio    = false
> 
> [dos]
> xms = false
> ems = false
> umb = false
> ```

I tried with this config and it no longer crashes. It does sound extremely rough (crackly and distorted and too slow), but no crashes.
