### ISSUE TITLE
[BUG] vcpkg install of PCRE fail

### ISSUE THREAD

**Issue by LowLevelMahn** [dosbox-staging/dosbox-staging#1354]
freshly installed Win10+VS2019 German is not able to install the needed vpckg packages

vcpkg tried to grab an very old PCRE  8.45 version and fails due to missing download sever

filed a bug report: https://github.com/microsoft/vcpkg/issues/21201#issue-1045563470

**Comment by dros0-0** [comment]
Download [pcre-8.45.zip](https://sourceforge.net/projects/pcre/files/pcre/8.45/) from SourceForge. Place it in vcpkg\downloads.

**Comment by LowLevelMahn** [comment]
fixed with https://github.com/microsoft/vcpkg/commit/61b3046e513d189495ee37247e6cc550ee75e471
