### ISSUE TITLE
DOSBox Staging launched from Steam via directory symlink crashes with most SoundFonts for Star Trek: Judgment Rites

### ISSUE THREAD

**Issue by dros0-0** [dosbox-staging/dosbox-staging#1357]
Given my nonstandard use case, I was leery of filing this as a bug.

Windows 10.0.19043.1288 Pro 64-bit; DOSBox Staging 0.77.1 64-bit (official precompiled binary). My DOSBox Staging directory as well as my Steam directory (and games directories) are located on a different storage drive (D) than my system drive (C). The game at issue is Star Trek: Judgment Rites, which Steam launches via a batch file (launch judgment rites.cmd). I have not yet tested GM SoundFonts on any other DOSBox-supported game (with DOSBox Staging's directory symlinked) to see if this issue is unique to ST:JR. 

This is very much a corner case of negligible importance. I was hesitant to even bring this up, except that I don't encounter this issue with the most recent releases of DOSBox ECE or DOSBox-X (I tested the 64-bit SDL 2.0 VS Studio portable build of DOSBox-X), when using either of them via the same directory symlink method with ST:JR and stipulating a SoundFont for FluidSynth to use, and I can also fix this issue with DOSBox Staging if I copy libfluidsynth-3.dll (replacing the existing libfluidsynth-3.dll), libglib-2.0-0.dll, libinstpatch-2.dll, libgobject-2.0-0.dll, libgthread-2.0-0.dll, libsndfile-1.dll, libgcc_s_sjlj-1.dll, libstdc++-6.dll, libgomp-1.dll, libintl-8.dll, libwinpthread-1.dll from https://github.com/FluidSynth/fluidsynth/releases/download/v2.2.3/fluidsynth-2.2.3-win10-x64.zip into my DOSBox Staging directory.

Background:
I have DOSBox Staging launch via Steam instead of the DOSBox 0.74 release included with the game (via directory symlink in the "Star Trek Judgment Rights" [sic] directory; I renamed the original dosbox directory to dosbox-0.74, and created a DOSBox Staging directory symlink named dosbox). I have also updated the relevant game CONF file (dosbox_stjr.conf) via config -wc to remove obsoleted options (e.g. fulldouble), and have smoothed out the only previous issue I encountered: the game's original SDL settings of fullresolution=original and output=surface in combination with the use of PictView, which the game uses to display a splash screen, caused DOSBox Staging to immediately close when opened (this happened whether I used a directory symlink, or copied DOSBox Staging into the game's directory, or set the game up in DBGL with DOSBox Staging using Steam's default CONF settings for the game). If I started the game in windowed mode and then went to fullscreen after PictView had loaded the splash screen, DOSBox Staging wouldn't crash, and if I started the game in fullscreen, but changed either the fullresolution or output SDL settings in dosbox_stjr.conf, or commented out "pictview title.png" in dosbox_stjr_single.conf, the game would launch successfully in fullscreen. Rather than forgo the splash screen, I ended up changing to fullresolution=desktop and output=texture (with scaler=normal2x) in dosbox_stjr.conf, both to resolve the issue and for visual personal preference. 

Issue:
Everything has been copacetic since then (including MT-32 via mt32emu; the game requires unofficial patches for this), except when I switched from MT-32 to Fluidsynth and specified a SoundFont. I have a bevy of SoundFonts I'm testing (located in DOSBox Staging's %LocalAppData%\DOSBox\soundfonts directory). When launching DOSBox Staging via directory symlink, only a few SoundFonts have worked; e.g. at the moment, soundfont=FluidR3 GM.sf2 does not cause DOSBox Staging to immediately close for some reason, but if I switch to many of the other SoundFonts (e.g. ChoriumRevA.SF2), the next time I attempt to launch the game via Steam, DOSBox Staging closes right after it opens. There are dozens of SoundFonts I have which all work in DOSBox Staging when not launching DOSBox Staging via directory symlink (i.e. when DOSBox Staging is instead copied to the "Star Trek Judgment Rights" [sic] directory), but when launching DOSBox Staging via directory symlink with ST:JR, oftentimes DOSBox Staging won't stay open if I specify one of these SoundFonts in dosbox_stjr.conf. It doesn't matter if I stipulate absolute paths for the SoundFont or not; DOSBox Staging crashes either way. This crashing also happens whether the aforementioned unofficial patches have been applied or not. I have also tried using a directory junction (mklink /J) instead of a directory symlink (mklink /D), but encountered the same issue with DOSBox Staging. As previously mentioned, I can't replicate this issue with DOSBox-X or DOSBox ECE, and copying the aforementioned DLLs from FluidSynth's most recent release into my DOSBox Staging directory resolved the issue.

PS Is there a way to stack SoundFonts (e.g. WeedsGM4 Update.sf2 + WeedsGM3.sf2) with DOSBox Staging's implementation of FluidSynth?

**Comment by arrowgent** [comment]
can you test running symlinked dosbox-staging from the startrek judgement rites folder without steam?

try to determine if its steam overlay,  disable steam overlay in the steam properties for judgement rites

is dosbox-staging symlinked or is the soundfont symlinked?

interesting you are replacing the provided `libfluidsynth-3.dll` with a set from `fluidsynth-2.2.3-win10-x64.zip`
that seems like a lot of extra files compared to what is already included (1 file)
Q?: what version of fluidsynth does dosbox-staging currently ship with and support?

**Comment by kcgen** [comment]
I appreciate that you took so much time to write this up @dros0-0. 

For us to help, please start with a clean-slate and list the absolute minimum steps reproduce the problem.

Here's roughly what I'd like to see:

1. unzip dosbox-staging 0.77.1 and place the game's ISO image in the same directory
1. open a cmd prompt in this directory
1. run `dosbox .`
1. `mount d trek.iso`
1. `cd d:`
1.  run `install.exe`, and install it to c:/trek
1. exit dosbox
1. describe a single step that causes it to fail
1. launch `dosbox .`, run the game from c: and confirm it fails: take a screenshot or paste the log
1. change the fail step back to original setting
1. launch `dosbox .`, run the game from c: and confirm it works. take a screenshot or paste the log.

Thank you.

**Comment by dros0-0** [comment]
I uninstalled Star Trek: Judgment Rites, making sure to delete the remaining files and directory Steam left behind, then I reinstalled ST:JR. I deleted my DOSBox Staging directory and %LocalAppData%\DOSBox\ directory, then reinstalled and opened DOSBox Staging 64-bit, just be sure I started with a clean slate. I then copied the SoundFonts to %LocalAppData%\DOSBox\soundfonts.

These are the changes I subsequently made:

1. I updated the game's dosbox_stjr.conf via `config -wc` [Run "D:\Program Files\DOSBox Staging\dosbox.exe" -conf "D:\Program Files (x86)\Steam\steamapps\common\Star Trek Judgment Rights\dosbox_stjr.conf". Once DOSBox Staging is open, enter config -wc "D:\Program Files (x86)\Steam\steamapps\common\Star Trek Judgment Rights\dosbox_stjr.conf".]
2. Once dosbox_stjr.conf was updated, I changed the options below in the game's dosbox_stjr.conf. If desiring to use the default dosbox-staging.conf instead, I highly recommend at least changing cpu cycles to max (this is already changed in dosbox_stjr.conf), although as a matter of preference I would also change render aspect to false, and render scaler to normal2x (these are also already changed in dosbox_stjr.conf); mididevice needs to be set to fluidsynth and soundfont needs to be set to whatever SoundFont is being testing.
```
[sdl]
# fullresolution = original
output = texture
# mapperfile = mapper-0.74.map
[midi]
mididevice = fluidsynth
[fluidsynth]
soundfont = <whatever SoundFont I want to test>
```
3. I changed the following values in trek.cfg in order to enable MPU-401. This can also be achieved using the Interplay Installer.
```
music=A001
music_io=330
```
4. I renamed the dosbox subdirectory in D:\Program Files (x86)\Steam\steamapps\common\Star Trek Judgment Rights\ to dosbox-0.74.
5. I created a directory symlink [mklink /D "D:\Program Files (x86)\Steam\steamapps\common\Star Trek Judgment Rights\dosbox" "D:\Program Files\DOSBox Staging"].
6. I started the game via Steam.

This leads to DOSBox Staging 64-bit immediately closing (it closes in less than 2 seconds) after launch (I tested both 0.77.1 and 0.78.0-alpha-755-g2b4af). However...

New wrinkle: I tested 32-bit DOSBox Staging 0.77.1 via directory symlink, and it worked beautifully with SoundFonts with ST:JR (it did have the same unrelated issue of the combination of fullresolution=original + output=surface + PictView causing DOSBox Staging to close).

This may not provide any actionable comparative info given the differences between the projects, but I retested the most recent 64-bit DOSBox-X SDL 2.0 VS Studio build as well as the 64-bit DOSBox-X SDL 2.0 MinGW build via directory symlinks, and both DOSBox-X 64-bit SDL 2.0 builds work when choosing a SoundFont. And as previously mentioned, replacing libfluidsynth-3.dll in DOSBox Staging 64-bit with libfluidsynth-3.dll (plus the 10 DLL dependencies mentioned in my original comment) from FluidSynth's 2.2.3 64-bit release for Windows 10 fixed the issue with DOSBox Staging 64-bit 0.77.1.

As previously mentioned, there are at least a couple of SoundFonts that don't seem to cause DOSBox Staging 64-bit to close when DOSBox Staging is launched via a directory symlink with the Steam installation of the game.
- The same SoundFonts that cause DOSBox Staging 64-bit to close when I use DOSBox Staging 64-bit via a directory symlink work as expected when I don't use a directory symlink (i.e. if I copy DOSBox Staging 64-bit into ST:JR's directory, then those SoundFonts work fine).
- Also, the same SoundFonts that cause DOSBox Staging 64-bit to immediately close when I use DOSBox Staging 64-bit via directory symlink work as expected when I use DOSBox Staging 32-bit via a directory symlink.

I could document the results of all of the SoundFonts if needed, but they all work with DOSBox Staging 64-bit except in this one corner case (i.e. directory symlink or directory junction when used with Steam), and they pose no issue for DOSBox Staging 32-bit, regardless of if a directory symlink is used.

**Re: issuecomment-962451615** @arrowgent 

With a clean install of ST:JR and DOSBox Staging 0.77.1, with only the changes made as outlined in 1-5 above:
- With Steam completely exited, then starting the game, DOSBox Staging 64-bit immediately closes (in less than 2 seconds).
- With Steam running, and Steam overlay disabled, DOSBox Staging 64-bit immediately closes.
- The DOSBox Staging directory is symlinked, not the SoundFonts directory.
- Yes, all Windows partitions are formatted NTFS.

**Re: issuecomment-962467850** @kcgen 
new directory path = path where I extracted the fresh copy of 0.77.1 64-bit
1. ✓
2. ✓
3. ✓
4. ✓
5. ✓
6. ✓
7. ✓
8. No steps fail
9. ✓ It does not fail (attached image), but this also doesn't replicate the problematic setup.
![picforstep9](https://user-images.githubusercontent.com/93776065/140647335-b70e07a2-3c4d-473e-9852-e1828aa03b24.png)

I am in the process of trying to replicate the failure one variable at a time. E.g. batch file, no batch file, game (via Interplay Installer) and DOSBox Staging installed on the system drive, game (via Interplay Installer) and DOSBox Staging installed on a separate drive, etc. I have not been able to replicate the failure thus far except when I use the game as installed by Steam with a directory symlink for DOSBox Staging 64-bit and specify a SoundFont. I uninstalled Steam and removed DOSBox Staging from D and installed them on the system drive (C), then tried again, and it still results in DOSBox Staging 64-bit closing in less than two seconds when using a directory symlink and SoundFonts. I've also tried with ST:JR installed by Steam to a different parent directory than the Steam client, but I get the same result. I'll probably next compare the game files installed with Steam to those installed by the Interplay Installer on the off chance there is a difference, but as previously mentioned, the 32-bit version of DOSBox Staging had no issue with SoundFonts when being accessed via directory symlink with the game files as installed by Steam.

**Comment by dros0-0** [comment]
I apologize if parts of these comments are repetitive, I'm just trying to be thorough.

ST:JR’s default directory structure on Steam:
- Steam
  - steamapps
    - common
      - Star Trek Judgment Rights
        - dosbox
        - trek2
          - uncomp

I renamed the original dosbox subdirectory (the one included with the game) to dosbox-0.74 (alternatively, it can be deleted), then used `mklink /D "D:\Program Files (x86)\Steam\steamapps\common\Star Trek Judgment Rights\dosbox" "D:\Program Files\DOSBox Staging"`. I.e. I created a directory symlink for DOSBox Staging named "dosbox" in the "Star Trek Judgment Rights" directory. 

---
The SoundFont failure isn't as pervasive as I originally thought. I have now gone through 42 SoundFont files using the setup above, and 20 of the SoundFonts didn't result in DOSBox Staging 64-bit closing within seconds of opening. But I haven't been able to diagnose the issue yet as to why the rest trigger failure in this particular setup.

SoundFont naming convention isn't at issue, nor is filesize. I thought file construction might be a factor somehow, but it doesn't appear to be the issue [e.g. CT2MGM.SF2 and CT8MGM.SF2 both fail, but CT4MGM.SF2 doesn't fail, and all three were taken from [https://archive.org/details/cd-sb-audigy](https://archive.org/details/cd-sb-audigy) (if you mount the image, they can be found in Audio > Common > SFBank)].

Here are a handful of other SoundFonts that either work or don't work for me with the directory symlink setup described above.
| Works  | Fails |
| ------------- | ------------- |
| [Arachno SoundFont](http://www.arachnosoft.com/main/download.php?id=soundfont-sf2)  | [Chorium Revision A](http://www.un4seen.com/download.php?extra/ChoriumRevA)  |
| [FluidR3 GM](https://archive.org/details/fluidr3-gm-gs)  | [Giant Soundfont](https://giantsoundfont.hpage.com/downloads.html)  |
| [Timbres of Heaven (XGM) 3.94 ](http://midkar.com/soundfonts/)  | [Weeds GM 3](http://www.un4seen.com/download.php?extra/WeedsGM3)   |

- All 42 SoundFonts I've tested work with DOSBox Staging 0.77.1 64-bit when its directory is symlinked as described above but the provided libfluidsynth-3.dll has been replaced by the libfluidsynth-3.dll taken from [fluidsynth-2.2.3-win10-x64.zip](https://github.com/FluidSynth/fluidsynth/releases/tag/v2.2.3) (plus the 10 necessary FluidSynth DLL dependencies from that archive, as listed in my first comment).
- All 42 SoundFonts I've tested work with DOSBox Staging 0.77.1 32-bit when its directory is symlinked as described above (no replacement libfluidsynth-3.dll needed).
- All 42 SoundFonts I've tested work with DOSBox Staging 0.77.1 64-bit when its directory isn't symlinked, e.g. if I copy the DOSBox Staging 64-bit (renamed as "dosbox") directory into "Star Trek Judgment Rights".

**Comment by dros0-0** [comment]
I compiled DOSBox Staging 0.77.1 64-bit with FluidSynth 2.2.1 as provided by vcpkg and all 42 SoundFonts are working now when I use a directory symlink.

**Comment by kcgen** [comment]
Thanks for continuing to progress this to a conclusion @dros0-0.

If you copy your compiled `dosbox.exe` (just the without any of its companion DLLs you installed to build it),  file into the 0.77.1 release directory -- does the problem return?

If so, this might points to the release missing some fluidsynth dependencies that we instead should be bundling.

**Comment by dros0-0** [comment]
Yes, the problem returns when I overwrite the precompiled binary with the one I compiled.
