### ISSUE TITLE
[BUG] Mouse was not locked in Daggerfall

### ISSUE THREAD

**Issue by Reonaydo** [dosbox-staging/dosbox-staging#1371]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Different version than latest?

0.77.1

### What Operating System are you using?

Linux x86_64

### Relevant hardware info

OpenGL renderer string: Radeon RX 5500 XT (NAVI14, DRM 3.42.0, 5.15.2-gentoo-x86_64, LLVM 13.0.0)

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Hello!

Mouse lock does not work in Daggerfall game. Nor autolock nor manual lock via Ctrl+F10. So the game is unplayable.
I have also checked "vanilla" dosbox (in the same environment, same libs, same config) and there all is ok.

Also I have tried dosbox-staging from lutris. There is same problem.

### Steps to reproduce the behaviour.

Explain how to reproduce
1. 
2.
3.

### Your configuration

```ini
[sdl]

fullscreen=false
fulldouble=true
fullresolution=desktop
windowresolution=1900x1000
output=opengl
autolock=true
sensitivity=100
waitonerror=true
priority=higher,normal
mapperfile=mapper-0.74-2.map
usescancodes=true
raw_mouse_input = true

[dosbox]
language=
machine=svga_s3
captures=capture
memsize=63

[render]
frameskip=0
aspect=true
scaler=normal3x

# skpped other sections
```

### Provide a Log

```text
$ dosbox -conf dosbox_daggerfall.conf -scaler normal3x -exit
dosbox-staging version 0.77.1
---
CONFIG: Loading primary file dosbox_daggerfall.conf
CONFIG: Unknown option fulldouble
CONFIG: Unknown option autolock
CONFIG: Unknown option usescancodes
CONFIG: Deprecated option 'oplrate'
CONFIG: oplrate is deprecated. The OPL waveform is now sampled
        at the mixer's playback rate to avoid resampling.
CONFIG: Unknown option gusrate
CONFIG: Unknown option ipx
MAIN: Sized window to 1334x1000 with stretched pixels
OPENGL: Pixel buffer object extension: available
SDL: Mouse will move seamlessly without being captured and middle-click will uncapture the mouse.
Memory sizes above 31 MB are NOT recommended.
Stick with the default values unless you are absolutely certain.
MEMORY: Base address: 0x7f393fcff010
MEMORY: Using 16128 DOS memory pages (63 MiB)
MIXER: Negotiated 2-channel 44100-Hz audio in 1024-frame blocks
MIDI: No working MIDI device found/selected.
MIDI: Opened device: none
MIXER: FM channel operating at 44100 Hz without resampling
MIXER: SB channel operating at 22050 Hz and upsampling to the output rate
MIXER: SPKR channel operating at 44100 Hz without resampling
MIXER: DISNEY channel operating at 10000 Hz and upsampling to the output rate
MAPPER: Found no joysticks
MAPPER: Loaded default key bindings
MOUNT: Path 'DAGGER' found
MOUNT: Path 'DFCD' found
MAIN: Draw resolution: 640x400, pixel aspect ratio: 1.20
```

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by kcgen** [comment]
Tested with the latest build and all of the mouse capture modes are working, at least for me.

Try this:
 - get the latest build (or compile it)
 - backup your game's directory
 - then extract this into your game directory: [tes_settings.tar.gz](https://github.com/dosbox-staging/dosbox-staging/files/7534242/tes_settings.tar.gz)

It will extract these files (expects the game's subdir to be `arena2`), along with the first save-game:

``` text
dosbox.conf
z.cfg
start.bat
caster.cfg

arena2/viewplyr.dat

save0/
save0/savename.txt
save0/savetree.dat
save0/mapsave.sav
save0/at50050.amf
save0/rumor.dat
save0/bio.dat
save0/image.raw
save0/savevars.dat
```

On your command prompt, CD into here where `dosbox.conf` and launch the latest build.  You can also pass the `-noprimaryconf` to ensure you're getting default settings.

This should lock your mouse right away.  Middle-click will release your mouse back to the OS.

You will have WASD + mouse controls.

**Comment by Reonaydo** [comment]
@kcgen thank you ver much!
There is exactly one options was needed in fact: `capture_mouse = onstart middlerelease`.
All works with it. 
But I have not found about this option in this documentation: https://github.com/dosbox-staging/dosbox-staging/blob/main/README

**Comment by kcgen** [comment]
Glad you're up and running.

Right; README's section 13 mentioned the conf file in general - but it doesn't cover individual conf settings (neither in upstream DOSBox nor other forks, in general).

This is because the conf settings are documented inline in the conf file, when you write a new one.  It would be duplicate effort to keep two sets of documents up-to-date, and would risk them getting out of sync. 

You can populate your conf file with the latest settings and documentation by running `config -wc` at your Z:\> prompt.  The console log will tell you where it wrote the file.

This will add the `capture_mouse = ...` setting to your conf, along with the documentation, and all of Staging's other settings.

(To help users in general, it's mentioned at the top of the release notes: https://dosbox-staging.github.io/v0-77-1/).   The command works for all DOSBoxes.
