### ISSUE TITLE
Is there need for instructions test?

### ISSUE THREAD

**Issue by xor2003** [dosbox-staging/dosbox-staging#1373]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Whats your question and how can we help?

QEMU project have good test for x86 instructions and flags like add, adc, mul, etc.
Executibale can be called on real and emulated CPU and results can be compared. (I mean it is not google test)
I haven't found such test in this project.
I already tried it myself on dosbox and it work pretty fine.
Do you want me to make a pull request?
I wanted to ask before doing some work.

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by LowLevelMahn** [comment]
yes please!!!

**Comment by kcgen** [comment]
Correctness tests are very welcome, indeed. 
Thanks for helping, @xor2003.

**Comment by xor2003** [comment]
If I call test from DOSBox-X or Windows or Linux it does not crash.
I if call from staging - it is crashing on div instruction.

x86 instructions test (testi386.exe) is build using mingw right now.
The HX extender is used so you can run in on real windows/wine system and compare results under emulator.

Sorry you have to integrate it yourself.
[qemu_dbs.zip](https://github.com/dosbox-staging/dosbox-staging/files/7541551/qemu_dbs.zip)

**Comment by xor2003** [comment]
I was not able to properly build it on djgpp gcc 5.4.0

**Comment by xor2003** [comment]
Crash on cmovnel:

 11180              	 # 402 "test-i386.c" 1
 11181 0061 39DB     		cmpl %ebx, %ebx
 11182 0063 0F457424 		cmovnel 28(%esp), %esi
 11182      1C
 11183              		
 11184              	 # 0 "" 2
 11185              	LVL1133:
 11186              		.loc 3 402 5 view LVU2011
 11187              	/NO_APP
 11188 0068 89742408 		movl	%esi, 8(%esp)
 11189 006c C7442404 		movl	$LC135, 4(%esp)
 11189      39050000 
 11190 0074 C7042441 		movl	$LC136, (%esp)
 11190      050000
 11191 007b E8000000 		call	_printf

**Comment by xor2003** [comment]
So the instruction emulation is very good for staging.
CMOV, CMPXCHB8 are not implemented. Maybe not required.
[qemu_x86_instructions.zip](https://github.com/dosbox-staging/dosbox-staging/files/7548163/qemu_x86_instructions.zip)

**Comment by kcgen** [comment]
Thank you @xor2003. It would be nice to get these working.

I did some quick tests see if the signed 32-bit division routines implemented by the DOSBox-X team could work in Staging (`IDVID` from `instructions.h`) but that wasn't sufficient, as the test program still failed in the same spot even with `core = normal`.

So it seems DOSBox-X has implemented further per-requisites to have this work properly. I haven't checked to see if CMOV or CMPXCHB8 are in the same boat, or if they could be more trivially ported. 

Are games affected by these? 

If games _aren't_ affected - then perhaps you or someone else could pursue adding these to Staging?

I would imagine each instruction would be a separate block of code, easily merged with no risk and no extra maintenance burden.  So this would be very welcome, if someone wants to add them.

**Comment by kklobe** [comment]
Probably of minimal value, at least CMOV. https://yarchive.net/comp/linux/cmov.html, and it wasn't available until PPro, IIRC.

**Comment by xor2003** [comment]
Right these instructions (CMOV, etc) are not required for DOS software since provided for recent CPUs. What's why they are not yet in original Dosbox I think.

**Comment by Burrito78** [comment]
It's dead, Jim.

**Comment by Grounded0** [comment]
Here's an easy way to test this if we actually emulate Pentium MMX B1-stepping behaviour and not the bugfixed B2-stepping: 😁

https://en.wikipedia.org/wiki/Pentium_F00F_bug
