### ISSUE TITLE
PERFDOS displays corrupted VBE OEM String with UniVBE

### ISSUE THREAD

**Issue by Grounded0** [dosbox-staging/dosbox-staging#1385]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Different version than latest?

0.78.0-alpha-848-g5355050c

### What Operating System are you using?

Mac OS

### If Other OS, please describe

macOS 11.6.1/x86-64

### Relevant hardware info

Apple MacBook Pro 15" Mid 2017 with AMD Radeon Pro 560

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

I have a discrepancy between 0.78.0-dev and 0.77.1 operation.

Please note: This bug only happens with 4MB or above of VRAM set.

When i run PERFDOS with 0.78.0-dev with UniVBE 5.3a loaded i get this @ 4MB VRAM:

<img width="1392" alt="Screenshot 2021-11-21 at 12 25 14" src="https://user-images.githubusercontent.com/48192273/142760016-fa813366-94f9-46d2-8109-2db3fd2cb15a.png">

When i run PERFDOS with 0.78.0-dev with UniVBE 5.3a loaded i get this @ 2MB VRAM:

<img width="1392" alt="Screenshot 2021-11-21 at 19 52 23" src="https://user-images.githubusercontent.com/48192273/142773304-2051a04f-00fa-4634-bfc8-2e4c48588668.png">

When i run PERFDOS with 0.77.1 with UniVBE 5.3a loaded i get this:

<img width="1392" alt="Screenshot 2021-11-21 at 12 24 29" src="https://user-images.githubusercontent.com/48192273/142760003-452f9062-291b-4dd5-87dd-71a67cc9ac09.png">

Tools i run however extract the correct OEM String:

<img width="1392" alt="Screenshot 2021-11-21 at 13 26 12" src="https://user-images.githubusercontent.com/48192273/142760024-85c424f9-aff4-403c-a4e9-29a1d7107f9d.png">

<img width="1392" alt="Screenshot 2021-11-21 at 13 26 37" src="https://user-images.githubusercontent.com/48192273/142760030-468d3f9c-571a-4cbd-990f-a5ae471d1c15.png">

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Run UniVBE 5.3a with 0.78.0-alpha-848-g5355050c
2. Run PERFDOS
3. Press ENTER key to see the info page

### Your configuration

```ini
UniVBE 5.3a preloaded with 2/4 MB VRAM.
Each system configuration configured separately with UVCONFIG.
```

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by LowLevelMahn** [comment]
did you also check 0.77.1 with UniVBE 5.3a and 4MB? (Screenshot missing)

**Comment by Grounded0** [comment]
I cannot because it only supports maximum of 2MB VRAM.

**Comment by Grounded0** [comment]
I will be closing this ticket as @krc looked this up. PERFDOS apparently supports a maximum of 127 mode values and loading UniVBE exceeds that with VRAM set at 4MB causing a memory overrun condition in the program.
