### ISSUE TITLE
Error trying to compile 0.77.1 release under Haiku

### ISSUE THREAD

**Issue by unspacyar** [dosbox-staging/dosbox-staging#1416]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### What Operating System are you using?

Other

### If Other OS, please describe

Haiku

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Hi!  When trying to compile Dosbox-staging r. 0.77.1, I got the following error:

```
src/hardware/libhardware.a(serialport_misc_util.cpp.o): In function TCPClientSocket::TCPClientSocket(int)':
/boot/home/Compilar/dosbox-staging-0.77.1/build/../src/hardware/serialport/misc_util.cpp:50: undefined reference to `getpeername'
/boot/home/Compilar/dosbox-staging-0.77.1/build/../src/hardware/serialport/misc_util.cpp:59: undefined reference to `getsockname'
collect2: error: ld returned 1 exit status
[228/229] Compiling C++ object tests/support.p/support_tests.cpp.o
ninja: build stopped: subcommand failed.


```

Thanks for your time!

### Steps to reproduce the behaviour.

Explain how to reproduce
1. extract the 0.77.1 source code .zip file.
2. run "meson setup -Duse_opengl=false build" from Terminal
3. run "ninja -C build" from Terminal

### Provide a Log

```text
[227/229] Linking target dosbox
FAILED: dosbox 
c++  -o dosbox dosbox.p/meson-generated_.._version.cpp.o dosbox.p/src_main.cpp.o dosbox.p/src_dosbox.cpp.o -Wl,--as-needed -Wl,--no-undefined '-Wl,-rpath,$ORIGIN/subprojects/munt-libmt32emu_2_5_0:/packages/libsdl2-2.0.14-6/.self/develop/lib:/packages/opusfile-0.12-1/.self/develop/lib:/packages/fluidsynth2-2.1.8-1/.self/develop/lib' -Wl,-rpath-link,/boot/home/Compilar/dosbox-staging-0.77.1/build/subprojects/munt-libmt32emu_2_5_0 -Wl,-rpath-link,/packages/libsdl2-2.0.14-6/.self/develop/lib -Wl,-rpath-link,/packages/opusfile-0.12-1/.self/develop/lib -Wl,-rpath-link,/packages/fluidsynth2-2.1.8-1/.self/develop/lib -Wl,--start-group src/cpu/libcpu.a src/debug/libdebug.a src/dos/libdos.a src/libs/decoders/libdecoders.a src/fpu/libfpu.a src/gui/libgui.a src/libs/ppscale/libppscale.a src/hardware/libhardware.a src/libs/nuked/libnuked.a src/libs/residfp/libresidfp.a src/ints/libints.a src/midi/libmidi.a subprojects/munt-libmt32emu_2_5_0/libmt32emu.so src/misc/libmisc.a src/shell/libshell.a -latomic /packages/libsdl2-2.0.14-6/.self/develop/lib/libSDL2.so /packages/opusfile-0.12-1/.self/develop/lib/libopusfile.so /packages/libpng16-1.6.37-1/.self/develop/lib/libpng16.so /packages/libpng16-1.6.37-1/.self/develop/lib/libz.so /packages/sdl2_net-2.0.1-2/.self/develop/lib/libSDL2_net.so /packages/sdl2_net-2.0.1-2/.self/develop/lib/libSDL2.so /packages/fluidsynth2-2.1.8-1/.self/develop/lib/libfluidsynth.so -Wl,--end-group
src/hardware/libhardware.a(serialport_misc_util.cpp.o): In function `TCPClientSocket::TCPClientSocket(int)':
/boot/home/Compilar/dosbox-staging-0.77.1/build/../src/hardware/serialport/misc_util.cpp:50: undefined reference to `getpeername'
/boot/home/Compilar/dosbox-staging-0.77.1/build/../src/hardware/serialport/misc_util.cpp:59: undefined reference to `getsockname'
collect2: error: ld returned 1 exit status
[228/229] Compiling C++ object tests/support.p/support_tests.cpp.o
ninja: build stopped: subcommand failed.
```

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by kcgen** [comment]
It seems Haiku offers the `sys/socket.h` header but without some necessary network functionality.

I've added checks for these in the latest `main` branch . Curious if this works for you.

**Comment by unspacyar** [comment]
Hi, thanks for your answer!  I tried again with the main branch, but this time I got another error:

`
[45/260] Compiling C++ object src/libs/loguru/libloguru.a.p/loguru.cpp.o
FAILED: src/libs/loguru/libloguru.a.p/loguru.cpp.o 
c++ -Isrc/libs/loguru/libloguru.a.p -Isrc/libs/loguru -I../src/libs/loguru -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wnon-virtual-dtor -Wextra -Wpedantic -std=c++17 -g -Wmaybe-uninitialized -Weffc++ -Wextra-semi -MD -MQ src/libs/loguru/libloguru.a.p/loguru.cpp.o -MF src/libs/loguru/libloguru.a.p/loguru.cpp.o.d -o src/libs/loguru/libloguru.a.p/loguru.cpp.o -c ../src/libs/loguru/loguru.cpp
../src/libs/loguru/loguru.cpp: In function 'loguru::Text loguru::vtextprintf(const char*, va_list)':
../src/libs/loguru/loguru.cpp:431:30: error: 'vasprintf' was not declared in this scope; did you mean 'vsprintf'?
  431 |                 int result = vasprintf(&buff, format, vlist);
      |                              ^~~~~~~~~
      |                              vsprintf
../src/libs/loguru/loguru.cpp: In function 'loguru::Text loguru::errno_as_text()':
../src/libs/loguru/loguru.cpp:572:22: warning: unused variable 'buff' [-Wunused-variable]
  572 |                 char buff[256];
      |                      ^~~~
../src/libs/loguru/loguru.cpp: In function 'void loguru::init(int&, char**, const loguru::Options&)':
../src/libs/loguru/loguru.cpp:622:38: warning: unused variable 'this_thread' [-Wunused-variable]
  622 |                                 auto this_thread = pthread_self();
      |                                      ^~~~~~~~~~~
../src/libs/loguru/loguru.cpp: In function 'void loguru::set_thread_name(const char*)':
../src/libs/loguru/loguru.cpp:1035:42: warning: unused parameter 'name' [-Wunused-parameter]
 1035 |         void set_thread_name(const char* name)
      |                              ~~~~~~~~~~~~^~~~
../src/libs/loguru/loguru.cpp: In function 'void loguru::get_thread_name(char*, long long unsigned int, bool)':
../src/libs/loguru/loguru.cpp:1076:25: error: 'pthread_getname_np' was not declared in this scope
 1076 |                         pthread_getname_np(pthread_self(), buffer, length);
      |                         ^~~~~~~~~~~~~~~~~~
../src/libs/loguru/loguru.cpp:1097:66: error: invalid conversion from 'pthread_t' {aka '_pthread_thread*'} to 'uint64_t' {aka 'long long unsigned int'} [-fpermissive]
 1097 |                                 uint64_t thread_id = pthread_self();
      |                                                      ~~~~~~~~~~~~^~
      |                                                                  |
      |                                                                  pthread_t {aka _pthread_thread*}
[50/260] Compiling C++ object src/dos/libdos.a.p/program_rescan.cpp.o
ninja: build stopped: subcommand failed.
`

**Comment by unspacyar** [comment]
`
[45/260] Compiling C++ object src/libs/loguru/libloguru.a.p/loguru.cpp.o
FAILED: src/libs/loguru/libloguru.a.p/loguru.cpp.o 
c++ -Isrc/libs/loguru/libloguru.a.p -Isrc/libs/loguru -I../src/libs/loguru -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wnon-virtual-dtor -Wextra -Wpedantic -std=c++17 -g -Wmaybe-uninitialized -Weffc++ -Wextra-semi -MD -MQ src/libs/loguru/libloguru.a.p/loguru.cpp.o -MF src/libs/loguru/libloguru.a.p/loguru.cpp.o.d -o src/libs/loguru/libloguru.a.p/loguru.cpp.o -c ../src/libs/loguru/loguru.cpp
../src/libs/loguru/loguru.cpp: In function 'loguru::Text loguru::vtextprintf(const char*, va_list)':
../src/libs/loguru/loguru.cpp:431:30: error: 'vasprintf' was not declared in this scope; did you mean 'vsprintf'?
  431 |                 int result = vasprintf(&buff, format, vlist);
      |                              ^~~~~~~~~
      |                              vsprintf
../src/libs/loguru/loguru.cpp: In function 'loguru::Text loguru::errno_as_text()':
../src/libs/loguru/loguru.cpp:572:22: warning: unused variable 'buff' [-Wunused-variable]
  572 |                 char buff[256];
      |                      ^~~~
../src/libs/loguru/loguru.cpp: In function 'void loguru::init(int&, char**, const loguru::Options&)':
../src/libs/loguru/loguru.cpp:622:38: warning: unused variable 'this_thread' [-Wunused-variable]
  622 |                                 auto this_thread = pthread_self();
      |                                      ^~~~~~~~~~~
../src/libs/loguru/loguru.cpp: In function 'void loguru::set_thread_name(const char*)':
../src/libs/loguru/loguru.cpp:1035:42: warning: unused parameter 'name' [-Wunused-parameter]
 1035 |         void set_thread_name(const char* name)
      |                              ~~~~~~~~~~~~^~~~
../src/libs/loguru/loguru.cpp: In function 'void loguru::get_thread_name(char*, long long unsigned int, bool)':
../src/libs/loguru/loguru.cpp:1076:25: error: 'pthread_getname_np' was not declared in this scope
 1076 |                         pthread_getname_np(pthread_self(), buffer, length);
      |                         ^~~~~~~~~~~~~~~~~~
../src/libs/loguru/loguru.cpp:1097:66: error: invalid conversion from 'pthread_t' {aka '_pthread_thread*'} to 'uint64_t' {aka 'long long unsigned int'} [-fpermissive]
 1097 |                                 uint64_t thread_id = pthread_self();
      |                                                      ~~~~~~~~~~~~^~
      |                                                                  |
      |                                                                  pthread_t {aka _pthread_thread*}
[50/260] Compiling C++ object src/dos/libdos.a.p/program_rescan.cpp.o
ninja: build stopped: subcommand failed.
`

**Comment by unspacyar** [comment]
Sorry, I messed up the text format.  Just in case, there is a picture:

http://0x0.st/-h2a.png

Sorry for the inconveniences.

**Comment by LowLevelMahn** [comment]
its a third party dependency for logging that fails in your build: https://github.com/emilk/loguru

try to build loguru on haiku and report building issues to the loguru project
here is the official example that should build: https://github.com/emilk/loguru/tree/master/loguru_example

following the tradition of build from the smallest to the biggest problematic lib :)

**Comment by kcgen** [comment]
@unspacyar , can you try compiling branch `kc/loguru-haiku-1`?

I'm hoping that Haiku is only missing some superficial functionality.  But we'll see.

I've also submitted this upstream: https://github.com/emilk/loguru/pull/188

**Comment by unspacyar** [comment]
Hi! About the **loguru**, I followed @LowLevelMahn suggestion and it's correct, i got the same error:

`
```
~/Compilar/loguru-2.1.0/loguru_example> ./build_and_run.sh 
CMake Deprecation Warning at CMakeLists.txt:1 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


-- The C compiler identification is GNU 11.2.0
-- The CXX compiler identification is GNU 11.2.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /boot/system/bin/x86/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /boot/system/bin/x86/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- CMAKE_BUILD_TYPE: Debug
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE  
-- Configuring done
-- Generating done
-- Build files have been written to: /boot/home/Compilar/loguru-2.1.0/loguru_example/build
[ 50%] Building CXX object CMakeFiles/loguru_example.dir/main.cpp.o
In file included from /boot/home/Compilar/loguru-2.1.0/loguru_example/main.cpp:5:
/boot/home/Compilar/loguru-2.1.0/loguru_example/../loguru.cpp: In function 'loguru::Text loguru::vtextprintf(const char*, va_list)':
/boot/home/Compilar/loguru-2.1.0/loguru_example/../loguru.cpp:391:30: error: 'vasprintf' was not declared in this scope; did you mean 'vsprintf'?
  391 |                 int result = vasprintf(&buff, format, vlist);
      |                              ^~~~~~~~~
      |                              vsprintf
/boot/home/Compilar/loguru-2.1.0/loguru_example/../loguru.cpp: In function 'loguru::Text loguru::errno_as_text()':
/boot/home/Compilar/loguru-2.1.0/loguru_example/../loguru.cpp:528:22: error: unused variable 'buff' [-Werror=unused-variable]
  528 |                 char buff[256];
      |                      ^~~~
/boot/home/Compilar/loguru-2.1.0/loguru_example/../loguru.cpp: In function 'void loguru::init(int&, char**, const loguru::Options&)':
/boot/home/Compilar/loguru-2.1.0/loguru_example/../loguru.cpp:578:38: error: unused variable 'this_thread' [-Werror=unused-variable]
  578 |                                 auto this_thread = pthread_self();
      |                                      ^~~~~~~~~~~
/boot/home/Compilar/loguru-2.1.0/loguru_example/../loguru.cpp: In function 'void loguru::set_thread_name(const char*)':
/boot/home/Compilar/loguru-2.1.0/loguru_example/../loguru.cpp:919:42: error: unused parameter 'name' [-Werror=unused-paramete]
  919 |         void set_thread_name(const char* name)
      |                              ~~~~~~~~~~~~^~~~
/boot/home/Compilar/loguru-2.1.0/loguru_example/../loguru.cpp: In function 'void loguru::get_thread_name(char*, long long unsigned int, bool)':
/boot/home/Compilar/loguru-2.1.0/loguru_example/../loguru.cpp:979:54: error: invalid conversion from '_pthread_thread*' to 'uint64_t' {aka 'long long unsigned int'} [-fpermissive]
  979 |                                 uint64_t thread_id = thread;
      |                                                      ^~~~~~
      |                                                      |
      |                                                      _pthread_thread*
cc1plus: all warnings being treated as errors
CMakeFiles/loguru_example.dir/build.make:75: recipe for target 'CMakeFiles/loguru_example.dir/main.cpp.o' failed
make[2]: *** [CMakeFiles/loguru_example.dir/main.cpp.o] Error 1
CMakeFiles/Makefile2:82: recipe for target 'CMakeFiles/loguru_example.dir/all' failed
make[1]: *** [CMakeFiles/loguru_example.dir/all] Error 2
Makefile:90: recipe for target 'all' failed
make: *** [all] Error 2
~/Compilar/loguru-2.1.0/loguru_example> 
```
`

@kcgen : about the **loguru-haiku** branch, I also hit another issue with the **whereami** library:

```
~/Compilar/dosbox-staging-kc-loguru-haiku-1> ninja -C build
ninja: Entering directory `build'
[49/260] Generating symbol file subprojects/munt-libmt32emu_2_5_3/libmt32emu.so.p/libmt32emu.so.symbols
WARNING: Symbol extracting has not been implemented for this platform. Relinking will always happen on source changes.
[94/260] Compiling C object src/libs/whereami/libwhereami.a.p/whereami.c.o
FAILED: src/libs/whereami/libwhereami.a.p/whereami.c.o 
cc -Isrc/libs/whereami/libwhereami.a.p -Isrc/libs/whereami -I../src/libs/whereami -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wextra -Wpedantic -g -MD -MQ src/libs/whereami/libwhereami.a.p/whereami.c.o -MF src/libs/whereami/libwhereami.a.p/whereami.c.o.d -o src/libs/whereami/libwhereami.a.p/whereami.c.o -c ../src/libs/whereami/whereami.c
../src/libs/whereami/whereami.c:790:2: error: #error unsupported platform
  790 | #error unsupported platform
      |  ^~~~~
[99/260] Compiling C++ object src/dos/libdos.a.p/cdrom_image.cpp.o
ninja: build stopped: subcommand failed.
~/Compilar/dosbox-staging-kc-loguru-haiku-1> 
```

I will try to investigate more about this two issues from this libs.  Maybe I could get some help from the Haiku team too.
Thanks a lot for your help!!!

**Comment by kcgen** [comment]
Thanks @unspacyar; I think we've got Loguru fixed up for Haiku.

Next up is the https://github.com/gpakosz/whereami library.  

This library lets us get the path where the dosbox binary lives in the host filesystem.

Would you be able to file this build issue with that project?
Please let them know that it's not compiling on Haiku with the error message from above.  Maybe they can add a "best effort" level of support, which might be better than nothing. 

I will also try to add some checks and work around it; but that will mean some features (like portable assets) probably won't work on Haiku.

**Comment by kcgen** [comment]
Updates were pushed to address this issue, however the user has not responded.
Assuming closed until we hear otherwise.
