### ISSUE TITLE
kc/lang-priority-1: Language isn't automatically set through $LANG on german macOS

### ISSUE THREAD

**Issue by Burrito78** [dosbox-staging/dosbox-staging#1425]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Different version than latest?

kc/lang-priority-1

### What Operating System are you using?

Mac OS

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

With default config, german language file isn't used automatically although $LANG = de_DE.UTF-8.

Everything else about this branch is working as expected.

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Freshly install above branch on german macOS
2. Run
3. Observe english language file used.

### Your configuration

```ini
default
```

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by kcgen** [comment]
When launched from the Finder, the locale will provide the language instead of LANG via the shell.
