### ISSUE TITLE
Pair character sets with languages

### ISSUE THREAD

**Issue by kcgen** [dosbox-staging/dosbox-staging#1438]
https://www.vogons.org/viewtopic.php?t=21824

If the users sets a language on startup (in the conf / `LANG=` or locale via environment / `-lang ..` arg), then:
 1. Construct a KEYB command line argument with corresponding code-page selection
 2. Add that KEYB call to the on-the-fly constructed autoexec sequence (similar to `SET BLASTER=`).
 
This will be better supported when we can bundle FreeDOS commands and add them to the PATH.

**Comment by Burrito78** [comment]
@kcgen A detected/set language will properly load the correct keyboard layout and select the proper codepage so i'm closing this now, reopen please if this is something else.
