### ISSUE TITLE
Trouble with Discord

### ISSUE THREAD

**Issue by Grounded0** [dosbox-staging/dosbox-staging#1439]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Whats your question and how can we help?

I have trouble accessing Luxtorpeda server. Is this universal problem with the server now or am i alone with this?

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by Grounded0** [comment]
![2021-12-15_12-30](https://user-images.githubusercontent.com/48192273/146264403-98200523-5d07-4473-a26d-862710b07991.png)

I'm not seen on the server yet i can chat with anyone on the server normally:

<img width="296" alt="Screenshot 2021-12-15 at 23 01 07" src="https://user-images.githubusercontent.com/48192273/146264472-95344d99-1e80-4754-9165-1e21a37a6866.png">

**Comment by Grounded0** [comment]
I'm including @dreamer in this ticket as he's responsible for operation of Luxtorpeda project Discord server:

![Screenshot_20211216-020932](https://user-images.githubusercontent.com/48192273/146284944-5c98277b-5192-4d26-b8bb-7793bc86f35a.png)

![Screenshot_20211216-020953](https://user-images.githubusercontent.com/48192273/146284959-e5faa14c-2deb-496c-9d66-7518228976ed.png)

**Comment by Grounded0** [comment]
Adding @Discord in this ticket.

**Comment by Grounded0** [comment]
![Screenshot_20211216-043402](https://user-images.githubusercontent.com/48192273/146298263-aa02e55f-5f14-4a9f-bb8d-a02478065346.png)

Guessed it. Oper left phone unlocked in pocket and it managed to ban me. Closed.

**Comment by kcgen** [comment]
PEBKAC
🏳️ oper, reporting for duty 😅
