### ISSUE TITLE
[BUG] mount does not work with git version

### ISSUE THREAD

**Issue by LowLevelMahn** [dosbox-staging/dosbox-staging#1444]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Different version than latest?

git/currently 528caea358f706383433868974f2c35fd2097e21

### If Other OS, please describe

Windows

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

mount seems to only mount the drive no subdirectories anymore

### Steps to reproduce the behaviour.

mount c f:\blub\tralala just mounts f:
mount x d:\temp\trial just mounts d:

### Your configuration

```ini
i did let dosbox create a fresh git config
```

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by LowLevelMahn** [comment]
![image](https://user-images.githubusercontent.com/580819/146632890-36d1ef1f-9816-4b09-9f9f-c3b5824bd338.png)

**Comment by Wengier** [comment]
So I believe it is probably the same bug that I was experiencing in macOS VM:

![image](https://user-images.githubusercontent.com/8216923/146636083-aa82468b-d1fa-46e3-9dce-983338fc41a2.png)

**Comment by kcgen** [comment]
Thanks @Wengier. Indeed, the revert in this PR should have this regression solved.
