### ISSUE TITLE
[BUG] Continuum/Alpha Waves: Slow due to blocked IO-Port 03d0h?

### ISSUE THREAD

**Issue by LowLevelMahn** [dosbox-staging/dosbox-staging#1448]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Different version than latest?

git

### What Operating System are you using?

Windows 10

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

the game flickers alot and seems to be very slow in the intro animation

the only thing that is noticeable is the log gets cluttered with many many lines of port 0x3d0 write accesses blocks

```
IO:IOBUS: Unexpected write of 1 to 03d0h; blocking
IO:IOBUS: Unexpected write of 2 to 03d0h; blocking
IO:IOBUS: Unexpected write of 4 to 03d0h; blocking
IO:IOBUS: Unexpected write of 8 to 03d0h; blocking
IO:IOBUS: Unexpected write of 16 to 03d0h; blocking
IO:IOBUS: Unexpected write of 32 to 03d0h; blocking
IO:IOBUS: Unexpected write of 64 to 03d0h; blocking
IO:IOBUS: Unexpected write of 128 to 03d0h; blocking
```

according to Ralph Brown's port overview: 
https://github.com/cirosantilli/ralf-brown-interrupt-list/blob/fde1a5ac1b7e8a45ff4255ee275ee77c7fe7e256/inter61d/PORTS.B#L5615

```
03D0  -W  same as PORT 03D4h  <=================!!!
03D1  RW  same as PORT 03D5h
03D2  -W  same as PORT 03D4h
03D3  RW  same as PORT 03D5h
--------V-P03D403D5--------------------------
PORT 03D4-03D5 - COLOR VIDEO - CRT CONTROL REGISTERS
03D4  rW  CRT (6845) register index   (CGA/MCGA/color EGA/color VGA)  <=================!!!
	selects which register (0-11h) is to be accessed through 03D5
	this port is r/w on some VGA, e.g. ET4000
	    bit 7-6 =0: (VGA) reserved
	    bit 5   =0: (VGA) reserved for testage
	    bit 4-0   : selects which register is to be accessed through 03D5
```

its seems to be some sort of mirrored port

is there something missing in dosbox staging or is that programming bug/wrong behavior of the game?

### Steps to reproduce the behaviour.

get the clean floppy image as 7z from: https://archive.org/details/002297-AlphaWaves
start the game, press F5 (for VGA) and the F1 for starting

see the flickering and log exploding after the armadillo intro picture scrolled in

### Your configuration

```ini
freshly created, empty config file
```

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by Grounded0** [comment]
Does this happen with normal DOSBox too?

**Comment by LowLevelMahn** [comment]
does not happen with DOSBox SVN
does not happen with  DOSBox Staging v0.77.1

**Comment by Grounded0** [comment]
Linking here as a technical reference relating to the regression:

https://anttipeltola.eu/docs/tech/ibm_vga_technical_reference.pdf

**Comment by LowLevelMahn** [comment]
what is the relation to this document - i can't find the port?

**Comment by Grounded0** [comment]
"CRT Controller Registers"

**Comment by kcgen** [comment]
@LowLevelMahn , I am seeing the same behavior versus DOSBox SVN and DOSBox-X, when running the `main` branch: https://dosbox-staging.github.io/downloads/devel/

Can you try those builds?

**Comment by LowLevelMahn** [comment]
>I am seeing the same behavior versus DOSBox SVN 

freshly build VS2022 Dosbox SVN runs without flicker (also fresh config) on my side - strange

> Indeed, 03D0 is not a valid CRT control register per @Grounded0 's reference document.

according to ralph browns list these are mirrored ports

here is an articel about these mirrored ports
https://www.vogons.org/viewtopic.php?t=18311

**Comment by kcgen** [comment]
Found the game on original hardware, VGA mode:
 - https://www.youtube.com/watch?v=ukSuCG1L5Gs

And Circa 2016 DOSBox, VGA mode:
 - https://www.youtube.com/watch?v=jN9KKnfwoNY
 - https://www.youtube.com/watch?v=u9qAtVwSIV8

All look similar, so DOSBox is doing the right thing.

**Comment by LowLevelMahn** [comment]
> here is an articel about these mirrored ports
> https://www.vogons.org/viewtopic.php?t=18311

what about the port mirroring - isn't that missing?
 (not to fix any bug but to be more compatible)
