### ISSUE TITLE
Terminal mode for DOS development (ANSI passthrough or curses text mode)

### ISSUE THREAD

**Issue by promovicz** [dosbox-staging/dosbox-staging#1450]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Is your feature request related to a problem? Please describe.

My main use case for dosbox is for development. For that I currently use a dosbox window, but it would be extremely convenient if dosbox would support terminal text mode. An application that uses only console/ANSI output could potentially run without curses by simple passthrough and be part of the terminal experience like any other POSIX command.

### Describe the solution you'd like

I imagine it would be possible to specify a DOS command on the dosbox commandline:

```
Usage: dosbox [command...]
```

A simple implementation could use curses to display any of the already supported character cell text modes. Smart screen management could be used to make the "DOS subwindow" appear in the right place in the terminal for the output to appear contigouos.

An alternative and more advanced implementation could pass through console/ANSI output so that DOS application output can be printed on the terminal as if it were POSIX output. Such an implementation could also engage graphics mode when required, opening an SDL window for the VGA while showing either a blank screen or text mode contents on the terminal.

For simple development use it might be sufficient to have only an ANSI pass-through mode, but it is likely that many tools will break under such circumstances.

```
$ dosbox dir
Volume in drive C is C_DRIVE     
 Directory of  c:\bc31\*.*

.            <DIR>       1-23-18   2:07 
..           <DIR>      12-20-21  23:33 
BGI          <DIR>       1-22-18   8:15 
BIN          <DIR>       2-02-18   8:19 
CLASSLIB     <DIR>       1-22-18   8:16 
CRTL         <DIR>       1-22-18   8:15 
DOC          <DIR>       1-22-18   8:17 
EXAMPLES     <DIR>       1-22-18   8:19 
INCLUDE      <DIR>       1-23-18  20:27 
LIB          <DIR>       1-23-18   2:07 
TVISION      <DIR>       1-22-18   8:19 
bc31p1.mrk           0   1-23-18   2:07 
bc32p2.mrk           0   1-23-18   2:07 
filelist.doc    121614   1-22-18   8:17 
readme           56343   1-22-18   8:18 
readme.com        4217   1-22-18   8:18 
        182,174 bytes in 5 files and 11 dirs    260,096 bytes allocated
    262,111,744 bytes free
```

### Describe alternatives you've considered

None. This is just an idea I am trying to share.

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by arrowgent** [comment]
id love a switch for input/output from a *nix terminal
but it does seem rather complex and beyond scope of what dosbox is designed to provide

even minimum the -switch could provide output of text displayed in dosbox into the terminal
