### ISSUE TITLE
[BUG] CHOICE return code is not received properly

### ISSUE THREAD

**Issue by NicknineTheEagle** [dosbox-staging/dosbox-staging#1455]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### What Operating System are you using?

Windows 10

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

If the built-in CHOICE program is called from another program (not from shell), the return code is not received by the calling program properly.
From what I can tell, when you run CHOICE normally via shell dos.return_code gets initially set to the right value in DOS_Shell::CMD_CHOICE, then reset to 0 by DOS function 4ch (why?) and then set back to proper value in DOS_Shell::Execute.
When you run CHOICE from another program, the last step is omitted so return code remains stuck at 0. This likely affects all emulated programs on Z: drive. Can be worked around by putting an external CHOICE.COM in PATH (e.g. from FreeDOS).

### Steps to reproduce the behaviour.

Can be reproduced in this simple game (needs codepage 866): [MENT.ZIP](https://github.com/dosbox-staging/dosbox-staging/files/7768178/MENT.ZIP) Although it should be easily possible to write a basic test app using CHOICE.
1. On title screen press 1 to proceed.
2. The screen that says "Поехали?" uses CHOICE. Pressing 2 should go back to intro sequence but since CHOICE return code is lost it acts same as 1.

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by Wengier** [comment]
It is hopefully fixed in PR #1460.
