### ISSUE TITLE
[Feature] linux bash completion documentation

### ISSUE THREAD

**Issue by arrowgent** [dosbox-staging/dosbox-staging#1471]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Different version than latest?

0.78.0

### What Operating System are you using?

Linux x86_64

### Is your feature request related to a problem? Please describe.

no problem

### Describe the solution you'd like

short summary of how to use bash_completion
https://github.com/dosbox-staging/dosbox-staging/blob/main/contrib/linux/bash-completion/README

i had to read through the document to see how to use it, it should be more obvious for showing an example

`dosbox -h` shows the list of bash features
`dosbox -v` very good! this is much improved than previously showing the full version string
the main tool i can use this for is
`dosbox -machine type` starting dosbox in a unique mode such as `tandy` without having to exit and modify the dosbox-staging.conf

### Describe alternatives you've considered

although this should be fairly obvious.  its been a billion years since any version of dosbox accepted a `-switch` at runtime
even dosbox-svn just ignores --version or -v or -h or --help
and previous versions of dosbox-staging ignored these terminal switches

### Add any other context or screenshots about the feature request here.

```
Usage: dosbox [OPTION]... [FILE]

These are common options:

  -h, --help          Displays this message.

  --printconf         Prints the location of the default configuration file.

  --editconf          Open the default configuration file in a text editor.

  -c <command>        Runs the specified DOS command before running FILE.
                      Multiple commands can be specified.

  -noautoexec         Don't perform any [autoexec] actions.

  -noprimaryconf      Don't read settings from the primary configuration file
                      located in ~/.config/dosbox/dosbox-staging.conf.

  -nolocalconf        Don't read settings from "dosbox.conf" if present in
                      the local current working directory.

  -conf <configfile>  Start dosbox with the options specified in <configfile>.
                      Multiple configfiles can be present at the commandline.

  -fullscreen         Start dosbox in fullscreen mode.

  -lang <langfile>    Start dosbox with the language specified in
                      <langfile>.

  -machine <type>     Setup dosbox to emulate a specific type of machine.
                      The machine type has influence on both the videocard
                      and the emulated soundcards.  Valid choices are:
                      hercules, cga, cga_mono, tandy, pcjr, ega, vgaonly,
                      svga_s3 (default), svga_et3000, svga_et4000,
                      svga_paradise, vesa_nolfb, vesa_oldvbe.

  -exit               Dosbox will close itself when the DOS program
                      specified by FILE ends.

  -v, --version       Output version information and exit.

You can find full list of options in the man page: dosbox(1)
And in file: /usr/share/doc/dosbox-staging/README
```

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by kcgen** [comment]
Adding @FeignInt and @rderooy , as completion has now landed for DOSBox-X.
If there's any overlap , user would benefits from having a similar understanding. 

@arrowgent , regarding adding more help, we can append the wording you've provided (follows) to the README: 

```
dosbox -h shows the list of bash features
dosbox -v very good! this is much improved than previously showing the full version string
the main tool i can use this for is
dosbox -machine type starting dosbox in a unique mode such as tandy without having to exit and modify the dosbox-staging.conf
```

**Comment by arrowgent** [comment]
actually, this is documented in README
https://github.com/dosbox-staging/dosbox-staging/blob/main/README

no need to expand the documentation here.
