### ISSUE TITLE
A completely full-screen or filled screen option

### ISSUE THREAD

**Issue by Jkapp76** [dosbox-staging/dosbox-staging#1474]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### What Operating System are you using?

Windows 11

### Is your feature request related to a problem? Please describe.

not really a problem. But, the only reason I still keep DOSBox-X around is for certain games that I like to play with the maximized full-screen. No bars at all is best for quite a few games.

### Describe the solution you'd like

Whatever DOSBox-X does to make the whole screen filled with the emulation view, having no black bars at all. 

If you set it to (fullscreen) and (aspect = false) you get a filled screen type of full screen.

I think both options would be best. Keep fullscreen as an option and add filled screen or something as an alternative?

### Describe alternatives you've considered

Just DOSBox-X. I'd like to be rid of it once and for all, but I prefer it's maximized full-screen for a handful of games. I also play some text adventures and text-only programs that benefit from full-screen.

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by arrowgent** [comment]
is that stretching 4:3 to 16:9 ?

**Comment by Wengier** [comment]
While it is true that filled screen mode works in some outputs in DOSBox-X, I don't really think all of its outputs support this mode. The surface and openglpp outputs there for example do not support filled screen mode, regardless of the aspect setting. In DOSBox Staging you can almost achieve filled screen mode with ``aspect=false`` in full-screen mode, although I think completely filled screen mode may also be useful for some. Compared with DOSBox-X, DOSBox Staging is more oriented towards gaming.

**Comment by kcgen** [comment]
I remember there was a trick that works with most DOSBoxes to maximize the horizontal stretching: set fullscreen to true, then set fullresolution to a 4:3 resolution that you know the monitor supports natively, something like 800x600 or 1024x768. Finally, set aspect to false. 
I remember on my Pi + 720p widescreen, that I could get a fully stretched image using DOSBox-X, SVN, and Staging.  SDL 1.2 seems to do an even better job, because it tries to set that lower resolution video mode. 

This trick worked great on older 16:9 displays; my newer 4k display interprets the 4:3 mode and refuses to stretch it though. So in this case, we would need to do the stretching upstream in SDL prior to sending it out.

**Comment by Jkapp76** [comment]
I'll play with this more tomorrow. I think some extra setting to help stretch the horizontal would be great. Maybe an sdl 1.2 version if that isn't too difficult... That might get more joysticks to work? 

⁣Get BlueMail for Android ​

On Dec 28, 2021, 11:07 PM, at 11:07 PM, kcgen ***@***.***> wrote:
>I remember there was a trick that works with most DOSBoxes to maximize
>the horizontal stretching: set fullscreen to true, then set
>fullresolution to a 4:3 resolution that you know the monitor supports
>natively, something like 800x600 or 1024x768. Finally, set aspect to
>false. 
>I remember on my Pi + 720p widescreen, that I could get a fully
>stretched image using DOSBox-X, SVN, and Staging.  SDL 1.2 seems to do
>an even better job, because it tries to set that lower resolution video
>mode. 
>
>This trick worked great on older 16:9 displays; my newer 4k display
>interprets the 4:3 mode and refuses to stretch it though. So in this
>case, we would need to do the stretching upstream in SDL prior to
>sending it out. 
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/dosbox-staging/dosbox-staging/issues/1474#issuecomment-1002388053
>You are receiving this because you authored the thread.
>
>Message ID:
***@***.***>

**Comment by johnnovak** [comment]
I'm inclined to close this. We removed the "pixel perfect" mode and gave users aspect ratio preserving integer scaling per one axis only. This would add another possibility to completely disregard the aspect ratio, even more than aspect=off (which is warranted and has its use cases). @kcgen @Grounded0 ?

**Comment by Jkapp76** [comment]
I'm getting caught up here...

So we can now fill the screen even more than the (aspect=off) setting?
I think filling up the screen any more than the standard aspect=off did justifies closing this.

**Comment by johnnovak** [comment]
> I'm getting caught up here...
> 
> So we can now fill the screen even more than the (aspect=off) setting? I think filling up the screen any more than the standard aspect=off did justifies closing this.

No we can't.

What I'm saying, we shouldn't really have this option. We've been steering people away from using incorrect, random aspect ratios in the recent stream of additions/enhancements, as mentioned. Then just giving them an option that goes like "yeah, whatever... just stretch this to the viewport size, I don't care" seems to fly in the face of all that.

Hence, I'm inclined to close this _with prejudice_ 😎

**Comment by Jkapp76** [comment]
I get that. I like that stretched screen for certain games. Like full screen text adventures and a few others. For the most part I prefer a properly shaped screen. I like it purposefully wrong only in those rare cases. I tend to play those rare few games though too. I'm certainly happy with whatever is best overall.

**Comment by johnnovak** [comment]
> I get that. I like that stretched screen for certain games. Like full screen text adventures and a few others. For the most part I prefer a properly shaped screen. I like it purposefully wrong only in those rare cases. I tend to play those rare few games though too. I'm certainly happy with whatever is best overall.

To be honest, maybe the solution for you would be a custom build or something.

**Comment by Jkapp76** [comment]
I play through the original mainframe Zork game every year or so. I even have a perfect reproduction of the original hand-drawn game map by the 1977 MIT team, only updated to include those few later-added places. (I know, nerd)

I use DOSBox-X for this one game and a few others like this, but it's not really worth much to me for this feature. I like it, but I wouldn't miss it much if it was completely unavailable... 

![20230630_231600](https://github.com/dosbox-staging/dosbox-staging/assets/89743985/3eae6713-78f3-4b08-9a7c-4598fb46a535)

**Comment by johnnovak** [comment]
> I play through the original mainframe Zork game every year or so. I even have a perfect reproduction of the original hand-drawn game map by the 1979 MIT team, only updated to include those few later-added places. (I know, nerd)

That's really nice, man 👍🏻 Funny, I was thinking it's time to play Zork (for the first time!) just an hour ago during my afternoon walk. Which version would you recommend?

I was thinking of r88 by Infocom from here; that is supposed to be "most common final version" based on my understanding:
https://eblong.com/infocom/#zork1

Btw, I'm using this Z-machine interpreter to play old Infocom adventure games:
https://ccxvii.net/gargoyle/ 

Also, closing this ticket then.

**Comment by Jkapp76** [comment]
@johnnovak 

There are many versions of Zork, all of them including different puzzles and things as they went, and the final version is cut into three parts: Zork 1, 2 and 3. This final version omits many great puzzles too.

I have the absolute best version here. It's the most complete version before they broke it into three parts. 
I made you a special zip file containing the full game, the best illustrated solution (some puzzles are almost impossible to figure out) AND I also include a copy of the full original Map.

https://u.pcloud.link/publink/show?code=XZC5XIVZJ3aHr578ljkUudH38VzS6FVSUUoX

**Comment by johnnovak** [comment]
Thanks a lot for this @Jkapp76, much appreciated! ❤️  Looks like I'm going to have some quality fun-time soon! 😄
