### ISSUE TITLE
[BUG] Delay when exiting DOSBox in fullscreen mode

### ISSUE THREAD

**Issue by johnnovak** [dosbox-staging/dosbox-staging#1484]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Different version than latest?

I'm using the latest 0.78 release.

### What Operating System are you using?

Windows 10 (64-bit)

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

It seems I found a regression: when exiting DOSBox in fullscreen mode (either by using the exit command, or by pressing Alt-F4), there's an about 2 second delay before the application actually exits. During this period, the DOSBox window is "stuck" on the screen, usually with some garbage content.

The problem doesn't happen in windowed mode, only in fullscreen, and only with the `opengl*` backends. When using the `surface` and `texture` backends, the app exits immediately from fullscreen mode as well, as expected.

It's not a huge issue, but slightly annoying, and the problem did not exist in the previous version. Most likely some SDL weirdness...

I guess a dead simple workaround would be to switch back to windowed when receiving a window close event, then exit (same when the user explicitly types `exit`).

### Steps to reproduce the behaviour.
1. Start DOSBox with the default config (or make sure to use the `opengl` backend)
2. Enter fullscreen with Alt-Enter (or set `fullscreen` to `on` in the config, makes no difference how you enable fullscreen mode)
3. Exit by either typing `exit` or pressing Alt-F4.
4. Note that the application doesn't exit immediately, but there's an about 2 second delay.
5. Repeat in windowed mode with the `opengl` backend -> the application exits immediately
6. Repeat in fullscreen mode with the `texture` and `surface` backends -- the application exits immediately

### Your configuration

The problem manifests with the default config.

### Provide a Log

There's nothing remarkable in the logs, I've checked.

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by Grounded0** [comment]
This is a known regression in 0.78.0. It is already fixed in upcoming 0.78.1.

**Comment by GranMinigun** [comment]
I suspect it's already resolved by https://github.com/dosbox-staging/dosbox-staging/pull/1466. Could you please try a build from here? https://github.com/dosbox-staging/dosbox-staging/actions/runs/1639477448

**Comment by johnnovak** [comment]
Cheers, I'll test it tomorrow! But by the description it seems it's the exact same issue.

**Comment by johnnovak** [comment]
Confirmed, it's fixed in https://github.com/dosbox-staging/dosbox-staging/commit/f083659a26056a49e54f7374842c73d12b4207c8
