### ISSUE TITLE
VESA resolutions and refresh rates

### ISSUE THREAD

**Issue by Kappa971** [dosbox-staging/dosbox-staging#1486]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Different version than latest?

DOSBox 0.79.0-alpha-31-g5352e

### What Operating System are you using?

Windows 11

### Whats your question and how can we help?

I wanted to open a new problem to try to better understand what is happening with VESA resolutions, taking up what was discussed here: https://github.com/dosbox-staging/dosbox-staging/issues/1482
We were talking about Quake as an example, and the various resolutions and refresh rates.  I've only tested up to 640x480 for performance reasons with 144hz Freesync monitor.
I ran dosbox_with_debugger.exe with Quake and I copied the following lines trying to understand something:
1. 320x200 resolution
    `3738591867: VGA:v total 14,26812 (70,09Hz) blank(12,93347/14,04568) retrace(13,09235/13,15591)`
    `3738591867: VGA:VGA: Width 320, Height 200, fps 70,086`
    `DISPLAY: VGA 320x200 8-bit (mode 13h) scaling by 4,5x5,4 to 1440x1080 with 1,20 pixel-aspect`
2. VESA 640x480 (DOSBox 0.78.0)
    `3869681236: VGA:v total 6,96056 (143,67Hz) blank(6,47000/6,85449) retrace(6,49652/6,52304)`
    `3869681236: VGA:VGA: Width 640, Height 480, fps 143,667`
    `DISPLAY: VESA 640x480 8-bit (mode 101h) scaling by 2,7x2,2 to 1728x1080 with 0,833 pixel-aspect` 
3. VESA 640x480 (DOSBox 0.79.0 alpha)
    `2810658767: VGA:v total 14,28426 (70,01Hz) blank(13,27756/14,06659) retrace(13,33197/13,38639)`
    `2810658767: VGA:VGA: Width 640, Height 480, fps 70,007`      
    `DISPLAY: VESA 640x480 8-bit (mode 101h) scaling by 2,7x2,2 to 1728x1080 with 0,833 pixel-aspect`

DOSBox 0.78.0 seems to set the emulator refresh rate equal to that of the monitor and produce about 143fps (?) according to the debugger, while within DOSBox the fps counter indicates 72 fps. Monitor tries to sync at 72 fps but stuttering is present. Why doesn't the debugger report 72 fps?

At 320x200 (that is not a VESA resolution from what I understand), in addition to stuttering, there is tearing despite the Freesync monitor

The behavior of DOSBox 0.79.0 alpha I think is the same that DOSBox has always had (DOSBox 0.77 and lower).

I tried Duke Nukem 3D with DOSBox 0.78.0 in 640x480 mode. In the game 109fps is reported, with the debugger continuing to claim 143hz and 143fps. So I guess Quake is running at 143hz/72fps (with the debugger indicating 143hz/143fps). Stuttering is also present in Duke Nukem 3D, so there must be something wrong between the emulator and the monitor.

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by Kappa971** [comment]
According to this issue https://github.com/dosbox-staging/dosbox-staging/issues/953, VESA resolutions can work at refresh rates above 70hz. That's what DOSBox 0.78.0 does. In the case of DOSBox 0.79.0 alpha, it sets 70hz for all VESA resolutions, limiting e.g. Quake and Duke Nukem 3D to 70fps, so it shouldn't matter if the game runs at 70hz, 72hz or 144hz (that's at least what I have understood). However Quake at 640x480 70hz / 70fps, seems to skip frames despite the fixed 70 fps (DOSBox 0.79.0 alpha). The situation gets worse at 640x480 144hz / 72fps (DOSBox 0.78.0).
In Quake at 320x200 (non-VESA), again it doesn't feel perfectly smooth and there is tearing present, as if the game is not syncing with the monitor at all.
I tried other non-VESA games (320x200):
1. Heretic, same problem as Quake.
2. Wolfenstein 3D there is no tearing but he also suffers from stuttering.
Anyway it seems that DOSBox doesn't get along very well with my monitor, it is as if it gives the monitor the wrong fps and therefore there is stuttering (and tearing in some 320x200 games).

I don't know if everything I've written is correct, I'm here on purpose to try to understand and help. I deleted some things previously written because I realized they were irrelevant or wrong.

**Comment by Kappa971** [comment]
According to this issue https://github.com/dosbox-staging/dosbox-staging/issues/953, VESA resolutions can work at refresh rates above 70hz. That's what DOSBox 0.78.0 does. In the case of DOSBox 0.79.0 alpha, it sets 70hz for all VESA resolutions, limiting e.g. Quake and Duke Nukem 3D to 70fps, so it shouldn't matter if the game runs at 70hz, 72hz or 144hz (that's at least what I have understood). However Quake at 640x480 70hz / 70fps, seems to skip frames despite the fixed 70 fps (DOSBox 0.79.0 alpha). The situation gets worse at 640x480 144hz / 72fps (DOSBox 0.78.0).
In Quake at 320x200 (non-VESA), again it doesn't feel perfectly smooth and there is tearing present, as if the game is not syncing with the monitor at all.
I tried other non-VESA games (320x200):
1. Heretic, same problem as Quake.
2. Wolfenstein 3D there is no tearing but he also suffers from stuttering.
Anyway it seems that DOSBox doesn't get along very well with my monitor, it is as if it gives the monitor the wrong fps and therefore there is stuttering (and tearing in some 320x200 games).

I don't know if everything I've written is correct, I'm here on purpose to try to understand and help. I deleted some things previously written because I realized they were irrelevant or wrong.

**Comment by kcgen** [comment]
Thanks for all your comments @Kappa971.
I've been working through the issues on order, so haven't had time to focus on this and give meaningful feedback, but everything you've mentioned is correct. 

We explored customizing the VESA refresh rate in the mid-78 alpha cycle (supported with conf settings), Bur couldn't identify any cases were lowring the rate from 70 Hz to the monitor's 60 Hz limit actually helped (in many cases, it caused flickering).  However, for people with 75 Hz / 85 Hz CRTs and LCDs, it seemed to do no harm.  So I added the allowance to go upward to the host's rate. 

Unfortunately, with 144 Hz monitors, allowing 144 Hz  put too much rendering pressure on DOSBox and performance expectedly suffered. (On top of that, 144 Hz is beyond VESA 120 Hz limit).

So maybe there's a happy medium allowing slightly faster VESA rates if the monitor supports it. But that will have to be proven with tests that show real benefits. This will come after all the pressing 0.78.1 issues are dealt with.  Thanks for your patience @Kappa971 .

**Comment by Kappa971** [comment]
> Thanks for all your comments @Kappa971. I've been working through the issues on order, so haven't had time to focus on this and give meaningful feedback, but everything you've mentioned is correct.
> 
> We explored customizing the VESA refresh rate in the mid-78 alpha cycle (supported with conf settings), Bur couldn't identify any cases were lowring the rate from 70 Hz to the monitor's 60 Hz limit actually helped (in many cases, it caused flickering). However, for people with 75 Hz / 85 Hz CRTs and LCDs, it seemed to do no harm. So I added the allowance to go upward to the host's rate.

For those who own a 60hz monitor, 70hz/fps DOS games don't work very well: there is tearing or, if you force vsync, the tearing disappears but the game still works badly. This is what I noticed when I owned a 60hz monitor. They are not ideal for DOS games.

The problem here is that DOSBox currently doesn't work smoothly even with a Freesync monitor, with stuttering and tearing, whether in VESA mode or not (as already described).

> Unfortunately, with 144 Hz monitors, allowing 144 Hz put too much rendering pressure on DOSBox and performance expectedly suffered. (On top of that, 144 Hz is beyond VESA 120 Hz limit).
>
> So maybe there's a happy medium allowing slightly faster VESA rates if the monitor supports it. But that will have to be proven with tests that show real benefits. This will come after all the pressing 0.78.1 issues are dealt with. 

In fact I noticed that with VESA at 144hz the issues get worse.

>Thanks for your patience @Kappa971 .

Thanks to you :)

**Comment by Kappa971** [comment]
I think a lot of progress has been made and different aspects of DOS games explained in the other issue regarding variable refresh rate, so I think this issue can be closed.
