### ISSUE TITLE
[Question] Has v0.78.1 been released?

### ISSUE THREAD

**Issue by oturpe** [dosbox-staging/dosbox-staging#1488]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Different version than latest?

That is what I am trying to find out...

### Whats your question and how can we help?

Has version v0.78.1 been released?
Is it safe to package the `v0.78.1` tag in distributions?

What is see is:
* There is [tag v0.78.1](https://github.com/dosbox-staging/dosbox-staging/releases/tag/v0.78.1).
* There is no corresponding entry in [GitHub Releases](https://github.com/dosbox-staging/dosbox-staging/releases), unlike earlier non-alpha releases.
* There are no releases notes for v0.78.1 at [dosbox-staging.github.io](https://dosbox-staging.github.io/).
* Repology already lists some distributions are already listed as [shipping v0.78.1](https://repology.org/project/dosbox-staging/versions)
* My local Git repo had a `v0.78.1` tag that I had to delete, because it collided with `get fetch --tags` — I am not sure where it came from, but since I have not made any tags myself, the only explanation I can come up with is that the tag is being moved around upstream.

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by kcgen** [comment]
It's not released. I haven't added a release for it in GitHub's releases list nor have I posted any announcement on the blog (the .io site) listing what's changed.

The tag represents commits that are so far planned be in 0.78.1, but the tag might be marched forward if we can fix the remaining issues reported against 0.78.0. 

Thanks for letting me know @oturpe. Next opportunity, I will replace this tag with `v0.78.1-rc`

**Comment by oturpe** [comment]
Thank you for the explanation.
This was a point of confusion,
because many projects just use Git tags to flag releases.
For example, the [dosbox-staging entry for release-monitoring.org][relmon]
was, until recently, watching GitHub tags instead of releases,
so it now incorrectly lists some `-alpha` -releases.
(And the admins have not yet reacted to my request to clean them up).

Could you consider explaining how tags are used in the README?
I suspect there are many people who, just like I did,
automatically assume that once a tag has been set,
it is never moved to another commit.

I have contacted the distributions that have already packaged 0.78.1, too,
so that they can adjust their packaging as needed.

[relmon]: https://release-monitoring.org/project/234902/
