### ISSUE TITLE
Use FreeDOS code page 668 instead of 852 for Polish language

### ISSUE THREAD

**Issue by FeralChild64** [dosbox-staging/dosbox-staging#1495]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Is your feature request related to a problem? Please describe.

**Background**

Back in the 80s, when the first MS-DOS machines arrived in Poland, there was no standard for our national accents. Multiple solutions were invented internally, eventually Mazovia (https://en.wikipedia.org/wiki/Mazovia_encoding) became the dominant encoding in the PC ecosystem. It basically replaced accents from the default CP437 character set which we had no use for, and served us well for several years.

Then came the orcish hordes... I mean, MS-DOS 5.0 and localized Windows 3.x :) IBM and Microsoft decided to use code page 852 (so-called Latin 2) for CE (Central Europe) languages. Thanks to Windows 3.1, the encoding was accepted and eventually superseded Mazovia. This is the standard DOSBox currently follows - unfortunately, for polish users this is not the best idea.

**Problem**

Code page 852 was designed to cover well over 10 languages, each with different accents - so it has to replace a lot of graphic characters (Mazovia replaced none) for all these national letters. Full code page 852 can disrupt display of some software, see for example this DOS Navigator showing double-accented 'u' national characters instead of check marks:

![Example](https://user-images.githubusercontent.com/48332137/147967842-ed976ea5-0523-4320-b13c-6f8f50fb4db8.png)

**Old solutions**

So instead, locally developed utilities were commonly used to set up the character set, like the popular `EGAPL.EXE` (https://fiskas.pl/pliki/Sekafi2X/polskie_znaki/):
- `EGAPL.EXE MA ACTIVE+` - enables the Mazovia character set (it was already obsolete when I got my first PC)
- `EGAPL.EXE LA ACTIVE+` - enables the minimal 852 subset needed for polish language; fortunately for us such a subset was working well with most software

Similarly, `KEYBPL.EXE` from this package was typically used to setup the matching keyboard layout (RALT+A, RALT+C, RALT+E, RALT+L, RALT+N, RALT+O, RALT+S, RALT+X, RALT+Z, and SHIFT+RALT+... for capital letters), there were alternative tools like Kumar drivers too (http://www.kumar.com.pl/programy/kbpl.zip). Side effect was that such utilities used much less conventional memory than bloated MS-DOS tools (although for DOSBox this is not a problem anymore).

**Modern solution**

FreeDOS extends the list of code pages, to include sane character sets for languages like Polish, Slovak, or Czech (see here: https://gitlab.com/FreeDOS/base/cpidos/-/blob/master/DOC/CPIDOS/CODEPAGE.TXT) and IMHO this is the right approach to provide a trouble-free environment for polish users.

### Describe the solution you'd like

- make sure up to date FreeDOS CPX files are imported to DOSBox source (if I'm not mistaken, currently only EGA.CPX is present)
- for polish keyboard layout don't use code page 852 by default - use code page 668 from EGA10.CPX instead
- if possible, extend the KEYB command to allow users to select other encodings too (some might still prefer the Mazovia standard)
- support for Czech / Slovak / Hungarian / etc. might also benefit from non-Microsoft code pages

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by FeralChild64** [comment]
Please don't "fix" it by importing FreeDOS tools; they eat 13KB of conventional memory, while the current DOSBox one eats none!

**Comment by Grounded0** [comment]
Related to #785.
