### ISSUE TITLE
IMGMOUNT can't mount read-only IMG files

### ISSUE THREAD

**Issue by Burrito78** [dosbox-staging/dosbox-staging#1499]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Different version than latest?

0.79.0 DEV

### What Operating System are you using?

Mac OS

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

While trying to mount a read-only IMG file, DOSBox Staging show the following error message:

<img width="458" alt="Bildschirmfoto 2022-01-04 um 23 37 26" src="https://user-images.githubusercontent.com/61995128/148133654-2d09fc92-1a15-4c36-96da-9aeaab35c6e6.png">

Read-Only IMG files are common, e.g. some floppy image preservation groups on archive.org.

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Set the file attribtes of a floppy disk image to read-only
2. Try to mount the image using IMGMOUNT A disk1.img -t floppy

### Your configuration

```ini
default
```

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by kcgen** [comment]
Thanks for the testing @Burrito78. 

Indeed, physical floppies could be write-protected, and it was common for games to offer one or more read-only "data disks" while the user's progress was written to a separate "save-game disk".  

We should treat the floppy as read-only if:
1. the image file is marked with the read-only attribute, exactly as you've indicated.
2. the user passes an argument, perhaps `-ro`` to the `imgmount` command. (`-ro` follows the well known unix-mount syntax).

**Comment by Burrito78** [comment]
It took me some time to figure out that the IMGMOUNT error "Can't create drive from file" was actually triggered by the read-only flag. I first thought the IMG was created in a non-standard way that DOSBox has trouble mounting correctly.

I would expect that IMGMOUNT would just mount that IMG anyways. And any try to write to it should fail anyway with a "Can't write" error.

**Comment by Wengier** [comment]
@Burrito78 It is indeed quite frustrating in this case, which should to be treated as read-only instead of showing the error. Also, a -ro option need to be added as mentioned above.

**Comment by Grounded0** [comment]
Priority fix as its an old issue: #545

**Comment by Wengier** [comment]
I have fixed this via PR #1509.
