### ISSUE TITLE
Replace subset userland with FreeDOS 1.3 equivalents

### ISSUE THREAD

**Issue by Grounded0** [dosbox-staging/dosbox-staging#1504]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### If Other OS, please describe

macOS 11.6.2/x86-64

### Is your feature request related to a problem? Please describe.

I've seen a ton of bug reports and feature requests lately on our subset userland. Its crummy and there's no point of trying to fix or enhance it if there's better GPL replacements readily available at the FreeDOS project. Only bits worth keeping are DOSBox Staging specific utilities like IMGMOUNT.

Connected tickets:
- #1495
- #1336
- #1296
- #1062
- #785
- #729
- #642
- #448
- #399
- #391
- #209
- #62

### Describe the solution you'd like

Once FreeDOS 1.3 ships work should start on planning how to deploy subset userland replacement.

### Describe alternatives you've considered

Trying to fix a codebase that is outdated and crummy is not a worthwhile investment when there's better GPL licensed replacements available. Ricardian comparative advantage at work. 

This will also offload development and maintenance burden from us and let us concentrate on our own comparative advantage that is proper emulation of DOS games.

### Add any other context or screenshots about the feature request here.

FreeDOS Project website:
https://www.freedos.org/

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by arrowgent** [comment]
improving dos in dosbox is good

we should also consider if any changes here breaks backwards compatibility with "real" dos
or games such as GOG installers (dosbox) or things like win3.1
there are a lot of cases where it could cause a regression?

dosbox dos reports version 5.00 simulated
i can see where some examples prefer to report version 3.0, 6.22, etc
does freedos effect this in any way?

also, does switching to freedos restrict or expand upstream issues from dosbox-svn?
https://github.com/dosbox-staging/dosbox-staging/tree/main/src/dos

if it works out to be a sideways upgrade that just adds features and ability to improve then that would be fantastic
especially if the end-user doesnt need to know anything special about the difference

**Comment by FeralChild64** [comment]
IMHO replacing built-in KEYB.COM with a FreeDOS alternative to close https://github.com/dosbox-staging/dosbox-staging/issues/1495 and https://github.com/dosbox-staging/dosbox-staging/issues/1062 is not a good idea.

To set the font codepage and keyboard in FreeDOS, we have to sacrifice 13KB of conventional memory (and for the polish language we have much better tools already developed in 80's and early 90's, no need for all these oversized MODE, KEYB, etc.).

Doing the same using DOSBox KEYB.COM eats 0KB of conventional memory. I definitely don't want this tool to disappear.

**Comment by Grounded0** [comment]
I agree that anything that imposes a permanent conventional memory reduction must stay. Fixing DOSBox KEYB makes sense.

**Comment by Grounded0** [comment]
Seems more like 2 KB of conventional and 1 KB of upper memory but should still be avoided.

<img width="1392" alt="Screenshot 2022-01-05 at 20 41 11" src="https://user-images.githubusercontent.com/48192273/148271131-88d483ea-ff4d-4e19-ba90-0022ecc8ddb9.png">

**Comment by FeralChild64** [comment]
@Grounded0: I don't know what you have installed there, and I'm not familiar with Finnish at all, but in a real FreeDOS in order to have polish letters (_right_ALT+A_ produces an accented 'a', etc.), you need to issue several commands:

```
DISPLAY CON=(EGA,437,1)
MODE CON CP PREP=((852) %dosdir%\CPI\EGA10.CPX)
MODE CON CODEPAGE SELECT=852
KEYB PL,852,%dosdir%\BIN\KEYBOARD.SYS
```
FreeDOS/MS-DOS `KEYB.EXE` only sets the keyboard layout, while DOSBox built-in one one also loads the screen font.

**Comment by kcgen** [comment]
That's a truckload of level 9 language-mage stuff right there! Glad you've figured that out, @FeralChild64. 

It's nice Microsoft made it so easy. I think some users might find learning English a bit more user friendly! 

(Jk, but yeah.. this is exactly the stuff we should automate for users behind `-lang country`, with of course options to customize those details if needed in the conf)

**Comment by Grounded0** [comment]
FreeDOS COMMAND does not interfere with reported DOS version as its queried from DOS 30H function which can set in dosbox-staging.conf:
![Screenshot_20220105-212035](https://user-images.githubusercontent.com/48192273/148277109-a7b25038-2d2f-41bd-b19b-ec7da17c5128.png)

**Comment by Grounded0** [comment]
Does DOSBox Staging support loading external screen fonts? If not we're kinda forced to try to fix that mess.

**Comment by FeralChild64** [comment]
@kcgen That's taken from some guide. If you have MS-DOS (not FreeDOS) it is very similar, but you have to load COUNTRY.SYS in the CONFIG.SYS. Of course we did not like it back in the day at all, and preferred our own ugly solutions, like:

```
LH EGAPL.EXE LA ACTIVE+
LH KBPLP852.COM
```

which was taking away some 2-3 KB and only provided characters we actually needed :) AFAIK something similar was used in Czechoslovakia. But anyway - I don't want to see this ever again. FreeDOS CPI (CPX) files are OK, DOSBox built-in KEYB.COM just needs some tweaking, MS-DOS style settings are not fun at all.

@Grounded0 I figured it out you can load CPI/CPX files using DOSBox Staging (or DOSBox X) KEYB.COM, like:

```
KEYB PL 668 C:\DOS\CPI\EGA10.CPX
```

but in Staging this seems to be unstable, sometimes it takes down the whole emulator. I'm still experimenting, trying to find out what's the reason (which setting) before I submit a bug report.

BTW, you have an outdated _EGA.CPX_ embedded in _dos_keyboard_layout_data.h_, and the code utilizing it was most likely written before _sizeof_ operator was invented :P Once you have subdirectories in Z:\, this should be cleaned up.

**Comment by Grounded0** [comment]
If the backend code is there i try to load FreeDOS CPI/CPX with FreeDOS KEYB if its more stable.

**Comment by FeralChild64** [comment]
FreeDOS KEYB can't load CPI/CPX files, you need this whole MODE magic. Actually, if you look at the FreeDOS 1.3 default FDAUTO.BAT, you'll see a REM'ed example how to use the `MODE & friends` stuff. It's a little bit different than what I've pasted here, but I really don't intend to dig into it.

**Comment by FeralChild64** [comment]
BTW, CPX files are UPX compressed CPI files. Type `UPX -d FILE.CPX`, and they'll be back in the original MS-DOS format.

**Comment by Grounded0** [comment]
Looking at it we should fix KEYB and poach all the newest CPI/CPX files from FreeDOS and save everyone a 10 KB+ of conventional memory. What a mess.

**Comment by brandonrobertz** [comment]
Love this concept. 💚 Right now lots of the userland is implemented via C++ code in `shell/`. I started going down the road of building test cases for our C++ version of DOS commands, but it's really really messy code. By replacing that with userland binaries provided by something like FreeDOS we could really simplify the codebase and focus on providing compatibility at the DOS API level.

**Comment by Wengier** [comment]
While the concept itself sound interesting, this need to be proceeded with great cautions as discussed elsewhere. Comparisons of individual commands need to be done in order to decide which command works better. Also, this does not solve issues like #1336 and #729 listed above. For example, the readability of help messages as adopted in #729 appear to look more attractive than the FreeDOS counterparts, and replacing them with FreeDOS ones will likely make them less readable.

**Comment by Grounded0** [comment]
Since KEYB can be loaded into upper memory i think it should also be replaced by FreeDOS equivalent:
<img width="1392" alt="Screenshot 2022-01-06 at 6 37 30" src="https://user-images.githubusercontent.com/48192273/148329015-a5a570a5-9593-41fb-a84b-84da029a92f3.png">

**Comment by Wengier** [comment]
Issue #1506 can be fixed easily in the code. I don't see the real benefits of FreeDOS equivalent in this case.

**Comment by LowLevelMahn** [comment]
the big problem with using FreeDOS tools is loosing control and ease of development and the ability to do things that are just not possible with a pure DOS solution

dosbox internal commands can use the host and dosbox's DOS environment (in any form) and can be developed using todays standard C++ compilers and IDEs

FreeDOS tools are restricted to the DOS environment and DOS development tools and their IDEs (its not impossible, but just much harder compared to the way it works with internal commands)

another point is that i wouldn't use just pre-build binaries from (some) the freedos server, so at least the source code parts that are needed for the tools need to get build on the dosbox staging CI

the KEYB bug isn't big enough to just switch to a complete different codebase
solving the batch stuff needs to replace the complete COMMAND.com hierarchy - which is the base of every execution from the shell i think

**Comment by Wengier** [comment]
Agree with @LowLevelMahn. We lost controls over the code once FreeDOS tools are adopted. Most FreeDOS tools are clearly not updated regularly, often not updated over 10+ or even 20+ years.

If anyone really wants to replace some Z: drive programs with FreeDOS (or MS-DOS) ones, I can easily port the Z: drive customization feature so that you can use your own files to replace any existing files on Z: drive, and this does not limit to FreeDOS ones.

**Comment by Grounded0** [comment]
Problem is that DOSBox userland probably will never be fixed because most people annoyed by it install a more feature complete and robust DOS userland. So there's no value in keeping them in POSIX C++ constructs anyway.

Regarding the tools not updated in a while in FreeDOS: A code that works well and offers enough features doesn't have to be changed. Sadly doesn't apply to DOSBox userland.

**Comment by Wengier** [comment]
I do have serious plans to improve the current commands, and fixing ourselves is much more flexible. It can be done relatively easily, by porting code from e.g. DOSBox-X with further improvements. Replacing with FreeDOS ones means lose of control, which certainly does not work well enough. But with the Z drive customization feature you can replace them with FreeDOS (or MS-DOS or DR-DOS or 4DOS etc) if you want.

**Comment by LowLevelMahn** [comment]
> Problem is that DOSBox userland probably will never be fixed because most people annoyed by it install a more feature complete and robust DOS userland anyway.

is that prooved or just a feeling you've got?
i've never came across any big discussion on vogons about that 
do you got some links so i can read thorugh and get a feeling what tools are usually missing? (beside XCOPY, DEBUG, MODE, KEYB and DELTREE)

> So there's no value in keeping them in POSIX C++ constructs because nobody touches it.

even if you don't feel the same: there is huge difference between untouched C++17 code inside dosbox that can be easily changed and runs through the full dosbox compilation, unit (even if there currently are not that much) and asan/tsan stack and multi platform compile builds

or a untouched DOS code writen in 16bit C, Pascal or Assembler from another project

> Regarding some utilities not updated in a while in FreeDOS: A code that works well enough and offers enough features doesn't have to be changed. Sadly doesn't apply to DOSBox userland.

you're absolutely right - but switching to a complete different implementation is not a tiny step
- this will define a new standard that we can't remove easily and that need to be based on more evidence and proofs how desperately this different implementations are really needed

how many tools would you replace, or just add all available?

**Comment by Wengier** [comment]
Many FreeDOS have limitations and/or have broken functions in DOSBox, either from the FreeDOS side or the DOSBox side. This had been discussed elsewhere.

**Comment by Grounded0** [comment]
> how many tools would you replace, or just add all available?

Replacing COMMAND and all that is in Z: drive while keeping IMGMOUNT and any other DOSBox specific commands. Adding XCOPY, DEBUG and DELTREE used by DOS game installers. Adding LH to load KEYB into high memory. Replacing our own fonts and codepages with FreeDOS ones as requested by our users.

**Comment by Wengier** [comment]
COMMAND includes internal DOS commands, which FreeDOS has various limitations or broken functions. Again with the Z drive customization feature you can replace COMMAND with 4DOS, or COMMAND from NS-DOS, DR-DOS, or FreeDOS with the Z drive customization feature, not just limited to FreeDOS.

**Comment by Grounded0** [comment]
I have been doing "Z drive customisation" for years by setting Z: drive as the lowest order directory in my PATH. Problem is that doesn't fix the userland for users who aren't tech savvy or informed enough to install a better DOS userland and configure their AUTOEXEC.BAT properly.

**Comment by LowLevelMahn** [comment]
the XCOPY, DEBUG and DELTREE commands are easy to implement - and these 3 came from a single issue that opens up this whole replace-all-with-free-dos stuff

the second issue was a regression with 0.78 KEYB and CPX files (wich is now fixed)
the replacement FreeDOS version isn't even able to read CPX files
even the original Issue poster told that using FreeDOS MORE + KEYB is more complicated 
so what is the benefit of using that version?

so in the End there is only COMMAND.COM, or?

@Grounded0: 
this switch is technically bigger then you think (not from a get it working and not from a what the FreeDOS tools can give us standpoint) and telling that "there are" people coping with that is just not enough for such a huge strategical switch

**Comment by kcgen** [comment]
Sounds like we're in good hands all around the table. Leverage what we can from existing tools, implement when it doesn't meet our needs or expectations with @Wengier leading this charge, and stay flexible (with bin path override) in either case to suit custom needs.

**Comment by Grounded0** [comment]
I don't see any activity regarding those 12 tickets either. Whole ticket served as a notice that there is a problem no one is doing anything about. Hopefully someone starts addressing these now. I don't care how those tickets are closed in the end.

**Comment by LowLevelMahn** [comment]
sorry but there are not 12 issues that can be fully closed with using FreeDOS implementations

#1495 its not wanted
  from FeralChild64 
     `Please don't "fix" it by importing FreeDOS tools; they eat 13KB of conventional memory (much more than EGAPL.EXE + Kumar keyboard drivers), while the current DOSBox one eats none!`
#1336
#1296
#1062 its unclear
  from Burrito78 
  `So maybe using 437 for german is the "more correct" codepage for running old DOS programs and should be the default.`
#785
#729
  Wengier improved it very much
#642
#448
#399
#391 is there even a FreeDOS less?
#209
#62 i think that should be integrated better like for example MT32 roms

the KEYB and codepage stuff needs to be better handled - that is clear

you did not even prooved that every of these issues can definitily be closed using FreeDOS - that would be a start

**Comment by Wengier** [comment]
Z drive customization is certainly more than just putting lowest order directory in PATH. It can be done very easily to customize the drive from a user’s prospective with proper documentations. There are certainly better way to fix some problems than pushing FreeDOS commands, which will without a doubt lead to its own problems.

**Comment by Grounded0** [comment]
It was just proposition. If you have other means to close them they are perfectly okay too. All the options have to be examined and evaluated for a good design choice in the end.

**Comment by LowLevelMahn** [comment]
> It was just a proposition. 

"just a propostion comes" not with the style of a ultimate solution while someway ignoring the concerns :)

**Comment by Grounded0** [comment]
I'm concerned about the current state of the userland as it is. Work should commence in addressing the tickets that cannot be fixed by replacing the bits in question with a FreeDOS 1.3 binary blob and let us decide what should be done to those tickets later.

**Comment by Wengier** [comment]
There were already much previous work done for existing commands. Even more are already planned and will come shortly. Replacing with FreeDOS ones will cause new problems, and others also have different preferences, not limited to FreeDOS ones. If you have preferences over the FreeDOS ones you can do yourself, but other people may prefer different ones.

**Comment by Grounded0** [comment]
4DOS has a problematic license to be bundled outside of FreeDOS as the default command interpreter:

![Screenshot_20220108-130635](https://user-images.githubusercontent.com/48192273/148641867-ac7b6433-603e-4fb0-8161-427ff5f9c5df.png)

All the rest are black box closed source binaries and such are out of question as the default command interpreter for DOSBox Staging.

Realistic options are either fixing FreeDOS COMMAND or shipping FreeCOM as the default command interpreter. Of course we can select our own preferences with PATH like to date.

I just want something that does batch prosessing reliably and correctly out of the box for a start for all of our users.

**Comment by Wengier** [comment]
As far I as know 4DOS was once the default shell for vDos. But if you just look for GNU GPL command shells that work in DOS, there are also for example the COMMAND or RXDOSCMD from RxDOS, or even command shell like Bash, which are ported to DOS as part of DJGPP.

With Z drive customization feature one can put any command shells they prefer, such as COMMAND from MS-DOS, DR-DOS etc, and the license type does not really matter in this case as long as the user owns them. In such case there is no need for DOSBox Staging to bundle them, but users can put any command shell they own and add them to Z drive and set as the default shell.

More work is already planned and will come shortly to further upgrade the internal COMMAND shell, and while FreeCOM may be added as an alternative shell (perhaps along with RXDOSCMD, Bash, etc), there is no need to make it the default shell as it has various limitations that are much harder to fix than the internal command shell and will cause new problems.

**Comment by Grounded0** [comment]
We'll do quarterly progress reports on this from now on the next being on 5th of April 2022.

**Comment by LowLevelMahn** [comment]
@Grounded0
i would help alot if you had at least react in any form to the concerns of the other developers/users 
its very easy to think that you see the FreeDOS implementations as the only possible solution (with no problems at all)

such comments
- "Will close 12 issues", 
- "DOSBox userland probably will never be fixed", 
- "there's no value in keeping them in POSIX C++17"
- "A code that works well enough and offers enough features doesn't have to be changed. Sadly doesn't apply to DOSBox userland."
- " Problem is that it doesn't fix the userland for users who aren't tech savvy or informed enough to install a better DOS userland"
- "I don't see any activity regarding those 12 tickets either."

and you never said anything to wengies or my concerns (not a bit) and in the end you said

- "I don't care how those tickets are closed in the end."
- "If you have other means to close them they are perfectly okay too."

after posting over 10 times aorund the overall greatness of the FreeDOS code - that not a discussion about
a solution - its more forcing a solution

think about it

**Comment by kcgen** [comment]
One of Staging's goals is using modern technologies and practices; so I opened <https://github.com/dosbox-staging/dosbox-staging/issues/1314>, which asks for help trying replace existing non-trivial shell code with easier to read c++17 and, more importantly, rigorously unit-tested behaviour (good cases, bad cases, corner cases, etc..). 

@brandonrobertz has made excellent progress in this area. At the same time, users are asking for more command line functionality, some of which can help game installers.

How do we progress the request for that added CLI functionally?

1. if unit-tested easy-to-read and c++17 equivalents are available, we will gladly accept that as an improvement to the codebase - and use them straight away. Any interest or help in this area can speed up this pathways.

2. In the meantime before they're ready, the next best thing is leave the C-style code as-is and bundle high-quality freeDOS binaries that simply trump the existing internal binaries by given them first position in the PATH sequence. 

We would do this conservatively to plug the feature gap. @Wengier noted some of these tools may have issues, so in those cases where they're a net loss we will yank them and fallback to the baseline. 

So we have two pathways that can let us provide more functionality on a command-by-command basis, and neither are mutually exclusive.

**Comment by Grounded0** [comment]
Apologies for my personal style.

There seems to be a formulation above that everyone seems to find acceptable which is really nice and long standing issues can finally start to be addressed.

**Comment by Grounded0** [comment]
I've studied string processing on DOSBox COMMAND.COM vs FreeDOS COMMAND.COM.

DOSBox COMMAND.COM processes % as %.

FreeDOS COMMAND.COM processes them like MS-DOS COMMAND.COM so %% is %.

These significant differences in string processing make any modifications to DOSBox COMMAND.COM unviable if we're going to retain 100% backwards compatibility for batch files written for DOSBox during the last 20 years.

My suggestion is to allow users boot directly into FreeDOS COMMAND.COM if they choose to in the future. I'm closing DOSBox COMMAND.COM related tickets based upon this analysis.

**Comment by brandonrobertz** [comment]
> These significant differences in string processing make any modifications to DOSBox COMMAND.COM unviable if we're going to retain 100% backwards compatibility for batch files written for DOSBox during the last 20 years. Any improvements to the code may impair backwards compatibility as the overall behaviour is erratic.
> 
> My suggestion is to allow users boot directly into FreeDOS COMMAND.COM if they choose to in the future. I'm closing DOSBox COMMAND.COM related tickets based upon this 

Yeah I agree with this conclusion, FWIW.

**Comment by kcgen** [comment]
Also agree, thanks for that write up, @Grounded0.

**Comment by Grounded0** [comment]
Closing this megaticket since almost every entry have been resolved except:
- #62

**Comment by Grounded0** [comment]
Technically this was never implemented but it created enough pressure for people to finally start fixing the rubbish userland.

**Comment by johnnovak** [comment]
Yeah okay, I read the thread and forgot the original title 😄  Technically it wasn't implemented, right, so putting back to "won't do".
