### ISSUE TITLE
Multi-disk image mounts "leak" information to the DOS side

### ISSUE THREAD

**Issue by kcgen** [dosbox-staging/dosbox-staging#1510]
In F-19 Stealth Fighter, if both floppies are mounted in swap mode (Ctrl+F4), the game's copy protection rejects the key disk:

``` ini
[autoexec]
imgmount a disk1.img disk2.img -t floppy
a:
f19.com
```
![2022-01-06_19-15](https://user-images.githubusercontent.com/1557255/148485659-8a2ffca1-c22b-4b4c-8448-900970949929.png)

But if the disks are mounted individually (either both A and B or just A), then the game starts:

``` ini
[autoexec]
imgmount a disk1.img -t floppy
imgmount b disk2.img -t floppy
a:
f19.com
```

![2022-01-06_19-14](https://user-images.githubusercontent.com/1557255/148485683-f5813a45-6553-4f93-b3b6-89ca4aba8139.png)

Reported by @NicknineTheEagle - thank you!

**Comment by kcgen** [comment]
Fixing this will involve some not-so-trivial refactoring of how the multi-image mount interacts with the disk-manager.

Currently, when multiple images are passed, a new FAT drive is created for each image (all up-front as part of the `imgmount` command).  The `fatDrive` constructor does a lot of work, including registering various details with the DOS side.  

Ctrl+F4 then asks the drive manager to rotate the list of full-up fatDrive objects with the drive letter, followed by a cache refresh.

Fixing this will require making multi-image simply store the list of filename, and then making it behave more like calling `mount -u a; mount a disk1.img`, then `mount -u a; mount a disk2.img`, and so on.

**Comment by NicknineTheEagle** [comment]
This appears to be fixed in the latest nightly build. I wonder what specific commit is the fix.

**Comment by NicknineTheEagle** [comment]
Must be this one: https://github.com/dosbox-staging/dosbox-staging/commit/d40affc717e7430037a7a3fcb03f3f1daeaf2530#diff-d5969affec6ace367e149ef143f353f6be213e2000a73ded6072b048c23a23bc
