### ISSUE TITLE
Is this a compiled version of THE OFFICIAL SVN version?

### ISSUE THREAD

**Issue by Videogamer555** [dosbox-staging/dosbox-staging#1519]
Or is it a community modded version? I want the latest OFFICIAL SVN version, with NO community modifications, no matter how slight they may be. As of right now, the official release is version 0.74, and I want to try out the latest SVN (aka nightly build) features. However, I don't want to get used to using unofficial features, because as soon as they release the next official version (like 0.75 or 0.8 or whatever), I want to transition back from the SVN to the release version. So that's why I'm looking for a compiled copy of the latest official SVN version. If that's what Dosbox Staging is, then great. If not, please direct me to where I can find the latest official SVN version of official Dosbox.

**Comment by LowLevelMahn** [comment]
Dosbog Staging is the most active (beside Dosbox X) fork of dosbox - update regular with the Dosbox SVN changes

most of the unofficial but very good working patches are already included with dosbox staging (for example Munt MT32 support) - any many many more features

`So that's why I'm looking for a compiled copy of the latest official SVN version. If that's what Dosbox Staging is, then great. If not, please direct me to where I can find the latest official SVN version of official Dosbox.`

sorry its not what you're looking for - there is no offical Dosbox SVN build server: best you can use are links on https://www.dosbox.com/wiki/SVN_Builds

having no official auto build system was one of the reasons for starting the dosbox staging project

**Comment by Videogamer555** [comment]
> Dosbog Staging is the most active (beside Dosbox X) **fork** of dosbox - update regular with the Dosbox SVN changes
> 
> most of the unofficial but very good working patches are already included with dosbox staging (for example Munt MT32 support) - any many many more features
> 
> `So that's why I'm looking for a compiled copy of the latest official SVN version. If that's what Dosbox Staging is, then great. If not, please direct me to where I can find the latest official SVN version of official Dosbox.`
> 
> sorry its not what you're looking for - there is no offical Dosbox SVN build server: best you can use are links on https://www.dosbox.com/wiki/SVN_Builds
> 
> having no official auto build server for dosbox SVN was one of the many reasons for starting the dosbox staging project


Why does it even exist then? If your project STARTED as a source for the latest SVN compiled, then WHY did it change? WHAT ON EARTH caused you to basically turn into DosBox X? I DO NOT WANT FAKE CRAP MODS LIKE DOSBOX X!

Also "staging" is a misnomer then. Staging is a term used by major software corporations for a download server that the latest official version of software is on, prior to its announcement on the company's official website. For example the Fortnite Staging Server is where Epic Games puts the latest update for the game, just prior to officially sending the signal to the Epic Games launcher to tell it that a new version is ready for download. So when I saw DosBox staging I thought, "OH GOOD the DosBox project FINALLY has a place where I can download the LATEST OFFICIAL SVN release, even before the official DosBox website announces that a new release exists".

Sadly that's not what it is. The name you are using is therefore FALSE ADVERTISING, and that is JUST SO WRONG WRONG WRONG WRONG!!!!!

**Comment by rsribeiro** [comment]
Well, that escalated quickly

**Comment by LowLevelMahn** [comment]
clam down little tiger - no place here for sceaming around like a naughty child

this forks "dosbox staging" and "dosbox x" do not harm the whole dosbox world in any way - its just a playground for different development - thats it, you don't need to understand or use it at all

just build your very own svn version - it tooks me 1min everytime i need a fresh build - even without screaming :)

**Comment by kcgen** [comment]
@Videogamer555,

In the open-source community, a _Staging_ project consists of a group focused on triaging and testing community patches, proposing fixes, and making code improvements offered for assessment and discussion with the main group, who can further decide what to accept into the main branch. 

For example, the [Wine Staging project](https://wiki.winehq.org/Wine-Staging) **"... contains bug fixes and features, which have not been integrated yet \<snip\> to give developers the possibility to discuss and improve their patches before they are integrated into the main branch."**

In the same way, the DOSBox Staging team offered code-reviewed (and cleaned-up) community patched and small code improvement to the upstream DOSBox project. 

Here's our [second patch series](https://sourceforge.net/p/dosbox/patches/284/):

![2022-01-11_08-03](https://user-images.githubusercontent.com/1557255/148978266-670ce693-4c34-4629-a26e-927e6ea7b9a1.png)

And our fourth patch series consisting of 78 separate patches:

![2022-01-11_08-05](https://user-images.githubusercontent.com/1557255/148978290-89fa23f0-a692-4994-b4be-050f794dccca.png)

We received feedback and assessment from QBix:

![2022-01-11_08-17](https://user-images.githubusercontent.com/1557255/148981073-35156587-6a96-4f9e-8bbb-a2a8ab0f1e84.png)

With further discussion we found the two teams' goals weren't aligned in some project management aspects but were aligned in the areas of game-specific bug fixes. So, we have contributed fixes to both DOSBox (SVN) and DOSBox ECE.

![2022-01-11_07-32](https://user-images.githubusercontent.com/1557255/148975802-c287a55d-bd77-4484-9cc9-4e0e82866d38.png)

![2022-01-11_07-31](https://user-images.githubusercontent.com/1557255/148975857-69d0180f-caae-43b3-b191-98b961dcac24.png)

**Comment by kcgen** [comment]
## I want the latest OFFICIAL SVN! I DO NOT WANT FAKE CRAP MODS

DOSBox SVN - aka, NON-FAKE-CRAP-MODS edition, is not supported here. You'll need to go to the DOSBox SOURCEFOGE or Vogons.org websites for support.
