### ISSUE TITLE
Vgaonly broken in v.0.78.1? [BUG] 

### ISSUE THREAD

**Issue by Diduz** [dosbox-staging/dosbox-staging#1526]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Relevant hardware info

RTX 2070, i7 processor, Windows 10

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Hi guys, sorry to bother you again after that other issue  :-P https://github.com/dosbox-staging/dosbox-staging/issues/1485
but I think "vgaonly" setting isn't working properly in v.0.78.1. I don't know if this is related to the aspect ratio problem we discussed, but check these screens I took.
You need the "vgaonly" setting to show some scanlines effects in some games (the water in **Sleepwalker** was and still is glitchy with "svga_s3") and some demos (**Copper** by Surprise Team needs "vgaonly" for the majority of its effects, except wobbling, which only works under Dosbox-X, as far as I'm aware, so don't consider that one).
Anyway, as you may see, something strange is happening in version 0.78.1. I don't know if this may help, but I noticed that screenshots taken under v.0.78.1 ("vgaonly" enabled) are **lowres**. Now, usually vgaonly Dosbox screenshots have always been **hires**, because vgaonly actually renders VGA 320x200 as 640x400 (I think the reason is covering all the scanlines of the original VGA hardware). Screens still were hires in v.0.77.1 and v.0.78, but now they're lowres as in "svga_s3" setting. Could there be a connection between the malfunctioning and the screenshot grabbing system?

![copper_vgaonly_right](https://user-images.githubusercontent.com/39902698/149554042-2b1881f9-bfa2-4669-a051-958f464e5a4b.jpg)
![copper_vgaonly_wrong](https://user-images.githubusercontent.com/39902698/149554121-2ef5081e-1318-4fd1-bc00-e08f908c6ba6.jpg)

![sleepwalker_vgaonly_right](https://user-images.githubusercontent.com/39902698/149554155-e4c740c7-ee09-4bec-a680-118172577c49.jpg)
![sleepwalker_vgaonly_wrong](https://user-images.githubusercontent.com/39902698/149554179-c54ad9e4-1ec9-469c-b872-80caa4f25024.jpg)

### Steps to reproduce the behaviour.

Explain how to reproduce
1. 
2.
3.

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by kcgen** [comment]
Thanks @Diduz.  I've reverted the prior fix done to treat VGA mode 13h at 320x200, so we're back to the full scanline resolution of 400 (or 480 w/ aspect).  

This larger source resolution means that the pixel perfect scaler needs a large rendering area to hit the integer numbers:

Before:  320x200 @ 1.2 pixel-aspect 5x6 is 1600x1200 -> users need need a ~2K monitor
After: 640x400 @ 1.2 pixel-aspect 5x6 is 3200x2400 -> user needs need a ~4K monitor

![2022-01-14_13-47](https://user-images.githubusercontent.com/1557255/149590338-9984ea68-4993-4222-941d-a0a746256111.png)
 
`openglnb` or `texturenb` with a `windowresolution=1600x1200` will resulting in 2.5x3.0 scaling - to achieve the same result as before.

**Comment by kcgen** [comment]
Build underway here to test: https://github.com/dosbox-staging/dosbox-staging/actions/runs/1699719324

**Comment by Diduz** [comment]
Thanks! Vgaonly is working again as intended. :-) Unfortunately, my monitor is 1440p, so I cannot use pixel perfect scaling...

> `openglnb` or `texturenb` with a `windowresolution=1600x1200` will resulting in 2.5x3.0 scaling - to achieve the same result as before.

There's a thing I don't understand. Up until v.0.77.1, vgaonly and openglpp worked fine together even on my 1440p monitor. I got consistent 4:3 images even from games with weird resolutions (see Jazz Jackrabbit in-game 320x199: the game becomes widescreen without pp). The solution you propose works as long as the game features standard resolutions, but cannot help when the resolution isn't standard. Pixel-perfect managed to solve the issue anyway. Was there something different in the way it worked up until 0.77.1?
Anyway, there was some stuttering in scrolling in v.0.78.1 and now everything is smooth again! Wau to go! :-)

P.S.: I know you don't need vgaonly for Jazz Jackrabbit, I just needed a good example of a strange resolution. ;-)

**Comment by kcgen** [comment]
Thanks for the checks, @Diduz, and for reporting these regressions. Being aware of unique test cases is very useful. 
 
 >  Pixel-perfect managed to solve the issue anyway. Was there something different in the way it worked up until 0.77.1?

There were some corner cases that the overall pixel perfect solution didn't handle right (perhaps not the algorithm itself, but what it was being fed with):

![2020-03-21_17-49](https://user-images.githubusercontent.com/1557255/77240961-7ed8bd80-6ba9-11ea-9b0e-8d042dfce738.png)

Rayman + PP now scales properly:

![2022-01-14_15-51](https://user-images.githubusercontent.com/1557255/149599330-acece911-06a7-4f48-ba9c-45c7bf554812.png)

So perhaps correcting those areas has taken some more lenient behavior off the table. 

>  The solution you propose works as long as the game features standard resolutions, but cannot help when the resolution isn't standard.

Indeed; I think the next incremental improvement will be to make the integer-scaling pathway aware when it's being fed an "already-scaled by 2x" standard mode like 320x200, despite the source resolution being 640x400, to re-open up PP to smaller screens (but not allow it for non-standard resolution w/ your suggestion). 

Let's keep this open until we have this better approach in place.

**Comment by Diduz** [comment]
> I think the next incremental improvement will be to make the integer-scaling pathway aware when it's being fed an "already-scaled by 2x" standard mode like 320x200, despite the source resolution being 640x400, to re-open up PP to smaller scree(but not allow it for non-standard resolution w/ your suggestion).
> 
Do you think non-standard resolution wouldn't be displayed correctly with that approach?

**Comment by kcgen** [comment]
> Do you think non-standard resolutions wouldn't be displayed correctly with that approach?

Yes, I was originally worried about that, but with enough canvas space, the scaled image will simply underrun by some number of pixels. New binary, if you'd like to check:

 https://github.com/dosbox-staging/dosbox-staging/actions/runs/1701954761

![2022-01-15_08-05](https://user-images.githubusercontent.com/1557255/149628796-cd3a3ec9-bec9-4a04-a61d-b96bb494920f.png)

**Comment by Diduz** [comment]
>  New binary, if you'd like to check:

Checked aaaannnddd... we've a winner! :-) I confirm that now I get consistent 4:3 ratio over all the resolutions.
One more thing, but I'm not really sure about this. I get the impression that the aspect ratio for FULLSCREEN 4:3 is slightly larger than WINDOWED 4:3. I think this happens with any machine setting. I mean, fullscreen 320x200 doesn't look exactly 1.2:1, pixels seem to be **_slightly_** larger, but entering windowed display ratio feels right. Try a 320x200 game, press ALT+ENTER many times and confront the two images. Is it just me?
Anyway, thanks for all the work! :-)

**Comment by kcgen** [comment]
Thanks!

> . I get the impression that the aspect ratio for FULLSCREEN is slightly larger than WINDOWED. 

Can you paste the `VIDEO:` logs from running in window-mode?

Then set `fullscreen = true` and crank up both allowed resolutions to desktop:  `windowresolution = desktop` and `fullresolution`. Then launch that, and paste the `VIDEO:` logs.

pixel-perfect will use the largest integer multiple based on  availabile screen real estate: so, maybe we'll see different multiples being used between window mode vs fullscreen mode.

**Comment by Diduz** [comment]
> Can you paste the `VIDEO:` logs from running in window-mode?

Did you mean "DISPLAY"? Anyway, turns out you were right.
I ran a plain simple 320x200 Monkey Island 1 in svga_s3 via openglpp and that's what I got (on my 2560x1440 monitor)

_FULLSCREEN_ 
DISPLAY: VGA 320x200 8-bit (mode 13h) scaling by 6,0x7,0 to 1920x1400 with 1,17 pixel-aspect
_WINDOWED_
DISPLAY: VGA 320x200 8-bit (mode 13h) scaling by 5,0x6,0 to 1600x1200 with 1,20 pixel-aspect

But wait for it... there's a happy twist! :-)

I managed to force fullscreen in 1.20 by _**slightly**_ reducing the "max_resolution"  parameter to 2471x1390!
After I did that, I got a fullscreen pixel-perfect Monkey Island in 1.20:1. The only downside is a black "vignetting" around the image (basically you get both pillarbox and letterbox! :-P ). But I don't mind that, my monitor is 27", I can live with that if I get the right ratio. The log confirms the trick worked:
DISPLAY: VGA 320x200 8-bit (mode 13h) scaling by 5,0x6,0 to 1600x1200 with 1,20 pixel-aspect
This method works even with "problematic" resolutions in Jazz and Sleepwalker, and in vgaonly mode too! On the other hand, I noticed that "max_resolution=auto" is preferrable with EGA 640x350, which becomes too "vignetted" and tiny with this trick.
That said, I have NO idea why reducing the max_resolution parameter solves the issue!!! It was just a hunch.

**Comment by kcgen** [comment]
> I managed to force fullscreen in 1.20 by slightly reducing the "max_resolution" parameter to 2471x1390!
After I did that, I got a fullscreen pixel-perfect Monkey Island in 1.20:1 <snip> 

Glad you following your hunch! :-)

I wanted to say that there is no issue though; recall that pixel-perfect seeks out whole integer-multipliers that can "fit" the source resolution into the target canvas size, provided the aspect-ratio "error" stays below an acceptable threshold.  

 - **Fullscreen:** `320x200 by  6x7 to 1920x1400 1.17 pixel-aspect`
    vs
 - **Windowed:** `320x200 by  5x6 to 600x1200 with 1.20 pixel-aspect`

So in this case, it's able to perfectly scale using 6x7 multipliers and give you a bit bigger image at fullscreen - and the tradeoff is 2.5% error in aspect ratio. 

> I have NO idea why reducing the max_resolution parameter solves the issue!!! It was just a hunch.

Reducing the `max_resolution` shrinks the space that pixel-perfect can operate in, and in this case, 6x7 no longer fits - so it falls back to the next whole integers, which are 5x6, which also perfectly hit the 1.2 aspect ratio.

(Perfect aspect ratio is always achieved by the nearest-neighbour scalars, in exchange for possibly blending content of adjacent pixels i.e using fractional scaling).

**Comment by Diduz** [comment]
> I wanted to say that there is no issue though; recall that pixel-perfect seeks out whole integer-multipliers that can "fit" the source resolution into the target canvas size, provided the aspect-ratio "error" stays below an acceptable threshold.
> 

I see! Out of curiosity, how large is the threshold? Does it go beyond a 2.5% error range?

**Comment by kcgen** [comment]
I believe it's around 14%  - but I would have to do the math (you can also test it by constraining to smaller resolutions).

For example, for people with smaller screens (1280p or 1080p), it can produce an aspect of ~1.33, which is still "better" than giving up and going with 1x1 and then getting a 1.0 aspect.  Better being: you get a multiplier scaling plus 1.33-aspect is still closer to 1.20 than 1.0. 

The algorithm is much more advanced than the simple integer calculators found in other systems because of this aspect-ratio flexibility.
