### ISSUE TITLE
>=0.78 loguru compilation fails with other C libraries (like musl)

### ISSUE THREAD

**Issue by voyageur** [dosbox-staging/dosbox-staging#1528]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### What Operating System are you using?

Linux x86_64

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

loguru module that was included in 0.78 does not compile on non-glibc systems (if using musl for example), failing with:
../dosbox-staging-0.78.0/src/libs/loguru/loguru.cpp:103:18: fatal error: execinfo.h: No such file or directory
  103 |         #include <execinfo.h>  // for backtrace
      |                  ^~~~~~~~~~~~

As this header is glibc specific.

I do not use musl myself but a Gentoo archtester was running dosbox-staging on a musl system fine with older versions, and 0.78.1 works fine again with small change to only enable backtraces with glibc:
https://github.com/emilk/loguru/pull/206/files#diff-482bf8d9b0cd788997d714c6c4d0dac8d6b106a086b35a0d340e9d6d2fdb3981

I filled a loguru PR to hopefully get it merged there: https://github.com/emilk/loguru/pull/206
For dosbox-staging, do you prefer a PR now or waitin to see how the loguru PR works out? I will carry the patch downstream in the meantime

Downstream bug: https://bugs.gentoo.org/830930

### Steps to reproduce the behaviour.

Explain how to reproduce
Compile dosbox-staging 0.78.0 or newer on a musl system

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by kcgen** [comment]
Thanks for this fix @voyageur , merged here: https://github.com/dosbox-staging/loguru, which is Staging's "upstream" for Loguru.

I then sync'd this back into Staging, so hopefully the `main` branch is once-again buildable with `libmusl`.

**Comment by voyageur** [comment]
Oh nice, I had not seen upstream was a fork in dosbox-staging! Thanks for quickly picking it up, ernsteiswuerfel in https://bugs.gentoo.org/830930 confirmed main branch is now fine again with musl!

**Comment by kcgen** [comment]
Thanks for facilitating this fix and the check, @voyageur!
(closing)
