### ISSUE TITLE
Duke Nukem 3D: SFX produce static with GUS

### ISSUE THREAD

**Issue by RavenMacDaddy** [dosbox-staging/dosbox-staging#1532]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### What Operating System are you using?

Windows 11

### Relevant hardware info

CPU: AMD Ryzen 3600 | MB: MSI B450 Gaming Plus MAX | DAC: RME ADI-2 DAC | Speakers: EVE Audio SC205

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Testing both the SoundBlaster (16) and the Gravis Ultrasound as SFX device, the GUS sound device works fine a lot of the time, but specific SFX produces static.

SoundBlaster seems fine.

Note that other games like Jazz Jackrabbit as far as I've played doesn't have issues with GUS.

I first noticed issues in Duke3D when I got the shotgun weapon as shooting it produces static (mostly on the right sound channel).

https://user-images.githubusercontent.com/67732686/149654824-f5d6ee41-3fa7-4557-9256-1068688d440a.mp4

### Steps to reproduce the behaviour.

1. Check the DOS Games Archive [here](https://www.dosgamesarchive.com/download/duke-nukem-3d/) for the game.
2. Enable GUS emulation in the config of DOSBox Staging and run UltraMid.exe in the ULTRASND directory through DOSBox Staging to initialize the driver in the emulator (tip: add this to Autoexec at the bottom of the config to streamline things).
3. Run the setup for Duke3D and select Gravis Ultrasound as the SFX device (use Test sound to confirm it's working).
4. Play through the first level of Duke3D (episode LA Meltdown) and go for the shotgun that's on the left side of the map.
5. Try firing the weapon and you should hear the static as you fire it (turn off the music in case you enabled it to make it easier to troubleshoot).

### Your configuration

```ini
gus      = true
gusbase  = 240
gusirq   = 5
gusdma   = 3
ultradir = C:\Audio\ULTRASND
```

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by kcgen** [comment]
The audio driver in Duke 3D is doing the audio mixing itself and simply using the GUS as a two-channel stereo PCM sink.

You can tell when a game does this when only two GUS voices (or one) are reported in the log output:
``` text
2022-01-19 12:56:57.210 | GUS: Audio comprised of 16-bit samples from 2 voices
2022-01-19 12:56:57.210 | GUS: Peak amplitude reached 74% of max
2022-01-19 12:56:57.210 | GUS: Shutting down
```

Also, further up in the log you will see:

```
2022-01-19 12:56:51.063 | GUS: Activated 32 voices at 19294 Hz
```

This is even when music is see to disabled in `setup.exe`.

So even though Duke's driver only uses two voices, it actually harms the audio quality by activating all 32 GUS voices (which it's not even using) - but in doing so, it lowers the effective output sampling rate to sub-22 kHz. 

So with both these bits of info, using the SB16 output would be superior: sampling rates won't be hurt and it provides a perfectly adequate 16-bit stereo PCM pass-through.

I would recommend using General MIDI for the Duke music with FluidSynth (or an external MIDI player) using a high quality sound font.

**Comment by RavenMacDaddy** [comment]
Thank you @kcgen, that's what I needed to know - closed.
