### ISSUE TITLE
`windowresolution` presets produce a window that's now too big

### ISSUE THREAD

**Issue by kcgen** [dosbox-staging/dosbox-staging#1538]
As flagged by @shermp:
> `windowresolution isn't quite right on my system now. It doesn't seem to take into account the dosbox title bar, or my Windows taskbar, so it's just a bit too big.

**Comment by shermp** [comment]
For more context, starting staging with the following `[sdl]` section:
```ini
[sdl]
fullscreen       = false
display          = 0
vsync            = false
vsync_skip       = 7000
fullresolution   = desktop
windowresolution = large
output           = opengl
texture_renderer = auto
capture_mouse    = seamless middlerelease
sensitivity      = 100
raw_mouse_input  = false
waitonerror      = true
priority         = auto,auto
mapperfile       = mapper-sdl2-0.78.0.map
screensaver      = auto
```

Results in the following log entries:
```
DISPLAY: Initialized 1440x1080 window-mode using Bilinear scaling on 1080p display-0
...
DISPLAY: Unknown 640x400 (mode FFFFh) scaling by 2.2x2.7 to 1440x1080 with 1.20 pixel-aspect
...
DISPLAY: Text 640x400 (mode 3h) scaling by 2.2x2.7 to 1440x1080 with 1.20 pixel-aspect
```

Since my display is a standard 24" 1920 x 1080 display, this means that the bottom line or two of the dosbox window is hidden by the taskbar, and the window title bar is just a tiny sliver.

**Comment by kcgen** [comment]
@shermp , is this still happening for you?

Testing on my side with the above conf doesn't consume the entire vertical space:
 - 4k screen: `DISPLAY: Text 640x400 (3h) at 70.087 Hz VFR, scaled by 4.0x4.9 to 2592x1944 with 1.2 pixel-aspect`
 - 1080p screen: `DISPLAY: Text 640x400 (3h) at 70.087 Hz VFR, scaled by 2.0x2.4 to 1296x972 with 1.2 pixel-aspect`
 -

**Comment by shermp** [comment]
I think you fixed it back then, but I'll double check when I get home.

**Comment by shermp** [comment]
> I think you fixed it back then, but I'll double check when I get home.

Seems to be good. I'll close the issue.
