### ISSUE TITLE
Incorrect PCJr sound in Jumpman

### ISSUE THREAD

**Issue by Jkapp76** [dosbox-staging/dosbox-staging#1542]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Different version than latest?

0.79 alpha 0.140 (also 0.78 and older)

### What Operating System are you using?

Windows 11

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

There are some extra noise playing during the intro music of Jumpman on PCJr. Shrill high pitch sounds.

This also happens on DOSBox-X and ECE. But it does not happen with PCem and 86Box.

I tried just a few more games with PCJr music and did not notice any issue. 

*Also... The DOSBox-Staging manual says Tandy composite mode and CGA use OLD composite mode and PCJr uses NEW mode. I could be wrong but It looks like PCJr mode also uses OLD composite mode as default.

### Steps to reproduce the behaviour.

Explain how to reproduce
1. 
2.
3.

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by kcgen** [comment]
New-era composite is used is if `machine = pcjr`  -and- if `era = auto` (which is the default). 

https://github.com/dosbox-staging/dosbox-staging/blob/af80a1445ca81a63d36686b89a37873a128bc84a/src/hardware/vga_other.cpp#L1467-L1469

**Comment by kcgen** [comment]
thanks for the report; will look into it.

**Comment by Jkapp76** [comment]
I was mostly going by the look when I said the composite might be backward. I noticed the CGA, Tandy, and PCJr all start 'below the root' with the dark colors, then, hittin F11 switches them to lighter colors. In our earlier exchange about this game we referred to the brighter pcjr colors on this same game as 'new pcjr composite'. I had screenshots of both modes.

**Comment by kcgen** [comment]
@Jkapp76 , when you get a chance, please try this build: https://github.com/dosbox-staging/dosbox-staging/actions/runs/1743874879

and in Jumpman, set:

``` ini
[mixer]
rate = 96000
```

To confirm it's working, you should see this in your log output:

``` text
2022-01-24 22:03:30.780 | MIXER: TANDY channel operating at 96000 Hz without resampling
2022-01-24 22:03:30.780 | MIXER: TANDYDAC channel operating at 96000 Hz without resampling
```

Hopefully this improves the intro to Jumpman.

This is an interim solution; longer term, it would be nice to run the Tandy at an even higher rate and then use a resampler (like Speex) to step-down the audio to the mixer's native rate.

**Comment by arrowgent** [comment]
JUMPMAN LIVES!
now that was a game.

>DOSBox-Staging manual says Tandy composite mode and CGA use OLD composite mode and PCJr uses NEW mode. I could be wrong but It looks like PCJr mode also uses OLD composite mode as default.

its interesting that PCjr is what Tandy was based on.  i rarely use these but i have one game i am interested to test Tandy with.
`In 1984, Tandy developed an IBM PCjr clone.`


also note dosbox.conf suggests:

```
#   tandyrate: Sample rate of the Tandy 3-Voice generation.
#              Possible values: 44100, 48000, 32000, 22050, 16000, 11025, 8000, 49716.
tandyrate   = 49716
```

set to highest and let your cpu downscale to the correct audio 44.1k or 48k
is what my experience with the mixer in dosbox is

**Comment by Jkapp76** [comment]
Jumpman sounds great using this new version and 96000hz.

**Comment by kcgen** [comment]
Thanks for the checks @Jkapp76 !

@arrowgent ; thinking your conf is outdated. The 47 kHz rate was dropped before the 0.76 release. Might have to regen your conf to get the latest settings (see the first para in any of the new release notes).

**Comment by Jkapp76** [comment]
I tried this build some more. It also sounds significantly better even with the rate set to 44100. It may snap a little when sound begins and ends, but it is much better.

**Comment by Jkapp76** [comment]
You probably know this, but... the newest development build .192 has the sound issue back. The .152 version linked above sounded much better. Whatever was changed in .152 was a big improvement for the Jumpman music.

**Comment by kcgen** [comment]
Thanks for checking @Jkapp76 ; that's expected right now, because this fix hasn't been merged yet. Will let you know when there's more to test!

**Comment by Jkapp76** [comment]
The latest release, 0-363 seems to work much better for this game. (perfect really)
I loaded Jumpman about 20 times to test the intro music. 
Also, one odd note about 10 seconds into the theme tune for Below the Root sounds better now too. (I was never sure about that one)

Great Job!

**Comment by Wengier** [comment]
Great to hear that it works for you, @Jkapp76.
