### ISSUE TITLE
Ubuntu/Mint PPA contains wrong version

### ISSUE THREAD

**Issue by FBachofner** [dosbox-staging/dosbox-staging#1544]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Different version than latest?

n/a -- installation issue

### What Operating System are you using?

Linux x86_64

### Whats your question and how can we help?

When adding the PPA indicated at https://dosbox-staging.github.io/downloads/linux/
to LinuxMint 20.3, `apt-get install dosbox-staging` installs version 0.76.

[Launchpad](https://launchpad.net/~feignint/+archive/ubuntu/dosbox-staging) indicates the PPA _shoud_ install 0.78.1

`apt-cache policy dosbox-staging`

yields the following:

> dosbox-staging:
>   Installed: (none)
>   Candidate: 0.76.0-1+ubuntu20.04
>   Version table:
>      0.76.0-1+ubuntu20.04 500
>         500 http://ppa.launchpad.net/feignint/dosbox-staging/ubuntu focal/main amd64 Packages

This is not a bug in the dosbox-staging _code_, so I am posting this as a question.  Launchpad itself is not letting me log in with my UbuntuOne credentials, so I am reporting here.

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by kcgen** [comment]
I'm not seeing Ubuntu (or Mint) in the repology listing: https://repology.org/project/dosbox-staging/versions

The repository package maintainers are responsible for managing their packages (and versions).  Do you know who's taking care of the Mint (or maybe Ubuntu) Staging PPA? I would suggest contacting them.

**Comment by FBachofner** [comment]
The maintainer is [feignint](https://launchpad.net/~feignint)

Since I can for whatever reason (won't accept credentials I know to be correct) not log into Launchpad, I can not get the maintainer's e-mail address.

**Comment by FBachofner** [comment]
I found an identically named user on StackOverflow, but of course that silly site does not allow DMs

**Comment by apandada1** [comment]
The build failed due to missing dependencies. https://launchpad.net/%7Efeignint/+archive/ubuntu/dosbox-staging/+build/22993444

**Comment by kcgen** [comment]
@feignint, can you try removing slirp from the dependencies? Meson will embed it statically without any system dependencies or shared libraries needed.

**Comment by arrowgent** [comment]
yes the ppa is kind of old
i saw this ppa the other day and skipped it mainly since the binaries provided here and compiling yourself are both fairly easy.
i even thought like you did of reporting here that it was outdated

**Comment by arrowgent** [comment]
also what is interesting, the weekly repo seems to be updated and compiled just fine

**Comment by apandada1** [comment]
No, the week repo has similar [build failures](https://launchpad.net/~feignint/+archive/ubuntu/dosbox-staging-weekly/+packages) due to [missing dependencies](https://launchpad.net/~feignint/+archive/ubuntu/dosbox-staging-weekly/+build/23081420). 
![image](https://user-images.githubusercontent.com/3063132/150986365-e881e64f-d619-4843-ae86-0806bfe8a713.png)

**Comment by FBachofner** [comment]
Hi @arrowgent

> also what is interesting, the weekly repo seems to be updated and compiled just fine https://launchpad.net/~feignint/+archive/ubuntu/dosbox-staging-weekly

Whether weekly works or not is secondary to the issue here.

Keep in mind, many gaming users (and especially newbies) will shy away from alpha software.  They generally want something known to "just work."

**Comment by FBachofner** [comment]
Hi @arrowgent

> yes the ppa is kind of old i saw this ppa the other day and skipped it mainly since the binaries provided here and compiling yourself are both fairly easy. i even thought like you did of reporting here that it was outdated

Keep in mind, many will not know how to install/use a binary.  Even more so with compiling.

I do the former frequently as more moves away from PPAs to Flatpaks and Snaps (neither of which I particularly like), but manually installing software also then leads to needing to make shortcuts and the like.

What a pain.

> launchpad allows you to email users (the maintainer), if you have a login with launchpad.

As mentioned, I have such a login but am unable to get in.  Also can't reset the password (e-mail claims "sent" but does not come through, even to spam!)  Meanwhile, I can not create "new" account because the e-mail address is already in use.

I was a very early Ubuntu unified login (forgot what they called it before "Ubuntu One") account holder.  It seems to be a huge mess for those of us who also used Launchpad (maybe because of infrequency?)

**Comment by FBachofner** [comment]
Hi @kcgen

>@FeignInt, can you try removing slirp from the dependencies? Meson will embed it statically without any system dependencies or shared libraries needed.

I later noticed that the Flatpak (on Flathub) to which the install page links is ALSO out of date (likewise 0.76)

Now the [link](https://flathub.org/apps/details/io.github.dosbox-staging) doesn't even work at all!

On the other hand, perhaps this means it is being updated?

**Comment by kcgen** [comment]
> I later noticed that the Flatpak (on Flathub) to which the install page links is ALSO out of date (likewise 0.76)
> 
> As of a few minutes ago the [link](https://flathub.org/apps/details/io.github.dosbox-staging) doesn't even work at all!
> 
> On the other hand, perhaps this means it is being updated?

hi @FBachofner - thanks for checking these.  Looks like that flatpack is still at 0.76. 
If you can inform them, that would be a big help. :+1:

**Comment by apandada1** [comment]
> Looks like that flatpack is still at 0.76.

Already reported https://github.com/flathub/io.github.dosbox-staging/issues/4

**Comment by FBachofner** [comment]
Hi @kcgen 

> hi @FBachofner - thanks for checking these. Looks like that flatpack is still at 0.76. If you can inform them, that would be a big help. +1

Looks like the report is already done (thanks @apandada1 !)

I'm not sure I understand the Flathub ecosystem.  Doesn't it fall on the developer to make a flatpak and upload it to Flathub?

Your comment makes it sound like _they_ make the package . . . 


Side note: while waiting for the PPA and/or Flathub to update, I manually installed the binary of 0.78.1  --  It works awesomely!  **Thanks to all involved.**

It is **_so_** much easier to get sound working now that synthesizers are built right in versions >=0.77 !

**Comment by kcgen** [comment]
> I'm not sure I understand the Flathub ecosystem. Doesn't it fall on the developer to make a flatpak and upload it to Flathub? Your comment makes it sound like they make the package . . .

I would say your understanding is correct from my read of the documentation as well: Flathub wants the developers (maintainers) to be responsible for defining, submitting, and maintaining flatpaks. 

There are other self-contained formats like Flatpak - with large user bases and actively supported:
 - AppImage (https://appimage.org/)
 - Guix Packages (https://guix.gnu.org/en/packages/)
 - Nix Packages (https://search.nixos.org/packages)
 - Snap (https://snapcraft.io/)
 - Zero Install (https://0install.net/)

And those are the just the one for Linux. I'm sure we could find more for BSD, macOS, and Windows as well.

So when the task comes to learning how to construct packages to satisfy these formats, to put together scripts or other tooling to create said packages, to maintain and stay current with these package format's best practices, metadata, and finally, to support bug reports and issues arising from just these packages themselves: unfortunately this is beyond what I'm willing to personally put my time into. Infact, ii's too much even for most businesses with fulltime employees and paying customers. 

I (and other project contributors) have appreciated the folks who volunteered to build these packages in the first place. But it seems they've gone stale.  At a minimum, we should have those old packages pulled down and we can see if someone else would like to take up this task.

**Comment by FBachofner** [comment]
HI @kcgen

> Yes; the Flathub project wants 3rd party developers to do the work of creating, submitting, and maintaining packages in their Flathub repository.
> [...snip...]
> So when the task comes to learning how to construct packages to satisfy these formats, to put together scripts or other tooling to create said packages, to stay current with these projects' best practices, and finally, to field bug reports arising from behavioral and security related nuances imposed by the packages runtime wrappers: unfortunately this is beyond what I'm willing to personally put my time into. (Infact, it's too much even for most businesses with paying customers and fulltime technical staff.)

This is _totally understandable_ -- but also sad.  Dosbox-Staging has reinvigorated a critically important piece of technology to assure historic software can still be used. 

The only other realistic options (DOS on running on actual hardware or in a VM) have their place, but sometimes have vexing limitations.

> I (and other project contributors) appreciate the folks who volunteered to build these packages in the first place. But it seems they've gone stale. At a minimum, we should have those old packages pulled until someone can step forward and volunteer to take on this task going foward.

Your assessment of "stale" seems spot on.  3 days later, the packager "Feignint" has not responded to [my post to their account](https://github.com/FeignInt/dosbox-staging-deb/issues/16), nor (apparently) updated the PPA.

 
I agree the first thing to do is to have the non-current packages pulled _as quickly as possible_.

I, for example, initially thought: "oh great, another empty tech promise" when built-in MIDI did not work.  Fortunately, on _uninstall_ I noticed that version 0.76 was being removed . . . leading to more investigation (since I had previously read that this inbullt functionality was not available until >=0.77.x ).

Not everyone would notice that type of detail, but I'd like to hope that the types of users contemplating installing / using dosbox _would_ be willing to try a manual install **right off the bat** if a PPA and/or flatpak is not available -- especially since the dosbox-staging install page is so clear on required dependencies.  The only real "hassle" after all is setting up shortcuts and/or scripts to launch it.

While you do not have time to make packages, can you give me a quick idea on what is involved -- a bit beyond your comments above?  Maybe I could help moving forward.

Is making a PPA just a question of compressing/bundling/uploading (or otherwise somehow arranging the binary files a developer provides)?  . . . OR, is it yet another (potentially lengthy?) build process?  _Must_ a PPA be generated from source files?

I would almost certainly be able to assist for a number of cycles (maybe until you reach v 1.x ?) in the first case (compressing/bundling/uploading).  The latter might be challenging as (among other issues) I probably don't want to load more tools on my machines at the moment.

I can read up on creating and maintaining PPAs over the weekend, but your quick take might be very useful to encourage or discourage me.

BTW, on a related note: I would almost certainly NOT be interested in packaging flatpaks.  I am disappointed that 3rd party software proponents and supporters of Debian derivatives seem to be dropping PPAs left and right and even _more_ disappointed that Canonical is specifically pushing Snaps (a closed ecosystem).

**Comment by FBachofner** [comment]
> Is making a PPA just a question of compressing/bundling/uploading (or otherwise somehow arranging the binary files a developer provides)? . . . OR, is it yet another (potentially lengthy?) build process? _Must_ a PPA be generated from source files?
> 
> I would almost certainly be able to assist for a number of cycles (maybe until you reach v 1.x ?) in the first case (compressing/bundling/uploading). The latter might be challenging as (among other issues) I probably don't want to load more tools on my machines at the moment.
> 
> I can read up on creating and maintaining PPAs over the weekend, but your quick take might be very useful to encourage or discourage me.

D'Oh!  Thinking about this for just a few _seconds_ . . .

I guess the first step to getting to a PPA would be to create a .deb file, which dosbox-staging has not done.

So it seems I just need to figure out how "complicated" it would be to go from the binary you provide to a .deb file.

Come to think of it, maybe just distributing a .deb file coupled with the efforts of the great packagers at the Arch AUR might already cover ~90% of dosbox users' needs.

**Comment by apandada1** [comment]
The PPA package failed to build from due to missing dependencies in older versions of Ubuntu. Even if you distribute .deb files, it may not work due to missing dependencies. However, flatpak and snap should not have this issue (as they ship the dependencies along with the package).

Maybe add a note in the readme that these packages are outdated, and Ubuntu users should use the binaries provided in GitHub.

> Come to think of it, maybe just distributing a .deb file coupled with the efforts of the great packagers at the Arch AUR might already cover ~90% of dosbox users' needs. In the presence of a good .deb file, maybe a PPA is not needed (except for "automatic" update capability, of course).

Arch contains all the latest packages, and thus, it does not have the dependency issues like Ubuntu. Sadly, it is not as widely used as Ubuntu and Debian based operating systems.

**Comment by apandada1** [comment]
@kcgen  Maybe the developers of dosbox-staging can ask the snap maintainer to either update the package or pull it down. https://github.com/popey/dosbox-staging-snap

**Comment by kcgen** [comment]
In the meantime, the build instructions _should_ be step-by-step  (if not, please file a bug!). Another option is to unpack and run the binaries. 

@FBachofner - having more people helping the project is great news. If you can step through the deb/PPA process, that would be a big help. 

@apandada1 , thanks for the heads up regarding the snap package. I've left a note there asking for it to be updated or removed.  I am reluctant to get too involved with shepharding and dealing with all these packaging formats (even mentioning which are up to date and which aren't - now I've got to track those and keep documents current) - even asking for packages to be removed now injects me into the loop.. I really want this to be completely "beyond my involvement").  I don't mean this in a negative way: it's just me setting a boundary to trying to manage my time.

**Comment by Grounded0** [comment]
Flathub is updated to DOSBox Staging 0.78.1:

https://github.com/flathub/io.github.dosbox-staging/pull/5

**Comment by Grounded0** [comment]
Flathub is updated to DOSBox Staging 0.78.1:

https://github.com/flathub/io.github.dosbox-staging/pull/5
