### ISSUE TITLE
Compile error "fluid_synth_key_pressure’ was not declared in this scope"

### ISSUE THREAD

**Issue by orderorder** [dosbox-staging/dosbox-staging#1553]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### What Operating System are you using?

Linux x86_64

### If Other OS, please describe

Manjaro Linux

### Relevant hardware info

AMD A10-7850K Radeon R7

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Compile error.

### Steps to reproduce the behaviour.

Explain how to reproduce
1. meson setup \
    -Dbuildtype=release \
    -Ddefault_library=static \
    -Db_asneeded=true \
    -Dtry_static_libs=png \
    -Dfluidsynth:enable-floats=true \
    -Dfluidsynth:try-static-deps=true \
  build
2. meson compile -C build

### Provide a Log

```text
FAILED: src/midi/libmidi.a.p/midi_fluidsynth.cpp.o 
ccache c++ -Isrc/midi/libmidi.a.p -Isrc/midi -I../src/midi -I../include -I. -I.. -Isrc/libs/ghc -I../src/libs/ghc -Isrc/libs/loguru -I../src/libs/loguru -I/usr/include/SDL2 -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/sysprof-4 -I/usr/include/opus -I/usr/include/pipewire-0.3 -I/usr/include/spa-0.2 -I/usr/include/dbus-1.0 -I/usr/lib/dbus-1.0/include -I/usr/include/libinstpatch-2 -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wnon-virtual-dtor -Wextra -Wpedantic -std=c++17 -g -Wmaybe-uninitialized -Weffc++ -Wextra-semi -shared-libgcc -fPIC -pthread -D_DEFAULT_SOURCE -D_XOPEN_SOURCE=600 -D_REENTRANT -MD -MQ src/midi/libmidi.a.p/midi_fluidsynth.cpp.o -MF src/midi/libmidi.a.p/midi_fluidsynth.cpp.o.d -o src/midi/libmidi.a.p/midi_fluidsynth.cpp.o -c ../src/midi/midi_fluidsynth.cpp
../src/midi/midi_fluidsynth.cpp: En la función miembro ‘virtual void MidiHandlerFluidsynth::PlayMsg(const uint8_t*)’:
../src/midi/midi_fluidsynth.cpp:466:17: error: ‘fluid_synth_key_pressure’ was not declared in this scope; did you mean ‘fluid_synth_channel_pressure’?
  466 |                 fluid_synth_key_pressure(synth.get(), chanID, msg[1], msg[2]);
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~
      |                 fluid_synth_channel_pressure
[181/242] Compiling C++ object src/misc/libmisc.a.p/ansi_code_markup.cpp.o
ninja: build stopped: subcommand failed.
```

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

[log.txt](https://github.com/dosbox-staging/dosbox-staging/files/7981409/log.txt)

**Comment by kcgen** [comment]
Please post the FluidSynth package version installed in manjero. 
Please do a `git clean -fdx` , then re-setup and build, and post that entire log for both steps as a text attachment.

**Comment by orderorder** [comment]
[log.txt](https://github.com/dosbox-staging/dosbox-staging/files/7981417/log.txt)

Same error after your instructions. My fluidsynth version is 2.2.4

**Comment by kcgen** [comment]
Thanks @orderorder ; can you capture the entire meson log output from both the setup step and the compile step?

**Comment by orderorder** [comment]
[meson-log.txt](https://github.com/dosbox-staging/dosbox-staging/files/7981627/meson-log.txt)
[setup.log](https://github.com/dosbox-staging/dosbox-staging/files/7981659/setup.log)

**Comment by kcgen** [comment]
Thanks @orderorder ; I didn't see anything obvious.
Can you paste this command and then attach `/tmp/fluidsynth_version_scan.txt`

```shell
find /usr -name '*.h' \
  | grep -i fluidsynth \
  | xargs grep -i FLUIDSYNTH_VERSION > /tmp/fluidsynth_version_scan.txt
```

**Comment by orderorder** [comment]
[fluidsynth_version_scan.txt](https://github.com/dosbox-staging/dosbox-staging/files/7988362/fluidsynth_version_scan.txt)

**Comment by orderorder** [comment]
Sorry, it seems that residual archives from another fluidsynth compilation (another version) were breaking the dosbox compilation. This archives were in /usr/local/include/fluidsynth. Thanks for the "find" trick

**Comment by kcgen** [comment]
Right on @orderorder.

**Comment by kcgen** [comment]
Renamed for future lookup.
