### ISSUE TITLE
Redirecting command output to NUL causes error message

### ISSUE THREAD

**Issue by FeralChild64** [dosbox-staging/dosbox-staging#1555]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Different version than latest?

dosbox (dosbox-staging), version 0.79.0-alpha-192-gdf4add04+

### What Operating System are you using?

Linux x86_64

### If Other OS, please describe

Gentoo, custom ebuild

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Command output redirection to NUL stopped working correctly, it displays an error message. This must be a recent regression (like within the last week), it did work correctly before.

### Steps to reproduce the behaviour.

1. From the DOSBox command line (internal COMMAND.COM) execute any command with output redirection to NUL, for example `dir > NUL`
2. As a result, I see an error message `File creation error - NUL` - I expect no output at this point

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by FeralChild64** [comment]
It seems you were pulling the fix more or less the same time I was filling in a bug report :)
I'll try it, but not at this moment (I have to go now).

**Comment by FeralChild64** [comment]
Just checked - commit https://github.com/dosbox-staging/dosbox-staging/pull/1554/commits/e1aa72dacabaed7667e5e2b2b6a04c261fbd413c fixes the bug.

**Comment by kcgen** [comment]
@Wengier , can you add a couple unit test cases covering the good and bad scenarios covered by this fix? (So we can do more refactoring in downstream code, and be confident we don't regress in this functionality).

**Comment by Wengier** [comment]
@kcgen Since the fix is located in the ParseLine function (rather than the GetRedirection function), I assume you meant unit test cases for the ParseLine function. I will think about better ways to test it. Thanks for the suggestion.
