### ISSUE TITLE
Game Blaster regression "static audio" since 0.78.0

### ISSUE THREAD

**Issue by Burrito78** [dosbox-staging/dosbox-staging#1557]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Different version than latest?

Latest DEV v0.79.0-alpha-193-g725ff

### What Operating System are you using?

Mac OS

### If Other OS, please describe

MacOS 11.6.3 (Intel)

### Relevant hardware info

Macbook Pro 13" (Mid 2014)

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

In The Secret of Monkey Island EGA (v1.0, Interpreter 4.0.62), audio is output but it is heavily distorted.
I used this version: https://archive.org/details/001276-TheSecretOfMonkeyIsland
Use this for copy protection: https://www.oldgames.sk/codewheel/secret-of-monkey-island-dial-a-pirate

This isn't a speed issue, tried cycles < 1000.
This isn't a detection issue, tried "monkey" and "monkey g" for "Game Blaster".

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Install latest DEV with default settings.
2. Change sbtype to "gb"
3. Install and launch game.

### Your configuration

```ini
sbtype = gb
```

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by Burrito78** [comment]
DOSBox Staging 0.78.1 has the same issue.

Vanilla DOSBox is fine.

**Comment by Burrito78** [comment]
Issue happens also with the VGA version of the game. I used this one:
https://archive.org/details/003048-TheSecretOfMonkeyIsland

**Comment by Burrito78** [comment]
Prince of Persia is also affected so it seems GB is universally broken in 0.78.1 and newer.
https://archive.org/details/002475-PrinceOfPersia

**Comment by Python-Exoproject** [comment]
Ive experienced this in numerous games using 64bit 78.1 on pc as well so seems GB is borked at the moment all round
