### ISSUE TITLE
Sound of Jurassic Park (CD-ROM version) is to quiet

### ISSUE THREAD

**Issue by naatje80** [dosbox-staging/dosbox-staging#1558]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### What Operating System are you using?

Linux x86_64

### If Other OS, please describe

RockyLinux 8

### Relevant hardware info

Intel(R) Core(TM) i7-10700K CPU, GPU: NVIDIA GeForce GTX 1050 Ti 

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

I noticed that whenever I play Jurassic Park (at least for the CD-ROM version of the game, I did not check the diskette version) the sound is to quite. Especially the CD music is to soft. There is a similar know issue with Wipeout (in that case the Sound effects are to soft compared to the CD music), so I assumed this was related. 

Like required for Wipeout: I changed the sound settings using the MIXER command, but did does not seem to help. However, because I was playing around with the MIXER command, I noticed that either due to a bug or because the game itself (not sure if a game is able/allowed to do this, I was not aware of the existence of the MIXER command in a "normal" DOS environment), the output of CDAUDIO, FM and SB are lowered to 10:10 (instead of the default setting 100:100). It does not help if I first set the level to e.g. 200:200. As soon as jp.exe is executed, the volume is back on 10:10 for CDAUDIO FM and SB channel. (see screenshot for the output of the mixer command after executing jp.exe)

Could this be a bug? Is there a certain way to prevent this? I would not mind to make some changes to the code and recompile a specific version for Jurassic Park...

![mixer_output](https://user-images.githubusercontent.com/26620355/152378887-99e4634e-30cc-4344-9f36-61b83ab2abaf.png)
.

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Execute mixer coomand. The volume of all channels should be on 100:100
2. Mount and install jurassic park cdrom edition
3. Execute: cd jurassic park
4. Execute: jp.exe
5. Quit the game
6. The volume of the CDAUDIO, SB and FM channels are lowered to 10:10.

### Your configuration

```ini
[autoexec]
# Lines in this section will be run at startup.
# You can put your MOUNT lines here.
mount c: ./C-Drive
c:
# Uncomment for installation
#jpfix.com
#mixer cdaudio 500:500
imgmount d: ./CD/jurassic.cue -t cdrom
d:
cd jurassic
jp.exe
exit
```

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by kcgen** [comment]
@naatje80 , thanks for the thorough report and detailed reproduction steps.

Yes, real SB cards came with an internal volume mixer for various channels that the card had control over (PCM, FM, and CDDA), which software can change.  DOSBox has emulated this for quite some time, and Staging hasn't touched this area (so we believe it should act the same). 

So in this case - does Jurassic Park have in-game volume controls? 

If not, you can block the game from tampering with these settings:

``` ini
[sblaster]
sbmixer  = false
```

Or in your startup batch file, just run: `sbmixer false` before the game launches.

**Comment by naatje80** [comment]
@kcgen: Thank you for your quick reply! We only owned clones instead of the real thing. Possible that was the reason why I'm not familiar with the mixer settins. I was also a lot of years younger during those days  :D 

Unfortunately there is only an option to switch off/on the sound and music. So even more strange why Jurassic Parks does a default "reset".... 

But your suggestion works great! The CD Music is now loud enough with the sound effect covering up the music.

Thank you for your clear explanation and quick solution!
