### ISSUE TITLE
Avoid loading duplicate conf files

### ISSUE THREAD

**Issue by kcgen** [dosbox-staging/dosbox-staging#1562]
Assuming the current directory contains `dosbox.conf`, launching with `dosbox -conf dosbox.conf` will result in the conf being loaded twice:

```
2022-02-10 14:59:56.458 | CONFIG: Loaded local conf file dosbox.conf
2022-02-10 14:59:56.460 | CONFIG: Loaded custom conf file .\dosbox.conf
```

This is because Staging by default automatically loads `dosbox.conf` if it's found in the current-working-directory. Additionally, Staging also loads any manually specified `-conf` files. 

A solution for this should be generic, for example: `-conf A -conf B -conf C -conf A` should de-dupe the last `A`.

Thanks to @shermp for catching this subtlety!

**Comment by shermp** [comment]
Probably the easiest way to handle this might be to save the resolved path of the file into a set or map, and only load a config if the file path isn't already in the set/map.

**Comment by shermp** [comment]
I've created a test branch https://github.com/dosbox-staging/dosbox-staging/tree/sp/parseconf-std-fs-1 which refactors `Config::ParseConfigFile()` to use `std_fs::path`, and prevents loading duplicate config files.

It's probably going to need some extensive regression testing, especially around non-ascii filenames/paths, if they ever worked in the first place that is...
