### ISSUE TITLE
Audio artifacts with Sound Blaster 16 emulation in DOSBox 0.79.0 alpha

### ISSUE THREAD

**Issue by Kappa971** [dosbox-staging/dosbox-staging#1573]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Different version than latest?

v0.79.0-alpha-205-g1ecda

### What Operating System are you using?

Windows 11

### Relevant hardware info

AMD Ryzen 5 1600, Nvidia GeForce GTX 1060

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Sound Blaster 16 emulation in DOSBox 0.79.0 (master branch) creates audible audio artifacts in Tyrian 2000 (maybe in other games too). This doesn't happen in DOSBox 0.78.1. This is an example file of the issue: [T2k_DOSBox0.79.zip](https://github.com/dosbox-staging/dosbox-staging/files/8084215/T2k_DOSBox0.79.zip)
 

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Run DOSBox 0.79.0 alpha
2. Run Tyrian 2000 (tyrian2k.exe)

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by shermp** [comment]
I think I can confirm this. My ears are far from golden, but after switching back and forwards between 0.78.1 and a recent build from main, it seems like there's some artifacts.

To me, I seem to notice it most with explosions. 

If someone else hasn't already got to it tomorrow, I'll see if I can find where it changes. Prime culprit is probably the DMA stuff @kcgen added a little while ago.

**Comment by kcgen** [comment]
> To my non-golden ears, main now sounds very very close to 0.78.1. I'm glad you figured it out.

All credit to you and @Kappa971 for the figuring ; thanks guys! :beers:

**Comment by Kappa971** [comment]
I confirm that this solved the issue, thanks @kcgen.
