### ISSUE TITLE
snap version breaks home directory

### ISSUE THREAD

**Issue by yendor26** [dosbox-staging/dosbox-staging#1579]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### What Operating System are you using?

Linux x86_64

### If Other OS, please describe

Kubuntu Debian and Opensuse (all KDE)

### Relevant hardware info

Intel integrated graphics

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Hi, when opening dosbox-staging snap version for the first time, all folders in the Home directory of GNU/Linux (Downloads, Documents, etc) become inaccessible, and their icon no longer is a folder, they look instead like some kind of links. Type of file unkown. When trying to open them an error pops up that it cant be opened. (sorry i didnt take screenshots). Even after restarting, removing dosbox-staging and even snapd, the problem remains.

 Tested in 3 different distributions: Kubuntu 21.10, Debian 11 and Opensuse Tumbleweed. All with KDE, all same result

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Install snapd in a GNU/Linux distribution (tested only in KDE)
2. install dosbox-staging snap
3. Open dosbox-staging, and close
4. Open Dolphin (KDE file manager) and see Home directory

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by kcgen** [comment]
@yendor26 , please open this with the snap project.

The behavior you're describing is due to runtime limitations imposed by the snap environment. 

> all folders in the Home directory of GNU/Linux (Downloads, Documents, etc) become inaccessible, and their icon no longer is a folder, they look instead like some kind of links. Type of file unkown. When trying to open them an error pops up that it cant be opened. (sorry i didnt take screenshots). Even after restarting, removing dosbox-staging and even snapd, the problem remains.


Please inform those who are those responsible for creating the snap package.  We won't be facilitating issues with 3rd party packages here.

**Comment by yendor26** [comment]
thanks! will do

**Comment by Grounded0** [comment]
https://github.com/popey/dosbox-staging-snap/issues/12
