### ISSUE TITLE
buggy [autoexec] using invalid goto causing segfault (bisected)

### ISSUE THREAD

**Issue by AaronBPaden** [dosbox-staging/dosbox-staging#1591]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Different version than latest?

git main

### What Operating System are you using?

Linux x86_64

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Jumping to an invalid label can cause a segfault.

### Steps to reproduce the behaviour.

Pressing 2 after loading the provided conf should trigger the segfault.

### Your configuration

```ini
[autoexec]
@echo off
mount c .
c:
choice /c123 /n "Choice:"
if errorlevel 1 goto e1
if errorlevel 2 goto e2
if errorlevel 4 toto e3

e1:
exit

e2:
goto e5
echo test

e3:
exit
```

### Provide a Log

Results of `git bisect`: 67dee0b93a3ff1d0e967c045b8697cf0e21ab626 is the first bad commit

gdb backtrace: https://gist.githubusercontent.com/AaronBPaden/10e16ec1b367add6f7368b11684723c3/raw/d653215acf1004d20134e9eee96d19b0af4a6e58/gistfile1.txt

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by kcgen** [comment]
Thanks for catching this @AaronBPaden, and for bisecting this down.
Looks like there's a bit more to fixing this particular memory leak. You nice unit tests will help narrow this down.. :+1:
