### ISSUE TITLE
What is the status of long filename support (LFN)?

### ISSUE THREAD

**Issue by JKjakay** [dosbox-staging/dosbox-staging#1607]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### What Operating System are you using?

Linux x86_64

### Whats your question and how can we help?

Is the LS command within dosbox-staging able to display long filenames (LFN)? I saw some closed issues on github regarding this, but it seems it is not yet implemented. I would really love to see this. Forgive me if I just cant find out how.

The reason is that I like to browse through my DOS games with a DOS shell just in the old times. But I absolutely hate (as I did in said times), to have to remember what BENASTEE or GAM45FT1 stands for... So I tend to rename the directories, or better, if I am nostalgic, to place the BENASTEE within a long filename directory called "Beneath a Steel Sky". Really a great invention, long filenames...

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by kcgen** [comment]
LFN was attempted by @Wengier through great effort, however addressing all of the code changes lead to over 100 discussion points and, at the time, was more effort that the project could handle.  You can see those discussions here: https://github.com/dosbox-staging/dosbox-staging/pull/476

With time and with design changes, it's likely we will add LFN, but before that happens there are many emulation holes and bugs that will come before.

It sounds like DOSBox-X would be perfect for your case, as it has excellent late-DOS era features supporting Windows 95+, LFN, (and many more).

Another option, if you enjoy text interfaces in general, is to skip the emulation layer and use a native TUI like Midnight Commander (MC) or GoFul (https://github.com/anmitsu/goful).  

Lots of other fun stuff here: https://github.com/rothgar/awesome-tuis !
