### ISSUE TITLE
Different results with `openglpp` and `texturepp` on macOS Retina screens

### ISSUE THREAD

**Issue by tobx** [dosbox-staging/dosbox-staging#1611]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### What Operating System are you using?

Mac OS

### Relevant hardware info

MacBook Pro (15-inch, 2016)

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

On Retina screens `openglpp` produces a pixel perfect result, but `texturepp` seems to produce a pixel perfect result only for the half resolution and then scales up to Retina (smoothing pixel borders):

openglpp:
![openglpp](https://user-images.githubusercontent.com/6427718/161388189-8e17dc34-7ae1-4ab4-9a43-b9584770ae89.png)

texturepp:
![texturepp](https://user-images.githubusercontent.com/6427718/161388190-07e66442-ec86-4fac-b5a0-cab882cb169f.png)

**Note:** I resized both images to double size (Nearest Neighbour) for better visibility.

I am not sure if this is really a bug or if this is due to SDL behaviour that cannot be changed, but at the following link it is said that both options should behave the same, so I guess at least this part might be updated:

https://dosbox-staging.github.io/v0-76-0/#2-4-add-integer-scaling-pixel-perfect-option-for-opengl-output

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Set config either to

   ```ini
   [sdl]
   output = texturepp
   ```

   or

   ```ini
   [sdl]
   output = openglpp
   ```

2. Compare the results

### Your configuration

```ini
# I did not touch the default configuration except the `output` setting.
```

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by tobx** [comment]
I guess this is related to #1616. If so, I am happy to close this one.

**Comment by GranMinigun** [comment]
I'll tell you more: it's most likely related to #759. You can try out a current WIP build from [here](https://github.com/dosbox-staging/dosbox-staging/actions/runs/2084304617).

**Comment by tobx** [comment]
@GranMinigun Yes, the WIP solves the issue for me.

**Comment by GranMinigun** [comment]
The initial support for DPI scaling has been merged (see #1745). I'll leave the issue opened for the time being, just in case. You can grab the latest development builds to test and report on any weird behaviour.

**Comment by Burrito78** [comment]
@kcgen Latest main produces identical output for

`output = texturepp`

and

`output = openglpp`

Ticket should be closed, imho?

**Comment by Grounded0** [comment]
Closing as completed.
