### ISSUE TITLE
About changing the contents of Drive Z:

### ISSUE THREAD

**Issue by Jkapp76** [dosbox-staging/dosbox-staging#1612]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### What Operating System are you using?

Windows 11

### Whats your question and how can we help?

Did I read somewhere that we can now modify the contents of drive Z:  ?

If so, can I get some instructions on how this works?

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by Wengier** [comment]
Yes, but only available in the current Git release, and will be available for the next release version. You can put files in the drivez directory of the DOSBox directory, and they will show up on Z drive, replacing existing files if any. Hope this helps.

**Comment by Jkapp76** [comment]
Yes, this works great! It allows me to eliminate one mounted drive too.
