### ISSUE TITLE
Use the FreeDOS choice command instead of the current one

### ISSUE THREAD

**Issue by tobx** [dosbox-staging/dosbox-staging#1615]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### What Operating System are you using?

Mac OS

### Is your feature request related to a problem? Please describe.

Some old games (e.g. Worms) include batch scripts to start. Those scripts call `CHOICE.EXE`. The choice version that DOSBox Staging uses is not fully compatible with the original version from MS-DOS (different command line flags): https://en.wikipedia.org/wiki/Choice_(command). The scripts can fail in this case.

I do not have any background on this, so there might be good reasons, but I thought I mention it.

### Describe the solution you'd like

The choice command should be compatible with the one from MS-DOS.

### Describe alternatives you've considered

The FreeDOS version is compatible:
https://www.ibiblio.org/pub/micro/pc-stuff/freedos/files/distributions/1.2/repos/pkg-html/choice.html

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by kcgen** [comment]
Thanks @tobx ; can you please post step(s) so we can reproduce the exact CHOICE.EXE failure?

This will let us assess if it makes sense to fill in that hole or if it makes more sense to swap in the FreeDOS executable.

**Comment by Wengier** [comment]
If there’s indeed a failure with the builtin CHOICE program which is not trivial to fix, I also support to swap in the FreeDOS one in this case since most likely it would not cause other issues such as LFN incompatibility.

**Comment by tobx** [comment]
The exact command from the game is:

```
choice /C:NS /N /T:N,3 "Press S to skip intro and quick-load the game..."
```

DOSBox displays:

```
/T:N,3 Press S to skip intro and quick-load the game...
```

and does not respect the `/T` flag that should wait for 3 seconds and then automatically choose the default option `N`.

The FreeDOS version displays:

```
Press S to skip intro and quick-load the game...
```

and chooses the default option `N` after 3 seconds.

So there is not really a failure, but the timeout is not respected and the user does not know how to _not_ skip the intro if he does not understand the choice command.

The only option missing seems to be `/T` for the timer. There is also `/B` to beep when asking for input, but I guess this is negligible.

**Comment by Wengier** [comment]
Looking at the code, the built-in CHOICE command is a simple version of the DOS counterpart, so the /T option is not supported, and /T:... (with a :) will be displayed as is. For the latest Git version you can replace the built-in CHOICE command with the FreeDOS one manually by putting the latter in the drivez directory of the DOSBox directory, so that the FreeDOS version will be used instead. Hope this helps.

**Comment by Wengier** [comment]
The PR #1624 should fix this issue by adding support for /T option, while preserving the style of the help messages as used by DOSBox Staging (instead of the FreeDOS style).
