### ISSUE TITLE
Jazz Jackrabbit 4:3 Letter-Box not displaying

### ISSUE THREAD

**Issue by OpenRift412** [dosbox-staging/dosbox-staging#1621]
In Jazz Jackrabbit, the game's 320x199 resolution is meant to be displayed with letterboxing on the top and bottom on a 4:3 display (seen [here](https://github.com/dosbox-staging/dosbox-staging/issues/317#issuecomment-619403292).) In Staging, it does display the actual game screen at the appropriate 16:10-ish aspect ratio, but the letter boxing on the top and bottom is missing. This could be divisive kind of fix as it can be a matter of preference, so I propose that the letterboxing be restored when aspect=true and cropping it when aspect=false. Can that be done?

**Comment by OpenRift412** [comment]
Here's my config by the way:
[dosbox_jazz.txt](https://github.com/dosbox-staging/dosbox-staging/files/8497464/dosbox_jazz.txt)

**Comment by kcgen** [comment]
The current `main` branch will honor exact windowresolution=WxH, and will pillarbox or letterbox as needed to maintain the window size. 

So if you provide a common 4:3 resolution like, 1280x960, then when the game switches to the square-pixel VGA mode, you will get leterboxinf above and below. 

In that CRT screenshot, there's even an extra amount of padding around the sides, like a border, which you can simulate with `viewport_resolution=85%` (in the `main` build).

**Comment by OpenRift412** [comment]
> The current `main` branch will honor exact windowresolution=WxH, and will pillarbox or letterbox as needed to maintain the window size.

But what about in full screen?

**Comment by kcgen** [comment]
If you have a widescreen monitor (and matching resolution dimensions, such as 1920x1080), then your display's dimensions closely accomodate the 16:10 aspect the game is using, so there will probably be some slight pillarboxing on your display. 

(Because your display is even wider than what the game will use). 

If you still want top and bottom letterboxing, then set your viewport_resolution to something that's shaped like an actual CRT.  Say, 1366x1080

That will force staging to fit the game's 16:10 aspect inside the "taller" 4:3 box, and to do will will require letterboxing.

**Comment by OpenRift412** [comment]
> If you have a widescreen monitor (and matching resolution dimensions, such as 1920x1080), then your display's dimensions closely accomodate the 16:10 aspect the game is using, so there will probably be some slight pillarboxing on your display.
> 
> (Because your display is even wider than what the game will use).
> 
> If you still want top and bottom letterboxing, then set your viewport_resolution to something that's shaped like an actual CRT. Say, 1366x1080.
> 
> That will force staging to fit the game's 16:10 aspect inside the "taller" 4:3 box, which will require letterboxing.

Is `viewport_resolution` in the current dev build or is that in 0.78.1 as well?

**Comment by kcgen** [comment]
It's only in recent dev builds.

**Comment by kcgen** [comment]
Closing as this is addressed in the `main` branch.
