### ISSUE TITLE
ReShade is super laggy, to the point of uselessness

### ISSUE THREAD

**Issue by johnnovak** [dosbox-staging/dosbox-staging#1635]
### Different version than latest?

latest main & 0.78.1, 64-bit

### What Operating System are you using?

Windows 10 64-bit

### Relevant hardware info

NVidia RTX 3060

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Not exactly a bug, but not quite a feature request either...

When using [ReShade](https://reshade.me/) with DOSBox Staging, ReShade either cannot be activated at all with its hotkey, or it can but it's super laggy and the screen updates drop to 1-2 FPS or much less. Sometimes the ReShade UI can be activated with the hotkey after pressing it like 10-15 times, but then the whole application freezes and the process has to be killed.

This must have something to do with how DOSBox Staging handles input events. I know that in some games you have to pause the game first to be able to bring up the ReShade UI, but in many games there are no such issues.

For the record, WinUAE works flawlessly with ReShade, with no slowdowns whatsoever (although that's with a DirectX 11 backend).

While this is not a super important issue, the fix might be something quite trivial. I personally need ReShade to apply subtle bloom & glow effects on top of the CRT shader's output I set in DOSBox Staging (poor man's multipass shader setup, but hey, it does the job). Not being able to bring up the UI makes tweaking the ReShade shaders extremely cumbersome (I need to edit the preset file and restart DOSBox instead of tweaking parameters on the fly in the nice ImGUI interface).

If someone can give me a few pointers on what to try, I might experiment with a fix a bit, but I'm clueless as to where to start looking...

Same results with both the latest ReShade 5.x and the last 4.x version.

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by kcgen** [comment]
I wonder if driving it at a constant frame rate would help?

```ini
[sdl]
presentation_mode = cfr
```

**Comment by johnnovak** [comment]
> I wonder if driving it at a constant frame rate would help?

Yes! That was it! If I force CFR then the ReShade UI works flawlessly at max FPS in both windowed & fullscreen!

With the latest `main` I'm getting CFR in fullscreen and VFR in windowed with the default settings. It's just that on 0.78.1 the ReShade UI is always laggy (in fullscreen too), and for some reason I've only tested `main` with windowed.

I'm glad you helped me solve it! 🎉 

I've read https://github.com/dosbox-staging/dosbox-staging/pull/1596 and it contains a lot of important info that's not really apparent at all from the brief config descriptions of these parameters (e.g. why would you care about these options, in the first place). I know we have the wiki, but there's no DOSBox Staging User Manual project underway, is it? Many of these PR descriptions contain valuable information that could made their way into such a user manual with some editing, and normal users don't go on fishing expeditions for info to the GitHub issue tracker 😝 

Btw, here's my logs:

```
[ start in fullscreen ]

2022-05-01 09:59:59.481 | SDL: Using standard SDI (auto) display refresh rate of 60 Hz
2022-05-01 09:59:59.484 | DISPLAY: EGA 640x350 16 color (10h) at 70.086 Hz synced CFR, scaled by 2.0x2.7 to 1280x960 with 1.4 pixel-aspect

[ switch to windowed ]

2022-05-01 10:00:01.011 | DISPLAY: EGA 640x350 16 color (10h) at 70.086 Hz VFR, scaled by 2.0x2.7 to 1280x960 with 1.4 pixel-aspect
```

**Comment by kcgen** [comment]
I didn't realize that PR could also help the Reshade scenario; that's a new one!

> I've read https://github.com/dosbox-staging/dosbox-staging/pull/1596 and it contains a lot of important info that's not really apparent at all from the brief config descriptions of these parameters (e.g. why would you care about these options, in the first place). 

In general the presentation mode should 'pick the right mode' given the conditions; "right" being that it tries to avoid vsync issues.  But reshade is a new case where more information in the conf can definitely help the user.

In your default case, it it picks CFR when full screen because it's detecting some amount of vsync (be it hard-blocking at 60 Hz or adaptive vsync, which can digest frames a bit faster), and using synced-CFR to to avoid stalling DOSBox when the rendering rate goes beyond the host rate.

In Windowed mode, it's detected that it's not vsync bound, so is using VFR, which can present up to the full ~70 FPS without hitting any vsync walls. 

> I know we have the wiki, but there's no DOSBox Staging User Manual project underway, is it? Many of these PR descriptions contain valuable information that could made their way into such a user manual with some editing, and normal users don't go on fishing expeditions for info to the GitHub issue tracker

I'm all for that!  Maybe to begin with, we can collectively write up a nice description for the release notes (coming in ~June/July).  @omnicidle and @Kappa971 were a huge help in testing and shaping this feature, as they both have high-end VRR displays and performed extensive testing.   There are some gems in this 500-message-long discussion here, like this one: https://github.com/dosbox-staging/dosbox-staging/issues/1228#issuecomment-1064782763

**Comment by kcgen** [comment]
(think we can close this?)

**Comment by johnnovak** [comment]
Sure. About the changelog for the coming release, can you point me to it please? I'm guessing we will discuss the user manual later?

**Comment by kcgen** [comment]
> Sure. About the changelog for the coming release, can you point me to it please?

Not started yet (for 0.79), but I tend to summarize all the PRs for the timeframe.
Here's [0.78](https://dosbox-staging.github.io/v0-78-0/)'s, which is rendered from [markdown sources](https://raw.githubusercontent.com/dosbox-staging/dosbox-staging.github.io/pages/content/v0.78.0.md) on (from our .io repo: https://github.com/dosbox-staging/dosbox-staging.github.io).

> I'm guessing we will discuss the user manual later?

:+1: 

Added a discussion: https://github.com/dosbox-staging/dosbox-staging/discussions/1639

**Comment by kcgen** [comment]
@johnnovak , CFR is now used in text modes.
