### ISSUE TITLE
How do I change a conf paramater and reboot the instance?

### ISSUE THREAD

**Issue by Banjo-Oz** [dosbox-staging/dosbox-staging#1657]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### What Operating System are you using?

Windows 7

### Whats your question and how can we help?

Is there a way to reboot the guest DOSBox Staging instance with config and change a parameter, such as a different soundfont?

I tried "config -r soundfont=mysoundfont.sf2" but it doesn't seem to make a difference to the soundfont being used.

As a test (in case it was the soundfont parameter), I also tried "config -r fullscreen=false" (my loaded conf has it as true) but this kept the instance as fullscreen regardless (even though "config -get sdl fullscreen" shows "false" now). Same lack of result trying "config -r glshader=scan3x" (i.e. no visible change to the filter, but -get shows it is changed).

If this is a known issue that can't be solved, I'm happy to just set the parameter and use -wc to set the loaded conf file if that's the only way, but if I have to do that, how do I get it to save just the modified parameters (and not all of them and all the remarks) to my conf? In DOSBox-X, I use -norem and -mod but those don't seem to be recognised by Staging.

Failing that, is a way to just strip the remarks from a conf in Staging?

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by Wengier** [comment]
@Banjo-Oz With the current code as is in PR #1633 you can indeed reboot the guest DOSBox Staging instance with CONFIG command like this:

``config -r --set soundfont=mysoundfont.sf2``

Note the two dashes are used in the case of ``--set`` for it to work. If you use one dash (as in ``-set``), then it will be treated as a command-line option to CONFIG command itself, which will not the way that it is intended.

Meanwhile, I don't think options like -norem and -mod are currently supported by CONFIG command (as in DOSBox-X), but I think they can certainly be added for user convenience.

**Comment by Banjo-Oz** [comment]
@Wengier Thanks! Like an idiot, I spent the last half hour trying to get it to work only to then realise it wasn't actually in the existing current build but the source code to be added next version, right (i.e. I'd have to build it myself if I wanted it now)? Cool that it will be possible, though.

That said, having -mod and -norem would mean I wouldn't need to use config -r at all, I think, because it could then be done as I do it in DOSBox-X through modifying the conf file itself within DOSBox. If those options could be added, that would be very cool.

**Comment by Wengier** [comment]
@Banjo-Oz Yes, it is true that the current release builds do not have this functionality yet. However, there are automated CI builds for the PR code, which you can use directly if you do not want to compile the source code yourself. For example, if you use Windows, you can use the automated Windows MinGW build below:

https://github.com/dosbox-staging/dosbox-staging/suites/6351804248/artifacts/229124853

As for options -norem and -mod, they can certainly be considered too as mentioned above (in addition to the -r option which may still be useful in some cases of course).

**Comment by kcgen** [comment]
Closing; thanks for answering this, @Wengier!
