### ISSUE TITLE
Can I not show the debug console (besides using commandline parameters)?

### ISSUE THREAD

**Issue by Banjo-Oz** [dosbox-staging/dosbox-staging#1659]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Whats your question and how can we help?

I know you can do it with a command line parameter, but is there any other way to not show the second "debug" console window whenever DOSBox Staging opens?

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by kcgen** [comment]
You skipped answering which operating system and which version of Staging you're using; so now I have to type all this and tell you that these are relevant details and especially relevant to answer this. 

Thanks.

**Comment by Wengier** [comment]
@Banjo-Oz I agree it is better to provide some more details (at least) for this question as @kcgen mentioned above. Thanks for your support.

**Comment by Banjo-Oz** [comment]
Sorry, the form used here makes it easy to miss those dropdowns when asking a question.

Windows 7 and the latest version (0.78.1, I think?).

**Comment by kcgen** [comment]
Thanks @Banjo-Oz.
@kklobe recently got the debugger window working in the latest `main` releases, which is a second SDL window in addition to the console text logging window -- so I wasn't sure if it was the debugger you were mentioning. 

I now realize it's the usual console log window that you'd like to suppress/hide. 

Indeed, normally it's via command line. I'm not sure if there's a way to do it via environment variables (maybe?).  

We don't have a conf settings to hide it. Anyone have other ideas? 

If not, sounds like a conf settings would be good addition.

**Comment by Banjo-Oz** [comment]
Yup, the usual console window. :)

A conf setting would be great. It's a pain to have to make a shortcut just to hide it rather than just run the exe file when I'm testing stuff.

**Comment by shermp** [comment]
> Indeed, normally it's suppressed via command line (on Windows); but I'm not sure if there's a way to do it via environment variables (maybe?).

Actually, on the debugger version, `-noconsole` does not work, because the old debugger system relied on the original console.

With the new SDL debugger window, keeping the console window is no longer required, but the code preventing it from working is still in intact.

And all this stuff is done *before* the config file is read...

**Comment by Burrito78** [comment]
If someone else wants this, it can be looked at again.
