### ISSUE TITLE
DOS command help messages

### ISSUE THREAD

**Issue by Kappa971** [dosbox-staging/dosbox-staging#1660]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Different version than latest?

0.79.0-alpha-430-g67866082

### What Operating System are you using?

Windows 11

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Hi, I think I have noticed some inconsistencies with the help messages of DOS commands.
All DOS and DOSBox commands recognize `[command] /?` displaying the help message correctly.
On the other hand `help [command]` is inconsistent in some DOS commands, I give an example: 
`cls /?` displays the help message correctly
![Immagine 2022-05-10 151519](https://user-images.githubusercontent.com/62349018/167637147-9c3ca904-4aea-47e7-8074-1bf5ae2bb5bf.png)
but `help cls` doesn't
![Immagine 2022-05-10 151600](https://user-images.githubusercontent.com/62349018/167637176-4e5b974e-8a05-4564-9a75-f71d241d76c4.png)
Other commands display the same thing in both (for example `dir /?` and `help dir`). I guess it should be the correct behavior.
Others don't recognize `help [command]`.

Some proprietary DOSBox commands also recognize `[command] -help` (mount, autotype), others `[command] -h` (rescan, imgmount) or both (mount).
To avoid confusion, you could remove `[command] -help` and `[command] -h` (I think they aren't used in DOS), and make consistent `[command] /?` and `help [command]`.

I also discovered a bug with the command `boot` .  If you type `boot /?`, The `boot` help message will not be displayed but instead the `autotype` one.

It shouldn't matter, but I used the italian translation file not merged yet to the main branch.

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Run DOSBox Staging
2. Play around with "[command] /?", "help [command]", "[command] -help", "[command] -h"

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by shermp** [comment]
I can confirm the `boot /?` help message being the autotype one. I haven't yet found out *why* it's happening though.

**Comment by shermp** [comment]
Ok, git bisected to my `ProgramStart` refactor, now to try and figure out why.

**Comment by shermp** [comment]
Oh for ____ sake, how did we miss this!!!!????

```cpp
        PROGRAMS_MakeFile("AUTOTYPE.COM", ProgramCreate<AUTOTYPE>);
#if C_DEBUG
	PROGRAMS_MakeFile("BIOSTEST.COM", ProgramCreate<AUTOTYPE>);
#endif
	PROGRAMS_MakeFile("BOOT.COM", ProgramCreate<AUTOTYPE>);
```

Sorry @Kappa971 this was a brainfart of epic proportions.

**Comment by shermp** [comment]
So, taking a look at the `help` command, seems it's designed to work with the in-build shell commands, not the "external" programs (such as `MOUNT`, `BOOT` etc). Question, do we want to extend it to work with those as well?

Regardless, I can see that some of the commands are indeed missing the long help option.

**Comment by Kappa971** [comment]
> So, taking a look at the `help` command, seems it's designed to work with the in-build shell commands, not the "external" programs (such as `MOUNT`, `BOOT` etc). Question, do we want to extend it to work with those as well?

Those commands aren't even listed in `help /all`.

> Regardless, I can see that some of the commands are indeed missing the long help option.

Yes, with `help [command]`.
Also there are inconsistencies with `[command] -h` and `[command] -help` (which only work with proprietary DOSBox commands).

**Comment by johnnovak** [comment]
> So, taking a look at the `help` command, seems it's designed to work with the in-build shell commands, not the "external" programs (such as `MOUNT`, `BOOT` etc). Question, do we want to extend it to work with those as well?

I would say yes.

As I mentioned in my [other ticket](https://github.com/dosbox-staging/dosbox-staging/issues/1685#issuecomment-1128418316=), as a user, I just want to see a complete list of commands I can use; how they're implemented, that's not interesting to me.

**Comment by kcgen** [comment]
All in agreement here too, help should give help - especially with the high value commands, like you've flagged @johnnovak .
