### ISSUE TITLE
How do I delete non-empty directories and subdirectories?

### ISSUE THREAD

**Issue by Banjo-Oz** [dosbox-staging/dosbox-staging#1661]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### What Operating System are you using?

Windows 7

### Whats your question and how can we help?

I've been going nuts trying to figure out why a batch file installer wasn't working and realised it was because "rmdir" in DOSBox Staging doesn't recognise the /s or /q switches.

Presumably, this is because pre-Windows (2000, I think?) versions or rmdir didn't recognise the switches either right?

Is the only way around this to edit the installer to use deltree (after adding that manually from FreeDOS or old DOS, since it's not included with DOSBox Staging)? What other solutions could I try with minimal use of 3rd party programs or file editing?

Alternately, could deltree be added to DOSBox Staging to resolve this issue (and maintain rmdir's classic DOS limitations)?

If I do have to use an external solution, is https://www.ibiblio.org/pub/micro/pc-stuff/freedos/files/distributions/1.2/repos/pkg-html/deltree.html considered the "best" one to use with DOSBox Staging?

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by Wengier** [comment]
I do not think RD command from MS-DOS actually supports options like /S or /Q (although they may be considered for compatibility with certain scripts). Instead, DELTREE command is expected for standard DOS batch scripts etc. I think commands like DELTREE can be natively bundled indeed, but in the meantime you can always add such commands to Z drive by yourself, with the existing Z drive customization function (same as in DOSBox-X). Hope this helps.

**Comment by Banjo-Oz** [comment]
@Wengier You're right, it doesn't. It was only Windows (2000 or XP?) that added those switches. I remember using deltree for later DOS versions for that job. I didn't know Staging allowed a custom Z drive (it's one of my favourite features from DOSBox-X)!

For now, I have a the above linked Freedos version of deltree in my path that I am using, which does the job in this specific  situation. For my main DOSBox install (which uses DOSBox-X) I have alternatives in Z drive already. :)

**Comment by kcgen** [comment]
Glad you have a solution, @Banjo-Oz .

`DELTREE` is listed in the executable we'd like to bundle as tools: https://github.com/dosbox-staging/dosbox-staging/issues/1504

Closing this; if there's still problems - we can reopen!
