### ISSUE TITLE
Is there any LFN support in Staging?

### ISSUE THREAD

**Issue by Banjo-Oz** [dosbox-staging/dosbox-staging#1663]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### What Operating System are you using?

Windows 7

### Whats your question and how can we help?

I'm trying to mount, rename, and unmount a folder that uses Windows naming, so it changes files to DOS style short names. Usually that's fine, but in this case I need to keep the original filename. Is there any way to use LFN with DOSBox Staging? I know it works great under DOSBox-X (either manual conf setting or auto with DOS ver reported as 7+) but Staging doesn't seem to have that feature. I am happy with any workaround as this is a singular case and not something I need to do with Staging a lot. I also understand if it simply isn't possible in Staging to do what I want, and will happily look for an alternate solution if so.

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by kcgen** [comment]
(previously asked)
 - https://github.com/dosbox-staging/dosbox-staging/issues/1238
 - https://github.com/dosbox-staging/dosbox-staging/issues/1607

Status the is same as mention: we do hope to add it, eventually!

**Comment by Banjo-Oz** [comment]
Thanks. I use DOSBox-X 90% of the time but am in a situation where I "have" to use Staging, hence why I was trying to solve it with this fork. It is far from something essential in what I am doing and I can code my way around it in batch files, so no probs. LFN support eventually would definitely be useful (incidentally, I actually keep it turned off in DOSBox-X for a more "authentic" feel, and just enable it in rare cases I need it).
