### ISSUE TITLE
Mouse gets restricted now and then (more now than then..)

### ISSUE THREAD

**Issue by arjenv** [dosbox-staging/dosbox-staging#1667]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### What Operating System are you using?

Linux x86_64

### Whats your question and how can we help?

Running Fedora 35 and Dosbox staging 0.78.1

Probably after some updates from Fedora, the mouse cursor is restricted within a small area in the dosbox. Both within fullresolution as windowresolution. I changed fullresolution from 640x480 to 1280x960. I can now move to the corners, however, during gaming the cursor suddenly restricts to a sort of invisible wall. I then need to move the cursor a few times hence and forth to break through this invisible wall. In the mean time I lost valuable time and the game is over....
The phenomena seems random and only after a while in the game. 

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by kcgen** [comment]
Yes, the seamless mouse sometimes is inconsistent; try capturing the mouse on start with this conf setting:

```ini
capture_mouse = onstart middlerelease
```

Does that help?

**Comment by arjenv** [comment]
Alas, does not help. I tried other settings as well: onclick and nomouse (the latter is not an option of course :-)  )

**Comment by kcgen** [comment]
Wow.. that's surprising; it's the first time where `capture_mouse = onstart` hasn't worked to give perfect mouse control (captured within the SDL2 window).

Is there a specific program or game where this is happening, and you can share it and your conf file(s) to reproduce it? Or is it universally happening?

If it's the latter case, given other Linux users aren't affected, I would have to say the issue likely lies somewhere in the SDL2 - Wayland - Video driver space.  In which case, you could try updating SDL2, maybe build the latest from source, and try running Staging via X11 instead of Wayland.

**Comment by arjenv** [comment]
I am gaming a very old dos game: SHERLOCK (dos version)

I'm afraid that's the only game with a mouse I play in Dosbox.

I checked with 
echo $XDG_SESSION_TYPE
It said 'Wayland'

I am reluctant to change settings that work for me, this is my main computer and if I f.. uhh heck up changing to X11 I would be very sad indeed... I even might cry a bit...

conf file: 

# This is the configuration file for dosbox-staging (0.77.1).
# Lines starting with a '#' character are comments.

[sdl]
#       fullscreen: Start directly in fullscreen.
#                   Run INTRO and see Special Keys for window control hotkeys.
#          display: Number of display to use; values depend on OS and user settings.
#   fullresolution: What resolution to use for fullscreen: 'original', 'desktop'
#                   or a fixed size (e.g. 1024x768).
# windowresolution: Set window size when running in windowed mode:
#                     default:   Select the best option based on your
#                                environment and other settings.
#                     small, medium, or large (or s, m, l):
#                                Size the window relative to the desktop.
#                     <custom>:  Scale the window to the given dimensions in
#                                WxH format. For example: 1024x768.
#                                Scaling is not performed for output=surface.
#           output: What video system to use for output.
#                   Possible values: surface, texture, texturenb, texturepp, opengl, openglnb, openglpp.
# texture_renderer: Choose a renderer driver when using a texture output mode.
#                   Use texture_renderer=auto for an automatic choice.
#                   Possible values: auto, opengl, opengles2, software.
#    capture_mouse: Choose a mouse control method:
#                      onclick:        Capture the mouse when clicking inside the window.
#                      onstart:        Capture the mouse immediately on start.
#                      seamless:       Never cature the mouse; let it move seamlessly.
#                      nomouse:        Hide the mouse and don't send input to the game.
#                   Choose how middle-clicks are handled (second parameter):
#                      middlegame:     Middle-clicks are sent to the game.
#                      middlerelease:  Middle-click will release the captured mouse.
#                   Defaults (if not present or incorrect): seamless middlerelease
#                   Possible values: seamless, onclick, onstart, nomouse.
#      sensitivity: Mouse sensitivity. The optional second parameter specifies vertical sensitivity (e.g. 100,-50).
#  raw_mouse_input: Enable this setting to bypass your operating system's mouse
#                   acceleration and sensitivity settings. This works in
#                   fullscreen or when the mouse is captured in window mode.
#      waitonerror: Wait before closing the console if dosbox has an error.
#         priority: Priority levels for dosbox. Second entry behind the comma is for when dosbox is not focused/minimized.
#                   pause is only valid for the second entry. auto disables priority levels and uses OS defaults
#                   Possible values: auto, lowest, lower, normal, higher, highest, pause.
#       mapperfile: File used to load/save the key/event mappings from.
#                   Resetmapper only works with the default value.
#      screensaver: Use 'allow' or 'block' to override the SDL_VIDEO_ALLOW_SCREENSAVER
#                   environment variable (which usually blocks the OS screensaver
#                   while the emulator is running).
#                   Possible values: auto, allow, block.

fullscreen       = true
display          = 0
fullresolution   = 1280x960
windowresolution = 1280x960
#fullresolution   = 640x480
#windowresolution = 640x480
#output           = openglnb
output           = openglnb
texture_renderer = auto
capture_mouse    = onstart middlerelease
#capture_mouse    = seamless middlerelease
sensitivity      = 120
raw_mouse_input  = true
waitonerror      = true
priority         = auto,auto
mapperfile       = mapper-sdl2-0.77.1.map
screensaver      = auto

[dosbox]
#          language: Select another language file.
#           machine: The type of machine DOSBox tries to emulate.
#                    Possible values: hercules, cga, cga_mono, tandy, pcjr, ega, vgaonly, svga_s3, svga_et3000, svga_et4000, svga_paradise, vesa_nolfb, vesa_oldvbe.
#          captures: Directory where things like wave, midi, screenshot get captured.
#           memsize: Amount of memory DOSBox has in megabytes.
#                    This value is best left at its default to avoid problems with some games,
#                    though few games might require a higher value.
#                    There is generally no speed advantage when raising this value.
# startup_verbosity: Controls verbosity prior to displaying the program:
#                    Verbosity   | Splash | Welcome | Early stdout
#                    high        |  yes   |   yes   |    yes
#                    medium      |  no    |   yes   |    yes
#                    low         |  no    |   no    |    yes
#                    quiet       |  no    |   no    |    no
#                    splash_only |  yes   |   no    |    no
#                    auto        | 'low' if exec or dir is passed, otherwise 'high'
#                    Possible values: high, medium, low, splash_only, quiet, auto.

language          = 
machine           = svga_s3
captures          = capture
memsize           = 16
startup_verbosity = high

[render]
#          frameskip: How many frames DOSBox skips before drawing one.
#             aspect: Scales the vertical resolution to produce a 4:3 display aspect
#                     ratio, matching that of the original standard-definition monitors
#                     for which the majority of DOS games were designed. This setting
#                     only affects video modes that use non-square pixels, such as
#                     320x200 or 640x400; where as square-pixel modes, such as 640x480
#                     and 800x600, will be displayed as-is.
# monochrome_palette: Select default palette for monochrome display.
#                     Works only when emulating hercules or cga_mono.
#                     You can also cycle through available colours using F11.
#                     Possible values: white, paperwhite, green, amber.
#             scaler: Scaler used to enlarge/enhance low resolution modes.
#                     If 'forced' is appended, then the scaler will be used even if
#                     the result might not be desired.
#                     Note that some scalers may use black borders to fit the image
#                     within your configured display resolution. If this is
#                     undesirable, try either a different scaler or enabling
#                     fullresolution output.
#                     Possible values: none, normal2x, normal3x, advmame2x, advmame3x, advinterp2x, advinterp3x, hq2x, hq3x, 2xsai, super2xsai, supereagle, tv2x, tv3x, rgb2x, rgb3x, scan2x, scan3x.
#           glshader: Either 'none' or a GLSL shader name. Works only with
#                     OpenGL output.  Can be either an absolute path, a file
#                     in the 'glshaders' subdirectory of the DOSBox
#                     configuration directory, or one of the built-in shaders:
#                     advinterp2x, advinterp3x, advmame2x, advmame3x,
#                     crt-easymode-flat, crt-fakelottes-flat, rgb2x, rgb3x,
#                     scan2x, scan3x, tv2x, tv3x, sharp (default).

frameskip          = 0
aspect             = false
monochrome_palette = white
scaler             = none
glshader           = default

[cpu]
#      core: CPU Core used in emulation. auto will switch to dynamic if available and
#            appropriate.
#            Possible values: auto, dynamic, normal, simple.
#   cputype: CPU Type used in emulation. auto is the fastest choice.
#            Possible values: auto, 386, 386_slow, 486_slow, pentium_slow, 386_prefetch.
#    cycles: Number of instructions DOSBox tries to emulate each millisecond.
#            Setting this value too high results in sound dropouts and lags.
#            Cycles can be set in 3 ways:
#              'auto'          tries to guess what a game needs.
#                              It usually works, but can fail for certain games.
#              'fixed #number' will set a fixed number of cycles. This is what you usually
#                              need if 'auto' fails (Example: fixed 4000).
#              'max'           will allocate as much cycles as your computer is able to
#                              handle.
#            Possible values: auto, fixed, max.
#   cycleup: Number of cycles added or subtracted with speed control hotkeys.
#            Run INTRO and see Special Keys for list of hotkeys.
# cycledown: Setting it lower than 100 will be a percentage.

core      = auto
cputype   = auto
cycles    = auto
cycleup   = 10
cycledown = 20

[mixer]
#   nosound: Enable silent mode, sound is still emulated though.
#      rate: Mixer sample rate, setting any device's rate higher than this will probably lower their sound quality.
#            Possible values: 44100, 48000, 32000, 22050, 16000, 11025, 8000, 49716.
# blocksize: Mixer block size, larger blocks might help sound stuttering but sound will also be more lagged.
#            Possible values: 1024, 2048, 4096, 8192, 512, 256.
# prebuffer: How many milliseconds of data to keep on top of the blocksize.

nosound   = false
rate      = 44100
blocksize = 1024
prebuffer = 25

[midi]
# mididevice: Device that will receive the MIDI data (from the emulated MIDI
#             interface - MPU-401). Choose one of the following:
#             'fluidsynth', to use the built-in MIDI synthesizer. See the
#                    [fluidsynth] section for detailed configuration.
#             'mt32', to use the built-in Roland MT-32 synthesizer.
#                    See the [mt32] section for detailed configuration.
#             'auto', to use the first working external MIDI player. This
#                    might be a software synthesizer or physical device.
#             Possible values: auto, oss, alsa, fluidsynth, mt32, none.
# midiconfig: Configuration options for the selected MIDI interface.
#             This is usually the id or name of the MIDI synthesizer you want
#             to use (find the id/name with DOS command 'mixer /listmidi').
#             - This option has no effect when using the built-in synthesizers
#               (mididevice = fluidsynth or mt32).
#             - When using ALSA, use Linux command 'aconnect -l' to list open
#               MIDI ports, and select one (for example 'midiconfig=14:0'
#               for sequencer client 14, port 0).
#             - If you're using a physical Roland MT-32 with revision 0 PCB,
#               the hardware may require a delay in order to prevent its
#               buffer from overflowing. In that case, add 'delaysysex',
#               for example: 'midiconfig=2 delaysysex'.
#             See the README/Manual for more details.
#     mpu401: Type of MPU-401 to emulate.
#             Possible values: intelligent, uart, none.

mididevice = auto
midiconfig = 
mpu401     = intelligent

[fluidsynth]
# soundfont: Path to a SoundFont file in .sf2 format. You can use an
#            absolute or relative path, or the name of an .sf2 inside
#            the 'soundfonts' directory within your DOSBox configuration
#            directory.
#            An optional percentage will scale the SoundFont's volume.
#            For example: 'soundfont.sf2 50' will attenuate it by 50 percent.
#            The scaling percentage can range from 1 to 500.

soundfont = default.sf2

[mt32]
#  model: Model of synthesizer to use.
#         'auto' picks the first model with available ROMs, in order as listed.
#         'cm32l' and 'mt32' pick the first model of their type, in the order listed.
#         'mt32_old' and 'mt32_new' are aliases for 1.07 and 2.04, respectively.
#         Possible values: auto, cm32l, cm32l_102, cm32l_100, mt32, mt32_old, mt32_107, mt32_106, mt32_105, mt32_104, mt32_bluer, mt32_new, mt32_204.
# romdir: The directory containing ROMs for one or more models.
#         The directory can be absolute or relative, or leave it blank to
#         use the 'mt32-roms' directory in your DOSBox configuration
#         directory. Other common system locations will be checked as well.
#         ROM files inside this directory may include any of the following:
#           - MT32_CONTROL.ROM and MT32_PCM.ROM, for the 'mt32' model.
#           - CM32L_CONTROL.ROM and CM32L_PCM.ROM, for the 'cm32l' model.
#           - Unzipped MAME MT-32 and CM-32L ROMs, for the versioned models.
#         

model  = auto
romdir = 

[sblaster]
#  sbtype: Type of Sound Blaster to emulate. 'gb' is Game Blaster.
#          Possible values: sb1, sb2, sbpro1, sbpro2, sb16, gb, none.
#  sbbase: The IO address of the Sound Blaster.
#          Possible values: 220, 240, 260, 280, 2a0, 2c0, 2e0, 300.
#     irq: The IRQ number of the Sound Blaster.
#          Possible values: 7, 5, 3, 9, 10, 11, 12.
#     dma: The DMA number of the Sound Blaster.
#          Possible values: 1, 5, 0, 3, 6, 7.
#    hdma: The High DMA number of the Sound Blaster.
#          Possible values: 1, 5, 0, 3, 6, 7.
# sbmixer: Allow the Sound Blaster mixer to modify the DOSBox mixer.
# oplmode: Type of OPL emulation. On 'auto' the mode is determined by 'sbtype'.
#          All OPL modes are AdLib-compatible, except for 'cms'.
#          Possible values: auto, cms, opl2, dualopl2, opl3, opl3gold, none.
#  oplemu: Provider for the OPL emulation. 'compat' provides better quality,
#          'nuked' is the default and most accurate (but the most CPU-intensive).
#          Possible values: default, compat, fast, mame, nuked.

sbtype  = sb16
sbbase  = 220
irq     = 7
dma     = 1
hdma    = 5
sbmixer = true
oplmode = auto
oplemu  = default

[gus]
#      gus: Enable Gravis UltraSound emulation.
#  gusbase: The IO base address of the Gravis UltraSound.
#           Possible values: 240, 220, 260, 280, 2a0, 2c0, 2e0, 300.
#   gusirq: The IRQ number of the Gravis UltraSound.
#           Possible values: 5, 3, 7, 9, 10, 11, 12.
#   gusdma: The DMA channel of the Gravis UltraSound.
#           Possible values: 3, 0, 1, 5, 6, 7.
# ultradir: Path to UltraSound directory. In this directory
#           there should be a MIDI directory that contains
#           the patch files for GUS playback. Patch sets used
#           with Timidity should work fine.

gus      = false
gusbase  = 240
gusirq   = 5
gusdma   = 3
ultradir = C:\ULTRASND

[innovation]
#   sidmodel: Model of chip to emulate in the Innovation SSI-2001 card:
#              - auto:  Selects the 6581 chip.
#              - 6581:  The original chip, known for its bassy and rich character.
#              - 8580:  A later revision that more closely matched the SID specification.
#                       It fixed the 6581's DC bias and is less prone to distortion.
#                       The 8580 is an option on reproduction cards, like the DuoSID.
#              - none:  Disables the card.
#             Possible values: auto, 6581, 8580, none.
#   sidclock: The SID chip's clock frequency, which is jumperable on reproduction cards.
#              - default: uses 0.895 MHz, per the original SSI-2001 card.
#              - c64ntsc: uses 1.023 MHz, per NTSC Commodore PCs and the DuoSID.
#              - c64pal:  uses 0.985 MHz, per PAL Commodore PCs and the DuoSID.
#              - hardsid: uses 1.000 MHz, available on the DuoSID.
#             Possible values: default, c64ntsc, c64pal, hardsid.
#    sidport: The IO port address of the Innovation SSI-2001.
#             Possible values: 240, 260, 280, 2a0, 2c0.
# 6581filter: The SID's analog filtering meant that each chip was physically unique.
#             Adjusts the 6581's filtering strength as a percent from 0 to 100.
# 8580filter: Adjusts the 8580's filtering strength as a percent from 0 to 100.

sidmodel   = none
sidclock   = default
sidport    = 280
6581filter = 50
8580filter = 50

[speaker]
#   pcspeaker: Enable PC-Speaker emulation.
#      pcrate: Sample rate of the PC-Speaker sound generation.
# zero_offset: Neutralizes and prevents the PC speaker's DC-offset from harming other sources.
#              'auto' enables this for non-Windows systems and disables it on Windows.
#              If your OS performs its own DC-offset correction, then set this to 'false'.
#              Possible values: auto, true, false.
#       tandy: Enable Tandy Sound System emulation. For 'auto', emulation is present only if machine is set to 'tandy'.
#              Possible values: auto, on, off.
#   tandyrate: Sample rate of the Tandy 3-Voice generation.
#              Possible values: 44100, 48000, 32000, 22050, 16000, 11025, 8000, 49716.
#      disney: Enable Disney Sound Source emulation. (Covox Voice Master and Speech Thing compatible).
#    ps1audio: Enable IBM PS/1 Audio emulation.

pcspeaker   = true
pcrate      = 18939
zero_offset = auto
tandy       = auto
tandyrate   = 44100
disney      = true
ps1audio    = false

[joystick]
#  joysticktype: Type of joystick to emulate: auto (default),
#                none (disables joystick emulation),
#                2axis (supports two joysticks),
#                4axis (supports one joystick, first joystick used),
#                4axis_2 (supports one joystick, second joystick used),
#                fcs (Thrustmaster), ch (CH Flightstick).
#                auto chooses emulation depending on real joystick(s).
#                (Remember to reset DOSBox's mapperfile if you saved it earlier)
#                Possible values: auto, 2axis, 4axis, 4axis_2, fcs, ch, none.
#         timed: enable timed intervals for axis. Experiment with this option, if your joystick drifts (away).
#      autofire: continuously fires as long as you keep the button pressed.
#        swap34: swap the 3rd and the 4th axis. Can be useful for certain joysticks.
#    buttonwrap: enable button wrapping at the number of emulated buttons.
# circularinput: enable translation of circular input to square output.
#                Try enabling this if your left analog stick can only move in a circle.
#      deadzone: the percentage of motion to ignore. 100 turns the stick into a digital one.

joysticktype  = auto
timed         = true
autofire      = false
swap34        = false
buttonwrap    = false
circularinput = false
deadzone      = 10

[serial]
#       serial1: set type of device connected to com port.
#                Can be disabled, dummy, modem, nullmodem, directserial.
#                Additional parameters must be in the same line in the form of
#                parameter:value. Parameter for all types is irq (optional).
#                for directserial: realport (required), rxdelay (optional).
#                                 (realport:COM1 realport:ttyS0).
#                for modem: listenport (optional).
#                for nullmodem: server, rxdelay, txdelay, telnet, usedtr,
#                               transparent, port, inhsocket (all optional).
#                Example: serial1=modem listenport:5000
#                Possible values: dummy, disabled, modem, nullmodem, directserial.
#       serial2: see serial1
#                Possible values: dummy, disabled, modem, nullmodem, directserial.
#       serial3: see serial1
#                Possible values: dummy, disabled, modem, nullmodem, directserial.
#       serial4: see serial1
#                Possible values: dummy, disabled, modem, nullmodem, directserial.
# phonebookfile: File used to map fake phone numbers to addresses.

serial1       = dummy
serial2       = dummy
serial3       = disabled
serial4       = disabled
phonebookfile = phonebook.txt

[dos]
#            xms: Enable XMS support.
#            ems: Enable EMS support. The default (=true) provides the best
#                 compatibility but certain applications may run better with
#                 other choices, or require EMS support to be disabled (=false)
#                 to work at all.
#                 Possible values: true, emsboard, emm386, false.
#            umb: Enable UMB support.
#            ver: Set DOS version (5.0 by default). Specify as major.minor format.
#                 A single number is treated as the major version.
#                 Common settings are 3.3, 5.0, 6.22, and 7.1.
# keyboardlayout: Language code of the keyboard layout (or none).

xms            = true
ems            = true
umb            = true
ver            = 5.0
keyboardlayout = auto

[ipx]
# ipx: Enable ipx over UDP/IP emulation.

ipx = false

[autoexec]
# Lines in this section will be run at startup.
# You can put your MOUNT lines here.

mount c /media/data/Downloads/Cdownloads
c:
cd sherlock
sherlock.exe

**Comment by kcgen** [comment]
Try these two changes in your conf:

```ini
fullscreen = true
fullresolution   = desktop
output           = texturepp
```

**Comment by arjenv** [comment]
Thank you for all your input (and a great piece of software! I am using it probably from the start)

These options work as well with the exception of fullresolution =  desktop. The graphics then expand in the vertical and gets less sharp. 

You could close this question for now. The 'raw_mouse_input = true' option holds for the last 10 games I played. If I find further issues I will surely contact again. Thanks..

**Comment by kcgen** [comment]
Thanks @arjenv  (and glad you're having fun with some old DOS games!)
