### ISSUE TITLE
Add Adlib Gold Surround (YM7128) DSP emulation

### ISSUE THREAD

**Issue by kcgen** [dosbox-staging/dosbox-staging#1672]
From @johnnovak:

 I've been looking into this earlier, and it turns out that the [AdLib Gold emulation](https://github.com/sarah-walker-pcem/pcem/blob/dev/src/sound/sound_adlibgold.c) in PCem includes the emulation of the [YM2128 surrond processor](https://github.com/sarah-walker-pcem/pcem/blob/dev/src/sound/sound_ym7128.c) as well which was the DSP used on the surround add-on module.

There's another library that aims to emulate YM7128, and just by looking at the code it seems to be a better effort then what's in PCem (at least it's much better documented, and it provides different engines: integer, float, "ideal", etc.)

https://github.com/TexZK/YM7128B_emu

If we spend effort doing this, I think my preference would be to use the YM7128 library for accuracy. Those old DSP effect processors used some funky integer-only maths which resulted in lots of weird noise and precision errors that gave those units their characteristic sound (e.g. old Lexicon studio reverbs). I'm assuming it's about the same level of effort anyway, or maybe even less, because we won't need to try to match and tune the reverb and chorus settings.

Here's the full AdLib Gold Dune soundtrack for reference.

https://www.youtube.com/watch?v=gUfGyfbzl9k

_Originally posted by @johnnovak in https://github.com/dosbox-staging/dosbox-staging/issues/1662#issuecomment-1127103836_

**Comment by johnnovak** [comment]
Btw, we couldn't even simulate it with just a reverb and a chorus, as it implements 8 freely programmable delay lines that allow you to create not just reverb and chorus but all sorts of other effects too.

It's a stereo processor, so I assume the whole OPL output is just sent through it as an aux send where you can only control the send level.

From the [chip's manual](https://github.com/TexZK/YM7128B_emu/blob/master/doc/YM7128-ETC.pdf
):

<img width="1126" alt="image" src="https://user-images.githubusercontent.com/698770/168516463-2f7e672d-5b79-4f00-97dc-2fe49eae9868.png">

**Comment by kcgen** [comment]
> It's a stereo processor, so I assume the whole OPL output is just sent through it

Very interesting! This feature will be a nice candidate to use the same pattern and design that comes out of your filter PRs.

PS.. that Dune adlib gold soundtrack with the surround module is other worldly!

**Comment by johnnovak** [comment]
Couldn't help it, I've started working on this! This ticket was calling for me in the night 😁

**Comment by johnnovak** [comment]
> Please pass my utmost regards to the sweet night creature that keeps calling you to these tickets! ⚡

I have! He says "hi"!

![image](https://user-images.githubusercontent.com/698770/172275513-a6b641a1-bd9e-4b6a-81bd-7db9b9bc3feb.png)

**Comment by kcgen** [comment]
:joy:

**Comment by stephanepicqdune** [comment]
Hello Everybody! You like it? 
The remaster of the album "Dune Spice Opera"  in Hi-res Audio (96khz/24bits)
will feature special bonus tracks of the OST (mix Adlib-Gold+ Roland MT32).
Release in january 2024! Just type my name + "Dune Spice Opera" in any search! 😏
Stéphane Picq

**Comment by johnnovak** [comment]
Hi @stephanepicqdune! I'm a big fan of your music, so I'll definitely check it out 😄 Thanks for stopping by to comment ❤️

**Comment by MasterO2** [comment]
**He who controls the spice controls the Universe!**

**Comment by johnnovak** [comment]
> **He who controls the spice controls the Universe!**

He who ~~controls the spice~~ masters the AdLib Gold controls the Universe.

☝🏻 Fixed it for ya, @MasterO2 😎 🤘🏻

**Comment by stephanepicqdune** [comment]
Hello!

You are welcome!

https://m.facebook.com/profile.php/?id=100005053622211&name=STSDirectNavUserDecorator 

https://m.facebook.com/groups/276481461988631/ 

https://stphanepicq.bandcamp.com/ 

https://m.soundcloud.com/st-phane-picq/ecolove 

https://twitter.com/DuneSpiceOpera


     Le lundi 15 janvier 2024 à 04:48:52 UTC+3, John Novak ***@***.***> a écrit :  
 
 


Hi @stephanepicqdune! I'm a big fan of your music, so I'll definitely check it out 😄 Thanks for stopping by to comment ❤️
