### ISSUE TITLE
Add crossfeed support for headphone listening

### ISSUE THREAD

**Issue by johnnovak** [dosbox-staging/dosbox-staging#1678]
Related to https://github.com/dosbox-staging/dosbox-staging/issues/1662

Add support for crossfeed between the left and right audio channels for headphone listening.

There are two ways to set the crossfeed:

**1. Easy mode**

Crossfeed can be enabled globally in the mixer; this is what most users should use. Once it's enabled, it is applied to all stereo channels:

```
[mixer]
crossfeed = 50      
```

Valid values are:

- `off` (default, same as setting it to 0)
- `on` (set crossfeed to 30)
-  an integer from 0 to 100, where 0 means no crossfeed (same as `off`), and 100 means 100% crossfeed, which effectively converts stereo signals to mono

**2. Advanced mode**

Advanced users can fine-tune the crossfeed strength per channel using mixer commands. Crossfeed strength commands are prefixed with `x`:

```
mixer sb x50
mixer cdaudio x0
```

Crossfeed can be set globally as well for all stereo channels:

```
mixer x30
```

The crossfeed strength per channel is displayed in the mixer (`Xfeed`):

```
Channel      Volume    Volume(db)  Rate(Hz)   Mode    Xfeed  Reverb  Chorus
MASTER      100:100   +0.00:+0.00     48000   Stereo      -       -       -
CDAUDIO     100:100   +0.00:+0.00     10000   Stereo    off       -       -
DISNEY      100:100   +0.00:+0.00     10000   Mono        -      42      75
FM          100:100   +0.00:+0.00     48000   Stereo     60      42      75
INNOVATION  100:100   +0.00:+0.00     48000   Mono        -      42      75
MT32        100:100   +0.00:+0.00     48000   Stereo    off       -       -
SB          100:100   +0.00:+0.00     22050   Stereo     20       8     off
SPKR        100:100   +0.00:+0.00     18939   Mono        -      42      75
```

---

Technically, crossfeed is implemented as treating the left and right channels as two separate mono channels, and applying the -6dB linear pan law to them (gradually panning between 100% left/right and center). That keeps the amplitude constant regardless of the crossfeed strength, and thus leaves the volume of mono content unaltered.

**Comment by Burrito78** [comment]
According to my understanding and Wikipedia, headphone users would probably want crossfeed also for MT-32, Fluidsynth and CD-Audio if possible as these also feature sometimes extreme panning and some users prefer a little crossfeed for all sources when using headphones (some headphone amplifiers even have crossfeed build in for this purpose).

> Crossfeed is the process of blending the left and right channels of a stereo audio recording. It is generally used to reduce the extreme channel separation often featured in early stereo recordings (e.g., where instruments are panned entirely on one side or the other), or to make audio played through headphones sound more natural, as when listening to a pair of external speakers.

**Comment by johnnovak** [comment]
> According to my understanding and Wikipedia, headphone users would probably want crossfeed also for MT-32, Fluidsynth and CD-Audio if possible as these also feature sometimes extreme panning and some users prefer a little crossfeed for all sources when using headphones (some headphone amplifiers even have crossfeed build in for this purpose).

Probably that's the best, yes. I've updated the feature description so it will work similarly to reverb and chorus (apply the same settings to all channels in easy mode, which can be overriden with mixer commands).
