### ISSUE TITLE
Support sampled audio playback via OPL/Adlib 

### ISSUE THREAD

**Issue by kcgen** [dosbox-staging/dosbox-staging#1683]
Some discussion here:
https://www.vogons.org/viewtopic.php?p=1040302#p1040302

And from @joncampbell123:

> You may also be interested in sub-millisecond Adlib rendering as well. Some DOS games support a hack to play digitized speech through the Adlib OPL2/OPL3 FM chip and you have to render up to current time on OPL write to play that back correctly as well. "Links golf challenge" and "Pinball dreams" support that kind of hackery, for example.

**Comment by johnnovak** [comment]
I've just tried Pinball Dreams with the AdLib driver and sampled playback works fine. So it seems like it's already supported? The volume is quite low, though, but maybe that's normal.

**Comment by kcgen** [comment]
If you add these couple lines:

``` c++
	if (PIC_Ticks == lastUsed)
		LOG_MSG("Adlib: additional sub-ms write at tick %.3f to port %03xh with val 0x%02x", PIC_FullIndex(), port, value);
```

As the first thing that happens in Adlib's Module::PortWrite function (adlib.cpp:601), then try Rescue Rover 2: [RescueR2.zip](https://github.com/dosbox-staging/dosbox-staging/files/8834117/RescueR2.zip)

It will reports when the Adlib is written to more than once during the same 1ms tick:

``` text
2022-06-03 09:19:36.529 | Adlib: additional sub-ms write at tick 14902.446 to port 389h with val 0x02
2022-06-03 09:19:36.529 | Adlib: additional sub-ms write at tick 14902.492 to port 388h with val 0xb0
2022-06-03 09:19:36.529 | Adlib: additional sub-ms write at tick 14902.513 to port 389h with val 0x34
2022-06-03 09:19:36.529 | Adlib: additional sub-ms write at tick 14902.562 to port 388h with val 0xb0
2022-06-03 09:19:36.529 | Adlib: additional sub-ms write at tick 14902.582 to port 389h with val 0x00
```

Those writes are all being fed into the OPL emulation code and changing the OPL register bits. 

However, in Adlib, we're only extracting audio stream from the OPL code every 1ms - asking for the full 1ms worth of frames.

The trouble is, the only way the OPL code can "effect change" on the waveform is through state of its registers.

So we really want to extra audio for the tiny chunks of time after every write - so the effect of the prior write has a chance to influence the waveform before being clobbered by this next write.

But the strange thing is, I'm having a really hard time hearing the impact of not getting the waveform for these sub-ms chunks (regardless of what game I try, mentioned above). 

I wonder if there are other more obvious examples?

**Comment by joncampbell123** [comment]
Pinball dreams. They're using a music tracker that can do PC speaker, LPT DAC, Adlib, Sound Blaster...

I think it goes at about 4-6KHz.

**Comment by johnnovak** [comment]
> Pinball dreams. They're using a music tracker that can do PC speaker, LPT DAC, Adlib, Sound Blaster...
> 
> I think it goes at about 4-6KHz.

I think it makes sense then that I works now with only 1ms updates, albeit at much lower sample rate & quality.

**Comment by joncampbell123** [comment]
DOSBox-X makes it possible by calling module->mixerChan->FillUp() on every write to port 389h, just before passing the write to the OPL emulation code.

That FillUp() call forces audio rendition up to (but not including) the change of audio in the chip.

**Comment by kcgen** [comment]
> There's no need for a complicated queue of events like the way DOSBox SVN does PC speaker emulation

Indeed, I'm chipping away at getting ripa's sinc-waveform patch in, and one of the refactoring aspects I'm doing is removing the DelayEvent queue in favour of generating the impulse at the time of the PIT call - which removes one of the queues in the code (more in an effort to simplify the code and make it a bit easier to follow).

We've got a couple of the older cards covered now, and Adlib will be next  :+1:  

Thanks for the help and pointers, @joncampbell123!

**Comment by kcgen** [comment]
We now deliver OPL-generated samples to the mixer on a per-sample basis.
(closing).
