### ISSUE TITLE
English strings, new color tags

### ISSUE THREAD

**Issue by Kappa971** [dosbox-staging/dosbox-staging#1698]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Different version than latest?

0.79.0-alpha

### What Operating System are you using?

Windows 11

### Whats your question and how can we help?

Hi, using the DOSBox command `config -wl [filename]` with `language = en`, a file containing the English text strings will be printed but it will be incomplete (some strings are absent such as what concerns `mixer /?`): [eng.txt](https://github.com/dosbox-staging/dosbox-staging/files/8793760/eng.txt).
Also the strings use new color tags other than what is found in the utf-8 translation files, which makes it difficult to copy the new strings from the English file to another language.
Examples:
English
```
:SHELL_CMD_TIME_HELP_LONG
Usage:
  [color=green]time[reset] [/t]
  [color=green]time[reset] /h
  [color=green]time[reset] [color=cyan]TIME[reset]

Where:
  [color=cyan]TIME[reset] is the new time to set to, in the format of [color=cyan]%s[reset].

Notes:
  Running [color=green]time[reset] without an argument shows the current time, or a simple time
  with the /t option. You can force a time synchronization of with the host
  system with the /h option, or manually specify a new time to set to.

Examples:
  [color=green]time[reset]
  [color=green]time[reset] /h
  [color=green]time[reset] [color=cyan]%s[reset]

.
```
Italian
```
:SHELL_CMD_TIME_HELP_LONG
Utilizzo:
  [32;1mtime[0m [/t]
  [32;1mtime[0m /h
  [32;1mtime[0m [36;1mORA[0m

Dove:
  [36;1mORA[0m è il nuovo orario da impostare, nel formato [36;1m%s[0m.

Note:
  L'esecuzione di [32;1mtime[0m senza un argomento, mostra l'orario corrente e permette
  l'immissione di uno nuovo. Aggiungendo l'opzione /t, sarà mostrato solo
  l'orario corrente. È possibile forzare la sincronizzazione dell'orario con il
  sistema host tramite l'opzione /h.

Esempi:
  [32;1mtime[0m
  [32;1mtime[0m /h
  [32;1mtime[0m [36;1m%s[0m

.
```

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by kcgen** [comment]
The color tags were used to replace the ANSI code inline in the source code - but replacing them in each UTF-8 source file still needs to be done.  I think with some careful search-and-replacing (perhaps some `sed` statements could do the job).

Anyone out there want to tackle this?

In here,  https://github.com/dosbox-staging/dosbox-staging/tree/main/contrib/resources/translations/utf-8, check out the English file versus the other files.  The color tags match 1:1 with the ansi codes; so with some back and fourth inspection the replacement strings can be understood.

If anyone wants to try this, feel free to attach the color-tagged versions here, and we can add & credit that contribution. :+1:

**Comment by shermp** [comment]
We can probably come up with a `sed` one-liner to do the job...

**Comment by Kappa971** [comment]
So could I replace the old code with the new color tags in the utf-8 file?

Also note that DOSBox doesn't correctly print English strings with the command `config -wl [filename]`, some are missing (I have attached the file above).

**Comment by shermp** [comment]
> We can probably come up with a `sed` one-liner to do the job...

Actually, I'm dumb. no we can't :(

Let me see if I can come up with something

**Comment by shermp** [comment]
Here's a quick & dirty ANSI to tag conversion list:
```
\33[0m  [reset]
\33[30;1m  [color=black]
\33[31;1m  [color=red]
\33[32;1m  [color=green]
\33[33;1m  [color=yellow]
\33[34;1m  [color=blue]
\33[35;1m  [color=magenta]
\33[36;1m  [color=cyan]
\33[37;1m  [color=white]
\33[39;1m  [color=default]
\33[30m  [color=light-black]
\33[31m  [color=light-red]
\33[32m  [color=light-green]
\33[33m  [color=light-yellow]
\33[34m  [color=light-blue]
\33[35m  [color=light-magenta]
\33[36m  [color=light-cyan]
\33[37m  [color=light-white]
\33[39m  [color=light-default]
\33[40;1m  [bgcolor=black]
\33[41;1m  [bgcolor=red]
\33[42;1m  [bgcolor=green]
\33[43;1m  [bgcolor=yellow]
\33[44;1m  [bgcolor=blue]
\33[45;1m  [bgcolor=magenta]
\33[46;1m  [bgcolor=cyan]
\33[47;1m  [bgcolor=white]
\33[49;1m  [bgcolor=default]
\33[40m  [bgcolor=light-black]
\33[41m  [bgcolor=light-red]
\33[42m  [bgcolor=light-green]
\33[43m  [bgcolor=light-yellow]
\33[44m  [bgcolor=light-blue]
\33[45m  [bgcolor=light-magenta]
\33[46m  [bgcolor=light-cyan]
\33[47m  [bgcolor=light-white]
\33[49m  [bgcolor=light-default]
[erasel=0]  [erasel=0]
[erasel=1]  [erasel=1]
[erasel=2]  [erasel=2]
[erases=0]  [erases=0]
[erases=1]  [erases=1]
[erases=2]  [erases=2]
\33[3m  [i]
\33[23m\33[1m  [/i][b]
\33[22m  [/b]
\33[4m  [u]
\33[24m  [/u]
\33[9m  [s]
\33[29m  [/s]
\33[5m  [blink]
\33[25m  [/blink]
\33[2m  [dim]
\33[22m  [/dim]
\33[8m  [hidden]
\33[28m  [/hidden]
\33[7m  [inverse]
\33[27m  [/inverse]
```

Depending on how we actually do the replacement, the octal `\33` control character may need to be in a different format.

**Comment by Kappa971** [comment]
Ok, I'll wait in case faster solutions are found before having to manually change everything (with the risk of making mistake 😅).

> Also note that DOSBox doesn't correctly print English strings with the command `config -wl [filename]`, some are missing (I have attached the file above).

Is this a bug? Do I have to open a new issue?

**Comment by shermp** [comment]
I'll work on replacing ANSI escape codes with tags in existing translation files this afternoon.

Also, #1696 was just merged, which should (hopefully!) fix the `config -wl [filename]` issue.

**Comment by shermp** [comment]
In theory, this should have been straightforward.

In practice? Well, I did a mass search/replace, and `intro` was pretty messed up...

It's going to take a bit more time/effort than I had hoped :(

**Comment by Kappa971** [comment]
> Also, #1696 was just merged, which should (hopefully!) fix the `config -wl [filename]` issue.

Thanks @shermp, it seems to be solved: [eng.txt](https://github.com/dosbox-staging/dosbox-staging/files/8804432/eng.txt)

> In theory, this should have been straightforward.
>
>In practice? Well, I did a mass search/replace, and `intro` was pretty messed up...
>
>It's going to take a bit more time/effort than I had hoped :(

What method are you using? Maybe I could take care of the Italian translation.

**Comment by Kappa971** [comment]
This is the updated Italian translation file with the new color tags and some additions/corrections: [it.txt](https://github.com/dosbox-staging/dosbox-staging/files/8810013/it.txt)
I noticed two things:
1. blue strings can't be translated:
![dosbos_help](https://user-images.githubusercontent.com/62349018/171301713-2dc202de-ec99-41f9-abc8-1ef21334d207.png)
2. Is there a new tag for `\33[2J`?
Example:
```
:PROGRAM_INTRO
[2J[color=green]Benvenuto in DOSBox Staging[reset], un emulatore di x86 con audio e grafica.
DOSBox crea una shell simile al vecchio DOS.
```

**Comment by shermp** [comment]
Oh, good call on the category headers, they should become part of the translation. Let me think of the best way to do that.

**Comment by Kappa971** [comment]
Thanks @shermp!
Would it be possible to also create a script to automatically generate a translated configuration file in UTF-8 format? I was talking about it here: https://github.com/dosbox-staging/dosbox-staging/issues/884#issuecomment-1122918403

**Comment by Kappa971** [comment]
Here is the updated translation file: [it.txt](https://github.com/dosbox-staging/dosbox-staging/files/8837545/it.txt)
Here instead the configuration file created with the commands described above (I renamed `.conf` to `.txt` otherwise it doesn't let me load it): [dosbox-staging-ita.txt](https://github.com/dosbox-staging/dosbox-staging/files/8837546/dosbox-staging-ita.txt)

**Comment by Kappa971** [comment]
The problems here have been solved, the command "config -wl [filename] now works. As for the Italian translation I have released the file with the necessary corrections. None of the other translators seem aware of this, so maybe you should put a "announce" here https://github.com/dosbox-staging/dosbox-staging/issues/884, in order to let them know.
Following this, I could close this issue.

**Comment by kcgen** [comment]
> Here is the updated translation file (with new color tags and strings): [it.txt](https://github.com/dosbox-staging/dosbox-staging/files/8837545/it.txt) 

Thanks @Kappa971 - merged to `main` along with the generated `it.lng`.

> Here instead the configuration file created with the commands described above (I renamed `.conf` to `.txt` otherwise it doesn't let me load it): [dosbox-staging-ita.txt](https://github.com/dosbox-staging/dosbox-staging/files/8837546/dosbox-staging-ita.txt)
> 
> > ```
> > dosbox -c "config -wc dosbox.conf" -exit
> > iconv -f CP858 -t UTF-8 C:\Users\%username%\AppData\Local\DOSBox\dosbox.conf > dosbox-staging-ita.conf
> > ```

Thanks for the translated conf!  I'm not sure where to put these though. 
 - Do we put them somewhere in `the ./contrib/` folder as plain text files?
 - Should we convert it to markdown and host it on the Wiki?
 
Ideas / discussion welcome! :beers:

**Comment by kcgen** [comment]
> None of the other translators seem aware of this, so maybe you should put a "announce" here https://github.com/dosbox-staging/dosbox-staging/issues/884, in order to let them know.

Welcome to the Staging team, @Kappa971 !  Check your email for an invite - you now have upgraded rights in the organization and here, so can manage issues and other aspects on GitHub. 

We need help organizing the translation efforts. My time and knowledge in this area is limited; Please feel free to wear the pink jersey and take lead on this! (Giro d'Italia, :biking_man: :sunglasses: )

**Comment by Kappa971** [comment]
> Thanks @Kappa971 - merged to `main` along with the generated `it.lng`.

Thanks @kcgen!

> Thanks for the translated conf! I'm not sure where to put these though.
> 
> * Do we put them somewhere in `the ./contrib/` folder as plain text files?
> * Should we convert it to markdown and host it on the Wiki?
> 
> Ideas / discussion welcome! 🍻

I have some ideas, I don't know which of these is realistic:
1. DOSBox automatically generates a localized configuration file at startup and at the same time converts it to UTF-8. This would be the best in my opinion.
2.or we use the pre-created and converted configuration file and place it in a `ConfigFiles` folder inside `resources\translations`. In this folder we will have all the configuration files for each language. In this case the user would have to manually copy the `.conf` file and rename it to dosbox-staging.conf or DOSBox could do it automatically (instead of creating a configuration file, with languages other than English, it copies it from the ConfigFiles folder).

I would prefer the first method.

> Welcome to the Staging team, @Kappa971 ! Check your email for an invite - you now have upgraded rights in the organization and here, so can manage issues and other aspects on GitHub.
>
>We need help organizing the translation efforts. My time and knowledge in this area is limited; Please feel free to wear the pink jersey and take lead on this! (Giro d'Italia, 🚴‍♂️ 😎 )

I'm not an expert at all but thanks @kcgen 🙂

**Comment by kcgen** [comment]
Option 1 is combersome:
 - DOSBox needs to launch `iconv -f CP858 -t UTF-8 ...` as a system command, which perhaps is the easiest part.
 - Because we're launching an external command, `iconv`, the user needs to have the GNU `iconv` tools installed.  If they don't, they'll get an error message.
 - A lot of users aren't going to like us telling them to install a bunch of GNU tools (often with lots of dependencies) on their system, and then add it to their system PATH.
 - So that brings up a different approach: maybe we could bundle `iconv`?  Possible, but we'd have to provide binaries for all the different platforms we support (macOS ARM64, Win32, Linux-ARM7a, and so on).

Maybe there's a hybrid approach?  We could provide a simple script to run that command for the user, and including some comments that the user should indicate which code-page (ie: 858, etc) and that they'll need  `iconv` installed.

The second approach has me worried about conf files getting outdated, and the content becoming wrong or misleading for users. Although we could generate fresh conf dumps in CI, so the package is always up-to-date.

From a convenience position though, expecting users to setup `iconv` is a much bigger hassle than being able to open a text file; so the second option is certainly the most convenient.

If we did generate these conf files in CI, where should we place these conf files?

**Comment by shermp** [comment]
Umm, or we can just use a library to do the encoding, such as... `iconv`. Or ICU, or maybe there's a nice C++ encoding converter around because the `iconv` API is annoying to use. DOSBox should know what codepage it's using, so that shouldn't be an issue.

**Comment by Kappa971** [comment]
> Option 1 is combersome:
> 
> * DOSBox needs to launch `iconv -f CP858 -t UTF-8 ...` as a system command, which perhaps is the easiest part.
> * Because we're launching an external command, `iconv`, the user needs to have the GNU `iconv` tools installed.  If they don't, they'll get an error message.
> * A lot of users aren't going to like us telling them to install a bunch of GNU tools (often with lots of dependencies) on their system, and then add it to their system PATH.
> * So that brings up a different approach: maybe we could bundle `iconv`?  Possible, but we'd have to provide binaries for all the different platforms we support (macOS ARM64, Win32, Linux-ARM7a, and so on).
> 
> Maybe there's a hybrid approach? We could provide a simple script to run that command for the user, and including some comments that the user should indicate which code-page (ie: 858, etc) and that they'll need `iconv` installed.

Too complex...

> Option 2 has me worried about conf files getting outdated:
> 
> With time, they will become misleading or invalid. Although we could generate fresh conf dumps in CI, so the package is always up-to-date.

This could be a solution. We have pre-created configuration files, but in this case we should document that these files exist, otherwise no one would use them. I would create them inside a `ConfigFiles` folder in `resources/translations`.

> Umm, or we can just use a library to do the encoding, such as... iconv. Or ICU, or maybe there's a nice C++ encoding converter around because the iconv API is annoying to use. DOSBox should know what codepage it's using, so that shouldn't be an issue.

This would be the ultimate solution as DOSBox would do it all by itself, it would automatically create a configuration file based on the chosen language.

**Comment by kcgen** [comment]
Option 2 is good for new users because they haven't customized their primary conf yet, so they can take the conf straight away.

It becomes more more work for this user on the next release.

They now have heavily customized 0.79 conf, and now 0.80 is out with an all new translated conf file. 

They've got options:
 1.  Be lazy: abandon their customizations and overwrite their old 0.79 file with the new one
 2.  Be lazy: ignore the new one, and keep using their old (and pay attention to warnings/errors)
 3.  Do work: manually back-port the 0.80 additions into their old 0.79 conf
 4.  Do work: manually carry their 0.79 customizations into the 0.80 conf

I also like the third option: `DOSBox would do it all by itself`, with @shermp's better approaches to deal with iconv.  
 - I'm thinking about the first-time user: that's when DOSBox sees that the user's config directory and conf files are not present, and it tries to create them.
 - It's at this moment when the conf is written, so that's when it needs to be informed of the code-page to use.  Are we thinking it will determine this from the OS or can derive it from a shell variable, like `LANG=...`? (just thinking/wondering out loud).

**Comment by Kappa971** [comment]
> The third option, `DOSBox would do it all by itself` sounds great with @shermp's better approaches to deal with iconv.
> 
> * I'm thinking about the first-time user: that's when DOSBox sees that the user's config directory and conf files are not present, and it tries to create them.
> * It's at this moment when the conf is written, so that's when it needs to be informed of the code-page to use.  Are we thinking it will determine this from the OS or can derive it from a shell variable, like `LANG=...`? (just thinking/wondering out loud).

It might link to this: https://github.com/dosbox-staging/dosbox-staging/issues/1062
I understand that currently DOSBox sets the language according to that of the OS, and so it could set the codepage based on the language.

**Comment by Kappa971** [comment]
If DOSBox 0.79 release happens soon, I will upload the finished Italian translation file for this version. What do the new permissions allow me to do? Can I upload the it.txt and it.lng files myself? Do I need to create a PR? 

Also the other translations date back to DOSBox 0.78 and have not been updated since then, the en.txt file has been updated several times already, so updating it again would not display all the changes from 0.78 to 0.79. This is a problem because those translations require serious revision.

**Comment by kcgen** [comment]
> I can update the Italian translation as soon as DOSBox 0.79 is complete (before release).

:+1: , I've just refreshed the source UTF-8 files with the current additions, deletions, and changes from `main`.

> Other translators should help update their translations, adding at least the new strings 

We'll let the main translation thread throw, and hopefully many hands can make this light work. 

> (the old color "tags" should work anyway, right?)

Yes!

> To help we could downgrade the eng.txt file to DOSBox 0.78.0 and then update the file to DOSBox 0.79 (final), so that all changes would be shown. Is there an easier way to do this?

With the latest commit to main, hopefully this is now the case.  On the changed messages in need of translation have been changed (and are now switched back to English).  

If a message is still shown in the native language, then we know it's perfectly up-to-date.

> oh and the translated config files...

Thanks for bringing that up, @Kappa971.  

Did we have a dedicated ticket for this proposal/idea? If not, can you make a new ticket for it - so we can add it to the 0.79 project triage list?

(If you can find that original discussion, you can convert a comment into a ticket using the three dots beside the comment and choose "Reference in new ...")

**Comment by Kappa971** [comment]
I think it is this: https://github.com/dosbox-staging/dosbox-staging/issues/1698#issuecomment-1148243212
And I created a new issue: https://github.com/dosbox-staging/dosbox-staging/issues/1791

**Comment by kcgen** [comment]
This command can tell us how many ANSI colour codes need to be replaced:

**`git grep -c '\[[03]' contrib/resources/translations/utf-8/`**

 - contrib/resources/translations/utf-8/de.txt:228
 - contrib/resources/translations/utf-8/en.txt:71
 - contrib/resources/translations/utf-8/es.txt:310
 - contrib/resources/translations/utf-8/fr.txt:98
 - contrib/resources/translations/utf-8/it.txt:1
 - contrib/resources/translations/utf-8/pl.txt:98
 - contrib/resources/translations/utf-8/ru.txt:246

Or, drop the `-c` to show the actual affected lines, for example, to see the remaining use in the Italian messages:

git grep  '\[[03]' contrib/resources/translations/utf-8/it.txt

`[color=yellow]%s+F1[reset]   %s Avvia il [1;31m[33mkeymapper[1;31m[0m.`

**Comment by Kappa971** [comment]
> ```
> it.txt:[1;31m[2J[color=green]Benvenuto in DOSBox Staging[reset], un emulatore di x86 con audio e grafica.
> it.txt:[1;31m[2J[color=green]Ecco alcuni comandi utili per iniziare:[reset]
> it.txt:[1;31m[2J[color=green]Come montare un'unità CD-ROM reale/virtuale in DOSBox:[reset]
> it.txt:[1;31m[2J[color=green]Come montare un'unità CD-ROM reale/virtuale in DOSBox:[reset]
> it.txt:[1;31m[2J[color=green]Tasti speciali:[reset]
> ```

I don't know how to replace `[1;31m[2J`

> ```
> it.txt:[color=yellow]%s+F1[reset]   %s Avvia il [1;31m[33mkeymapper[1;31m[0m.
> ```

Solved

**Comment by kcgen** [comment]
I wonder if the [2J is some kind leftover junk?

Nice work @Kappa971 ! The Italian messages are ahead of the English ones in adopting the color tags. 😅

**Comment by Kappa971** [comment]
> I wonder if the [2J is some kind leftover junk? (Probably can drop it without issue).

I think it cleans the screen.

**Comment by shermp** [comment]
> I wonder if the [2J is some kind leftover junk? (Probably can drop it without issue).
> 
> Nice work @Kappa971 ! The Italian messages are ahead of the English ones in adopting the color tags. 😅

`[2J` is "erase entire screen", so definitely not leftover junk.

**Comment by shermp** [comment]
As a note, when I tried doing a bulk find & replace, I uncovered issues on some of the really complex stuff, so it probably isn't a viable solution.

**Comment by kcgen** [comment]
> As a note, when I tried doing a bulk find & replace, I uncovered issues on some of the really complex stuff, so it probably isn't a viable solution.

The bulk conversion was still a massive improvement!

```
git grep -c '\[[a-z]' 
de.txt:13
en.txt:287
es.txt:21
fr.txt:196
it.txt:381
pl.txt:195
ru.txt:13
```

The remaining migration can happen by hand whenever an message needs translation. The translator can drop the ANSI symbols and switch to the much nicer tags.

**Comment by Kappa971** [comment]
Here is the updated Italian translation file: [it.txt](https://github.com/dosbox-staging/dosbox-staging/files/9123130/it.txt)
I hope there are no errors 😁
