### ISSUE TITLE
Page Faults after FMV playback for Virtual Pool (1995)

### ISSUE THREAD

**Issue by OpenRift412** [dosbox-staging/dosbox-staging#1731]
After the intro/game videos for Virtual Pool play or are skipped, the game gives a pagefault error (see below). I can't find any other information on this, and I didn't have this issue in my Win95 VM. 

The error:
![pool_000](https://user-images.githubusercontent.com/29780788/174214263-67ff271d-ca48-4eab-b1cb-c3f07bab4ec0.png)

Any idea on how this could be fixed?

**Comment by OpenRift412** [comment]
> In exodos we had to use Daum, set cycles to 30000, machine=svga_s3, run games config.exe and select 1024x768 VESA Linear Single Page. You can also copy this game cfg file into the game folder: [POOL.zip](https://github.com/dosbox-staging/dosbox-staging/files/8941946/POOL.zip). When you start the game dont press F5 to skip video driver selection as this will reset the driver being used to a default that will cause issues on next game launch.
> 
> Virtual Snooker has the same issue

Yeah, it seems to _only_ work in in SVN Daum. I tried the same settings in Staging and was still getting the page fault stuff. Also seems to work fine in 640x480 VESA Planar Multi Page in Daum. No idea what the difference between the two would be that's causing that, so I dunno. 

Thanks anyway, though!

**Comment by Burrito78** [comment]
Work in latest DEV version, so i'm closing this now.
