### ISSUE TITLE
Apply auto-gain/leveler/compressor to the master output

### ISSUE THREAD

**Issue by johnnovak** [dosbox-staging/dosbox-staging#1743]
From the point of adding samples to the mixbuffer, now we have a float signal path. Volume scaling is applied to the float samples per channel first, and once more to the summed master channel (in the form of the master volume). This renders applying the soft-limiter to certain channels unnecessary at best and potentially harmful at worst, as we can technically raise the gain of every channel by say +20 dB and then bring down the master by -20 dB and we'd get no clipping whatsoever thanks to float processing. The soft-gainer would introduce unwanted artifacts in this scenario.

This is an extreme example and no one would want to do this, of course, but it illustrates the concept clearly — limiting individual channels to the 16-bit value range is meaningless when using floats. A better approach would be to apply some auto-gainer, or levelling amplifier, or compressor to the summed master output only. It's unclear what kind of processing would be best, so deciding on the final solution will require some experimentation with different algorithms.

**Comment by johnnovak** [comment]
The setting I used for reference:

![image](https://user-images.githubusercontent.com/698770/175298220-a188e70d-2830-46d9-bddf-447aced9969c.png)

**Comment by kcgen** [comment]
Very nice find!  I haven't even heard of this programming language, let alone the compressor :laughing: 

The code looks extremely readable - basically fortran-ish, but for N-channel audio vector'd to the "pins", behind each variable? 

Regarding linking the algorithm to the peak volume of any of the input pins - is that something the language does (I can't tell in the algorithm where it does that).

Regarding the detection source: `Feedforward`: does that need it needs some look-ahead (or add latency, before compressed frames are coming out the back side?)  A couple milliseconds is no big deal, if that's the case.

**Comment by johnnovak** [comment]
> Very nice find! I haven't even heard of this programming language, let alone the compressor 😆

Yeah, I think nowadays it gets referred to as JSFX; apparently they "rebranded" it from JesuSonic (look at the [pictures](https://www.cockos.com/jsfx/) here and you'll understand the original naming choice... 😄)

Here's the reference manual:
https://www.reaper.fm/sdk/js/js.php

You can find tons of JSFX plugins online for all sorts of signal processing tasks imaginable (and even for MIDI processing), some of them even feature quite nice GUIs. And the best part: you can always inspect the source code!

> The code looks extremely readable - basically fortran-ish, but for N-channel audio vector'd to the "pins", behind each variable?

It supports up to 64 channels; the samples of a single frame are available through the `spl0`-`spl63` variables, or alternatively the `spl[]` array.

> Regarding linking the algorithm to the peak volume of any of the input pins - is that something the language does (I can't tell in the algorithm where it does that).

There's no magic  — everything is 100% done in the algorithm. `spl0` and `spl1` (the stereo input) and the parameters set with the sliders on the GUI are the only inputs. Have another look at stuff like `maxspl`, `runave`, `overdb > maxover`, etc. 

You can select whether the compressor reacts to RMS or peaks; I found that using RMS gives the best and most natural results as acting on peaks can become too "jumpy".

> Regarding the detection source: Feedforward: does that imply some look-ahead before compressed frames are coming out the back side? (just for understanding; even if that's the case, a couple milliseconds is no big deal).

It's a zero-latency algorithm. The name "feed-forward" is a bit deceptive; it might imply lookahead, you're right, but when it comes to compressors, it means something entirely different:

- In **feed-forward** designs the gain reduction is a function of the input signal only (so the input controls the gain control circuit, which then "feeds that forward" to the VCA (voltage controlled amplifier) that performs the gain reduction)
- In **feedback** designs the gain reduction is a function of the compressor's output, _not_ the input signal. So we get a complex adaptive behaviour that is dependent on the compressors output, which in turn is dependent on the original input — so we have a feedback loop in the control circuit.

In practical terms, **feedback** designs are the vintage tube, FET and optoelectric compressors. The feedback design introduces a "lag" to how fast the compressor can react to changes in the input signal, which results in very laid-back, relaxed, and "musical" compression characteristics. They are highly sought after for this reason, but they're not very good at fast limiting type compression and reacting to transients.

Modern **feed-forward** designs are almost always transistor based (e.g. implemented in integrated circuits) and provide very precise and fast control over transients. I think they became popular during the 80s or so, and you just _need_ these fast compressors for modern musical styles. They have a kind of a sledge-hammer approach to transients, so that's what we need here.

It's a fascinating topic, here's a very comprehensive article about compressors if you're interested:

https://mynewmicrophone.com/feedback-vs-feedforward-dynamic-range-compressors-in-audio/#Feedback-Vs.-Feed-Forward-Compressors

Here's the most important part relevant to our discussion:

> Though both feed-forward and feedback compressors are capable of fast attack and release times (depending on the gain reduction circuit type), the feed-forward topology can act more instantaneously as it doesn't have to adjust to any signal that's already been compressed.
>
> Therefore, feed-forward circuits are favoured for catching fast transients and for hard limiting. Hard limiting is the process where, ideally, absolutely no signal can be passed above a hard threshold (think of it as a compressor with an attack time of 0 and a ratio of ∞:1).
>
> Feed-forward designs can approximate the idealization, whereas feedback designs, though fast, could never reach this instantaneous reaction time.

Well, maybe too much information, but I really like to talk about audio stuff 😊

**Comment by kcgen** [comment]
Done.
