### ISSUE TITLE
Launch override parameters

### ISSUE THREAD

**Issue by keenanweaver** [dosbox-staging/dosbox-staging#1744]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### What Operating System are you using?

Linux x86_64

### If Other OS, please describe

Arch

### Is your feature request related to a problem? Please describe.

Not a problem necessarily, but changing Staging settings mostly requires editing an external file. Changing settings on the fly at runtime could prove useful in certain cases.

### Describe the solution you'd like

Howdy. I looked around the wiki, past issues, and discussions, but couldn't really find a similar topic. Please point me in that direction if this discussion has already occurred, or if this feature already exists in Staging.

I think it would be a valuable feature to have a launch parameter that overrides all layered Staging config files--including global. DOSBox-X has the feature with the "set" parameter.

Overview:

cat WC1.conf
```
[sdl]
output = openglpp
[cpu]
cycles = max
```

(Using global conf)
`./dosbox `
```
[sdl]
output = surface
[cpu]
cycles = auto
```

(Using user conf)
`./dosbox -conf WC1.conf`
```
[sdl]
output = openglpp
[cpu]
cycles = max
```

(Using user conf, setting 1 override parameter)
`./dosbox -conf WC1.conf -set "cpu cycles=4000"`
```
[sdl]
output = openglpp
[cpu]
cycles = 4000
```

(Using global conf, setting 2 override parameters)
`./dosbox -set "cpu cycles=4000" -set "mt32 model=mt32_new"`
```
[sdl]
output = surface
[cpu]
cycles = 4000
[mt32]
model = mt32_new
```
Why I think it's worth pursuing:

- Provides another option for modifying settings in addition to the global & user configs and hotkeys.
- Fast workflow in testing config settings. Personally, I like testing out different soundfonts, and being able to change it in the launch parameters would be much faster than finding & modifying the conf file. Unfortunately, not everyone is a vim wizard.
- Easy portable usage for 'smaller' configs.  As elegant as the conf files are, I think for some users, creating a shortcut or shell script with the launch parameters might work best. It would make for easy distribution of DOSBox setting 'profiles' in the form of shortcuts or shell scripts.

Examples:
./Wing Commander I (MT-32).bat
`dosbox.exe -set "cpu cycles=4000" -set "midi mididevice=mt32"`
./Wing Commander I (SB16).bat
`dosbox.exe -set "cpu cycles=4000" -set "midi mididevice=fluidsynth"`

(WC1 is kind of a bad example since you also have to modify another file to 'fully' set up which sound system to use, but I think the idea comes across.)

Concerns:

- Provides an avenue of confusion. User may not realize why modifying the dosbox.conf file is not changing a certain setting if a launch override parameter is also being used.
- Incredibly long launch commands if the feature is overused.

I'm not a programmer (just a lowly sysadmin), so I can't provide the necessary code at this point in time. But I hope this request is a warranted feature and someone pursues it!

### Describe alternatives you've considered

DOSBox-X has a similar "set" function (see links). As far as I've researched, Staging presently has no viable alternative.

### Add any other context or screenshots about the feature request here.

DOSBox-X implementation of similar feature https://dosbox-x.com/wiki/Home#_dosbox_xs_configuration_file

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by arrowgent** [comment]
this idea is already partially complete

see: Command Line Parameters.

https://github.com/dosbox-staging/dosbox-staging/blob/main/README#L367

**Comment by Burrito78** [comment]
I think the current implementation is complex enough. Reopen if this gets requested again.

**Comment by johnnovak** [comment]
Too much complication. Just edit the the configs.
