### ISSUE TITLE
Clang format broken in Visual Studio 2019

### ISSUE THREAD

**Issue by johnnovak** [dosbox-staging/dosbox-staging#1767]
Hey @kklobe, updating the Clang format to 12.0.0 in your commit e7fda5a7d1aa466b6f7 broke the formatter for me in Visual Studio 2019 16.11.2

![image](https://user-images.githubusercontent.com/698770/176980569-7fd998da-37c1-40b4-9bd3-fb67f5e19174.png)

If I comment out the last line it complains about (`SortIncludes: Never`), or change `Never` to `false`, then it works. It's strange because the `clang-format.exe` included with VS2019 seems to be v12.0.0:

![image](https://user-images.githubusercontent.com/698770/176980695-c0b051cc-d40b-469d-b4be-c7fa8bddcd90.png)

Can anyone else on Windows reproduce the issue? @shermp, you're using Windows if I recall correctly?

**Comment by kcgen** [comment]
Falling back to default (by commenting out `SortIncludes` for now).
Thanks for catching this @johnnovak!

**Comment by kcgen** [comment]
Fixed with https://github.com/dosbox-staging/dosbox-staging/commit/d6902ed5a068b685b6efeb9f37a4eecb039d02f4.
