### ISSUE TITLE
PC speaker emulation causes Narco Police to segfault

### ISSUE THREAD

**Issue by johnnovak** [dosbox-staging/dosbox-staging#1776]
1. Start Narco Police
2. Keep moving forward by pressing 9
3. When the first wave of enemy soldiers appear, move fully to the side by pressing 6 and start shooting with 0
4. 9 times out of 10 the game will segfault within seconds (interestingly it happens much less frequently when you stay in the centre)

If you disable the PC speaker emulation, the game doesn't crash.

Sanitizer logs:

```
2022-07-07 22:59:23.256 | ENVELOPE: PCSPEAKER done after 7142 frames, peak sample was 16399.000000
2022-07-07 22:59:35.678 | EXCEPTION: Standard library exception: array::at
2022-07-07 22:59:35.790 | atexit
2022-07-07 22:59:35.791 | PCSPEAKER: Shutting down discrete model
/opt/local/libexec/llvm-14/bin/../include/c++/v1/__memory/unique_ptr.h:503:12: runtime error: applying non-zero offset 800 to null pointer
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior /opt/local/libexec/llvm-14/bin/../include/c++/v1/__memory/unique_ptr.h:503:12 in

Loguru caught a signal: SIGSEGV
2022-07-07 22:59:35.792 | Signal: SIGSEGV
zsh: segmentation fault  ~/dev/jn/dosbox-staging/build/sanitizer/dosbox
```

**Comment by kcgen** [comment]
Reproduced; thanks @johnnovak !
Will probably switch out the fixed sized array for a queue.

**Comment by johnnovak** [comment]
> Reproduced; thanks @johnnovak ! Will probably switch out the fixed sized array for a queue.

That was quick! Great outcome!
