### ISSUE TITLE
GS2000

### ISSUE THREAD

**Issue by DarthSabbath** [dosbox-staging/dosbox-staging#1787]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### What Operating System are you using?

Windows 11

### Whats your question and how can we help?

How do I use a controller for Gunship 2000? 

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by kcgen** [comment]
Do you have a controller and have you  you tried to get it working in this game? 

If so, what happened? 

Please share all those details in a new GitHub ticket.
