### ISSUE TITLE
Translate the DOSBox configuration files

### ISSUE THREAD

**Issue by Kappa971** [dosbox-staging/dosbox-staging#1791]
I have some ideas, I don't know which of these is realistic:
1. DOSBox automatically generates a localized configuration file at startup and at the same time converts it to UTF-8. This would be the best in my opinion.
2. or we use the pre-created and converted configuration file and place it in a `ConfigFiles` folder inside `resources\translations`. In this folder we will have all the configuration files for each language. In this case the user would have to manually copy the `.conf` file and rename it to dosbox-staging.conf or DOSBox could do it automatically (instead of creating a configuration file, with languages other than English, it copies it from the ConfigFiles folder).

I would prefer the first method, if it is possible to implement it.

These are the commands I used to manually create the translated configuration file:
```
dosbox -c "config -wc dosbox.conf" -exit
iconv -f CP858 -t UTF-8 C:\Users\%username%\AppData\Local\DOSBox\dosbox.conf > dosbox-staging-ita.conf
```

**Comment by kcgen** [comment]
@shermp , @Kappa971 ,

1. Regarding the `iconv` requirement, we should have it under Linux, macOS, and MSYS2 - so I think we're covered?

2. When it comes to generating the conversions using the above command:

    ``` shell
    dosbox -c "config -wc dosbox.conf" -exit
    iconv -f CP858 -t UTF-8 C:\Users\%username%\AppData\Local\DOSBox\dosbox.conf > dosbox-staging-ita.conf
    ```

    I think this step could be added at package-creation time, given at that point we have an up-to-date-build.  

    So in theory, this step could be added to `script/create-package.sh`? (or perhaps called as a sub-script, looping over each language file)

3. Finally, where to put the resulting conf files? 
    - We want these bundled in the release package as examples for users.
    - We don't want them in our source repo; they're derived artifacts just meant for the release package.
    - Suggest we create a new directory in the release package for these, and perhaps add a little readme.txt to inform users about them.


I've marked this this in-scope for the 0.79 release, if either of you feel like progressing this over the next ~3 or so weeks (if not - no problem; then move the ticket to the backlog).

**Comment by shermp** [comment]
I feel DOSBox should do this internally instead of as an external command. We can call iconv as a library, or perhaps https://en.cppreference.com/w/cpp/locale/codecvt could work?

**Comment by kcgen** [comment]
[Haven't heard of ](https://en.cppreference.com/w/cpp/locale/codecvt) looks interesting! I wasn't aware the language itself supported this type of locale/UTF-8 conversion.  If you know how to put that to use, I'm all for it!

As for `iconv`, I'm not sure if it's in a better state - but I remember "iconv and friends" giving me a lot of heartburn on systems that weren't GNU-through-and-through (might have been BSD, MinGW, and/or macOS) - I very much want to avoid using it, let along having our binaries link-with it (the less `iconv` the better :laughing:!)

**Comment by shermp** [comment]
I mean, we're linking against `iconv` anyway, because `glib`. But yeah, having used `iconv` myself, it's not the nicest thing in the world to use...

**Comment by kcgen** [comment]
argh :face_exhaling: at least it's not a direct dependency and only comes in by way of using FluidSynth (I think). The more we can move to the language itself, the better :+1:

**Comment by Kappa971** [comment]
I think for DOSBox 0.79 we could have the `create-package.sh` script automatically create these files in the "resources\translations" folder (perhaps in a subfolder called "configFiles"), and then it is up to the user to rename and copy the files to the correct location (not the best solution but temporarily it could be done this way).

**Comment by kcgen** [comment]
Moving to 0.8! 

Can also discuss possibilities of documenting settings in various languages in an online documentation system too, with search and better formatting/layout (versus text files).

**Comment by Kappa971** [comment]
It would be nice to have the translated configuration files into the DOSBox Staging 0.79 release package, at least until a better solution is found.

> Moving to 0.8!
> 
> Can also discuss possibilities of documenting settings in various languages in an online documentation system too, with search and better formatting/layout (versus text files).

It is certainly a good thing, but you have to consider how "expensive" it can be for a single person to translate and maintain a documentation that I imagine can be very detailed, and therefore with a lot of text, in addition to the translation of DOSBox... but it's a nice idea.

**Comment by kcgen** [comment]
> you have to consider how "expensive" it can be for a single person to translate and maintain a documentation

That's for sure - the translations are a great example. It takes ongoing effort keep those up-to-date, and further downstream versions will be even harder.

The good news is that @FeralChild64's current PR (slated for 0.80) will allow for UTF8 in the translated content, and I believe this will translate to UTF8-generated conf file (so it might render this no longer an issue).

**Comment by Kappa971** [comment]
This is good news, but I still believe that with the release of DOSBox 0.79 the translated .conf files converted in UTF-8 should be provided. You could temporarily add commands to generate the .conf file (as described above) in the .sh script for creating the package, and when that PR is merged, the commands will be removed.

**Comment by Grounded0** [comment]
Unix has some nice tools for character set conversions like iconv.

**Comment by kcgen** [comment]
@Kappa971,

We're going to have three or four supported languages at release time:
 - German
 - Italian
 - Polish
 - Russian (maybe)

When we create the 0.79 release branch, I think it will make sense to simply manually run your `iconv` command and add these conf files to the branch under the `contrib/` area, at the time of release.

Is that something you could PR, when that time comes? (alternatively: you could attach a zip of the files and recommended where you would like to place them in the release package). I will add them to the branch with yourself as author.

These files will only exist on the 0.79 branch as 0.79-specific artifacts.

The `main` branch will not have them, as it will soon have @FeralChild64 's UTF-8 routines performing this conversion.

**Comment by Kappa971** [comment]
In `contrib/translations` do we create a new directory for the configuration files? And inside this folder the configuration files called for example `dosbox-staging-[lang].conf`.

Or we could wait for @FeralChild64's PR to be merged into the main branch and then release DOSBox 0.79 (if the PR is almost finished, and it would only delay release a little).

**Comment by Grounded0** [comment]
It will not go into 0.79 because it's considered a high risk merge.

**Comment by Kappa971** [comment]
These steps can also be done from the GitHub web GUI, right?


However I would like to point out (even if this is not the right place), that some new strings added are not "translatable":
https://github.com/dosbox-staging/dosbox-staging/commit/8730780d5bd1b1d32feabc41872d291fa30530ef and the PR https://github.com/dosbox-staging/dosbox-staging/pull/1903

**Comment by kcgen** [comment]
> These steps can also be done from the GitHub web GUI, right?

I'm not sure (I use the `git` command line).
But if the GitHub web GUI lets you create a new branch, edit existing files, and add/upload new files, then yes :+1: !

> However I would like to point out (even if this is not the right place), that some new strings added are not "translatable":

In progress :slightly_smiling_face:

**Comment by kcgen** [comment]
@Kappa971 , if you can send a zip (or PR) of the confs, we can drop them in now!

**Comment by kcgen** [comment]
Option 1 is now implemented in `main` :partying_face: 
Big thanks to @FeralChild64's UTF-8 PR!
Closing.
