### ISSUE TITLE
No AdLib music but PC Speaker Fire & Forget II

### ISSUE THREAD

**Issue by admnd** [dosbox-staging/dosbox-staging#1797]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Different version than latest?

0.79.0-alpha-929-gf2b185564

### What Operating System are you using?

Linux x86_64

### If Other OS, please describe

Gentoo

### Relevant hardware info

AMD Ryzen 5950X

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Fire and Forget II defaults to PC Speaker even if AdLib is choosen. No idea if a previous version was functional.
I saw that an issue had been filed for another of their titles (Blue Brothers in issue #459), even using the mentioned commit no AdLib sound :(

Some other AdLib games works seems specific to that game.

Tried with 0.78.1 no more success. 

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Run FF2 and choose AdLib
2.
3.

### Your configuration

```ini
https://gist.github.com/admnd/3d54cff961f0535c793fb17ea4172e5f
```

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by LowLevelMahn** [comment]
there is an old discussion on vogons: https://www.vogons.org/viewtopic.php?t=9327

**Comment by admnd** [comment]
Seems that only setting oplmode to 'opl2'  was sufficient (the game has to be slowed down to be playable but the base rate works for the audio). Thank you so much for the hint!

Also found this => https://www.vogons.org/viewtopic.php?t=16523, quoting:

`The OPL3 is intended to be fully backwards-compatible to the OPL2, which means an OPL2 app should sound exactly the same on an OPL3. If you don't use the new features, it behaves like an OPL2.

The OPL3 was not widely supported before 1992 because few sound cards had it (first appeared on later SB Pro revisions, I think). Sid Meier's Civilization for example had a special driver for OPL3 cards added at the last moment (or probably as a separate download, don't recall exactly), and indeed, the music sounds more richly with it.
`

**Comment by kcgen** [comment]
Yes, `sbtype = sb1` works.

Fire & Forget II was released in 1990, which was when the Sound Blaster 1.x was available.  Even th

```
1988 - Adlib
1990 - SB1 and MT-32
1991 - SB2 and SBPro1
1992 - SBPro2 and Adlib Gold
1993 - SB16
```

Summarized from JamesF's excellent research reported here: https://www.vogons.org/viewtopic.php?f=46&t=50670
