### ISSUE TITLE
When 'language = de', writing the conf using 'config -wc' results in a file that isn't UTF-8

### ISSUE THREAD

**Issue by Burrito78** [dosbox-staging/dosbox-staging#1799]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Different version than latest?

development version

### What Operating System are you using?

Mac OS

### Relevant hardware info

Macbook Pro 2014

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

When „language = de“ is set, the command „config -wc“ writes a file that isn’t UTF-8 and can’t be opened by textedit.app. The file contains mangled german umlauts (ä, ö, ü characters).

The file in question is attached.

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Set language to german using 'language = de' in the conf file.
2. Start DOSBox Staging
3. Enter 'config -wc' to write the config file back in german.

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by Burrito78** [comment]
[dosbox-staging.conf.zip](https://github.com/dosbox-staging/dosbox-staging/files/9133811/dosbox-staging.conf.zip)

**Comment by Burrito78** [comment]
Uhh, this seems to be related to https://github.com/dosbox-staging/dosbox-staging/issues/884#issuecomment-1122918403

So maybe not a new issue.

**Comment by Kappa971** [comment]
It could relate to this: https://github.com/dosbox-staging/dosbox-staging/issues/1791

DOSBox doesn't automatically create translated configuration files on startup, and doesn't create UTF-8 translated configuration files with the command `config -wc`

**Comment by Kappa971** [comment]
I think it concerns all languages, probably also English, and not just German or Italian.

**Comment by Burrito78** [comment]
Yes, russian too according to @GranMinigun. German language is an example to reproduce 100% easily.

**Comment by Kappa971** [comment]
This will not be solved for DOSBox 0.79. 
With the command "config -wc" DOSBox prints a translated configuration file with code page 850 (Italian, German, French and Spanish). Windows Notepad supports UTF-8 or Windows ANSI (CP1252), so some characters are shown incorrectly.
The solution for now is to convert the configuration file to UTF-8 with the "iconv" tool, and include the converted .conf files in the DOSBox 0.79 release package

**Comment by FeralChild64** [comment]
@Burrito78: With recent changes in _main_ this should be fixed, for all the languages. Can you confirm?

**Comment by Burrito78** [comment]
> @Burrito78: With recent changes in _main_ this should be fixed, for all the languages. Can you confirm?

Yes, this is now properly working in latest main build! Thanks!!

**Comment by Kappa971** [comment]
I confirm the problem has been fixed, DOSBox now produces a UTF-8 file.

Unfortunately, however, at the first start, if it doesn't detect any configuration file, DOSBox prints a configuration file only in English. Is it possible to fix this?

**Comment by FeralChild64** [comment]
@Kappa971: I would suggest creating a separate issue for this. I'm not sure in what state is the language detection at startup, however.
