### ISSUE TITLE
viewport_resolution is broken on HighDPI displays unless set to "fit"

### ISSUE THREAD

**Issue by johnnovak** [dosbox-staging/dosbox-staging#1802]
The physical resolution of my MacBook Pro's Retina screen is 3072x1920. `SDL_GetDisplayBounds` returns the display dimensions in some sort of logical units, 1792x1120 to be exact, which is very strange as the scale factor is then 1.7142857143... Huh?

My specs:

<img width="289" alt="image" src="https://user-images.githubusercontent.com/698770/180202119-e4603a8c-7f4a-4446-b071-6f61ee26b656.png">

For normal drawing operations the unscaled physical dimensions are used, apparently. This completely screws up the `viewport_resolution` handling, as `viewport_resolution` is interpreted in physical pixels, but `windowresolution` as a logical dimension (whatever that means on macOS).

So when I simply try to to set `viewport_resolution = 960x720`, I'm getting a tiny image because it's using unscaled pixels.

No problem, let's double it then and use `viewport_resolution = 1920x1440`. Ooops, can't do that because of the physical/logical unit discrepancy (`SDL_GetDisplayBounds` is used to determine the max desktop bounds):

```
2022-07-21 18:14:04.637 | DISPLAY: Requested viewport_resolution of '1920x1440' is outside the desktop '1792x1120' bounds or the 1-100% range,  using the default setting ('fit') instead
```

The problem is that there simply isn't a way to find out the HighDPI scaling factor before creating a window. For an existing window, you can call `SDL_GL_GetDrawableSize` on it and then divide that by the logical window dimensions returned by `SDL_GetWindowSize`.

I attempted using `SDL_GetDisplayDPI` in the hope that I can get some useful info out of the returned values, but not even sure what those numbers mean... I have no idea how to infer the scaling factor from them.

```
    float ddpi, hdpi, vdpi;
    SDL_GetDisplayDPI(0, &ddpi, &hdpi, &vdpi);
    LOG_WARNING("ddpi %f, hdpi %f, vdpi %f", ddpi, hdpi, vdpi);
```

This outputs: `ddpi 226.525497, hdpi 226.285706, vdpi 227.142868`

So, as I see it, there are only two solutions at the moment (well, the third is to pester the SDL devs to fix this; apparently many users are quite unhappy with their HighDPI API):

1. Remove the bounds check completely on macOS only, then the user can manually scale the `viewport_resolution values` up to get correct results. For example, in this case you'll get a window where the viewport perfectly fits within the window bounds (because of the 2x scaling factor):

```ini
[sdl]
windowresolution = 960x720
viewport_resolution = 1920x1440
```

Well, it's not a great solution, and not portable between different operating systems.

2. Create the window with hardcoded dimensions with an OpenGL context at startup, then we can query `SDL_GL_GetDrawableSize` on that window and resize it accordingly. Hacky, but could work, and hopefully there will be no flashing when resizing it...

Really wanted to fix this today, but I'm unsure about the best way forward, given these complications.

---------

Some images:

```ini
[sdl]
windowresolution = 960x720
viewport_resolution = 960x720
```

<img width="1072" alt="image" src="https://user-images.githubusercontent.com/698770/180170887-92c00655-590f-4575-a23d-08961dceb314.png">

-------

You need to remove the bounds check for the below config to work:

```ini
[sdl]
windowresolution = 960x720
viewport_resolution = 1920x1440
```

<img width="1072" alt="image" src="https://user-images.githubusercontent.com/698770/180171200-d31ceab4-f880-434d-82a5-8b15623e2daf.png">

**Comment by kcgen** [comment]
> For pixel purists, this kind of scaling is far from ideal, bordering on sacrilegious. To make matters worse, Apple set the 2019 16-inch MacBook Pro to a scaled resolution by default; the 2x native resolution was available in System Preferences as an option, but it wasn’t the default. 

Saw that in a 9to5 mac article. Maybe this issue was an accident by Apple just in the 2019 16" model? I suspect the only hope for SDL to handle this correctly would be to include model-specific hard-coded workarounds (which is probably justified).

But absent that, I think it's reasonable for us to offer an override type settings that lets the user provide surrogate values if their OS is feeding SDL bad data.

**Comment by johnnovak** [comment]
Indeed, it's a 2019 16" model... 😐 

<img width="303" alt="image" src="https://user-images.githubusercontent.com/698770/180182141-07586d4f-a9c1-4495-883a-a44fa10f11dc.png">

> But absent that, I think it's reasonable for us to offer an override type settings that lets the user provide surrogate values if their OS is feeding SDL bad data.

Yeah, maybe an optional `force` attribute after the `viewport_resolution` setting that bypasses the bounds check.

**Comment by kcgen** [comment]
> Indeed, it's a 2019 16" model... 😐

Oof 😢 ; makes sense why @Grounded0 didn't hit this during the hidpi PR testing.

Hmm; the resolution and scaling value (1.7x) is very specific -- maybe we can I can catch these one off issues and have a conf setting like "workaround_known_dpi_issues = true"?

**Comment by johnnovak** [comment]
Yeah that's all good and well to implement some workaround, but the SDL issue is still unaddressed, right? Meaning that `SDL_GetDisplayBounds` returns logical pixels (regardless of the scaling factor, whether 1.7x or 2.0x, or anything else), while the rest of the window sizing logic assumes physical pixels.

I'm guessing `viewport_resolution` hasn't been tested adequately tested by anyone on HighDPI displays, I see no other explanation.

**Comment by johnnovak** [comment]
As confirmed by @Grounded0, non-1.0x scaling ratios are just not handled correctly when setting an explicit `viewport_resolution`, *except* for the default "fit" mode, which works correctly.

So this issue is not specific to particular Mac models; as long as the scaling ratio is not 1.0x between logical window dimensions and resulting physical pixels, the `viewport_resolution` logic just won't work correctly on any OS. This is an SDL API limitation, and only workaround #2 in my top comment could remedy this.

**Comment by johnnovak** [comment]
> makes sense why @Grounded0 didn't hit this during the hidpi PR testing.

@Grounded0 confirmed he did not test `viewport_resolution` previously, that's why the issue hasn't surfaced earlier.

**Comment by kcgen** [comment]
Option 2 sounds perfect, especially that it uses SDL's interface into OpenGL instead of using OpenGL directly. 

This means that it should work even for configurations that disable OpenGL using `meson setup -Duse_opengl=false ...`

**Comment by GranMinigun** [comment]
`SDL_GetDisplayDPI` returns physical DPI. That is, the one reported by hardware / EDID. If it reported the actual DPI scale, then it'd be a matter of dividing that by 96 to get the scale. But alas.

And I really don't like the idea of introducing any of those hacks. It is most likely just an oversight on my side, and should be (hopefully) trivial to fix. Or maybe ugly, like the way DPI scaling is handled in pixel-perfect setup.
