### ISSUE TITLE
More consistent handling of enabling/disabling features

### ISSUE THREAD

**Issue by johnnovak** [dosbox-staging/dosbox-staging#1807]
## Consistent handling of enabling/disabling features

Currently, boolean flags in the config accept the following values:
- true, on, enabled, 1
- false, off, disabled, 0

This is a really nice way of handling flags, I fully approve. But when "toggle states" are included in a list of enum values (e.g. for `reverb` the values are `off, on, tiny, small, medium, large, huge`), we only accept whatever we included in the enums for "enabling" or "disabling" the feature (so only `on` and `off` in this case, but not `enabled` or `disabled`, for example).

Some examples to highlight the numerous inconsistencies with toggle flags in enum values:

- `sidmodel`: auto, 6581, 8580, **none**
- `pcspeaker`: discrete, impulse, **none**, **off**
- `mpu401`: intelligent, uart, **none**
- `cms_filter`: **on**, **off**
- `composite`: auto, **on**, **off**

The problem is that the user has to remember whether to use `none` or `off` for every single config param. For config params that accept enum values but also `on` and `off` (or `none`), it's confusing why you cannot just use `disabled` or `false` instead of say `none`, like you can with simple boolean toggles.

I'd say it would be better if we did the following cleanup across the board:

- Extend list of accepted "disabled" boolean values with `none`
- Introduce two helper functions to parse disabled and enabled values, respectively, e.g. `parseEnabledValue`, `parseDisabledValue`. These would use the same set of allowed boolean values for parsing, *minus* the numeric `0` and `1` values, because those could interfere with more complex config params that allow either string enums or numbers (e.g. `crossfeed`).
- Using the above two methods for parsing enums, the enabled/disabled values would be automatically aliased to the full set of allowed values.
- To keep the noise levels down in the descriptions, we should always just mentione *one* enum value that is the "most natural fit" for the feature (e.g. `off` for a filter setting, but `none` for the SID model.) 

## Invalid boolean values shouldn't enable features

Try the following in the DOS prompt:

```
gus = asdf
ps1audio = qwer
```

You'll get the "not a valid value" error in both cases, yet the audio interfaces will be enabled. Haven't tried all boolean flags, but probably many would exhibit the same behaviour. I'd say a no-op would be the best course of action, and it that's not possible, just using the default (which is "disabled" in these cases).

**Comment by kcgen** [comment]
Fully agree; this would be a significant quality of life improvement!
 I often configure games with only the audio devices they use, and sure enough, I often forget exactly how to disable some devices.

**Comment by johnnovak** [comment]
> Fully agree; this would be a significant quality of life improvement! I often configure games with only the audio devices they use, and sure enough, I often forget exactly how to disable some devices.

Yeah, I carefully considered when to use `none` and `off` for my own stuff, but even I forget about those details a week later and consistently use the wrong one, then find the correct one by trial and error 😅 The fact that incorrect names *enable* certain flags doesn't help either...

**Comment by johnnovak** [comment]
Consistent handling of boolean values across the board is addressed in this PR by @kcgen 
https://github.com/dosbox-staging/dosbox-staging/pull/2541
