### ISSUE TITLE
PPA Jammy Empty?

### ISSUE THREAD

**Issue by FalcoGer** [dosbox-staging/dosbox-staging#1819]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Different version than latest?

none

### What Operating System are you using?

Linux x86_64

### Whats your question and how can we help?

I have read your installation guide on https://dosbox-staging.github.io/downloads/linux/
However I am running on Ubuntu Mate 22.04, Jammy. I checked the [repository metadata](https://ppa.launchpadcontent.net/feignint/dosbox-staging/ubuntu/dists/jammy/main/binary-amd64/) and it's empty for Jammy/amd64.
Can you fix that?

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by FalcoGer** [comment]
I have tried pulling the focal fossa release, but
```text
sudo apt install dosbox-staging
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 dosbox-staging : Depends: libfluidsynth2 (>= 2.0.5) but it is not installable
```

**Comment by kcgen** [comment]
If you install `libfluidsynth-dev`, does that satisfy the dependency?

**Comment by FalcoGer** [comment]
I have built it from source fine. That's not the issue. The issue is that the apt repository is empty and I can't install it using the official method.

**Comment by kcgen** [comment]
Ok, thanks for confirming.

@FeignInt :arrow_up: 

The Staging project itself doesn't maintain repository packages, because we're not repository maintainers. It's up to those repo maintainers to integrate and keep their builds working.  

Can you open a ticket w/ Ubuntu's PPA team - so this can be tracked and fixed by them?

**Comment by FalcoGer** [comment]
I shall.
The issue with the libfluidsynth dependency is that's for the old ubuntu 20.04 repo, because I thought i might be able to get it to install if I provide that as the repository instead of the (empty) jammy one as a workaround. It didn't work is all. That that doesn't work isn't an issue.

**Comment by kcgen** [comment]
Thanks @FalcoGer!
