### ISSUE TITLE
SDL-backed PDCurses debugger is not compatible with OpenGL

### ISSUE THREAD

**Issue by kcgen** [dosbox-staging/dosbox-staging#1824]
Reproduce with steps:

1. **Setup a debugger build with OpenGL forced on:**

    ``` shell
    meson setup -Duse_opengl=true -Denable_debugger=normal \
        -Dunit_tests=disabled -Db_ndebug=true build/gl_debugger
    ```

2. **Confirm the debugger and OpenGL are both enabled:**

    ```
      Build Summary
        OpenGL support      : True
        ...
      User defined options
        b_ndebug            : true
        enable_debugger     : normal
        use_opengl          : true
    ```

3. **Build:**
   
    ``` shell
    meson compile -C build/gl_debugger
    ```

4. Launch the debugger build inside this package: [shamus.zip](https://github.com/dosbox-staging/dosbox-staging/files/9226836/shamus.zip)

On startup, the debugger window appears OK:

![2022-07-30_08-51](https://user-images.githubusercontent.com/1557255/181924939-b6c91247-3879-45b6-b8b2-69e079d830e8.png)

Tap F10 to step ahead by some instructions which triggers a GL video-mode change that impacts the debugger window:

![2022-07-30_08-51_1](https://user-images.githubusercontent.com/1557255/181924933-2e4ca0e1-6614-40b5-b33d-d391e4612d4c.png)

Here's the state of the debugger after the mode change:

![Screenshot from 2022-07-30 08-52-05](https://user-images.githubusercontent.com/1557255/181925018-00251858-3b22-4171-a588-b947c0748478.png)

What's interesting is that the debugger is still alive.

**Comment by kcgen** [comment]
**from @GranMinigun**
> Does OpenGL output break in debugger builds for you as well? I'll do more testing as needed, and if debugger is the only thing that makes OpenGL fall apart, then maybe I could find out why and where.

Thanks for your help, @GranMinigun.

**Comment by kklobe** [comment]
@kcgen any way you could revert 0dd5e9d3a9582e9bae142b3ac868abfeb9b47f3d and maybe confine it to Linux? OGL works fine for me on macOS and that's my default setup; now I can't use the debugger. 

Thanks!

**Comment by kcgen** [comment]
Definitely; will make that Linux-specific.

**Comment by kcgen** [comment]
@kklobe: fixed.

**Comment by kklobe** [comment]
does the recently-released SDL 2.24.0 make any difference here?

**Comment by kcgen** [comment]
> does the recently-released SDL 2.24.0 make any difference here?

Thanks for the reminder to retest this one, @kklobe.

Got a local build of SDL done (and confirmed latest):
```
Run-time dependency sdl2 found: YES 2.25.0
```

But runtime is still broken:

![2022-08-20_12-18](https://user-images.githubusercontent.com/1557255/185763006-f1aabeec-308a-4684-9bd8-0a951906d338.png)

**Comment by grapeli** [comment]
With SDL2-2.0.6 it's the same as long as we run with `SDL_FRAMEBUFFER_ACCELERATION=1` (currently the default).

I don't know of any software that uses PDCurses under Linux (with SDL2).

**Comment by kcgen** [comment]
@grapeli, you're a bisecting wizard! :mage_man: -- thank you.

Very interesting that the bug was introduced in SDL 2.0.6 (and hasn't been fixed since); just a couple weeks shy of 5 years now.

@kklobe just pushed branch `kk/debugger-no-highdpi-1` that disables hiDPI for the debugger's window, but alas it's not the culprit here either.  Also tried setting  `SDL_FRAMEBUFFER_ACCELERATION=0` with the latest SDL-from-source, but also to no avail.

**Comment by kcgen** [comment]
What I've now noticed is that on Starting `debug.com shamus`, simply moving my mouse into the window is enough to trigger the resolution degradation.

**Comment by grapeli** [comment]
The [sdltest](https://raw.githubusercontent.com/wmcbrine/PDCurses/master/sdl2/sdltest.c) program works fine under linux with PDCurses (master).

Does not work properly when built with the header files and the PDCurses library included with dosbox-staging.
`-I./dosbox-staging/src/libs/PDCurses ./dosbox-staging/build/src/libs/PDCurses/libpdcurses.a`

I wonder if it works properly under windows and macOS.

**Comment by kklobe** [comment]
> The [sdltest](https://raw.githubusercontent.com/wmcbrine/PDCurses/master/sdl2/sdltest.c) program works fine under linux with PDCurses (master).
> 
> Does not work properly when built with the header files and the PDCurses library included with dosbox-staging. `-I./dosbox-staging/src/libs/PDCurses ./dosbox-staging/build/src/libs/PDCurses/libpdcurses.a`
> 
> I wonder if it works properly under windows and macOS.

It shouldn't work, I had to rip out their `SDL_PollEvent` management and replace it with the custom queue due to `sdlmain.cpp` already handling SDL events.

**Comment by grapeli** [comment]
Dosbox-staging started like this.
`PDC_FONT=./9x15.bmp SDL_FRAMEBUFFER_ACCELERATION=1 ./dosbox`

https://user-images.githubusercontent.com/452325/185795989-bccdd68e-abeb-480a-ad95-20c679399083.mp4

There is nothing in the dosbox-staging window. The debug window will behave bizarrely.

With `PDC_FONT=./9x15.bmp SDL_FRAMEBUFFER_ACCELERATION=0 ./dosbox`.
Works fairly well. Although there are certainly some shortcomings.

The dosbox-staging window does not appear completely under wayland.
`SDL_VIDEODRIVER=wayland ./dosbox`
