### ISSUE TITLE
GUS repeating forever drum beat in Duke Nukem 3D

### ISSUE THREAD

**Issue by Mzed3D** [dosbox-staging/dosbox-staging#1827]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### What Operating System are you using?

Linux ARM (Raspberry Pi)

### If Other OS, please describe

Armbian Jammy 5.17

### Relevant hardware info

Odroid n2+ 

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Always on the first level of Duke Nukem 3D as soon as the drum beats start. The beat is repeated forever very fast. 

### Steps to reproduce the behaviour.

Just try Duke Nukem 3d with gravis ultrasound. The drum beats start few seconds after the beginning of the first level. 

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by kcgen** [comment]
Which GUS MIDI patches are you using?

**Comment by Mzed3D** [comment]
I tried with GUS 4.11 and Pro Patches Light 1.61 update, the error happens in both cases.

**Comment by Mzed3D** [comment]
And the Ultrasound settings in the conf files are the default ones, I just set to "true" the gus option and wrote the directory for the rom files. I also tried in the game setup to use soundblaster for the sound and gus for the music, then I tried gus for both sound and music but the error happens in any case.

**Comment by kcgen** [comment]
Unfortunately I can't reproduce it. Can you zip up your entire Duke 3D directory + dosbox conf + included ultrasnd, and share that?  Or let me know exactly how to setup the same configuration (links to archive.org, etc) to set this up.


I'm launch the `main` branch of DOSBox-Staging in a local Duke 3D 1.5 (Atomic Edition) directory tree like:

.
├── ***dosbox.conf**
├── cdrom
│   ├── atominst
│   │   └── ten
│   ├── dn1inst
│   ├── dn2inst
│   ├── dn3dinst
│   │   └── ten
│   └── support
├── duke3d
│   ├── **duke3d.cfg**
│   ├── gus
│   └── ten
└── **ultrasnd**

Here's my `dosbox.conf`, listed above (rename without the .txt extension): 
[dosbox.conf.txt](https://github.com/dosbox-staging/dosbox-staging/files/9229155/dosbox.conf.txt)

Here's my `duke3d.cfg`, listed above (renamed without the .txt extension): 
[duke3d.cfg.txt](https://github.com/dosbox-staging/dosbox-staging/files/9229168/duke3d.cfg.txt)

Here's the ultrasnd dir (as zip): [ultrasnd.zip](https://github.com/dosbox-staging/dosbox-staging/files/9229146/ultrasnd.zip)

The `conf` file disables all audio devices except for GUS, just to be extra sure that it the only thing being used.  You can run the mixer to prove it:

![Screenshot from 2022-07-31 08-12-23](https://user-images.githubusercontent.com/1557255/182033704-cc0ace0e-7058-424c-bb13-5a7b4914e8e0.png)

Here's a recording of it starting up:

https://user-images.githubusercontent.com/1557255/182033718-1c43e771-41f9-4066-9298-ed92b3909094.mp4

**Comment by kcgen** [comment]
Here's a user mentioning the repeating GUS drum issue using an actual GUS card:

https://www.vogons.org/viewtopic.php?p=361431#p361431

**Comment by Mzed3D** [comment]
I changed my gus files with yours and everything worked.. Which version are those files?

**Comment by kcgen** [comment]
It's a collection of the last updated revision of (most?) of Gracie's DOS tools/drivers. I believe from March 20, 1995 (according to the log). 

There's also some version info in the ini:

```text
  #==============================                            # Ver:     2.1                                             # Title:   ULTRASOUND Patch Library for Windows            # Purpose: Patch library information.                      # Modifed: 06/22/93 - #45 now TREMSTR.PAT        [JRS]     #                     HONKTONK.PAT now HONKY.PAT [JRS]
#          10/06/93 - You may now have multiple patch bank\s/libraries
#                      To do this you must define a bank a\s either                                                   #                      [Melodic Bank x]/[Drum Bank x] wher\e x is the number                                          #                      of the bank.
#                   - [Melodic Patches]/[Drum Patches] are\ kept for                                                  #                     compatibility with older software    #==============================                            [Ultrasound]                                               PatchDir=C:\ULTRASND\MIDI\                                                                                            [Melodic Bank 0]                                           BankName=UltraSound GM Melodic Bank                        PatchDir=C:\ULTRASND\MIDI\                                 0
```
