### ISSUE TITLE
DOSBox Staging hangs when trying to use encodings from EGA18.CPX (like code page 3848, for Brazil - ABICOMP encoding)

### ISSUE THREAD

**Issue by FeralChild64** [dosbox-staging/dosbox-staging#1866]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### What Operating System are you using?

Linux x86_64

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Emulator hangs when trying to set code page 3848 (ABICOMP). DOSBox-X suffers from exactly the same bug, https://github.com/joncampbell123/dosbox-x/issues/3681

### Steps to reproduce the behaviour.

Execute command inside the emulator:

`keyb br 3848`

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by kcgen** [comment]
> this particular one is smaller than the rest 

I wonder if CPX files (or the spec) requires an exact size? (we could check that and ignore/discard the results after parsing the file)

I checked the FreeDOS 1.3 Live CDROM, and EGA18.CPX's md5sum matches the one we have:

```
md5sum ./freedos/cpi/ega18.cpx
8cce89fd82d6a2c0c1de0252c7ae473f  ./freedos/cpi/ega18.cpx
```

**Comment by kcgen** [comment]
Will investigate the cpx parsing routine.

**Comment by Grounded0** [comment]
Connected ticket:
- #1882
