### ISSUE TITLE
RFE: IPX emulation: basic authentication

### ISSUE THREAD

**Issue by hpax** [dosbox-staging/dosbox-staging#1867]
I am the author of dosbox-ipxrelay (https://git.zytor.com/games/dosbox/ipxrelay.git/). One thing that has been bothering me for a very long time is that there is no form of authentication/access control in the DOSBOX IPX emulation protocol, even on the most rudimentary level.

The absolutely simplest thing would be to include a username and password in the UDP registration packet. Is it secure? Definitely not, but would at least provide a minimal protection from "any random user on the Internet".

I don't believe anything more than that is really needed, because for fancier setups that can involve browsing and setting up games, billing, and whatnot, it would be way easier and saner to handle that outside DOSBOX -- perhaps in a web browser -- and provide the user with a one-time token that can be used in place of the password.

For security beyond that, the connection itself would have to be secured; this would best be done by supporting operation over DTLS instead of plain UDP; there is no reason to reinvent the wheel.

**Comment by Burrito78** [comment]
That is out-of-scope. Secure a lower layer of your network if you need security instead of relying on hacky stuff like this.

**Comment by hpax** [comment]
It is OK if you still feel this is out of scope, but I would like to add one more motivation for this: it would make it very, very easy to support multiple virtual IPX networks (i.e. simultaneous games) on the same incoming UDP port. There just has to be some way to know what game the user wants to connect to.
