### ISSUE TITLE
PC_Jr Composite no longer working in 0.1153

### ISSUE THREAD

**Issue by Jkapp76** [dosbox-staging/dosbox-staging#1874]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

This works fine in the last version I downloaded 0.561
The latest version gives me only shades of blue when I hit F12 to enter composite mode with the game (Below the Root).
I'm not sure how long this has been broken, I haven't tried several versions.

The Reverb and Chorus sound nice though...

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Load Below the Root
2. Press F12
3.

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by kcgen** [comment]
I'm using the current main branch (https://dosbox-staging.github.io/downloads/devel/), and can tap `F12` to scroll through composite modes: off/auto/on - 

![2022-08-21_14-18](https://user-images.githubusercontent.com/1557255/185811359-4c1af792-1ebf-46f8-a6c3-6f60765aea64.png)

![2022-08-21_14-19](https://user-images.githubusercontent.com/1557255/185811358-cb0a98c7-dd7f-49fc-a90e-992867c43176.png)

**Comment by Jkapp76** [comment]
This works fine for me with other games. And with CGA mode. By PCjr mode, and below the root the colors are blue.

**Comment by kcgen** [comment]
Thanks @Jkapp76 : for my own understanding, the baseline pcjr composite colors in btroot should be brownish?

This will help us bisect where the palette changed.

**Comment by Jkapp76** [comment]
![20220821_184559](https://user-images.githubusercontent.com/89743985/185814035-67249f49-489d-4118-93bc-2c77836d93ab.jpg)

Older build...

**Comment by Jkapp76** [comment]
![20220821_184658](https://user-images.githubusercontent.com/89743985/185814047-72ef9161-1b31-496f-94ec-6d1f4a1d1cf3.jpg)

Newest build...

**Comment by Jkapp76** [comment]
I read in the change log about some CGA 16 color changes. Maybe these have been wrongly applied to the PCjr?

**Comment by kcgen** [comment]
Here's my PCjr conf for the game:

```ini
[sdl]
windowresolution = small
output = opengl

[dosbox]
# machine=tandy
machine=pcjr
memsize=1
startup_verbosity = quiet

[speaker]
pcspeaker = none
tandy = on
lpt_dac = none
ps1audio = false

[render]
aspect=true

[cpu]
core=dynamic
cycles=300

[sblaster]
sbtype = none
oplmode = none

[joystick]
joysticktype = disabled

[dos]
xms = false
ems = false
umb = false

[composite]
composite  = on
era        = auto

[autoexec]
@echo off
mount c . > NUL
c:
loader
```

PCjr screenshot:

![Screenshot from 2022-08-21 22-41-54](https://user-images.githubusercontent.com/1557255/185847996-0216daea-90ea-4287-918f-94734d7f9021.png)


And when I switch to `machine = tandy`, I get:

![Screenshot from 2022-08-21 22-42-41](https://user-images.githubusercontent.com/1557255/185847965-4639c778-bdbc-4a64-9a2e-a3fee18b0406.png)


Can you try placing the above `dosbox.conf` inside the game directory, and launch from within there with `/path/to/dosbox -noprimaryconf`?

Your console log should only report `CONFIG: ` reading the local conf, and no other conf files.

``` text
2022-08-21 22:52:11.129 | dosbox-staging version 0.79.0-alpha-1166-gb0ff7b82d
2022-08-21 22:52:11.129 | ---
2022-08-21 22:52:11.129 | LOG: Loguru version 2.1.0 initialized
2022-08-21 22:52:11.223 | SDL: version 2.0.18 initialized (x11 video and pulseaudio audio)
2022-08-21 22:52:11.224 | CONFIG: Loaded local conf file dosbox.conf
2022-08-21 22:52:11.224 | RENDER: Using GLSL shader 'sharp'
2022-08-21 22:52:11.225 | DISPLAY: Initialized 1440x1080 window-mode using Bilinear scaling on 2160p display-0
2022-08-21 22:52:11.251 | OPENGL: Vendor: Intel
2022-08-21 22:52:11.252 | OPENGL: Version: 4.6 (Compatibility Profile) Mesa 22.3.0-devel (git-1d521a5 2022-08-20 jammy-oibaf-ppa)
2022-08-21 22:52:11.252 | OPENGL: GLSL version: 4.60
```

**Comment by Jkapp76** [comment]
![20220822_111138](https://user-images.githubusercontent.com/89743985/185956151-7992dc83-4e2f-460e-adb1-6b218ed1ced4.jpg)

Here it is using your conf

**Comment by kcgen** [comment]
Can you scroll up in the console to show the first bit of logging?
```
2022-08-21 22:52:11.129 | dosbox-staging version 0.79.0-alpha-1166-gb0ff7b82d
2022-08-21 22:52:11.129 | ---
2022-08-21 22:52:11.129 | LOG: Loguru version 2.1.0 initialized
2022-08-21 22:52:11.223 | SDL: version 2.0.18 initialized (x11 video and pulseaudio audio)
2022-08-21 22:52:11.224 | CONFIG: Loaded local conf file dosbox.conf
2022-08-21 22:52:11.224 | RENDER: Using GLSL shader 'sharp'
```

**Comment by Jkapp76** [comment]
![20220822_112057](https://user-images.githubusercontent.com/89743985/185958010-0a1da834-be85-4632-9409-fb32c9db09b4.jpg)

**Comment by kcgen** [comment]
Thanks @Jkapp76 - all looks good.  Thanks for catching this!

**Comment by Jkapp76** [comment]
Are you able to see any problem?
I can test with older versions to determine where the change happened if needed.

**Comment by kcgen** [comment]
Thanks for the offer to help, @Jkapp76.
 
Was able to reproduce it in the gcc release builds (clang and msvc were ok).

When you have a chance, here's build 1173 from the PR branch:  https://github.com/dosbox-staging/dosbox-staging/actions/runs/2908918085

Curious if that solves it. Any other general composite check (CGA, Tandy, etc) would be much appreciated! Thank you, @Jkapp76.

**Comment by Jkapp76** [comment]
I gave a quick test of just Below the Root. Loaded and played perfectly.

**Comment by Jkapp76** [comment]
I loaded some more games. Jumpman composite. Load Runner. ZorkQuest. Hulk.

All look perfect.

Zork Quest has always failed on PCJr, and still does, but I tried again anyway.

**Comment by kcgen** [comment]
Thanks for the careful testing and feedback, @Jkapp76. 

I know booter games are one of your specialties, and not many people might know the optimal settings (cycles, preferred machine type, composite settings to adjust colors, etc). 

If you have any settings you could share, they would no doubt let more user enjoy these game the way they were meant to be played! (And by share, it could be any mechanism.. here, on the wiki, or your own blog or other sites). 

Thanks again, @Jkapp76

**Comment by Jkapp76** [comment]
There's a new issue.
I tried Below the Root again. Most of the sound effects are missing now.
The sound of the guy walking up the vines and opening his shuba-cape. no sound.

At first I thought it was my playing with the new reverb and chorus. But I shut that off and the sounds are still gone.
I loaded the older build and the sound is all there.

**Comment by kcgen** [comment]
The effects are played through the PC speaker, try:

``` ini
[speaker]
pcspeaker = impulse
```

**Comment by kcgen** [comment]
At the dos prompt, run `config -wc` to write a complete conf. You'll see the options for pcspeaker: you can change its type and toggle its filter. By setting `discrete` and turning off its filter, you can get similar sounds as 0.78 and DOSBox SVN.

**Comment by Jkapp76** [comment]
Yes, the filter option gets the sound how I like it.

I can dig up some settings to share for the old booter games, composite games and ancient stuff. I could maybe make a list of games and settings.

Like, 

Below the root (machine=PCJr, cycles 244, composite=old)    Shader=crt-hyllian.glsl shader?

Something like this?

I can share the images and things too if that's okay.

**Comment by kcgen** [comment]
Sounds perfect! And those settings are perfectly portable across to all the dosbox's running on many different platforms (even the web variant used on archive.org), so this will benefit the entire community.
