### ISSUE TITLE
Audio 'pop' artifact is heard on CD audio track changes.

### ISSUE THREAD

**Issue by Burrito78** [dosbox-staging/dosbox-staging#1893]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Different version than latest?

DEV

### What Operating System are you using?

Mac OS

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

When a game changes between CD audio tracks, a distracting 'pop' sound can be heard in the latest DEV version.

The problem isn't heard on v0.78.1.

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Start a game with CD audio tracks. (I used Monkey Island Enhanced CD).
2. Observe in the opening cutscenes between track changes the artifact.
3. Go in and out of the Scumm Bar to easily hear the problem.

### Your configuration

```ini
default
```

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by GXTX** [comment]
Did Lucas Arts give permission to distribute their game like that? I'm now wondering the orgs thoughts on piracy in issue comments.

**Comment by Grounded0** [comment]
Archive.org link has been removed.

**Comment by kcgen** [comment]
> Did Lucas Arts give permission to distribute their game like that?

archive.org operates under similar laws as a library, which give them exclusions around copyright laws for purposes that are deemed to benefit society as a whole. One of those benefits is the cultural preservation of software and video games.

Specifically, the library of congress grants exclusions to distribute old software and video games for the purposes of cultural preservation.

Therefore, archive.org has legal protection to share Lucas Arts' DOS games without the need to acquire their explicit permission for scholarship and research purposes that further the cultural preservation of software and video games.

>  I'm now wondering the orgs thoughts on piracy in issue comments.

Do you feel that the communication of archive.org materials specifically between members of an emulation project putting time in to investigate, discuss, and fix emulation accuracy for the purposes of cultural preservation of video games is a violation of their (terms of use)[https://archive.org/about/terms.php] granted to myself and @Burrito78 who filled the issue?

I believe /our/ use of said material meets the letter of terms of use exactly. 

Please keep in mind that the terms of user are applied individually. If you, GCTX, are _not_ involved in researching or preserving the emulation accuracy of this specific work, then you would be violating archive.org's terms of use: the risk falls on your shoulders, not ours, as we are cleared under the terms of use.

**Comment by GXTX** [comment]
> archive.org operates under similar laws as a library, which grant exclusions to copyright laws

The user had linked to the user upload section of IA. We can both surely agree that IA sponsored operations such as book distribution, and the way back machine are beneficial, and legal.

The user upload section is something else entirely. We see items locked down or disabled 'often' due to complains from their respective copyright holders either by locking them down to IA registered members only (and logged in), or having them be completely disabled for download. If what were are claiming were true they would not have or need these types of protections on the user upload section.

I was blocked by Jason Scott bringing up similar things, I truly believe user upload content should be screened. You and I both know there's things that really shouldn't be publicity available such as stolen source code, stolen secrets, etc being uploaded every day... on the user upload section.

**Comment by Grounded0** [comment]
We're trying to find out if there is a bug in our CD-DA subsystem or not. Please stop polluting this ticket further.

**Comment by kcgen** [comment]
Members of the DOSBox Staging team are using archive.org in compliance with its terms of service. 

But you're now bringing up ToS violations unrelated to the issue at hand.

Any public carrier service may be used by used to break the law: Gmail is often used by corrupt politicians to discuss topics that they want to keep off public record, which is illegal and harms citizens of those nations. Are we going to solve that here, too?

The volunteers on DOSBox Staging team have neither the responsibility nor authority to address use cases that violate archive.org's terms of service.

Please raise those issues with the the groups who are tasked with addressing those violations.

**Comment by kcgen** [comment]
Bisected to 2eae4273b plus using `[mixer] rate = 48000`:
 - `git checkout 2eae4273b^` does not produce the pop
 - `git checkout 2eae4273b^` has the pop

When `rate = 44100`, the speex resampler is inactivate, and `main` will not pop.

Need to figure out if/how the speex resampler is being affected by the CDDA transitions.

**Comment by Burrito78** [comment]
The issue is gone with the [kc/cdda-pop-1](https://github.com/dosbox-staging/dosbox-staging/tree/kc/cdda-pop-1) build.

Also while running with default 'rate' setting. I expected to have to change 'rate = 44100' for it to be free of pops but i didn't change anything.

**Comment by Grounded0** [comment]
Connected ticket:

- #1894
