### ISSUE TITLE
Audio issues with high polling rate mice when moving the cursor outside the active DOSBox window

### ISSUE THREAD

**Issue by Burrito78** [dosbox-staging/dosbox-staging#1897]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Different version than latest?

DEV

### What Operating System are you using?

Mac OS

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

The CD-Audio music crackles, stutters and slows down when a mouse (mine is a Logitech G305) is running at high polling rate (1000 Hz). Reducing the polling rate to 125 Hz (lowest setting) fixes the issue.

I've used Monkey Island Enhanced CD version to reproduce the problem.

The issue happens with latest DEV and 0.78.1.

It's the worst when moving the mouse over a Safari window open in parallel or when moving it inside the macOS dock.

![Bildschirmfoto 2022-09-02 um 14 44 23](https://user-images.githubusercontent.com/61995128/188149715-83ea6393-9b7b-426b-8813-e18d4221052e.png)

Activity monitor doesn't show a very high CPU load when the issue happens. Also log is showing no errors.

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Open Monkey Island CD and Safari in windows side by side
2. Run your mouse at 1000 Hz refresh rate.
3. Move the mouse between windows.
4. Observe crackling, stutters and slowdowns of the music.

### Your configuration

```ini
default
```

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by Grounded0** [comment]
When you move mouse rapidly open up Activity Monitor.app and it's CPU tab... How much the total CPU load is on the system then?

**Comment by kcgen** [comment]
Thanks, @Burrito78.

I don't have a 1000 Hz mouse, so unfortunately can't reproduce it. 

Does it also appen when using FM-based music music? The difference is CDDA depends on host disk IO reads to service the stream (although I would assume most of those data blocks reside in cache), but FM music is entirely software generated without any disk IO. 

DOSBox SVN already includes event throttling specifically for macos, however I suspect the other mac apps are as yielding.

**Comment by kcgen** [comment]
418 users have clicked the "me too" button on Big She's high refresh mouse lag issue: https://discussions.apple.com/thread/252047056?page=2

Users report that not only so all applications in the background slowdown dramatically, but Bluetooth devices can disconnect too. 

This seems like an IO / event starvation problem.

**Comment by Burrito78** [comment]
The problem is also happening on macOS Catalina. The poster on the Apple Community post said it never happened to him with Catalina.

Also, the issue happens with FM audio (Monkey Islands default adlib audio). It's the same crackle so it has nothing to do with CD audio specifically (changed the title).

DOSBox stays in the foreground while the problem occurs, its only that the cursor is moved outside the window.

**Comment by kcgen** [comment]
> Also, the issue happens with FM audio (Monkey Islands default adlib audio). It's the same crackle so it has nothing to do with CD audio specifically (changed the title).

Thanks :+1: 

> its only that the cursor is moved outside the window.

If you set `[sdl] capture_mouse = onstart middlerelease`, does it prevent it?

**Comment by Burrito78** [comment]
`[sdl] capture_mouse = onstart middlerelease` on normal system load (Safari, Discord are open but in the background) the issue is still there. It crackles way less often but still does it from time to time when moving the mouse normally, even when the mouse is captured.

Only when i close all open apps, then its not crackling anymore. But when i open Discord in the background it goes completely crazy (again, with captured mouse and slight mouse movement).

**Comment by kcgen** [comment]
Darn; this really seems like the Big Sir scheduler is letting applications starve. Curious if cranking up the `[mixer]`'s prebuffer and/or blocksize can help "fill the gaps" across the starvation periods.

**Comment by kklobe** [comment]
not seeing any issues here (macOS 12.5.1 / M1 MacBook Pro), tried with single and dual monitors setup, windows on different monitors, startup up apps while game is running. Logitech G502 w/latest G-HUB:

![unknown](https://user-images.githubusercontent.com/541026/188684145-f7845016-68ab-40b2-9c8f-939bd9660a97.png)

**Comment by Burrito78** [comment]
According to @kklobe's findings, the problem is fixed in current macOS versions.
Reference: https://discord.com/channels/514567252864008206/852376220117237840/1016721507277357056

@kcgen We can close this for the time being, if you have no objections!

Thanks for the help @kklobe!
