### ISSUE TITLE
Monkey Island crashes Staging on macOS Big Sur (11.6) when `sbtype = gb`

### ISSUE THREAD

**Issue by Burrito78** [dosbox-staging/dosbox-staging#1898]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Different version than latest?

DEV

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

When configuring `sbtype = gb`(Gameblaster) in the config file and starting Monkey Island (VGA EN) it crashes DOSBox Staging.

The issue doesn't happen in macOS Catalina.
The issue doesn't happen in DOSBox Staging 0.78.1, Monkey Island falls back to PC Speaker there.

macOS crash log: https://pastebin.com/Hm1RGFcJ

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Set `sbtype = gb` in dosbox-staging.conf. 
2. Launch Monkey Island without parameters
4. Observe crash and crash report.

### Your configuration

```ini
sbtype = gb
```

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by kcgen** [comment]
@Burrito78 , I can't reproduce this on Linux or macOS ARM M1 (11.6.8)

I'm launching `dosbox -noprimaryconf` (to force the default config), plus a local `dosbox.conf` with only `[sblaster] sbtype = gb`, and launching `monkey.exe` directly.

It falls back and plays music via the PC Speaker.
I also tried `pcspeaker = none`, `impulse`, but also wasn't able to get it to crash.

I also tried release, debug, ASAN, and USAN builds.

@johnnovak , @Grounded0 - can you reproduce it on your x86-based MacOS 11.x systems?

**Comment by Grounded0** [comment]
Let me test this 👍

**Comment by Grounded0** [comment]
GameBlaster works with Monkey Island. Should it sound like a really fancy multivoice PC speaker?

**Comment by Burrito78** [comment]
Yes! Good description.

If the music starts on the Lucasfilm Games logo, you are hearing SB/GB.
If the music starts at the Monkey Island title screen, you are hearing PC speaker.

I also can't reproduce this on Catalina, only happens for me on Big Sur.

Also note as i wrote above to start Monkey Island using `monkey` without command line parameters.

**Comment by kcgen** [comment]
> If it works, it will start with the copy protection and after that will play GB or SPEAKER music.

@Burrito78 , do you have a link to archive.org for your version? Mine does not go into the copy protection, so might be why I'm not reproducing the crash.

**Comment by Burrito78** [comment]
Afaik, you can use any version. Copy protection should make no difference. But i can link/upload a version that crashes for me later.

**Comment by Grounded0** [comment]
I tested EGA version that has been cracked.

**Comment by Burrito78** [comment]
Can't reproduce anymore with latest DEV version! Closing the issue for now.
