### ISSUE TITLE
Sign the DOSBox Staging app for an easier, quicker and less scary first program start

### ISSUE THREAD

**Issue by Burrito78** [dosbox-staging/dosbox-staging#1901]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### What Operating System are you using?

Mac OS

### Is your feature request related to a problem? Please describe.

Since the DOSBox Staging app isn't currently signed by an Apple Developer account, users that download the app have to jump to a few more hoops to get it running and might be scared by all the warnings that are popping up.

This will only get worse with newer versions of macOS.

This comparison is valid if the user already has allowed apps downloaded from the internet in security settings:
<img width="780" alt="Screenshot 2022-09-04 at 12 44 54" src="https://user-images.githubusercontent.com/61995128/188309689-f0a244ee-0b84-4afa-ab03-53bcbad48288.png">

DOSBox Staging
1. Double click app
2. Click 'OK'
3. Right click app
4. Click 'Open'
5. Click 'Open' again

![Open DOSBox Staging first start](https://user-images.githubusercontent.com/61995128/188309768-3a99c3a8-2de5-4518-91ad-98bb798c9e0f.gif)

Vanilla DOSBox
1. Double click app
2. Click 'Open'

![Open DOSBox vanilla first start](https://user-images.githubusercontent.com/61995128/188309786-7fe71d5b-7bea-4988-b35e-85c61a0746e3.gif)

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by Grounded0** [comment]
Privilege to sign apps costs 99 USD per year from Apple. If you boost your yearly contribution to 100 USD per year we could earmark your contribution to pay for this fee. Personally i'm opposed that my donations would be used to bankroll 2 Trillion+ USD corporation to mint more money.

**Comment by Burrito78** [comment]
Maybe someone with a developer account would be willing to sign it for us, @kcgen wanted to make a connection with one or two guys i know of.

**Comment by Burrito78** [comment]
@dreamer My donation of 10$/mo would already pay for this, could you please consider signing Staging in your name?

**Comment by dreamer** [comment]
@Burrito78 Yes. I need to learn how to do it anyway.

**Comment by Burrito78** [comment]
#2426 is depending on this.

**Comment by Burrito78** [comment]
If possible, would be nice to have for 0.81 @dreamer!

**Comment by dreamer** [comment]
@Burrito78 I just ordered a Mac Mini, ETA this Monday, so I'll start working on it next week.

**Comment by Grounded0** [comment]
If @dreamer starts signing this i'm okay that my donations are used to bankroll this.

**Comment by johnnovak** [comment]
> Fellow macOS users: Time to step up with donations. If you can afford 4,000 USD MacBook Pro you can afford to donate 5 USD per month since we bring you 10,000 games on DOS and Windows 3.x.

Maybe start these announcement on Mastodon so they reach more people 😎

**Comment by Grounded0** [comment]
@johnnovak 

That's quite gauche but people are quite tone deaf so maybe necessary. 😁

**Comment by johnnovak** [comment]
> @johnnovak
> 
> That's quite gauche but people are quite tone deaf so maybe necessary. 😁

You know the joke when the bear has a death-list of animals he intends to kill, then the rabbit walks up to him:

- Hey bear, am I on your death-list?
- Yes.
- Can you strike me off?
- No problem, rabbit [and he does so]

Quite often, you just need to ask 😏 (I'm experiencing this in real life all the time, you need to prod people a bit)

**Comment by Burrito78** [comment]
@dreamer It would be very nice if we could get this done for 0.81, maybe you could take another look into this.

**Comment by Grounded0** [comment]
Seems like people are content to do couple extra clicks per year for a good macOS experience. 🙂

This also saves us 99 USD per year going to big corporation money printer.

**Comment by Grounded0** [comment]
Since we're currently notarising our releases this ticket can be closed in my opinion. I'll give it 12 hours or so.
