### ISSUE TITLE
Monkey Island PC Speaker missing notes

### ISSUE THREAD

**Issue by Burrito78** [dosbox-staging/dosbox-staging#1906]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Different version than latest?

DEV

### What Operating System are you using?

Mac OS

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

During the "Chapter One" screen of the beginning of Monkey Island there is a short song heard that is called 'Interlude'.
There are notes missing in that song on DOSBox Staging that are heard on a real hardware recording.

![Bildschirmfoto 2022-09-06 um 09 47 22](https://user-images.githubusercontent.com/61995128/188577426-11da94e1-1e0e-426e-a6c7-f9d9700e3512.png)

![Bildschirmfoto 2022-09-06 um 09 39 48](https://user-images.githubusercontent.com/61995128/188577463-10af8dca-36a7-49ee-aab7-e0bfea2b291a.png)

### Audio Samples:
[3 audio samples.zip](https://github.com/dosbox-staging/dosbox-staging/files/9494469/3.audio.samples.zip)

Source of the hardware recording: https://www.zeitgestalten.org/somi_monophony.html

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Launch Monkey Island EN VGA on DOSBox Staging with `monkey i` to select internal speaker.
2. Record using CTRL/CMD+F6.
3. Compare the recorded file to the hardware recording.

### Your configuration

```ini
default
```

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by Burrito78** [comment]
The issue probably happens on all tracks of the soundtrack. I just selected the second track of the game because i heard it there initially and it's easy to reproduce.

**Comment by kcgen** [comment]
Isolated the issue to commit cae58040ce63ddd2929c9e9eaf0ac719de763714
When I revert that, I get this note back, however Paratrooper then no longer creates the buzz. Still looking into how to solve this.
