### ISSUE TITLE
CPU max 100% being CPU thread load 90% is outdated

### ISSUE THREAD

**Issue by Grounded0** [dosbox-staging/dosbox-staging#1913]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### What Operating System are you using?

Mac OS

### Relevant hardware info

2017 15" MacBook Pro with Radeon Pro 560

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

DOSBox Staging still uses outdated model of issuing load to thread it runs on. Current model actually issues 90% load on the thread with CPU max 100% while 95% load is being issued with CPU max 105%.

This is based on decision made 20 years ago as single thread computers needed more leeway on top of their single thread for background operations to run smoothly. Way to fix this is by making CPU max 100% issue 95% load on the thread and CPU max 105% issue 98% load on the thread that is more suitable to multicore and multithread CPUs of this era.

You can test how flawlessly thread load 95% runs by setting CPU max at 105%. I flagged this as a bug because its misinforming the user that they're maxed out while they're not.

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by Burrito78** [comment]
Yes, agreed. If 105% has no downsides for the platforms we support then it should be the new 100%.

Should be a 0.80 change though. We should now focus on features freeze and bug hunting/translation in the next few days.

**Comment by Grounded0** [comment]
Yeah we're in a code freeze for 0.79.

**Comment by johnnovak** [comment]
I wonder if we could stop this 105% silliness altogether and just treat the percentage values literally (e.g. 100% would mean 100% thread utilisation, no matter what).

**Comment by Burrito78** [comment]
@kcgen Maybe a candidate to implement for 0.81 RC and see how it goes?

**Comment by johnnovak** [comment]
Related: how about not defaulting to max cycles in protected mode? It's a cause for way too many problems. I'd rather default to a roughly 486 DX2/66 equivalent speed which is probably the best overall fit for 90s DOS games when protected mode usage became prevalent. So say 20-30k cycles would be a good starting point instead of max. Maybe we could use your fine-tuned per game configs for the minimum viable cycles value as a guide @kcgen?

**Comment by MasterO2** [comment]
https://dosbox-x.com/wiki/Guide%3ACPU-settings-in-DOSBox%E2%80%90X#_cycles

Scroll down that page for a chart of CPU cycles.

**Comment by Grounded0** [comment]
It's a fairly easy change and no one can't come up with rationale why this shouldn't be done. 😩

**Comment by johnnovak** [comment]
Make it happen 😎 100% is 100%, and you can't go up to 105%.

**Comment by Grounded0** [comment]
`dosbox.cpp`:

```
		/* ratio we are aiming for is around 90% usage*/
		int32_t ratio = static_cast<int32_t>(
		        (ticksScheduled * (CPU_CyclePercUsed * 90 * 1024 / 100 / 100)) /
		        ticksDone);
```

Here's your wrong 2004 era assumption. How much lower this fruit must be to be picked up?

**Comment by Grounded0** [comment]
@kcgen ⬆️

**Comment by Grounded0** [comment]
We could still retain 105% value but make it 97% to squeeze couple extra percent of performance from high performance machines.

**Comment by johnnovak** [comment]
> `dosbox.cpp` line 229 onwards:
> 
> ```
> 		/* ratio we are aiming for is around 90% usage*/
> 		int32_t ratio = static_cast<int32_t>(
> 		        (ticksScheduled * (CPU_CyclePercUsed * 90 * 1024 / 100 / 100)) /
> 		        ticksDone);
> ```
> 
> Here's your wrong 2004 era assumption. How much lower hanging this fruit must be in order to be picked?

There's more; search for "105" in cpu.ccp 😄

**Comment by shermp** [comment]
Honestly, I still think 90% is a good target. Allows for some overhead in case some background program decides to use a bit of CPU out of the blue.

Although if you want to make this change, I'd perhaps suggest making the default setting 90%.

**Comment by Grounded0** [comment]
```
if (CPU_CyclePercUsed>105) CPU_CyclePercUsed=105;
```

We could bump this to 107 for real balls to the wall setting.

**Comment by johnnovak** [comment]
> Honestly, I still think 90% is a good target. Allows for some overhead in case some background program decides to use a bit of CPU out of the blue.
> 
> Although if you want to make this change, I'd perhaps suggest making the default setting 90%.

100% is 100%. "Renaming" 90% to 100%, then introducing 105% that aliases to 100% is just stupid.

> Allows for some overhead in case some background program decides to use a bit of CPU out of the blue.

Everybody has a minimum of 4 or 6 physical cores these days, and often twice as many logical cores. The Intel Core 2 line was released in 2006, and pretty much nobody has been using single-core CPUs since about 2008 or so. So any background programs will naturally use any of the remaining 4+ physical cores.
