### ISSUE TITLE
Make the phrase "local directory" in the title screen translatable.

### ISSUE THREAD

**Issue by Burrito78** [dosbox-staging/dosbox-staging#1922]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### What Operating System are you using?

Mac OS

### Is your feature request related to a problem? Please describe.

There is a string after startup regarding mounting that isn't translatable.

### Describe the solution you'd like

Make it translatable.

### Add any other context or screenshots about the feature request here.

![Bildschirmfoto 2022-09-13 um 09 28 31](https://user-images.githubusercontent.com/61995128/189838814-1e91cc60-a6c4-4fad-9e9e-427bc4bbf21c.png)

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by Kappa971** [comment]
In fact I don't understand why it isn't present in `:PROGRAM_MOUNT_STATUS_2`. 
Perhaps it was inherited from DOSBox 0.74

**Comment by kcgen** [comment]
Fixing this is a bit more involved than most messages.

When a drive / ISO / floppy image is mounted in DOSBox, an info-record is created and populated with various info about the mounted object.

One of those bits of info is the type of mount, in this case, "local directory" indicates that its a local directory and not one of the image types.

It's that chunk of the info record that's printed here, in the screenshot above.

In other parts of the code involving mounted objects, it checks if the mount is an directory or an image-type.  It does so by actually looking at this string here: _"Does this info record's string say 'local directory'? If yes: do X, if no: do Y."_

So fixing this will involve dropping the approach of storing the mount type as a string, and replacing it with an enumeration - and from there, we can use `MSG_Get("MOUNT_TYPE_LOCAL_DIRECTORY")` for the matching mount type enumeration.

I've tagged this for 0.80; I think it's too much for 0.79.

**Comment by Burrito78** [comment]
Yes, of course 0.80 is absolutely fine. Didn't mean that this has to go in quick, it's a long standing issue.
