### ISSUE TITLE
Jazz Jackrabbit's sprite flickering.

### ISSUE THREAD

**Issue by KainXVIII** [dosbox-staging/dosbox-staging#1941]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### What Operating System are you using?

Windows 10

### Relevant hardware info

i5-3570, gtx 970

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

GoG version of Jack Rabbit, main protagonist (Jazz itself) sprite is constantly flickering when running/jumping. Default dosbox config, tried vsync on and off - does not help.

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Run the game
2. Jump on first jump-pad in the first level for example and see the flickering.

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by Burrito78** [comment]
Just tried this with my floppy version and the flicker is there in 0.78.1 and 0.79.

I just thought the game was like that, but on closer inspection it looks more like an error.

Here a user says its normal with this game, but could be a vsync/60Hz issue:
https://www.gog.com/forum/jazz_jackrabbit/jazz_jackrabbit_flickering_issues

I couldn't get it to run in vanilla, it always asks me to set up my soundcard.

**Comment by KainXVIII** [comment]
> I couldn't get it to run in vanilla, it always asks me to set up my soundcard.

Seems like this is normal behavior even on CRT display, if eyes does not deceive me. Bummer!
https://youtu.be/92olhbB3KKM?t=637 (timestamped LGR video)

**Comment by Burrito78** [comment]
Yes, its the same flicker in LGR's video that i've seen in Staging. Sorry, but that seems to be how the game is originally.

@kcgen Do you have another idea or do you want to close this issue?

**Comment by kcgen** [comment]
Also happens in Holiday Hare: :file_folder:  [jazz_jackrabbit_holiday_hare.zip](https://github.com/dosbox-staging/dosbox-staging/files/9600753/jazz_jackrabbit_holiday_hare.zip)

In this 23 second capture (~1400 frames) at 1:1 frame rate (59.71 fps):

[jazz_002-vp8.webm](https://user-images.githubusercontent.com/1557255/191065810-09a6a93d-e1b1-4fce-8e74-9b056eb85af1.webm)

I was able to catch one "blink-out", during the first jump:

Frame T-1:

![Screenshot from 2022-09-19 09-25-17](https://user-images.githubusercontent.com/1557255/191066121-7fc05d3d-14d8-4556-a7d5-ee4afa73ca29.png)

Frame T-0. Blink-out:

![Screenshot from 2022-09-19 09-25-22](https://user-images.githubusercontent.com/1557255/191066144-365e2b83-4fc9-4884-a940-f9276f73784f.png)

DOSBox shows the frame-buffer's flat memory region; it's the game that draws to it (however complex or simple it might be). 

So in terms of the video handling side, it would be impossible for DOSBox's renderer and SDL output chain to remove a subset (and additionally redraw the game's "background": notice his knee occludes part of the pink block in the prior frame, which is fully drawn here when Jazz is gone).

Yes: we can have frame tearing, stuttering, and lots of problems, but this definitely looks "game-side" to me. 

(to play devils advocate: the the logic that leads the game to decide to draw Jazz (or not to draw him) might be lead astray, if it's doing some floating point math and the emulated FPU rounds digits slightly differently than hardware.. but this is highly unlikely, especially if hardware also shows the blink-outs).  

Frame T+1:

![Screenshot from 2022-09-19 09-25-27](https://user-images.githubusercontent.com/1557255/191066166-21ac8b27-738a-4a95-bf1f-c5851e8b2014.png)

All other ~1379 frames are unaffected.
