### ISSUE TITLE
Need help setting custom CGA colors

### ISSUE THREAD

**Issue by Jkapp76** [dosbox-staging/dosbox-staging#1942]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Whats your question and how can we help?

I've been trying to get DOSBox to match my old CGA PC and can't figure out how to modify the CGA palete.

The red is what bothers me the most. Castle Wolfenstein is MUCH darker red on the real hardware. The blue seems a bit light too, but not as noticable as the red. 

Wheel of fortune 2nd edition also has the deep red on true hardware and its a pale pinkish red on DOSBox. 

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by johnnovak** [comment]
As per our discussion with @Jkapp76, the issue can be closed (he just needed a little guidance on how to use the feature).
