### ISSUE TITLE
DSO missing from commandline for libpcre

### ISSUE THREAD

**Issue by silverhikari** [dosbox-staging/dosbox-staging#1943]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### What Operating System are you using?

Linux x86_64

### If Other OS, please describe

Manjaro

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

when building the latest version, the build fails with "/usr/lib/libpcre.so.1: error adding symbols: DSO missing from command line", i have checked that pcre is installed, and that the file in lib does exist with the correct file name.

### Steps to reproduce the behaviour.

Explain how to reproduce
1. download tar.gz of the latest version
2. unpack and run meson setup --prefix /usr build
3. build with meson compile -C build

### Provide a Log

```text
https://paste.ee/p/ru1hi
```

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by kcgen** [comment]
try with shared libraries: 

`meson setup -Ddefault_library=shared --prefix /usr build`

**Comment by silverhikari** [comment]
yep, adding that fixed it
