### ISSUE TITLE
Portable .conf file

### ISSUE THREAD

**Issue by SpitFire-666** [dosbox-staging/dosbox-staging#1948]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### What Operating System are you using?

Windows 7

### Is your feature request related to a problem? Please describe.

The .conf file is an important file containing your custom settings, including autoexec.bat, window size, and all kinds of tweaks that people use to get things just right. 

The .conf file lives in the appdata folder by default. This is fine/standard for normal windows installations.

I like to run DosBOX (and many other apps) portably, so I can easily "reinstall" and back up my data. 

The .conf file often gets forgotten about, and to edit it you have to dig through your user profile folders to edit it (not to mention copy it between systems and back it up).

### Describe the solution you'd like

It would be handy being able to have the .conf file sit among the Dosbox files (as an option)

Perhaps have dosbox look for a .conf file in the current dir (eg C:\Dosbox). If none exist, then fall back on the appdata .conf file.

### Add any other context or screenshots about the feature request here.

There might be other files/reg keys that prevent DosBOX from being completely portable, but the .conf file is most important for me at least. 

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by GranMinigun** [comment]
I'm positive that was implemented at some point, but can't quickly find any documentation or even pull-requests on that. Not the first request of that kind.

**Comment by kcgen** [comment]
@SpitFire-666 , search for 'portable' in the README; it's supported
