### ISSUE TITLE
Autoselect of Dutch keyboard layout

### ISSUE THREAD

**Issue by rderooy** [dosbox-staging/dosbox-staging#1951]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Different version than latest?

0.79.0

### What Operating System are you using?

Linux x86_64

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

@FeralChild64 asked me to open this issue.

As mentioned on Discord.

I have been making a Dutch language file for -staging, which I will be submitting in the next days. When I use this file (at least on Linux), -staging will automatically switch to a matching Dutch keyboard layout.

However, Dutch keyboard layouts in the Netherlands are very rare. Step into any computer retailer, and you will find **only** US keyboards (with Euro symbol).

Some of the larger manufacturers (at least HP and Lenovo) do offer Dutch layouts as a special order option, but often only on their professional line of machines.

As such, defaulting to a US layout may make more sense.

### Steps to reproduce the behaviour.

Explain how to reproduce
1. 
2.
3.

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by Wengier** [comment]
@rderooy Can you try the code in PR #1954 (which tries to make Dutch language file default to U.S. keyboard layout)? Hope it helps.

**Comment by rderooy** [comment]
@Wengier I will try it out later today.
