### ISSUE TITLE
Alone in the Dark (floppy version) SB Pro support

### ISSUE THREAD

**Issue by KainXVIII** [dosbox-staging/dosbox-staging#1959]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### What Operating System are you using?

Windows 10

### Whats your question and how can we help?

So after intriguing examples of some new Staging features (mainly AITD intro with reverb and chorus) i tried this game and curiously i can't get it to work with SB Pro support for sound effects, game just hangs. Is it a bug, a feature, does SB Pro support adds anything (like stereo)? Original Sound Blaster works just fine. 
AFAIK cd-version does not even have SB Pro in option settings, just SB (DMA and without DMA)..

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by rderooy** [comment]
Sound Blaster is Mono

Sound Blaster Pro 1 & 2 are Stereo, but in subtle incompatible ways. So you must select the right Pro card for the game. Of course that assumes the game even supports one of the Pro (or 16) cards. Generally if the game list a "Sound Blaster Pro" as option, you can assume it to be the SB Pro 1.

SB16 is backward compatible with the original mono SoundBlaster cards, and the stereo SB Pro 2 (but not the SB Pro 1).

In later DOS CD games, some of the more advanced sound options were removed as they would stream background music from the CD, and only use the soundcard for some sound effects.

**Comment by KainXVIII** [comment]
> SB16 is backward compatible with the original mono SoundBlaster cards, and the stereo SB Pro 2 (but not the SB Pro 1).

Yeah, in AITD when i set sbtype to sb16 i can't even select SB Pro in AITD sound setup, but question still remains - why game hangs when i set sound effects to SB Pro in Alone the Dark 1 (floppy version)?
My config
sbtype              = sbpro1
sbbase              = 220
irq                 = 7
dma                 = 1
hdma                = 5
sbmixer             = true
sbwarmup            = 100
oplmode             = auto
sb_filter           = auto
sb_filter_always_on = false
opl_filter          = auto
cms_filter          = on

**Comment by kcgen** [comment]
@KainXVIII , can you test this with a physical SB Pro 2 (or perhaps a significantly different emulator like PCem or 86box)?

The SB Pro 2 drivers includes s test program, which passes on all the DOSBoxes (with `sbtype = sbpro2`):

https://winworldpc.com/download/78f9ead2-4c60-11eb-b764-0200008a0da4

If DOSBox's SB Pro 2 emulation had bugs that prevented it from being detected or used, then there would be large swaths of early 90s games affected - so I suspect this is a game-driver issue. 

Will tentatively close this - but if it does prove to work on hardware or other emulators, then please reopen.  Thanks @KainXVIII !
