### ISSUE TITLE
Fix include order between <ctype> and <algorithm> 

### ISSUE THREAD

**Issue by kcgen** [dosbox-staging/dosbox-staging#196]
It turns out that the include order between these two matters, and if `<algorithm>` comes before `<cctype>` then performance of `toupper` (and other simple functions) will be reduced significantly as they won't be inlined.

Include order ultimately needs `<ctype.h>` or `<cctype>` prior to `<algorithm>`. 

English - https://travisdowns.github.io/blog/2019/11/19/toupper.html
Russian (PVS team) - https://habr.com/ru/company/pvs-studio/blog/480012/
Discussion - https://news.ycombinator.com/item?id=21579333

Possibly affected files:
```
include/support.h:#include <algorithm>
src/dos/drive_cache.cpp:#include <algorithm>
src/gui/midi.cpp:#include <algorithm>
src/gui/sdl_gui.cpp:#include <algorithm>
src/gui/sdl_mapper.cpp:#include <algorithm>
src/hardware/mixer.cpp:#include <algorithm>
src/hardware/pcspeaker.cpp:#include <algorithm>
src/ints/bios_disk.cpp:#include <algorithm>
src/libs/decoders/archive.h:#include <algorithm>
src/misc/setup.cpp:#include <algorithm>
src/misc/support.cpp:#include <algorithm>
src/shell/shell_cmds.cpp:#include <algorithm>
src/shell/shell_misc.cpp:#include <algorithm>
```

**Comment by dreamer** [comment]
C++…
![](https://i.kym-cdn.com/entries/icons/original/000/000/554/picard-facepalm.jpg)

Perhaps the best way would be to write custom clang static analyzer checker; I haven't written one before, but this seems to be the only fix, that will keep us from making this mistake by accident.

**Comment by krcroft** [comment]
PR https://github.com/dreamer/dosbox-staging/pull/213 addresses the assessment side of this issue.
When we've fixed the order, we can include this checker script along with the other verify-* linters.

**Comment by dreamer** [comment]
#213 is merged already, but I presume we want to keep this open until we'll have the checker running cleanly on master? :)

**Comment by krcroft** [comment]
Yup; I renamed the title from "Assess and fix"; to now just "Fix"', which is the hard part :-)
Once we fix and the checks pass, we'll add it to our code analysis linter step.

**Comment by kcgen** [comment]
Although there are small performance regressions, these aren't on the hot path of the emulation once games are running.
