### ISSUE TITLE
Opening mapper crashes to desktop when sdl output is set to texture or texturenb

### ISSUE THREAD

**Issue by Lippeth** [dosbox-staging/dosbox-staging#1960]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### What Operating System are you using?

Windows 10

### Relevant hardware info

Intel i9-9900K, Nvidia GeForce RTX 2080 SUPER

### Have you checked that no other similar issue already exists?

- [x] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

DOSBox Staging crashes to desktop when pressing ctrl+F1 to open mapper when sdl output is set to texture or texturenb in the config file.

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Select texture or texturenb as output type in [sdl] section of config
2. Launch DOSBox
3. Press ctrl+F1

### Your configuration

```ini
https://gist.github.com/Lippeth/8a97079fcb00c2e21943100431ca968c
```

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by kcgen** [comment]
@ThomasEricB, is this something you can confirm on your Windows system? ( @GranMinigun mentioned it will help w/ the sdlmain refactoring PR).

**Comment by GranMinigun** [comment]
Is this still the case in the current development version? Could've been fixed by #2763 or subsequent PRs.

**Comment by johnnovak** [comment]
> Is this still the case in the current development version? Could've been fixed by #2763 or subsequent PRs.

I'll try on Windows tomorrow, hopefully. Maybe someone else can confirm before that.

Just tried it on macOS; the mapper works fine with `texture`. So I'm 95% sure it fine on Win 10 too, but let's confirm first.

**Comment by Grounded0** [comment]
Can we close this or not? Should be checked already. Time to check and close this.

**Comment by johnnovak** [comment]
Just retested on macOS with all backends, works fine.
