### ISSUE TITLE
Large IMG sizes

### ISSUE THREAD

**Issue by almeath** [dosbox-staging/dosbox-staging#1964]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Different version than latest?

0.80

### What Operating System are you using?

Mac OS

### Whats your question and how can we help?

Can I just start by saying that I understand and respect that the focus of DOSBox Staging is to play DOS games, and while my questions below pertain to functionality that better supports running Win9x within DOSBox, I only ask these question to understand if 1) support for these features already exists or 2) I need to look at implementing my own custom-patches. I do not expect any support in this task, but I am interested if anyone has any views or recommendations.

I have a specific use case for large IMG files of 4GB+ in size. Support for this has existed for DOSBox SVN via custom patches, but it does not appear to be supported by DOSBox Staging. Is this correct?

For example, in my custom-patched SVN I can mount two images in this way:

```
[autoexec]
# Lines in this section will be run at startup.
@echo off
cls
imgmount 2 "harddisk/hdd.img" -size 512,63,32,1015 -t hdd -fs none
imgmount 3 "harddisk/hdd2.img" -size 512,63,255,560 -t hdd -fs none
boot -l c
cls
```

This allows for niche usage cases, such as booting Win9x on the first image, and using the large second image as a repository for data that would otherwise reside on a DVD iso. In this way, I was able to get some early DVD era games such as Riven and Legacy of Time installed and working perfectly. 

Is there a way to gain similar functionality in Staging? 

A second but related question would be if there is a way to just mount a DVD ISO image via the -ide feature, but detectable within a Win9x environment?

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by almeath** [comment]
I should add, I did have a go at patching in the larger img size patch into Staging, but I found that key files such as dos_inc.h and bios_disk.h had too many differences for it to be clear if this would work.

**Comment by kcgen** [comment]
@almeath - thanks for pushing into less-used areas. 

> I have a specific use case for large IMG files of 4GB+ in size. Support for this has existed for DOSBox SVN via custom patches, but it does not appear to be supported by DOSBox Staging. Is this correct?

Right, we haven't added (or changed) anything in these areas, like moving to 64-bit offsets in CDROM or HDD images, and other API changes.

If this can be enabled with minimal code and zero-impact to DOS, then your help level would be appreciated (patch round-up, PRs, testing, updating docs).

**Comment by almeath** [comment]
OK then, I will continue investigating this. 

As a starting point, I remember I had to change several functions to support the 64-bit-only macOS (i.e. fopen64, ftello64, fseeko64, Bit64u etc.).

I will need to learn how to apply such changes to the Staging codebase, which, for example, replaced all references to Bit16u and Bit32u with uint32_t and uint16_t. 

I will need to read up on this stuff.

**Comment by Wengier** [comment]
For large IMG sizes, I think the FAT32 patch can be considered too. FAT32 is supported by all recent DOS such as FreeDOS and MS-DOS 7+.

**Comment by almeath** [comment]
OK, so I have been attempting to get my SVN large drive image patch to apply cleanly to the Staging code. It was difficult at first, due to the extensive differences in the bios_disk.cpp and drive_fat.cpp files. However, I was able to use the DOSBox-X code as a reference point to work most of it out. The changes are detailed here:

https://github.com/almeath/DOSBox-Staging/commit/afa60a6fe1bc91cc084d55e78a57061fa8d96163

This is confirmed to give me access for up to 4GB drive images in Win9x. For example, I can use the following launch commands to boot a 1GB FAT 32 drive image, with an accompanying D drive of 4GB.

```
imgmount 2 "harddisk/hdd.img" -size 512,63,32,1015 -t hdd -fs none
imgmount 3 "harddisk/hdd2.img" -size 512,63,130,1023 -t hdd -fs none
boot -l c
```
What I cannot get to work, is images larger than 4GB in size. For example, attempting to boot a 4.6GB image (which works with my SVN patch) would use the following launch commands:

```
imgmount 2 "harddisk/hdd.img" -size 512,63,32,1015 -t hdd -fs none
imgmount 3 "harddisk/hdd2.img" -size 512,63,255,560 -t hdd -fs none
boot -l c
```

Before the Windows boot screen I can see that DOS considers the drive mounted, but I will instead see D drive as an optical drive - clicking on that give me an error that the device is not accessible / ready.

In in SVN patch, there is a last bit of code added to bios_disk.cpp, which seems to trigger access to 4GB+, but I do not understand why this is the case. Adding this code to the Staging bios_disk.cpp results in build errors. There is no equivalent to this code in the corresponding DOSBox-X bios_disk.app which probably explains why it is failing - it is only SVN compatible.

This is the specific code:

```
@@ -556,6 +579,85 @@ static Bitu INT13_DiskHandler(void) {
 		reg_ah = 0x00;
 		CALLBACK_SCF(false);
 		break;
+            case 0x41: /* Check Extensions Present */
+                              if ((reg_bx == 0x55aa) && !(driveInactive(drivenum))) {
+                                  LOG_MSG("INT13: Check Extensions Present for drive: 0x%x", reg_dl);
+                                  reg_ah=0x1;    /* 1.x extension supported */
+                                  reg_bx=0xaa55;    /* Extensions installed */
+                                  reg_cx=0x1;    /* Extended disk access functions (AH=42h-44h,47h,48h) supported */
+                                  CALLBACK_SCF(false);
+                                  break;
+                              }
+                              LOG_MSG("INT13: AH=41h, Function not supported 0x%x for drive: 0x%x", reg_bx, reg_dl);
+                              CALLBACK_SCF(true);
+                              break;
+                          case 0x42: /* Extended Read Sectors From Drive */
+                              /* Read Disk Address Packet */
+                              readDAP(SegValue(ds),reg_si);
+                      
+                              if (dap.num==0) {
+                                  reg_ah = 0x01;
+                                  CALLBACK_SCF(true);
+                                  return CBRET_NONE;
+                              }
+                              if (!any_images) {
+                                  // Inherit the Earth cdrom (uses it as disk test)
+                                  if (((reg_dl&0x80)==0x80) && (reg_dh==0) && ((reg_cl&0x3f)==1)) {
+                                      reg_ah = 0;
+                                      CALLBACK_SCF(false);
+                                      return CBRET_NONE;
+                                  }
+                              }
+                              if (driveInactive(drivenum)) {
+                                  reg_ah = 0xff;
+                                  CALLBACK_SCF(true);
+                                  return CBRET_NONE;
+                              }
+                      
+                              segat = dap.seg;
+                              bufptr = dap.off;
+                              for(i=0;i<dap.num;i++) {
+                                  last_status = imageDiskList[drivenum]->Read_AbsoluteSector(dap.sector+i, sectbuf);
+                                  if((last_status != 0x00) || (killRead)) {
+                                      LOG_MSG("Error in disk read");
+                                      killRead = false;
+                                      reg_ah = 0x04;
+                                      CALLBACK_SCF(true);
+                                      return CBRET_NONE;
+                                  }
+                                  for(t=0;t<512;t++) {
+                                      real_writeb(segat,bufptr,sectbuf[t]);
+                                      bufptr++;
+                                  }
+                              }
+                              reg_ah = 0x00;
+                              CALLBACK_SCF(false);
+                              break;
+                          case 0x43: /* Extended Write Sectors to Drive */
+                              if(driveInactive(drivenum)) {
+                                  reg_ah = 0xff;
+                                  CALLBACK_SCF(true);
+                                  return CBRET_NONE;
+                              }
+                      
+                              /* Read Disk Address Packet */
+                              readDAP(SegValue(ds),reg_si);
+                              bufptr = dap.off;
+                              for(i=0;i<dap.num;i++) {
+                                  for(t=0;t<imageDiskList[drivenum]->getSectSize();t++) {
+                                      sectbuf[t] = real_readb(dap.seg,bufptr);
+                                      bufptr++;
+                                  }
+                      
+                                  last_status = imageDiskList[drivenum]->Write_AbsoluteSector(dap.sector+i, &sectbuf[0]);
+                                  if(last_status != 0x00) {
+                                      CALLBACK_SCF(true);
+                                      return CBRET_NONE;
+                                  }
+                              }
+                              reg_ah = 0x00;
+                              CALLBACK_SCF(false);
+                              break;
 	default:
 		LOG(LOG_BIOS,LOG_ERROR)("INT13: Function %x called on drive %x (dos drive %d)", reg_ah,  reg_dl, drivenum);
 		reg_ah=0xff;
```

So, I am partially successful at this stage. Accessing 4GB images is useful, but it is not enough to be able to hold the entire contents of a DVD image.

**Comment by Wengier** [comment]
As mentioned above, custom patches including native FAT32 support and geometry detections are not integrated into the DOSBox Staging code at the time. Ideally, commands like the following should work regardless the image size and geometry:

``imgmount C harddisk/hdd.img``
`` imgmount D harddisk/hdd2.img``
`` boot c:``

Such commands will be much shorter and more readable than the commands as shown in your above post, with native FAT32 support so that you will see the contents of the FAT32 drives in the internal DOS as well regardless the image size. Some time and efforts will be needed for these to actually work as in DOSBox-X, partially due to the required formatting changes in DOSBox Staging. But the mounting process will be much simplified with this.

**Comment by almeath** [comment]
@Wengier , thanks, I do understand that the custom FAT32 patches are not yet integrated into DOSBox Staging, hence my initial attempt to see if it is viable to apply the same code I was successfully using with SVN. I consider it only partially successful at this stage, and I would not propose any commits unless I thought it was 100% working and not negatively impacting DOS, as @kcgen pointed out. I have detailed my progress above, in case it elicits any thoughts or feedback from others. 

On the issue of the automatic drive geometry detection, I entirely agree it would be better to find a way to patch in the FAT32 support without having to detail the specific drive geometry of each image in the configuration file. I personally do not find it inconvenient, as I tend to "set and forget" for each configuration, but I see how it could be confusing for less experienced users.

As things currently stand, I can only get the above patches to work if I use the extended imgmount commands detailed above, and, as mentioned, this only works for images up to 4GB. I would like to try unlocking support for larger images, if I can figure out how to properly apply that errant code to bios_disk.cpp .. or find an alternative. My testing repository is available for anyone who wants to have a crack at it.

https://github.com/almeath/DOSBox-Staging

**Comment by Wengier** [comment]
@almeath Looking at your repository code, I went ahead to make a test branch (https://github.com/dosbox-staging/dosbox-staging/tree/ww/fat32-test) containing functional code that includes the following patches: native FAT32 support, auto-geometry detection, INT13 extension, in addition to the type fixes in your repo. The code is considered WIP mostly for demonstration purposes for those who may need it. The native FAT32 patch was mostly done by @joncampbell123, and @rderooy also improved the auto-geometry detection code earlier. In any case, with this test branch the following should work:

``imgmount C harddisk/hdd.img -ide``
``imgmount D harddisk/hdd2.img -ide``
``boot C:``

Tested with 4GB and 8GB FAT32 images myself. Hope this helps.

**Comment by kcgen** [comment]
@almeath , @Wengier , @joncampbell123 , @rderooy : wow.. look at all this good stuff :rocket:

**Comment by almeath** [comment]
@Wengier , thanks so much for combining the patches and providing a test repository. So far, it appears to be working great. I can now mount the 4.6gb and 8gb drive images in Windows 98. It appears to be stable..

**Comment by ThomasEricB** [comment]
@Wengier @almeath Do I have to compile it myself into an executable (something I never done) or is there a .zip of this branch and I'm failing to find?

**Comment by ThomasEricB** [comment]
I want to help test this

**Comment by ThomasEricB** [comment]
Thanks for all the documentation on how to build the executable on Windows! I downloaded Virtual Studio and I am ready to test the FAT32 test! (https://github.com/dosbox-staging/dosbox-staging/tree/ww/fat32-test)
