### ISSUE TITLE
Titus the Fox freezes on exit

### ISSUE THREAD

**Issue by javi-s** [dosbox-staging/dosbox-staging#1967]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### What Operating System are you using?

Windows 10

### Relevant hardware info

Core i7-6700, GTX 1060 3GB

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Titus the Fox freezes when quitting the game.

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Launch Titus the Fox from drive C: (mounted filesystem)
2. Press space to skip the year screen
3. Let the game reach at least the splash screen where music begins
4. Press ESC to quit the game
5. The game freezes in the screen below

![Titus-Freeze](https://user-images.githubusercontent.com/34216160/192150709-b904c6f2-b31b-4cb8-a59d-a1dbee3316b6.png)

### Your configuration

```ini
https://gist.github.com/javi-s/e4d0101a2b5075c74d242132fc242692
```

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by kcgen** [comment]
Thanks, @javi-s

When you have a chance, can you test either of the packages here: https://github.com/dosbox-staging/dosbox-staging/actions/runs/3122888835

(Scroll down to the 'Artifacts' section).

**Comment by javi-s** [comment]
Thank you.  I tested dosbox-staging version 0.80.0-alpha-17-g217181cfd and I experience the freeze in the same screen when quitting the game.

**Comment by kcgen** [comment]
Here's another try: <https://github.com/dosbox-staging/dosbox-staging/actions/runs/3123532862> (build in-progress)

**Comment by javi-s** [comment]
Thanks, this version (dosbox-staging version 0.80.0-alpha-18-g2f4d7935b) fixes the issue for me, the game quits cleanly now.

**Comment by kcgen** [comment]
Right on; thanks for the checks on your side, @javi-s .

When that branch is merged, this ticket will be closed out automatically.

**Comment by nemo93** [comment]
This fixes other Titus games as well (Super Cauldron, Blues Brothers, Prehistorik, Moktar). Well done!
