### ISSUE TITLE
Pressing slash/question mark key does type anything in the shell

### ISSUE THREAD

**Issue by rsribeiro** [dosbox-staging/dosbox-staging#1981]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### What Operating System are you using?

Windows 10

### Relevant hardware info

Keyboard with Brazilian ABNT2 Layout

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

My keyboard has a brazilian abnt2 layout. All relevant configuration is default, I didn't use the keymapper nor did I change any keyboard/language settings on my .conf file.

My keyboard is exactly like this one:
![image](https://user-images.githubusercontent.com/11283302/193412156-069fc90b-bac4-4afc-99f6-844a4438a1e9.png)

The slash/question mark key (the one next to right shift) doesn't do anything in the shell. I also tested DOSBox Staging 0.78.1 and the behaviour is the same.

The key does work with the mapper though, performing any action I assign to it, even if the behaviour is a little weird.

If I assign this key to an action, it shows an empty field, like this:
![image](https://user-images.githubusercontent.com/11283302/193412377-a25e8448-ae78-4bce-9dba-5938a4a15846.png)

The colon/semicolon key works normally in the shell, but if I assign the colon/semicolon key, it shows a slash:
![image](https://user-images.githubusercontent.com/11283302/193412438-49f50d3f-417d-471b-9bc5-2b8a256d9e1c.png)

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Have brazilian abnt2 keyboard and press slash/question mark key in the shell
2.
3.

### Your configuration

```ini
mapperfile          = mapper-sdl2-0.78.1.map
country               = 0
keyboardlayout        = auto
```

### Provide a Log

```text
2022-10-01 10:40:53.140 | LANG: The 'pt' language resource file: 'pt.lng' could not be loaded, using English messages
2022-10-01 10:40:53.495 | LAYOUT: Loaded codepage 860 for detected language br
2022-10-01 10:40:53.576 | MAPPER: Failed loading mapperfile 'mapper-sdl2-0.78.1.map' directly and from resources
2022-10-01 10:40:53.577 | MAPPER: Loaded default key bindings
```

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by kcgen** [comment]
It's good that most of the ABNT keys are working.

0.79 added code to:
 - extract Microsoft's layout and [map it to DOS's Brazilian layout](https://github.com/dosbox-staging/dosbox-staging/blob/main/src/dos/dos_keyboard_layout.cpp#L1570)
 - From there, [uses FreeDOS's Brazilian layout](https://github.com/dosbox-staging/dosbox-staging/blob/main/src/dos/dos_keyboard_layout.cpp#L1224-L1238) 

However, it looks like the the [/?] key and the numpad period key are specifically an issue, mentioned in FreeDOS's 2.6 ([28/05/09) keyboard layout notes](https://github.com/dosbox-staging/dosbox-staging/blob/22fbebfa124c29d0cb0dd89307ce8b21d6339438/contrib/resources/freedos-keyboard/DOC/HISTORY.TXT#L202):

```
Brazil: two other keys, </>  and <NumPad.>  are now
handled by DOSEMU thanks to the  work  of  Alain
Mouette through a patch made available by him
http://sourceforge.net/tracker/?func=detail&aid=2797605&group_id=49784&atid=457449.
```
 
So (my assumption) is that DOSEMU (an emulator for Linux) included some special handling for these two keys.

I couldn't find references to ABNT2, which are the blue differences versus the ABNT layout:

![2016-06-21-900px-kb-portuguese-brazilsvg-](https://user-images.githubusercontent.com/1557255/193415355-373b7173-c238-49e7-8d27-337e6c8d9f9f.png)

But the interesting thing is that ABNT2 added those blue additions as a work-around for problems like this (Provide alternates if the [/?] key isn't mappable).  

From my limited ability to test with a US-keyboard, it _does_ look like the  **Alt+Q** should type a forward slash `/`, and **Alt+W** type a question mark `?` with the mapping.

Do those work on your side? 

If so, it means that ABNT2's alternates are supported, which is at least a fallback option.

**Comment by kcgen** [comment]
Thanks for confirming, @rsribeiro , and great you've got some options (and the mapper route too), but I agree: it's not perfect.

I think the crux of the slash-problem is that the key value for the slash incoming from an ABNT keyboard has a different number versus the "normal slash" (from the DOSEMU handling):

```diff
 #define NUM_SLASH	0x35
 #define NUM_LESSGREATER	0x56	/* not on US keyboards */
+#define NUM_ABNT_SLASH	0x73	/* Brazil-ABNT "/?" and other non US */
```

Tagging this with the 'want-help' label: there are a couple places where keycodes / scancode are handled. If someone can poke around, maybe it will be easy to intercept the ABNT-slash and replace it with the DOS BIOS code for a normal slash.

**Comment by ThomasEricB** [comment]
Can reproduce! Thanks @kcgen for pointing this out. Also having the same issue with the Slash. 

However BR275 behaves normally in Dosbox-X

**Comment by ThomasEricB** [comment]
Hey @joncampbell123 Is there a problem if I were to take a look at DOSBOX-x implementation of BR275 and try to implement it here? Like create a test branch with the BR275 keyboard code from DOSBox-X? 

Also to @Wengier @kcgen

**Comment by kcgen** [comment]
Thanks for this fix, @rsribeiro!
