### ISSUE TITLE
Missing mapping of FreeDOS code page characters to Unicode

### ISSUE THREAD

**Issue by FeralChild64** [dosbox-staging/dosbox-staging#1986]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Different version than latest?

0.80.0-alpha

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

The main branch has just switched to UTF-8 locale. For this to work, the DOSBox Staging Unicode engine has to know how to map the DOS code page characters to Unicode graphemes. Currently the mappings are provided for all the FreeDOS code pages (as we are using FreeDOS CPX files for screen fonts), but there are few missing points:

- **864** (Arabic) - unidentified characters: **0x9b**, **0x9c**, **0x9f**, **0xa6**, **0xa7**
- ~~30020 (Low Saxon and Frisian) - possibly misidentified characters: 0xa4, 0xa5, 0xc6, 0xc7~~ EDIT: charactters identified dosbox-staging/dosbox-staging/pull/1988
- **59829** (Georgian) - unidentified character: **0xa6** (most likely a SHIN letter with some accent - but which one?)

Once the characters are identified, mappings should be updated in file:
https://github.com/dosbox-staging/dosbox-staging/blob/main/contrib/resources/mapping/MAIN.TXT
and, additionally, fallback mapping to a 7-bit ASCII character set shall be added to:
https://github.com/dosbox-staging/dosbox-staging/blob/main/contrib/resources/mapping/ASCII.TXT

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by FeralChild64** [comment]
Unidentified characters isolated on screenshots:

![HelpNeeded_864](https://user-images.githubusercontent.com/48332137/193514808-a36b0609-c3cf-45e6-8e22-35ea2bee6451.png)

![HelpNeeded_59829](https://user-images.githubusercontent.com/48332137/193514817-28bcdc20-42e2-4947-a4cb-4fa8b4602ba0.png)

**Comment by FeralChild64** [comment]
4 arabic characters identified, see https://github.com/dosbox-staging/dosbox-staging/pull/2458

Still to identify:
- character `0x9f` from code page 864 (Arabic)
- character `0xa6` from code page 59829 (Georgian)

**Comment by johnnovak** [comment]
Going into extreme niche territory here, but okay :)

**Comment by Burrito78** [comment]
@FeralChild64 Cleaning up tickets today, is this still unsolved and do you plan working on it? If yes, just ignore me. :)

**Comment by FeralChild64** [comment]
Yes, please don’t close this one. We can actually fix this in no-time if we have help from native speakers…

**Comment by FeralChild64** [comment]
Found the code page 864 character `0x9f` on Wikipedia - https://en.wikipedia.org/wiki/Code_page_864

One unidentified character still left:
- character `0xa6` from code page 59829 (Georgian)

**Comment by FeralChild64** [comment]
Yes, it’s a mistake on the screenshot.

**Comment by johnnovak** [comment]
Haven't you fixed this recently @FeralChild64 ?

**Comment by FeralChild64** [comment]
No, this one single character (0xa6 from code page 59829) is still unidentified. I have tried to find some Facebook groups about the Georgian language and ask for help there, so far without success - they all seem to exist just to promote some language schools :(

**Comment by johnnovak** [comment]
Keeping it open then.

**Comment by FeralChild64** [comment]
Found the last remaining letter, here: https://en.m.wikibooks.org/wiki/Character_Encodings/Code_Tables/MS-DOS/Code_page_59829 - looks like it's შ̌, which encodes in UTF-8 as `0xE1 0x83 0xA8 0xCC 0x8C`, which gives:

`U+10E8 U+030C` - GEORGIAN LETTER SHIN + COMBINING CARON

:D
