### ISSUE TITLE
Allow shaders in composite modes

### ISSUE THREAD

**Issue by Jkapp76** [dosbox-staging/dosbox-staging#1987]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Is your feature request related to a problem? Please describe.

This is a request to allow composite modes for CGA and PCJr to have shaders. This is already done with 86box and it is a big improvement.

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by Jkapp76** [comment]
![20221002_212826](https://user-images.githubusercontent.com/89743985/193488769-929e6d90-99ab-41fa-a5ec-4e8fff8a45f4.jpg)
![20221002_212923](https://user-images.githubusercontent.com/89743985/193488773-cb0eacab-cfd0-41d5-9a5d-d683e2c8eb61.jpg)
![20221002_212812](https://user-images.githubusercontent.com/89743985/193488774-dbdde89f-da26-4da4-ae08-8ed2b05826ab.jpg)

**Comment by Jkapp76** [comment]
Here's a few examples of shaders used with the 86box emulator.

**Comment by Jkapp76** [comment]
It's been a while since I tested shaders in composite mode. I think some work, but none give scan lines anything like 86box or a real monitor.

**Comment by Jkapp76** [comment]
Staging allows shaders, it just doesn't give scan lines. Not even with scalers like TV2x and so on.

**Comment by GranMinigun** [comment]
Scanlines aren't DOSBox's responsibility, it's solely on the shaders. If none of the built-in shaders or those from the [shaders repo](https://github.com/tyrells/dosbox-svn-shaders) provide the effect you want, then the only options are either porting desired shaders from other projects or waiting for RetroArch shaders system integration (no ETA on that).

**Comment by Jkapp76** [comment]
The same shaders give scanlines on 86box so I thought it would require a change to the emulator.

**Comment by GranMinigun** [comment]
Which shaders specifically then?

**Comment by Jkapp76** [comment]
I use crt-hyllian-3d.glsl in 86box...

Actually, I was using a different shader in Staging. Here's the result after switching to hyllian.
![Screenshot 2022-10-06 014009](https://user-images.githubusercontent.com/89743985/194223734-9ce1b5d2-a7ee-49bb-a2a8-16ae0ad48e11.png)

It appears the scan lines show up fine. I made a mistake with my shaders apparently.

**Comment by Jkapp76** [comment]
It looks even better than 86box. The text is better. The standard DOS text is much better.

**Comment by johnnovak** [comment]
Shaders are already supported in composite mode, so closing.
