### ISSUE TITLE
The All-Seeing Eye automapper tool and Dosbox Staging

### ISSUE THREAD

**Issue by KainXVIII** [dosbox-staging/dosbox-staging#1989]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### What Operating System are you using?

Windows 10

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

The All-Seeing Eye automapper tool (http://www.ase.zorbus.net/) seems like is not compatible with Dosbox Staging, when i try to search for characters in memory and load automap - nothing can be found. Normal dosbox (or dosbox ece build) works fine with ASE by the way..
![Снимок экрана 2022-10-03 115417](https://user-images.githubusercontent.com/16922126/193538168-7d0a7432-d8cc-402c-8690-0da0924366c1.jpg)

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Install and run ACE
2. Load save file from Eye Of Beholder 1
3. Click Search button

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by kcgen** [comment]
Can you try some of the older builds, like 75.x and 76.x, and also compare 32bit builds vs. 64bit?

**Comment by KainXVIII** [comment]
> Can you try some of the older builds, like 75.x and 76.x, and also compare 32bit builds vs. 64bit?
ASE works with these versions:
dosbox-staging-windows-msys2-i686-v0.78.0
dosbox-staging-windows-v0.75.0
dosbox-staging-windows-x86-v0.76.0
But not working with dosbox-staging-windows-msys2-x86_64-v0.78.0 (and latest 079.1)

**Comment by kcgen** [comment]
hmm.. AES seems to depend on 32-bit builds.

When Staging launches (both 32-bit and 64-bit builds), the log will show you the base address of DOS's memory. For example:

```
MEMORY: Base address: 0x42f9000
```

We added this info to support cheat tools that scan the DOS memory. 

Maybe you can try inserting this the AES start region.
For the end-scan address, add 4 to the 7th value from the right. In this example, the value would be: `0x82f9000`

```
0x0042f9000
   +4
===========
0x0082f9000
```

This increments the memory by 64 MiB: (0x82f9000 - 0x42f9000) / (1024 * 1024) = 64.

**Comment by KainXVIII** [comment]
I tried other values in AES - they doesn't work (or i did something wrong, my hacking skills are quite poor 😅)

**Comment by GranMinigun** [comment]
All-Seeing Eye is 32-bit. Maybe contact them asking for 64-bit support, if building Staging from source isn't an option (can't say if official 32-bit builds were kissed goodbye (is that the right word?), but they're definitely becoming less relevant with time). As an alternative, perhaps you'd be interested in [drawing maps](https://gridmonger.johnnovak.net/) yourself? That was kinda part of the experience with those games, so who knows, maybe you'll find it enjoyable too.

**Comment by kcgen** [comment]
@KainXVIII -- try building the 32bit version using our build notes. The Visual Studio solution has a selection for 32bit targets. 

Tentatively closing.
