### ISSUE TITLE
Sync date/time with host

### ISSUE THREAD

**Issue by bdhirsch-code** [dosbox-staging/dosbox-staging#1990]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### What Operating System are you using?

Windows 10

### Is your feature request related to a problem? Please describe.

I'm running a fullscreen DOS-based embedded business application that uses the date and time for timestamped log entries.  After doing some batch processing that kept the CPU, disk read/write, and serial port very busy for a few hours, I noticed that the DOSBox-Staging time had lagged behind the host time by about five minutes.  My assumption is that the DOSBox-Staging clock falls behind when the computer gets busy.

### Describe the solution you'd like

Add a config setting to sync the date and time with the host.  The feature may be set with a parameter to determine how often to retrieve the host date and time to correct the DOSBox-Staging internal clock error.

### Describe alternatives you've considered

DOSBox-X has this feature.

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by Burrito78** [comment]
Shouldn't DOSbox internal clock accuracy be independent of system load?

**Comment by kklobe** [comment]
I cleaned it up a bit and fixed a logic error, so please try https://github.com/dosbox-staging/dosbox-staging/actions/runs/3278243894 instead, thanks.

**Comment by Burrito78** [comment]
User never replied. Seems like he's too happy with the solution.

**Comment by johnnovak** [comment]
Bear in mind the pause and fast-forward features will always get the clock out of sync. This can't really be solved as some programs might not like clock jumps or the clock jumping back in time either...
