### ISSUE TITLE
Test case bit_view.size_safety fails on s390x architecture

### ISSUE THREAD

**Issue by oturpe** [dosbox-staging/dosbox-staging#1993]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### What Operating System are you using?

Other

### If Other OS, please describe

Linux s390x

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

I am trying to update DOSBox Staging in Fedora to 0.79.1.
The build succeeds on all other Fedora architectures except s390x.
On s390x, there is one failing test as follows:

```
[ RUN      ] bit_view.size_safety
../tests/bit_view_tests.cpp:310: Failure
Value of: r8.first_8 == 0b000'1111
  Actual: false
Expected: true
[  FAILED  ] bit_view.size_safety (0 ms)
```

Investigating further, `r9.first_8` actually has the value that the test sets for `last_8`.
Since I know that using `union` and bitwise operations (like `bit_view` does) can lead to endianess-dependent code,
my guess is that this is related to s390x being big endian.

Testing is somewhat difficult, due to lack of hardware.
However, I have a setup where I can build and run code in Fedora's infra.

Admittedly, it seems unlikely that anybody will want to run DOSBox Staging on a mainframe,
so I could just not build for s390x,
on the basis that the test suite does not pass on that arch.
However, seeing that the codebase otherwise has support for big endian through `WORDS_BIGENDIAN`,
perhaps this is a valid bug that deserves to be fixed?

### Steps to reproduce the behaviour.

Explain how to reproduce
Build and run the test suite on s390x architecture.
For example, [dosbox-staging-build][copr] in Copr.
Check chroot `fedora-rawhide-s390x`'s logs at `builder-live.log` for gtest output.

[copr]: https://copr.fedorainfracloud.org/coprs/oturpe/dosbox-staging-build/build/4882237/

### Your configuration

```ini
n/a
```

### Provide a Log

```text
Build and test logs:
https://download.copr.fedorainfracloud.org/results/oturpe/dosbox-staging-build/fedora-rawhide-s390x/04882237-dosbox-staging/builder-live.log.gz
```

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by kcgen** [comment]
Thanks @oturpe ; will get this fixed up in 0.80.x (probably doesn't warranty a 0.79.2 release). But if any s390x do appear.. then will reconsider 👍
