### ISSUE TITLE
0.79.1 Crashes Immediately on Launch

### ISSUE THREAD

**Issue by OpenRift412** [dosbox-staging/dosbox-staging#1994]
I don't know why I'm only now just noticing this issue, but for some reason 0.79.1 is deciding to crash as soon as it starts.

Running it with the console produces this error:
`2022-10-03 22:07:46.873 | EXCEPTION: Standard library exception: filesystem error: in posix_stat: failed to determine attributes for the specified path: Resource temporarily unavailable ["D:/a/_temp/msys64/clang64/share\dosbox-staging"]`

I would highly recommend putting the ZIPs and setup EXEs for 0.79.0 back up in the meantime, because they're the only ones that are missing from the github releases page for some reason.

**Comment by kcgen** [comment]
Can you provide steps to reproduce this? 
 - ie: are you building it from source? If not, which package are you running?

>  would highly recommend putting the ZIPs and setup EXEs for 0.79.0 back

They contained critical regressions and the 0.79.1 release includes fixes for them, so we only recommend them.  However, the 0.79.0 can still be built from source, if anyone's interested.

**Comment by OpenRift412** [comment]
> Can you provide steps to reproduce this?
> 
> * ie: are you building it from source? If not, which package are you running?

No, I'm not building it from source, I'm just using the version provided. This happens with both the installer and ZIP versions.

**Reproducing**
Step 1: Download either the installer or ZIP package.
Step 2: Run it

That's pretty much all I can really say. I also tried emptying my config to make sure it wasn't something there either.

**Comment by kcgen** [comment]
Thanks @OpenRift412.

**Comment by Grounded0** [comment]
Install into empty Wine bottle:
<img width="1296" alt="Screenshot 2022-10-04 at 6 13 40" src="https://user-images.githubusercontent.com/48192273/193726647-b8ae2fcb-65a3-4335-9fb2-2f2ea0920bd1.png">

**Comment by Grounded0** [comment]
Why is the pathname like this: "D:/a/_temp/msys64/clang64/share\dosbox-staging"]

Paths are always specified in Windows with \ so what's up with that?

**Comment by OpenRift412** [comment]
> Why is the pathname like this: "D:/a/_temp/msys64/clang64/share\dosbox-staging"]
> 
> Paths are always specified in Windows with \ so what's up with that?

Honestly, no idea because my D: drive is a CD drive.

**Comment by kcgen** [comment]
@OpenRift412, when you've got a chance to try some new packages here:
https://github.com/dosbox-staging/dosbox-staging/actions/runs/3180007520

Very curious how these go for you!

**Comment by Jkapp76** [comment]
79.1 crashes for me as well. it just hangs on start up. It only does this about once every 10 launches. I just X it off and reload it. It has done this twice in a row a few times.

**Comment by kcgen** [comment]
@Jkapp76 , this might be a different issue, as I suspect @OpenRift412's case was 100% repeatable (due to an unexpected filesystem property). 

When it locks up for you next time, can you open a ticket and paste your console log and also info to help reproduce it (game, conf)

**Comment by Max833** [comment]
> > @OpenRift412, when you've got a chance to try some new packages here: https://github.com/dosbox-staging/dosbox-staging/actions/runs/3180007520
> > Very curious how these go for you!
> 
> Yeah, that seems to load fine! I'd recommend pushing that fix to a second maintenance release as soon as you're able.

Same problem, but the new packages fixes it for me as well, thank you!

**Comment by impeeza** [comment]
Hi, for me, the dosbox-staging-windows-x86_64-v0.79.1.zip uncompressed generate the problem, if use the installation dosbox-staging-v0.79.1-setup.exe on MSVC mode all runs fine, but using the installation dosbox-staging-v0.79.1-setup.exe and installing MSYS binaries get the same error.

**Comment by kcgen** [comment]
Thanks @impeeza , do the MSYS2's `main` builds work better for you? : https://dosbox-staging.github.io/downloads/devel/

**Comment by Max833** [comment]
Great that this issue is fixed. Thank you! Will there be a v0.79.2?

**Comment by impeeza** [comment]
> Thanks @impeeza , do the MSYS2's `main` builds work better for you? : https://dosbox-staging.github.io/downloads/devel/

Hi, yes it does, downladed dosbox-staging-v0.80.0-alpha-129-g0234-setup.exe.zip dosbox-staging-windows-msys2-x86_64-v0.80.0-alpha-129-g02346.zip and booth works fine since first run.  thanks a lot.
