### ISSUE TITLE
Staging hangs on startup

### ISSUE THREAD

**Issue by Jkapp76** [dosbox-staging/dosbox-staging#2002]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Different version than latest?

I've used 0.79 an the latest alpha build.

### What Operating System are you using?

Windows 11 and 10

### Relevant hardware info

Nvidia

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

About one launch out of about every 15 or so it will hang up and fail to start.

### Steps to reproduce the behaviour.

just launch

### Your configuration

opengl with shader

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by Jkapp76** [comment]
![0001](https://user-images.githubusercontent.com/89743985/194461962-a7201a06-3eea-4368-8565-879a07b91a46.png)
![0002](https://user-images.githubusercontent.com/89743985/194461974-5218ba20-bc98-4973-8ed1-80c679f18df6.png)

**Comment by Jkapp76** [comment]
I don't always use Dos Navigator. I've seen it hang without it.

**Comment by kcgen** [comment]
When using the `zdrive` augmentation feature, all content in the 2nd level of directories is inaccessible (which is where DOS Navigator store its language files, colors themes, screen savers, etc)

We haven't had any reports of random hanging on a bare startup, so I suspect relates to the various tools being used on startup.

I moved your custom zdrive configuration two two automount drives, in this archive (it will unzip inside a parent `Jkapp76` directory):

https://kcgen.duckdns.org/Jkapp76.zip

If you can launch DOSBox Staging inside there, so it picks up the local `dosbox.conf`, the `c:` and `u:` now _will_ have all sub-directories accessible (the red bars:

![2022-10-06_21-16](https://user-images.githubusercontent.com/1557255/194467261-d3ffd404-7eef-475f-9cc2-3991678877bd.png)

I haven't had this lockup yet on start up (tried about 20 times in a row).  Hopefully it helps.

**Comment by Jkapp76** [comment]
@kcgen I like the new U drive. I spent some time studying it and I greatly improved my portable version.

However, the lock up was not on the portable version. Happened on my standard installation.

It locked up again this morning and I have new info.

Dos Navigator goes into a screen saver after setting a minute idle. So this probably isn't Staging locking. DN2 is on drive X on my standard installation, a mounted directory with my utils in there.

I'm going to comb through it better and see if I can see any potential conflicts.

**Comment by kcgen** [comment]
> Dos Navigator goes into a screen saver after setting a minute idle. So this probably isn't Staging locking. DN2 is on drive X on my standard installation, a mounted directory with my utils in there.

nice investigation!

**Comment by kcgen** [comment]
Tentatively closing.

Thanks to @Jkapp76 for noting that this is due to DN2 hanging after looking for it's missing screen savers (in the depth-limited Z-drive) after 1 minute of idle.

**Comment by Jkapp76** [comment]
@kcgen 
![Screenshot 2022-10-08 000312](https://user-images.githubusercontent.com/89743985/194687325-28dcdd04-d4ea-45d8-a401-e8538188c495.png)

I'm still occasionally hanging up at startup.
nothing in drivez
I removed many utils too, running lean.
Still rarely happens... but it happens.
