### ISSUE TITLE
Write a new conf file in the language queried by locale

### ISSUE THREAD

**Issue by Burrito78** [dosbox-staging/dosbox-staging#2003]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Different version than latest?

DEV

### What Operating System are you using?

Mac OS

### Is your feature request related to a problem? Please describe.

Initial config file is in english on a german macOS when starting with default settings.

### Describe the solution you'd like

Config file is written from the same translation file that is automatically selected.

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by Kappa971** [comment]
It has already been done here: https://github.com/dosbox-staging/dosbox-staging/pull/2001
Doesn't it work on Mac? Works on Windows and Linux (tested on Debian 11).

**Comment by Burrito78** [comment]
I tested this on my other system and it didn't work but now on my macBook with macOS 11.7 it works using latest main.

Will retest on the other system to be sure but it should work. Closing this for now! 

Thanks for the hint @Kappa971!
