### ISSUE TITLE
Meson fails at setup in src/misc/meson.build

### ISSUE THREAD

**Issue by MrMisanthrope** [dosbox-staging/dosbox-staging#2004]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Different version than latest?

Git main

### What Operating System are you using?

Linux x86_64

### If Other OS, please describe

Linux version 5.10.0-15-amd64 (debian-kernel@lists.debian.org) (gcc-10 (Debian 10.2.1-6) 10.2.1 20210110, GNU ld (GNU Binutils for Debian) 2.35.2) #1 SMP Debian 5.10.120-1 (2022-06-09)

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Meson version reported from command line: 0.56.2
Debian version: 
    meson:
      Installed: 0.56.2-1
      Candidate: 0.56.2-1
      Version table:
         0.61.1-1~bpo11+1 100
    

`$ meson setup build`
src/misc/meson.build:30:0: ERROR: Invalid use of addition: can only concatenate list (not "str") to list

...and will fail again at
src/misc/meson.build:37:0: ERROR: Invalid use of addition: can only concatenate list (not "str") to list

Fixed with manual changes to src/misc/meson.build
Line 32: **libmisc_sources + 'messages.cpp',**
to
Line 32: **[libmisc_sources, 'messages.cpp'],**
and
Line 39: **libmisc_sources + 'messages_stubs.cpp',**
to
Line 39: **[libmisc_sources, 'messages_stubs.cpp'],**

### Steps to reproduce the behaviour.

1. Follow the build instructions.
2. Fail.

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by kcgen** [comment]
Thanks for the report, @MrMisanthrope.
Can you try the latest `main`?

**Comment by kcgen** [comment]
Fix confirmed by @kklobe 👍
