### ISSUE TITLE
Add new palette options

### ISSUE THREAD

**Issue by Jkapp76** [dosbox-staging/dosbox-staging#2014]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Different version than latest?

0.80 alpha

### If Other OS, please describe

win11

### Is your feature request related to a problem? Please describe.

The only problem is getting the exact colors for a few obscure old 80's games.

### Describe the solution you'd like

I'm suggesting a few more color palettes for Staging.
I found one usable palette online
#000000 #0000aa #00aa00 #00aaaa #aa0000 #aa00aa #AAAA00 #aaaaaa #323232 #5555ff #55ff55 #55ffff #ff5555 #ff55ff #ffff55 #ffffff

*I personally just refer to this as (alternate PCJr palette) but online it was referred to as (low-intensity colors on non-IBM monitor) It pretty much just swaps the brown for dark yellow,

I also created one myself with a boosted contrast because mine always had such vivid colors. It's like maxing out your contrast knob.
#000000 #0000A8 #008C00 #008686 #9D0000 #970097 #8C3600 #939393 #545454 #4B4BFF #23FF23 #1AFFFF #FF3B3B #FF32FF #FFFF0A #ffffff

*I call this Default colors with increased contrast. (vivid might be okay too) Very colorful.

PCJr Palette (from Pcjr Magazine) I cloned the colors from PCJr magazine screenshots!
#000000 #0D1B9E #146626 #639F7A #AD1F13 #7A0EA1 #FFB139 #94B1C1 #4E4075 #3756E2 #8BAF65 #9CC4E3 #D13321 #DE24AD #F7E36F #EFF1ED

CGA Palette (from pcjr Magazine) Same as above but for CGA machines. 
#000000 #0D1B9E #146626 #3B8CC4 #AD1F13 #7A0EA1 #8F8034 #94B1C1 #4E4075 #3756E2 #8BAF65 #9CC4E3 #D13321 #DE24AD #F7E36F #EFF1ED

### Describe alternatives you've considered

The old Dos version of the MESS PCJr emulator gets these dark weird colors like this. I think this color depended on the monitor brand and old PC hardware. 

### Code of Conduct & Contributing Guidelines

- [X] #2015

**Comment by Jkapp76** [comment]
![caswolf004](https://user-images.githubusercontent.com/89743985/194970202-22f76948-cb3d-47c1-b397-82af06996dbe.png)

**Comment by Jkapp76** [comment]
![jm002](https://user-images.githubusercontent.com/89743985/194978287-274cccad-4fc6-474d-8152-08c60dc114bf.png)

**Comment by Jkapp76** [comment]
These games actually get different colors with CGA emulation. But Castle wolfenstein only has the 16 color level screen graphics in PCJr mode. And Jumpman only has the 3-voice music on PCJr (and non-composite 16 colors). So I think it's cool to get the most out of these systems.

**Comment by Jkapp76** [comment]
![wof004](https://user-images.githubusercontent.com/89743985/194979918-ab646969-cbd2-432f-bc1e-4fdabf901be6.png)

**Comment by Jkapp76** [comment]
It would be really cool to change the palette from the command line. Then we could just add that info to a .Bat file and run with it.

I really only know of a couple games that need such an option though.

**Comment by Jkapp76** [comment]
![f451001](https://user-images.githubusercontent.com/89743985/194987351-4878e576-718a-4a28-a3e2-628e3465045b.png)

I would say all the graphics on Fahrenheight 451 look better on PCJr with the alternate palette. The brown looked bad. Dark yellow looks nice.

**Comment by johnnovak** [comment]
Have you played around with the `ibm5153` palette and the various contrast settings? Also, with `tandy` you can fine tune the look of the brown/dark-yellow colour. `tandy-warm` is very nice too as it simulates the actual colours displayed by these old monitors, but probably not exactly what you're looking for.

We can include one or two PCjr variants for sure, maybe we can even make it parametric like the `ibm5153` if the parameters would affect a subset of colours.

For global brightness, contrast, saturation and white balance we'll eventually introduce "monitor controls" tweakable via the GUI. But that depends on the multi-pass shader support feature, so it will take a while...

**Comment by Jkapp76** [comment]
@johnnovak I'm using the crt-hyllian-3d.glsl shader. It's my current go-to for these ancient games.
I have used all of your palette options and I use quite a few regularly. 

I really only have a peeve with Castle Wolfenstein. It's one game my dad bought me in the 80's that I played a bit on real hardware and can't seem to get the colors I'm used to easily. The game looks as good or better on CGA, but PCJr seems off. I was happy to see the colors this alternate palette gives. It's dark red and ugly yellow looks very close to me. And only one color has changed.

I always had cheap no-name aftermarket components in and on my computers. So, when this site said only better IBM brand monitors could get brown and lesser monitors get dark yellow I felt I was on to something. And You are the person I wanted feedback from about this.

I don't have my hardware any more to test this, but these ugly colors look close.

**Comment by Jkapp76** [comment]
![cw_007](https://user-images.githubusercontent.com/89743985/195181883-0eb0c7d8-f2fe-4e6a-939e-66201de53082.png)
I will say your IBM 5153 is super good too!

**Comment by Jkapp76** [comment]
@johnnovak Maybe something like this screenshot above is what I remember? It's close enough using your palette that It could be right.

**Comment by Jkapp76** [comment]
![btr001](https://user-images.githubusercontent.com/89743985/195190847-0bca2e27-e81d-4340-9cda-586f1307e53d.png)

**Comment by Jkapp76** [comment]
![Screenshot 2022-10-11 212206](https://user-images.githubusercontent.com/89743985/195227408-6a22eb95-109d-48b9-ab80-788f9ffef24b.png)

**Comment by Jkapp76** [comment]
![brown](https://user-images.githubusercontent.com/89743985/195234532-452c3014-3e77-4f37-b34d-49d59fc706f3.png)

**Comment by Jkapp76** [comment]
![cw013](https://user-images.githubusercontent.com/89743985/195244854-0fce3ecc-e9b5-4bc0-80b8-5fdd460020fa.png)
![cw015](https://user-images.githubusercontent.com/89743985/195244871-67d78681-5dc3-4f2c-8454-4c640884128a.png)

The game is winnable LOL

**Comment by Jkapp76** [comment]
![tumblr_8ee9b102f7f8edd1ed6a9a5106469bee_a6c252dc_540](https://user-images.githubusercontent.com/89743985/195503795-b27da2a5-0c70-4355-97fb-3a657f354e62.jpg)
I typed castle wofenstein PCjr in a search and found this picture.

**Comment by Jkapp76** [comment]
![mine01](https://user-images.githubusercontent.com/89743985/195645591-b90099be-6b3c-46b2-bae0-34b725270db6.png)
![mine02](https://user-images.githubusercontent.com/89743985/195645602-dd071d09-f1a3-4e65-a053-66acda623553.png)

This is pretty nerdy, but I downloaded PCJr magazine and found all 16 colors from different screenshots and created a palette from those images. These colors have the alternate yellow and grey, but I also made a standard CGA palette if anyone is interested.

#000000 #0D1B9E #0D601C #639F7A #AD1F13 #7A0EA1 #E5BA38 #94B1C1 #CA5815 #3756E2 #8DB35E #529AC7 #C21555 #DE24AD #F4E370 #ffffff

**Comment by Jkapp76** [comment]
@kcgen I really like my increased contrast CGA palette. 
I'm hoping for feedback on the two PCJr palettes. I'm not sure about the dark grey on those either. I somehow lost my winning screenshot on pcjr, but everything that was brown on CGA was the dark grey on pcjr. ugly. I could swap that dark grey for the original lighter dark grey of CGA on pcjr but I want it perfect, not wrong. It's weird that the colors are different on pcjr with CW.

**Comment by Jkapp76** [comment]
![pcmagcga1](https://user-images.githubusercontent.com/89743985/196078569-12f9eff0-8f4b-404d-99ad-c79b6ab0e2a1.png)
Here's Jumpman using my PCJr magazine palette on PCJr.

I also added all four of these palettes to the top post to make it easy. Updated two also.

**Comment by kcgen** [comment]
Wow; these are looking great, @Jkapp76 !

I'd like to convert the internal CGA colors options into bundled resources, and then we can add yours as well.  With @johnnovak's feedback, between both of you, I'm sure the combined results will thoroughly cover the range of hardware and needs!

The directory and filenames will be very similar to the shaders:

 - `resources/cga_colors/ibm5153`
 - `resources/cga_colors/tandy-warm`
 - `resources/cga_colors/more-name`

Each with conf content:

``` ini
[cga_colors]
black = #000000
blue  = ...
green = ...
cyan  = ...
...
```

A given cga_color file will be loaded on-demand (and only if requested).

**Comment by Jkapp76** [comment]
![kings_quest_1](https://user-images.githubusercontent.com/89743985/196093765-465d13fd-57e0-428a-b4b8-32cc992d2d0e.jpg)
![bebu4e8a](https://user-images.githubusercontent.com/89743985/196093784-ac96a96d-6732-41b8-9e41-c314922ac43c.jpg)

@kcgen 
I can find pictures of real monitors getting the dark yellow instead of the brown. I don't fully understand all of this, but I think we should have this alternate palette.

You can feel free to use any of my stuff here. You can change it or whatever. I won't feel weird about it if you modify them or decide not to use one.

**Comment by kcgen** [comment]
> You can feel free to use any of my stuff here.

That's the plan! 

Would you be able to make a post (here in this thread) that rounds up (or narrows down) your 'final' set  of palettes and your suggested name(s) for them (that other users will ideally understand)? Just the lists of values; screenshots aren't needed.  Thanks!

**Comment by rderooy** [comment]
IBM tweaked the colour palette on the IBM CGA monitors such that the "yellow" displays as brown. But some other monitors (especially monitors that pre-dated CGA) did not do that and would display it as yellow.

**Comment by johnnovak** [comment]
@kcgen Converting the palettes seems like a good idea at first glance, but you'll run into complications with the parametrised palettes (e.g. ibm5153, check the config descriptions for others). These special palettes will require special hardcoded behaviour in the OSD as well (e.g. to display a slider for the tweakable parameter in the UI somewhere).

For this reason, I'd personally just leave them hardcoded as they are now; IMO the complications make the whole effort not really worth it. Going down the route of adding some kind of generalised support for parameters in the resource files, then displaying those in a generic way in the OSD would be a huge overkill for just a few special parametric palettes.

Alternatively, you could convert to resource files the non-parametric palettes only; perhaps this would be the best trade-off?

@Jkapp76 Certain CGA monitors displayed dark yellow instead of the special brown colour. This behaviour is well-documented, please read the relevant Wikipedia entries on CGA/EGA for details. On certain Tandy monitors there was a knob to continuously tweak this colour from dark yellow to brown (my parametric tandy palette fully emulates this; no need for further palettes if you only want to get a dark yellow).

I'll review and test your proposed palettes later this week, but trying to mimic the colours of old magazine photographs doesn't make a whole lot of sense (there are too many stages where the colours get distorted, the choice of film, exposure, white balance, printing process  etc... and I assume you are using magazine scans, and we know nothing about the colour profile or calibration of the scanner... In the end you might end up with some cool looking but totally random colours. I'm inclined not to include such palettes, that's what the support for user-provided palettes are for. But we'll see, and thanks for your efforts, regardless :) )

**Comment by kcgen** [comment]
> These special palettes will require special hardcoded behaviour in the OSD

That sounds painful - and with that foresight I fully agree it makes sense just to leave it for now.

The benefit of externalizing them is that user can easily adapt them, similar to adjusting the R, G, and B knobs on a display.

For example, someone using the ibm5153 palette might have always turned down the blue knob when playing a submarine game (maybe making it darker) - so they could copy  `ibm5153` to `ibm5153-submarine` and lower the `blue = ` and `dark-blue =` values.

Then in the OSD, their custom `ibm5153-submarine` CGA palette would be among the list to pick from.  But yes: let's wait until the OSD basics are in place, and then can explore the constraints - for example, if the OSD's choices are compile-time only (using macros or `constexpr` lists), then yes: the set of resources isn't locked in at compile time).

**Comment by Jkapp76** [comment]
I just saw on Wikipedia that a company created  a mod years ago for pcjr that makes it compatible with Tandy 1000 software.

This could be interesting to emulate. I always thought it would be nice if the Tandy 1000 would play all the PCjr games, but this would be about the same.

I have a friend that used to modify old PCjr games to work on Tandy. He said the games checked for one of three things before utilizing 16 colors and 3-voice sound.

**Comment by rderooy** [comment]
You can already emulate either a PCjr or Tandy 1000 in DOSBox. So why bother with such emulation if all you need to do is use the correct machine type? e.g. `machine=pcjr` or `machine=tandy`.

**Comment by Jkapp76** [comment]
@rderooy That's a decent point. My thinking is that most people play the CGA version of these old games and never realize the game can be played with 16 colors and/or 3-voice sound.

I played Dragonworld back in 86 and only realized the game has 3-voice music recently. So I've personally missed out because I never knew to try PCJr emulation.

I just thought making a combo of PCJr/Tandy... or ever both together with CGA would help gamers to find these features they don't know exist.

**Comment by rderooy** [comment]
Both Tandy and PCjr are backward compatible with CGA. So you can make for instance Tandy your default if you want. Pure CGA games will still show CGA, and any Tandy capable games will show in their respective mode.

Tandy is also "mostly" backward compatible with PCjr.

**Comment by Jkapp76** [comment]
@rderooy I know this. Some games, like jumpman and bruce lee only work in pcjr mode. Bruce Lee actually locks up only in pcjr mode. 

I thought a tandy/pcjr option might allow some rare games to work too with both 16 colors and 3-voice sound. 

This might be a bad idea, I'm not sure.

Dragonworld is a pcjr game cracked to run from a hard drive and fixed to run on tandy, but the game has a bug where it loses the 3-voice sound if a save is loaded. And this won't play with pcjr emulation like bruce lee. (Dragonworld was transferred from disk 20 years ago and although it includes the crack, we accidentally cracked the master disk and I've never got another clean copy to fix this... the original would keep the music after loading a save... and my copy is the same one on every game site.

**Comment by johnnovak** [comment]
> > These special palettes will require special hardcoded behaviour in the OSD
> 
> That sounds painful - and with that foresight I fully agree it makes sense just to leave it for now.
> 
> The benefit of externalizing them is that users can adapt them, similar to adjusting the R, G, and B knobs on a display.
> 
> For example, someone using the ibm5153 palette might have always turned down the blue knob when playing a submarine games (maybe making it darker) - so they could copy `ibm5153` to `ibm5153-submarine` and lower the `blue = ` and `dark-blue =` values.
> 
> Then in the OSD, their custom `ibm5153-submarine` CGA palette would be among the list to pick from. But let's wait until the OSD basics are in place, and then we can see if it's still possible to move them to resources (for example, if the OSD needs lists of things defined at compile time, then we wouldn't be able to move them to resources).

I've been thinking over this in the last couple of days, and I agree with your points above on the benefits of externalising palettes into resource files. Apart from making it easy to make a copy of an included stock palette for user customisations, it's also a lot easier to just create a new palette resource, say `resources/cga_colors/foo` then reference it in your config by specifying `cga_colors = foo` instead of having to copy/paste the colour definitions into multiple configs. It's very hard to tell palettes apart by looking at the colour definitions, so referring them by names is definitely preferred — a big benefit of the resource file approach.

But the complications with those two special parametrised palettes still stand (`tandy` and `ibm5153`), therefore I think the best approach forward would be to externalise the non-parametrised palettes (most of them), and keep the two special ones internal and hardcoded. I think this is the best trade-off when it comes to implementation complexity.

**Comment by Jkapp76** [comment]
would it be possible to externalize the tandy [**] palette? Just keep that brown color adjustable? It would be nifty to have the parametric abilities in-tact over a slightly modified palette...

**Comment by johnnovak** [comment]
> would it be possible to externalize the tandy [**] palette? Just keep that brown color adjustable? It would be nifty to have the parametric abilities in-tact over a slightly modified palette...

Please see my detailed explanation above why this is not a good idea, and would only cause complications that make it not worth it.

**Comment by Burrito78** [comment]
@kcgen Is there still anything to do here? It's not clear to me.

**Comment by johnnovak** [comment]
Nope, closing. These palettes are too niche to add as standard settings, and the user can use any custom palette now anyway. There is another ticket to turn palette presets into resource files, making user defined presets even more reusable. https://github.com/dosbox-staging/dosbox-staging/issues/2051
