### ISSUE TITLE
SonarCloud for static analysis of the source

### ISSUE THREAD

**Issue by LowLevelMahn** [dosbox-staging/dosbox-staging#2022]
is the SonarCloud a sensible extension to the static code analysis?

features like bugs, code-smells, duplicated-lines?

example: 
https://github.com/ihhub/fheroes2
![image](https://user-images.githubusercontent.com/580819/195515597-c95c2401-9414-4d8a-9262-1bd202bbe413.png)

there are so many services integrateable with github that im loosing overview :)

**Comment by Burrito78** [comment]
I think our code quality is good enough for a DOSBox clone, no need to brag about it.
