### ISSUE TITLE
Alien Incident + GUS emulation = sound stutter.

### ISSUE THREAD

**Issue by KainXVIII** [dosbox-staging/dosbox-staging#2033]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### What Operating System are you using?

Windows 10

### Relevant hardware info

i5-3570, gtx 970

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Alien Incident is a GUS native game, but sound in this game stutters and crackles, especially noticeable in fmv intro (not so much in main game). Dosbox was configured according to the wiki article https://github.com/dosbox-staging/dosbox-staging/wiki/Sound-Cards#configuration
PS - also sound volume was quite low (comparing to sb16), but maybe its a not an issue, just how GUS emulation works..

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Run the game
2. Listen.
3.

### Your configuration

```ini
[cpu]
cycles = fixed 20000

[mixer]
rate = 44100

[midi]
mpu401 = none
mididevice = none 

[sblaster]
sbtype = none
oplmode = none

[gus]
gus = true

[speaker]
pcspeaker = off
tandy = off
```

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by kcgen** [comment]
In your startup batch file, use: `mixer gus 200`

The intro movie is played using the `game/animplay.exe` program, which has inferior control over the GUS.  For example, it activates all 32 GUS voice channels on the card but only uses a single channel.  The audio drop out are also in the data itself, and not clipping or lost data no the emulation side:

![2022-10-15_18-09](https://user-images.githubusercontent.com/1557255/196013222-60729764-62ad-478d-9ec0-9bf330529279.png)

I would suggest using SB16 to play the intro movie and GUS in the game, which I've seen use up to 10 simultaneous voices (plus has zero audio issues, like you mentioned).

**Comment by KainXVIII** [comment]
> Note a perfect solution: you'll have to toggle between the two setups.

Thanks, that's how i will play this game lol
