### ISSUE TITLE
Speed-shift option

### ISSUE THREAD

**Issue by Jkapp76** [dosbox-staging/dosbox-staging#2035]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Different version than latest?

0.80 alpha

### What Operating System are you using?

Windows 11

### Is your feature request related to a problem? Please describe.

This is more of a luxury feature than a problem.

### Describe the solution you'd like

I think it would be great to have a speed-shift option. 

It would be useful to have a special key, like ctrl+F8 to temporarily change to a different cycles setting specified in the conf file.

So, if you're playing a game at 800 cycles and you want to speed quickly through a part of the game ctrl+F8 could change to your preset cycles of say, 1800. 

This would also help with testing games for compatibility. We can zip to the problematic part faster.

### Describe alternatives you've considered

I already increase cycles to speed through parts of some games. It's just hard to come back to the same starting cycles often.

This might not have as much affect with newer games that are run at max speed anyway. 

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by kcgen** [comment]
There's Alt+F12 - press and hold it.  It will fast-forward time as fast as possible, until you release it. (not the same, but maybe useful for zipping ahead).

**Comment by Jkapp76** [comment]
This is pretty good. I didn't notice this feature.
It is a bit fast for some of the old stuff I mess with, but probably 95 percent good enough.

If this feature had a cycle limit it would be ideal for old games... like waiting 250 seconds for a chest to open in castle wolfenstein. You can shoot to speed up opening, but if there's explosives inside you blow up. 
I would set this lower for tandy, pcjr and cga machines.

Just a little suggestion for certain games.

I suggested the "stop turbo after X seconds" feature that was put into dosbox-x. Mostly to zip through the intro screens in games like "I have no mouth and i must scream". But this is a bit different. Their turbo works for newer games, but staging's f12 thing works for older games.

**Comment by Jkapp76** [comment]
@kcgen This alt-f12 works good enough.

You can close this. 

It would be a nice feature, but probably not worthy of the time.

Thanks for showing me this feature!

**Comment by kcgen** [comment]
Glad it's helpful! I believe it's supported in most of the DOSBoxes, including 0.74.x and SVN.
