### ISSUE TITLE
PCJr booter game Bruce Lee crashes and staging completely exits

### ISSUE THREAD

**Issue by Jkapp76** [dosbox-staging/dosbox-staging#2039]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Different version than latest?

0.80 alpha

### What Operating System are you using?

Windows 11

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

If you boot the PCJr booter version of Bruce Lee, the game goes into demo mode and in the middle of the demo Staging exits back to desktop.

### Steps to reproduce the behaviour.

Explain how to reproduce
1.  Boot the game image
2. Press space to enter the game's start options
3. wait for the demo. It crashes soon into it after bruce kicks a few guys.

This game works in CGA mode but only has the 3-voice music and 16 colors in PCJr mode. CGA composite will make 16 colors however.

My Booter disk collection has this game in the "Other" folder. If you downloaded this collection in the past I have recently added Bruce Lee and BoulderDash to the "Other" folder just yesterday.
 
https://u.pcloud.link/publink/show?code=XZnLthVZ19hvLYcfBBfDxT4qmLeCg4G14qdy

With 86Box the game freezes.

### Your configuration

```ini
opengl
pcjr machine
```

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by Jkapp76** [comment]
Nine princes in amber fails on pcjr too. This game is made for pcjr and only has 3-voice music on pcjr.

It plays for a minute, then crashes.

**Comment by kcgen** [comment]
> Nine princes in amber fails on pcjr too

I'm running the MS-DOS preservation copy courtesy of eXoDOS + archive.org hosting (see below, with the embedded `dosbox.conf` to launch with PCjr settings).  Seems OK?

https://user-images.githubusercontent.com/1557255/197091236-aee46c54-2484-4d85-bb39-cfc432ecdbef.mp4

[:file_folder: nine_princes_in_amber_pcjr.zip](https://github.com/dosbox-staging/dosbox-staging/files/9834984/nine_princes_in_amber_pcjr.zip)

**Comment by kcgen** [comment]
> boot the PCJr booter version of Bruce Lee, the game goes into demo mode and in the middle of the demo Staging exits back to desktop

I'm running the MS-DOS preservation copy courtesy of eXoDOS + archive.org hosting (see below, with the embedded `dosbox.conf` to launch with PCjr settings).  Seems OK?

https://user-images.githubusercontent.com/1557255/197091808-c19e0f85-8541-4344-be7b-4bab04651290.mp4

[:floppy_disk: bruce_lee_pcjr.zip](https://github.com/dosbox-staging/dosbox-staging/files/9835016/bruce_lee_pcjr.zip)

**Comment by kcgen** [comment]
> This game works in CGA mode but only has the 3-voice music and 16 colors in PCJr mode. CGA composite will make 16 colors however.

Here's CGA composite mode, with the PC Speaker (MS-DOS preservation copy courtesy of eXoDOS + archive.org hosting (see below, with the embedded dosbox.conf to launch with CGA Composite settings). 

https://user-images.githubusercontent.com/1557255/197092038-99d8cd4c-aa04-4f8f-9862-8956a1ad9adc.mp4

[**:floppy_disk: bruce_lee_cga.zip**](https://github.com/dosbox-staging/dosbox-staging/files/9835021/bruce_lee_cga.zip)

**Comment by kcgen** [comment]
> DW loses the 3-voice music after restoring a save. It probably checks to see if it's a PCJr after restoring and that part wasn't cracked

I'm running the MS-DOS preservation copy courtesy of eXoDOS + archive.org hosting (see below, with the embedded dosbox.conf to launch with PCjr + composite settings). Seems OK?


https://user-images.githubusercontent.com/1557255/197094359-112b354f-94b8-4623-90a0-65f15f38c7af.mp4

[**:floppy_disk: dragon_world_pcjr.zip**](https://github.com/dosbox-staging/dosbox-staging/files/9835105/dragon_world_pcjr.zip)

**Comment by Jkapp76** [comment]
It works. I don't really understand why it works, but it works.

And yes, the 3-voice music stays after a restore for me too. After the game starts you can type "dragonpearl" and you get a complex music score. This is where I saved, and it still works.

**Comment by kcgen** [comment]
> After the game starts you can type "dragonpearl" and you get a complex music score. 

Nice tip! 🥳 Will check that out. These games have really nice Tandy music.

**Comment by Jkapp76** [comment]
Over 20 something years ago I made these disks bootable to play on my real hardware. I used PCDos 2.1. This old DOS might be the issue. I needed to download games and make them run off a floppy back then. I made everything a booter.

This version you downloaded from eXoDos is the same as mine. Accidentally cracked by my friend Dan, but still includes the crack anyway.

**Comment by kcgen** [comment]
> Over 20 something years ago I made these disks bootable to play on my real hardware. I used PCDos 2.1. This old DOS might be the issue. I needed to download games and make them run off a floppy back then. I made everything a booter.

We had an Amstrad 1640, and a handful of games - none were composite, and the few EGA games we had were a real treat :-) you had a really nice collection!

> This version you downloaded from eXoDos is the same as mine. Accidentally cracked by my friend Dan, but still includes the crack anyway.

Dan's work lives on :+1: ; and long live DOSbox!

> Back in 86 or 87 my family had game night. We hooked the pcjr up to the family tv and played through Dragonworld. Took a few weeks of playing and We had the hintbook. We had about every game. Fun times.

That's awesome to hear to hear your entire family played these games together. Sounds like it's time for game night, once again! :desktop_computer: :joystick:
