### ISSUE TITLE
Problem with double-height pixel-perfect scaling with machine=vgaonly

### ISSUE THREAD

**Issue by dreamer** [dosbox-staging/dosbox-staging#204]
This is a tracking issue for an obscure problem with pixel-perfect scaling, as described by @ant-222 in: https://github.com/dreamer/dosbox-staging/pull/185#issuecomment-593117275

> In order for optimal operation, pixel-perfect scaling needs to know the exact resolution of the original game, but RENDER_SetSize() in render.cpp does not always receive the original resolution in the width and height parameters. Here is what I have with the Dial8 demo with two DOSBox machine settings:
> ```   
> +-------------+-------------+---------+
> | Dial8 res.  | vgaonly     | svga_s3 |
> +-------------+-------------+---------+
> | 320x200     | 320x400     | 320x200 |
> | 320x240     | 320x480     | 320x240 |
> | 256x256     | 256x512     | 256x256 |
> | 376x282     | 376x564     | 376x282 |
> | 256x200     | 256x400     | 256x200 |
> +-------------+-------------+---------+
> ```
> In this test case, the behavior of svga_s3 is better suitable for pixel-perfect scaling than that of vgaonly because it allows finer-grained scaling factors, e.g. for the original resolution of 320x240 my current algorithm can upscale the image to the following dimensions:
> ```
> +-----------+-----------+
> | vgaonly   | svga_s3   |
> +-----------+-----------+
> |  320x240  |  320x240  |
> |  640x480  |  640x480  |
> |    N/A    |  960x720  |
> | 1280x960  | 1280x960  |
> |    N/A    | 1600x1200 |
> | 1920x1440 | 1920x1440 |
> |    ...    |    ...    |
> +-----------+-----------+
> ```
> In my patch for official DOSBox I tried to handle this by analysis of the double-widht and double-height flags, and allowance in certain cases of scaling factors that are multiples of 1/2, e.g.:
> ```
> 320x400 --[4x2.5]--> 1280x1000 (pixel-perfect!)
> ```
> Another important test case is a game called Veil of Darkness. Its intro (with the Event Horizon and SSI logos) features a true 320x400 resolution, that is not a double-scalled 320x200, whereas in-game is 320x200 seen by vgaonly as 320x400, but in vgaonly DOSBox does not see any difference between these modes.
> 
> Perhaps I should try to analyse the vga.draw.double_scan flag in vga_draw.cpp, but won't help in the current version because neither RENDER_SetSize() nor RENDER_Reset() is called during the transition from the true-320x400 intro to double-scanned 320x400 in-game (which is 320x200 in fact) if machine is vgaonly. If you could modify DOSBox to detect this transition and correctly to set the double_scan flag, pixel-perfect scaling would work better because it would be able to upscale double-scanned 320x400 as shown above. That is the bug I was talking about.

**Comment by krcroft** [comment]
Hit this today while testing permutations for PR 222: https://github.com/dreamer/dosbox-staging/pull/222

[dosbox-vert-stretch.conf.txt](https://github.com/dreamer/dosbox-staging/files/4364547/dosbox-vert-stretch.conf.txt)

![2020-03-21_17-49](https://user-images.githubusercontent.com/1557255/77240961-7ed8bd80-6ba9-11ea-9b0e-8d042dfce738.png)

**Comment by kcgen** [comment]
Fixed in the latest version.

![rayman_000](https://user-images.githubusercontent.com/1557255/133951515-8759106e-4366-4b0e-9a4d-83a1bb2a9c87.png)
