### ISSUE TITLE
Any ideas how I can get Windows 98 to recognize a IMGMOUNT disk on E: or D:? 

### ISSUE THREAD

**Issue by ThomasEricB** [dosbox-staging/dosbox-staging#2047]
### Are you using the latest Dosbox-Staging Version?

- [x] I have checked releases and am using the latest release.

### Different version than latest?

ww-fat32-test

### What Operating System are you using?

Windows 10

### Whats your question and how can we help?

I've managed to run Windows 98 without any errors, however it won't recognize the Diablo disc even after I do the usual add new hardware on Control Panel... Any ideas on what should I do?
![dosbox_HYJaGf5M4c](https://user-images.githubusercontent.com/9662095/198834718-0f6bafa4-b5ba-4336-ab81-159deea18841.png)

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by ThomasEricB** [comment]
![dosbox_N8TiAPTkvF](https://user-images.githubusercontent.com/9662095/198835094-e8c8aaf3-e282-4d70-9c10-93ee787427ad.png)

**Comment by rderooy** [comment]
You need to IMGMOUNT the ISO (or CUE/BIN) file before you run the BOOT command in the [autoexec] section of your dosbox-x config file, to start Win9x.

Alternatively, assuming you have another ISO (or CUE/BIN) image file already mounted and have WIn9x already booted, you can swap the file from the menus to another CD image.

**Comment by rderooy** [comment]
Forgot to add, that you also need to enable IDE emulation for the CD-ROM also. So when you do the `IMGMOUNT`, be sure to add the `-ide` option.

**Comment by ThomasEricB** [comment]
> You need to IMGMOUNT the ISO (or CUE/BIN) file before you run the BOOT command in the `[autoexec]` section of your dosbox config file, to start Win9x.

That`s what I did

**Comment by ThomasEricB** [comment]
> Forgot to add, that you also need to enable IDE emulation for the CD-ROM also. So when you do the `IMGMOUNT`, be sure to add the `-ide` option.

I still did not give -ide a chance. I'll update you here about it when I have the time.

**Comment by ThomasEricB** [comment]
@rderooy I'm happy to announce that `-ide ` works:

![dosbox_GZ4ffB0Qmm](https://user-images.githubusercontent.com/9662095/199408013-33d14f00-64bd-4299-8158-45bd54bd35ea.png)

I used the following autoexec:

```
[autoexec]
imgmount d "E:\WingCommanderProphecyUSAEurope\Wing Commander - Prophecy (USA) (Disc 1).cue" -ide -t cdrom
imgmount e "E:\WingCommanderProphecyUSAEurope\Wing Commander - Prophecy (USA, Europe) (Disc 2).cue" -ide -t cdrom
imgmount f "E:\WingCommanderProphecyUSAEurope\Wing Commander - Prophecy (USA, Europe) (Disc 3).cue" -ide -t cdrom

imgmount 0 E:\test\win98c.img -t floppy -fs none
imgmount 2 E:\test\Win98SE4.img -size 512,63,255,522 -t hdd -fs none
COUNTRY 55
KEYB br275 
boot c:
[2:37 AM]

```
