### ISSUE TITLE
How can i properly make scaled fullscreen screenshot?

### ISSUE THREAD

**Issue by KainXVIII** [dosbox-staging/dosbox-staging#2061]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### What Operating System are you using?

Windows 10

### Whats your question and how can we help?

I already know about CTRL+F5 combo which will take unscaled screenshot and save it to the capture folder, but i want fullscreen scaled screenshot (maybe even with some shader applied) and prtscreen button (or win+prtscreen combo) is barely works - often it make just a black screen capture or very late in time when the desired frame of the game has already been missed..

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by johnnovak** [comment]
Sadly, currently you cannot do this, only the contents of the raw VGA framebuffer are saved to disk. 

What we need is a second shortcut that captures exactly what you see on the screen.

**Comment by johnnovak** [comment]
Raised a separate ticket and closing this. Thanks @KainXVIII for drawing our attention on this long-standing issue again!
