### ISSUE TITLE
Dual Mouse - Bluetooth, touchpad, mapper

### ISSUE THREAD

**Issue by Torinde** [dosbox-staging/dosbox-staging#2066]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Different version than latest?

msys2-x86_64-v0.80.0-alpha-169-g7c14a

### What Operating System are you using?

Windows 10

### Is your feature request related to a problem? Please describe.

[Dual mouse](https://github.com/dosbox-staging/dosbox-staging/wiki/Dual-Mouse-Gaming) works with USB external mouse (both wired or wireless via USB dongle with proprietary interface) and works with laptop internal "mouse" Synaptics trackpoint (nubbin in the middle of the keyboard).

It doesn't work with Bluetooth mouse or with laptop internal "mouse" Synaptics touchpad (left click doesn't do anything in `MOUSECTL.COM`). Both of those work in normal "single mouse" mode.

### Describe the solution you'd like

Add support for Bluetooth mouse and laptop internal "mouse" Synaptics touchpad.

As extras:
- Add some Ctrl+C/Escape or another way to cancel mapping in `MOUSECTL.COM` - for cases where second mouse is unsupported.
- Add support for Touchscreen (in "single mouse" mode it kind-of-works... at least moving the cursor and left click. Game is unplayable without right click, but for dual mouse - `MOUSECTL.COM` map command doesn't detect touchscreen left click).
- Allow second mouse to be mapped to physical keyboard keys (via mapper or via `MOUSECTL.COM` - but user has to select which keys move the cursor, which are buttons, which are scrollwheel/tilt/etc.)
- Allow second mouse to be mapped to physical gamepad/joystick
- eventually get to a joncampbell123/dosbox-x/issues/3636

### Describe alternatives you've considered

Using USB-to-COM adapter with physical COM mouse... among other ideas: joncampbell123/dosbox-x/issues/2412
But the native Dual mouse implementation is of course much more handy!

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by kcgen** [comment]
> Allow second mouse to be mapped to physical keyboard keys / joystick movement

A bit of context: DOSBox Staging strives to use cross-platform libraries as our interface to the host, like SDL and Many mouse, to shield us from dealing with vendor-specific APIs by  Microsoft, Apple, Linux, BSD, and the relentless version treadmills in which that entails. 

So we try to use the input devices as presented to us by SDL and ManyMouse, and leave it at that. 

One option is to use your operating systems event mappers or motion mapping, (or vendors drivers and tools for keyboards and controllers), which in turn can "fake-out" downstream users of these devices.. like games and programs. 

There are some open-source tools to help with this too, like: https://github.com/AntiMicroX/antimicrox/

> "You can use this program to control any desktop application with a gamepad on Linux🐧 and Windows"

> Features: Mapping of gamepads/joystick buttons to:
> - keyboard buttons
> - mouse buttons and moves
> - scripts and executables
> - macros consisting of elements mentioned above
> - Assigning multiple switchable sets of mappings to gamepad.
> - Auto profiles - assign profile to active application window (not in Wayland note).

**Comment by FeralChild64** [comment]
I'm the one who added the dual mouse support. I'll go with your remarks one by one:

> It doesn't work with Bluetooth mouse or with laptop internal "mouse" Synaptics touchpad

For accessing multiple mice in an Operating System independent way we are using a _ManyMouse_ library, [link](https://icculus.org/manymouse/). Quote from their page: _On most platforms, it can at least make all USB mice available, but in many cases can make serial mice and built-in laptop trackpads available too._ - so it seems not every device is supported. I intend to try to do some tests (I just don't have a Bluetooth mouse at home), but I suppose this is a library limitation.

> Add some Ctrl+C/Escape or another way to cancel mapping in MOUSECTL.COM - for cases where second mouse is unsupported.

I agree this would be handful; I'm just not yet sure how to implement it nicely. Definitely on my private TODO list, just not the top priority.

> Add support for Touchscreen

There is already a feature request for it: https://github.com/dosbox-staging/dosbox-staging/issues/779
SDL2 has some support for the touchscreens, but I haven't tested it yet.
Might happen one day, but definitely not in the near future.

> Allow second mouse to be mapped to physical keyboard keys
> Allow second mouse to be mapped to physical gamepad/joystick

A lot of work, unfortunately - and I'm not sure if it would be that useful. These are functionalities I'm not planning to add, sorry.

> (issue 3636 in DOSBox X)

Lots and lots of features requested. Some of them might happen one day, who knows.

**Comment by Burrito78** [comment]
Ticket on SDL Github is dead, closing this as currently out of scope.
