### ISSUE TITLE
Add shortcut to capture what's actually seen on the screen

### ISSUE THREAD

**Issue by johnnovak** [dosbox-staging/dosbox-staging#2073]
Currently, the capture screenshot feature saves the contents of the raw VGA framebuffer to the disk (e.g. a non-aspect-ratio corrected 320x200 or 640x480 image). We should add a second shortcut to capture the image that's actually seen on the screen (post-scaling, aspect-ratio correction, and shaders).

**Comment by KainXVIII** [comment]
Thanks for creating this ticket 😊

**Comment by Burrito78** [comment]
This should be the standard capture method, imho.

**Comment by johnnovak** [comment]
> This should be the standard capture method, imho.

I agree, but keeping the ability to capture the raw framebuffer is still handy (so we need both, I think).

**Comment by rderooy** [comment]
Perhaps have the screenshot type set using a config flag?

**Comment by KainXVIII** [comment]
> Perhaps have the screenshot type set using a config flag?

Or different keycombos for different types of screenshots? ie CTRL+F5 for raw, SHIFT+F5 - for fullscreen (for example)

**Comment by rderooy** [comment]
The problem with those keyboard shortcuts is that they will end up clashing with some DOS programs. e.g. WordPerfect which uses pretty much every possible <modifier>-<function-key> combination. I know such applications are not the primary focus, but still...

**Comment by johnnovak** [comment]
Having a flawless WordPerfect experience is not really among our goals 😄 Having said that, in the new mapper I think we should use reconfigurable "meta modifier" keys. E.g. by default we use Ctrl (Cmd on macOS), Shift, etc. So say the "meta1" key is Ctrl, "meta2" Shift, and so on. Then one could reconfigure them, say "meta1" the Home, "meta2" to PrintScreen, or whatever.

Out of the box we should map these meta keys to the existing ones, but for such fringe use cases like running WordPerfect and being able to use all available shorcuts one could remap the meta keys to their liking.

But by all means we should optimise the out-of-the-box experience for our 99.99999% of our users who will run all the games, and never ever touch programs like WordPerfect 😄 In other words, we should make running such apps a possibility, but requiring such minority users to jump through some hoops should be expected.

**Comment by Burrito78** [comment]
These cards were initially marketed as Reelmagic and later the name was changed to REALmagic.

I bought a Creative Labs Encore DXR2 DVD for 600,- DM (Deutsche Mark, today that would be 430 USD).
I bought it mainly to watch DVDs on my Pentium II 266Mhz based system.

The Creative Labs card was based on the Realmagic Hardware with a different branding and software.

LGR Episode on the DXR2:
https://www.youtube.com/watch?v=Amhqdbj0vpQ

I remember to make this card regionfree, i used a software called "Remote Selector" by Erwin van den Berg.

More about that software here:
https://www.overclockers.com.au/article.php?id=367537&P=5

**Comment by johnnovak** [comment]
> These cards were initially marketed as Reelmagic and later the name was changed to REALmagic.
> 
> I bought a Creative Labs Encore DXR2 DVD for 600,- DM (Deutsche Mark, today that would be 430 USD). I bought it mainly to watch DVDs on my Pentium II 266Mhz based system.
> 
> The Creative Labs card was based on the Realmagic Hardware with a different branding and software.
> 
> LGR Episode on the DXR2: https://www.youtube.com/watch?v=Amhqdbj0vpQ
> 
> I remember to make this card regionfree, i used a software called "Remote Selector" by Erwin van den Berg.
> 
> More about that software here: https://www.overclockers.com.au/article.php?id=367537&P=5

Commented on the wrong ticket? :)

**Comment by Burrito78** [comment]
Yeah, i wondered where that post went! :)

**Comment by johnnovak** [comment]
https://github.com/dosbox-staging/dosbox-staging/pull/2078 already merged, so closing this.
