### ISSUE TITLE
Handling of STDIN (file handle to CON) from COMMAND breaks C's gets() function

### ISSUE THREAD

**Issue by datapackrat** [dosbox-staging/dosbox-staging#209]
A program is passed STDIN handle at start from COMMAND.COM, which is a handle to the CON device.

When the Enter key is pressed reading from STDIN, '\n' is supposed to be returned.  Instead, '\r' is returned, which breaks gets() (it expects '\n').  Pressing Ctrl-J will return a '\n' to finish the gets().

Demo program:  [TEST.C and TEST.EXE](https://github.com/datapackrat/DOSBOX-error-files)

C compiler (with source):  [DeSmet v3.03](https://github.com/datapackrat/Desmet-V3.03)
[More info on the compiler](http://desmet-c.com/ver_303.shtml)

If you want to track gets() through the source code, look in lib_303 in src_303.  The file CREAT3.C contains gets(), which calls _gets() (also in CREAT3.C).  _gets() explicitly looks for '\n' as end of input (Enter key).

In _gets(), getc() (also in CREAT3.C) is called with an argument of 0 (STDIN handle).  This calls read() to get input from CON.

read() is MSVER2.A.  It sets up registers and calls DOS (INT 21H) function 3FH to read the file.

**Comment by dreamer** [comment]
Uhh, sorry - I somehow missed this bug at the time it was created. When saying "supposed" to, what DOS implementation do you compare it to?

**Comment by datapackrat** [comment]
DOS 2.0 and up.

I was trying an old program under DOSBOX (both dosbox-staging and the main release), and found this.  The code worked under DOS.

I wrote a minimal program to show the bug.

The handle from COMMAND is supposed to be "cooked", not "raw" (as I remember the terminology.)  I'd have to dig out my old manuals for more.

**Comment by Akuma-Git** [comment]
When I do a simple test in PCE
```
C:\>copy con test.txt
some text
some more text^Z
        1 file(s) copied
C:\>type test.txt
some text
some more text
C:\>
```
When I do the same in dosbox-staging it breaks on the enter key instead of F6.
It does not echo the text to screen either, but writes only the first line.
```
C:\>copy con test.txt
 CON
    1 Files(s) copied.
C:\>type test.txt
some text
C:\>
```
SVN behaves the same, if this does not work, his program wont either.

**Comment by Grounded0** [comment]
I've studied string processing on DOSBox COMMAND.COM vs FreeDOS COMMAND.COM.

DOSBox COMMAND.COM processes % as %.

FreeDOS COMMAND.COM processes them like MS-DOS COMMAND.COM so %% is processed as %.

These significant differences in string processing make any modifications to DOSBox COMMAND.COM unviable if we're going to retain 100% backwards compatibility for batch files written for DOSBox during the last 20 years. Any improvements to the code may impair backwards compatibility as the overall behaviour is erratic.

My suggestion is to allow users boot directly into FreeDOS COMMAND.COM if they choose to in the future. I'm closing DOSBox COMMAND.COM related tickets based upon this analysis.
