### ISSUE TITLE
Codepage 3021 MIK - wrong character

### ISSUE THREAD

**Issue by Torinde** [dosbox-staging/dosbox-staging#2093]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### What Operating System are you using?

Windows 10

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

[Staging CP_3021.TXT](https://github.com/dosbox-staging/dosbox-staging/blob/13872698c34caff1321b241779872ceb37e7c7e9/contrib/resources/mapping-wikipedia.org/CP_3021.TXT#L95) has the following character:
0xd6	0x00d7	#MULTIPLICATION SIGN

[DOSbox-X CP3021.TXT](https://github.com/joncampbell123/dosbox-x/blob/ca87976b1933ea67c20e18c00dbecf50a30fcc64/contrib/mappings/CP3021.TXT#L236) has a different one:
0xd6	0x00a7	#SECTION SIGN

I think Section sign is correct (matches [Wikipedia](https://en.wikipedia.org/wiki/MIK_(character_set))) - and that's what I made for DOSbox-X: joncampbell123/dosbox-x/issues/2622

Also, lines 9 to 13 in the DOSbox-X file give a little bit more background info about the codepage origin/purpose.

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by FeralChild64** [comment]
@Torinde; Fix is on the way - thanks for noticing. Sorry for the mistake, I have manually created mappings for tens of FreeDOS-specific codepages, didn't even notice the DOSBox-X already has this one.
