### ISSUE TITLE
Defer use of Feedback Directed Optimization for macOS releases

### ISSUE THREAD

**Issue by kcgen** [dosbox-staging/dosbox-staging#210]
One of our goals is to use profiling data to guide the compiler's optimization of release binaries. 

Currently [the most beneficial method](https://elinux.org/images/4/4d/Moll.pdf) comes from using  externally-sampled data collected from a custom-built Linux kernel and processor supporting Intel's last-branch-record ([LBR](https://easyperf.net/blog/2019/05/06/Estimating-branch-probability)) performance monitor, also known as AutoFDO or Feedback-Directed-Optimization; versus using data collected from a profile-instrumented binary, also known as PGO or Profile-Guided-Optimization.

Using dosbox-staging's suite of 144 test cases, we have recorded this sampling data, which is then converted into the compiler's profiling format using Google's AutoFDO package: https://github.com/google/autofdo.

AutoFDO's converter needs to be built using the compiler that will take in the converted profiles, and on GitHub's macOS VM this is Clang v11.0.  Unfortunately, Clang v11 is very new and AutoFDO fails to [build with it for the time being](https://github.com/google/autofdo/issues/87). 

AutoFDO does however build with Clang v10.x, however X-Code 10.x is not available on the VM; and getting it in place would involve a tool like: https://github.com/xcpretty/xcode-install combined with an Apple account. (and lots of time.. X-Code 10.3 is 5.6 GB and takes a long time to fetch and extract). So using Clang 10.x is out of the question for now. 

When AutoFDO is fixed, we will be able to build it using Clang v11 and then use our sample profiling data to optimize macOS releases.  Until then though, we will have to make due without.

**Comment by kcgen** [comment]
Closing this issue because this is unlikely to be possible using the CI systems unless we're willing to build various packages from source (which adds time and complexity).

For example, under Linux, we run tests and collect samples on our home development machines (I'm running the latest kernel 5.6.x and latest gcc 9.3.x).  However, our release build is performed on Ubuntu 18.04 using an older compiler.  When it's autofdo package attempts to parse the samples, it fails:

``` text
E0505 18:28:00.904330  7097 perf_reader.cc:996] Unsupported event type 79
F0505 18:28:00.904508  7097 perf_parser.cc:240] Check failed: reader_.ReadPerfSampleInfo(*parsed_event.raw_event, &sample_info) 
*** Check failure stack trace: ***
    @     0x7fc424a7f0cd  google::LogMessage::Fail()
    @     0x7fc424a80f33  google::LogMessage::SendToLog()
    @     0x7fc424a7ec28  google::LogMessage::Flush()
    @     0x7fc424a81999  google::LogMessageFatal::~LogMessageFatal()
```

The solution on Linux involves adding the following to the GitHub workflow:
- install gcc 9.3.x on the release VM
- compile the `autofdo` package on the release VM
- use this custom-build `autofdo` to parse the binary and collected samples, and aggregate the `.afdo` file
- compile the release binary using gcc 9.3.x using the aggregated `afdo` file

The solution on macOS is different:

- On a linux host (doesn't have to be a CI host), build a local Clang/LLVM stack using the *exact* source tree from which GitHub's CI macOS clang is built from
- build the `autofdo` package pointing it to this custom-built Clang's `llvm-config` binary, by passing it `--with-llvm=/path/to/custom/llvm-config-<$version>`
- Then, on this linux host, use this custom-built `autofdo` to convert and aggregate the samples into a Clang-compatible profraw file.  This resulting profraw file will be /exactly compatible/ with the Clang version running on the GitHub macOS VMs.
- Host that profraw file on web-server, and pull it into the macOS release workflow passing the compiler `-fprofile-sample-use="${{ github.workspace }}/current.profraw`

This macOS solution is slightly easier because less work is done on the GitHub VM side.  However, the challenge is that the Google developers supporting the `autofdo` package are perpetually late in updating it to build with the latest stable Clang release used in the GitHub VMs.  So for example, the macOS GitHub VMs are using Clang-10 or even 11 now, while the `autofdo` package has only be updated to compile against Clang-9.   Will there ever be a window-in-time when `autofdo` supports the Clang used on the GitHub VMs?

So unfortunately based on this (frankly dismal mess), gaining the benefit of FDO optimizations will be left to those building from source.

**Comment by kcgen** [comment]
So what _can_ we do?  We can install xvfb in the GitHub CI VMs, build PGO-instrumented binaries, run a suite of test cases directly in the workflow, and then re-build using the resulting PGO profile data.

This approach doesn't optimize as well as the FDO-based builds, however it still provides a 2% to 5% speedup over what -O3 and LTO can do.

**Comment by ruijiefang** [comment]
@kcgen Mainly here because of your issue opened in AutoFDO repository, but it's interesting how PGO-based builds perform less well than FDO-based builds: Theoretically, wouldn't PGO-based builds perform better since instrumentation provides more accurate information over sampling-based approach?

**Comment by kcgen** [comment]
@ruijiefang , thanks for the fix in the autoFDO repo!

Although you're absolutely right that PGO performs exact measurements of each and every call, the mechanism to do so is also its handicap: the heavy instrumentation ultimately performs differently than an optimized binary, and its influence on the processor's performance is not easy to subtract out or compensate for. 

FDO on the other hand lets you run end-state optimized binaries, and acts 'at a distance' by periodically recording measurements provided by a hardware monitoring mechanism (which have almost no impact on the general operation of the processor in terms of branch prediction, page faults, and so on).  Both aspects mean the measurements are far less tainted and influenced versus the PGO measurements.

**Comment by ruijiefang** [comment]
@kcgen Thanks for the insights! This is interesting :-D
