### ISSUE TITLE
Soundblaster audio swaps left and right continuously

### ISSUE THREAD

**Issue by digistorm79** [dosbox-staging/dosbox-staging#2106]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### What Operating System are you using?

Mac OS

### Relevant hardware info

Macbook Pro M1 Pro

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

When using Soundblaster (16 or Pro) for audio, the left and right channels continuously swap left and right, about each second. I tried GUS also and that is fine.

The latest alpha version (as of typing) has the same bug.
Version 0.78.1 does NOT have the bug.

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Use a program that produces clear stereo sound (I use Cubic Player)
2. Use Soundblaster as the playback device
3. In Cubic Player, I can control the master panning to pan everything hard left or right with F7 and F8
4. Hear the sound bounce around like crazy. If you pan all the sound hard left, it should stay left. But it doesn't, it jumps from left to right and keeps doing it.

### Your configuration

```ini
<script src="https://gist.github.com/digistorm79/876d8e68df77dfab459631bd121d8e93.js"></script>

I don't know if I'm doing this right, but my config is pretty standard.
```

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by Burrito78** [comment]
I cannot reproduce this on macOS Big Sur using Duke Nuke 3D using default dosbox-staging.conf.

I had to reverse stereo in setup which is strange but the channels don't switch from left to right and back.

**Comment by kcgen** [comment]
Thanks for the report @digistorm79 ; I was able to reproduce it with cubic player. Try the latest `main` build from CI, when it's ready.
