### ISSUE TITLE
Soundblaster PRO channel swap issue with Future Crew s/w

### ISSUE THREAD

**Issue by digistorm79** [dosbox-staging/dosbox-staging#2109]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Different version than latest?

v0.80.0-alpha-326

### What Operating System are you using?

Mac OS

### Relevant hardware info

Macbook Pro M1 Pro

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Related to [this bug](https://github.com/dosbox-staging/dosbox-staging/issues/2106) but it only seems to happen with Future Crew software, like Scream Tracker or Second Reality. I don't know for sure if a real Soundblaster Pro also does this, but my real system with CT1470 Soundblaster 16 (with midito patch to enable SB Pro compatibility) does play stereo sound correctly without swapping channels. It may have to do with the crappy routines of Future Crew, because on real hardware I can hear a lot of popping, probably because of DMA transfer inaccuracies or something.
But in the off chance that one of you programmers sees something in the code that relates to this, I still wanted to make a bug report.

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Run the Future Crew demo Second Reality and listen veeeeery carefully
2. or (this is elaborate):
3. Start Scream Tracker 3 with the -s5 option to use the Soundblaster Pro driver
4. Press F1 to open the settings screen
5. Tab all the way to the right and cursor down to enable stereo sound with the space bar (on my config it starts in mono by default)
6. Press F3 to open the instruments list
7. Press Enter to load a sample (any file is okay for demo purposes, but a file of around 64000 samples makes it easier to hear the effect)
8. Press Q to play the sample. If it plays long enough, you hear it bounce around. Alternatively, you can repeatedly press Q to play it again and it should also bounce around. This is not supposed to happen.

### Your configuration

```ini
Standard configuration.
```

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by kcgen** [comment]
definitely a regression.
Thanks, @digistorm79.

**Comment by kcgen** [comment]
@digistorm79, when you have a chance to try the latest `main`, it should be fixed.

**Comment by digistorm79** [comment]
Yes this is totally fixed.
