### ISSUE TITLE
Allow both `-` and `--` prefixes for all command line options

### ISSUE THREAD

**Issue by johnnovak** [dosbox-staging/dosbox-staging#2121]
Currently, some command line options only work with a single dash (e.g. `-opencaptures`, `-noconsole`), while some others work with either a single or a double dash (e.g. `--editconf`/`-editconf`, `--list-glshaders`/`-list-glshaders`).

While there's good reason to keep the single dash variants working for backwards compatibility, the most consistent approach would be to simply allow both single and double dashes for all command line options (that's for example what the Nim compiler and the CLI parser in the standard library does; maybe that's not strictly GNU Command Line Interface standard compliant, but I don't think that really matters...)

Also, the current handling of both single and double dash variants for the same option is very manual; the command line parser needs to be refactored to handle the two variants transparently (but be careful because the parser is also used by some of the included DOS commands, so maybe the DOSBox CLI parser needs to be separated out).

**Comment by johnnovak** [comment]
Okay, it turns out that this is easily achievable with GNU getopt. The prospect of having to roll our own CLI parser was slightly offputting (although it's not a hard thing to do, of course).

The (slightly peculiarly named) `getopt_long_only` does exactly what we need here:

> The getopt_long_only function is equivalent to the getopt_long function but it allows the user of the application to pass long options with only ‘-’ instead of ‘--’. The ‘--’ prefix is still recognized but instead of looking through the short options if a ‘-’ is seen it is first tried whether this parameter names a long option. If not, it is parsed as a short option.



https://www.gnu.org/software/libc/manual/html_node/Getopt-Long-Options.html

**Comment by johnnovak** [comment]
@weirddan455 would you be interested in this? It's a nice self-contained ticket to migrate to getopt.

**Comment by weirddan455** [comment]
Is that function available on MSVC and Mac?

**Comment by johnnovak** [comment]
> Is that function available on MSVC and Mac?

I guess finding it out is part of the task 😄 But here's some info I gathered in 5 minutes:

According to this, MSCV versions after 14 should be fine:
https://www.gnu.org/software/gnulib/manual/html_node/getopt.html

You can try compiling this for example:
https://www.gnu.org/software/libc/manual/html_node/Example-of-Getopt.html

I've just done that on macOS with both gcc and clang, and they're fine (unsurprisingly).

Ultimately, we can take one of these implementations and embed it into the project, but that should be the last resort:
https://github.com/alex85k/wingetopt/tree/master/src

**Comment by johnnovak** [comment]
Here are a few more alternatives. I think the main question is UTF-8 support; I think we want that for command line args (@FeralChild64 is the UTF-8/localisation expert here, maybe he can chime in).

getopt Windows implementation available via vcpkg
https://github.com/nanoporetech/getopt-win32

Alternative **cargs** libary (available via vckpg and meson)
https://github.com/likle/cargs

Alternative **cxxopts** library (available via vckpg and meson)
https://github.com/jarro2783/cxxopts

So I guess this needs some research, the main criteria being:

- Ideally we want getopt if it's available on Windows too and UTF-8 is supported
- If not, we need a replacement that's not overengineered, small, and supports UTF-8 on all compilers (the above suggestions seem to fit the bill)

**Comment by weirddan455** [comment]
I can take a look at this next.  I've been working on that MOVE command trying to get the parsing and (interesting?) syntax right.  I think I've finally got that part done which is maybe good practice for more parsing related stuff.

**Comment by johnnovak** [comment]
> I can take a look at this next. I've been working on that MOVE command trying to get the parsing and (interesting?) syntax right. I think I've finally got that part done which is maybe good practice for more parsing related stuff.

Glad to hear you're making progress with the MOVE command! 🎉 

Getting the command line argument handling would be a nice improvement that's long overdue, yeah.

But note I'm merely suggesting stuff that (I think) is suitable for someone new to the codebase... Whatever you fancy doing and is fun for you, of course 🚀

**Comment by Grounded0** [comment]
Connected issues and PRs:

- #2837
