### ISSUE TITLE
`viewport_resolution` regression

### ISSUE THREAD

**Issue by johnnovak** [dosbox-staging/dosbox-staging#2134]
Paging @GranMinigun 📣 

This commit broke `viewport_resolution` in an interesting way when DOSBox is started with `fullscreen = on` on **macOS with a Retina display**. I couldn't trigger the regression on Windows.

```
commit b3ddc0f27dafbe4ee86e435c61dbb76c8071ebdc
Author: GranMinigun <11149380+GranMinigun@users.noreply.github.com>
Date:   Thu Dec 8 00:31:30 2022 +0500

    Calculate DPI scaling value on window resize
```

## How to reproduce 

Start any game with the following config:

```ini
[sdl]
fullscreen = on
viewport_resolution = 960x720
```

`viewport_resolution` setting is ignored, *but* if you then switch to windowed mode with Alt+Tab, it's in effect. From that point, you can switch back and forth between fullscreen and windowed and it keeps working. So it's an init thing, apparently, but couldn't fix it in 15 mins...

If you start DOSBox in windowed mode, it always works fine.

**Comment by kcgen** [comment]
I tested viewport on that PR on Linux and on the Pi (so many tests I went a bit dizzy!) - and retested `main` here on X11 + SDL 2.24.0, with the conf setting, and it starts up properly with the viewport set.

Here's the startup log showing the first `DISPLAY:` resolution set, followed by shutdown which leaves fullscreen mode and logs the second `DISPLAY:` change:

``` text
...
2022-12-16 18:03:14.661 | MAPPER: no joysticks found
2022-12-16 18:03:14.663 | MAPPER: Loaded default key bindings
2022-12-16 18:03:14.737 | SDL: Using standard SDI (auto) display refresh rate of 60 Hz
2022-12-16 18:03:14.819 | DISPLAY: Text 640x400 (3h) at 70.087 Hz VFR, scaled by 1.5x1.8 to 960x720 with 1.2 pixel-aspect
2022-12-16 18:03:16.285 | SDL: Exit requested
2022-12-16 18:03:16.285 | PCSPEAKER: Shutting down discrete model
2022-12-16 18:03:16.286 | GUS: Shutting down
2022-12-16 18:03:16.286 | IOBUS: Releasing 65 read and 56 write 8-bit port handlers
2022-12-16 18:03:16.286 | IOBUS: Releasing 34 read and 35 write 16-bit port handlers
2022-12-16 18:03:16.286 | IOBUS: Releasing 34 read and 35 write 32-bit port handlers
2022-12-16 18:03:16.286 | IOBUS: Handlers consumed 8624 total bytes
2022-12-16 18:03:16.409 | DISPLAY: Text 640x400 (3h) at 70.087 Hz VFR, scaled by 1.5x1.8 to 960x720 with 1.2 pixel-aspect
2022-12-16 18:03:16.435 | atexit
```

Unfortunately I only did a handful of checks on macOS and none on Windows.  This isn't the first time we've had slightly different behavior across OSes (and versions); so my hunch is that there's something slightly different in terms of order-of-operations to get the viewport setup on Windows or macOS.

Will see what @GranMinigun sees on his side - hopefully can reproduce!

**Comment by kcgen** [comment]
@johnnovak , here's what I see on macOS (non-high DPI). I'm using SDL 2.26.1. Two parts, to stay under the 8 MB attachment limit:


https://user-images.githubusercontent.com/1557255/208220871-cde00c52-066d-429e-b7f2-e0796aa0f44c.mp4


Part 2:


https://user-images.githubusercontent.com/1557255/208220877-53cbcb6c-7633-41c0-a54a-bad5ba7de4a1.mp4

**Comment by johnnovak** [comment]
Okay, so that seems to be the same behaviour @kcgen — at startup the viewport is way too small (definitely not 960x720), then when you switch from fullscreen to windowed, the `viewport_resolution` setting becomes active.

**Comment by kcgen** [comment]
Thanks for the confirmation @johnnovak; I've pushed a small change to only recalculate the DPI on window-size changes when in window-mode, as opposed to treating the "in-flight" transition from fullscreen to window mode as a "window resize".

This "in-flight" state between fullscreen and window-mode has been a cause of previous differing behavior between Linux and macOS (unfortunately).  I think the state values are fetched/set (on SDLs side) at different boundaries around events.  Just a hunch.

@GranMinigun , tests are still running well on Linux (and now on macOS).  Should if you see any problems!

**Comment by GranMinigun** [comment]
Apple...

The change doesn't seem to break anything on my side, so it should be fine.

**Comment by johnnovak** [comment]
Looks fine so far @kcgen; I'll keep an eye on it and report back if the issue comes back or is not fully fixed.

**Comment by kcgen** [comment]
Tentatively closing.
