### ISSUE TITLE
Alt-F5 screenshot capture broken

### ISSUE THREAD

**Issue by johnnovak** [dosbox-staging/dosbox-staging#2140]
I've just tried this on macOS.

1. Start DOSBox with `-noprimaryconf -nolocalconf`
2. Press Alt-F5 to capture the actual framebuffer.

This is the result I'm getting:

![image](https://user-images.githubusercontent.com/698770/208280217-8c611c07-9f13-44bd-a50d-1abb6e75e4fc.png)

**Comment by GranMinigun** [comment]
Wild guess: RGB vs RGBA?
