### ISSUE TITLE
`MORE.COM` sometimes hides local mounted filesystem

### ISSUE THREAD

**Issue by kcgen** [dosbox-staging/dosbox-staging#2144]
Reproduce with:

1. Launch `dosbox .`, inside the source directory.
1. More the README: `C:\> more README`

    ![2022-12-18_18-29](https://user-images.githubusercontent.com/1557255/208336204-85ea3306-f58a-4bb1-b97c-93b178d916aa.png)

1. Press space once to scroll a page, then `q` to quit.
   Now list  the local C: with `ls` or `dir`:

    ![2022-12-18_18-29_1](https://user-images.githubusercontent.com/1557255/208336220-e7686256-1019-453c-9419-67a65fc62996.png)

1. The filesystem might be empty.

This version of MORE doesn't exhibit it (Feb 2022): e9a4baa3544dfb6f2561bdd644ee7c3a285c5b86 (good)

This is where the problem starts (Oct 2022): c8a04435cc4b8faed55833f64684d8a67f9d5570 (bad)

Interestingly, if you quit on the very page - the filesystem is intact.  But then try MORE once more and quit on the first page, and the filesystem will be dropped.

I was also able to get similar behavior by using it in a pipe, like: `type FILE | MORE`.

Curious what you can find, @FeralChild64 :+1:

**Comment by kcgen** [comment]
A bit more info: if C:\ is mounted _after_ startup, then it's OK.
For example:

```shell
Z:\> mount c .
Z:\> c:
C:\> more README
```

Then subsequent `ls` and `DIR` both list C:\ contents.

Contrast this with mounting C:\ via directory argument into the DOSBox Staging executable: `dosbox .`

It seems that the pipe's temporary file might not be setup right on the latter case?

**Comment by FeralChild64** [comment]
First observation: it seems to happen only if _startup_verbosity_ is set to _auto_. Any other settings makes it impossible to reproduce for me.

**Comment by FeralChild64** [comment]
Fails inside `DOS_Drive_Cache::OpenDir`, or somewhere even deeper.
