### ISSUE TITLE
Absolute touchscreen input not working anymore in v0.80

### ISSUE THREAD

**Issue by codeflorist** [dosbox-staging/dosbox-staging#2151]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### What Operating System are you using?

Windows 11

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

I've been playing lot's of old games using dosbox-staging on my Surface Pro 6 using touchscreen. Up until v0.79 touch input works in an absolute fasion, meaning the cursor is moved and a left mouseclick is produced, anywhere the screen is tapped, without the need to move the cursor around. This is a godsend for many old DOS adventure- and rpg games, since they are perfectly and convenietly playable just like native touchscreen apps. A really great way to relive those classics!

In v0.80 touch input controls the mouse in a relative instead of an absolute fashion, meaning the mouse cousor is dragged around just like with a trackpad. This is not only inferior to the absolute control (at least for these types of games), it also has a fatal flaw. It produces a mouse-click immediately when touching the screen - even if i just want to move the cursor - producing many anwanted clicks and making touch-input almost useless.

I know, touchscreen input does not seem to be a great priority for dosbox-staging at the moment, but since (at least for my usecase) this is a bit of a regression, it would be great, if absolute touchscreen input would still be possible in v0.8 and up.

Ideally there should imho be a config option to switch between absolute and relative touch input. In addition relative mode could be greatly improved, if cursor-movements do not produce any clicks, and only a single tap registers as a click. 

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Use a touchscreen Windows device (like Microsoft Surface)
2. Launch a mouse-controlled game
3. In v0.79.1 the cursor moves to and clicks at the tapped position. In v.0.80 the cursor is being dragged around like via touchpad.

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by johnnovak** [comment]
@FeralChild64 ?

**Comment by GranMinigun** [comment]
Try to change `mouse_capture` setting to `seamless` (if you don't see it, then regenerate configuration file with `config -wc` - note that this will erase all your custom comments, if you have any). That was the old default, and likely the reason it worked for you.

**Comment by FeralChild64** [comment]
Another thing which might fix you problem is to change `mouse_raw_input` to `false`, also in `[mouse]` section. Here the default has also changed.

**Comment by codeflorist** [comment]
> Try to change `mouse_capture` setting to `seamless` (if you don't see it, then regenerate configuration file with `config -wc` - note that this will erase all your custom comments, if you have any). That was the old default, and likely the reason it worked for you.

That did the trick! Awesome, mamy thanks!

**Comment by johnnovak** [comment]
Added the "documentation" tag and reopening because this is something important that needs to go into the yet-to-be-written user manual.

**Comment by Burrito78** [comment]
Will get linked in new doco issue so it won't get forgotten.
