### ISSUE TITLE
Cursor capturing issue on macOS

### ISSUE THREAD

**Issue by Burrito78** [dosbox-staging/dosbox-staging#2170]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### What Operating System are you using?

Mac OS

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

If the cursor is in the Dock on macOS while starting up Staging the mouse is neither working in game nor the host OS. Its still visible on the Dock.

On mouse click, the cursor is working again on the host. Only when clicking inside the Staging window then the cursor is captured correctly.

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Start v0.80.0 (default config) using Spotlight while hovering the mouse cursor over the dock area. 
2. Host mouse cursor is still visible but frozen.
3. Click once to unfreeze the mouse on the host.
4. Click inside DOSBox window to capture mouse.

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by FeralChild64** [comment]
@Burrito78: To be clear: behavior with `mouse_capture = onclick` works correctly?

I suppose some environment might prevent applications from capturing the mouse if the cursor is not inside the window and/or application is not in focus (makes sense IMHO) - supposedly (Discord message) Linux with Wayland behaves similarly. In such case we will have to change the defaults and add a warning to config entry description.

**Comment by Burrito78** [comment]
> To be clear: behavior with `mouse_capture = onclick` works correctly?

Yes, working correctly.

**Comment by johnnovak** [comment]
Can you confirm that the fix works for you @Burrito78 ? Then we can close this.

**Comment by Burrito78** [comment]
This will certainly fix default behavior regarding this but the issue is still there if someone would configure 'onstart' in his config.

**Comment by johnnovak** [comment]
Ah okay. Maybe leave it open then for now.

**Comment by kcgen** [comment]
`onstart` mitigates the ill-fitting SDL+macOS interactions that lead to this bug report, but in exchange we've (knowingly) accepted a less ideal default experience on the Windows and Linux/BSD side.

Eventually, it would be nice to offer capture_mouse = auto`, where we can make use of `onstart` for those systems that positively support it, and fallback to `onclick` for all other environments (to be more cautious).

**Comment by FeralChild64** [comment]
That could be complicated. We know that macOS is incompatible, but on Linux there are many desktop environments - some are compatible, some not. Windows seems to be compatible with `onstart` - but for how long? What if some future „Late Winter Update” changes the system behavior at some point? IMHO `auto` would need too much constant attention to changes in various environments.

**Comment by kcgen** [comment]
> What if some future „Late Winter Update” changes the system behavior at some point

:smile: Alas; as it always does - I agree @FeralChild64 ; `onclick` is going to be the always-safe and reliable default.

Given this, I think the current approach really is the best default; and it's trivial for users to try `onstart` if they like.

**Comment by kcgen** [comment]
Maybe then, we should consider this closed? 

Otherwise we're pursuing `onstart` with the custom checks and fallbacks (indefinitely).

**Comment by johnnovak** [comment]
> Maybe then, we should consider this closed?
> 
> Otherwise we're pursuing `onstart` with the custom checks and fallbacks (indefinitely).

Yeah I can live this default; at least it's a consistent experience across platforms then. I don't think I'm a huge fan of using different defaults per platform.

Intelligent `auto` mode that does things differently per platform could be maybe an exception, unless we overuse it. It can also complicate troubleshooting, documentation, and general maintenance, so I'm in favour of a consistent cross-platform experience (as much as possible).

Closing this then.
