### ISSUE TITLE
Windows 3.1x keyboard problem

### ISSUE THREAD

**Issue by pgzh** [dosbox-staging/dosbox-staging#2175]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Different version than latest?

0.80.0

### What Operating System are you using?

Linux x86_64

### Is your feature request related to a problem? Please describe.

Yes - Windows for Workgroups 3.11 has an issue with the dosbox-staging mouse that leads to a non-working keyboard.
The problem occured on real hardware also and there is a fix / patch for Windows fWG 3.11 to address this issue.
So this is *NOT* a dosbox-staging bug!

[edit by @FeralChild64 - this actually seems to be emulation problem, most likely not limited to Staging]

### Describe the solution you'd like

Include the following information in the Wiki for Windows 3.1x:

Windows for Workgroups 3.11 (and 3.11a as well) ships with a keyboard driver that gets confused by unhandled interrupts. 
After starting Windows 3.11 fWG no keyboard input is possible and even after exiting Windows, keyboard input is no longer working until restarting dosbox-staging.
Sometimes exiting Windows will even lead to a system hang.
The "normal" Windows 3.1x (without "for Workgroups") are not affected by this issue.

The issue can be fixed by installing WG0974 which updates the keyboard driver.
The update needs to be applied manually by:
1. Copying VKDA.386 to WINDOWS\SYSTEM
2. Edit WINDOWS\SYSTEM.INI
Replace the following line in the [386Enh] section
   keyboard=*vkd
with
   keyboard=c:\windows\system\vkda.386

The patch file and original description can be found here:
https://www.vogons.org/viewtopic.php?t=37380

Dosbox-X also seems affected:
https://github.com/joncampbell123/dosbox-x/issues/845

More patches/updates are also available here:
http://www.conradshome.com/win31/archive/

Most interesting seem:
WG0970: VNETBIOS.386 Corrects Real-Mode Transport Problems
WG0971: NDIS2SUP.386 Corrects Problems Restarting WFWG
WG0973: RMM.D32 Corrects 5-Second Delay When Starting Applications
WG0974: VKDA.386 Corrects Keyboard Problems
WG0990: ELNK3.386 Corrects System Hangs (Non-802.3 Packets)
WG0991: Updated NE2000.386 Allows WFWG to Start Correctly
WG0988: IBMTOK.386 Corrects Problems with Exiting WFWG
WG1001: Updated SERIAL.386 Driver for Windows for Workgroups
WG1126: Updated AWFAXIO.DLL Prevents System Hangs

Also interesting:
WFWFILUP.EXE: Updated File Manager for WFW 3.11 and Post-Year-2000 Dates
WG1129: Updated Files from the Windows NT Server 3.5 CD-ROM

All of these need to be manually installed - the WGxxxx.EXE files are only self-extracting archives that contain updated files and a README.TXT with installation instructions.

### Describe alternatives you've considered

Avoid using Windows 3.11 versions for Workgroups.

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by rderooy** [comment]
I think anyone can edit the wiki.

Regarding WFW 3.11 vs 3.11a, the **only** difference is that in 3.11a, MS removed compression support from the bundled Remote Access software, which was probably due to the Stacker lawsuit.

**Comment by FeralChild64** [comment]
>  So this is NOT a dosbox-staging bug!

I'm not sure. The description of the patch says:

```
CAUSE
=====

The keyboard controllers in these machines generate unnecessary
interrupts each time a key is pressed and released. The keyboard stops
responding because the Windows for Workgroups 3.11 VKD, unlike the
Windows 3.1 VKD, does not ignore these extra interrupts.
```

so there might be a bug in the DOSBox keyboard controller emulation code.

**Comment by pgzh** [comment]
Would it be also possible the mentioned interrupts aren't being generated by the dosbox keyboard controller, but the mouse?
I noticed keyboard input stopping after I installed the VBADOS mouse driver and using dosbox-staging 0.80.0 .
I had WfWG running before on earlier versions and the keyboard input worked.
And even without pressing a single key, WfWG hung when starting and trying to exit immediately...which of course involved moving the mouse and clicking.
I could try to reproduce the issue with new installs with and without the VBADOS driver if this helps.

**Comment by FeralChild64** [comment]
Not impossible. But the interrupts might be generated even without key being pressed, within a response to the commands issued by the guest OS.

Back then I had such keyboard problems constantly when I was trying to implement register-level access to PS/2 mouse. Unfortunately, I was unable to find out the reason of the problem - and thus PS/2 mouse is still limited to BIOS interface in Staging.

The issue on 0.80.0 is sporadic, right?

**Comment by pgzh** [comment]
No, it's not sporadic, I haven't been able to get a single character input to any text field without the WG0974 fix.
The only thing that was sporadic was the hang trying to exit Windows - 50% dosbox-staging (or the emulated Windows) just froze/hung, 50% of the time it exited to the dosbox prompt but the keyboard was not functional anymore after exiting Windows all the time.
With the fix keyboard input works, exiting works reliably and input is possible after exiting Windows.

I'll set up another WfWG installation without the fix and check if using the VBADOS driver changes anything tomorrow and report back.

**Comment by pgzh** [comment]
I've started with a clean installation to investigate and initially was unable to reproduce the issue - there's a little more involved than I thought.

A clean install of Windows (no extra drivers, no updates) works. Installing the VBMouse INT33 driver caused no problems.
Another new install of Windows with S3 Trio, VMouse and after installation SB16 drivers also works without problems.
Installing Win32s, WinG, QuickTime, ... caused no problems in both installations.

Next I wanted to change mouse-related settings in the dosbox config, but noticed I put an extra 0 in the cycles (instead of 18 000 I had 180 000 (no spaces in the real config, just here for readability).
After changing the cycles, the installation without extra drivers still worked, but keyboard input in the installation with drivers was broken again!
Changing the cycles back made it work again.

I set it back to the non-working value and ran setup to change the VBMouse driver back to the Logitech default - the keyboard worked again.

Then I ran setup again and switched back to VBMouse - keyboard working.
Change cycles - keyboard stops working.
Run setup and just select VBMouse again (keeping the already installed driver) - keyboard works again.

Change cycles - keyboard stops working.
Install the WG0794 fix - keyboard works again.
With the fix installed changing cycles does not break the keyboard anymore.

So in a nutshell: Changing the cycles in the config after installing the VBMouse driver causes the keyboard to stop working in Windows for Workgroups 3.11 without the WG0974 fix. After re-installing the driver, the keyboard works again with the modified cycles setting until changing it again.

Whenever the keyboard was not working in Windows, it also was not working after exiting Windows in the dosbox prompt (but before starting Windows it was always working since I started windows by typing WIN.COM).

Since the WG0974 fix is related to interrupts, my best guess is the VBMouse driver sets up some kind of timing information at installation and this breaks if the speed of the emulated machine changes causing some interrupt to go uncaught by the VBMouse driver and the Windows keyboard driver tries to handle it and jumps off into never-never land.
So to me this is starting to look like a dosbox-staging bug, too...

**Comment by FeralChild64** [comment]
I confirm that the problem happens with a very high cycle count - but it is completely random for me, and happens even using built-in Windows mouse drivers (Logitech, PS/2). Must be something related to timing.

I have edited the issue to reflect that this is most likely a bug.

**Comment by FeralChild64** [comment]
The current Intel 8042 (PS/2 keyboard+mouse port controller chip) emulation seems to be oversimplified:
- it inject delays even if they are not needed
- it indeed fires unnecessary IRQs
- it skips several commands
I’m not surprised some drivers are confused - I’m rewriting this part of code, hopefully it will work better.

**Comment by pgzh** [comment]
Thanks a lot for looking into this issue! I'm looling forward to testing the improved controller emulation when it's ready.

**Comment by FeralChild64** [comment]
@pgzh Just to let you know - I'm still working on it, just don't have much time recently. The whole rework is over 4000 lines of code long at this moment, so this is not a trivial task. There are still some serious problems left to resolve before I can give you the code for testing.

**Comment by pgzh** [comment]
@FeralChild64 I didn't get the impression you weren't working on this anymore - you already told me it will take some time and the fix won't be a simple one-liner.
I also read about refactoring related issues where you announced you're also working on this and the parallel work may cause implications for both tasks.
So thanks for the unexpected status update, I understand it will take it's time. Occasionally I still find time to do some hobby-coding on small projects (mostly for my own stuff), so I know how much time this stuff can consume...I really appreciate you're working on it!

**Comment by FeralChild64** [comment]
@pgzh Good news - it seems I managed to resolve the problems quicker than I thought :) Would it be possible for you to check if the branch https://github.com/dosbox-staging/dosbox-staging/tree/fc/ps2-mouse-registers-1 fixes the problem?

At this point it will print some strange WARNING logs, but that's OK - they are for testing only. The whole implementation still needs some cleanup and a lot of testing, but so far everything I tried works as expected.

**Comment by pgzh** [comment]
> @pgzh Good news - it seems I managed to resolve the problems quicker than I thought :) Would it be possible for you to check if the branch https://github.com/dosbox-staging/dosbox-staging/tree/fc/ps2-mouse-registers-1 fixes the problem?
> 
> At this point it will print some strange WARNING logs, but that's OK - they are for testing only. The whole implementation still needs some cleanup and a lot of testing, but so far everything I tried works as expected.

I just checked out the branch. As expected, I got the debugging warning messages (starting with 'XXX PS/2') and successfully installed a clean WfWG 3.11.
Running multiple times changing cycles up and down the keyboard was always working flawlessly!

I checked with dosbox-staging 0.80.1 to double-check and the keyboard stopped working immediately after changing the cycles config setting.

So the problem indeed seems fixed in your new branch, great work!

I hope you'll be able to complete the rework and get this merged back into master soon :-)
Thank you very much!

**Comment by FeralChild64** [comment]
Fix got merged to the main line. I have extended the Wiki to cover various Windows add-ons and patches I have personally tested: https://github.com/dosbox-staging/dosbox-staging/wiki/Windows-3.1x#windows-patches-and-add-ons

Closing the issue.
