### ISSUE TITLE
For serial ports, documentation has "directserial" as an option but the code uses "direct"

### ISSUE THREAD

**Issue by rrcook** [dosbox-staging/dosbox-staging#2178]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Different version than latest?

dosbox-staging, version 0.80.0-2-gdcb440822

### What Operating System are you using?

Linux x86_64

### If Other OS, please describe

Ubuntu 22.04

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

When following the documentation to set up a direct serial connection from within DOSBox, the setting is "directserial" but when using that, this error message appears in the logs.
`CONFIG: "directserial" is an invalid value for: type. Using the default: dummy`

If you instead use a setting "direct" then you get the expected behavior.

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Set up the dosbox.conf as shown in "your configuration"
2. Run dosbox
3. See the error message in the logs.
4. Edit dosbox.conf, change "direcsterial" to "direct"
5. You get the expected behavior, the serial port works with the hardware serial port.
6. Go to the file serialport.cpp, line 1317, see that the code is checking the type against "direct".

### Your configuration

```ini
[serial]
serial1       = modem baudrate:2400 
serial2=directserial realport:ttyUSB0 
phonebookfile = phones.txt
```

### Provide a Log

```text
2022-12-30 20:24:49.738 | SDL: version 2.0.8 initialized (x11 video and pulseaudio audio)
2022-12-30 20:24:49.739 | CONFIG: Loaded primary conf file /home/rrc/.config/dosbox/dosbox-staging.conf
2022-12-30 20:24:49.739 | CONFIG: "directserial" is an invalid value for: type. Using the default: dummy
2022-12-30 20:24:49.739 | CONFIG: Loaded custom conf file plain.conf
2022-12-30 20:24:49.739 | LANG: Using internal English language messages
2022-12-30 20:24:49.741 | RENDER: Using GLSL shader 'interpolation/sharp'
2022-12-30 20:24:49.741 | DISPLAY: Initialized 1776x1332 window-mode using Bilinear scaling on 1800p display-0
```

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by kcgen** [comment]
Thanks for flagging this @rrcook! This should now be fixed in `main`.

**Comment by kcgen** [comment]
Writing a new configuration file with `Z:\> config -wc` inside DOSBox Staging should produce a conf that mentions `direct` as one of the port-type options:

```ini
[serial]
#  serial1: set type of device connected to com port.
#  Can be disabled, dummy, mouse, modem, nullmodem, direct.
...
#  for direct: realport (required), rxdelay (optional).
#              (realport:COM1 realport:ttyS0).
...
#  Possible values: dummy, disabled, mouse, modem, nullmodem, direct.
```

**Comment by gragia79** [comment]
I set:
`serial1 = direct realport=ttyS0`
but if I go to consol dos and write serial it tells me that com1 is disabled.

searching around I also tried the solution
```
[serial]
serial1 = direct
realport = ttyS0
```
but same result.
my autoexec in dosbox-staging.conf configuration
is set to mount C:
```
[autoexec]
mount C /home/dos/C
C:
```
