### ISSUE TITLE
eXoWin9x emulation requirements

### ISSUE THREAD

**Issue by Torinde** [dosbox-staging/dosbox-staging#2185]
in addition to save/restore memory and CPU state - what about snapshot capabilities like Virtualbox, e.g. for the HDD/CD images, configuration changes, etc.? To have a "ROM-like" frozen state (snapshot) and subsequent storage changes to be recorded in a subsequent-state-file(s). User to be able to "merge" or not those back into the ROM frozen state (or in a copy of that).
A better description is at the [emulator requirements for eXoWin9x](https://www.retrorgb.com/interview-with-exo-pc-ms-dos-and-windows-game-preservationist.html).

_Originally posted by @Torinde in https://github.com/dosbox-staging/dosbox-staging/issues/313#issuecomment-1368709554_

Related to https://github.com/dosbox-staging/dosbox-staging/projects/7#column-10278621

From the interview:
- master Win98 install, with each game installing to its own child image. This would allow any changes to the OS folders (or the C: at all) to be captured by the child\diff image.
- dynamic images. report to the OS that there is plenty of free space available without having to make a custom image for every single game that has exactly the amount of space we need for the installed product.
- emulator that has the horsepower needed. 

My comments on the horsepower:
- Period in question - Win9x mainstream support ends in 2003, extended support in 2006, latest game I find that works under Win9x - [Age of Empires III](https://www.pcgamingwiki.com/wiki/Age_of_Empires_III#System_requirements)
- CPU: hypervisor core, for example based on [virt86](https://github.com/StrikerX3/virt86) as discussed at joncampbell123/dosbox-x/issues/1089
- GPU: multi-threaded 3dfx emulation 86Box/86Box/discussions/2909 joncampbell123/dosbox-x/discussions/3867
- GPU: hypervisor [QEMU-3dfx mod](https://github.com/kjliew/qemu-3dfx) joncampbell123/dosbox-x/issues/3405
- separately, nice to have - emulation of Aureal3D and EAX. 86Box/86Box/discussions/2795 86Box/86Box/discussions/2911 joncampbell123/dosbox-x/issues/3597

**Comment by kcgen** [comment]
Thanks @Torinde.

Windows 9x (and related era hardware) is out of scope - see: https://dosbox-staging.github.io/about/

**Comment by Torinde** [comment]
Oh, sorry. I got carried away by seeing that you track explicitly in a project the "eXoDOS features" and I remembered that interview where Win9x was mentioned as needing more from emulators than what's available already.
