### ISSUE TITLE
Pressing right side Command key inserts / character

### ISSUE THREAD

**Issue by Grounded0** [dosbox-staging/dosbox-staging#2199]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### What Operating System are you using?

Mac OS

### If Other OS, please describe

macOS 12.6.2/x86-64

### Relevant hardware info

2017 15" MacBook Pro

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

When pressing right side Command key the key press is registered but also inserts / character.

### Steps to reproduce the behaviour.

1. Start DOSBox Staging 0.80.1.
2. Press right side Command key.
3. Observe / character being inserted on the command line.

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by Grounded0** [comment]
This works properly on 0.79.1 so its a regression. I'd rather keep my right side Command key mappable as i use it in some games already.

A fix would be discovering where this got broken down with help from people like @Burrito78 . 🙂

**Comment by Grounded0** [comment]
This works properly on 0.79.1 so its a regression.

**Comment by Grounded0** [comment]
Connected tickets:
[] #2200

**Comment by Grounded0** [comment]
Connected tickets:
- #2200

**Comment by kcgen** [comment]
> This works properly on 0.79.1 so its a regression.

Thanks for this information @Grounded0. My keyboard's 'Right-GUI' button produces a forward-slash in 0.80.x but did not in 0.79.x, which bisects to, b28c10f8a8c102a32fc9a8f48a778a3137646640 that added support for the ABNT2 key on Brazilian keyboards.

**Comment by Grounded0** [comment]
Once #2209 is merged feel free to close this ticket on my behalf since i'm not following whats going on in GitHub.

**Comment by kcgen** [comment]
Thanks for flagging this, @Grounded0.
