### ISSUE TITLE
[linux] meson 57 failed raspberry pi debian 11

### ISSUE THREAD

**Issue by arrowgent** [dosbox-staging/dosbox-staging#2233]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Different version than latest?

src v0.80-1

### What Operating System are you using?

Linux ARM (Raspberry Pi)

### If Other OS, please describe

raspbian debian 11 armhf (32bit)

### Relevant hardware info

raspberry pi 4b

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

build process fails dependency version,
unable to "officially" upgrade meson
i suppose this applies to ALL debian stable variants.

```
lsb_release -a
Distributor ID:	Raspbian
Description:	Raspbian GNU/Linux 11 (bullseye)
Release:	11
Codename:	bullseye
```

### Steps to reproduce the behaviour.

Explain how to reproduce
1. 
2.
3.

### Provide a Log

```text
meson setup -Dbuildtype=release build
The Meson build system
Version: 0.56.2
Source dir: /home/pi/Downloads/BUILD/dosbox-staging/dosbox-staging-0.80.1
Build dir: /home/pi/Downloads/BUILD/dosbox-staging/dosbox-staging-0.80.1/build
Build type: native build

meson.build:1:0: ERROR: Meson version is 0.56.2 but project requires >= 0.57.0

A full log can be found at /home/pi/Downloads/BUILD/dosbox-staging/dosbox-staging-0.80.1/build/meson-logs/meson-log.txt




apt list meson
Listing... Done
meson/stable,stable,now 0.56.2-1 all [installed]
```

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by kcgen** [comment]
Grab meson 0.64.x from Bullseye's backports: https://manpages.debian.org/bullseye-backports/meson/meson.1.en.html

Or uninstall meson and ninja from Deb, and pull them in from Python PIP (as they're both PIP packages, fully up-to-date there: you'll get Meson 1.0.x).

**Comment by arrowgent** [comment]
ah thanks i will check pip3, install it in .local and try again

i try to avoid testing or backports on this system

https://pypi.org/project/meson/
pip install --ignore-installed meson

https://pypi.org/project/ninja/


 meson --version
1.0.0
pi@raspberrypi:~ $ sudo meson --version
0.56.2

pi@raspberrypi:~ $ ninja --version
1.11.1.git.kitware.jobserver-1
pi@raspberrypi:~ $ sudo ninja --version
1.10.1


compiling, will take a few minutes

**Comment by arrowgent** [comment]
compiles no issues.

thanks for your help!

**Comment by kcgen** [comment]
> meson --version
> 1.0.0

:+1: nice!
