### ISSUE TITLE
NHL 97 freezes during installation

### ISSUE THREAD

**Issue by jlnhlfan** [dosbox-staging/dosbox-staging#2250]
I wanted to try this out instead of using the old DOSBox to play NHL 97. However, I encountered a problem.

![dosbox_000](https://user-images.githubusercontent.com/31529087/214468472-4165fe72-efb3-42c5-a003-e962103507ba.png)

The game freezes during this part of DOSSETUP.EXE, and it's kind of infuriating.

The crash happens with both .iso and .bin file types. It doesn't even matter if you select a sound card or not, the game WILL freeze at this point, no exceptions.

Is there anything that can be done to fix this freezing issue, or am I going to have no choice but to give up?

**Comment by jlnhlfan** [comment]
Found the problem: I didn't have a dedicated C: drive.

**Comment by kcgen** [comment]
@jlnhlfan , glad you found the issue.

Here are my settings for the game. There are some tiny audio stutters during the intro movie, but in-game it plays very smooth without hitches.

```
[sdl]
fullscreen = true

[dosbox]
startup_verbosity = quiet

[sblaster]
sbtype = sb16
sbfilter = auto
oplmode = none

[speaker]
pcspeaker = none

[midi]
mididevice = none

[cpu]
cycles = 130000

[mouse]
mouse_capture       = onstart
mouse_sensitivity   = 160
dos_mouse_immediate = true

[autoexec]
@echo off
imgmount d cd\NHL97.iso -t cdrom
mount c .
c:
cd NHL97DOS
hockey.exe
```

**Comment by jlnhlfan** [comment]
Nice! Thanks, I will now create the .conf file.

**Comment by jlnhlfan** [comment]
By the way, I just name it "nhl97.conf", right?
