### ISSUE TITLE
DosBox ignores "mute_when_inactive" and "pause_when_inactive" options when you selecting and moving other windows.

### ISSUE THREAD

**Issue by CortexReaver** [dosbox-staging/dosbox-staging#2253]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### What Operating System are you using?

Windows 7

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

So, if you just select some another window just once these options are working fine, but when you start dragging, resizing this and also a dozen other windows (not related to the emulator) DosBox unmutes and unpauses on its own.

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Open some random windows.
2. Run Dosbox.
3. Run some game (I've tested on this one: https://store.steampowered.com/app/358220/Mystic_Towers/).
4. Start to select and resize these non-related to the emulator windows.

### Your configuration

```ini
priority            = auto auto
mute_when_inactive  = true
pause_when_inactive = true
```

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by kcgen** [comment]
@CortexReaver , when you have a chance - test binaries are here:

https://github.com/dosbox-staging/dosbox-staging/actions/runs/4030558655

**Comment by johnnovak** [comment]
Cannot reproduce.

I've tried both v0.80.1 and the latest main (`v0.81.0-alpha-169-gfd14e`) on Windows 10 and macOS (M1) -- selecting o rresizing other windows don't unmute and/or resume the paused DOSBox process.

**Comment by kcgen** [comment]
Excellent; thanks for those tests @johnnovak !

Depending on the window manager, SDL can report slightly different events to the application. I suspect on Linux, we get a couple more during the other resize events (reporting the window is exposed), which was unpausing. 

My own tests on Linux reproduced and fixed it, so these results from macos and windows should be all that's needed. 

Will merge. Thanks @johnnovak 👍
