### ISSUE TITLE
Mouse is broken with `pause_when_inactive` enabled in the config file on macOS

### ISSUE THREAD

**Issue by johnnovak** [dosbox-staging/dosbox-staging#2255]
Paging @FeralChild64. See the reproduction steps. I'm only experiencing this on macOS; Windows 10 is not affected.

Another interesting thing is that the bug only manifests if `pause_when_inactive = true` is set in a config file. If you launch DOSBox without setting this to true, and then set ``pause_when_inactive = true` from the command line, it works correctly.

So it's a bug that only manifests on init, and only on macOS. Spent 30 mins trying to figure it out, but that mouse handling code is really complex...

### What Operating System are you using?

macOS Monterey 12.5.1

### Steps to reproduce the behaviour.

1. Put pause `pause_when_inactive = true` in your config.
2. Start DOSBox in windowed mode and launch something that uses the mouse.
3. Click on the DOSBox window to capture the mouse -- note that the window title now contains the text "mouse captured".
4. Press Cmd+Tab to switch to another window -- DOSBox is paused as expected and the title bar text has changed.
5. Click on the DOSBox window again with the mouse, or Cmd+Tab back to it -- note that the mouse doesn't work, and the title bar text has not changed; it's still in the "inactive window" state. The emulator has resumed working, though, and there is sound, and the keyboard works, but not the mouse!
6. You can fix this by switching to fullscreen, the mouse will start working. Switching back to windowed mode again fixes the title bar text issue too.

**Comment by FeralChild64** [comment]
Unfortunately, I don’t have a Mac. Are you able to check if MOUSE_NotifyHasFocus is called at the beginning of point 5? It looks to me like the mouse emulation is not aware that we have focus again.

**Comment by FeralChild64** [comment]
First fix attempt: https://github.com/dosbox-staging/dosbox-staging/tree/fc/mouse-focus-fix-1

Seems to be work on my system, but I need to test it more. Now I'm really going sleep :)

**Comment by kcgen** [comment]
branch is working well on my side too, @FeralChild64 (X11 + KDE)

**Comment by johnnovak** [comment]
Confirming that the fix works on macOS too @FeralChild64. Great job! 🎉
