### ISSUE TITLE
Duke Nukem 2 triggers assertion in Sound Blaster

### ISSUE THREAD

**Issue by GranMinigun** [dosbox-staging/dosbox-staging#2256]
Running Duke Nukem 2 triggers the following assertion: ```dosbox: ../src/hardware/sblaster.cpp:940: void PlayDMATransfer(uint32_t): Assertion `((void)"Frames should never exceed samples", frames <= samples)' failed.```

To reproduce, just watch the intro (where it shows Neo LA) or load into gameplay. If it doesn't trigger, make sure Sound Blaster sounds are enabled in the options menu (accessible via the game's main menu).

**Comment by johnnovak** [comment]
Have you tried to bisect it? Does the problem happen in other DOSBox variants?

**Comment by kcgen** [comment]
See it; ty @GranMinigun.
