### ISSUE TITLE
`/?` command line parameter handling weirdness

### ISSUE THREAD

**Issue by johnnovak** [dosbox-staging/dosbox-staging#2263]
1. Execute any built-in DOS command with the `/?` parameter (e.g. `DIR /?`), or any 3rd party executable that supports the `/?` param to print out some built-in help (e.g. `DOSMID /?`)
2. Observe that the help for the invoked command is printed out.
3. Start DOS Navigator, then execute the same `SOMEEXE /?` command.
4. Note that regardless of the invoked command, the help for the built-in DOS command shell is printed out, without exception (same as invoking `COMMAND /?`)

**Comment by johnnovak** [comment]
No it's not path related; just tried it with `-noprimaryconf` and I'm getting the same results. This is my `PATH`:

```
PATH==Z:\;y:\dos
```

Just try it and you'll see, there's some weird incompatibility/special case handling that breaks the `/?` under DOS Navigator. It's not a huge deal, but still, a bug...

**Comment by kcgen** [comment]
Good eye catching this @johnnovak !
