### ISSUE TITLE
Installer - to provide all three builds 32-bit MSVC, 64-bit MSVC, 64-bit MSYS2

### ISSUE THREAD

**Issue by Torinde** [dosbox-staging/dosbox-staging#2267]
- x86 - releases after 0.78.0 don't have 32-bit zip
- installer setup.exe - it offers choice between MSVC x64 and MSYS2 x64. Suggestion: put both executables in a subfolder, so that user can switch at any moment and not only at the moment of installation.
- installer setup.exe - on x86 Windows it installs unworkable (x64) versions. Suggestion: install the x86 build instead if host is x86 or put the 32-bit executable in a subfolder, so that user can manually launch it later, if required.

_Originally posted by @Torinde in https://github.com/dosbox-staging/dosbox-staging/issues/2258#issuecomment-1417688661_

**Comment by kcgen** [comment]
The MSVC workflow *is* building 32-bit binaries and uploading them as artifacts, however they're just not shipped in the Windows packages.

Adding them should be relatively straight forward (the dots needs to be connected into the MSYS2 workflow, which currently fetches the 64-bit build and bundles it along-side the MSYS2 binaries).

In general we don't want to take on extra work (code hacks or more CI complexity) to support EOL'd operating systems; but in this case were *are* interested in running those CI builds and it's not much work to toss those builds into the Windowspackages.

Flagging with help and good first issue.

The downside is user confusion: some users on Windows 10 or 11 /will/ choose the 32-binaries if they see it, despite those operating systems now being exclusively 64-bit. So  my only suggestion is to add explicit wording for these 32-bit MSVC builds indicating they should only be considered for those on Windows 8.1 or earlier.

**Comment by Grounded0** [comment]
Anyone running a legacy OS and/or hardware have to jump a couple extra hoops. Applies also for macOS where legacy support is through MacPorts. First x86-64 hardware was released in 2003 or 20 years ago so we're covering 99.5% of the total Windows installed base already.

**Comment by Kappa971** [comment]
Windows 10 should still be available for 32 bit PCs (or did they retire it and I didn't notice?) however I'm wondering which PC would run Windows 10 32 bit today. If I'm not mistaken the latest 32-bit desktop CPUs are Intel Pentium 4 and AMD Athlon XP CPUs from 2003-2005. Athlon XP can't go beyond Windows 7 because they don't support necessary instructions (and also they are slow for Windows 7, better Windows XP), with Pentium 4 32 bit I think it's possible to install Windows 8. So I think Windows 10 32 bit only makes sense for Pentium 4 64 bit (socket 775) and maybe some early versions of AMD Athlon 64 where it isn't possible to install Windows 10 64 bit.
So:
AMD Athlon XP: Windows 7 32-bit
Pentium 4 32-bit: Windows 8 32-bit
Pentium 4/AMD Athlon 64 (early models): Windows 10 32-bit
I don't think Athlon XPs and Pentium 4 32 bits are enough to have adequate performance in DOSBox Staging, maybe Athlon 64s and Pentium 4 64 bits neither, so a 32 bit version of DOSBox Staging doesn't make sense... (If I have I wrote something wrong, correct me).
As for MSYS2 vs MSVC, months ago I noticed a performance difference in favor of the MSVC build, but haven't tried it since and maybe things have changed.

**Comment by kcgen** [comment]
yup, even the old Core-2-Duo is 64-bit! And yet I don't see it any of Microsoft's supported hardware lists:

https://learn.microsoft.com/en-au/windows-hardware/design/minimum/windows-processor-requirements

> Windows 10 should still be available for 32 bit PCs (or did they retire it and I didn't notice?

I think it's still out there. Microsoft started phasing out support for 32-bit Windows 10 in 2020:

 https://www.neowin.net/news/microsoft-is-beginning-to-phase-out-32-bit-support-for-windows-10/

And apparently an "Official end of supply" notice was sent out to manufacturers (but I can't find it.. only mentioned here: https://answers.microsoft.com/en-us/windows/forum/all/windows-10-32-bit-end-of-supply-official-notice/9cd8073f-e630-41dc-9fb2-ccfd52c8bfdc)

**Comment by Kappa971** [comment]
But, if I understand correctly, Microsoft still releases updated builds of Windows 10 32 bit, while Windows 11 is 64 bit only (along with the absurd minimum requirements)

**Comment by kcgen** [comment]
> We could add instructions to Wiki how to build your own x86 binaries for Windows though.

The builds notes have 32-bit fully covered :+1:

Meson: no change for Meson, regardless if you're on 32-bit ARM on Linux or 64-bit x86 Windows.

MSVC: there's a GUI pull-down to select either debug or release, as well as 32-bit or 64-bit.

**Comment by kcgen** [comment]
> But, if I understand correctly, Microsoft still releases updated builds of Windows 10 32 bit, while Windows 11 is 64 bit only (along with the absurd minimum requirements)

Yes, the MSVC CI chain is currently compiling for 32-bit hosts (and has always done so since we added it).  We just need to add those binaries into the zip and setup packages.

**Comment by Torinde** [comment]
Last 32-bit CPUs are some lower end models of Sempron (2006), VIA C7 (2007), Atom N280 (2009), Atom Clover Trail (2013).
Some laptops and tablets with those or even with 64-bit capable CPUs were released with 32-bit Windows due to storage and/or memory constrains, I assume.

Win10 32-bit is still fully supported, updated and even sold-at-retail by Microsoft. What stopped is offering new OEM devices with it since 2020:
> Starting with Windows 10 version 2004, Microsoft will require new OEM devices to use 64-bit processors, and will therefore cease the distribution of x86 (32-bit) variants of Windows 10 via OEM channels. The 32-bit variants of Windows 10 will remain available via non-OEM channels, and Microsoft will continue to "[provide] feature and security updates on these devices".[[272]](https://en.wikipedia.org/wiki/Windows_10#cite_note-289)

So, on everything below Win11 - one more checkbox can be added:
| [ ] Run 64-bit MSVC release binary (instead of 64-bit MSYS2 binary) as the default binary
| [ ] Run 32-bit MSVC release binary (instead of 64-bit MSYS2 binary) as the default binary
![image](https://user-images.githubusercontent.com/97228894/216900898-23fdfb61-5593-4228-a0db-c4e4ed63e690.png)

So, only users who know/need it will click it?

Nice to have, although not crucial, on 32-bit hosts the 64-bit builds to be skipped/grayed out (if Staging installer has such host-detection capabilities):
![image](https://user-images.githubusercontent.com/97228894/216905632-77c3e646-db19-4482-bde8-36eed497b8fd.png)
There is also an option to have all builds "discoverable" after installation:
![image](https://user-images.githubusercontent.com/97228894/216905830-47d4e20b-f36b-448c-a3ee-77e008189d57.png)

**Comment by Grounded0** [comment]
Seems like adding x86 MSVC binary to the installer makes sense since we're already building it. It could be just a radio button in Inno Setup to keep it simple.

**Comment by Kappa971** [comment]
> Last 32-bit CPUs are some lower end models of Sempron (2006), VIA C7 (2007), Atom N280 (2009), Atom Clover Trail (2013).
Some laptops and tablets with those or even with 64-bit capable CPUs were released with 32-bit Windows due to storage and/or memory constrains, I assume.

Those CPUs are useless for emulation and barely capable of running Windows 10 32 bit at decent speeds 😆
I'm of the opinion that DOSBox Staging should be 64 bit only on Windows because I think a 32 bit version for very old/low performing PCs doesn't make sense, and makes the installer more complex for the casual user.

**Comment by kcgen** [comment]
Progressing this is going to involve:

- Differentiating the MSVC Windows upload artifacts into 32-bit and 64-bit

- Adding the differentiated win32 build to the CI release section

- Adding the 32-bit release to the CI package creation step

- Including the 32-bit created package to the Inno installer script (both at the file level and in the UI elements)

- Avoiding confusion: the 32-bit build is only needed for EOL Windows OSes, so we want to avoid confusing the baseline Windows users (currently Win10 and 11):
    - Ideal solution: functionally hide the 32-bit builds so it's not shown to users running modern 64-bit Windows.
    - Second best: show it to all users, but use a translated description to clarify which they should choose.
    - Third best: Same as above, but only in English.
    - Worst: Don't say anything.. just present both builds and let the user decide.

- Testing on Windows 8.1, 8, 7, and Vista:
    - The developer will need to "acquire" these and setup them up in a VM inside an isolated network bubble off their own network.
    - Test the updated installer, share results, and make adjustments until the installer is working and meeting expectations.

Currently there are no maintainers running unsupported Windows versions or willing the carry out the above work.

If anyone in the community wants to pursue this, your effort would be appreciated!

**Comment by kcgen** [comment]
In the meantime, the 32-bit release zip has been added to the GitHub release:

https://github.com/dosbox-staging/dosbox-staging/releases/tag/v0.80.1

**Comment by kcgen** [comment]
With the 32-bit ZIP now in the release section (and a note helping Windows users decide), that's about as much time as I'm willing to put into this. 

Closing this ticket because this is out of the project scope - but the addition to Inno is welcome if anyone wants to pursue it.

**Comment by kcgen** [comment]
Thanks for bringing this up @Torinde - hopefully the compromised result (adding the 32-bit ZIP) should be "good enough" for the few instances this is needed.

**Comment by Grounded0** [comment]
Seems like a reasonable solution for the moment. Anyone running a 32-bit system knows they're running a 32-bit system and are probably willing to dig around to find that binary. At least we're not actively hiding it anymore which is great.
