### ISSUE TITLE
Echo environment variable does not work

### ISSUE THREAD

**Issue by rderooy** [dosbox-staging/dosbox-staging#2279]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Different version than latest?

latest git

### What Operating System are you using?

Linux x86_64

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

You should be able to echo environment variables, but this does not work in DOSBox Staging. It does work in DOSBox-X.

Current behaviour:
```dos
Z:\>echo %PATH%
%PATH$
Z:\>echo %BLASTER%
%BLASTER%
```

### Steps to reproduce the behaviour.

Explain how to reproduce
1. 
2.
3.

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by kcgen** [comment]
It should be expanded when running inside a batch file.

Do we know how real DOS handles this?

I've always thought this was deliverate, like a symbol calculator that lets you keep working with your defined symbols up to the point when you want them evaluated.

In this case, the interactive prompt stays symbolic.

But then it's run in a batch file, the symbols are evaluated.

It lets you truly worth the variables as-is:

![2023-04-01_09-50](https://user-images.githubusercontent.com/1557255/229304076-968c18ec-6074-49b1-a406-347f388a0163.png)

If this bug is fix, then the variable will always be evaluated on-the-spot, and the above will be impossible.

**Comment by rderooy** [comment]
With this setting, it works for my use cases:
```ini
[dos]
expand_shell_variable=true
```
Namely
```shell
SET PATH=%PATH%;C:\WINDOWS;
```

**Comment by johnnovak** [comment]
> It should be expanded when running inside a batch file.
> 
> Do we know how real DOS handles this?
> 
> I've always thought this was deliberate, like how a symbolic calculator lets you work with symbols as-is until you want them evaluated.
> 
> In this case, the interactive prompt stays symbolic while batch files evaluate them:
> 
> ![2023-04-01_09-50](https://user-images.githubusercontent.com/1557255/229304076-968c18ec-6074-49b1-a406-347f388a0163.png)
> 
> When this bug is fixed, the variables will be expanded on-the-spot, and the above meta-programming on the interactive shell will be impossible (well, maybe possible with lots of escaping).

I can try this quickly today. We should just do whatever real DOS is doing.

**Comment by rderooy** [comment]
I gave it a quick test myself.

With both MS-DOS 6.22 and PC DOS 2000:
```
C:\>echo %PATH%
%PATH%
```

With MS-DOS 7.0 (aka Win95):
```
C:\>echo %PATH%
C:\
```

So it seems the behaviour changed, starting with 7.0. Perhaps dosbox-staging should at least do the same thing when you set `ver=7.0`?

**Comment by rderooy** [comment]
FYI, the `SET PATH=%PATH%;C:\WINDOWS;` statement I referenced, is being run from the [autoexec] section of the dosbox config.

**Comment by rderooy** [comment]
I'm guessing you want to close this then. If not, feel free to re-open it, in case you want to set `expand_shell_variable=true` automatically if ver >= 7.0

**Comment by kcgen** [comment]
Yup, makes sense @rderooy. We should do what DOS did automatically. 

The `expand_shell_variable` conf is currently just a bool, but should be upgraded to a string that defaults to `auto`, that also lets the users override with a bool-string

**Comment by kcgen** [comment]
Will keep it opened.  It's a good find.

**Comment by rderooy** [comment]
Had a quick go at it.
```
diff --git a/src/dosbox.cpp b/src/dosbox.cpp
index dac46dd87..de3ec0f9b 100644
--- a/src/dosbox.cpp
+++ b/src/dosbox.cpp
@@ -1125,9 +1125,11 @@ void DOSBOX_Init()
                       "formats. If set to 0, the country code corresponding to the selected keyboard\n"
                       "layout will be used.");
 
-       Pbool = secprop->Add_bool("expand_shell_variable", when_idle, false);
-       Pbool->Set_help("Enable expanding environment variables such as %PATH% in the DOS command shell\n"
-                       "(disabled by default).\n"
+       Pstring = secprop->Add_string("expand_shell_variable", when_idle, "auto");
+       const char *expand_shell_variable_choices[] = {"auto", "true", "false"};
+       Pstring->Set_values(expand_shell_variable_choices);
+       Pstring->Set_help("Enable expanding environment variables such as %PATH% in the DOS command shell\n"
+                       "(auto by default, enabled if DOS version >= 7.0).\n"
                        "FreeDOS and MS-DOS 7/8 COMMAND.COM supports this behavior.");
 
        secprop->AddInitFunction(&DOS_KeyboardLayout_Init, changeable_at_runtime);
diff --git a/src/shell/shell_misc.cpp b/src/shell/shell_misc.cpp
index 38a4aa45e..46aade04d 100644
--- a/src/shell/shell_misc.cpp
+++ b/src/shell/shell_misc.cpp
@@ -420,9 +420,11 @@ void DOS_Shell::InputCommand(char * line) {
        if (l_completion.size()) l_completion.clear();
 
        /* DOS %variable% substitution */
-       const auto dos = static_cast<Section_prop *>(control->GetSection("dos"));
-       assert(dos);
-       if (dos->Get_bool("expand_shell_variable"))
+       const auto dos_section = static_cast<Section_prop *>(control->GetSection("dos"));
+       assert(dos_section);
+       if (strcmp(dos_section->Get_string("expand_shell_variable"), "true") == 0)
+               ProcessCmdLineEnvVarStitution(line);
+       else if (strcmp(dos_section->Get_string("expand_shell_variable"), "auto") == 0 && dos.version.major >= 7)
                ProcessCmdLineEnvVarStitution(line);
 }
```
This does the trick, but for some reason when I write the config with `config -wcd` there is some corruption from the vesa_modes setting.
```
# expand_shell_variable: Enable expanding environment variables such as %PATH% in the DOS command shell
#                        (auto by default, enabled if DOS version >= 7.0).
#                        FreeDOS and MS-DOS 7/8 COMMAND.COM supports this behavior.
#                        Possible values: auto, true, false, ÐA½l4^?, compatible, all, halfline.
```

**Comment by kcgen** [comment]
Hmm.. yes - nothing jumping out at me as missing or off. 
worth a PR as-is, then with the branch locally, more eyes can poke around and test it.
