### ISSUE TITLE
Incorrect output size picked for EGA mode

### ISSUE THREAD

**Issue by dreamer** [dosbox-staging/dosbox-staging#228]
@joncampbell123 said:
> Is anyone working on machine=ega and aspect ratio calculations?
> 
> machine=ega, aspect=true, output=opengl gives me a 640x350 screen that is way too wide for what EGA was actually like. EGA monitors were nothing like the widescreen displays we have now.
> ![egawidescreen](https://user-images.githubusercontent.com/6245486/77100170-70847900-69d2-11ea-8aee-d6ca09635de3.png)

Yup, I can reproduce this on Linux, with `output=opengl`, and `output=texture`.

`output=texturepp` decided to scale it 2x2.

I will run bisect to find out when did this regression happen.

**Comment by dreamer** [comment]
Nothing to really bisect - this is a bug we inherited from SVN; I checked 0.74-3, 0.74, 0.73 and then gave up - all versions have this problem.

In SVN it's most likely not recognized as a bug, because in upstream `aspect=true` does not apply to text modes when in window. However, it's still evident in there in fullscreen.

**Comment by dreamer** [comment]
I had a moment to bisect the problem, it seems like it got introduced in commit: ba3110ca07808d5e6e1ec08c70479ccf59de4bc3

**Comment by Akuma-Git** [comment]
Are we waiting on upstream ?

**Comment by dreamer** [comment]
No, unless someone with Vogons forum access will notify **ripsaw8080** about regression (I can't).

Reverting ba3110c fixes the problem, but likely introduces regressions to a number of games (see commit message).

**Comment by kcgen** [comment]
No longer an issue.
