### ISSUE TITLE
Do not truncate 18-bit VGA colour to 16-bit

### ISSUE THREAD

**Issue by johnnovak** [dosbox-staging/dosbox-staging#2282]
The VGA RAMDAC is capable of 18-bit colour (6-bit per channel), resulting in a total palette of 262k colours. 

`machine = vgaonly` renders the image as 16-bit RGB (non-palettised), which results in a total palette of 65k colours. That's a 1/4 reduction, which is rather unfortunate... This is especially noticeable on smooth colour gradients where it manifests as banding artifacts.

This was an optimisation that maybe made some sense on old hardware 15-20 years ago, but it's no longer necessary.

Is should be also checked as part of this work that all the other output modes use 32-bit colour.

More details here:
https://www.vogons.org/viewtopic.php?p=761632#p761632

**Comment by rderooy** [comment]
This is why I mention on the wiki, the "reduced colour depth" limitation of using `vgaonly`,
https://github.com/dosbox-staging/dosbox-staging/wiki/Video-Cards#ibm-vga
