### ISSUE TITLE
Retire `machine = vgaonly` and line-double all low-res VGA resolutions properly

### ISSUE THREAD

**Issue by johnnovak** [dosbox-staging/dosbox-staging#2283]
VGA cards cannot output 200/240p content; they're only capable of 350/400/480-line output (in standard modes, then there's all sorts of wacky custom modes, but those are variations of these). All low-resolution 200/240-line modes are *emulated* on VGA cards by line-doubling them to 400/480 lines. From the monitor's perspective, there is *absolutely zero difference* between 320x200 and 640x400, and 320x240 and 640x480 modes, respectively.

DOSBox emulates the VGA line-doubling faithfully in the `machine =vgaonly` mode only. This is all good and well, but when you use any of the SVGA modes, 640x480 content will be sent as a 640x480 texture to the shaders, while 320x200 as 320x200. This causes a problem with shaders, scalers, etc., and is wholly inauthentic. Yes, this is something that is "fixable" in the shaders, but the proper solution is to retire `vgaonly` altogether and implement 200/240p line-doubling for all (S)VGA modes.

As of now, you can only achieve the correct low-res VGA look with regular shaders with `vgaonly` enabled.

`machine = vgaonly` plus a tweaked version of `crt-aperture`.
[crt-aperture.vga-retina.zip](https://github.com/dosbox-staging/dosbox-staging/files/10765972/crt-aperture.vga-retina.zip)

![gods-vga-retina](https://user-images.githubusercontent.com/698770/219627861-44170446-65c6-4f12-994a-da5428fe8414.png)

Detail view (notice there are *two* scanlines going through every single pixel; this is how real low-res VGA looks like)

![image](https://user-images.githubusercontent.com/698770/219627795-285c807d-f79f-4e5f-917b-402d0c82c02d.png)

For reference, EGA/CGA/Tandy resolutions are not line doubled (basically everything prior to VGA), so for those the single-scanline look is the correct solution:

![space-quest-3-retina](https://user-images.githubusercontent.com/698770/219631080-8d082a47-b052-4c17-9e0f-c4343dfac4c1.png)

![image](https://user-images.githubusercontent.com/698770/219632665-32d79f96-4835-43a5-8a41-c056c9f9ea31.png)

**Comment by rderooy** [comment]
If `vgaonly` is retired, it should be replaced by an actual `vga` mode, and configs that reference `vgaonly` should use that.

**Comment by johnnovak** [comment]
> If `vgaonly` is retired, it should be replaced by an actual `vga` mode, and configs that reference `vgaonly` should use that.

Good point, I'll make that clear in the description.

**Comment by naatje80** [comment]
@johnnovak: Please be aware that some games still depend on vgaonly mode. E.g. The main menu of Pinball Fantasies is otherwise displayed with wrong colors and the first version of Lemmings (Lemmings and the Extension Oh No! More Lemmings) the display is partially garbled. I hope this will also be supported by the proposed actual VGA mode?

**Comment by johnnovak** [comment]
> @johnnovak: Please be aware that some games still depend on vgaonly mode. E.g. The main menu of Pinball Fantasies is otherwise displayed with wrong colors and the first version of Lemmings (Lemmings and the Extension Oh No! More Lemmings) the display is partially garbled. I hope this will also be supported by the proposed actual VGA mode?

You misunderstand @naatje80. The VGA card was only accurately emulated in `vgaonly` mode previously; in all other VGA modes the emulation was simplified and not wholly accurate. That lead to to the issues you mentioned with other machine types.

Now all VGA machine types are emulated accurately. In other words, you can think of "vgaonly being always on" but for all possible VGA machine types. Hope that makes sense.

Try the games your mentioned with the latest dev build. They'll work fine with any VGA machine types.

**Comment by naatje80** [comment]
@johnnovak Great, thank you for your additional explanation. Great to hear about this improvement!
