### ISSUE TITLE
Implement per-scanline rendering for all emulated graphics modes

### ISSUE THREAD

**Issue by johnnovak** [dosbox-staging/dosbox-staging#2284]
DOSBox currently renders the emulated video output in quarter-frame chunks. This optimisation step was probably necessary 20 years ago, but all modern emulators use the much more accurate per-scanline (and sometimes even sub-scanline) timing/rendering approach.

DOSBox X has implemented per-scanline rendering, which appears to cause a ~7% performance drop compared to the quarter-frame method (see benchmarks below for details). It also has an option to enable per-scanline rendering "lazily", only when the program actually changes certain VGA registers mid-frame that necessitates this method.

DOSBox SVN & Staging only does per-scanline rendering in the `machine = vgaonly` mode. After the [retirement of the `vgaonly` mode](https://github.com/dosbox-staging/dosbox-staging/issues/2283), we should implement the "optionally lazy" per-scanline rendering for *all* emulated graphics modes (down to Hercules) like DOSBox X.

## Performance measurements

As of 2023-02-17

### DOSBox SVN latest

**~211 FPS**

![image](https://user-images.githubusercontent.com/698770/219633932-0a891a90-1835-408d-8737-d0c76a555ff3.png)

### DOSBox Staging `main`

**~211 FPS**

![image](https://user-images.githubusercontent.com/698770/219634292-b00cb3f2-3b10-4d5a-932a-fe681157a42f.png)

### DOSBox X `main`

**~189 FPS** with the following optimisations enabled (this enables per-scanline rendering only on demand, and Quake doesn't require it)

``` ini
[video]
memory io optimization 1  = true
scanline render on demand = true
```

This is what DOSBox X says about `scanline render on demand`:

> Render video output at vsync or when something is changed mid frame, instead of stopping to render every scanline. May provide a performance benefit to most DOS games. However this may also break timing-dependent game or Demoscene effects. Default OFF (false)

![image](https://user-images.githubusercontent.com/698770/219636154-37c7a389-322b-4354-8576-5d2b0f28224e.png)

**~177 FPS** with per-scanline rendering always enabled

``` ini
[video]
memory io optimization 1  = true
scanline render on demand = false
```

![image](https://user-images.githubusercontent.com/698770/219636045-c1bcee24-ac04-46e9-a1c5-de585e8c507a.png)

**Comment by FeralChild64** [comment]
Given the benchmark result - maybe it would make sense to enable per-scanline rendering for all the modes below SVGA?

**Comment by johnnovak** [comment]
> Given the benchmark result - maybe it would make sense to enable per-scanline rendering for all the modes below SVGA?

Yeah, we'll benchmark it when implemented and we'll see.

**Comment by johnnovak** [comment]
Implementation notes from @joncampbell123 

> Locate the function that schedules when the VGA draw code is called to render another quarter and make it always schedule per scanline. That's what I did.
Although in DOSBox-X there is an experimental mode for those who would rather get more performance out of VGA rendering than per-scanline.
When enabled, it renders the frame up to the point in the raster where it would be drawing only when you do certain things with the hardware, or it draws the complete frame at vsync anyway.
