### ISSUE TITLE
Screenshots taken with Ctrl-F5 need to respect `aspect=true` option

### ISSUE THREAD

**Issue by dreamer** [dosbox-staging/dosbox-staging#229]
Default settings in dosbox-staging should assure, that when user takes a screenshot, the resulting png file uses 4:3 aspect ratio.

For screenshots, we don't need to worry about dynamically scaling them down to specific window size or screen size - we can just generate very large image and let the user worry about scaling it down (if necessary).

When game is using resolution with non-square pixels, e.g. 320x200 - scale by 5x6 to generate png of size 1600x1200 (no scaling down).

When the game is using resolution with square pixels, e.g. 640x480 - scale it up by 2x2 (or more) to avoid bilinear scaling up when user uploads the file on some forum.

It's somewhat similar to using pixel-perfect scaling for playing the game, but not exactly the same - we don't need to compromise to fit the image onto the specific screen.

## Why?

Users uploading game screenshots to internet forums, archival sites, wikipedias, etc sometimes don't know about correct aspect ratio, which leads to wide-spread misrepresentation of graphical game assets from 80s-90s.

It's also somewhat non-trivial task to scale 320x200 image to 4:3 manually using GIMP, Photoshop, or other editor - simple scale up to 320x240 does not preserve the image correctly.

**Comment by dreamer** [comment]
Moving to Backlog, as I won't have time to implement it for the first release.

**Comment by HeuristicPerson** [comment]
I disagree that DosBox should "fix" a mistake from people. Screenshots should remain as they are now, 1:1 copy of video memory. Then, if you want to take screenshots of what you see on screen, including shaders, that should be a completely different feature and, as you said, it can be easily done at the moment by simply capturing the program's window.

Regards

**Comment by kcgen** [comment]
Screenshots are by nature "what you see is what you get"; essentially a photo of the screen, performed by software.  

We might both agree that low-level memory dumps are truer to the underlying DOS game; but that's not what users see when they slam the screenshot button: they expect what they see.

So maybe a couple options are needed: raw video-memory dump, versus WYSIWYG screenshot?

**Comment by HeuristicPerson** [comment]
I completely agree on the usefulness of the WYSIWYG... but that single approach introduces other complications. Imagine you have issues with the video configuration, how do you know they are not introduced by the shader, the aspect ratio correction or anything else? The only way to detect them would be to completely change the video configuration to a "raw" one, take another screenshot and then compare both images. What if you forget to disable one of the post-processing options? what about games with different resolutions for menus and gameplay?

Having raw screenshots should be mandatory, and above them any other capturing solution should be welcomed.

Regards

**Comment by kcgen** [comment]
The argument can be made along any chain of inputs and outputs resulting in an end-result.

data files > game > driver > dosbox > SDL > OS API > OS driver > audio card/USB > amplifier > speakers.

When a user "captures audio", where along the chain should we record the data?  I can make the case there is value in debugging each point in the chain.. but for the end user, we need to capture as far as we can in the software, which is our output handed to SDL.

I can draw a simple chain for video, and screen-capture is similarly going to land on the far right; the pixels we handle to OpenGL or SDL's texture frame.  

But your point stands that there is value in capturing content at prior points in the chain - and that's certainly worth considering as a feature.

**Comment by dreamer** [comment]
> Screenshots should remain as they are now, 1:1 copy of video memory.

They are not 1:1 copy of video memory: they have palette applied, vertical pixels doubled, and are compressed to png.

> Then, if you want to take screenshots of what you see on screen, including shaders, that should be a completely different feature and, as you said, it can be easily done at the moment by simply capturing the program's window.

Including shaders in the screenshot is not part of this feature, only accurately capturing the intended aspect ratio is.

And no, it can't be "simply done by capturing the program's window" - that's the point. Scaling 320x200 by 5x6 gives you resolution higher than FHD. And most users have no idea about non-square pixels, DOS aspect ratios, etc, etc. This is a recurring source of confusion (including false bug reports from users).

Right now, there's no option for a user to *simply* capture pixel-perfect screenshot accurately showing what's on the screen. This change is going to address this problem.

**Comment by HeuristicPerson** [comment]
> They are not 1:1 copy of video memory: they have palette applied, vertical pixels doubled, and are compressed to png

Not 1:1 copy, OK. And not exactly at the beginning of the video chain, but in the last "viewable" state were 1 pixel is 1 pixel. At that stage is where you can compare the accuracy of the image produced by DosBox with any screenshot directly saved in MS-DOS. .png compression doesn't play any role here, it's a losless format so you can have the original data which is what matters.

If DosBox removes the ability to automatically take screenshot at this stage, we'll be losing something very important because the only way to compare screenshots taken after this point is to carefully modify DosBox configuration (using proper resolution, no aspec ratio correction and no shaders).

I agree that being able to capture what's on the screen is important, but I don't see why that should replace the raw screenshots we have now.

**Comment by kcgen** [comment]
I authored a PR during 2020 that captured the post-rendered screen, with correct aspect (among other settings).

This PR was discussed offline and eventually rejected:
 - https://github.com/dosbox-staging/dosbox-staging/pull/727

Suggest we close this in favour of using screenshot / capture tools at the host or window-manager level.

Thinking about the big picture: if every game or software application came with their own internal screen-capture code, that would be a lot of re-invented wheels.  This is a similar scenario.
