### ISSUE TITLE
Floppy drive access through imgmount causes DOSBox to hang if mounted before CDROM folder mounting

### ISSUE THREAD

**Issue by distantvale** [dosbox-staging/dosbox-staging#2304]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### What Operating System are you using?

Windows 11

### Relevant hardware info

Intel Gen 12, embedded intel GPU

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

I'm trying to mount both a directory with type CDROM and a floppy image using imgmount.
The order of mounting produces different results:
If I mount the floppy (imgmount) after mounting the CDROM - no issues.
But if I mount the floppy image before mounting the CDROM, reading from the floppy causes staging to crash.
It's enough to create a simple batch file on that image that has a single `echo test` command - the actual logic doesn't seem to matter.
Note that I can even `type` the content of that batch file and it shows the correct content (though if I do that, it's enough for a `dir` command to crash staging).

### Steps to reproduce the behaviour.

Explain how to reproduce
1. create a floppy image that contains a single batch file with a single line: `echo test`
2. imgmount the floppy image as drive B
3. mount any HD folder as a CDROM
4. navigate to drive B
5. execute the batch file
6. crash

Note that in my case the mount/imgmount commands were in the staging config file.

### Your configuration

```ini
output             = opengl
machine            = svga_s3
memsize            = 16
aspect             = true
core      = auto
cputype   = auto
cycles    = auto
sbtype              = sb16
sbbase              = 220
irq                 = 7
dma                 = 1
hdma                = 5
xms                   = true
ems                   = true
umb                   = true
```

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by kcgen** [comment]
Bisected to: 598de870fd6654bd8478b1e53afdc75e9372d272
