### ISSUE TITLE
Player Manager 2 behaves strangely with unusually terminated batch file

### ISSUE THREAD

**Issue by amak79** [dosbox-staging/dosbox-staging#231]
I’ve been attempting to run [Player Manager 2](https://www.mobygames.com/game/player-manager-2) with dosbox-staging (git master) and Dosbox 0.74-3 on Gentoo Linux. The game starts but isn't able to get past the intro video. Calling `LOADFIX` solves that issue but there is no sound and the game can’t be saved. After trying many different settings to get the sound to work, I looked at the `C:\PM2\PM2.BAT` batch file that is used to start the game.
```
SET BLASTER=A220 I7 D1
SET DOS4G=QUIET
D:
GO.BAT C:\pm2^@xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
^@
```
I noticed that the batch file is unusually terminated with a null `^@` character, followed by 33 `x` characters, and another null character. Surprisingly after deleting those characters the game runs without any issues. Specifically, inserting a space between `C:\pm2` and first null character, or deleting just the `x` characters will make it work. FreeDOS will run the game with the batch file unmodified.

The characters are visible with `nano` on Linux. The Dosbox `TYPE` command displays the `x` characters but the null characters are displayed as spaces. Interestingly the characters are not visible with `TYPE` and `EDIT` on FreeDOS.

**Comment by dreamer** [comment]
I guess the goal here will be to improve error signalling to the user, so broken bat files would be easier to detect. Something about output of `TYPE` needs to be done, but I'm not sure what yet (going the route of FreeDOS or displaying non-printable characters, the way `vim` or `nano` do).

If we decide to remove trailing characters from lines in .bat file, then this .bat would be runnable by default, which *seems* user-friendly… but it might have some unforeseen security implications - I need to investigate before deciding.

As for now, I am classifying this as a bug in `TYPE` built-in command. Thanks for detailed report :)

**Comment by amak79** [comment]
Thank you for looking into this problem. I've been trying to get the game to run for a long time and had given up, but I gave it one more shot.

I would certainly be in favour of a warning, but I'm not sure about trailing characters being removed, especially if it results in regressions. If needed I can provide more info and test any changes.

**Comment by Akuma-Git** [comment]
> ...I looked at the `C:\PM2\PM2.BAT` batch file that is used to start the game.
> 
> ```
> SET BLASTER=A220 I7 D1
> SET DOS4G=QUIET
> D:
> GO.BAT C:\pm2^@xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
> ^@
> ```
> 
> I noticed that the batch file is unusually terminated with a null `^@` character, followed by 33 ...

Three things come to mind:

1. Files created with "copy con" required F6 followed by enter to save and quit.
Its likely whomever created this, did not know how to use this properly.

2. Media could have been damaged

3. Not an original, (one of the reasons why dosbox only supports legitimate software)

**Comment by dreamer** [comment]
I think right now, if such bat file is executed, dosbox-staging will leave a warning in log about a weird character. But we haven't retested it for this particular case, I believe.

**Comment by amak79** [comment]
> Three things come to mind:
> 
>     1. Files created with "copy con" required F6 followed by enter to save and quit.
>        Its likely whomever created this, did not know how to use this properly.
> 
>     2. Media could have been damaged
> 
>     3. Not an original, (one of the reasons why dosbox only supports legitimate software)

It's definitely not 3 as I have the original CD. 2 is possible, but I have no way to verify it. Redump doesn't have any entry for it.

**Comment by Akuma-Git** [comment]
```
SET BLASTER=A220 I7 D1
SET DOS4G=QUIET
D:
CALL GO.BAT C:\pm2
```
Try this

**Comment by dreamer** [comment]
It might be possible, that original CD got corrupted or something like this. The problem lies not with running the game (that was figured out instantly), it's more about: "how do we communicate to users, that something is wrong with their .bat file" :)

**Comment by kcgen** [comment]
Data CDROMs container a per-sector CRC check, and failing that another 15% of forward-error-correction data per sector that the CDROM drive will use to fix the data on-the-fly. 

If that fails, your drive will enter a loop trying to re-read it (and appear to get stuck for some time) until the read itself will error out and your OS will report a failure. 

The bad file will either not exist, be zero bytes, or will be partially populated up to the point where the read failed. 

So if you had no problems copying/installing the software off an original physical CD, then you can rest assured the resulting files are byte-exact (provided your CPU, memory, and HDD aren't compromised and corruping data mid-transfer or on write :-) )

**Comment by kcgen** [comment]
@amak79 , would you be able to to zip the original batch file and drag it into a new comment here? 

We can see how the latest code handles it, just to double-check this before the 0.76 release.  Thank you!

**Comment by amak79** [comment]
> ```
> SET BLASTER=A220 I7 D1
> SET DOS4G=QUIET
> D:
> CALL GO.BAT C:\pm2
> ```
> 
> Try this

That works, but I already confirmed this in my original post.

I doubt the CD is damaged. The game runs off the CD as there is no install to disk option. The `C:\PM2` directory only contains the `PM2.BAT` and `PM2.CFG` files, along with any saves that are made.

Original batch file: [PM2.BAT.zip](https://github.com/dosbox-staging/dosbox-staging/files/5179419/PM2.BAT.zip)

**Comment by kcgen** [comment]
![2020-09-06_03-22](https://user-images.githubusercontent.com/1557255/92323758-3d6d8a80-eff0-11ea-9dff-a91c52a7536b.png)

Thanks @amak79 - and glad to see these breaking hidden control characters flagged; atleast tipping off users that there's something not right here.

**Comment by dreamer** [comment]
OK, closing this issue for now, I think there's not much more to discuss in here.

Perhaps we should consider making the warning more user-friendly (e.g. including the line or line+column where unexpected character was found, and informing that it might be a corrupted file), but we can do this in a PR or a new issue.
