### ISSUE TITLE
Links to the feature highlights on the front-page

### ISSUE THREAD

**Issue by Torinde** [dosbox-staging/dosbox-staging#2313]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### What Operating System are you using?

None

### Is your feature request related to a problem? Please describe.

Feature highlights links is very useful, thank you for that @johnnovak!

Two remain unlinked:
- Immediate mouse mode for fast-paced games: unsure where to link that to?
- Vertical sync (vsync) support: I see a vsync setting description in the .conf file, maybe it can be linked to that?

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by johnnovak** [comment]
I couldn't find any relevant info about those two. If you do, please post here and I'll update the front page.

**Comment by Torinde** [comment]
In the .conf file:
```
#               vsync: Synchronize with display refresh rate if supported. This can
#                      reduce flickering and tearing, but may also impact performance.
#          vsync_skip: Number of microseconds to allow rendering to block before skipping the next frame. 0 disables this and will always render.
vsync               = false
vsync_skip          = 7000
```

I'm not sure how to make a link to that, but it should be somewhere in the Github repository...

For the mouse mode I have no idea what it is (a reason why I think having the links is great addition).

**Comment by Burrito78** [comment]
Explanation from ChatGPT, changed by me slightly.

@johnnovak can put this in the Wiki and link to it. @kcgen can take a look too because he is the expert on this.

> Vsync, or vertical sync, is a feature that synchronizes the frame rate of a video game or other application with the refresh rate of the display. The purpose of this synchronization is to prevent screen tearing, which occurs when the display shows parts of multiple frames at once, resulting in an unsightly visual artifact.
> 
> In DOSBox Staging, enabling vsync ensures that the emulator's output is synchronized with the vertical refresh rate of your monitor. This means that each time the display refreshes, DOSBox will wait until it's ready to show the next frame, instead of immediately displaying it. This ensures that the entire frame is displayed in one go, without any tearing or visual artifacts.
> 
> To enable vsync in DOSBox Staging, you'll need to add a line to the emulator's configuration file. Open the configuration file (called dosbox-staging.conf) in a text editor and look for the section called [sdl]. Look for the vsync parameter and change its value to „true“ like this:
> 
> `vsync=true`
> 
> Save the file and restart DOSBox Staging for the changes to take effect. Once vsync is enabled, you should notice smoother and more consistent visuals in your games and applications.

**Comment by johnnovak** [comment]
@Burrito78 this is overly wordy I think. You should have access to edit the wiki, if not, we can sort that out. Also, can we not use ChatGPT, please? :)

**Comment by Burrito78** [comment]
Will improve it and see that i get access to the Wiki.

**Comment by Torinde** [comment]
@Burrito78, can you ask ChatGPT-4 to "create DOSbox Staging code of the [FAT32 commit](https://github.com/dosbox-staging/dosbox-staging/tree/ww/fat32-test) following the [guidelines](https://github.com/dosbox-staging/dosbox-staging/blob/main/CONTRIBUTING.md)" or to "create DOSbox Staging code emulating AWE32 by using code from PCem [sound_emu8k.h](https://github.com/sarah-walker-pcem/pcem/blob/bed5fced7b1b9a2aa55f05cfc68033a6f406bd6a/includes/private/sound/sound_emu8k.h) and [sound_emu8k.c](https://github.com/sarah-walker-pcem/pcem/blob/bed5fced7b1b9a2aa55f05cfc68033a6f406bd6a/src/sound/sound_emu8k.c)"

I don't expect that to work and will be surprised if the output even compiles/runs (in which case my expectation is that reviewing the code will be more effort than doing it by hand in the first place - by somebody who knows what they're doing), but would be interested to check if my preconceptions are wrong (with all the buzz around it - somebody may expect capabilities like "here is the Wikipedia page/Datasheet of PowerVR, emulate it" and of course I would like to have such a magic wand... my list of requests for it is 85KB already)

**Comment by johnnovak** [comment]
> @Burrito78, can you ask ChatGPT-4 to "create DOSbox Staging code of the [FAT32 commit](https://github.com/dosbox-staging/dosbox-staging/tree/ww/fat32-test) following the [guidelines](https://github.com/dosbox-staging/dosbox-staging/blob/main/CONTRIBUTING.md)" or to "create DOSbox Staging code emulating AWE32 by using code from PCem [sound_emu8k.h](https://github.com/sarah-walker-pcem/pcem/blob/bed5fced7b1b9a2aa55f05cfc68033a6f406bd6a/includes/private/sound/sound_emu8k.h) and [sound_emu8k.c](https://github.com/sarah-walker-pcem/pcem/blob/bed5fced7b1b9a2aa55f05cfc68033a6f406bd6a/src/sound/sound_emu8k.c)"
> 
> I don't expect that to work and will be surprised if the output even compiles/runs (in which case my expectation is that reviewing the code will be more effort than doing it by hand in the first place - by somebody who knows what they're doing), but would be interested to check if my preconceptions are wrong (with all the buzz around it - somebody may expect capabilities like "here is the Wikipedia page/Datasheet of PowerVR, emulate it" and of course I would like to have such a magic wand... my list of requests for it is 85KB already)

I expect it's shit, so if someone else wants to waste their time on this, be my guest 😄 Won't be me, though, and I will not review its code either...

**Comment by johnnovak** [comment]
> LOL
> 
> ![Bildschirmfoto 2023-03-23 um 08 51 17](https://user-images.githubusercontent.com/61995128/227137924-5379f57a-96e3-4417-9648-242c06cf0cb6.png)
> 
> ![DodWFQ9mQkVyWoKFa0ZIu12PYrPo3P2T0taaK-lgJCo](https://user-images.githubusercontent.com/61995128/227137618-833d1e39-7b0b-48fd-b947-ac39a162ea3c.png)

That's hilarious :) `npm install` & `npm test`... yeah right on! :trollface:

**Comment by Burrito78** [comment]
This is finished.
