### ISSUE TITLE
Assistance converting an old Daum fx shader

### ISSUE THREAD

**Issue by Python-Exoproject** [dosbox-staging/dosbox-staging#2315]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### What Operating System are you using?

Windows 10

### Whats your question and how can we help?

Hi Staging peeps!

Im part of the eXoDOS team and have been looking at staging for some of the functions we have setup for our users. 

Once of these functions is to allow the user to choose to apply a shader that attempts to remove the interlace lines from DOS game FMVs. Its not always very successful but has shown its use from time to time with certain games. The issue is that the shader is in a format (.fx) that is only used by an old abandoned dosbox fork, Daum.

I am not a coder so @kcgen has suggested I post a request here to see if anyone with the requisite skills would be willing to convert the Daum shader into a staging compatible one.

If anyone is interested in doing this, the Daum files are here: 
[Shader.zip](https://github.com/dosbox-staging/dosbox-staging/files/10911638/Shader.zip)

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by Python-Exoproject** [comment]
Here are some examples of the difference between standard output and the fx shader:

![example1](https://user-images.githubusercontent.com/67406191/223642710-c53a9c7e-3393-4695-9a6b-2fa6128c5c81.png)

![example2](https://user-images.githubusercontent.com/67406191/223643014-28b254bf-1abf-40af-b5b4-a0f9f7886f8c.png)

![example3](https://user-images.githubusercontent.com/67406191/223643218-65f4066d-6680-4796-a942-19bbe805caab.png)

![example4](https://user-images.githubusercontent.com/67406191/223643423-0155c02e-4e0d-4ea0-81e6-15f8eeff1f61.png)

**Comment by johnnovak** [comment]
I kinda prefer the fake interlace lines :) I might have a look later, maybe there's an improved GLSL version out there already.

**Comment by johnnovak** [comment]
Okay, I've checked it out how it works and it's rather simple, I can rewrite this to GLSL. I can also enhance it a bit to support variable-strength scanlines instead of just doubling them :)

**Comment by kcgen** [comment]
> I kinda prefer the fake interlace lines :) I might have a look later, maybe there's an improved GLSL version out there already.

Very interesting - I wonder if the original shader is also cutting the brightness (or averaging between the black lines?), because the result is rather drab:

![2023-03-08_14-58](https://user-images.githubusercontent.com/1557255/223871448-0cfd3356-b372-4c42-a1c6-7f548f9907e9.png)

>  I can also enhance it a bit to support variable-strength scanlines instead of just doubling them

This strength-boost should help a lot in this regard.

**Comment by johnnovak** [comment]
> Very interesting - I wonder if the original shader is also cutting the brightness (or averaging between the black lines?), because the result is rather drab (suggest opening fullscreen):

I noticed that brightness-loss in the deinterlaced version too (the right one, the left one is the original).
It's the second variant of the de-interlacer that does it. There are two versions, these are the comments from the sources:

```
// This version fills in the black lines with full brightness,
// but since this shader can't tell if this is a video or not,
// the interactive screens will not look very good.
float4 PS_Video1 ( in VS_OUTPUT_VIDEO input ) : COLOR
```

```
// This version does a vertical blur, which means the videos
// will have half brightness, but at least lets the interactive
// screens look mostly OK, just a little blurred.
float4 PS_Video2 ( in VS_OUTPUT_VIDEO input ) : COLOR
```

Clearly the screenshots showcase the second version, the simplistic first version can look a little bit like crap because it blindly line-doubles all pixels if there's a black pixel under them (it has to work on individual pixel level; pretty expensive to check in a shader whether a whole line is black).

**Comment by Python-Exoproject** [comment]
@johnnovak Thank you John for offering your assistance! I agree, the deinterlaced result of the fx shader is quite dark so I look forward to your results.

As for using it, as with most of these visual things its a case of personal preference. I myself do not, due mostly to the dreary result, but many of our users do as they dont like the missing lines. 

Being able to move away from Daum some more and still offer our users the same or better options and experience will be greatly appreciated.

**Comment by johnnovak** [comment]
> Being able to move away from Daum some more and still offer our users the same or better options and experience will be greatly appreciated.

Yeah, I figured that's the goal here — not make it worse, at least 😂 

> And if you ever do add it as an actual staging function, I think it would be cool. The result would be even better and as time moves on im certain the younger crowd who arent as nostalgic for the period and would think someone is crazy for wanting to keep blank lines in their video will appreciate the option

Yes, it would be a cool option. However, it should always be an _option_ — even young people should be able to learn to saviour the proper authentic retro-experience, or might be even _looking_ for that experience (something different to what they're used to 😎). As I enjoy enjoy silent movies from the 1920s 😄

**Comment by johnnovak** [comment]
Here we go. Attaching as a ZIP file as GitHub doesn't allow me to attach a `*.glsl` file...

[fixvideo.zip](https://github.com/dosbox-staging/dosbox-staging/files/11358835/fixvideo.zip)

You can customise it via the defines at the top of the shader, should be self-explanatory. My new "intelligent scanline-doubling" mode is better than what you had previously as it can usually guess correctly whether the above scanline is fully black or not. It takes 4 sample points of the above scanline, you might need to tweak these for each game slightly.

Let me know if any issues:

```ini
// Deinterlace method
// ------------------
//   0.0 = Mode 0: vertical average + brightness-boost
//   1.0 = Mode 1: intelligent scanline-doubling
#define DEINTERLACE_METHOD 1.0

// Mode 0 params
// -------------
//   Brightness boost (0.00 to 1.00)
#define BRIGHT_BOOST 0.50

// Mode 1 params
// -------------
//   4 sample points to check if the scanline above the current is black;
//   might need to tweak it a bit per game
//   0.00 = leftmost pixel; 0.50 = middle pixel; 1.0 = rightmost pixel
#define SAMPLE_POINT_1 0.00
#define SAMPLE_POINT_2 0.25
#define SAMPLE_POINT_3 0.75
#define SAMPLE_POINT_4 1.00
```

**Comment by johnnovak** [comment]
Result:

![image](https://user-images.githubusercontent.com/698770/235296641-78225268-9c32-494d-9fae-1bd0266107d7.png)

**Comment by Python-Exoproject** [comment]
Brilliant job @johnnovak, works in the games ive tested so far exactly as advertised. Thanks for the assist

**Comment by Python-Exoproject** [comment]
Even better, the old shader technique didnt work with some games, Privateer 2 being one of them. Your new versions works with it

**Comment by johnnovak** [comment]
> Even better, the old shader technique didnt work with some games, Privateer 2 being one of them. Your new versions works with it

Glad to hear that!

**Comment by dreamer** [comment]
Maybe we should include this new shader with our predefined set? It has a very clear and valid usecase :)

**Comment by ThomasEricB** [comment]
I agree with @dreamer.  Could we do that @johnnovak ?

**Comment by johnnovak** [comment]
I was kinda considering it but was hesitant to propose it myself (I was 50/50 about it). Okay I'll raise a PR then :)

**Comment by ThomasEricB** [comment]
Added with https://github.com/dosbox-staging/dosbox-staging/pull/2442 .
