### ISSUE TITLE
Distorted sound in Worms

### ISSUE THREAD

**Issue by numberZero** [dosbox-staging/dosbox-staging#233]
In Worms sound is distorted, while it is OK in 0.74. Also in 0.74 there are two “clicks” on Worms start, which are not there in Staging. Maybe the signedness is wrong somewhere?

**Comment by dreamer** [comment]
You need to be more precise - is distorted sound only Worms voices or also music and video cutscenes?

I know about single audio distortion bug in Worms we inherited from SVN: [SF #510](https://sourceforge.net/p/dosbox/bugs/510/) - do you experience this one?

> while it is OK in 0.74

Oh! This is important. Do you mean 0.74, 0.74-2 or 0.74-3? When testing 0.74-3 I *think* I hear this distortion, but I'm not sure; I haven't tested older versions yet.

> Also in 0.74 there are two “clicks” on Worms start

IIRC this was some kind of harmless problem with CD-DA implementation in upstream project; this issue disappeared when we merged-in new CD-DA emulation stack by @krcroft.

**Comment by numberZero** [comment]
The issue is with voices. It is actually mush like SF#510 you referenced. Changing `sbtype` from `sb16` to `sb1` fixes the distortion. But on svn-0.74-3, it works with `sb16` as well, in stereo (position-dependent).

My system has:
 * JACK as the sound server, running at 48kHz
 * Its ALSA plugin as the default output
 * DOSBox Staging d0da4341 and SVN 0.74-3

Note that the sound is chopped in capture files as well, not only in real output.

Here is relevant part of the config:
```
[mixer]
nosound=false
rate=48000
#blocksize=1024
blocksize=4096
prebuffer=20

[sblaster]
sbtype=sb16
sbbase=220
irq=7
dma=1
hdma=5
sbmixer=true
oplmode=auto
oplemu=default
oplrate=48000
```
and output:
```
MIXER: Got different values from SDL: freq 48000, blocksize 4096
ALSA:Can't subscribe to MIDI port (65:0) nor (17:0)
No working midi device found/selected! Please check your settings and/or compilation environment.
MIDI: Opened device:none
```

P.S. CD-DA is perfect in Staging (and totally broken in SVN).

**Comment by krcroft** [comment]
@numberZero , this is merely a workaround  looking at my own Worms config, but I also hit this in the past (probably pre-0.74.3), and am using GUS at 44.1 (and mixer at 44.1). Soundblaster is disabled. Is that an improvement over sb1? (I think the sfx internal samples are pretty low quality; so might not be much of a help).

**Comment by numberZero** [comment]
It works well with GUS, thanks. (But channels are swapped for some reason)

**Comment by kcgen** [comment]
Swapped audio channels has been repeatedly brought up on Vogons over the years, and ripsaw8080 provided a nice patch roughly 13 years ago in this thread: https://www.vogons.org/viewtopic.php?f=41&t=15800; so we can add this to our merge queue. 

ripsaw8080 also wrote a tool that directly patches the Miles sound driver; so this is definitely the _"one and done"_ fix that would be preferred for applicable games: https://www.vogons.org/viewtopic.php?p=204889#p204889

**Comment by numberZero** [comment]
Actually it does *not* work as expected. For whatever reason, Worms refuse to use per-team voices with GUS, playing the default voice only. Switching back to `sb`; stereo was never good in Worms anyway...

**Comment by kcgen** [comment]
@numberZero, thanks for investigating and reporting back.  I wasn't aware that some sound effects are missing from the GUS sample set (I suppose this is proof that the developers provided different sets between the GUS and SB).  Very interesting!

**Comment by nemo93** [comment]
Game is working fine here with the settings found on the [wiki](https://github.com/dosbox-staging/dosbox-staging/wiki/Config-file-examples#worms-cd).

**Comment by kcgen** [comment]
Thanks for the report @nemo93 - closing.

**Comment by Burrito78** [comment]
Happens with DOSBox Staging 0.81.0-alpha-850 for me.

Example:
[wrms_001.wav.zip](https://github.com/dosbox-staging/dosbox-staging/files/11646315/wrms_001.wav.zip)

Config:
```
-noprimaryconf

soundfont = FluidR3_GM_GS.sf2
joysticktype = disabled
```

The only working fix is to set `sbtype = sb1`.

**Comment by Burrito78** [comment]
Reported the regression here: https://www.vogons.org/viewtopic.php?f=31&t=94543

**Comment by kcgen** [comment]
Bisecting in DOSBox's subversion repository:

- **r4112** was the last SVN commits where Worms voices play clean:

    https://github.com/dosbox-staging/dosbox-staging/assets/1557255/462ebe20-d73a-46fb-ae1e-c74038856731

- [**r4113**](https://sourceforge.net/p/dosbox/code-0/4113/) fixed [SVN bug #482](https://sourceforge.net/p/dosbox/bugs/482/), but introduces a repeating pitter-patter in Worms:

    https://github.com/dosbox-staging/dosbox-staging/assets/1557255/8bffbeb2-460f-4de9-b58c-771d8d9001fb

- [**r4175**](https://sourceforge.net/p/dosbox/code-0/4175/) solves the pitter-patter in Worms, but introduces a warble in the voices:

     https://github.com/dosbox-staging/dosbox-staging/assets/1557255/8025493a-4397-44fc-b4fa-900cca19711f

r4175 is where SVN and Staging are currently today.

**Comment by Burrito78** [comment]
Can we let Qbix know directly somehow? Maybe he can fix this in SVN.

**Comment by Grounded0** [comment]
Can you do a short writeup on Worms in Game Issues or do i?

**Comment by Grounded0** [comment]
@Burrito78 I'll write the workaround now there.

**Comment by Grounded0** [comment]
Workaround added:
https://github.com/dosbox-staging/dosbox-staging/wiki/Game-issues#worms
