### ISSUE TITLE
BIOS Fonts and 0x10 interrupt

### ISSUE THREAD

**Issue by ianselmi** [dosbox-staging/dosbox-staging#2331]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### What Operating System are you using?

Windows 11

### Whats your question and how can we help?

A lot of years ago I wrote a simply software in C that redefine the bios font to load custom fonts set.
a code snippet is 
`void SetNewFont ( unsigned char *Array, unsigned char Car)
{
 struct REGPACK r;

 r.r_ax  =  0x1100;
 r.r_es  = (unsigned ) FP_SEG(Array);
 r.r_bp  = (unsigned ) FP_OFF(Array);
 r.r_bx  = 0x1000;
 r.r_dx  = Car;
 r.r_cx  = 1;
 intr(0x10, &r);
}`

whe I tried to use it with dosbox the custom fonts are not visible like this screenshot
![image](https://user-images.githubusercontent.com/5089542/224535458-101e22e9-44f4-4a26-8438-aee6f48b0656.png)

My question is, is this mode supported? Is the char mapping equals to the past?

thanks in advance

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by johnnovak** [comment]
I did use custom charsets in my text mode programs too, but I forgot how I did it exactly...

Can you try FontEdit II and compare the results? http://www.geocities.ws/ivan_llanas/software/fontedit2.html

If you post your whole program here, and tell me which DOS compiler you used, I can try it on real hardware too.

**Comment by ianselmi** [comment]
Hi @johnnovak thanks for the response, this evening I found the problem. 
I use borland turbo c++ (ver 3.0) compiler and the problem appears when I use the memory model setted to Huge
![image](https://user-images.githubusercontent.com/5089542/224851803-a43da013-b831-46e5-bae3-60b63781a3c1.png)

when the memory model is set on small the problem is not present.
Honestly, I don't remember the difference (from small to huge), I'll try to use the small model, but is a long way 😄 
FontEdit works better so the problem is only on my software and not with DosBox.

thanks a lot

**Comment by johnnovak** [comment]
Glad to hear you've managed to resolve the problem, probably it's still worthwhile for me to compile your example code  when you post it and test it on real hardware, just that we understand the issue and confirm it's not a DOSBox bug.

> when the memory model is set on small the problem is not present. Honestly, I don't remember the difference (from small to huge), I'll try to use the small model, but is a long way 😄 FontEdit works better so the problem is only on my software and not with DosBox. tomorrow I'll post a simple code example.

Yeah, I've forgotten 99% of that stuff too from my DOS coding days in asm/C/Pascal 😁

**Comment by johnnovak** [comment]
Related:

**Fontraption**
https://int10h.org/blog/2019/05/fontraption-vga-text-mode-font-editor/
https://github.com/viler-int10h/Fontraption

**VGA ROM Fonts**
http://www.alexandrugroza.ro/microelectronics/essays-research/vga-rom-fonts/index.html

**Comment by ianselmi** [comment]
Hi @johnnovak this is the example (don't look at the ugliness of the code 😄 ):

```C
#include <dos.h>
typedef struct
  {
    unsigned char Font[16][8];
  }TipoFont;

void SetNewFont ( unsigned char *Array, unsigned char Car);
unsigned char BinDec( unsigned char *vet);
void SetFont ( TipoFont *Font, int NumChar);

unsigned char BinDec( unsigned char *vet)
{
   int i;
   unsigned char ris = 0;
   unsigned char pw[8] = {128, 64, 32, 16, 8, 4, 2, 1};

   for (i = 7; i >= 0; i--)
      ris += (unsigned char)(vet[i] * pw[i]) ;

   return ris;
}

void SetFont ( TipoFont *Font, int NumChar)
{
   unsigned char Fnt[16];
   unsigned char i;

   for (i = 0; i <16; i++ )
       Fnt[i] = (unsigned char)BinDec(Font->Font[i]);
   SetNewFont(Fnt, NumChar);
}

void SetNewFont ( unsigned char *Array, unsigned char Car)
{
 struct REGPACK r;

 r.r_ax  =  0x1100;
 r.r_es  = (unsigned ) FP_SEG(Array);
 r.r_bp  = (unsigned ) FP_OFF(Array);
 r.r_bx  = 0x1000;
 r.r_dx  = Car;
 r.r_cx  = 1;
 intr(0x10, &r);
}

void SetMode ( int mode )
{
  union REGS r;

  r.h.ah = 0;
  r.h.al = mode;
  int86(0x10,&r,&r);
}
void main(void)
{
	 struct REGPACK r;
	 char c;
	 unsigned char i,j;
      TipoFont tf;
      unsigned char tmp[16][8] = {
			1, 1, 1, 1, 1, 1, 1, 1,
			1, 1, 1, 1, 1, 1, 1, 1,
			1, 1, 1, 1, 1, 1, 1, 1,
			1, 1, 1, 1, 1, 1, 1, 1,
			1, 1, 1, 1, 1, 1, 1, 1,
			1, 1, 1, 1, 1, 1, 1, 1,
			1, 1, 1, 1, 1, 1, 1, 1,
			1, 1, 1, 1, 1, 1, 1, 1,
			1, 1, 1, 1, 1, 1, 1, 1,
			1, 1, 1, 1, 1, 1, 1, 1,
			1, 1, 1, 1, 1, 1, 1, 1,
			1, 1, 1, 1, 1, 1, 1, 1,
			1, 1, 1, 1, 1, 1, 1, 1,
			1, 1, 1, 1, 1, 1, 1, 1,
			1, 1, 1, 1, 1, 1, 1, 1,
			1, 1, 1, 1, 1, 1, 1, 1
       };
    for(i=0;i<16;i++)
    {
      for(j=0;j<8;j++)
      {
       tf.Font[i][j] = tmp[i][j];
      }
   }

  SetMode(0x3);
  SetFont(tf.Font, 0x00);
  printf("%c AAAA BBBB ", '\0');
  getchar();
  SetMode(0x3);
}


```


If you compile it with Model not Huge all works ok
![image](https://user-images.githubusercontent.com/5089542/224937532-37d4d883-3763-45ba-8b8b-9f24af472a7e.png)

If you compile it with Model Huge the result is this:
![image](https://user-images.githubusercontent.com/5089542/224937830-56b4a62c-d854-4930-af5a-956dcb212be8.png)

I don't know if there is a solution.

thanks for the resources

**Comment by johnnovak** [comment]
Cheers, I'll test it in on my real machine sometime this week 😄

**Comment by johnnovak** [comment]
@ianselmi Sorry, I've been busy with other stuff... If you attach the binary in a ZIP file I can test it on my real machine quickly today.

**Comment by ianselmi** [comment]
No problem @johnnovak, I attached a zip with 2 files, fnt_small works because is compiled with a small model, fnt_huge doesn't work because is compiled with model huge. to compile them I used TurboC ver 3.0
[FNT.zip](https://github.com/dosbox-staging/dosbox-staging/files/11058725/FNT.zip)

**Comment by johnnovak** [comment]
@ianselmi I've just tried it on real hardware, and I'm getting the same results as shown on your DOSBox screenshots.
Model small looks fine (solid rectangle), but model huge results in similar garbage as shown on the screenshot.

So, it's not a DOSBox bug, the code is at fault. Closing.

**Comment by ianselmi** [comment]
Thanks a lot @johnnovak for your test, I appreciate it very much.

**Comment by johnnovak** [comment]
> Thanks a lot @johnnovak for your test, I appreciate it very much.

No problem, man 😎
