### ISSUE TITLE
MS Serial mouse not detected in Windows 1.01

### ISSUE THREAD

**Issue by rderooy** [dosbox-staging/dosbox-staging#2332]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Different version than latest?

latest git

### What Operating System are you using?

Linux x86_64

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Running different Windows 1.0x releases, I noticed that the MS Serial mouse would not work with Windows 1.01 specifically.

Running Windows 1.02, 103 or 1.04 and the MS Serial mouse emulation **does** work.

Basically no mouse is detected when Windows 1.01 starts, and no mouse cursor is therefore drawn.

Changing the mouse during `SETUP` to "Mouse Systems or VisiOn Mouse (COM1)" and setting `com_mouse_model=msm` in the config file does work.

Something @FeralChild64 may want to have a look at.

### Steps to reproduce the behaviour.

Explain how to reproduce
1.  Run Windows 1.01 `SETUP`
2. When prompted for the mouse type, select "Microsoft Mouse (Bus/Serial)"
3. Start Windows 1.01

### Your configuration

```ini
[dos]
ver=3.4
expand_shell_variable=true

[mouse]
#dos_mouse_driver     = false
#com_mouse_model=msm
com_mouse_model=2button

[autoexec]
@ECHO OFF
MOUNT C .
C:
SET PATH=%PATH%;C:\WINDOWS;
IF EXIST C:\WINDOWS\IBMMOUSE.DRV GOTO WINDOWS.IBM
IF EXIST C:\WINDOWS\WIN.COM      GOTO WINDOWS
ECHO No Windows installation found
GOTO END

:WINDOWS
ECHO Starting Windows 1.0x with serial mouse
CONFIG -SET SERIAL SERIAL1=mouse
C:\WINDOWS\WIN.COM
GOTO END

:WINDOWS.IBM
ECHO Starting Windows 1.04 IBM OEM Release
C:\WINDOWS\WIN.COM
GOTO END

:END
```

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by rderooy** [comment]
I suspect the MS mouse driver included with the initial release was simply buggy. https://jeffpar.github.io/kbarchive/kb/028/Q28502/

**Comment by FeralChild64** [comment]
@rderooy Have you tried to set the mouse to `2button`? 3-button mouse and wheel mouse send different id’s during the initialization, I can imagine some old software might fail to recognize them.

**Comment by rderooy** [comment]
@FeralChild64 Yes I did, as shown in the above config example.

**Comment by rderooy** [comment]
Ok, it seems my Windows 1.01 installation directory got messed up. After unpacking a clean set of disk images, it worked.
