### ISSUE TITLE
Window resolution is ignored when `fullscreen` is turned on

### ISSUE THREAD

**Issue by johnnovak** [dosbox-staging/dosbox-staging#2335]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### What Operating System are you using?

Mac OS

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

`windowresolution` is ignored when DOSBox is started in fullscreen mode (`fullscreen = on`), at least on macOS. I'll test it on Windows later.

### Steps to reproduce the behaviour.

1. Use the following config

```ini
[sdl]
fullscreen = on
windowresolution = 960x720
```

2. Toggle between fullscreen & windowed mode and note that the window size is not what you specified with `windowresolution` — the window always has the size of the full desktop.

3. Change the config so we start in windowed mode by default:

```ini
[sdl]
fullscreen = off
windowresolution = 960x720
```

4. Note the specified window size is applied at startup.

5. Toggle between fullscreen & windowed mode, and notice the window size is set correctly when exiting fullscreen mode.

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by kcgen** [comment]
Good catch, @johnnovak. 

It was working at some point, but probably was a regression.  If anyone has time to help bisect where it started, help would be appreciated!

**Comment by kcgen** [comment]
Been looking into this; at the transition from fullscreen to windowed, the 'setwindowsize' call actually gets the desired `windowresolution = ` values, and the `DISPLAY: ..` message reports the dimensions correctly too.  But then two rounds of callbacks trigger gfx__reset calls that ratchet the size back up to the full dimensions (all in quick succession, so the end result is the window is still maximum sizes).

On Linux, this doesn't happen. 

So the next step is getting a handle on these rendering and sdlmain callback functions.

**Comment by johnnovak** [comment]
> Been looking into this.
> 
> At the transition event from fullscreen to windowed, the 'setwindowsize(...)' call is given the desired and correct `windowresolution = ` values, and puts them into effect properly, followed by the log message reporting the correct `DISPLAY: ..` window resolution.
> 
> However, then two rounds of (what appears to be identical) callbacks trigger gfx__reset() calls that ratchet the window size right back up to the full dimensions (all in quick succession), so the end result is the window now is back to the full screen dimensions.
> 
> On Linux, this doesn't happen.
> 
> So the next step is getting a handle on these rendering and sdlmain callback functions.

Good progress. Windows handling, input handling, and the graphics pipeline is such a mess... 😱
