### ISSUE TITLE
Unnecessary duplicate frames in VFR presentation mode

### ISSUE THREAD

**Issue by 0mnicydle** [dosbox-staging/dosbox-staging#2340]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Different version than latest?

0.81.0-alpha

### What Operating System are you using?

Windows 10

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

When using custom dos rates and vfr presentation method after commit afc1279 many unnecessary duplicate frames are created when using high dos_rate values, which causes frame rate to exceed host rate and negate the benefits of VRR.

Copying my comments on the commit here:

> Can we please have a config option to disable this feature? There was never any need for it on my system, and it completely breaks my use case for the vfr presentation method, which is to use 1000Hz dos_rate to get the true fps out of games which are often running over 70Hz internally, and have the frames perfectly synced to my monitor (as long as it's under max refresh rate). For instance in Dark Forces I can get smooth 72fps native frame rate out of that game and avoid frame pacing glitches, but with this commit I get 400-500fps for no good reason and it tears because it exceeds my max refresh rate. Some other games that will run over 100fps like Duke3D and Quake have similar problems now.
> 
> For now I am setting max_dupes to 0 in sdlmain.cpp before compiling to resolve the issue.
> 
> As an alternative, might I suggest an optional VFR "floor?" Presentation is typically VFR but will never drop below xHz CFR, say 15Hz or something... So instead of just repeating frames up to 10 times until a new frame is ready, you only repeat the previous frame if time since previous frame exceeds a certain value (ideally user configurable).

Regarding above, 1000Hz dos_rate is necessary in my experience to get optimal frame pacing in games that aren't internally synced to the emulated display as frames are delivered on the same tick they are completed. It also provides the best input response, and so is the primary use case for the vfr presentation method in my view. When these factors aren't a concern, I use the default dos_rate and cfr presentation method on my VRR display.

### Steps to reproduce the behaviour.

Explain how to reproduce
1. 
2.
3.

### Your configuration

[sdl]
vsync = false
presentation_mode  = vfr

[dosbox]
dos_rate = 1000

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by ThomasEricB** [comment]
> Excellent suggestions @0mnicydle -- yes, this is really just a worst-case safety cap and is meant to be low impact.
> 
> I like the 're-present last frame after some timeout' period, where the timeout is some "guaranteed" period where we know the host won't throw away this frame too (unlike the prior frame, which might have been dropped because our framerate exceeds the host rate).
> 
> I think if we've waiting more than twice the host's frame period, then that should ensure the host will actually present (and not drop) this follow up duplicate

I agree with @kcgen over at https://github.com/dosbox-staging/dosbox-staging/commit/afc127932687b48f21852f54a36cbf3fc9575f99#commitcomment-104489052 ! Excellent suggestions!

**Comment by kcgen** [comment]
(closing - thanks for all the testing, @0mnicydle !)
