### ISSUE TITLE
ANSI text format engine unable to display `[/b]`

### ISSUE THREAD

**Issue by FeralChild64** [dosbox-staging/dosbox-staging#2345]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### What Operating System are you using?

Linux x86_64

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

ANSI text format engine is not able to display `[/b]` - this is visible with DIR command, where the help in the source code contains the line:

https://github.com/dosbox-staging/dosbox-staging/blob/58349434d10cc2a35189e38348949d68671f6919/src/shell/shell.cpp#L1135

but the output is:

![out](https://user-images.githubusercontent.com/48332137/226030422-c3dbb8a5-d812-40ce-b134-a87fd7f8ae7d.png)

### Steps to reproduce the behaviour.

Explain how to reproduce
1.  Type `dir /?`, check for `[/b]` in output

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by shermp** [comment]
Hmm, I need to think of a way to escape valid tags?

Something like `[!/b]`? Or `[[/b]]`?

If anyone has better escape ideas please let me know!

**Comment by shermp** [comment]
Ah, my memory must be getting hazy. I did allow escaping tags.

@FeralChild64 try `\[/b]` (or ``\\[/b]`)

**Comment by FeralChild64** [comment]
I’ll try, but I don’t have access to my development environment right now.

Do you know which switches are affected? We might need to do some search&replace fixing, other commands/programs might be affected too.

**Comment by shermp** [comment]
The single letter switches that would potentially need escaping are `[/i] [/b] [/u] [/s]`

**Comment by kcgen** [comment]
Looks like only `[/b]` and `[/s]` needed escaping.
Pushed to kc/escape-tags-1

I used this git-replace alias inside the `contrib/` folder:
``` shell
grp '\[/b\]' '\\[/b\]'
grp '\[/s\]' '\\[/s\]'
```

``` shell
# git replace
grp() {
    local -r search="$1"
    local -r replace="$2"
    shift; shift
    sed -i "s^${search}^${replace}^g" $(git grep -l "${search}" "$@")
}
```
