### ISSUE TITLE
Quitting while certain games are running freezes the app

### ISSUE THREAD

**Issue by distantvale** [dosbox-staging/dosbox-staging#2347]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### What Operating System are you using?

Windows 11

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

When attempting to quit (ALT+F4 or CTRL+F9) while running certain games, the app freezes and the only way to close it is to kill the process.

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Run the attached game
2. Press ALT+F4

### Your configuration

```ini
tput             = opengl
machine            = svga_s3
memsize            = 16
aspect             = true
core      = auto
cputype   = auto
cycles    = auto
sbtype              = sb16
sbbase              = 220
irq                 = 7
dma                 = 1
hdma                = 5
xms                   = true
ems                   = true
umb                   = true
```

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by distantvale** [comment]
[OTHELLO.zip](https://github.com/dosbox-staging/dosbox-staging/files/11012521/OTHELLO.zip)

**Comment by johnnovak** [comment]
To be clear, test with the game attached in the above comment to reproduce.

**Comment by kcgen** [comment]
Reproduced all the way back to 0.76.

**Comment by kcgen** [comment]
When Ctrl + F9 is pressed, the game interprets the input as these right arrows:

![2023-03-20_17-36](https://user-images.githubusercontent.com/1557255/226500060-8e2773de-1a98-4e55-9ea1-0ae28d03f472.png)

However, DOSBox Staging does detect the exit request, and this gets logged in the console:

```
2023-03-20 18:40:38.362 | SDL: Exit requested
```

The console input is still running, waiting for text input.

As soon as the input loop is completed, it catches the exit detection and exits.  So pressing Ctrl+F9 followed by `Enter` is enough to get out.

Staging doesn't throw an exception when Ctrl+F9, and instead we do an orderly exit (checking for the request, then exiting back up to the CPU loop, and finally out from there and out of the `main` function). 

The problem with this approach is we need execution to pass over these exit checks, where as an exception would forcefully jump the execution out of the input wait step.
