### ISSUE TITLE
On `ww/voodoo-3dfx-2`, when DOSBox creates a new instance for Voodoo Emulation it causes my Steam Deck to crash

### ISSUE THREAD

**Issue by ThomasEricB** [dosbox-staging/dosbox-staging#2361]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Different version than latest?

0.81.0-alpha, branch ww/voodoo-3dfx-2

### What Operating System are you using?

Linux x86_64

### If Other OS, please describe

NixOS installed on a Chroot on SteamOS 3.0. Running on Gamescope (Game Mode), a Wayland based mode.

### Relevant hardware info

Steam Deck: Processor: AMD APU - CPU: Zen 2 4c/8t, 2.4-3.5GHz (up to 448 GFlops FP32) - GPU: 8 RDNA 2 CUs, 1.0-1.6GHz (up to 1.6 TFlops FP32) - RAM: 16 GB LPDDR5

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Right now, every time you launch a game that uses 3dfx's Voodoo 1, DOSBox Staging tears down SDL's existing context and reinstates a new instance for Voodoo's GL. This tear-down and regen of content inside Gamescope (not in Steam Decks desktop mode!) causes my hardware, the Steam Deck, to completely crash and make it reboot. Really odd behavior that wasn't happening before the new Steam Deck update nor before the new update for @Tormak9970 's Bash Shortcuts (I talked to him and it doesn't seem like it's from his end, probably something to do with Gamescope). **Even though this is probably being caused by the former, this is relevant for DOSBox Staging. That's because creating a new instance isn't desirable**, as according to @kcgen, ["re-using the same GL content will be something we will want (instead of tear-down and regen)"](https://discord.com/channels/514567252864008206/852376220117237840/1037250865544835072), so this needs to be fixed at some point before merging into main. I feel like this should be high priority for this branch. I hope that at some point @Wengier might take a look at this. 

Here is a video of this issue happening (bear in mind that I'm recording the footage through Steam Remote Play and a Ethernet cable):

https://youtu.be/wej9JAk0UuE

Also here is a video of me running Voodoo with no issues on Desktop mode:

https://www.youtube.com/watch?v=5driVM8yIck

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Have a Steam Deck and Run DOSBox Staging on Game Mode (also known as Gamescope)
2. Install any Voodoo1 game and install the drivers (if on Windows 9.x)
3. Run a Voodoo game

### Your configuration

```ini
[pci]
voodoo = opengl
voodoomem = max
```

### Provide a Log

```text
N/A
```

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by kcgen** [comment]
Thanks for the thorough explanation, @ThomasEricB.
Fully agree this GL context reuse is critical to getting this merge-ready.

**Comment by Kappa971** [comment]
One question, will the 3dfx emulation for DOS games also work in DOSBox without having to install Windows 95 (like in the old DOSBox Daum or DOSBox ECE or various customized GOG versions)?

**Comment by ThomasEricB** [comment]
> One question, will the 3dfx emulation for DOS games also work in DOSBox without having to install Windows 95 (like in the old DOSBox Daum or DOSBox ECE or various customized GOG versions)? If yes, is there an option to adjust the resolution? (I assume you're not using nGlide).

It works without having to install Windows 95 (Windows 9.x are unsupported by DOSbox Staging!)

> If yes, is there an option to adjust the resolution? (I assume you're not using nGlide).

If there isn't I'll take a look on how to implement support to that.

**Comment by elektronicznypank** [comment]
> 1. Game Mode (also known as Gamescope)

As far as i know, gamemode and gamescope are two different things. Which one did you mean?

**Comment by ThomasEricB** [comment]
> As far as i know, gamemode and gamescope are two different things. Which one did you mean?

Nop, it's the same thing. When you go to "game mode" you swap from x11 to Gamescope

**Comment by ThomasEricB** [comment]
Fixed by https://github.com/dosbox-staging/dosbox-staging/pull/2410
