### ISSUE TITLE
Windows Defender doesn't like DOSBox Staging's executable because it's unsigned

### ISSUE THREAD

**Issue by ThomasEricB** [dosbox-staging/dosbox-staging#2369]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### What Operating System are you using?

None

### If Other OS, please describe

Windows 10

### Relevant hardware info

CPU: Intel (R) Core (TM) i7-7700k CPU @ 4.2GHz | RAM: 32,00 GB | GPU: GeForce GTX 1080ti 11GB

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

As @dreamer pointed out [here](https://discord.com/channels/514567252864008206/852376220117237840/1090453518441271347), because the Windows Executable is unsigned, Windows Defender will not allow it to copy the .exe file and will delete the .exe in any folder that it will be placed. 

![image](https://user-images.githubusercontent.com/9662095/228407134-7ef05209-a268-48a7-ba33-f36ee6b949c5.png)

This is critical, because if someone that is not knowledgable about Windows they will be unable to use the executable or worse, they might think DOSBox Staging is untrustworthy.

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Unzip the executable provided in the downloaded .zip
2. Unable to execute the program

### Your configuration

```ini
N/A
```

### Provide a Log

```text
N/A
```

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by kcgen** [comment]
Thanks for the help writing up the ticket, @ThomasEricB  and for the heads-up about this issue, @dreamer.

**Comment by kcgen** [comment]
If anyone has a Microsoft account, please submit the binaries in the release zip package(s) to Microsoft for analysis: https://www.microsoft.com/en-us/wdsi/filesubmission

The more submissions, the better, as they use both virus scanning and reputation.

**Comment by ThomasEricB** [comment]
This is a weird case, for me, where it sometimes happens with MYSYS builds from Actions. This happened when you gave me that zip file to test Code Page 860 for instance...

**Comment by kcgen** [comment]
Is anyone able to reproduce this extracting the release .zip file on a vanilla installation of Windows 10?

The 0.80.1 64-bit zip has been downloaded ~4,000 times, and this is the first time it's been reported:

![2023-03-31_11-33](https://user-images.githubusercontent.com/1557255/229202161-7ecd30d4-8187-402d-846b-c0825ec96cf7.png)

https://api.github.com/repos/dosbox-staging/dosbox-staging/releases

Maybe some additional security measures are causing this?

**Comment by shermp** [comment]
I just downloaded the latest MSYS2 ZIP from Actions, and it successfully extracted on Windows 11.

**Comment by Torinde** [comment]
I think this error is a different one from "executable is unsigned", but maybe it's still "tightened security"-related...
My tests (but not on "vanilla" Windows):
- latest MSVC x64 from actions - when extracting the ZIP was flagged for "Cloud check", which happened automatically (e.g. file was sent to Microsoft and checked with something more than the Win10 desktop Defender?) and all files got to the destination OK at the end.
- 0.80.1 installer EXE - downloaded without problems (e.g. in other cases I get warning "This file is not common, are you sure you want to it?" - for Staging installer I didn't get that)
- 0.80.1 x64 ZIP - downloaded without problems
- 0.80.1 x64 ZIP when extracting with Windows built-in "compressed folders" - **got the same error** as @ThomasEricB (and no Defender warnings)
- 0.80.1 x64 ZIP when extracting with 7-Zip - no problems

**Comment by kcgen** [comment]
Very interesting. Thank you for these tests, @Torinde !

From this result: *"0.80.1 x64 ZIP when extracting with 7-Zip - no problems"* -> can you use Windows built-in "compressed folders" to compress the result back into a ZIP, and then re-extract that new zip with Windows built-in "compressed folders"?

If that works, can you post the ZIP here, too?

(I will double check internal checksums to be sure all is as expected)

The plan will be to replace the 0.80.1 release zip with the zip produced from your built-in "compressed folders" feature :slightly_smiling_face: 

If this works, then we'll use this approach for the next release too.

**Comment by Torinde** [comment]
[CF dosbox-staging-windows-x86_32-v0.80.1.zip](https://github.com/dosbox-staging/dosbox-staging/files/11130238/CF.dosbox-staging-windows-x86_32-v0.80.1.zip)
[CF dosbox-staging-windows-x86_64-v0.80.1.zip](https://github.com/dosbox-staging/dosbox-staging/files/11130239/CF.dosbox-staging-windows-x86_64-v0.80.1.zip)
The original 32-bit version gave the same error, but with file "iconv-2.dll"

**Comment by kcgen** [comment]
@Torinde - thank you!

The content checksums match, so I've replaced the prior 0.80.1 release zips with your blessed versions. 

Link to the releases: https://github.com/dosbox-staging/dosbox-staging/releases/tag/v0.80.1

Hopefully this does the trick!

**Comment by kcgen** [comment]
Closing this out given @Torinde reproduced the issue and confirmed it's now fixed with the zips.
