### ISSUE TITLE
DOSBox doesn't receive Control keypresses when the Caps Lock and Control keys are swapped on macOS

### ISSUE THREAD

**Issue by johnnovak** [dosbox-staging/dosbox-staging#2371]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Different version than latest?

main

### What Operating System are you using?

Mac OS

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

When the Caps Lock and Control keys are swapped in the Keyboard preferences on macOS, DOSBox doesn't receive any Control keypresses.

<img width="780" alt="image" src="https://user-images.githubusercontent.com/698770/228748385-2da5d055-71ec-48d8-965c-f6dd8c2895f9.png">

### Steps to reproduce the behaviour.

1. Start DOS Navigator
2. Press Ctrl+O that should hide the directory panes
3. You'll the letter `O` being printed to the command line and that's it...

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by kklobe** [comment]
I tested this with SDL2 2.26.5, which claims a fix, and with swapped Ctrl <-> Caps Lock modifiers as per your screen shot, Ctrl-O worked properly in DN 1.51.

https://github.com/libsdl-org/SDL/releases/tag/release-2.26.5

**Comment by johnnovak** [comment]
That's great news @kklobe, this was driving me crazy as I'm a chronic CapsLock / Control swapper :)

**Comment by kklobe** [comment]
Preach! Just about the first thing I do on any new OS install, Caps -> Ctrl, can hardly function until that's done.

**Comment by johnnovak** [comment]
> Preach! Just about the first thing I do on any new OS install, Caps -> Ctrl, can hardly function until that's done.

I'm exactly the same. And neither can my colleagues when they to do anything on my machine. It's a secondary protection layer after my vim-shorcuts-everywhere deterrent mechanism 😄

**Comment by Burrito78** [comment]
This did/will land it main automatically and appear in the next release so closing as complete.

**Comment by johnnovak** [comment]
So apparently I'm using SDL 2.28.1 here and this is still an issue. But I swear it was working again. Did they perhaps fix it then broke it again? If we pinned... :ducks:

```
2023-08-24 16:10:02.493 | SDL: version 2.28.1 initialised (cocoa video and coreaudio audio)
```

**Comment by kcgen** [comment]
> How can we specify an SDL lib version to build against?

In meson.build, each dependency has an allowed exact version or range:

```python
sdl2_dep = dependency(
    'sdl2',
    version: ['>= 2.0.5', '< 3'],
    static: ('sdl2' in static_libs_list),
    include_type: 'system',
)
```

You can try tightening that range or going with an exact `version: '2.26'` or something like `version: '<2.28.1'`.

**Comment by johnnovak** [comment]
Thanks @kcgen. It's broken in their later 2.28.2 patch release as well.

Turns out I can't just go and downgrade packages in MacPorts (or any Unix/Linux package manager? The wonders of making the whole world march to the same beat... 😅) so I gave up on testing with earlier releases. But I'm 100% sure it was working before as I'm using these Ctrl shortcuts in  DOS Navigator all the time. 

I've raised an issue in their bug tracker:
https://github.com/libsdl-org/SDL/issues/8156

**Comment by johnnovak** [comment]
Uh, started working again a while ago. I'm hoping it was just user error 😊 @kklobe @Grounded0 can you confirm this works for you too using the latest dev build?

**Comment by kklobe** [comment]
> Uh, started working again a while ago. I'm hoping it was just user error 😊 @kklobe @Grounded0 can you confirm this works for you too using the latest dev build?

Looks good on `main`.

![DN-CTRL-O](https://github.com/dosbox-staging/dosbox-staging/assets/541026/65bfab17-94bb-4ac1-b359-d2b5fe3dd58d)

**Comment by Grounded0** [comment]
```
2023-11-27 01:26:48.515 | SDL: version 2.26.5 initialised (cocoa video and coreaudio audio)
```

We can bump to 2.28 branch of SDL once they fix this there. Someone should build with 2.28.5 and see does it happen there.

**Comment by Grounded0** [comment]
[SDL 2.26.5 release notes](https://github.com/libsdl-org/SDL/releases/tag/release-2.26.5):

• Fixed incorrect modifier keys handling on macOS

**Comment by kklobe** [comment]
> ```
> 
> 2023-11-27 01:26:48.515 | SDL: version 2.26.5 initialised (cocoa video and coreaudio audio)
> 
> ```
> 
> 
> 
> We can bump to 2.28 branch of SDL once they fix this there. Someone should build with 2.28.5 and see does this work there.

Yep, that's what I'm on.

**Comment by johnnovak** [comment]
> > ```
> > 
> > 2023-11-27 01:26:48.515 | SDL: version 2.26.5 initialised (cocoa video and coreaudio audio)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > We can bump to 2.28 branch of SDL once they fix this there. Someone should build with 2.28.5 and see does this work there.
> 
> Yep, that's what I'm on.

I'm on 2.28.4. Seems to be fine then, so we can close this.

<img width="804" alt="image" src="https://github.com/dosbox-staging/dosbox-staging/assets/698770/02db95e0-b4ce-4fff-89cd-ed3311bc3915">

**Comment by Grounded0** [comment]
This will finally allow us to deploy the SDL 2.28 branch so this is good.
