### ISSUE TITLE
Brazilian Portuguese translation underway -- Precisamos de voluntários!

### ISSUE THREAD

**Issue by ThomasEricB** [dosbox-staging/dosbox-staging#2375]
### Version and Branch:

`0.81.0-alpha, branch teb/Brazilian-Portuguese`

### Message:

Olá amigos (Hello folks)!

I've started an effort to translate DOSBox Staging into Brazilian Portuguese in branch `teb/Brazilian-Portuguese` ! You can check out the current progress at https://github.com/dosbox-staging/dosbox-staging/blob/teb/Brazilian-Portuguese/contrib/resources/translations/br.lng ! Don't be shy in contributing, keeping in mind that any Pull Requests should be done to the `teb/Brazilian-Portuguese` branch and not to `main` itself. Also, feel free to submit any suggestions below!

Obrigado e tenha um ótimo dia (Thank you and have a nice day)!

**Comment by johnnovak** [comment]
Any progress on this @ThomasEricB ?

**Comment by johnnovak** [comment]
Close due to inactivity. @ThomasEricB can reopen later if he wishes to.

**Comment by ThomasEricB** [comment]
> Any progress on this @ThomasEricB ?

Hey sorry for not replying sooner but every progress is on here: https://github.com/dosbox-staging/dosbox-staging/tree/teb/translation-utility 

Law School and real life took a toll on me, sorry
