### ISSUE TITLE
Is there a way to import a text file or "real" autoexec.bat file into the [autoexec] section of the current config?

### ISSUE THREAD

**Issue by Banjo-Oz** [dosbox-staging/dosbox-staging#2382]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### What Operating System are you using?

Windows 7

### Whats your question and how can we help?

If I had a file named autoexec.bat in my mounted c drive (or a text file containing similar lines), is there a way to make "config" write the contents of this file to my current configuration (dosbox-x.conf) under the [autoexec] section? I don't mind if it erases everything in that config section or if it adds to the ones already there.

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by dreamer** [comment]
Perhaps you just want to call your autoexec.bat file in autoexec section of your .conf file?

For example, like this:

```ini
[autoexec]
mount C ~/.local/DOS/drives/c
C:
@cls
@autoexec.bat
```

**Comment by Banjo-Oz** [comment]
> Perhaps you just want to call your autoexec.bat file in autoexec section of your .conf file?
> 
> For example, like this:
> 
> ```ini
> [autoexec]
> mount C ~/.local/DOS/drives/c
> C:
> @cls
> @autoexec.bat
> ```

Thanks for the reply!

That's actually what I've been doing currently (creating a "fake" autoexec.bat with all my commands apart from basic drive mounts in it, then adding that to [autoexec] to run like your example) however in doing so, I just got wondering if such a file could be imported directly into DOSBox's [autoexec] section, since we can use -axtype to add a single line, I was imagining something like -axfile to add the contents of a text or bat file. e.g. config -axfile C:\MYBOOTUP.TXT

Since this can be worked around, it's hardly essential, but just an idea, since I was working on a utility that creates an autoexec.bat with guided prompts and that was what made me think about a version that worked directly with DOSBox's [autoexec] section rather than a separate file.

**Comment by dreamer** [comment]
I was not aware that `config -axadd <line>` is a thing, and ATM I'm not sure why this functionality exists...

 But yeah - it seems like it works for your case (I think?).

Your suggestion for (`config -axfile <file>`) seems interesting; can you show how would you like to use it?

Do you want to have a separate script wrapping DOSBox to generate .conf files, like this:

```bash
#!/bin/bash
dosbox -noautoexec \ 
        -c 'config -axclear' \
        -c 'config -axadd "@echo hello-world!"' \
        -c 'config -wcd' \
        -exit
```

(or some variation on the idea)

**Comment by johnnovak** [comment]
Adding support for this seems like feature bloat to me. Existing solutions mentioned so far seem perfectly adequate, IMO.

**Comment by kcgen** [comment]
I agree @johnnovak ; the layered conf system is both elegant and complex - but still manageable to understand and document.

Folding in a second way to inject auto exec content (separate from the existing conf system) opens up the complexity flood gates: imagine config axfile calls inside [autoexec] blocks themselves, in addition to the CLI, and multiply that into several conf layers. The result would be beyond predictable. 

I like @dreamer's suggestion; it's nice and predictable.

**Comment by dreamer** [comment]
These `config` options were added in 143beec6b12b947fb983be54f78952144ab7fe6d - it seems like the main functionality was to enable user to edit and save .conf files in interactive session... which is nice for sake of completeness of `config` command, but otherwise I agree that it feels "bloaty". They are even [documented](https://github.com/dosbox-staging/dosbox-staging/blob/main/README#L862).

I can imagine only two usecases really:

1. Allows user to reconfigure everything in runtime and store the results (hey, someone can write TUI for configuration without touching DOSBox source code)!
2. Allows user to save .conf properly encoded according to the language setting. This is quite interesting feature! Without it it's somewhat hard to figure out how to write text file in DOS encoding correlating to the language selected.

For example, I can set my .conf file to `language=pl` and then type inside DOSBox:

    Z:\>config -axadd "@echo Zażółć" "@echo Gęślą" "@echo Jaźń"
    Z:\>config -wcd

Without googling what codepages to use and how to convert from utf8 to that codepage...

@Banjo-OZ Do you have some other usecase for generating autoexec at runtime? I think we'll eventually close this question without implementing new features… unless we'll find some really useful usecase.

**Comment by johnnovak** [comment]
>For example, I can set my .conf file to language=pl and then type inside DOSBox:
>Both of these usecases are really niche though.

Well, yeah... ultra-niche, I'd say 😅

**Comment by kcgen** [comment]
@dreamer, good news is the conf and language system are all UTF-8 clean now thanks to @FeralChild64 :  https://github.com/dosbox-staging/dosbox-staging/pulls?q=is%3Apr+utf-8+author%3AFeralChild64 , so using a modern UTF-8 editor is safe and reliable.

**Comment by dreamer** [comment]
@kcgen @FeralChild64 - superb! Unfortunately that means we have a bug in `config -wcd` - it overwrites the .conf file with DOS-encoded version of the file :(

**Comment by dreamer** [comment]
@FeralChild64

Steps, testing 0.80.1:

1. I am using en.GB locale; completely clean config, in freshly created dosbox-staging.conf I change to `'language = pl`
2. Run emulator and type `config -wcd` (.conf file is re-written in unicode, all the comments are now in polish, great!)
3. Run emulator again, now type:
    ```
    Z:\>config -axadd "@echo zażółć"
    Z:\>config -wcd
    Z:\>exit
    ```

And right, only autoexec section got rewritten in DOS encoding... rest of file is still in unicode... but it doesn't matter - almost none of the software I tried was able to handle the file correctly. `vim` and `neovim` both display it as non-utf (latin1 I presume), `firefox` opens it as latin1, `gnome-text-editor` is refusing to save file. Only `cat` and `meld` show it sort-of ok.

Even after adding [BOM](https://en.wikipedia.org/wiki/Byte_order_mark) manually - firefox can now open it as unicode, other programs are more or less confused by mixed-encoded file...

So it's not *that* bad, but well - I would still consider it a bug. But super-low priority, I think.

**Comment by FeralChild64** [comment]
Actually, I need some use case to implement/test DOS -> UTF-8 conversion, and I also don't like the fact that saving the configuration eats all the empty lines in [autoexec] section, so intend to take care about this :)

**Comment by kcgen** [comment]
It might make the most sense to keep the DOS autoexec block in it's native DOS codepage, beacuse that content must be digestible by DOS applications. 

The alternative - if those strings could be switched to UTF-8, we'd need a way to switch them back to their DOS CP, which might not be CP437, and there's also no guarantee they match the language of the conf file itself; so at the time of conversion, we'd need to embed an identifier to assist in this conversion back to DOS-native CP.

**Comment by FeralChild64** [comment]
IMHO the best would be to keep [autoexec] in UTF-8 internally, all the time, as DOS code page can be changed in runtime:

- during the startup, or with code page change - we convert [autoexec] to Z:\AUTOEXEC.BAT using appropriate code page
- if a new line is added - we convert it to UTF-8, add it to internal [autoexec] (and, of course, to AUTOEXEC.BAT, without conversion)

I think this would be the easiest way.

**Comment by ThomasEricB** [comment]
> IMHO the best would be to keep [autoexec] in UTF-8 internally, all the time, as DOS code page can be changed in runtime

I agree 100% with @FeralChild64 here. His solution is very elegant and ideal.

**Comment by FeralChild64** [comment]
Not ideal, as there are some problems converting from FreeDOS code pages to UTF-8, namely:

```
# (*) The following symbols had to be worked around as they are missing in Unicode standard:
# - 30025      : LATIN CAPITAL LETTER D WITH HOOK AND TAIL (only the SMALL one is available)
# - 991, 58335 : PLN SYMBOL (currency)
# - 30019      : CYRILLIC LIGATURE UO (both SMALL and CAPITAL)
#
#
# Code pages mostly supported (3 code pages), but with unidentified characters still left (TODO):
#
# 864   - Arabic
#       - 5 characters (FreeDOS specific extension) still unidentified
# 59829 - Georgian
#       - 1 character still unidentified
# 60258 - Russian Cyrillic and Latin Azeri
#       - dotted capital I not handled due to UTF-8 code limitation
```

We might be able to fix problems with code pages 864 and 59829 if someone knowing these alphabets (native speaker?) tells me which Unicode graphemes the unidentified characters represent.

To fix code pages 30025, 991, 58335, 30019 we would need to extend the Unicode standard. I was actually thinking about submitting a request for PLN SYMBOL (it's 'zł', these two letters should form a single symbol), but I would need to find some organization which would agree to provide free TTF font with such a symbol (if I understand correctly the Unicode organization rules).

Code page 60258 is most likely impossible to fix. The FreeDOS folks decided to put a dotted capital letter 'I' (U+0130 - 'İ') as character 0x49 (thus, the code page is no longer an ASCII), and move the classic, dotless 'I' somewhere above 0x7F - I have absolutely no idea how should we handle something like this without breaking things and properly displaying file names.

**Comment by ThomasEricB** [comment]
> Not ideal, as there are some problems converting from FreeDOS code pages to UTF-8, namely:

I had no clue there were even such gaps! Great digging!

**Comment by johnnovak** [comment]
My view: 

[](https://miro.medium.com/v2/resize:fit:750/format:webp/0*BpxXEoRod291jC-M.jpg)

Seems like an edge case probably no one will ever hit... but technically a bug.

Anyway, I'm the sort of person who doesn't get why anyone would want to localise DOS, so... 😄 

> This will be a good testcase before my Unicode engine is used for TTF display output :)

Are you going to actually do that yourself? If so, I've already added stb_truetype and fontstash to the project. I will use these libraries for te OSD work, please read my PR comment.

https://github.com/dosbox-staging/dosbox-staging/pull/2075

**Comment by FeralChild64** [comment]
I don’t intend to work on the TTF output anytime soon - I have full hands with other things. But at least we will have the DOS to Unicode part.

There is already some implementatation by @Wengier, but it uses FreeType and SDL_ttf libraries - https://github.com/dosbox-staging/dosbox-staging/tree/ww/ttf-output-1. Nevertheless, it can be a good reference.

**Comment by johnnovak** [comment]
> I don’t intend to work on the TTF output anytime soon - I have full hands with other things. But at least we will have the DOS to Unicode part.
> 
> There is already some implementatation by @Wengier, but it uses FreeType and SDL_ttf libraries - https://github.com/dosbox-staging/dosbox-staging/tree/ww/ttf-output-1. Nevertheless, it can be a good reference.

Yeah we discussed it with @Wengier and agreed that Freetype and SDL_ttf are no-go. I'm pretty sure he just took that from DOSBox-X and he was going to migrate that to stb_truetype + fonstash as I described on my ticket.

I'm not personally interested in TTF output either, so it's all good then 😄

**Comment by FeralChild64** [comment]
Not that I'm not interested - I just have plenty of other things to do, which I consider higher priority.

**Comment by kcgen** [comment]
@Banjo-Oz , another approach is to use a wrapper conf that simply calls the `autoexec.bat` file. Such as:

**`autoexec.conf`**:
```ini
[autoexec]
@call autoexec.bat
```

Provided C:\ is mounted (and `autoexec.bat` is available there), this approach gives fine-grained control of loading it's lines relative to other conf files. 

For example:

`dosbox-staging . -conf custom1.conf -conf autoexec.conf -conf custom2.conf`

Would load:
 - your primary or portable conf's `[autoexec]` lines first,
 - then local `dosbox.conf` conf `[autoexec]` lines,
 - then `custom1.confs`s lines,
 - then `autoexec.conf`s lines (which call `autoexec.bat`),
 - and finally `custom2.conf`s lines

![2023-04-09_12-49](https://user-images.githubusercontent.com/1557255/230793621-80d44eaf-ccc0-4aa9-9255-b864bd156edb.png)



**`autoexec.bat`**:
```shell
@echo autoexec
```


**`custom1.conf`**:
```ini
[autoexec]
@echo custom 1
```

**`custom2.conf`**:
```ini
[autoexec]
@echo custom 2
```

**`dosbox.conf`**:
```ini
[dosbox]
autoexec_section = join

[autoexec]
@echo local
```

Here's a zip, if you want to try it out:

[2382.zip](https://github.com/dosbox-staging/dosbox-staging/files/11186198/2382.zip)
