### ISSUE TITLE
DLLs named wrong, one is missing?

### ISSUE THREAD

**Issue by SolsticeProjekt** [dosbox-staging/dosbox-staging#2394]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### What Operating System are you using?

Windows 10

### Whats your question and how can we help?

Hello.

First: Please know that I have no idea what I am doing, this is my first ever build. I have had bing's AI guide me through this process, including installing mingw (apparently for nothing) and msys2. I will be using chatgpt for hopefully small changes to the source beyond the scope of my question and I only want to steal as little of your time as possible. Still, bing suggested I reach out to you, so here I am. Also know that I do not speak C at all, but other languages.

The code I've downloaded is the latest from github. Bing told me how to do that.

My questions:

I've successfully managed to build dosbox-staging. It's in the release-gcc folder. The executable is there, but when I run it, it complains about missing DLLs. Okay, that makes sense, I thought. So I've copied the DLLs from the official installation over, thinking that might work ... but no.

So, two problems:

(1) "The code execution cannot proceed, because" ... libiir.dll, libmt32emu-2.dll, libopusfile-0.dll, libslirp-0.dll ... "were not found".

The DLLs the freshly built program looks for are named differently than the ones the official release uses. That's fine, I've renamed them, but I don't know yet if that actually works, because of (2). Why would they be named differently, though? That makes no sense to me.

(2) There is one DLL missing. It's not part of the official release, yet the freshly built one asks for it. "libslirp-0.dll" is not part of the official release, at least not with any name that would allow me to recognize it as such. Why is it required, when it's not part of the official release and where do I find it? I've installed the official release today, btw, maybe two hours ago.

I do not know if there are other problems looming, because this is as far as I can get.

Can you please clear this up for me and tell me how I can fix this?
I have no idea what I'm doing, and I'll be really, REALLY happy when I can leave C behind me again.

Thank you and I'm sorry for taking away your time.

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by kcgen** [comment]
> This is my first ever build. I have had bing's AI guide me through this process, including installing mingw

We have build documentation. It describes step by step how to install everything needed from scratch and get a working build. 

I would suggest uninstalling and deleting all remnants of what Bing' AI had you install - not as some kind of punishment or out of distrust, but simply because it might interfere, override, or conflict in ways that none of us can predict. 

Please read the project's README.md fully. It will link you To OS-specific  Windows MSYS2 instructions. 

If you follow those exactly, it should result in a working build. 

Good luck! Hopefully you come back with good news 👍

**Comment by SolsticeProjekt** [comment]
Well ... after going through the process again,
exactly how it's written in build-windows.md,
which is exactly, to the T, what Bing told me to do (because I pointed it at it and it told me what's there) ...

... I've realised that my home directory contained a new directory, called "dosbox-staging-gcc-pkg".

"./scripts/create-package.sh -p msys2 build/release-gcc ../dosbox-staging-gcc-pkg"

I am dumb.
It works.
I'm sorry.

Thank you!

**Comment by kcgen** [comment]
Nice work in picking out that detail, and thank you for highlighting it's importance here for any readers! 

Glad you're up and running.

**Comment by dreamer** [comment]
@SolsticeProjekt do you mind sharing what you asked Bing AI exactly?

Also, are you sure you want to compile DOSBox Staging by yourself as opposed to using either our [stable build](https://dosbox-staging.github.io/downloads/windows/) or [development snapshot build](https://dosbox-staging.github.io/downloads/development-builds/)?

**Comment by SolsticeProjekt** [comment]
Hey.

Well, it suggested that, because I asked it to help me with that process.
I can't give you the exact wording anymore, because that window is gone already. "Broomed" away.

I need to change a small bit of code responsible for receiving input, compile that and use the result for myself.
It's the optimal solution for the problem I am having in regards to providing input to dosbox.

I'm pretty damn sure it's a really small change,
but I still require chatGPT to help me, because I don't speak C ... but that's totally fine.

I'm not planning on releasing my personal build, at all, ever.
It'll be used in my own group only, which i believe means that I'm not violating the license.

Sorry I can't really give you any more details.

**Comment by dreamer** [comment]
Well, maybe you can share what problem are you trying to solve anyway? :smile: 

Maybe we can help you by pointing you in the correct direction in code, or maybe even your solution will help someone else?

**Comment by SolsticeProjekt** [comment]
I'm sorry, but I can't tell you. There will be people who will attempt to copy what I'm going to do,
and every day, they can't manage to do that, is a win for me. 

That's also why I'm going to edit my comments here, to make sure they won't find any hints. :)
I am not trying to do anything illegal, or anything which violates the license.

I'm just trying to do something *new* that, as far as I know, nobody has done so far. :)

In regards to bing and chatgpt writing code ... yeah, they often write code that doesn't necessarily work,
BUT they ALSO write code which actually can work! Like a neural network on the most fundamental level!

They're both capable in terms of reproducing the logical steps of code.

It's fascinating what they can do. ChatGPT can, for example, explain to you how LZW compression works,
*because it read the paper*, actually apply it immediately in a response,
re-read it in a prompt and decompress that result "mentally"
to use it to increase the context window it *sometimes denies to have*.

It found my approach really interesting, while denying it has a context window,
while at the same time helping me improve its context window for our conversation! lol

If you want to use chatgpt or bing, you have to figure out how to word things properly and be aware that it, when it produces faulty code, not necessarily remembers what it does wrong. It stubbornly tries to fix the error regardless of the context and "big picture".

I've caught both trying to fix errors without considering the rest of the code, which caused them both to pile up more and more errors. Someone, who never wrote any code, will have some serious struggles. When it does that, it's required to make them re-consider the whole approach (and the prompter to re-think the prompt).

I'm pretty confident that I am able to use chatgpt to help me writing the code I need.
Worst I will figure it out myself, but I doubt that it's needed. I don't like C.

Sorry I can't give you any more input.
I need every advantage I can get, before everyone else starts doing the same. :)

**Comment by kcgen** [comment]
Not understanding why your language model experiement(s) didn't produce your desired results is one thing, but posting it as newbie build issue for an open source team to expend time from their day is a brutally entited behavior, given the team here took your issue at face value and assumed you were simply flailing about struggling to find or follow the notes. 

Well. I'm not getting these hours back. 
Feel free to join our discord if you have ideas for how you would like to make ammends.
