### ISSUE TITLE
AWE32/AWE64 Support

### ISSUE THREAD

**Issue by OpenRift412** [dosbox-staging/dosbox-staging#2396]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### What Operating System are you using?

Windows 11

### Is your feature request related to a problem? Please describe.

I realized recently that Dungeon Keeper (and other games as well) supported audio effects that were exclusive to those with AWE32 and AWE64 cards. In the case of Dungeon Keeper, the game uses a built-in soundfont with the AWE32 to create additional ambient sounds. I'm sure some other DOS games have very similar features as well.

### Describe the solution you'd like

I think having AWE32 (and AWE64 if necessary) emulation would be a much-appreciated feature for getting the best auditory experience possible out of Staging, given the heap of existing features and options for the current set of emulatable sound methods.

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by OpenRift412** [comment]
> Yes! See discussion: [#1682 (comment)](https://github.com/dosbox-staging/dosbox-staging/issues/1682#issuecomment-1491177943)

Gotcha. Has any progress been made in implementing it? Or is there other things on the to-do list to address first?

**Comment by johnnovak** [comment]
> > Yes! See discussion: [#1682 (comment)](https://github.com/dosbox-staging/dosbox-staging/issues/1682#issuecomment-1491177943)
> 
> Gotcha. Has any progress been made in implementing it? Or is there other things on the to-do list to address first?

Progress has definitely been made as I started researching it. My cautious prediction is that support will be added by the end of the year if things go well.

**Comment by OpenRift412** [comment]
> Progress has definitely been made as I started researching it. My cautious prediction is that support will be added by the end of the year if things go well.
> 
> There are no other dependencies; I'll actually get started in the coming weeks. I already have an AWE32 in my physical DOS-box, next step is to get the digital output going as it helps with reverse engineering.

Well I do know that PCem and 86Box both have options to emulate the AWE32, so perhaps there's code there that could be used?

> You might be delighted to hear that Dungeon Keeper will be the "leading game" to get going first, and I'm a big fan of the series.

Great to hear :)

**Comment by ThomasEricB** [comment]
> Well I do know that PCem and 86Box both have options to emulate the AWE32, so perhaps there's code there that could be used?

Well, in this specific case, @johnnovak decided to write his own code for it. 

In any case, I advise you @OpenRift412 NOT to hold against John if he doesn't end up meeting the end of the year for AWE32. These are goals, not promises nor deadlines!

**Comment by OpenRift412** [comment]
> 
> Well, in this specific case, @johnnovak decided to write his own code for it.
> 
> In any case, I advise you @OpenRift412 NOT to hold against John if he doesn't end up meeting the end of the year for AWE32. These are goals, not promises nor deadlines!

That's fine, I wasn't really going to hold it against him. I was just giving a suggestion that may help with his goal.

**Comment by ThomasEricB** [comment]
> That's fine, I wasn't really going to hold it against him. 

Yeah, don't worry. I just had to post that since some people might think they are entitled to something when dates get mentioned. I don't want anyone to read that and extract unwanted expectations from it.

**Comment by johnnovak** [comment]
> Well I do know that PCem and 86Box both have options to emulate the AWE32, so perhaps there's code there that could be used?

Thanks for that, I'm aware of it. I was planning to just port that one, but I find it a bit questionable; too many assumptions and unfinished business there, so I'll just start from first principles 😄
