### ISSUE TITLE
Release notes are all broken links

### ISSUE THREAD

**Issue by LauraTaylorUK** [dosbox-staging/dosbox-staging#2400]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Different version than latest?

Git

### What Operating System are you using?

None

### If Other OS, please describe

All

### Relevant hardware info

n/a

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Under the Releases page, all release notes URLs are broken:

https://dosbox-staging.github.io/v0-80-0/        (404)
https://dosbox-staging.github.io/v0-80-1/        (404)
https://dosbox-staging.github.io/v0-79-0/        (404)
https://dosbox-staging.github.io/v0-79-1/        (404)

etc.

### Steps to reproduce the behaviour.

Explain how to reproduce
1.  Go to: https://github.com/dosbox-staging/dosbox-staging/releases
2. Click on the release note URLs
3. Note how they all produce 404 errors

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by ThomasEricB** [comment]
Can reproduce.

**Comment by MasterO2** [comment]
> Fixed, but needs a second set of eyes ☑️ before closing.

I clicked on every release note URL.  All release notes URLs are now working.

**Comment by kcgen** [comment]
Thanks for reporting this, @LauraTaylorUK !

**Comment by johnnovak** [comment]
Nice catch @LauraTaylorUK! Thanks for fixing @kcgen.
