### ISSUE TITLE
MIDI not working on macOS through Coreaudio in latest DEV version

### ISSUE THREAD

**Issue by Burrito78** [dosbox-staging/dosbox-staging#2402]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Different version than latest?

0.81.0-alpha-553

### What Operating System are you using?

Mac OS

### If Other OS, please describe

Big Sur 11.7.6

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

When testing MIDI playback i get no MIDI output through Coreaudio

Stable 0.80.1 is working fine!

mididevice is "auto".

Log says that Coreaudio is used for MIDI.

Tested in Descent and Dark Forces setup programs.

### Steps to reproduce the behaviour.

Explain how to reproduce
1.  Download latest DEV version
2. Start with a fresh config
3. Try to configure and test MIDI (Port 330) in Descent/Dark Foces setup.exe

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by kcgen** [comment]
Good catch @Burrito78 ; very subtle - it boiled down to a header-file include order (https://github.com/dosbox-staging/dosbox-staging/commit/744869ec92d39a47d47400aac102e6c765d1b1f9)
