### ISSUE TITLE
Can't change Quake viewsize parameter above "99" through in-game menu on ARM machines

### ISSUE THREAD

**Issue by Burrito78** [dosbox-staging/dosbox-staging#2404]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Different version than latest?

0.80.1 and latest DEV

### What Operating System are you using?

Mac OS

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

In Quake SW I can't change the screen size above the default value.
The slider in the menu just won't move beyond that point.

Tested in vanilla, 0.80.1 and latest DEV on macOS Ventura.

On Windows using 0.80.1 it works as expected!

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Download latest DEV on macOS
2. Run Quake SW 1.06
3. Go into menu and try to increase screen size, doesn't work

See the screenshots to see what it should look like:
![IMG_2056](https://user-images.githubusercontent.com/61995128/231757327-8be7f4e5-54de-4c43-b69a-ac3126a32c5c.jpeg)
![IMG_2057](https://user-images.githubusercontent.com/61995128/231757278-f314923f-b622-4dbd-b732-5e5f0d7dc962.jpeg)
![IMG_2058](https://user-images.githubusercontent.com/61995128/231757313-2e348727-52e5-4a26-9830-649fccbc68bf.jpeg)

### Your configuration

```ini
default
```

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by Burrito78** [comment]
OK, tried to reproduce on a second Mac (Macbook Pro mid 2014 running Big Sur latest update), there latest DEV release is working fine using Quake SW 1.06!

So for me it only happens on macMini M2 using macOS Ventura.

**Comment by GranMinigun** [comment]
This is not related to window sizing at all.

@Burrito78, can you please back up your current Quake installation and test with a clean one, preferably patched to 1.08?

**Comment by Burrito78** [comment]
Yes, of course. I've used Redumps "Quake (USA) (Rerelease) (19980921)", it is v1.08. Same issue. A very weird bug and no regression from our POV as it happens in vanilla too.

**Comment by Burrito78** [comment]
Its a Apple silicon or Ventura bug affecting all DOSBox versions.

**Comment by Burrito78** [comment]
This is it what happens when I delete config.cfg (Quakes internal config file) and try to move the slider to the right for the first time:

![Bildschirmaufnahme 2023-04-14 um 12 40 04_2](https://user-images.githubusercontent.com/61995128/232025318-f06bba6f-c33e-40fb-becb-3e8dcb2a5ade.gif)

**Comment by Burrito78** [comment]
Setting the value manually in the cfg to 110 and 120 is working fine, menu is reflecting the change correctly. 
But once you touch the slider again its back to value 99.00000 at max again.

**Comment by GranMinigun** [comment]
FPU weirdness? Can you please try with `core = normal`?

**Comment by Burrito78** [comment]
> FPU weirdness? Can you please try with `core = normal`?

Yes, same result.

**Comment by Burrito78** [comment]
I tested all the output modes, no difference. Tested texture/software too.
Also tested machine types vgaonly, et_3000 and et_4000. All the same.

Doom doesn't have this issue.

**Comment by Burrito78** [comment]
If possible, would be nice to have fixed for 0.81 @kcgen!

**Comment by Grounded0** [comment]
Works fine with macOS 12.6.5/x86-64. Probably a bug in ARM64 binary. Will be a tough to fix so probably will not make it into 0.81.0.

**Comment by Grounded0** [comment]
If anyone can test this under Linux/ARM64 that would be very helpful in narrowing it down.

**Comment by Burrito78** [comment]
Just confirmed and yes, the screen size parameter can be changed normally through the in-game menu when running x86-64 on Apple M2 using Rosetta.

**Comment by Grounded0** [comment]
Okay so apparently another macOS/ARM64 bug then.

Pinging @kklobe.

This should be tested on a PowerPC machine too so pinging @classilla.

**Comment by classilla** [comment]
Also occurs on `ppc64le` with `core=auto` or `core=normal`.

**Comment by kcgen** [comment]
I remember finding the Quake code (it's shared and open source) for the menu and seeing where that size-step is calculated from the menu slider.

It's unfortunately very sloppy floating point code that casts the result to an integer on the razor's edge of a whole number. 

I don't have it in front of me, but it's something like this:

`screen_size = (int)(screen_size_step / 10.0);`

And that `(screen_size_step / 10.0)` floating-point division, in DOSBox, is handled by the host CPU; ie ARM64, x86-64, etc..

The result might be a hair above or below the whole number. For example,

`(80 / 10.0)` might be `7.9999999999999921` or `8.0000000000000053`.

And when it's cast to an integer from a floating point value, it becomes 7 or 8. 

On ARM64 (and now confirmed on ppc64le), the result is always on the smaller side and on x86 (32-bit and 64-bit) it's on the large side.

Unfortunately to fix this, we need to avoid doing the emulated 80x86's CPU's floating point instructions on host CPU (natively) and instead emulate the original FPU's 80-bits of precision using something like `libsoftfloat`, similar to how 86box does it:

https://github.com/86Box/86Box/pull/3285/files

It would come with a large performance hit (remember how FPU-intensive Quake is?).  So as soon as we'd fix this, ARM64 users would say "I have a full window! But frame rates have tanked in-game" :-)

So we'd want this feature to be not-only configurable, but likely switchable at run-time. Well.. until the day when host CPUs are so fast that soft-FPU can be default-enabled.

**Comment by Grounded0** [comment]
Connected issues and PRs:

- #2900

**Comment by runlevel5** [comment]
I can confirm this issue also impact `linux-ppc64le` with both `normal` and `auto` core

**Comment by GranMinigun** [comment]
Is it possible to define what kind of rounding should be used? `std::fesetround`?

**Comment by classilla** [comment]
Power ISA does have a 128-bit long double. I might see what I can do with that (mostly because I want Carmageddon to work right and it also depends on 80-bit floats), though this wouldn't help ARM64, I don't think.

**Comment by johnnovak** [comment]
At the end of the day, very few pre-Quake DOS games use the FPU. So largely a non-issue. Going the soft FPU route would be a massive overkill, IMO; it's actually easier to patch tha games for DOSBox 🤷🏻

**Comment by kcgen** [comment]
> Is it possible to define what kind of rounding should be used? `std::fesetround`?

You're hunch was right, @GranMinigun! Forcing the DOS FPU to cast-torward-integers _does_ let that menu screensize crank up to full (with the expected window size result).  

The downsize with such a universal bludgeon is (many) other float-to-int casts don't work as expected; and that symptom is seen even in other menu items which get stuck or limited in their range (in this video, I try to key them left and right, but they're stuck.. the brightness does appear to "flicker" slightly):

https://github.com/dosbox-staging/dosbox-staging/assets/1557255/d12a1267-2f6f-452c-b080-2c26a38ec768

I suppose a work-around is to use the in-game tilde menu to manually enter the `viewsize <value>`, where values are 30, through 120 in increments of 10:


https://github.com/dosbox-staging/dosbox-staging/assets/1557255/98fc97c2-e9d1-47b5-8306-a89ca574581c

**Comment by kcgen** [comment]
@GranMinigun , your hunch was right: forcing the core FPU to cast toward whole integers does let the Quake menu size slider crank up to maximum.

The downsize with this universal bludgeon is that all other DOS-side float-to-int casts are similarly affected, which is seen in the other menu items that have new limited range (in the video, I'm actively trying to adjust them but they don't budge):

https://github.com/dosbox-staging/dosbox-staging/assets/1557255/71bcb58e-c995-4f94-81e8-d4a644964c1f

The good news is that most DOS FPU games and software don't rely on those remaining handful of bits of accuracy going from 64-bit double precision up to 80-bits of precision. 

Heck.. our circa-2023 modern world of C++, Rust, and multi-GB Electron apps runs on 64-bit float FPUs.. so I guess 80-bits of FPU was deemed overkill after all.

**Comment by kcgen** [comment]
@Burrito78 , as a tiny **_consolation_**, the `viewsize` can be manually set:


https://github.com/dosbox-staging/dosbox-staging/assets/1557255/cc7025cf-036f-4888-b910-a219f420d6c7

Better than editing config files, I suppose.

**Comment by Torinde** [comment]
Would be great if @classilla can add 80-bit support via the 128-bit of POWER9 (IBM z also supports 128-bit floating point if you want to add that to the [Fedora build](https://github.com/dosbox-staging/dosbox-staging/actions/runs/6327236977/job/17182626976)). Maybe in the future Intel will add AVX-FP128 and ARM as well, while RISC-V already has it defined as extension "Q".

On the other hand - Softfloat (or another) emulation of 80-bit precision and of anything else using x87 registers (x87, **MMX, 3DNow!**) would be needed as well for:
- x86-64 MSVC builds
- all non-x86 CPUs
- when x86-64 CPUs drop the x87 stack (the [x87, MMX, and 3DNow! instruction sets are already deprecated in 64-bit modes](https://learn.microsoft.com/en-us/windows/win32/dxtecharts/sixty-four-bit-programming-for-game-developers) on Windows; there is the example of the planned [x86-S](https://en.wikipedia.org/wiki/X86-64#x86-S) dropping 16-bit modes)

Maybe not a priority due to current hosts still not being fast enough for that, but eventually it has to be added?

**Comment by Grounded0** [comment]
With this kind of performance available on Apple silicon there should be at least configurable option to enable quadruple-precision (128-bit) on those systems that can handle it without issues:

<img width="916" alt="283057823-dee3543c-e20c-4f99-b2da-f2311dcbe22a" src="https://github.com/dosbox-staging/dosbox-staging/assets/48192273/d3e7d521-a646-4e19-81fd-d3cef750787e">

**Comment by Grounded0** [comment]
This MAY or MAY NOT be an FPU extended precision issue. The only way to find out is to do a CPU instructions level analysis of this.
