### ISSUE TITLE
So can I use "machine cga" while Dosbox-Staging is running?

### ISSUE THREAD

**Issue by JKjakay** [dosbox-staging/dosbox-staging#2405]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Different version than latest?

I´m on 0.80 (from Fedora 37 repository, which has not yet updated to 80.1)

### What Operating System are you using?

Linux x86_64

### Whats your question and how can we help?

The Release Notes of Dosbox-Staging 80 and higher say that "many more settings can now be changed on the fly", among them screen, soundcard, etc. It gives an example of changing the Soundblaster type from None to SB16, etc.

I would like to do that with machine type. Specifically, I usually use a "machine svga_s3" config, but would like to switch on-the-fly to cga, hercules, etc. (for games from the early 80ies, to try out how they look). Now, I can enter "machine cga" and Dosbox-Staging accepts this, and will even report "machine cga" afterwards. But it does not really change to CGA, it is still using SVGA. What am I doing wrong? I couldn´t find anything about this.

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by GranMinigun** [comment]
In short, no, `machine` setting cannot be changed at run-time.
