### ISSUE TITLE
Set up a Project security policy to improve community standards rating

### ISSUE THREAD

**Issue by Burrito78** [dosbox-staging/dosbox-staging#2407]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### What Operating System are you using?

None

### Is your feature request related to a problem? Please describe.

[Security policy](https://github.com/dosbox-staging/dosbox-staging/community)

I think that's really low hanging fruit and should be very quickly be done with.

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by johnnovak** [comment]
Not necessarily against it, but these are the first three questions that popped in my head straight away:

- Is this something applicable to our project? I can see how such a security policy would be important for a library (e.g. a JSON parser you use in web applications), but for an emulator like ours, I'm unsure. What would the attack vectors be?

- What do we gain by doing this? Do we lose anything by not doing it if it feels forced for us?

- Are we just ticking boxes? I don't think we should just do something because GitHub lists it in their generic project template.

**Comment by johnnovak** [comment]
Having said all that, if it's just a matter of pasting some generic `.md` file there to increase the rating by 5% or something, then why not 😄

**Comment by kcgen** [comment]
With us handing out executables, users have to trust that we're not pulling in a trojaned dependencies or inserting backdoors into the builds.

We want to avoid the need for this trust all together, so all our binaries are built and shared directly from github's CI systems, and not by hand by team members. 

The source and CI workflow steps are auditible and public. They're technically reproducible using the exact same host, build tool versions, and dependency versions. 

(And a final CI step!) The builds are only cleared for export once they pass virus scanning with the latest up-to-date scanner database.

We've provided a local security.txt file that adheres to https://securitytxt.org/ (which is agnostic of GitHub and is generic for any web hosted tree). It tells people who to contact if they have a security issue, but no reports have come in yet.

I've added a basically security .md.. It's made to be timeless so we don't have to update it every release. Hopefully it's good enough.

**Comment by johnnovak** [comment]
Sound like a good approach @kcgen. I was under the impression this security policy is more about outlining how we deal with security related fixes, which are mostly applicable to libraries, frameworks, etc. But yeah, now we've ticket that box too 😄

**Comment by Torinde** [comment]
Then what about PR template - the last checkbox remaining to tick:
![image](https://user-images.githubusercontent.com/97228894/232280917-29bf5e98-5e19-475b-aaf8-075c20c7a3d3.png)
