### ISSUE TITLE
Quake rerelease installer can't find some files to copy from the CD

### ISSUE THREAD

**Issue by Burrito78** [dosbox-staging/dosbox-staging#2408]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Different version than latest?

0.80.1 and latest DEV

### What Operating System are you using?

Mac OS

### If Other OS, please describe

Ventura 13.3.1

### Relevant hardware info

macMini M2

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

During installation of the Quake rerelease (v1.08) the installer script can't find some files.
The version I tested is Redumps "Quake (USA) (Rerelease) (19980921)"
http://redump.org/disc/29723/

Happens in 0.80.1 and latest DEV version.

![Bildschirmfoto 2023-04-14 um 13 22 12](https://user-images.githubusercontent.com/61995128/232031358-576b9b43-97d8-43fc-bd13-0185c99d3e89.png)

### Steps to reproduce the behaviour.

Explain how to reproduce
1.  Try to Install the rerelease version of Quake with the new installer (see above) in Staging.
2. Observe multiple "file not found" errors during the installation process.
3. 

### Your configuration

```ini
default
```

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by Burrito78** [comment]
Issue happens in all versions, tested 0.77.1 and newer and also vanilla.

**Comment by LowLevelMahn** [comment]
can you go in more detail - do you mount a image (parameter?), or did you copied the files from the image to the hard disk?

**Comment by Burrito78** [comment]
Yes, of course. I mounted the image using

imgmount d quakecd.cue -t cd-rom

Just checked all the different US rerelease versions and they are missing the files on the CD that give these copy errors. So I guess (but i can't really believe it) that this isn't a DOSBox issue.

Maybe the imgmount doesn't work correctly and won't show these DOC files??

If no one has an idea, we can close this I guess.

**Comment by ThomasEricB** [comment]
As I'm also having a similar issue on Windows, where a .img file is not read by imgmount, I would recommend not to close this yet.

**Comment by rderooy** [comment]
Could it be an issue with lack of support for ISO9660 extensions such as Joliet?
