### ISSUE TITLE
Mime type for dosbox.conf file

### ISSUE THREAD

**Issue by evertvorster** [dosbox-staging/dosbox-staging#2409]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### What Operating System are you using?

Linux x86_64

### If Other OS, please describe

Arch Linux

### Is your feature request related to a problem? Please describe.

Nope, no problems. 
I just want to be able to click on a dosbox.conf file in my file manager, and have dosbox launch in that directory optionally with the configuration file as an option. Something similar to clicking on a text file and the text editor opening up with the text file loaded.

### Describe the solution you'd like

Adding a mimetype of "dosbox.conf"  in the .desktop file for this application would make the file manager launch dosbox in the proper directory and dosbox would read it's configuration file and be on it's merry way. 

I have a LOT of MS-DOS games, and they all seem to need different configurations in dosbox to run properly. So, I have taken to making a separate configuration file for each game, and then if I want to run said game, I just execute dosbox in it's directory. Now, it's a little bit of a pain opening a terminal just so I can type dosbox and hit enter. It would be so much easier to just click on the configuration file and have dosbox launch.

### Describe alternatives you've considered

I have added in dosbox to the Application associations in KDE, but once the mime database is updated my custom associations goes away. I think it's a bit of a bug in the way that KDE implements custom application bindings for certain files. 

However, it's so useful that maybe it should be the default behavior, and so I humbly request that the dosbox.conf be added as a Mime type in the .desktop file for this application.

### Add any other context or screenshots about the feature request here.

System information:
```
Operating System: Arch Linux 
KDE Plasma Version: 5.27.4
KDE Frameworks Version: 5.105.0
Qt Version: 5.15.9
Kernel Version: 6.2.10-AMD-znver2 (64-bit)
Graphics Platform: X11
Processors: 8 × AMD Ryzen 7 4700U with Radeon Graphics
Memory: 37.0 GiB of RAM
Graphics Processor: AMD Radeon Graphics
Manufacturer: LENOVO
Product Name: 20T8001JUS
System Version: ThinkPad E15 Gen 2
```

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by dreamer** [comment]
Personally I used to solve this issue by making my .conf files executable and adding a hashbang:

     #!/usr/bin/dosbox --conf

But we changed the behaviour around .conf files to make them more user-friendly and it conflicted with hashbangs a little bit.

My solution works only with dosbox installed via a native package manager (e.g. rpm or deb) - can be improved with using `env` but it still has issues with flatpaks and such.

I feel like executable .conf file should be solution for Linux users, but we need to improve the behaviour of DOSBox to make it a viable solution. Registering custom mime type (`application/x-dosbox`) should be way easier to discover.

**Comment by evertvorster** [comment]
Thanks for looking into this!

It's a nifty little feature to be able to assign a mimetype. 
If the .desktop file specifies the mimetype, then standards-compliant desktops should be able to import that with no more user interaction.

**Comment by johnnovak** [comment]
@shermp @weirddan455 @FeralChild64 Linux people, shall we implement this or shall we kill it? Anyone interested?

**Comment by weirddan455** [comment]
I quite like my .conf file to open in a text editor when I double-click it so that I can edit it.  It's easy enough to change the default program but this behavior might confuse more people than it helps.

I wouldn't be opposed if someone wanted to do this but I think most Linux users can figure out how to set this MIME type themselves, open from a terminal, or create per-game shortcuts they can double-click on.

**Comment by johnnovak** [comment]
> but I think most Linux users can figure out how to set this MIME type themselves, open from a terminal, or create per-game shortcuts they can double-click on.

I agree with that. Installing such a custom MIME type by default seems to go against typical Linux usage patterns. It should be up to the individual to customise their desktop setup like this.

> I have added in dosbox to the Application associations in KDE, but once the mime database is updated my custom associations goes away. I think it's a bit of a bug in the way that KDE implements custom application bindings for certain files.

@evertvorster If that's still the case, that's something you might wanna take up with the KDE devs, thanks.

**Comment by Grounded0** [comment]
We definitely do not want to start messing with Linux users preferences over the way they set up things.

**Comment by johnnovak** [comment]
> We definitely do not want to start messing with Linux users preferences over the way they set up things.

Word 😎

**Comment by interloper98** [comment]
@evertvorster - I recently just added some Debian stuff to `contrib/linux/`. It's entirely optional.

I suspect if you wanted to contribute a KDE desktop MIME type, it could likely be put in `contrib/linux/kde/...` with some notes for interested users.
