### ISSUE TITLE
Tomb Raider 1 crash

### ISSUE THREAD

**Issue by nemo93** [dosbox-staging/dosbox-staging#241]
Hi. First I'd like to thanks all people working on this Dosbox version. Really impressive as it allows me to play my old DOS games almost flawlessly on a simple non-overclocked Pi3B+! As this version relies on SDL2 I have no more tearing in games like Raptor or Rayman which is fantastic. Thank you all for that.

I'm unsure where I should report the below bug hence I do that hereafter. Please let me know if I should report to another place (or in a different manner). I assume one game issue => one ticket.

* Description
Game crashes straight before the 1st stage.

* To Reproduce
Launch Tomb Raider 1 (TOMB.EXE). I'm using a bin/cue which is mounted prior launching the game. Eidos/Core logos anims are fine so does the first intro. Main menu with the fantastic music still ok. Start a game, another intro will play and... then Dosbox just crash. I just can't get to the game. 
NOTE: I realized that if I let the main menu without doing anything you go to Demo mode which is working, I can see the game in that mode.
NOTE2: with the current Dosbox SVN (default in Retropie) the game won't even go further the Eidos logo.

* Environment:
Raspbian Jessie (the one shipped with Retropie+all packages up-to-date)
Retropie Version 4.5.18 (latest)
Pi3B+
SDL2 2.0.10 (no dispmanx)
I've compiled Dosbox-staging this morning after I saw the commits for SDL texture.

* Dosbox config
```
fullscreen       = true
vsync            = false
fullresolution   = desktop
windowresolution = desktop
output           = texture
texture_renderer = auto
capture_mouse    = nomouse
sensitivity      = 100
waitonerror      = true
priority         = higher,normal
mapperfile       = mapper-SVN.map

machine  = svga_s3
captures = capture
memsize  = 32

frameskip = 0
aspect    = true
scaler = none

core = dynamic
cputype   = auto
cycles = max
cycleup   = 10
cycledown = 20
[...] // everything else as default
```

**Comment by dreamer** [comment]
> I'm unsure where I should report the below bug hence I do that hereafter. Please let me know if I should report to another place (or in a different manner). I assume one game issue => one ticket.

This is fine :) So far we had no reason to bundle multiple reports for a single game in a single report.

> Game crashes straight before the 1st stage.

Does it crash when going through tutorial "Lara's Home"? Does crash happen before or after the video cutscene?

> I've compiled Dosbox-staging this morning after I saw the commits for SDL texture.

Pasting the output of `git describe` will help us determine which commit exactly are you testing.

I am regularly testing with Tomb Raider I on Linux x86-64 (software renderer, as dosbox-staging does not support Glide yet), so I'm sure we'll figure it out. I will paste my .conf file and .cue file in a few minutes.

**Comment by nemo93** [comment]
Thank you @dreamer. 

* game does crash also before launching the tutorial. Crash does happen after the video cutscene (which plays ok).

* $ git describe
v0.75.0-pre-706-gdbc77a6f

* cue
```
FILE "tbraider.bin" BINARY
   TRACK 01 MODE1/2352
      INDEX 01 00:00:00
   TRACK 02 AUDIO
      INDEX 01 19:26:53
   TRACK 03 AUDIO
      INDEX 01 22:43:23
   TRACK 04 AUDIO
      INDEX 01 24:43:36
   TRACK 05 AUDIO
      INDEX 01 27:46:45
   TRACK 06 AUDIO
      INDEX 01 30:55:28
   TRACK 07 AUDIO
      INDEX 01 34:03:00
   TRACK 08 AUDIO
      INDEX 01 35:06:40
   TRACK 09 AUDIO
      INDEX 01 36:04:05
   TRACK 10 AUDIO
      INDEX 01 36:19:35
```

**Comment by dreamer** [comment]
I am using Steam copy of the game (which is the same as GOG, I believe), with .conf generated by [Boxtron](https://github.com/dreamer/boxtron) (that's why boxtron references appear):

```
[sdl]
fullscreen=true
fullresolution=desktop
output=opengl
waitonerror=true

[render]
aspect=true
scaler=none
glshader=sharp

[cpu]
core=auto
cputype=auto
cycles=max 95%

[mixer]
nosound=false
swapstereo=false
rate=44100
blocksize=1024
prebuffer=20

[sblaster]
sbtype=sb16
sbbase=220
irq=7
dma=1
hdma=5

[dos]
xms=true
ems=true
umb=true

[autoexec]
mount C "."
imgmount D "boxtron.cue" -t iso -fs iso
C:
cd TOMBRAID
TOMBNO~1.EXE
exit
```
Note: `TOMBNO~1.EXE` is file `TOMBno3Dfx.EXE` distributed with my copy of the game; md5sum: `e8125fc28230822a032f545c5003dd67`.


boxtron.cue (original .cue retouched to fix bugs via Boxtron):
```
FILE "GAME.GOG" BINARY
  TRACK 01 MODE1/2352
    INDEX 01 00:00:00
FILE "02.mp3" MP3
  TRACK 02 AUDIO
  INDEX 01 00:00:00
FILE "03.mp3" MP3
  TRACK 03 AUDIO
    INDEX 01 00:00:00
FILE "04.mp3" MP3
  TRACK 04 AUDIO
    INDEX 01 00:00:00
FILE "05.mp3" MP3
  TRACK 05 AUDIO
    INDEX 01 00:00:00
FILE "06.mp3" MP3
  TRACK 06 AUDIO
    INDEX 01 00:00:00
FILE "07.mp3" MP3
  TRACK 07 AUDIO
    INDEX 01 00:00:00
FILE "08.mp3" MP3
  TRACK 08 AUDIO
    INDEX 01 00:00:00
FILE "09.mp3" MP3
  TRACK 09 AUDIO
    INDEX 01 00:00:00
FILE "10.mp3" MP3
  TRACK 10 AUDIO
    INDEX 01 00:00:00
```
Can you paste md5sum of your file `tbraider.bin`?

**Comment by nemo93** [comment]
```
$ md5sum RetroPie/roms/pc/games/tbraider/tbraider.bin
58a4d58db6a9651f53b2c0d11a6fe97e
```
It's from my (french) copy. Also I do confirm the same `[dos]` settings:
```
xms            = true
ems            = true
umb            = true
keyboardlayout = auto
```

**Comment by krcroft** [comment]
Runs stable but slow; this games needs roughly 170,000 for super smooth play.  On my Pi3 30,000 cycles produces about 3 frames/sec.  

I'm using DOS32/a inside the `tomb.exe`, CDROM mounted (with Opus audio tracks), and launching the game with `tomb -audio 2`.  Config is my default for Pi (texturepp, fullscreen), plus the following for Tomb Raider:

```
[cpu]
core=dynamic
cycles=max 95% limit 30000
cputype=auto

[dosbox]
vesa_nolfb
machine=vesa_nolfb
memsize=24

[midi]
mpu401=intelligent
mididevice=alsa
midiconfig=128:0

[sblaster]
sbtype=sb16
sbbase=220
irq=7
dma=1
hdma=5
sbmixer=true
oplmode=auto
oplemu=fast

[gus]
gus=false

[dos]
xms=true
ems=false
umb=true

[speaker]
pcspeaker=false
tandy=off
disney=false
```

**Comment by dreamer** [comment]
@nemo93 ok; I see you have crashes in other games as well - let's focus on this issue first.

Since we can't reproduce so far, can you generate a backtrace for us, so we have a better idea what might be the root cause?

Steps:

1. Install `gdb` via `apt`
2. Compile dosbox-staging with debug symbols, without optimisations:

```
$ git clean -fdx .  # this will completely clean up your local git repo
$ ./autogen.sh
$ ./configure CXXFLAGS=-g CFLAGS=-g
$ make -j $(nproc)
```
3. Load dosbox-staging inside gdb:
```
$ gdb <path>/src/dosbox
```
4. In gdb shell type command `run` with dosbox arguments you use to start the game:
```
(gdb) run -conf your-config-file.conf
```
5. Follow the steps to reproduce the crash; when it happens, generate a backtrace:
```
(gdb) backtrace
```
And paste it here :) (gdb session can be closed using `q` command)

It should give us a better clue where to look for the problem - if it won't be enough, then we'll follow up with a core file (although I am not sure if I can load core from a different architecture - we'll see).

**Comment by nemo93** [comment]
```
Starting program: /home/pi/dosbox-staging -conf RetroPie/roms/pc/tbraider.conf
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/arm-linux-gnueabihf/libthread_db.so.1".
[New Thread 0x765c0440 (LWP 26937)]
[New Thread 0x75bff440 (LWP 26938)]
[New Thread 0x753fe440 (LWP 26939)]
[New Thread 0x74bfd440 (LWP 26940)]
[New Thread 0x743fc440 (LWP 26941)]
[New Thread 0x7099b440 (LWP 26942)]
[Thread 0x7099b440 (LWP 26942) exited]
[Thread 0x743fc440 (LWP 26941) exited]
[Thread 0x74bfd440 (LWP 26940) exited]
[Thread 0x753fe440 (LWP 26939) exited]
[Thread 0x75bff440 (LWP 26938) exited]
[Thread 0x765c0440 (LWP 26937) exited]
[Inferior 1 (process 26936) exited with code 01]
No stack.
```
The `No stack.` is the result of the `backtrace` command.

**Comment by krcroft** [comment]
That's great news @nemo93 ! Thanks for sharing very detailed feedback as well; others will surely benefit from it. 

(If you will entertain a side topic: Are there quality or in-game settings you're using to make it mostly playable on your 3B?  Normally I would give Tomb Raider 170,000 cycles, which is more 4x greater than what the 3 and 3B can handle)

**Comment by nemo93** [comment]
I'm using a default-clocked PI3B+ (no overclock). No specific settings in-game. The only difference with your config is `machine  = svga_s3`. The game is definitely playable even if no 30fps I'd say it's around 15-20fps. Enough to play the game.

One last thing: I must run the game with `TOMB.EXE` only. With your `-audio 2` parameter game keeps on crashing.

**Comment by krcroft** [comment]
Thanks @nemo93 ; I'll give `svga_s3` a try!

**Comment by nemo93** [comment]
Reopening it as game crashes another time. In fact the crash looks to be random. For sure switching to DOS32/A improves thing as I can play the game sometimes but won't prevent 100% the game from crashing. 

I'm using the same conf and if you launch the game several times in a row there's a chance to enter 1st level once at least. Apparently the only "evidence" the game will run ok is whenever the FMV are playing smooth. Anytime one or more FMV start to stutter I'm almost certain the game won't go through 1st level.

Note: I double-check and the game uses the "medium" level of details setting which is the one I use. Could explain my 15-20fps on a Pi3B+.

**Comment by dreamer** [comment]
This is really weird, that no stack trace was generated… (did you add `-g` flag during configure step?). I think we'll need to make some change to make it easier for users to generate/upload stacktraces for cases like this one. I must've missed something…

**Comment by nemo93** [comment]
I agree. The exact command I've passed:
`$ ./configure CXXFLAGS=-g CFLAGS=-g --disable-screenshots --disable-network`

**Comment by dreamer** [comment]
No, `--enable-debug` turns on internal dosbox debugger for emulated DOS programs, I don't think it will be helpful in this case.

**Comment by krcroft** [comment]
In the log messages above:
```
[Thread 0x74bfd440 (LWP 29033) exited]
[Thread 0x753fe440 (LWP 29032) exited]
[Thread 0x75bff440 (LWP 29031) exited]
[Thread 0x765c0440 (LWP 29030) exited]
[Inferior 1 (process 29028) exited with code 01]
```

it appears DOSBox is quitting on its own accord (hastily and surely mid-game like you're reporting @nemo93 ), but that would explain why we're not seeing a backtrace from `gdb> bt`  .   We'd need it to segfault or bus-error to get a backtrace (or we could add a breakpoint if we know what part of the code is bailing out).

**Comment by dreamer** [comment]
@nemo93 run `ulimit -a` and paste output, please - in particular I am interested if following line will be printed: `core file size          (blocks, -c) unlimited`.

@krcroft yeah, that might be some C++ exception, that "neatly" cleans up the stack and sets return code 1 :/ Or maybe `E_Exit` misbehaves and does not leave anything on stderr before termination?

**Comment by nemo93** [comment]
Herer you go - I got "0" instead of "unlimited":
```
$ ulimit -a
core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 5909
max locked memory       (kbytes, -l) unlimited
max memory size         (kbytes, -m) unlimited
open files                      (-n) 1024
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 95
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) 5909
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited
```

**Comment by dreamer** [comment]
OK, let's try two different things:

1. I prepared a commit to test C++ exception hypothesis - it won't say us much, but if it's a C++ exception, then we'll at least know something ;) test branch `po/tr1-crash-investigation-1` (run in terminal, without gdb). If the "crash" was result of exception, then last lines on stderr should look something like this:
```
terminate called after throwing an instance of <type>
  what():  <description>
Aborted (core dumped)
```

2. If (1) won't give us any info, let's try to temporarily remove 0 limit on coredumps - not sure if steps for your OS will be exactly the same, for me they are:
```
$ sudo su - # (switches to root user, simple sudo might no be enough!)
# ulimit -c unlimited
# ulimit -a # (to confirm that 'core file size' line now says 'unlimited')
# su - <your-username> # (the same bash session!)
$ ulimit -a # (confirm that option got preserved after you switched to user)
```
(This way you won't change your OS permamently, after next restart everything will be back to your normal state) After that, let's try to generate stacktrace using gdb again.

*I seriously need to think about how to make these steps semi automatic, so our snapshots crashing will generate enough information without going through such advanced debugging steps.*

**Comment by nemo93** [comment]
Hi @dreamer @kcgen! Ok I followed @dreamer's guide above in order using the specific branch. Unfortunately nothing different, no backtrace no core dump. As the log generated was nothing I decided to take a picture of the exact output as some lines didn't show in the log (the ones related to EGL and the failed to add service).

![20200329_130636](https://user-images.githubusercontent.com/8100500/77848061-45fca200-71c2-11ea-92a0-71a78eb2935e.jpg)

**Comment by grapeli** [comment]
`[Inferior 1 (process 15246) exited with code 01]`

Raspberry Pi SDL2 uses hardware accelerated OpenGL ES2 rendering for the frame buffer.
Probably a regular user has no direct access to the frame buffer.
https://forum.qt.io/topic/112594/linuxfb-plugin-platform-cannot-use-gdb-to-debug-qt-programs-normally

**Comment by nemo93** [comment]
Just as a note if I manage to press 'ESC' quick enough to pass the stage intro video I could access to the game. If I let the video play it will start to stutter to the point it becomes a slide show and for sure game will crash. Really seems something is weird with video playback in some games. Like the video are somehow "exhausting" the Pi resources and lead it to crash at some point.

**Comment by nemo93** [comment]
On a Pi4 with `output = texturenb` or `output = texturepp` TombRaider will crash right after the Eidos logo as with Dosbox "SVN". With `output = texture` it will crash but only after the 2 FMV sequences right before the main menu screen. The FMV are playing almost frame by frame.

**Comment by nemo93** [comment]
Ok the game requires a **_fixed amount of cycles_** to run without crashing. By setting the below on a pi4 game is now running each time properly, fmv are smooth and perf-wise it's playable (with medium details). A bit disappointing as it looks like the same perf as with pi3 but at least no more crashing and it's good to understand why!

```
[cpu]
cycles = fixed 35000
```

Thanks for the help and assistance @dreamer @kcgen !
