### ISSUE TITLE
output = surface doesn't scale up 320x200 on macOS

### ISSUE THREAD

**Issue by Burrito78** [dosbox-staging/dosbox-staging#2414]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Different version than latest?

DEV

### What Operating System are you using?

Mac OS

### Relevant hardware info

Ventura

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Using output = surface the 320x200 game output isn't scaled to fit the window, instead is drawn top left in the window corner.

![Bildschirmfoto 2023-04-17 um 09 44 36](https://user-images.githubusercontent.com/61995128/232420265-0d7a3a4f-b394-467a-b9e2-941797cc169e.png)
![Bildschirmfoto 2023-04-17 um 09 45 37](https://user-images.githubusercontent.com/61995128/232420340-04f06f33-fa39-44b4-8db1-b2a410835ba1.png)

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Start latest DEV version with "output = surface" set in config file.
2. Start a game that uses 320x200.
3.

### Your configuration

```ini
default, except "output = surface".
```

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by ThomasEricB** [comment]
@Burrito78 Could you kindly grab 0.80 from the stable releases section to see if it was recent regression?

**Comment by Burrito78** [comment]
To my suprise, happens with v0.80.1 too!

**Comment by Burrito78** [comment]
Logfile is lying. :)

![Bildschirmfoto 2023-04-17 um 11 32 55](https://user-images.githubusercontent.com/61995128/232445307-b5f9efdf-25fb-4851-a4da-31f16cca3eec.png)

**Comment by Burrito78** [comment]
0.79.1 and 0.78.1 are the same. 0.77.1 looks different (see below) but that's also broken I guess. It's also 320x200 post stamp-size when going fullscreen.

![Bildschirmfoto 2023-04-17 um 14 43 45](https://user-images.githubusercontent.com/61995128/232487951-0bf05341-a6a2-4cf9-a84d-d8e81d4e36c4.png)

**Comment by ThomasEricB** [comment]
@kcgen Thank you for clarifying!

**Comment by kcgen** [comment]
@GranMinigun, with you progressing sdlmain, how would you prefer we handle this in the near-term? (I'm not saying you need to address this in the code).

Basically askinf if you think this is something the team should collectively address (or not / defer).

**Comment by GranMinigun** [comment]
`surface` isn't handled by HiDPI scaling. If one for whatever reason needs software output, then `texture` has it.

I've wiped `surface` in my branch, so it's only a matter of bringing it to digestible state (and you know my pacing).

**Comment by johnnovak** [comment]
Yes, I too think surface should be completely nuked. SDL can default to software rendering with the `texture` backend if hardware acceleration is not available.

**Comment by kcgen** [comment]
The fewer branches to test, the better!
