### ISSUE TITLE
PR template - last missing item in the Community checklist

### ISSUE THREAD

**Issue by Torinde** [dosbox-staging/dosbox-staging#2416]
Then what about PR template - the last checkbox remaining to tick:
![image](https://user-images.githubusercontent.com/97228894/232280917-29bf5e98-5e19-475b-aaf8-075c20c7a3d3.png)

An example is https://github.com/joncampbell123/dosbox-x/blob/master/.github/PULL_REQUEST_TEMPLATE.md

_Originally posted by @Torinde in https://github.com/dosbox-staging/dosbox-staging/issues/2407#issuecomment-1510146672_

**Comment by Burrito78** [comment]
Nope.
