### ISSUE TITLE
feature request: please provide an AppImage

### ISSUE THREAD

**Issue by legluondunet** [dosbox-staging/dosbox-staging#2437]
Hello,
could it be possible to provide an AppImage?
For stable release but for nightly too?

Thank you for the interest you gave to my request.

**Comment by dreamer** [comment]
Yup, it would be pretty neat; last time I tried to do that AppImage was not supporting creation of packages on Fedora (it worked only on Ubuntu/Debian). I will give it another try.

**Comment by dreamer** [comment]
Unfortunately, AppImage `appimage-builder` still does not work on Fedora (somehow it cannot run the application, thus leaving me with incomplete recipe as dependencies cannot be generated), and we cannot generate recipe on CI.

Someone else needs to work on this, sorry. If someone will provide us with a working recipe then we'll be happy to use that for packaging our builds in AppImage.

**Comment by johnnovak** [comment]
Can't we statically link everything minus libc, then ship as a tar.gz with resource files bundled? Unpack to ~/bin, job done.

But then I'm a big fan of static linking and wouldn't shed much of a tear if dynamic linking went completely out of fashion... 😄 
https://sta.li/faq/

Maybe DOSBox would need to be taught to try to find the resources dir from the exe start dir, and if it's there, start in "portable mode" (that's how I'm doing things in Gridmonger to detect a "portable via ZIP file" installation which is also very handy during development; no need to install anything).

**Comment by kcgen** [comment]
> But then I'm a big fan of static linking and wouldn't shed much of a tear if dynamic linking went completely out of fashion...

For maximum compatibility, the CI zip packages (and official releases) build almost everything using wraps and statically link to reduce dependencies to a minimum (and prevent those dependencies from "evolving out" from underneath the binary):

Release workflow sections:

```
.github/workflows/linux.yml: -Ddefault_library=static ...
.github/workflows/macos.yml: -Ddefault_library=static ...
/windows-msys2.yml:          -Ddefault_library=static ...
```

**Comment by kcgen** [comment]
Suggest opening this in the App Image communities tracker, and finding packagers there willing to create and maintain this. The project does not create 3rd party packages.
