### ISSUE TITLE
Hard crash on Windows when using QPEG with the latest dev build

### ISSUE THREAD

**Issue by johnnovak** [dosbox-staging/dosbox-staging#2439]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Different version than latest?

dosbox-staging-windows-msys2-x86_64-v0.81.0-alpha-674-g3b349

### What Operating System are you using?

Windows 10

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

With the latest dev build, QPEG consistently hard-crashes the DOSBox process when attempting to display an image.

I can reproduce it 100% of the time on Windows using the MSYS2 dev build. The issue does not happen on macOS with a self-built build off `main`; QPEG works flawlessly there.

v0.80.1 also works flawlessly on Windows. So this is a weird regression, most likely memory corruption that manifests more easily on my Windows box. I suspect it has something to do with the double-scanning VGA changes.

### Steps to reproduce the behaviour.

Explain how to reproduce

1. Use my attached repro pack
2. Start with `dosbox -noprimaryconf`
3. After QPEG started, press Enter on `GODS.BMP` to view it---bamm, crash! It crashes in spectacular ways, every time a bit differently, but the process always exits after a few seconds of hanging...

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by johnnovak** [comment]
Example:

![image](https://user-images.githubusercontent.com/698770/235273896-3069ada6-4f4a-48d6-aa46-e4cdcb423e8a.png)

**Comment by johnnovak** [comment]
Repro pack:
[bug.zip](https://github.com/dosbox-staging/dosbox-staging/files/11358010/bug.zip)

**Comment by dreamer** [comment]
I can reproduce the crash in local build on Linux, but annoyingly, only in a release build :disappointed: (debug builds work fine).

**Comment by dreamer** [comment]
Ah, I had few minutes anyway :) By bisecting I found that regression was introduced with this commit: 72ad31a370abb9edc29a99b0eab79a4454d68e1c

**Comment by johnnovak** [comment]
> Ah, I had few minutes anyway :) By bisecting I found that regression was introduced with this commit: [72ad31a](https://github.com/dosbox-staging/dosbox-staging/commit/72ad31a370abb9edc29a99b0eab79a4454d68e1c)

Nice, thanks to @kcgen's foresight of creating these small incremental commits for easy bisecting! Seem like that vector & dynamic allocation is needed, after all...

**Comment by kcgen** [comment]
Thanks for the bisect @dreamer !

> Seem like that vector & dynamic allocation is needed

Might go that route; but the good news is this is catching a wrong assumption about maximum line length (in pixels and/or bytes).
