### ISSUE TITLE
>NUL: produces a file creation error

### ISSUE THREAD

**Issue by Burrito78** [dosbox-staging/dosbox-staging#2440]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### What Operating System are you using?

Mac OS

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

`dir >NUL`

is working correctly. But

`dir >NUL:`

is giving a file creation error.

This was reported to me through Mastodon by a user who used old batch files in Staging that used the latter format.
These batches produce no error messages in both DOSBox 0.74 and DOSBox-X the user said.

### Steps to reproduce the behaviour.

Explain how to reproduce
1. 
2.
3.

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by kcgen** [comment]
Bisecting ...

**Comment by kcgen** [comment]
Job's finished. Bisected to: a0629955a1334ce1c3788c89c38f87917bda56b3
