### ISSUE TITLE
SHA256 is wrong for macOS Download

### ISSUE THREAD

**Issue by Burrito78** [dosbox-staging/dosbox-staging#2449]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### What Operating System are you using?

None

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

```
Website sha256 "46a256645255e8345981ea357f1416b8ce4bc60a2aba9a86b5122d5075aa7fa"
Real    sha256 "46a256645255e8345981ea357f1416b8ce4bc60a2aba9a86b5122d5075aa7fa9"
```

### Steps to reproduce the behaviour.

Explain how to reproduce
1. 
2.
3.

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by Burrito78** [comment]
https://github.com/dosbox-staging/dosbox-staging/issues/1901

**Comment by johnnovak** [comment]
Can you fix it? :)

**Comment by Burrito78** [comment]
Not yet but i bet you could. :)

**Comment by Burrito78** [comment]
Thanks @kcgen for fixing this!

Thanks to @johnnovak to remind me how easy it is to fail completely on something obviously trivial. 🥇 <- My medal for trying.

**Comment by johnnovak** [comment]
> Thanks @kcgen for fixing this!
> 
> Thanks to @johnnovak to remind me how easy it is to fail completely on something obviously trivial. 🥇 <- My medal for trying.

No problem, still qualifies for a participation award 🥈 😄 Thanks for spotting the problem in the first place, though.
