### ISSUE TITLE
Gauntlet locks up in `main` unless MPU+MIDI is enabled (but isn't a MIDI game)

### ISSUE THREAD

**Issue by kcgen** [dosbox-staging/dosbox-staging#2460]
Gauntlet's EGA 256x200 mode doesn't work in `main` but did in prior releases:

### `main`

![2023-05-06_12-36](https://user-images.githubusercontent.com/1557255/236643645-7a00c3c7-f0be-43f3-8785-efab83029d69.png)

### 0.80.1 release:

![2023-05-06_12-38](https://user-images.githubusercontent.com/1557255/236643593-1b621cd1-ae05-4388-9a20-c3cc83fe1b2c.png)

```ini
[sdl]
windowresolution = 1280x960
output = texture
presentation_mode = vfr
vsync = false
vsync_skip = 0

[dosbox]
machine=ega
memsize=1
automount = false
startup_verbosity = quiet

[cpu]
core = normal
cycles = 2000

[sblaster]
sbtype = none

[midi]
mididevice = none

[speaker]
pcspeaker = none

[joystick]
joysticktype = disabled

[ethernet]
ne2000 = false

[autoexec]
mount c .
c:
cd Gauntlet
GAUNTLET
```

Repro pack: [2460.zip](https://github.com/dosbox-staging/dosbox-staging/files/11413252/2460.zip)

Steps:
 1. Press `Enter` to get to the player selection menu
 2. Use left arrow and slight up arrow to hover over the **'One'** player, press `Enter`
 3. Press `Enter` again to select the warrior.
 4. The new 256x200 resolution is set and gameplay either starts or freezes

**Comment by kcgen** [comment]
There's a strange connection here to MIDI.

This bisects to 8f7d7ce49307d738639199fc9e7c7b20364bd446 (which is a MIDI-related commit), and in DOSBox SVN, commenting out the MPU and MIDI initialization produces the same result:

![2023-05-06_12-58](https://user-images.githubusercontent.com/1557255/236644600-203ba78b-a372-402c-b93c-c212797e37b5.png)

**Comment by johnnovak** [comment]
So what if you set `midi` and `mpu401` to `none`? Maybe log port 330h traffic as well?

**Comment by johnnovak** [comment]
I think it has something to do with my cleanup of reducing the MIDI event message buffer sizes to 3 from the arbitrary 8 bytes. I can run a sanitiser build later, but that's my hunch. The bulk of that commit is just renames otherwise.

**Comment by kcgen** [comment]
> what if you set midi AND mpu401 to none

Interesting!


``` ini
[midi]
mpu401 = none
mididevice = none
```

This repros the issue in all dosboxes (SVN / X / Staging 0.80.1 & `main`).

Giving it just the MPU401:

``` ini
[midi]
mpu401 = intelligent
mididevice = none
```

Gets the game working again in SVN / X / Staging 0.80.1, but not in `main`.

`main` needs an MPU and MIDI device (any will do):

``` ini
[midi]
mpu401 = intelligent
mididevice = mt32
```

![2023-05-06_14-59](https://user-images.githubusercontent.com/1557255/236648143-fd286e52-ad9e-4aec-8434-5e32533d78e6.png)

(The game itself is circa 1988 and doesn't use MIDI.. so this is definitely strange)

**Comment by johnnovak** [comment]
Well, it must screw around with the 330 port somehow. Maybe by mistake. I'll log call to port 330 and see.

**Comment by kcgen** [comment]
Hmm, is IRQ 2 PS/2 related? The game needs an EGA machine type, which predated PS/2.
