### ISSUE TITLE
RDP output, Multiplayer single screen games - to be played via separate computers

### ISSUE THREAD

**Issue by Torinde** [dosbox-staging/dosbox-staging#2462]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### What Operating System are you using?

Windows 10

### Is your feature request related to a problem? Please describe.

Multiplayer single screen games - to be played jointly on multiple DOSbox-X instances running on separate computers remotely (over LAN/internet) connected. One is running the game ("server") - sending audio/video to the others. The others are sending keyboard/mouse/joystick/microphone towards the "server". Of course the server can be used also by player1. 

Maybe leveraging VNC, Remote desktop, Teams, etc. and tying DOSbox-X as receiver of the remote keyboard/mouse/joystick/microphone.

RDP/VNC support is useful by itself as well - not only for multiplayer single screen games, e.g. instead of rendering on the local screen - output to a remote station (or smartphone). Private "DOSbox Cloud".

Same topic at: joncampbell123/dosbox-x/issues/3635

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by kcgen** [comment]
It's been done! - see: https://github.com/dosbox-staging/dosbox-staging/issues/673

**Comment by johnnovak** [comment]
> It's been done! - see: #673

Great, then we can close it.

**Comment by dreamer** [comment]
Nowadays the easiest way to achieve it is just to use Steam and invite your friend over using [Steam Remote Play](https://help.steampowered.com/en/faqs/view/0689-74B8-92AC-10F2). Works great and cross-platform - I played several rounds of Worms 1 this way with a friend some time ago.
