### ISSUE TITLE
Preserve mixer settings per device when changing 'mididevice' between fluidsynth/mt-32/...

### ISSUE THREAD

**Issue by Burrito78** [dosbox-staging/dosbox-staging#2468]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### What Operating System are you using?

Mac OS

### Is your feature request related to a problem? Please describe.

Currently if you have fluidsynth set as the active mididevice and adjusted the fluidsynth volume using the mixer and a 'config -set mididevice=fluidsynth' command restores the volume back to 100 because default values are loaded.

Also loading e.g. mt-32 resets volume settings of fluidsynth and mt-32.

The problem is that eXoDOS for example always does switch the mididevice before a game is started, therefore volume is always 100 currently.

### Describe the solution you'd like

'config -set mididevice=XXX' should remember last volume set per device.

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by johnnovak** [comment]
Thanks for raising this, @Burrito78. I'm aware of this issue but couldn't be bothered to fix it as it can get messy. But the eXoDOS use case turns this into a more pressing issue, agreed.

Could you please generalise the description that the whole mixer state (all channels) must be preserved when switching MIDI devices, including all mixer channel settings, so volume, crossfeed, chorus & reverb levels, and stereo reverse? From memory, all those settings are reset too.

Once we have a generic mechanism that enables us to save/restore the whole mixer state, we only need to identify other scenarios where the mixer params are reset, and simply just plug in the same mechanism to fix them.

Thanks!

**Comment by Burrito78** [comment]
Set everything to 99 to see changes easily.
Ran Dark Forces (the batchfile runs 'CONFIG -set "mididevice=fluidsynth"'.

See mixer before and after:
![Bildschirmfoto 2023-05-13 um 13 01 51](https://github.com/dosbox-staging/dosbox-staging/assets/61995128/42382568-4e65-44d9-9dbf-77e04c21e49a)
![Bildschirmfoto 2023-05-13 um 13 02 21](https://github.com/dosbox-staging/dosbox-staging/assets/61995128/c361b264-0c0a-4782-ae1a-193a690507e6)

**Comment by Burrito78** [comment]
Why r54 and c54 though??

**Comment by johnnovak** [comment]
Because you must have set some chorus and reverb preset, and on mixer reset the values are reset to the preset defaults.

**Comment by Burrito78** [comment]
Do you mean 'fsynth_chorus' and 'fsynth_reverb'? They are both off in dosbox-staging.conf and no other config is loaded.

**Comment by johnnovak** [comment]
Nope, `reverb` and `chorus` in the `mixer` section.

**Comment by Burrito78** [comment]
![Bildschirmfoto 2023-05-13 um 15 08 27](https://github.com/dosbox-staging/dosbox-staging/assets/61995128/86e6e45e-6199-4ca7-a21c-f5ba70aa6cc5)

**Comment by johnnovak** [comment]
Are you using `-noprimaryconf`? I highly recommend to always run DOSBox with that flag when testing these issues and always include your full local `dosbox.conf` if you have one. Without that info there's always gonna be lots if back and forth questioning about what is in your local config, what is in your global conf, have changed the default global conf, etc.

By starting DOSBox with the `-noprimaryconf` param, only the local config will be loaded, so by pasting that into the ticket we know for absolute certainity the settings you tested with. Thanks 😄 

Can you do this this issue and post your results then? Can you also include a screenshot of the mixer's ouput right after DOSBox started and before changing any of its settings via mixer commands?

**Comment by Burrito78** [comment]
Yeah, makes sense.

-noprimaryconf

dosbox.conf
```
[fluidsynth]
soundfont = FluidR3_GM_GS.sf2

[autoexec]
@echo off
keyb gr 437
c:
```

Mixer after startup
<img width="756" alt="Bildschirmfoto 2023-05-28 um 00 41 03" src="https://github.com/dosbox-staging/dosbox-staging/assets/61995128/32d410da-bbb8-434a-8516-d07460d49bdd">

Mixer after activating fluidsynth
<img width="772" alt="Bildschirmfoto 2023-05-28 um 00 43 16" src="https://github.com/dosbox-staging/dosbox-staging/assets/61995128/6f942160-4d9a-44af-a5d7-caca40500423">

Setting everything to 99 to check for changes easily
<img width="771" alt="Bildschirmfoto 2023-05-28 um 00 59 13" src="https://github.com/dosbox-staging/dosbox-staging/assets/61995128/13be9288-21e9-48b6-b2bf-1111e4e3ed34">

After running Dark forces (which calls 'config -set mididevice=fluidsynth' in its batchfile again)
<img width="762" alt="Bildschirmfoto 2023-05-28 um 01 04 19" src="https://github.com/dosbox-staging/dosbox-staging/assets/61995128/1224b28a-dc95-4310-9c44-845ae90c88fe">

**Comment by johnnovak** [comment]
Thanks for helping narrow this down @Burrito78. Yes this is definitely a bug, no questions about it, and it's a weird one. Tagged it with "audio" so I'll get to it when I'm in audio enhancement/bugfix mode next time 👍🏻

**Comment by kcgen** [comment]
Very detailed repro steps, @Burrito78. Thanks.

**Comment by Burrito78** [comment]
This is now a feature request AND a bug ticket, btw! Wanted a feature, got another bug...

**Comment by johnnovak** [comment]
Just notes for myself as I'll fix all these problems in one go:

- Setting `crossfeed` from the DOS prompt has no effect
- `mixer sb x40` works, but when you set `sbtype` to something else, it will also set the same crossfeed for the OPL channel
- `mixer asdf r1` sets the reverb to 1 for all channels 😩 same for chorus & crossfeed
- Enabling/disabling sound devices or `sbtype` resets the reverb/chorus/xfeed settings from the presets and/or from the previously stored values which are stored... somewhere?

This is a huge mess currently, I'll need to revisit the whole thing. Not sure if I did such a shitty job or if has regressed over time, but this is unacceptable.
