### ISSUE TITLE
Alien Trilogy Level 25, it is not possible to climb the ramps

### ISSUE THREAD

**Issue by orderorder** [dosbox-staging/dosbox-staging#2481]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Different version than latest?

main branch

### What Operating System are you using?

Linux x86_64

### Whats your question and how can we help?

in this Alien Trilogy gameplay we can see how at level 25 the character can go up through the ramps

https://www.youtube.com/watch?v=Hc3cUhyNkb0&t=11160s

The author of this other video comments refers to "slopes which you can't seem to climb to get out of some places"

https://www.youtube.com/watch?v=Wc5wxhGu8Qg

I have tried both the multilanguage version and the US version in Dosbox and I am not able to go up the ramps of that level. Does anyone know of a fix or anything they can comment on? Thank you

I leave the saved game of that level. Rename the file by removing .txt

[TRIL.SG2.txt](https://github.com/dosbox-staging/dosbox-staging/files/11472948/TRIL.SG2.txt)

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by kcgen** [comment]
Have you tried a fixed cycle-count that's roughly period-correct for the game?

**Comment by johnnovak** [comment]
Could be a bad crack as well...

**Comment by Grounded0** [comment]
Game patched to latest version?:

https://www.patches-scrolls.de/patch/298/7/

**Comment by orderorder** [comment]
I have tried with and without patches. I've tried the cycles, but it seems to be a problem with the game. I'll keep testing as I'm curious about this bug.

**Comment by kcgen** [comment]
I can't imagine a bug that only manifests on specific ramps in one level, but not in the other levels or other ramps in the same level.

This sounds a lot like how the level works - either a bug (level designer didn't mark the ramp as accessible) or deliberate (simply a unpassable boundary or some prior objective needs completing before entering).

It looks like this users is on PC hardware: https://www.youtube.com/watch?v=U9QmNXCIjmM  Maybe you can re-trace his steps in the same order, and get a similar outcome?

**Comment by orderorder** [comment]
According to the video it can be level 24 or 25. In the videos, the player is not seen going up the ramps. In the psx versions, it does go up the ramps.

PC

https://youtu.be/vyuenq7ot_I

PSX

https://youtu.be/6_9Fa2ijeT4

**Comment by kcgen** [comment]
I think that solves it, @orderorder .. even on a real PC, the player isn't going up the ramps. Will close this, as it doesn't seem to be anything unique or broken in DOSBox Staging.

**Comment by orderorder** [comment]
I'm going to put this in case anyone experiences this "false error". To go up the ramps, you must press Shift to run. My fault, that key is not configurable in the options menu but it is mentioned in the manual.

**Comment by MasterO2** [comment]
> I'm going to put this in case anyone experiences this "false bug". To go up the ramps, you must press Shift to run. My fault, that key is not configurable in the options menu but it is mentioned in the manual.

Now added to https://github.com/dosbox-staging/dosbox-staging/wiki/Game-issues#alien-trilogy as well.
