### ISSUE TITLE
CHAMP Galagon Name Entry Freezing

### ISSUE THREAD

**Issue by Gabeplus** [dosbox-staging/dosbox-staging#2483]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### What Operating System are you using?

Windows 10

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

**Please note that this bug could be due to the game itself and not the emulator.** In CHAMP Galagon, there is an in-game Hall of Fame showing the top scores in the game. Normally, the Name Entry screen will have a 60-second timer counting down, and you can enter your name with either the red selector using the cursor keys or just simply entering your name with the keyboard. However, the bug causes the Name Entry screen to freeze, which means the red selector, timer, and placeholder name (which you replace by entering your own) will not show up, and no keyboard/joystick controls (not even ESC) will allow you to go back to the game's main menu screen unless you press ALT+F4 to force-quit the emulator.

How the Name Entry screen is supposed to look:
![champ-galagon_14](https://github.com/dosbox-staging/dosbox-staging/assets/133732486/caf0c37f-16e2-4221-a9d9-dca5483d1d29)

How the frozen-up Name Entry screen looks:
![Screenshot 2023-05-15 220910](https://github.com/dosbox-staging/dosbox-staging/assets/133732486/265c93d8-eb75-46d7-9c0d-9c926134606f)

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Install and open CHAMP Galagon (set cycles to "fixed 23880" in order for the game to run properly)
2. Play until you lose all of your ships. If you reach a high enough score, the Name Entry screen will appear.
3. The bug occurs randomly, so it might take a few plays and attempts until it happens.

### Download URL of affected game or software

http://champ-em.com/download/GALAGON.ZIP

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by kcgen** [comment]
@Gabeplus , can you try with these settings?

```ini
[cpu]
core = dynamic
cycles = 23880

[dosbox]
dos_rate = 60

[sblaster]
sbtype = sb16

[dos]
xms = false
ems = false
umb = false

[ethernet]
ne2000 = false

[ipx]
ipx = false

[speaker]
pcspeaker = none
```

They are meant to be minimal and the game feels a bit more robust. Curious if it's of any help.

**Comment by kcgen** [comment]
(confirmed working better via chat) - closing.

**Comment by MasterO2** [comment]
> (confirmed working better via chat) - closing.

So as long as people use the settings you mentioned before, CHAMP Galagon will no longer freeze at the name entry screen?

**Comment by kcgen** [comment]
> will no longer freeze 

I won't be playing it for hours to find out, however, maybe game freezes are simply less frequent.
