### ISSUE TITLE
Small improvements to 'mixer /listmidi'

### ISSUE THREAD

**Issue by Burrito78** [dosbox-staging/dosbox-staging#2484]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### What Operating System are you using?

Mac OS

### Is your feature request related to a problem? Please describe.

When MT-32 is active, the current active ROM isn't displayed in green and so it's not immediately clear whats going on.
It's functional but could be better.

Also the paths to the SF2 soundfonts are too long and therefore cut off.

![Bildschirmfoto 2023-05-15 um 14 50 19](https://github.com/dosbox-staging/dosbox-staging/assets/61995128/1ef8c251-b781-431a-b077-4b4d0f21e976)

**Comment by Grounded0** [comment]
Highlighting active MT-32/CM-32 ROM makes sense and behaves similarly how we highlight active Fluidsynth soundfont.

**Comment by johnnovak** [comment]
This has been bothering me too. I have a branch that highlights the active MT-32 romset in green, like it used to earlier. I just need to finish it sometime...

**Comment by Grounded0** [comment]
@Burrito78 You can write your Fluidsynth directory as ~/Library/Preferences/DOSBox... so the whole path name + file name fits into the text field.

**Comment by Burrito78** [comment]
#3011 fixed these issues, closing.
