### ISSUE TITLE
Prevent loading of hidden files and files starting with '._' in IMGMOUNT

### ISSUE THREAD

**Issue by Burrito78** [dosbox-staging/dosbox-staging#2485]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Different version than latest?

DEV

### What Operating System are you using?

Windows 10

### Is your feature request related to a problem? Please describe.

When trying to load image files using  'imgmount' in Windows that have previously been handled by macOS, the command tries to load the hidden '._*.cue' files that macOS created.

Imgmount using wildcards on windows shouldn't load hidden files or files starting with '._'. 

![Unbenannt2](https://github.com/dosbox-staging/dosbox-staging/assets/61995128/480f309a-4f25-44a9-892a-f2067c6bf846)

![Unbenannt](https://github.com/dosbox-staging/dosbox-staging/assets/61995128/1eb2799c-922b-463b-a765-98561fb180a7)

**Comment by kcgen** [comment]
This should do it:
 - `imgmount d T7G*.CUE -t cdrom`

I haven't seen these phantom .dot-files, what (terrible) software is creating them?

I'm reluctant to put in hard-coded exclusions in the code, given these are valid host filesystem names, and moutable items come in from the host filesystem. (Names that start with dot are valid on Linux, macoOS, and Linux).

That said: perhaps mounting using wildcards should be best effort.

If a user does `imgmount -d * -t cdrom`, it should just crank through all the files and skip the bad ones (print warnings for files that it failed).  But keep the good ones.

**Comment by Grounded0** [comment]
Yeah which software is writing dot files like that?

**Comment by Burrito78** [comment]
macOS creates them on every USB drive you use, because the filesystem can't store them, they are written to disk with the same name and '._' in front.

https://www.diigo.com/annotated/02f8452857182c040ea991891d361a53

**Comment by Burrito78** [comment]
LOL, just learned about this: http://www.zeroonetwenty.com/blueharvest/

**Comment by kcgen** [comment]
BlueHarvest: a filesystem diaper for Finder, *"We keep the messes in!"* 🤦‍♂️ 

The more software like this, the better - it's a wake-up call to the macOS team to do better.  

Just like how Microsoft's sloppy management of the registry (orphaned keys, invalid references, ever-growing bloat, etc) spawned the Windows tuneup-ware industry of bottom-feeder software. It's a bad look for the OS, and they're finally getting a handle on it.

**Comment by Grounded0** [comment]
Fun thing is that in other POSIX operating systems besides macOS dot files would be ignored in a reg exp sweep but Windows doesn't respect special status of dot files so this shit happens.

**Comment by johnnovak** [comment]
Copying your DOSBox files from macOS to Windows via a USB drive then running into problems when trying to mount multiple CD image files via wildcards.

Sounds like a pretty niche problem when you describe it like that, doesn't it? 😄 

You just need to delete those Finder dot files when transfering files from the Mac to another OS. It's just one of those weird things you need to be aware of as a Mac user using other OSes as well 🤷🏻‍♂️ 

I think we can "creatively" break things on Windows and Mac by creating filenames with the same letters but different casing -- works on a case-sensitive filesystem, but macOS and Windows are case-preserving only by default.

So nothing to fix here. What I really dislike when these Finder files end up in distributes archives...

**Comment by Burrito78** [comment]
@kcgen Thanks for the fix, very nice!
