### ISSUE TITLE
Commander Keen 4 flickering pixel lines

### ISSUE THREAD

**Issue by Burrito78** [dosbox-staging/dosbox-staging#2488]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Different version than latest?

DEV

### What Operating System are you using?

Mac OS

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Using latest DEV version this happen right in the first level when walking up the little hill.

![Bildschirmfoto 2023-05-16 um 17 40 36](https://github.com/dosbox-staging/dosbox-staging/assets/61995128/4b0fdcae-85b2-43d8-b1cd-0d0effc8ede0)

![Bildschirmaufnahme 2023-05-16 um 17 28 00](https://github.com/dosbox-staging/dosbox-staging/assets/61995128/285b8b6e-caaf-4eb3-b7e3-6dbed8f98c19)

Doesn't happen in 0.74-3 vanilla or 0.80.1 Staging.

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Install Commander Keen 4 (eXoDOS version)
2. Run in DOSBox Staging 0.81.0 alpha DEV.
3. Walk up the small hill in first level.

### Your configuration

```ini
default
```

**Comment by kcgen** [comment]
Thanks, @Burrito78 - and for checking other versions.

**Comment by johnnovak** [comment]
Use `machine = ega`? I'm pretty sure it would behave the same way with `machine = vgaonly` on 0.80.1. This game has all sorts of visual issues and jerky scrolling on most VGA cards except a select few that got EGA compatibility mostly right.

If it works without glitches on EGA, I'm inclined to close this; it's not really regression when it was only working flawlessly with the imperfect non-double-scanning VGA emulation.

Actually, `force_vga_single_scan` should also do the trick.

Related: the Keen games use various EGA hardware tricks and break on all VGA cards that are not 100% compatible. Which led to patches like these: https://pckf.com/viewtopic.php?t=6192
