### ISSUE TITLE
Config File Location Different From Wiki Information

### ISSUE THREAD

**Issue by lukastom** [dosbox-staging/dosbox-staging#2499]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Different version than latest?

0.80.1

### What Operating System are you using?

Linux x86_64

### If Other OS, please describe

Linux Mint 21.1

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

The configuration file is located on:
`/home/<user>/.var/app/io.github.dosbox-staging/config/dosbox/`
which is totally different from what the documentation says (`~/.config/dosbox/`). Many new users can not find the configuration file.  The documentation probably needs adjusting.

### Steps to reproduce the behaviour.

Explain how to reproduce
1. install DosBox Staging (flatpak)
2. try to find the configuration file. The Wiki says it should be in `~/.config/dosbox/`
3. the file is not there, even the folder `dosbox` does not exist on this path.

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by kcgen** [comment]
"DosBox Staging (flatpak)". 

Download the zip provided here, and try again. 

Your conf file location is caused by flatpak and how their system works. These details are something you, as a flatpak user, need to learn about. 

There are countless other packaging systems with similar differences: snap, nix, appimage, guix, autopackage, etc..

We won't be documenting how those work either.

**Comment by lukastom** [comment]
Flatpak is the first suggested option for Linux users on this page: [https://dosbox-staging.github.io/downloads/linux/](https://dosbox-staging.github.io/downloads/linux/) and is also present in some Linux software centers like the only suggestion (for example Linux Mint, one of the most used Linux distros). Because of that, it is possible that many Linux users will simply use flatpak version. While you are technically right, the lack of documentation could deterr new users which is a pitty.

**Comment by kcgen** [comment]
All good points.

We'll adjust it to list the release package here first, followed by 3rd party repository packages next along with a note that 3rd party packages may different features, functional constraints, and conf location(s), among other possible differences, and that users should learn about those via the 3rd party repository's documentation.

**Comment by lukastom** [comment]
Sounds good, thank you for your comments!
