### ISSUE TITLE
Earthworm Jim graphical errors on left screen border

### ISSUE THREAD

**Issue by Burrito78** [dosbox-staging/dosbox-staging#2510]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Different version than latest?

DEV

### What Operating System are you using?

Mac OS

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

At the start of the first level, when you move the character there are parts of the backround that flicker on the left screen border.

Error does happen using v0.80.1 and latest dev build.
Error also happens in vanilla DOSBox v0.74-3.

Couldn't reproduce the error using DOSBox-X (May release). 

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Start Earthworm Jim (i used the eXoDOS version) after mounting the CD image.
2. Select option '1' for mixed resolutions (320x224 and 320x240 (recommended)).
3. You can skip the intro by pressing ESC once.
4. Start the game which brings you to the first level.

-The error doesn't always happen, try starting only the game again from the DOS CLI is enough to reproduce the problem.
-Performance also takes a huge hit when the error happens.

Log output about resolution switching with latest main:
<img width="973" alt="Bildschirmfoto 2023-05-22 um 11 02 58" src="https://github.com/dosbox-staging/dosbox-staging/assets/61995128/b719fbe3-6b69-4635-8614-471849b2de8c">

Video capture of the problem:
[ewj1_000.avi.zip](https://github.com/dosbox-staging/dosbox-staging/files/11529729/ewj1_000.avi.zip)

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by Kappa971** [comment]
This game runs at an odd resolution and refresh rate (320x224 72Hz reported as 640x448 in game, 320x240 60Hz reported as 640x480 in the menu).
With my old 60Hz FullHD monitor I also noticed this strange artifact, I don't remember what I did to remove it. However, I remember that to play it smoothly, before starting the game, I set the screen to 800x600 72Hz (The screen supported this mode).
To play this game I recommend any FreeSync monitor, even the cheapest 75Hz monitor (which I don't recommend for modern games as they don't support LFC).
