### ISSUE TITLE
The 7th Guest segfault with latest development version

### ISSUE THREAD

**Issue by Burrito78** [dosbox-staging/dosbox-staging#2515]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Different version than latest?

DEV

### What Operating System are you using?

None

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

When starting 'The 7th Guest' (eXoDOS) using 'Soundblaster' on latest development build.

<img width="976" alt="Bildschirmfoto 2023-05-22 um 19 36 22" src="https://github.com/dosbox-staging/dosbox-staging/assets/61995128/ae854f57-2f45-4243-8954-c20dda0a8c8a">

[7th guest segfault.txt](https://github.com/dosbox-staging/dosbox-staging/files/11534532/7th.guest.segfault.txt)

### Steps to reproduce the behaviour.

Explain how to reproduce
1. 
2.
3.

### Your configuration

```ini
config -set fullscreen=false
config -set memsize=32
config -set cycles=15000
config -set sbmixer=false
```

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by kcgen** [comment]
Can you find the `main` merge where it started? (might have to go back a ~week and then divide and conquer) 

https://github.com/dosbox-staging/dosbox-staging/actions/workflows/macos.yml?query=is%3Asuccess+branch%3Amain

**Comment by kcgen** [comment]
@MeAreJeenius , seeing that `string_view` is involved, suspect it relates to the shell refactoring PR. Will bisect and report back.
