### ISSUE TITLE
Megarace 2 crashes

### ISSUE THREAD

**Issue by geist22** [dosbox-staging/dosbox-staging#2519]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### What Operating System are you using?

Windows 10

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

I'm using the files from the GOG version of Megarace 2, which uses a .gog file (that I assume is an ISO) mounted as a CD. Menu and movies work, but when trying to enter a race, 5 out of the 6 levels crash the game immediately when the loading screen finishes, with the error message `mem error !Musique trop grande 00000000`. One level (Bayou) works, but after a while the music stops with some artifacts before it loops.

DOSBox 0.74-3 plays the game without issue.

### Steps to reproduce the behaviour.

1. Start the game and enter any level except Bayou.
2. The console should be flooded with the `GetTrack at sector x is outside the playable range` messages and the game should crash shortly thereafter.

### Download URL of affected game or software

https://www.gog.com/en/game/megarace_1_2

### Your configuration

```ini
default
```

### Provide a Log

```text
https://gist.github.com/geist22/be7ac2eb5909cc439612d2099d81c00a
```

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by kcgen** [comment]
Unfortunately I don't have the GOG version.

My copy of Mega Race 2 has two ISO CDROMs (not BIN/CUE) and uses files for music, not redbook audio. For example:

![2023-05-23_17-06](https://github.com/dosbox-staging/dosbox-staging/assets/1557255/2f381184-81aa-4bca-8f43-2f7c8670e26a)


https://github.com/dosbox-staging/dosbox-staging/assets/1557255/ebed2bf6-1f86-42be-a48d-ebea6be32010

**Comment by geist22** [comment]
There's only one image file (.gog, 871MB, which I guess is an ISO), unlike the games with CD audio music that I have which use two (.ins and .gog which I guess is .cue + .bin). I don't think this is CD audio. My Bronx folder from this image looks identical to yours:

![dir](https://github.com/dosbox-staging/dosbox-staging/assets/107389189/ddc843ba-01a9-4b5f-9de3-459a75fd812e)

If I disable music in the game's options menu, it works without crashing.

**Comment by kcgen** [comment]
Yes; looks similar. Can you share your exact files or reproduce the error with any of these:

https://archive.org/download/megarace-pc-redump/MEGARACE-PC-REDUMP/

And then indicate which has the issue?

**Comment by geist22** [comment]
GOG version is commercially sold, so I doubt it would be appropriate to share the files here.

Using my existing install, I've mounted `MegaRace 2 (Europe) (Disc 1)` and `MegaRace 2 (Europe) (Disc 2)` from your link as iso instead of the one .gog file, and all levels play fine, with music and no crashes. Could dosbox-staging have issues with images above 700MB?

I've made a list of the contents of the .gog image file:
[image.txt](https://github.com/dosbox-staging/dosbox-staging/files/11550285/image.txt)

**Comment by kcgen** [comment]
Thanks for all those tests, @geist22!
To investigate this further, please visit Discord.

**Comment by MasterO2** [comment]
@geist22 Regarding that error message in French `mem error !Musique trop grande 00000000`.  Have you considered changing the `memsize` setting in `dosbox-staging.conf` to 32?  (32 MB)

**Comment by geist22** [comment]
I've tried a higher memsize, up to 64 with no results.
I'll check out the discord today.
