### ISSUE TITLE
Dosbox-staging crashes with Ultimate Doom (UDoom32)

### ISSUE THREAD

**Issue by Ripthorn** [dosbox-staging/dosbox-staging#2523]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Different version than latest?

0.81.0-alpha-770-g4f4b3ff7f

### What Operating System are you using?

Windows 11

### Relevant hardware info

Core i9 10850K, RTX 3080 Ti, 32GB

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

I'm trying to use UDoom32 because I plan to use custom wads and mods. Is the only way for Ultimate Doom with vanilla engine.
https://doomwiki.org/wiki/UDoom32
https://www.doomworld.com/forum/topic/132915/
As soon as I try to save the progress the game crashes and shows the message below with GUS enabled

![image](https://github.com/dosbox-staging/dosbox-staging/assets/8785487/99df5aab-db89-49d9-93e8-52e50731658f)

With Sound Blaster enabled, shows a different message:
![image (1)](https://github.com/dosbox-staging/dosbox-staging/assets/8785487/e9771fe5-1fa2-4893-a6f5-469e0f8a68d0)

Same problem (maybe?) with DosBox-X:
![Captura de tela 2023-05-23 194941](https://github.com/dosbox-staging/dosbox-staging/assets/8785487/486bec5a-5ec7-4b01-b9a6-0de407bcb1ae)

Same thing with DOSBox 0.74-3, but it did not generate any error message. DOSBox-Staging 0.80.1 has the same behavior as the alpha version. None of that happens with the original .exe

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Run the hacked .exe
2. Select any episode
3. Try to save the progress

### Download URL of affected game or software

https://archive.org/download/doom-full-collection/Ultimate.iso

### Your configuration

```ini
https://gist.github.com/Ripthorn/17041d6f22f3dab8ad4189a8875d6b55
```

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by kcgen** [comment]
For `udoom.exe`, use GUS or SB16; not both at the same time.

### SB16:

1. Ensure GUS is off before launching udoom:
    - `[gus] gus = off`, or
    -  manually type `gus off` at the Z:\> or C:\> prompt.
2. `SETUP.EXE` w/ "SoundBlaster" at 220, IRQ 7, DMA 1

### GUS:

1. Ensure SoundBlaster is off before launching udoom:
    - `[sblaster] sbtype = none`, or
    -  manually type `sbtype none` at the Z:\> or C:\> prompt.
2. `SETUP.EXE` w/ "Gravis UltraSound" at 240, IRQ 5, DMA 3

**Comment by kcgen** [comment]
Given the original game tolerates having both SB and GUS devices simultaneously (even when saving), my hunch is that `udoom.exe` will also crash on a real DOS PC that has both an SB16 on 220/I7/D1 and GUS on 240/I5/D3.

Such a configuration is likely rare, but if someone out there has one, feel free to report back!

**Comment by Ripthorn** [comment]
I forgot to mention, but when I tested it with sound blaster, I had gus turned off in the config file and still crashes with the same error message. I tried with the gus off command you mentioned on dosbox command prompt and nope, same thing.

**Comment by kcgen** [comment]
Try these settings:

![2023-05-23_19-26](https://github.com/dosbox-staging/dosbox-staging/assets/1557255/e622a665-1b61-4be7-9428-17a5a5947fa2)

`udoom32` is a limit-removing hack, so let's make sure it has as much memory as possible.

**Comment by Ripthorn** [comment]
Yep, this really solves the issue, the weird part is it only crashes when you try to save.
Thanks to find the solution 😂
