### ISSUE TITLE
Descent 2 intro cinematic stuttering badly using GUS

### ISSUE THREAD

**Issue by Burrito78** [dosbox-staging/dosbox-staging#2525]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Different version than latest?

DEV

### What Operating System are you using?

Mac OS

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Happens in both Staging latest DEV 81.0-775 and 0.80.1 final.

The intro cinematic is stuttering badly (playing at like 5fps) and audio is rhythmically muting while the video hangs.

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Install Descent 2 (eXoDOS)
2. Configure game setup to use GUS
3. Start Descent 2

### Your configuration

```ini
-noprimaryconf 
mount c users/alex/games/exodos/drives/c
imgmount d cd\*.cue -t cdrom
config -set gus=true
```

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by kcgen** [comment]
Use the GUS conf: https://github.com/dosbox-staging/dosbox-staging/wiki/Sound-Cards#gus-native-games

Here's is a recording at 30k cycles:

https://github.com/dosbox-staging/dosbox-staging/assets/1557255/b7fc13d4-f017-4171-83b5-1f29fbc291b4

GUS games normally behave well in the sub-30k range. But the good news is Descent 2 isn't even GUS native. You can tell from output like this (1 or 2 voices at-most):

```
GUS: Audio comprised of 8-bit samples from 2 voices
```

**Comment by Burrito78** [comment]
Thanks @kcgen, yes it was the cycle setting! Still new to GUS, will remember that from now on for sure1

Again, i READ that guide and still f*cked it up. 🥇

**Comment by johnnovak** [comment]
> GUS games normally behave well in the sub-30k range.

That's news to me, maybe some playroutines in earlier GUS games were CPU sensitive?

1995+ demos that require a Pentium definitely have problem with GUS audio at 100-200k+ cycles (e.g. Inside by CNCD).

**Comment by kcgen** [comment]
Yup - the demo authors have a lot of mastery over the GUS!
For non-GUS-native games (that just push out DMA chunks), they often are fine w/ high cycles too.
It's the earlier GUS native games where (if you give them `max`) then can get less smooth or stuttery, and often easily hit peak-performance in the sub-30k cycle fixed range.

**Comment by Grounded0** [comment]
Descent 2 will not run smoothly with mere 30k cycles with SVGA and details maxed out. Would stick instead with SB16 + MIDI.

**Comment by johnnovak** [comment]
> For non-GUS-native games (that just push out DMA chunks), they often are fine w/ high cycles too.

Rendering via CPU then just using the GUS as a stupid DAC like the SB, that's... very sad 😢 
I thought Descent was of higher caliber than that 🤷🏻

**Comment by johnnovak** [comment]
> Descent 2 will not run smoothly with mere 30k cycles with SVGA and details maxed out. Would stick instead with SB16 + MIDI with near max cycles.

Yeah, and any SVGA 3D game would be choppy as hell on a Pentium MMX 233 too. Virtually no period-correct hardware could play those games at non-slideshow framerates; you needed a Pentium 2 450 or higher for that.

Well, I've tried on my MMX 200; all SVGA 640x480 games are around 2-3 FPS.

These were the "max ultra settings" graphics fidelity settings of the day like in Crysis, meant for future hardware generations 😎

**Comment by Grounded0** [comment]
2017 15" MacBook Pro scores a little bit better than 450MHz Pentium III in LINPACK so there's definitely horsepower to drive these games even with software renderer.

**Comment by johnnovak** [comment]
> 2017 15" MacBook Pro scores a little bit better than 450MHz Pentium III in LINPACK so there's definitely horsepower to drive these games even with software renderer.

Yeah, just max cycles can get you into all sorts of trouble (weird bugs, glitches, audio stutter, etc). Best to be avoided and set a high fixed cycles number manually.

**Comment by Burrito78** [comment]
Makes no sense for eXoDOS to offer GUS option on this game, nothing gained.

Closing again?
