### ISSUE TITLE
Descent 2 audio stutters shortly when skipping cinematics using ESC while using fluidsynth

### ISSUE THREAD

**Issue by Burrito78** [dosbox-staging/dosbox-staging#2526]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Different version than latest?

DEV

### What Operating System are you using?

Mac OS

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

When skipping cutscenes in Descent 2 using the ESC key, when the video stops playing there is an audio stutter that isn't happening using FM/GUS or CD audio.

Happens in both Staging 0.81.0-775 and 0.80.1.

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Install and start Descent 2 (eXoDOS)
2. Select SC55 in the menu or use fluidsynth through config.
3. Hear a audio stutter when skipping cutscenes.

### Your configuration

```ini
-noprimaryconf

mount c users/alex/games/exodos/drives/c
imgmount d cd\*.cue -t cdrom
config -set mididevice=fluidsynth
```

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by kcgen** [comment]
When using SB, the game's cinema player continues to send a bit of extraneous audio DMA buffer prior to terminating the cinematics sequence; this happens (and finishes) prior to game's driver sending the DSP request to the SB.

**Comment by johnnovak** [comment]
Probably this is how it behaves on real hardware too. You could also test with external MIDI

**Comment by kcgen** [comment]
Yup, it's the SB.  When you hit ESC, the cinematic sequence feeds some trailing non-zero'd audio into the SB via DMA, even before it sends the DSP reset signal. 

Unfortunately, there's not much we can do. The moment we get the DSP reset, we stop the mixer channel - however in this case, that bad audio has already come down the pipe. 

When the cinematic code uses the GUS, it properly clears/stops the DMA stream when you hit ESC.

**Comment by johnnovak** [comment]
> Yup, it's the SB. When you hit ESC, the cinematic sequence feeds some trailing non-zero'd audio into the SB via DMA, even before it sends the DSP reset signal.
> 
> Unfortunately, there's not much we can do. The moment we get the DSP reset, we stop the mixer channel - however in this case, that bad audio has already come down the pipe.
> 
> When the cinematic code uses the GUS, it properly clears/stops the DMA stream when you hit ESC.

Yeah I guess maybe you can experiment with different SB models. Although it's a mess on real hardware... Wouldn't be surprised it Creative's 1332134 revision of SB16 boards worked slightly differently in most games, having slightly different glitches and who knows what...

Maybe try the `sbtype = sbpro2`. Really, that should be everybody's default.

**Comment by kcgen** [comment]
`sbpro2` switches to 8-bit DMA transfers (and maybe smaller transfers?) it's subjectively maybe a shorter/quicker sequence.  Although I didn't do hard side-by-sides.

**Comment by johnnovak** [comment]
> `sbpro2` switches to 8-bit DMA transfers (and maybe smaller transfers?) it's subjectively maybe a shorter/quicker sequence. Although I didn't do hard side-by-sides.

Yeah, my point, `sb16` very rarely brings anything worthwhile to the table. Most games have 22kHz or lower 8-bit audio. It's unfortunate we need to keep `sb16` as the default for compatibility with pre-configured gamepacks out there.

**Comment by johnnovak** [comment]
> But Descent 2's cinematics don't use MIDI, just SB audio - very strange.

Sure, but what the game's code actually does under the hood when MIDI is enabled is anyone's guess... Anything goes there, and game devs are not famous for clean coding practices 😅

**Comment by GranMinigun** [comment]
Cinematics are a red herring, it's very likely just the way the game performs GM initialization, and it just coincides with the end of FMV playback. I don't think this is something to worry about, really. If anyone wants to dig into it, both games' sources are available.

**Comment by Burrito78** [comment]
Hey, happens with macOS Coreaudio too! So not related to Fluidsynth.

If no one wants to dig any further (don't know if that even would make sense), we can close this up.

**Comment by johnnovak** [comment]
> Cinematics are a red herring, it's very likely just the way the game performs GM initialization, and it just coincides with the end of FMV playback. I don't think this is something to worry about, really. If anyone wants to dig into it, both games' sources are available.

Yeah, a bit pointless to focus on these micro-issues. Most of these are present on various real hardware too.

**Comment by Burrito78** [comment]
@kcgen wrote:

> That's as good as I could get.. low host CPU usage and butter smooth ~80 FPS steady in-game, 640x400 
> It plays the high-res videos smooth too, without any pauses.  However, there's still a slight hitch when pressing escape.
> However, it's improved a bit by disabling the 16-bit audio and just using 8-bit DMA exclusively.
> 
> ...the game is extremely efficient with its 640x400 VESA mode - and blasts out 80+ FPS with only 200k fixed cycles.
> Where as going to 640x480 FPS falls into the 30s and 40s, and feels a lot less fluid.

<img width="1000" alt="Bildschirmfoto 2023-05-26 um 08 43 11" src="https://github.com/dosbox-staging/dosbox-staging/assets/61995128/b1d796c0-a82c-4a91-b8b7-dc0c117bd8be">

```
[sdl]
output = opengl
presentation_mode = auto

[render]
glshader = none

[cpu]
core = dynamic
cycles= 200000

[dosbox]
machine = svga_s3
memsize = 64
dos_rate = 120
startup_verbosity = quiet
automount = true

[midi]
mididevice = fluidsynth

[fluidsynth]
soundfont = sf2/awe64_gold_4mb_gm.sf2

[gus]
gus = false

[sblaster]
sbtype = sb16
oplmode = none

[dos]
xms = false
ems = false
umb = false

[speaker]
pcspeaker = none
tandy = off
disney = false

[ipx]
ipx = off

[ethernet]
ne2000 = off

[autoexec]
@echo off
c:
cd descent2 > NUL
del *.swp > NUL
descent2
```

**Comment by Burrito78** [comment]
Waiting on @kcgen how the game performs using ECE which eXo uses, just for completeness sake.
Sorry this got a little drawn out but Descent 2 using SB+MIDI is an important game to get running optimally.

Also, imho, we have to be better or equal to ECE performance and that is the main goal of this ticket.

**Comment by kcgen** [comment]
Yup, ECE is good too :+1: 

![2023-05-26_00-25](https://github.com/dosbox-staging/dosbox-staging/assets/1557255/8146c742-0a10-4a41-a06f-e666f96a88d0)

**Comment by kcgen** [comment]
![2023-05-26_00-28](https://github.com/dosbox-staging/dosbox-staging/assets/1557255/50c96b76-080b-415a-a003-a78d8d88e4da)

**Comment by Burrito78** [comment]
@kcgen Slight stutter there with ECE too when skipping the cutscenes i guess? :)

**Comment by kcgen** [comment]
> @kcgen Slight stutter there with ECE too when skipping the cutscenes i guess? :)

Unfortunately I can't tell; on my system it doesn't pick up the audio devices so fallsback to no-sound mode (see 5th log line).
