### ISSUE TITLE
Internal command Z:\MEM.COM eats away all the UMB memory

### ISSUE THREAD

**Issue by FeralChild64** [dosbox-staging/dosbox-staging#2532]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Different version than latest?

0.80.1, also reproducible on current GIT

### What Operating System are you using?

Linux x86_64

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

It seems the internal command `mem` eats away all the UMB memory. I have used the `mem` command from DR-DOS to confirm that it is not a display bug, but indeed UMB is not available any more.

### Steps to reproduce the behaviour.

1. Start DOSBox Staging with option `-noprimaryconf`
2. Execute `mem` command twice
3. The second time it reports no UMB memory

![bug](https://github.com/dosbox-staging/dosbox-staging/assets/48332137/c0eae000-d8fb-42ad-803c-055033a673cd)

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by kcgen** [comment]
Fascinating find, @FeralChild64 !

*"'one must pay a small fee in RAM to the memory checker"* 💰

**Comment by FeralChild64** [comment]
@kcgen It seems `program_mem.cpp` allocates memory and expects our DOS implementation to free it once the program exits. For some reason this works for conventional memory, but not for UMB.

**Comment by Grounded0** [comment]
Who stole the memory!:
<img width="1392" alt="Screenshot 2023-05-26 at 1 29 13" src="https://github.com/dosbox-staging/dosbox-staging/assets/48192273/5ea75e34-9dae-43f3-b1a7-f83f90520f6f">

**Comment by Grounded0** [comment]
Can we flag this as 0.81 Project. Seems nasty enough to me.
