### ISSUE TITLE
Setting 'condfig -set tandy=on', then 'config -set tandy=off' kills Soundblaster output

### ISSUE THREAD

**Issue by Burrito78** [dosbox-staging/dosbox-staging#2537]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Different version than latest?

DEV

### What Operating System are you using?

Mac OS

### Relevant hardware info

M2 mini

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Enabling Tandy using 'config -set tandy=on' and then disabling it again using 'config -set tandy=off' prevents sound output in games launched afterwards using Soundblaster output, e.g. Quake.

[Quake repro pack.zip](https://github.com/dosbox-staging/dosbox-staging/files/11579926/Quake.repro.pack.zip)

### Steps to reproduce the behaviour.

Explain how to reproduce
1. 
2.
3.

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by johnnovak** [comment]
If SB is enabled, tandy=on should only enable the tandy 3-Voice synth but not the DAC, so that should work. Tandy DAC cannot coexist with the SB DAC due to resource conflicts, so maybe tandy=off somehow messes with the SB DAC and disables it.

What if you explicitly set the sbtype after tandy=off?

**Comment by johnnovak** [comment]
Having said that, many Tandy games require machine=tandy to work. It's not quite normal or useful to switch tandy=on at runtime with non-Tandy machine types.

So quite low priority. I'd much rather fix GUS first so it can coexist with SB.

**Comment by Burrito78** [comment]
eXo does it in his Monkey Island config, afaik.

**Comment by Burrito78** [comment]
Yes, doing `config -set sbtype=sb16` fixes audio output again.

**Comment by Burrito78** [comment]
Happens in 0.80.1 too, btw.

**Comment by johnnovak** [comment]
Hasn't @kcgen 's recent DMA related improvent fixed this? Can you retest @Burrito78 ?

**Comment by Burrito78** [comment]
No, setting 'tandy=on', then 'tandy=off' kills sb16 output using latest DEV still. 'sbtype=sb16' restores soundblaster output.

**Comment by johnnovak** [comment]
> No, setting 'tandy=on', then 'tandy=off' kills sb16 output using latest DEV still. 'sbtype=sb16' restores soundblaster output.

Yeah, I'm starting to think this is alright. Turning Tandy on turns SB off because they conflict, then when you turn Tandy off, well, it does what it's supposed to do — Tandy is off 😄 

To me it makes sense that you need to re-enable SB explictily again after it was turned off automatically. I'm not sure I'd like it to spring back to life automatically when turning Tandy off again... That's too much magic & automatic behaviour for my taste, but we'll see what @kcgen says when he's back.

**Comment by kcgen** [comment]
That's right, @johnnovak, and how it's supposed to work.

It's like a dinner reservation: the table can only be occupied one reservation at a time.

The settings (in general) do not keep a memory and reinstate the prior value. 

If you set glshader A, then B, then C.. turning off shader C doesn't reinstate shader B, and then turning off shader B also doesn't reinstate shader A. 

Likewise, Tandy, GUS, and SB can all be configured to use the same DMA channel, and in the same way, only one card can occupy a given channel. The log was meant to be verbose enough to explain what's happening. 

The way to use it is simply set the device you want to use and don't worry about the consequences. If you game is configured for sb16, then set sb16.  any conflicting devices will be shut down to accomodate it. 

(This makes a lot more sense than working backward to "unravel" prior devices to get back to the original device).
