### ISSUE TITLE
Indiana Jones and the Fate of Atlantis no MT-32 music, log shows "MT32: Audio buffer underrun"

### ISSUE THREAD

**Issue by Burrito78** [dosbox-staging/dosbox-staging#2547]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Different version than latest?

0.81.0-alpha-785

### What Operating System are you using?

Mac OS

### Relevant hardware info

M2 mini

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

When launching the above game using MT-32 for music, no music is heard and the log shows the above error messages.

Repro pack:
https://mega.nz/file/0hRVQR4K#yYbjOlLsONWqoE7neWlarxGzztZwwmMw8QekKLHZdBA

**The problem seems to arise because `config -set mididevice=mt32` is called twice in the configuration i uploaded.**

### Steps to reproduce the behaviour.

Use above repro pack plz.

### Your configuration

`-noprimaryconf`

```
imgmount d cd\*.cue -t cdrom
config -set memsize=63
config -set mididevice=mt32
```

`atlantis r`

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by Burrito78** [comment]
Just noticed, works in 0.80.1.

**Comment by johnnovak** [comment]
Indeed, I managed to reproduce it. Doing `config -set mididevice=mt32` _twice_ causes this, like you said @Burrito78. If I comment it out in `r.bat`, then I get MT-32 sound:

```ini
@echo off
if exist CD imgmount d cd\*.cue -t cdrom
config -set memsize=63
REM config -set mididevice=mt32

cd fate
call run.bat
```

So something with the MIDI init code... Great testing and narrowing the issue down @Burrito78! 🎉

**Comment by Burrito78** [comment]
It happens with Fluidsynth too.

![Bildschirmfoto 2023-05-31 um 13 31 44](https://github.com/dosbox-staging/dosbox-staging/assets/61995128/981389ee-c86d-4c6b-a932-52570d37d971)

**Comment by Burrito78** [comment]
Add this to 0.81 todo @kcgen?
