### ISSUE TITLE
Under a Killing Moon - not enough memory

### ISSUE THREAD

**Issue by nemo93** [dosbox-staging/dosbox-staging#255]
* Description
Game will launch yet will display a message about "insufficient memory" or "out of memory" (I'm playing in french hence not sure about the exact translation!). The outcome is simply you can't play the game.

* To Reproduce:
I run the game that way in order to have Gravis sound:
```
CD UAKM
LOADPATS.EXE
TEX3.EXE
```
NOTE: game must be launched with MOON.EXE instead otherwise some video won't be triggered (like the one introducing each new day).

I'm using a cue/cd version with 1st cd mounted prior launching the game. On the main menu click new game. From there game will ask about the 2nd CD => Ctrl+F4 and ok. Another FMV will play and right after it the "out of memory message" will be shown.
NOTE: with the current Dosbox SVN (default in Retropie) the same issue occurs.

* Environment:
Raspbian Jessie (the one shipped with Retropie+all packages up-to-date)
Retropie Version 4.5.18 (latest)
Pi3B+
SDL2 2.0.10 (no dispmanx)
Self compiled Dosbox-staging:
```
$ git describe
v0.75.0-pre-706-gdbc77a6f
```

* Extender:
I tried with and without DOS32/A but the outcome is the same. Also I've tried with a patched EXE found on the Web (TEX197.EXE) but the game won't even play the FMV after main menu/new game.

* Dosbox config:
```
fullscreen       = true
fullresolution   = desktop
windowresolution = desktop
output           = texture
texture_renderer = auto
capture_mouse    = seamless middlerelease
sensitivity      = 100
waitonerror      = true
priority         = higher,normal
mapperfile       = mapper-SVN.map

language = 
machine  = svga_s3
captures = capture
memsize  = 24

frameskip = 0
aspect    = true
scaler = none

core = dynamic
cputype   = auto
cycles = max 95% limit 30000
cycleup   = 10
cycledown = 20
[...] 

sbtype  = none
sbbase  = 220
irq     = 7
dma     = 1
hdma    = 5
sbmixer = true
oplmode = auto
oplemu  = default
oplrate = 44100
[...]

gus      = true
gusrate  = 44100
gusbase  = 240
gusirq   = 5
gusdma   = 3
ultradir = U:\ULTRASND
[...] 

xms            = true
ems            = false
umb            = true
keyboardlayout = auto
```

**Comment by krcroft** [comment]
`memsize  = 31` any help?

On your 3B, a nice upper-bound cycle count should be roughly 35000 or 34000 (for protected-mode games)

**Comment by nemo93** [comment]
silly me. I should have confirmed that I did try a wide range of memsize and enabling/disabling xms/ems combo. Still same error. I'll keep trying and report here if I find anything useful.

**Comment by rderooy** [comment]
One hint, the game supports multiple CD-ROM drives, so you can have each CD on a different drive letter. So no need to "swap" disks.

I just set it up with 4 CD-ROM drives. And it starts with the default settings, 16MB RAM and such. I did not try GUS, but seeing how this game was designed for GM, I don't see a reason to use GUS.

**Comment by kcgen** [comment]
Awesome find @rderooy !
Are you aware of other giant DOS games that allow spanning their CDs across multiple drives? 

This list might be so small that it would warrant explicitly stating these game titles that support multi-drive in the README's media-swapping section.

**Comment by rderooy** [comment]
I know the 7th Guest and the 11th Hour support multiple CD-ROM drives. There are probably others.

**Comment by rderooy** [comment]
Looking around, I found people saying to disable EMS and to replace TEX3.EXE that gets installed with TEX197.EXE from CD1 (see README.TXT on CD1 for details). But I did none of that, and in my (limited) testing it seems to run fine with default settings. It is using a SB16 and GM for audio.

I tried it with DOSBox staging, DOSBox ECE and DOSBox-X. No problems with running through the intro and to the beginning of the actual game.

**Comment by rderooy** [comment]
[autoexec]
MOUNT C "UAKM"
IMGMOUNT D "UAKM/CD/Under_a_Killing_Moon_CD1.iso" -t iso
IMGMOUNT E "UAKM/CD/Under_a_Killing_Moon_CD2.iso" -t iso
IMGMOUNT F "UAKM/CD/Under_a_Killing_Moon_CD3.iso" -t iso
IMGMOUNT G "UAKM/CD/Under_a_Killing_Moon_CD4.iso" -t iso
C:
CD \KMOON
MOON.EXE

**Comment by nemo93** [comment]
thanks a lot @rderooy for the nice tip. Unfortunately issue remains despite switching for SB16 (no more GUS), 16MB RAM and disabling EMS. I've also tried running the game with MOON.EXE instead of TEX3/TEX197.EXE. Same outcome.

@kcgen I need to check Ripper (6CD) and the Wing Commander 3/4 to see if they support multiple drives. Down in the dumps as well.

**Comment by rderooy** [comment]
@nemo93 perhaps it is something specific to the RPi. As I said, no problems here on Fedora 31 on x86_64.

**Comment by nemo93** [comment]
On a Pi4 it's even worse as it takes forever to reach the main menu screen. Even when you get there the small menu which raises on the right side of the screen will appear but frame by frame.

**Comment by kcgen** [comment]
@nemo93 , I've freed some space on my Pi3's SD card, so will move this (huge) game over and see if I can reproduce this.

**Comment by kcgen** [comment]
@nemo93 , 

I'm using SB16 + FluidSynth (with [current FS PR](https://github.com/dosbox-staging/dosbox-staging/pull/575)), and a specific dosbox.conf, and not seeing memory issues; the game plays quite nicely and sounds great - 

**SB16 + GM**: [:speaker: under_a_killing_moon.flac ](http://205.250.146.105:8001/tex3_001.flac) (click to play)

My guess is that loading the GUS's patch-wavetables into low memory is causing the memory shortage problem.  Because the games doesn't leverage the GUS hardware features, I would not use GUS for this game.

Here's my dosbox.conf for it:

``` ini
sdl]
capture_mouse = onstart middlerelease

[cpu]
core=dynamic
cycles=90000

[dosbox]
machine=vesa_nolfb
memsize=16

[gus]
gus=false

[sblaster]
sbtype  = sb16
sbmixer = false
oplmode = none

[dos]
xms=true
ems=false
umb=false

[speaker]
pcspeaker=false
tandy=off
disney=false

[mixer]
rate = 48000

[midi]
mididevice = fluidsynth

[fluidsynth]
soundfont     = general_user_gs-1.471.sf2
fluid_rate    = 48000
synth_threads = 2
```

And audio sections in the game's `config.ini`:

``` ini

[DIGI_CONFIG]
BoardNum=3
IoAddr=0x220
DMA=5
Int=7
Volume=100

[MIDI_CONFIG]
BoardNum=10
IoAddr=0x330
DigiDrums=Yes
Volume=65
```

and finally, `start.bat`

``` shell

@echo off

mount d disk1 -t cdrom -label DISK1
mount e disk2 -t cdrom -label DISK2
mount f disk3 -t cdrom -label DISK3
mount g disk4 -t cdrom -label DISK4

moon
exit
```

**Comment by nemo93** [comment]
Well... once again apologize :-( Silly me. It turned out the iso dump of the game I was using was simply corrupt. I've done a proper bin/cue of the 4 discs and the issue is now gone. Nothing to do with memory or whatever just a bad dump....

Thanks @kcgen for the time and assistance as always. I feel terrible to have wasted so much of your time for something that trivial in the end :(
