### ISSUE TITLE
256 colour modes not working in latest dev builds on windows 3.1

### ISSUE THREAD

**Issue by jowtron** [dosbox-staging/dosbox-staging#2550]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Different version than latest?

dosbox-staging-macOS-v0.81.0-alpha-786-g89b47

### What Operating System are you using?

Mac OS

### Relevant hardware info

MacBook Pro 11,1

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Ive tried a few modes :
VESA 640x480 256-colour (mode 101h)
VESA 800x600 256-colour (mode 103h)
VESA 1024x768 256-colour (mode 105h)

All these work on the stable 0.80.1 but not in the 0.81 dev builds

There are some windows 3.1 games that require the graphics be set at 256 colours, so it would be good to find out why it's broken in the latest builds.

### Steps to reproduce the behaviour.

Explain how to reproduce
1. using the s3 trio64v 1.69.02 drivers
2.
3.

### Your configuration

```ini
default setup I think
output              = opengl
aspect             = true
```

### Provide a Log

```text
there doesnt seem to be any errors thrown, just a garbled display
```

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by johnnovak** [comment]
So which games are we talking about? Do you get the same garbled display when you simply just change the desktop resolution to 640x480 / 256-colour, or only when you launch a game?

**Comment by johnnovak** [comment]
Indeed, I tried some of my Win3.x games that work flawlessly with 0.80.1, and the 256 colour output in Windows 3.1 is completely broken. Probably something to do with the vgaonly changes @kcgen?

Windows 3.11 start screen:

![image](https://github.com/dosbox-staging/dosbox-staging/assets/698770/de3e111b-f144-437c-8cfa-ba29a436644b)

This is how Myst looks like:

![image](https://github.com/dosbox-staging/dosbox-staging/assets/698770/a5c8a17d-6ea5-47ab-9ca1-74fe91ad0a8c)

**Comment by johnnovak** [comment]
Okay, this caused the regression:
https://github.com/dosbox-staging/dosbox-staging/pull/2528#event-9333743214

Revert it @kcgen? Fixing one relatively small glitch in one game at the expense of breaking Win3.x 256-colour compatibility is quite a hard sell 😅

**Comment by Grounded0** [comment]
Robert E. Lee: Civil War General requires 256 colour mode in order to run:

https://www.mobygames.com/game/4773/robert-e-lee-civil-war-general/

**Comment by johnnovak** [comment]
> Robert E. Lee: Civil War General requires 256 colour mode in order to run:
> 
> https://www.mobygames.com/game/4773/robert-e-lee-civil-war-general/

Yeah, a lot of Win3.x games do, maybe most that aren't FMV games that require 15/16-bit high-colour modes? E.g. Myst, Darkseed 2, Shivers, etc. all need 256 colour modes.

**Comment by kcgen** [comment]
In the queue!

**Comment by Grounded0** [comment]
I have a few Win 3.x games and most will run even in 32-bit modes just fine even if they're 256 colour games but Robert E. Lee: Civil War General will crash unless Windows is set for 256 colour.

**Comment by johnnovak** [comment]
> I have a few Win 3.x games and most will run even in 32-bit modes just fine even if they're 256 colour games but Robert E. Lee: Civil War General will crash unless Windows is set for 256 colour.

Right, I see. I think Myst requires a 256-colour mode too, similarly to Civil War General. But yeah, most could actually run in 15/16/24-bit mode. I just run Win 3.1 in 256-colour mode because I only use it for games and very few actually need hi-colour modes.
