### ISSUE TITLE
Simcity 2000 hanging on exit when path is longer than 13 characters

### ISSUE THREAD

**Issue by Burrito78** [dosbox-staging/dosbox-staging#2556]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Different version than latest?

0.81.0-alpha-792

### What Operating System are you using?

Mac OS

### Relevant hardware info

M2 mini

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

When exiting, Simcity 2000 hangs and only displays a blinking cursor when its path is longer than 13 characters.

Repro pack (updated):
https://mega.nz/file/l8YBTZrb#338eyzK1Vdk1J_kU18TW-hwLAOuE0ePT6ck8x-V7oxM

The issue happens in 0.81.0-alpha, 0.80.1 and DOSBox 0.74-3 but not in DOSBox-X.

### Steps to reproduce the behaviour.

Use repro pack, launch sc2k.exe.

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

![Bildschirmaufnahme 2023-05-30 um 22 45 24](https://github.com/dosbox-staging/dosbox-staging/assets/61995128/59daef2a-0c6f-4ee0-b3b8-dc4b389f290b)

**Comment by Grounded0** [comment]
Seems to work just fine here. I configured that packed game to use Roland Sound Canvas for music, mounted the ISO and ran SC2000.BAT to run the game:

<img width="1392" alt="Screenshot 2023-05-30 at 22 04 15" src="https://github.com/dosbox-staging/dosbox-staging/assets/48192273/427e7b35-30e9-4c88-84c3-ba4802ddd429">

**Comment by Burrito78** [comment]
Hey, using a different COMMAND.COM doesn't count! :)

Nope, crashes on a different machine here too using -noprimaryconf, actually crashes on everything but DOSBox-X out of the box.

**Comment by Grounded0** [comment]
Do you execute SC2000.BAT or what?

**Comment by Grounded0** [comment]
Exits cleanly with DOSBox COMMAND.COM too:
<img width="1392" alt="Screenshot 2023-05-30 at 22 40 54" src="https://github.com/dosbox-staging/dosbox-staging/assets/48192273/457aee8d-84e7-4dfe-a830-5104d395cf9d">

**Comment by Grounded0** [comment]
Try mounting the ISO yourself and run SC2000.BAT. It looks like it gets stuck in a batch file loop.

**Comment by Burrito78** [comment]
Hey @Grounded0, thanks for the hint, i did find the exact cause, see updated first post!

A very weird bug again!

**Comment by johnnovak** [comment]
Ok, does this happen on real hardware on real MS-DOS 6.22? If yes, there's nothing to do here.

 At least someone could check in PCem or 86box. @Torinde I heard you like testing stuff? 😄

**Comment by Burrito78** [comment]
> Ok, does this happen on real hardware on real MS-DOS 6.22? If yes, there's nothing to do here.
> 
> At least someone could check in PCem or 86box. @Torinde I heard you like testing stuff? 😄

Well, i tested in 86box right now and the issue doesn't happen there. BUT it also doesn't happen in DOSBox-X...so i still think it's a issue we did inherit from vanilla but can and should probably fix.

Maybe @joncampbell123 can give a hint on this one?

**Comment by Grounded0** [comment]
I tested the game installed into `C:\MAXIS\BLAHBLAH\SC2000SE` and don't have that path length issue.

The ticket could be a command interpreter issue so i would recommend testing against FreeDOS FreeCOM 0.85a. DOSBox Staging `COMMAND.COM` is a shitshow and i would recommend against using it in most circumstances.

**Comment by Grounded0** [comment]
We're concentrating all SimCity 2000 issues to ticket #3518.

**Comment by Burrito78** [comment]
Just wanted to confirm that the workaround added to the Wiki prevents this issue from happening! Good job!

https://github.com/dosbox-staging/dosbox-staging/wiki/Game-issues#simcity-2000
