### ISSUE TITLE
Bundle DOS32/A with dosbox-staging

### ISSUE THREAD

**Issue by dreamer** [dosbox-staging/dosbox-staging#256]
In my experience, DOS32/A is sometimes required to make DOS software run correctly in dosbox (any fork/version). It looks like other users might have much worse experience and in some cases - the majority of games might require it to work correctly (it's really hard to tell).

Installing DOS32/A to run the game is easy… but it's still annoying (downloading dos32/a, making backups of dos4gw, renaming, etc, etc) and should be easier.

There are several ways to accomplish it, my initial idea is to add new configuration option:

```
[dos]
use_dos32a = false/true
```
When set to `true` and game tries to load DOS4GW, dosbox could load bundled DOS32/A instead (without the need to actually replace the file on disk).

This is a bigger task (not for 0.75.0 for sure) and there are certain licensing issues that need to be resolved ([link](https://opensource.stackexchange.com/questions/9518/does-gplv2-allow-for-prohibiting-misrepresentation-of-the-origin)), but I see no technical nor legal reasons why it wouldn't work.

**Comment by nemo93** [comment]
In case it helps, let me re-use the list provided by @kcgen in [that ticket](https://github.com/dreamer/dosbox-staging/issues/247#issuecomment-605352208). As I'm extensively testing Dosbox-staging these days with a testbed of ~150 games I'll add/change anything to this list to keep it as up-to-date as I possibly could. 
NOTE: I have no better place to put that list together hence feel free to point me to any other location.

```
11th hour/v32.exe (needs testing as game is presently crashing)
Abuse/abuse.exe
AD&D Legend III Eye of the Beholder III Assault of Myth Drannor/interp.exe
AD&D Ravenloft I Strahd's Possession/rloft/sinstall.exe
Afterlife/cdrom/alifedos.exe
Al-Qadim/genier.exe
Albion/main.exe
Alien Rampage/rampage.exe
Anvil of Dawn/anvil.exe
Archon Ultra/archon.exe
**Archimedean Dynasty (Schleichfahrt)/dos4gw.exe (needs confirmation)
Archimedean Dynasty (Schleichfahrt)/setup.exe (needs confirmation)**
Ascendancy/ascend.exe
Azrael's Tear/r.exe
Azrael's Tear/tm.exe
Blood/blood.exe
Caesar II/caeser2/ps.exe
Call of Cthulhu Prisoner of Ice/cdrom/ice640.exe
Callahan's Crosstime Saloon/ccs.exe
Command & Conquer/comcon/game.exe
Conquest Earth/game will crash with DOS/32A
Constructor/game will crash with DOS/32A
**Cybermage/needs confirmation
Deadline/deadline.exe (needs confirmation)**
Descent I/descentr.exe
Descent I/setup.exe
Discworld/dwb.exe
Disney's The Jungle Book/jungle.exe
Disney's The Lion King/lionking.exe
Doom I/doom.exe
**Doom 2/doom2.exe (needs confirmation)
Duke Nukem 3D/duke3d.exe (needs confirmation)**
Dungeon Keeper/keeper.exe
Earthworm Jim/ewj.exe
**Ecstatica/dos4gw.exe (needs confirmation)
Ecstatica 2/e2dos.exe (needs confirmation)
Exhumed (Powerslave)/dos4gw.exe (needs confirmation)
Fallout/fallout.exe (needs confirmation)
Fatal Racing (Whiplash)/fatal.exe (needs confirmation)
Fatal Racing (Whiplash)/process.exe (needs confirmation)
Funtrack (Ignition)/maindos.exe (needs confirmation)
Genewars/dos4gw.exe (needs confirmation)**
Great Naval Battles Vol IV Burning Steel, 1939-1942/gnb4.exe
**Harvester/dos4gw.exe (needs confirmation)
Heretic/heretic.exe (needs confirmation)
Heroes of Might & Magic/heroes.exe (needs confirmation)
Heroes of Might & Magic 2/heroes2.exe (needs confirmation)**
Hexen Beyond Heretic/hexen.exe
**Hi Octane/dos4gw.exe (needs confirmation)**
IndyCar Series/indycar.exe
Jagged Alliance Deadly Games/dg.exe
Jagged Alliance/ja.exe
Jungle Strike/cdrom/playgdv.exe
Jungle Strike/jungle/playgdv.exe
Krush Kill N Destroy (kknd)/kknd.exe
**LBA/dos4gw.exe (needs confirmation)
LBA2/dos4gw.exe (needs confirmation)
Lighthouse/sier.exe (needs confirmation)
Lost Vikings 2/lostv.exe (needs confirmation)
Lost Vikings 2/thevoice.exe (needs confirmation)**
MAX Mechanized Assault & Exploration/max104.exe
MAX Mechanized Assault & Exploration/maxrun.exe
**Master of Orion 2/orion2.exe (needs confirmation)
Master of Orion 2/setsound.exe (needs confirmation)**
MDK/mdk/mdk.exe
**MechWarrior 2/dos4gw.exe (needs confirmation)
MechWarrior 2 Mercenaries/dos4gw.exe (needs confirmation)**
Mega Man X/mmx/mmxrun.exe
**Mega Race 2/m.exe (needs confirmation)**
Micro Machines 2 Turbo Tournament/mm2/mm2.exe
Micro Machines 2 Turbo Tournament/mm2/_mm2_.exe
Millennia Altered Destinies/player.exe
Millennia Altered Destinies/playern.exe
Millennia Altered Destinies/_setup.exe
**Need for Speed/dos4gw.exe (needs confirmation)**
NHL 95/hockey/hockey.exe
Pizza Tycoon/pizza/pt.exe
Primal Rage/rage/prage.exe
**Privateer 2/dark.exe (needs confirmation)
Privateer 2/osi.exe (needs confirmation)
Quarantine/dos4gw.exe (needs confirmation)
Quarantine 2/rw.exe (needs confirmation)
Rama/sier.exe (needs confirmation)**
Raptor Call of the Shadows/rap.exe
Realms of Arkania III Shadows over Riva/riva.exe
**Redneck Rampage/rr.exe (needs confirmation)
Redneck Rampage/setmain.exe (needs confirmation)
Redneck Rampage/rdhelp.exe (needs confirmation)
Redneck Rampage 2/ra.exe (needs confirmation)
Redneck Rampage 2/setmain.exe (needs confirmation)
Ripper/player.exe (needs confirmation)
Ripper/ripper.exe (needs confirmation)
Ripper/setup.exe (needs confirmation)**
Rise of the Triad Dark War/rott.exe
**Screamer/dos4gw.exe (needs confirmation)
Screamer 2/setup.exe (needs confirmation)
Screamer 2/start65h.exe (needs confirmation)
Screamer 2/start65l.exe (needs confirmation)
Screamer 2/starth.exe (needs confirmation)
Screamer 2/startl.exe (needs confirmation)
Screamer Rally/st.exe (needs confirmation)
Screamer Rally/starth.exe (needs confirmation)
Screamer Rally/startl.exe (needs confirmation)
Settlers/intro.exe (needs confirmation)
Settlers/sett.exe (needs confirmation)
Settlers 2/s2.exe (needs confirmation)
Settlers 2/s2edit.exe (needs confirmation)
Shadow Warrior/setmain.exe (needs confirmation)**
Silent Hunter/silent/se.exe
Silent Hunter/silent/sh.exe
SimCity 2000/sc2000.exe
SimIsle Missions in the Rainforest/simisle/simisle.exe
**Space Hulk/dos4gw.exe (needs confirmation)**
Steel Panthers/steel.exe
STRIFE/strife1.exe
Terminal Velocity/tv/game.exe
The Elder Scrolls Chapter II - Daggerfall/fall.exe
The Horde/horde/horde.exe
The Smurfs/smurfs.exe
Theme Hospital/hospital/hospital.exe
Wacky Wheels/setup.exe
Wacky Wheels/ww.exe
Warcraft II Tides of Darkness/war2.exe
World of Aden Thunderscape/main.exe
World Rally Fever/rolling.exe
X-COM III Apocalypse/sound/player.exe
X-COM III Apocalypse/tacexe/tacp.exe
X-COM III Apocalypse/ufoexe/smkp.exe
X-COM III Apocalypse/ufoexe/ufo2p.exe
```

**Comment by nemo93** [comment]
Done @dreamer. [New entry](https://github.com/dreamer/dosbox-staging/wiki/DOS32A-compatibility-list) added to the Wiki. I'll update it the best I can in the following days.

**Comment by rderooy** [comment]
Don't know if this is helpful, but DOSBox-X includes both DOS4GW and DOS32A on the Z:\ drive

Z:\>DOS4GW.EXE
DOS/4G Protected Mode Run-time  Version 2.01a
Copyright (c) Tenberry Software, Inc. 1996
DOS/4G fatal error (1004): syntax is DOS4G <executable.xxx>

Z:\>DOS32A.EXE
DOS/32A -- DOS Extender version 9.1.2
Copyright (C) 1996-2006 by Narech K.
DOS/32A fatal (8001): syntax is DOS32A <execname.xxx>

**Comment by dreamer** [comment]
Indeed, it does! I don't know if it loads it automatically or only keeps it in `Z:\` to make it easier for user to copy into the game directory?

Including DOS32/A this way is ok, but DOS4GW is closed source, proprietary, *paid* (to the best of my knowledge) software - I can't include it and be GPL compliant AFAIK. If I did it, dosbox-staging would no longer be Free software.

**Comment by kcgen** [comment]
Similar to proprietary audio codecs used by GPL players, perhaps we could include a downloader for 4GW?

Then again, we need to weigh the value that DOS4GW adds versus the maintenance burden. There are only a handful of games that benefit from upgrading their older 4GW with the latest 4GW (so the benefit is pretty slim).  Versus carrying 32A, which corrects /lots/ of games; perhaps several hundreds.

**Comment by dreamer** [comment]
@kcgen exactly. I don't want to deal with *significant* downsides of bundling proprietary binary blobs vs very slim benefits. Few games that will require DOS4GW update will need to be handled by game distributors or archivists so we definitely need to document it on our wiki (or e.g. [PCGW](https://www.pcgamingwiki.com/wiki/Home), which is a consolidated place for this kind of information). So: bundling DOS4GW - nope, DOS32/A - yes.

We could however calculate checksum of DOS4GW used and if it's not the latest version (whatever that was), display a warning in  log (or maybe even in dosbox shell).

**Comment by kcgen** [comment]
> calculate checksum of DOS4GW used and if it's not the latest version (whatever that was), display a warning in log (or maybe even in dosbox shell)

That alone would be a huge help! If we can inspect the right part of the executable and lift this out of embedded binaries as well (reusing whatever code the GNU `file` tool uses).

**Comment by Akuma-Git** [comment]
This could be hung under: https://github.com/dosbox-staging/dosbox-staging/issues/601

**Comment by dreamer** [comment]
@Akuma-Git no, in this particular case it's a bit different. We don't want DOS32/A to be merely available in the path - we want it transparently replacing DOS4/GW in the game directory if user requested it via opt-in setting in .conf file. We don't want to physically overwrite the file on disk, only redirect file access in the emulated drive.

**Comment by Akuma-Git** [comment]
I could be wrong, but you kind of solved that issue here I think ;)
https://github.com/dosbox-staging/dosbox-staging/issues/504

**Comment by kcgen** [comment]
Adding this: https://github.com/dosbox-staging/dosbox-staging/issues/993, as another potential for bundling executable that are valuable for gaming.  (TIE Fighter installer calls `debug.exe` to apply patches to various files).

**Comment by kcgen** [comment]
We're recommending the freeDOS package manager be used to manage and install useful tools: https://github.com/dosbox-staging/dosbox-staging/wiki/Add-Utilities

DOS 32/a is supported: https://www.ibiblio.org/pub/micro/pc-stuff/freedos/files/distributions/1.2/repos/pkg-html/dos32a.html

**Comment by Grounded0** [comment]
Changed closed type to not completed.
