### ISSUE TITLE
Fixed DOSBox Staging unable to be added into force function keys in touch bar in macOS

### ISSUE THREAD

**Issue by Grounded0** [dosbox-staging/dosbox-staging#2567]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### What Operating System are you using?

Mac OS

### Relevant hardware info

2017 15" MacBook Pro

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

I've fixed a long standing issue in macOS where DOSBox Staging is unable to be added into force function keys in touch bar:

<img width="372" alt="Screenshot 2023-06-02 at 10 47 48" src="https://github.com/dosbox-staging/dosbox-staging/assets/48192273/2bc1af83-79fb-4235-80a4-510da844cdcd">
<img width="780" alt="Screenshot 2023-06-02 at 10 48 10" src="https://github.com/dosbox-staging/dosbox-staging/assets/48192273/ba80012c-92e9-4665-a55d-30e7c535933b">

The fix is on my fork where i've taken out the comments from CFBundleIdentifier:

Main:

https://github.com/dosbox-staging/dosbox-staging/blob/main/contrib/macos/Info.plist.template

My fork:

https://github.com/Grounded0/dosbox-staging/blob/main/contrib/macos/Info.plist.template

Pretty safe stuff so hopefully merged soon.

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by kcgen** [comment]
Nice fix, @Grounded0 (added).

**Comment by Grounded0** [comment]
What this accomplishes for the 0.81.0 release notes:

https://mastodon.world/@anttipeltola/110514143531689905

**Comment by Grounded0** [comment]
This should be documented in 0.81 release notes so tagging this with documentation.

**Comment by johnnovak** [comment]
Nice addition @Grounded0. I got used to globally enabling true function keys inthe system prefs because otherwise DOS Navigator in unusable, but with this I can only enable them for Staging 🎉
