### ISSUE TITLE
`string_utils_tests` regressions in Visual Studio 2019

### ISSUE THREAD

**Issue by johnnovak** [dosbox-staging/dosbox-staging#2571]
Looks like the recent switch to string views has introduced some test failures on Visual Studio 2019. I'm a bit confused how this wasn't caught by CI, but anyway, here are my local results. Most test cases are still passing, but there are some failures even after a clean + full rebuild.

Summary:

```
2>[----------] Global test environment tear-down
2>[==========] 225 tests from 36 test suites ran. (1224 ms total)
2>[  PASSED  ] 221 tests.
2>[  FAILED  ] 4 tests, listed below:
2>[  FAILED  ] StartsWith.Prefix
2>[  FAILED  ] StartsWith.TooLongPrefix
2>[  FAILED  ] StartsWith.EmptyPrefix
2>[  FAILED  ] StartsWith.EmptyString
```

Details:

```
1>[----------] 5 tests from StartsWith
1>[ RUN      ] StartsWith.Prefix
1>D:\Work\Code\dosbox-staging\tests\string_utils_tests.cpp(132): error : Value of: starts_with("ab", "abcd")
1>  Actual: false
1>Expected: true
1>D:\Work\Code\dosbox-staging\tests\string_utils_tests.cpp(133): error : Value of: starts_with("ab", std::string{"abcd"})
1>  Actual: false
1>Expected: true
1>[  FAILED  ] StartsWith.Prefix (0 ms)
1>[ RUN      ] StartsWith.NotPrefix
1>[       OK ] StartsWith.NotPrefix (0 ms)
1>[ RUN      ] StartsWith.TooLongPrefix
1>D:\Work\Code\dosbox-staging\tests\string_utils_tests.cpp(144): error : Value of: starts_with("abcd", "ab")
1>  Actual: true
1>Expected: false
1>D:\Work\Code\dosbox-staging\tests\string_utils_tests.cpp(145): error : Value of: starts_with("abcd", std::string{"ab"})
1>  Actual: true
1>Expected: false
1>[  FAILED  ] StartsWith.TooLongPrefix (0 ms)
1>[ RUN      ] StartsWith.EmptyPrefix
1>D:\Work\Code\dosbox-staging\tests\string_utils_tests.cpp(150): error : Value of: starts_with("", "abcd")
1>  Actual: false
1>Expected: true
1>D:\Work\Code\dosbox-staging\tests\string_utils_tests.cpp(151): error : Value of: starts_with("", std::string{"abcd"})
1>  Actual: false
1>Expected: true
1>[  FAILED  ] StartsWith.EmptyPrefix (0 ms)
1>[ RUN      ] StartsWith.EmptyString
1>D:\Work\Code\dosbox-staging\tests\string_utils_tests.cpp(156): error : Value of: starts_with("ab", "")
1>  Actual: true
1>Expected: false
1>D:\Work\Code\dosbox-staging\tests\string_utils_tests.cpp(157): error : Value of: starts_with("ab", std::string{""})
1>  Actual: true
1>Expected: false
1>[  FAILED  ] StartsWith.EmptyString (0 ms)
1>[----------] 5 tests from StartsWith (0 ms total)
1>
```

**Comment by kcgen** [comment]
`libiconv` in vcpkg has been broken for the last week in GitHub's Windows VMs, so unfortunately that's caused all builds (release, debug, and testing) to fail in the dependency phase.

![2023-06-02_07-08](https://github.com/dosbox-staging/dosbox-staging/assets/1557255/a1973f98-d407-4bb3-b904-cee9a57d0663)


When it rains it pours, eh?

I'll turn on MSVC builds early next week after GitHub revs their VMs; hopefully this will be mopped up then.

**Comment by kcgen** [comment]
Oh - even though the above is true, this might not be the case.

Remember you suggested we flip the order of `starts_with()`'s arguments? 

I think you mentioned doing that in your branch, and I did it in the MIDI PR, which appears to be OK: https://github.com/dosbox-staging/dosbox-staging/actions/runs/5164208907/jobs/9302963050

Maybe this is all it is?

**Comment by johnnovak** [comment]
> Oh - even though the above is true, this might not be the case.
> 
> Remember you suggested we flip the order of `starts_with()`'s arguments?
> 
> I think you mentioned doing that in your branch, and I did it in the MIDI PR, which appears to be OK: https://github.com/dosbox-staging/dosbox-staging/actions/runs/5164208907/jobs/9302963050
> 
> Maybe this is all it is?

Ah, could be... Maybe it's broken in my branch on macOS too and VS Studio is a red herring. I just started Windows testing this morning, but then I haven't run these tests on macOS either since I rebased to your merged string enhancements commit.

Ok, having another look later :)

**Comment by kcgen** [comment]
Hopefully it's OK!

`main` is running tests here locally, even with UB+ASAN enabled:

![2023-06-03_19-38](https://github.com/dosbox-staging/dosbox-staging/assets/1557255/cbd85928-09ab-404d-b022-671b537bcc6b)

**Comment by johnnovak** [comment]
Yep, a case of an embarassing user error 😊 I switched the args in `src`, but forgot to grep in `test`... 🤦🏻 Next time should look a bit closer before raising a ticket! 😅

**Comment by kcgen** [comment]
Np! Double checks with some false positives are better than real problems slipping by. 🍻
