### ISSUE TITLE
Flashback - The Quest for Identity CD Version - Hangs on black screen during Level 2 cutscene

### ISSUE THREAD

**Issue by Gryzor1363** [dosbox-staging/dosbox-staging#2572]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### What Operating System are you using?

Windows 7

### Relevant hardware info

FX-8350 4.5Ghz, 16 Gb Ram

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Whenever I reach the 2nd cutscene in Level 2 (at the very early stage of the level, once you free your friend and sit in the memory recovery machine), it presents a very brief error message stating "Invalid buffer number (move_video)" and then hangs on a black screen. 

Now I don't know whether this is a Dosbox-generated exit on error message or the game output itself within the emulated window.

For reference, crash happens at 0:22 in the cutscene here : https://www.youtube.com/watch?v=zLp9RBdiQsM.

Tried plenty of parameters combination involving memory/machine type/cpu type and speeds, also mounted the game's ISO on a separate virtual drive via Daemon Tools instead of the integrated image mounter, deactivated sound (some have reported it fixes other issues), but to no avail : that crash persists along with its message.

Noteworthy is that I can simply skip this cutscene and continue playing, all other following ones before and after that one seem to run smoothly. 

Thanks for your help !

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Launch game
2. Enter "CHOICE" as a password to reach Level 2 immediatly.
3. Reach the very first stand-off with a pair of enemies guarding a friendly NPC.
4. Enter the memory recovery chair once prompted.
5. Wait until second 22 of the said cutscene is reached.

### Your configuration

```ini
[sdl]

fullscreen          = true
display             = 0
fullresolution      = desktop
windowresolution    = original
viewport_resolution = fit
window_position     = auto
window_decorations  = true
transparency        = 0
host_rate           = auto
vsync               = false
vsync_skip          = 7000
presentation_mode   = auto
output              = openglpp
texture_renderer    = auto
waitonerror         = true
priority            = auto auto
mute_when_inactive  = false
pause_when_inactive = false
mapperfile          = mapper-v2.map
screensaver         = auto

[dosbox]

language           = 
machine            = svga_s3
captures           = capture
memsize            = 63
mcb_fault_strategy = deny
vmemsize           = auto
dos_rate           = default
vesa_modes         = compatible
speed_mods         = true
autoexec_section   = join
automount          = true
startup_verbosity  = high

[render]

aspect             = true
monochrome_palette = white
cga_colors         = default
glshader           = D:\Emulation\DOSBox Staging\resources\glshaders\crt\crt-lottes - custom.glsl

[composite]

composite   = auto
era         = auto
hue         = 0
saturation  = 100
contrast    = 100
brightness  = 0
convergence = 0

[cpu]

core      = auto
cputype   = auto
cycles    = auto
cycleup   = 200
cycledown = 200

[mouse]

mouse_capture        = onclick
mouse_middle_release = true
mouse_sensitivity    = 100
mouse_raw_input      = true
dos_mouse_driver     = true
dos_mouse_immediate  = false
ps2_mouse_model      = intellimouse
com_mouse_model      = wheel+msm

[mixer]

nosound    = false
rate       = 44100
blocksize  = 1024
prebuffer  = 25
negotiate  = false
compressor = true
crossfeed  = off
reverb     = off
chorus     = off

[midi]

mididevice = fluidsynth
midiconfig = 
mpu401     = intelligent

[fluidsynth]

soundfont     = D:\Emulation\DOSBox Staging\resources\Soundfonts\Roland.sf2
fsynth_chorus = auto
fsynth_reverb = auto
fsynth_filter = off

[mt32]

model       = auto
romdir      = 
mt32_filter = off

[sblaster]


sbtype              = sb16
sbbase              = 220
irq                 = 7
dma                 = 1
hdma                = 5
sbmixer             = true
sbwarmup            = 100
oplmode             = auto
sb_filter           = modern
sb_filter_always_on = false
opl_filter          = auto
cms_filter          = on

[gus]

gus        = false
gusbase    = 240
gusirq     = 5
gusdma     = 3
ultradir   = C:\ULTRASND
gus_filter = off

[innovation]


sidmodel          = none
sidclock          = default
sidport           = 280
6581filter        = 50
8580filter        = 50
innovation_filter = off

[speaker]

pcspeaker           = discrete
pcspeaker_filter    = on
tandy               = auto
tandy_filter        = on
tandy_dac_filter    = on
lpt_dac             = none
lpt_dac_filter      = on
ps1audio            = false
ps1audio_filter     = on
ps1audio_dac_filter = on

[reelmagic]

reelmagic       = off
reelmagic_key   = auto
reelmagic_fcode = 0

[joystick]


joysticktype                = none
timed                       = true
autofire                    = false
swap34                      = false
buttonwrap                  = false
circularinput               = false
deadzone                    = 10
use_joy_calibration_hotkeys = false
joy_x_calibration           = auto
joy_y_calibration           = auto

[serial]

serial1       = dummy
serial2       = dummy
serial3       = disabled
serial4       = disabled
phonebookfile = phonebook.txt

[dos]


xms                   = true
ems                   = true
umb                   = true
ver                   = 5.0
country               = 0
expand_shell_variable = false
keyboardlayout        = auto

[ipx]

ipx = false

[ethernet]

ne2000            = true
nicbase           = 300
nicirq            = 3
macaddr           = AC:DE:48:88:99:AA
tcp_port_forwards = 
udp_port_forwards = 

[autoexec]

MIXER FSYNTH 25
```

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by kcgen** [comment]
Does it happen on other builds of DOSBox, like SVN, ECE, or X?

> `"Invalid buffer number (move_video)"` and then hangs on a black screen.

I can at least confirm that this error has never existed in the DOSBox code-base (even going back up through all prior versions of SVN), so definitely coming from the game's executable.

**Comment by NicknineTheEagle** [comment]
Unable to reproduce. It's possible is corrupted, I suggest you find a CUE/BIN image that matches one of Redump entry:
http://redump.org/disc/31196/
http://redump.org/disc/35409/

**Comment by kcgen** [comment]
Thanks for this playtesting and pointers to the exact known-good versions, @NicknineTheEagle !

**Comment by Gryzor1363** [comment]
Thank you all for taking the time to respond and test, and sorry for the false positive, I indeed suspected this might come from a defective ISO file rather than Dosbox (since mainline 0.74 exited with the same message and nobody in the associated forum mentioned anything such regarding this bug (shows 100% compatibility on their website). The thing is, I had the very same issue with another, distinct BIN/CUE dump that I got elsewhere precisely to make sure it wasn't my image. So I guess there are a couple bad ones circulating around in different formats, thanks for pointing me in the right direction and so fast.

Keep up the great work people, the Saging fork changed my entire Dos gaming experience ever since I switched to it.

Cheers,


-G

**Comment by johnnovak** [comment]
> Update : after sourcing yet another dump, it worked as intended. Thanks again for the time spend investigating. My bad luck stumbling upon two consecutive bad dumps too :(
> 
> Thank you all for taking the time to respond and test, and sorry for the false positive, I indeed suspected this might come from a defective ISO file rather than Dosbox (since mainline 0.74 exited with the same message and nobody in the associated forum mentioned anything such regarding this bug (shows 100% compatibility on their website). The thing is, I had the very same issue with another, distinct BIN/CUE dump that I got elsewhere precisely to make sure it wasn't my image. So I guess there are a couple bad ones circulating around in different formats, thanks for pointing me in the right direction and so fast.
> 
> Keep up the great work people, the Saging fork changed my entire Dos gaming experience ever since I switched to it.
> 
> Cheers,
> 
> -G

Thanks for getting back to us, it's much appreciated! Also glad to hear you like Staging so much! 🚀 

If you're able to, it would be good to contact the uploaders/maintainers of the dumps you found about the issue so they can take them down, or flag them as "corrupted dumps" at the very least (although I don't think it's a good idea to leave bad dumps in circulation).

**Comment by Gryzor1363** [comment]
Thanks in turn for getting back to me.

Before answering your very legitimate advice, there needs to be a little context around this 👍 

-I used two distinct CD image dumps : One in IMG format and the other one as a CUE/BIN combination, taken on two different websites (the one with the IMG closed long ago, and I found the one with the CUE sheet only two days ago while searching for an alternative image). Those two images have had the exact same failure desribed above. So my asumption is that they either derive or are re-dumps of a sole defective master shared over several websites over the years, or there is something wrong in my dosbox configuration when it comes to mounting CD images.

-The version I managed to find that actually does the trick for me and stops breaking during the cutscene is actually not an image per se, but rather a raw copy-paste of the CD rom data files to a folder, with a custom executable allowing it to play by pointing to these files rather than a CD-drive. It was packaged like this from an abandonware site. This shows the issue is not related to Dosbox compatibility with the game, as you already figured out.

Now, one thing I could do is to point you guys to the binary + cue image from the existing site so that maybe you could indeed confirm you cannot reproduce the fail on your end ? before doing that obviously I would ask for permission to drop a URL. It presents itself as an abandonware site but I prefer to be cautious when it comes to forum/site rules regarding Roms.

Thanks a lot for your time and patience,


Regards

**Comment by Grounded0** [comment]
I like this for searching for floppy disk and CD disc images:

https://archive.org/
