### ISSUE TITLE
working-dir command line option is not documented in man page

### ISSUE THREAD

**Issue by amak79** [dosbox-staging/dosbox-staging#2574]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### What Operating System are you using?

Linux x86_64

### If Other OS, please describe

Gentoo

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

The `--working-dir` command line option is not documented in man page. I would expect all options and commands to be documented in the man page, even if some are left out in the help output.

### Steps to reproduce the behaviour.

Explain how to reproduce
1.  Open the man page: `man dosbox`
2.  Search the man page: `/--working-dir`

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by johnnovak** [comment]
I think we're going to eventually kill the man page plus the very old, outdated and incomplete .txt ,"manual" once the proper user manual is online, right @kcgen? Or are we still going to document the command line options only in the man page? Can't remember what we decided.

**Comment by johnnovak** [comment]
Do Linux guys wanna keep the man page alive? Yes/no? 😄 @kcgen @FeralChild64 @weirddan455 @rderooy @GranMinigun 

Be aware that the user manual will contain a section about the command line options, and we also have help text (`dosbox -h`). Betwern those two, I don't the need for a man page, but the manual will only appear online next year only. Anyway, you decide, but if you wanna keep it around, some of you Linux users will need to keep it up to date and in sync with the manual. If no takers, I will most likely nuke it once the manual is online as I don't want to maintain the same info in two places (until then it can stay, but be aware it's already quite outdated).

**Comment by weirddan455** [comment]
I don't care about the man page personally.  I like man pages for command line tools and C APIs but DOSBox as a whole is well beyond the scope of what can be reasonably documented in a single man page.

`dosbox -h` does a better job at documenting command line flags and for everything else, I'm with you in that I'd rather have a single point of documentation that's the same for all platforms.

**Comment by GranMinigun** [comment]
I like man pages, but I'm not maintaining that one.

**Comment by kcgen** [comment]
Same here, @weirddan455 and @GranMinigun.
`man` pages are great for more disparate documentation and references.  

Fortunately our documentation sits even "closer" to the points-of-use:
- `--help`, for CLI usage
- 1:1 conf key/value descriptions
- DOS tools have rich `/H` help pages

To me, these points make the man page very much secondary. That's fine, but not if we can't keep it in sync with our functionality.. which we can't; it's more work than the team is able to keep up with. So I also agree it should be tossed 🍌 🗑️ !

**Comment by kcgen** [comment]
> some of you Linux users will need to keep it up-to-date and in sync with the online manual. 

But will the macOS community lament the loss of the man page? 😏 (Ok.. I think I know the answer)

**Comment by johnnovak** [comment]
Yep, I have the same views; they're useful for pure CLI stuff, and have limited usefulness for GUI apps that have online manuals.

So the man pages will go the way of the dodo bird 🐦 🥳 One less thing to maintain! Rejoice! 😎 

> > some of you Linux users will need to keep it up-to-date and in sync with the online manual.
> 
> But will the macOS community lament the loss of the man page? 😏 (Ok.. I think I know the answer)

Maybe they would if they knew what "man pages" meant in the first place (hint: something _male_ Linux geeks like to use 🤣)

**Comment by GranMinigun** [comment]
Mac users read documentation?!

![](https://i.kym-cdn.com/entries/icons/original/000/012/589/patrickstar.jpg)

**Comment by johnnovak** [comment]
> Mac users read documentation?!

Wait, Mac users can read? (ok, I'll stop... 😅)

**Comment by johnnovak** [comment]
I quite liked these "man pages" when I was an adolescent male:

![image](https://github.com/dosbox-staging/dosbox-staging/assets/698770/c9560895-0b8f-4c91-a8c1-ff798b41bee2)

**Comment by johnnovak** [comment]
Closing because I found my stash of "man pages" I saved from the 80s, so I need no more 😎🤘🏻

**Comment by FeralChild64** [comment]
Maybe it will be worth having one if the command-line interface gets stable, or if we are able to generate it automatically from some other documentation. 

Right now - I agree, too much hassle maintaining it, too little benefit.

**Comment by rderooy** [comment]
I generally like having a man page, but I normally only use it if the built-in help is inadequate. And maintaining a man page is a PITA, so I perfectly understand ditching it.

**Comment by Grounded0** [comment]
Fixed by:

- #2837
