### ISSUE TITLE
Star Trek: The Next Generation - A Final Unity - Gravis Ultrasound regression

### ISSUE THREAD

**Issue by SideSwipe9th** [dosbox-staging/dosbox-staging#2575]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Different version than latest?

0.81.0-alpha-864-g98b9804c2

### What Operating System are you using?

Windows 10

### Relevant hardware info

Ryzen 9 5900X, RTX 3090, Sound BlasterX AE-5

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

There is a significant difference in audio quality between Dosbox Staging, and Dosbox SVN in Star Trek: The Next Generation - A Final Unity, when using an emulated Gravis Ultrasound. I've attached comparison recordings, using the same install media and settings of the game's setup sound test, and the initial Captains Log that plays after the intro videos. The SVN build is the non-ECE r4482 build downloaded from Yesterplay. 

In Staging when using a GUS, the game sounds like it is outputting audio at 22KHz. In the SVN build, the game sounds like it is outputting audio at closer to 44KHz. There is prominent audio clipping in the Staging, particularly on the sibilant consonants (most noticeable in the Captains Log clips, listen for the s-es), as well as more pronounced popping akin to the crackles you'd get on a vinyl record. To my ears, the voices sound clearer and less harsh on the SVN build, though I recognise that is largely subjective. 

[Captures.zip](https://github.com/dosbox-staging/dosbox-staging/files/11671466/Captures.zip)
[Conf files.zip](https://github.com/dosbox-staging/dosbox-staging/files/11671531/Conf.files.zip)

### Steps to reproduce the behaviour.

Reproduction steps
1. Open Dosbox Staging or SVN
2. Mount the image and install A Final Unity
3. In the game setup, configure it to use a Gravis Ultrasound.
4. Test and save the settings. 
5. Restart Dosbox
6. Re-mount the image, start the game. 
7. Make an audio recording so you can compare the differences
8. Close Staging or SVN, repeat steps 1-7 with the other version. 

### Download URL of affected game or software

https://archive.org/details/star-trek-the-next-generation-a-final-unity-usa-v-1.01a

### Your configuration

```ini
Configuration files for both Staging and SVN are in the second zip file.
```

### Provide a Log

```text
2023-06-07 02:22:39.459 | GUS: Activated 24 voices at 25725 Hz
2023-06-07 02:23:06.677 | GUS: Audio was made up of 1% 8-bit 23-voice and 100% 16-bit 1-voice samples
2023-06-07 02:23:06.677 | GUS: Shutting down
2023-06-07 02:23:06.677 | OPL: Shutting down OPL3
```

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by kcgen** [comment]
(assignee switched to the source of the regression :laughing: )

**Comment by digistorm79** [comment]
I don’t know much about this particular game (how many voices it actually uses on real hardware) but if it uses 24 voices then the accurate way to emulate is to use the lower 25725 Hz sample rate. DOSBox traditionally ignores this property of the GUS classic so that might be why it sounds like 44100 Hz. The only thing that might be off is the steepness of the anti aliasing filter. I know the GUSpnp uses a very aggressive filter but I have no good memory of what the filter of the GUS classic sounded like.

**Comment by johnnovak** [comment]
> I don’t know much about this particular game (how many voices it actually uses on real hardware) but if it uses 24 voices then the accurate way to emulate is to use the lower 25725 Hz sample rate. 

We do that degradation of the mixer rate depending on the number of active voices (channels) according to Gravis specs:

```cpp
		// Gravis' calculation to convert from number of active voices
		// to playback frame rate. Ref: UltraSound Lowlevel ToolKit
		// v2.22 (21 December 1994), pp. 3 of 113.
		frame_rate_hz = static_cast<int>(1000000.0 /
		                                 (1.619695497 * active_voices));
		ms_per_render = millis_in_second / frame_rate_hz;

		audio_channel->SetSampleRate(frame_rate_hz);
```

> DOSBox traditionally ignores this property of the GUS classic so that might be why it sounds like 44100 Hz. The only thing that might be off is the steepness of the anti aliasing filter. I know the GUSpnp uses a very aggressive filter but I have no good memory of what the filter of the GUS classic sounded like.

The reason for this difference between Staging vs SVN is actually something entirely different, @kcgen has found it already.
