### ISSUE TITLE
Zak McKracken Tandy composite mode has wrong aspect ratio

### ISSUE THREAD

**Issue by johnnovak** [dosbox-staging/dosbox-staging#2589]
<img width="1215" alt="image" src="https://github.com/dosbox-staging/dosbox-staging/assets/698770/b972ac09-c72c-4bb2-8907-b89858ec3caf">

**Comment by kcgen** [comment]
nice find, @johnnovak !

**Comment by johnnovak** [comment]
Two other things that are somewhat confusing:

- Switching between composite modes and composite on/off/auto also pauses the game. Maybe that's how the game is supposed to do things, I don't know, but it's a bit strange.
- Once you switch into composite mode, you cannot switch back into a proper Tandy mode. Maybe again it's some autodetection on the game's part?

In any case, these are low priority, I just wanted to mention.
