### ISSUE TITLE
Add a mode where joystick/gamepad input is read but not passed to the game

### ISSUE THREAD

**Issue by gapf2010** [dosbox-staging/dosbox-staging#2595]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### What Operating System are you using?

Windows 11

### Is your feature request related to a problem? Please describe.

I'm trying to configure wacky wheels to use my gamepad. I use mapper to map gamepad presses to keyboard presses, which works correctly for many games, however wacky wheels detects the gamepad (no way to disable it) and it detects the button presses incorrectly, I guess because they are seen as both: a keyboard press and a joystick press.

### Describe the solution you'd like

Add a mode where joystick/gamepad input is read by dosbox but the gamepad is not presented to the game running in dosbox. This would be useful to make the gamepad behave as a keyboard (map gamepad presses to keyboard presses) and it would avoid the game to detect the gamepad/joystick, which may make it behave strange (wacky wheels for instance).

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by kcgen** [comment]
See the `joysticktype = hidden`:

```ini
[joystick]
# joysticktype: Type of joystick to emulate:
#   auto:      Detect and use any joystick(s), if possible (default).
#   2axis:     Support up to two joysticks, each with 2 axis
#   4axis:     Support the first joystick only, as a 4-axis type.
#   4axis_2:   Support the second joystick only, as a 4-axis type.
#   fcs:       Emulate joystick as an original Thrustmaster FCS.
#   ch:        Emulate joystick as an original CH Flightstick.
#   hidden:    Prevent DOS from seeing the joystick(s), but enable them
#              for mapping.
#   disabled:  Fully disable joysticks: won't be polled, mapped,
#              or visible in DOS.
```

**Comment by kcgen** [comment]
> seems to be exactly what I'm looking for. Should this work on version 0.80.1?

Yes - but please, just try it. 

Closing, as it's still working as expected for 0.81.
