### ISSUE TITLE
Blood automap flickering

### ISSUE THREAD

**Issue by Burrito78** [dosbox-staging/dosbox-staging#2597]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Different version than latest?

0.81.0-alpha-884

### What Operating System are you using?

Mac OS

### Relevant hardware info

M2 mini

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

In Blood, the automap (simple or textured) flickers at different zoom levels. 
Happens in 0.74, 0.80.1, 0.81.0-alpha-884 and DOSBox-X to more or less degrees.

![Bildschirmaufnahme 2023-06-13 um 19 43 39](https://github.com/dosbox-staging/dosbox-staging/assets/61995128/b7133d07-0cca-471b-9071-807ee00cf3d9)

Repro pack:
[Archiv.zip](https://github.com/dosbox-staging/dosbox-staging/files/11737739/Archiv.zip)

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Use above repro pack 
2. Start a new game
3. Enter the automap using TAB.

### Your configuration

```ini
-noprimaryconf
```

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by Grounded0** [comment]
Interesting. I'm doing exactly what you are doing on Blood V1.21 and have no visual artifacts.

**Comment by Grounded0** [comment]
Automap issue becomes resolved when you let automap to populate with a larger map area. See if it resolves this issue for you.

**Comment by kcgen** [comment]
I also cannot repro. @Burrito78 ,just to confirm you're launching with `-noprimaryconf`?   I tried at mac cycles but it runs perfectly smooth at `cycles = 150000`, maybe that will help ?

**Comment by kcgen** [comment]
https://github.com/dosbox-staging/dosbox-staging/assets/1557255/10a4a0db-12da-4fa1-ac40-d73eb6c10b6e

**Comment by kcgen** [comment]
@Burrito78 , thanks I was able to reproduce it at `cycles = max`. This is the linear frame buffer issue that many build engine games have (although, this demo is a very early version. Like @Grounded0 suggested, if you can find a much later release, their drivers improved).

On real hardware (with fast processors > 800+ Mhz), they typically use a `nolfb.com` patch to use banked VESA modes.  Or they can craft custom univbe lines just for these games in specific modes: https://misterfpga.org/viewtopic.php?t=2780

In the case of DOSBox, `machine = vesa_nolfb` is the best solution.

I repacked your game with some small adjustments. This is a One line copy and paste into Linux, MSYS2, or macOS:

```shell
brew install wget zstd gzip gnu-tar

wget -q -O - https://github.com/dosbox-staging/dosbox-staging/files/11740853/blood-demo-nolfb-800x600.tar.zst.gz | gzip -dc | zstd -dcv | tar -x
```

It should run very smooth at a steady 60 fps on a typically desktop PC.

The mouse-look feature should feel very natural (with WASD controls).

**Comment by Burrito78** [comment]
Yes, using `vesa_nolfb` fixes the glitching even in this old build (heh) of the game.
Interestingly your choice for `cycles` leads to audio crackling at every resolution but `auto` works perfectly fine.

I've switched over to the ExoDOS version now, just wanted to test shareware version first.

**Comment by SergeVDev** [comment]
For those, who tried to fix the issue with the `machine = vesa_nolfb` trick unsuccessfully: download [NBlood](https://github.com/NBlood/NBlood), it works flawlessly. (It's a pack of executable files for modern OSes, so choose one for yours and copy it into the game folder).

**Comment by Grounded0** [comment]
I don't see this happening with 0.82.2. Seems to be working just fine with `machine = svga_s3`.

Configuration:
RAM: 31 MB (no 16-bit signed integer game bugs)
VRAM: 4 MB (triple buffering @ 800x600 with 256 colours)
350000 cycles
Blood 1.21 (One Unit Whole Blood binary)
BLOOD.CFG: `ScreenMode = 1` (VESA 2.0)
NoUNIVBE loaded by `AUTOEXEC.BAT` before running the game.
