### ISSUE TITLE
`CLS` command should not change the screen mode

### ISSUE THREAD

**Issue by johnnovak** [dosbox-staging/dosbox-staging#2598]
1. Start DOS Navigator .
2. Press Shift+F10 to switch into 80x50 column mode.
3. Exit DOS Navigator with Alt-X.
4. Issue the `CLS` command.
5. Note that the screen mode has been reverted to 80x25.

**Comment by Grounded0** [comment]
Doesn't happen with FreeDOS CLS so its a bug.

**Comment by johnnovak** [comment]
> I run 80x43 constantly with MODE.

I'm the same, although I switch to it in DOS Navigator. We should have a `MODE` utility that can also set the keyrepeat & delay. I use `TURBOKEY` for that purpose; can't stand the default slooooooow repeat delay since the 90s.

**Comment by dreamer** [comment]
Ugh, I think I had a fix for this behaviour on some old branch (IIRC current implementation reininitalizes the default mode while the proper fix is to use the "terminal window" shifting to effectively clean the screen.

**Comment by johnnovak** [comment]
> Ugh, I think I had a fix for this behaviour on some old branch, just need to find or reimplement it. IIRC current implementation reininitalizes the default mode while the proper fix is to use the "terminal window" shifting with width equal to width of screen and height equal to number of rows-1.

That seems the best way to go about it, indeed.

**Comment by johnnovak** [comment]
Any progress on this @dreamer ?

**Comment by kcgen** [comment]
Thanks for knocking this out, @weirddan455!
(Updated the assignment and project to be 0.81 just so it's part of the release summary.)
