### ISSUE TITLE
The default mouse driver only supports up to 80-column text modes

### ISSUE THREAD

**Issue by johnnovak** [dosbox-staging/dosbox-staging#2599]
When using the default mouse settings, the mouse pointer cannot be moved past the 80th column in 132-column VESA text modes.

However, if you load CuteMouse, you can use the full available area (you can move past the 80th column).

## Reproduction steps

All these steps assume stock settings.

1. Go to **Options / Configuration / System Setup** in DOS Navigator 1.51

<img width="990" alt="image" src="https://github.com/dosbox-staging/dosbox-staging/assets/698770/9bc6b97c-c8b7-4204-a62f-f26662a24091">

2. Set **Video Mode 2** to 266

<img width="986" alt="image" src="https://github.com/dosbox-staging/dosbox-staging/assets/698770/c2db5543-bfc1-4296-b3ba-bd21533e1c51">

3. Switch to **Custom video mode 2** either by using the menu option or by pressing **Ctrl+F10**

<img width="987" alt="image" src="https://github.com/dosbox-staging/dosbox-staging/assets/698770/c728fbca-2db4-49f2-a242-19b0dd67a735">

4. In 132-column mode, try to move the mouse pointer to the right edge of the screen. You won't be able to; you cannot move it past the 80th column. If you load CTMOUSE, however, then you can move it to the right edge of the screen.

<img width="1130" alt="image" src="https://github.com/dosbox-staging/dosbox-staging/assets/698770/b18ac560-a59f-4b4d-83e4-a413f91842f1">

**Comment by FeralChild64** [comment]
Most likely a problem within `‎MOUSEDOS_AfterNewVideoMode‎` function - I can see it reads video mode to `uint8_t`, and additionally has a hardcoded list of modes.

**Comment by johnnovak** [comment]
> Most likely a problem within `‎MOUSEDOS_AfterNewVideoMode‎` function - I can see it reads video mode to `uint8_t`, and additionally has a hardcoded list of modes.

Mind you, this is _very_ low priority, I just thought I'd report it for completeness. And probably it's an easy fix.
