### ISSUE TITLE
Double-scanning for sub-350 line VESA modes

### ISSUE THREAD

**Issue by johnnovak** [dosbox-staging/dosbox-staging#2604]
We've talked about this @kcgen, just creating this ticket so we don't forget. It's mainly needed by late DOS-era demos and should be quite easy to add. Typically they use 320x240 in some hi-colour mode or 400x300.

**Comment by kcgen** [comment]
I haven't been able to figure it out; the closest I can get is doubling the height, but not the width, so haven't pushed a PR yet.  Please poke around with it, and hope you have better luck.

**Comment by johnnovak** [comment]
Cool, I'll put it in my backlog of TODOs and have a look later if you haven't figured it out by then 😄

**Comment by johnnovak** [comment]
I'll tackle this @kcgen, as discussed, along with logging the "nominal" screen mode resolutions instead of the rendered image's dimensions.

**Comment by johnnovak** [comment]
The work has been completed on this.
