### ISSUE TITLE
Emulator crash after selecting 200-column text mode in Necromancer's DOS Navigator

### ISSUE THREAD

**Issue by FeralChild64** [dosbox-staging/dosbox-staging#2605]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Different version than latest?

0.81.0-alpha, GIT 7f4f4e48b3b1a8cb3a1fa8547c1f821f32cd943b (current main branch)

### What Operating System are you using?

Linux x86_64

### If Other OS, please describe

Gentoo, GCC 13.1.1 20230527

### Relevant hardware info

AMD64

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

DOSBox Staging crashes when selecting 200-column text mode in Necromancer's DOS Navigator. This is a regression - the problem does not happen in 0.80.1.

### Steps to reproduce the behaviour.

1. Start _Necromancer's DOS Navigator_ (I have version v3.00.0007v, DPMI32)
2. Select _"burger" menu_ -> _Video modes_ -> _Choose extended video mode..._ -> _Q200x25x8_ (but it crashes with other 200 column modes too)
3. DOSBox Staging crashes

### Download URL of affected game or software

http://ndn.muxe.com/download/file/ndn_3_00_0007_d32.zip

### Your configuration

```ini
[sdl]
fullscreen          = false
display             = 0
fullresolution      = desktop
windowresolution    = 1280x960
viewport_resolution = fit
window_position     = auto
window_decorations  = true
transparency        = 0
host_rate           = auto
vsync               = true
vsync_skip          = 7000
presentation_mode   = auto
output              = opengl
texture_renderer    = auto
waitonerror         = true
priority            = auto auto
mute_when_inactive  = false
pause_when_inactive = false
mapperfile          = mapper-sdl2-0.80.0-alpha.map
screensaver         = auto

[dosbox]
language                    = en
machine                     = svga_s3
captures                    = capture
memsize                     = 31
mcb_fault_strategy          = repair
vmemsize                    = 4
force_vga_single_scan       = false
dos_rate                    = default
vesa_modes                  = compatible
vga_8dot_font               = true
speed_mods                  = true
autoexec_section            = join
automount                   = true
startup_verbosity           = quiet
allow_write_protected_files = true

[render]
aspect             = true
integer_scaling    = off
monochrome_palette = green
cga_colors         = default
glshader           = 

[cpu]
core      = dynamic
cputype   = pentium_slow
cycles    = 100000
cycleup   = 1
cycledown = 1
```

### Provide a Log

```text
2023-06-15 16:37:20.158 | DISPLAY: Text 640x480 16-colour (mode 03h) at 67.433 Hz VFR, scaled to 1280x960 with 1:1 pixel aspect ratio
2023-06-15 16:37:27.053 | DISPLAY: Text 1600x400 16-colour (mode 03h) at 17.406 Hz VFR, scaled to 1280x879 with 1:2.75 pixel aspect ratio

Loguru caught a signal: SIGSEGV
```

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by Grounded0** [comment]
Looks like off spec:

https://en.wikipedia.org/wiki/VGA_text_mode#PC_common_text_modes

**Comment by kcgen** [comment]
They are really pushing the limits for mode 3h! (even gives the warning `'ON OWN RISK!!!'`)

**Comment by kcgen** [comment]
(Closed in referenced commit)

**Comment by FeralChild64** [comment]
@kcgen Shouldn't there be some protection against guest trying to set parameters over the emulator limit? We shouldn't crash in such case.

**Comment by kcgen** [comment]
Yes - in the width and height calculation, we should check the tweaked values against the limits before we go ahead with them. If they're out of bounds, we should exit with a message.

Opening and will PR that for review.

**Comment by FeralChild64** [comment]
If you are already digging into this code, would it be possible to raise some limits to make 200x64 mode work? Currently 200x60 is a maximum resolution which still works correctly.

**Comment by johnnovak** [comment]
@kcgen @FeralChild64 I think we should give a bit more generous extra limit, not just 30 pixels. There's no harm in doing so. Say increase max line length from 1600 to 2000.

**Comment by kcgen** [comment]
> @kcgen @FeralChild64 I think we should give a bit more generous extra limit, not just 30 pixels. There's no harm in doing so. Say increase max line length from 1600 to 2000.

These Q200 video modes warn that they are going out of bounds - and probably cause problems on real hardware. So I'd rather accommodate them to their fullest documented range (which is 30-extra pixels beyond 1600), despite seeing that the mode only writes an extra 9 pixels.

I agree we could dial it up to 1920 or 2000 - but there are minor costs:

![2023-06-17_17-08](https://github.com/dosbox-staging/dosbox-staging/assets/1557255/a141b7d1-625a-4d4d-9109-b25671826646)

And when we're already at "the end of the world" so to speak, I'd rather take a "prove me wrong" position, and wait to see if there anything out there that's actually going beyond 1600.

Do you know of anything?

When it comes to the edge of what the physical hardware could do - I am happy to exit and notify the user - and then we can realstically assess it.  For all we know, the game or demo is in a failing state (and might be passing in garbage values into the VGA registers).

**Comment by johnnovak** [comment]
Yeah fair enough. I'd personally just bump it up to 1700 (maybe 2000 would be a bit excessive), then if some weird program wants to create an 1632 pixel wide mode, it will just work.

But we're in extremely niche use case here, so yeah, whatever 😄 1630 is fine too 😄
