### ISSUE TITLE
Streaming Discord results in garbled mess

### ISSUE THREAD

**Issue by AlexMax** [dosbox-staging/dosbox-staging#2606]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### What Operating System are you using?

Windows 11

### Relevant hardware info

AMD Ryzen 7 5800X, Sapphire RX 5700 XT Pulse

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

100% of the time if I attempt to stream the game using Discord, the screen turns into incomprehensible garbage.  This is what it looks like - warning for folks who are sensitive to flashing.

https://github.com/dosbox-staging/dosbox-staging/assets/23563/fb4353f5-1224-4843-81e1-b9e56e29f011

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Launch DOSBox Staging
2. Start streaming the DOSBox window on Discord.
3. There is no step 3.

### Your configuration

```ini
https://gist.github.com/AlexMax/811fbb6324912744133d04abae33806c

I have tested both opengl and direct3d11 renderers.
```

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by johnnovak** [comment]
Dunno, a Discord problem perhaps?

**Comment by Burrito78** [comment]
And it works fine using DOSBox 0.74? Can you test this please?

**Comment by AlexMax** [comment]
@Burrito78 I can test 0.74 in a bit, but I did test DOSBox-X and can confirm it worked fine.

**Comment by Grounded0** [comment]
Do you have HiDPI display?

**Comment by kcgen** [comment]
try:

```ini
[sdl]
output = texture
```

**Comment by Burrito78** [comment]
@AlexMax if DOSBox-X works for you, you don't need to test 0.74 too. 

Can you test on another PC maybe?

**Comment by Burrito78** [comment]
Works for me on macOS using 0.80.1 and 0.81.0-alpha.

Do you see the garbled graphics on this screen already (locally)?

![Bildschirmfoto 2023-06-19 um 10 43 57](https://github.com/dosbox-staging/dosbox-staging/assets/61995128/a601063f-e195-4ad8-ad25-5b6d8ea23b8c)

**Comment by AlexMax** [comment]
@kcgen This appears to have fixed things.

**Comment by Grounded0** [comment]
@AlexMax It's a driver issue. Update your Adrenalin drivers for Windows. Greeting from fellow Radeon bro on macOS.

**Comment by anpage** [comment]
I'm on Windows 11 with an AMD GPU and I still have this problem on 0.80.1, but only with the OpenGL backend. Using another backend would be fine, except I'd like to stream to my friends with glshaders enabled.

**Comment by Grounded0** [comment]
We know we have tons of users using this on Windows 11 + AMD GPUs to lets see if this is a one off issue or something larger.

**Comment by Grounded0** [comment]
@anpage

Update your AMD Adrenalin drivers for Windows and lets see what happens.

**Comment by johnnovak** [comment]
Probably time to close this. It's a Discord problem, not a Staging problem.

**Comment by Grounded0** [comment]
Yeah bug reports to AMD and Discord about this. We can't help with host issues sadly.

**Comment by anpage** [comment]
For future reference, this does not happen with any other OpenGL software, including things like Minecraft and Half-Life. I'm also pretty sure this happens on upstream DOSBox as well. I am on the latest Windows updates, AMD driver, and Discord client and I've had this problem for a couple of years, at least.

I've found that one workaround is, in Discord:

1. Settings
2. Voice & Video
3. Disable `Use our advanced technology to capture your screen` (near the bottom, under `SCREEN SHARE`)

This makes DOSBox with OpenGL work, but it breaks streaming most other games for me.
