### ISSUE TITLE
autoexec commands are executed after a given program exits.

### ISSUE THREAD

**Issue by amano-kenji** [dosbox-staging/dosbox-staging#2607]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### What Operating System are you using?

Linux x86_64

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

autoexec commands are executed after a program given to dosbox command exits.

Thus, if I put mixer command in autoexec section, the audio volume is not changed in a program.

As far as I know, there is no other way to configure audio volume.

### Steps to reproduce the behaviour.

1. Put `mixer master 30 \noshow` in `[autoexec]` config section.
2. Execute `dosbox /path/to/program`
3. The master volume is not 30, but 100.

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by FeralChild64** [comment]
I can confirm. The problem is within the `src/shell/autoexec.cpp` - some `AddCommandBefore` calls should be changed to `AddCommandAfter`, also secure mode switch might need adaptations.
