### ISSUE TITLE
Refactor MIXER /LISTMIDI

### ISSUE THREAD

**Issue by johnnovak** [dosbox-staging/dosbox-staging#2617]
I know what to do, just a reminder so I won't forget...

Mockups by _yours truly_ we more or less agree on with @kcgen (incl. a few typos 🤦🏻 👀 )

![image](https://github.com/dosbox-staging/dosbox-staging/assets/698770/2cb5e4c5-d8a1-4748-9a8b-d22b89b1cf3c)

![image](https://github.com/dosbox-staging/dosbox-staging/assets/698770/a0052c91-81d4-4bcf-abb6-958ca7a39d9e)

**Comment by Burrito78** [comment]
The asterisk stands for "active", additionally to the green color?

**Comment by johnnovak** [comment]
> The asterisk stands for "active", additionally to the green color?

Yes. So it's consistent with marking the current SoundFont with an asterisk in addition the green colour. I think the asterisk is a good idea, especially for the monochrome Hercules mode (edge case, I know, but still...)

**Comment by Burrito78** [comment]
@johnnovak This is done, right?

**Comment by johnnovak** [comment]
> @johnnovak This is done, right?

Yep.
