### ISSUE TITLE
DOSBox sometimes writes command line history to current directory

### ISSUE THREAD

**Issue by FeralChild64** [dosbox-staging/dosbox-staging#2629]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Different version than latest?

current git main (172ba3322acf5a686e6daa1df4dbf4a0bc18a71d)

### What Operating System are you using?

Linux x86_64

### If Other OS, please describe

Gentoo

### Relevant hardware info

AMD64

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

When DOSBox Staging is started:
- either with `-noprimaryconf` switch
- or with configuration file not containing `command_history_file =` line

it stores the command line history file in the current directory.

This shouldn't happen - with various desktop environments the current directory can be anywhere (documents? desktop? home directory? temp? you don't really know), we shouldn't write there anything unless user explicitly requests.

### Steps to reproduce the behaviour.

(see description above)

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by kcgen** [comment]
Adding @weirddan455 :-)

**Comment by weirddan455** [comment]
Whoops yeah that’s a bug.  I’ll take a look.

**Comment by FeralChild64** [comment]
@weirddan455 There is one minor glitch: when `dosbox.conf` contains `command_history_file  =` without any parameter (empty value), upon closing the emulator I can see a warning severity log:

`SHELL: Unable to write command history to file: '(here is the path to my config directory)'`

**Comment by FeralChild64** [comment]
I'm reopening the issue, as I believe the solution implemented is not correct. The workaround implemented in `get_command_history_path` in `shell.cpp` should not be needed - `Prop_path::SetValue` already handles it.

Problem: if the user sets `file_name  = foobar.txt`, we will have a `Prop_path::SetValue("foobar.txt")` call executed. But if the configuration file does not contain `file_name  =` and all, and the default value of `file_name` is `default.txt`, the `Prop_path::SetValue("default.txt")` WILL NEVER BE EXECUTED!

This is actually a problem of our configuration handling code, and it will apply to various other values, like `phonebookfile` or `setver_table_file` if we introduce non-empty default value.

**Comment by weirddan455** [comment]
Yeah, I mentioned that in #2630.  I was going to be a separate issue in for that problem.

**Comment by FeralChild64** [comment]
@weirddan455 Most likely the proper solution is to call `SetValue(std::string(val));` in `Prop_path` constructor in `setup.h` - this way your workaround won't be needed.

It's getting late here and I had a busy day. I'll look at it in more detail tomorrow.

**Comment by weirddan455** [comment]
It's a little more complicated than that I believe.  There's a `current_config_dir` static global that gets set while the config file is getting parsed (and then cleared immediately after).  So that variable isn't available during construction time.

I think ideally, that variable should be done away with and replaced with a call to `get_platform_config_dir()` and also possibly change `Prop_path` to store a `std_fs::path` rather than a string.  But that's going to require a larger refactoring.

**Comment by weirddan455** [comment]
Erroneous warning message fixed in #2635 

Issue #2636 opened for future refactor work.

Closing this issue for now.
