### ISSUE TITLE
Refactor misc/setup.cpp Prop_path

### ISSUE THREAD

**Issue by weirddan455** [dosbox-staging/dosbox-staging#2636]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### What Operating System are you using?

Linux x86_64

### Is your feature request related to a problem? Please describe.

Prop_path has caused some previous issues.  See #2629 and #2630

The main issue being that if a user's config is missing an entry, `Prop_path::SetValue` never gets executed.  This function is supposed to set the variable `realpath` to an absolute path.  Instead, you can get left with just a filename.

### Describe the solution you'd like

`Prop_path::SetValue` is using a static global variable `current_config_dir` which gets set while the config file is being parsed and then cleared immediately after.  This means the function is unable to be called during construction time.

I think ideally, that global should be done away with and replaced with a call to `get_platform_config_dir()`.  This would let us set the `realpath` variable during construction of the object.

As an additional improvement, it may be worth looking to have `Prop_path` store a C++ 17 `std_fs::path` (alias for `std::filesystem::path`) rather than a string.

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by johnnovak** [comment]
The plan looks good @weirddan455; there are lots of globals unfortunately in the codebase with weird usage patterns, we are weeding them out slowly but steadily.

`std::filesystem` and `std_fs::path` is the way forward, we have migrated some parts of code to use them already, like in the new `capture.cpp` that I'm gonna merge in an hour.
