### ISSUE TITLE
Refactor DOS file attributes to use FatAttributeFlags

### ISSUE THREAD

**Issue by weirddan455** [dosbox-staging/dosbox-staging#2663]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### What Operating System are you using?

Linux x86_64

### Is your feature request related to a problem? Please describe.

There are these bit-fields defined here for DOS file attributes:  https://github.com/dosbox-staging/dosbox-staging/blob/d64ad72581e08e0c48b9dcc9d5da7703f03fb8b8/include/dos_system.h#L44-L75

The top one (marked obsolete) used plain old C style bitwise operations to make a bitfield.  It is still being used lots of places but we should probably start refactoring these to use the fancy new C++ bit_view API.

### Describe the solution you'd like

Grep for uses of the enum marked obsolete and replace them.  Or just delete them from the header file and check for compile errors.  Some of the functions that use these functions are a little cludgy so be warned.  `DOS_FindFirst` for example takes in a `uint16_t` while it should really be a `uint8_t` (or even better, refactor it to take in a `FatAttributeFlags` union directly.)

Similarly, `DOS_GetFileAttr` should probably return one of these instead (also currently returning a `uint16_t` for some reason).

There was some discussion about this in #2660

### Describe alternatives you've considered

Haven't considered alternatives but if anyone has any ideas to make these interfaces less cludgy, feel free to discuss.

### Add any other context or screenshots about the feature request here.

@johnnovak made the compiler very unhappy when he tried touching these things

https://user-images.githubusercontent.com/698770/251313955-2c4014e3-9da2-4a6a-bcb7-02fcd16d268e.png

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by johnnovak** [comment]
Thanks for raising @weirddan455 and including all relevant context! 🎉

**Comment by johnnovak** [comment]
Changed the label to "plumbing" @weirddan455 because we use "enhancement" for actual user-observable feature enhancements/improvements. Code-only improvements only get the unglamorous "plumbing" label. Hope that doesn't cause disappointment! 😆
