### ISSUE TITLE
Document how to mount a physical CD-ROM

### ISSUE THREAD

**Issue by weirddan455** [dosbox-staging/dosbox-staging#2664]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### What Operating System are you using?

Linux x86_64

### Is your feature request related to a problem? Please describe.

Because I can't figure it out.  I think other users might have problems too.  `mount -cd` lists my cd drive as `/dev/cdrom` which is good.  But then every other command I type either says `/dev/cdrom is not a directory` or it just prints the help page.

I even had a quick look at the code in `program_mount.cpp` but it's a bit hard to read what arguments are what.

And no, I'm not trying to mount the CD first.  That would work for data access but not for CD audio I believe (it would just be a normal directory mount).

### Describe the solution you'd like

An example of how to mount a physical cdrom in the `mount /?` page.

### Add any other context or screenshots about the feature request here.

![mount cd](https://github.com/dosbox-staging/dosbox-staging/assets/8128047/673fe92a-ec32-4972-9f32-b4d220503bfe)

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by weirddan455** [comment]
Well, it says "limited support" when I give it a mounted directory which I think is not ideal
![cd2](https://github.com/dosbox-staging/dosbox-staging/assets/8128047/bd6d1d34-60e8-46b0-8877-fec8b5a0de7c)

**Comment by Grounded0** [comment]
Could you rip your CD into a disc image and then use `IMGMOUNT´ to get CD redbook audio?

Not ideal but i don't think there's much demand for hardware level access for optical discs.

**Comment by johnnovak** [comment]
You use the `imgmount` command for mounting CD images. E.g.

```
imgmount D cd/bass.iso -t iso
```

You can try mounting it the way @Grounded0 suggested, I've never done it myself. I'm actually glad I don't need to deal with noisy CD drives, scratched discs, lasers getting out of alignment and faulty rubber bands anymore, so I just have my ISO & BIN/CUE collection 😄 

What would be nice to eventually teach the auto drive mounting mechanism to auto-mount CD images just by putting them into the "magic" drives folder. E.g. `drives/c` gets automounted as C drive if found in the startup folder. We'd need to extend this so it mounts any ISO or BIN/CUE files automatically too if just just shovel them into `drives/d` or something (we might even have a ticket for this already).

**Comment by weirddan455** [comment]
Yeah I’ve mounted bin/cue files before and they work fine and with audio.  But I just dug up this old Quake CD and thought it would be easier to use the real thing.  I found a giant PR where it looked like this was implemented (on my phone right now so don’t have a link handy, was from about a year ago)

**Comment by Grounded0** [comment]
Yeah and only BIN/CUE pairs or better include full rip with redbook CD audio. Not ISOs.

**Comment by Grounded0** [comment]
Yeah it would be nice if someone would implement block level access for POSIX operating systems like Linux and macOS.

**Comment by johnnovak** [comment]
> Yeah I’ve mounted bin/cue files before and they work fine and with audio. But I just dug up this old Quake CD and thought it would be easier to use the real thing. I found a giant PR where it looked like this was implemented (on my phone right now so don’t have a link handy, was from about a year ago)

Yeah for fun I can actually test physical CD support on Windows 10 and a Raspberry Pi4 later this week. On macOS too if my USB CD reader works with the Apple USB dongle thing 😄

**Comment by weirddan455** [comment]
Back at my computer.  The PR was #1540

There also exists a file src/dos/cdrom_ioctl_linux.cpp suggesting there *should* be some type of Linux support for this.  I may poke around at the code later to see if I can find what magic switches I need to use to get this to work.

**Comment by johnnovak** [comment]
> Back at my computer. The PR was #1540
> 
> There also exists a file src/dos/cdrom_ioctl_linux.cpp suggesting there _should_ be some type of Linux support for this. I may poke around at the code later to see if I can find what magic switches I need to use to get this to work.

Unlikely. See here: https://github.com/dosbox-staging/dosbox-staging/pull/1540#issuecomment-1041037373

Only the data parts of the physical CDs can be read with this feature, apparently, making CD Audio support when using physical CDs a Windows-only feature:

> The PR does not directly address the audio CD problem in Linux, but it does open the possibility of a future PR to implement the missing audio CD functions so that CD audio tracks will also be supported then (in addition to CD data tracks). Thanks for testing the code!

**Comment by weirddan455** [comment]
So I did some digging on this.  The SDL CD code we're using does have Linux audio support but it's done with the ioctl CDROMPLAYMSF.  That one is for using the old school CD audio analog cable that connects from your CD drive to your soundcard... which most people don't have anymore.

There's also no audio mixing support for CD audio.  SDL CD for Windows seems to be doing basically the same thing (issue this OS command that makes the CD start playing) except maybe on Windows, it can do it without the cable.  In any case, as far as I can tell, it's bypassing our entire audio stack on every platform.

Note, this doesn't apply to CD images.  Those do everything in software and feed the sound through our mixer.

Anyway, on Linux, there's another ioctl `CDROMREADAUDIO` that can just extract the audio from a given MSF or LBA that's actually pretty simple to use (I tested and got some sound back).  It's now a matter of feeding the sound into DosBox's mixer and I think I can make this work.

**Comment by johnnovak** [comment]
> Note, this doesn't apply to CD images. Those do everything in software and feed the sound through our mixer.

Yes, that's actually my preference; the only forward-looking way to handle Audio CD data is to only support CD images.
This whole physical CD support business is a bit of lost cause... I particularly don't like that the audio bypasses our mixer and the OS handles the CD Audio.

But, I guess if this doesn't complicate the software-only path and it's entirely opt-in, and you're willing to spend time on this, then why not 😄 Then it will become an extra feature that can be completely ignored. Just make it so that it can easily be dropped in the future it it becomes very unpractical to maintain it (because at some point no one will have working CD drives anymore).

**Comment by MasterO2** [comment]
Doesn't https://cdemu.sourceforge.io/ do this in Linux?

https://en.wikipedia.org/wiki/CDemu

**Comment by weirddan455** [comment]
>  This whole physical CD support business is a bit of a lost cause... I particularly don't like that the audio bypasses our mixer and the OS handles the CD Audio.

Yeah, so my plan is to have CD audio for Linux go through our normal mixer.  Linux is already on its own special path with `CDROM_Interface_Ioctl`.  That class is just missing audio functions.

@MasterO2  I've used CDemu.  That's for images.  I'm talking about support for a real physical CD drive.  Also (haven't tested) but I think CDemu audio would be broken in DosBox as well because it presents itself as a CD drive.  I haven't had much use for CDemu with regards to DosBox because DosBox can mount its own images.

**Comment by MasterO2** [comment]
> > This whole physical CD support business is a bit of a lost cause... I particularly don't like that the audio bypasses our mixer and the OS handles the CD Audio.
> 
> Yeah, so my plan is to have CD audio for Linux go through our normal mixer. Linux is already on its own special path with `CDROM_Interface_Ioctl`. That class is just missing audio functions.
> 
> @MasterO2 I've used CDemu. That's for images. I'm talking about support for a real physical CD drive. Also (haven't tested) but I think CDemu audio would be broken in DosBox as well because it presents itself as a CD drive. I haven't had much use for CDemu with regards to DosBox because DosBox can mount its own images.

I just realized that CDEmu is for images after I posted that, before anyone else says anything.  

Anyway, I'm kinda surprised that Staging doesn't support mounting physical CDs in Linux.

**Comment by weirddan455** [comment]
>  Anyway, I'm kinda surprised that Staging doesn't support mounting physical CDs in Linux.

It half-way does.  You have to mount the CD drive in Linux and then use the Linux mount point as if it were a normal directory for DosBox's mount.  Then you can add the `-t cdrom -usecd 0` to give Dosbox direct block-level access to the drive for games that need it.  But CD audio is broken for now.

**Comment by johnnovak** [comment]
> Yeah, so my plan is to have CD audio for Linux go through our normal mixer.

That would be great, looking forward to your implementation! 


> Linux is already on its own special path with `CDROM_Interface_Ioctl`. That class is just missing audio functions.
> And it's opt-in so to speak. As in, this only applies to real CDs. Images get handled separately.

All clear! 👍🏻

**Comment by Grounded0** [comment]
Red Book: Audio Recording Compact Disc Digital Audio System, IEC 60908, Second Edition, 1999 02 [ISBN 2 8318 4638 2]:

https://ia600700.us.archive.org/2/items/RedBookAudioRecordingCompactDiscDigitalAudioSystemIEC60908SecondEdition199902ISBN2831846382/Red%20Book%20-%20Audio%20Recording%20Compact%20Disc%20Digital%20Audio%20System%2C%20IEC%2060908%2C%20Second%20Edition%2C%201999-02%20%5BISBN%202-8318-4638-2%5D.pdf

**Comment by Grounded0** [comment]
Working Draft Project American National Standard Revision 5 October 28, 2013

Information technology -
ATA/ATAPI Command Set - 3 (ACS-3):

https://people.freebsd.org/~imp/asiabsdcon2015/works/d2161r5-ATAATAPI_Command_Set_-_3.pdf

**Comment by MasterO2** [comment]
[Vogons Thread: List of Old Games That Had CD Audio Tracks](https://www.vogons.org/viewtopic.php?p=673031#p673031)
