### ISSUE TITLE
MOVE must be an external command

### ISSUE THREAD

**Issue by NicknineTheEagle** [dosbox-staging/dosbox-staging#2666]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### What Operating System are you using?

None

### Is your feature request related to a problem? Please describe.

https://github.com/dosbox-staging/dosbox-staging/commit/98ae30850938d5b91dbeaa1cd52bdcfb7941a64d added MOVE command, however, it was implemented as an internal command which does not match MS-DOS 6.x where MOVE is an external command (move.exe). For reference, internal commands are commands built into command interpreter while external commands are standalone programs in PATH. This potentially poses a problem because:

1. Internal commands do not have return codes.
2. Internal commands cannot be called from other applications.

There was actually a real case where 2 caused an issue, there's a game that calls CHOICE which is bugged on Dosbox SVN because it implements CHOICE as an internal command, Staging has fixed that.

### Describe the solution you'd like

Re-implement MOVE as a Z: drive program.

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by weirddan455** [comment]
I wrote the MOVE command and yeah you're right, it is an external .exe file in MS-DOS 6.22.  @johnnovak @FeralChild64 Would it be enough to do like LS and CHOICE do and just call into the already written function?

https://github.com/dosbox-staging/dosbox-staging/blob/56a52cfceb1de0f5621228675789dd4b29653648/src/dos/program_ls.cpp#L28-L35

If so, I think I can knock this out pretty quickly.

**Comment by FeralChild64** [comment]
Given that we want to stabilize the code before releasing version 0.81, I think this would be a good idea for now. You could also do the same with `SUBST.EXE`.

@johnnovak?

**Comment by johnnovak** [comment]
> Given that we want to stabilize the code before releasing version 0.81, I think this would be a good idea for now. You could also do the same with `SUBST.EXE`.
> 
> @johnnovak?

Yes, agree with all that. Please do as the LS and CHOICE command @weirddan455, thanks.
