### ISSUE TITLE
The help of the `CONFIG` command needs improvement

### ISSUE THREAD

**Issue by johnnovak** [dosbox-staging/dosbox-staging#2669]
**UPDATE: This is just a documentation issue; the help message of the `CONFIG` command needs to be improved.**

---

As per the title; it's impossible to display the help text for the below settings with `config -h`:

- composite
- gus
- imfc
- reelmagic

You'll only get the list of settings in the section that has the same name, and that's it:

<img width="780" alt="image" src="https://github.com/dosbox-staging/dosbox-staging/assets/698770/bc2e6e51-78b0-416d-abf7-78349d602c30">

**Comment by rderooy** [comment]
Am I not understanding the issue properly? Seems to work correct here.
![image](https://github.com/dosbox-staging/dosbox-staging/assets/17701098/1efa5659-c521-41f2-b0c5-017ff94882f3)

The format is `<section> <key`. But you are allowed to skip the `<section>` part if the key is unique.

**Comment by rderooy** [comment]
The help for it could perhaps use some clarification.
![image](https://github.com/dosbox-staging/dosbox-staging/assets/17701098/da27efac-e1ae-4f9b-8d3a-33f8181bb18c)

**Comment by johnnovak** [comment]
> The format is `<section> <key>`. But you are allowed to skip the `<section>` part if the key is unique.

Thanks, it's a documentation issue then. Based on that help message, I tried `config -h gus / gus` but it didn't work. I'll update the help message then.

**Comment by rderooy** [comment]
the same `<section> <key>` principle, where `<section>` can be skipped in most cases also applies to `config -get` and `config -set`.

**Comment by johnnovak** [comment]
Addressed by #2672
