### ISSUE TITLE
Middle-click to release may register outside the DOSBox window

### ISSUE THREAD

**Issue by kcgen** [dosbox-staging/dosbox-staging#267]
To reproduce bug, use following settings:
```
[sdl]
fullscreen = true
capture_mouse = onstart middlerelease
```
Run some window maximised (for me it was the terminal emulator I used to start dosbox). Run dosbox, press Alt-Enter to leave fullscreen, middle-click to release the cursor. There's high chance, that click will register outside of dosbox window and WM will bring up background window instead. (problem does not happen with `seamless`, once I managed to reproduce it with `onclick`, but it's troublesome).

_Originally posted by @dreamer in https://github.com/dreamer/dosbox-staging/pull/250#issuecomment-606207504_

**Comment by dreamer** [comment]
I hoped we can maybe close this bug, as I haven't experienced it in a while… but nope - I just didn't experience it on my laptop.

I can't reproduce it on Gnome + X11, but it still happens on Gnome + Wayland (both XWayland and as native) :(

Easiest reproduction steps: start Norton Commander (or anything showing cursor), move cursor all the way to left or right border of the screen, Alt+Enter, middle-click.

**Comment by kcgen** [comment]
This seems to be either extremely rare of sufficiently inconsequential. 
Closing this for now - but if it becomes a problem, let's re-open it!
