### ISSUE TITLE
The default config should be created consistently

### ISSUE THREAD

**Issue by johnnovak** [dosbox-staging/dosbox-staging#2674]
To coerce DOSBox into writing the default `dosbox-staging.conf` config file into your config dir, you must start it in a directory that does _not_ contain a local `dosbox.conf` (or set the working dir to such a directory). That's the only way, see the below repro steps for details.

This is quite bad; in my view the default `dosbox-staging.conf` should _always_ be created if it doesn't exist, no exceptions.

This can easily to lead to a lot of confusion about the default config not being generated on the first startup, depending from which directory you start it.

---

#### Preconditions

- `dosbox-staging.conf` DOES NOT exist in config directory (e.g. `~/Library/Preferences/DOSBox`)
- Local `dosbox.conf` DOES exist in startup directory
- Start DOSBox normally without any arguments

#### Results

- `~/Library/Preferences/DOSBox/dosbox-staging.conf` containing the defaults DOES NOT get created
- `config -l` lists `dosbox.conf` (the local config) as the primary config file 

#### Preconditions

- `dosbox-staging.conf` DOES NOT exist in config directory (e.g. `~/Library/Preferences/DOSBox`)
- Local `dosbox.conf` config DOES NOT exist in startup directory
- Start DOSBox normally without any arguments

#### Results

- `~/Library/Preferences/DOSBox/dosbox-staging.conf` containing the defaults DOES get created
- `config -l` lists `~/Library/Preferences/DOSBox/dosbox-staging.conf` as the primary config file

**Comment by kcgen** [comment]
@johnnovak; I think this is working now, right?

**Comment by johnnovak** [comment]
> @johnnovak; I think this is working now, right?

Yes, added link to the PR.
