### ISSUE TITLE
Full Metal Planete does not start

### ISSUE THREAD

**Issue by LowLevelMahn** [dosbox-staging/dosbox-staging#2684]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Different version than latest?

git

### What Operating System are you using?

Windows 10

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

i try to start Full Metal Planete from this "orginal" Floppy image: https://archive.org/details/001938-FullMetalPlanete

Dosbox Staging Debug build just hangs in the "Loading..." screen

Dosbox SVN Debug build shows "unhandled Interrupt E and disk 127 access"

![image](https://github.com/dosbox-staging/dosbox-staging/assets/580819/9401b461-7210-4263-bc0b-ad60af41821f)

according to RBIL it interrupt 5 seems to be some disk controller stuff - maybe not supported?
https://github.com/cirosantilli/ralf-brown-interrupt-list/blob/fde1a5ac1b7e8a45ff4255ee275ee77c7fe7e256/inter61a/INTERRUP.A#L960

any idea?

### Steps to reproduce the behaviour.

using a vanilla config

1. get the archive: https://archive.org/details/001938-FullMetalPlanete
2. start tatou.com, select F2 -> F2 -> EGA -> start game with F1

Dosbox Staging does not output anything suspicous in the Logs

### Download URL of affected game or software

https://archive.org/details/001938-FullMetalPlanete

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by johnnovak** [comment]
So does this game work in any DOSBox fork or 86box /PCem @LowLevelMahn ? Could it be a bad dump or crack? Can you verify?

**Comment by LowLevelMahn** [comment]
im using a floppy image from Archive.org - dosbox svn does not work also - i've got a version from an abandonware page that works - so it could be a bad image or a image with some sort of crack

**Comment by johnnovak** [comment]
Thanks for confirming @LowLevelMahn. Yes, it's best to cross-check in such cases.
