### ISSUE TITLE
Changing some configuration options at runtime disables joysticks

### ISSUE THREAD

**Issue by JKingweb** [dosbox-staging/dosbox-staging#2687]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### What Operating System are you using?

Linux x86_64

### If Other OS, please describe

Also affects macOS ARM

### Relevant hardware info

Thrustmaster T.Flight Stick X and VKB Gladiator NXT Evo are both affected

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

If certain configuration parameters are changed using `config -set`, joysticks stop responding in DOS. They still function in the keymapper, but neither axes nor buttons respond in DOS programs. The `joytest` utility I found [on VOGONS](https://www.vogons.org/viewtopic.php?p=187168#p187168) exhibits the problem, as do multiple games I tried.

The `sdl mapperfile` configuration parameter is a simple one to test, but I believe changing any parameters under `sdl` will cause the problem.

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Run joytest utility; confirm it works
2. Execute `config -set sdl mapperfile=test.map`
3. Run joytest utility again; confirm it does not work

### Your configuration

```ini
[sdl]
fullscreen = true
```

### Provide a Log

```text
https://gist.github.com/JKingweb/5ee19fc724a4ba9fca9c7d5afef076a6
```

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by johnnovak** [comment]
Thanks for the well-written report @JKingweb ! That JOYTEST util is a nice find! 🎉 Hopefully this is something trivial to fix.

**Comment by JKingweb** [comment]
That was a quick turnaround! Thank you both.
