### ISSUE TITLE
config -set sdl mapperfile requires full path

### ISSUE THREAD

**Issue by weirddan455** [dosbox-staging/dosbox-staging#2695]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### What Operating System are you using?

Linux x86_64

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Changing the mapperfile using `config -set sdl mapperfile=mymap.map` does not work.  It instead requires typing out the entire path.  ex.  `config -set sdl mapperfile=~/.config/dosbox/mymap.map`

This is in contrast to setting the mapperfile in the config file, where it automatically prepends the config directory `~/.config/dosbox`.

I believe this is going to be related to some refactoring work that needs to be done in #2636

### Steps to reproduce the behaviour.

Explain how to reproduce
1.   `dosbox -startmapper` + click "Save" to create a mapperfile
2.   Rename the mapper file to test.map
3.   `config -set sdl mapperfile=test.map`
4.    It fails to load.

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by johnnovak** [comment]
> This is in contrast to setting the mapperfile in the config file, where it automatically prepends the config directory ~/.config/dosbox

That's not my experience with current `main`, at least not on macOS here (and it this works differently between platforms, that's bad).

E.g. if my local `dosbox.conf` has:

```ini
[sdl]
mapperfile = mapper-test.map
```

And start DOSBox from that directory with `-noprimaryconf`, then `mapper-test.map` gets resolved from the local start directory correctly:

```log
2023-07-26 09:29:20.332 | MAPPER: Loaded 152 key bindings from '/Users/jnovak/Documents/DOS/DOS Navigator/mapper-test.map'
```

**Comment by weirddan455** [comment]
I've never launched DOSBox like that but I just tested and that is also the behavior on Linux.

So to  be more accurate, if the mapperfile is specified on a config file, it prepends the directory that config file is located in unless it is already an absolute path.

The bug is that this is not consistent with the config command changing mapperfile at runtime.  In main, it only looks in current directory.  In my PR, it only looks in the default config path (Which maybe needs to change if we want it to look in current directory?  I hadn't thought of that use case.)

**Comment by johnnovak** [comment]
> I've never launched DOSBox like that but I just tested and that is also the behavior on Linux.

Thanks for confirming.

> So to be more accurate, if the mapperfile is specified on a config file, it prepends the directory that config file is located in unless it is already an absolute path.
> 
> The bug is that this is not consistent with the config command changing mapperfile at runtime. In main, it only looks in current directory. In my PR, it only looks in the default config path (Which maybe needs to change if we want it to look in current directory? I hadn't thought of that use case.)

I think it's a bit more subtle (and more confusing) than that; I'll raise a detailed repro case on your PR shortly.
