### ISSUE TITLE
Gravis Ultrasound sound effects fuzzy/crackly in DUKE3D when set to 44kHz 

### ISSUE THREAD

**Issue by x73rmin8r** [dosbox-staging/dosbox-staging#2696]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Different version than latest?

dosbox-staging-v0.81.0-alpha-1149-g09ee

### What Operating System are you using?

Windows 10

### Relevant hardware info

i5-4590/r9 290, i7-8650u/UHDgraphics620

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Sound effects exhibit significant distortion in DUKE3D when the game setup options are set to use the GUS at 44kHz. 22kHz and below sounds normal. GUS music sounds correct.

The current release version of DosBox-Staging exhibits similar distortions in several additional games (A Final Unity, Heretic, Doom) at any sample rate setting, but they all sound correct in the latest Dev build, so the latest patches must have fixed them.

The latest release build of DOSBox-X using the original GUS implementation isn't exhibiting the distortion at 44kHz.

[DUKE3D-44kHz-GUS.zip](https://github.com/dosbox-staging/dosbox-staging/files/12135197/DUKE3D-44kHz-GUS.zip)

### Steps to reproduce the behaviour.

Explain how to reproduce
1. with fresh config file using known working mounted C:\ with \ULTRASND\ and \DUKE3D\ directory, disable sound blaster (this actually didn't seem to affect it, just removing a variable) and enable GUS
2.  set sound device in duke3d setup to GUS, 44kHz mixing rate, disable music to hear SFX more clearly (number of voices doesn't seem to affect it, music sounds correct either way when enabled)
3. start duke3d, the initial radiation logo animation and main menu demo will show obvious sound distortion

### Download URL of affected game or software

Atomic Edition of DUKE3D from GOG

### Your configuration

```ini
https://gist.github.com/x73rmin8r/36c2d6569e31d5df5f617231c7d7c275
```

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by johnnovak** [comment]
Regression was introduced in this commit when kcgen in addition what is described in the commit message also switched to a different rendering method (also employed in the MT-32 and FluidSynth code, and more recent audio devices):


```
commit cb62d971e4d748495ce2d4579d3fadf730eaa08a
Author: kcgen <kcgen@users.noreply.github.com>
Date:   Thu Jun 23 02:25:43 2022 -0700

    Remove the SoftLimiter and related buffers from GUS

    The float samples that previously where processed by the
    SoftLimiter and converted to int16_t are now passed through
    as float using the mixer's new AddSamples_sfloat() interface.
```

**Comment by kcgen** [comment]
@x73rmin8r , when you have a chance, can you test the builds here:

https://github.com/dosbox-staging/dosbox-staging/actions/runs/5633300521

(scroll to the bottom, there's a setup exe and zip package, which ever you prefer)
