### ISSUE TITLE
Linux Feature description

### ISSUE THREAD

**Issue by rderooy** [dosbox-staging/dosbox-staging#2717]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Different version than latest?

devel

### What Operating System are you using?

Linux x86_64

### Whats your question and how can we help?

The `contrib/linux/dosbox-staging.metainfo.xml` file should be updated before the next release to reflect the current state of the project. I thought to simply add voodoo and reelmagic, but there are probably various other parts that should be updated, such as the video outputs.

So I thought lets ask the question, what should be added/removed.

For those that don't know, this file is used by the graphical software installer used on most modern Linux distributions, and also used by [flatpak](https://flathub.org/apps/io.github.dosbox-staging)

The specification for the file format can be found here: https://www.freedesktop.org/software/appstream/docs/

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by johnnovak** [comment]
I would honestly recommend even scaling back the current description and keep it high level, without going much into detailed feature descriptions. Then put this sentence at the end:

"For the full list of supported features, please visit the DOSBox Staging website /insert link/"

That removes the burden of having to update this after each release, plus you surely don't want to list all features here. So it removes the constant thinking too about what to include here. The front page highlights much better serve this need, and when the manual is up, they will link to relevant manual sections, inviting curious users to learn more about these features.

Also, thus description needs an overhaul, there's some strange wording in there. "DOS-like console", huh? Just copy bits of text from the website, everything is well-worded there.

**Comment by johnnovak** [comment]
> DOSBox Staging is a modern continuation of DOSBox with advanced features and current development practices.
>
> It is meant as a (mostly) drop-in replacement for older DOSBox versions—your existing configurations will continue to work, but you will have access to many advanced features.
>
> For the full list of supported features, please visit the DOSBox Staging website at https://dosbox-staging.github.io/

Works for me 😎
