### ISSUE TITLE
PCI BIOS does not check parameters and does not set error/status code on exit

### ISSUE THREAD

**Issue by FeralChild64** [dosbox-staging/dosbox-staging#2727]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### What Operating System are you using?

None

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

PCI BIOS does not check parameters and does not set error/status code on exit. Example:

Interrupt 0x1a function 0xb109 (read configuration word) is implemented like this:

```c
IO_WriteD(0xcf8,0x80000000|(reg_bx<<8)|(reg_di&0xfc));
reg_cx=IO_ReadW(0xcfc+(reg_di&2));
CALLBACK_SCF(false);
```

and that's it. But according to PCI BIOS specification v2.1 (attached: [pci_bios_21.pdf](https://github.com/dosbox-staging/dosbox-staging/files/12264271/pci_bios_21.pdf) - see page 18, chapter 4.3.2) it should only accept register numbers being a multiple of two (check is missing), and AH should be set to return value SUCCESSFUL or BAD_REGISTER_NUMBER (setting AH is also missing).

----

We need to review and fix the PCI BIOS implementation - who knows what failures the current implementation will cause.

### Steps to reproduce the behaviour.

Problem discovered during attempted implementation of the VirtualBox mouse protocol.

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by johnnovak** [comment]
To your knowledge, what other areas of DOS emulation would benefit from this? If we started supporting Win95/98, I assume better PCI emulation would be more important?

**Comment by FeralChild64** [comment]
@johnnovak It's hard to tell without the source code. It might get more important if we start emulating more PCI cards.
