### ISSUE TITLE
Improvements to resizable window support

### ISSUE THREAD

**Issue by dreamer** [dosbox-staging/dosbox-staging#274]
This feature is partially-implemented, and can be tested on branch: `po/resizable-window-4`.

Works only with:
```
[sdl]
output = opengl
```
and works correctly only on Linux (it can be tested on Windows and macOS, but the window will show graphical artifacts during resize).

The roadblock from continued work on this is: this feature requires SDL 2.0.5 (it can be implemented with 2.0.2, but it will be buggy). Our release builds use SDL 2.0.4, as this is the newest one available on Ubuntu 16.04 LTS (to be retired in April 2021).

We can't drop support for 16.04 completely (we use it as a testing ground for Steam compatibility), but we can upgrade our release snapshots to 18.04 (at the cost of losing some Linux users).

Even when implemented, it will be available only as "experimental" feature, as window resizing is not compatible with:
- `output=surface`
- `output=texture*`
- shaders (except `glshader=sharp` and maybe `pixellate`)
- `windowresolution=*`

**Comment by dreamer** [comment]
Base functionality is now merged to master branch. I am leaving this issue open for next round of improvements:

- resizable window with output=texture
- resizable window with output=texturepp
- fixing of any corner cases we'll find
- improvements to main dosbox rendering loop to make the feature turned on by default on Windows

But majority of this work will happen for 0.7**6**.0 release, I am taking it out of 0.75.0 and moving to Backlog.

**Comment by kcgen** [comment]
> The roadblock from continued work on this is: this feature requires SDL 2.0.5 (it can be implemented with 2.0.2, but it will be buggy). Our release builds use SDL 2.0.4, as this is the newest one available on Ubuntu 16.04 LTS (to be retired in April 2021).

Good news @dreamer !

With 16.04 EOL and Staging [now requiring SDL 2.0.5 or newer](https://github.com/dosbox-staging/dosbox-staging/pull/1096/commits/16f5aa99a0b983dd4cb28fad517d848a2e7e5042), these roadblocks are gone.

**Comment by kcgen** [comment]
Thanks for the report @crocket. 

Mainstream-Wayland (and now decorations w/ Wayland) are all relatively news and still undergoing support and bug fixes in SDL.

I would suggest running the latest from-source build of SDL 2, if you can.

Given the freezing when resizing it attempted, I guess we should detect when Wayland is being used and disable resizing for the time being.

**Comment by kcgen** [comment]
The resizable window properly works with OpenGL on all supported platforms, including Wayland and X11 on Linux. 

Closing this because we're in a "good enough" state now, and adding more handling for texture and surface outputs will drive even more complexity into SDL main, which is not desirable.
