### ISSUE TITLE
Copy-protected disk image support

### ISSUE THREAD

**Issue by Flyers80** [dosbox-staging/dosbox-staging#2752]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### What Operating System are you using?

Windows 11

### Is your feature request related to a problem? Please describe.

All copy protected images on disk do not work.

### Describe the solution you'd like

It would be possible to insert the HFE (Rev 3) format used by gotek, it works with most copy protected discs, it is easily created with Greaseweazle and the HXC Emulator software.

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by MasterO2** [comment]
There's a similar issue for copy-protected floppy disk support as well: https://github.com/dosbox-staging/dosbox-staging/issues/2224

**Comment by johnnovak** [comment]
> There's a similar issue for copy-protected floppy disk support as well: #2224

Yes, duplicate, closing.

**Comment by kcgen** [comment]
For those who landed on this via web search or GitHub search - see the implementation-related ticket: https://github.com/dosbox-staging/dosbox-staging/issues/2826 and help if you can!
