### ISSUE TITLE
Dosbox-Staging quit with atexit when I launch a game

### ISSUE THREAD

**Issue by V4lou** [dosbox-staging/dosbox-staging#2761]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### What Operating System are you using?

Linux x86_64

### Whats your question and how can we help?

Hello everyone.

I use the Dosbox-Staging for Linux (portable version) to create a portable TES:Daggerfall game.

I am under Linux Mint 21.1.

I have create a specific configuration file to launch the game.

When I submit the command _./dosbox -conf dosbox-staging.conf_, Dosbox-Staging starts, display the introduction text I have set in the configuration file, then, I press a key to continue. 
DOS DOS32/A Extender starts in Dosbox-Staging, but immediately Dosbox-Staging quit with atexit.
I have not issue in my terminal.

Do you have a tips to fix this problem ?

My config file:

[https://pastebin.com/HeQRctEB](https://pastebin.com/HeQRctEB)

Thanks a lot for your responses.

Cordially. 

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by weirddan455** [comment]
Remove that last line `Exit` at the very bottom of the config file under `[autoexec]`

Probably something is failing to mount but you can't see the error message because you're automatically exiting.
