### ISSUE TITLE
Pressing Intro button in Settlers II menu quits game to DOS command prompt

### ISSUE THREAD

**Issue by FeralChild64** [dosbox-staging/dosbox-staging#2762]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Different version than latest?

0.80.1, current GIT b1bf242d3333ae9492a3cac5573a0b8988f04f0c

### What Operating System are you using?

Linux x86_64

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Pressing Intro button in Settlers II menu quits game to DOS command line, without any error displayed in the DOS console or in the output log, even if using a debug build. 

This problem seems to be inherited from the original DOSBox - it is also present in my game installation from GOG (ticket [#1215223](https://support.gog.com/hc/requests/1215223) submitted to GOG almost 2 years ago), current DOSBox-X (GIT) suffers from the same issue.

### Steps to reproduce the behaviour.

1. Start Settlers II game (I have checked with original version 1.02 or Settlers II Gold 1.51 GOG release)
2. On the main menu press Intro button

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by kcgen** [comment]
eXoDOS v6's Settler's II is working OK:

https://github.com/dosbox-staging/dosbox-staging/assets/1557255/41b74d53-2752-4f8c-a9dc-ef732c65ee4d

Hopefully the GOG team will eventually fix their package?
