### ISSUE TITLE
Backlog Done column has many Rejected items

### ISSUE THREAD

**Issue by Torinde** [dosbox-staging/dosbox-staging#2782]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Different version than latest?

Backlog

### What Operating System are you using?

None

### Whats your question and how can we help?

At https://github.com/dosbox-staging/dosbox-staging/projects/3 there are a lot of items in column "Done" that look as if they're actually rejected?

Adding to the confusion it seems Issues nominally have three statuses: green/open, gray/not planned, pink/completed, but if you read the comments inside it's actually gray/low priority or pink/not completed and low priority.

Backlog has a "Low priority bugs" column, maybe that can be changed to "Low priority" (bugs and features) or a "Low priority features" column can be added?

![image](https://github.com/dosbox-staging/dosbox-staging/assets/97228894/a61a5310-0d68-46a2-8935-5afe6191a6e2)

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by johnnovak** [comment]
Embrace the chaos @Torinde 😎 🤘🏻 

Seriously, I'm not that fussed about this exact categorisation in the backlog—we can find our ways around it. It's there for us devs to keep track of things, to help us. I really don't wanna turn this in to a high-maintenance thing, I'm ok with the current slightly loose approach.

However, I've moved over a bunch of tickets from the Done column into Rejected (although it's fuzzy when does something become Rejected instead of just Done in the sense that we're "done discussing it" 😄... and frankly, I don't care about the distinction.)

**Comment by Torinde** [comment]
OK, clear.
I wish you time and stamina to go through many of the remaining items :)

Is there a different priority between the three "projects"? I would assume eXoDOS or ECE is highest priority and then Backlog is lowest? Or it's more or less random, based on developers interests?

**Comment by Torinde** [comment]
If you organize a DOS teambuilding event at work (competition, multiplayer or just playing) will that count as both structured and spontaneous?

ECE: I see only one pending item https://github.com/dosbox-staging/dosbox-staging/commit/d88f6db3b9193d276756b01703c6e9822e8646e5 (mapping keys to mouse buttons)

Clearing up tickets: I don't think I should make decisions for you guys (e.g. prioritizing)... I already voice my preferences here and there :)
But if you think that's useful - I can go through all items in Done/Rejected, read the comments inside and depending on that:
- do nothing
- move from Done to Rejected
- move from Rejected to Done
- move to Low priority features

**Comment by johnnovak** [comment]
> If you organize a DOS teambuilding event at work (competition, multiplayer or just playing) will that count as both structured and spontaneous?

Not enough DOS gamers at work for that 😄 

> Clearing up tickets: I don't think I should make decisions for you guys (e.g. prioritizing)... I already voice my preferences here and there :) But if you think that's useful - I can go through all items in Done/Rejected, read the comments inside and depending on that:

Yeah, on a second thought it's best if we did it ourselves, I agree. It was just an idea 😄
