### ISSUE TITLE
MSYS2 Windows Build with GCC is very slow

### ISSUE THREAD

**Issue by weirddan455** [dosbox-staging/dosbox-staging#2790]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### What Operating System are you using?

Windows 10

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Performance is so bad it's unplayable in a Windows MSYS2 GCC build.  Clang is fine.  I don't know why.  Reproduced on `main` so it's not my ffmpeg PR.  Maybe I'm missing some important package or something.  I'll investigate later but I'll put this ticket in in case anyone else can reproduce.

Should note this affects debug and release builds.  It's not just a slight FPS drop either.  It runs Doom like a slideshow.  It even hangs on a black screen for 5-10 seconds before showing the title screen.

Task Manager shows a constant 25% CPU (which is a full core of my quad core CPU).  I think something is stalling the main thread.

MSVC builds are also fine on my system.  Only affecting GCC for some reason.

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Install MSYS 2.
2. Load the MSYS2 MinGW64 shortcut
3. Compile through Meson and run
4. Start a game (tested with Doom, gave up on Quake and Duke3D as they took too long to load).
5. Very slow 😢 

Compiling with the MSYS2 Clang64 shortcut to get the Clang compiler runs fine.

### Your configuration

```ini
I deleted the conf folder and tested with a default config.
```

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by johnnovak** [comment]
Wait, does this happen only when you compile it yourself? Is that MSYS2 build from CI ok? Can you please compare @weirddan455 ?

**Comment by weirddan455** [comment]
@johnnovak  I tried the one from https://github.com/dosbox-staging/dosbox-staging/actions/runs/5973299720 labeled MSYS2 and it runs fine.  I don't know if that build comes from GCC or Clang though, it doesn't say.

**Comment by johnnovak** [comment]
> @johnnovak I tried the one from https://github.com/dosbox-staging/dosbox-staging/actions/runs/5973299720 labeled MSYS2 and it runs fine. I don't know if that build comes from GCC or Clang though, it doesn't say.

Riiiight, now I got it. Maybe we're only shipping clang builds (would make sense, to be honest). Probably the GCC build is only there for catching weird GCC issues, to make our codebase more robust. @shermp could offer some insights, perhaps.

**Comment by shermp** [comment]
I have reproduced this problem.

The issue appears to be the auto cycler. Setting `cycles` to a fixed value works fine, but if `cycles = max`, performance falls off a cliff.

**Comment by shermp** [comment]
The issue also manifests in the `ucrt64` environment, which is also GCC. So therefore it looks like it's a Windows GCC issue, and not related to the C runtime.

**Comment by shermp** [comment]
Ok, after a bit of a slog, I bisected it to commit 1eadb1c62ae8196dc377ab43d861ca8ac916ff40

Also, see https://github.com/dosbox-staging/dosbox-staging/pull/2655

@kklobe any ideas on why MSYS2 GCC might be having troubles?

**Comment by johnnovak** [comment]
> Ok, after a bit of a slog, I bisected it to commit [1eadb1c](https://github.com/dosbox-staging/dosbox-staging/commit/1eadb1c62ae8196dc377ab43d861ca8ac916ff40)
> 
> Also, see #2655
> 
> @kklobe any ideas on why MSYS2 GCC might be having troubles?

Maybe #ifdef out for GCC, or GCC + WIndows.

**Comment by weirddan455** [comment]
GCC on Linux is completely fine for me.  I think this only affects GCC on Windows.

**Comment by shermp** [comment]
Hmm, https://github.com/msys2/MINGW-packages/issues/5086 might be relevant?

**Comment by shermp** [comment]
> Hmm, [msys2/MINGW-packages#5086](https://github.com/msys2/MINGW-packages/issues/5086) might be relevant?

Maybe not, looks like staging is already using `std::chrono::steady_clock`

**Comment by weirddan455** [comment]
OK so I dug pretty deep and found the root cause of this bug although I'm still not sure of the best solution.  If you look inside GCC's headers where `std::this_thread::sleep_for` it calls `nanosleep`.

This is a POSIX function that lets you sleep with nanosecond precision and works great on Linux.  It sucks on Windows (and is not even available on MSVC, this is an MSYS2 function).  If you tell it to sleep for 100 microseconds, it returns almost immediately (0 to 1 microseconds later).  This is bugged behavior by the way, it's supposed to always sleep for _at least_ as long as you tell it, if not longer.  If you tell it to sleep for 1 millisecond, it sleeps anywhere between 3 and 15 milliseconds.

`nanosleep` behaves the same way in Clang (and you get the same bad performance if you call that instead) but Clang's implementation of `std::this_thread::sleep_for` doesn't call it.  It calls some internal `sleep_for` function.  However, it still can't sleep for such a low amount of time.  It sleeps between 1 and 2 milliseconds.  MSVC behaves about the same as Clang.  It calls some undcoumented `_Thrd_sleep` function and sleeps between 1 and 2 milliseconds.

From what I've read Windows just can't really sleep for less than a millisecond no matter how you try.

OK, so let's forget about sleeping for a moment (and maybe ask why _not sleeping_ would make performance bad).  The only reason we're sleeping is to save CPU cycles.  So, I swapped out the sleep for a busy wait.  Let's busy wait for 100 microseconds.  Laggy as hell.  OK, let's busy wait for 1 millisecond.  A lot better but still a bit choppy.  Busy wait for 2 milliseconds and performance is just about perfect.

So we're looking at two things.  Unreliable sleep functions on Windows and a weird ass function that causes bad performance if you don't wait long enough.  I haven't delved into the reasons for the latter as I think that's all I've got in me for today.

**Comment by johnnovak** [comment]
> From what I've read Windows just can't really sleep for less than a millisecond no matter how you try.

Yeah, you can, but it gets complicated:
https://randomascii.wordpress.com/2020/10/04/windows-timer-resolution-the-great-rule-change/

> I suspect that Linux and Mac are also sleeping for quite a bit longer than 100 microseconds (Which is how these sleep functions work, they're supposed to guarantee to sleep for at least the requested time. There is no defined max they can sleep). If they were only sleeping for 100 microseconds, I would expect them to have bad performance as well. I'll double check behavior on Linux tomorrow.

I wouldn't be surprised it that's the case. For timing critical work it's always the good old busy-wait that does the job.

**Comment by kklobe** [comment]
As mentioned in #2655, on my M1 Mac it sleeps for about 15% longer that requested:

```
2023-08-26 07:34:23.093 | time slept = 122us
2023-08-26 07:34:23.093 | time slept = 118us
2023-08-26 07:34:23.093 | time slept = 118us
2023-08-26 07:34:23.093 | time slept = 118us
2023-08-26 07:34:23.094 | time slept = 117us
2023-08-26 07:34:23.094 | time slept = 118us
2023-08-26 07:34:23.094 | time slept = 117us
```

That was also why I pointed out the new aggressive delay of 100ns to keep an eye on it.

However it's strange that by going to a busy wait you're still seeing choppiness. I've experimented with busy waits on my own builds for a couple years now, and that always works perfectly, especially using the old time of 1ms. I wonder if something else is busted inside the MSYS2 machinery, like it's not accurately measuring the time slept? Maybe throw some logging statements in for `timeSlept` and `cumulativeTimeSlept`.

I also really haven't seen any non-microscopic real benefit to the changes in that PR, so that's something that could be easily reverted.

**Comment by kklobe** [comment]
P.S. if you change the

```cpp
constexpr auto sleepDuration = std::chrono::microseconds(100);
```

back to 1ms:

```cpp
constexpr auto sleepDuration = std::chrono::microseconds(1000);
```

it should work exactly as it used to before that commit, otherwise something is going horribly wrong in the new fractional tick measurement and calculation:

```cpp
		if (cumulativeTimeSlept >= 1000) {
			const auto cumulativeTicksSlept = cumulativeTimeSlept / 1000;
			ticksDone -= cumulativeTicksSlept;
			cumulativeTimeSlept %= 1000;
		}
```

**Comment by weirddan455** [comment]
My assumption was wrong.  On Linux (x86_64, same computer as I tested with in Windows), it sleeps for about 150 microseconds average and it works fine.

Commenting out the sleep statement reproduces the bad performance on all tested platforms (so "sleeping" for 0, same behavior as GCC + Windows with the 100 microsecond sleep because that just returns immediately).

Also, the busy wait is fine on all platforms.  I even tried busy waiting for a little as 1 microsecond and that fixed performance _if you don't write a log statement_.  For reasons unknown, GCC + Windows chokes with`LOG_MSG("Slept for %lld", timeslept);` right outside the busy wait to log the time.  That same log statement is completely fine on Clang and MSVC on WIndows as well as on Linux.  That really threw me off and I don't understand why it happens.

Lastly, as you said, changing the sleep time from 100 microseconds to 1 millisecond also fixes the problem.  This is a long enough wait for GCC + Windows to actually go to sleep (though it ends up sleeping for 3-15ms like I said above).

**Comment by weirddan455** [comment]
And just to be completely specific, this is exactly what I tested:

```
// Comment out the sleep statement, busy wait instead

//constexpr auto sleepDuration = std::chrono::microseconds(100);
//std::this_thread::sleep_for(sleepDuration);
int64_t timeslept = 0;
while (timeslept < 100) {
	timeslept = GetTicksUsSince(ticksNewUs);
}
LOG_MSG("Slept for %lld", timeslept); // Comment this log statement out to fix GCC + Windows performance
```

**Comment by kklobe** [comment]
Yeah, let me revert to the old one millisecond sleep.
