### ISSUE TITLE
Store FAT file attributes as extended attributes on the host filesystem

### ISSUE THREAD

**Issue by johnnovak** [dosbox-staging/dosbox-staging#2793]
Work has started on this, but was abandoned. We collectively came to the conclusion to simply mirror the Wine and Dosemu2 implementation of the `user.DOSATTRIB` extended attribute:
https://github.com/dosbox-staging/dosbox-staging/pull/2693#issuecomment-1646815262

See abandoned implementation attempt and discussion here:
https://github.com/dosbox-staging/dosbox-staging/pull/2693

**Comment by Torinde** [comment]
A pity, it seemed that @NicknineTheEagle went through the hard part and just a few coding remarks were pending.

**Comment by FeralChild64** [comment]
Started working on this, as I would really like to have this feature - https://github.com/dosbox-staging/dosbox-staging/tree/fc/fs-attrib-1

- refactored the code a bit, most of the original PR review remarks are now handled
- changed the attribute format to be (in general) WINE-compatible

Still to be fixed/improved/done:
- more refactoring / cleanup / comments in the code
- for the read-only attribute WINE takes away the owner-write permission (like DOSBox Staging before this patch - this is something I have to fix
- if I'm not mistaken, DOS sets the Archive bit every time the file is created/modified - I haven't really tested this yet

There is one limitation regarding WINE compatibility I intend to keep: WINE does not allow to clear the Archive attribute on files, we do :) Files without `user.DOSATTRIB` extended attribute are considered to have Archive attribute set.

----

Unfortunately, I won't have much time in the near future (like a week or two) - if anyone wants to take over, feel free. If not, I'll finish when I have free time again.

**Comment by johnnovak** [comment]
That's great @FeralChild64; thanks for taking this over. Please make sure to credit @NicknineTheEagle as well in the commit logs somehow for the initial implementation.

There's no rush, it will take a while until I finish my outstanding tickets for the release candidate, so you'll have time to finish this at a leisurely pace once you're back. The auto-switching shader stuff caused a 5-6 week delay, but it was well worth it. But no more major scope creeps 😅

**Comment by johnnovak** [comment]
Would you have the appetite to tackle this as well @FeralChild64 ? It seems to be related and it might make your job even easier overall.

https://github.com/dosbox-staging/dosbox-staging/issues/2663

**Comment by FeralChild64** [comment]
We'll see, I'll have a look at https://github.com/dosbox-staging/dosbox-staging/issues/2663 - but it might be best to do it in a separate PR.

Yes, @NicknineTheEagle will be credited - even in the commit named 'WIP' for now he is already mentioned as a co-author.

Please don't wait for this with releasing 0.81.0; it is already delayed enough. and this feature won't be even noticed by most of our users. By removing the 'Archive-attribute hack' I might have just opened a Pandora's box; this 2 week estimation is a rather optimistic case.

**Comment by johnnovak** [comment]
Yep @FeralChild64 we are in agreement; I see this too as a non-essential nice-to-have. We won't wait for it, so no pressure 😄

**Comment by FeralChild64** [comment]
This is much more complicated than I anticipated, but I'm progressing. Still to do:
- slightly improve error handling
- set Archive bit on file close-after-write also on mounted FAT images
- test drive overlay support
- test Windows code path

**Comment by johnnovak** [comment]
> This is much more complicated than I anticipated, but I'm progressing. Still to do:
> 
>     * slightly improve error handling
> 
>     * set Archive bit on file close-after-write also on mounted FAT images
> 
>     * test drive overlay support
> 
>     * test Windows code path

No rush @FeralChild64. It' a very niche feature, so we can simply release it in the next version if it takes a long time. Thanks for doing a thorough job and considering all implications and use cases 🚀

**Comment by FeralChild64** [comment]
Last issue to be debugged before merge request: overlay support is not working properly.
