### ISSUE TITLE
MT32 does not reset instruments when changing game

### ISSUE THREAD

**Issue by Scattershor** [dosbox-staging/dosbox-staging#2795]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Different version than latest?

0.80.1 Maintenance release

### What Operating System are you using?

None

### Relevant hardware info

Ryzen 7 5800X, RTX 3080

### Have you checked that no other similar issue already exists?

- [x] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

The MT32 emulation does not reset instruments upon game quit or switch. Running SQ3 then switching to SOMI makes the theme of SOMI all stuffed up. This occurs when switching games from one MT32 game to another.

### Steps to reproduce the behaviour.

Explain how to reproduce
To easily replicate: 
1. Run Space Quest 3 with built in MT32 emulation. 
2. Quit to DOS prompt
3. Run Secrets of Monkey Island

Observe the theme music be all whack. 

### Download URL of affected game or software

https://archive.org/download/20220917_20220917_0541/Secret%20of%20Monkey%20Island%2C%20The%20%28VGA%29%20%281992%29%20%28v1.0%29%20%28Rerelease%29%20%281.44M%29%20%5B%23%5D.zip ; https://archive.org/download/spacequestcollectorseditionusa/Space%20Quest%20-%20Collector%27s%20Edition%20%28USA%29.zip

### Your configuration

```ini
https://gist.github.com/Scattershor/b8c7ae7820557b0652c2ae03e5fffc8f
```

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by rderooy** [comment]
I remember the same thing would happen on my real MT-32 that I had back in the day. The easy solution back then was to power-cycle the MT-32 in between games, which was quite easy with a real MT-32. But if you had the ISA card version (LAPC-I) you had to power cycle the PC. But I think there was also a MIDI command that could cause the MT-32 to reset to default settings.

**Comment by Scattershor** [comment]
> I remember the same thing would happen on my real MT-32 that I had back in the day. The easy solution back then was to power-cycle the MT-32 in between games, which was quite easy with a real MT-32. But if you had the ISA card version (LAPC-I) you had to power cycle the PC. But I think there was also a MIDI command that could cause the MT-32 to reset to default settings.

Is there any way to do that on DOSBox Staging without quitting the program outright? (This is referring to the internal MT32 emulator built in).

**Comment by kcgen** [comment]
in your game's batch file before launching the game, set your desired MT-32 model and then engage the device. Something like:

### sq3.bat

```shell
@echo off
config -set mt32 model=mt32_old
config -set midi mididevice=mt32

sierra.com
```

### somi.bat

```shell
@echo off
config -set mt32 model=cm32l
config -set midi mididevice=mt32

monkey2.exe
```

Then you can 

This "configure what the game needs" before-hand approach is really the only way to go if you're running multiple games, back-to-back, within the same long-lived DOSBox Staging session.

Same thing for SoundBlaster 2 game that doesn't use MIDI:

```shell
@echo off
config -set midi mididevice=none
config -set sblaster sbtype=sbpro2

game.exe
```

Or GUS:

```shell
@echo off
config -set midi mididevice=none
config -set sblaster sbtype=none
config -set gus gus=true

game.exe
```

Short-hand notation also works: `gus true`, `sbtype sb16`, `mididevice mt32`, etc..

**Comment by Burrito78** [comment]
How does ECE oder DOSBox-X behave? Same as Staging?

**Comment by kcgen** [comment]
Probably the same, @Burrito78.

One might wonder, _"Well, can't DOSBox give users a helping hand and just reset the audio devices when the game's .COM or .EXE exits?"_

The problem is, games themselves can be composed of many executables, some strung together with mere .BAT files or a simple .COM files calling them in some order. We don't want to be the hasty waiter that snatches your plate while you're mid-bite.

Instead, it's important that games "set the stage" how they like on startup - reset the DSP, flush or clear all instruments, etc. (But I guess some weren't as thorough at this).

**Comment by Scattershor** [comment]
> in your game's batch file before launching the game, set your desired MT-32 model and then engage the device. Something like:
> 
> ### sq3.bat
> ```shell
> @echo off
> config -set mt32 model=mt32_old
> config -set midi mididevice=mt32
> 
> sierra.com
> ```
> 
> ### somi.bat
> ```shell
> @echo off
> config -set mt32 model=cm32l
> config -set midi mididevice=mt32
> 
> monkey2.exe
> ```
> 
> This _configure-before-launch_ approach is the only way to go if you're running multiple games within the same long-lived DOSBox Staging session.
> 
> Same thing for Sound Blaster games that don't use MIDI:
> 
> ```shell
> @echo off
> config -set midi mididevice=none
> config -set sblaster sbtype=sbpro2
> 
> game.exe
> ```
> 
> Or GUS:
> 
> ```shell
> @echo off
> config -set midi mididevice=none
> config -set sblaster sbtype=none
> config -set gus gus=true
> 
> game.exe
> ```
> 
> Short-hand notation also works: `gus true`, `sbtype sb16`, `mididevice mt32`, etc..

Makes sense. And I'll set the BAT to run the commands to put the MIDI back to WIN32 (my Roland Sound Canvas) when it exits. Interestingly enough you can run commands after a program has ended, for example, I run NOVERT in a BAT then DOOM.EXE and when the EXE exits it runs NOVERT /u to disable it so I don't have to bother running the command myself before switching games.

**Comment by Grounded0** [comment]
This also happens with FluidSynth or General MIDI/Roland GS. Try running Space Quest 6 first and subsequently run Transport Tycoon Deluxe and enjoy the garbage MIDI.

This is how i reinitialise GM/GS after exiting Space Quest 6:

SQ6.BAT
``
imgmount -u d
imgmount d y:\sq6.iso -t cdrom
call CheckCD   D 
call vesatest 
if errorlevel 0 goto vesafound 
echo A VESA driver was not found on your system. Please rerun install 
echo and check the readme file for help on installing a VESA driver. 
goto end 
:vesafound 
C:\sierra\SQ6\sierra -o C:\sierra\SQ6\resource.cfg 
config -set mididevice mt32
config -set mididevice fluidsynth
:end
``

Sierra often seemed to mess this up by not making sure MIDI exited in a clean state. 😁

**Comment by Scattershor** [comment]
> This also happens with FluidSynth or General MIDI/Roland GS. Try running Space Quest 6 first and subsequently run Transport Tycoon Deluxe and enjoy the garbage MIDI.
> 
> This is how i reinitialise GM/GS after exiting Space Quest 6:
> 
> SQ6.BAT `imgmount -u d imgmount d y:\sq6.iso -t cdrom call CheckCD D call vesatest if errorlevel 0 goto vesafound echo A VESA driver was not found on your system. Please rerun install echo and check the readme file for help on installing a VESA driver. goto end :vesafound C:\sierra\SQ6\sierra -o C:\sierra\SQ6\resource.cfg config -set mididevice mt32 config -set mididevice fluidsynth :end`
> 
> Sierra often seemed to mess this up by not making sure MIDI exited in a clean state. 😁

I don't think I've had an issue with my Roland Sound Canvas after SQ6 but I'll actually test it out again and see if it makes DOOM's music stuffed when I can.

**Comment by johnnovak** [comment]
Yep, this is how DOS games behave:

- _Some_ games do not intialise MIDI devices to a known state on start; they just assume the device was just switched on.
- _Most_ games do not reset/reinit the MIDI device at exit.

So the funky behaviour you experienced is specific to any two particular game-pair. Might happen, or it might not—it entirely depends on the two games in question. People using real hardware have to either power-cycle their MIDI hardware between games for the best results, or need to send a special SysEx MIDI message sequence (device and vendor specific) to their MIDI device that resets it to the defaults. Power cycling is usually just easier and it's 100% reliable 😄 

It would be nice if we could just simply reset the device when you exit from a game, but that's fraught with a lot of problems, as @kcgen pointed it out, and it's ultimately too invasive.

If you use DOSBox as a "real computer", not just to launch a single game in a single session, you need to understand these issues in a bit more detail—just like you would need to if you built a real retro PC today. We try to simplify these quirks when we can do so reliably, e.g. you almost never need to mess around with memory management in DOSBox, which is I'd say one of the most painful things about using real MS-DOS. But as resetting MIDI devices between games cannot be done reliably, the solution is user education.

I'll definitely mention this in the upcoming user manual and offer tips on how to reset MIDI devices between games, so thanks for bringing this to my attention. But it's a power user issue; if you just use a single folder and single config per game, you'll never hit this problem.

Btw, in most cases you can set the config in a simpler way using shortcuts (in Staging only). E.g.

```
config -set midi mididevice=none
config -set sblaster sbtype=none
config -set gus gus=true
```

can be rewritten to

```
mididevice = none
sbtype = none
gus = on
```

You only need `config -set` when there's ambiguity (e.g., an executable with config name exists in the path). Also, you can use `enabled`, `on`, and `yes` for `true` now, and `disabled`, `off`, `no`, and `none` for `false` now. It just nicer and makes configs more readable 😄

**Comment by Scattershor** [comment]
> Yep, this is how DOS games behave:
> 
> * _Some_ games do not intialise MIDI devices to a known state on start; they just assume the device was just switched on.
> * _Most_ games do not reset/reinit the MIDI device at exit.
> 
> So the funky behaviour you experienced is specific to any two particular game-pair. Might happen, or it might not—it entirely depends on the two games in question. People using real hardware have to either power-cycle their MIDI hardware between games for the best results, or need to send a special SysEx MIDI message sequence (device and vendor specific) to their MIDI device that resets it to the defaults. Power cycling is usually just easier and it's 100% reliable 😄
> 
> It would be nice if we could just simply reset the device when you exit from a game, but that's fraught with a lot of problems, as @kcgen pointed it out, and it's ultimately too invasive.
> 
> If you use DOSBox as a "real computer", not just to launch a single game in a single session, you need to understand these issues in a bit more detail—just like you would need to if you built a real retro PC today. We try to simplify these quirks when we can do so reliably, e.g. you almost never need to mess around with memory management in DOSBox, which is I'd say one of the most painful things about using real MS-DOS. But as resetting MIDI devices between games cannot be done reliably, the solution is user education.
> 
> I'll definitely mention this in the upcoming user manual and offer tips on how to reset MIDI devices between games, so thanks for bringing this to my attention. But it's a power user issue; if you just use a single folder and single config per game, you'll never hit this problem.
> 
> Btw, in most cases you can set the config in a simpler way using shortcuts (in Staging only). E.g.
> 
> ```
> config -set midi mididevice=none
> config -set sblaster sbtype=none
> config -set gus gus=true
> ```
> 
> can be rewritten to
> 
> ```
> mididevice = none
> sbtype = none
> gus = on
> ```
> 
> You only need `config -set` when there's ambiguity (e.g., an executable with config name exists in the path). Also, you can use `enabled`, `on`, and `yes` for `true` now, and `disabled`, `off`, `no`, and `none` for `false` now. It just nicer and makes configs more readable 😄

Interesting. I'll try some of these and figure out the most efficient way of making this work out.

**Comment by rderooy** [comment]
I really dislike the "shorthand" notation. I consider it namespace pollution. In DOSBox-X it is disabled by default for that very reason.

**Comment by johnnovak** [comment]
> I really dislike the "shorthand" notation. I consider it namespace pollution. In DOSBox-X it is disabled by default for that very reason.

Don't use it then 😄 I love that feature, who wants to type `config -set ...` every time...

**Comment by Grounded0** [comment]
I just noticed that shorthand notation doesn't work with FreeDOS `COMMAND.COM`. You can keep DOSBox `COMMAND.COM` with this stuff if you want to. Nobody serious uses it anyway.

**Comment by rderooy** [comment]
1. I think `config -set ...` conveys the message better what you are trying to do, especially if the config will be shared.
2. the commands can conflict with DOS executable names, hence the namespace pollution (I think johncampbell ran into this, and that is why he disabled it).

**Comment by johnnovak** [comment]
> 1. I think `config -set ...` conveys the message better what you are trying to do, especially if the config will be shared.
> 
>     2. the commands can conflict with DOS executable names, hence the namespace pollution (I think johncampbell ran into this, and that is why he disabled it).

I get that, but 99% of the time it does _not_ conflict, and it's super handy. If it _does_ conflict, the exe name takes precedence, which is good.

Using it is entirely optional; if this very occasional potential conflict bothers anyone, they can just use `config -set`. That won't go away. I see it as a big usability enhancement, it was one of the many Staging enhancements that really impressed me because it enhances ease of use. Plus we can mandate in the future that the equals sign is mandatory, so `gus on` will no longer set the config, only `gus = on` would. That would reduce the likelihood of conflicts even further to almost zero!

So let's not just throw out the baby with the bathwater; it's a great usability feature 😄

**Comment by johnnovak** [comment]
> I think config -set ... conveys the message better what you are trying to do, especially if the config will be shared.

And yeah, agree with that for shared configs, probably for the best. That ensures it 100% works everywhere.

But for casual tinkering, the shorthand is perfectly fine (plus with mandating the equals sign, it would be also practically bulletproof, just like `config -set`).

**Comment by Grounded0** [comment]
Seems like another on/off switch to me with default on.

**Comment by johnnovak** [comment]
> Seems like another on/off switch to me with default on.

If someone raises a PR I'll merge it, if we leave shorthands on by default. But if we mandate the equals sign instead, are you guys seriously worried about having a DOS file with the name `gus=on` or `umb=off`. I think in that case the person deserved it 🤣 

But ok, it's diverging from DOS behaviour, hence an extension.

**Comment by Grounded0** [comment]
Yeah lets look if anyone is willing to slave away for a PR on this or will it turn into another FOR loops support for DOSBox `COMMAND.COM`. 🙂

**Comment by johnnovak** [comment]
> Yeah lets look if anyone is willing to slave away for a PR on this or will it turn into another FOR loops support for DOSBox `COMMAND.COM`. 🙂

Raise ticket, etc 😄

**Comment by FeralChild64** [comment]
It's actually trivial to implement - https://github.com/dosbox-staging/dosbox-staging/tree/fc/shell-config-1
I just need to write a config option description and cleanup the `DOS_Shell::CheckConfig` method - just not today, it's getting very late here where I live.

**Comment by johnnovak** [comment]
> It's actually trivial to implement - https://github.com/dosbox-staging/dosbox-staging/tree/fc/shell-config-1 I just need to write > Adding a requirement to use `=` could make some folks unhappy, as it would break compatibility with some batch files.

Yeah, but break once, then it's safer going forward? We could issue a warning first about missing equals signs, give them a release or two to upgrade, then drop support.

**Comment by Scattershor** [comment]
> in your game's batch file before launching the game, set your desired MT-32 model and then engage the device. Something like:
> 
> ### sq3.bat
> ```shell
> @echo off
> config -set mt32 model=mt32_old
> config -set midi mididevice=mt32
> 
> sierra.com
> ```
> 
> ### somi.bat
> ```shell
> @echo off
> config -set mt32 model=cm32l
> config -set midi mididevice=mt32
> 
> monkey2.exe
> ```
> 
> This _configure-before-launch_ approach is the only way to go if you're running multiple games within the same long-lived DOSBox Staging session.
> 
> Same thing for Sound Blaster games that don't use MIDI:
> 
> ```shell
> @echo off
> config -set midi mididevice=none
> config -set sblaster sbtype=sbpro2
> 
> game.exe
> ```
> 
> Or GUS:
> 
> ```shell
> @echo off
> config -set midi mididevice=none
> config -set sblaster sbtype=none
> config -set gus gus=true
> 
> game.exe
> ```
> 
> Short-hand notation also works: `gus true`, `sbtype sb16`, `mididevice mt32`, etc..

Your suggestions worked like a charm. 
Here's an example of my SQ3 BAT edited:
`@echo off 
config -set mt32 model=cm32l
config -set midi mididevice=mt32
sierra 
config -set mt32 model=auto
config -set midi mididevice=win32
cls`

**Comment by kcgen** [comment]
Excellent news, @Scattershor. 
(closing)
