### ISSUE TITLE
Voodoo usability fixes

### ISSUE THREAD

**Issue by johnnovak** [dosbox-staging/dosbox-staging#2803]
Extracted the low-hanging fruit fixes from https://github.com/dosbox-staging/dosbox-staging/issues/2770#issuecomment-1697213334 for you @kcgen if you happen to have the capacity to fix these for 0.81.0.

- Make `dos_rate = auto` set 60 Hz in Voodoo rendering mode.
- If the user customizes `dos_rate`, then the Voodoo rendering should run at that rate too.
- Set `voodoo_memsize = 4` as default to avoid crashes in some games (e.g., Carmageddon, Screamer Rally)
 - standardize voodoo conf settings:

    ```ini
    [voodoo]
    voodoo = on(*) / off
    voodoo_memsize = 4(*) / 12
    # emulate either 4 MB or 12 MB of combined memory allocated
    # to The frame buffer processor (FBI) and texture mapping
    # unit(s) (TMU), as follows:
    #   - 4 MB = 2 MB FBI and one 2 MB TMU
    #   - 12 MB => 4 MB FBI and two 4 MB TMUs
  
    voodoo_multi_threaded = on(*) / off
    # use multiple threads to improve performance.
  
    voodoo_texture_smoothing = on / off(*) 
    # use bi-linear filtering to emulate the 3dfx's
    # texture smoothing effect. Recommended for fast
    # desktop-class CPUs otherwise framerate might suffer.
    ```

**Comment by Kappa971** [comment]
- Also the column of black (or colored) pixels in the right side of the image
![261590192-451639a2-b8a8-4ae3-ad7b-2979bb5a4441](https://github.com/dosbox-staging/dosbox-staging/assets/62349018/6e1e99af-4f14-456e-b6be-0a279126a9b6)
It's difficult to notice. Here I managed to capture him in the transition from one menu to another:
![Wolfenstein 3D Screenshot 2023 08 30 - 00 59 05 00](https://github.com/dosbox-staging/dosbox-staging/assets/62349018/4ee5f2fc-fe38-4561-b09d-0d94e29ef545)

**Comment by johnnovak** [comment]
> * Also the column of black (or colored) pixels in the right side of the image

That's harder to fix. Let's focus on the quick wins on this ticket that are achievable for 0.81.0 😄 We can always use your original ticket as reference.

**Comment by Kappa971** [comment]
> That's harder to fix. Let's focus on the quick wins on this ticket that are achievable for 0.81.0 😄 We can always use your original ticket as reference.

Oh sorry 😁

**Comment by kcgen** [comment]
Added conf standardization to the ticket body (see original comment)

**Comment by Kappa971** [comment]
>   ```ini
>   [voodoo]
>   voodoo = on(*) / off
>   voodoo_memsize = 4(*) / 12
>   # emulate either 4 MB or 12 MB of combined memory allocated
>   # to The frame buffer processor (FBI) and texture mapping
>   # unit(s) (TMU), as follows:
>   #   - 4 MB = 2 MB FBI and one 2 MB TMU
>   #   - 12 MB => 4 MB FBI and two 4 MB TMUs
>   
>   voodoo_multi_threaded = on(*) / off
>   # use multiple threads to improve performance.
>   
>   voodoo_texture_smoothing = on / off(*) 
>   # use bi-linear filtering to emulate the 3dfx's
>   # texture smoothing effect. Recommended for fast
>   # desktop-class CPUs otherwise framerate might suffer.
>   ```

For a future version of DOSBox Staging I would add an option 
```ini
voodoo_16bitcolor_dithered = on/off
```
if this isn't difficult to implement and doesn't make the emulation more CPU intensive. 
This fancy option, if disabled, would allow LCD monitors to display 32-bit colors instead of dithered colors (like nglide).
Those who use a CRT monitor or want to use shaders can enable the option and have the original output.

**Comment by kcgen** [comment]
> EDIT
> 
> > voodoo_texture_smoothing = on / off(*)
> 
> The default value should be "on", I'm not wrong Voodoo cards enable bilinear filtering by default (?)

We will see how the review process goes when I PR this change. 

We're in compromise and tradeoff land here. So the questions I ask myself:

Will the majority of users have the horsepower to play 3dfx games at smooth framerates with this option default-enabled?

If that answer is no, most users won't have enough horse power (given even you with high end hardware had some major issues with framerate fallout and stuttering),

The next question is:

Of the two compromises, which should take priority?

1. Smooth(er) and more consistent frame rates, with less chance of stutters, with the compromise being less smooth looking textures.

2. More accurate smoothed textures with the compromise being lower, less consistent frame rates with higher frequency of stuttering.

The projects goal is the best experience, and to me, given both of the above are not great, I would decide that frame rate smoothness should take priority.

**Comment by johnnovak** [comment]
For the record, some guys appears to be continuing LeiLei's old Voodoo emulation shader. The one that emulates the "vaseline smear" I mentioned before that they intentionally did to smooth the dither. At some point, I think we'll integrate this into the auto CRT shader setup. Of course, people will be able to disable it and get eye piercing, sharp pixels 😏 

https://www.vogons.org/viewtopic.php?f=5&p=1194914#p1194914

**Comment by Kappa971** [comment]
> For the record, some guys appears to be continuing LeiLei's old Voodoo emulation shader. The one that emulates the "vaseline smear" I mentioned before that they intentionally did to smooth the dither. At some point, I think we'll integrate this into the auto CRT shader setup. Of course, people will be able to disable it and get eye piercing, sharp pixels 😏
> 
> https://www.vogons.org/viewtopic.php?f=5&p=1194914#p1194914

The problem is that this would only work with CRT shaders and not with the sharp shader or other shaders (or with glshader = none in case it is needed for some). Is there no way to create a color conversion internal to the DOSBox emulation? (take a dithered color and convert it to one that is reproducible without dithering on a 32-bit palette instead of 16-bit). No vaseline effect, just color conversion.

**Comment by johnnovak** [comment]
Yeah all possible @Kappa971 and maybe someone interested in this will add such a feature one day.

**Comment by johnnovak** [comment]
This is the type of voodoo I like 😎 

![voodoo](https://github.com/dosbox-staging/dosbox-staging/assets/698770/19520b5c-edf2-48eb-a112-4e9c309ab067)
