### ISSUE TITLE
Catacomb 3-D video regression

### ISSUE THREAD

**Issue by johnnovak** [dosbox-staging/dosbox-staging#2804]
The video rendering of Catacomb 3-D (1992) (from eXoDOS v5) has regressed compared to 0.80.1 and latest SVN.

Just start the game with the default config, then press Enter a couple of times to start the game.

The HUD at the bottom of the screen is constantly and rapidly flickering. In 0.80.1 and SVN the image is 100% stable—zero flicker. Tried with different `svga_*` machine types; there's no improvement.

![image](https://github.com/dosbox-staging/dosbox-staging/assets/698770/b41452f4-9328-48c0-96c0-1b7a28f22e2f)

**Comment by kcgen** [comment]
great catch, @johnnovak.
Bisecting.

**Comment by johnnovak** [comment]
> great catch, @johnnovak. Bisecting.

I'm going through a huge pile of EGA games because I love the EGA era, plus I have some tricks up my sleeve that I'm gonna unleash soon (some enhancements to the adaptive CRT shader stuff for EGA modes).

**Comment by kcgen** [comment]
bisects to: 2b26d90dc0cac2e17538836c95932b4b17e667bf
Prior commit is good: `git checkout 2b26d90~1`
Nothing jumping out at me that's obvious - looks like mostly rendering changes as opposed to VGA internals (which is more what I was suspecting!)

Hopefully you can discover what triggered it :+1:

**Comment by johnnovak** [comment]
> bisects to: [2b26d90](https://github.com/dosbox-staging/dosbox-staging/commit/2b26d90dc0cac2e17538836c95932b4b17e667bf) Prior commit is good: `git checkout 2b26d90~1` Nothing jumping out at me that's obvious - looks like mostly rendering changes as opposed to VGA internals (which is more what I was suspecting!)
> 
> Hopefully you can discover what triggered it 👍

Thanks, that helps. I think it's something related to VGA internals; it's just this change changes the double-scan rendering behaviour, that triggers some earlier mistake that I probably made around the double-scanning.

I'll investigate, this helps!
