### ISSUE TITLE
Crash when moving window between monitors with adaptive shaders enabled on macOS

### ISSUE THREAD

**Issue by johnnovak** [dosbox-staging/dosbox-staging#2809]
1. Start a 320x200 VGA game on macOS with the defaults (adaptive CRT shaders enabled)
2. Move the window from the laptop screen to the external monitor.
3. Crash... 😩 The following gets printed in an infinite loop:

```
Loguru caught a signal: SIGABRT
libc++abi: terminating with uncaught exception of type std::__1::system_error: recursive_mutex lock failed: Invalid argument

Loguru caught a signal: SIGABRT
libc++abi: terminate_handler unexpectedly threw an exception

Loguru caught a signal: SIGABRT
libc++abi: terminating with uncaught exception of type std::__1::system_error: recursive_mutex lock failed: Invalid argument
```

Notes:

- Laptop screen is 4k (high-DPI), external monitor is 1440p (not high-DPI... I think?)
- Only manifests with 320x200 mode 13h VGA games; other resolutions are not affected (I guess because this mode triggers the switching logic in a particular way)
- Making the external screen the primary screen makes no difference; things are always crashy-crashy on the external screen (e.g. toggling fullscreen) and moving the window between the monitors.

---

Also crashes when switching to fullscreen on the _external display only (!)_ Everything is 100% rock solid on the laptop display... WTF?

```
Loguru caught a signal: SIGSEGV
Stack trace:
18         0x1089bd08c 22  dyld                                0x00000001089bd08c start + 520
17         0x104a539c8 main + 36
16         0x104dfbe34 sdl_main(int, char**) + 4796
15         0x104ae2a5c Config::StartUp() + 28
14         0x1051ab0c0 SHELL_Init() + 3992
13         0x1051a840c DOS_Shell::Run() + 1540
12         0x1051a7900 DOS_Shell::ParseLine(char*) + 2008
11         0x1051be4b4 DOS_Shell::DoCommand(char*) + 440
10         0x1051ec984 DOS_Shell::Execute(std::basic_string_view<char, std::char_traits<char> >, std::basic_string_view<char, std::char_traits<char> >) + 996
9          0x1051ed86c run_binary_executable(std::basic_string_view<char, std::char_traits<char> >, std::basic_string_view<char, std::char_traits<char> >) + 1556
8          0x104ba5790 CALLBACK_RunRealInt(unsigned char) + 92
7          0x104a543c0 DOSBOX_RunMachine() + 28
6          0x104a542a8 Normal_Loop() + 20
5          0x104ff8930 PIC_RunQueue() + 292
4          0x105091d98 VGA_DrawPart(unsigned int) + 100
3          0x1050357d4 RMR_DrawLine_Passthrough(void const*) + 36
2          0x104db7db0 clear_cache_handler(void const*) + 152
1          0x104dc2084 NormalDw_32_32_L(void const*) + 144
0          0x1b9c574a4 _sigtramp + 56
2023-08-31 15:21:21.953 | Signal: SIGSEGV
```

Would be great if people could try this on different OSes when using an external monitor. @kcgen @shermp @weirddan455 @FeralChild64 et all. Thanks 😅

**Comment by weirddan455** [comment]
I can't reproduce.  I only have a single monitor on a desktop.  However, I have a hunch it's related to Loguru.  That looks to be the only place in the code that uses a recursive mutex.

```
$ grep -r recursive_mutex src
src/libs/loguru/loguru.cpp:     static std::recursive_mutex  s_mutex;
src/libs/loguru/loguru.cpp:             std::lock_guard<std::recursive_mutex> lock(s_mutex);
src/libs/loguru/loguru.cpp:             std::lock_guard<std::recursive_mutex> lock(s_mutex);
src/libs/loguru/loguru.cpp:             std::lock_guard<std::recursive_mutex> lock(s_mutex);
src/libs/loguru/loguru.cpp:             std::lock_guard<std::recursive_mutex> lock(s_mutex);
src/libs/loguru/loguru.cpp:             std::lock_guard<std::recursive_mutex> lock(s_mutex);
src/libs/loguru/loguru.cpp:                     std::lock_guard<std::recursive_mutex> lock(s_mutex);
src/libs/loguru/loguru.cpp:                     std::lock_guard<std::recursive_mutex> lock(s_mutex);
```

**Comment by johnnovak** [comment]
> I can't reproduce. I only have a single monitor on a desktop. However, I have a hunch it's related to Loguru. That looks to be the only place in the code that uses a recursive mutex.

Thanks testing @shermp  and for the tip. I'll play around with loguru then. The other crash seems unrelated to it, though.

**Comment by shermp** [comment]
> > I can't reproduce. I only have a single monitor on a desktop. However, I have a hunch it's related to Loguru. That looks to be the only place in the code that uses a recursive mutex.
> 
> Thanks for testing @shermp and for the tip. I'll play around with loguru then. The other crash seems unrelated to it, though.

You tagged the wrong person... Think you meant @weirddan455

**Comment by johnnovak** [comment]
> You tagged the wrong person... Think you meant @weirddan455

Huh, yeah 😅

**Comment by johnnovak** [comment]
No longer an issue with current `main` so closing (probably the surface output removal and the window size handling simplification by @GranMinigun helped).
