### ISSUE TITLE
ZMBV Video Encoder Performance Regression

### ISSUE THREAD

**Issue by weirddan455** [dosbox-staging/dosbox-staging#2812]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### What Operating System are you using?

Linux x86_64

### If Other OS, please describe

Arch Linux

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

I had complained previously about bad performance of the current ZMBV video encoder.  Today I grabbed the old stable version v0.80.1 and tried there and performance was fine.  I then did a git bisect and found the first bad commit 0d01f906ed9baec649146d62f46dedcf165229f6

This was tested in Release builds recording Doom.

```
0d01f906ed9baec649146d62f46dedcf165229f6 is the first bad commit
commit 0d01f906ed9baec649146d62f46dedcf165229f6
Author: kcgen <kcgen@users.noreply.github.com>
Date:   Mon Apr 10 17:04:27 2023 -0700

    Eliminate vgaonly-specific handling when checking for line-doubling

 src/hardware/vga_draw.cpp | 18 ++++++++++--------
 1 file changed, 10 insertions(+), 8 deletions(-)
```

It's related to this line-doubling thing which I don't really understand.  I just checked the output videos as I was typing this and it looks the bad performance may simply be due to encoding a higher res video.  The ones that made the game all laggy were 640X400 vs 320X200 for the ones that performed well in game.

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Start Doom (or probably any somewhat demanding VGA game)
2. Ctrl + F7 to start video capturing
3. Game starts stuttering badly

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by johnnovak** [comment]
Yes, it's normal as it stands now. My capture fixes will take care of this by dividing it back to 320x200 prior to passing the frame to the vide capturer (I'm doing that for upscaled image captures already).

https://github.com/dosbox-staging/dosbox-staging/issues/2734 will fix it and restore the exact v0.80.1 performance.

**Comment by weirddan455** [comment]
@johnnovak The video encoder is already being passed a 320X200 frame.  It looks for these `double_width` and `double_height` flags and does the doubling inside the video capture code here:

https://github.com/dosbox-staging/dosbox-staging/blob/facc3ebce933d6c4bba7e73f18b6e913cdbaed37/src/capture/capture_video.cpp#L382-L426

This is where I was getting confused.  In my ffmpeg renderer, I just ignore those flags and everything works fine.

**Comment by johnnovak** [comment]
> @johnnovak The video encoder is already being passed a 320X200 frame. It looks for these `double_width` and `double_height` flags and does the doubling inside the video capture code here:
> 
> https://github.com/dosbox-staging/dosbox-staging/blob/facc3ebce933d6c4bba7e73f18b6e913cdbaed37/src/capture/capture_video.cpp#L382-L426
> 
> This is where I was getting confused. In my ffmpeg renderer, I just ignore those flags and everything works fine.

As I said, all these things have the same root cause. Trust me, I understand 100% what's going on, and fixing the root cause will fix all these tickets at once 😄 Please be patient until I get there 😄 

It would take me ages to explain, and you'll be bored to tears around 30% in 😅 Well, I gave you a partial explanation here, btw, maybe read that a few times to understand what's going on (but it's not the complete picture):

https://github.com/dosbox-staging/dosbox-staging/pull/2785#issuecomment-1694099667

Thanks for raising these, btw 😄

**Comment by MasterO2** [comment]
What's the status on this issue for 0.81?

**Comment by johnnovak** [comment]
> What's the status on this issue for 0.81?

Hopefully, @kcgen or @shermp or someone will figure out how to integrate `zlib-ng`, eventually. But that can be done probably during the RC period too. Worst case—we'll release the final 0.81 with this perf regression.

**Comment by kcgen** [comment]
Yup, still working on this.

**Comment by Grounded0** [comment]
The website should be updated that running our Windows binaries has an SSSE3 CPU feature level requirement now. That also lines up with cards offering a robust OpenGL 2.1 support which is somewhere around 2006 so matches up perfectly.

For AMD this means Bulldozer+ so 2011 newer. Maybe pushing it a little? We'll see soon. SSE3 would run perfectly on 2005 era AMD and Intel chips. I think we should do performance comparisons between SSE3 and SSSE3 is the juice worth the squeeze.

**Comment by Grounded0** [comment]
Seems like the choices are SSE2 or SSSE3 from the documentation so we'll have to see how this is accepted by the users with the 0.81 RC.
