### ISSUE TITLE
Fluidsynth writes useless ALSA errors to the log

### ISSUE THREAD

**Issue by weirddan455** [dosbox-staging/dosbox-staging#2821]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### What Operating System are you using?

Linux x86_64

### If Other OS, please describe

Arch Linux

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

This happens only when dynamically linking with my system's Fluidsynth library.  When using the Fluidsynth build from the Meson Wrap, there are no errors being logged.  I'm guessing the Wrap version may just have ALSA support compiled out.

This is a low priority bug as it doesn't seem to affect functionality in any way.  Fluidsynth shouldn't be trying to talk to ALSA though.  As I understand it, we send Fluidsynth MIDI data and it sends us back synthesized audio data.  We then mix the audio and send it to the sound card ourselves via SDL.  So Fluidsynth should be just data in -> data out (someone can correct me if I'm wrong in that assumption).

### Steps to reproduce the behaviour.

Explain how to reproduce
1.  Install Fluidsynth from your system's package manager (only tested on Arch).
2.  Compile DOSbox (default settings should dynamically link with Fluidsynth if available).
3.  Configure DOSbox to use Fluidsynth as shown below.
4.  Examine the console and find the errors being logged right when Fluidsynth code gets executed.

### Your configuration

```ini
[midi]
mididevice = fluidsynth

[fluidsynth]
soundfont = something-valid.sf2
```

### Provide a Log

```text
2023-09-02 14:56:18.731 | MIXER: Negotiated 2-channel 48000 Hz audio in 512-frame blocks
2023-09-02 14:56:18.731 | MIXER: Master compressor enabled
ALSA lib pcm_dmix.c:999:(snd_pcm_dmix_open) unable to open slave
ALSA lib pcm.c:2666:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2666:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2666:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib pcm_route.c:877:(find_matching_chmap) Found no matching channel map
ALSA lib pcm_oss.c:397:(_snd_pcm_oss_open) Cannot open device /dev/dsp
ALSA lib pcm_oss.c:397:(_snd_pcm_oss_open) Cannot open device /dev/dsp
ALSA lib pcm_a52.c:1001:(_snd_pcm_a52_open) a52 is only for playback
ALSA lib confmisc.c:160:(snd_config_get_card) Invalid field card
ALSA lib pcm_usb_stream.c:482:(_snd_pcm_usb_stream_open) Invalid card 'card'
ALSA lib confmisc.c:160:(snd_config_get_card) Invalid field card
ALSA lib pcm_usb_stream.c:482:(_snd_pcm_usb_stream_open) Invalid card 'card'
ALSA lib pcm_dmix.c:999:(snd_pcm_dmix_open) unable to open slave
2023-09-02 14:56:19.881 | FSYNTH: Using SoundFont '/usr/share/soundfonts/default.sf2'
2023-09-02 14:56:19.881 | FSYNTH: Chorus enabled with 3 voices at level 1.20, 0.30 Hz speed, 8.00 depth, and sine-wave modulation
2023-09-02 14:56:19.881 | FSYNTH: Reverb enabled with a 0.61 room size, 0.23 damping, 0.76 width, and level 0.56
2023-09-02 14:56:19.882 | FSYNTH: Operating at 48000 Hz without resampling
2023-09-02 14:56:19.882 | MIDI: Opened device: fluidsynth
```

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by johnnovak** [comment]
>  As I understand it, we send Fluidsynth MIDI data and it sends us back synthesized audio data. We then mix the audio and send it to the sound card ourselves via SDL. So Fluidsynth should be just data in -> data out (someone can correct me if I'm wrong in that assumption).

That's exactly how it works. Same deal with the MT-32 emulation.

**Comment by AaronBPaden** [comment]
I believe this is a fluidsynth issue. I noticed similar warnings when testing #2816 when playing midis directly with fluidsynth through the command line.

**Comment by weirddan455** [comment]
> I believe this is a fluidsynth issue. I noticed similar warnings when testing #2816 when playing midis directly with fluidsynth through the command line.

Same.  Just typing `fluidsynth --version` on the command line displays the same errors.  I stepped through the initialization code in a debugger and all those messages appear during the very first function call we make to fluidsynth `new_fluid_settings()` which is just allocating a blank settings struct.

**Comment by weirddan455** [comment]
Closing this as I'm convinced it's not our bug and I don't think there is anything we can do about this on our side.  This does not happen when we build Fluidsynth ourselves and it also does not happen dynamically linking to Fedora's version of Fluidsynth.
