### ISSUE TITLE
Clocking mode screen disable bit is mishandled

### ISSUE THREAD

**Issue by classilla** [dosbox-staging/dosbox-staging#2838]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### What Operating System are you using?

Linux ppc64le

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

This is apparently a very old bug and doesn't affect many programs, but it does affect Alien Carnage/Halloween Harry. I like this game, and my wife likes this game because Australians wrote it. See earlier report (from 2007!) here: https://www.dosbox.com/comp_list.php?showID=950&letter=H

What happens is that the VGA display never blanks even when the program turns it off. This manifests in screens painting, fading out and fading in, when they should simply fade in from black.

This is because DOSBox improperly aliases the bit in the clocking register which disables screen display with other sources; although the `ClockingModeRegister` struct has `bit_view<5, 1> is_screen_disabled;`, it never actually gets used by anything. Instead, `vga_seq.cpp` sets `vga.attr.disabled` in `write_p3c5()`, which is the only thing checked in `vga_draw.cpp`. Unfortunately, in a debug build, it can be shown that `vga.attr.disabled` gets frequently reset by other writes to port `0x3c0` in `write_p3c0()` in `vga_attr.cpp`, so the value of the clocking mode register is thus dropped and the screen never blanks.

The problem affects upstream as well; it doesn't look like anyone bothered to sit down and fix it. Does the project allow local fixes?

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Run Alien Carnage. It happens right from the Apogee logo and everywhere else like the main menu.

### Download URL of affected game or software

https://www.myabandonware.com/game/alien-carnage-1pe

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by classilla** [comment]
This is enough to basically fix the problem, btw:

```
diff --git a/src/hardware/vga_draw.cpp b/src/hardware/vga_draw.cpp
index 357aca018..ef62a44b6 100644
--- a/src/hardware/vga_draw.cpp
+++ b/src/hardware/vga_draw.cpp
@@ -424,16 +424,23 @@ static uint8_t* draw_linear_line_from_dac_palette(Bitu vidstart, Bitu /*line*/)
        auto palette_index_it = vga.draw.linear_base + offset;
 
        // Pixels remaining starts as the total pixels in this current line and
        // is decremented per pixel rendered. It acts as a lower-bound cutoff
        // regardless of how long the wrapped and unwrapped regions are.
        auto pixels_remaining = check_cast<uint16_t>(vga.draw.line_length /
                                                     bytes_per_pixel);
 
+       // If the screen is disabled, just paint black. This fixes screen
+       // fades in titles like Alien Carnage.
+       if (GCC_UNLIKELY(vga.seq.clocking_mode.data & 0x20)) {
+               memset(line_addr, 0, vga.draw.line_length);
+               return TempLine;
+       }
+
        // see VGA_Draw_Linear_Line
        if (GCC_UNLIKELY((vga.draw.line_length + offset) & ~vga.draw.linear_mask)) {
                // Note: To exercise these wrapped scenarios, run:
                // 1. Dangerous Dave: jump on the tree at the start.
                // 2. Commander Keen 4: move to left of the first hill on stage 1.
 
                const auto end = (vga.draw.line_length + offset) &
                                 vga.draw.linear_mask;
```

**Comment by GranMinigun** [comment]
> Does the project allow local fixes?

Yes, absolutely. Feel free to open a pull request.

**Comment by johnnovak** [comment]
> > Does the project allow local fixes?
> 
> Yes, absolutely. Feel free to open a pull request.

Allow is an understatement; we do such things all the time and it's actively encouraged.

All I'm asking is to extensive regression testing to make sure this change doesn't have unwanted consequences. So please test with at least 10-20 other VGA games.

**Comment by johnnovak** [comment]
> if (GCC_UNLIKELY(vga.seq.clocking_mode.data & 0x20)) {

Yeah, so please don't do that; please use named bit fields as they were introduced to improve readability.

```cpp
 if (vga.seq.clocking_mode.data is_screen_disabled) {
```

**Comment by classilla** [comment]
I've been testing most of the evening and can't find any obvious regressions, so I will turn into a PR. Thanks.
