### ISSUE TITLE
Space Quest I hangs on PCjr

### ISSUE THREAD

**Issue by johnnovak** [dosbox-staging/dosbox-staging#2851]
When starting Space Quest I with the following config (eXoDOS v5 version), the emulator hangs and never recovers. Same behaviour with current `main` and v0.80.1. 

```ini
[dosbox]
machine = pcjr

[autoexec]
c:
sq
```

I'm not even sure if the eXoDOS version I'm using has functional PCjr support or not, but a bug is a bug; we should at least fail gracefully.

The sanitizer build doesn't print out anything interesting, but SVN exits immediately with "Corrupt MCB chain" error, and if I Ctrl-C the debug build of Staging, it looks as if it was stuck in an infinite loop in `DOS_MCB` or something.

```
Loguru caught a signal: SIGINT
Stack trace:
21         0x10c4a108c 25  dyld                                0x000000010c4a108c start + 520
20         0x104df389c main + 36
19         0x106292378 sdl_main(int, char**) + 18036
18         0x10507cc14 Config::StartUp() + 168
17         0x10746ec00 SHELL_Init() + 7152
16         0x107465888 DOS_Shell::Run() + 8104
15         0x10746351c DOS_Shell::RunBatchFile() + 2920
14         0x107461f64 DOS_Shell::ParseLine(char*) + 6488
13         0x1074cdcac DOS_Shell::DoCommand(char*) + 3348
12         0x10754c4ec DOS_Shell::ExecuteProgram(std::basic_string_view<char, std::char_traits<char> >, std::basic_string_view<char, std::char_traits<char> >) + 4680
11         0x1075502dc run_binary_executable(std::basic_string_view<char, std::char_traits<char> >, std::basic_string_view<char, std::char_traits<char> >) + 7376
10         0x1053741d8 CALLBACK_RunRealInt(unsigned char) + 412
9          0x104df5fac DOSBOX_RunMachine() + 28
8          0x104df5e94 Normal_Loop() + 596
7          0x10597185c DOS_21Handler() + 48020
6          0x105a49a8c DOS_ResizeMemory(unsigned short, unsigned short*) + 632
5          0x105a4776c DOS_CompressMemory() + 528
4          0x105a46d48 DOS_MCB::GetType() const + 276
3          0x106a1b488 mem_readb(unsigned int) + 24
2          0x106a1b27c mem_readb_inline(unsigned int) + 316
1          0x106a26c0c get_tlb_readhandler(unsigned int) + 208
0          0x1b9c574a4 _sigtramp + 56
2023-09-10 13:16:32.793 | Signal: SIGINT
```

**Comment by johnnovak** [comment]
Same deal with Manhunter 1 - New York from eXoDOS v5.

**Comment by Grounded0** [comment]
List of Sierra AGI games:

https://wiki.scummvm.org/index.php/Sierra_Game_Versions

**Comment by Jkapp76** [comment]
I've never seen this game work with pcjr. Always worked great with Tandy 1000. 
I like the term "fail gracefully". andagree. :)

**Comment by NRS-NewRisingSun** [comment]
DOSBox(-Staging)'s management of PCjr's memory over 128 KiB is still mysterious to me. On a real PCjr, you have to install a memory manager to use memory above 128 KiB. The original one was "IBM PCjr Memory Options" (PCJRMEM.COM), but most PCjr owners today use JRCONFIG.SYS. A plausible PCjr emulation would provide one or two config file settings that specify behavior similar to the options of at least one of these memory managers. I can elaborate on these behaviors if desired. Basically, the "configuration" does two things:
1. Modify memory control blocks corresponding to the chosen configuration, and
2. Intercept Int10 AH=00 calls (set video mode) to automatically set the CRT and CPU page register 3DFh to a particular memory location.

With the exception of Space Quest v1.0X, Sierra AGI games state in their Reference Card that users are supposed to boot pure DOS without a PCjr memory manager, as the "Loader v3.0" (SIERRA.COM) will configure PCjr memory itself before decrypting and executing AGI, the main interpreter program file.

**Comment by johnnovak** [comment]
For reference, I tried a couple of other Sierra AGI games from the excellenct Sierra floppy collection on archive.org, and all of them made Staging hang in a similar fashion. I always used the earliest version, so v1.0 of Larry I, Gold Rush, Space Quest I, etc.

https://archive.org/details/20220303_20220303_0527

I am too confused about the issue @NRS-NewRisingSun because I could not get these games to work in a recent(ish) build of DOSBox SVN either with `machine = pcjr`. It's great that they work fine with `tandy`, but it would be best to improve our PCjr emulation for preservation purposes.

You seem to be very knowledgeable about the PCjr and the early PC era in general @NRS-NewRisingSun. Can't speak for everybody on the team, but it seems to me that most people here are more familiar with the late 80s and the 90s DOS eras. For me personally, my first PC was a 486 DX2/66 with a Trident SVGA and a GUS, so a bit late to the party. I'm somewhat familiar with VGA and DOS 6.22 asm programming, but what came before that, well, I'm learning about it from random forum posts and from the oldtimers on Vogons. With great interest, but clearly, I'm at a disadvantage here. I only learned about the existence of the Tandy machines about two years ago! 😄 (They were pretty much unheard of in most of Europe back then, and PCs only started getting popular when cheap 386+VGA clones became readily available. I don't think I saw a true EGA monitor in my life! But there were lots of mono monitors as cheaper alternatives to VGA displays.)

Why I'm telling you all this is just to make it clear that getting help from a person like you familiar with the early PC era would be very valuable for the project. If you have the time and inclination to make some improvements to the PCjr, Tandy, composite, etc. emulation in Staging, PRs are very much appreciated! For example, I've noticed some weirdness about switching between composite modes which makes Staging "loose" the current BIOS mode ID. I think it's a bug as I don't believe every second game set up the graphics modes by writing to the video registers directly, circumventing the BIOS. Anyway, we could use some help 😄

**Comment by weirddan455** [comment]
This is enough to get Space Quest I v2.2 to work:

```
diff --git a/src/dos/dos_memory.cpp b/src/dos/dos_memory.cpp
index fd22a7a9e..3b3ac4607 100644
--- a/src/dos/dos_memory.cpp
+++ b/src/dos/dos_memory.cpp
@@ -512,21 +512,8 @@ void DOS_SetupMemory(void) {
                        the tandy graphics system's variable mapping of 0xb800 */
                mcb.SetSize(0x9BFF - DOS_MEM_START - mcb_sizes);
        } else if (machine==MCH_PCJR) {
-               /* memory from 128k to 640k is available */
-               mcb_devicedummy.SetPt((uint16_t)0x2000);
-               mcb_devicedummy.SetPSPSeg(MCB_FREE);
-               mcb_devicedummy.SetSize(umb_start_seg - 0x2000);
-               mcb_devicedummy.SetType(ending_mcb_type);
-
-               /* exclude PCJr graphics region */
-               mcb_devicedummy.SetPt((uint16_t)0x17ff);
-               mcb_devicedummy.SetPSPSeg(MCB_DOS);
-               mcb_devicedummy.SetSize(0x800);
-               mcb_devicedummy.SetType(middle_mcb_type);
-
                /* memory below 96k */
                mcb.SetSize(0x1800 - DOS_MEM_START - (2+mcb_sizes));
-               mcb.SetType(middle_mcb_type);
        } else {
                /* complete memory up to 640k available */
                /* last paragraph used to add UMB chain to low-memory MCB chain */
```

Just remove the high memory MCB entries since it wants to be its own DOS extender apparently.

Version 1.0x is still broken but in a different way.  On main it hangs at a screen that says "Welcome" (not hanging the whole emulator though).  With this change, it beeps and never launches.

I don't know what the "correct" fix would be.  Maybe we need a config option to disable the kind of built-in DOS extender thing we do?  Basically, applying the above patch but behind a new config option.

**Comment by johnnovak** [comment]
> I don't know what the "correct" fix would be. Maybe we need a config option to disable the kind of built-in DOS extender thing we do? Basically, applying the above patch but behind a new config option.

According to [NewRisingSun's previous comment](https://github.com/dosbox-staging/dosbox-staging/issues/2851#issuecomment-1712875708), that's the correct fix, and it makes perfect sense. Some games want to manage their own memory, so we can't just hardcode a fixed memory manager for PCjr like this.

**Comment by weirddan455** [comment]
Ok, I'll work on a fix.  I mistakenly used the term DOS extender in my above comment.  I was thinking of EMS/XMS but pcjr cannot have more than 640KB installed so we're only dealing with conventional memory here.

It's more like the memory layout is wrong.  I saw this and we're not exactly using any of these standard configurations:  https://www.atarimagazines.com/compute/issue58/pcjr_memory.html

The emulator hang from Space Quest is because the game steps on our MCB chain and then runs INT21 ah=0x4a (resize memory block) and we end up spinning in a loop forever in that interrupt due to a broken MCB chain.

**Comment by johnnovak** [comment]
> Ok, I'll work on a fix. I mistakenly used the term DOS extender in my above comment. I was thinking of EMS/XMS but pcjr cannot have more than 640KB installed so we're only dealing with conventional memory here.
> 
> It's more like the memory layout is wrong. I saw this and we're not exactly using any of these standard configurations: https://www.atarimagazines.com/compute/issue58/pcjr_memory.html
> 
> The emulator hang from Space Quest is because the game steps on our MCB chain and then runs INT21 ah=0x4a (resize memory block) and we end up spinning in a loop forever in that interrupt due to a broken MCB chain.

So you're thinking of introducing something like `pcjr_memory_config` with the four options? (standard, expanded, enhanced, compatible) That seems a good idea.

**Comment by Jkapp76** [comment]
Yay! Space Quest 1 on PCJr!

And Roger only has his epic blond hair (Took a brown adjusted monitor setting). This blond hair trivia was really made popular by the creators of the fan-made SQ game "Space Quest The Lost Chapter".

I have no idea how to move Roger in the game, the arrow keys do not work on THIS game either.

I thought someone said Jumpman does not work with the settings for SQ1, but so far Jumpman works for me.

**Comment by Jkapp76** [comment]
Hold down shift while using the arrow keys to move. I wish caps lock would keep this going, but no.

And... The static sound at the beginning of SQ2 is clearly different than on Tandy when Roger is sweeping the floor. I like these little differences. The later static sounds are probably different too, like when the hovercraft runs out of gas.

I get excited with updates to PCJr and ancient stuff.

**Comment by weirddan455** [comment]
The arrow keys worked for me on SQ1.  You have to turn off numpad though.  For some reason on PCjr, numpad affects both the stand-alone arrow keys as well as the numpad arrow keys.  Turn off numlock and both with move the character.

**Comment by Jkapp76** [comment]
Setting machine to EGA seems to be the oldest setting that will shake the screen. Tandy or PCJr is best for probably everything with these games but is missing the screen shake feature. No single machine can have everything for these games.

**Comment by Jkapp76** [comment]
![image0001](https://github.com/dosbox-staging/dosbox-staging/assets/89743985/c7eaf92a-80c1-4977-a198-e0a6aeaa61ec)

I don't know if anyone will see this at this point, but I'm just posting this to show how much fuss was made over Roger's hair color being different between machines.
