### ISSUE TITLE
Crash on development build (v0.81.0-alpha-1668-g4c3db) when core is switched to dynamic

### ISSUE THREAD

**Issue by mckellenjaundice122** [dosbox-staging/dosbox-staging#2861]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Different version than latest?

v0.81.0-alpha-1668-g4c3db

### What Operating System are you using?

Windows 10

### Relevant hardware info

i5-7200U @ 2.50 GHz, 8 GB Ram, Intel HD 630

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

When dosbox switches the core either automatically or manually to dynamic, dosbox crashes. The log itself doesn't seem to point to much, other than it only seems to happen in the latest development build. Nothing at all in the config was changed besides core. This happens in both the MSYS2 and MSVC builds.

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Launch either a protected mode game or switch core to dynamic via command line or in the config file

### Provide a Log

```text
https://gist.github.com/mckellenjaundice122/9400531e294b88048678c31c8f1199a8
```

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by Kappa971** [comment]
I confirm that setting `core = dynamic` DOSBox crashes. Build 0.81.0-alpha-1659

**Comment by kcgen** [comment]
![2319](https://github.com/dosbox-staging/dosbox-staging/assets/1557255/33febcd4-f30e-4c26-9ff3-4fb33a9e14b1)

**Comment by kcgen** [comment]
@Kappa971 and @mckellenjaundice122, and anyone else on Win32/64: Can you try to isolate which PR caused this regression?

Here are the successful `main` builds starting with the current (which we know is bad), going back in time one PR at a time:

https://github.com/dosbox-staging/dosbox-staging/actions/workflows/windows-msys2.yml?query=branch%3Amain+event%3Apush+is%3Asuccess

Click back a couple pages in the list (say, 2 weeks ago) and find one that works.  If it works OK, then pick another build half-way in between.

Keep picking builds half-way in between your bad one and your good one to cut the list in half each time.

It should only take about 7 attempts to isolate it down (if using this half-way approach)

**Comment by weirddan455** [comment]
Or you can use `git bisect` to automate that process if you're building from source.

**Comment by Kappa971** [comment]
> @Kappa971 and @mckellenjaundice122, and anyone else on Win32/64: Can you try to isolate which PR caused this regression?
> 
> Here are the `main` builds starting with the current/latest, which we know is bad, going back in time, one PR at a time:
> 
> https://github.com/dosbox-staging/dosbox-staging/actions/workflows/windows-msys2.yml?query=branch%3Amain+event%3Apush+is%3Asuccess
> 
> Click back a couple pages in the list (say, 2 weeks ago) and find one that works. If it works OK, then pick another build half-way in between (say 1 week ago).
> 
> Keep picking builds half-way in between your bad one and your good one to cut the list in half each time. It should only take about 7 attempts to isolate it down (if using this half-way approach)

The crashes started from this build: https://github.com/dosbox-staging/dosbox-staging/actions/runs/6077262550

**Comment by kcgen** [comment]
@classilla, the x86-64 dynamic core has started crashing in the `main` branch, which @Kappa971 isolated to the recent PPC64le PR.

Do you have a Windows PC (or VM) you can poke around with a get it fixed up again?

**Comment by johnnovak** [comment]
> @classilla, the x86-64 dynamic core has started crashing in the `main` branch, which @Kappa971 isolated to the recent PPC64le PR.
> 
> Do you have a Windows PC (or VM) you can poke around with a get it fixed up again?

Great job narrowing that down, guys!

**Comment by johnnovak** [comment]
Raised PR @kcgen and @weirddan455. 
https://github.com/dosbox-staging/dosbox-staging/pull/2862

While it's ok for the dev build to be in flux, such fundamental breakages/regressions should be avoided at all costs—especially if the change only deals with something extremely niche like PPC support. This regression makes dev builds semi-unusable for Windows users; that's far from great.

Lesson learned, we should do far more thorough regression testing on stuff that changes fundamental aspects of the emulation.
