### ISSUE TITLE
Microsoft Flight Simulator 5.x video flickering regression (dev)

### ISSUE THREAD

**Issue by Grounded0** [dosbox-staging/dosbox-staging#2864]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Different version than latest?

Version 0.81.0-alpha (v0.81.0-alpha-1558-g55969d)

### What Operating System are you using?

macOS (Intel)

### If Other OS, please describe

macOS 12.6.5

### Relevant hardware info

2017 15" MacBook Pro

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Video flickers on displayed scenery when playing Microsoft Flight Simulator 5.x with development builds. It's a regression against 0.80.1.

Scenery was tested in Honolulu HI, Tokyo, Chicago IL and Los Angeles CA so its not a game issue.

Video recording:

https://github.com/dosbox-staging/dosbox-staging/assets/48192273/33ec0268-cb5a-4274-95f0-c12205118105

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Run Microsoft Flight Simulator 5.x with development builds
3. Observe flickering video in scenery view

### Your configuration

I haven't rebased my dosbox conf file for 0.81 dev.

```ini
[sdl]
fullscreen          = false
display             = 0
fullresolution      = desktop
windowresolution    = 1280x960
viewport_resolution = fit
window_position     = auto
window_decorations  = true
transparency        = 0
host_rate           = auto
vsync               = false
vsync_skip          = 7000
presentation_mode   = auto
output              = opengl
texture_renderer    = auto
waitonerror         = true
priority            = auto auto
mute_when_inactive  = false
pause_when_inactive = false
mapperfile          = mapper-v2.map
screensaver         = allow

[dosbox]
language           =
machine            = svga_s3
captures           = capture
memsize            = 32
mcb_fault_strategy = deny
vmemsize           = 4096
dos_rate           = default
vesa_modes         = compatible
speed_mods         = true
autoexec_section   = overwrite
automount          = false
startup_verbosity  = low
```

### Provide a Log

```text
2023-09-13 21:11:15.651 | MOUNT: Path '~/Misc/dosbox/c_drive' found
2023-09-13 21:11:15.652 | MOUNT: Path '~/Misc/images/iso/dosbox' found
2023-09-13 21:11:22.690 | IMGMOUNT: Path 'y:\msflight\msflight.iso' not found, maybe it's a DOS path
2023-09-13 21:11:22.692 | IMGMOUNT: Path 'MSFLIGHT\MSFLIGHT.ISO' found on virtual drive Y:
2023-09-13 21:11:22.698 | CDAUDIO: Operating at 48000 Hz without resampling
2023-09-13 21:11:22.844 | DISPLAY: SVGA 640x400 256-colour graphics mode at 69.755 Hz VFR, scaled to 2560x1920 with 1:1.2 (5:6) pixel aspect ratio
```

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by kcgen** [comment]
@FeralChild64, suprisingly this bisects the mouse limits per video-mode commit 31a0c4d.
- Previous commit (solid terrain): `git checkout 31a0c4d~`
- Affected commit (mouse flicker): `git checkout 31a0c4d`

Repro-pack inbound.

**Comment by FeralChild64** [comment]
Initial fix: https://github.com/dosbox-staging/dosbox-staging/tree/fc/flicker-fix-1 (but I am still investigating /testing it).

In order to fix mouse driver in some strange text modes, the `MOUSEDOS_AfterNewVideoMode` function was reworked - after the rework and internal `INT10_SetCurMode` call has appeared to refresh certain BIOS values. But if `MOUSEDOS_AfterNewVideoMode` is called within character generator functions, this call is definitely not needed (and harmful, breaking something the Microsoft Flight Simulator needs).

**Comment by Grounded0** [comment]
@FeralChild64 

The issue seems to have been resolved by `flicker-fix-1`. Thanks.
