### ISSUE TITLE
Auto integer scaling affects texture output

### ISSUE THREAD

**Issue by GranMinigun** [dosbox-staging/dosbox-staging#2865]
1) Launch DOSBox Staging with default configuration;
2) Switch `output` to `texture`;
3) Resize the window.

It appears that automatic integer scaling retains whatever it calculated for the last used shader instead of resetting for the new output. @johnnovak, as you've been tinkering around that area lately, think you could have a look?

**Comment by kcgen** [comment]
> It appears that automatic integer scaling retains whatever it calculated for the last used shader 

Additionally, it looks like even when in texture-mode, shaders are still active (so many some state isn't being passed through?)

![2023-09-13_11-27](https://github.com/dosbox-staging/dosbox-staging/assets/1557255/d59efec9-fc73-4d87-8ebe-1c61cd3d243e)

**Comment by johnnovak** [comment]
I'll have a look. I've done some testing with `texture` output now and then, but 90% of the time I'm testing with `opengl`. In any case, this is easy to fix, thanks for raising it @GranMinigun.

**Comment by KainXVIII** [comment]
For education purposes - how does texture output option differs from other like surface or opengl?

**Comment by johnnovak** [comment]
> For education purposes - how does texture output option differs from other like surface or opengl?

Surface has been removed; we only have the texture and OpenGL modes now.

Texture is basically a fallback mode we get cheaply (almost free) from SDL. It's only meant for people who don't have a somewhat functional OpenGL card 😄 

The huge difference is that `texture` mode does not support shaders, only `opengl` does. There's no reason to use texture mode, unless you're on some really underpowered or old hardware. It's just a fallback option.

**Comment by KainXVIII** [comment]
Thanks for the enlightenment!
