### ISSUE TITLE
Investigate playability issues with Abaron (1995)

### ISSUE THREAD

**Issue by kcgen** [dosbox-staging/dosbox-staging#2872]
### Context

Currently the eXoDOS project runs this game using [the DOSBox Daum fork](https://github.com/ykhwong/dosbox-svn-daum), which is understood to have specific emulation fixes not currently in upstream DOSBox (0.74.x and SVN) or active forks such as X, Pure, and Staging.

DOSBox Daum had 51 releases that included DOSBox SVN's commits ~r3600 through ~r3900, [spanning 2010 through 2015](http://ykhwong.x-y.net/).

### The goal of this ticket is to answer the following

Is Daum _still_ needed for this game?
- [ ] Does DOSBox SVN ([download latest](http://www.emucr.com/2023/09/dosbox-svn-r4483.html)) play it OK?
- [ ] Does DOSBox X ([download latest](https://dosbox-x.com/)) play it OK?
- [ ] Does DOSBox Staging ([download latest](https://dosbox-staging.github.io/downloads/development-builds/)) play it OK?

If Daum plays it better:
- [ ] What aspect is better?
- [ ] Which Daum release was the **_first_** to fix it?
    Use these builds [here](http://ykhwong.x-y.net/subpages/old.php) to narrow it down.

### How you can help

 1. Download the above lastest DOSBox SVN, X, and Staging builds.
 1. Ensure you have [eXoDOS v5](https://www.retro-exo.com/exodos.html) (or eventually v6)
 1. Find this game inside the eXoDOS installed folders (look for: `Abaron/`)
 1. Run the game using the DOSBox SVN, X, and Staging builds.
    _If it plays fine (everything looks, sounds, and handles OK) then simply indicate as such. Your task is done!_

If SVN, X, and Staging all have problems, then try it with Daum:
 1. Download the [first and last Daum releases](http://ykhwong.x-y.net/subpages/old.php).
    Note: _Daum had the most releases for Microsoft Windows, so having a Windows system (or VM) will help the most to answer the last question above._
 1. Does the latest Daum release play it correctly? If so: summarize/describe how it's better than DOSBox SVN, X, and Staging (screenshots, video, audio records all help too).
 1. Find the earliest (or oldest) Daum release that fixed it.
    1. Run the Daum release half way between the known good release (where the game playing correctly) and bad release (where the game doesn't playing correctly) until you've narrowed it down to adjacent releases.
    1. It will take _at-most_ seven runs of different Daum versions to narrow this down (using this middle-selecting technique); so it's not as daunting as it seems! :-)

---

### Follow up by code contributors

If Daum plays it better, your answers (especially the last one that narrows down the fix to a specific release) are critical to helping isolate the chunk of code fixed the given bug.

Pull requests should credit:
- @ykhwong as the original code author,
- the test team member who confirmed and isolated the Daum release,
- yourself (PR author) as integrating the fix

The PR should include the `imported-from:` URL pointing to DOSBox Daum. For an example, see commit a35c7c889.

**Comment by ebenbruyns** [comment]
This game is just stuck on the loading screen for me, but that happens in daum on linux and daum on wine. So that probably warrants more investigation. I'll drop more notes as I uncover more information

**Comment by Burrito78** [comment]
If it hangs on the loading screen, the CD isn't mounted. 

Works for me without issues in DOSBox Staging v0.81.0-alpha-1689-gae32 Mon, 18 Sep 2023.

Configuration was default, besides:
serial1       = mouse

I will close this if nobody objects.

**Comment by rderooy** [comment]
How does it behave with DOSBox 0.74-3 and DOSBox-X?
Do you need to set `serial1 = mouse`?

**Comment by Burrito78** [comment]
Can't get the mouse to work in DOSBox-SVN using 'serial1=directserial' ('mouse' and 'serialmouse' are no option in SVN) and screen is flickering.

Game is working fine when using DOSBox-X with 'serial1=serialmouse' but mouse movement is (too) slow compared to Staging.

**Comment by rderooy** [comment]
German language game (menus and speech). Luckily I understand German...

## DOSBox 0.74-3
As mentioned by @Burrito78 no mouse control

## DOSBox Daum
Crashes on startup (2nd game to do so?)
```
E_Exit: DRC64:Unhandled memory reference

ROMBIOS memory dump:
     0x000e0000-0x000f06ff free=1 
     0x000f0700-0x000f070d free=0 DOSBox vm86 hack
     0x000f070e-0x000f0fff free=1 
     0x000f1000-0x000f25ff free=0 DOSBox callbacks region
     0x000f2600-0x000fdfef free=1 
     0x000fdff0-0x000fdfff free=0 BIOS configuration (INT 15h AH=0xC0)
     0x000fe000-0x000fffef free=0 BIOS with fixed layout
[end dump]
TIMER: 1 leftover handlers (clean up!).
Exit to error: DRC64:Unhandled memory reference
```
## DOSBox Staging 0.80.1
No mouse with supplied config. As mentioned by @Burrito78 enabling serial mouse solves it.
```ini
[serial]
serial1=mouse
```
After that the game works fine.

## DOSBox-X 2023.09.01
No sound and no mouse. Mouse can be solved with:
```ini
[serial]
serial1=serialmouse
```

## DOSBox-X Git
Same as 2023.09.01

# dosbox.conf
```ini
# Config file for Dosbox-SVN Daum Jan 25, 2015
[sdl]
fullscreen=false
fulldouble=false
fullresolution=0x0
windowresolution=1280x960
output=direct3d
mapperfile=mapper.map
usescancodes=true
[dosbox]
machine=svga_s3
memsize=16
[render]
aspect=true
scaler=normal2x
[cpu]
core=auto
cputype=auto
cycles=40000
[mixer]
[midi]
[sblaster]
[gus]
gus=true
[speaker]
disney=true
[joystick]
[serial]
[dos]
[ipx]
[autoexec]
mount c .\eXoDOS\Abaron
imgmount d .\eXoDOS\Abaron\CD\Abaron.iso -t cdrom
c:
@cd Abaron
@cls
@abaron
exit
```

**Comment by rderooy** [comment]
I think this can be closed. Just enable serial mouse support with Staging.

**Comment by rderooy** [comment]
Comments updated above with joystick support (Staging seems to have an issue there, compared to DOSBox-X).

**Comment by rderooy** [comment]
If anyone needs some hints for the German selection menu...
At the intro press ESC until you get a menu screen.

- "Neues Spiel" == New Game
- "Spiel Laden" == Load game
- "Spieler" == Player
- "Musik" == Music
- "Geräusch" == Noise (sound effects)
- "Bildrate" == Refresh rate
- "Beenden" == Exit
- "Schwierigkeit" == Difficulty

Options:
- "Maus" == Mouse
- "An" == On
- "Aus" == Off


![image](https://github.com/dosbox-staging/dosbox-staging/assets/17701098/8d42f17a-cd68-4700-8e86-972ac30dcc17)

**Comment by Grounded0** [comment]
Reopening this for the joystick issue.

**Comment by Grounded0** [comment]
Agreed. Thanks.
