### ISSUE TITLE
Investigate playability issues with Backroad Racers (1993)

### ISSUE THREAD

**Issue by kcgen** [dosbox-staging/dosbox-staging#2878]
### Context

Currently the eXoDOS project runs this game using [the DOSBox Daum fork](https://github.com/ykhwong/dosbox-svn-daum), which is understood to have specific emulation fixes not currently in upstream DOSBox (0.74.x and SVN) or active forks such as X, Pure, and Staging.

DOSBox Daum had 51 releases that included DOSBox SVN's commits ~r3600 through ~r3900, [spanning 2010 through 2015](http://ykhwong.x-y.net/).

### The goal of this ticket is to answer the following

Is Daum _still_ needed for this game?
- [ ] Does DOSBox SVN ([download latest](http://www.emucr.com/2023/09/dosbox-svn-r4483.html)) play it OK?
- [ ] Does DOSBox X ([download latest](https://dosbox-x.com/)) play it OK?
- [ ] Does DOSBox Staging ([download latest](https://dosbox-staging.github.io/downloads/development-builds/)) play it OK?

If Daum plays it better:
- [ ] What aspect is better?
- [ ] Which Daum release was the **_first_** to fix it?
    Use these builds [here](http://ykhwong.x-y.net/subpages/old.php) to narrow it down.

### How you can help

 1. Download the above lastest DOSBox SVN, X, and Staging builds.
 1. Ensure you have [eXoDOS v5](https://www.retro-exo.com/exodos.html) (or eventually v6)
 1. Find this game inside the eXoDOS installed folders (look for: `BRdRace/`)
 1. Run the game using the DOSBox SVN, X, and Staging builds.
    _If it plays fine (everything looks, sounds, and handles OK) then simply indicate as such. Your task is done!_

If SVN, X, and Staging all have problems, then try it with Daum:
 1. Download the [first and last Daum releases](http://ykhwong.x-y.net/subpages/old.php).
    Note: _Daum had the most releases for Microsoft Windows, so having a Windows system (or VM) will help the most to answer the last question above._
 1. Does the latest Daum release play it correctly? If so: summarize/describe how it's better than DOSBox SVN, X, and Staging (screenshots, video, audio records all help too).
 1. Find the earliest (or oldest) Daum release that fixed it.
    1. Run the Daum release half way between the known good release (where the game playing correctly) and bad release (where the game doesn't playing correctly) until you've narrowed it down to adjacent releases.
    1. It will take _at-most_ seven runs of different Daum versions to narrow this down (using this middle-selecting technique); so it's not as daunting as it seems! :-)

---

### Follow up by code contributors

If Daum plays it better, your answers (especially the last one that narrows down the fix to a specific release) are critical to helping isolate the chunk of code fixed the given bug.

Pull requests should credit:
- @ykhwong as the original code author,
- the test team member who confirmed and isolated the Daum release,
- yourself (PR author) as integrating the fix

The PR should include the `imported-from:` URL pointing to DOSBox Daum. For an example, see commit a35c7c889.

**Comment by rderooy** [comment]
The eXoDOS setup boots a DOS image with CD-ROM support, which only works in DOSBox variants with IDE emulation.

## DOSBox 0.74-3
Lacks IDE emulation

## DOSBox Daum
Crash on startup (again "E_Exit: DRC64:Unhandled memory reference")

## DOSBox Staging 0.80.1
Seems to work fine

## DOSBox 2023.09.01
Seems to work fine

# dosbox.conf
```ini
# Config file for Dosbox-SVN Daum Jan 25, 2015
[sdl]
fullscreen=false
fulldouble=false
fullresolution=0x0
windowresolution=1280x960
output=direct3d
mapperfile=mapper.map
usescancodes=true
[dosbox]
machine=svga_s3
memsize=63
[render]
aspect=true
scaler=normal2x
[cpu]
core=auto
cputype=auto
cycles=20000
[pci]
[mixer]
prebuffer=25
[midi]
mididevice=mt32
[sblaster]
sbtype=sbpro1
[gus]
[speaker]
disney=true
[joystick]
[serial]
[dos]
[ipx]
[ide, primary]
[ide, secondary]
[ide, tertiary]
enable=true
[ide, quaternary]
enable=true
[autoexec]
@imgmount c .\eXoDOS\BRdRace\i50_101.img
@imgmount d .\eXoDOS\BRdRace\cd\BACKROAD.cue -t iso -fs iso -ide 2m
cls
@boot -l c
exit
```

**Comment by johnnovak** [comment]
@rderooy Are you testing with the Daum build from eXoDOS? I think you should test with that exact binary, otherwise the comparisons are a bit pointless (e.g. what if a later Daum version has regressed in some areas).

These "crashes on Daum" reports are suspicious; surely these games work with the bundled eXoDOS Daum build?

**Comment by rderooy** [comment]
No, I'm testing with the flatpak daum build, that I build locally. The eXoDOS binaries are for Windows afterall.

**Comment by johnnovak** [comment]
> No, I'm testing with the flatpak daum build, that I build locally. The eXoDOS binaries are for Windows afterall.

Ok, I guess I'm questioning the value of that as I'm pretty sure these games just run fine on Windows with the bundled Daum build. So we're not really doing an exact comparison here if that's true. But, I guess if they just run in fine in Staging that's good enough, even without the comparison.

**Comment by Torinde** [comment]
Comment from the "Investigate compatibility" issue, kind of addressed already above:
> CDROM and C:\ image mountable together.
Without Daum need to use HDD-image containing CDROM image mounted w/ SHSUCDX (See [1](https://www.vogons.org/viewtopic.php?t=34767) and [2](http://adoxa.altervista.org/shsucdx/index.htm))

**Comment by johnnovak** [comment]
> Comment from the "Investigate compatibility" issue, kind of addressed already above:
> 
> > CDROM and C:\ image mountable together.
> > Without Daum need to use HDD-image containing CDROM image mounted w/ SHSUCDX (See [1](https://www.vogons.org/viewtopic.php?t=34767) and [2](http://adoxa.altervista.org/shsucdx/index.htm))

I'm confused, where is this info coming from @Torinde ? Not from this ticket.

**Comment by rderooy** [comment]
I tested it with the eXeDOS provided Daum running under Wine. And it seems to work fine.

I also tried playing it from a folder mount, instead of the imgmount with DOSBox Staging Git and DOSBox-X Git. And that seems to work fine. Except... that after taking too much damage, where you get someone making fun of you through the window, there was no speech.

I think the dosbox.conf file could be minimised significantly. Options like mididevice=, disney=, ide* are really not needed.

**Comment by rderooy** [comment]
Ok, found what is going on. This game actually needs a specific driver loaded "SBPDD.SYS" for FMVs, and that is why you need to boot DOS, unless you have another way of loading a device driver.
https://www.vogons.org/viewtopic.php?t=34767

I was able to load the driver in DOSBox-X as such, but still no sound from the FMVs.
```
[config]
install=MOUNT.COM C: .
device=C:\BACKROAD\SYSTEM\SBPDD.SYS
```

This is what the driver prints on boot:
```
 Sound Blaster Adapter Device Driver
 (C) Copyright IBM Corp. 1990, 1991.  ALL RIGHTS RESERVED.
 IBM Multimedia Systems, Austin.
 (C) Copyright CREATIVE LABS,INC. 1989, 1991, 1992.  ALL RIGHTS RESERVED.
 Version 2.0 SB/SBPRO

 Installed as device AUDIO1, interrupt level 7, I/O address 0x220, dma ch. 1 .
```

**Comment by johnnovak** [comment]
> This game actually needs a specific driver loaded "SBPDD.SYS" for FMVs, and that is why you need to boot DOS, unless you have another way of loading a device driver.

That's great info @rderooy, thanks for getting to the bottom of this. We need to let Python and eXo now that Staging can also boot real DOS from HDD images to make this work, not sure if they're aware.

**Comment by Torinde** [comment]
> I'm confused, where is this info coming from @Torinde ? Not from this ticket.

It's from here: #804

**Comment by Grounded0** [comment]
We actually can load device drivers without booting into real DOS with this. Its DEVICE.COM pulled from late DR-DOS:

https://anttipeltola.eu/misc/files/DEVICE.COM.zip

**Comment by Grounded0** [comment]
Adding to Problematic games with DOSBox Staging due to audio in FMVs not working.

**Comment by rderooy** [comment]
@Grounded0 I tried using DEVICE.COM, just like I tried using DOSBox-X's ability to load device drivers. While the driver loaded in both cases, there was no sound from the FMV clips in either case.

**Comment by Python-Exoproject** [comment]
I just tested using Staging 81 with the autoexec section from our current Daum setup and it worked, sound in FMV and all. Im happily surprised as this was one we thought would be bottom of the pile for Staging compatibility, thanks guys for all the work

From our end happy for this to close
