### ISSUE TITLE
Investigate playability issues with City (1989)

### ISSUE THREAD

**Issue by kcgen** [dosbox-staging/dosbox-staging#2880]
### Context

Currently the eXoDOS project runs this game using [the DOSBox Daum fork](https://github.com/ykhwong/dosbox-svn-daum), which is understood to have specific emulation fixes not currently in upstream DOSBox (0.74.x and SVN) or active forks such as X, Pure, and Staging.

DOSBox Daum had 51 releases that included DOSBox SVN's commits ~r3600 through ~r3900, [spanning 2010 through 2015](http://ykhwong.x-y.net/).

### The goal of this ticket is to answer the following

Is Daum _still_ needed for this game?
- [ ] Does DOSBox SVN ([download latest](http://www.emucr.com/2023/09/dosbox-svn-r4483.html)) play it OK?
- [ ] Does DOSBox X ([download latest](https://dosbox-x.com/)) play it OK?
- [ ] Does DOSBox Staging ([download latest](https://dosbox-staging.github.io/downloads/development-builds/)) play it OK?

If Daum plays it better:
- [ ] What aspect is better?
- [ ] Which Daum release was the **_first_** to fix it?
    Use these builds [here](http://ykhwong.x-y.net/subpages/old.php) to narrow it down.

### How you can help

 1. Download the above lastest DOSBox SVN, X, and Staging builds.
 1. Ensure you have [eXoDOS v5](https://www.retro-exo.com/exodos.html) (or eventually v6)
 1. Find this game inside the eXoDOS installed folders (look for: `City89/`)
 1. Run the game using the DOSBox SVN, X, and Staging builds.
    _If it plays fine (everything looks, sounds, and handles OK) then simply indicate as such. Your task is done!_

If SVN, X, and Staging all have problems, then try it with Daum:
 1. Download the [first and last Daum releases](http://ykhwong.x-y.net/subpages/old.php).
    Note: _Daum had the most releases for Microsoft Windows, so having a Windows system (or VM) will help the most to answer the last question above._
 1. Does the latest Daum release play it correctly? If so: summarize/describe how it's better than DOSBox SVN, X, and Staging (screenshots, video, audio records all help too).
 1. Find the earliest (or oldest) Daum release that fixed it.
    1. Run the Daum release half way between the known good release (where the game playing correctly) and bad release (where the game doesn't playing correctly) until you've narrowed it down to adjacent releases.
    1. It will take _at-most_ seven runs of different Daum versions to narrow this down (using this middle-selecting technique); so it's not as daunting as it seems! :-)

---

### Follow up by code contributors

If Daum plays it better, your answers (especially the last one that narrows down the fix to a specific release) are critical to helping isolate the chunk of code fixed the given bug.

Pull requests should credit:
- @ykhwong as the original code author,
- the test team member who confirmed and isolated the Daum release,
- yourself (PR author) as integrating the fix

The PR should include the `imported-from:` URL pointing to DOSBox Daum. For an example, see commit a35c7c889.

**Comment by Burrito78** [comment]
Password is GoldDust.

Results (macOS Ventura 13.5.2/Apple M2):

DOSBox Staging	All OK
DOSBox SVN		All OK
DOSBox-X		All OK

I don't run Windows so i can't test with Daum.

**Comment by Burrito78** [comment]
@rderooy Do you want to take a look before we close this one?

**Comment by rderooy** [comment]
Financial markets simulation game - fully text mode

As it is such an exciting game, I will skip going over all the usual DOSBox variants. As listed below DOSBox 0.74-3 has some type of input buffering issue, which is why Daum is being used.

@Burrito78 already showed that Staging, SVN and X works. As such closing this.

# DOSBox 0.74-3
Very unresponsive to inputs

# DOSBox Daum - eXoDOS included version
Works fine

# eXoDOS dosbox.conf
```ini
# Config file for Dosbox-SVN Daum Jan 25, 2015
[sdl]
fullscreen=false
fulldouble=false
fullresolution=0x0
windowresolution=1280x960
output=direct3d
mapperfile=mapper.map
usescancodes=true
[dosbox]
machine=svga_s3
memsize=16
[render]
aspect=true
scaler=normal2x
[cpu]
core=auto
cputype=auto
cycles=100
[mixer]
[midi]
[sblaster]
[gus]
gusrate=44100 start
[speaker]
disney=true
[joystick]
[serial]
[dos]
[ipx]
[autoexec]
@echo off
mount c .\eXoDOS\City89
c:
@cls
echo.
echo The password is GoldDust
echo.
pause
@city
exit
```
