### ISSUE TITLE
Investigate playability issues with Crazy Brix (1999)

### ISSUE THREAD

**Issue by kcgen** [dosbox-staging/dosbox-staging#2881]
### Context

Currently the eXoDOS project runs this game using [the DOSBox Daum fork](https://github.com/ykhwong/dosbox-svn-daum), which is understood to have specific emulation fixes not currently in upstream DOSBox (0.74.x and SVN) or active forks such as X, Pure, and Staging.

DOSBox Daum had 51 releases that included DOSBox SVN's commits ~r3600 through ~r3900, [spanning 2010 through 2015](http://ykhwong.x-y.net/).

### The goal of this ticket is to answer the following

Is Daum _still_ needed for this game?
- [ ] Does DOSBox SVN ([download latest](http://www.emucr.com/2023/09/dosbox-svn-r4483.html)) play it OK?
- [ ] Does DOSBox X ([download latest](https://dosbox-x.com/)) play it OK?
- [ ] Does DOSBox Staging ([download latest](https://dosbox-staging.github.io/downloads/development-builds/)) play it OK?

If Daum plays it better:
- [ ] What aspect is better?
- [ ] Which Daum release was the **_first_** to fix it?
    Use these builds [here](http://ykhwong.x-y.net/subpages/old.php) to narrow it down.

### How you can help

 1. Download the above lastest DOSBox SVN, X, and Staging builds.
 1. Ensure you have [eXoDOS v5](https://www.retro-exo.com/exodos.html) (or eventually v6)
 1. Find this game inside the eXoDOS installed folders (look for: `CrazBrix/`)
 1. Run the game using the DOSBox SVN, X, and Staging builds.
    _If it plays fine (everything looks, sounds, and handles OK) then simply indicate as such. Your task is done!_

If SVN, X, and Staging all have problems, then try it with Daum:
 1. Download the [first and last Daum releases](http://ykhwong.x-y.net/subpages/old.php).
    Note: _Daum had the most releases for Microsoft Windows, so having a Windows system (or VM) will help the most to answer the last question above._
 1. Does the latest Daum release play it correctly? If so: summarize/describe how it's better than DOSBox SVN, X, and Staging (screenshots, video, audio records all help too).
 1. Find the earliest (or oldest) Daum release that fixed it.
    1. Run the Daum release half way between the known good release (where the game playing correctly) and bad release (where the game doesn't playing correctly) until you've narrowed it down to adjacent releases.
    1. It will take _at-most_ seven runs of different Daum versions to narrow this down (using this middle-selecting technique); so it's not as daunting as it seems! :-)

---

### Follow up by code contributors

If Daum plays it better, your answers (especially the last one that narrows down the fix to a specific release) are critical to helping isolate the chunk of code fixed the given bug.

Pull requests should credit:
- @ykhwong as the original code author,
- the test team member who confirmed and isolated the Daum release,
- yourself (PR author) as integrating the fix

The PR should include the `imported-from:` URL pointing to DOSBox Daum. For an example, see commit a35c7c889.

**Comment by kcgen** [comment]
Same results as you, @Burrito78 - confirmed on Linux.

It's a rough experience all round, but it's nice we've got some differences actually showing up in circa-2015 Daum that roughly match how X behaves. 

Unfortunately I can't find a recording on actual hardware, so it's hard to tell if Daum is showing more accurate behavior.  If it is, there's some useful video (blanking vs. shaking).

Staging and SVN:

https://github.com/dosbox-staging/dosbox-staging/assets/1557255/1418a487-c9c0-4439-9d2c-1913958232b5

circa-2015 Daum (Linux) and latest -X

https://github.com/dosbox-staging/dosbox-staging/assets/1557255/bf49e5f1-386f-4c32-beec-06b6d08dbc2b

**Comment by johnnovak** [comment]
@kcgen I can (and will) try these games on hardware to make sure we're not chasing our tails and going around in circles. Luckily, they're all late DOS era games so my MMX 200 is the perfect match for them. "PaybackTime 2 (1997)" is the other one. I guess I'll wait a few days then test a bunch of them in one go, maybe even create recordings of the music, etc.

**Comment by ebenbruyns** [comment]
Just on the screen shaking from left to right, it doesn't happen on the daum versrion in wine, it blinks. I just thought I'd throw that variation in as it might become a clue later on.

**Comment by kcgen** [comment]
> Just on the screen shaking from left to right, it doesn't happen on the daum versrion in wine, it blinks. I just thought I'd throw that variation in as it might become a clue later on.

Thanks for the confirmation @ebenbruyns!

Does it roughly look like the blinking in the second video, above? https://github.com/dosbox-staging/dosbox-staging/issues/2881#issuecomment-1728660899

**Comment by ebenbruyns** [comment]
> > Just on the screen shaking from left to right, it doesn't happen on the daum versrion in wine, it blinks. I just thought I'd throw that variation in as it might become a clue later on.
> 
> Thanks for the confirmation @ebenbruyns!
> 
> Does it roughly look like the blinking in the second video, above? [#2881 (comment)](https://github.com/dosbox-staging/dosbox-staging/issues/2881#issuecomment-1728660899)

Sorry for the slow reply, yes it looks like that.

**Comment by Burrito78** [comment]
DOSBox-X looks the same too.

**Comment by Python-Exoproject** [comment]
I think #3597 fixes this one as well.

I used Staging 82.0a with cycles 70000 and vmem_delay of 2000 and seems to play at a constant smooth speed

**Comment by johnnovak** [comment]
> @johnnovak I think #3597 fixes this one as well.
> 
> I used Staging 82.0a with cycles 70000 and vmem_delay of 2000 and seems to play at a constant smooth speed

Great news @Python-Exoproject! 🎉 Great to see the feature reaping dividends 🥳

If you stumble across more games that are helped by `vmem_delay`, please continue pinging me on the issue tickets or send me a PM on Discord. Then we can add them to our [Game issues](https://github.com/dosbox-staging/dosbox-staging/wiki/Game-issues) wiki page.

Thanks, man! 😎
