### ISSUE TITLE
Investigate playability issues with DREAMS to Reality (1997)

### ISSUE THREAD

**Issue by kcgen** [dosbox-staging/dosbox-staging#2888]
### Context

Currently the eXoDOS project runs this game using [the DOSBox Daum fork](https://github.com/ykhwong/dosbox-svn-daum), which is understood to have specific emulation fixes not currently in upstream DOSBox (0.74.x and SVN) or active forks such as X, Pure, and Staging.

DOSBox Daum had 51 releases that included DOSBox SVN's commits ~r3600 through ~r3900, [spanning 2010 through 2015](http://ykhwong.x-y.net/).

### The goal of this ticket is to answer the following

Is Daum _still_ needed for this game?
- [ ] Does DOSBox SVN ([download latest](http://www.emucr.com/2023/09/dosbox-svn-r4483.html)) play it OK?
- [ ] Does DOSBox X ([download latest](https://dosbox-x.com/)) play it OK?
- [ ] Does DOSBox Staging ([download latest](https://dosbox-staging.github.io/downloads/development-builds/)) play it OK?

If Daum plays it better:
- [ ] What aspect is better?
- [ ] Which Daum release was the **_first_** to fix it?
    Use these builds [here](http://ykhwong.x-y.net/subpages/old.php) to narrow it down.

### How you can help

 1. Download the above lastest DOSBox SVN, X, and Staging builds.
 1. Ensure you have [eXoDOS v5](https://www.retro-exo.com/exodos.html) (or eventually v6)
 1. Find this game inside the eXoDOS installed folders (look for: `DREAMSto/`)
 1. Run the game using the DOSBox SVN, X, and Staging builds.
    _If it plays fine (everything looks, sounds, and handles OK) then simply indicate as such. Your task is done!_

If SVN, X, and Staging all have problems, then try it with Daum:
 1. Download the [first and last Daum releases](http://ykhwong.x-y.net/subpages/old.php).
    Note: _Daum had the most releases for Microsoft Windows, so having a Windows system (or VM) will help the most to answer the last question above._
 1. Does the latest Daum release play it correctly? If so: summarize/describe how it's better than DOSBox SVN, X, and Staging (screenshots, video, audio records all help too).
 1. Find the earliest (or oldest) Daum release that fixed it.
    1. Run the Daum release half way between the known good release (where the game playing correctly) and bad release (where the game doesn't playing correctly) until you've narrowed it down to adjacent releases.
    1. It will take _at-most_ seven runs of different Daum versions to narrow this down (using this middle-selecting technique); so it's not as daunting as it seems! :-)

---

### Follow up by code contributors

If Daum plays it better, your answers (especially the last one that narrows down the fix to a specific release) are critical to helping isolate the chunk of code fixed the given bug.

Pull requests should credit:
- @ykhwong as the original code author,
- the test team member who confirmed and isolated the Daum release,
- yourself (PR author) as integrating the fix

The PR should include the `imported-from:` URL pointing to DOSBox Daum. For an example, see commit a35c7c889.

**Comment by Grounded0** [comment]
Will be reviewed soon.

**Comment by Burrito78** [comment]
Results (macOS Ventura 13.5.2/Apple M2):

**DOSBox Staging 0.81.0-alpha-1689**
Intro video is juddery/tearing, probably because the game is loading univbe.drv during start.
NoUniVBE doesn't work, game gives an error that UniVBE couldn't be loaded.
Gameplay is fine.

**DOSBox SVN	snapshot 12.09.23**
Intro juddering/tearing, aspect ratio is very wide.
Gameplay is tearing heavily and aspect ratio is also very, very wide.

**DOSBox-X v2023.09.01**
Intro video is juddery/tearing, probably because the game is loading univbe.drv during start.
Gameplay is tearing heavily.

I don't run Windows so i can't test with Daum.

**Comment by johnnovak** [comment]
Looks like Staging is consistently winning in most of these comparisons 😎 🤘🏻

**Comment by GranMinigun** [comment]
Please make sure both software and Glide (3dfx, Voodoo, whatever) modes work.

**Comment by Burrito78** [comment]
I Glide enabled in DEV builds?

**Comment by Grounded0** [comment]
This is an AAA game so spend extra resources on this.

**Comment by GranMinigun** [comment]
> I Glide enabled in DEV builds?

Voodoo emulation is unconditionally compiled, yes. You may need to enable it in the configuration though.

**Comment by johnnovak** [comment]
> > I Glide enabled in DEV builds?
> 
> Voodoo emulation is unconditionally compiled, yes. You may need to enable it in the configuration though.

I think it's enabled by default.

**Comment by Burrito78** [comment]
Voodoo doesn't work, 3Dfx logo is spinning and then the game hangs.

![Bildschirmfoto 2023-09-22 um 11 24 48](https://github.com/dosbox-staging/dosbox-staging/assets/61995128/9eb67cf2-60bd-4f99-86ad-d4c71b1c59b4)

**Comment by kcgen** [comment]
Hmm.. maybe a regression.
I tested this game with the voodoo branch before merge: https://github.com/dosbox-staging/dosbox-staging/pull/2410#issuecomment-1523808076

**Comment by rderooy** [comment]
eXoDOS v5 packaging includes a win32 version of CHOICE.EXE that I deleted to prevent issues.

Comes with two very extensive dosbox config files (dosbox.conf and dosbox_ece.conf), that are too long to add here. The ECE one is setup for 3dfx.

## DOSBox 0.74-3
- Using dosbox.conf: Starts the game in a strange video mode. Basically the image is vertically squashed.

![dreams_000](https://github.com/dosbox-staging/dosbox-staging/assets/17701098/a44dbca3-8c3c-4be6-ab92-a3a0e0ab7bd1)

## DOSBox ECE r4230 - eXoDOS included edition
- Using dosbox.conf: Intro animation is not as smooth as Daum
- Using dosbox_ece.conf: 3dfx logo on startup, smooth intro, game plays fine

## DOSBox Daum - eXoDOS included edition
- Using dosbox.conf: Seems to work fine
- Using dosbox_ece.conf: Black screen but based on sound, the game is running

## DOSBox Staging 0.80.1
- Using dosbox.conf: Intro was graphically not as smooth as Daum
- Using dosbox_ece.conf: No 3dfx logo, and the intro was not smooth. Most likely the 3dfx detection failed.

## DOSBox-X 2023.09.01
- Using dosbox.conf: DOSBox-X Segfault on startup. Same with the latest git code.
- Using dosbox_ece.conf: works fine (like DOSBox ECE)

**Comment by kcgen** [comment]
3Dfx version is running OK on Staging:

https://github.com/dosbox-staging/dosbox-staging/assets/1557255/f178c5e7-d194-4775-81ab-84d171aa5a30

1. Started Staging `main` with defaults (`--noprimaryconf`)
1. Removed the local `XCOPY.EXE`
    (this in the bundled `Y:` tools, which is mounted and in the PATH by default)
1. Deleted the local `CRYO` tree.
1. Did a fresh install from CD:
    - Selected `auto` for the sound card (SB16)
    - At the `GETKEY` prompt, selected 'No' to ensure a full install is performed

1. Started it with this conf (soon the 60 Hz will be default for Voodoo):

```ini
[dosbox]
memsize = 128
dos_rate = 60
startup_verbosity = quiet

[render]
aspect = off

[cpu]
cycles = 60000

[dos]
umb = off
ems = off
xms = off

[midi]
mididevice = off

[speaker]
pcspeaker = off

[sblaster]
sbtype = sb16
sb_filter = sb16

[mixer]
reverb = large
chorus = on

[voodoo]
voodoo_memsize = 4
voodoo_perf = 3

[autoexec]
@echo off
imgmount d "cd/*.cue" -t cdrom
mount c .
c:
cd cryo\dreams
dreamsfx
```

**Comment by kcgen** [comment]
The game is really nice and polished. Press `F10` for all the hotkeys in a single page.

**Comment by Python-Exoproject** [comment]
3DFX works find in staging, but the juddery intro cinematic in all forks other than Daum is why we are using Daum for the non 3DFX launch choice. Is this something that can be fixed in staging or does Daum need to be kept?

**Comment by Grounded0** [comment]
Let's see what we can do about it.

**Comment by Python-Exoproject** [comment]
Appreciated. If you are using exodos v6 for testing it seems we broke the launch of this specific game with a last minute tweak we made to our games that use exception.bat. Replace exception.bat (found in \eXoDOS\!dos\DREAMSto) with this one: [exception.zip](https://github.com/dosbox-staging/dosbox-staging/files/13489459/exception.zip)

**Comment by kcgen** [comment]
If cycles are limited around 70000 or below, the video plays smooth, however in-game frame rates will be a bit sluggish. This where the Syndicate one-big-cycle up/down step would be a decent work-around (to pump up cycles to say, 150,000 in-game).

But yeah - there's still some Daum mystique remaining!

Daum unfortunately crashes on Linux when starting the game:

```text
DOS_FreeMemory(seg=0x0171)
DOS_FreeMemory(seg=0x04e9)
E_Exit: DRC64:Unhandled memory reference

ROMBIOS memory dump:
     0x000e0000-0x000f06ff free=1 
     0x000f0700-0x000f070d free=0 DOSBox vm86 hack
     0x000f070e-0x000f0fff free=1 
     0x000f1000-0x000f25ff free=0 DOSBox callbacks region
     0x000f2600-0x000fdfef free=1 
     0x000fdff0-0x000fdfff free=0 BIOS configuration (INT 15h AH=0xC0)
     0x000fe000-0x000fffef free=0 BIOS with fixed layout
[end dump]
TIMER: 1 leftover handlers (clean up!).
Exit to error: DRC64:Unhandled memory reference
```

I've inspected Daum's S3 clock rates and the register values that feed it, and it's identical.

Still needed to check:

- Calculated custom VESA refresh rate.  The game tweaks the 640x400 VESA mode prior to video playback and actually get a refresh rate of 35 Hz.

    `DISPLAY: VESA 640x400 16-bit high colour graphics mode at 35.69 Hz`

- horizonal and vertical timing values after the mode is set (in `vga_draw`). 

- row-by-row drawing timing in `vga_draw`. In Daum, chek  `PIC_..` call for both VGA and EGA.  Daum has slightly delayed draw timings from these examples:
    - EGA game 'Hostage', Daum doesn't flicker during the intro.
    - VGA 320x200 game 'Inca' (CDDA release), press F1 to play the ~5 minute intro until the music stops playing. Daum lets the video sequence play for a longer duration allowing the CDDA music to finish perfectly with actual hardware recordings on youtube, where as non-Daum the video sequence finishes a bit earlier (maybe about 10 seconds earlier).

If anyone wants to poke around with this, checkout the `remotes/origin/forks/daum-scm-restoration` branch. It compiles on macOS and Linux, and logging messages can easily added!

**Comment by kcgen** [comment]
Very interesting @johnnovak!
In the S3 clock rate calculation (`SVGA_S3_GetClock`), the game does request the division-by-2 bit via the PLL control 2 register, producing a clock rate of ~280-some MHz instead of 500+ MHz.  However - even this is identical to what Daum gets. 

Could 35 Hz progressive be something like ~70 Hz interlaced?

**Comment by johnnovak** [comment]
> Could 35 Hz be interlaced? The actual video frame rate is very poor; I would say the content itself only runs at about half of 35 Hz.

(S)VGA monitors don't normally do any interlacing. Think about it, PC monitors were designed for business and office use. No one could have sold a monitor that exhibited any interlace flicker...

About 35 Hz vertical refresh, if that's calculated from the timings, then the code that calculates it is buggy, simple as that. No (S)VGA monitor is able to sync below 50 Hz, that's just not possible. The usual vertical sync range is between from 50 Hz to 85-140 Hz for SVGA monitors.

So don't let that weirdness make you explore weird tangents—that's most definitely bug, the real refresh rate is most likely 70 Hz, and that "divide by 2" thing is some bug.

Here's a random specs spot-check to prove it (I happen to own two of these models, btw)

- Samsung SyncMaster 15GLe ([source](https://www.manualslib.com/manual/316416/Samsung-Syncmaster-15gle.html?page=17#manual))

![image](https://github.com/dosbox-staging/dosbox-staging/assets/698770/b17c93bc-98ad-41cd-8711-41f7f9faf102)

- Compaq S710 ([source](https://www.manualslib.com/manual/1785180/Compaq-S710.html?page=15#manual))

![image](https://github.com/dosbox-staging/dosbox-staging/assets/698770/06c37659-d9fb-4148-a267-f4e832dd5d26)

- Compaq 5500 ([source](https://www.manualslib.com/manual/30062/Compaq-7500-Series.html?page=24#manual))

![image](https://github.com/dosbox-staging/dosbox-staging/assets/698770/5145d161-ea3f-4108-b3ae-2eb506da7737)

**Comment by kcgen** [comment]
> About 35 Hz vertical refresh, if that's calculated from the timings, then the code that calculates it is buggy, simple as that. No (S)VGA monitor is able to sync below 50 Hz, that's just not possible. The usual vertical sync range goes from 50 Hz to 85-140 Hz on SVGA monitors.

Sounds like we need to inspect that S3 clock calculation and the other CRTC registers values that all factor into the fps calculation.

**Comment by kcgen** [comment]
The game relies on UVCONFIG as its VBE 2.0 interface.

Playing with some different rates can get us to a relatively acceptable point (although these are just hacks), but at least this is more evidence that the frame rate calculation is off.

@Python-Exoproject, if you want to try this work-around, this zip [DREAMSto-60Hz-VBE.zip](https://github.com/dosbox-staging/dosbox-staging/files/13508228/DREAMSto-60Hz-VBE.zip) contains `UNIVBE.DRV` and `UVCONFIG.DAT` that you can place in your `DREAMSto/cryo/dreams/data/univbe` directory. 

Then set the following in your conf:

```ini
[dosbox]
dos_rate = 91

[cpu]
cycles = 130000
```

Here's the first ~90 seconds of the intro sequence running at 130,000 cycles, which also produces smooth frame rates in-game:

https://github.com/dosbox-staging/dosbox-staging/assets/1557255/113ccfb8-b4f2-43bb-bbcb-e51fb8242b06

**Comment by Grounded0** [comment]
@Python-Exoproject 

Has this issue now been resolved or do you think the offered solution is still unsatisfactory in some way?

**Comment by Python-Exoproject** [comment]
Resolved thank you
