### ISSUE TITLE
Investigate playability issues with Virtual Pool (1995)

### ISSUE THREAD

**Issue by kcgen** [dosbox-staging/dosbox-staging#2891]
### Context

Currently the eXoDOS project runs this game using [the DOSBox Daum fork](https://github.com/ykhwong/dosbox-svn-daum), which is understood to have specific emulation fixes not currently in upstream DOSBox (0.74.x and SVN) or active forks such as X, Pure, and Staging.

DOSBox Daum had 51 releases that included DOSBox SVN's commits ~r3600 through ~r3900, [spanning 2010 through 2015](http://ykhwong.x-y.net/).

### The goal of this ticket is to answer the following

Is Daum _still_ needed for this game?
- [ ] Does DOSBox SVN ([download latest](http://www.emucr.com/2023/09/dosbox-svn-r4483.html)) play it OK?
- [ ] Does DOSBox X ([download latest](https://dosbox-x.com/)) play it OK?
- [ ] Does DOSBox Staging ([download latest](https://dosbox-staging.github.io/downloads/development-builds/)) play it OK?

If Daum plays it better:
- [ ] What aspect is better?
- [ ] Which Daum release was the **_first_** to fix it?
    Use these builds [here](http://ykhwong.x-y.net/subpages/old.php) to narrow it down.

### How you can help

 1. Download the above lastest DOSBox SVN, X, and Staging builds.
 1. Ensure you have [eXoDOS v5](https://www.retro-exo.com/exodos.html) (or eventually v6)
 1. Find this game inside the eXoDOS installed folders (look for: `VirtualP/`)
 1. Run the game using the DOSBox SVN, X, and Staging builds.
    _If it plays fine (everything looks, sounds, and handles OK) then simply indicate as such. Your task is done!_

If SVN, X, and Staging all have problems, then try it with Daum:
 1. Download the [first and last Daum releases](http://ykhwong.x-y.net/subpages/old.php).
    Note: _Daum had the most releases for Microsoft Windows, so having a Windows system (or VM) will help the most to answer the last question above._
 1. Does the latest Daum release play it correctly? If so: summarize/describe how it's better than DOSBox SVN, X, and Staging (screenshots, video, audio records all help too).
 1. Find the earliest (or oldest) Daum release that fixed it.
    1. Run the Daum release half way between the known good release (where the game playing correctly) and bad release (where the game doesn't playing correctly) until you've narrowed it down to adjacent releases.
    1. It will take _at-most_ seven runs of different Daum versions to narrow this down (using this middle-selecting technique); so it's not as daunting as it seems! :-)

---

### Follow up by code contributors

If Daum plays it better, your answers (especially the last one that narrows down the fix to a specific release) are critical to helping isolate the chunk of code fixed the given bug.

Pull requests should credit:
- @ykhwong as the original code author,
- the test team member who confirmed and isolated the Daum release,
- yourself (PR author) as integrating the fix

The PR should include the `imported-from:` URL pointing to DOSBox Daum. For an example, see commit a35c7c889.

**Comment by Grounded0** [comment]
I tested this game with video modes:
VESA 1024x768 single page
VESA 640x480 page flipping
VESA 640x480 single page

And this is what i got:
<img width="1392" alt="Screenshot 2023-09-17 at 19 53 25" src="https://github.com/dosbox-staging/dosbox-staging/assets/48192273/09896683-bc8e-4957-b437-a617b08fcb17">

**Comment by kcgen** [comment]
@Grounded0 , any improvement with:

```ini
[dosbox]
machine = vesa_nolfb

[cpu]
cycles = 30000
```

Then VESA 1024x768 single page in-game?

**Comment by kcgen** [comment]
Nice investigation, @Grounded0!

Closing this as and no longer needing Daum as latest `main` is running with default settings (and VESA selected in-game).

@Python-Exoproject, over to you to flag this for future reprocessing. If it turns out to still need Daum, let us know the details how we can repro the Daum-specific handling and we can re-open this ticket :+1:

**Comment by rderooy** [comment]
## DOSBox 0.74-3
Game crash during intro

## DOSBox Daum - eXoDOS included edition
Works fine

## DOSBox ECE r4230 - eXoDOS included edition
Crash like DOSBox 0.74-3

## DOSBox-X 2023.09.01
Works fine

# exoDOS dosbox.conf
```ini
# Config file for Dosbox-SVN Daum Jan 25, 2015
[sdl]
fullscreen=false
fulldouble=false
fullresolution=0x0
windowresolution=1280x960
output=direct3d
priority=higher,higher
mapperfile=mapper.map
[dosbox]
machine=svga_s3
memsize=32
[render]
aspect=true
scaler=normal2x
[vsync]
[cpu]
core=auto
cputype=auto
cycles=30000
isapnpbios=true
[keyboard]
[pci]
[mixer]
[midi]
[sblaster]
[gus]
[innova]
[speaker]
[joystick]
[serial]
[printer]
[parallel]
dongle=true
[glide]
[dos]
[ipx]
ipx=true
[autoexec]
mount c .\eXoDOS\VirtualP
imgmount d .\eXoDOS\VirtualP\cd\VIRTUALPOOL.CUE -t cdrom
c:
cls
@call run
exit
```
