### ISSUE TITLE
Investigate playability issues with Virtual Snooker (1996)

### ISSUE THREAD

**Issue by kcgen** [dosbox-staging/dosbox-staging#2892]
### Context

Currently the eXoDOS project runs this game using [the DOSBox Daum fork](https://github.com/ykhwong/dosbox-svn-daum), which is understood to have specific emulation fixes not currently in upstream DOSBox (0.74.x and SVN) or active forks such as X, Pure, and Staging.

DOSBox Daum had 51 releases that included DOSBox SVN's commits ~r3600 through ~r3900, [spanning 2010 through 2015](http://ykhwong.x-y.net/).

### The goal of this ticket is to answer the following

Is Daum _still_ needed for this game?
- [ ] Does DOSBox SVN ([download latest](http://www.emucr.com/2023/09/dosbox-svn-r4483.html)) play it OK?
- [ ] Does DOSBox X ([download latest](https://dosbox-x.com/)) play it OK?
- [ ] Does DOSBox Staging ([download latest](https://dosbox-staging.github.io/downloads/development-builds/)) play it OK?

If Daum plays it better:
- [ ] What aspect is better?
- [ ] Which Daum release was the **_first_** to fix it?
    Use these builds [here](http://ykhwong.x-y.net/subpages/old.php) to narrow it down.

### How you can help

 1. Download the above lastest DOSBox SVN, X, and Staging builds.
 1. Ensure you have [eXoDOS v5](https://www.retro-exo.com/exodos.html) (or eventually v6)
 1. Find this game inside the eXoDOS installed folders (look for: `VirtualS/`)
 1. Run the game using the DOSBox SVN, X, and Staging builds.
    _If it plays fine (everything looks, sounds, and handles OK) then simply indicate as such. Your task is done!_

If SVN, X, and Staging all have problems, then try it with Daum:
 1. Download the [first and last Daum releases](http://ykhwong.x-y.net/subpages/old.php).
    Note: _Daum had the most releases for Microsoft Windows, so having a Windows system (or VM) will help the most to answer the last question above._
 1. Does the latest Daum release play it correctly? If so: summarize/describe how it's better than DOSBox SVN, X, and Staging (screenshots, video, audio records all help too).
 1. Find the earliest (or oldest) Daum release that fixed it.
    1. Run the Daum release half way between the known good release (where the game playing correctly) and bad release (where the game doesn't playing correctly) until you've narrowed it down to adjacent releases.
    1. It will take _at-most_ seven runs of different Daum versions to narrow this down (using this middle-selecting technique); so it's not as daunting as it seems! :-)

---

### Follow up by code contributors

If Daum plays it better, your answers (especially the last one that narrows down the fix to a specific release) are critical to helping isolate the chunk of code fixed the given bug.

Pull requests should credit:
- @ykhwong as the original code author,
- the test team member who confirmed and isolated the Daum release,
- yourself (PR author) as integrating the fix

The PR should include the `imported-from:` URL pointing to DOSBox Daum. For an example, see commit a35c7c889.

**Comment by MasterO2** [comment]
*insert obligatory Ronnie O'Sullivan reference here.*

**Comment by Grounded0** [comment]
0.80.1 RELEASE:

<img width="1392" alt="Screenshot 2023-09-17 at 21 10 39" src="https://github.com/dosbox-staging/dosbox-staging/assets/48192273/3b9df171-1c49-4ea3-a677-0e71cf70c7a4">

```
2023-09-17 21:09:14.183 | IMGMOUNT: Path 'virtuals.cue' not found, maybe it's a DOS path
2023-09-17 21:09:14.183 | IMGMOUNT: Path 'TEMP\VIRTUALS\CD\VIRTUALS.CUE' found on virtual drive C:
2023-09-17 21:09:14.184 | CDAUDIO: Operating at 48000 Hz without resampling
2023-09-17 21:09:36.809 | DOSBox has switched to max cycles, because of the setting: cycles=auto.
If the game runs too fast, try a fixed cycles amount in DOSBox's options.
2023-09-17 21:09:39.901 | SB16: DSP was reset
2023-09-17 21:09:39.960 | DISPLAY: VESA 640x480 8-bit (mode 101h) at 70.007 Hz VFR, scaled to 2560x1920 with 1 pixel aspect ratio
2023-09-17 21:10:21.779 | DISPLAY: Text 640x400 16 color (mode 03h) at 70.087 Hz VFR, scaled to 2560x1920 with 1.2 pixel aspect ratio
```

Few days old DEV:

<img width="1392" alt="Screenshot 2023-09-17 at 21 17 55" src="https://github.com/dosbox-staging/dosbox-staging/assets/48192273/db2cc946-d082-42b7-84fd-076c0deb8071">
<img width="1392" alt="Screenshot 2023-09-17 at 21 18 37" src="https://github.com/dosbox-staging/dosbox-staging/assets/48192273/73f0159c-6565-472e-a3b6-757515b40e3b">

```
2023-09-17 21:16:22.185 | IMGMOUNT: Path 'virtuals.cue' not found, maybe it's a DOS path
2023-09-17 21:16:22.185 | IMGMOUNT: Path 'TEMP\VIRTUALS\CD\VIRTUALS.CUE' found on virtual drive C:
2023-09-17 21:16:22.185 | CDAUDIO: Operating at 48000 Hz without resampling
2023-09-17 21:16:57.433 | DOSBox has switched to max cycles, because of the setting: cycles=auto.
If the game runs too fast, try a fixed cycles amount in DOSBox's options.
2023-09-17 21:17:00.218 | SB16: DSP was reset
2023-09-17 21:17:00.238 | DISPLAY: VESA 640x480 256-colour graphics mode 101h at 70.007 Hz VFR, scaled to 2560x1920 with 1:1 (1:1) pixel aspect ratio
2023-09-17 21:17:49.365 | MOUSE (DOS): Custom acceleration profiles not implemented
2023-09-17 21:18:04.265 | SB16: DSP was reset
2023-09-17 21:18:04.305 | SB16: Speaker-output has been toggled on
```

**Comment by rderooy** [comment]
## DOSBox 0.74-3
Hang during intro with corrupted colour palette

## DOSBox Daum - eXoDOS included edition
Works fine

## DOSBox-X 2023.09.01
Works fine

# eXoDOS dosbox.conf
```ini
# Config file for Dosbox-SVN Daum Jan 25, 2015
[sdl]
fullscreen=false
fulldouble=false
fullresolution=0x0
windowresolution=1280x960
output=direct3d
priority=higher,higher
mapperfile=mapper.map
usescancodes=true
[dosbox]
machine=svga_s3
memsize=32
[render]
aspect=true
scaler=normal2x
[cpu]
core=auto
cputype=auto
cycles=50000
[mixer]
[midi]
[sblaster]
[gus]
[speaker]
disney=true
[joystick]
[serial]
[dos]
[ipx]
ipx=true
[autoexec]
mount c .\eXoDOS\VirtualS
imgmount d ".\eXoDOS\VirtualS\cd\Virtual Snooker.cue" -t cdrom
c:
cls
@call run
exit
```
