### ISSUE TITLE
Investigate playability issues with Hardline (1997)

### ISSUE THREAD

**Issue by kcgen** [dosbox-staging/dosbox-staging#2902]
### Context

Currently the eXoDOS project runs this game using [the DOSBox Daum fork](https://github.com/ykhwong/dosbox-svn-daum), which is understood to have specific emulation fixes not currently in upstream DOSBox (0.74.x and SVN) or active forks such as X, Pure, and Staging.

DOSBox Daum had 51 releases that included DOSBox SVN's commits ~r3600 through ~r3900, [spanning 2010 through 2015](http://ykhwong.x-y.net/).

### The goal of this ticket is to answer the following

Is Daum _still_ needed for this game?
- [ ] Does DOSBox SVN ([download latest](http://www.emucr.com/2023/09/dosbox-svn-r4483.html)) play it OK?
- [ ] Does DOSBox X ([download latest](https://dosbox-x.com/)) play it OK?
- [ ] Does DOSBox Staging ([download latest](https://dosbox-staging.github.io/downloads/development-builds/)) play it OK?

If Daum plays it better:
- [ ] What aspect is better?
- [ ] Which Daum release was the **_first_** to fix it?
    Use these builds [here](http://ykhwong.x-y.net/subpages/old.php) to narrow it down.

### How you can help

 1. Download the above lastest DOSBox SVN, X, and Staging builds.
 1. Ensure you have [eXoDOS v5](https://www.retro-exo.com/exodos.html) (or eventually v6)
 1. Find this game inside the eXoDOS installed folders (look for: `Hardline/`)
 1. Run the game using the DOSBox SVN, X, and Staging builds.
    _If it plays fine (everything looks, sounds, and handles OK) then simply indicate as such. Your task is done!_

If SVN, X, and Staging all have problems, then try it with Daum:
 1. Download the [first and last Daum releases](http://ykhwong.x-y.net/subpages/old.php).
    Note: _Daum had the most releases for Microsoft Windows, so having a Windows system (or VM) will help the most to answer the last question above._
 1. Does the latest Daum release play it correctly? If so: summarize/describe how it's better than DOSBox SVN, X, and Staging (screenshots, video, audio records all help too).
 1. Find the earliest (or oldest) Daum release that fixed it.
    1. Run the Daum release half way between the known good release (where the game playing correctly) and bad release (where the game doesn't playing correctly) until you've narrowed it down to adjacent releases.
    1. It will take _at-most_ seven runs of different Daum versions to narrow this down (using this middle-selecting technique); so it's not as daunting as it seems! :-)

---

### Follow up by code contributors

If Daum plays it better, your answers (especially the last one that narrows down the fix to a specific release) are critical to helping isolate the chunk of code fixed the given bug.

Pull requests should credit:
- @ykhwong as the original code author,
- the test team member who confirmed and isolated the Daum release,
- yourself (PR author) as integrating the fix

The PR should include the `imported-from:` URL pointing to DOSBox Daum. For an example, see commit a35c7c889.

**Comment by Burrito78** [comment]
Results (macOS Ventura 13.5.2/Apple M2):

**DOSBox Staging 0.81.0-alpha-1689**
Game runs UniVBE and shows tearing but is playable and otherwise OK.

**DOSBox SVN	snapshot 12.09.23**
Game runs UniVBE and shows heavy tearing, runs way slower than Staging.
Aspect ratio is very, very wide.

**DOSBox-X v2023.09.01**
Game runs UniVBE and shows a little tearing.
Mouse cursor has a large offset to host cursor, otherwise OK.

I don't run Windows so i can't test with Daum.

**Comment by rderooy** [comment]
FMV "action" game

Not sure why this is in the daum investigation. According to the eXoDOS dosbox.conf comment, this is setup for DOSBox 0.74?

I did not experience any noticeable tearing issues. @Burrito78 did you use the eXoDOS dosbox.conf file?

## DOSBox 0.74-3
Works

## DOSBox Daum - as included with eXoDOS
Works

## DOSBox ECE r4230 - as included with eXoDOS
Works

## DOSBox Staging 0.80.1
Works

## DOSBox-X 2023.09.01
Had to "capture mouse" to lock the mouse to the window to resolve mouse offset issues.
Otherwise works

# eXoDOS dosbox.conf
```ini
# Config file for Dosbox-0.74
[sdl]
fullscreen=false
fulldouble=false
fullresolution=0x0
windowresolution=1280x960
output=direct3d
mapperfile=mapper.map
[dosbox]
machine=svga_s3
memsize=32
[render]
aspect=true
scaler=normal2x
[cpu]
core=auto
cputype=auto
cycles=65000
[mixer]
[midi]
[sblaster]
[gus]
[speaker]
[joystick]
[serial]
[dos]
[ipx]
[autoexec]
mount c .\eXoDOS\Hardline
imgmount d ".\eXoDOS\Hardline\cd\HARDLINE-1.iso" ".\eXoDOS\Hardline\cd\HARDLINE-2.iso" ".\eXoDOS\Hardline\cd\HARDLINE-3.iso" -t cdrom
c:
@cd Hardline
@echo off
@cls
echo.
echo This game is made up of 3 CD's.  Press CTRL-F3 to change to the
echo next CD when prompted.
echo.
pause
@call hard
exit
```

**Comment by Burrito78** [comment]
> I did not experience any noticeable tearing issues. @Burrito78 did you use the eXoDOS dosbox.conf file?

As I'm on macOS, I didn't use the eXoDOS config file (output=direct3d). I'm testing with Staging default config and only edit selected config settings if needed. In my experience, the DOSBox config files from eXoDOS are mostly not needed in Staging.

**Comment by rderooy** [comment]
@Burrito78 I was not referring to the direct3d setting. I am aware that is a Windows specific feature. When I test it with Linux native DOSBox builds, that setting also does not get used. Instead it will end-up use the default output option for the respective dosbox build.

What could influence it though is the cycles setting, if you used something completely different. Or perhaps you have some other options enabled that could influence it.

**Comment by kcgen** [comment]
> Not sure why this is in the daum investigation. According to the eXoDOS dosbox.conf comment, this is setup for DOSBox 0.74?

It was in the list handed over from the team circa-2021: https://github.com/dosbox-staging/dosbox-staging/issues/804

Good to see it's running across the board!
Thanks for the tests, @Burrito78 and @rderooy.

**Comment by MasterO2** [comment]
Can the game detect all 3 CDs imgmounted separately as 3 different drive letters?

**Comment by rderooy** [comment]
> Can the game detect all 3 CDs imgmounted separately as 3 different drive letters?

I did not try it, but very few games support that. Also I did not progress far enough into the game for it to even ask for the second CD to test if it works.
