### ISSUE TITLE
Investigate playability issues with Operation AirStorm (1994)

### ISSUE THREAD

**Issue by kcgen** [dosbox-staging/dosbox-staging#2915]
### Context

Currently the eXoDOS project runs this game using [the DOSBox Daum fork](https://github.com/ykhwong/dosbox-svn-daum), which is understood to have specific emulation fixes not currently in upstream DOSBox (0.74.x and SVN) or active forks such as X, Pure, and Staging.

DOSBox Daum had 51 releases that included DOSBox SVN's commits ~r3600 through ~r3900, [spanning 2010 through 2015](http://ykhwong.x-y.net/).

### The goal of this ticket is to answer the following

Is Daum _still_ needed for this game?
- [ ] Does DOSBox SVN ([download latest](http://www.emucr.com/2023/09/dosbox-svn-r4483.html)) play it OK?
- [ ] Does DOSBox X ([download latest](https://dosbox-x.com/)) play it OK?
- [ ] Does DOSBox Staging ([download latest](https://dosbox-staging.github.io/downloads/development-builds/)) play it OK?

If Daum plays it better:
- [ ] What aspect is better?
- [ ] Which Daum release was the **_first_** to fix it?
    Use these builds [here](http://ykhwong.x-y.net/subpages/old.php) to narrow it down.

### How you can help

 1. Download the above lastest DOSBox SVN, X, and Staging builds.
 1. Ensure you have [eXoDOS v5](https://www.retro-exo.com/exodos.html) (or eventually v6)
 1. Find this game inside the eXoDOS installed folders (look for: `OpAirSto/`)
 1. Run the game using the DOSBox SVN, X, and Staging builds.
    _If it plays fine (everything looks, sounds, and handles OK) then simply indicate as such. Your task is done!_

If SVN, X, and Staging all have problems, then try it with Daum:
 1. Download the [first and last Daum releases](http://ykhwong.x-y.net/subpages/old.php).
    Note: _Daum had the most releases for Microsoft Windows, so having a Windows system (or VM) will help the most to answer the last question above._
 1. Does the latest Daum release play it correctly? If so: summarize/describe how it's better than DOSBox SVN, X, and Staging (screenshots, video, audio records all help too).
 1. Find the earliest (or oldest) Daum release that fixed it.
    1. Run the Daum release half way between the known good release (where the game playing correctly) and bad release (where the game doesn't playing correctly) until you've narrowed it down to adjacent releases.
    1. It will take _at-most_ seven runs of different Daum versions to narrow this down (using this middle-selecting technique); so it's not as daunting as it seems! :-)

---

### Follow up by code contributors

If Daum plays it better, your answers (especially the last one that narrows down the fix to a specific release) are critical to helping isolate the chunk of code fixed the given bug.

Pull requests should credit:
- @ykhwong as the original code author,
- the test team member who confirmed and isolated the Daum release,
- yourself (PR author) as integrating the fix

The PR should include the `imported-from:` URL pointing to DOSBox Daum. For an example, see commit a35c7c889.

**Comment by rderooy** [comment]
Another SBPDD.SYS user, hence the need to boot a DOS HDD image. Similar to #2878 and #2923 

There are some type of FMV-like sequences before game play that are quite sluggish in their motion. But raising the amount of cycles from 20 to 50k made no real difference.

## DOSBox 0.74-3
Lacks the necessary IDE emulation for this setup

## DOSBox Daum
Works

## DOSBox Staging 0.80.1
Fails to start the game.
![boot_000](https://github.com/dosbox-staging/dosbox-staging/assets/17701098/d3b6e468-2494-4e02-91f6-0210979a433a)

By default with Staging there is only 517K conventional available to the game

Changing config.sys to `devicehigh` the VIDE-CDD.SYS and SBPDD.SYS drivers made no difference.

## DOSBox-X 2023.09.01
Works

# eXoDOS dosbox.conf
```ini
# Config file for Dosbox-SVN Daum Jan 25, 2015
[sdl]
fullscreen=false
fulldouble=false
fullresolution=0x0
windowresolution=1280x960
output=direct3d
mapperfile=mapper.map
usescancodes=true
[dosbox]
machine=svga_s3
memsize=63
[render]
aspect=true
scaler=normal2x
[cpu]
core=auto
cputype=auto
cycles=20000
[pci]
[mixer]
prebuffer=25
[midi]
mididevice=mt32
[sblaster]
sbtype=sbpro1
[gus]
[speaker]
disney=true
[joystick]
[serial]
[dos]
[ipx]
[ide, primary]
[ide, secondary]
[ide, tertiary]
enable=true
[ide, quaternary]
enable=true
[autoexec]
@imgmount c .\eXoDOS\OpAirSto\i50_101.img
@imgmount d ".\eXoDOS\OpAirSto\CD\Operation AirStorm.cue" -t iso -fs iso -ide 2m
@cls
@boot -l c
exit
```

**Comment by kcgen** [comment]
https://github.com/dosbox-staging/dosbox-staging/assets/1557255/61521786-34d7-4894-890a-fd38a4225eac

https://github.com/dosbox-staging/dosbox-staging/assets/1557255/8372ed7a-791c-4db7-a04f-011a431f42fe

https://github.com/dosbox-staging/dosbox-staging/assets/1557255/51464666-e44d-4718-b9aa-ce413f2763ea

```ini
[cpu]
cycles = 10000

[sblaster]
sbtype = sbpro2
sb_filter = auto

[midi]
mididevice = none

[speaker]
pcspeaker = off

[dos]
xms = false
ems = false
umb = false
mixer sb 200

[autoexec]
imgmount d "CD/Operation AirStorm.cue" -t cdrom -ide
imgmount c i50_101.img
boot -l c
```

With these adjustments to `config.sys`:

![2023-09-23_17-26](https://github.com/dosbox-staging/dosbox-staging/assets/1557255/1cdeb873-7654-45e2-bfc1-b7a31e6a8d20)

And `autoexec.bat`:

![2023-09-23_17-28](https://github.com/dosbox-staging/dosbox-staging/assets/1557255/46e4d708-9465-459e-829f-1ac785fe92fe)

Gets us just over the 600 KB edge! (where have my DOS mem skills gone!)

![2023-09-23_17-29](https://github.com/dosbox-staging/dosbox-staging/assets/1557255/7963d8b0-629b-4db3-b59d-6572b9712665)

Good enough :-)

**Comment by Grounded0** [comment]
Certainly no [Fleet Defender](https://www.mobygames.com/game/4540/fleet-defender/)

**Comment by Burrito78** [comment]
Results (macOS Ventura 13.5.2/Apple M2):

Just a quick report that besides having no sound during the video on the TV, the game worked with Staging DEV, DOSBox SVN and DOSBox-X without booting from the included C-Drive IMG. 

But i understand that this is needed to load the SBPDD.SYS driver to support sound during the briefing videos.

I don't run Windows so i can't test with Daum.

**Comment by Grounded0** [comment]
The game seems to run well so closing. DOS memory management issue is not directly related to game compatibility. If in dispute please reopen.

**Comment by johnnovak** [comment]
> @johnnovak, I wonder how that UMB-sensitive demo would fare in Daum?

Well, to be fair, it crashes on real hardware too, UMB or not, so I think it's largely uninteresting.

**Comment by kcgen** [comment]
> > @johnnovak, I wonder how that UMB-sensitive demo would fare in Daum?
> 
> Well, to be fair, it crashes on real hardware too, UMB or not, so I think it's largely uninteresting. Detailed in my Vogons post.

Oh right; thanks for the reminder. (in the end, you figured out that DOSBox was able to keep it on the rails a bit better than real hardware, I think?)

**Comment by Grounded0** [comment]
> Oh right; thanks for the reminder. (in the end, you figured out that DOSBox was able to keep it on the rails a bit better than real hardware, I think?)

Games so shitty they require DOSBox to run. 😂

**Comment by johnnovak** [comment]
> Oh right; thanks for the reminder. (in the end, you figured out that DOSBox was able to keep it on the rails a bit better than real hardware, I think?)

Yeah, that's it. From memory, you could run it _once_ on anything, Staging, SVN, and real hardware. Problems and different behaviour started to happen when running it repeatedly. On real hardware you could do it about 3 times, then crash, but interestingly with `umb = off` you could run it as many times as you wanted in SVN and Staging... but not under real DOS 😄 

Bit of a mess, and a bit inconclusive, but in general `umb = off` helps with stability in Staging.
