### ISSUE TITLE
Investigate playability issues with Pac Man (1982)

### ISSUE THREAD

**Issue by kcgen** [dosbox-staging/dosbox-staging#2917]
### Context

Currently the eXoDOS project runs this game using [the DOSBox Daum fork](https://github.com/ykhwong/dosbox-svn-daum), which is understood to have specific emulation fixes not currently in upstream DOSBox (0.74.x and SVN) or active forks such as X, Pure, and Staging.

DOSBox Daum had 51 releases that included DOSBox SVN's commits ~r3600 through ~r3900, [spanning 2010 through 2015](http://ykhwong.x-y.net/).

### The goal of this ticket is to answer the following

Is Daum _still_ needed for this game?
- [ ] Does DOSBox SVN ([download latest](http://www.emucr.com/2023/09/dosbox-svn-r4483.html)) play it OK?
- [ ] Does DOSBox X ([download latest](https://dosbox-x.com/)) play it OK?
- [ ] Does DOSBox Staging ([download latest](https://dosbox-staging.github.io/downloads/development-builds/)) play it OK?

If Daum plays it better:
- [ ] What aspect is better?
- [ ] Which Daum release was the **_first_** to fix it?
    Use these builds [here](http://ykhwong.x-y.net/subpages/old.php) to narrow it down.

### How you can help

 1. Download the above lastest DOSBox SVN, X, and Staging builds.
 1. Ensure you have [eXoDOS v5](https://www.retro-exo.com/exodos.html) (or eventually v6)
 1. Find this game inside the eXoDOS installed folders (look for: `PacMan82/`)
 1. Run the game using the DOSBox SVN, X, and Staging builds.
    _If it plays fine (everything looks, sounds, and handles OK) then simply indicate as such. Your task is done!_

If SVN, X, and Staging all have problems, then try it with Daum:
 1. Download the [first and last Daum releases](http://ykhwong.x-y.net/subpages/old.php).
    Note: _Daum had the most releases for Microsoft Windows, so having a Windows system (or VM) will help the most to answer the last question above._
 1. Does the latest Daum release play it correctly? If so: summarize/describe how it's better than DOSBox SVN, X, and Staging (screenshots, video, audio records all help too).
 1. Find the earliest (or oldest) Daum release that fixed it.
    1. Run the Daum release half way between the known good release (where the game playing correctly) and bad release (where the game doesn't playing correctly) until you've narrowed it down to adjacent releases.
    1. It will take _at-most_ seven runs of different Daum versions to narrow this down (using this middle-selecting technique); so it's not as daunting as it seems! :-)

---

### Follow up by code contributors

If Daum plays it better, your answers (especially the last one that narrows down the fix to a specific release) are critical to helping isolate the chunk of code fixed the given bug.

Pull requests should credit:
- @ykhwong as the original code author,
- the test team member who confirmed and isolated the Daum release,
- yourself (PR author) as integrating the fix

The PR should include the `imported-from:` URL pointing to DOSBox Daum. For an example, see commit a35c7c889.

**Comment by rderooy** [comment]
To clarify there is both a "Pac-Man (1982)" and a "Pac Man (1982)", this is about the latter.

Unfortunately I could not find any hints as to why Daum is default for this game.

I tried the game with DOSBox 0.74-3, DOSBox Staging 0.80.1, DOSBox Staging Git and DOSBox-X 2023.09.01, and could not notice a real difference. I also tried to play the game with a gamepad, but that did not work with any of the DOSBox variants I tried.

Supplied dosbox.conf for reference:
```ini
# Config file for Dosbox-SVN Daum Jan 25, 2015
[sdl]
fullscreen=false
fulldouble=false
fullresolution=0x0
windowresolution=1280x960
output=direct3d
mapperfile=mapper.map
usescancodes=true
[dosbox]
machine=svga_s3
memsize=16
[render]
aspect=true
scaler=normal2x
[cpu]
core=auto
cputype=auto
cycles=200
[mixer]
[midi]
[sblaster]
[gus]
[speaker]
disney=true
[joystick]
joysticktype=2axis
[serial]
[dos]
[ipx]
[autoexec]
mount c .\eXoDOS\PacMan82
c:
@cls
@pacman2
exit
```

**Comment by rderooy** [comment]
I tried it with a locally build version of the Daum flatpak, and it seems to play the same as other DOSBox forks. Also joystick did not work.

**Comment by kcgen** [comment]
That great news, @rderooy - thanks for taking it through the paces!

@Python-Exoproject, with @rderooy's results, what's the next step to get this into the eXoDOS conveyor belt for processing?

For us, we're trying to figure out the game still needs Daum's extra magic sauce (or not).

**Comment by MasterO2** [comment]
Out of curiosity, were these official ports or some small company or random guy making their own ports?

**Comment by Grounded0** [comment]
I checked the games on Mobygames both Pac Man and Pac-Man and both have nothing to do with Namco. So these were hacked together in a garage.

**Comment by rderooy** [comment]
The game only consists of 2 files
```
PACMAN2  BAS             16,494 12/24/1996 11:32p
PACMAN2  EXE             49,664 12/24/1996 11:32p
```

The basic file has no copyright, company or developer information in it that I could find. The executable contains this text "Licensed Material - Program Property of IBMUVW"

The basic file is not actually needed to run the game. Clearly the EXE contains both the game and a basic interpreter.

I tried to run the basic file with PC-DOS 2.0 BASIC.COM but it just exists with:
```
Syntax error in 120
120 ON KEY(10) GOSUB 9000
```

But running it with BASICA.COM and it runs, but very slow at the 200 cycles set in the supplied DOSBOX.CONF file.

**Comment by rderooy** [comment]
In case someone wonders how I could run BASIC.COM and BASICA.COM, since it needs the IBM BASIC ROM... I used DOSBox-X which has supports for loading the IBM BASIC ROM.
