### ISSUE TITLE
Investigate playability issues with Palace of Deceit - The Secret of Castle Lockemoer, The (1991)

### ISSUE THREAD

**Issue by kcgen** [dosbox-staging/dosbox-staging#2924]
### Context

Currently the eXoDOS project runs this game using [the DOSBox Daum fork](https://github.com/ykhwong/dosbox-svn-daum), which is understood to have specific emulation fixes not currently in upstream DOSBox (0.74.x and SVN) or active forks such as X, Pure, and Staging.

DOSBox Daum had 51 releases that included DOSBox SVN's commits ~r3600 through ~r3900, [spanning 2010 through 2015](http://ykhwong.x-y.net/).

### The goal of this ticket is to answer the following

Is Daum _still_ needed for this game?
- [ ] Does DOSBox SVN ([download latest](http://www.emucr.com/2023/09/dosbox-svn-r4483.html)) play it OK?
- [ ] Does DOSBox X ([download latest](https://dosbox-x.com/)) play it OK?
- [ ] Does DOSBox Staging ([download latest](https://dosbox-staging.github.io/downloads/development-builds/)) play it OK?

If Daum plays it better:
- [ ] What aspect is better?
- [ ] Which Daum release was the **_first_** to fix it?
    Use these builds [here](http://ykhwong.x-y.net/subpages/old.php) to narrow it down.

### How you can help

 1. Download the above lastest DOSBox SVN, X, and Staging builds.
 1. Ensure you have [eXoDOS v5](https://www.retro-exo.com/exodos.html) (or eventually v6)
 1. Find this game inside the eXoDOS installed folders (look for: `PoDtSoCL/`)
 1. Run the game using the DOSBox SVN, X, and Staging builds.
    _If it plays fine (everything looks, sounds, and handles OK) then simply indicate as such. Your task is done!_

If SVN, X, and Staging all have problems, then try it with Daum:
 1. Download the [first and last Daum releases](http://ykhwong.x-y.net/subpages/old.php).
    Note: _Daum had the most releases for Microsoft Windows, so having a Windows system (or VM) will help the most to answer the last question above._
 1. Does the latest Daum release play it correctly? If so: summarize/describe how it's better than DOSBox SVN, X, and Staging (screenshots, video, audio records all help too).
 1. Find the earliest (or oldest) Daum release that fixed it.
    1. Run the Daum release half way between the known good release (where the game playing correctly) and bad release (where the game doesn't playing correctly) until you've narrowed it down to adjacent releases.
    1. It will take _at-most_ seven runs of different Daum versions to narrow this down (using this middle-selecting technique); so it's not as daunting as it seems! :-)

---

### Follow up by code contributors

If Daum plays it better, your answers (especially the last one that narrows down the fix to a specific release) are critical to helping isolate the chunk of code fixed the given bug.

Pull requests should credit:
- @ykhwong as the original code author,
- the test team member who confirmed and isolated the Daum release,
- yourself (PR author) as integrating the fix

The PR should include the `imported-from:` URL pointing to DOSBox Daum. For an example, see commit a35c7c889.

**Comment by rderooy** [comment]
Shareware Text adventure, running in an EGA text mode with some PC speaker sounds.

As displayed in the staging log:
```
DISPLAY: Text 640x400 16 color (mode 03h) at 70.087 Hz VFR, scaled to 1280x960 with 1.2 pixel aspect ratio
```

## DOSBox 0.74-3
Could not detect any game play issue
![image](https://github.com/dosbox-staging/dosbox-staging/assets/17701098/8943605f-c164-4d52-9d41-d784e518f8c8)

## DOSBox Daum
Seems fine. Aspect ratio is a bit different from DOSBox 0.74-3

![image](https://github.com/dosbox-staging/dosbox-staging/assets/17701098/0f549269-fe45-4e25-80ae-8e06550976b1)


## DOSBox Staging 0.80.1
Seems fine. Only slightly annoying issue is that Staging keeps capturing the mouse when you click on the window, despite the game not supporting the mouse. But that is not unique to this game.

![image](https://github.com/dosbox-staging/dosbox-staging/assets/17701098/efb7f167-937c-4f09-bf08-2f385915aca4)


## DOSBox-X 2023.09.01
Game play seems fine. But the font has vertical lines in between the characters.
![image](https://github.com/dosbox-staging/dosbox-staging/assets/17701098/4710d3a7-91e7-43d2-aeb5-df0a3cf5d942)

# dosbox.conf
```ini
# Config file for Dosbox-SVN Daum Jan 25, 2015
[sdl]
fullscreen=false
fulldouble=false
fullresolution=0x0
windowresolution=1280x960
output=direct3d
mapperfile=mapper.map
usescancodes=true
[dosbox]
machine=svga_s3
memsize=16
[render]
aspect=true
scaler=normal2x
[cpu]
core=auto
cputype=auto
cycles=auto
[mixer]
[midi]
[sblaster]
[gus]
[speaker]
disney=true
[joystick]
[serial]
[dos]
[ipx]
[autoexec]
mount c .\eXoDOS\PoDtSoCL
c:
@echo off
@cls
@cls
echo.
echo Press space or return at the black screen to start.
echo.
pause
cls
@call runme
exit
```

**Comment by rderooy** [comment]
## DOSBox Staging GIT
same vertical lines as with DOSBox-X. Also the text mode has changed.
```
DISPLAY: VGA 720x400 16-colour text mode 03h at 70.087 Hz VFR, scaled to 1280x960 with 1:1.35 (20:27) pixel aspect ratio
```
![image](https://github.com/dosbox-staging/dosbox-staging/assets/17701098/425517c9-fee1-48ab-86bc-f8c91f140f99)

**Comment by rderooy** [comment]
The games equivalent of a readme file mentions EGA required. So I think the solution for this game is to run it with `machine=ega`.

Here is what DOSBox Staging git looks like in that case:
![image](https://github.com/dosbox-staging/dosbox-staging/assets/17701098/8f4f2446-0d7d-411a-869c-715357fc45b8)

Staging than reports:
```
DISPLAY: EGA 640x350 16-colour text mode 03h at 59.702 Hz VFR, scaled to 1280x960 with 1:1.37143 (35:48) pixel aspect ratio
```
