### ISSUE TITLE
Investigate playability issues with Puzzle Bobble (1994)

### ISSUE THREAD

**Issue by kcgen** [dosbox-staging/dosbox-staging#2927]
### Context

Currently the eXoDOS project runs this game using [the DOSBox Daum fork](https://github.com/ykhwong/dosbox-svn-daum), which is understood to have specific emulation fixes not currently in upstream DOSBox (0.74.x and SVN) or active forks such as X, Pure, and Staging.

DOSBox Daum had 51 releases that included DOSBox SVN's commits ~r3600 through ~r3900, [spanning 2010 through 2015](http://ykhwong.x-y.net/).

### The goal of this ticket is to answer the following

Is Daum _still_ needed for this game?
- [ ] Does DOSBox SVN ([download latest](http://www.emucr.com/2023/09/dosbox-svn-r4483.html)) play it OK?
- [ ] Does DOSBox X ([download latest](https://dosbox-x.com/)) play it OK?
- [ ] Does DOSBox Staging ([download latest](https://dosbox-staging.github.io/downloads/development-builds/)) play it OK?

If Daum plays it better:
- [ ] What aspect is better?
- [ ] Which Daum release was the **_first_** to fix it?
    Use these builds [here](http://ykhwong.x-y.net/subpages/old.php) to narrow it down.

### How you can help

 1. Download the above lastest DOSBox SVN, X, and Staging builds.
 1. Ensure you have [eXoDOS v5](https://www.retro-exo.com/exodos.html) (or eventually v6)
 1. Find this game inside the eXoDOS installed folders (look for: `PuzBob/`)
 1. Run the game using the DOSBox SVN, X, and Staging builds.
    _If it plays fine (everything looks, sounds, and handles OK) then simply indicate as such. Your task is done!_

If SVN, X, and Staging all have problems, then try it with Daum:
 1. Download the [first and last Daum releases](http://ykhwong.x-y.net/subpages/old.php).
    Note: _Daum had the most releases for Microsoft Windows, so having a Windows system (or VM) will help the most to answer the last question above._
 1. Does the latest Daum release play it correctly? If so: summarize/describe how it's better than DOSBox SVN, X, and Staging (screenshots, video, audio records all help too).
 1. Find the earliest (or oldest) Daum release that fixed it.
    1. Run the Daum release half way between the known good release (where the game playing correctly) and bad release (where the game doesn't playing correctly) until you've narrowed it down to adjacent releases.
    1. It will take _at-most_ seven runs of different Daum versions to narrow this down (using this middle-selecting technique); so it's not as daunting as it seems! :-)

---

### Follow up by code contributors

If Daum plays it better, your answers (especially the last one that narrows down the fix to a specific release) are critical to helping isolate the chunk of code fixed the given bug.

Pull requests should credit:
- @ykhwong as the original code author,
- the test team member who confirmed and isolated the Daum release,
- yourself (PR author) as integrating the fix

The PR should include the `imported-from:` URL pointing to DOSBox Daum. For an example, see commit a35c7c889.

**Comment by MasterO2** [comment]
I had no idea there was even a DOS port of Puzzle Bobble.

That's a Neo-Geo game usually run in MAME or if you play online, via Fightcade....

**Comment by rderooy** [comment]
Korean game, but contains enough English to make it understandable.

## DOSBox 0.74-3
Hangs on the vendor splash screen with a never-ending stream of `Illegal read from a2911f2d, CS:IP     f000:    11c4` errors in the log.

## DOSBox Daum
Game works, but there are some issues:
- some top-of-screen corruption at the beginning at the "Puzzle Bobble" screen (with the falling "snow")
- some temporary graphical glitches on occasion.
- cursor keys don't work during gameplay (numeric keypad does)

## DOSBox Staging 0.80.1
Works fine

## DOSBox-X 2023.09.01
Works fine

# dosbox.conf
```ini
# Config file for Dosbox-SVN Daum Jan 25, 2015
[sdl]
fullscreen=false
fulldouble=false
fullresolution=0x0
windowresolution=1280x960
output=direct3d
mapperfile=mapper.map
usescancodes=true
[dosbox]
machine=svga_s3
memsize=32
[render]
aspect=true
scaler=normal2x
[cpu]
core=auto
cputype=auto
cycles=30000
[mixer]
[midi]
[sblaster]
[gus]
[speaker]
disney=true
[joystick]
[serial]
[dos]
[ipx]
[autoexec]
cd ..
@cd ..
@mount c .\eXoDOS\PuzBob
c:
cls
@pb
exit
```

**Comment by Grounded0** [comment]
Its a obscure unofficial third party port of Puzzle Bobble (1994) for DOS released in 1997 so i think we have enough confidence it runs fine.

**Comment by MasterO2** [comment]
Personally speaking, I believe if anyone asks Staging about **DOS ports** of games that are obviously arcade games, such as Pac-Man, Donkey Kong, Puzzle Bobble, etc, that we should refer them to *MAME* or *Fightcade* (for multiplayer online matches).

Playing third-rate DOS bootlegs of these games is not at all the optimal way of playing said games.
