### ISSUE TITLE
Investigate playability issues with Realms of Arkania - Blade of Destiny (1992)

### ISSUE THREAD

**Issue by kcgen** [dosbox-staging/dosbox-staging#2928]
### Context

Currently the eXoDOS project runs this game using [the DOSBox Daum fork](https://github.com/ykhwong/dosbox-svn-daum), which is understood to have specific emulation fixes not currently in upstream DOSBox (0.74.x and SVN) or active forks such as X, Pure, and Staging.

DOSBox Daum had 51 releases that included DOSBox SVN's commits ~r3600 through ~r3900, [spanning 2010 through 2015](http://ykhwong.x-y.net/).

### The goal of this ticket is to answer the following

Is Daum _still_ needed for this game?
- [ ] Does DOSBox SVN ([download latest](http://www.emucr.com/2023/09/dosbox-svn-r4483.html)) play it OK?
- [ ] Does DOSBox X ([download latest](https://dosbox-x.com/)) play it OK?
- [ ] Does DOSBox Staging ([download latest](https://dosbox-staging.github.io/downloads/development-builds/)) play it OK?

If Daum plays it better:
- [ ] What aspect is better?
- [ ] Which Daum release was the **_first_** to fix it?
    Use these builds [here](http://ykhwong.x-y.net/subpages/old.php) to narrow it down.

### How you can help

 1. Download the above lastest DOSBox SVN, X, and Staging builds.
 1. Ensure you have [eXoDOS v5](https://www.retro-exo.com/exodos.html) (or eventually v6)
 1. Find this game inside the eXoDOS installed folders (look for: `rarkani1/`)
 1. Run the game using the DOSBox SVN, X, and Staging builds.
    _If it plays fine (everything looks, sounds, and handles OK) then simply indicate as such. Your task is done!_

If SVN, X, and Staging all have problems, then try it with Daum:
 1. Download the [first and last Daum releases](http://ykhwong.x-y.net/subpages/old.php).
    Note: _Daum had the most releases for Microsoft Windows, so having a Windows system (or VM) will help the most to answer the last question above._
 1. Does the latest Daum release play it correctly? If so: summarize/describe how it's better than DOSBox SVN, X, and Staging (screenshots, video, audio records all help too).
 1. Find the earliest (or oldest) Daum release that fixed it.
    1. Run the Daum release half way between the known good release (where the game playing correctly) and bad release (where the game doesn't playing correctly) until you've narrowed it down to adjacent releases.
    1. It will take _at-most_ seven runs of different Daum versions to narrow this down (using this middle-selecting technique); so it's not as daunting as it seems! :-)

---

### Follow up by code contributors

If Daum plays it better, your answers (especially the last one that narrows down the fix to a specific release) are critical to helping isolate the chunk of code fixed the given bug.

Pull requests should credit:
- @ykhwong as the original code author,
- the test team member who confirmed and isolated the Daum release,
- yourself (PR author) as integrating the fix

The PR should include the `imported-from:` URL pointing to DOSBox Daum. For an example, see commit a35c7c889.

**Comment by rderooy** [comment]
- DOSBox 0.74-3 - seems to work ok, apart from lacking MT32 support
- DOSBox Daum - Working ok with SB, MT32 and CD-Audio options
- DOSBox Staging 0.80.1 - directly starts the game in SB mode (no DOS batch menu with sound options)
- DOSBox Staging Git - same ^^
- DOSBox-X 2023.09.01 - core dump unless I disable the line below. After that the same as Staging:
```ini
[ide, secondary]
enable=false
```
- DOSBox-X Git - same

It seems there is a problem with the provided `RUN.BAT` file. For some reason both DOSBox Staging and DOSBox-X immediately run the SB option.

## dosbox.conf
```ini
# Config file for Dosbox-SVN Daum Jan 25, 2015
[sdl]
fullscreen=false
fulldouble=false
fullresolution=0x0
windowresolution=1280x960
output=direct3d
mapperfile=mapper.map
[dosbox]
machine=svga_s3
memsize=16
[render]
aspect=true
scaler=normal2x
[vsync]
[cpu]
core=auto
cputype=auto
cycles=5000
isapnpbios=true
[keyboard]
[pci]
[mixer]
[midi]
mididevice=mt32
[sblaster]
sbmixer=false
[gus]
gus=true
[innova]
[speaker]
[joystick]
[serial]
[printer]
[parallel]
dongle=true
[glide]
[dos]
[ipx]
[ne2000]
[ide, primary]
enable=false
[ide, secondary]
enable=false
[ide, tertiary]
[ide, quaternary]
[autoexec]
@mount c .\eXoDOS\
imgmount d ".\eXoDOS\rarkani1\cd\Realms1_BoD_ST.cue" -t cdrom
@c:
cls
cd rarkani1
@call run
exit
```

## RUN.BAT
```dos
:menu
@echo off
cls
echo.
echo Press 1 for Realms of Arkania: Blade of Destiny w/ SoundBlaster
echo Press 2 for Realms of Arkania: Blade of Destiny w/ MT32
echo Press 3 for Realms of Arkania: Blade of Destiny w/ CD Audio*
echo Press 4 to Quit
echo.
echo Note: The CD Audio version is the German version of the game hacked
echo to mostly run in English. Occasional messages and the in game journal are
echo still in German.
echo.
choice /C:1234 /N Please Choose:

if errorlevel = 4 goto quit
if errorlevel = 3 goto German
if errorlevel = 2 goto MT32
if errorlevel = 1 goto SB

:SB
CONFIG -set "mididevice=default"
copy .\sb16\*.* .\
cls
@call blade
goto quit

:MT32
CONFIG -set "mididevice=mt32"
copy .\mt32\*.* .\
cls
@call blade
goto quit

:German
cd G
imgmount -u d
imgmount d ".\eXoDOS\rarkani1\cd\DSA_1293.cue" -t cdrom
cls
@call blade
cd..
goto quit

:quit
exit
```

**Comment by Grounded0** [comment]
FreeDOS `COMMAND.COM`:

<img width="1392" alt="Screenshot 2023-09-18 at 0 05 48" src="https://github.com/dosbox-staging/dosbox-staging/assets/48192273/7be051cb-a85b-41b4-af95-af37588dca9a">

**Comment by Grounded0** [comment]
I get no `CHOICE` menu with FreeDOS `COMMAND.COM`.

**Comment by Grounded0** [comment]
Can't execute eXo provided CHOICE.EXE:

<img width="1392" alt="Screenshot 2023-09-18 at 0 22 50" src="https://github.com/dosbox-staging/dosbox-staging/assets/48192273/d909eaa7-9396-4d9d-b05a-620814665de4">

**Comment by MasterO2** [comment]
Since Staging already has its own `CHOICE` command, the one that is included with the game can be moved into another folder so that Staging uses its own `CHOICE` command.

**Comment by Grounded0** [comment]
Yeah i'm merely pointing out that the eXoDOS release of the game is broken because it relies on Windows version of `CHOICE` which naturally does NOT execute under DOS.

**Comment by Grounded0** [comment]
I'll give this ticket a good nights sleep and then i shut it as not our problem since the game seems to run fine.

**Comment by Grounded0** [comment]
@MasterO2 take the game for a short spin since i'm too fed up to play it after figuring this out. Back to Jane's ATF.

**Comment by MasterO2** [comment]
In Windows 10 (64-bit), I moved the game-supplied `CHOICE.EXE` into another folder, opened **Dosbox-Staging 80.1 (64-bit)**, then ran `RUN.BAT` in the game folder. This allowed the BAT file to run properly using Staging's own internal `CHOICE` command.

Even though you can navigate to the imgmounted image as normal and look at files (imgmounted as the **D drive**), I was only able to run the first two choices in `RUN.BAT` because the game does **not** detect the CUE file as an imgmounted CD-ROM.   The `CUE` and `IMG` files are located under the `rarkani1\cd` folder.

These are the messages I got in the Dosbox Staging Status Window in regards to the `CHOICE` command:

```
CHOICE: '1' (#1 of 4 choices)
2023-09-17 18:24:44.146 | CONFIG: "default" is an invalid value for: mididevice. Using the default: auto
2023-09-17 18:24:44.288 | MIDI: Opened device: win32
```

```
CHOICE: '2' (#2 of 4 choices)
2023-09-17 18:26:19.618 | MT32: Failed to find ROMs for model auto in:
2023-09-17 18:26:19.618 | MT32:  |- mt32-roms\
2023-09-17 18:26:19.621 | MT32:  |- C:\Users\---\AppData\Local\DOSBox\mt32-roms\
2023-09-17 18:26:19.623 | MT32:  `- C:\mt32-rom-data\
2023-09-17 18:26:19.624 | MIDI: Can't open device: mt32 with config: ''
2023-09-17 18:26:19.768 | MIDI: Opened device: win32

Note: I removed the username after C:\Users which is why you see the three dashes --- there.
```

Once I got into the actual game itself, the intro cutscenes played without issues and the gameplay does not appear to have any obvious issues graphically speaking.  Just be aware that you have to press `Escape` if you do not want to keep watching the intro cutscenes over and over so that you can actually start playing the game.

**Comment by johnnovak** [comment]
Great to see you guys started going through the list of games @rderooy @MasterO2 @Grounded0 🎉 Massive thanks for the effort! 🙇🏻‍♂️ ❤️ 

Just making sure that you're playing each game a little bit (say at least 5-10 minutes) too, right? I found issues in the past that were not readily apparent, e.g. the game started up fine and seemed to work, but certain sound options resulted in hard crashes a few minutes in (from memory, Might and Magic – World of Xeen was one with MT-32 sound).

It would be good if guys also documented what you tested, for example:

- Started
- Checked out all the menu and settings screens
- Played for 5 minutes and progressed to the second level

Something brief but at the same time very accurate, so if we need to re-investigate a game, we'll know what was and wasn't tested. Thanks 😄

**Comment by Grounded0** [comment]
I give more play time when i wake up in order to close this with better confidence.

**Comment by johnnovak** [comment]
> I give more play time when i wake up in order to close this with better confidence.

Thanks @Grounded0. This is one of the very few games from the list I'm personally interested in 😄

**Comment by rderooy** [comment]
Strange that it includes a Win32 version of CHOICE.EXE that somehow vanilla DOSBox and Daum can actually run.

**Comment by kcgen** [comment]
> Strange that it includes a Win32 version of CHOICE.EXE that somehow vanilla DOSBox and Daum can actually run.

Yup; my understanding is this part of the external scaffolding used to select options about how you want to run the game (which happens to use a Windows console plus choice) and those answers then let eXo launch different DOSBox builds, with different confs or machine types.. and finally, inside of those you get to audio card selection.

With most of us testing on Linux and macOS, we're not getting the full eXoDOS experience, so just have to manually work through these nuances to test the game as best as possible.

**Comment by Grounded0** [comment]
I played the game for 35 minutes travelling the island, doing stuff and engaging in combat with no issues. Used Roland LAPC-I for music (feeding into Roland CM-32L emulator) + Sound Blaster for audio and the sound was great. No video issues even if the game pushes Mode 13h a bit. @GranMinigun also played the game briefly so closing this ticket for now.

**Comment by kcgen** [comment]
That's 4 for 4, in 3 days.
This megaticket is off to a great start.
Thanks @Grounded0 , @MasterO2 , and @rderooy.

**Comment by johnnovak** [comment]
> Strange that it includes a Win32 version of CHOICE.EXE that somehow vanilla DOSBox and Daum can actually run.

For the record @rderooy @kcgen, talked to Python about this yesterday, and he assured me they have removed all problematic CHOICE,EXE instances from the mounted DOS drives for all games in v6.

**Comment by Torinde** [comment]
> With most of us testing on Linux and macOS, we're not able to get the full eXoDOS experience

In case you're not aware there is a patch, but probably still not the full experience: https://www.retro-exo.com/linux.html
