### ISSUE TITLE
Investigate playability issues with Super Dog Story (1997)

### ISSUE THREAD

**Issue by kcgen** [dosbox-staging/dosbox-staging#2932]
### Context

Currently the eXoDOS project runs this game using [the DOSBox Daum fork](https://github.com/ykhwong/dosbox-svn-daum), which is understood to have specific emulation fixes not currently in upstream DOSBox (0.74.x and SVN) or active forks such as X, Pure, and Staging.

DOSBox Daum had 51 releases that included DOSBox SVN's commits ~r3600 through ~r3900, [spanning 2010 through 2015](http://ykhwong.x-y.net/).

### The goal of this ticket is to answer the following

Is Daum _still_ needed for this game?
- [ ] Does DOSBox SVN ([download latest](http://www.emucr.com/2023/09/dosbox-svn-r4483.html)) play it OK?
- [ ] Does DOSBox X ([download latest](https://dosbox-x.com/)) play it OK?
- [ ] Does DOSBox Staging ([download latest](https://dosbox-staging.github.io/downloads/development-builds/)) play it OK?

If Daum plays it better:
- [ ] What aspect is better?
- [ ] Which Daum release was the **_first_** to fix it?
    Use these builds [here](http://ykhwong.x-y.net/subpages/old.php) to narrow it down.

### How you can help

 1. Download the above lastest DOSBox SVN, X, and Staging builds.
 1. Ensure you have [eXoDOS v5](https://www.retro-exo.com/exodos.html) (or eventually v6)
 1. Find this game inside the eXoDOS installed folders (look for: `SDogStry/`)
 1. Run the game using the DOSBox SVN, X, and Staging builds.
    _If it plays fine (everything looks, sounds, and handles OK) then simply indicate as such. Your task is done!_

If SVN, X, and Staging all have problems, then try it with Daum:
 1. Download the [first and last Daum releases](http://ykhwong.x-y.net/subpages/old.php).
    Note: _Daum had the most releases for Microsoft Windows, so having a Windows system (or VM) will help the most to answer the last question above._
 1. Does the latest Daum release play it correctly? If so: summarize/describe how it's better than DOSBox SVN, X, and Staging (screenshots, video, audio records all help too).
 1. Find the earliest (or oldest) Daum release that fixed it.
    1. Run the Daum release half way between the known good release (where the game playing correctly) and bad release (where the game doesn't playing correctly) until you've narrowed it down to adjacent releases.
    1. It will take _at-most_ seven runs of different Daum versions to narrow this down (using this middle-selecting technique); so it's not as daunting as it seems! :-)

---

### Follow up by code contributors

If Daum plays it better, your answers (especially the last one that narrows down the fix to a specific release) are critical to helping isolate the chunk of code fixed the given bug.

Pull requests should credit:
- @ykhwong as the original code author,
- the test team member who confirmed and isolated the Daum release,
- yourself (PR author) as integrating the fix

The PR should include the `imported-from:` URL pointing to DOSBox Daum. For an example, see commit a35c7c889.

**Comment by rderooy** [comment]
Chinese Platform game using DOS4GW

Rather slow moving with all the tested DOSBox builds. But I found this video  of the game, using DOSBox SVN, where it plays quite a bit faster https://www.youtube.com/watch?v=i69MlEcT9Bk

As a test, I changed `cycles=max` to `cycles=50000` and it made no apparent difference to the in-game speed.

## DOSBox 0.74-3
The game play, but after a bit the sound stopped.

## DOSBox Daum - eXoDOS included version
Works fine

## DOSBox Staging 0.80.1
Works fine

## DOSBox-X 2023.09.01
Works fine

# eXoDOS dosbox.conf
```ini
# Config file for Dosbox-SVN Daum Jan 25, 2015
[sdl]
fullscreen=false
fulldouble=false
fullresolution=0x0
windowresolution=1280x960
output=direct3d
mapperfile=mapper.map
usescancodes=true
[dosbox]
machine=svga_s3
memsize=63
[render]
aspect=true
scaler=normal2x
[cpu]
core=auto
cputype=auto
cycles=max
[mixer]
[midi]
[sblaster]
[gus]
[speaker]
disney=true
[joystick]
[serial]
[dos]
[ipx]
[autoexec]
mount c .\eXoDOS\SDogStry
c:
@cls
@play
exit
```

**Comment by kcgen** [comment]
@rderooy , do your get the same result with Daum as I do in the video below?

### Daum (on Linux)

https://github.com/dosbox-staging/dosbox-staging/assets/1557255/757c0e19-ff0d-4d87-b7b3-d2f73897f475

Staging `main` (SVN looks equivalent):

https://github.com/dosbox-staging/dosbox-staging/assets/1557255/814daf7f-cb3e-494c-bf96-6362d5516103

This game sure looks like a Skunny knock off... :laughing:

**Comment by kcgen** [comment]
This video shows SVN playing it at more natural looking pace:

https://www.youtube.com/watch?v=i69MlEcT9Bk

However, my local build of SVN (optimized) at various cycle setting, core settings, etc.. never varies from the above recording.

I remember reading about a DOS call that would alter the PIT tick timer's rate, similar how games could also the sound blaster's playback rate.

I /don't/ think DOSBox (SVN and Staging) support it.. perhaps this game is trying to use it.

**Comment by rderooy** [comment]
@kcgen in those videos, you still in the "overworld", and yes that is how I experienced it. But you need to enter the platform part where you can really notice the difference.

**Comment by kcgen** [comment]
> @kcgen in those videos, you are still in the "overworld", and yes that is how I experienced it. But you need to enter the platform part where you can really notice the difference.

Ahh that helped a lot, @rderooy. Inside the level, you can tap ESC and adjust the speed to a lower (faster) value from the default (slowest) value of 5.

Here's the gameplay at speed 2, running at 60 fps:

https://github.com/dosbox-staging/dosbox-staging/assets/1557255/3df68e40-45d2-4061-b08c-c0174fdeae8a

**Comment by kcgen** [comment]
Thanks to your suggestion to get inside the level, @rderooy.

With this in-game speed modifier, it looks like the game is playing very smooth and without glitches. Closing.

**Comment by MasterO2** [comment]
Now added to Game Issues page:

https://github.com/dosbox-staging/dosbox-staging/wiki/Game-issues#super-dog-story
