### ISSUE TITLE
Investigate playability issues with Sooty and Sweep (1992)

### ISSUE THREAD

**Issue by kcgen** [dosbox-staging/dosbox-staging#2935]
### Context

Currently the eXoDOS project runs this game using [the DOSBox Daum fork](https://github.com/ykhwong/dosbox-svn-daum), which is understood to have specific emulation fixes not currently in upstream DOSBox (0.74.x and SVN) or active forks such as X, Pure, and Staging.

DOSBox Daum had 51 releases that included DOSBox SVN's commits ~r3600 through ~r3900, [spanning 2010 through 2015](http://ykhwong.x-y.net/).

### The goal of this ticket is to answer the following

Is Daum _still_ needed for this game?
- [ ] Does DOSBox SVN ([download latest](http://www.emucr.com/2023/09/dosbox-svn-r4483.html)) play it OK?
- [ ] Does DOSBox X ([download latest](https://dosbox-x.com/)) play it OK?
- [ ] Does DOSBox Staging ([download latest](https://dosbox-staging.github.io/downloads/development-builds/)) play it OK?

If Daum plays it better:
- [ ] What aspect is better?
- [ ] Which Daum release was the **_first_** to fix it?
    Use these builds [here](http://ykhwong.x-y.net/subpages/old.php) to narrow it down.

### How you can help

 1. Download the above lastest DOSBox SVN, X, and Staging builds.
 1. Ensure you have [eXoDOS v5](https://www.retro-exo.com/exodos.html) (or eventually v6)
 1. Find this game inside the eXoDOS installed folders (look for: `SootySwe/`)
 1. Run the game using the DOSBox SVN, X, and Staging builds.
    _If it plays fine (everything looks, sounds, and handles OK) then simply indicate as such. Your task is done!_

If SVN, X, and Staging all have problems, then try it with Daum:
 1. Download the [first and last Daum releases](http://ykhwong.x-y.net/subpages/old.php).
    Note: _Daum had the most releases for Microsoft Windows, so having a Windows system (or VM) will help the most to answer the last question above._
 1. Does the latest Daum release play it correctly? If so: summarize/describe how it's better than DOSBox SVN, X, and Staging (screenshots, video, audio records all help too).
 1. Find the earliest (or oldest) Daum release that fixed it.
    1. Run the Daum release half way between the known good release (where the game playing correctly) and bad release (where the game doesn't playing correctly) until you've narrowed it down to adjacent releases.
    1. It will take _at-most_ seven runs of different Daum versions to narrow this down (using this middle-selecting technique); so it's not as daunting as it seems! :-)

---

### Follow up by code contributors

If Daum plays it better, your answers (especially the last one that narrows down the fix to a specific release) are critical to helping isolate the chunk of code fixed the given bug.

Pull requests should credit:
- @ykhwong as the original code author,
- the test team member who confirmed and isolated the Daum release,
- yourself (PR author) as integrating the fix

The PR should include the `imported-from:` URL pointing to DOSBox Daum. For an example, see commit a35c7c889.

**Comment by rderooy** [comment]
Trying to understand why this is shipped as a HDD (and floppy) image.

The only thing the HDD image does, is boot DOS, there is no config.sys, and all autoexec.bat contains is:
```
@echo off
cls
type old-game.nfo
a:
sooty
```

Simplifying the dosbox.conf to:
```ini
[autoexec]
@echo  off
imgmount a sooty.img -t floppy
a:
sooty
exit
```
Starts the game on DOSBox Staging and DOSBox-X. But it freezes the same way.
Running Daum with this setup, and the game exits straight away. DOSBox 0.74-3 likely directly exits, but DOSBox ECE (as included with eXoDOS) **can** run the game this way.

**Comment by kcgen** [comment]
Very interesting findings, @rderooy.

Another case where a fix has been isolated in Daum (and now ECE, in one of the patch additions).

**Comment by Burrito78** [comment]
I just mounted the sooty.img as drive A: and started the game.
Press CTRL+ESC to return to main menu.

Results (macOS Ventura 13.5.2/Apple M2):

**DOSBox Staging 0.81.0-alpha-1689**
All OK! No lockups for me.

**DOSBox SVN	snapshot 12.09.23**
Game quits right back to the prompt when started.

**DOSBox-X v2023.09.01**
All OK! No lockups for me.

I don't run Windows so i can't test with Daum.

**Comment by kcgen** [comment]
Can't repro menu freezing. I'm using this conf (just as a minimum-approach):

```ini
[cpu]
cycles = 600

[sblaster]
sbtype = none

[midi]
mididevice = none

[speaker]
pcspeaker = on

[dos]
xms = false
ems = false
umb = false

[autoexec]
mixer pcspeaker 50
imgmount a sooty.img -t floppy
a:
sooty
```


https://github.com/dosbox-staging/dosbox-staging/assets/1557255/a31cfa60-7f52-4067-9af5-cf4e6b113721

**Comment by rderooy** [comment]
I cannot give this another go until later today

**Comment by rderooy** [comment]
Figured out the problem. It was because I had a joystick (PS4 controller) plugged it, which with the default setup prevents the keyboard from working.

I had tried to use both the mouse and joystick previously, but only the left stick. For some weird reason that does not work with this game and I had to use the left stick instead.

Adding the fragment below to the dosbox.conf solves the issue with the wrong stick, and also allows the keyboard to work with the controller plugged it:

```ini
[joystick]
joysticktype=2axis
```

During the initial title screen, if you press a joystick key, only the joystick will work. If you press a key on the keyboard, only the keyboard will work.

**Comment by kcgen** [comment]
Very interesting discovery, @rderooy.

> During the initial title screen, if you press a joystick key, only the joystick will work. If you press a key on the keyboard, only the keyboard will work.

This "implied control" selection is a nasty trap door for users.

Makes me think the best solution is `joysticktype = hidden`. This avoids the trap door and leaves both control methods available (simultaneously), provided the joystick actions are mapped over to the correct keyboard buttons.

**Comment by Grounded0** [comment]
The game seems to run well so closing. If in dispute please reopen.
