### ISSUE TITLE
Investigate playability issues with Town With No Name (1993)

### ISSUE THREAD

**Issue by kcgen** [dosbox-staging/dosbox-staging#2939]
### Context

Currently the eXoDOS project runs this game using [the DOSBox Daum fork](https://github.com/ykhwong/dosbox-svn-daum), which is understood to have specific emulation fixes not currently in upstream DOSBox (0.74.x and SVN) or active forks such as X, Pure, and Staging.

DOSBox Daum had 51 releases that included DOSBox SVN's commits ~r3600 through ~r3900, [spanning 2010 through 2015](http://ykhwong.x-y.net/).

### The goal of this ticket is to answer the following

Is Daum _still_ needed for this game?
- [ ] Does DOSBox SVN ([download latest](http://www.emucr.com/2023/09/dosbox-svn-r4483.html)) play it OK?
- [ ] Does DOSBox X ([download latest](https://dosbox-x.com/)) play it OK?
- [ ] Does DOSBox Staging ([download latest](https://dosbox-staging.github.io/downloads/development-builds/)) play it OK?

If Daum plays it better:
- [ ] What aspect is better?
- [ ] Which Daum release was the **_first_** to fix it?
    Use these builds [here](http://ykhwong.x-y.net/subpages/old.php) to narrow it down.

### How you can help

 1. Download the above lastest DOSBox SVN, X, and Staging builds.
 1. Ensure you have [eXoDOS v5](https://www.retro-exo.com/exodos.html) (or eventually v6)
 1. Find this game inside the eXoDOS installed folders (look for: `twnoname/`)
 1. Run the game using the DOSBox SVN, X, and Staging builds.
    _If it plays fine (everything looks, sounds, and handles OK) then simply indicate as such. Your task is done!_

If SVN, X, and Staging all have problems, then try it with Daum:
 1. Download the [first and last Daum releases](http://ykhwong.x-y.net/subpages/old.php).
    Note: _Daum had the most releases for Microsoft Windows, so having a Windows system (or VM) will help the most to answer the last question above._
 1. Does the latest Daum release play it correctly? If so: summarize/describe how it's better than DOSBox SVN, X, and Staging (screenshots, video, audio records all help too).
 1. Find the earliest (or oldest) Daum release that fixed it.
    1. Run the Daum release half way between the known good release (where the game playing correctly) and bad release (where the game doesn't playing correctly) until you've narrowed it down to adjacent releases.
    1. It will take _at-most_ seven runs of different Daum versions to narrow this down (using this middle-selecting technique); so it's not as daunting as it seems! :-)

---

### Follow up by code contributors

If Daum plays it better, your answers (especially the last one that narrows down the fix to a specific release) are critical to helping isolate the chunk of code fixed the given bug.

Pull requests should credit:
- @ykhwong as the original code author,
- the test team member who confirmed and isolated the Daum release,
- yourself (PR author) as integrating the fix

The PR should include the `imported-from:` URL pointing to DOSBox Daum. For an example, see commit a35c7c889.

**Comment by johnnovak** [comment]
I looked at the issue tracker and was like "who's the asshole who started spammed our issue tracker like this??!?" 😅 

Well, I thought someone was intentionally trolling us or something, then saw it was you @kcgen 😄 Great job, it would be good to achieve full parity with other forks with these problematic games (and maybe we already have it, I guess we only have to test and see).

**Comment by kcgen** [comment]
Hey.. just doing as suggested :laughing: Was a nice suggestion by @Burrito78 and you to split the list into separate tickets.

There's a lot of 'em though! It's the only way to address them one by one, and have separate discussions. I sure hope some of them have already been addressed.. but we'll see :-)

**Comment by johnnovak** [comment]
> Hey.. just doing as suggested 😆 Was a nice suggestion by @Burrito78 and you to split the list into separate tickets.
> 
> There's a lot of 'em though! It's the only way to address them one by one, and have separate discussions. I sure hope some of them have already been addressed.. but we'll see :-)

I agree, best to threat them individually. Thanks @Burrito78 ! 🚀

**Comment by rderooy** [comment]
This is actually a Commodore CDTV game... It is basically an FMV style game, but with poor hand-drawn graphics, and very poor input response.

# dosbox.conf
```
# Config file for Dosbox-SVN Daum Jan 25, 2015
[sdl]
fullscreen=false
fulldouble=false
fullresolution=0x0
windowresolution=1280x960
output=direct3d
mapperfile=mapper.map
usescancodes=true
[dosbox]
machine=svga_s3
memsize=32
[render]
aspect=true
scaler=normal2x
[cpu]
core=auto
cputype=auto
cycles=auto
[mixer]
[midi]
[sblaster]
sbmixer=false
[gus]
[speaker]
disney=true
[joystick]
[serial]
[dos]
ems=false
[ipx]
[autoexec]
mount c .\eXoDOS\twnoname
imgmount d ".\eXoDOS\twnoname\cd\Town with no name.cue" -t cdrom
mixer sb 30
@c:
@cd twnoname
cls
@call town
exit
```

Running the game with DOSBox 0.74-3, it just exits straight away when starting the games executable (`DTVPLAY.EXE`).

Starting with DOSBox Daum, DOSBox Staging and DOSBox-X works fine.

**Comment by rderooy** [comment]
At one point with DOSBox Daum, I got some screen corruption. This did not happen with Staging and -X. I tried to take a screenshot of the corruption, but that turned out fine.

**Comment by Grounded0** [comment]
Played 20 minutes with no issues.

AVGN episode of this masterpiece:

https://www.youtube.com/watch?v=HfnNrISCFfk
