### ISSUE TITLE
Joysticktype setting isn't respected

### ISSUE THREAD

**Issue by GranMinigun** [dosbox-staging/dosbox-staging#294]
In DOSBox 0.74-3, if we set `joysticktype` to, say, `none`, game controller doesn't get initialized at all.

In DOSBox Staging, this setting seems to be completely ignored, and games always see joystick. Well, at least `none` is ignored - I'm not sure how to check other values. Resetting mapper doesn't help.
```
MAPPER: Found one joystick
MAPPER: Initialized Logitech Gamepad F510 with 6 axes, 11 buttons, and 1 hat(s)
```
@kcgen?

**Comment by kcgen** [comment]
Thanks @GranMinigun , looks like we should skip Joystick initialization here in `sdlmapper.cpp`:

```
static void MAPPER_Init(Section *sec) {
	(void) sec; // unused but present for API compliance
	QueryJoysticks();
 ```

And probably need similar skipping when destroying the mapper:

```
static void MAPPER_Destroy(Section *sec) {
    ...
	// Decrement our reference pointer to the Joystick subsystem
	SDL_QuitSubSystem(SDL_INIT_JOYSTICK);
```

**Comment by kcgen** [comment]
@GranMinigun , can you beat up `kc/joystick-init-1` from as many angles as you can? 
I've got one joystick, so was able to test those scenarios.

**Comment by GranMinigun** [comment]
Controller gets initialized when `joysticktype` is not `none`, games detect it, but buttons stopped working. Mapper recognizes input though.

**Comment by kcgen** [comment]
Thanks @GranMinigun ; can you try `kc/mapper-defreg-1`?
I've integrated this fix in there, and it appears to be working well from my side.

**Comment by GranMinigun** [comment]
All seems to be good, but:
1) I don't have a second controller to check `2axis` and `4axis_2`*;
2) I'm not sure where to check whether `fcs` and `ch` work as intended; and
3) Y axis on right stick isn't recognized by mapper, it uses triggers' axis instead (not related and should be addressed by b881409).

*Mapper binds triggers and right stick X axis to second joystick, but only one (first) device is reported to game anyway. Not a bug, of course.

**Comment by kcgen** [comment]
Thanks @GranMinigun!

Indeed - I'm also unable to check those other cases.  Fortunately the PR doesn't touch the number of joysticks nor how the different types are handled; so (at least logically) that should be unaffected. 

> Mapper binds triggers and right stick X axis to second joystick, but only one (first) device is reported to game anyway.

Yup. To properly support distinct joysticks in games, we will need to overhaul more of the joystick code, perhaps using something like: https://www.vogons.org/viewtopic.php?f=32&t=27452.

I would also like to leverage SDL2's  [game controller](https://wiki.libsdl.org/CategoryGameController) type, and have it take care of sorting out buttons, sticks, and pads for the various models in it's database (instead using the more simplistic [joystick](https://wiki.libsdl.org/CategoryJoystick) type).  This is free benefit we get with SDL2, so might as well use it.

**Comment by kcgen** [comment]
Closing; resolved in https://github.com/dosbox-staging/dosbox-staging/pull/299.
