### ISSUE TITLE
Game compatibility megaticket

### ISSUE THREAD

**Issue by Grounded0** [dosbox-staging/dosbox-staging#2945]
Modified: Thu 28 Mar 2024 20:44:21 UTC

Removed "Problematic games with DOSBox Staging" so i don't have to micromanage this list as games are getting opened and closed. You can check for up-to-date list of problematic games by opening label https://github.com/dosbox-staging/dosbox-staging/labels/game%20compatibility.

### Games run by DOSBox Daum in eXoDOS

- #2941 
- #2940 
- #2939 
- #2938 
- #2937 
- #2936 
- #2935 
- #2934 
- #2933 
- #2932 
- #2931 
- #2930 
- #2929
- #2928 
- #2927 
- #2926 
- #2925 
- #2924 
- #2923 
- #2922 
- #2921 
- #2920 
- #2919 
- #2918 
- #2917
- #2916 
- #2915 
- #2914 
- #2913 
- #2912 
- #2911 
- #2910 
- #2909 
- #2908 
- #2907 
- #2906 
- #2905 
- #2904 
- #2903 
- #2902 
- #2901 
- #2900 
- #2899 
- #2898 
- #2897 
- #2894
- #2893 
- #2892
- #2891
- #2890 
- #2889 
- #2888 
- #2887 
- #2886 
- #2885 
- #2882 
- #2881 
- #2880 
- #2879 
- #2878 
- #2877 
- #2876 
- #2875 
- #2874 
- #2873 
- #2872 
- #2871 
- #2949 
- #2950

### Connected issues and PRs

- #804

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by johnnovak** [comment]
I heard you like testing, comparing things, and focusing on details, @Torinde 😉

**Comment by MasterO2** [comment]
> I heard you like testing, comparing things, and focusing on details, @Torinde 😉

*hands @johnnovak a flamethrower.*

**Comment by Grounded0** [comment]
![office-slave_wage-slave-slaving_away-slave_wages-employees-njun3750_low](https://github.com/dosbox-staging/dosbox-staging/assets/48192273/37226f2b-4563-4f53-9af8-609d6ae61574)

**Comment by Torinde** [comment]
> I heard you like testing, comparing things, and focusing on details, @Torinde 😉

I planned to test the SimCity 13-character path problem, but that's still pending...
The three headed monster is supposed to grow more heads only _after_ you cut one of them, not just to multiply those by itself by two orders of magnitude

Are the following also in scope here?
- #1671 
- [Audio stuttering in D.O.G - Fight For Your Life (1997)](https://github.com/dosbox-staging/dosbox-staging/projects/7#card-43005053)
- [Corncob 3-D The Other Worlds Campaign (1992)", Corncob Deluxe, screen flickers; no flickering in Daum](https://github.com/dosbox-staging/dosbox-staging/projects/7#card-61261677)
- [Microsoft Flight Simulator v1.05 FPU DIV exceptions ... patch mentioned](https://github.com/dosbox-staging/dosbox-staging/projects/7#card-67424512)
- [Lone Wolf: The Mirror of Death works strange in Tandy mode. ...graphics is all corrupted... same with the "Tower of Fear" re-release](https://github.com/dosbox-staging/dosbox-staging/projects/7#card-68575043)
- [FITUP ... expects video banks to be swapped when exceeding segment limits](https://github.com/dosbox-staging/dosbox-staging/projects/7#card-70677633)
- [Gato's installer doesn't work: it has names with spaces, which is fine in real DOS](https://github.com/dosbox-staging/dosbox-staging/projects/7#card-71851613)

**Comment by kcgen** [comment]
Thanks for your help, @Torinde.

> Are the following also in scope here? 

Yes!  Thanks for rounding up those other game-compatibility tickets.

**Comment by Grounded0** [comment]
@johnnovak 

Added Problematic games with DOSBox Staging as you instructed.

**Comment by Torinde** [comment]
> Yes! Thanks for rounding up those other game-compatibility tickets.

@kcgen, should I create "Investigate compatibility" issues for those games? Or at least for the Corncob games as those are Daum related?

Mentioning here the other ["game compatibility" issues](https://github.com/dosbox-staging/dosbox-staging/issues?page=3&q=is%3Aissue+is%3Aopen+label%3A"game+compatibility"), which aren't Daum-related:
- #1231 
- #809 
- #610 

> Added Problematic games with DOSBox Staging as you instructed.

@Grounded0, now you have those listed twice. Should the list be split in "to be checked" and "Problematic games with DOSBox Staging" (e.g. checked, problem with Staging)?

**Comment by Grounded0** [comment]
There's a general listing and a problematic listing. Makes it more maintainable. We'll add those later after we've cleaned up this Daum list a bit.

**Comment by johnnovak** [comment]
> There's a general listing and a problematic listing. Makes it more maintainable. We'll add those later after we've cleaned up this Daum list a bit because its a priority.

Yeah, let's not solve all outstanding issues at once 😅 This is about retiring Daum, let's keep it to that.

**Comment by Torinde** [comment]
> This is about retiring Daum

OK, so I created issues only for the Daum related ones:
- #2949 
- #2950

**Comment by Torinde** [comment]
> There's a general listing and a problematic listing. Makes it more maintainable. We'll add those later after we've cleaned up this Daum list a bit because its a priority.

Whatever you prefer. I thought it's better if the "general list" becomes a kind of "not yet checked" (e.g. testers can pick open/green issues from here) and then if game works in Staging issue becomes closed/pink, if game has problem in Staging - entry is moved to the bottom list for developers to further look into it.
![image](https://github.com/dosbox-staging/dosbox-staging/assets/97228894/d2007061-0809-4209-afed-e829486849a9)

**Comment by Grounded0** [comment]
It adds to our maintenance workload because games maybe moved into and off the problematic section and thats a lot of editing and potential human errors like games being lost from the list. Document maintainability is a key since i don't have energy to lord over this constantly.

**Comment by johnnovak** [comment]
Let's not change the system midway through. Let's keep doing what we started out to do without merging any lists @Torinde .

**Comment by Grounded0** [comment]
Added to Problematic games with DOSBox Staging:

- #2908

**Comment by Grounded0** [comment]
Added to Games run by DOSBox Daum in eXoDOS:

- #2949 
- #2950

**Comment by Grounded0** [comment]
Added to Problematic games with DOSBox Staging

- #2905

**Comment by Burrito78** [comment]
I looked at all the open tickets and the testing phase is 99% done.

**Comment by johnnovak** [comment]
> I looked at all the open tickets and the testing phase is 99% done.

Great job everybody 🎉

**Comment by Torinde** [comment]
Can one more be sneaked in, not Daum related? 
- #1671 - reasons/fixes for all of those games are identified except:
Viper (1998) - [DOSBox 0.63](https://sourceforge.net/projects/dosbox/files/dosbox/0.63/) works, other versions/builds mostly crash, X gives an error

**Comment by Grounded0** [comment]
Once this Daum list is completed i plan to close this anyway because there's no megaticket left anymore. Everything else can be handled under game compatibility label from there on.

**Comment by Grounded0** [comment]
Added to Connected issues and PRs

- #804

**Comment by Grounded0** [comment]
Added to Problematic games with DOSBox Staging

- #2904

**Comment by Grounded0** [comment]
We just hit 100 % completion rate on this ticket. Thanks for everyone who helped out!

**Comment by johnnovak** [comment]
Great job everyone 🎉 @Grounded0 I'm short on time (as always), so if you want to help, extending the list of problematic games with condensed description of the issue to check for on real hardware would help a lot (max 2-3 lines, as short as possible).

**Comment by Torinde** [comment]
Corncob issues are not part of the eXoDOS project (unlike the other games) - mentioning in case that has any impact on visibility/traceability.

**Comment by Grounded0** [comment]
Removed from Games run by DOSBox Daum in eXoDOS

- #2949 
- #2950

Removed from Problematic games with DOSBox Staging

- #2949 
- #2950

**Comment by Torinde** [comment]
I meant to add the project label to those issues, not to delete them from this ticket. Sorry being unclear.

Corncob games are using Daum in eXoDOS, there are even tickets in the Staging eXoDOS project. What's missing is that the two issues don't have the project label:
![image](https://github.com/dosbox-staging/dosbox-staging/assets/97228894/055ec71c-4481-4f1b-803e-f2dabd6b8787)

**Comment by Grounded0** [comment]
😂

**Comment by Grounded0** [comment]
Added to Games run by DOSBox Daum in eXoDOS

- #2949 
- #2950

Added to Problematic games with DOSBox Staging

- #2949 
- #2950

**Comment by Grounded0** [comment]
@johnnovak @kcgen 

Can you add #2949 and #2950 to eXoDOS features list since i don't seem to have permissions to do so:

![271926281-055ec71c-4481-4f1b-803e-f2dabd6b8787](https://github.com/dosbox-staging/dosbox-staging/assets/48192273/9204f3e2-6932-4b62-97c2-602df0b1b69a)

**Comment by GranMinigun** [comment]
Done.

**Comment by Grounded0** [comment]
> Great job everyone 🎉 @Grounded0 I'm short on time (as always), so if you want to help, extending the list of problematic games with a condensed description of the issue to check for on real hardware would help a lot (max 2-3 lines, as short as possible).

I currently don't have capacity for this due to mental illness but anyone else please go ahead with this.

**Comment by Grounded0** [comment]
Added UTC timestamp to reduce disambiguity.

**Comment by Python-Exoproject** [comment]
Hi guys,

First of all, thank you everyone for all the assistance this has provided me for moving games away from Daum! It has been invaluable and useful to both Staging and eXoDOS.

Im adding this comment as one game was missed off the list which ive just created a ticket for and I was wondering if the same sort of analysis could be given to it as well. The ticket is #3635 

Thanks

**Comment by johnnovak** [comment]
> First of all, thank you everyone for all the assistance this has provided me for moving games away from Daum! It has been invaluable and useful to both Staging and eXoDOS.

Definitely, your tireless work of migrating eXoDOS gradually over to Staging is a great way to identify bugs, regressions and shortcomings in Staging. We very much appreciate it! 🏅 Keep up the good work! 😎 🤘🏻
