### ISSUE TITLE
Investigate playability issues with Corncob Deluxe (1994)

### ISSUE THREAD

**Issue by Torinde** [dosbox-staging/dosbox-staging#2950]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### What Operating System are you using?

None

### Context
Currently the eXoDOS project runs this game using [the DOSBox Daum fork](https://github.com/ykhwong/dosbox-svn-daum), which is understood to have specific emulation fixes not currently in upstream DOSBox (0.74.x and SVN) or active forks such as X, Pure, and Staging.

DOSBox Daum had 51 releases that included DOSBox SVN's commits ~r3600 through ~r3900, [spanning 2010 through 2015](http://ykhwong.x-y.net/).

### The goal of this ticket is to answer the following
Is Daum _still_ needed for this game?

* [ ]  Does DOSBox SVN ([download latest](http://www.emucr.com/2023/09/dosbox-svn-r4483.html)) play it OK?
* [ ]  Does DOSBox X ([download latest](https://dosbox-x.com/devel-build.html)) play it OK?
* [ ]  Does DOSBox Staging ([download latest](https://dosbox-staging.github.io/downloads/development-builds/)) play it OK?

If Daum plays it better:

* [ ]  What aspect is better?
* [ ]  Which Daum release was the **_first_** to fix it?
  Use these builds [here](http://ykhwong.x-y.net/subpages/old.php) to narrow it down.

### How you can help
1. Download the above lastest DOSBox SVN, X, and Staging builds.
2. Ensure you have [eXoDOS v5](https://www.retro-exo.com/exodos.html) (or eventually v6)
3. Find this game inside the eXoDOS installed folders
4. Run the game using the DOSBox SVN, X, and Staging builds.
   _If it plays fine (everything looks, sounds, and handles OK) then simply indicate as such. Your task is done!_

If SVN, X, and Staging all have problems, then try it with Daum:

1. Download the [first and last Daum releases](http://ykhwong.x-y.net/subpages/old.php).
    Note: _Daum had the most releases for Microsoft Windows, so having a Windows system (or VM) will help the most to answer he last question above._
2. Does the latest Daum release play it correctly? If so: summarize/describe how it's better than DOSBox SVN, X, and Staging (screenshots, video, audio records all help too).
3. Find the earliest (or oldest) Daum release that fixed it.
   
   1. Run the Daum release half way between the known good release (where the game playing correctly) and bad release (where the game doesn't playing correctly) until you've narrowed it down to adjacent releases.
   2. It will take _at-most_ seven runs of different Daum versions to narrow this down (using this middle-selecting technique); so it's not as daunting as it seems! :-)

### Follow up by code contributors
If Daum plays it better, your answers (especially the last one that narrows down the fix to a specific release) are critical to helping isolate the chunk of code fixed the given bug.

Pull requests should credit:

* @ykhwong as the original code author,
* the test team member who confirmed and isolated the Daum release,
* yourself (PR author) as integrating the fix

The PR should include the `imported-from:` URL pointing to DOSBox Daum. For an example, see commit [a35c7c8](https://github.com/dosbox-staging/dosbox-staging/commit/a35c7c88935bb7694c771187edce37b2ad38978b).

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by Torinde** [comment]
[Corncob 3-D The Other Worlds Campaign (1992)", Corncob Deluxe, screen flickers; no flickering in Daum](https://github.com/dosbox-staging/dosbox-staging/projects/7#card-61261677)
> In Corncob Deluxe, the intro screen flickers when the plane flies across the screen.
Staging is affected, while it works good (no flickering) in Daum.

Related: #2949 

Somebody who can, please replace the label with "game compatibility".

**Comment by rderooy** [comment]
Shareware flight-sim/combat game.

Issues seem to be identical to #2949

## DOSBox 0.74-3
Graphical flickering during intro (plane)
Seems to play fine

## DOSBox Daum - eXoDOS included edition
Less flickering in intro
Seems to play fine

## DOSBox ECE r4230 - eXoDOS included edition
black screen on startup

## DOSBox Staging 0.80.1
the same as DOSBox 0.74-3

## DOSBox-X 2023.09.01
Less flickering than DOSBox 0.74-3, but more than Daum

# eXoDOS dosbox.conf
```ini
# Config file for Dosbox-0.74
[sdl]
fullscreen=false
fulldouble=false
fullresolution=0x0
windowresolution=1280x960
output=overlay
mapperfile=mapper.map
[dosbox]
machine=svga_s3
memsize=64
[render]
aspect=true
scaler=normal2x
[cpu]
core=auto
cputype=auto
cycles=auto
[mixer]
[midi]
[sblaster]
[gus]
[speaker]
[joystick]
[serial]
[dos]
[ipx]
[autoexec]
cd ..
cd ..
mount c .\eXoDOS\
c:
cd CorncobD
cls
@call corncob
exit
```

**Comment by Grounded0** [comment]
Adding to Problematic games with DOSBox Staging due to audio static issue.

**Comment by Python-Exoproject** [comment]
related #3244

**Comment by Python-Exoproject** [comment]
I have found a way to remove the flickering when using Staging by using the dos_rate= setting.

As exodos needs to be compatible on multiple users systems can someone confirm that using auto cycles and dos_rate=140 fixes the issue for them as well? If it does, are there any side effects to using dos_rate that I should be aware of?

I wonder if the magic sauce that Daum has to make these games flicker free is related to what dos_rate does

**Comment by johnnovak** [comment]
@Python-Exoproject 
It is possible to completely get rid of the flicker with the new `vmem_delay` option.

See the details and the config to fix the game here: https://github.com/dosbox-staging/dosbox-staging/pull/3597
