### ISSUE TITLE
Various problems with the `model` setting for the MT-32 emulation

### ISSUE THREAD

**Issue by johnnovak** [dosbox-staging/dosbox-staging#2969]
A couple of problems with the `model` setting for the MT-32:

- The `mt32` and `cm32l` symbolic model settings stopped working (probably a regression).
- Changing `model` only takes effect when resetting the MIDI device with `mididevice = mt32` (very confusing).
- The full list of accepted values should be documented in the config description.
- Add support for `cm32ln`.

**Comment by weirddan455** [comment]
I'll take a look at this.

>  The mt32 and cm32l symbolic model settings stopped working (probably a regression).

This one looks to be my regression from the first PR I made to this project:  https://github.com/dosbox-staging/dosbox-staging/pull/2591

**Comment by weirddan455** [comment]
PR for the first point is up (was a very simple fix).

>  Changing model only takes effect when resetting the MIDI device with mididevice = mt32 (very confusing).

I looked at this.  The way we have the MIDI class set up makes this a bit annoying.  Usually, we have Init and Destroy functions for each section.  However, the MIDI class "manages' each of the MIDI handlers.  The MT32 section doesn't self-init (it has an empty init function that does nothing).  It instead gets initialized from the MIDI section.  I have an idea of how I might fix it though.

**Comment by johnnovak** [comment]
Sorry @weirddan455 , but I'm already in the middle of implementing this. I did self-assign it a while ago, so in such cases when the ticket is already assigned to someone it's best to check with the person to avoid wasted effort.

The auto reinit on ROM model change is tricky, most likely I won't do that for now, though. You can continue to look into that if you're interested, but PR incoming for the rest in a day or two.

**Comment by johnnovak** [comment]
Fixed.

**Comment by weirddan455** [comment]
>  Changing model only takes effect when resetting the MIDI device with mididevice = mt32 (very confusing).

Did you fix this bit or are we just not worrying about that for now?

**Comment by johnnovak** [comment]
> > Changing model only takes effect when resetting the MIDI device with mididevice = mt32 (very confusing).
> 
> Did you fix this bit or are we just not worrying about that for now?

I knew I forgot something! Changed the top description.
