### ISSUE TITLE
Terminator Skynet Cant Create Swap File

### ISSUE THREAD

**Issue by orderorder** [dosbox-staging/dosbox-staging#2978]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### What Operating System are you using?

Linux x86_64

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

When i try to launch the game it says:

DOS/4GW Profesional error (2504): cant create swap file ""
DOS/4GW Profesional fatal error (1011): VMM initialization error [1]

In the stable version 0.80.1 it works well, dont show this error

### Steps to reproduce the behaviour.

Explain how to reproduce
1. 
2.
3.

### Your configuration

```ini
core      = auto
cputype   = pentium_slow
cycles    = max

memsize   = 32
```

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by kcgen** [comment]
Can you try the latest `main` build? 

We had a small care-related filesystem regression that was recently fixed up: https://github.com/dosbox-staging/dosbox-staging/pull/2971

**Comment by johnnovak** [comment]
For a moment I read this _literally_; I thought it's either a joke entry, or an _actual_ message from SkyNet 😅

**Comment by orderorder** [comment]
> Can you try the latest `main` build?
> 
> We had a small case-related filesystem regression that was fixed up: #2971

Stay the same error with the latest build

**Comment by FeralChild64** [comment]
Looks like another attribute support regression - game still works with commit https://github.com/dosbox-staging/dosbox-staging/commit/6e0f36df811a6ef4165f7a3a6d515023912e573f, but fails with commit https://github.com/dosbox-staging/dosbox-staging/commit/0823071ae0eea05efec1329b6c81d86a43ae3899

Workaround for now would be to use DOS32A extender to play the game.

**Comment by FeralChild64** [comment]
OK, found the core reason of the regression. @orderorder, many thanks for reporting this!
