### ISSUE TITLE
Alone in the Dark - broken text rendering

### ISSUE THREAD

**Issue by FeralChild64** [dosbox-staging/dosbox-staging#2984]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Different version than latest?

current GIT main, e755b9e53042b2fdb0bf0917b128422c15216c28

### What Operating System are you using?

Linux x86_64

### If Other OS, please describe

Gentoo

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

When using dynamic CPU core, the main menu of the game gets corrupted once you move the cursor:

![bug](https://github.com/dosbox-staging/dosbox-staging/assets/48332137/20cdb22a-a776-4c3b-83d6-6779e2cd4450)

The problem only occurs on current GIT main; on 0.80.1 the game works correctly.

### Steps to reproduce the behaviour.

1. Set `core = dynamic` (with `core = normal` the problem does not occur)
2. Start _Alone in the Dark_ game (I have used the CD version)
3. In the main menu press cursor up/down few times to move the highlight
4. The menu text gets broken; if you start the game all the in-game texts are broken in a similar way

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by kcgen** [comment]
Great find, @FeralChild64.

Interesting.. `core = auto` is OK, but explicitly setting `dynamic` triggers it.

Also confirmed in the ~5.5 MB floppy edition.  Bisecting with:

```ini
[cpu]
core = dynamic
cycles = 10000

[autoexec]
mount c .
c:
autotype -w 0.2 enter , esc , down up down
TATOU.COM
```

**Comment by kcgen** [comment]
Can't repro on ARM64.

**Comment by weirddan455** [comment]
Bisected to fa4c535efe99e60a004c1053e6b1be4c75549f55 as the first bad commit.

Note for future bisections:  I had to bisect with release builds for this because many of the commits were crashing with a SIGABRT (some iterator compare error) when attempting to start the game preventing me from testing this bug.  Release builds were unaffected.

**Comment by johnnovak** [comment]
Can reproduce reliably on Windows with this config and Soundblaster Pro sound using the eXoDOS v5 version:

```ini
[cpu]
cycles = 6000
core = dynamic
```

To reproduce 100% of the time, you need to wait until the intro animation finishes, press enter twice to turn the page, then use the up & down cursors keys until the problem manifests (sometimes it takes 3 keypresses, sometimes more than 10).

Can't reproduce on macOS using the same method.

**Comment by weirddan455** [comment]
I've got a fix.  We're not zeroing out the newly allocated memory in `GrowWriteMask`.  Before we were using `std::make_unique` which does zero out the memory.
