### ISSUE TITLE
Sync 3rd party ported-in dependencies prior to 0.81 testing

### ISSUE THREAD

**Issue by kcgen** [dosbox-staging/dosbox-staging#2998]
```
src/libs
├── decoders
│   └── docs
├── enet
│   └── include
├── fontstash
├── ghc
│   └── ghc
├── loguru
├── manymouse
├── mverb
├── nuked
├── PDCurses
│   ├── common
│   ├── pdcurses
│   └── sdl2_queue
├── residfp
│   └── resample
├── stb_truetype
├── tal-chorus
├── whereami
└── YM7128B_emu
```

Snipped from the above list:

```
├── sdlcd     -> Internally maintained transplant from SDL 1.x
│   ├── dummy
│   ├── linux
│   ├── macosx
│   └── win32
└── zmbv      -> Not 3rd party code
```

**Comment by kcgen** [comment]
Examples of prior sync PRs:

https://github.com/dosbox-staging/dosbox-staging/pulls?q=is%3Apr+sync+label%3A%22upstream+sync%22

**Comment by weirddan455** [comment]
sdl_truetype is up to date.  Hasn't had an update upstream in 2 years.  I ran a shasum and ours matches exactly with the upstream file:  https://github.com/nothings/stb/blob/master/stb_truetype.h

I believe the version of SDL CD we have is unmaintained upstream.  It's from SDL 1.  There is an implementation of SDL CD in the SDL1->2 comparability layer that is maintained:  https://github.com/libsdl-org/sdl12-compat

It would take more work than a simple sync to update though.  Maybe something to do after 0.81?

**Comment by kcgen** [comment]
Thanks for poking through the list, @weirddan455.

> I believe the version of SDL CD we have is unmaintained upstream. It's from SDL 1.

Yup; SDL dropped its host-level CDROM drive interface in the transition to SDL 2.x; so when Staging moved from SDL 1.x to 2.x, this "functional regression" became a sore point that some users were quite unhappy with.

Through a [mega-PR effort](https://github.com/dosbox-staging/dosbox-staging/pull/1540), Wengier transplanted the cross-platform functionality from SDL1. I think you've helped fix and maintain this, too :blush: :+1: !

I think SDL2 is missing this functionality (and has no plans to restore it, which is fine.. CDROM drives are now retro hardware themselves.. but I understand the desire for folks to play their DOS games via original media).

Looking at the compat12 code, they've stubbed it out with MP3 playback:

https://github.com/libsdl-org/sdl12-compat/blob/bfc8f941eb70a57b24885f841bb05b690a659a12/src/SDL12_compat.c#L9015-L9040

So we'll keep carrying/maintaining this code so long as it makes sense.
Perhaps with time, host OSes will drop their CDROM APIs, then this layer will eventually become orphaned and dropped.

**Comment by johnnovak** [comment]
> The best thing to do would probably be to call Win32 API directly for Windows and have the sound go through our mixer properly, similar to how I wrote the Linux code. Or just drop support for it if most people don't care. I'm one of the old fogeys that still has a CD drive in his computer (well it's a blue ray burner but it still does CDROM). 😛

That might be a good idea, but we're in finishing outstanding business mode now; our focus should be 0.81.0 now. While I cannot prevent anyone from working on nee features, we won't merge anything new from now until v0.81.0 RC and then the final release after that is out. RC will e released in Dec if things go to plan, the the final only early next year, ideally by Feb.

**Comment by johnnovak** [comment]
@weirddan455 sdl_truetype is not use currently, but please leave it alone; I introduced it for the OSD stuff when there was a chance that @Wengier will use it before me for TrueType console support (but then he disappeared). I'll still need it whenever I get to the OSD stuff, so it's pointless to remove it.

**Comment by weirddan455** [comment]
>  Our Windows users still vastly outnumber macOS and Linux users, and this is a quite distinct feature, so if you're interested in improving it so CD Audio goes through the mixer, I'm happy to keep it, even without macOS support.

I was thinking this would be a way to drop SDL CD entirely and just use Win32 API directly instead (similar to how we're doing on Linux).  If MacOS is already broken, SDL CD isn't helping us there.

I may look into it later but yeah I'll hold off until after 0.81 release as it could cause regressions.  I'm not that motivated to touch Win32 API in the first place so no big deal :stuck_out_tongue: 

>  sdl_truetype is not used currently, but please leave it alone

Yep, I was just verifying the file is up to date with upstream already.  So, nothing to do here.

**Comment by weirddan455** [comment]
fontstash has a pretty large diff which doesn't make a lot of sense to me.  The project hasn't had a commit since 2019 and says on the README that it's not actively maintained.  We only have 1 commit bringing the file in and it's from 2022.

https://github.com/memononen/fontstash

```
$ git log src/libs/fontstash/fontstash.h 
commit b204e392685b5f3bb2a0b7bfd9f680a12c3f10ab
Author: Mikko Mononen
Date:   Tue Nov 8 20:21:44 2022 +1000

    Add fontstash library
    
    Font stash is light-weight online font texture atlas builder written in
    C. It uses stb_truetype to render fonts on demand to a texture atlas.
```

**Comment by weirddan455** [comment]
Wait, are we even actively using fontstash?  I don't see anyone `#include`'ing this thing:

```
$ git grep fontstash
LICENSE:   - fontstash: Zlib
vs/dosbox.vcxproj:    <ClInclude Include="..\src\libs\fontstash\fontstash.h" />
vs/dosbox.vcxproj.filters:    <ClInclude Include="..\src\libs\fontstash\fontstash.h">
vs/dosbox.vcxproj.filters:      <Filter>src\libs\fontstash</Filter>
vs/dosbox.vcxproj.filters:    <Filter Include="src\libs\fontstash">
```

**Comment by weirddan455** [comment]
ghc is already synced to the latest version in 204bb9ad1f0212ea0e0be78ff9db39324cbedaf8

**Comment by johnnovak** [comment]
> fontstash is bit-rotting; issues like compilation failures and bugs have gone unaddressed for 5+ years: https://github.com/memononen/fontstash/issues.
> 
> This is similar to loguru, where the author also hasn't given co-maintainer rights to grow the team - so people have had to fork fontstash to make improvements:
> 
> ![2023-10-16_07-05](https://user-images.githubusercontent.com/1557255/275546188-f9418b46-32b5-4720-948f-f9cbaf16b054.png)
> 
> Maybe we should switch upstreams to one of these active forks?

On the surface, yes 😄 In practice, myself and other project have been using it fine for years. See my comment here: https://github.com/dosbox-staging/dosbox-staging/pull/3013#issuecomment-1765362721

It's tiny enough that you can copy in in your project and "own" it. Like apparently many other projects have done. Having said that, I haven't encountered a single bug in the past few years since I'm using it.

**Comment by johnnovak** [comment]
@weirddan455 mverb and tal-chorus; those are DSP algos and never need updates. Treat them like a hardware DSP box; the DSP algo created in 1980 won't stop working in 2050 because the "world has moved on" 😄 Same as DOS code 😄 

We can do trivial changes to remove warnings, etc. of course, but we own these. tal-chorus is hard to find; it was part of a larger framework so I had to change and remove a few internal deps. Practically we own that too.

**Comment by weirddan455** [comment]
Just put a PR in for YM7128B_emu.  I've now gone through the entire list.

Question marks on PDCurses and residfp as mentioned above where I was not sure what to sync from.

**Comment by kcgen** [comment]
@weirddan455 -- I think you've got them all, right?

**Comment by weirddan455** [comment]
Yeah except for PDCurses and residfp as I mentioned.

**Comment by kcgen** [comment]
> Yeah except for PDCurses and residfp as I mentioned.

Sorry for the delay!

For resid, sync from:

https://github.com/libsidplayfp/libsidplayfp/tree/master/src/builders/residfp-builder

The only delta between us and upstream is the use of initial values (in our copy). You'll be able to tell which changes can be ignored just based on this.

The author is open to improvements (some prior ones: https://github.com/libsidplayfp/libsidplayfp/issues?q=is%3Aissue+is%3Aclosed+author%3Akcgen), so any PRs upstream would be awesome to narrow the gap!

As for PDCurses - @kklobe , I think this came from ustream on github?

@weirddan455, the notable difference is the addition of a shared event queue to handle keystrokes. I think it's relatively self-contained.

I also recall fixing quite a few minor C function prototypes just to mop up warnings. (PDCurses caused a large spike in our Coverity issues earlier this year). Hopefully there's not much new!

**Comment by kklobe** [comment]
> As for PDCurses - @kklobe , I think this came from ustream on github?

Correct, I started with the github repo.
 
> @weirddan455, the notable difference is the addition of a shared event queue to handle keystrokes, added by @kklobe . I think it's relatively self-contained. @kklobe - do you remember any other functional changes you made?
> 

I only added the shared queue and also a [very minor cleanup](https://github.com/wmcbrine/PDCurses/pull/132) to allow C++ compilation. The shared queue was needed to avoid a dueling `SDL_PollEvent` setup.

**Comment by kcgen** [comment]
Closing this out; all the non-debuggger deps have been sync'd (leaving only PDCurses as a potential update, but not critical). Thanks for all the sync--ups, @weirddan455 !
