### ISSUE TITLE
Problem Creating shortcuts using different CONF files

### ISSUE THREAD

**Issue by lordarmchair** [dosbox-staging/dosbox-staging#2999]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### What Operating System are you using?

Windows 7

### Whats your question and how can we help?

Please forgive me if this has been addressed, but for the life of me, i cannot get any combination of commands to start dosbox staging v.80 to use a different conf file. It either ignores the command completely, or does odd things like trying to access the c: drive then running random garbage words as commands that are included in the shortcut. e.g.
"C:\Users\L0rdArmchair\AppData\Local\Programs\DOSBox Staging\dosbox.exe" -config "c:\dosboxwin.conf"
yields the command prompt output
Z:\ MOUNT C "c:"
Directory c: doesn't exit!
You must mount it first. Type intro or intro mount for more information.
Z:\DOSBOXWIN.CONF
Illegal command: DOSBOXWIN.CONF.

then it goes on to run the autoexec from the primary config file
what am i doing wrong?
All im looking to do is start an instance of Doxbox Staging with a different conf file to keep windows and dos games seperate.

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by kcgen** [comment]
Dear Lord ArmChair, use `-conf` (instead of `-config`).

You can pass the `-h` or `--help` to see the CLI arguments.
