### ISSUE TITLE
Scaler by default

### ISSUE THREAD

**Issue by es20490446e** [dosbox-staging/dosbox-staging#301]
With the inclusion of the **sharp** glshader and **SDL2**, many scalers no longer have poor performance or look blurry as they used to.

Looking at the [Screenshots](https://github.com/dosbox-staging/dosbox-staging/files/4505019/Screenshots.zip) taken on a bunch of games these were the **findings**:
- Any game will look better using one of the following **scalers**: advinterp3x, advmame3x, hq3x.
- **advmame3x** has less artifacts than **advinterp3x**, with no drawback.
- **hq3x** result in more reliable 2D shapes, but will make 3D look somehow blurry.
- The scalers didn't affect performance in a **desktop PC** 12 years old.
- hq3x slightly affected performance in very punctual situations on Jazz in a 11 years old **laptop**, in form of micro-jumps. But didn't on the PC.

So the **suggestion** is having these by default:
```
scaler = advinterp3x
glshader  = sharp
```

I can create a **pull request** if needed.

**Comment by dreamer** [comment]
At the moment I am working on something else and can't write long detailed post, but from technical and usability perspectives, `scaler` option and implementation have *lots* of drawbacks (yeah, including performance drawbacks… even when using `scaler=none` - which in reality is `scaler=normal1x`). When dealing with games using up to 640x480, the performance problems are not really visible on modern hardware (except small devices like RPi), but if we want to improve performance for games using 640x480 or more, then `scaler` code is problematic.

In the future, I would be quite happy if we could get rid of software scalers completely and rely only on shaders for upscaling/resizing/modifying the visual output.

I suggest you should take a look at other available `glshader` values - most "scalers" are reimplemented in there, but it would be helpful to have a visual reference about quality difference between available scalers and shaders.

One more thing is… scaler quality is *very* subjective and any value other than `none` might ruin artwork for some games. It will be a hard sell for other users to agree, that anything other than straight upscaling of pixels should be the default option.

**Comment by dreamer** [comment]
Or, I will revise/simplify my answer:

If you're asking to change to:

    scaler = advinterp3x # or any other, except "none"
    glshader  = sharp

then my answer is **hard** no, as it will cause maintenance and implementation headaches in the future.

If you're suggesting a change to something like:

    scaler = none
    glshader  = advinterp3x 

Then I have my subjective opinion about that, but I am withholding the judgement until I'll hear opinions of larger number of users :)

**Comment by kcgen** [comment]
I agree; software scaling made sense when onboard graphics cards didn't have pixel shaders or full hardware acceleration - but those years have passed.  

Now even a $10 battery-powered Raspberry Pi-A stick and basic cellphones support hardware acceleration.

So based on that, software scaling now acts as a maintenance burden and an unnecessary configuration option that will only confuse users and harm their experience.

The sooner we drop it the better!

**Comment by es20490446e** [comment]
You aren't understanding, extract and compare [these](https://github.com/dosbox-staging/dosbox-staging/files/4506610/Filter.combinations.zip) fullscreen.

**Comment by kcgen** [comment]
@es20490446e; good point, and great screenshots to show the effect.

So right now, its possible to push the result from software scaling through a GLshader to create new (and unique) result, which wouldn't be possible with just one or the other.

The good news is that new GLshaders can be written that produce the same end-result! (although yes.. that work needs to be done, and for the desired combos.. ).  But technically, the pure-shader approach will be lower-latency and essentially eliminate the CPU burden associated with software scaling.

**Comment by es20490446e** [comment]
What if sharp had its dedicated option, and could always be applied on any other shader? Do you think that could be a good idea?

**Comment by kcgen** [comment]
We would need new code to apply two shaders.. essentially a shader pipeline. But I'm not even sure if that's possible. Ultimately though, the most efficient method is to always "flatten" whatever effects you want into a single shader.  So for example, we could have "sharp-hq", and "sharp-xbr4".  You could have scanline versions of them too; "sharp-xbr3-scanlines".. and so on.
I don't know much about shaders, so am not sure how hard it is to write these (assuming you had the prior shader algorithm/code to work from).

**Comment by tyrells** [comment]
To add to what @kcgen is saying, I know libretro (where I have ported several of these shaders from) supports "shader chaining", so it is definitely a viable solution, but I don't know if the dosbox code currently supports it.

**Comment by es20490446e** [comment]
It calls my attention that that the [pixel perfect shadder](https://github.com/tyrells/dosbox-svn-shaders/blob/master/interpolation/pp.glsl) has two main functions...

**Comment by dreamer** [comment]
@tyrells no, it does not - we can only submit one shader at a time right now. But I hoped to revise this design when I'll start work on Vulkan backend. Overall I was planning to contact you about bundling  shaders you developed directly with dosbox-staging source code, so users won't need to install them (or maybe even replacing `sharp` with `pixellate`, but I discovered some problems during testing). But I wanted to finish 0.75.0 release first and convert existing shaders to C++11 raw string syntax soon afterwards (that will make them much more readable and easier to modify).

@es20490446e pixel perfect does not need a shader even :) it can be achieved with clever viewport calculation - this way the code is smaller, existing shaders can (or rather: will) be applied on top of pp and pp is compatible with all texture backends (DirectX, DirectX11, Metal, etc).

**Comment by dreamer** [comment]
> You aren't understanding, extract and compare [these](https://github.com/dosbox-staging/dosbox-staging/files/4506610/Filter.combinations.zip) fullscreen.

Is `hq3x alone.png` a hq3x scaler or shader?

> The fact that the filter is as scaler or a shader doesn't matter.

It does matter very much :(

"Scalers" are implemented purely in software, and original authors went out of their way to obscure the code (grrrrr) - in result, the code is impossible to read by humans and extremely hard (impossible in practice) to vectorize by compilers (I needed to expand all macros via GCC to even understand what this code does). My performance tests indicated, that normal1x scaler (aka 'none', the fastest one which should literally do barely any work at all) takes about 2-4% of emulation time on my desktop computer (It should do <0.5%, or maybe even less in my opinion).

**Comment by es20490446e** [comment]
When I said "it doesn't matter" I was just saying "not what I was pointing out", you know 😉

[scaler-vs-shadder](https://github.com/dosbox-staging/dosbox-staging/files/4507056/scaler-vs-shadder.zip)

**Comment by es20490446e** [comment]
That said there's a [shader version of hqx](https://github.com/CrossVR/hqx-shader/tree/master/glsl), although I guess you already knew that.

**Comment by dreamer** [comment]
@es20490446e I didn't know about hq in shader version, thanks! :) Now someone needs to test to make sure it works with dosbox-staging, so we could bundle it as one of builtin shaders ;)

**Comment by es20490446e** [comment]
When I have a moment I will have a look.

Also, do you think it really makes sense anymore having multiple scales (x2,x3,x4) of a filter?

Cause I guess those existed only for performance reasons, reasons that no longer seem to exist.

**Comment by tyrells** [comment]
I had a quick look at this yesterday. I don't have a full understanding of all the rendering code, but I think there are currently a couple of limitations currently that prevent us from converting all the scalers into shaders:

1. Shaders can not currently specify a manual scaling factor (e.g. 2x, 3x, etc.) - the scaling factor is calculated automatically based on the original source input size (e.g. 320x200) and the output window/fullscreen size. On a separate note: @dreamer I was thinking the same thing regarding not requiring a shader for pixel-perfect mode, being able to independently set the X & Y scaling factors programmatically, should be enough to implement this...

2. The HQx shader requires the loading of additional textures, which are used as part of the shader calculation. Currently the only texture that DOSBox loads is the input source image.

3. Some of the more efficient shader implementations (again using HQx as an example) require multiple shader passes.

**Comment by dreamer** [comment]
@tyrells regarding pixel-perfect - we already have it done with `output=texturepp` - the way I described it is exactly how @ant-222 ported his patch to our codebase; right now it's only used for `texture` output, but updating it for `opengl` is rather easy task (but conflicted a bit with resizable window support, and I don't want to risk new regressions before 0.75.0, because we're [almost there](https://github.com/dosbox-staging/dosbox-staging/projects/2)). So work on pixel-perfect is not finished, but the functionality is already available to our users :)

**Comment by es20490446e** [comment]
So do you think the shader is something I would be able to test without having to write extensive sections of code?

**Comment by i30817** [comment]
why would you want to have pixel perfect as a software scaler when it has a glshader implementation nowadays?

If you're thinking of combinations, isn't it better to make dosbox support multiple shader passes and implement glshaders for what's still in 'software' for hardware+hardware than only have the possibility of combining software+hardware?

Meaning i kind of agree it's time to drop the scaler setting - or at least making it 'not special' and importing one 'default' fallback scaler to the 'glshader' zone as a fallback if nothing hardware works.

imagine that there is one setting 'filter' (for example) that can have a software fallback (sharp for instance) and many glshader, with multiple passes possible by combining them eg:

`filter=pixel_perfect;supereagle` (likely a abomination but you get my meaning)

**Comment by es20490446e** [comment]
I mean we can just set scaler=mame3x for the time being, and implement shaders only later on.

Cause doing the first takes zero time compared with the second.

**Comment by kcgen** [comment]
No matter what, we have to set the drawing surface to a size (any size), before we can do anything with it (such as apply OpenGL shaders).

Pixel-perfect is just one of many initial sizes we can choose.  Once we choose a size, SDL2 gives us hardware-acceleration for free.  So the amount of work to implement Pixel Perfect is simply an initial calculation, and that's it - we set the size, and it's a done deal.  No GL-shaders needed.

Having SDL2 simply stretch the surface to a Pixel-Perfect resolution is as elegant as it gets, versus a shader, which is has your GPU grinding away on every pixel "quad'ing them up before handing them over to SDL2 for rendering.

(That's a separate point from chained shaders - I like you're suggestion @i30817 ! )

**Comment by dreamer** [comment]
> why would you want to have pixel perfect as a software scaler when it has a glshader implementation nowadays?

Pixel-perfect is neither a scaler nor a shader - it's an algorithm for calculating draw area size. Scaling itself is accelerated via OpenGL or any available SDL2 Texture backend.

There is an implementation of Pixel-perfect scaling using a GLSL shader, which we are not going to use, as it will duplicate the functionality (and we don't want 2 different algorithms for 1 functionality in code).

> If you're thinking of combinations, isn't it better to make dosbox support multiple shader passes and implement glshaders for what's still in 'software' for hardware+hardware than only have the possibility of combining software+hardware?

Yes, multiple shader passes would be better, but code, as inherited from SVN, is not capable of it, and we need pretty hefty refactorization to make it work. *And I would prefer to make this refactorization while working on Vulkan backend.*

> btw, my ubuntu ppa build supports the tyrells shaders (including pixel perfect) without the user having to install them now by installing them on a system readonly dir and modifying the shader search path to include that dir.

We are interested in an improvements to glshader path, that follows XDG spec :) if that's how your change works, then I will be pretty stoked about PR (insert my usual spiel about about WIP contributing guide, yada-yada-yada). Also, this is a little bit relevant here: #318 

--
There's a lot of off-topic discussion in here. I want to remind my dear interlocutors, that topic at hand is:

User opinions about changing the default **scaler** from `none` to (something specific). So far OP expressed an opinion and I am withholding describing my opinion and waiting to hear from more users.

**Comment by i30817** [comment]
it has little to do with the XDG spec - the 'little' is because i'm not certain if ~/.local override will work for it, probably not - it was needed because a package can't install or depend on files that are installed in a user dir. 

All files installed in a package need to go to root owned directories, otherwise it's really easy for the user to delete functional parts of a program, or the uninstall becoming broken because files are missing/renamed/added.

**Comment by dreamer** [comment]
@i30817 Quote from [XDG Base Directory Specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html)
>  $XDG_DATA_DIRS defines the preference-ordered set of base directories to search for data files in addition to the $XDG_DATA_HOME base directory. The directories in $XDG_DATA_DIRS should be seperated with a colon ':'.
>
> If $XDG_DATA_DIRS is either not set or empty, a value equal to /usr/local/share/:/usr/share/ should be used. 

The correct way of handling this is following XDG spec.

**Comment by i30817** [comment]
Mmm. Makes sense, i'll update the patch later to use it if it's available in the env vars.

**Comment by dreamer** [comment]
It doesn't need to be in env vars - that's what second sentence is about :)

**Comment by i30817** [comment]
You know what, i think no, it's not relevant here. Because the files *exist* in that dir and the debian packager doesn't use XDG so they won't be placed anywhere else.

**Comment by kcgen** [comment]
See the XBR shaders, which provide a equivalent to advinterp, however leveraging HW acceleration:
 -  https://github.com/tyrells/dosbox-svn-shaders/tree/master/xbr
