### ISSUE TITLE
City of the Lost Children (unable to open file)

### ISSUE THREAD

**Issue by orderorder** [dosbox-staging/dosbox-staging#3018]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### What Operating System are you using?

Linux x86_64

### Relevant hardware info

CPU: AMD Ryzen 7 - Nvidia 3070m

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

When I try to install the game I get the following error "unable to open file". The game installs correctly on the stable version of dosbox-staging. I have seen that the game does not allow the "full installation" because it does not detect space on the hard drive. Is there any trick to avoid this behavior?
![Captura desde 2023-10-17 00-14-48](https://github.com/dosbox-staging/dosbox-staging/assets/7293829/e6120ca0-23a8-4d7a-95d5-d15c2e1cff50)

### Steps to reproduce the behaviour.

Select "Minimum installation"

### Your configuration

```ini
core      = auto
cputype   = pentium_slow
cycles    = max

memsize   = 32
```

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by MasterO2** [comment]
Have you tried something like this?

https://github.com/dosbox-staging/dosbox-staging/wiki/Game-issues#setup-reports-not-enough-space

**Comment by johnnovak** [comment]
> Have you tried something like this?
> 
> https://github.com/dosbox-staging/dosbox-staging/wiki/Game-issues#setup-reports-not-enough-space
> 
> Mounting your C drive with the `-freesize 1024` switch?

☝🏻 that's the only workaround for problematic software, AFAIK.

**Comment by orderorder** [comment]
Yes, thanks, it works but the initial "unable to open file" problem still persists

**Comment by johnnovak** [comment]
Maybe related to this:
https://github.com/dosbox-staging/dosbox-staging/issues/3019#issuecomment-1765443600

Could be related to @FeralChild64 's attribute related refactors.

**Comment by MasterO2** [comment]
On an unrelated note, in Staging 0.80.1, `-freesize 1024` does **not** show up in the Dosbox Status Window. Is that supposed to be normal?
