### ISSUE TITLE
Failing to access files from mounted cdrom image

### ISSUE THREAD

**Issue by 0mnicydle** [dosbox-staging/dosbox-staging#3019]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### What Operating System are you using?

Windows 11

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

I noticed while testing the most recent build that I could no longer start Dark Forces; I get an error about not being able to find the "helnum.fnt" file.

My existing install of this game was done with the standard install which copies the minimum number of files to the hard drive and relies on the cdrom to load the rest at launch. I tried to run the custom install with all the optional components selected, but received an error in the setup program about not being able to find the "jedi.cfg" file.

Next I ran the full install in DOSBox SVN and tried running the game again in staging and this time it worked with all needed files already present on the hard drive, so it became pretty clear to me there is an issue with reading mounted cdrom images.

Interestingly I could complete the minimal install in staging, so whatever the issue is it only affects some files and not others.

Using the CI builds I narrowed it down to somewhere between 254dbe2b9a2bb4d5029288b7c057a29598aff053 and 65b29a6c0da8071c1a3a121d6573f9fe51ee4418

I tried both with the iso of my own personal cdrom I've been using for ages, and from a fresh cue/bin from exodos.

### Steps to reproduce the behaviour.

Explain how to reproduce
1. mount Dark Forces iso or cue/bin
2. run standard install
3. try to launch game

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by johnnovak** [comment]
Are you mounting via DOSBox or via some external tools, like DaemonTools or some OS provided mounting functionality?

The TL;DR is that always mount using DOSBox because other methods are not 100% compatible with MSCDEX.

**Comment by 0mnicydle** [comment]
Within DOSBox using imgmount, always.

**Comment by johnnovak** [comment]
You've described the issue in a rather roundabout way 😄 , so you're saying the installation works in SVN, but not in Staging, correct? Could you regression test the installation with the latest stable version 0.80.1? That would help.

**Comment by 0mnicydle** [comment]
Works in v0.80.1 and as recently as 254dbe2b9a2bb4d5029288b7c057a29598aff053 in CI builds. The very next CI build that was available to me fails (65b29a6c0da8071c1a3a121d6573f9fe51ee4418), but there were several commits between them.

> What I'm confused about is you're conflating several issues here, apparently. Some files cannot be copied by the installer (in Staging only?) but otherwise the game runs in Staging if installed in other forks?

The game runs in recent staging if all files have been installed to the HDD already (in an earler build, or SVN etc.), but if it has to read the cdrom to run, or if you try to do the FULL install (minimal completes) in recent staging, it will fail to find all the files it needs to.
