### ISSUE TITLE
Fullscreen not working if Run with older config type

### ISSUE THREAD

**Issue by OpenRift412** [dosbox-staging/dosbox-staging#3036]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Different version than latest?

v0.81.0-alpha-1804

### What Operating System are you using?

None

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

When Staging is run from an older configuration file, the window will flicker on startup and then will refuse to go into full screen mode. I know running with older configuration files isn't ideal, but there should be a more elegant way to make it compatible.

My suggestion would be for Staging to be do an automatic `config -wc` on startup to keep the config up to date.

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Run Staging with a config from the last release version
2. See if it goes into fullscreen or not (automatically or manually)

### Your configuration

```ini
https://gist.github.com/OpenRift412/abdb4143f12e6e0220d109c703726cfc
```

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by kcgen** [comment]
One of the very things mentioned in all our release notes has been to write a fresh config (if you look back at previous releases).

This is unlikely to change because the effort to map all prior release confs (keys and values) to present keys and values is a stack of busy work.

So it's best just to start with a valid and default config.

**Comment by Grounded0** [comment]
Can you remove [text] from the title. Makes it difficult to read and does not form in our ticket style. Thanks.

**Comment by johnnovak** [comment]
Vague issue description and I've never encountered this myself. Also, we will never auto update any configs, too invasive and error-prone.
