### ISSUE TITLE
Unexpected vertical moire in 1440p `crt-auto` on a 4k macOS w/ 25% scaling

### ISSUE THREAD

**Issue by kcgen** [dosbox-staging/dosbox-staging#3039]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Different version than latest?

latest `main`

### What Operating System are you using?

macOS (Apple Silicon)

### Relevant hardware info

3840x2160 4k screen

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

On macOS running a 4k screen with _OS_ -> _Settings_ -> _Display_ -> _Scaling_ -> +25% display scaling step:

<img width="712" alt="Screen Shot 2023-10-22 at 8 54 32 AM" src="https://github.com/dosbox-staging/dosbox-staging/assets/1557255/0a84b05c-2f54-42b9-8a85-3fce40eb38fe">

The default (`--noprimaryconf --nolocalconf`) CRT 1440p shader shows a moire interference pattern (taken at an angle to avoid further moire patterns):

![2023-10-22_09-10](https://github.com/dosbox-staging/dosbox-staging/assets/1557255/dff9c3a4-8425-498a-9c75-0970e2fee175)

Fullscreen 3840x2160 PNG (suggest viewing at 1:1 fullscreen on 4k):

<img width="2560" alt="Screen Shot 2023-10-22 at 8 36 42 AM" src="https://github.com/dosbox-staging/dosbox-staging/assets/1557255/009c0715-b399-48e9-ba33-d1880cd46131">

### Steps to reproduce the behaviour.

Confirm you have prerequisites: macOS system with full 4k (3840x2160) screen

1. Set +25% display scaling in:  _OS_ -> _Settings_ -> _Display_ -> _Scaling_ -> +25% display scaling step:

<img width="712" alt="Screen Shot 2023-10-22 at 8 54 32 AM" src="https://github.com/dosbox-staging/dosbox-staging/assets/1557255/0a84b05c-2f54-42b9-8a85-3fce40eb38fe">

2. Launch the latest build with `--noprimaryconf --nolocalconf`.

3. Click and drag the DOSBox Staging window size until the console log reports:

    `RENDER: Auto-switched to shader 'crt/vga-1440p'`

4. Inspect the DOSBox Staging CLI window for signs of a moire pattern, as in the above screenshot.

### Your configuration

```ini
Default configuration (`--noprimaryconf --nolocalconf`)
```

### Provide a Log

```text
(to-be-pasted)
```

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by kcgen** [comment]
When scaling is set back to default (or none), the moire in the 1440p scaler disappears:

![Screen Shot 2023-10-22 at 8 53 08 AM](https://github.com/dosbox-staging/dosbox-staging/assets/1557255/062e1731-90ef-4888-a85e-b5c85f48220d)

**Comment by kcgen** [comment]
Using the same display on X11 Linux with similar +25% (or 125%) scaling:

![2023-10-22_09-37](https://github.com/dosbox-staging/dosbox-staging/assets/1557255/71aef8a4-144e-4eaa-bb74-0883c4202ad3)

... there is no moire pattern in the CRT 1440p shader (3840x2160 PNG, suggest viewing at 1:1 fullscreen on 4k):

![Screenshot_20231022_084635](https://github.com/dosbox-staging/dosbox-staging/assets/1557255/5f534083-9bb8-4f1e-9dd4-4ae49ca081d5)

**Comment by kcgen** [comment]
Will upgrade the system to BigSur 11.7.10 and perform a full update of homebrew (both x86 and arm64 sides)

**Comment by GranMinigun** [comment]
Welcome to Apple's gardens. That's how they do DPI scaling, by rendering a higher-resolution frame then downscaling to native monitor's resolution.

**Comment by johnnovak** [comment]
> Welcome to Apple's gardens. That's how they do DPI scaling, by rendering a higher-resolution frame then downscaling to native monitor's resolution.

In that case, there's not much we can do about this... 😩 I will test too at some point, but if things are rendered at higher resolutions by a scale factor of X of the native res where X is a non-integer factor (1.25x in your example), then downsampled to the native res, that's bad, and moire can happen. Windows and Linux are fine because they don't do this downscaling thing; we always render simply at the DPI scaling adjusted final res. Not sure if you can force such thing on macOS, but that's the only robust solution.

**Comment by kcgen** [comment]
Indeed; I knew @GranMinigun's DPI handling and integer scaling, and the npot pragmas in your tweaked CRT shaders were all solid because there are no platform-specific code paths; but I didn't know if something was off in SDL, or if macOS itself was the culprit.

Glad you knew what was going on, @GranMinigun !

I'll go back down to no scaling, and find another way to bump up the desktop fonts.

**Comment by kcgen** [comment]
Switched the macOS desktop to 2x / 200% scaling, and as expected the moire pattern is gone in all shaders. So that's always an option for users:

<img width="1920" alt="Screen Shot 2023-10-22 at 7 41 29 PM" src="https://github.com/dosbox-staging/dosbox-staging/assets/1557255/e7705e24-1eed-4d41-a374-87c66958c8c2">
