### ISSUE TITLE
Anti-virus false positive for x86 dev build

### ISSUE THREAD

**Issue by almeath** [dosbox-staging/dosbox-staging#3043]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### What Operating System are you using?

Windows 11

### Whats your question and how can we help?

I tried downloading the latest Windows x86 development build and my anti-virus (Bitdefender) blocked it as:

"...tried to load a malicious resource detected as Gen:Variant.Lazy.412383.."

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by johnnovak** [comment]
99.99% false positive.

**Comment by Burrito78** [comment]
Just scanned the current build on VirusTotal and false positive is already gone.

**Comment by kcgen** [comment]
@almeath , the Windows CI builds (which include the dev builds) need to pass Microsoft's own BitDefender scanner first as a CI per-requisit.

And yeah, looks like yesterday's build passed:

![2023-10-23_18-28](https://github.com/dosbox-staging/dosbox-staging/assets/1557255/38fd497a-69a1-4b6b-9889-b7885fca02b7)

**Comment by almeath** [comment]
Thanks for the feedback. Good to know it passes via the other scans. I am new to Windows, so just being extra cautious.
