### ISSUE TITLE
DualSense (PS5) and DualShock 4 controllers not working on macOS

### ISSUE THREAD

**Issue by Dnilo** [dosbox-staging/dosbox-staging#3047]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### What Operating System are you using?

macOS (Apple Silicon)

### If Other OS, please describe

Mac OS Sonoma 14.0

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Joysticks are not being detected in 0.80.1. 

I tried updating the config file, then deleting it but the results are the same.

The latest version I use is 0.80.0-alpha-34-g92be702d4 which does detect joysticks perfectly.

I also tried v0.81.0-alpha-1811-g6e534 but is not working either.

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Run dosbox-staging and try to calibrate/use gamepad/joystick in any game.

### Your configuration

```ini
https://gist.github.com/Dnilo/5136a323be32e3f5540d1ab3e13a6d15
```

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by Grounded0** [comment]
What model of joystick you're trying to get working?

**Comment by Dnilo** [comment]
> What model of game controller you're trying to get working with 0.80.1?

A dualshock 4

**Comment by johnnovak** [comment]
@Dnilo Are you having the same problem with 0.81.0?

**Comment by Dnilo** [comment]
> @Dnilo Are you having the same problem with 0.81.0?

Yes, I'm not able to use dualsense(ps5) or dualshock 4 controllers with version 0.81.0, only with Version 0.79.0 (v0.80.0-alpha-34-g92be7).

However, I connected my 8bitdo SN30 in Xinput mode and it does work with 0.81.0, but not in "mac mode" in which the OS detects it as a Dualshock 4.

I also tested the 8bitdo USB Adapter 2, with a Dualsense. This adapter allows to set the same configurations, these being Xinput, Dinput, Mac mode and others. When choosing "Mac mode" it's the same result as using it on the SN30 controller, no matter the bluetooth controller connected to the USB Adapter 2, the OS detects it as a Dualshock 4. BUT changing to Xinput or Dinput works with DOSBox Staging. Dinput being the best option for DOSBox since Xinput has some issues with MacOS and this USB adapter at the time of writing this post.

I want to point out that while the 8bitdo USB Adapter 2 is worth every cent ($20usd or less) and allows me to play DOSBox, this doesn't solve the issue introduced after Version 0.79.0 which now prevents owners of playstation controllers to play and have to resort to earlier versions.

**Comment by johnnovak** [comment]
@Dnilo Well, I don't have any Playstation controllers, so can't help you there. Maybe someone who has one and uses it on macOS can chime in. But I can assure you people use Staging with all sorts of controllers and we're not swamped with controller related issue tickets. Maybe the PS controllers on macOS are kinda special.

**Comment by Dnilo** [comment]
@johnnovak Yeah, in the meantime I can use the setting alternative fine. My question would be what changed in 0.80.0 that made the playstation pads stop working?

**Comment by johnnovak** [comment]
> @johnnovak Yeah, in the meantime I can use the setting alternative fine. My question would be what changed in 0.80.0 that made the playstation pads stop working?

No idea, man. I'm not a big controller guy myself, I mostly play with keyboard + mouse. But AFAIK we haven't made significant changes to the joystick handling. Maybe some SDL changes.

**Comment by johnnovak** [comment]
For the record, SDL started adding DualSense support in 2.0.14:
https://www.gamingonlinux.com/2020/12/sdl-2014-is-out-with-support-for-ps5-dualsense-and-xbox-series-x-controllers/

Searching for "DualSense" in their issue tracker shows they have bern working on lots of DualSense related issues and regression. Probably these are connected to the Playstation controller regressions on macOS.

Let's not forget that although SDL is cross platform, most people game on Windows, so Windows related issues must get a lot more attention.

Ultimately, we'd need someone on macOS who owns these controllers to get to the bottom of this issue, so help is needed. But probably this can be only fixed in SDL anyway.

Chsnging the ticket description to reflect this specific niche use case.

**Comment by Dnilo** [comment]
@johnnovak How can I help?

**Comment by johnnovak** [comment]
> @johnnovak How can I help?

By help, I meant help from someone who's technical and gets to the bottom of it by debugging what SDL (or DOSBox) does wrong with the PlayStation controllers connected. I think we need a coder to get their hands dirty at this point.

**Comment by Dnilo** [comment]
@johnnovak Got it.

**Comment by Grounded0** [comment]
@johnnovak 

Project funds could be used for you to buy one or both of these Sony game controllers. @kcgen also had at least one of these Sony controllers just for testing purposes. Xbox and PS controllers are the most popular on the market so it would make sense to have both for testing these out.

**Comment by Grounded0** [comment]
Anyone wishing to help us out should test their PS4 or PS5 controller with macOS does it work or not. We're more confident to continue to work on this once we get a second confirmation.

**Comment by johnnovak** [comment]
> @johnnovak
> 
> Project funds could be used for you to buy one of these PlayStation controllers. @kcgen also had at least one of these PlayStation controllers just for testing purposes. Xbox and PlayStation controllers are the most popular on the market so it would make sense to have both for testing these out and to make sure we or the SDL Project didn't break anything.

That's not a bad idea. I've just checked, you can get one for around 100 AUD, so not a big deal.

Ideally, we'd buy one for a core team member who can test on macOS, Windows, and Linux. It seems macOS introduces its own set problems, so access to macOS is a must. That leaves @kklobe and myself, pretty much.

I'm fine taking this on as the mapper rework has significant overlap with the OSD, and at least half of the work is coming up with a better user interface. But the mapper work won't start this year, and I won't jump on the PlayStation controller issues right away anyway, so don't wanna take the chance away from someone else who really wants to work on this (and earlier than I would).

@kklobe are you intersted in this? Or someone else who is able to test on all three OSes regularly? I'm happy paying for the controller from the project funds, with the expectation that person will then own the PS controller issues & testing at least for a good while.

**Comment by kklobe** [comment]
> @kklobe are you intersted in this? Or someone else who is able to test on all three OSes regularly? I'm happy paying for the controller from the project funds, with the expectation that person will then own the PS controller issues & testing at least for a good while (minimum two major releases).

Interested in a "I guess if no one else wants it, I will take it" sort of way. I'm happy to do some basic release testing (given some help on what titles to test; I have never played a game with a controller on a PC), but don't have enough enthusiasm to e.g. submit upstream fixes to SDL.

**Comment by johnnovak** [comment]
> > @kklobe are you intersted in this? Or someone else who is able to test on all three OSes regularly? I'm happy paying for the controller from the project funds, with the expectation that person will then own the PS controller issues & testing at least for a good while (minimum two major releases).
> 
> Interested in a "I guess if no one else wants it, I will take it" sort of way. I'm happy to do some basic release testing (given some help on what titles to test; I have never played a game with a controller on a PC), but don't have enough enthusiasm to e.g. submit upstream fixes to SDL.

That's fine, I guess I'll just buy a PS5 controller at some stage when it's time for the mapper rework. I'm not super enthusiastic about controller support either as I almost never use mine, plus most DOS games require keyboard + mouse anyway...

Also, I'd expect this to be a solved issue by the SDL team, but I guess not too many people game on Macs.

**Comment by Grounded0** [comment]
This should be checked with the latest release of SDL 2.30.6 bundled with DOSBox Staging 0.82.0 RC1 or newer. Could be a regression in this particular SDL release that has been now fixed.

**Comment by johnnovak** [comment]
@Dnilo Version 0.82.0-RC1 (release candidate) is going to be released tomorrow. Would you be able to re-check this with the RC then?

**Comment by Dnilo** [comment]
@johnnovak Yes, I can test with DS4, DS5, and 8-bitdo usb adapter 2 (which I use now for all my games) if that helps you guys.

**Comment by johnnovak** [comment]
> @johnnovak Yes, I can test with DS4, DS5, and 8-bitdo usb adapter 2 (which I use now for all my games) if that helps you guys.

Thank you @Dnilo, tomorrow is the day then when the RC is out 🚀

**Comment by Grounded0** [comment]
https://www.dosbox-staging.org/releases/release-notes/0.82.0-rc/

**Comment by Dnilo** [comment]
I'm happy to report that my gamepads work!

DualShock 4, Dualsense, and the 8bitdo USB adapter 2. I have other gamepads but I think if these work all other gamepads compatible with the system will, but I can test if required.

**Comment by johnnovak** [comment]
> I'm happy to report that my gamepads work!
> 
> DualShock 4, Dualsense, and the 8bitdo USB adapter 2. I have other gamepads but I think if these work all other gamepads compatible with the system will, but I can test if required.

Excellent news! 🥳 Thank you very much for confirming! Enjoy Staging 😎

**Comment by Grounded0** [comment]
Got my blame SDL hunch right. 😁

**Comment by Dnilo** [comment]
Thank you so much guys.
