### ISSUE TITLE
Trouble mounting a large HDD image

### ISSUE THREAD

**Issue by almeath** [dosbox-staging/dosbox-staging#3053]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### What Operating System are you using?

Windows 11

### Whats your question and how can we help?

Last year I asked about mounting large hard drive images in DOSBox Staging. Some changes were made in a test branch that allowed me to boot a 3.5GB Windows 98 img in DOSBox Staging. The thread was subsequently closed in February, stating that support had been rolled into the main source, but using "a slightly different approach". Refer to the original thread:

https://github.com/dosbox-staging/dosbox-staging/issues/1964

On that note, I am unable to get the same Windows 98 3.5GB image to boot up in the latest DOSBox Staging alpha build.

For clarity, the following commands work perfectly in (patched) DOSBox SVN:

```
[autoexec]
# Lines in this section will be run at startup.
@echo off
imgmount 2 harddisk\hdd.img -size 512,63,128,888 -t hdd -fs none
boot -l c
```

In DOSBox Staging, this will not work. 

I see a message in the DOS prompt that 'The image must be on lost or local drive'.

In the console, I see this:

2023-10-25 13:48:58.660 | IMGMOUNT: Path 'harddisk\hdd2.img' found

Not too sure what I am doing wrong here, as I understood that drive geometry settings are still required? I have other (smaller) disk images booting successfully in both Windows 95 and 98 using the standard auto exec approach from my SVN build. It works under both 0.80.1 and also 0.81.0 alpha. It is just the larger (I presume 2GB+) size of img files that are failing to boot.

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by johnnovak** [comment]
@shermp wasn't it you who added some support for large drives? I never quite understood from your description what that exactly meant, though 😄 Any insights on this issue?

**Comment by shermp** [comment]
I'll see if I can reproduce it.

**Comment by shermp** [comment]
I cannot reproduce this. Using the latest `main`, I have installed Windows 98 to a image file with the exact same geometry as @almeath 

![image](https://github.com/dosbox-staging/dosbox-staging/assets/14854761/7845bb9c-4333-4b66-8bd5-b8a981a2b5fd)

The only thing I can think of is the name of the file is incorrect, or quotes are required around the filename. Or the image is read only, or mounted in another program.

**Comment by almeath** [comment]
Thanks for looking into this. I just tried again with a fresh install of the latest development build, and it is working now. I am not sure what I was doing wrong the first time, but I can confirm that I can now boot a Windows 98 image of 3.5GB in size, and it does not matter whether I use quotes around the filename - both work.

**Comment by almeath** [comment]
I'll close this as my question has been answered.

**Comment by johnnovak** [comment]
Thanks @almeath and @shermp , great outcome 🚀
