### ISSUE TITLE
Bo Jackson Baseball (1991)

### ISSUE THREAD

**Issue by Python-Exoproject** [dosbox-staging/dosbox-staging#3056]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### What Operating System are you using?

Windows 11

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

In exodos we currently use ECE r4230. Using the Tandy choice (option 1) given to the user in exodos during start ECE works fine. If switched to Staging the sound of the baseball being hit in the intro is missing.

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Start game and choose Tandy sound option
2.
3.

### Download URL of affected game or software

exodos

### Your configuration

```ini
Default Staging config with tandy=on
```

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by kcgen** [comment]
The sfx are played through the PC speaker; `pcspeaker = impulse` does the job here too.

**Comment by Burrito78** [comment]
@Python-Exoproject Is this a working solution for you?

**Comment by Python-Exoproject** [comment]
Yes, confirmed
