### ISSUE TITLE
Messed up colors in Lemmings

### ISSUE THREAD

**Issue by Ekamekia** [dosbox-staging/dosbox-staging#3057]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Different version than latest?

0.80.1

### What Operating System are you using?

macOS (Apple Silicon)

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

The color pallet of the level description screen in the games Lemmings and Oh No! More Lemmings is messed up. The entire rest of the game seems fine.

Screenshot: https://imgur.com/a/4PKr344

Dosbox-X for comparison
https://imgur.com/a/uPlpAhI

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Run Lemmings
2. F1 to start new game
3.

### Download URL of affected game or software

https://www.myabandonware.com/game/lemmings-16x

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by johnnovak** [comment]
@Ekamekia With 0.80.1 you need `machine  = vgaonly` and the colours will be fine.

With the latest dev build the colours are fine out of the box with any VGA machine type.

**Comment by MasterO2** [comment]
@Ekamekia https://github.com/dosbox-staging/dosbox-staging/wiki/Game-issues#lemmings-1991 and scroll down to **Fixing Level Introduction Screen's Incorrect Colors**.  Follow those instructions.
