### ISSUE TITLE
Unable to switch between multiple mounted images

### ISSUE THREAD

**Issue by orderorder** [dosbox-staging/dosbox-staging#3060]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Different version than latest?

0.80.1 stable

### What Operating System are you using?

Linux x86_64

### If Other OS, please describe

Endeavour OS

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

I've used the multi-image setting along with the Ctrl + F4 combination, but it doesn't change the cue+img image. I've tried several versions of dosbox-staging but I'm only successful on the stable version 0.77.1

I use a line like this in my .conf file:

     imgmount d -t iso /path/cd.cue  /path/cd2.cue /path/cd3.cue

The dosbox terminal says at the begining:

     unit already mounted on that letter (once for each cue+img image)

When I press CTRL+ F4 the linux terminal says:

     Diskcaching reset for normal mounted drives.

It's as if Dosbox misinterprets the command and mounts the units one by one without taking into account the multiple configuration.

I've read the manuals, but I think I'm doing well. Has this type of setting changed since 0.77.1 version?

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by kcgen** [comment]
I have the following directory:

```
dosbox.conf
cd/
├── cd1.bin
├── cd1.cue
├── cd2.bin
├── cd2.cue
├── cd3.bin
├── cd3.cue
├── cd4.bin
└── cd4.cue
```

The `cue` files contain:

```cue
FILE "cd1.bin" BINARY
   TRACK 01 MODE1/2352
      INDEX 01 00:00:00
```

```cue
FILE "cd2.bin" BINARY
   TRACK 01 MODE1/2352
      INDEX 01 00:00:00
```

```cue
FILE "cd3.bin" BINARY
   TRACK 01 MODE1/2352
      INDEX 01 00:00:00
```

```cue
FILE "cd4.bin" BINARY
   TRACK 01 MODE1/2352
      INDEX 01 00:00:00
```

If I launch DOSBox Staging in this top level directory, I can mount them all with: `imgmount d cd/*.cue -t cdrom`:

![2023-10-26_18-50](https://github.com/dosbox-staging/dosbox-staging/assets/1557255/99083e38-118d-4a32-a8bf-16452787c89a)

I can switch to `D:`, run `ls` and then `mount` to see disc 1's content and LABEL:

![2023-10-26_18-51](https://github.com/dosbox-staging/dosbox-staging/assets/1557255/25f8032d-4f6d-46ac-bb23-c14f4227cab5)

Pressing `Ctrl + F4` switches to the next disk. `ls` and `mount` show disc 2's content and LABEL:

![2023-10-26_18-51-2](https://github.com/dosbox-staging/dosbox-staging/assets/1557255/930c646f-8ed2-4a91-a1e4-54119c86aa0e)

Pressing `Ctrl + F4` against switches to the next disk. `ls` and `mount` show disc 3's content and LABEL:

![2023-10-26_18-51-3](https://github.com/dosbox-staging/dosbox-staging/assets/1557255/d6539dc8-4800-4d73-b6f7-df1f9aaedbf4)

Pressing `Ctrl + F4` against switches to the next disk. `ls` and `mount` show disc 4's content and LABEL:

![2023-10-26_18-52](https://github.com/dosbox-staging/dosbox-staging/assets/1557255/a3c9bbbf-160b-4896-ac54-169714df8a46)


Pressing `Ctrl + F4` against goes back to disk 1.

**Comment by orderorder** [comment]
Ok, thank you

**Comment by kcgen** [comment]
> Ok, thank you

Hopefully there's enough here to help you debug what's going on in your scenario. 

The output from the `imgmount` command will list all the image (iso/cue) filenames explicitly, so there's no guessing what it has.

Use the `mount` command to list the labels and see what disk you're on. 

(closing for now: if you have a reproduceable set of files that causes problems, please host/share them and re-open this).
