### ISSUE TITLE
Errors/typing mistakes with dosbox --help and dosbox -v commands

### ISSUE THREAD

**Issue by Kappa971** [dosbox-staging/dosbox-staging#3061]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### What Operating System are you using?

Windows 11

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

I noticed some errors/typing errors:
`  --noprimaryconf          Don't load or create the the primary configuration file.`
Double **the**

`  -c <command>             Run the specified DOS command before running FILE.`
Shouldn't it be **PATH**?

-----
```
:PROGRAM_CONFIG_SET_SYNTAX
Usage: [color=light-green]config [/reset]-set [color=light-cyan][SECTION][/reset] [color=white]PROPERTY[/reset][=][color=white]VALUE[/reset]

.
```
Why `[/reset]` and not `[reset]`?

-----

`dosbox --version` works but `dosbox -v` doesn't:
```
dosbox --version
dosbox-staging, version 0.81.0-alpha-1864-g2d0fcb92c

Copyright (C) 2020-2023  The DOSBox Staging Team
License: GNU GPL-2.0-or-later <https://www.gnu.org/licenses/gpl-2.0.html>

This is free software, and you are welcome to change and redistribute it under
certain conditions; please read the COPYING file thoroughly before doing so.
There is NO WARRANTY, to the extent permitted by law.
```

```
dosbox -v
CHECK FAILED:  arg_it < argc  (2 < 2)  Missing verbosity level after -v
```

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Run on Windows Powershell or CMD `dosbox --help` and `dosbox -v`

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by kcgen** [comment]
Thanks @Kappa971, will get these fixed.

**Comment by Grounded0** [comment]
Updated man page:

https://anttipeltola.eu/docs/dosbox.1
