### ISSUE TITLE
Modem/Nullmodem issues

### ISSUE THREAD

**Issue by Ekamekia** [dosbox-staging/dosbox-staging#3101]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Different version than latest?

0.80.1

### What Operating System are you using?

macOS (Apple Silicon)

### Whats your question and how can we help?

Not 100% sure if this is a bug or if I'm just ignorant. I was attempting to set up a game, Wacky Wheels for 2 player action. There are options for a Serial cable or modem play.

I could not get serial link to work at all.

I put serial1= nullmodem in the config of the server
and serial1 = nullmodem 192.168.1.17 on the client

Couldn't get it to connect, I tried Doom as well and nothing.

I switch to trying to get a modem game to connect, changing the config lines to:
serial1= modem in the config of the server
serial1 = modem 192.168.1.17 on the client

It worked...Kind of. It connects successfully, but then the game, still on the connection menu drops to seconds per frame, after a minute or so it disconnects and a connection summary appears saying:

Bad CRC: 40
Timeouts: 59
Noise: 210

Another issue I noticed is that you have to "dial" the IP address to get it to connect
ATDT192.168.1.17 Which works fine in Wacky Wheels, but Doom doesn't let you put in periods.

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by MasterO2** [comment]
Regarding Wacky Wheels, have you also tried using https://dosbox-staging.github.io/downloads/release-notes/0.75.0/#modem-phonebook?

**Comment by Ekamekia** [comment]
That worked for Doom and Doom runs fine! Wacky Wheels is just messed up I guess.

**Comment by Ekamekia** [comment]
Wacky Wheels needs the Interbyte delay set to 1 in the Setup.

**Comment by MasterO2** [comment]
> Wacky Wheels needs the Interbyte delay set to 1 in the Setup.

If you're willing to do so, you could write a guide about setting up multiplayer for Wacky Wheels and put it on the wiki.

**Comment by Grounded0** [comment]
I wrote this to help people along to set this up:

https://github.com/dosbox-staging/dosbox-staging/wiki/multiplayer-&-serial-ports

**Comment by Grounded0** [comment]
@MasterO2 

We could definitely expand [Multiplayer & serial ports](https://github.com/dosbox-staging/dosbox-staging/wiki/multiplayer-&-serial-ports) with game specific settings to make them work.

**Comment by Grounded0** [comment]
I'll expand it with game specific tweaks with Wacky Wheels tweak mentioned.
