### ISSUE TITLE
Ultima VIII – Pagan keyboard regression

### ISSUE THREAD

**Issue by johnnovak** [dosbox-staging/dosbox-staging#3104]
Paging @FeralChild64 😆

Commit e73aaa57436bf5ef4eeea16255c78bef8511787e ("Rework keyboard emulation") has introduced a keyboard input regression in **Ultima VIII – Pagan**. I used the eXoDOS v5 version for testing.

### Steps to reproduce

1. Start the game (I just used option 1 (SoundBlaster) with the eXoDOS launcher, but it doesn't matter).
2. Press Esc to skip the intro.
3. Try to type something in at the "Give thy name" prompt — you can't.

**Comment by FeralChild64** [comment]
The game issues command 0xAD to the Intel 8042 controller, which disables keyboard input. But I don't see the game doing anything which should re-enable it. It seems I missed something in the reworked emulation. Commenting out the 

```
is_disabled_kbd = true;
```

line in the `intel8042.cpp` "fixes" the problem, but it is definitely not a proper fix. Investigating...

**Comment by johnnovak** [comment]
Thank for the quick reply @FeralChild64.

> The game issues command 0xAD to the Intel 8042 controller, which disables keyboard input.

Channeling Toni Wilen (WinUAE maintainer): never code anything in emulators relying on specifications. Almost always there is a lot of undocumented behaviour 😏 Good luck, you'll probably need to test on hardware at some point and/or check out what other emulators do.

**Comment by johnnovak** [comment]
> [edit] Before my rework disabling the keyboard did not really do anything, that's why it was working. Strange.

This issue got me interested, I can test the game on real hardware and can run test programs if that helps @FeralChild64. Just send me some test binaries I can simply run.

**Comment by johnnovak** [comment]
You might be already aware of the information from this article, but here we go:
http://www.os2museum.com/wp/ibm-pcat-8042-keyboard-controller-commands/

Some interesting tidbits below, but make sure to read the whole thing (if you haven't already). The last one is the most interesting and maybe that's the answer to the mystery. Like I said, manufacturer's specs always lie 😎 Test programs or I don't believe it 😆 

> IBM documented a number of commands the host can send to the KBC. It should be understood that all those commands are a pure software construct, with nothing about the 8042 hardware dictating that the commands need to follow any specific format, function, or that they even need to be there at all. Therefore understanding the 8042 ROM code is the only way towards understanding exactly what the commands are and what they do, with the caveat that different controllers may and do have somewhat different code in their ROM.

> In late 2010, Attila Tarpai [disassembled](http://www.halicery.com/8042/8042_1503033.TXT), commented and [analyzed](http://www.halicery.com/8042/8042_INTERN.TXT) the ROM.

> The PC/AT Technical Reference lists most of the commands, and other literature such as The Undocumented PC lists almost all the rest. However, some aspects of the command operation are not fully documented anywhere.

> Additionally, *writing a byte to port 60h in order to send it to the keyboard (i.e. a KBC command is not expecting input) causes the keyboard interface to be enabled.* This allows the host to skip explicitly enabling the keyboard interface in some situations. *Neither of these details is documented by IBM.*

**Comment by FeralChild64** [comment]
> Additionally, writing a byte to port 60h in order to send it to the keyboard (i.e. a KBC command is not expecting input) causes the keyboard interface to be enabled

I have implemented this - see _intel8042.cpp_ file, `write_data_port` function contains a line:

```
is_disabled_kbd     = false; // port auto-enable
```

I'll probably have to observe what 86Box does, if I understand their code correctly there are more cases when the keyboard can be re-enabled. Making the implementation ignore the _keyboard disable_ bit is a possible stop-gap solution, too.

In this particular case observing the real hardware might not be that good idea. Probably every single chipset manufacturer used to tamper with the 8042 firmware, different machines might show slightly different behavior - even Microsoft did run into problems with Windows 3.11 when it's keyboard driver didn't work correctly on some PCs, see [WG0974 article](https://www.betaarchive.com/wiki/index.php/Microsoft_KB_Archive/109561). I would like the implementation to be as compatible with as much software as possible - not to emulate all the quirks of a selected chipset.

**Comment by johnnovak** [comment]
> In this particular case observing the real hardware might not be that good idea. Probably every single chipset manufacturer used to tamper with the 8042 firmware, different machines might show slightly different behavior - even Microsoft did run into problems with Windows 3.11 when it's keyboard driver didn't work correctly on some PCs, see [WG0974 article](https://www.betaarchive.com/wiki/index.php/Microsoft_KB_Archive/109561). I would like the implementation to be as compatible with as much software as possible - not to emulate all the quirks of a selected chipset.

Cool, I get that in a general sense, but I'm pretty sure the keyboard of Ultima VIII would work on 99% of real hardware out there. I guess we're saying the same thing slightly differently, but I'm pretty sure if we just 100% emulated _one_ specific ROM exactly, then 99.99% games would run correctly.

Anyway, I'll leave it to you, and your approach sounds fine too 😄 If you want me to run some DOS executable on real hardware, just let me know (not sure if you have a retro PC, can't remember 😄 ).

**Comment by FeralChild64** [comment]
After deeper investigation and observing game+DOS+BIOS behavior in 86Box - it's more BIOS problem than hardware emulation problem (which, by the way, is also not 100% correct). For 0.81.0 I only intend to provide a workaround, full fix would require another rework, possibly large and risky.

Too precise hardware emulation might be undesirable - in this case it would increase PS/2 mouse input latency by 2-3 ms and key press/release latency by about 1 ms (here some latency is already enforced, otherwise some software would break; notable example is Borland TurboVision library).
Maybe not much, but for game-oriented emulator this is definitely undesirable.

**Comment by Grounded0** [comment]
Closed by?

- #3109

**Comment by johnnovak** [comment]
> Closed by?
> 
>     * [Workaround for keyboard problem in Ultima VIII: Pagan #3109](https://github.com/dosbox-staging/dosbox-staging/pull/3109)

Yes, the fix works.
