### ISSUE TITLE
upper memory is lost after "mem /c /p" is executed.

### ISSUE THREAD

**Issue by kirbyzhou** [dosbox-staging/dosbox-staging#3112]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### What Operating System are you using?

macOS (Apple Silicon)

### Relevant hardware info

M1 Pro

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

upper memory is lost after "mem /c /p" is executed.

When mem is executed for the first time, it returns 64k upper memory.
Then it returns no upper memory.

### Steps to reproduce the behaviour.

![image](https://github.com/dosbox-staging/dosbox-staging/assets/3401630/2ff8a38d-64a6-42c2-aa8a-7c2bacc590fd)

### Your configuration

```ini
Just out of box.
```

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by johnnovak** [comment]
Already fixed in the dev build:
https://github.com/dosbox-staging/dosbox-staging/issues/2532
