### ISSUE TITLE
"%LOCALAPPDATA%\dosbox\dosbox-staging.conf" created and used even when the -conf parameter is being used

### ISSUE THREAD

**Issue by liPillON** [dosbox-staging/dosbox-staging#3116]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Different version than latest?

0.81.0-alpha-1925-g523bfc21a

### What Operating System are you using?

Windows 10

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Imagine a scenario where:
- "%LOCALAPPDATA%\dosbox\dosbox-staging.conf" does not exist (eg: a new OS installation)
- a primary cfg file is being used to customize common settings
- secondary config files are being used to provide each game its own autoexec commands

Recent 0.81 development builds generate "%LOCALAPPDATA%\dosbox\dosbox-staging.conf" even when the -conf command line parameter is being used (this was not the case with the 0.80.1 release).

The file is created by merging the primary and secondary cfg file specified by the user, thus storing the autoexec section from the secondary config specified the first time staging has been run.

During the subsequent run, this happens:
1. settings are loaded from "%LOCALAPPDATA%\dosbox\dosbox-staging.conf" (including the autoexec section previously merged)
2. settings are overwritten with the values coming from the primary configuration file
3. the autoexec section of the secondary configuration file is appended to the autoexec session from "%LOCALAPPDATA%\dosbox\dosbox-staging.conf"

### Steps to reproduce the behaviour.

Explain how to reproduce
1. download the [build I was testing](https://github.com/dosbox-staging/dosbox-staging/actions/runs/6844778233) and unzip it to a directory (eg: C:\MYDOSBOX)
2. download the [test case](https://github.com/dosbox-staging/dosbox-staging/files/13342938/dosbox-staging-autoexec-test.zip) and unzip it to the same directory
3. delete or rename the existing "%LOCALAPPDATA%\dosbox\dosbox-staging.conf" file
4. double click on GAME1.CMD, take notice of the result (eg: the autoexec from GAME1.CONF will print a message)
8. open "%LOCALAPPDATA%\dosbox\dosbox-staging.conf" and notice how the autoexec section has been populated with what's coming from GAME1.CONF
9. double click on GAME2.CMD, notice how two messages will now be displayed, coming from "%LOCALAPPDATA%\dosbox\dosbox-staging.conf" and from "GAME2.CONF" respectively
10. open "%LOCALAPPDATA%\dosbox\dosbox-staging.conf" to ensure it has the same content as before and no changes have been made to the autoexec section, which still contain the commands from GAME1.CONF
11. edit MAIN.CONF (eg: change fullscreen to true) to ensure if the file is being actually used by dosbox
12. double click on GAME2.CMD, notice how dosbox is running in fullscreen (this tells us MAIN.CONF is being used) and is showing two lines of text (one from %LOCALAPPDATA% and the other from GAME2.CONF)

### Your configuration

```ini
see the attached test case:
- MAIN.CONF is a configuration file generated from scratch, with the only setting changed being glshader
- GAME1.CONF provide autoexec commands for an hypothetical game
- GAME2.CONF provide autoexec commands for a second game
- GAME1.CMD launches dosbox, instructing it to use MAIN.CONF as primary and GAME1.CONF as secondary config. file
- GAME2.CMD launches dosbox, instructing it to use MAIN.CONF as primary and GAME2.CONF as secondary config. file
```

### Provide a Log

```text
not applicable
```

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by liPillON** [comment]
I suspect this has something to do with this recently merged PR
https://github.com/dosbox-staging/dosbox-staging/pull/2966

But I can't tell if what I'm facing is indeed a bug, or if what I'm trying to do is no longer supported given what has been discussed in that PR.

**Comment by MasterO2** [comment]
Want to take a look, @johnnovak?

**Comment by johnnovak** [comment]
@liPillON 

Yes, we always want to create the default config file if it's missing. That's our starting point for this discussion.

> The file is created by merging the primary and secondary cfg file specified by the user, thus storing the autoexec section from the secondary config specified the first time staging has been run.

Indeed, that's not ideal. To sum up your ticket succinctly, you've described the scenario where you use `-conf` to load some config but the primary config does not exist. Then effectively the default config merged with the config your provided with `-conf` gets saved.

We don't want this, of course — we always want to write the primary config when it's not present, regardless of any `-conf` parameters or any other config overrides.

I don't think this can be done in the 0.81.0 timeframe, though, as it would require extensive refactoring of the config handling mechanism. Happy to prove me wrong, though @kcgen and @weirddan455 , but I won't be doing this now.

The workaround in the interim is to start Staging with no extra parameters for the first time when you don't have the primary config written yet.

**Comment by johnnovak** [comment]
Actually, scrap that @liPillON @kcgen @weirddan455 ... briefly looked into it and it seems like an easy fix after all. Thanks for reporting this @liPillON , I'm working on a fix.

**Comment by liPillON** [comment]
I understand your point in having a reliable, identifiable, always-present primary config to fall back to when the user does not specify anything.
What I'm not that sure about is saving any autoexec commands in it, since that section is tipically used to perform different actions in different scenarios (such as different games being launched).

Saving other configuration sections is fine, since they can/would be overwritten by any user-specified configuration file; [autoexec] sections otoh do not replace each other, they are appended following the order set by the --conf command line parameters.

With how this currently works, the commands found in the first user-specified configuration file to ever be loaded will be forever stored in (and always executed from) in the application-generated primary configuration file.

**Comment by johnnovak** [comment]
Fixed @liPillON . Should be in the next dev build. Thanks again for your report.
