### ISSUE TITLE
Some Windows 3.1 games fail with `cputype=auto`

### ISSUE THREAD

**Issue by kcgen** [dosbox-staging/dosbox-staging#312]
Some Windows 3.1 game's use PE32-type executables, and these almost always require `cputype=pentium_slow`, otherwise they crash with errors like:

![Screenshot at 2020-04-23 16-37-35](https://user-images.githubusercontent.com/1557255/80161085-1e5fe600-8584-11ea-985f-fad7dae69a6d.png)

These games can be discovered in a directory tree of games using something like this:

```
exes=( */*/*.exe */*/*.EXE )
for e in "${exes[@]}"; do
    echo "$e" \
    | grep -qi '32\|inst\|autorun\|95\|windows\|sb16\|setup\|isdel\|demo\|tease' \
    || file "$e" | grep PE32 | sed 's^:.*^)^; s^/^ (^'
done
```

Some educational titles that need `cputype=pentium_slow`:

- Adventures of Valdo & Marie, The (1997) (valdo/valdo.exe)
- AweSome Animated Monster Maker (1997) (mmultra/mmover.exe)
- AweSome Animated Monster Maker (1997) (mmultra/mmultra.exe)
- Barbie Storymaker (1996) (cdrom/genesisb.exe)
- Chess Mates (1996) (cdrom/cmateuns.exe)
- Chess Mates (1996) (cdrom/dsndenum.exe)
- Crayola Magic Princess Paper Doll Maker (1999) (cdrom/launcher.exe)
- Fisher-Price Great Adventures - Pirate Ship (1997) (cdrom/fppirate.exe)
- Freddi Fish 2 - The Case of the Haunted School House (1996) (cdrom/autofred.exe)
- Freddi Fish 3 - The Case of the Stolen Conch Shell (1998) (cdrom/autofred.exe)
- Hoyle Battling Ships And War (1998) (cdrom/sigspat.exe)
- Jump Start 2nd Grade (1996) (cdrom/kahelp.exe)
- Jump Start 2nd Grade (1996) (cdrom/website.exe)
- Jump Start Baby (1999) (cdrom/unbball.exe)
- Jump Start Pre-K Year 2 - Trucks N Things (1999) (cdrom/kahelp.exe)
- Jump Start Pre-K Year 2 - Trucks N Things (1999) (cdrom/website.exe)
- Just Grandma and Me (1993) (cdrom/genesisb.exe)
- Madeline's Rainy Day Activities (1996) (cdrom/launcher.exe)
- Magic Fairy Tales - Barbie As Rapunzel (1997) (cdrom/launcher.exe)
- Marty And The Trouble With Cheese (1996) (cdrom/maxis.exe)
- Math Heads (1996) (cdrom/otto.exe)
- Oregon Trail II - 25th Anniversary Limited Edition (1996) (cdrom/mecctour.exe)
- Pajama Sam 2 - Thunder and Lightning aren't so Frightening (1998) (cdrom/autosam.exe)
- Pajama Sam - No Need to Hide When It's Dark Outside (1996) (cdrom/autosam.exe)
- Pink Panther, The - Hokus Pokus Pink (1998) (pokus/hpp.exe)
- Pink Panther, The - Passport to Peril (1997) (peril/pptp.exe)
- Putt-Putt Enters the Race (1998) (cdrom/autoputt.exe)
- Putt-Putt Enters the Race (1998) (hegames/autoputt.exe)
- Putt-Putt Goes to the Moon (1993) (cdrom/automoon.exe)
- Putt-Putt Joins the Parade (1992) (cdrom/autoputt.exe)
- Putt-Putt Travels Through Time (1997) (cdrom/autotime.exe)
- Sesame Street - Letters (1999) (cdrom/genesisb.exe)
- Sesame Street - Numbers (1999) (cdrom/genesisb.exe)
- SimAnt - The Electronic Ant Colony (1991) (cdrom/maxis.exe)
- SimAnt - The Electronic Ant Colony (1991) (cdrom/simant.exe)
- SimCity 2000 - CD Collection (1993) (cdrom/ip.exe)
- SimEarth - The Living Planet (1990) (cdrom/maxis.exe)
- SimLife (1992) (cdrom/maxis.exe)
- Skipper & Skeeto - Paradise Park (1996) (cdrom/launcher.exe)
- Smart Games Puzzle Challenge 3 (1998) (sgpc3/sgpc3.exe)
- Snoopy's Campfire Stories (1996) (cdrom/chkrun.exe)
- Sonic's Schoolhouse (1997) (sonic/sonic.exe)
- Spy Fox in Dry Cereal (1997) (cdrom/autospy.exe)
- Storybook Weaver Deluxe (1994) (cdrom/mecctour.exe)
- Strategy Heads (1997) (cdrom/otto.exe)
- Strategy Heads (1997) (sheads/strategy.exe)
- Super Solvers - Treasure Mountain! (1994) (cdrom/genesisb.exe)
- Time Warp of Dr. Brain, The (1996) (cdrom/dbverchk.exe)
- Time Warp of Dr. Brain, The (1996) (cdrom/drbrain4.exe)
- Word Heads (1997) (cdrom/otto.exe)
- Word Heads (1997) (wordhead/wheads.exe)

**Comment by Akuma-Git** [comment]
Maybe block execution has something to do with this, but I could be full of shit too ;)

**Comment by kcgen** [comment]
@Akuma-Git, if you've discovered a pattern or area of code that only these type of executables trigger, then perhaps the CPU type can be flipped to `pentium_slow` and keep things on the rails.  Like an "auto-cpu-mode" safety-net.

**Comment by Akuma-Git** [comment]
header @offset 80h 'PE'

**Comment by Burrito78** [comment]
@kcgen OK to close?

**Comment by kcgen** [comment]
Unfortunately swapping CPU types when a executable is loading currently isn't possible (and likely won't be).  I think @Akuma-Git's detection routine is perfect for users wanting to pre-check all their executables.

But even more robustly: win 3.1x users should just use `pentium_slow` for all systems. I'm not aware of a single case were this is detrimental.
