### ISSUE TITLE
Mouse lost after mouse_capture=nomouse

### ISSUE THREAD

**Issue by rderooy** [dosbox-staging/dosbox-staging#3127]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Different version than latest?

latest git

### What Operating System are you using?

Linux x86_64

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

When staging captured the mouse and typing:
```shell
config -set mouse_capture=nomouse
```
Does not return the mouse to the host OS, and the keyboard shortcut to release the mouse no longer works. You can recover from this by setting the value back to "onclick", after which you can use the keyboard shortcut to release the mouse.

What should happen, is that staging should release the mouse to the host OS when it had been captured.

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Start Staging
2. Capture mouse
3. `config -set mouse_capture=nomouse`
4. attempt to release the mouse

### Your configuration

```ini
default
```

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by FeralChild64** [comment]
Releasing by middle mouse button still works - that’s probably why I missed that during my testing.

**Comment by FeralChild64** [comment]
Fix is not in rewiew - @rderooy, many thanks for noticing this!

**Comment by johnnovak** [comment]
> rewiew

Well, you are a prope Pole, @FeralChild64 😆

**Comment by FeralChild64** [comment]
Sorry, it’s rather late here - I should go sleep in fact :)
