### ISSUE TITLE
A few `[mouse]` settings need some love

### ISSUE THREAD

**Issue by johnnovak** [dosbox-staging/dosbox-staging#3133]
`mouse_sensitivity` in particular:

- Modifying the setting at runtime has no effect; it can be only set from the config at startup. This is something super important to configure at runtime in the upcoming OSD.
- Nothing is logged when using invalid settings (e.g., `100 150` instead of `100, 150`, or `asdf`).
- We should support the comma-less syntax which is consistent with other compound config values (the comma should be still optional for backward compatibility reasons).
- Percentage signs should be optionally accepted for consistency with other config settings (e.g., `150%` and `100% 150%` should be valid). (Related: https://github.com/dosbox-staging/dosbox-staging/issues/3132)

The rest of the`[mouse]` settings should also be reviewed and enhanced as needed to support changing values at runtime (`mouse_capture`, `mouse_middle_release`, and `mouse_multi_display_aware` in particular; the rest are probably fine to only set at startup as they are hardware related).

**Comment by FeralChild64** [comment]
Regarding `mouse_sensitivity`:

> Modifying the setting at runtime has no effect; it can be only set from the config at startup.

I have made it only-at-start, because I have no idea how to define a sane behavior when it is being changed at the runtime.
What's more, the whole config API does not tell me which value was touched by the user, so if he executes `config -set mouse_sensitivity=120` when it already was 120, I won't be able to tell whether he touched `mouse_sensitivity` or some other setting (in fact, I'm not even sure if I'll get the notification at all if the supplied string is the same, I didn't test it).

If you can define some sane behavior, let me know.

> This is something super important to configure at runtime in the upcoming OSD.

Just use the same API the `MOUSECTL.COM` command uses - see `program_mousectl.cpp` file, `MOUSECTL::CmdSensitivity` function. Provide an empty `ListIDs &list_ids` parameter to change the setting for all the mouse interfaces, or specify which ones would you like to affect (like only DOS driver or only PS/2 mouse).

> Nothing is logged when using invalid settings

True - this is one of the drawbacks of the current configuration API. The code to retrieve the values is:

```C++
	PropMultiVal *prop_multi = conf->GetMultiVal("mouse_sensitivity");
	mouse_config.sensitivity_x = static_cast<int16_t>(
	        prop_multi->GetSection()->Get_int("xsens"));
	mouse_config.sensitivity_y = static_cast<int16_t>(
	        prop_multi->GetSection()->Get_int("ysens"));
```

and it does not return back any error information to me.

> We should support the comma-less syntax which is consistent with other compound config values (the comma should be still optional for backward compatibility reasons)
> Percentage signs should be optionally accepted for consistency with other config settings

Again, this are being parsed upstream, by the configuration subsystem - not by the mouse emulation code. First the infrastructure (config subsystem) has to be extended.

> The rest of the[mouse] settings should also be reviewed and enhanced as needed to support changing values at runtime (`mouse_capture`, `mouse_middle_release`, and `mouse_multi_display_aware` in particular; the rest are probably fine to only set at startup as they are hardware related).

Mostly done - the following settings can be changed at the runtime:
- `mouse_capture`
- `mouse_multi_display_aware`
- `mouse_middle_release`
- `mouse_raw_input`
- `dos_mouse_immediate`

I might implement runtime change of `ps2_mouse_model` in the future, but - unless someone gives me a valid use case - I consider it a low priority task.

------

I agree that the current configuration subsystem could see some love - unfortunately, I am busy with other topics, and I don't think I'll be able to handle this in a foreseeable future.

**Comment by johnnovak** [comment]
> > Modifying the setting at runtime has no effect; it can be only set from the config at startup.
> 

> I have made it only-at-start, because I have no idea how to define a sane behavior when it is being changed at the runtime.

> Just use the same API the `MOUSECTL.COM` command uses - see `program_mousectl.cpp` file, `MOUSECTL::CmdSensitivity` function. Provide an empty `ListIDs &list_ids` parameter to change the setting for all the mouse interfaces, or specify which ones would you like to affect (like only DOS driver or only PS/2 mouse).

I'm confused—so it _is_ possible to change sensitivity at runtime then? How can both statements be true? Just make `mouse_sensitivity` work as `MOUSECTL.COM` does, no? Ultimately, in an emulator real-time control of mouse sensitivity is important during playing a game. Having to restart the emulator 10 times to fine-tune the mouse sensitivity sucks; we absolutely want to be able to do this _while_ the game is running. So maybe you need to apporach it differently at the technical level, but this is the high-level goal of the feature. I mean, scaling the OS-reported figures can't be that hard, right?

I realise it might conflict with some of your other features, but keep the high level goal in mind and the most common use case: mouse _just works_ with the defaults in 99% of games, so 99% of people don't mess around with the mouse settings. BUT they want to adjust the mouse sensitivity at runtime! It's fine if you can't support real-time sensitivity adjustments with all the weird mouse config cases you introduced, but the 99% use case must work as people expect it to, IMO.

> What's more, the whole config API does not tell me which value was touched by the user, so if he executes `config -set mouse_sensitivity=120` when it already was 120, I won't be able to tell whether he touched `mouse_sensitivity` or some other setting (in fact, I'm not even sure if I'll get the notification at all if the supplied string is the same, I didn't test it).
> If you can define some sane behavior, let me know.

The way around that is to store the previous settings somewhere on init, then on next init you can compare them and figure out what's changed. I've been doing that for ages, man 😄 Check out `mixer.cpp` or `render.cpp`, there's lots of this diffing behaviour going on. It's completely manageable but yeah you need to adjust your mindset to it a bit.

> > Nothing is logged when using invalid settings
> 
> True - this is one of the drawbacks of the current configuration API. The code to retrieve the values is:
> 
> ```c++
> 	PropMultiVal *prop_multi = conf->GetMultiVal("mouse_sensitivity");
> 	mouse_config.sensitivity_x = static_cast<int16_t>(
> 	        prop_multi->GetSection()->Get_int("xsens"));
> 	mouse_config.sensitivity_y = static_cast<int16_t>(
> 	        prop_multi->GetSection()->Get_int("ysens"));
> ```
> 
> and it does not return back any error information to me.

`PropMultiVal` is a bit crap, don't use it 😄 @kcgen and myself have been just using string and doing our own parsing and validation. It's highly recommended you migrate to doing the same thing too, and the good news is you're just one `const auto parts = split(setting_value);` from that 😎 Most of your logic should remain the same but you'll have greater control over the validation and error reporting.

> > We should support the comma-less syntax which is consistent with other compound config values (the comma should be still optional for backward compatibility reasons)
> > Percentage signs should be optionally accepted for consistency with other config settings
> 
> Again, this are being parsed upstream, by the configuration subsystem - not by the mouse emulation code. First the infrastructure (config subsystem) has to be extended.

As above, take the matters into your own hands 😄 The whole config support will be ditched and rewritten anyway, and I'm pretty sure we want to continue this same approach going forward with "compound" settings: just use strings, and let the relevant subsystem deal with parsing the compound config settings as they can be very specific.

> > The rest of the[mouse] settings should also be reviewed and enhanced as needed to support changing values at runtime (`mouse_capture`, `mouse_middle_release`, and `mouse_multi_display_aware` in particular; the rest are probably fine to only set at startup as they are hardware related).
> 
> Mostly done - the following settings can be changed at the runtime:
> 
>     * `mouse_capture`
> 
>     * `mouse_multi_display_aware`
> 
>     * `mouse_middle_release`
> 
>     * `mouse_raw_input`
> 
>     * `dos_mouse_immediate`

Great news, thanks! 🎉 
 
> I might implement runtime change of `ps2_mouse_model` in the future, but - unless someone gives me a valid use case - I consider it a low priority task.

I don't think that's important; it's generally fine to require an emulator restarts for certain hardware-related changes. Yeah, we can do a lot more with sound cards and `sbtype`, but let's not go overboard with this for no good reason 😄 

> I agree that the current configuration subsystem could see some love - unfortunately, I am busy with other topics, and I don't think I'll be able to handle this in a foreseeable future.

As mentioned, it's probably best to keep using it as it is and not making major changes to it—it will go away. In the meantime, you can and absolutely should migrate to using plain strings for compound settings as explained. And there is no rush, this is not an urgent issue, just wanted to keep track of it 😄 Whenever you have time and the inclination, man 😎

**Comment by FeralChild64** [comment]
@johnnovak

> I'm confused—so it is possible to change sensitivity at runtime then?

As stated in the `mouse_sensitivity` help: `The setting can be adjusted in runtime (also per mouse interface) using internal MOUSECTL.COM tool, available on drive Z`. There are 2 situations which bother me currently:

Situation 1:

```C++
config -set mouse_sensitivity=100
mousectl PS/2 -s 200
mousectl COM1 -s 300
config -set mouse_sensitivity=150
```

What shall we do? Reset sensitivity of PS/2 and COM1 mouse interfaces? Or just set 150 as the new default?

Situation 2:

```C++
config -set mouse_sensitivity=100
mousectl DOS -s 200
config -set mouse_sensitivity=100
```

With current API we are not able to detect what the user did in the last step - we only know that the user changed some mutable setting in the `[mouse]` section, that's it.

One solution for both problem would be to replace `mouse-sensitivity` with a set of: `dos_mouse_sensitivity`, `ps2_mouse_sensitivity`, `com1_mouse_sensitivity`, `com2_mouse_sensitivity`, `com3_mouse_sensitivity`, `com4_mouse_sensitivity`, and (in the future) , `bus_mouse_sensitivity`.
I wanted to avoid overhelming the user with too many config options - but if the team agrees, I can implement it this way.

> `PropMultiVal` is a bit crap, don't use it 😄 @kcgen and myself have been just using StringProp and doing our own parsing and validation for a long time now. It's highly recommended you migrate to doing the same thing too, and the good news is you're just one `const auto parts = split(setting_value);` away from that

OK, this is something to do for me, then.

**Comment by johnnovak** [comment]
> One solution for both problem would be to replace `mouse-sensitivity` with a set of: `dos_mouse_sensitivity`, `ps2_mouse_sensitivity`, `com1_mouse_sensitivity`, `com2_mouse_sensitivity`, `com3_mouse_sensitivity`, `com4_mouse_sensitivity`, and (in the future) , `bus_mouse_sensitivity`.
> I wanted to avoid overhelming the user with too many config options - but if the team agrees, I can implement it this way.

Here's an idea @FeralChild64: how about having `mouse_sensitivity` in the config as a _global_ sensitivity multiplier while still keeping the per-mouse-type tweakability via MOUSECTL? The rationale is that 99.999% of people just use a _single_ mouse anyway. So in the OSD you could select the type of your single mouse (PS2, DOS, COM1, COM2, COM3, COM4), and the sensitivity slider would set `mouse_sensitivity` which just sets this global sensitivity multiplier.

Then the calculation for every mouse type would be `global_scale_factor * ps2_mouse_factor`, etc. The per-mouse sensitivities would be 100,100 by default too. That bypasses your dilemma completely too, it would allow for ultimate flexibility for niche users, but it won't pollute the config with many settings, plus it's easily supportable for the 99.99% most common single mouse use case. It would work similarly to having a master volume control in addition to the per-soundcard volume controls.

Then the 0.001% of users who want to mess around with multiple mice having different sensitivities, using multiple mice at the same time, etc., can do so using the MOUSECTL commands, but that niche feature won't be exposed on the OSD.

**Comment by Torinde** [comment]
I suggest: in the OSD you could select the mouse (PS2, DOS, COM1, COM2, COM3, COM4, **All**), and the sensitivity slider would set relevant mouse sensitivity (where the global sensitivity multiplier is set if you selected "All" or just skipped selecting a specific mouse, e.g. that selector remained empty/default).

**Comment by FeralChild64** [comment]
@johnnovak OK, this I can implement.

@Torinde OSD is still far away and out of scope of this issue.

**Comment by johnnovak** [comment]
Sounds like a plan then, @FeralChild64 🚀 

Not a bad idea, @Torinde 👍🏻
