### ISSUE TITLE
Jurassic Park (1993) - Installation Bug That Totally Prevents Game Installation

### ISSUE THREAD

**Issue by MasterO2** [dosbox-staging/dosbox-staging#3135]
Windows 10, 64-bit
Dosbox Staging 0.80.1, 64-bit

Original bug from Vogons: https://www.vogons.org/viewtopic.php?p=169833#p169833

How to re-produce in Dosbox-Staging, 0.80.1, 64-bit:

1. Get Jurassic Park (1993) from EXODOS.

2. Imgmount the CD-Rom image in dosbox-staging.conf's [autoexec]:

* `imgmount d path\to\JP_CD-ROM.cue -t cdrom`

3. Open Dosbox-Staging, navigate to the D drive, then the `JURASSIC` folder, then run `INSTALL.EXE`.

4. When you start the installer, the install path is `:\JURASSIC` and **is missing the drive letter.**

5. The installer **does not** allow you to add the letter C to install the game to the C drive.

**Comment by johnnovak** [comment]
Thanks for linking the Vogons comment @MasterO2. Based on that, this is unfixable at the emulation level:

> There is a bug in the installer when the highest drive letter is Z. Also happens in real DOS if you set LASTDRIVE=Z in the CONFIG.SYS file.

The two possible workarounds:

- Use the TSR attached to the Vogons post
- Temporarily unassign the Z drive to install the game

Could you please document this on the wiki on the problematic games page? Then I'll close this.

**Comment by MasterO2** [comment]
@johnnovak:

https://github.com/dosbox-staging/dosbox-staging/wiki/Game-issues#jurassic-park-1993

**Comment by johnnovak** [comment]
Thanks @MasterO2 🎉

**Comment by MasterO2** [comment]
https://github.com/dosbox-staging/dosbox-staging/wiki/Preparing-games-to-run-with-batch-files#jurassic-park-1993 as well.
