### ISSUE TITLE
S3 Colors Incorrect on PowerPC big-endian platforms

### ISSUE THREAD

**Issue by casey-ac** [dosbox-staging/dosbox-staging#3144]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Different version than latest?

0.81.0-alpha

### What Operating System are you using?

Other

### If Other OS, please describe

Linux PPC64 kernel, 32-bit userland (Debian derivative)

### Relevant hardware info

IBM PowerPC 970MP x2, Radeon HD6450

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

DOSBox Staging on PowerPC Linux displays incorrect colors for VGA modes. For example, red and green channels seem to be flipped. However, EGA does not have this issue. Additionally, if a screenshot is taken using the in-app Ctrl+F5 method, the colors will be correct, but using an out-of-app screenshot utility will show the incorrect colors. Changing renderer to texture/software also does not have an impact. This bug seems to be very similar to a bug reported for DOSBox-X:  [https://github.com/joncampbell123/dosbox-x/pull/3428](url)

I am happy to patch/test any potential solutions. 

VGA:  
![dosbox-staging_VGA-S3](https://github.com/dosbox-staging/dosbox-staging/assets/33240480/d1b46e8c-acf1-4cd4-9b97-c1c9669e94ee)

EGA:  
![dosbox-staging_ega](https://github.com/dosbox-staging/dosbox-staging/assets/33240480/8870b903-9b82-4c06-908c-7af1c7cc4714)

Theme Hospital In-Game Example (note the grass is red):  
![dosbox-staging_theme-hospital_colors](https://github.com/dosbox-staging/dosbox-staging/assets/33240480/999717ff-19fb-47a7-9cb5-0a8469bd6772)

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Launch DOSBox Staging on PowerPC Linux
2.
3.

### Your configuration

```ini
https://gist.github.com/casey-ac/1c60eeb7c77c63ef592e937f0711c04f
```

### Provide a Log

```text
https://gist.github.com/casey-ac/75c4e1f56345530cf9682423d79a1a3c
```

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by johnnovak** [comment]
Only @kcgen has any interest in supporting PPC from the dev team; it's kinda "unofficially" supported only 😄 Which means any help is welcome. This seems like an endianness issue.

I suggest cross-checking with 0.80.1, and if it's fine on 0.80.1 then bisecting `main` to find the offending commit.

If you could give a go at a patch that would be great as this is low-priority and we have no way to test the successfulness of a patch (unless @kcgen has capacity to work on it on his PPC laptop).

**Comment by Grounded0** [comment]
@casey-ac 

Are you running DOSBox Staging as `ppc32` or `ppc64` binary? This could help dissecting this as we have a few `ppc64le` users to narrow it down further.

**Comment by Grounded0** [comment]
User is confirming in #3145 that the user is running the binary as 32-bit PowerPC big endian.

**Comment by classilla** [comment]
I've seen this problem when SDL and DOSBox disagree about the byte ordering (RGB vs BGR, etc.).

**Comment by Grounded0** [comment]
Related commits?

- #2823 
- #2766

**Comment by johnnovak** [comment]
> Pinging @weirddan455
> 
> Related commit?
> 
>     * [Rename PixelFormat enum members BGR555 and BGR565 to RGB555 and RGB565 #2823](https://github.com/dosbox-staging/dosbox-staging/pull/2823)

No need to ping him @Grounded0:

> This is just a re-name. _Nothing functional changes_ in this PR.

**Comment by Grounded0** [comment]
Author can trace the commit that broke it from March 2023 and tell us.

Last working commit is `kc/openbsd-ppc-1`

We're trying to release 0.81 and have zero bandwidth now.

**Comment by johnnovak** [comment]
Agreed @Grounded0 . Actual PPC users invested in getting PPC to work are welcome to fix this, of course, but outside of the scope of the core dev team (except for @kcgen if/when he feels like it).

**Comment by weirddan455** [comment]
I am interested in fixing this bug.  Endianess bugs are usually pretty straightforward to fix and their existence is a code smell that can lead us to fixing other bugs.

However, I don't have big endian hardware to test on so I would need it bisected to a specific commit (saying it broke sometime after March doesn't help me much).

**Comment by LowLevelMahn** [comment]
i think qemu + debian 12 (https://cdimage.debian.org/cdimage/ports/12.0/ppc64/) could be a way for the ones that want to help but missing the hardware - i once fixed a big-endian problem using qemu and sparc

**Comment by weirddan455** [comment]
> i think qemu + debian 12 (https://cdimage.debian.org/cdimage/ports/12.0/ppc64/) could be a way for the ones that want to help but missing the hardware - i once fixed a big-endian problem using qemu and sparc

I tried qemu before and kept running into problems.  I missed that Debian 12 still supported PowerPC big endian.  They've removed it from https://www.debian.org/distrib/netinst only showing ppc64el (little endian).

I ended up trying various architectures on NetBSD.  I think I got SPARC to boot but couldn't get a stable X11 environment up.  I spent several hours on it and it was a royal pain in the ass.  I would have much preferred to use Debian.

If someone can provide some good instructions on how to get a working qemu environment suitable for compiling/testing Dosbox maybe I'll give it another go.

**Comment by LowLevelMahn** [comment]
https://wiki.powerprogress.org/OpenStackPPC64Debian10  seem to be recent enough, is for debian 10, should work for 12

**Comment by Grounded0** [comment]
I still got my 2002 PowerBook G4 in my closet with Mac OS X 10.4 but i really don't have the energy to start tinkering with it.

**Comment by Grounded0** [comment]
@kcgen just stated on IRC that the person pulled their PowerBook G4 from their closet and has builds underway to have this sorted out by the core developer team.

**Comment by johnnovak** [comment]
> We're committed to supporting the PowerPC platform.

Well, "unofficially", kinda/sorta 😏

**Comment by Grounded0** [comment]
> Well, "unofficially", kinda/sorta 😏

That's why i omitted "officially" not to get in jeopardy. 😏

**Comment by Grounded0** [comment]
@casey-ac

Can you confirm 0.82.0 RC1 runs properly on PowerPC. Thanks.

**Comment by casey-ac** [comment]
@Grounded0 I built version 0.82.0-alpha with no issues. I tested a couple games with S3 graphics that played well, but I haven't gone through the whole gamut.

**Comment by Grounded0** [comment]
@casey-ac

Is the PowerPC build still working fine?

We don't have any big endian machines in the team, so doing my annual checkup.
