### ISSUE TITLE
/src/cpu/meson.build core selection is incorrect for ppc64

### ISSUE THREAD

**Issue by casey-ac** [dosbox-staging/dosbox-staging#3145]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Different version than latest?

0.81.0-alpha

### What Operating System are you using?

Other

### If Other OS, please describe

Linux PPC64 kernel, 32-bit userland (Debian derivative)

### Relevant hardware info

PowerPC 770MP x2, Radeon HD6450

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

DOSBox-Staging does not currently build on 64-bit PowerPC (PPC64) systems due to an error in /src/cpu/meson.build. This file assigns the target "PPC64LE" for PPC64; however, PPC64 is a big-endian architecture. If the target is changed to "POWERPC" as specified below the build will complete successfully. 

Line 26 currently:  
    [ ['ppc64',   'powerpc64'],   ['auto', 'dynrec'],  'C_DYNREC',      'PPC64LE', 1,         1 ], # 64 bit PPC processors

However, it should specify:  
    [ ['ppc64',   'powerpc64'],   ['auto', 'dynrec'],  'C_DYNREC',      'POWERPC', 1,         1 ], # 64 bit PPC processors

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Attempt to build DOSBox-Staging on a PPC64 based system
2.
3.

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by Grounded0** [comment]
I don't think its a good idea to start compiling 32-bit big endian binaries for `ppc64` target but pinging @classilla as our PowerPC person.

**Comment by classilla** [comment]
No, reporter is correct, `ppc64` is big-endian and `ppc64le` is little. However, I have no idea if the dynrec JIT backend would work properly on big systems, so we'd need to check if it does (and disable it if not). There's not much that requires a particular endianness and I tried to write with that in mind but it is certainly not tested.

**Comment by Torinde** [comment]
What is "PowerPC 770MP" and where is it used? I found 750 and 970, but no 770...

Another PowerPC build that fails for a long time is the Fedora ppc64le:
https://github.com/dosbox-staging/dosbox-staging/actions/runs/6945073363
![image](https://github.com/dosbox-staging/dosbox-staging/assets/97228894/0a47bdde-ba6b-4f47-9499-d3c2e4371421)
