### ISSUE TITLE
GUI for changing options / configuration

### ISSUE THREAD

**Issue by enderandrew** [dosbox-staging/dosbox-staging#315]
From dreamer's comments it may make sense for a new implementation rather than using the old community patch.

**Comment by dreamer** [comment]
@enderandrew Thanks you for creating this issue, I think we'll use it for tracking progress on our GUI rework :) (I see I haven't mentioned my plans for this anywhere on the project page yet)

### Why I don't want to copy DOSBox-X interface

I don't know how much it differs, but I believe DOSBox-X unifdefed and cleaned up implementation, that sits disabled in the codebase: https://github.com/dosbox-staging/dosbox-staging/blob/master/src/gui/sdl_gui.cpp - but maybe that's something totally different and there's a patch implementing menu bar like DOSBox-X has flying around (I would appreciate the link to such patch, I've never seen it).

Anyways - this solution is pretty good, but I consider it a "local optimum" thing.

- It's not tailored to gamepad usage at all (community using DOSBox on Raspberry Pis or set-top boxes is large and vibrant, we want UI that can be navigated with a controller - like most modern game menus are
- looks really dated and unattractive (parts look like pseudo-text mode, parts implement Windows 3.x-like interface while old ugly mapper GUI is kept in place)
- it mixes options, that should not be exposed via UI (those, that are very game-specific and should be hardcoded inside game container, like CPU type) with user options (like scalers or volume change)
- and it implements a whole windowing UI (with movable windows and such) in there, so it seems like much more complicated, that it needs to be

I am not trying to criticize design decisions from DOSBox-X - their UI is *excellent* for DOSBox-X usecase - allows for rapid testing of many of configuration tweaks to find the best ones for particular demo or game.

I just think it's not well suited for dosbox-staging, where we want GUI to get out of the way as much as possible, but still allow user to tweak options (but not all options, only the ones that user reasonably might want to change).

### Plan for dosbox-staging

My plan is:

1. Remove existing "keymapper" GUI completely and re-appropriate Ctrl-F1 shortcut to show half-transparent overlay screen (a'la Quake menu, or Steam overlay)
2. For the first iteration, overlay screen should have a new "keymapper" submenu, allowing to change keybindings using similar interface as modern PC games (e.g. Doom 2016) - such interfaces are better suited for the purpose than showing full ugly "mini-keyboard" and expecting user to click on specific letter; it will require some design work to get it right
3. After that, we'll start adding new submenus, with options, that user likely wants to change (like shaders or "start in fullscreen", or fullscreen resolution, or volumes)

Additional requirements:
- All UI should be navigable using keyboard, or mouse, or controller
- Saving options should go into game-specific .conf file, *not* into global default dosbox-staging .conf file - to avoid problems with settings for one game affecting other games.
- We should follow the user interface patterns estabilished by modern cross-platform games - new users familiar with modern games are our target audience.

We might need to use new dependency or integrate a library for creating gaming UI - AFAIK there are many competing libraries for such use case, but I haven't investigated it yet (suggestions are welcome).

Some necessary technical groundwork for this was touched by #222 and then refined in #279, #283

I would be pretty happy if people started to mindstorm and prepare interface mockups for this overlay page - I suggest working in similar way e.g. Gnome design team approaches user interface work (where they show inspirations, and then go through multiple design iterations to arrive at functional and beautiful design). *I'm not saying follow Gnome HIG or Gnome user interface - I'm saying mimic the way they work on designing the GUIs.*

(This is a long-haul feature, it's not going to be finished for next release, and it will require many iterations and subtasks)

**Comment by michalgor** [comment]
Never used it, but AFAIK Dear ImGui is very popular and is lightweight

https://github.com/ocornut/imgui

**Comment by HeuristicPerson** [comment]
Would it be possible to create some sort of simple API or interface so anyone can interact from outside with DosBox?

That way we can not only change the configuration but also send commands from external programs to launch programs inside DosBox, set environment variables and so on...

**Comment by kcgen** [comment]
@HeuristicPerson - can you create a new issue for this?  (in the three-dots to the right of your comment, you can "create a new issue ... " for the comment).  

I believe it's distinct enough from GUI output that we shouldn't overlap in this issue here.

**Comment by johnnovak** [comment]
See main discussion & plans about the OSD feature here:
https://github.com/dosbox-staging/dosbox-staging/discussions/1953

**Comment by Burrito78** [comment]
Continued in #1953
