### ISSUE TITLE
200 USD bounty for deploying PR #3157

### ISSUE THREAD

**Issue by Grounded0** [dosbox-staging/dosbox-staging#3150]
The roundel is universally disliked and isn't compliant with modern OS interface guidelines for icons. Anyone who gets this PR merged gets a 200 USD bounty paid by me personally.

I can pay via SWIFT, cryptos available in Coinbase, or PayPal. Make the design shown below in required icon sizes, get it preferably merged before 0.81.0 ships and collect your 200 USD.

The application icons need an outline pictured here due to bleeding issues against white background:

![image](https://github.com/dosbox-staging/dosbox-staging/assets/48192273/f0585912-5a72-46fb-a7cf-c6f9d0267027)

Connected issues and PRs:

- #3157
- #2232

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by Grounded0** [comment]
Pinging @ThomasEricB

**Comment by johnnovak** [comment]
I'm fine to do it @Grounded0 . I like money 🤑 😎

**Comment by Grounded0** [comment]
Assigned to @johnnovak
