### ISSUE TITLE
pi5 - dosboxstaging - piOs Compiled and running.  pi0S 64bits. Compiled but no running. Logs attached. 

### ISSUE THREAD

**Issue by jlopezvil** [dosbox-staging/dosbox-staging#3154]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### What Operating System are you using?

Linux ARM (Raspberry Pi)

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

I have installed on my pi5 piOS bookworm lite and piOS lite bookworm x64. Also configured retropie by hand. I have compiled dosbox-staggin with retropie .sh file in bookworm 32 bits and it is ok and running ok. But in x64 it compiles ok but doesnt run any games as on 32 bits. I attach compile log and attempt running log.

### Steps to reproduce the behaviour.

Explain how to reproduce
1. 
2.
3.

### Provide a Log

```text
https://gist.github.com/jlopezvil/40605ad53056f1a76cd1eaffe0018912
```

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by jlopezvil** [comment]
I have attached in  logs a log with attempt running a game on x64 bookwork with dosbox-stagin compiled to last commit.

**Comment by kcgen** [comment]
RetroPie doesn't support aarch64 builds or the Pi5 (see here: https://retropie.org.uk/download/)

So I would dump this _retropie-shoe-horned-into-pi5+aarch64_ configuration. Also, mixing retropie's 32bit library dependencies will conflict with your  host OS's package manager.

Start with a clean OS that supports The Pi5 and then build Staging yourself, without using retropie's scripts or dependencies.

See this ticket here by @brunnis who has a working Out configuration with Debian, running latest `main` in an aarch64 with hardware acceleration: https://github.com/dosbox-staging/dosbox-staging/issues/3152#issuecomment-1826419480

**Comment by kcgen** [comment]
Will close this as not supported because retropie itself doesn't support the pi5.
