### ISSUE TITLE
Drakkar (1989) bugs

### ISSUE THREAD

**Issue by kcgen** [dosbox-staging/dosbox-staging#3158]
Flagged by @python-exoproject here:

- https://github.com/exoscoriae/eXoDOS/issues/4875

@python-exoproject, can you drop a note about the nature of the regression (Crash on start? video/audio/performance/...)

**Comment by Python-Exoproject** [comment]
Not much to tell unfortunately. The game starts, after the title screen there is a picture of a ship. When working the background then flashes (meant to be lightning I think?). In 81.0a the game just stops before the flashing would start, nothing in the console, no hard crash - just stops.

**Comment by kcgen** [comment]
Thanks for this info @Python-Exoproject !

Repro pack, if anyone wants to bisect: [Drakk89-repro-pack.zip](https://github.com/dosbox-staging/dosbox-staging/files/13508375/Drakk89-repro-pack.zip) 

(yes: only 39 KB!)

**Comment by kcgen** [comment]
Ahh good catch - yup, dropping that label.

**Comment by kcgen** [comment]
> Don't want to keep this as a bug?

I _think_ the bug is on the game's side; but I guess we'd need real hardware to figure it out. 

Even SVN has issues when a joystick is present (same hang):

![2023-11-30_21-19](https://github.com/dosbox-staging/dosbox-staging/assets/1557255/cee8bef6-ec12-40b3-b801-ecccf6f80a0c)

Some games just don't do well when a game port card is present; maybe their authors didn't have one. Game ports weren't really ubiquitous in the DOS gaming scene until Creative integrated them in their first Sound Blaster  in 1989 (the same year this game was released).

Another "tell" is that this game doesn't support any FM synth or DACs.. so the author might not have had any audio (or other gaming) expansion devices. 

If you want to keep it open and check it on your physical PC first (w/ SB present) - that might solve it :-)

**Comment by rderooy** [comment]
I tested it with 86Box 4.1.

- When a joystick **is not** attached it boots from the disk image just fine and shows the viking ship with the "lighting" and continues to the game menu screen.
- When a joystick **is** attached, it shows the viking ship without the lighting, but the game hangs at that point.

**Comment by kcgen** [comment]
Looked more at this, and I think it's OK.

It looks like on hardware, the game port disabled the IO port (201h) when a joystick isn't present.

This is why the game works for us when we set `joysticktype = disabled` or `hidden`: because both those settings disable joystick IO port 201h, no matter what.

Our default though is to expose IO port (201h) because we want to let users map keyboard events to "mock up" a joystick, even if they don't have one. 

There are maybe 30 or so Tandy games that _require_ joystick control, so this approach of allowing keyboard->joystick events lets these games be played by people without a joystick (unlike on real hardware). 

eXoDOS ships mappings for these specific games that pre-configure the keyboard arrow keys, ctrl, alt buttons to joystick actions.

Because the number of games that require a joystick outnumbers those that  need the abense of a joystick (like Drakkar), the current default makes the most sense. (and setting `joystick = hidden` is perfectly fine for games like Drakkar).

**Comment by Grounded0** [comment]
The game allows to play with the hacks we have in place. It's a poorly written game we allow users to play. Suggest closing this.

**Comment by johnnovak** [comment]
> The game allows to play with the hacks we have in place. It's a poorly written game we allow users to play. Suggest closing this since this issue is resolved on our end.

Agreed, probably it's a broken mess on various hardware configs too.
