### ISSUE TITLE
Crashing on raspberry pi 5 when auto switching to max 100% CPU cycles

### ISSUE THREAD

**Issue by ekondis** [dosbox-staging/dosbox-staging#3160]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### What Operating System are you using?

Linux ARM (Raspberry Pi)

### Relevant hardware info

Raspberry PI 5

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Dosbox-staging runs normally, but when a dos application is executed that leads to auto switching to max 100% cpu cycles (e.g. Windows 3.1) it crashes.

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Launch a DOS program that requests max 100% cycles, e.g. Windows 3.1
2.
3.

### Your configuration

```ini
https://gist.github.com/ekondis/42cdc9aaed40f91c3cd6572524d15054
```

### Provide a Log

```text
dosbox-staging logs:
https://gist.github.com/ekondis/c76d876ca8ccf0726760553c80afa796

gdb stack trace:
https://gist.github.com/ekondis/b18581a0217ec9dff6d3e6f8004c3b3f
```

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by kcgen** [comment]
Great detailed logs, @ekondis!

In `src/cpu/dyn_cache.h` on line 894, can you replace the assert statement with the following (in green, without the preceeding `+` signs):

```diff
-       assert(mp_res == 0);
+       if (mp_res != 0) {
+               LOG_ERR("DYNAMIC CPU: Error flagging %lu bytes "
+                       "at 0X%" PRIuPTR " with %s permissions because %s",
+                       size,
+                       reinterpret_cast<uintptr_t>(ptr),
+                       execute ? "execute" : "write",
+                       strerror(mp_res));
+       }
```

This will just log a bit more detail.

Also, if you can try a separate build that disables the W^X memory changes:

```shell
meson setup -Dper_page_w_or_x=disabled  build/without_wx
meson compile -C build/without_wx
```

Launch with `path/to/build/without_wx/dosbox`.  Just curious if that changes anything. You can delete the `build/without_wx` directory after (and your existing build will be unaffected).

**Comment by ekondis** [comment]
Adding the extra LOG_ERR yields these logs: https://gist.github.com/ekondis/8bae90b9b9c81dd3525ab920ac1804ad

I also tried a build without wx, but the problem still occurred: https://gist.github.com/ekondis/6ea298f23eb8b2239d0d491024a01ab0

**Comment by kcgen** [comment]
Thanks for the logs, @ekondis, however I'm not seeing anything too helpful to go on.

Can you run `lsb_release -a` and `uname -a`? This will report your operating system and kernel details.

We do have positive reports from the pi5, such as from @brunnis [here](https://github.com/dosbox-staging/dosbox-staging/issues/3152#issuecomment-1826937903). 

@brunnis, can you also run `lsb_release -a` and `uname -a` and report back here?

Maybe you two are running different Linux OS distros and/or kernels.

**Comment by Brunnis** [comment]
@kcgen I'll try to remember to do this tomorrow.

**Comment by ekondis** [comment]
These are the outputs for my case:

```
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 12 (bookworm)
Release:	12
Codename:	bookworm
```

```
Linux pluto 6.1.0-rpi6-rpi-2712 #1 SMP PREEMPT Debian 1:6.1.58-1+rpt2 (2023-10-27) aarch64 GNU/Linux
```

What is strange is that the same binary on raspberry pi 400 (essentially pi 4) does not reproduce this issue. The same info for raspberry pi 400 follows:

```
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 12 (bookworm)
Release:	12
Codename:	bookworm
```

```
Linux Oberon 6.1.0-rpi6-rpi-v8 #1 SMP PREEMPT Debian 1:6.1.58-1+rpt2 (2023-10-27) aarch64 GNU/Linux
```

**Comment by kcgen** [comment]
Also seeing a possibly-related MMU paging error reported from the pi5 running the same 6.1.0 rev 2712 kernel on Bookworm: https://github.com/raspberrypi/linux/issues/5676

@Brunnis - any luck w/ getting your system specs?

@ekondis, If you can build with the address sanitizer, it will catch any memory out of bounds issues:

```shell
meson setup \
  -Dbuildtype=debugoptimized \
  -Dunit_tests=disabled \
  -Db_sanitize=address \
  build/asan

meson compile -C build/asan
```

Launch with `path/to/build/asan/dosbox`

We do run ASAN builds on macOS+ARMv8 and x86 systems, but less-so on Linux+ARMv8, so this might reveal something!

**Comment by johnnovak** [comment]
Ok, @kcgen ... So this is why you started going down the pagesize path 😄 Honestly I would carefully ifdef it for the platform that need other sizes than 4k. Whitelist on demand, not change potentially everything wholesale. Seems risky.

**Comment by kcgen** [comment]
Page size needs to be correct because the dynamic core converts DOS instructions on the fly into a sequence of host machine instructions, packed into a "page", and passes it to the host as if it's native compiled code. 

The host then executes that page of machine byte code, one page at a time (that's not something we're in charge of, it's literally tied to the host hardware). 

Some processors have boot time switches can control the page size, like the pi5.

So there's no wiggle room; we either get it correct or DOSBox just crashes straight away as soon as the dynamic recompiler passes its first generated page of instructions in, like we saw here.

Knowing that users can boot different kernels to use different page sizes, I think moving to runtime detection is the bomb-proof solution, even better than built-time syscall. 

This is going to become a bigger problem with arm64 and aarch64 chips now becoming very common.

**Comment by johnnovak** [comment]
Thanks for taking the time to explain this to me @kcgen. Might be worthwhile to paste this into the description of the related PR for posterity as it wasn't clear why this is necessary. Yeah, now I agree too this needs to be detected at runtime 👍🏻

**Comment by kcgen** [comment]
Good call, @johnnovak - will do!

**Comment by ekondis** [comment]
I can also confirm from my side that the issue looks to be resolved with this change.

Thanks @kcgen for the thorough explanation. 

I also believe determining page size on runtime is the proper way to go as it would be problematic having a fixed one for platforms like Raspberry PI, where this can be configurable. Moreover, AFAIK the raspberry pi OS packages are common for all 64bit raspberry PI hardware releases, so this could be an issue when creating a generic DEB package.
