### ISSUE TITLE
Monkey Island 2 no voice with sbpro2 (works with sb16)

### ISSUE THREAD

**Issue by AnonTet** [dosbox-staging/dosbox-staging#3165]
### Are you using the latest Dosbox-Staging Version?

- [ ] I have checked releases and am using the latest release.

### Different version than latest?

0.81.0-alpha-2053

### What Operating System are you using?

Windows 11

### Whats your question and how can we help?

As per title, I since I know there was an issue that affected the talkie version in MI1 using the sb16 a few versions back, I wonder if SBPro2 has the same issue. In dosbox.conf using sb16 I can hear the voices, but sbpro2 is mute.
Not sure if it is a bug or something HW related to sbpro2 or lack of support from MI2 hence the question instead.
Thanks for your work.

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by kcgen** [comment]
@AnonTet , can you please re-open this as an issue instead of a question?

The form includes fields asking for a link to the package and your conf file so the issue can be reproduced.

**Comment by AnonTet** [comment]
will do. closing this

**Comment by johnnovak** [comment]
> In dosbox.conf using sb16 I can hear the voices, but sbpro2 is mute.

@AnonTet It's normal and expected. The talkie version only has speech with the SB16.

> Not sure if it is a bug or something HW related to sbpro2 or lack of support from MI2 hence the question instead.

The talkie version is a hack and apparently badly coded. This is how the game would behave on a real hardware SB Pro2, and in fact I'm pretty sure any SB model prior to the SB16.

Only the authors of the talkie version can fix this to support other SB models as well.
