### ISSUE TITLE
Monkey Island 2 Ultimate Talkie without voice if using sbpro2

### ISSUE THREAD

**Issue by AnonTet** [dosbox-staging/dosbox-staging#3166]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Different version than latest?

0.81.0-alpha-2053

### What Operating System are you using?

Windows 11

### Relevant hardware info

 i5 8600K @5GHz - MSI GTX1080 Gaming X - 1080p@240Hz G-Sync

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

As per title, I since I know there was an issue that affected the talkie version in MI1 using the sb16 a few versions back, I wonder if SBPro2 has the same issue. In dosbox.conf using sb16 I can hear the voices, but sbpro2 is mute.
Not sure if it is a bug or something HW related to sbpro2 or lack of support from MI.
Thanks for your work.

### Steps to reproduce the behaviour.

1. Install eXoDOS
2. backup eXo\emulators\dosbox\staging0.81.0a 
3. edit eXo\emulators\dosbox\staging0.81.0a\dosbox-staging.conf and change sbtype to sbpro2 (default is sb16)
4. Install MI2
5.  Run MI2 with option pixel-perfect, use default settings, choose dosbox and then talkie version
6. no voices are heard. 
7. change back sbtype to sb16 and run it as above. Now we can hear the voices

another method: 
1. go to eXo\emulators\dosbox\staging0.81.0a (updated to -2053 version - btw, 2007 doesn't work either
2. call dosbox.exe
3. run: mount c ..\..\..\eXoDOS\mi2 (after install mi2 from launchbox)
4. c:
5. cd talkie
6. monkey2 s <- s is short that tells the .exe to use soundblaster. to use other settings use s220/7/1 for example (default is s220/7/8)

### Your configuration

```ini
I use eXo defaults. Just change sbtype between sbpro2 and sb16:

sbtype              = sbpro2
#sbtype              = sb16
sbbase              = 220
irq                 = 7
dma                 = 1
hdma                = 5
sbmixer             = true
sbwarmup            = 100
oplmode             = auto
sb_filter           = auto
sb_filter_always_on = false
opl_filter          = auto
cms_filter          = on
```

### Provide a Log

```text
I don't know how to get dosbox logs.
```

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by johnnovak** [comment]
No problem @AnonTet. Copying my earlier answer here for posterity (https://github.com/dosbox-staging/dosbox-staging/issues/3165#issuecomment-1836818452):

---

It's normal and expected. The talkie version only has speech with the SB16.

The talkie version is a hack and apparently badly coded. This is how the game would behave on a real hardware SB Pro2, and in fact I'm pretty sure any SB model prior to the SB16.

Only the authors of the talkie version can fix this to support other SB models as well.

**Comment by kcgen** [comment]
Glad @johnnovak knew the limitations of this hack, @AnonTet -- and very thorough ticket and repro steps! Thank you. Please help us test more; this is the attention to detail and teat quality needed in the run up to 0.81.
