### ISSUE TITLE
100 USD bounty for fixing icons on Linux due to the deployment of PR #3157

### ISSUE THREAD

**Issue by Grounded0** [dosbox-staging/dosbox-staging#3169]
Icons are now a mishmash of legacy and new style icons on Linux due to deployment of PR #3157. Deliver a PR fixing this in a deployable state and collect 100 USD bounty from me. I can pay via SWIFT, cryptos available in Coinbase, or PayPal.

#3157 has all the technical aspects already detailed on what needs to be fixed and how it can be fixed. We just need a person with motivation to fix Linux desktop user experience now for everyone who uses Linux like me (though i only use it over SSH or Mosh).

Connected issues and PRs:

- #3157

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by weirddan455** [comment]
I just compiled latest main with the icon changes merged.  However, I can only see the small icon in the bottom taskbar and the even smaller icon at the top-left of the window.  I see your comment here:  https://github.com/dosbox-staging/dosbox-staging/pull/3157#issuecomment-1837000072

However, I don't know how you're seeing all those different icon sizes from inside KDE.  My alt+tab doesn't look like your "large icon switcher".  It opens a bar on the left side of the screen and shows an icon the same size as in the task bar.

**Comment by Grounded0** [comment]
Cuttlefish is KDE's icon theme viewer and comes with plasma-sdk package.

**Comment by Grounded0** [comment]
Enabling KDE Large Icon Application Switcher for testing purposes:

https://bbs.archlinux.org/viewtopic.php?id=218308

**Comment by weirddan455** [comment]
Did some testing on this.  The .desktop file that we have in `contrib/linux/dosbox-staging.desktop` is good with regards to icons and matches what other applications are doing.  It's one single line in there `Icon=dosbox-staging` that tells it what icon to use.

The icon files themselves need to be placed in a specific location for the desktop environment to find them.  There are (at least) two directories that should always get searched: `~/.local/share/icons` (per user directory) and `/usr/share/applications/icons` (system-wide directory).  Inside that directory, they should be placed in `hicolor/256X256/apps/dosbox-staging.png`.  Icons of multiple resolutions can be placed in the appropriate folder (replace 256X256 with the real resolution of the icon).  One SVG icon can go in `hicolor/scalable/apps/dosbox-staging.svg`

>  Question is what we're going to do with [icon.c](https://github.com/dosbox-staging/dosbox-staging/tree/main/src/gui/icon.c).

Remove this I think.  We may not need to programmatically set an icon at runtime at all.  Currently, this code is already ignored by MacOS and MSVC:

https://github.com/dosbox-staging/dosbox-staging/blob/c60501fa0abbb369e157c49b9644ffdaf41fc09d/src/gui/sdlmain.cpp#L520-L551

That leaves Linux and MSYS2 Windows builds.  For MSYS2, I would prefer to have the build system embed the icon the same way MSVC does.  For Linux, the runtime `SetIcon()` approach does not work on Wayland at all.  The .desktop file approach on Linux works on both X11 and Wayland.

From testing now in KDE + X11, the .desktop file takes precedence for the icon in the taskbar but the icon in the top left of the window gets replaced by the `SetIcon()` function at runtime leading to mis-matched icons.

**Comment by johnnovak** [comment]
> That leaves Linux and MSYS2 Windows builds. For MSYS2, I would prefer to have the build system embed the icon the same way MSVC does. For Linux, the runtime SetIcon() approach does not work on Wayland at all. The .desktop file approach on Linux works on both X11 and Wayland.

+1 for getting rid of `icon.c`. Nuke it with _extreme prejudice_ @weirddan455 😎 🤘🏻

**Comment by shermp** [comment]
MSYS2 builds should already be embedded using windows resources like MSVC does? I'm pretty sure I implemented that in meson.

**Comment by shermp** [comment]
> MSYS2 builds should already be embedded using windows resources like MSVC does? I'm pretty sure I implemented that in meson.

```meson
# Add Windows resources file if building on Windows
if host_machine.system() == 'windows'
    winmod = import('windows')
    res_file = winmod.compile_resources('src/winres.rc')
    dosbox_sources += res_file
endif```

**Comment by peteroupc** [comment]
I can see that the approach for icon generation illustrated in this issue and in #3157 and #3171 may be useful for GUI applications in general, not just DOSBox.

**Comment by weirddan455** [comment]
>  The issue is now that KDE Plasma prefers bitmaps over vector icons and pulls its icon resource for the "large icon task switcher" now from the small bitmaps. It of course looks like dog shit.

Ok, I'll do some testing on this later.

>  My recommendation is to ignore Gnome HIG and provide bitmaps in larger sizes for Linux at sizes of 48x48, 64x64, 96x96, 128x128, and 256x256 to ameliorate this issue. Thanks for perseverance.

Or could we just not ship .png files at all so we force it to use the .svg?  That's the point of an SVG to look good at all sizes right?

**Comment by johnnovak** [comment]
@weirddan455 @Grounded0 The reason behind shipping small bitmap icons in addition to the SVG is that small icons can be made to look better. And in fact the 32px and smaller icons are generated from special SVG files optimised for better lixel grid alignment of the shapes at those sizes. See the README in `contrib/icons` for details.

I agree that we should just ditch the SVG file from the Linux package and simply include PNGs up to 1024x1024 if that makes it pick up the bigger icons. I think this SVG business on Linux is misguided a bit... Reality check: macOS uses 1024px bitmap icons only for all app icons and they look great, including on high DPI.

If that's good enough for the best Unix GUI, it will be good enough for any Linux desktop 😎 

Really, we should only use the SVG files to generate the small icons from, but never ship it in the packages. Gnome HIG can stuff it 🤣

**Comment by johnnovak** [comment]
@weirddan455 If you wanna do this, add the 256, 512 and 1024px ones after this line (I think it's worthwhile to go up to 1024px, why not):
https://github.com/dosbox-staging/dosbox-staging/blob/main/contrib/icons/Makefile#L45

Then adjust the `install` target accordingly:
https://github.com/dosbox-staging/dosbox-staging/blob/main/contrib/icons/Makefile#L107-L108

That's it!

**Comment by johnnovak** [comment]
> But I don't know if `icotool` generates 16- and 256-color versions of Windows icons by default (in addition to "true color" icons).

We don't need those.

**Comment by Grounded0** [comment]
This is solely about Linux so lets keep it that way. Windows and macOS have been addressed already.

**Comment by johnnovak** [comment]
> > > But I don't know if `icotool` generates 16- and 256-color versions of Windows icons by default (in addition to "true color" icons).
> > 
> > 
> > We don't need those.
> 
> I see. (As I already understood, although this DOSBox application might not want 16- and 256-color icons, other cross-platform GUI applications might, which is why I suggested that option in a stand-alone icon generation solution, which I understand won't come sooner than the next release of this DOSBox application, if at all in the near future.)

I don't quite get what you're talking about here... This is the DOSBox project, we're dealing with DOSBox development here and not any other applications or "standalone icon generation solutions"...

**Comment by peteroupc** [comment]
> I don't quite get what you're talking about here... This is the DOSBox project, we're dealing with DOSBox development here and not any other applications or "standalone icon generation solutions"...

What I meant here is that (sometime after the release of the next DOSBox version) the solutions DOSBox just came up with to generate icons in the DOSBox application could be separated out into its own stand-alone project (e.g., a separate repository from this one), to reduce the work of developers of other cross-platform GUI applications in generating and supplying the necessary icons for their applications &mdash; all they would have to do is provide a single SVG or high-resolution PNG of their application icon.  But, as this GitHub issue is limited to Linux icons (and not also to icons in other operating systems), I will leave it at that.

**Comment by Grounded0** [comment]
Okay my desktop Linux expert came up with a better proposition:

Since we clearly don't know what the hell we are doing in this space lets steal from others who do:

[The VCMI Project](https://vcmi.eu) ships bitmap icons up to 2048x2048 AND the SVG so suggest going for a model of: 1024x1024 including intermediates AND the SVG shipping along with these bitmaps.

**Comment by Grounded0** [comment]
My point being that no harm is being done by including the SVG is we also provide bitmaps to large enough sizes. But since weirddan455 is working on this issue i'll let the person sort this out at fundamental level and not interfere.

**Comment by weirddan455** [comment]
#3179 is merged which should solve this issue for the most part.  If you re-run `meson install` you'll get higher res icons on Linux now (up to 1024X1024).  I left the SVG file in because it's not hurting anything (KDE prefers not to use it even if it's there).

The only thing other thing I can think to do on this issue is provide an easy way for users downloading the tarball off the website to get the icons and .desktop shortcut installed.  Currently they are in the tarball but they don't do much good unless the user manually copies them out.   I was thinking of writing a quick bash script that does what the meson installer does but only for the icons.  It would be optional if the user doesn't care about icons and shortcuts.

Probably most Linux users are going to get this from either a distro-specific package like [Fedora in the main repos](https://src.fedoraproject.org/rpms/dosbox-staging) or from something like [Arch's AUR](https://aur.archlinux.org/packages/dosbox-staging) or from [Flatpack](https://flathub.org/apps/io.github.dosbox-staging)

Yeah... packaging on Linux is a whole topic on its own.  But as the tarball is our official binary Linux distribution, we should probably do something to make icons work there.  Thoughts?

**Comment by Grounded0** [comment]
Closing as fixed.

@weirddan455 

How do you wish to reclaim your bounty? I can put the bounty on the project Open Collective too and you can sort that out later if you wish. You can also pass private payment details to me via @kcgen since we both use IRC.

**Comment by weirddan455** [comment]
Well I used to have Coinbase and Paypal accounts but I changed my phone number and can't get into them now :cry: 

I'll accept crypto though and figure out how to trade it later.  Been several years since I messed with Bitcoin.  Since the price has ballooned so much, is it still viable for a $100 transaction?  That's the only crypro I'm familiar with but I'll accept another if you have it on hand as long as its not too much of a hassle to trade for USD.

**Comment by johnnovak** [comment]
> Well I used to have Coinbase and Paypal accounts but I changed my phone number and can't get into them now 😢
> 
> I'll accept crypto though and figure out how to trade it later. Been several years since I messed with Bitcoin. Since the price has ballooned so much, is it still viable for a $100 transaction? That's the only crypro I'm familiar with but I'll accept another if you have it on hand as long as its not too much of a hassle to trade for USD.

Well... if you fix your PayPal account, I'm happy to transfer the money to your PayPal later. Man, how can you live without PayPal??? 😅

**Comment by Grounded0** [comment]
I think its the best for me to move the money on Open Collective and let you figure out how to transfer it to you from there. Its been earmarked to you after all so its all good. @johnnovak can probably act as an intermediary and SWIFT that money directly to your bank account. That's usually the most accessible and bullet proof way to move money since only a bank account is required.

**Comment by johnnovak** [comment]
> . @johnnovak can probably act as an intermediary and SWIFT that money directly to your bank account.

Sure thing.
