### ISSUE TITLE
Wrong aspect ratio in Jazz Jackrabbit

### ISSUE THREAD

**Issue by dreamer** [dosbox-staging/dosbox-staging#317]
User report:

> I tried DOSBox-staging 0.75.0-rc1 Windows build and noticed that Jazz Jackrabbit has a wrong aspect ratio when in game with a default DOSBox-staging config file. Jazz Jackrabbit has 320x200 resolution when in menu, but 320x199 when in game. It should be scaled to 4:3 aspect ratio all the time with non-square pixels because that was what it was designed for. Of course, using `output = texturepp` fixes it, but I think something is wrong when default settings don't just work.

Confirmed; I remember that bug, but it got lost as a side comment in a different issue.

This is definitely a bug; I expect, that custom resolution set by JJ will be treated the same way as 320x200.

I remember, that some artwork in JJ was designed with square pixels in mind (but not all!), but it's up to the user to decide if square pixels are desired or not - we should assure, that user setting is correctly respected.

**Comment by dreamer** [comment]
Hmm, the story might be more complicated here. It seems like JJ used both square pixels and non-square pixels (obviously - judging by the artwork), but the intention might've been to use non-standard resolution (320x199) to force CRT into displaying square pixels with black bars on top and bottom.

See this clip from [LGR channel video](https://www.youtube.com/watch?v=CaNDeyYP98A&t=1202s) (20:10 - 20:32).

I think we'll need to find a way to fix the dosbox behaviour to match the behaviour of real hardware, and allow users to override it force square pixels or force 4:3.

**Comment by kcgen** [comment]
This is quite a _rabbit hole_ (groan ;-) ) you can literally search google for "320x199" and the top hits all deal with Jazz Jackrabbit! 

Some in-depth coverage:
- Vogons: https://www.vogons.org/viewtopic.php?f=33&t=37821&hilit=320x199
- Pixel Musement: http://www.pixelships.com/adg/ep0150.html
- Nerdy Pleasures: http://nerdlypleasures.blogspot.com/2014/09/oddball-ega-and-vga-resolutions-when.html

Correct representation on real hardware (courtesy: https://twitter.com/dosnostalgic):

![EFl4jrlXUAAy24S](https://user-images.githubusercontent.com/1557255/80284732-106daa80-86d5-11ea-8566-8170580d4f77.jpeg)

Ripsaw [gets it working](https://www.vogons.org/viewtopic.php?p=336477#p336477) like this in DOSBox, but involves modifying the JAZZ.EXE as well as modifying using custom fork of DOSBox.

**Comment by Max833** [comment]
@dreamer How do I even enable pixel perfect mode? With DOSBox ECE I just have to start the program and that's it. Here... Seems like I have to change output to texturepp, but... this those nothing. Could you help me with this? Thank you.

**Comment by dreamer** [comment]
@Max833 `output = texturepp` work in here just fine? 
![Screenshot from 2020-05-06 12-24-03](https://user-images.githubusercontent.com/3967/81166890-94a51500-8f94-11ea-97d5-3cac7db552d2.png)

**Comment by Max833** [comment]
@dreamer: Thanks for your reply. Appreciate that. Hm, for me it doesn't look as sharp as DOSBox ECE. Strange.

Different topic: When windows mode is enabled, the DOSBox window is incridible small like the regular dosbox. Is there a way to scale this as well? DOSBox ECE does this (you have to click the picture).

DOSBox-staging:
![image](https://user-images.githubusercontent.com/53529402/81171601-eea9d880-8f9c-11ea-8c75-f48790cad649.png)

DOSBox ECE:
![image](https://user-images.githubusercontent.com/53529402/81172084-dc7c6a00-8f9d-11ea-85a2-800fbef1acf6.png)

**Comment by dreamer** [comment]
@Max833 I don't know what options you have selected - you can set `windowresolution=<specific-resolution>` to simulate what ECE is doing or even better - `windowresolution=resizable` and just resize the window (although it does not work with `texturepp` yet).

This issue is dedicated to fixing aspect ratio in JJ; if you need further help with tweaking configuration file, create a new issue, please :)

**Comment by Max833** [comment]
Okay, I will experiment a little bit. Thank you, dreamer! :)

**Comment by Burrito78** [comment]
At least with default config (can't speak for the output with texturepp), the current version 0.77.0 looks exactly like the LGR video. So this ticket can be closed, imho.

<img width="859" alt="Bildschirmfoto 2021-07-17 um 23 34 25" src="https://user-images.githubusercontent.com/61995128/126049916-af053dcf-ef8b-4bc8-95a5-bfcdec8b0dc4.png">
<img width="870" alt="Bildschirmfoto 2021-07-17 um 23 33 58" src="https://user-images.githubusercontent.com/61995128/126049921-10f5ed2e-bad2-4524-9044-9798f02cd81e.png">

**Comment by kcgen** [comment]
Confirmed on Linux as well; thanks for this check @Burrito78 !

**Comment by OpenRift412** [comment]
Okay so if I'm understanding this correctly, Jazz Jackrabbit is supposed to be in more or less 16:10 ratio with letterboxes on the top and bottom in 4:3?

**Comment by Burrito78** [comment]
Yes, that's right. See photo of CRT monitor above.

**Comment by OpenRift412** [comment]
> Yes, that's right. See photo of CRT monitor above.

I gotcha now. So for me it's filling the screen to 16:10 instead of maintaining the letterboxes. Is there a way to re-enable that?

**Comment by Burrito78** [comment]
Open a new Issue including current config and a screenshot or visit us on our discord for support please.
