### ISSUE TITLE
For GLSL shaders, can I use high resolution intermediate texture?

### ISSUE THREAD

**Issue by srhouyu** [dosbox-staging/dosbox-staging#3189]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### What Operating System are you using?

Windows 11

### Whats your question and how can we help?

Hello, I am trying to write a triad shadow mask shader. I'm not very good at GLSL. I find that the overall effect is not very good for 1080p resolution. 
1080p just has not enough pixels drawing the shadow mask for a 14 inch and 0.39mm dot pitch CRT. The dots are rough, and there is moire.
Is there a way to draw on a higher-resolution intermediate texture? So that I can draw the shadow mask better and then downscaling it to a normal screen.

This is a windowed screen under 1080p, 0.8mm dot pitch.

![screen](https://github.com/dosbox-staging/dosbox-staging/assets/20735968/6a854d14-926d-442f-9c27-b0cede202198)

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by johnnovak** [comment]
No, we don't support rendering at higher res then downsampling as a second pass. Also, 1080p is not enough for what you try to do. After downsampling, the dot mask pattern will disappear (it will be averaged out by the downsampling procesd). Check out the adaptive CRT shaders in the dev build; I'm faking the impression of the dot mask at 1080p, that's the best that can be done. 4K is not quite enough to emulate a VGA monitor's triad dot mask accurately, so... 😄
