### ISSUE TITLE
External GLSL Shaders don't seem to work...

### ISSUE THREAD

**Issue by OpenRift412** [dosbox-staging/dosbox-staging#321]
I tried using some GLSL shaders that are usually used for Retroarch, but the only results I've had thus far are either nothing happening or it just renders a black screen. I tried installing it using the multiple ways that the conf file suggested, to no avail.

**Comment by dreamer** [comment]
We do not support Retroarch shaders, but there's an open request for that #100 (it's already in our backlog).

dosbox-staging uses a specific format, which unfortunately means shaders need to be ported, you can test few shaders developed by @tyrells https://github.com/tyrells/dosbox-svn-shaders

To use it, create `glshaders` directory:

     (Windows) C:\Users\<username>\AppData\Local\DOSBox\glshaders\
     (Linux)   ~/.config/dosbox/glshaders/
     (macOS)   ~/Library/Preferences/DOSBox/glshaders/

Place `.glsl` file in there and edit .conf file, e.g.:
```
glshader = ScanLine.glsl
```
Please confirm if it worked :)

However, if you're using macOS, then we have a bug in RC1, that might prevent you from using it: #311

**Comment by tyrells** [comment]
@OpenRift412 there are some limitations to which shaders can be ported at the moment, due to DOSBox's current shader support - more details: https://github.com/dosbox-staging/dosbox-staging/issues/301#issuecomment-617352725 - but if there's a particular shader you're looking for, let me know and I can try and port it.

**Comment by dreamer** [comment]
I believe the question was answered. If there's something left to discuss, feel free to reopen or just continue discussion :)

**Comment by goloskokovic** [comment]
to port any RetroArch shader you need to modify main() function:

```
attribute vec4 a_position;

//gl_Position = MVPMatrix * VertexCoord;
gl_Position = a_position;
//TEX0.xy = TexCoord.xy;
TEX0 = vec2(a_position.x + 1.0, 1.0 - a_position.y) / 2.0 * InputSize / TextureSize;
```
