### ISSUE TITLE
Digitized sounds do not play in SimLife

### ISSUE THREAD

**Issue by kadaj29** [dosbox-staging/dosbox-staging#3212]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### What Operating System are you using?

Windows 10

### Have you checked that no other similar issue already exists?

* [x]  I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Digital sound will not play when running the game in Dosbox-Staging. The music plays fine, but the digital sound effects (easily heard when manually placing plants or animals, for instance) will not. The game's quick start guide mentions the following:
![sounds](https://github.com/dosbox-staging/dosbox-staging/assets/57066321/00dd9c5c-4ba3-47de-9dfc-3e26bd31f02d)
Changing the cputype and increasing cycles doesn't seem to make a difference. The game does not support Sound Blaster 16, but it is compatible with earlier Sound Blaster models. I've set the game up with Dosbox-X, and the digitized sounds work perfectly fine- the only configuration change I make is setting sbtype to sbpro2.

### Steps to reproduce the behaviour.
Explain how to reproduce

1. Configure sbtype to a model that the game supports, such as sbpro2 or earlier
2. Install and play the DOS version of the game and check if digital sound effects are working. The quickest and easiest way to check is to manually place animals or plants (the in-game tutorial explains how). There should be a sound effect every time you manually place one. 
3. Follow the above steps in Dosbox-X to hear the digital sound effects playing properly

### Download URL of affected game or software
 
_No response_

### Your configuration

```ini
https://gist.github.com/kadaj29/1a96b0de659816b00bf02f14624c1fbf
```

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by johnnovak** [comment]
Please fill out the whole issue template, incl. the config you're using, etc.

**Comment by Grounded0** [comment]
It's probably something we do wrong if it works in DOSBox-X.

**Comment by Grounded0** [comment]
I usually play SimLife with Roland MT-32 setting but tried the latest 1.04d version with Sound Blaster setting with `sbtype=sbpro2`and i can't get any digital audio to play.
