### ISSUE TITLE
How do I load the game?

### ISSUE THREAD

**Issue by DOOMMARINE117** [dosbox-staging/dosbox-staging#322]
i finally found the conf file. looks cool. 

how do i load the game in the automount? 

im assuming its:

Mount C C:\DOS\DOSBox\DOSGames
C:
cls
cd wolf3d
WOLF3D

thats what i have loaded it in. 

what about properties?

what should i add in the target line?

**Comment by kcgen** [comment]
Sorry @DOOMMARINE117, are you asking about how to create a batch file to launch your game?

**Comment by dreamer** [comment]
Different users have different ideas about what is the most effective way, here's the way I recommend:

Based on the paths you mentioned in the question:

1. Create a new text file `wolf3d.conf` in `C:\DOS\DOSBox\DOSGames\` (or where do you prefer)
2. Content of this file:
```
[cpu]
# different cycles values seem to work well for different people, depending on your hardware
# default cycles value does not work for many, many people in Wolfenstein 3D
cycles = max 50%

[autoexec]
mount C .
C:
cd WOLF3D
WOLF3D.EXE
exit
```
3. Create new Windows shortcut for Wolf3D, to run dosbox-staging `dosbox.exe` in working directory `C:\DOS\DOSBox\DOSGames\` with following parameter:
```
dosbox.exe -conf wolf3d.conf
```
4. This setup will *not* share any of settings with default .conf file (so you can experiment in there and it won't break wolf3d, and you can experiment in wolf3d.conf without breaking other games). If you *want* to share settings between games, use following commandline instead:
```
dosbox.exe -conf <path-to-shared-conf-file> -conf wolf3d.conf
```

There are other ways to approach this and organize .conf file exactly as you want - it's entirely up to you, depending on your usecase. There are some other complementary options to `-conf` (e.g. `-userconf` - you will need to look them up in manual file to learn all specifics).

**Comment by dreamer** [comment]
@DOOMMARINE117 if my answer was comprehensive enough, then close the issue, please :)

**Comment by DOOMMARINE117** [comment]
> 
> 
> @DOOMMARINE117 if my answer was comprehensive enough, then close the issue, please :)

sorry for the late reply. was taking a nap, lol. 

yeah, your answer helped. 

do i always need to put 50% next to max or no?

just to make sure i understood this. for the target line i should put: -conf C:DOS\DOSBox\DOSGames\WOLF3D.conf

**Comment by dreamer** [comment]
Well, that was a short nap ;)

> do i always need to put 50% next to max or no?

No, it's up to you - test various settings and see what works the best for you. Some users have no issues in Wolf3D with default value for this setting (`cycles = auto`), but I received complaints about it being too slow; many people get excellent results with fixed number (e.g. `cycles = 30000` or `cycles = fixed 30000`). If you'll use `max` without % (`cycles = max`) - it behaves like `cycles = max 100%` (this might result in faster battery drain if you play on a laptop).

My *personal, subjective,* preference for most games is `cycles = max 90%` (but Wolf3D is very light, so I feel 90% is an overkill).

You can also adjust CPU speed dynamically while in-game using CTRL-F11, CTRL-F12.

AFAIK no other options need to be touched for this game to work perfectly, other defaults are fine.

> just to make sure i understood this. for the target line i should put: -conf C:DOS\DOSBox\DOSGames\WOLF3D.conf

You can do that, but this will mean you need to change `mount` line to:
```
mount C C:\DOS\DOSBox\DOSGames\
```

I *think* the better way is to set Working Directory in shortcut file - it's "Start in:" field in shortcut properties; I don't run Windows ATM, so here's a random screenshot

![T10869F1](https://user-images.githubusercontent.com/3967/80319528-fb963180-8810-11ea-952d-71c49edf99c8.png)

So, in shortcut properties:
```
Target:    <path-to-dosbox-staging>\dosbox.exe -conf wolf3d.conf
Start in:  C:\DOS\DOSBox\DOSGames\
```
and use mount line: `mount C .`

**Comment by dreamer** [comment]
Ah, I think it's clear now :) closing the question.

**Comment by DOOMMARINE117** [comment]
you can add mount c in start in? interesting.
