### ISSUE TITLE
Improve the help text of the `LOADFIX` command

### ISSUE THREAD

**Issue by johnnovak** [dosbox-staging/dosbox-staging#3221]
The `LOADFIX` command accepts a bunch of options that are not documented in its help text. This should be improved.

See here:
https://www.dosbox.com/wiki/LOADFIX

![image](https://github.com/dosbox-staging/dosbox-staging/assets/698770/3b6f74b0-3d2c-4e40-b69d-3c347eb75d8d)

![image](https://github.com/dosbox-staging/dosbox-staging/assets/698770/fe082187-b39c-4b9f-a70c-d763ddd331d5)

**Comment by MasterO2** [comment]
https://www.dosbox.com/wiki/LOADFIX for Dosbox 0.74-3 mentions there is also a `-size` parameter:

For example: `loadfix -123` means **123 kB allocated** for the program in question.

**Comment by johnnovak** [comment]
Fixed by https://github.com/dosbox-staging/dosbox-staging/pull/3427
