### ISSUE TITLE
Improved, more configurable title bar

### ISSUE THREAD

**Issue by FeralChild64** [dosbox-staging/dosbox-staging#3226]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### What Operating System are you using?

None

### Is your feature request related to a problem? Please describe.

This is a follow-up of the discussions from the PRs: https://github.com/dosbox-staging/dosbox-staging/pull/3214 and https://github.com/dosbox-staging/dosbox-staging/pull/3223. To please everyone (or at least just about everyone), we need a configurable title bar message. Ideas so far (both mine and from the discussion):

- there should be a runtime-changeable config file option (like `title =`) to override the default _DOSBox Staging_ or  _DOSBox Staging (debug build)_ string in the title bar with something arbitrary, for example a game name
- similarly to debug build, we could mention that the build is an alpha
- DOSBox version information should be optionally displayed
- ability to display running program name should be brought back - but should be optional (disabled by default)
- ability to display program path and extension (configurable)
- displaying CPU cycles configuration in the title bar should be optional (enabled by default) - it might look strange and cryptic to an ordinary user who just runs a pre-configured emulator
- title bar should indicate if audio/video recording is in progress
- DOS program names containing box drawing or national characters should be provided to host OS using UTF-8 encoding

Work-in-progress code: https://github.com/dosbox-staging/dosbox-staging/tree/fc/titlebar-3

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by johnnovak** [comment]
Nice idea. We could have something called `window_titlebar` set to `auto` by default, or to some simple format string.

**Comment by Grounded0** [comment]
Just keep the old method available for the reasons pointed by @rderooy.

Windows 3.1x itself has 2 different operating modes: KRNL286 and KRNL386 protected modes and i need to know which one was picked due to operating factors.

**Comment by FeralChild64** [comment]
@Grounded0 The change to remove program name was just reverted. For 0.82.0 I intend to make it configurable.

**Comment by FeralChild64** [comment]
Draft implementation is ready in https://github.com/dosbox-staging/dosbox-staging/tree/fc/titlebar-3, not tested thoroughly yet (and there is a risk of regressions!).

Known problems:
- detection of alpha build not implemented yet
- changing any title bar setting at runtime causes the window to be destroyed and created again

**Comment by johnnovak** [comment]
Will test it later, but this is for 0.82.0, to be clear.

A couple of things that I'd like to see addressed:

- Option to put the version number and the git hash in the title bar (useful when testing and developing).
- Change the exe name in the title bar for our internal commands too.
- Interesting edge case: what about piped commands, e.g. TYPE followed by MORE. What then?
- At least an option to include the extension too  I always found jarring that I execute RUN.BAT and it shows RUN.
- Btw, I don't think @Grounded0 's example with batch files that execute commands now works (I guess it should to make this actually valuable).
- Current time, weather reports, scrollers, and a `fortune` command implementation that sends you cute messages periodically (ok, I'll show myself out... 😎 )

**Comment by FeralChild64** [comment]
> Option to put the version number and the git hash in the title bar (useful when testing and developing).

Version number - easy.
GIT hash - not so much. Definitely doable with GNU-environment builds, but I have no idea how to do it with Visual Studio build.

> Change the exe name in the title bar for our internal commands too.

Should be doable, I'll investigate.

> Interesting edge case: what about piped commands, e.g. TYPE followed by MORE. What then?

DOS is a single-tasking operating system. I suppose the currently executed command will be displayed - not sure, I'll try to test it.

> At least an option to include the extension too

Might be doable, I'll investigate.

> I don't think @Grounded0 's example with batch files that execute commands now works

Which example?

> Current time, weather reports, scrollers, animated emojis, and (...)

Blinking dot in `[⚫ REC]` mark (when audio/video is being recorded) is planned.

**Comment by johnnovak** [comment]
> but I have no idea how to do it with Visual Studio build.

No big deal if MSVC is not supported for this.

> I don't think @Grounded0 's example with batch files that execute commands now works

If you execute a batch file that runs various commands, will the name of the batch file be shown in the title bar, or the current command executed by the batch file? While the latter is more useful, not sure if that's the case (but maybe just because our internal commands don't show up in the title bar, and that confused me?)

> Blinking dot in [⚫ REC] mark (when audio/video is being captured) is planned.

I was joking about those things 😅 I guess that's kinda cool, so I'm not against it.

The OSD will display all such things, and do a better job (there's tons of things to potentially display, paused state, muted state, recording MIDI/video/audio, etc.—of course, all should be configurable not to spam the poor user Blinking dot in [⚫ REC] mark (when audio/video is being captured) is planned. 😅)

**Comment by FeralChild64** [comment]
> At least an option to include the extension too

Implemented. Can also display absolute path - configurable.
Unfortunately, the implementation is a little bit tricky (DOS only remembers name without path/extension) and starts working strangely once DOS prompt is opened and closed in Windows 3.11 :(

> Change the exe name in the title bar for our internal commands too

This one would probably be complicated, it would require digging into our `COMMAND.COM`. I don't really want to do this, at least for now.

> what about piped commands

Tested, currently executed one is reported.

> If you execute a batch file that runs various commands, will the name of the batch file be shown in the title bar, or the current command executed by the batch file?

The current command.

**Comment by FeralChild64** [comment]
Animated recording indicator added. Now, time to clean up all this code...
