### ISSUE TITLE
Upscaling shader regression in 0.81.0-alpha

### ISSUE THREAD

**Issue by pgzh** [dosbox-staging/dosbox-staging#3227]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Different version than latest?

0.81.0-alpha

### What Operating System are you using?

Linux x86_64

### If Other OS, please describe

Debian 12.4

### Relevant hardware info

Ryzen 7 Pro 5750G with integrated graphics

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Using a GLSL upscaling shader in 0.81.0-alpha does not work as expected, i.e. the scaler does not improve image quality.
In 0.80.1 the same shader improves image quality significantly.
My very uneducated guess is that in 0.80.1 the shader was passed the output image before dosbox-staging internal upscaling and in 0.81.0-alpha the shader is passed a already upscaled image and is therefore useless.

Maybe I missed a config option and misconfigured something?
If not, there should be a config option to select if the GLSL shader is passed the image before or after dosbox-staging internal upscaling to allow using upscaling shaders.

0.80.1:
![0 80 1](https://github.com/dosbox-staging/dosbox-staging/assets/38223870/a47de7d1-60eb-491e-aaea-6798a90f0ec9)

0.81.0-alpha:
![0 81 0-alpha](https://github.com/dosbox-staging/dosbox-staging/assets/38223870/80df1078-489b-4b6a-8a88-92ec7c18765b)

Configs and logs:
[configs_logs.zip](https://github.com/dosbox-staging/dosbox-staging/files/13697428/configs_logs.zip)

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Start any game in 0.80.1 with attached config
2. Start the same game in 0.81.0-alpha with attached config
3. Notice huge difference in image quality

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by johnnovak** [comment]
Thanks for your report @pgzh. This has been overlooked as I tend to forget those upscalers even exist 😊 Fortunately, the fix is only two lines of extra config per shader, so it's coming in a few hours.

**Comment by johnnovak** [comment]
Fix underway @pgzh...

**Comment by pgzh** [comment]
Thank you very much for taking care so quickly @johnnovak , but I'm afraid something should be done about this.

Your changes will fix the issue for the scalers included with dosbox-staging, but I am using an external shader that does not ship with the dosbox-staging release.

The comments in the config file say that an absolute path to a GLSL shader may be provided.
I could probably fix "my problem" by adding the two pragmas to my shader, but it wouldn't help anybody else.

IMHO there are at least the following two options that should be considered:

1. Modify the comments in the config and mention this in the wiki/manpage/documentation telling people what's going on and how to modify shaders.
This is probably the most error-prone way as it requires users to RTFM and edit stuff other than the config.

2. Add/extend config options:
When using a scaling shader integer scaling will effectively be disabled.
If we had a config option named 'scaling' with the options 'integer', 'shader' and 'off' (and possibly more I am overlooking now) this could be solved in the config file.
Maybe 'shader' wouldn't even be required if it was the same as 'off' or could be an alias for convenience.
Still somewhat error prone due to possible misconfiguration or not reading at least the comments in there, but what config option isn't?

I would very much prefer the second option.
I'm looking forward to read about your thoughts about this and if there is a better third option I haven't thought of.

**Comment by johnnovak** [comment]
@pgzh I can mention the pragmas in the release notes, good idea.

But that's the extent I'm willing to go about it. Messing around with custom shaders is an advanced topic and people need to know what they're doing. If the community is interested in such 3rd party shader packs, upscaler, whatnot, people are free to put together shader add-on packs for Staging with setup instructions, config snippets, and so on. We have provided the tools to make it happen, now it's in your hands 😄 This is out of scope for the core project, though.
