### ISSUE TITLE
James Bond 007 - The Stealth Affair (1990) (AKA Operation Stealth)

### ISSUE THREAD

**Issue by Python-Exoproject** [dosbox-staging/dosbox-staging#3244]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Different version than latest?

81.0a

### What Operating System are you using?

Windows 11

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

This game has screen flicker when run using EGA or VGA graphics. MCGA graphics do not seem to be affected. There is another Delphine software game (Future Wars) that has the same issue with VGA graphics (and again MCGA seems to be ok).

Of note is that all dosbox forks suffer from this flicker *Except* Daum, so it has some special sauce not yet in any other fork. @kcgen did some initial testing and ruled out the direct3d output and confirmed its something that is part of Daum itself

If this can be resolved there are a number of games that will benefit (@kcgen raised 'Corncob 3D' and 'Hostage' as some) and is probably one of the last things Daum can do better than Staging

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Use eXoDOS copy of James Bond 007 - The Stealth Affair
2. Choose the EGA option from the choice menu
3. Under Daum as per current eXoDOS launch there is no flickering. Under Staging you can see the flickering from the first screen, around the 'OK' button.

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by johnnovak** [comment]
From dosbox.com:
https://www.dosbox.com/comp_list.php?showID=191&letter=F

> Flickering is caused by picking 'VGA' from the installation menu. Pick MCGA and the game will run fine without odd clipping problems or flickering.

Same comment in random Vogons threads.

Tried with DOSBox X, it has the same flicker issue just like you said @Python-Exoproject. Don't keep your hopes up, if neither the original team nor Jon figured this out, I don't think we know where to even start looking 😅 Video emulation is THE most complicated and most underdocumented part of the codebase, bar none... Even with the Daum sources, this is a bit of a finding a needle in a haystack situation.

**Comment by kcgen** [comment]
Excellent reproduction, @johnnovak !

I can definitely see that flickering and judder/ghosting, similar to how the Xeen mouse works. 

This is really nice to see that DOSBox's S3 implementation matches the hardware, right down to these corner case behaviors.

**Comment by johnnovak** [comment]
Closing as Staging emulates the S3 behaviour correctly. It's unclear why there is no flickering in Daum.

**Comment by Python-Exoproject** [comment]
I have found a way to remove the flickering when using Staging by using the dos_rate= setting.

As exodos needs to be compatible on multiple users systems can someone confirm that using auto cycles and dos_rate=140 fixes the issue for them as well? If it does, are there any side effects to using dos_rate that I should be aware of?

I wonder if the magic sauce that Daum has to make these games flicker free is related to what dos_rate does

**Comment by johnnovak** [comment]
@Python-Exoproject 
It is possible to completely get rid of the flicker with the new `vmem_delay` option.

See the details and the config to fix the game here: https://github.com/dosbox-staging/dosbox-staging/pull/3597

**Comment by johnnovak** [comment]
@Python-Exoproject 
It is possible to completely get rid of the flicker with the new `vmem_delay` option.

See the details and the config to fix the game here: https://github.com/dosbox-staging/dosbox-staging/pull/3597
