### ISSUE TITLE
Microsoft Space Simulator (1994)

### ISSUE THREAD

**Issue by Python-Exoproject** [dosbox-staging/dosbox-staging#3248]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Different version than latest?

81.0a

### What Operating System are you using?

Windows 11

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

This game seems to suffer from two other issues that still haunt Staging and most other Dosbox forks.

1. Its a flickering mess from the moment you are in the cockpit. As per #3244, #2905 & #2950 the copy of Daum included in eXoDOS fixes it.
2. There is a speed issue as per #2751. At around 50k you can move around fine (maybe even a bit slowly) while the Earth is in view. The second Earth is of screen you flick around in the blink of an eye to have the Earth back on screen

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Play the game in Staging 81.0a
2.
3.

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by Python-Exoproject** [comment]
Ok looks like this might be a completely unrelated flickering issue to the ones I linked above. One of our team members discovered that while the other games I listed flicker in Staging 80.1, this game does not. So this specific games flickering might be a regression instead of whatever is going on with Daum and those other games

**Comment by Grounded0** [comment]
Can confirm regression from 0.80.1.

Since this is probably based on Microsoft Flight Simulator 5.x engine and i had a regression there with 0.81 this could be useful:

Connected issues and PRs:

- #2864
