### ISSUE TITLE
sound problems for wolfenstein 3d.

### ISSUE THREAD

**Issue by DOOMMARINE117** [dosbox-staging/dosbox-staging#325]
when i play wolf3d or monster bash. i notice the sound issues appears. it skips especially during the intro.
overall very playable. 
can you fix those in the next update?
is there xbox one controller support?
great job on the source port. i like it:) much better than the original dosbox.

**Comment by mitigd** [comment]
Hopefully I'm not out of bounds in trying to help here but from what I know of Dosbox, it can be very finicky when it comes to the speed at which you run certain games.

Recently I beat one of my favorite DOS era games 'The Riddle of Master Lu', which when run normally (without touching conf files) the speech skips ridiculously. Only when setting the 'cycles' option in your 'dosbox.conf' file to a setting that is tailored for your PC, will that game run properly. For example, on my PC I used 'cycles=max 25%' and that pretty much solved all of the audio issues I was getting. 

Try and play around with that and hopefully that'll solve your sound issues.

Note: If you have a considerably fast computer you'll want to drop that percentage even lower.

**Comment by kcgen** [comment]
thanks @mitigd ; mich the opposite! This is a community effort: the more we all can  contribute, the better it gets for everyone. :+1:

**Comment by dreamer** [comment]
@DOOMMARINE117 Try with following settings in your .conf file:
```
[mixer]
nosound = false
rate = 44100
blocksize = 4096
prebuffer = 30
```
no guarantee it'll work, but these settings work for me ;). I believed `cpu` was the only thing I had changed in my .conf for this game, but I was wrong.

**Comment by DOOMMARINE117** [comment]
> 
> 
> Hopefully I'm not out of bounds in trying to help here but from what I know of Dosbox, it can be very finicky when it comes to the speed at which you run certain games.
> 
> Recently I beat one of my favorite DOS era games 'The Riddle of Master Lu', which when run normally (without touching conf files) the speech skips ridiculously. Only when setting the 'cycles' option in your 'dosbox.conf' file to a setting that is tailored for your PC, will that game run properly. For example, on my PC I used 'cycles=max 25%' and that pretty much solved all of the audio issues I was getting.
> 
> Try and play around with that and hopefully that'll solve your sound issues.
> 
> Note: If you have a considerably fast computer you'll want to drop that percentage even lower.

cool. i give it a shot and see how it runs. i try wolf3d first and then monster bash and then doom.

**Comment by DOOMMARINE117** [comment]
okay that idea works. is 5000 blocks ok for wolf3d, doom and monster bash type games?

**Comment by dreamer** [comment]
@DOOMMARINE117 5000 is not a valid value for blocksize; see comments in `dosbox-staging.conf` file for details. Each of these games use different engine, so most likely different tweaks are needed.

For games on DOOM engine, I use:
```
[mixer]
nosound = false
rate = 22050
blocksize = 2048
prebuffer = 10
```
These are values picked by the game publisher (copied from DOOM 2 released on Steam) and they work perfectly (for me - I inject them automatically into dosbox-staging via [Boxtron](https://github.com/dreamer/boxtron)), but maybe different values will work better for you.

In my experience, DOS games on GOG and Steam usually come with ok-ish .conf files. I recommend starting with dosbox-staging defaults (they should work for most games), and tweak only if the game have sound problems :)

**Comment by DOOMMARINE117** [comment]
> 
> 
> @DOOMMARINE117 5000 is not a valid value for blocksize; see comments in `dosbox-staging.conf` file for details. Each of these games use different engine, so most likely different tweaks are needed.
> 
> For games on DOOM engine, I use:
> 
> ```
> [mixer]
> nosound = false
> rate = 22050
> blocksize = 2048
> prebuffer = 10
> ```
> 
> These are values picked by the game publisher (copied from DOOM 2 released on Steam) and they work perfectly (for me - I inject them automatically into dosbox-staging via [Boxtron](https://github.com/dreamer/boxtron)), but maybe different values will work better for you.
> 
> In my experience, DOS games on GOG and Steam usually come with ok-ish .conf files. I recommend starting with dosbox-staging defaults (they should work for most games), and tweak only if the game have sound problems :)

gotcha, makes sense. so sounds 4094 is the limit. cool. 

im assuming prebuffer is limit to 10 to 30?

what about rate? whats the highest it can go too?

**Comment by DOOMMARINE117** [comment]
im still playing around with it. still cant get the voices.

**Comment by dreamer** [comment]
@DOOMMARINE117 we greatly appreciate you putting the software through the wringer and testing it, but we need some actionable feedback about what exactly does not work ;)

We will greatly appreciate one bug report per game - this way it's easier for us to track discussions, and for future users to find solutions to their problems :)

Maybe let's rename this issue to "Sound problem in Wolfenstein 3D" (which I presume could be closed now), and create new bug reports for other games?

**Comment by DOOMMARINE117** [comment]
> 
> 
> @DOOMMARINE117 we greatly appreciate you putting the software through the wringer and testing it, but we need some actionable feedback about what exactly does not work ;)
> 
> We will greatly appreciate one bug report per game - this way it's easier for us to track discussions, and for future users to find solutions to their problems :)
> 
> Maybe let's rename this issue to "Sound problem in Wolfenstein 3D" (which I presume could be closed now), and create new bug reports for other games?

sure i can do that for now on.
