### ISSUE TITLE
Vertical space not fully utilized by default

### ISSUE THREAD

**Issue by Torinde** [dosbox-staging/dosbox-staging#3255]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Different version than latest?

dosbox-staging-windows-msys2-x86_64-v0.81.0-alpha-2248-g91e65

### What Operating System are you using?

Windows 10

### Whats your question and how can we help?

Without modifying anything in .conf - vertical space is not fully utilized:
![image](https://github.com/dosbox-staging/dosbox-staging/assets/97228894/f1efac33-f2c9-428d-be04-bf2a8bbf0113)
DISPLAY: VGA 720x400 16-colour text mode 03h at 70.087 Hz throttled VFR, scaled to 1067x800 pixels with 1:1.35 (20:27) pixel aspect ratio

Also, even in full screen the there are sizable black areas on top and bottom. On a screen with height 1440 pixels I get "DISPLAY: VGA 720x400 16-colour text mode 03h at 70.087 Hz throttled VFR, scaled to 1600x1200 pixels with 1:1.35 (20:27) pixel aspect ratio"

I'm not yet familiar with all the scaling/viewport/etc. settings, so maybe I miss some setting, but shouldn't the default be "occupy all vertical space available"?

When using a smaller window - all vertical space is utilized:
![image](https://github.com/dosbox-staging/dosbox-staging/assets/97228894/c4a4ee29-517e-435b-a7a7-db0ea9eb0875)
DISPLAY: VGA 720x400 16-colour text mode 03h at 70.087 Hz throttled VFR, scaled to 533x400 pixels with 1:1.35 (20:27) pixel aspect ratio

Mapper occupies the whole space. Both in window and fullscreen. But I can't switch with Alt+Enter while the Mapper is visible.

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by weirddan455** [comment]
This is intentional but can be configured to use all available space by setting `integer_scaling = off`.  Integer scaling is defaulted to on when using the CRT shaders (also default enabled) so disabling the integer scaling may make the shaders look a bit off.

**Comment by johnnovak** [comment]
@Torinde what @weirddan455 said is accurate.

I recommend to read my Getting Started guide, it's not just for beginners 😏 
https://dosbox-staging.github.io/getting-started/introduction/

Specifically, the last "Advanced graphics options" chapter answers all your questions.. and then some 😎 
https://dosbox-staging.github.io/getting-started/advanced-graphics-options/

**Comment by johnnovak** [comment]
> It seems strange _not_ to fill the vertical space _while_ using CRT shaders, but probably I missed/forgot where it was discussed.

I sent you links to the guide that explains it, so please read it 😄

**Comment by Torinde** [comment]
What I would like is to have integer scaling and shader while NOT having empty space.

Is it possible to do all the rendering off-screen and as last step to crop the output only to the relevant part in the middle, so that the borders of the window match the borders of the actual content?
As in red here:

<img width="1457" height="1121" alt="Image" src="https://github.com/user-attachments/assets/27720be7-0600-40b1-af61-ea783daa6100" />

**Comment by weirddan455** [comment]
I don't know what the hell you're talking about @Torinde

Offscreen rendering would not solve anything. Set `window_size` to be an integer multiple of the DOS resolution of the game you're playing.

**Comment by johnnovak** [comment]
We don't have a feature to resize the window dynamically to the actual content area. Especially with integer scaling, that would be a nightmare in games that switch resolutions; the window size would be potentially jumping back and forth between different sizes.

We will not implement such a feature, I'm strongly against it. It conflicts with current features, and will conflict with many other features I'm planning. Won't happen.

Your options:

- Set window size explicitly
- Turn off integer scaling
- Buy a 4K monitor and you'll have a lot more flexibility with content scaling (integer scaling off will become a much more viable option)

I'm gonna experiment with supersampling at some point (render at 2x/3x/4x the integer scaled height, then scale it back to the viewport height). That's basically how macOS does high DPI scaling, it's a form of brute force antialiasing. That might reduce the non-integer-scaling artifacts while filling the viewport vertically, but it's not a magic bullet.
