### ISSUE TITLE
Add Lua support to the DosBox debugger, to allow for more complex debugging actions and analysis of running programs

### ISSUE THREAD

**Issue by naerbnic** [dosbox-staging/dosbox-staging#3257]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### What Operating System are you using?

Other

### If Other OS, please describe

Windows, Mac OS

### Is your feature request related to a problem? Please describe.

Just in relation to some nice-to-haves I found when trying to reverse engineer a program.

There are times that I wanted to follow data structures farther into memory at different points in the code when the debugger was running. This includes looking at pointer values at the entry point to functions (e.g. what is the C-string available in a particular segment:offset realptr pair), or possibly following the pointers further into memory from an intermediate struct. At one point, I wanted to validate a linked-list in memory, but doing that by hand would have been at least tricky.

### Describe the solution you'd like

I'd like to add a Lua interpreter to the debugger command line interface, including the ability to load external scripts, where different lua functions can be called directly from the debugger command line, or in response to hitting certain breakpoints. As an example of the latter, take a breakpoint that should only break when a certain value is seen at a particular position in memory.

The interface could vary, but simplest would be to use the existing command parser, with at least a new command (for bikeshedding purposes, something like "LUA") that will run the remainder of the command line as a Lua function in the current lua context. This context would include functions that allows the context to get current register values, read the running program memory, modify breakpoints, and set up callbacks in response to breakpoints, and print to the debugger console. There would also be a command to load a script from the filesystem, similar to how debug vars can be loaded (e.g. "LUALOAD <filename>"). At least for starters, this Lua context would have no access to any external resources directly (e.g. the filesystem, program console, etc.)  to prevent additional security issues by running unexpected scripts.

Looking at the existing build system, it appears that the Lua library is available both through vcpkg and through meson's WrapDB. Adding it as a dependency seems to be simple.

For the record, I'm willing to make an attempt at this feature to start with.

### Describe alternatives you've considered

One alternative is to create our own scripting language, but as can be imagined that is a non-trivial task. We could do simple things to extend the debugger, and create expressions whose values can be printed more easily, but the benefits would be minimal.

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by johnnovak** [comment]
Very nice idea @naerbnic and I fully support this! 🎉 

> At least for starters, this Lua context would have no access to any external resources directly (e.g. the filesystem, program console, etc.) to prevent additional security issues by running unexpected scripts.

It's good to start small and with a minimal set of features, but frankly, I don't think security is a concern here. Normal users won't be running Lua scripts on their machines anyway. It would be handy if the script had access to the host filesystem, that way you could create automated memory dumps on certain conditions, maybe build up tables in memory and write them to CSV files then hitting a manual or automatic trigger—the possibilities are endless!

> One alternative is to create our own scripting language, but as can be imagined that is a non-trivial task. We could do simple things to extend the debugger, and create expressions whose values can be printed more easily, but the benefits would be minimal.

Yeah, Lua is probably the sweet spot for this kind of stuff and the number one choice. There's also the benefit of not having to learn a different custom language; Lua is pretty standard for extending functionality in performance-intensive apps. I see no benefits from writing a custom language, but only drawbacks, and quite serious ones.

**Comment by grannypron** [comment]
I was also thinking of a project where this would come in handy.

Somebody tried to add Python support a whiiiile back:
https://github.com/stt/dosbox-python

**Comment by johnnovak** [comment]
Closing as @naerbnic has disappeared into the ether 😎

**Comment by Player1UK** [comment]
Before I begin looking into this, is there a preference between LUA or Python?

**Comment by johnnovak** [comment]
> Before I begin looking into this, is there a preference between LUA or Python?

I would definitely prefer Lua. That's much better for embedding and more lightweight.

**Comment by Player1UK** [comment]
> > Before I begin looking into this, is there a preference between LUA or Python?
> 
> I would definitely prefer Lua. That's much better for embedding and more lightweight.

Gotcha.  With Python I was thinking of using and calling out to an external version, whereas LUA can be built-in.
So LUA as the default it is.
Once that's finished I can also look at allowing other external scripting to be called, by exposing access to the debugger.

I'll have to check, but I get the feeling DOSBox already exposes access to several things already (by default), seeing as there's an IDA plugin for viewing an active DOSBox session.

**Comment by Player1UK** [comment]
Any particular branch best to work on this using?
Or create a new one specifically for the debugger?

**Comment by johnnovak** [comment]
> Gotcha. With Python I was thinking of using and calling out to an external version, whereas LUA can be built-in.
> So LUA as the default it is.

Yeah, I like to keep things simple, so a built-in Lua interpreter is the way to go IMO. Then we're 100% self-contained; no extra external environment/tooling is necessary (at least for the most common default use case).

> Once that's finished I can also look at allowing other external scripting to be called, by exposing access to the debugger.
> I'll have to check, but I get the feeling DOSBox already exposes access to several things already (by default), seeing as there's an IDA plugin for viewing an active DOSBox session.

It doesn't. I've just checked, [idados](https://github.com/wjp/idados?tab=readme-ov-file) uses a [custom-hacked fork of original DOSBox](https://github.com/wjp/dosbox).  It communicates with the debugger through sockets, see [here](https://github.com/wjp/dosbox/blob/idados/src/debug/server.cpp).

It's good to plan a little bit ahead, but I highly recommend to start small, and build this up progressively. Also note that we have gained a simple HTTP API not so long ago:

https://github.com/dosbox-staging/dosbox-staging/pull/4730

This change already provides some rudimentary functionality that can be used to interface with external debuggers and reverse engineering/hacking tools. Your work should take this into account and modify/generalise it, not build a completely parallel implementation. Just some quick thoughts how I see a potential evolution of this:

1. Add Lua scripting support to the debugger (built-in Lua only, no external control)
2. Think about whether we need another transport than the HTTP REST API. Maybe we don't. But if we do (e.g., to achieve lower latency), we could implement messages through raw TCP/IP sockets, or maybe we could adopt the open [DAP protocol](https://code.visualstudio.com/blogs/2018/08/07/debug-adapter-protocol-website)
3. Come up with a design that allows remote control of the debugger via potentially different transports. I.e. we have the commands at the lowest layers, these can be invoked either by the built-in Lua scripting, the HTTP REST API (JSON payloads), or the raw TCP/IP socket based transport (maybe via DAP).

Of course, you don't _have_ to do all this 😄 I'm just spitballing ideas and pointing out that some design/vision/goal would be needed to do all this cleanly, taking the existing HTTP API into account. And I said, one step at a time, and the first step is definitely the built-in Lua stuff 😄 

Also very important: whatever you can up _must_ be 100% cross platform across Windows, macOS, and Linux.

> Any particular branch best to work on this using? Or create a new one specifically for the debugger?

How we work is we create a branch for "new feature X", work on that branch until it's ready to be merged, then we raise a PR. We prefix branches by our initials, e.g. I use `jn/my-awesome-feature`.

I image you would raise the first PR when you have some rudimentary support in for the Lua stuff, then can progressively enhance it with subsequent PRs. We want to avoid "big bang" merges as much as possible—start small, get it in, iterate on it, GOTO 10 😎 

Also, please make sure to read out [contributors guide](https://github.com/dosbox-staging/dosbox-staging/blob/main/docs/CONTRIBUTING.md) carefully in its entirety if you haven't already done so.

Looking forward to your work! Exciting times 😎 🚀
