### ISSUE TITLE
shell history not to record duplicative consecutive commands

### ISSUE THREAD

**Issue by Torinde** [dosbox-staging/dosbox-staging#3259]
> . another shell history improvement is not to record the same command twice after each other, e.g. if new entry is the same as previous - don't add it - not sure how common this scenario is, usually people enter different commands, but while testing I was entering the same...

One ticket, one issue. You know what to do 😏

_Originally posted by @johnnovak in https://github.com/dosbox-staging/dosbox-staging/issues/3235#issuecomment-1868380162_

**Comment by weirddan455** [comment]
This would probably be easy enough to change.  The question would be if we want this behavior.

As far as I know, most terminals will save duplicate commands in their history.  Tested on my system with KDE Console + Bash.  If you enter the same command multiple times, you'll have to hit the up arrow that many times to get past it.

That doesn't mean we have to follow Linux terminal conventions.  Just an observation.  I'll wait for the rest of the dev team to weigh in.  I don't really have a strong opinion either way.

**Comment by FeralChild64** [comment]
I have checked that Windows 11 behaves this way. Since:

1. It is an official continuation of MS-DOS
2. Its is probably the most popular host OS among our users

I would vote to follow Windows 11 behavior.

**Comment by weirddan455** [comment]
Which way @FeralChild64 ?  With duplicate commands left in or removed?

**Comment by johnnovak** [comment]
I guess there are different schools of thought to shell history. If it's a "record" of the sequence of commands that were executed, in exact order, you need to store dupes.

But I'd say that's less useful. Really, how I treat it is a "repository" of past commands so I can easily re-execute them without typing. So I have deduping turned in zsh. Plus 95% of the time I don't even use the arrow keys, I just do Ctrl+R search.

So personally I'm for not storing consecutive dupes, I don't see why that's desirable.

**Comment by kcgen** [comment]
> So personally I'm for not storing consecutive dupes, I don't see why that's desirable.

In my Bash shell, I also have it set to avoid dupes. I don't want to be hitting the 'up' arrow repeatedly past a wall of dupes (say, like compiling Staging commands).

(in bash: `export HISTCONTROL=ignoredups`)

**Comment by johnnovak** [comment]
I think we can conclude removing the dupes is the most useful thing to do. We want to keep the number of config options down, so I don't think this should have it's own config option.

**Comment by FeralChild64** [comment]
> Which way @FeralChild64 ? With duplicate commands left in or removed?

I’m not sure if I understand the question correctly - if you execute exactly the same command several times, one after another - only one command will be remembered in a history.
