### ISSUE TITLE
Would make sense to also port Dosbox Staging to Emscripten?

### ISSUE THREAD

**Issue by LowLevelMahn** [dosbox-staging/dosbox-staging#3264]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### What Operating System are you using?

None

### Whats your question and how can we help?

like https://github.com/dreamlayers/em-dosbox which is used (if im correct) on archive.org 

or is Emscripten too much of a burden?

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by johnnovak** [comment]
No 😎 At least not part of what we're doing here as we have enough on our plate. I can see this kinda of thing as spin-off project, maintained by a different team.
