### ISSUE TITLE
rect tests failing in `buildtype=plain`

### ISSUE THREAD

**Issue by signed-log** [dosbox-staging/dosbox-staging#3273]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Different version than latest?

0.81.0-rc1

### What Operating System are you using?

Linux x86_64

### If Other OS, please describe

openSUSE Tumbleweed

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

When building with meson setup with [`--buildtype=plain`](https://sourceforge.net/p/meson/wiki/Quick%20guide/), the test suite fails with all the tests configured as `EXPECT_DEATH` failing

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Setup meson with `meson setup --buildtype=plain . test-death`
2. Compile `meson compile -C test-death`
3. Run test suite `meson test -C test-death --print-errorlogs`

See that all rect tests with `EXPECT_DEATH` are failing

### Provide a Log

```text
[Test log](https://paste.opensuse.org/pastes/fa183b9c48a5)
```

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by johnnovak** [comment]
@signed-log Looks like Gtest death tests are not compatible with your particular Linux environment. They run fine on all our CI Linux jobs and no one from the team on Linux has complained yet either.

Death tests muck around with subprocesses and stuff, it's a bit murky but I never had problems with them on macOS and Windows. Maybe read the relevant doco section and if you can up with and adjustment/workaround to make them work on your Linux env too, we might consider merging your changes:

https://google.github.io/googletest/reference/assertions.html#death

**Comment by signed-log** [comment]
@johnnovak 

They run and succeed fine on `--buildtype=debug`, so the issue is not from the environment

I discussed with @kcgen on the Discord, and what came out of that, is that those will only run on `--buildtype=debug`

`--buildtype=plain` is a specific meson argument to allow custom CFLAGS/LDFLAGS... and other commands passing to gcc (useful when doing packaging)

Using `--buildtype=plain` does enable the debug test suite by default, which a normal build does not.

However, it is not a debug build, so it doesn't build the debug executable needed for those tests to actually run.

@kcgen proposed a solution that would make those tests only run on debug build

```diff
- EXPECT_DEATH(test(), "");
+ EXPECT_DEBUG_DEATH(test(), "");
```

in tests/rect_tests.cpp

This solves my issue after patching

**Comment by johnnovak** [comment]
> @johnnovak
> 
> They run and succeed fine on `--buildtype=debug`, so the issue is not from the environment
> 
> I discussed with @kcgen on the Discord, and what came out of that, is that those will only run on `--buildtype=debug`
> 
> `--buildtype=plain` is a specific meson argument to allow custom CFLAGS/LDFLAGS... and other arguments to the compiler (useful when doing packaging)
> 
> Using `--buildtype=plain` does enable the debug test suite by default, which a normal build does not.
> 
> However, it is not a debug build, so it doesn't build the debug executable needed for those tests to actually run.
> 
> @kcgen proposed a solution that would make those tests only run on debug build
> 
> ```diff
> - EXPECT_DEATH(test(), "");
> + EXPECT_DEBUG_DEATH(test(), "");
> ```
> 
> in tests/rect_tests.cpp
> 
> This solves my issue after patching

Thanks for the explanation @signed-log, wasn't aware of that detail. Yes, I'd say it's fine if these tests only run in debug mode, that's an acceptable compromise. I saw on Discord you're gonna raise a PR for this, looking forward to it.

**Comment by kcgen** [comment]
Thanks for this @signed-log.

Yup, the Rect unit test exercises illegal values that expected death of the executable  (full exit out to the shell), which is all a good thing. 

The nuance is the _death_ comes from hitting asserts in the code, which only exist in debug builds. So the expected_debug_death is a the right fit for these unit tests. 

If our code always terminated (regardless of build type) such as using E_Exit, an  unhandled throw, or a return from main(), then we could keep using the existing expect_death gtest check.

**Comment by johnnovak** [comment]
> The nuance is that _death_, in these specific tests, comes from hitting asserts in the Rect code, which only exist in debug builds. So the expected_debug_death is a the right fit for these unit tests.

Actually, you're correct, so not running those tests in release builds is not even a compromise. I wrote those tests but forgot about that nuance 😄 So nothing to do with the Linux env.
