### ISSUE TITLE
Megarace 2 Does Not Start at All and Hangs at Startup

### ISSUE THREAD

**Issue by MasterO2** [dosbox-staging/dosbox-staging#3294]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Different version than latest?

Version 0.81.0-rc1

### What Operating System are you using?

Windows 10

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Windows 10, 64-Bit
https://github.com/dosbox-staging/dosbox-staging/releases/download/v0.81.0-rc1/dosbox-staging-windows-msys2-x86_64-v0.81.0-rc1.zip

In 0.81 RC, 64-bit, if you try to run **Megarace 2** at all, the game simply hangs,  goes no further, and shows no error messages at the Dosbox-Staging command prompt.  Additionally, no error messages are shown in the Dosbox Status Window.

This bug occurs with or without `-noprimaryconf` being specified. 

https://github.com/dosbox-staging/dosbox-staging/issues/2519 and https://github.com/dosbox-staging/dosbox-staging/commit/0ce4ff7e29ba53308ce231718d516dec41319ed3 were supposed to fix Megarace 2 not properly playing the game's music.  However, now the game **does not start at all** in Dosbox-Staging version 0.81.0-rc1, but simply hangs if you try to run it.

I had the same issue in 0.80.1 as user Geist22 did in https://github.com/dosbox-staging/dosbox-staging/issues/2519 where the game will run, but it crashes back to DOS prompt.

### Steps to reproduce the behaviour.

Steps to reproduce:

1. Use [Inno-Extract](https://constexpr.org/innoextract/#download) on the GOG Megarace 2 Offline Installer to extract the game folder.

2. In Dosbox-Staging, mount the newly created `app` folder produced by Inno-Extract as your C drive.

3. Next in Dosbox-Staging, imgmount `MEGARACE2.GOG` as a CD-ROM / ISO to your D drive to satisfy the CDROM check on game startup.

4. After `MEGARACE2.GOG` is successfully imgmounted as your D drive, run `MEGARACE.EXE` itself in the game folder. 

The game will simply hang, go no further, and show no error messages at the Dosbox-Staging command prompt. Additionally, no error messages are shown in the Dosbox Status Window.

### Download URL of affected game or software

https://www.gog.com/en/game/megarace_1_2

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by johnnovak** [comment]
To clarify, does the game run with 0.80.1? You kinda implied that, but I need a statement that you can run it with the exact same setup on 0.80.1 😄

**Comment by MasterO2** [comment]
> @MasterO2 To clarify, does the game run with 0.80.1? You kinda implied that, but I need a statement that you can run it with the _exact same setup_ on 0.80.1 😄

I had the same issue in 0.80.1 as user Geist22 did in https://github.com/dosbox-staging/dosbox-staging/issues/2519 where the game will run, but it crashes back to DOS prompt.

**Comment by kcgen** [comment]
Bisected to `v0.81.0-rc1~247`

```
Author: @weirddan455 
Date:   Thu Nov 30 23:07:39 2023 -0600

    Fix MSCDEX regression in game "Fascination (1991)"

    Regression from commit c4a6c7db9abe3ebf84953744794b4b82266732e9

    Fixed a bug when traversing the DOS device linked list.
    The last valid device is one before the end pointer.
```

7a9384244b67a1f0404496064c483642ac4245e5 (games runs in the prior commit):

```

@weirddan455, the prior related fix, `v0.81.0-rc1~247` is good and the game works! 

Zipping a repro pack using original ISOs.

**Comment by weirddan455** [comment]
PR #3163 is where I made this commit.  I'm taking a look.

**Comment by MasterO2** [comment]
I also request that @Grounded0 add the **Lance Boyle** tag. [/joking]

**Comment by Grounded0** [comment]
![image](https://github.com/dosbox-staging/dosbox-staging/assets/48192273/edb15ddb-675f-4770-8cb9-904c7abb555f)
