### ISSUE TITLE
DOSBox-staging 0.81 RC1 adaptive CRT shaders are not working on Intel Core i5-4300U (Haswell)

### ISSUE THREAD

**Issue by MonkeyPilot** [dosbox-staging/dosbox-staging#3308]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Different version than latest?

0.81 RC1

### What Operating System are you using?

Windows 10 x64 (build 1909)

### Relevant hardware info

CPU Intel Core i5-4300U (Haswell) with iGP HD 4400 (OpenGL 4.3 / Shaders 5.0 / DirectX 11.1)
Driver v20.19.15.5144

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Errors appear on startup, and no built-in shaders work.

shader "**crt-auto**"
`OPENGL: Shader info log: WARNING: 1:29: '' :  #version directive missing`

shader "**sharp**"
`OPENGL: Shader info log: WARNING: 1:26: '' :  #version directive missing`

External shaders are working.

### Your configuration

```ini
Default config, without changes (it is created at startup by the program itself).
```

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by johnnovak** [comment]
@MonkeyPilot I'll need your help with troubleshooting this as I don't have access to that particular GPU.

### Test 1

Open `$DOSBOX_ROOT/resources/glshader/interpolation/sharp.glsl` in a text editor, and paste `#version 120` in as the very first line before everything else. The result should look like this:

```glsl
#version 120

/*
 *  SPDX-License-Identifier: GPL-2.0-or-later
 *
 *  Copyright (C) 2020  The DOSBox Team
```

Start Staging with `dosbox --set glshader=sharp` to test (or set `glshader = sharp`) in your config.

If it still doesn't work, upload the _full logs_ as [GitHub Gist](https://gist.github.com/) please and share the link.

### Test 2

Start Staging with `dosbox --set glshader=crt/vga-4k` to test (or set `glshader = crt/vga-4k`) in your config (without making any changes to that shader).

If it still doesn't work, upload the _full logs_ as [GitHub Gist](https://gist.github.com/) please and share the link.

---

That should be enough in the first round, thanks!

**Comment by MonkeyPilot** [comment]
@johnnovak
### Test 1 (success)
Yes, after adding the version string to the `sharp` shader, these errors disappeared.

### Test 2 (success)
The shader `vga-4k` (and others) is working and does not issue errors (if there is a version in `sharp`). But it seems that adaptive shaders still do not work in auto mode, but only if I specifically specify any of them. The display resolution of my laptop is `1366x768`, could this be the reason? The games I tested them on - Dungeon Keeper, Settlers 2, Quake, Doom.

**Comment by johnnovak** [comment]
Thanks for helping with the testing @MonkeyPilot.

The minimum cutoff point for the VGA shader is 800 pixels of vertical resolution. And even on 1080p, we can only fake the double-scanned VGA output (as 320x200 is really 640x400, that's why we need at least 800 lines even to fake it to some degree on 1080p).

You need at least 1440p for good VGA emulation, and 4K for outstanding results.

If the available vertical resolution is not sufficient for a given video mode, the adaptive shaders revert to the `sharp` shader.

For pre-VGA graphics, there are tweaked 720p variants of the shaders, so you'll get shaded output for CGA, EGA, Hercules, etc. games.

**Comment by MonkeyPilot** [comment]
@johnnovak 
Everything is clear, thank you for the clarification. Good luck to you in completing the work on the new version. I've been on the github recently, do I need to close this bug (as resolved) or will you do it yourself after fixing it?

There are a number of other bugs that I have discovered, but I suppose you will fix them without entering them into the bug report, because they immediately manifest themselves as soon as you launch a 0.81. I'll write a few just in case.:
1. When starting, the focus always gets a second window with the log, instead of the main one. You have to switch to the main window first every time.
2. I did not identify any patterns (as it appears chaotically), but sometimes the program freezes when switching to full-screen mode after startup.
3. There is also a long-standing bug that stretches for more than one version, and it is also difficult to reproduce. The bottom line is this — if you leave the program running for a long time (say you go through some kind of game and just don't close the DOSBox-staging, leaving the game on pause and minimizing the main window), then after a while, DOSBox-stagng begins to consume a significant amount of resources (CPU load increases greatly, FPS subsides). Only restarting helps.

**Comment by johnnovak** [comment]
> Good luck to you in completing the work on the new version. I've been on the github recently, do I need to close this bug (as resolved) or will you do it yourself after fixing it?

Thanks man 😄 The ticket was auto-closed once I merged the fix.

> There are a number of other bugs that I have discovered, but I suppose you will fix them without entering them into the bug report, because they immediately manifest themselves as soon as you launch a 0.81.

No, please raise issues when you find them. Problems might only arise on your specific setup.
 
>     1. When starting, the focus always gets a second window with the log, instead of the main one. You have to switch to the main window first every time.

Can't reproduce on Windows 10. Log window appears first, then the DOSBox Staging window second, which then gets the focus as it appears.

>     2. I did not identify any patterns (as it appears chaotically), but sometimes the program freezes when switching to full-screen mode after startup.

Never happened to me. Maybe the iGPU is at fault, hard to tell. Try it with the `sharp` shader only.
 
>     3. There is also a long-standing bug that stretches for more than one version, and it is also difficult to reproduce. The bottom line is this — if you leave the program running for a long time (say you go through some kind of game and just don't close the DOSBox-staging, leaving the game on pause and minimizing the main window), then after a while, DOSBox-stagng begins to consume a significant amount of resources (CPU load increases greatly, FPS subsides). Only restarting helps.

Never noticed this myself. How long are we talking? Hours, days? Please raise an issue with all the relevant info, I'm unware of this.
