### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by nemo93** [dosbox-staging/dosbox-staging#331]
Hello @dreamer @kcgen. Still impressed by the energy deployed in that project! Allow me to share the below.

**1. addition to Retropie**
@kcgen [spotted on my post](https://github.com/dosbox-staging/dosbox-staging/issues/326#issuecomment-620040265) on Retropie's forum :-) Let me share why I haven't yet published a PR. 
=> First I'm not sure to be the best person to do that! I'm no DOSbox-Staging maintainer and I _don't want to steal anyone's thunder_. I definitely had a plan to issue a PR at Retropie's github but only after asking @dreamer and @kcgen first. Also it might be fair for @dreamer and @kcgen to let @joolswills or @cmitu to know about this plan.
=> Second and more important is to have a common set of features shared by various DOSbox implementations. As far as I've tested the main "issue" of Staging is the lack of Fluidsynth/MT32 support which other versions do have including the DOSbox "SVN" shipped by default with Retropie. This happened to me: I've toyed around with this "SVN" version and setup few games with MT32 as music soundcard. After I've switched to Staging no more music. The other "[SDL2](https://github.com/duganchen/dosbox)" version shipped with Retropie (based on @duganchen's implementation) doesn't work as good as Staging yet it comes with Fluidsynth/MT32. No regression when I switched from "SVN" to "SDL2" in Retropie. 
=> Last which has already been pointed by @i30817 in his [other post](https://github.com/dosbox-staging/dosbox-staging/issues/324). There's also a DOSbox "[libretro](https://github.com/libretro/dosbox-core)" core also in the work. I haven't tried it myself so I won't comment further.

Anyhow I'm not the one to decide either Staging should be added to Retropie or not :) I'm just explaining why I haven't released PR before that's all! and I'm fine looking to add it to Retropie.

**2. wiki**
with @dreamer and @kcgen permission I'll keep updating and adding more entries to the wiki of this repo (eg. Games / issues|tips - How to install Staging / Retropie|others - etc).

**3. use [issue templates](https://help.github.com/en/github/building-a-strong-community/configuring-issue-templates-for-your-repository)**
it might help to gather as many info as possible when ppl do raise new ones, help to articulate a change request or when submitting a bug report etc.

**4. forum**
is there a forum or a common place to discuss stuff like this one :-) I'm fine using tickets I'm just asking!

Apologize for this long post.

**Comment by kcgen** [comment]
The only thunder I care about is from the community trying to make things better; everyone's contributions are pieces of the same puzzle: testing, bug-reporting, fixing.  

I certainly don't want to be a gate-keeper or ribbon cutter for all the potential uses of `dosbox-staging` -- I say, keep running with your assessment of dosbox-staging vs. what the RetroPie project is using. Your feedback enlightens both projects, and will lead to your PR there when you at the RPi team feel everything is right. 

On the Pi, set `mididevice = alsa` and `midiconfig = 128:0` in your dosbox-staging config; which should get it at least at MIDI-parity with SVN. (those setting are applied to SVN in `~RetroPie-Setup/scriptmodules/emulators/dosbox.sh`). Then you can run either `timidity -iA` or `mt32d` in the background, putting them on a different core.

Thanks for contributing information on the wiki, and feel free to propose an issue template!  I think there's a sweet-spot in term of the minimal amount of information we want mentioned; and this will save everyone's time.
