### ISSUE TITLE
Is it possible to use both CRT and FMV shaders at the same time?

### ISSUE THREAD

**Issue by mikesk8** [dosbox-staging/dosbox-staging#3324]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Different version than latest?

0.81 RC1

### What Operating System are you using?

macOS (Intel)

### Whats your question and how can we help?

Hi, I just wanted to ask if it's possible to use CRT shaders together with FMV ones at the same time? e.g .in Wing Commander 4, Thanks a lot! m.

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by johnnovak** [comment]
@mikesk8 Not possible currently. The deinterlacer will most likely become a config option, so it will be done at render time instead in a shader, and then you'll be able to apply a CRT shader on top of it. So yeah, I already have plans to address this 😄

**Comment by mikesk8** [comment]
Super! thank you for your answer. I hope it will arrive soon ;-)

**Comment by johnnovak** [comment]
Closing as this is a question.
