### ISSUE TITLE
Investigate/implement AV scan on Windows release build artefacts

### ISSUE THREAD

**Issue by dreamer** [dosbox-staging/dosbox-staging#333]
As of #303 we do anti-virus scans using ClamAV on Linux and macOS development builds and stable release builds.

We don't have a similar option for Windows (where it's the most desired). There is ClamAV available via Chocolatey, but it's an outdated version, not suitable to protect users on an ongoing basis.

We should investigate options we have in here - perhaps Windows Defender is preinstalled on Windows Server 2019 GitHub images?

**Comment by dreamer** [comment]
I'm not a Windows person, so can't tell exactly how well it works, but Windows provides powershell interface to Windows Defender via [MpCmdRun.exe](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-antivirus/command-line-arguments-windows-defender-antivirus).

**Comment by kcgen** [comment]
Great find; this should do the job.
