### ISSUE TITLE
Performance regression going from 0.81.0 RC to 0.81.0 RC2 on macOS

### ISSUE THREAD

**Issue by Grounded0** [dosbox-staging/dosbox-staging#3343]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### What Operating System are you using?

macOS (Intel)

### If Other OS, please describe

macOS 12.6.5

### Relevant hardware info

2017 15" MacBook Pro

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

PERFDOS score falls from 420 to 400.

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Open PERFDOS on macOS/x86-64
2. Observe performance decline

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by Grounded0** [comment]
We probably should use @kcgen buildbot to produce final release macOS binaries because this is exactly the type of stuff i don't want prior to release.

**Comment by Grounded0** [comment]
Connected issues and PRs:

- #3323

**Comment by johnnovak** [comment]
> PERFDOS score falls from 420 to 400.

I'm not buying it. That's 5% difference. If this is the result of two single runs, that means nothing.

If you're really into this, test with Quake bench, please. I don't care about PERFDOS, really, on any DOS benchmarks. Those results can be highly controversial.

Compare 5 Quake bench runs with the same config on 0.81.0 RC1 and RC2, then pick the best. Best to interleave the rusn: one with RC1, one with RC2, etc. (because what if you systems starts overheating and throttling itself after you finished the 5 round of RC1 tests).

**Comment by johnnovak** [comment]
Ok... I've just done it using this:
[Quake Bench.zip](https://github.com/dosbox-staging/dosbox-staging/files/14009109/Quake.Bench.zip)

Downloaded the RC1 and RC2 form the website and I've done 5-5 runs, interleaved.

Best results highlighted.

There's no performance regression whatsoever here, mate.

### RC2

_**33.7**_
33.5
33.4
32.5
33.3


### RC1

_**33.4**_
25.4
33.4
33.1
33.0

**Comment by Grounded0** [comment]
I'll do more extensive tests today.

**Comment by Grounded0** [comment]
@johnnovak 

Which platform are those? I'm currently only quite sure about 5 % gap on x86-64 but i'll have to extensive testing to make myself more assured.

**Comment by johnnovak** [comment]
> Which platform are those?

macOS M1

**Comment by Grounded0** [comment]
I did some extensive performance profiling last night and there's a consistent 7 % performance decline across the board at least on macOS/x86-64.

RC:
```
-rwxr-xr-x  1 ajp admin 18750912 Dec 21 02:53 dosbox
```

RC2:
```
-rwxr-xr-x  1 ajp admin 17932272 Jan 21 01:37 dosbox
```

This kind of difference in binary size tells me something is off with optimisation and i need to figure out exactly what.

**Comment by Grounded0** [comment]
I figured out that we're not doing LTO (Link-time optimization) with the current buildbot. This explains 7 % decline in performance going from RC to RC2. We need to sort this out before 0.81.0 release or use kcgen's buildbot to produce the release macOS binaries if we can't sort this out in time.

**Comment by Grounded0** [comment]
Pinging @kcgen and @kklobe

**Comment by kklobe** [comment]
ah, thank you @Grounded0, I had commented out a build line in the runner file that also enabled LTO. PR incoming.

**Comment by kklobe** [comment]
@Grounded0 please try out https://github.com/dosbox-staging/dosbox-staging/actions/runs/7629116463 and let me know.

**Comment by johnnovak** [comment]
> I figured out that we're not doing LTO (Link-time optimisation) with the current buildbot. This explains 7 % decline in performance going from RC to RC2. We need to sort this out before 0.81.0 release or use kcgen's buildbot to produce 0.81.0 release binaries for macOS if we can't sort this out in time.

Ah, that's a good find. As @kklobe mentioned in his PR, that wasn't intentional to comment the LTO stuff out. 

It's interesting that no-LTO does not affect Quake bench in a negative way on M1. So maybe Intel builds are hit harder? Or you have some specific way of testing? That would be worthwhile to share with us and make it into a regression test suite, perhaphs.

Just curious, what are you using DOSBox for that needs maximum possible performance? Some 3D rendering stuff perhaphs? That would make sense as you were also into accurate FPU emulation.

**Comment by kklobe** [comment]
I gave it a shot on my local M3, and it made no difference on the benchmarks I tried, but it seemed like about 4x the build time, so we'll definitely leave it off for arm64 builds, especially for potential single-digit performance benefits.

**Comment by johnnovak** [comment]
> I gave it a shot on my local M3, and it made no difference on the benchmarks I tried, but it seemed like about 4x the build time, so we'll definitely leave it off for arm64 builds, especially for potential single-digit performance benefits.

Absolutely. I'd still like to see @Grounded0 's measurements as ~5% fluctuations between runs are definitely expected when you push things to the max.

**Comment by Grounded0** [comment]
Performance is now restored.

**Comment by Grounded0** [comment]
> Just curious, what are you using DOSBox for that needs maximum possible performance? Some 3D rendering stuff perhaphs? That would make sense as you were also into accurate FPU emulation.

@dreamer started this project with the idea of no performance regressions unless emulation accuracy is increased. Its working quite well for us looking from the feedback. It really matters when running Win9x disk images. Oh and Carmageddon.

**Comment by Grounded0** [comment]
I use my custom modified DOSBENCH for performance profiling with a lot of added stuff:

http://anttipeltola.eu/misc/files/DOSBENCH.ZIP
