### ISSUE TITLE
`ver` has not been updated for rc2

### ISSUE THREAD

**Issue by signed-log** [dosbox-staging/dosbox-staging#3348]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Different version than latest?

0.81.0-rc2

### What Operating System are you using?

Linux x86_64

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

0.81.0-rc2 still has the `rc1` marking in `ver`

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Install 0.81.0-rc2
2. Run `ver` in dosbox

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by Grounded0** [comment]
<img width="1392" alt="Screenshot 2024-01-24 at 16 48 52" src="https://github.com/dosbox-staging/dosbox-staging/assets/48192273/2c8f2e03-2f68-4a22-ba20-5181891e9907">

**Comment by weirddan455** [comment]
Looks the same in the Linux build as well.  Sure you're launching the correct binary?  https://github.com/dosbox-staging/dosbox-staging/releases/download/v0.81.0-rc2/dosbox-staging-linux-v0.81.0-rc2.tar.xz

**Comment by Burrito78** [comment]
Then it should be wrong on the welcome box too, which it obviously isn't. Can't reproduce on macOS.

**Comment by Grounded0** [comment]
Will close in a day or so since nobody else cannot reproduce.

**Comment by signed-log** [comment]
Seems extremely weird

This is my build (direct from [source](https://github.com/dosbox-staging/dosbox-staging/archive/refs/tags/v0.81.0-rc2.tar.gz))

https://build.opensuse.org/package/show/home:stig124:branches:Emulators/dosbox

With patches, but nothing that would induce that weirdness

**Comment by Grounded0** [comment]
We're not responsible for what packagers do so closing this before going asleep. Contact packager for a fix.

**Comment by signed-log** [comment]
The packaging is done by myself, I know what I did, and I did no modifications to the package in order to do that

**Comment by signed-log** [comment]
Can reproduce from a clean source build

```
git clone https://github.com/dosbox-staging/dosbox-staging.git -b v0.81.0-rc2
cd dosbox-staging
meson setup build
meson compile -C build
```

Does lead up to the `rc1` issue

**Comment by signed-log** [comment]
My bad, I wasn't using the correct executable
