### ISSUE TITLE
Correctly update timestamps on written files

### ISSUE THREAD

**Issue by dreamer** [dosbox-staging/dosbox-staging#335]
This fix is a long-standing, reoccurring user request, but nobody managed to properly finish the implementation.

We had a very promising attempt in #227 - so this seems like a great starting point for next person, who wants to work on this.

**Comment by NicknineTheEagle** [comment]
I guess this can be closed now

**Comment by kcgen** [comment]
Thanks for flagging this and developing this feature @NicknineTheEagle!
