### ISSUE TITLE
Can you get the all of the songs playing on MT-32 or GUS emulations on Elite: First Encounters setup.exe / game itself?

### ISSUE THREAD

**Issue by marsej** [dosbox-staging/dosbox-staging#3353]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### What Operating System are you using?

Windows 10

### Whats your question and how can we help?

This is probably issue with the game but lets document it here anyway. Actually 2 issues, some with music, other with hang on startup when GUS selected.

For testing I used the GoD 002032-FrontierFirstEncounters 3 floppies and FFE106EC patch files.

I changed GUS to use 220 i5 d5 as the setup only accepts 220 for midi.

I get no sound in setup.exe when selecting GUS 220 or MT32 330. In-game, with MT32 In the hall of the mountain king and Great gates of kiev songs didn't play. After applying the 106EC patch, Baba yaga and Ride of the valkyries also do not play. With GUS selected, the game runs loadpats when running firstenc.exe but the hangs.

misc note: from https://www.youtube.com/watch?v=rErSqA3Jkfc : 
"Note : The game has 8 more tracks : the musics from "Frontier Elite II" written/arranged by Dave Lowe, but these ones are heavily bugged in First Encouters and sounds awful. They were written for Roland LA devices such as MT-32/CM-32L/LAPC-I/CM-64/CM-500 and were not properly transposed to General Midi before their conversion to the game proprietary format. So they are played with wrong instruments and GM channel 1 is silent."

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by marsej** [comment]
Found some more info on the GUS and this game here. I'll try what's posted to see if the hang issue resolves:

https://www.vogons.org/viewtopic.php?t=16974&start=100

**Comment by johnnovak** [comment]
> This is probably issue with the game but lets document it here anyway. 

Let's not. This not a public wiki or a dumping ground for your random notes. Only real bug reports or DOSBox Staging related questions please.
