### ISSUE TITLE
Regression with 'Bo Jackson Baseball (1991)'

### ISSUE THREAD

**Issue by Python-Exoproject** [dosbox-staging/dosbox-staging#3364]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Different version than latest?

81 RC2

### What Operating System are you using?

Windows 11

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Using the copy of the game from eXoDOS and running it with RC2 I get the below zoomed in image for all game screens. Using the same conf in RC1 its as it should be

Staging 81 RC2
![image](https://github.com/dosbox-staging/dosbox-staging/assets/67406191/285e729c-385a-4023-b8be-eb1b06c10e7a)

Staging 81 RC1:
![image](https://github.com/dosbox-staging/dosbox-staging/assets/67406191/8cccd76b-5825-478f-a156-2f263063a00e)

### Steps to reproduce the behaviour.

Explain how to reproduce
1. 
2.
3.

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by weirddan455** [comment]
I can reproduce this on rc2 but it's fixed in main.  Probably by #3356

Closing this as fixed.
