### ISSUE TITLE
Breakpoints added with BPMR are not included in BPLIST

### ISSUE THREAD

**Issue by gzip** [dosbox-staging/dosbox-staging#3372]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Different version than latest?

0.81-rc2

### What Operating System are you using?

Windows 11

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

@LowLevelMahn @kcgen As mentioned in the [original merge](https://github.com/dosbox-staging/dosbox-staging/pull/3191#issuecomment-1922643134), memory read break points aren't included in BPLIST.

![bpmr](https://github.com/dosbox-staging/dosbox-staging/assets/104513/a6b36c64-298c-4c2a-be8b-9edb28b0da08)

### Steps to reproduce the behaviour.

Explain how to reproduce
1. 
2.
3.

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by Grounded0** [comment]
Hopefully 0.81.0 will include a working implementation of this.

**Comment by LowLevelMahn** [comment]
im currently struggeling with a hardcore flu

but i think only these two lines are missing

```
void CBreakpoint::ShowList(void)
{
...
		} else if (bp->GetType()==BKPNT_MEMORY_READ) {
			DEBUG_ShowMsg("%02X. BPMR %04X:%04X\n",nr,bp->GetSegment(),bp->GetOffset());
                }
...  

```
