### ISSUE TITLE
Command HQ (1990)

### ISSUE THREAD

**Issue by Python-Exoproject** [dosbox-staging/dosbox-staging#3385]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Different version than latest?

82.0 alpha

### What Operating System are you using?

Windows 11

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

When running this game with MT32 the intro screen slows down to a crawl compared to when using Tandy or Adlib.

You can use the different sound cards via command line:

Tandy = 'HQ2 /GE /AT'
Adlib = 'HQ2 /GE /AA'
MT32 = 'HQ2 /GE /AR'

I dont think its specific to Staging either, ECE has the same trouble

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Use the copy of the game from eXoDOS.
2. Run with MT32
3.

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by codengine** [comment]
This also happens in PCem, even with a Pentium-class CPU. I guess there is nothing that can be done, the game is probably just faulty.

**Comment by johnnovak** [comment]
Happy to close this one @Python-Exoproject ?

**Comment by Python-Exoproject** [comment]
Yep, happy to close. Thank you for confirming its a game bug, not an emulation one

**Comment by johnnovak** [comment]
Thanks @codengine and @Python-Exoproject. Another one down 🚀
