### ISSUE TITLE
vsync lagging?

### ISSUE THREAD

**Issue by Nitrosparxx** [dosbox-staging/dosbox-staging#3391]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Different version than latest?

0.80.1.0

### What Operating System are you using?

Windows 10

### Whats your question and how can we help?

_I first tried asking about these issues on VOGONS. But I was told to ask here instead._ 

To preface, I'm predominantly a retro console kind of guy. Though I have taken an interest in exploring DOS games (namely DOS games from the early to mid 90s) Recently, as I've been testing out different DOS games, I'm noticing odd slow downs here and there. For context, my PC's display is a TV. A Samsung Series 5, 40" 1080p LED (smart) TV to be exact. It maxes out at 60hz (at least, I think it does. I can't set the refresh rate higher using Nvidia or the windows system settings. And I can't find any refresh rate options in the TV menu). I default to having my games run at full screen (resolution set to, "desktop), vsync on, with a crt filter (been using mattias, but recently I've switched to lottes-fast). And sometimes I find myself messing with dos_rate, depending on the game. Sometimes leaving at default results in the frame rate being kind of jerky looking. I've noticed however, that sometimes my games will suddenly slow down or, "skip" at random points. It's different for each game. Some examples;

1) **Jazz Jackrabbit (GOG.com version)**
Mostly runs fine, though Jazz's sprite keeps flickering (from what I understand, that's just how the game is?). Though sometimes when entering cave/enclosed areas, the game will suddenly slow down a bit. Going from full frame rate down to the 30~20fps range. Most notably, are the two splash screens when exiting. The credits screen and the order info screens seem to chug quite a bit. Sometimes the credits screen absolutely hangs or slows down to single digits. And the order screen animations stutters (runs smooth -> stops -> runs smooth -> stops -> etc.). Not a big issue in that case, but still, it's very odd behavior. 

2) **Duke Nukem 3D**
Will run at full frame, but like five or so minutes into the game, it will suddenly chug and drop down into the 30~20fps range. It eventually gets back up to full frame rate, but it will then slowly chug again. Should point out I'm also using the bmouse mod for smoother mouse controls, so I don't know how much that's affecting things. 

3) **Epic Pinball (GOG.com version)**
Usually behaves itself. Runs at full frame rate, but sometimes during the menus (mostly during the transitions where the text, "explodes") the game will slow way, way down. One time it was so bad, it hanged the game. This has mostly been culled after disabling Nvidia overlay, but it still sometimes happens. 

4) **Happyland Adventures**
This game is the bane of my existence. This is one of the few games I've had to mess with the dos_rate, because default settings makes the frame rate awful and jittery. So dos_rate is either set to host (host set to auto) or 60.000. But even then, the game still sometimes, "skips." It's very difficult to describe what I mean. Basically, the game runs at a smooth pace, but I can physically feel the game like, "skip" slightly at times (usually during jumping, or when scrolling up). I've tried the running the game with vsync off, but then the music suddenly corrupts (slowing down, speeding up at random intervals). Not to mention the abysmal screen tearing that occurs with vsync off. 

5) **Wolfenstein 3D (GOG.com version)**
Seems to run fine. Don't recall running into slowdown during actual gameplay. However something strange happens upon start up. The game boots up directly into the choose game menu (asking to choose either Wolfenstein 3D or Spear of Destiny). But then the screen immediately goes black. I can just hit enter, and it'll take me to the options menu, and then the title screen just fine. One time I tried to shift from fullscreen to windowed mode, and the game just completely blacked out. Very strange.

6) **Star Wars: Dark Forces (GOG.com version)**
Runs okay for the most part, though it inconsistently drops frames here and there. Like, in certain parts of stages, the game runs at full frame rate, but then I'll turn a corner and it's dropped a bit. Should point out that there was a bug with the ice in mission 8. Where stopping dead on the ice would make it virtually impossible to move. I did the thing where the DOS Box staging wiki recommended setting the cycles to 50000, and this seems to have fixed things. But I'm unsure if that has anything to do with this issue.

The most I've deduced is that these issues are largely due to vsync. But turning that off results in distracting screen tearing (or music corruption). I have read that most DOS games ran at 70hz, but I don't know how to get my 60hz TV to play nice with that. I've been messing with settings here and there, but nothing seems to work. As stated, I'm mostly a retro console guy, so my DOS prompt/programming skills are incredibly weak (the most technical thing I was able to accomplish were making a CHOICE menu for episodic games in a .conf file using notepad++). Any tips or advice on how to fix these issues would be appreciated. 

Some more info on how I have things set up;

1) One half of my DOS games were purchased through GOG.com. The other half are things I've gotten elsewhere. The GOG games have had their folders modified by swapping out the vanilla DOS BOX folders with ones containing DOS Box Staging. The non-GOG DOS games I have are each in their own folder on my drive. And in each one of those folders is a DOXBOX folder with DOS Box Staging in those. It's uh...rather inelegant, but works. Regardless of the kind of DOS game, I have all them run through GOG Galaxy (as in, I have them added to my GOG Galaxy library, and have the DOS Box executable linked. So I can press play and have my non-GOG games run automatically). 

2) Neither GOG Galaxy nor the individual DOS are on my actual C:\ drive. Space is rather limited on my C:\ drive. So everything is running off of a second M.2 stick (labeled as my E:\ drive)

3) I typically run Anti-Micro with certain games when I'm using a gamepad. I know DOS Box Staging offers remapping, but I find Anti-Micro easier to use. 

4) I'm running everything using an NVIDIA GeForce RTX 2070 Super. 32gb of RAM, and about 36.7gb of virtual RAM. My processor is an AMD Ryzen 7 3700X 8-Core Processor, running at 3.60Ghz. And my operating system is Windows 10 home edition (vers. 22H2)

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by johnnovak** [comment]
I've skimmed most of this, and sorry, I'm not going to review your points in detail because this is a huge infodump.

But here are my general remarks:

– Most VGA DOS games from the early to late 1990s use 70 Hz screen modes, yeah.
- You don't need to worry about this much for 3D games, they will JustWork(tm) with the _defaults_ of our new v0.81.0 release to be released next week.
- Please don't screw around with `dos_rate`, `vsync` etc. if you don't know exactly what you're doing. It's likely you'll make things a lot worse. The defaults of v0.81.0 should serve you well on your 60Hz setup (yes, there will be frame skips, of course — there's no other way unless your display can do 70 Hz). 
- Weird periodic slowdowns/glitches — these can be anything, man 😎 Antivirus kicking in, scheduled background processes, automatic wallpaper switchers, any number of things running on your system in the background...

So, please upgrade to the new version next week when it comes out, use the defaults, and see how that goes.

If you're experiencing issues with a game and you've ruled out issues specific to your setup (e.g., some heavy antivirus process that does things every 20-30 minutes), please raise short, focused tickets — only one game per ticket please.

Thank you and good luck! 😄

**Comment by Nitrosparxx** [comment]
Thank you for replying, and sorry for my verbosity. Yeah, on retrospect, I do have a lot of background things running (usually discord, and I have my background cycle between two pics periodically). So I'll see about disabling those. Perhaps in the future I'll invest in a dedicated emulation box with a proper high refresh rate screen. I'll wait for version 81.0 to drop next week and see from there. Thanks again!
