### ISSUE TITLE
PowerVR Emulation support

### ISSUE THREAD

**Issue by green909** [dosbox-staging/dosbox-staging#3394]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Different version than latest?

latest

### What Operating System are you using?

Windows 10

### Is your feature request related to a problem? Please describe.

I wanted to try out the PowerVR version of Tomb Raider but I get an error that says "Couldn't find either a PCX2 or PCX1 card in this PC. Exiting."

### Describe the solution you'd like

It would be nice if it were somehow possible to emulate PowerVR on DOSBox.

### Describe alternatives you've considered

DOSBox X, and DOSBox SVN.

### Add any other context or screenshots about the feature request here.

The error: https://imgur.com/a/JH5jU2G

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by FeralChild64** [comment]
Be realistic; 3D accelerators are complicated little beasts, for most of them the hardware documentation is not available, and the workforce is very limited. And very few DOS games can utilize them.

Unless someone steps in and writes the emulation code, this is unlikely to happen.

**Comment by Jkapp76** [comment]
I have sucessfully used Staging with Oculus Rift 2. Just set it to 2D mode and play on. It was fun looking at all those visible pixels up close, and I may never do it again, but it was easy to achieve. Looks like a huge dos movie screen hovering in the air.

**Comment by weirddan455** [comment]
> I have sucessfully used Staging with Oculus Rift 2. Just set it to 2D mode and play on. It was fun looking at all those visible pixels up close, and I may never do it again, but it was easy to achieve. Looks like a huge dos movie screen hovering in the air.

@green909 was talking about emulating old PowerVR graphics cards from the 90s, not virtual reality.

> Be realistic; 3D accelerators are complicated little beasts, for most of them the hardware documentation is not available, and the workforce is very limited. And very few DOS games can utilize them.
>
> Unless someone steps in and writes the emulation code, this is unlikely to happen.

Agreed.  PowerVR emulation is even more niche than the Voodoo emulation we already have.  I don't think anyone on the core team is interesting in developing this right now but PRs are welcome if you are interested in this and have the skills and time to do it.

**Comment by johnnovak** [comment]
Out of scope, but we won't reject a PR, of course. But there's not much point in leaving this ticket open.
