### ISSUE TITLE
country and keyboardlayout settings

### ISSUE THREAD

**Issue by CommodoreST** [dosbox-staging/dosbox-staging#3401]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Different version than latest?

0.81.0

### What Operating System are you using?

Windows 10

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Dosbox-staging doesn't respect my settings from dosbox.conf (country = 1 keyboardlayout = 1) in it's own portable directory. It uses Windows keyboard language settings instead.

My Windows setup is: US language, PL keyboard
Dosbox uses PL for everything - messages.
What i want? US for everything.
Obviously I can delete resource files to solve it but it looks like a bug.

### Steps to reproduce the behaviour.

Explain how to reproduce
1. 
2.
3.

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by CommodoreST** [comment]
I've just changed language=en in dosbox.conf and at least Dosbox-staging started to use English but it still uses Windows setting for keyboard.

**Comment by FeralChild64** [comment]
`keyboardlayout = 1` is not a valid setting, try `keyboardlayout = us`. You can find the list of valid layouts here: https://github.com/dosbox-staging/dosbox-staging/blob/main/contrib/resources/freedos-keyboard/DOC/LAYOUTS.TXT

We need to document it better in the configuration file...

**Comment by johnnovak** [comment]
Okay so this is a documentation issue. I'll leave it with you @FeralChild64. I've updated the labels accordingly.

**Comment by FeralChild64** [comment]
I intend to do this, but probably not now. We already have 20 PRs in a queue, it starts being unmanageable.

**Comment by FeralChild64** [comment]
Documentation is now updated, closing the issue.
