### ISSUE TITLE
Inconsistency between ipx over udp/ip default setting and it's description in config file

### ISSUE THREAD

**Issue by rsribeiro** [dosbox-staging/dosbox-staging#3402]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Different version than latest?

0.81.0

### What Operating System are you using?

Windows 11

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Comment section in config file says "ipx" setting is enabled by default, but in a newly generated file the value for the setting is "false".

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Delete/rename your config file 
2. Open DOSBox-Staging
3. Check newly generated default file (on windows it's at %LOCALAPPDATA%\DOSBox)

### Provide a Log

```text
CONFIG: Created primary config file 'C:\Users\...\AppData\Local\DOSBox\dosbox-staging.conf'
```

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by weirddan455** [comment]
Good catch.  I put a PR in #3403

**Comment by johnnovak** [comment]
Thank for reporting this @rsribeiro ❤️
