### ISSUE TITLE
Please stop using VirtualBox! Please use Qemu!

### ISSUE THREAD

**Issue by DeafMan1983** [dosbox-staging/dosbox-staging#3407]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### What Operating System are you using?

Other

### If Other OS, please describe

All operating systems support

### Is your feature request related to a problem? Please describe.

I would like to explain about VirtualBox because VirtualBox is really scammed emulator because you don't expect about PowerPC support or Vulkan, GPU or higher OpenGL 4.6. I want you bring backend with Qemu 8.2.x. Please remember that!

Sorry I caught German magazine Heiss Online that he wrote "Thanks with VirtualBox...." I warned him because VirtualBox is scammed emulator. I have high experience with Qemu because I already read news about Qemu with Vulkan support as venus and GPU rendering as virglrenderer and more features so close VMWare Player physical device support.

Why do I not care about VirtualBox since I have tested on my computer but it shows me like common picture as comic with sitting Chinese with orange cloth. That's why it seems scammed emulator. I hope you understand my English.  Sorry my bad English and it is not my current Language.

### Describe the solution you'd like

Please use Qemu support!

### Describe alternatives you've considered

Qemu for support like Vulkan, GPU rendering and higher OpenGL Version.

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by DeafMan1983** [comment]
Ok no planned? No problem!

**Comment by kklobe** [comment]
Hello @DeafMan1983, this is the DOSBox Staging project and doesn't have anything to do with VirtualBox or QEMU - but we are glad you like QEMU!
