### ISSUE TITLE
Shader selection with a 'display hardware emulation' mindset

### ISSUE THREAD

**Issue by dani-jozsef** [dosbox-staging/dosbox-staging#3415]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### What Operating System are you using?

Linux x86_64

### Is your feature request related to a problem? Please describe.

While I adore the new adaptive crt shader modes, even the `crt-auto-machine` mode is trying to be a little too smart for my taste / the use case I have in mind, as for example in text modes it seems to prefer the 'sharp' shader. (A solid choice for pure usability of text-mode application, but if I want to emulate a CGA crt monitor, I'd prefer it being emulated end to end.)

However, if I explicitly select a crt shader, when I switch to CGA composite mode, I'd still prefer a more TV or composite monitor-like shader, like one of the arcade or composite crt shaders, instead of the CGA shader I want for RGB.

### Describe the solution you'd like

I guess as an alternative to the current approach to shaders that is very much focused on trying to guess what would fit a certain application best, it would be cool to have the ability to approach shaders from a different perspective; where users can pick what type of hardware is emulated.

Eg. setting up a CGA machine with two alternative emulated monitors, one a Tandy CGA/EGA, and the other a composite one, like those from Commodore. (Or a color TV.)

### Describe alternatives you've considered

Maybe some kind of granular user-customizable shader selection logic could serve this and many other use cases.

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by johnnovak** [comment]
Hi @dani-jozsef. I'm glad to hear you enjoy the new CRT shaders 😄 

> even the crt-auto-machine mode is trying to be a little too smart for my taste / the use case I have in mind, as for example in text modes it seems to prefer the 'sharp' shader. (A solid choice for pure usability of text-mode application, but if I want to emulate a CGA crt monitor, I'd prefer it being emulated end to end.)

If you use `crt-auto-machine`, that will work exactly like you described. If you use `machine = cga`, a CGA monitor is emulated, full stop. The CGA shaders will be used in all video modes, including text modes, which will appear single scanned as they are 200 pixel high.

If you get the sharp shader is some text modes, that must happen on VGA and a 1080p screen  or running is windowed mode and using small window sizes. If there is no sufficient vertical resolution for a passable CRT emulation, we revert to the sharp shader as there is no other choice.

Can you be specific and describe the cases in exact detail where you're not getting the results you were hoping for? Please post your config, your logs, and program you are testing with for each test case, and also the result you were hoping to get. Screenshots are not necessary, I can see what's going on from the logs.

> However, if I explicitly select a crt shader, when I switch to CGA composite mode, I'd still prefer a more TV or composite monitor-like shader, like one of the arcade or composite crt shaders, instead of the CGA shader I want for RGB.

Explicitly select a shader how? Which shader? Againg, be specific and describe a concrete repro case, as per above.

> I guess as an alternative to the current approach to shaders that is very much focused on trying to guess what would fit a certain application best, it would be cool to have the ability to approach shaders from a different perspective; where users can pick what type of hardware is emulated.

Only `crt-auto` is guessing. `crt-auto-machine` is non-guessing as it emulates the monitor set by the `machine` setting. `crt-auto-arcade` is non-guessing either.

> Eg. setting up a CGA machine with two alternative emulated monitors, one a Tandy CGA/EGA, and the other a composite one, like those from Commodore. (Or a color TV.)

How would this work and why would be necessary? What's the use case here? I can't see any use case that is not served by the current option. Remember, you can always set `glshader` at runtime too and from batch files (e.g., to switch between `crt-auto-machine` and `crt-arcade`).

> Maybe some kind of granular user-customizable shader selection logic could serve this and many other use cases.

Possible, but complicated, and ultimately not many people would need this, so I abandoned the idea. Again, what's the use case?

---

I suggest to read the config description of the various CRT shaders carefully again (the description of the `glshader` setting), and if you still think there is an issue, please describe separate concrete example I can reproduce as per above.

**Comment by dani-jozsef** [comment]
Thanks for the detailed answer. I think I misunderstood the reason why the sharp shader was chosen, I'll keep a lookout at this behavior, and update if I find something that looks off. In the meantime it's okay to close this feature request.

(One thing that could be cool though is to have a user choice between different shaders for composite mode? What do you think?)

**Comment by johnnovak** [comment]
> Thanks for the detailed answer. I think I misunderstood the reason why the sharp shader was chosen, I'll keep a lookout at this behavior, and update if I find something that looks off. In the meantime it's okay to close this feature request.

No problem 😄 

> (One thing that could be cool though is to have a user choice between different shaders for composite mode? What do you think?)

I'm not sure I follow? What do you have in mind exactly?

**Comment by Jkapp76** [comment]
I love the shader for composite mode. It's the only one I ever saw that works perfectly in single-scan mode for composite.

**Comment by johnnovak** [comment]
Closing this for now. Please raise a new ticket @dani-jozsef with your ideas in the future if you wish.
