### ISSUE TITLE
Wrong scaling in Wing Commander 3

### ISSUE THREAD

**Issue by PoulpSquad** [dosbox-staging/dosbox-staging#3416]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### What Operating System are you using?

Windows 10

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Wing Commander 3 is only showing part of its display area in SVGA:

![image0001](https://github.com/dosbox-staging/dosbox-staging/assets/91291669/6e2d0fb0-7523-41b6-9408-89b6cd43a49c)

Pressing the Win key fixes it:

![image0002](https://github.com/dosbox-staging/dosbox-staging/assets/91291669/c9e6db62-03e9-404e-a3db-d300f37b9b3d)

Proceeding to the flight control breaks it again:

![image0003](https://github.com/dosbox-staging/dosbox-staging/assets/91291669/1c8f2023-0e8e-42c5-8843-fd9dbf9ec496)

This time alt-tabbing or pressing Win has no effect.

Introduction video is also cut in half and displayed in the bottom part of the screen:

![image0004](https://github.com/dosbox-staging/dosbox-staging/assets/91291669/9c0fb350-219c-4d41-88ab-5cf789f2199f)

UNIVBE has no effect on this issue.

Console insists the original display is 640x240 256 colors and gets scaled to 1920x1440 pixels with 1:2 (1:2) pixel aspect ratio (instead of 640x480 pixels).

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Install Wing Commander 3 with SVGA options enabled. 
2. Run with WC3.EXE as per usual.

### Your configuration

```ini
machine            = svga_s3
aspect             = auto
integer_scaling    = vertical
viewport           = fit
```

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by Grounded0** [comment]
Which graphics card or integrated GPU and at which specific driver release?

**Comment by PoulpSquad** [comment]
Drivers version 546.65 on MSI GTX 1070 GAMING X.

OS is Windows 10 x64.

**Comment by Grounded0** [comment]
Are you using OpenGL?

**Comment by PoulpSquad** [comment]
Yes sir

output                   = openglnb
texture_renderer    = auto

**Comment by johnnovak** [comment]
It's DOSBox issue, host driver does not matter. The PAR is calculated probably incorrectly for some VESA mode or perhaps it's a custom res.

**Comment by weirddan455** [comment]
This is a regression from 0.80.1.  I'll start a bisect.

**Comment by weirddan455** [comment]
This is going to have to be a 2 step bisect.  Everything works from v0.80.1 to d47e8c624d4303a98607746d86e51c5e5d52bf28 where the intro movie is bugged but in a different way:

![wc3-bug1](https://github.com/dosbox-staging/dosbox-staging/assets/8128047/11745ddb-09b1-49a0-a51b-51d8918a2d82)

**Comment by weirddan455** [comment]
5d26dd94c49d1282a6464e826c9dd70381314cf5 is the first bad commit that displays current behavior.  These are both very recent commits by @johnnovak and deep inside VGA code (which is a very scary place for me :fearful: )

**Comment by johnnovak** [comment]
> 5d26dd94c49d1282a6464e826c9dd70381314cf5 is the first bad commit that displays current behavior.  These are both very recent commits by @johnnovak and deep inside VGA code (which is a very scary place for me :fearful: )

This change keeps giving... I'll have a look at some point. I'm sure we'll get it right after about 5 more such regression reports :)

**Comment by Grounded0** [comment]
AAA title like Wing Commander 3 being broken is large enough reason to issue 0.81.1. A lesson learnt on how you only really know how everything works by releasing the software to the public.

**Comment by johnnovak** [comment]
> AAA title like Wing Commander 3 being broken is large enough reason to issue 0.81.1. 

Fair enough. I'll probably fix this week, but we to wait a few weeks to let potential reports/fixes accumulate. Ideally, I want to do a single patch release within one month after the release and that's it.

> A lesson learnt on how you only really know how everything works by releasing the software to the public.

I think we already know that 😄 The RC approach has worked very well and it was worth it as it cut down significantly on the number of regressions that went into the final. Look at the number of issues fixed between RC1 and the final.

Issues like this one are a roll of the dice. It's very easy to introduce regressions into the VGA code (or anything) that will only be discovered in a handful of games, and potentially years later.
