### ISSUE TITLE
Mike Ditka Ultimate Football (1991) Tandy Regression

### ISSUE THREAD

**Issue by Python-Exoproject** [dosbox-staging/dosbox-staging#3421]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Different version than latest?

0.81.0

### What Operating System are you using?

Windows 11

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

If you play this game using tandy sound for the game setup, machine=svga_s3 and tandy=on in the conf with Staging 80.1, dosbox 0.74, or ECE you get a voice during the intro credits saying "Accolade Presents" when that screen is displayed. 

In Staging 81.0 you no longer get the voice.

If this is a verified bug and Tandy code needs modifying, one of the best games to check against to ensure nothing else was broken with the new fix is Outrun with tandy sound. Outrun was recently fixed by @kcgen and should have intro voice, engine rumble, and crash effects if its all working

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Run Mike Ditka Ultimate Football (1991) with Tandy 3 voice sound 
2. 
3.

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by Python-Exoproject** [comment]
This can be closed. With a bit more testing I found that even though the game was set to use Tandy 3 Voice it was utilising the Sound Blaster in ECE to provide the voice. This explains why 80.1 worked as it allows both devices, but 81.0 shuts down the SB when Tandy is turned on

**Comment by johnnovak** [comment]
> This can be closed. With a bit more testing I found that even though the game was set to use Tandy 3 Voice it was utilising the Sound Blaster in ECE to provide the voice. This explains why 80.1 worked as it allows both devices, but 81.0 shuts down the SB when Tandy is turned on

Thanks for the follow-up, @Python-Exoproject, appreciated.
