### ISSUE TITLE
Demo content with video and audio

### ISSUE THREAD

**Issue by Eonfge** [dosbox-staging/dosbox-staging#3425]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### What Operating System are you using?

None

### Is your feature request related to a problem? Please describe.

This is a more general request, not really platform specific or version related.

Long story short; Perhaps it would be cool for Dosbox staging to have an `intro video` that shows a basic visual animation and that plays some sort of jingle.

### Background
The main reason why I think that this would be nice, is to have a simple way for users to test if Dosbox is working. Right now, people have to spend quite a bit of time mounting disks, installing a game, and running it... before they might encounter some problems with their setup.

### Inspiration
I was thinking of the demoscene and the CGI graphics that they rpoduce. These applications are often really small, only kilobytes, but they features some graphics and audio. Perhaps somebody from the demoscene would like the challenge of creating an intro just for dosbox?

https://en.wikipedia.org/wiki/Demoscene

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by johnnovak** [comment]
This is out of scope, man 😄 Just use any 4k or 64k intro from https://www.pouet.net/ if you need a simple small test program. If you pass the current directory or any path to DOSBox, it will mount that as the C drive (e.g., `dosbox .` to mount the current working dir as the C drive).

There are so many variations of things that could be potentially tested by a such app that this is way out of scope...
