### ISSUE TITLE
Stuttering in Wing Commander 3 Videos

### ISSUE THREAD

**Issue by weirddan455** [dosbox-staging/dosbox-staging#3431]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### What Operating System are you using?

Linux x86_64

### If Other OS, please describe

Arch Linux

### Relevant hardware info

AMD Ryzen 7 1700 Eight-Core Processor, AMD Radeon RX 460/560 (one of the two)

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

About every second, the video will stutter.  It's most noticeable by the audio popping.  Gameplay seems fine when it's not playing videos.

This is reproducible for me both on v0.80.1 and latest main.

### Steps to reproduce the behaviour.

Explain how to reproduce
1.  Start Wing Commander 3
2.  Watch intro video and listen for pops

### Your configuration

```ini
Default config
cycles = auto (switches to max when game starts)
```

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by keenanweaver** [comment]
Those of us in the Wing Commander community have had a rule of thumb for WC3 and DOSBox cycles: 75000. It's seemingly the most accurate and greatly reduces the stuttering/popping.

There's another long-standing issue with WC3 and all versions of DOSBox where transitions in cutscenes result in a very brief 'static' screen that does not happen on original hardware (or if it does, it's not as obvious). Never opened an issue for it for whatever reason. Not sure if that's fixable. I'm sorry if you never noticed these before now because now you will always see them!

**Comment by MasterO2** [comment]
> Those of us in the Wing Commander community have had a rule of thumb for WC3 and DOSBox cycles: 75000. It's seemingly the most accurate and greatly reduces the stuttering/popping.
> 
> There's another long-standing issue with WC3 and all versions of DOSBox where transitions in cutscenes result in a very brief 'static' screen that doesn't happen as much on original hardware (and when it does, it's not as obvious, might be a CRT thing). Never opened an issue for it for whatever reason. Not sure if that's fixable. I'm sorry if you never noticed these before now because now you will always see them!
> 
> If you're curious, here's an example:
> 
> DOSBox: https://youtu.be/507sqq1i3u0?t=1138
> 
> DOS: https://youtu.be/5KIpl9gSSpM?t=1420

Can you add that information about the 75000 CPU Cycles to https://github.com/dosbox-staging/dosbox-staging/wiki/Game-issues?  That's very useful knowledge.

**Comment by keenanweaver** [comment]
> @keenanweaver, can you add that information about the 75000 CPU Cycles to https://github.com/dosbox-staging/dosbox-staging/wiki/Game-issues? That's very useful knowledge.

Sure thing, just added!

**Comment by johnnovak** [comment]
> There's another long-standing issue with WC3 and all versions of DOSBox where transitions in cutscenes result in a very brief 'static' screen that doesn't happen as much on original hardware (and when it does, it's not as obvious, might be a CRT thing). Never opened an issue for it for whatever reason. Not sure if that's fixable. I'm sorry if you never noticed these before now because now you will always see them!

This is how it looks, grabbed a frame when it happens from the linked video. If it happens on real hardware too, that's pretty much the end of it.

Seems like a palette bug, btw.

<img width="1217" alt="image" src="https://github.com/dosbox-staging/dosbox-staging/assets/698770/4ece73df-5c79-422d-9087-cb6d4c165032">

**Comment by weirddan455** [comment]
Don't think there's anything else actionable here.  It's been documented in the wiki to lower the cycles and the new default of 60,000 cycles for protected mode should also mitigate this issue.
