### ISSUE TITLE
Show by Majic 12 video regression

### ISSUE THREAD

**Issue by johnnovak** [dosbox-staging/dosbox-staging#3434]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### What Operating System are you using?

macOS (Apple Silicon)

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

The zoom-rotator part in the intro of Show by Majic 12 has regressed. As this used to be my group in the 90s, I'm rather saddened by this unfortunate turn of events 😢 

## main

With `svga_s3`. This is bad.

<img width="1072" alt="image" src="https://github.com/dosbox-staging/dosbox-staging/assets/698770/4b63535b-bc91-49b8-80b6-3914eefac496">

## 0.80.1

Same results with `svga_s3` and `vgaonly`. The results are perfect.

<img width="1072" alt="image" src="https://github.com/dosbox-staging/dosbox-staging/assets/698770/557caf74-04bd-4b03-b786-b5a4f98a1db5">

### Steps to reproduce the behaviour.

Start the demo (needs GUS) then watch the intro. Bamm!

### Download URL of affected game or software

https://www.pouet.net/prod.php?which=1158

### Your configuration

```ini
Stock
```

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by weirddan455** [comment]
Rather large commit unfortunately.

```
bc924b6f7cb966e5a2f1b0235e0d43a5bde68fd4 is the first bad commit
commit bc924b6f7cb966e5a2f1b0235e0d43a5bde68fd4
Author: John Novak
Date:   Tue Aug 22 22:32:08 2023 +1000

    Implement adaptive CRT emulation shaders
    
    - All shader management code has been moved from 'render.cpp' to
      the ShaderManager.
    
    - The 'default' shader alias to 'interpolation/sharp' has been replaced
      with the 'sharp' alias.
    
    - Three new adaptive (auto-switching) CRT emulation shader modes have
      been added: 'crt-auto', 'crt-auto-machine', and 'crt-auto-arcade'.
      These modes switch dynamically between CRT shader variants depending
      on the current video mode, the graphics adapter in use, and the
      viewport resolution (see the description of the 'glshader' setting for
      further details).

 include/render.h           |  35 +--
 src/gui/meson.build        |   5 +-
 src/gui/render.cpp         | 453 ++++++++++++++------------------------
 src/gui/sdlmain.cpp        |  16 +-
 src/gui/shader_manager.cpp | 531 +++++++++++++++++++++++++++++++++++++++++++++
 src/gui/shader_manager.h   | 179 +++++++++++++++
 src/hardware/vga_draw.cpp  |  12 +
 vs/dosbox.vcxproj          |   2 +
 vs/dosbox.vcxproj.filters  |   6 +
 9 files changed, 918 insertions(+), 321 deletions(-)
 create mode 100644 src/gui/shader_manager.cpp
 create mode 100644 src/gui/shader_manager.h
```

**Comment by weirddan455** [comment]
Actually, it's just the shaders that are causing this bug somehow.  Run with `glshader = none` on `main` and it looks correct.

**Comment by weirddan455** [comment]
Previous bisect was not meaningful.  I was testing with `glshader = crt-auto` which on older versions just fell back to using no shader at all.  The real commit that causes this regression is the following (reproducible with `glshader = default`):

```
2b26d90dc0cac2e17538836c95932b4b17e667bf is the first bad commit
commit 2b26d90dc0cac2e17538836c95932b4b17e667bf
Author: John Novak
Date:   Thu Jul 6 21:33:23 2023 +1000

    Add 'force_single_scan' and 'force_no_pixel_doubling' OpenGL shader pragmas
    
    Shaders can now request single-scanning and no pixel-doubling with these
    pragmas. The motivation for this can be to increase performance where
    such doublings would make no visual difference (e.g. for our default
    'interpolation/sharp' shader), or to achieve a certain look (e.g. to
    emulate a consumer TV or an arcade or home computer monitor).

 include/render.h     | 10 ++++++----
 src/gui/render.cpp   | 37 ++++++++++++++++++++-----------------
 src/gui/sdlmain.cpp  | 49 ++++++++++++++++++++-----------------------------
 src/hardware/vga.cpp | 12 ++++++++++++
 4 files changed, 58 insertions(+), 50 deletions(-)
```

**Comment by johnnovak** [comment]
Thanks for the bisects @weirddan455. The second one is closer but is still not the root cause.

The root cause is that forced VGA single scanning is broken. This can be triggered in a few ways:

- `sharp` shader
- `output = texturenb` mode
- `crt-auto-arcade` and `crt-auto-arcade-sharp` shaders

The `none` shader and `crt-auto` double-scans VGA, so those modes are fine.

**Comment by weirddan455** [comment]
>  The none shader and crt-auto double-scans VGA, so those modes are fine.

I can trigger the bug with `glshader = crt-auto` on `main`.  This demo makes it switch shaders quite a lot.  At the time the bug triggers, it was running the sharp shader so it seems you have found the root cause:

```
2024-02-22 18:25:37.546 | RENDER: Auto-switched to shader 'interpolation/sharp'
2024-02-22 18:25:37.546 | VGA: Forcing single scanning of double-scanned VGA video modes
2024-02-22 18:25:37.546 | VGA: Forcing no pixel doubling
2024-02-22 18:25:37.547 | DISPLAY: VGA 320x240 256-colour graphics mode at 63.317 Hz VFR, scaled to 1010x800 pixels with 1:1.05634 (71:75) pixel aspect ratio
```
