### ISSUE TITLE
Impossible Mission II: SIGFPE crash in Tandy mode

### ISSUE THREAD

**Issue by dani-jozsef** [dosbox-staging/dosbox-staging#3436]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### What Operating System are you using?

Linux x86_64

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

The game **Impossible Mission II** (Novotrade / Epyx, 1988) crashes with a Floating Point Exception when loading the first game level on `tandy` machine type.

### Steps to reproduce the behaviour.

1. Start emulation with `--machine tandy` command line parameter (the config below is svga by default)
2. Run the game with `im.com` or `im2_tan.exe`
3. Proceed past the title screen and questions about joystick and saved games
4. Note DOSBOX crashing (with a series of strange video mode switches in the log before)

### Download URL of affected game or software

https://www.abandonwaredos.com/abandonware-game.php?abandonware=Impossible+Mission+2&gid=1873

### Your configuration

```ini
https://gist.github.com/dani-jozsef/b07dfef964e095b7dba8e845c514aaaf
```

### Provide a Log

```text
https://gist.github.com/dani-jozsef/5246a9a481d106f36f07bb72851509ca
```

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by johnnovak** [comment]
Could you test on 0.80.1 as well @dani-jozsef to determine if this is a long-standing bug or a regression?

**Comment by dani-jozsef** [comment]
This seems to be a regression. The crash doesn't happen on 0.80.1. Here's the run log to the point where the game starts:
https://gist.github.com/dani-jozsef/c7dfaf59ad1350499db4d384af0d41b0

**Comment by weirddan455** [comment]
I'll give it I bisect.

**Comment by weirddan455** [comment]
Removing the FPU emulation tag.  This is a good ole integer divide by zero (which for some reason on Linux translates to SIGFPE but on the host side, not the DOS side).  Seems to be caused by a VGA timing variable not being set correctly.

**Comment by johnnovak** [comment]
> 4\. Note DOSBOX crashing (with a series of strange video mode switches in the log before)

That's "normal"; even DOSBox SVN does that. It changes the window size to the current resolution, so you can see the window shrink and grow.
