### ISSUE TITLE
To generate gnu cobol in the FreeDOS within DOSBOX ... [solved]

### ISSUE THREAD

**Issue by arcanjoebc1971** [dosbox-staging/dosbox-staging#3456]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Different version than latest?

0;80;1

### What Operating System are you using?

Linux x86_64

### Whats your question and how can we help?

​I've been trying to generate a gnu cobol compiler for FreeDOS 1.3 for two years, which I have installed in DOSBOX on Debian 12 LXqt, and now an error has appeared that I can't resolve. In the process of generating GNU Cobol, at a certain point, DOSBOX exits and displays several error messages. Can you help me?

 [error-compilation-within-FreeDOS.txt](https://github.com/dosbox-staging/dosbox-staging/files/14426628/error-compilation-within-FreeDOS.txt)

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by johnnovak** [comment]
We need reproduction steps @arcanjoebc1971, config, etc. You haven't filled out half of the sections of the issue template, please try again and do so.

**Comment by arcanjoebc1971** [comment]
I didn't understand ... must I to create a new question? Put I just the half of the informations? I ask because I never posted here in this site ...

**Comment by weirddan455** [comment]
You used the "Question" template instead of "Bug Report".  The latter has more prompts for info that we need.

There's not enough info here for us to help you.  You just gave us a stack trace with no function names and said something about Cobol.  At the very least, try with v0.81.0.  We've fixed a lot of bugs in the new release (including fixing stack traces to have more helpful info).

**Comment by arcanjoebc1971** [comment]
Ok! Now, I installed v0.81.0 and the problem doesn't appear more ,,, Thank you for help me weirddan455 ...

**Comment by johnnovak** [comment]
> Ok! Now, I installed v0.81.0 and the problem doesn't appear more ,,, Thank you for help me weirddan455 ...

Glad to hear that 😄
