### ISSUE TITLE
imgmount (-fs none) is broken in clang-cl (and maybe msvc)

### ISSUE THREAD

**Issue by shermp** [dosbox-staging/dosbox-staging#3464]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Different version than latest?

v0.82.0-alpha-232-gf4452209a

### What Operating System are you using?

Windows 11

### Relevant hardware info

N/A

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

When running `main` compiled with Visual Studio (clang-cl), an imgmount command like `imgmount 2 "C:\DiskImages\db-staging-98se.img" -fs none -t hdd -size 512,63,255,1023` fails with the following message in dosbox: `The image must be on a host or local drive`.

CD images mount correctly.

This does not happen when dosbox-staging is compiled with MSYS2. 

I'm pretty sure I've narrowed this down to lines 294-296 of `program_imgmount.cpp`:
```cpp
// Test if input is file on virtual DOS drive.
constexpr int posix_success = 0;
struct stat test;
if (posix_success != stat(temp_line.c_str(), &test)) {
```

It appears that the MSYS2 clang version of `stat.h` includes a typedef for `stat` from `_stat64`, whereas the VS `stat.h` does not. This *might* only be an issue for large files, I haven't tested with smaller images.

### Steps to reproduce the behaviour.

1. Run Dosbox-staging compiled with VS clang-cl
2. Attempt to mount a raw disk image with  `imgmount 2 "C:\DiskImages\db-staging-98se.img" -fs none -t hdd -size 512,63,255,1023`
3. The image fails to mount with the `The image must be on a host or local drive`

### Your configuration

```ini
N/A
```

### Provide a Log

```text
2024-03-02 11:27:27.373 | IMGMOUNT: Path 'C:\DiskImages\db-staging-98se.img' found
```

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by weirddan455** [comment]
I've had problems in the past with POSIX functions on Windows.  They exist and kind of work sometimes but the behavior is often different than on a real POSIX OS.

Take a look at `cross.cpp` and `fs_utils.cpp` where we have some platform specific stuff taken care of.  There's some helper functions you might be able to use in place of `stat` like `path_exists`.  If you need extra functionality, maybe time to write a new Dosbox helper function with the Windows build using WIN32 native functions instead of POSIX.

**Comment by shermp** [comment]
I wrote a quick and dirty 
```cpp
// Also typedef stat to _stat64. MSYS2 does this
#define stat  _stat64
#define fstat _fstat64
```
In `cross.h`, which seems to work in this case, but I'm not sure if it's the best thing to do, or the best place for it.

I suspect the main issue is actually that plain `stat` was being called, which fails on large files such as hard disk images.

**Comment by johnnovak** [comment]
Nice detective work @shermp 🎉 

> If you need extra functionality, maybe time to write a new Dosbox helper function with the Windows build using WIN32 native functions instead of POSIX.

I agree, platform-specific functions are the way to go. I would always prefer Windows-native APIs over POSIX, so no big deal, just needs some simple abstraction layer.

**Comment by shermp** [comment]
> Nice detective work @shermp 🎉

It's called running it through the debugger to see where it failed. I had a pretty good idea where the problem was, simply by the error printed.

**Comment by shermp** [comment]
Honestly, I think the whole `mount` and `imgmount` programs good use a good refactor.

**Comment by johnnovak** [comment]
> In `cross.h`, which seems to work in this case, but I'm not sure if it's the best thing to do, or the best place for it.

Not really, man 😄 I really dislike such `#define` hackery.

The proper way consistent with our new direction would be to introduce a `get_filesize` function in `fs_utils` and similar functions for all fstat-related functionality.

Don't add anything new to `cross.cpp`; that's legacy stuff we inherited from original DOSBox. We added the `fs_utils` stuff which attempts to be a cleaner implementation of such cross-platform filesystem functionality. `cross.cpp` should eventually go away, but the work hasn't been completed yet.

**Comment by weirddan455** [comment]
In this case, it looks like we are only using `stat` to check if the path exists and if it is a directory.  We already have helper functions for both of these things.

**Comment by shermp** [comment]
> In this case, it looks like we are only using `stat` to check if the path exists and if it is a directory. We already have helper functions for both of these things.

Yeah, I just saw that.

**Comment by shermp** [comment]
Right, pushed a small fix to replace the stat calls in `imgmount`
