### ISSUE TITLE
Investigate "push" vs "pull request" CI workloads

### ISSUE THREAD

**Issue by weirddan455** [dosbox-staging/dosbox-staging#3476]
### A clear and concise description of what the bug is.

We have both "push" and "pull request" workloads for most of our CI jobs but these don't do what I thought they did.

When one of the core team members makes a PR, we are pushing to a branch on this repo.  This runs both of these workloads and it looks like a duplicate gets canceled (sometimes, maybe).  These commits are both a push to the repo and part of a PR.  I was under the impression "push" meant push to main but that is not the case.

When a contributor makes a PR from their own fork, only the "pull request" workload gets run.  This leaves out certain jobs, such as PVS.  CI is currently red on `main` because such a PR got merged and we had no way of knowing beforehand there were warnings that needed to be addressed.

I understand there are certain jobs (such as Coverity I believe) where we have a limited number of minutes we can use.  It makes sense in that case we only want to run it on commits to main.  Coverity also does not turn the CI red due to new warnings.

The "push" vs "pull request" distinction needs to be investigated though.  If anything, "push" gets run more frequently since most of our commits are by core members.  What makes sense to me is to have one set of jobs that gets run on any PR or non-main branch and then the full set of jobs gets run on main.  This would also eliminate some of the clutter where every job gets listed twice in a PR.

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by johnnovak** [comment]
Great writeup and summary of the situation @weirddan455. Indeed, this confused me too last week when modifying the build workflow and I don't really love the doubling up of jobs the cancelling half of them (sometimes) either. 

This was invented well before my time, probably GitHub workflows had a more limited feature set then. If there is a way to do achieve what we want in a cleaner way without duplicating workflows, I'm all for it.

**Comment by johnnovak** [comment]
>  This leaves out certain jobs, such as PVS. 

No longer the case @weirddan455 😎 
https://github.com/dosbox-staging/dosbox-staging/blob/main/.github/workflows/pvs-studio.yml#L23

> CI is currently red on main because such a PR got merged and we had no way of knowing beforehand there were warnings that needed to be addressed.

I think with this change PVS can run on forked PRs: https://github.com/dosbox-staging/dosbox-staging/commit/9a04ee9bcb2a859400ec7f338a7303665b61bbab

We're currently testing it with @MeAreJeenius in his forked PR: https://github.com/dosbox-staging/dosbox-staging/pull/3485

**Comment by johnnovak** [comment]
@weirddan455 Can we close this?

**Comment by weirddan455** [comment]
I think this is still problematic but low priority as we're not currently getting a lot of contributions from non-core members.  IIRC we had problems with that PVS change and it looks like PVS is still not getting run on PRs made from outside our tree.

Take a look at this PR from before you invited @interloper98 to the team:  https://github.com/dosbox-staging/dosbox-staging/pull/3775/checks

No PVS being run there, but it is on his later PRs.

**Comment by johnnovak** [comment]
> No PVS being run there, but it is on his later PRs.

Yeah I think that's "fine" in the sense that it's too hard to make it run in a semi-safe way on external PRs due to the security tokens needed by the PVS workflow.

Living with that seems to be the lesser evil vs complicating the workflows (I tried it for a few days straight, and have failed miserably...)

**Comment by johnnovak** [comment]
Shall I close this @weirddan455 ?

**Comment by weirddan455** [comment]
Up to you.  I think the root problem still exists of not being able to run all of the CI jobs on external PRs.  If there's no good way to do it, I guess there's nothing we can do.  We haven't been getting many PRs from non-core members lately so it hasn't been a real problem.

**Comment by johnnovak** [comment]
> Up to you. I think the root problem still exists of not being able to run all of the CI jobs on external PRs. If there's no good way to do it, I guess there's nothing we can do. We haven't been getting many PRs from non-core members lately so it hasn't been a real problem.

@weirddan455 My view: I don't really like keeping tickets open that have no clear path forward, or worse, that don't really have solutions for them and/or are low priority, and we're not in a rush to do anything about them. So closing this one then 😆
