### ISSUE TITLE
Shell history file does not get created if it does not exist

### ISSUE THREAD

**Issue by weirddan455** [dosbox-staging/dosbox-staging#3482]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### What Operating System are you using?

Linux x86_64

### If Other OS, please describe

Fedora 39

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

`~/.config/dosbox/shell_history.txt` does not get initially created if it does not already exist.  I have not done a full bisect but it was working before #3093 got merged so I'm 95% sure it is a regression in that PR somewhere.

### Steps to reproduce the behaviour.

Explain how to reproduce
1.  Delete `~/.config/dosbox/shell_history.txt`
2.  Start Dosbox
3. Type a command
4.  Exit Dosbox
5.  Shell history does not get saved

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by johnnovak** [comment]
@MeAreJeenius Would you be able to have a look perhaps?
