### ISSUE TITLE
Strange behavior of new adaptive shaders with default conf settings on v0.81

### ISSUE THREAD

**Issue by Gryzor1363** [dosbox-staging/dosbox-staging#3489]
![image0003-rendered](https://github.com/dosbox-staging/dosbox-staging/assets/92555103/075cf0b5-145a-4026-ad6f-6a2ad18f6d6f)
![image0004-rendered](https://github.com/dosbox-staging/dosbox-staging/assets/92555103/ae899f4a-f78c-42b6-a832-46ddc5346c7a)
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Different version than latest?

No

### What Operating System are you using?

Windows 7

### Whats your question and how can we help?

Hello,

first of all thanks a lot for the latest release, it takes dedication and hard work that come with due recognition from our part every time.

After reading through the new CRT feature and namely the auto-select of pre-configured settings, so I rushed into it by creating a portable conf file with default settings (by doing the usual blank dosbox-staging.conf within the Dosbox folder and launching it to fill it in.

Issue is, no matter which setting I use for the render, results seem broken in my case. Indeed, all I get are extremely thin, barely discernable horizontal scanlines and absolutely not the clean, intended effect showcased in the release screenshots (results that I get much closer to with the previous release, with a customized crt-lottes shader). 

Since I use WIn 7 I had to go through the portable zip that I then used as is. I see there

 is a difference when I use "crt-auto" compared to "none" or "sharp" but none give me anything close to the CRT look emulation I'm used to.

I attached screenshots representing my issue, and also my dosbox conf file.

[dosbox-staging.txt](https://github.com/dosbox-staging/dosbox-staging/files/14540963/dosbox-staging.txt)

### Code of Conduct & Contributing Guidelines

- [x] Yes, I agree.[](url)

**Comment by johnnovak** [comment]
Hi @Gryzor1363, glad to hear you appreciate our work. Those screenshots look correct for 1080p; VGA is double-scanned, please read the relevant section of the getting started guide that explains it:

https://dosbox-staging.github.io/getting-started/enhancing-prince-of-persia/#vga

Indeed, there is little discernible difference between the sharp shader and the double-scanned CRT shaders or low-res VGA on 1080p. You need 1440p or 4k for better results (all screenshots on the front page are 4k).

This might be worthwhile to read too:

https://dosbox-staging.github.io/getting-started/passport-to-adventure/#true-ega-emulation

Finally, if you're after the inauthentic but fun look you were getting previously with thick single scanlines on VGA, this section is the ticket 😎 

https://dosbox-staging.github.io/getting-started/beneath-a-steel-sky/?h=arcade#arcade-monitor-emulation

So it all works as intended.

**Comment by Gryzor1363** [comment]
Thanks a lot for your feedback and advice, I was starting to believe something was seriously wrong my the very way I launched Dosbox.

What remains odd to me is that the look I referred too in the previous version with Lottes is nearly identical to the screenshots of your release page. That's what initially brought me to doubt my results being the intended effects. Or maybe there is a quite notable difference between 1080p and 4k and the latest shaders are optimized specially for them, I'll have to wait and test it on actual UHD hardware I guess !

I'm absolutely after authentic results and precisely want to stick to it and not the overblown Mame-style shading, so I'll stick to the first two categories and not the arcade one when it comes to Dosbox ;-)

A good day and thanks again.

Regards,

-G

**Comment by johnnovak** [comment]
No problem @Gryzor1363 😄 

Here's some further clarification on the authentic CRT emulation. On VGA pretty much every resolution lower than 640x350 is double-scanned. This means that pixels appears more like little rectangles than single little blobs of light, and notice there are two scanlines going through every single pixel.

# 320x200 VGA

<img width="593" alt="image" src="https://github.com/dosbox-staging/dosbox-staging/assets/698770/8a2d0067-929a-4112-806a-ef05af694835">

But 640x480 (S)VGA is not double scanned, so you get single scanlines per pixel

### 640x480 SVGA

<img width="659" alt="image" src="https://github.com/dosbox-staging/dosbox-staging/assets/698770/f6844eba-0c57-45b2-9135-88820ee54de3">

Then on anything before VGA, you always get single scanlines per pixel again. Pixels look more like little blobs of light on CGA, EGA, and Hercules.

# 320x200 EGA

<img width="605" alt="image" src="https://github.com/dosbox-staging/dosbox-staging/assets/698770/928dc3d9-3509-4da3-83c8-43a7675060f1">

On the front page we have examples of all these different scenarios, so some of the screenshots might look similar to you previous results, especially when zoomed in.

**Comment by Gryzor1363** [comment]
Indeed the double vs single scan is the biggest discovery of the day for me, if not at all ever since I delved into reshading through HLSL on Mame and its exclusive emphasis on 15khz 240p which is much more oriented towards arcade + home consoles (since the progressive signal worked that way on 480-line TVs I suppose), which is noticeably different both in look *and* original hardware behavior and CRT type and specialization. As I understand, double scan requires bluntly double the amont of pixels devoted to representing them, which in 1080p start looking like even single scan does on 720p : not visible enough, too thin.

**Comment by johnnovak** [comment]
> As I understand, double scan requires bluntly double the amont of pixels devoted to representing them, which in 1080p start looking like even single scan does on 720p : not visible enough, too thin.

That's spot-on. The VGA hardware effectively does a "hardware 2x upscaling step" of 320x200 to 640x400. "True" 640x400 modes and 320x200 hardware-double-scanned to 640x400 are literally 100% indistinguishable from the monitor's point of view.

**Comment by Gryzor1363** [comment]
Thanks again for the valuable insight, I've been meticulously reading through all of your links mate ;-) )and it's super interesting, and that was me thinking the only real difference between commercial TVs and PC monitor had to do with resolution and pixel form, not tech and scan frequency.

Looking forward to your article, I bookmarked your blog, you can count me in for the read !

Please allow me to take this ticket as an opportunity for a couple ultimate questions if I may, as a very enthusiast user advertising your software around ever since I learned of the fork : 

- Is there or will there be some tutorials or at least links to basic instructions as to how to best refine and tune the new CRT shaders to one's liking ? don't get me wrong, default settings are extremely healthy and neat-looking already but let's say I have a taste for experimentation :D I see there are some comments within their code and global parameters have meaningful names already, and one can figure out step by step by min-maxing values with a dichotomous approach like I did with CRT Lottes" but an actual guide would be an ideal world, if that's not too much asking as a new feature suggestion for 2024 ^^
- I recall reading longer-term features include the addition of sliders allowing for in-game tuning of active shaders , a bit à la Mame or Retroarch, if my understanding is correct. Is it still in the cards ? 

Cheers and a good week ahead,


-G

**Comment by Gryzor1363** [comment]
Oh I'm planning on staying tuned for the long-term considering the software's growing quality in every release :)

Indeed at the end of the day, shaders have always been about individual takes on whatever is the true canon, and in that regard the part of your blog article about people mistaking or arbitrarily choosing a PVM as a supposed benchmark of the purest theoretical form of 8/16 bit gaming in your blog, while game designers themselves never even worked or based themselves upon such screens as a canvas to begin with, perfectly sums it up. 
Now I'm myself a prime example with my "virtual RGB TV screen hooked onto a virtual VGA PC from the late 80s" that I mistook for the "true Dos experience". Memories from childhood are fading and I should have recalled that my VGA gaming days didn't include console or arcade-like thicker, blacker scanlines.

I've make great stride since my last post in familiarizing myself with the adaptive ones from the new release, it's so close to exactly what I want now, opting for Hyllian's was definitely a good call @johnnovak , way simpler to handle than Lottes (despite it being so neat but clearly consolish so technically inauthentic, or at least a representation of non-standard irl setup).

Anyhow, again keep up the great work and thanks for all the replies on that thread, and stay tuned for surprise donations as well :p
