### ISSUE TITLE
Keyboardlayout parameter not being properly handled when codepage is included

### ISSUE THREAD

**Issue by boohyaka** [dosbox-staging/dosbox-staging#3490]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Different version than latest?

0.81.0

### What Operating System are you using?

Windows 11

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Trying to use keyboard layout US with codepage 850, it seems there is a problem with the parsing of the string and assignation to variables, according to a discussion on Discord.

![image](https://github.com/dosbox-staging/dosbox-staging/assets/31538990/fca9a70e-be05-4282-8e60-4d56045dda40)

> yeah, that's a bug
> the code checks for space but forgets to actually separate the value string into layout and codepage 
> open an issue on GitHub
> you can write keyb us 850 into autoexec as a workaround in the meantime

### Steps to reproduce the behaviour.

Explain how to reproduce
1. 
2.
3.

### Provide a Log

```text
2024-03-08 19:53:01.699 | LAYOUT: Failed to load keyboard layout us 850
```

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by NicknineTheEagle** [comment]
Ideally, keyboardlayout parameter should function identically to KEYB command.
