### ISSUE TITLE
crt-auto-arcade setting using wrong shader versions on different resolutions.

### ISSUE THREAD

**Issue by Nikatomix** [dosbox-staging/dosbox-staging#3495]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### What Operating System are you using?

Windows 10

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

When using glshader = crt-auto-arcade setting, DOSBox applies shaders that are mismatched to the monitor/display resolution.

At 1080p the system interface appears to be using "sharp" setting but when in-game switches to the incorrect arcade-1440p shader.
At 1440p the system interface uses arcade-1080p but when in-game switches to the correct arcade-1440p shader.
At 2160p the system interface uses arcade-1440p but when in-game switches to the correct arcade-4k shader.

You can check the log after startup and after launching a game for confirmation.

![Screenshot 2024-03-10 204043](https://github.com/dosbox-staging/dosbox-staging/assets/162900242/608d6ccc-eca5-430a-bccc-431bec8e7973)

### Your configuration

```ini
glshader = crt-auto-arcade
```

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by Nikatomix** [comment]
Was already discussed in: https://github.com/dosbox-staging/dosbox-staging/issues/3334
Sorry.

**Comment by Nikatomix** [comment]
Was already discussed in: https://github.com/dosbox-staging/dosbox-staging/issues/3334
Sorry.

**Comment by johnnovak** [comment]
> Was already discussed in: #3334 Sorry.

No prob. It works correctly as you found out.
