### ISSUE TITLE
Add silent installation support to the Windows installer

### ISSUE THREAD

**Issue by AsciiWolf** [dosbox-staging/dosbox-staging#3496]
It looks like that the exe installer for MS Windows does not support standard [silent installation](https://www.advancedinstaller.com/silent-install-exe-msi-applications.html) switches. Please, consider adding them if possible.

**Comment by shermp** [comment]
Dosbox Staging uses inno setup. Does using the `/SILENT` or `/VERYSILENT` switches (see [here](https://jrsoftware.org/ishelp/index.php?topic=setupcmdline)) work?

**Comment by AsciiWolf** [comment]
It looks like they do not work, at least with the Winget CI automation (see the linked PR) that uses them by default. Sadly, I currently do not have any Windows machine here so I am not able to test it locally.

**Comment by johnnovak** [comment]
PRs are welcome, but personally I'm uninterested in figuring out and testing this. Very niche stuff.

Are you planning to do a 500+ user corporate Staging rollout @AsciiWolf? I'm flattered 😎

**Comment by shermp** [comment]
Honestly, winget might actually be a way around the Windows smart screen stuff that happens when you download staging.

**Comment by AsciiWolf** [comment]
Well, it's not about corporate deployment or even about Winget. Many users, including myself, really do not want to spend time installing their software using a "next-next-next" installers from Windows 98 era that sadly are still a thing on Windows (thanks IT god for MSIX or at least old MSI). Silent installation switches are fortunately a standard thing with most Windows software these days and can be used to make the installation and/or updating a little less crappy using some of the third party tools that allow easy software management by utilizing these switches, or even by automatizing their setups using tools like Ansible. Sure, I understand that this is not a thing for majority of common users, but it is a good and very useful thing to have for advanced ones.

**Comment by johnnovak** [comment]
I'm a "next next next" guy, so again, PRs welcome 😎 But maybe you can already do that with our existing installer with some switches. If you figured it out, let us know 😄

**Comment by AsciiWolf** [comment]
[This](https://private-user-images.githubusercontent.com/114952565/311906018-334fc1f3-2f3f-4990-9b88-6d59d3754f4e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAyMDc0MTAsIm5iZiI6MTcxMDIwNzExMCwicGF0aCI6Ii8xMTQ5NTI1NjUvMzExOTA2MDE4LTMzNGZjMWYzLTJmM2YtNDk5MC05Yjg4LTZkNTlkMzc1NGY0ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxMlQwMTMxNTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05OTVmNjJkMGUyZGE1NmExZjcyNzU5MGE4NjY4MjliMDI5NmMxYjBmZWEzYmM2NWE0NzVkOWY5YWZjODBmMjg2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.k1Cyx9dQ81tth-E8UptGDk8ztx9fgQppOMncoh9LjLQ) is the problem. It looks like it cannot be overridden by any switch.

**Comment by AsciiWolf** [comment]
It looks like the silent installation works correctly after adding `/CURRENTUSER` to install switches. Closing this ticket.
