### ISSUE TITLE
A couple of localisation issues

### ISSUE THREAD

**Issue by johnnovak** [dosbox-staging/dosbox-staging#3498]
The eXoDOS guys raised a few localisation related issues today:

1. The config description of the `language` settings states this: "unset by default; this defaults to English". This does not seem to be true, the language seems to be auto-selected based on the OS settings by default. The config description needs to be updated to reflect this behaviour.
2. Certain characters, such as the Russian alphabet, don't seem to be supported on pre-EGA machine types. It would probably be a good idea to block the transcription to Latin charsets on these machine types, log a warning, and revert back to English.
3. One user has reported that for some reason, Staging detects his environment as French and auto-sets an AZERTY keyboard layout, which is not the layout he has configured at the OS level. The person has a Swiss-French Windows installation with a Swiss-French keyboard layout (QWERTZ), but the language is set to English (UK) in his Windows. A suggestion was made that maybe we should call `GetKeyboardLayout` instead of `GetUserDefaultLocaleName` to auto-determine the keyboard layout in a more reliable way, which seems sensible.

**Comment by Grounded0** [comment]
The Swiss use QWERTZ keyboard layout officially also in the French speaking regions so this is a corner case.

**Comment by boohyaka** [comment]
Hey @Grounded0 just to clarify that we're on the same page:

Yes, the French-speaking part of Switzerland uses QWERTZ. We have our own layout: Swiss-French, or sf. Using keyboardlayout=sf works as expected. German-speaking part has the sg, Swiss-German layout.

That said, not fully sure what you mean by saying it is a corner case, the main issue is that nothing in my setup is set to French on my OS yet I end up with an AZERTY keyboard with autodetection.

- My OS is set to English
- My keyboard layout is set so Swiss-French
- My location is set to Switzerland
- My regional settings are "English - Switzerland"

So from my point of view the issue really boils down to what parameter dosbox (staging) uses to determine the keyboard layout when set to auto. Is it only a matter of the Switzerland location or other regional settings being wrongly mapped to French locale and Azerty keyboard? 

As John mentioned in the first post, getting the active keyboard layout of the host seems like the most sensible approach and better than trying to guess off any other regional setting in my opinion, but maybe I don't see the full picture.

**Comment by Grounded0** [comment]
Don't worry. I pay these guys to sort out these issues. This definitely needs to be sorted out.

By corner case i mean that this could've been easily missed out when creating current implementation. I'll stop interfering now.

**Comment by boohyaka** [comment]
haha! no worries, I get you now.

**Comment by FeralChild64** [comment]
It will take quite some time to handle all the reported locale issues - for example, we can't simply revert the language to English, as the translation system does not support switching the language during runtime, this will have to be added.

In order to detect which script the translation is using (Latin, Cyrillic, Greek, etc.), our Unicode engine needs to know which script the particular letter belongs to - this will be needed nevertheless for constructing the DOS collation tables, but it will take a little time to implement.

The locale detection has to be reworked nevertheless, to properly take care of both POSIX systems (LC_* environment variables) and Windows. Again, quite some (in large part - boring) work.

And so on...

**Comment by johnnovak** [comment]
> As John mentioned in the first post, getting the active keyboard layout of the host seems like the most sensible approach and better than trying to guess off any other regional setting in my opinion, but maybe I don't see the full picture.

I think when this was implemented, people thought using the active layout can be confusing. But I think that's the only correct way—set up the layout automatically that I'm *actually* using, not just whatever my default locale or layout is.

The keyboard layout on Windows 10+ is global now, so this wouldn't be confusing. You need to opt-in to per-window keyboard layouts via some localisation settings in Windows, but those power-users are expected to know what they're doing.

> It will take quite some time to handle all the reported locale issues - for example, we can't simply revert the language to English, as the translation system does not support switching the language during runtime, this will have to be added.

Sure, but could you update the config descriptions first and mention the auto-detection stuff? That should be easy then we could include it in the patch release.

> In order to detect which script the translation is using (Latin, Cyrillic, Greek, etc.), our Unicode engine needs to know which script the particular letter belongs to - this will be needed nevertheless for constructing the DOS collation tables, but it will take a little time to implement.

If it's this complicated, I don't think it's worth it. People will just need to live with it and/or work around it.

> I like the transcription feature... and actually it's handy exactly for such situations where Cyrillic isn't supported - then you can at least read (however awkwardly) via Latin letters.
For when do you say it has to be blocked, e.g. for the [autoexec] section or somewhere else?

Up to @FeralChild64, I guess one half of the people would like it, the other half would hate it. If it's difficult to do and one solution is not clearly superior to the other, maybe just leave it as is @FeralChild64. It's a very niche use case, added lots of code complexity for niche cases is a not a good idea in general.

**Comment by johnnovak** [comment]
I must add that many people in Hungary who grew up with US keyboards in the 80s/90s hate the Hungarian layout with passion. That includes me. The specials symbols are in completely different places, even the Shift + top row number combos are totally different. That's a nightmare for coders especially.

I still only use the Hungarian layout if I write something formal so I misr get the accented characters right. But I switch back to US to type in the special chars 😄 Then in informal messages I don't bother with accents; 99% of the time you can understand the message without the accents. That's what many oldschoop guys still do 🤷🏻

**Comment by FeralChild64** [comment]
OK, I was forced to basically take some break from the development, plus there were more important issues - but now I'm working on the locale problems again. Status of my locale autodetection/synchronization branch: https://github.com/dosbox-staging/dosbox-staging/tree/fc/locale-1:

- for now Linux-only; I still need to write OS-specific Windows and macOS parts
- reworked the way it handles `language`, `country` and `keyboard_layout`, documentation should be up to date
- reworked `KEYB` command (more informative output, better error messages)
- added '--list-layouts' command line option
- problems 1. and 2. should be fixed; problem 3. (https://github.com/dosbox-staging/dosbox-staging/issues/3523) should now not happen on Linux (Windows implementation is still missing)
- I am still planning some minor enhancements and code improvements
- still needs a lot of testing before I can submit the PR

Problems https://github.com/dosbox-staging/dosbox-staging/issues/1925 and https://github.com/dosbox-staging/dosbox-staging/issues/3233 definitely won't be fixed now - they require rework of the code I don't want to rework now, the upcoming PR is already huge.
