### ISSUE TITLE
Save states

### ISSUE THREAD

**Issue by BenMcLean** [dosbox-staging/dosbox-staging#350]
Save states for DOSBOX have [already been made](https://www.vogons.org/viewtopic.php?f=32&t=53116), and they work for most games.

I've thought they should be included in official DOSBOX for years even if they don't have universal game compatibility. Just let people decide for themselves whether to use them or not with a setting to turn them on or off.

**Comment by BenMcLean** [comment]
Ooh, there is [already a branch for the save states](https://github.com/dosbox-staging/dosbox-staging/tree/vogons/save-states-r4176)! Well, now there's also an issue for them. :)

**Comment by dreamer** [comment]
Yeah, but it's pretty problematic topic - that implementation wreaks havoc inside codebase and would make it very hard / practically impossible to develop other improvements… :(

We are discussing this topic in #313, so I'm closing this issue to avoid parallel discussions - I moved your original post in there already :)
