### ISSUE TITLE
Time Warriors (1997), Deus (1996), Ishar 3 (1994), & Robinson's Requiem (1994)

### ISSUE THREAD

**Issue by Python-Exoproject** [dosbox-staging/dosbox-staging#3501]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Different version than latest?

81.0

### What Operating System are you using?

Windows 11

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Straight after the 'Press DEL to enter setup' screen goes away the games crash with the below screenshot.

Time Warriors also crashes in 80.1 and Daum. It works in X, 0.74, and ECE

Deus also crashes in 80.1 and Daum. In X it hardlocks. It works in 0.74, and ECE

Edit: Ive added more notes below with further information and added two more games with similar issue (Ishar 3 and Robinsons Requiem)

![TimeWarriors](https://github.com/dosbox-staging/dosbox-staging/assets/67406191/05cea578-2985-4848-80bd-a5887c5ed07b)

### Steps to reproduce the behaviour.

I used the exodos version of the games. Run with staging, issue happens during loading of the game

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by Python-Exoproject** [comment]
Typical, just as I post it I solve it. Seems the games are sensitive to cycles and the same cycles are not cross compatible between all dosbox forks

**Comment by Python-Exoproject** [comment]
Ive found that the crash only happens during the game boot. You can start the game at 10k and then once youve started gameplay increase the cycles, but there must be someway to make Staging do better than that. Even 0.74 can go up to 55k and boot the game (at 60k 0.74 also crashes with an "Illegal Interrupt" error

**Comment by Python-Exoproject** [comment]
Time Warriors is the same as Deus, however there is an additional problem if I want to move this game over to staging in that the game requires an external tsr called 'cdseek.com' (created by ripsaw I think) to get the CD audio working in game. When testing Staging at 10k I noticed its not working

**Comment by Python-Exoproject** [comment]
Looks like Ishar 3 (1994) is another Silmarils game with this issue. We run the game at 7k cycles which works in X, 0.74, and ECE, but Staging 81.0 crashes with the below error. If you reduce the cycles to 3k Staging will run the game, but thats too slow for the game. Again, you can start at 3k and then increase cycles to 7k once in game but that shouldnt be necessary and wouldnt be a worthwhile tradeoff to switch the game to Staging in exodos.

One interesting thing I found with this one, Staging 80.1 had no problem with the 7k cycles

**Comment by Python-Exoproject** [comment]
One more for the ticket, Robinson's Requiem (1994). It is the same as Ishar 3 (1994), Staging 81.0 will load the game at 3k but we need closer to 20k. Same error message as Ishar 3, and like Ishar 3 Staging 80.1 played the game fine at the higher cycles

**Comment by johnnovak** [comment]
Lots of super useful info @Python-Exoproject, thanks for taking the time to test all this and document your findings.

You haven't mentioned the audio settings, but I assume the problems happen with any audio config, and Silmarils games don't usually have many audio options anyway.

**Comment by johnnovak** [comment]
Ishar 3 crash bisected. It's an easy fix.

This is the offending commit:

```
commit 30bb127916c03794def8c4b9a6c442f561f14865 (HEAD)
Author: kcgen <kcgen@users.noreply.github.com>
Date:   Mon Apr 10 16:00:00 2023 -0700

    Eliminate vgaonly-specific handling in INT10 vertical res case
```

**Comment by johnnovak** [comment]
The root cause is that 0.80.1 and even SVN manifest the bug with `machine=vgaonly`, and we made `vgaonly` the default (always on, effectively).

**Comment by johnnovak** [comment]
We'll treat the Time Warrior CD Audio issue separately @Python-Exoproject 
https://github.com/dosbox-staging/dosbox-staging/issues/3508
