### ISSUE TITLE
Silmarils games with missing intro tone

### ISSUE THREAD

**Issue by Python-Exoproject** [dosbox-staging/dosbox-staging#3504]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Different version than latest?

81.0

### What Operating System are you using?

Windows 11

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

During the intro logo for the listed Silmaril games there is a tone played (OPL channel I think) that doesnt happen when using Staging 81.0

While the single tone itself isnt a big deal, the question is raised, if this tone isnt playing what else might not be playing due to whatever is causing the issue.

Its also odd in that Staging is the only fork that seems to have this issue, 0.74, ECE, Daum, and X all play the sound.

Of the other forks when comparing and investigating, X plays the tone best as there is some pitch change to the note, the other forks just play one constant sound.

The games are:

Transantartica (1993)
Ishar 2 (1993)
Ishar 1 (1992)
Bunny Bricks (1993)
Storm Master (1992)
Boston Bomb Club (1991)
Metal Mutant (1991)
Crystals of Arborea (1990)

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Start game
2. Watch intro and listen for tone
3. Compare to X to hear the tone that should be there

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by johnnovak** [comment]
An interesting problem and we should get to the bottom of it. Thanks for reporting @Python-Exoproject 🖖🏻

**Comment by johnnovak** [comment]
I'm interested in investigating this, so I've assigned it to myself. However, if anyone else wants to go ahead with it, don't let that hold yourself back. I will probably get to this only in a few months' time.

**Comment by johnnovak** [comment]
FYI, the _author_ (!) of Silmarils' DOS sound driver has made a very insightful comment on a related discussion ticket:
https://github.com/dosbox-staging/dosbox-staging/discussions/3467

Hopefully we'll get to the bottom of this soon with his help! 🚀

**Comment by johnnovak** [comment]
Just merged the fix for this @Python-Exoproject. It will be available in the next dev build in the next 30 mins or so.

**Comment by Python-Exoproject** [comment]
@interloper98 As per our discord discussion there was a bit more nuance to this that still needs fixing in Staging. 

For other interested parties, while the current fix adds the tone back in it was just a constant flat (and loud) tone where it should have been changing in volume\pitch. interloper mentioned that it affects sound in some games as well, not just the intro note. Here is an example between X and Staging using Transartica intro tone (zipped as github wont allow audio files):

[Sound.zip](https://github.com/user-attachments/files/15910570/Sound.zip)

Dosbox X does it correctly and interloper has done further investigation and located the issue.

**Comment by Grounded0** [comment]
Closed by:

- #3785

**Comment by Python-Exoproject** [comment]
@interloper98 Brilliant work, thats 8 more games we con move from X to Staging once 82 comes out
