### ISSUE TITLE
Implement seeking in MSCDEX

### ISSUE THREAD

**Issue by johnnovak** [dosbox-staging/dosbox-staging#3508]
**Time Warriors** does not play CD Audio music in the main menu and during gameplay (reported here https://github.com/dosbox-staging/dosbox-staging/issues/3501). Note that CD Audio music _does_ play during the intro sequence.

ripsaw8080 did a fix for the in-game and menu music issue via a TSR, but that doesn't work in Staging. The root cause, however, is that the seek function of the emulated MSCDEX driver is not implemented.

Quoting his description of the issue ([source](https://www.vogons.org/viewtopic.php?p=299150#p299150)):

> The audio tracks are not working because the game is confused by the lack of support for the cdrom driver seek function. Very few games use seek, and this game seems to use it only to convert MSF to HSG sector numbers. It first reads the start sector for a particular track in MSF, calls the seek function with that MSF sector, calls the get position function to get the HSG sector, and finally calls the play function with the HSG sector. Seems pointless to me, but maybe the game developers had some reason to prefer HSG.
>
> The attached workaround program simulates seeks by converting them to zero length plays -- nothing actually plays, but the current position is updated. Run the program in DOSBox before running the game and the audio tracks should work. It also fixes the intro movie in [Alpha Storm](http://www.mobygames.com/game/dos/alpha-storm).

So implementing seek should improve CD Audio support for at least **Time Warriors** and **Alpha Storm**.

I've checked a few DOSBox forks, including X, and none of them implements the seek function, so we'll need to figure this out from scratch.

From `dos_mscdex.cpp`:

<img width="1017" alt="image" src="https://github.com/dosbox-staging/dosbox-staging/assets/698770/0554c15d-8f00-4ccc-be36-06d263c1515d">

Well, no wonder it doesn't work! 😂

**Comment by weirddan455** [comment]
I think I can implement this.  I've hacked on the CD Audio stuff before.
