### ISSUE TITLE
DOS menus from gog releases messed up

### ISSUE THREAD

**Issue by Erick-BR** [dosbox-staging/dosbox-staging#3513]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### What Operating System are you using?

Windows 8

### Whats your question and how can we help?

Hello, some games sold by GOG come with a DOS menu to select game or setup or something else. They have special colors and characters that form a frame around the text. It appears normally with the original dosbox, dosbox-x and even with version 0.80.1 of dosbox staging. This 0.81 update ruined those menus. The characters that form the borders were replaced by ????????... I don't know if it's a bug or just configuration, but I'm asking for your help to resolve this, because this update is fantastic and I don't want to go back to the previous version because of this. I've already changed several things in the configuration file but it didn't help.

Below is a line of these .conf files that forms a border if anyone wants to test on the previous version of dosbox staging to confirm what I'm saying.

ECHO [1;33m[42mÉÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍ»

Sorry my poor english.

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by weirddan455** [comment]
This is because the .conf files are expected to be in UTF-8 format for 0.81.  There was an old issue about this that I can't find at the moment but the solution is to either copy the menu to a .bat file or convert the .conf file to UTF-8.  There's a couple scripts here to help with that, a Windows batch file and a Python script:  https://github.com/dosbox-staging/dosbox-staging/tree/main/contrib/scripts

**Comment by Erick-BR** [comment]
Hi, I opened one theese .conf files on notepad++ and convert it to utf-8. Now I don't see ??????? anymore but special characters as they appear on .conf file. Character "Í" that would be converted do horizontal frame appear as "Í". Character "º" that would be converted do vertical frame appear as "º". They are showing as they are on .conf file.
This same .conf file converted to utf-8 works ok on dosbox or dosbox-x. I see the borders.
Notepad++ already have "utf-8 bom" option, but this causes "illegal command: -c" when confi file is executed.

**Comment by FeralChild64** [comment]
I don't think I understand - do the characters inside the DOSBox look like in the `[autoexec]` section, or are there differences?

**Comment by Erick-BR** [comment]
[dosbox_jazz_single.txt](https://github.com/dosbox-staging/dosbox-staging/files/14607061/dosbox_jazz_single.txt)

I added one of theese .conf files.

**Comment by FeralChild64** [comment]
Looks like wrong conversion to UTF-8. Could you set the code page in Notepad++ to 437 before saving the file as UTF-8? If I see correctly on the screenshots, you have to go to _Encoding_ -> _Character sets_, then probably to _Western European_.

**Comment by Erick-BR** [comment]
Hi, I couldn't find this option for set the code page to 437.

Encoding / character settings / western european shows 
ISO 8859-1
ISO 8859-15
OEM 850
OEM 858
OEM 860 PORTUGUESE
OEM 863 FRENCH
OEM US
WINDOWS 1252

**Comment by Erick-BR** [comment]
![Sem título](https://github.com/dosbox-staging/dosbox-staging/assets/25747613/07091c18-77d2-477c-8378-5b63b935c2b6)

dosbox staging v0.81

![Sem título 2](https://github.com/dosbox-staging/dosbox-staging/assets/25747613/796666c0-9173-4f49-8e3a-9e2f2bbccc79)

dosbox-x
(same .conf)

**Comment by FeralChild64** [comment]
OEM US should probably be the correct one.

**Comment by Erick-BR** [comment]
after set to OEM US and convert to UTF 8 I have this result:

![Sem título 3](https://github.com/dosbox-staging/dosbox-staging/assets/25747613/7f9d8c85-8ae7-4eff-9316-a679380ac839)

There are another free notepad tool to try conversion?
I have 255 conf files organized on my DOS collection. Edit manually is a diffcult task.

**Comment by rderooy** [comment]
As already mentioned, there is a python script and a windows bat file to convert existing/old config files to UTF-8 format.

And no, UTF-8 is the way forward. See also:
https://github.com/dosbox-staging/dosbox-staging/issues/3027

**Comment by johnnovak** [comment]
Use the script to mass update your GOG configs. We included info about this in the release notes:

https://dosbox-staging.github.io/releases/release-notes/0.81.0/#script-to-convert-gog-cp473-config-files-to-utf-8

UTF-8 is the way forward. Ultimately, only GOG could fix this by moving the menu stuff into a .BAT file.

In the grand scheme of things, it's a minor visual issue.

**Comment by johnnovak** [comment]
Closing as we have explained the issue and have provided a solution.
