### ISSUE TITLE
Alpha Storm install script fails to create directories

### ISSUE THREAD

**Issue by weirddan455** [dosbox-staging/dosbox-staging#3517]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### What Operating System are you using?

Linux x86_64

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

The installer for Alpha Storm is just a .bat file.  It contains the following snippet to create new directories if they don't already exist:

```
IF EXIST %1\NUL GOTO D1
MD %1
IF NOT EXIST %1\NUL GOTO FAILURE
:D1
IF NOT EXIST %1\MONS\NUL	MD %1\MONS
IF NOT EXIST %1\OLD_ONES\NUL	MD %1\OLD_ONES
IF NOT EXIST %1\PACS\NUL	MD %1\PACS
IF NOT EXIST %1\SOUNDS\NUL	MD %1\SOUNDS
IF NOT EXIST %1\SPAM\NUL	MD %1\SPAM
IF NOT EXIST %1\SPAM\BASE\NUL	MD %1\SPAM\BASE
IF NOT EXIST %1\SPAM\DARK\NUL	MD %1\SPAM\DARK
IF NOT EXIST %1\SPAM\IMP\NUL	MD %1\SPAM\IMP
IF NOT EXIST %1\SPAM\VARG\NUL	MD %1\SPAM\VARG
IF NOT EXIST %1\SPAM\PIR\NUL	MD %1\SPAM\PIR
IF NOT EXIST %1\TEXAS\NUL	MD %1\TEXAS
IF NOT EXIST %1\YARDS\NUL	MD %1\YARDS
```
The directories fail to get created.  I wrote a stand-alone script to reproduce the problem.  Copy this to `test.bat` and run `test foo`.  Expected result is `C:\FOO` gets created and then `C:\FOO\BAR`.  Instead neither gets created.

```
IF NOT EXIST %1\NUL MD %1
IF NOT EXIST %1\BAR\NUL MD %1\bar
```

I debugged the code starting from `CMD_IF` and the problem is it's matching to a DOS device called `NUL` and returning that the path does exist even when `C:\FOO` does not exist.

### Steps to reproduce the behaviour.

Explain how to reproduce
1.  Run the Alpha Storm install.bat or my 2 line repro script.
2.  Directories do not get created as expected.

### Download URL of affected game or software

https://www.myabandonware.com/game/alpha-storm-bh2

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by johnnovak** [comment]
Huh, what a bizarre edge case! 😅 Good catch @weirddan455!

**Comment by johnnovak** [comment]
> Why does the batch script even need to use `nul`? Wouldn't the script work correctly without needing it?

But that's the script the game uses, and we have a bug here.

**Comment by MasterO2** [comment]
> > Why does the batch script even need to use `nul`? Wouldn't the script work correctly without needing it?
> 
> But that's the script the game uses, and we have a bug here.

It was just an observation on my part that was unrelated to the bug.  Obviously, it's a Dosbox-Staging bug here.

**Comment by weirddan455** [comment]
Did a bit of digging on this.  FreeDOS's COMMAND.COM also has the same behavior because it makes a DOS interrupt that calls `DOS_FindFirst`, same as our `CMD_IF` does.  Found this commented out code which uncommenting fixes the bug:

https://github.com/dosbox-staging/dosbox-staging/blob/a324e46e00414c946fa0dd5e3f874d90a15ac2e2/src/dos/dos_devices.cpp#L391-L393

Code was commented out in c5f2bfe233edf71be0874f113c796bf01d1bf3c7 (merge commit from DOSBox SVN around 2 years ago).

>  Specified path can be invalid if filename is a device. Fixes installer for World Series of Poker.

I guess I can test the installer for that game and see if putting this check back in breaks it.

**Comment by weirddan455** [comment]
The only World Series of Poker I could find is a Windows 3.1 game and I don't have that setup.

Btw @MasterO2 the usecase of using `NUL` in scripts like this is to detect if the path is a directory.  `IF EXISTS FOO` returns true if `FOO` is a directory or a file.  `IF EXISTS FOO\NUL` only returns true if it is a directory.

**Comment by MasterO2** [comment]
> The only World Series of Poker I could find is a Windows 3.1 game and I don't have that setup.
> 
> Btw @MasterO2 the usecase of using `NUL` in scripts like this is to detect if the path is a directory. `IF EXISTS FOO` returns true if `FOO` is a directory or a file. `IF EXISTS FOO\NUL` only returns true if it is a directory.

Thanks for explaining that.  

Is `NUL` often used like that in DOS batch files?

**Comment by johnnovak** [comment]
> Is `NUL` often used like that in DOS batch files?

I'd say it's extremely rare.
