### ISSUE TITLE
Build fails with LTO

### ISSUE THREAD

**Issue by eli-schwartz** [dosbox-staging/dosbox-staging#3519]
I tried to build with the following *FLAGS to optimize the build: `-flto=4 -Werror=odr -Werror=lto-type-mismatch -Werror=strict-aliasing`

Note the -Werror=* flags are used to help detect cases where the compiler tries to optimize by assuming UB cannot exist in the source code -- if it does exist, ordinarily the code would be miscompiled, and this says to make the miscompilation a fatal error.

I got this error:
```
FAILED: dosbox 
x86_64-pc-linux-gnu-g++  -o dosbox dosbox.p/meson-generated_.._version.cpp.o dosbox.p/src_main.cpp.o dosbox.p/src_dosbox.cpp.o dosbox.p/src_libs_ghc_fs_std_impl.cpp.o -flto -Wl,--as-needed -Wl,--no-undefined -Wl,-Map,dosbox.map -Wl,--Map,dosbox.map -rdynamic -march=native -fstack-protector-all -O2 -pipe -fdiagnostics-color=always -frecord-gcc-switches -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=3 -fstack-clash-protection -Werror=odr -Werror=lto-type-mismatch -Werror=strict-aliasing -Wformat -Werror=format-security -Wl,-O1 -Wl,--as-needed -Werror=odr -Werror=lto-type-mismatch -Werror=strict-aliasing -Wl,--defsym=__gentoo_check_ldflags__=0 -Wl,--start-group src/misc/libmisc.a src/libs/loguru/libloguru.a src/libs/whereami/libwhereami.a src/capture/libcapture.a src/libs/zmbv/libzmbv.a src/cpu/libcpu.a src/dos/libdos.a src/libs/decoders/libdecoders.a src/fpu/libfpu.a src/gui/libgui.a src/hardware/libhardware.a src/libs/nuked/libnuked.a src/libs/residfp/libresidfp.a src/libs/YM7128B_emu/libym7128bemu.a src/ints/libints.a src/midi/libmidi.a src/shell/libshell.a src/libs/sdlcd/libsdlcd.a src/libs/tal-chorus/libtalchorus.a src/libs/manymouse/libmanymouse.a -lstdc++fs /usr/lib64/libSDL2.so -pthread /usr/lib64/libiir.so -lstdc++fs -ldl /usr/lib64/libpng16.so /usr/lib64/libz.so /usr/lib64/libopusfile.so /usr/lib64/libGL.so /usr/lib64/libspeexdsp.so /usr/lib64/libfluidsynth.so /usr/lib64/libasound.so /usr/lib64/libXi.so -Wl,--end-group
../dosbox-staging-0.81.0/include/fraction.h:31:7: error: type ‘struct Fraction’ violates the C++ One Definition Rule [-Werror=odr]
   31 | class Fraction {
      |       ^
../dosbox-staging-0.81.0/src/hardware/imfc.cpp:520:8: note: a different type is defined in another translation unit
  520 | struct Fraction {
      |        ^
../dosbox-staging-0.81.0/include/fraction.h:170:17: note: the first difference of corresponding definitions is field ‘num’
  170 |         int64_t num   = 0;
      |                 ^
../dosbox-staging-0.81.0/src/hardware/imfc.cpp:521:17: note: a field with different name is defined in another translation unit
  521 |         uint8_t value = 0;
      |                 ^
../dosbox-staging-0.81.0/src/hardware/virtualbox.cpp:137:12: error: type ‘ReturnCode’ violates the C++ One Definition Rule [-Werror=odr]
  137 | enum class ReturnCode : uint32_t {
      |            ^
../dosbox-staging-0.81.0/src/ints/bios_pci.cpp:44:12: note: a type with different precision is defined in another translation unit
   44 | enum class ReturnCode : uint8_t {
      |            ^
../dosbox-staging-0.81.0/src/hardware/input/keyboard.cpp:68:12: error: type ‘Command’ violates the C++ One Definition Rule [-Werror=odr]
   68 | enum class Command : uint8_t { // PS/2 keyboard port commands
      |            ^
../dosbox-staging-0.81.0/src/hardware/input/mouseif_ps2_bios.cpp:79:12: note: an enum with different value name is defined in another translation unit
   79 | enum class Command : uint8_t { // PS/2 AUX (mouse) port commands
      |            ^
../dosbox-staging-0.81.0/src/hardware/input/keyboard.cpp:70:9: note: name ‘SetLeds’ differs from name ‘SetScaling11’ defined in another translation unit
   70 |         SetLeds              = 0xed,
      |         ^
../dosbox-staging-0.81.0/src/hardware/input/mouseif_ps2_bios.cpp:81:9: note: mismatching definition
   81 |         SetScaling11  = 0xe6,
      |         ^
../dosbox-staging-0.81.0/src/hardware/virtualbox.cpp:137:12: error: type ‘ReturnCode’ violates the C++ One Definition Rule [-Werror=odr]
  137 | enum class ReturnCode : uint32_t {
      |            ^
../dosbox-staging-0.81.0/src/ints/bios_pci.cpp:44:12: note: an enum with different value name is defined in another translation unit
   44 | enum class ReturnCode : uint8_t {
      |            ^
../dosbox-staging-0.81.0/src/hardware/virtualbox.cpp:138:9: note: name ‘ErrorNotImplemented’ differs from name ‘Successful’ defined in another translation unit
  138 |         ErrorNotImplemented = (UINT32_MAX + 1) - 12,
      |         ^
../dosbox-staging-0.81.0/src/ints/bios_pci.cpp:45:9: note: mismatching definition
   45 |         Successful        = 0x00,
      |         ^
lto1: some warnings being treated as errors
lto-wrapper: fatal error: x86_64-pc-linux-gnu-g++ returned 1 exit status
compilation terminated.
/usr/lib/gcc/x86_64-pc-linux-gnu/13/../../../../x86_64-pc-linux-gnu/bin/ld: error: lto-wrapper failed
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
```

Originally reported downstream: https://bugs.gentoo.org/926078
Full build log: [build.log](https://github.com/dosbox-staging/dosbox-staging/files/14630636/build.log)

**Comment by johnnovak** [comment]
@eli-schwartz Just compile with the same flags we use in our CI workflows?

I'm sure this can be fixed easily, so if this is important to you, PRs are welcome.

**Comment by eli-schwartz** [comment]
> @eli-schwartz Just compile with the same flags we use in our CI workflows?

The flags you use in your CI workflows don't check for and require errors in cases where the compiler stress-tests the optimizer and starts detecting additional cases of Undefined Behavior that can crash at runtime. (Optimizer passes such as LTO are really quite good at causing pre-existing issues to become detectable.)

What we've done instead for Gentoo is mark dosbox-staging as not LTO-safe, which means people trying to compile the system with global LTO will have their LTO flags silently dropped for dosbox-staging. Without LTO optimization passes, it's much less likely to produce runtime crashes.

> I'm sure this can be fixed easily, so if this is important to you, PRs are welcome.

I'm not in a huge rush. I've been chasing down issues in dozens of packages trying to resolve several years worth of backlog, figuring out which ones are not solved by newer versions of the upstream software, and filing bugs with the upstream projects where applicable.

I don't always have time to also implement fixes, especially given that some fixes require getting to know the codebase a bit in order to know which of several possible solutions are the correct solution, and it's not always obvious when that is the case vs when the fix is trivial.

My hope is that as long as the upstream projects are aware of the issue, they can fix it at their own pace and in their own time, probably better than I can. :)

**Comment by johnnovak** [comment]
@eli-schwartz That's fine, I guess what I'm saying is we're not particularly interested in such issues if they don't affect our normal builds.

**Comment by eli-schwartz** [comment]
I just wanted to clarify -- the issues DO affect your normal builds.

Your normal builds include several builds with LTO, and do have UB in them, which may or may not lead to runtime nasal demons or other failures. It's very difficult to know whether they lead to runtime issues since this is prone to change arbitrarily between compilers, and between bugfix releases of a compiler.

You aren't detecting them and failing the build, but they do exist.

I think you meant that they don't affect your normal "build statuses", not your normal "builds", which is a fair point as these issues don't, in fact, block CI.
