### ISSUE TITLE
RAYMAN CD: game crashed at start

### ISSUE THREAD

**Issue by legluondunet** [dosbox-staging/dosbox-staging#352]
Hello,
I just tried last Dosbox-staging git version from today and I have an issue with RAYMAN DOS CD:
game crashed at start

I joined you error messages and my conf file.
[rayman_dosbox.zip](https://github.com/dosbox-staging/dosbox-staging/files/4589868/rayman_dosbox.zip)

![Capture d’écran de 2020-05-07 00-56-17](https://user-images.githubusercontent.com/325405/81236522-acfd4a00-8ffd-11ea-8cad-da8c786aadbe.png)

Thank you for your help.

**Comment by legluondunet** [comment]
I tested Rayman Forever GOG, similar error messages:

![Capture d’écran de 2020-05-07 01-29-37](https://user-images.githubusercontent.com/325405/81238436-61996a80-9002-11ea-874c-4f9fb55132a6.png)

But this time the crash happened after animation/before access to main menu.

**Comment by kcgen** [comment]
Thanks for the report @legluondunet. 

I'm unable to reproduce this with Rayman CD (I have the Eupo and JP versions).  

Here's how I run it.  First, I rip it to ISO + FLAC audio tracks, install it to`C:\rayman`, and configure it with Gravis audio.

I use a local `dosbox.conf` inside the game's directory (I've included SDL and joystick settings just for completeness here, which you might want to change):

``` ini

[sdl]
fullscreen = true
windowresolution = 960x800
output     = texturepp

[render]
aspect   = false
scaler   = none
glshader = none

[cpu]
core=dynamic
cycles=fixed 15000
cputype=auto

[dosbox]
machine= svga_s3
memsize=8

[mixer]
nosound=false
rate=44100
blocksize=2048
prebuffer=20

[midi]
mpu401=none
mididevice=none

[gus]
gus=true
gusrate=44100
gusbase=240
gusirq=5
gusdma=3

[dos]
xms=true
ems=false
umb=true

[speaker]
pcspeaker=true
tandy=off
disney=false

[sblaster]
sbtype=none

[joystick]
joysticktype = none

[autoexec]
mixer gus 400:400
```

I then launch it using this `start.bat` batch file:

@echo off
imgmount d cd\opus\cdrom.cue -t iso > NUL
d:
cd \rayman
rayman.exe save=c:\rayman
mount -u d
exit

**Comment by legluondunet** [comment]
@kcgen I can reproduce this issue with dosbox-svn (I just compiled it). So it is not a dosbox-staging only issue. I tested your conf and it works. In this moment I'm trying different tests to understand why your conf works and not mine. My conf was compatible with Dosbox-CE.

**Comment by legluondunet** [comment]
@kcgen could you explain me why you use gravis sound instead of sound blaster? With Dosbox using Sound Blaster 16 music card generally always works.

ANother thing:
why are you using
`mount -u d`
`mixer gus 400:400` outside the gus dosbox.conf file

Thanks

**Comment by dreamer** [comment]
@legluondunet I'm really confused about this - for me both your config and @kcgen's work… both result in way too fast game though (visible only once map loads). The settings I were using during testing are:
```
[sdl]
fullscreen       = true
fullresolution   = desktop
output           = opengl

[render]
aspect   = true
scaler   = none
glshader = sharp

[cpu]
core    = dynamic
cycles  = fixed 15000
cputype = auto

[dosbox]
machine = vgaonly
memsize = 8

[dos]
xms = true
ems = false
umb = true
```
(+my personalized `autoexec` section; I was testing in dosbox-staging only)

**Comment by legluondunet** [comment]
my Rayman CD version EU:
$ md5sum rayman/ray.lng 
76476102aca1137300e48dcc7714cbb8  rayman/ray.lng

Now, could you try this steps to reproduce this is what I think is a compatibility issue:

use the config file joined to this comment, it is a generic Dosbox config file mostly use by GOG. It uses Sound Blaster (not gus) and opengl, you just need to change imgmount command.

Now press 2 (install).
It will launch install.bat from Rayman CD.
Choose a soundblaster card.
At the end of the install choose play....

Normally we don't need to change the .bat file as it is automatically generated by setup program.

[rayman_dosbox.zip](https://github.com/dosbox-staging/dosbox-staging/files/4592720/rayman_dosbox.zip)

**Comment by legluondunet** [comment]
Ok I found the cause of this issue and I tried to explain it with my little english knowledge:
I tried to launch a DOS Rayman install with dosbox-staging.
But the game was install with dosbox-ce.
--> it don't work (see error messages above).
I just reinstalled DOS CD and GOG version from scratch with dosbox-staging and everything works as expected.
I close this issue.

**Comment by dreamer** [comment]
Tested exactly your file .conf (only with path to cue adjusted), decided to backup my installation and create a new one so default .bat file is kept in place (nothing unexpected inside, looks exactly the same as my autoexec earlier).

- selected card "sound_blaster" option (IRQ 7 / port 220 / dma 1) - test sound is extremely quiet, but in-game works fine
- selected option "autodetect" (on 3rd "page") - it picks: "SB16", IRQ 7, PORT 220, DMA 5 (which is in-line with settings inside .conf file) - it works as well (test sound and in-game)
- selected option "sbpro" (IRQ 7 / port 220 / dma 1) - still works (test sound and in-game)

Tested option `sound_blaster` with DOSBox 0.74-3 - worked as well (but I have usual input issues and can't use cursor keys, need to use numeric keyboard for menu navigation :/).

**Comment by dreamer** [comment]
> But the game was install with dosbox-ece.
> --> it don't work (see error messages above).
> I just reinstalled DOS CD and GOG version from scratch with dosbox-staging and everything works as expected.
> I close this issue.

Oh, this is important information to us! Thank you! :) IIRC ECE had some patches designed to improve filesysystem compatibility for Windows 95 (if I don't confuse old discussions) - whenever touching filesystem-related changes from ECE we need to be extra careful.

**Comment by kcgen** [comment]
> both result in way too fast game though (visible only once map loads)

@dreamer , you've mentioned this runaway or unthrottled-type game play a couple times; does it only happen using the `texture*` outputs? where as the `opengl*` behave correctly? 

I wonder if this is a common issue with the `texture*` video-flow under Wayland, or if it's something unique to your setup/configuration.
