### ISSUE TITLE
A follow-up to my two previous tickets regarding upscaling glshaders like DOSBox-X's xbr-lv3.glsl in VGA apps on 0.81

### ISSUE THREAD

**Issue by CitricTabby** [dosbox-staging/dosbox-staging#3520]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### What Operating System are you using?

Windows 11

### Whats your question and how can we help?

@johnnovak @joncampbell123 

I just solved my own problem regarding the xbr-lv3.glsl GL shader based inconsistency being put into 0.81 straight from my DOSBox-X portable install while running 256 color games like my purchased GOG copy of Indiana Jones and the Last Crusade.

At the beginning of the parameter lines of xbr-lv3.glsl as I edit it via BowPad (my everyday text file app), if I added the four lines
#pragma use_srgb_texture
#pragma use_srgb_framebuffer
#pragma force_single_scan
#pragma force_no_pixel_doubling

I'd get a picture like this (see the blurred text on the bottom half):
![Screenshot 2024-03-18 002449](https://github.com/dosbox-staging/dosbox-staging/assets/159926831/eb48aaad-acae-4c58-95a7-9bf4f16cf569)
![Screenshot 2024-03-18 002501](https://github.com/dosbox-staging/dosbox-staging/assets/159926831/d2ba6109-2407-4ce1-b1a6-fd8001a5b5e3)
![Screenshot 2024-03-18 002519](https://github.com/dosbox-staging/dosbox-staging/assets/159926831/0e727781-6080-4443-ab30-aa57b21bd925)

But if I exclude the two lines #pragma use_srgb_texture and #pragma use_srgb_framebuffer from xbr-lv3.glsl, the results are better (see all of the ingame text consistency across the board):
![Screenshot 2024-03-18 000511](https://github.com/dosbox-staging/dosbox-staging/assets/159926831/048cccef-77bb-42de-8375-ea3f3d7fb811)
![Screenshot 2024-03-18 000525](https://github.com/dosbox-staging/dosbox-staging/assets/159926831/b3417393-35b6-452f-a768-de106a26b4f9)
![Screenshot 2024-03-18 000537](https://github.com/dosbox-staging/dosbox-staging/assets/159926831/ef0f06f5-744e-4740-a2da-334b43e1edb1)

At least this means I can find some closure to this VGA upscaling shader inconsistency conundrum.

BTW thanks for your help, and keep up the great work on this spiritual successor to the legendary DOSBox!

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by johnnovak** [comment]
Glad you solved it @CitricTabby. Yes, that makes sense as these older shaders assume "technically incorrect" non-sRGB-aware interpolation.
