### ISSUE TITLE
Gold of the Aztecs, The (1990)

### ISSUE THREAD

**Issue by Python-Exoproject** [dosbox-staging/dosbox-staging#3524]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Different version than latest?

81.0

### What Operating System are you using?

None

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Another game with graphics flicker. Its pretty bad for this one, but its mostly during the intro if you let it run and if you slect the map in gameplay.

This time Daum doesnt improve things. Staging with a dos_rate of 140 helps while still being playable, but it takes dos_rate of 280 to fix it and that causes other issues like hiccups in the displaying of the graphics.

It would be interesting to add this to the games to check on hardware @johnnovak as Daum didnt fix it which means it might not be the same issue as #2950 #2949 #3244 #2905

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Load game, watch intro
2.
3.

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by MX9000** [comment]
@Python-Exoproject doing more tests in the meantime, I found that by setting cycles=20000 the flickering disappears!

**Comment by Python-Exoproject** [comment]
Great job @MX9000. 

I wouldnt think a game from 1990 would need that many cycles though. I have managed success with only 8500.

Looks like this one can be closed @johnnovak

**Comment by johnnovak** [comment]
> Great job @MX9000.
> 
> I wouldnt think a game from 1990 would need that many cycles though. I have managed success with only 8500.
> 
> Looks like this one can be closed @johnnovak

@Python-Exoproject 
It is possible to completely get rid of the flicker with the new `vmem_delay` option.

See the details and the config to fix the game here: https://www.vogons.org/viewtopic.php?t=89650
