### ISSUE TITLE
Text mode double scanning regression in Indenture v1.7

### ISSUE THREAD

**Issue by W-Livi** [dosbox-staging/dosbox-staging#3536]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### What Operating System are you using?

Windows 10

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Indenture is a game which runs in an 80x25 text mode, using a customized 8x8px character set.
DOSBox Staging seems to present this game with twice the intended vertical resolution, squishing the gameplay into the upper half of the screen while the lower seemingly exposes some sort of buffer. Said buffer starts out all black, but at certain times (including dark mazes and victory fanfare) the current room will get drawn there, blinking rapidly and offset about 48 characters to the right.

### Steps to reproduce the behaviour.

Explain how to reproduce
1. launch indentur.com
  - the DOSBox status window will report a 640x400 text mode, when it should be 640x200
  - the title screen will immediately occupy only the top half of the screen
2. hit F3 twice to select a game 2
3. hit F4 to begin
4. with the cursor keys, navigate one screen south, east, and south again.
  - this will take you to the nearest dark maze, causing the room's layout to flicker on the lower half of the screen

### Download URL of affected game or software

https://archive.org/details/IndentureV1.71996CraigPellAdventure

### Your configuration

```ini
behavior observed with default config
```

### Provide a Log

```text
2024-03-23 15:20:21.298 | DISPLAY: VGA 640x400 16-colour text mode at 70.086 Hz throttled VFR, scaled to 1600x1200 pixels with 1:1.2 (5:6) pixel aspect ratio
```

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by Grounded0** [comment]
Try changing value `vga_8dot_font` to `true`.

We're currently defaulting to 9x9 px fonts so it could cause this.

**Comment by johnnovak** [comment]
This is a legitimate regression and @W-Livi was right, the game uses a non-standard 640x200 text mode with double scanning. Fixing.

**Comment by johnnovak** [comment]
Many thanks for the valuable report @W-Livi. Double scanned text modes are extremely rare, so now at least we have a single test case for this 🎉 

This will be fixed in https://github.com/dosbox-staging/dosbox-staging/pull/3568
