### ISSUE TITLE
Multiplied intro video in Afterlife

### ISSUE THREAD

**Issue by shitsux420** [dosbox-staging/dosbox-staging#3541]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### What Operating System are you using?

Windows 10

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

The LucasArts logo intro video in Afterlife has itself multiplied relating to what resolution has been set via the setup program.

640x480:
![afterlife640](https://github.com/dosbox-staging/dosbox-staging/assets/74032044/18831734-e600-4839-a03b-751c6b9070a5)

800x600:
![afterlife800](https://github.com/dosbox-staging/dosbox-staging/assets/74032044/c1c35092-a255-4eab-85a4-72333ccebb6e)

1024x768:
![afterlife1024](https://github.com/dosbox-staging/dosbox-staging/assets/74032044/cd56da21-c946-4d34-abca-95db82353cad)

DOSBox settings doesn't seem to affect it. Tried different `core`, `cputype` and `cycles`. For `machine` tried normal svga_s3 with VBE 2.0 and vesa_oldvbe with VBE 1.2 by itself and with UNIVBE driver.

Possibly related to issue #3416?

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Install game with Large installation, choose any video resolution, configure sound for SB16.
2. Start the game with AFTERDOS.BAT.
3. Observe the intro video.

### Your configuration

```ini
Didn't seem to matter
```

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by weirddan455** [comment]
Are you sure this isn't how the intro is supposed to look?  Behavior is the same on current main and v0.80.1.  I found this 10 year old video showing the same (not exactly proof, they could have been recording from an old Dosbox version).

https://www.youtube.com/watch?v=KySWr71nxfI

It looks intentional to me.  Would be useful if someone could prove otherwise.

**Comment by Grounded0** [comment]
This is actually how the intro should be looking. Try changing the game resolution to see how the multiplication is either increased or reduced.

**Comment by johnnovak** [comment]
What makes you think, @shitsux420 (what a handle, LOL), that this is not intentional? I'm almost certain it's intentional and I'm too lazy to test on hardware... But this can't be a bug, everything looks correct, there are no glitches or artifacts, etc. Please prove it's a bug then we're talking.

**Comment by shitsux420** [comment]
I certainly thought it was a bug due to the way it looked since I felt it doesn't make any sense for the video to be repeated like that, plus the [YouTuber LGR's retrospective video on the game shows it only once](https://youtu.be/-azFNwF6fa0?si=_M1dKjwy3pLYiIAi&t=105), and he always uses footage recorded from actual hardware for his content unless stated differently. Other videos on YT most likely run the game via DOSBox, so either it really isn't a bug or it's a very longstanding one.

I guess someone else would have to run the game on real perioid correct hardware to verify.

**Comment by johnnovak** [comment]
Cheers @shitsux420. It's a bit suspicious at least, and it's inclear what display res the LGR guy is using in his video, so reopening and adding a tag for myself to test on hardware at some point.

**Comment by Burrito78** [comment]
I reported this on Aaron Giles DREAMM emulator as a bug too but he told me it's supposed to be this way!
Anyone can test this using latest DREAMM official release.

**Comment by Burrito78** [comment]
![Bildschirmfoto 2024-03-27 um 14 20 48](https://github.com/dosbox-staging/dosbox-staging/assets/61995128/5029ccbd-9f05-4054-85cb-cbb9a81d2dc6)
![Bildschirmfoto 2024-03-27 um 14 20 32](https://github.com/dosbox-staging/dosbox-staging/assets/61995128/43e2948a-ac71-4717-b5c3-3351f957c8cd)
![Bildschirmfoto 2024-03-27 um 14 20 14](https://github.com/dosbox-staging/dosbox-staging/assets/61995128/e96ff295-f4bc-4d4a-af49-e775f42f2b90)

**Comment by shitsux420** [comment]
I tested this in 86Box using various videocard configurations with various VBE 2.0 extension programs and they all repeat this "bug". So pending someone testing this in actual hardware I'm leaning towards it supposed to be this way too.

Perhaps the issue is instead in the UNIVBE.DRV driver the game ships with? AFTERDOS.INI too contains a `BIOS           = Auto` line, but not knowing it's syntax it's impossible to know what could be configured there.

**Comment by johnnovak** [comment]
@shitsux420 Aaron Giles worked at LucasArts, so I tend to trust his judgement on this. However, now I will test this on my MNX box in my next hardware testing roundup just for the lulz. Let's keep it open until then.

**Comment by Grounded0** [comment]
If we see similar behaviour in Windows or Mac OS versions of this game we can close this.

**Comment by johnnovak** [comment]
> If we see similar behaviour in Windows or Mac OS versions of this game we can close this.

Yeah, good call. I have low inclination to test this on hardware, and I'm pretty sure this is authentic and correct behaviour.

**Comment by Grounded0** [comment]
I'm going to install this on Mac OS 8.6 in 24 hours and if I get the same result I'm going to close this.

**Comment by Grounded0** [comment]
<img width="1392" alt="Screenshot 2024-07-17 at 6 04 34" src="https://github.com/user-attachments/assets/f79c6eb8-b9c4-49ae-bc6e-6e2f2e17bfd3">

**Comment by johnnovak** [comment]
Thanks @Grounded0 for confirming. As I thought.
