### ISSUE TITLE
Millionaire - The Stock Market Simulation (1982) only runs in vanilla dosbox 0.73

### ISSUE THREAD

**Issue by Python-Exoproject** [dosbox-staging/dosbox-staging#3543]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Different version than latest?

81.0

### What Operating System are you using?

None

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Another interesting one. Only vanilla dosbox 0.73 will run this game. Any other fork or even later vanilla dosbox builds will freeze. Something obviously changed between vanilla 0.73 and 0.74 which was also inherited by Staging.

Weird as its not a complicated game, it doesnt even have graphics

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Start the game
2. When 'Pro.exe" runs dosbox will freeze
3.
4.

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by Python-Exoproject** [comment]
Tested some other vanilla dosbox releases:

Earlier than 0.70 the game freezes during boot. Starts working in 0.70 and continues to work with 0.71, 0.72, and 0.73. In 0.74 though the freeze on boot appears again

**Comment by codengine** [comment]
I tested all 3 versions that I have here, they all stem from Total DOS and they work flawlessly in 0.81.1.
@Python-Exoproject Which version did you use?

**Comment by Python-Exoproject** [comment]
Version 2.0 is the one in eXoDOS. I can confirm that it looks like the issue was with the copy in eXoDOS and that it was indeed the copy protection as when I replaced the current exodos exe with the cracked one from the TDC copy it worked.

Thank you again, its so good to be able to close these off

Release 2 is also in eXoDOS as its different enough to keep both versions due to the interface

**Comment by johnnovak** [comment]
Great testing @codengine, this was super helpful! 🏅
