### ISSUE TITLE
Remove SDL CD dependency

### ISSUE THREAD

**Issue by weirddan455** [dosbox-staging/dosbox-staging#3548]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### What Operating System are you using?

None

### Is your feature request related to a problem? Please describe.

I plan on doing this myself soon.  Just wanted to make a ticket to document what needs to be done.  The SDL CD library has problems and is unmaintained.  I would like to drop it from the codebase.

### Describe the solution you'd like

1. Write OS specific functions to scan the host for CD drives on startup and store them in a list.  This is the only functionality from SDL CD that Linux depends on.  This SDL CD function is also called once in `program_mount.cpp` and  once in`dos_mscdex.cpp`
2. Write a class implementing `CDROM_Interface` that uses the Win32 API.  This should read digital audio data from the CD drive and push it through the DOSBox mixer.  SDL CD bypasses our mixer.
3. Remove the `CDROM_Interface_SDL` class and remove the library from `src/libs/sdlcd`
4. If someone cares enough, they can write an implementation for Mac.  Apparently SDL CD has been broken on Macs for a long time and no one seems to mind.  Probably most Macs these days don't have CD drives.

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by johnnovak** [comment]
Sounds like a good plan @weirddan455.

**Comment by weirddan455** [comment]
After thinking about this more, I think we should just get rid of the "scan and list CD drives" thing that SDL CD does and also remove the `-usecd` flag from the `mount` command.

Instead, we can just auto-detect the device.  In Windows, `mount d d:\ -t cdrom` already works without the flag.  In Linux, you specify the mount point like `mount d /mnt/cdrom -t cdrom` and the device ex. `/dev/sr0` is not known.  However, we can just parse `/proc/mounts` to get the name of the device and do an `ioctl` call to test if it is a CD drive.

This would be both more user friendly and handle the case where a user plugs in a USB drive while DOSBox is running.

**Comment by FeralChild64** [comment]
Yeah, I imagine the USB optical drives will get more common. Majority of PC cases does not even have a 5.25” slot anymore.

**Comment by johnnovak** [comment]
> Yeah, I imagine the USB optical drives will get more common. Majority of PC cases does not even have a 5.25” slot anymore.

Not _my_ PC case! Antec P183 😎 🤘🏻 

![image](https://github.com/dosbox-staging/dosbox-staging/assets/698770/84c44546-0d96-4764-a70a-ed9ef56ab958)

(But I'm using an USB DVD drive with it once in a blue moon... 😆)

**Comment by johnnovak** [comment]
> After thinking about this more, I think we should just get rid of the "scan and list CD drives" thing that SDL CD does and also remove the `-usecd` flag from the `mount` command.
> 
> Instead, we can just auto-detect the device.

All such streamlining is welcome @weirddan455. We should always try to keep the number of switches, toggles, options, etc. to the minimum if there is a better automatic option.

**Comment by johnnovak** [comment]
> Good idea.
> 
> > Probably most Macs these days don't have CD drives.
> 
> Agree. Not a Mac user and I don't know how feasible it is to accommodate, but I see even Apple still sells a [USB drive](https://www.apple.com/shop/product/MD564LL/A/apple-usb-superdrive). I mention that just because elsewhere it seems Staging strives to behave similarly on the different platforms.

Yeah, we try hard to. CD Audio support is admittedly a bit of an outlier, but I guess we did not want to reject the Windows-only CD Audio patch when someone restored support (given 99% of Staging users are on Windows).

**Comment by Grounded0** [comment]
Optical drives have been de facto dead on the Mac for a long, long time. That's final things Steve Jobs killed before dying.
