### ISSUE TITLE
Add support for Haiku OS

### ISSUE THREAD

**Issue by 0xtrzy** [dosbox-staging/dosbox-staging#355]
?

**Comment by kcgen** [comment]
@0xtrzy , I'm assuming you have a system running Haiku OS?

If so, can you check if the following packages are available:
- autotools suite (autoconf, automake)
- pkgconfig
- GCC (version 5 or greater; ideally 9.x), or
- Clang (ideally version 8 or greater)
- SDL2 (main package and/or library)
- SDL2 Net (addon-library for SDL2)
- Opusfile (an API wrapper that uses the opus and ogg libraries)

If so, go ahead and try to install them.  Then we move onto the next step and try building.

**Comment by kcgen** [comment]
I installed the latest build of Haiku, which came nicely equipped with the core GNU dev stack (gcc 8.3, autotools, git, make, etc). 

According to SDL2's documentation, it should build straight-away per their documentation: 

https://wiki.libsdl.org/Installation#Haiku

Configuration works, but the build fails half-way through:
 
![VirtualBox_Haiku_07_05_2020_23_05_40](https://user-images.githubusercontent.com/1557255/81375928-5bb19100-90b7-11ea-8f38-cba49d1335e7.png)

@0xtrzy , can you follow the SDL2 steps above, and see if you can also reproduce this issue? (If yes, next step would be opening an issue w/ the SDL2 team).

**Comment by kcgen** [comment]
@0xtrzy ,

I've added basic Haiku build support; try this in your Terminal:

Clone and checkout the Haiku specific branch: 

`git clone --depth 1 https://github.com/dosbox-staging/dosbox-staging --single-branch --branch kc/haiku-build-1`

Next follow from Step 2 onward, in these notes: 

https://github.com/dosbox-staging/dosbox-staging/blob/kc/haiku-build-1/scripts/build.md#haiku-installation

I was only able to run inside a VM, so my renderer backend was empty:

![Screenshot at 2020-05-08 14-49-28](https://user-images.githubusercontent.com/1557255/81454017-f3f35880-913f-11ea-935f-9b5b15d8e7d0.png)

Hopefully you will have better luck under actual hardware; let us know how it goes!

**Comment by kcgen** [comment]
The above `build.md` notes mention switching to `core = normal` in your config file. 
However, if the `dynamic` core is used, it crashes Haiku's kernel:

![Screenshot at 2020-05-08 14-46-08](https://user-images.githubusercontent.com/1557255/81454466-3e290980-9141-11ea-98a0-0dd7d86e5757.png)

**Comment by dreamer** [comment]
@0xtrzy Issue got closed automatically with PR introducing build instructions for Haiku. Exact instructions can be found in file `scripts/build.md`.

Unfortunately, we are unable to include this OS in our CI at this time, so we will need Haiku OS community to help us with packaging and distributing builds. We will also gladly accept PR with fixes/improvements for Haiku (as long as they won't introduce regressions for other OSes).

If you have any specific needs/questions - start a new thread, please :)
