### ISSUE TITLE
`INTRO` cannot be launched if a new `COMMAND.COM` is started

### ISSUE THREAD

**Issue by johnnovak** [dosbox-staging/dosbox-staging#3550]
As the title says.

A very minor issue, but it might point to bigger problems with either our INTRO or shell implementations.

**Comment by weirddan455** [comment]
Looks like this is intentional:

https://github.com/dosbox-staging/dosbox-staging/blob/ed557435564b23644f1bb5f23e7d6e794cadd2d6/src/dos/program_intro.cpp#L78-L79

**Comment by johnnovak** [comment]
> Looks like this is intentional:
> 
> https://github.com/dosbox-staging/dosbox-staging/blob/ed557435564b23644f1bb5f23e7d6e794cadd2d6/src/dos/program_intro.cpp#L78-L79

Huh, interesting find. I see no reason to disable the `INTRO` command in subshell, so I vote on getting rid of this questionable feature.

**Comment by weirddan455** [comment]
Well it says in the comment it might cause problems with that Xcom game so maybe test that first.

**Comment by johnnovak** [comment]
> Well it says in the comment it might cause problems with that Xcom game so maybe test that first.

Maybe that was true in ancient DOSBox times 😄 All executables on the emulated file system take precedence over built-ins. So if there's `INTRO.COM`, `INTRO.EXE` or `INTRO.BAT` in the path, that will be executed instead. I've just tried that, but I'll test with **X–COM: Terror From the Deep** as well.

**Comment by johnnovak** [comment]
Okay, I've just tested it X-COM – Terror From the Deep.

First of all, there's no executable called INTRO in the game's installed directory (I'm using the eXoDOS version).
Secondly, it runs fine.

The verdict:

<img width="304" alt="image" src="https://github.com/dosbox-staging/dosbox-staging/assets/698770/31adb932-7ccb-4d0b-a36f-dcad97834419">

Let's just nuke that line with _extreme prejudice_ 😎 🤘🏻
