### ISSUE TITLE
Translations differ between platforms

### ISSUE THREAD

**Issue by japsmits** [dosbox-staging/dosbox-staging#3562]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### What Operating System are you using?

None

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

When translating a group of items that differ per target, translations are created based on the current target. So when translating on a Windows-box, all Apple-related help-texts are removed.

An example of this can be found in midi.cpp, init_midi_dosbox_settings(). The possible values of the property "mididevice" vary between targets.

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Follow the translation guidelines on a Windows box and see the MacOS values disappear in en.lng
2.
3.

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by johnnovak** [comment]
> My suggestion would be to add help-texts per item, so that the proper items can be gathered for each target. The translation file would contain translations for all possible items.
> 
> So something like: str_prop->Set_item_help("coremidi", " coremidi: Any device that has been configured in the macOS\n" " Audio MIDI Setup.\n");
> 
> This could add a help-item SETUPITEM_MIDIDEVICES_COREMIDI with the appropriate text.
> 
> Property::GetHelp would then gather all appropriate subitems using this pattern. This would produce a complete help-text suitable to a specific target, but the en.lng-file would always contain all possible values.

I think that would be a better solution, I agree. Needs confirming it would really work in practice, but I think it would.

**Comment by japsmits** [comment]
I'll give this one a try.
