### ISSUE TITLE
Regression when setting a `cycles` value containing a `%` sign in `[autoexec]`

### ISSUE THREAD

**Issue by johnnovak** [dosbox-staging/dosbox-staging#3564]
This a regression we introduced in 0.81.0, it was working fine in 0.80.1 and earlier.
Setting the same value in the `[cpu]` section works fine; it can only be triggered by setting it in the `[autoexec]`.

1. Create a `dosbox.conf` with the following content:

```ini
[autoexec]
cycles = auto 20000 80% limit 400000
```

2. Start with `dosbox --noprimaryconf`

3. Observe that the `%` sign was eaten by a grue and we get 80 cycles.

<img width="1215" alt="image" src="https://github.com/dosbox-staging/dosbox-staging/assets/698770/e92f74ea-46ae-4014-a47e-7b4f154b553e">

**Comment by weirddan455** [comment]
First bad commit is bab4e9bc5da5adc11d3b54e4bfaeff87671e18d2 by @MeAreJeenius 

It looks like the thing that was making it work before was a pretty ugly hack in a core function for reading batch files and it was intentionally removed.

**Comment by johnnovak** [comment]
> First bad commit is [bab4e9b](https://github.com/dosbox-staging/dosbox-staging/commit/bab4e9bc5da5adc11d3b54e4bfaeff87671e18d2) by @MeAreJeenius
> 
> It looks like the thing that was making it work before was a pretty ugly hack in a core function for reading batch files and it was intentionally removed.

Yeah, we should be careful with such cleanups and removing stuff we don't fully understand. Often weird looking things are there for a reason.

**Comment by johnnovak** [comment]
@weirddan455 @MeAreJeenius I take it all back, with @MeAreJeenius 's change what we have now is the accurate MS-DOS behaviour.

Tested this on real MS-DOS, putting the same command into a batch file and the percentage disappears. 

I'm strongly against reintroducing the hack, people will just need to learn not to set such things from the autoexec or batch files.

**Comment by Grounded0** [comment]
Yeah `%%` is the correct DOS string processing. We're here to emulate DOS and trying to be backwards compatible with our string processing is only going to harm us in some other way like batch files for DOS failing to run properly.

**Comment by johnnovak** [comment]
Closing as we emulate the MS-DOS behaviour accurately.
