### ISSUE TITLE
Cannot set `output` at runtime

### ISSUE THREAD

**Issue by interloper98** [dosbox-staging/dosbox-staging#3570]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Different version than latest?

v0.82.0-alpha-356-gf55f0 (latest `main` build)

### What Operating System are you using?

Windows 11

### Relevant hardware info

AMD Ryzen 7 PRO 7840U w/ Radeon 780M Graphics

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

In recent releases (0.80 and 0.81), I could set `output` at runtime - for example, to switch from OpenGL to `texturenb` and then back to `opengl`.

However when I try with recent builds from CI (latest `main`), it seems to ignore the `output texture` request.

### Steps to reproduce the behaviour.

Explain how to reproduce

1. Launch with defaults: `dosbox.exe --noprimaryconf --nolocalconf`

    Confirm OPENGL is being used:
    ```
    2024-04-06 12:49:23.367 | OPENGL: Vendor: ATI Technologies Inc.
    2024-04-06 12:49:23.367 | OPENGL: Version: 4.6.0 Compatibility Profile Context 24.2.1.240215
    2024-04-06 12:49:23.367 | OPENGL: GLSL version: 4.60
    2024-04-06 12:49:23.367 | OPENGL: NPOT textures supported
    2024-04-06 12:49:23.367 | RENDER: Using adaptive CRT shader based on the graphics standard of the video mode
    ... <snip> ...
    2024-04-06 12:49:23.594 | RENDER: Auto-switched to shader 'crt/vga-1080p'
    2024-04-06 12:49:23.594 | SDL: Using standard SDI (auto) display refresh rate of 60 Hz
    2024-04-06 12:49:23.611 | DISPLAY: VGA 720x400 16-colour text mode 03h at 70.087 Hz throttled VFR,     scaled to 1067x800 pixels with 1:1.35 (20:27) pixel aspect ratio
    2024-04-06 12:49:23.611 | OPENGL: VSync state: off
    ```

2. In DOSBox Staging's console, enter: `output texture` and press enter.
    - Notice that no visible change has occurred (OpenGL and the CRT auto-shader are still active)
    - Notice that no new log messages have been printed

    ![2024-04-06 13_07_04-Greenshot](https://github.com/dosbox-staging/dosbox-staging/assets/165201780/dc762ca6-e000-4b8c-914b-9aa2b1d9caa3)

3. Expected output

    If 0.80 and 0.81 builds are used, entering `output texture` immediately switches output modes to texture rendering with visible indications and console log updates:

    ![2024-04-06 13_05_59-Greenshot](https://github.com/dosbox-staging/dosbox-staging/assets/165201780/1a739622-7838-4c94-9df8-bb98c0a5588b)

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by weirddan455** [comment]
95055debb1dae0b5eb3616c4f3c830d6f235b26d is the first bad commit by @FeralChild64

**Comment by FeralChild64** [comment]
I suspect the problem is here:

https://github.com/dosbox-staging/dosbox-staging/blob/f55f0ae3565c144549001fe65bcf439c315fa510/src/gui/sdl_mapper.cpp#L3259

The processing should continue if the new `output` value differs from the old one. There might be a similar problem with other setting from the `[sdl]` section. I’ll try to check tomorrow.

**Comment by johnnovak** [comment]
> I suspect the problem is here:
> 
> https://github.com/dosbox-staging/dosbox-staging/blob/f55f0ae3565c144549001fe65bcf439c315fa510/src/gui/sdl_mapper.cpp#L3259
> 
> The processing should continue if the new `output` value differs from the old one. There might be a similar problem with other setting from the `[sdl]` section. I’ll try to check tomorrow.

Yeah I explained this @FeralChild64. You need to flip this around: store the previous value of your titlebar setting, execute the titlebar init/setup stuff if that has changed, and otherwise leave the previous `[sdl]` section config processing logic alone.
