### ISSUE TITLE
Spell It Plus! (1989) (Regression)

### ISSUE THREAD

**Issue by Python-Exoproject** [dosbox-staging/dosbox-staging#3580]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### What Operating System are you using?

Windows 11

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

I was testing games in eXoDOS and found that this game has an issue in Staging 81.0 and 81.1 where all the white has gone pink. I then tested 80.1 and found that the game displayed correctly there.

81.1
![image](https://github.com/dosbox-staging/dosbox-staging/assets/67406191/97ab23e5-2002-4e6e-8311-515576a690c7)

80.1
![image](https://github.com/dosbox-staging/dosbox-staging/assets/67406191/e9ef470e-5422-4ac0-821d-181f472002d0)

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Load the game in Staging 81.1 or 81.0
2.
3.

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by interloper98** [comment]
Surely an unlikely coincidence, but that similar shade of pink shows up in both the box cover a d floppy disk labels. Would be very interesting to get this tested on real hardware, if it happens to be a palette tweak. 

![6647650-spell-it-plus-dos-front-cover](https://github.com/dosbox-staging/dosbox-staging/assets/165201780/c866ee43-7de6-4f21-ac6e-6a8296c5e185)
![6647662-spell-it-plus-dos-media](https://github.com/dosbox-staging/dosbox-staging/assets/165201780/032f97e9-4219-4850-a980-05e86ca15f88)
![6646528-spell-it-plus-dos-media](https://github.com/dosbox-staging/dosbox-staging/assets/165201780/78fabf8f-d922-43f7-a900-d0096290b0f7)

**Comment by johnnovak** [comment]
We just turned it into a lady 😎 🤘🏻 

Very interesting and I'm curious about the reason. Testing on hardware to find out how it should look.

**Comment by johnnovak** [comment]
Yeah, this is a legit regression; no need to even test on hardware. Fixing.

First bad commit:

```
commit 7c0a39cd139a3f05f61638b4fc3d482ead9cf581 (HEAD)
Author: kcgen <kcgen@users.noreply.github.com>
Date:   Mon Apr 10 15:47:46 2023 -0700

    Avoid an unaligned read in the simple renderer
```

**Comment by Grounded0** [comment]
Moved into 0.81.2 or 0.82.0 queue.

**Comment by johnnovak** [comment]
> Moved into 0.81.2 or 0.82 queue.

No, I'm working on a better fix now. It will go into 0.81.1, and it's gonna be safe.

**Comment by johnnovak** [comment]
Fixed in https://github.com/dosbox-staging/dosbox-staging/pull/3589#event-12443279245

This will be part of 0.81.1 @Python-Exoproject

**Comment by Python-Exoproject** [comment]
Thanks John!
