### ISSUE TITLE
Host large website images in our GitHub pages repo instead of archive.org

### ISSUE THREAD

**Issue by johnnovak** [dosbox-staging/dosbox-staging#3593]
Just a reminder for myself.

**Comment by Grounded0** [comment]
This seems to have been fixed.

**Comment by johnnovak** [comment]
I've done the front page only (which was the biggest problem because of the screenshots); the release notes and the getting started guide are still outstanding, so let's leave it open.

**Comment by johnnovak** [comment]
I've completed the task for all media and other files referenced in all our release notes and the Getting Started guide.
