### ISSUE TITLE
Consider using the Speex resampler consistenly for every audio device

### ISSUE THREAD

**Issue by johnnovak** [dosbox-staging/dosbox-staging#3595]
1. Some audio devices use the resampler from the reSIDfp library. This creates an unfortunate dependency on reSID in these unrelated devices, plus we're already using the Speex resampler for the Sound Blaster, and there's generic resampling support in the mixer for any mixer channel.

    <img width="1190" alt="image" src="https://github.com/dosbox-staging/dosbox-staging/assets/698770/1c172863-8889-414f-afc5-64480b4dd1a2">

2. The Speex resampler is probably more performant than all these other resamplers bundled with the libraries.

3. `TwoPassSincResampler` gives you an assertion failure when you set a target sample rate between about 16010 and 16050 Hz. With 16000 Hz or lower, you get no assertion but no sound either. Speex doesn't have such problems, and this conflicts with the variable sample rate enhancement. Affected sound devices:
    - Game Blaster
    - PS/1 Audio
    - Tandy 3-Voice

5. ~~Consider rendering OPL and MT-32 output at their original rates too, then use Speex to resample to the host sample rate. Rendering at the host sample rate instead of the device's native sample rate might introduce timing discrepancies and these bundled resamplers might be lower quality and not as performant as Speex.~~ **_This has been done for the MT-32 and OPL; the rest is outstanding._**

**Comment by weirddan455** [comment]
I'll continue our discussion from #3629 here.  We probably want to add the flag `SDL_AUDIO_ALLOW_FREQUENCY_CHANGE` when we open the SDL audio device.

```cpp
int sdl_allow_flags = 0;

if (negotiate) {
	// We allow chunk size changes (if supported), but don't allow
	// frequency changes because we've only seen them go beyond
	// SDL's desired 48 Khz limit
#if defined(SDL_AUDIO_ALLOW_SAMPLES_CHANGE)
	sdl_allow_flags |= SDL_AUDIO_ALLOW_SAMPLES_CHANGE;
#endif
```

>  I'd really like disallow any SDL-side resampling whatsoever. Is that possible with some flags? I want it to work as per above, and I want to keep all resampling business in our hands.

I believe this is enough to avoid resampling for our use-case but I'd really have to check the SDL source code to be sure.  If we ever use the SDL audio streams, it's a bit different but I'd probably recommend staying away from those and continue using the lower-level callback like we currently are.

There is also some `SDL_Hint` flags (which can also be set as environment variables).  One of which can use a third-party re-sampler library if available (I think it had "rabbit" in the name or something).

**Comment by johnnovak** [comment]
Solved in https://github.com/dosbox-staging/dosbox-staging/pull/3756
