### ISSUE TITLE
questiomn for dosbox of wolf3d.

### ISSUE THREAD

**Issue by DOOMMARINE117** [dosbox-staging/dosbox-staging#360]
for mounting how should i have it?

i put wolf3d with wolfenstein return to castle planium edition main directory and wa swondering how should i properly mount that?

its in my c drive of program\x86 or should i uninstall it to dosbox location? what you think?

**Comment by kcgen** [comment]
Hi @DOOMMARINE117 , 

It looks like the Platinum Edition runs is a pure-Windows game: https://www.ign.com/articles/2003/10/09/return-to-castle-wolfenstein-platinum-edition, in which case, you won't need to any version of DOSBox to play it. 

You mentioned having the original DOS `wolf3d` game: you can place its `wolf3d` directory  where-ever you you want, separated from *Return to Castle Wolfenstein*, in a place that's convenient for you.

**Comment by DOOMMARINE117** [comment]
> 
> 
> Hi @DOOMMARINE117 ,
> 
> It looks like the Platinum Edition is a pure-Windows game: https://www.ign.com/articles/2003/10/09/return-to-castle-wolfenstein-platinum-edition, in which case, you won't need to any version of DOSBox to play it.
> 
> You mentioned also having the original DOS **wolf3d** game: you can place its `wolf3d` directory where-ever you you want, separated from **Return to Castle Wolfenstein**, in a place that's convenient for you.

for dosbox how should i mount it the wolf 3d game? 

like cd programs(x86)? will taht work for dosbox automoutn commands? i have wolf 3d in my program(x86) or si that too many keys?

**Comment by dreamer** [comment]
@DOOMMARINE117 You can store it, and mount any directory you like (except `C:\Windows\`).

**Comment by DOOMMARINE117** [comment]
> 
> 
> @DOOMMARINE117 You can store it, and mount any directory you like (except `C:\Windows\`).

cool. awesome. wanted to make sure. i know dosbox is sensitive with certain mount commands. 


But, sounds like im good to go. i keep that in mind of future dosgames. i amke sure not to put them in C:\windows.

cool. thank you.

also, i did managed to figiure it out the controller support thing. i guess i can us ethe keymapper for it. is right trigger supported for dosbox or it just my controller? cause some reason it doesn't want to work?

**Comment by DOOMMARINE117** [comment]
what im also asking is. how do i change directories from where i have dosbox located to wolf3d?

**Comment by kcgen** [comment]
On your Windows 10 machine, let's say you've installed `dosbox-staging` here:

- c:\dos\dosbox (inside here you have `dosbox.exe`)

And Wolf3D is installed here:
- c:\dos\wolf3d (inside here you have `wolf3d.exe`)

You would run your Windows terminal, change directories into wolf3d:

- `cd \dos\wolf3d`

Then you would launch dosbox, passing it the `wolf3d.exe`:

- `c:\dos\dosbox\dosbox.exe wolf3d.exe`

There are front-ends that hide this complexity from you, and given you a nice list of games you can click on.  Although I don't use one, I've heard good things about **Dosbox Game Launcher** - http://members.quicknet.nl/blankendaalr/dbgl/

Hope that gets you up and running!

**Comment by DOOMMARINE117** [comment]
> 
> 
> On your Windows 10 machine, let's say you've installed `dosbox-staging` here:
> 
>     * **c:\dos\dosbox** (inside here you have `dosbox.exe`)
> 
> 
> And Wolf3D is installed here:
> 
>     * **c:\dos\wolf3d** (inside here you have `wolf3d.exe`)
> 
> 
> You would run your Windows terminal, change directories into wolf3d:
> 
>     * `cd \dos\wolf3d`
> 
> 
> Then you would launch dosbox, passing it the `wolf3d.exe`:
> 
>     * `c:\dos\dosbox\dosbox.exe wolf3d.exe`
> 
> 
> There are front-ends that hide this complexity from you, and given you a nice list of games you can click on. Although I don't use one, I've heard good things about **Dosbox Game Launcher** - http://members.quicknet.nl/blankendaalr/dbgl/
> 
> Hope that gets you up and running!

will that also apply to program(x86) thats where i have wolf3d installed. im assuming i need to move the wolf3d folder to dosbox? i have in C:\program(x86)\RTCW\wolf3d and i have dosbox in C:\DOS\DOSBOX

**Comment by kcgen** [comment]
You can move the `wolf3d` directory if you want; but you don't /have/ to.
Here's what you would type into your Windows 10 command-prompt:

``` shell
cd "\program(x86)\RTCW\wolf3d"
C:\DOS\DOSBOX\dosbox.exe wolf3d.exe
```

Does that work for you?

**Comment by DOOMMARINE117** [comment]
> 
> 
> You can move the `wolf3d` directory if you would prefer it somewhere else; what I wrote above is just an example.
> 
> With your current system as-is, here's what you would type into your Windows 10 command-prompt:
> 
> ```shell
> cd "\program(x86)\RTCW\wolf3d"
> C:\DOS\DOSBOX\dosbox.exe wolf3d.exe
> ```
> 
> Does that launch the game for you?

it almost works. took me few tries to get it right on cmd prompt. 

but i did manage to find the wolf3d file in cmd prompt. 

as for the target line and start in. what should i type in those and what about auto command line?

**Comment by kcgen** [comment]
> as for the target line and start in. what should i type in those and what about auto command line?

Sorry @DOOMMARINE117 ; I'm not following here.  Are you trying to create a desktop shortcut?

**Comment by DOOMMARINE117** [comment]
> > as for the target line and start in. what should i type in those and what about auto command line?
> 
> Sorry @DOOMMARINE117 ; I'm not following here. Are you trying to create a desktop shortcut?

Yes. I already have a desktop shortcut for the locations of both programs. So im hoping i can load them even my wolf3d is in Program(x86)\RTCW\wolf3d. C:\DOS\dosbox.

**Comment by kcgen** [comment]
**Target:** "C:\DOS\dosbox\dosbox.exe" wolf3d.exe
**Start in:** "C:\Program(x86)\RTCW\wolf3d"

**Comment by DOOMMARINE117** [comment]
> 
> 
> **Target:** `C:\DOS\dosbox\dosbox.exe wolf3d.exe`
> **Start in:** `"C:\Program(x86)\RTCW\wolf3d"`
> 
> (Or it might be `“c:\Program Files (x86)\RTCW\wolf3d”`?)

thanks. that works.

**Comment by DOOMMARINE117** [comment]
las thing what about the wolf3d.confs? i also have spear of destiny exe too?

**Comment by LowLevelMahn** [comment]
> last thing what about the wolf3d.confis?

what are wolf3d.confis?

>  i also have spear of destiny exe too?

same procedure but with different path?

**Comment by DOOMMARINE117** [comment]
> 
> 
> > last thing what about the wolf3d.confis?
> 
> what are wolf3d.confis?
> 
> > i also have spear of destiny exe too?
> 
> same procedure but with different path?

dang it, lol. typo. conf, lol. there is a conf file when you go to local and then dosbox folder. there is a conf file. lol. sorry, i have autism. plus, my keyboard stinks sometimes too. lol. 

what do i put in auto mount command line all the way at the bottom?

**Comment by LowLevelMahn** [comment]
see: https://www.dosbox.com/wiki/Usage
-conf is the parameter

**Comment by DOOMMARINE117** [comment]
> 
> 
> see: https://www.dosbox.com/wiki/Usage
> -conf is the parameter

gotcha. 

so far its not laod the wolf3d.conf file. it says: "it can't  load the wolf3d.conf. 

its loads the primary conf file though.

what do i go from here? 

i have so faar: in target line: C:\DOS\DOSBOX\dosbox.exe wolf3d.exe spear.exe -conf WOLF3D.conf. i tried doing that before the wolf3d.exe?

**Comment by DOOMMARINE117** [comment]
>     * "C:\programs files (x86)\wolf3d"

it almost works. but then it shutsdown. not sure why. it closes it out too fast for me to see the error.

**Comment by kcgen** [comment]
The autoexec section in your wolf3d.conf should be empty.  Can you take screenshots of your shortcut properties, your wolf3d directory contents (in windows explorer), as well as your dosbox directory contents?  This will help us more accurately help.

**Comment by DOOMMARINE117** [comment]
![20200513_163626](https://user-images.githubusercontent.com/64376960/81876684-19b1a080-9538-11ea-844e-c15340ad03e7.jpg)


here is my file.

**Comment by DOOMMARINE117** [comment]
oopps. i forgot to turn it forwrad, lol.

**Comment by kcgen** [comment]
Thanks @DOOMMARINE117 , can you try the shortcut, but with the `[autoexec]` section empty?

**Comment by DOOMMARINE117** [comment]
> 
> 
> Thanks @DOOMMARINE117 , can you try the shortcut, but with the `[autoexec]` section empty?

well that actually works. cool.

**Comment by kcgen** [comment]
@DOOMMARINE117 , I'm glad you're up and running! 

For other DOS games, you can create shortcuts for them using the same pattern we used here. 

I'm going to close this issue, bur if you hit any other snags feel free to open a new issue.
