### ISSUE TITLE
ESS ES1688 AudioDrive emulation

### ISSUE THREAD

**Issue by johnnovak** [dosbox-staging/dosbox-staging#3608]
# Overview

The [ESS ES1688 AudioDrive](https://www.youtube.com/watch?v=fWOdIuRO5fI) is my favourite Sound Blaster clone card. In fact, it outdoes the Sound Blaster at its own game: much lower noise floor, perfect Sound Blaster Pro compatibility (including the sound of the lowpass filter), and ESFM synthesis which is ESS' own take on the OPL3. It's extremely close to the Yamaha OPL3; unlike CQM, it's very faithful to it, yet it has its own unique subtle flavour.

I've just learned that some enterprising individual has achieved virtually perfect ESFM emulation in the [ESFMu](https://github.com/Kagamiin/ESFMu) library which is built upon NukedOPL3 that we all know and love. The words of the author:

> It's currently fully register-compatible with the real card and the sound output is audibly indistinguishable from the real thing. The emulator has already been battle-tested in other software (specifically, Furnace Tracker) and optimized by members of the community. 

The card can operate in two modes:

- **Legacy mode** — Sound Blaster Pro emulation plus ESFM in OPL3 compatibility mode. This could be basically `sbtype = sbpro2` plus `oplmode = esfm`. The point of this is to enjoy the slightly different rendering of FM music by the ESFM chip which is still very faithful to "true OPL3" (I actually prefer it to OPL3 on real hardware, it sounds a bit mellower). As the author says:

    > The emulated ESFM card can also be used for playing normal OPL2/OPL3 games. ESFMu does accurately reproduce the differences in sound between a real OPL3 and a real ESFM, so you can appreciate those differences in soundtracks that showcase them.

- **Native mode** — A few games support the advanced capabilities of the ESFM which goes way beyond what the OPL3 can do. Sadly, very few games have direct ESFM support to take advantage of these advanced features (Settlers 2 (Siedler 2) is the most notable example).

ESFM and ES1688 emulation have been recently integrated into DOSBox-X, so porting it should be pretty straightforward. Both operational modes are supported, which is great! 🥳 

- https://github.com/joncampbell123/dosbox-x/pull/4843
- https://github.com/joncampbell123/dosbox-x/pull/4854

## Sound examples

ESFM vs. Yamaha OPL3-FM: Siedler 2 Track 14
https://www.youtube.com/watch?v=Bpk3vkreSsA

Theme Hospital Soundtrack (ESFM)
https://www.youtube.com/watch?v=T_EqeRV0W7g

HoMM2 (OPL3)
https://soundcloud.com/user-931890863/heroes2-opl3?in=user-931890863/sets/opl3-vs-esfm-vs-esfm-enhanced

HoMM2 (ESFM Enhanced)
https://soundcloud.com/user-931890863/heroes2-esfm-enhanced?in=user-931890863/sets/opl3-vs-esfm-vs-esfm-enhanced

Warcraft 2 (OPL3)
https://soundcloud.com/user-931890863/warcraft2-opl3?in=user-931890863/sets/opl3-vs-esfm-vs-esfm-enhanced

Warcraft 2(ESFM Enhanced)
https://soundcloud.com/user-931890863/warcraft2-esfm-enhanced?in=user-931890863/sets/opl3-vs-esfm-vs-esfm-enhanced

## Further info

DOS Days — List of 86 games with enhanced (native) ESFM support
https://www.dosdays.co.uk/topics/ess_games.php

MobyGames — List of games with direct ESS AudioDrive support (94 games)
https://www.mobygames.com/game/attribute:568/sort:moby_score/page:1/

MobyGames — List of DOS games with Miles Sound System support (148 games)
https://www.mobygames.com/game/group:13047/platform:dos/sort:moby_score/page:1/
ESFM related info on Vogons:
https://www.vogons.org/viewtopic.php?t=75935

Details about the card:
https://dosdays.co.uk/topics/Manufacturers/ess.php#ES1688

**Comment by KainXVIII** [comment]
Cannot wait to test Coktel Vision games with ESFM!

**Comment by johnnovak** [comment]
ESFM has been implemented and we have basic support for the ESS 1688 now.
