### ISSUE TITLE
Reverb and Chorus Settings for MT-32/Munt

### ISSUE THREAD

**Issue by nickkeane** [dosbox-staging/dosbox-staging#3618]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### What Operating System are you using?

Windows 11

### Is your feature request related to a problem? Please describe.

Settings for Reverb and Chorus for the Roland MT-32 are missing.

### Describe the solution you'd like

Implement Reverb Type, Level, and Time settings via config file. Munt Properties:

<img width="388" alt="image" src="https://github.com/dosbox-staging/dosbox-staging/assets/770042/a9a039fb-3432-4889-8f14-f66d56283059">

Reverb Type ranges from 0 to 3 - Default: 0.
Time ranges from 0 to 7 - Default: 5.
Level ranges from 0 to 7 - Default: 3.

DoxBox-X has this feature integrated - See [Code Section](https://github.com/joncampbell123/dosbox-x/blob/master/src/gui/midi_mt32.h#L292).

### Describe alternatives you've considered

Integrated Mixer reverb, but that's for sound cards, and doesn't seem to apply to MT-32.

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by johnnovak** [comment]
@nickkeane What's the use case here? MT-32 games set up the reverb as per the composers' intention. I'm reluctant to provide options to muck around with that (on FluidSynth, it's a necessity; that's a different story).

This seems to hard-override the reverb settings in DOSBox-X. So if a game sets the reverb dynamically per track, you'd override all that.
