### ISSUE TITLE
`CONFIG -H` regression

### ISSUE THREAD

**Issue by johnnovak** [dosbox-staging/dosbox-staging#3619]
Another small regression after the translation refactorings @japsmits: now two blank lines are printed after a setting's help message. Same result with any setting.

Would you be able to take a look?

<img width="1074" alt="image" src="https://github.com/dosbox-staging/dosbox-staging/assets/698770/4bc7c9cd-4362-41b2-a735-07658ab3cca2">

**Comment by japsmits** [comment]
Apparently this issue was already fixed by another update. I've tried a few settings, but all look good to me. Unless you've looked somewhere I haven't (which is always possible), I think this issue can be closed.

**Comment by johnnovak** [comment]
@japsmits Yeah I fixed it in one of my recent PRs but forgot about this ticket. Closing.
