### ISSUE TITLE
CDROM_Interface pointer ownership issue

### ISSUE THREAD

**Issue by japsmits** [dosbox-staging/dosbox-staging#3620]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Different version than latest?

Git

### What Operating System are you using?

Windows 10

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

The pointer created by new CDROM_Interface_Image gets stored in two places (CDROM_Interface_Image::images and CMmscdex::cdrom) and can get deleted in both places. This is undefined behaviour.

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Code inspection...
2.
3.

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by japsmits** [comment]
Working on a not-too-invasive solution of this. Basically, one owning store for all CDROM_Interface decedents.

**Comment by weirddan455** [comment]
I'd suggest either adding some (temporary) log statements or setting a debugger breakpoint to confirm a double free happens in practice.  Actual behavior can often be surprising.

Either way, a cleanup of this would be welcome though.
