### ISSUE TITLE
Two errors in README.md install procedure? Attempted install on macos

### ISSUE THREAD

**Issue by bartvanderwal** [dosbox-staging/dosbox-staging#363]
I was trying to build dosbox from source (macOS Mojave), but when following the instructions from your `README` I got two errors

## Configure
first got an error on a missing DSL2 when running `configure`:

```console
./configure
checking for pkg-config... /usr/local/bin/pkg-config
[...]
checking for SDL - version >= 2.0.0... no
*** The sdl2-config script installed by SDL could not be found
*** If SDL was installed in PREFIX, make sure PREFIX/bin is in
*** your path, or set the SDL_CONFIG environment variable to the
*** full path to sdl2-config.
configure: error: *** SDL version 2.0.0 not found!
```

## Make
Then I tried to fix this through installing DSL2 with brew, which  I got yet another error on running `make`:

```console
dosbox-staging$ make
make: *** No targets specified and no makefile found.  Stop.
```

**Comment by dreamer** [comment]
Hmm, yeah - I think we need to improve documentation for macOS… I noticed some outdated info in `scripts/build.md`. Perhaps it's time to reorganize our README.md in general, since we have proper homepage now.

Try following steps:

```
$ brew install coreutils autogen autoconf automake make pkg-config libpng sdl2 sdl2_net opusfile
$ ./autogen.sh
$ ./configure  # some flags will be needed if you want faster release build
$ gmake -j "$(sysctl -n hw.physicalcpu)"
```
This should result in a working binary `src/dosbox`. If you want to package it as a bundle, then we have a helper script for that: `contrib/macos/create-app-bundle.sh` (it requires additional brew packages to help with generating .icns file)

**Comment by kcgen** [comment]
> I noticed some outdated info in scripts/build.md

Thanks @dreamer ; indeed. I'll take a pass through and get it back in sync with the script's arguments!

**Comment by kcgen** [comment]
@bartvanderwal , thanks for flagging this. 
We've updated the build docs; hopefully the steps here give you a working binary:

https://github.com/dosbox-staging/dosbox-staging/blob/master/BUILD.md#macos-procedures

**Comment by kcgen** [comment]
Closing this because the documentation issues flagged have been fixed.  Thanks for the report @bartvanderwal ; if you have any further compiling issues feel free to comment further or open a new issue.
