### ISSUE TITLE
Menus have double inputs in Tyrian

### ISSUE THREAD

**Issue by ffyte** [dosbox-staging/dosbox-staging#3632]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Different version than latest?

0.82.0-alpha-0c41e

### What Operating System are you using?

Windows 10 
Microsoft Windows [Version 10.0.19045.4291]

### Relevant hardware info

Intel 4770

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

When pressing the up/down arrows in the menus, setup program or otherwise, it double inputs and makes the menus unreliable.
 
https://github.com/dosbox-staging/dosbox-staging/assets/54371112/192ebaf7-dc08-41a9-ab00-1f88eab45b1a

This was working prior to 0.81

### Steps to reproduce the behaviour.

Explain how to reproduce
1.  Start dosbox
2.  Start Tyrian 2000 setup
3. Press up/down

### Download URL of affected game or software

https://www.gog.com/en/game/tyrian_2000

### Your configuration
(same as for 0.80, where there's no issue)
_No response_

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by Grounded0** [comment]
Reported as being a regression from 0.80.1.

**Comment by interloper98** [comment]
Happens in Tyrian's `SETUP.EXE`; this is a quick way to test it.


https://github.com/dosbox-staging/dosbox-staging/assets/165201780/c40ae2ba-5b1c-49ed-be8e-2c6cb4d18d78

**Comment by johnnovak** [comment]
@FeralChild64 Could this be related to your keyboard handler refactorings?

**Comment by FeralChild64** [comment]
Quite possible. I'll investigate this as soon as I have time.

**Comment by weirddan455** [comment]
I can't reproduce this bug on Linux.

**Comment by interloper98** [comment]
> I can't reproduce this bug on Linux.

I am seeing the same problem in the latest GIT build with this: [Tyrian 2000.zip](https://github.com/dosbox-staging/dosbox-staging/files/15136132/Tyrian.2000.zip)

`dosbox.exe --working-dir "Tyrian 2000"`

@weirddan455 - maybe this zip will help?

**Comment by weirddan455** [comment]
Thanks @interloper98 it is reproducible with that version.  You have a `dosbox.conf` in there but I deleted it and ran with `--noprimaryconf` and it's still reproducible.  So the bug only happens on certain game versions I suppose.

**Comment by weirddan455** [comment]
Did a bisect on it.  It's the keyboard rework as we suspected.  I'll let @FeralChild64 take a look at it before I go any further.

First bad commit is e73aaa57436bf5ef4eeea16255c78bef8511787e  It's a big one.

**Comment by johnnovak** [comment]
> Did a bisect on it. It's the keyboard rework as we suspected. I'll let @FeralChild64 take a look at it before I go any further.
> 
> First bad commit is [e73aaa5](https://github.com/dosbox-staging/dosbox-staging/commit/e73aaa57436bf5ef4eeea16255c78bef8511787e) It's a big one.

Remind me @FeralChild64 , why did we need this keyboard rework in the first place? 😄 Was there a concrete problem your refactoring aimed to solve? It definitely has caused some regressions but not sure what I improved.

Anyway, now it's in, so I guess you'll need to keep patching it up 😄

**Comment by FeralChild64** [comment]
There were two problems:
- exiting the Windows 3.11 for Workgroups sometimes was causing the keyboard to stuck - https://github.com/dosbox-staging/dosbox-staging/issues/2175
- I was unable to emulate register-level PS/2 mouse access - adding it was causing the Windows 3.11 for Workgroups to stop responding to mouse/keyboard events

**Comment by FeralChild64** [comment]
OK, I'm back home. I think I have a proper fix (https://github.com/dosbox-staging/dosbox-staging/tree/fc/tyrian-kbd-fix-1), but it needs some more testing before I submit it as a PR.

**Comment by interloper98** [comment]
I searched for related [keyboard regressions](https://github.com/dosbox-staging/dosbox-staging/issues?q=keyboard+label%3Aregression+author%3AFeralChild64) and found **_Ultima VIII Pagan_** and **_In Extremis_**, so I tested those games with the `fc/tyrian-kbd-fix-1` executable from the Actions page.

Both games continue to properly accept keyboard input with this build.

**Comment by johnnovak** [comment]
> I searched for related [keyboard regressions](https://github.com/dosbox-staging/dosbox-staging/issues?q=keyboard+label%3Aregression+author%3AFeralChild64) and found **_Ultima VIII Pagan_** and **_In Extremis_**, so I tested those games with the `fc/tyrian-kbd-fix-1` executable from the Actions page.
> 
> Both games continue to properly accept keyboard input with this build.

Thanks for proactively testing this @interloper98, much appreciated ❤️
