### ISSUE TITLE
sbtype=gb not working in latest 0.81.1 RC

### ISSUE THREAD

**Issue by Burrito78** [dosbox-staging/dosbox-staging#3636]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Different version than latest?

0.81.1 RC1

### What Operating System are you using?

macOS (Apple Silicon)

### Relevant hardware info

M2

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

See screenshots:

<img width="1210" alt="Bildschirmfoto 2024-04-27 um 12 47 21" src="https://github.com/dosbox-staging/dosbox-staging/assets/61995128/c9cd2616-ac84-4f89-9ec6-19ee5cdd9704">

<img width="1210" alt="Bildschirmfoto 2024-04-27 um 12 46 03" src="https://github.com/dosbox-staging/dosbox-staging/assets/61995128/4e05d077-fba0-4f09-8810-87a6ea2d46ca">

<img width="1210" alt="Bildschirmfoto 2024-04-27 um 12 49 41" src="https://github.com/dosbox-staging/dosbox-staging/assets/61995128/e8cd1292-afd7-46b2-9d6a-71dc159eef91">

### Steps to reproduce the behaviour.

Explain how to reproduce
1. 
2.
3.

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by johnnovak** [comment]
Indeed. Fixing tomorrow, thanks @Burrito78 .
