### ISSUE TITLE
Linux ARM prebuild binaries?

### ISSUE THREAD

**Issue by stackErr-NameNotResolved** [dosbox-staging/dosbox-staging#3638]
### Are you using the latest Dosbox-Staging Version?

- [ ] I have checked releases and am using the latest release.

### What Operating System are you using?

Linux ARM (Raspberry Pi)

### Is your feature request related to a problem? Please describe.

It looks like there are no prebuild Linux ARM binaries under the latest [release](https://github.com/dosbox-staging/dosbox-staging/releases/tag/v0.81.0).

### Describe the solution you'd like

Are there plans to release pre build Linux ARM binaries (that are at least compatible with Raspberry Pi 3B and higher)?

The Raspberry Pi 5 proves to be a [quite capable](https://github.com/dosbox-staging/dosbox-staging/issues/3152#issuecomment-1826439637) DosBox platform.

### Describe alternatives you've considered

I suspect it may be possible to compile DosBox Staging [yourself](https://github.com/dosbox-staging/dosbox-staging/blob/main/BUILD.md) for a ARM target. However the `BUILD.md` file talks about Linux, it does not state anything about supporting (or not supporting) ARM targets. So I did not put time into compiling.

Also, having no pre build binaries, significantly raises the bar for newcomers.

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by johnnovak** [comment]
Yes, ARM is supported, our macOS releases are Intel + ARM universal binaries.

The RetroPie project was (or still is?) a popular way to get Staging running on the RPi. They had to make a few tweaks, change the defaults etc. to make it run optimally on the Pi.

Ultimately, maintaining an official Pi port takes someone who has a vested interest in making this happen. Currently, no one in the core team cares about that enough and we don't want to spread ourselves thin anyway, neither support a platform half-assedly.

So you're best bet is contacting the RetroPi folks about this, or joining our team as the long-term maintainer of the Pi release 😄

**Comment by rderooy** [comment]
The linux flatpak build of DOSBox-Staging is available for 64bit ARM.

**Comment by weirddan455** [comment]
>  The linux flatpak build of DOSBox-Staging is available for 64bit ARM, as are the Fedora RPM packages. And there are probably some other linux distributions that build packages for multiple architectures.

I was just about to say the same thing but I'll include some links:

https://flathub.org/apps/io.github.dosbox-staging
https://docs.fedoraproject.org/en-US/quick-docs/raspberry-pi/

As for compiling yourself, there shouldn't be any major differences vs compiling an x86 build (unless you're trying to do a cross-compile, then it gets more complicated).  If you have any problems, post here and maybe we can help but it should just work as long as you have an up to date distro (Debian 10 based distros could be problematic).

We do also have a Linux ARM CI build going (and passing).  Not sure if it spits out a binary though.  CI is not my specialty :sweat_smile: https://github.com/dosbox-staging/dosbox-staging/actions/runs/8842205478/job/24280493185

**Comment by shermp** [comment]
In theory, the ARM CI builds should run on the RPi if the user is using an RPi OS based on bullseye or newer. I don't think it currently spits out binaries, but it could be made to do so if desired.

**Comment by johnnovak** [comment]
All good info, thanks guys. To be clear, my point was, we, the core team, don't actively test on the RPi currently, regardless of whether we have CI jobs that can produce RPi compatible ARM binaries or not. So shipping untested builds "officially" would be basically the "stuff compiles, ship it" mentality 😄 There is a lot more to producing working software for platfrom X than just being able to compile your project for it 😏

**Comment by stackErr-NameNotResolved** [comment]
Clear, thanks for the quick replies!

Currently I do not intent to become a RPI port maintainer per se, and I see what downsides come with that.

What do you all think about the following hybrid: don't release a RPI ARM based port, but do expose the binary on the CI build. This allows users who know where to look to easily grab the latest build and play around with it (and providing feedback on the working of this specific target build), but it keeps the binaries away from the regular user (and thus does not falsely presents itself as a fully tested build).

Please share your opinion on this idea. I can imagine you want to shoot it down since it might introduce extra traffic/noise in the issue tracker 😉.

**Comment by johnnovak** [comment]
We'd need to create and maintain the CI job too. If we don't, it's pointless because no one will even fix it when it breaks.

I'm talking from actual experience: our previous project leader had a soft spot for the PPC and a couple of other esoteric architectures and created CI jobs for them. Now that he's no longer with us (which is hopefully just an extended leave!), nobody cares much about those and they're probably broken.

What I find a good acceptable solution is to have RPi specific build instructions which are periodically checked and updated. We are in the process of revisiting our build approach, but it should be just one or two commands.

The current Linux instructions should work. Give them a try and let us know how it went, then we'll add the tested RPi specific build info.

**Comment by stackErr-NameNotResolved** [comment]
Cool. I will take a look at compiling this weekend.

**Comment by johnnovak** [comment]
> Cool. I will take a look at compiling this weekend.

Do note it's a matter of executing twoMmeson commands, so it should work right out of the box 🤞🏻 

> I can imagine you want to shoot it down since it might introduce extra traffic/noise in the issue tracker 😉.

To clarify, issue tickets are welcome regardless of the user's OS... unless it's something way off the common and beaten path, e.g. running outdated OSes with custom outdated drivers, etc. But true Staging specific issues should be pretty much OS agnostic, and the dynamic recompiler for ARM is heavily tested because of macOS.

**Comment by shermp** [comment]
And if you want to cross-compile, you can pull the Docker images used in CI locally, and build using that.

**Comment by Grounded0** [comment]
0.81.0 will run without issues on big-endian PowerPC. The project is popular enough now that it should be community's responsibility to make sure that big-endian PowerPC can be supported from this milestone forward.

**Comment by stackErr-NameNotResolved** [comment]
I tried to compile DOSBox Staging on my Raspberry Pi 3B+. The documentation seems to be complete. The compilation quickly grinds to a crawl since both the 1GB of memory and the swap is full. After 8 hours of compiling it only managed to compile 41 items out of the 300 or so.

Info:
```
Hardware: Raspberry Pi 3B+
Image: 2024-03-15-raspios-bookworm-arm64-lite.img.xz
uname: Linux raspberrypi 6.6.20+rpt-rpi-v8 #1 SMP PREEMPT Debian 1:6.6.20-1+rpt1 (2024-03-07) aarch64 GNU/Linux
```

@shermp I think that cross-compiling is definitely preferable in this case 😄.

I dove into the pipeline configuration to see how things are setup, and I almost managed to do a cross-compile locally. But it seems that I did miss something.

Steps:

1. Checkout repo and `v0.81.1` tag
2. Run ghcr.io/dosbox-staging/debian-cross:11-v0.81.1-arm64 with a mount against my local checkout
3. Install all packages from `ubuntu-20.04-apt.txt`
4. meson setup --cross-file dosbox-cross build/release
5. meson compile -C build/release

During the linking things seems to fail:

```
[473/473] Linking target dosbox
FAILED: dosbox
/usr/bin/aarch64-linux-gnu-g++  -o dosbox dosbox.p/meson-generated_.._version.cpp.o dosbox.p/src_main.cpp.o dosbox.p/src_dosbox.cpp.o dosbox.p/src_libs_ghc_fs_std_impl.cpp.o -Wl,--as-needed -Wl,--no-undefined -Wl,-O1 -Wl,-Map,dosbox.map -Wl,--Map,dosbox.map -Wl,--gc-sections -rdynamic '-Wl,-rpath,$ORIGIN/subprojects/libslirp-v4.7.0:$ORIGIN/subprojects/iir1-1.9.3/iir:$ORIGIN/subprojects/fluidsynth-2.3.3:$ORIGIN/subprojects/munt-libmt32emu_2_7_1' -Wl,-rpath-link,/foo/build/release/subprojects/libslirp-v4.7.0 -Wl,-rpath-link,/foo/build/release/subprojects/iir1-1.9.3/iir -Wl,-rpath-link,/foo/build/release/subprojects/fluidsynth-2.3.3 -Wl,-rpath-link,/foo/build/release/subprojects/munt-libmt32emu_2_7_1 -Wl,--start-group src/misc/libmisc.a src/libs/loguru/libloguru.a subprojects/libslirp-v4.7.0/libslirp.so.0.4.0 src/libs/whereami/libwhereami.a src/capture/libcapture.a src/libs/zmbv/libzmbv.a subprojects/zlib-ng/libzlib.a subprojects/libpng-1.6.40/libpng16.a src/cpu/libcpu.a src/dos/libdos.a src/libs/decoders/libdecoders.a subprojects/iir1-1.9.3/iir/libiir.so.1.9.3 src/fpu/libfpu.a src/gui/libgui.a src/hardware/libhardware.a src/libs/nuked/libnuked.a src/libs/residfp/libresidfp.a src/libs/YM7128B_emu/libym7128bemu.a src/ints/libints.a src/midi/libmidi.a subprojects/fluidsynth-2.3.3/libfluidsynth.so subprojects/munt-libmt32emu_2_7_1/libmt32emu.so src/shell/libshell.a src/libs/sdlcd/libsdlcd.a src/libs/tal-chorus/libtalchorus.a src/libs/manymouse/libmanymouse.a -lstdc++fs /usr/lib/aarch64-linux-gnu/libSDL2.so -pthread -lstdc++fs -ldl /usr/lib/aarch64-linux-gnu/libz.so -lm /usr/lib/aarch64-linux-gnu/libSDL2_net.so /usr/lib/../lib/libopusfile.so /usr/lib/aarch64-linux-gnu/libGL.so /usr/lib/aarch64-linux-gnu/libspeexdsp.so /usr/lib/aarch64-linux-gnu/libasound.so /usr/lib/aarch64-linux-gnu/libXi.so -Wl,--end-group
/usr/lib/gcc-cross/aarch64-linux-gnu/10/../../../../aarch64-linux-gnu/bin/ld: /usr/lib/../lib/libopusfile.so: error adding symbols: file in wrong format
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
```

Looks like the `aarch64-linux` linker tries to link `libopusfile.so` from `/usr/lib/../lib/libopusfile.so` in stead of `/usr/lib/aarch64-linux-gnu/`. I can verify that  `/usr/lib/aarch64-linux-gnu/libopus.so` exists.

Can someone shed some light on the linker behaviour? Thanks!

**Comment by johnnovak** [comment]
8 hours... 😮 That's some patience there! 😅

**Comment by interloper98** [comment]
@stackErr-NameNotResolved, I run retroarch on an older Pi. I think mine only has a GB of RAM.  When I build the modules from source, The problem is usually memory.  I use the `-j1` switch to only build. Does DOSBox Staging let you control the number parallel jobs when compiling?

**Comment by weirddan455** [comment]
>  Maybe DOSBox Staging also lets you control the number parallel jobs when compiling? (maybe using -j1 in your compile command will also work).

`-j1` is a supported option according to Meson documentation:  https://mesonbuild.com/Commands.html

make will usually default to only running a single job whereas Meson (or maybe ninja since that's what it uses on the backend) will default to using however many CPUs you have.  Usually that's not a problem unless you're very constrained on RAM.

**Comment by shermp** [comment]
Someone please tell me why I baked ccache into the meson cross toolchain file?

**Comment by shermp** [comment]
@stackErr-NameNotResolved try the following (if compiling from `main`):

```sh
docker pull ghcr.io/dosbox-staging/debian-cross:11-v0.82.0-dev-arm64
alias docker-cmd='docker run --rm -u "$(id --user):$(id --group)" -v "$PWD:$PWD" -v "$PWD/.ccache:$PWD/.ccache" -e HOME -e CCACHE_DIR="$PWD/.ccache" --workdir "$PWD" ghcr.io/dosbox-staging/debian-cross:11-v0.82.0-dev-arm64'
cd dosbox-staging
docker-cmd meson setup build --cross-file dosbox-cross --prefix=/opt/dosbox-staging
docker-cmd meson install -C build --destdir="./dosbox-staging-pkg"
```

After that, the output files will be in `build/dosbox-staging-pkg`. You should be able to copy the `dosbox-staging` directory in `build/dosbox-staging-pkg/opt/` to `/opt` on the RPi, add `/opt/dosbox-staging/bin` to PATH etc.

On your Pi, you will also need to install the packages listed in `packages/debian-11-docker-apt.txt` to get the required libraries.

**Comment by stackErr-NameNotResolved** [comment]
Neat, I got it to work. Thanks @shermp for the extended instructions!

The issue was installing the `ubuntu-20.04-apt.txt` packages inside of the Docker container. Oops... This package list contains `libopusfile-dev` which will confuse the linker.

I was able to build on Windows 11 with WSL2. Talking about layers.

**Comment by stackErr-NameNotResolved** [comment]
So, to summarize everything and wrap up the comments:

1. The `BUILD.md` instructions seem to be technically complete for a Linux ARM build. A quality of life improvement may be to include the limiting of Meson jobs. (did not test this on the actual RPI).
2. Cross-compiling work likes a charm. However there are no clear instructions on how to do this. You have to dive into the CI setup. But I guess there is no point in documenting how to do this locally. The added benefit of this documentation might be low and chances of desync against the actual CI setup might be high.

I will do a Meson build with `-j1` this evening. I'll make sure to benchmark, so we get some concrete data from it. If the build does work, this point can get addressed at least 😜:

> What I find a good acceptable solution is to have RPi specific build instructions which are periodically checked and updated. We are in the process of revisiting our build approach, but it should be just one or two commands.

**Comment by shermp** [comment]
Another option might be flatpak. While the dosbox-staging team does not manage this ourselves, the flatpak community do maintain a build, and `aarch64` seems to be an option.

**Comment by johnnovak** [comment]
Glad you managed to get it to work @stackErr-NameNotResolved. Feel free to raise a PR to add some extra info to the build instruction if you'd like to help others following your footsteps 😄

**Comment by stackErr-NameNotResolved** [comment]
I can confirm that he `j1` flag works on the RPI. 

"real    62m23.345s". 

Let me make a PR for the doc, to at least clarify on low memory cases.

**Comment by stackErr-NameNotResolved** [comment]
I have created a PR for the doc change. Unfortunately I am still fighting with `MDL`:

Looks like MDL trips over list ordering:
BUILD.md:167: MD029 Ordered list item prefix
BUILD.md:170: MD029 Ordered list item prefix
BUILD.md:173: MD029 Ordered list item prefix
BUILD.md:177: MD029 Ordered list item prefix
BUILD.md:181: MD029 Ordered list item prefix

**Comment by johnnovak** [comment]
> I have created a PR for the doc change. Unfortunately I am still fighting with `MDL`:
> 
> Looks like MDL trips over list ordering: BUILD.md:167: MD029 Ordered list item prefix BUILD.md:170: MD029 Ordered list item prefix BUILD.md:173: MD029 Ordered list item prefix BUILD.md:177: MD029 Ordered list item prefix BUILD.md:181: MD029 Ordered list item prefix

That's a local issue? The MDL pass ran just fine on CI:
https://github.com/dosbox-staging/dosbox-staging/actions/runs/8991592846/job/24701719916?pr=3658

**Comment by stackErr-NameNotResolved** [comment]
Since #3658 is now merged, I think that this issue can be closed.
