### ISSUE TITLE
King's Quest IV: The Perils of Rosella Ultimate* - no music in Linux

### ISSUE THREAD

**Issue by parricc** [dosbox-staging/dosbox-staging#3641]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Different version than latest?

0.81.0 Stable

### What Operating System are you using?

Linux x86_64

### If Other OS, please describe

Ubuntu 22.04.3 LTS (Flatpak freedesktop SDK 23.08)

### Relevant hardware info

AMD Ryzen 7 2700X

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

I'm seeing a Staging issue for King's Quest IV that is present in Linux but not Windows.
In Linux, the music does not play when selecting the King's Quest IV: The Perils of Rosella Ultimate* option.
This option is special in that it uses the GUS, Adlib, and MT32 channels simultaneously.

I've created a bundle with the relevant eXoDOS 6 files for easy testing in both Windows and Linux:
https://drive.google.com/file/d/1G3mXSdQ1iJkrcW4kVXf2wMEbN_SLewk5/view?usp=sharing

### Steps to reproduce the behaviour.

How to reproduce:
1. Download and extract https://drive.google.com/file/d/1G3mXSdQ1iJkrcW4kVXf2wMEbN_SLewk5/view?usp=sharing
2. flatpak install com.retro_exo.dosbox-staging-081-0.flatpak
3. Navigate to `eXo/eXoDOS/!dos/KQ4` and execute the game's `.command` file
4. Select option 2 for IBM PC, and then option 6 for King's Quest IV: The Perils of Rosella Ultimate*
5. Reference the jpg in the Extras folder for key

Other relevant notes:
- The KQ4 ultimate version works by using the GUS, Adlib, and MT32 channels simultaneously.
- The `./eXo/eXoDOS/KQ4/run.bat` file is called within DOSBox to choose which version of KQ4 to run.
- The `./eXo/util/dosbox_linux.txt` file defines which version of DOSBox Staging is executed. By simply changing the line within that file, you can retest the game with new development builds of DOSBox Staging.

### Download URL of affected game or software

https://drive.google.com/file/d/1G3mXSdQ1iJkrcW4kVXf2wMEbN_SLewk5/view?usp=sharing

### Your configuration

```ini
Conf files can be found in the linked archive at:
`./eXo/eXoDOS/!dos/KQ4/dosbox_linux.conf`
`./eXo/emulators/dosbox/options_linux.conf`

Both of these conf files are referenced when DOSBox Staging is called.
```

### Provide a Log

```text
https://gist.githubusercontent.com/parricc/7b580912b17377e4554d8d521090d028/raw/678511992a5a2be94b0ff61345f24f5f529223a9/kq4log.txt
```

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by parricc** [comment]
Just found out this works by editing the `dosbox_linux.conf` file to change `mididevice=auto` to `mididevice=fluidsynth`.
However, the fact that it works correctly with `mididevice=auto` in Windows but not Linux is concerning.

**Comment by johnnovak** [comment]
Can you please come up with a self-contained minimal config that triggers the issue @parricc? That would be ideal for future tickets too. Ideally, just a `dosbox.conf` one can put into the game dir with only a few lines that triggers the issue when you launch with `dosbox --noprimaryconf`. That would speed things up for us, thanks.

**Comment by johnnovak** [comment]
Btw, it's sime silly MIDI issue. Would be a problem on Windows or macOS too, but it's practically impossible to get zero number of MIDI devices on these OSes; the system always provides a few by default.

```
2024-04-30 15:17:38.584 | MIDI:ALSA: No available MIDI devices found
2024-04-30 15:17:38.584 | MIDI: Can't find device: 'auto', MIDI is not available
```

@weirddan455 or @FeralChild64 are your men to fix this. Should be rather simple.

**Comment by johnnovak** [comment]
That's an interestimg weird hybrid versio, by the way. Yeah, the sfx of Amiga Sierra ports are usually quite good:

> Combines the Amiga sound effects, SCI0 high-detail graphics, MT-32 audio (emulated using the Munt MT-32 emulator), and other features from the various releases into a single version run through [DOSBox](https://www.pcgamingwiki.com/wiki/DOSBox).

**Comment by parricc** [comment]
@johnnovak Is this file better? https://drive.google.com/file/d/1ECs0DDL8OADqYM-iGUkwBPeYtSJaqJGk/view?usp=sharing
Just the game directory specifically for the weird hybrid version with a dosbox.conf inside along with the mt32 directory, and the key jpg.

**Comment by johnnovak** [comment]
> @johnnovak Is this file better? https://drive.google.com/file/d/1ECs0DDL8OADqYM-iGUkwBPeYtSJaqJGk/view?usp=sharing Just the game directory specifically for the weird hybrid version with a dosbox.conf inside along with the mt32 directory, and the key jpg.

Yeah thanks, that's the best way.

**Comment by johnnovak** [comment]
Whoa, that's an interesting config @parricc 😅  It trips a debug assert too in the GUS code (release builds are fine), and FluidSynth is not initialised on macOS either.

<img width="863" alt="image" src="https://github.com/dosbox-staging/dosbox-staging/assets/698770/ac253d9a-7ba0-4887-9bc7-bbd7d4fd1604">



<img width="1472" alt="image" src="https://github.com/dosbox-staging/dosbox-staging/assets/698770/4605621e-27a7-42a4-b9dd-5acbf1a52136">

**Comment by johnnovak** [comment]
Wait a minute @parricc, so this is because you're not setting `midiconfig = fluidsynth`.

With this config (so `midiconfig` not set) you will always get the OS MIDI driver. I'm not sure how you're even getting FluidSynth in Windows with this config...

```
mididevice = auto
midiconfig =
```

So, the fix is to fix the config. Please read the full descriptions of the `mididevice` and `midiconfig` settings.

**Comment by Grounded0** [comment]
`mididevice = auto` on macOS will use Core MIDI to play back the MIDI music.

**Comment by johnnovak** [comment]
> `mididevice = auto` on macOS will use Core MIDI to play back the MIDI music.

Yeah and that's what it should do on Windows too, select the default MIDI out port which maps to the Microsoft GS Synth on whatever. If it doesn't, Windows is an outlier and breaks our consistent cross-platform behaviour

Will test shortly.

**Comment by johnnovak** [comment]
Okay, this is not a bug but a configuration issue. Staging defaults to the following MIDI settings:

```ini
mididevice = auto
midiconfig =
```

This will output the MIDI stream to the default MIDI port. This will cause the music to be played using the Microsoft MIDI Synth on Windows, and CoreMidi on macOS. So that's where the confusion was coming from — it was not FluidSynth playing but the Microsoft MIDI synth.

To select FluidSynth, you have two options:

1. Set `mididevice` to `fluidsynth`. in this case `midiconfig` is ignored, it can be anything, doesn't matter.
2. Leave `mididevice` on its default `auto` setting, _or_ set `mididevice = auto` explicitly, _and also_ set `midiconfig = fluidsynth`.
