### ISSUE TITLE
Around the World - Christmas (1999): Static during sound fx except on X

### ISSUE THREAD

**Issue by Python-Exoproject** [dosbox-staging/dosbox-staging#3651]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Different version than latest?

81.1

### What Operating System are you using?

Windows 11

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

When played in Staging this game gives a burst of static during the gameplay everytime one of the fx trigger.

All other forks do this as well except for dosbox X. Seems there are a few of these tickets ive created recently where only X can do or detect the sound properly

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Play game and listen for static when jump\collect presents\etc
2.
3.

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by johnnovak** [comment]
Would you also be able to include information about the games's sound configuration in the tickets @Python-Exoproject ? Just naming the sound device would be enough (e.g., "I'm using `sbtype = sb16`"). Given this is post-DOS-era game, I'm guessing you're using the SB16 with it.

**Comment by Python-Exoproject** [comment]
> Would you also be able to include information about the games's sound configuration in the tickets @Python-Exoproject ? Just naming the sound device would be enough (e.g., "I'm using `sbtype = sb16`").
> 
> Given this is a post-DOS-era game, I'm guessing you're using the SB16 with it.

Fair, im so used to using exodos that it doesnt always occur to me to do so as our template standard is SB16 and I test other devices when there is an issue anyway so that if one worked properly I wouldnt make the report.

The issue occurs on SB16, SBPro2, SBPro1, SB2, and SB1

**Comment by johnnovak** [comment]
> > Would you also be able to include information about the games's sound configuration in the tickets @Python-Exoproject ? Just naming the sound device would be enough (e.g., "I'm using `sbtype = sb16`").
> > Given this is a post-DOS-era game, I'm guessing you're using the SB16 with it.
> 
> Fair, im so used to using exodos that it doesnt always occur to me to do so as our template standard is SB16 and I test other devices when there is an issue anyway so that if one worked properly I wouldnt make the report.
> 
> The issue occurs on SB16, SBPro2, SBPro1, SB2, and SB1

Thanks, yeah it helps a bit because then we don't need to assume 😄 

I have the full eXoDOS collection on my PC, but I need to haul my ass over to the other room when I'm my laptop, so this is more convenient if you just list it. Plus not everybody in the team has the full eXoDOS collection, and it's good if the issue tickets are self-contained 😄

**Comment by Python-Exoproject** [comment]
Can this ticket be marked with the eXoDOS label please?

**Comment by Grounded0** [comment]
Yup.

**Comment by codengine** [comment]
With "loadfix -25" the issue is gone. Tested with current DosBox Staging 0.81.1.

**Comment by johnnovak** [comment]
Nice one @codengine 👍🏻

**Comment by Python-Exoproject** [comment]
Wow, confirmed. Would not have picked loadfix as a solution for static in sound fx
