### ISSUE TITLE
Loadfix command does not work on batch files

### ISSUE THREAD

**Issue by weirddan455** [dosbox-staging/dosbox-staging#3655]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### What Operating System are you using?

Linux x86_64

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

The loadfix command allows you to specify a program as an argument.  This allocates some memory before starting the program and then frees it when it finishes.  However, this does not work with batch files and it would be nice if it did.  Example:  `loadfix test.bat` outputs `64kb allocated. 64kb freed.` and the batch file never gets executed.

This can be worked around by typing `loadfix` on its own and then manually freeing with `loadfix /d` afterwards.

I have tested on v0.80.1 and this is not a regression.  I assume loadfix just never had this working.

### Steps to reproduce the behaviour.

Explain how to reproduce
1. `loadfix anybat.bat`
2.  Memory gets allocated and immediately freed without the batch file being executed.

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by johnnovak** [comment]
Isn't it supposed to only work with COM and EXE files? The MS-DOS help text implies that. But it's easy to test by running real MS-DOS inside Staging or 86box, PCem, etc.

https://home.csulb.edu/~murdock/loadfix.html

**Comment by weirddan455** [comment]
I didn't even realize loadfix was a command in real DOS.  Either way, is there anything wrong with extending our version to work with batch files?

**Comment by johnnovak** [comment]
> I didn't even realize loadfix was a command in real DOS. Either way, is there anything wrong with extending our version to work with batch files?

Yeah, I was thinking about that after I wrote it. I don't think enhancing it would be a problem, if it can be done. Would LOADFIX affect the first executable in the batch file then?

**Comment by weirddan455** [comment]
It would just allocate memory until all the commands in the batch file have been executed.  I just took a look at the code.  It's not doing anything fancy.  It's basically `DOS_AllocateMemory()`, `shell.ExecuteProgram()`, `DOS_FreeMemory()`.

There's actually a branch inside `shell.ExectureProgram()` that's supposed to handle batch files but it's not working.  I'll investigate.
