### ISSUE TITLE
Disappears mouse of the Debian

### ISSUE THREAD

**Issue by arcanjoebc1971** [dosbox-staging/dosbox-staging#3656]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Different version than latest?

0.81.0

### What Operating System are you using?

Linux x86_64

### If Other OS, please describe

Dell Vostro 3681

### Relevant hardware info

DELL

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

When I use dosbox staging 0.81.0, the Debian mouse disappears and I have to restart the computer... how to solve this?

### Steps to reproduce the behaviour.

Explain how to reproduce
1. I just run a simple build with DJGPP (GCC) and the mouse stops working on Debian....
2.
3.

### Your configuration

```ini
[autoexec]

# FreeDOS
mount e "/home/everaldo/HDDs/E/" -t cdrom
mount c "/home/everaldo/HDDs/C/" -freesize 2048
C:\
C:\FDAUTO.BAT
```

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by weirddan455** [comment]
It sounds like dosbox captured the mouse maybe.  You should be able to use the middle-click mouse button to release the mouse.  You can also configure capture behavior with the `mouse_capture` setting in the config file.

**Comment by MasterO2** [comment]
@arcanjoebc1971, you can also press `CTRL` and `F10` together on the keyboard to release the mouse.

**Comment by arcanjoebc1971** [comment]
MasterO2, I trued to press ctrl + F10, but nothing happen ... Have you other option?

**Comment by arcanjoebc1971** [comment]
weirddan455 , I tried your suggestion and now it work .... thank you!

**Comment by johnnovak** [comment]
@arcanjoebc1971 If you're new to Staging, DOSBox, and emulating DOS in general, I highly recommend going through our Getting Started guide:

https://dosbox-staging.github.io/getting-started/introduction/

Have fun using Staging! 😎
