### ISSUE TITLE
Command line history saving can't be disabled

### ISSUE THREAD

**Issue by vladkosi** [dosbox-staging/dosbox-staging#3661]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Different version than latest?

0.82.0-alpha-847d0

### What Operating System are you using?

Windows 10

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

The command line history saving can't be disabled by setting the `shell_history_file` value to empty like the config file suggests. The file `shell_history.txt` is always created and the history is saved.

You can disable it in version 0.81.0

### Your configuration

```ini
shell_history_file =
```

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by weirddan455** [comment]
Confirmed regression.  First bad commit is 32a44a9ed129d333e65c7e588768df32ee452477

Good news is this commit was not cherry picked for 0.81.1

**Comment by johnnovak** [comment]
> Confirmed regression. First bad commit is [32a44a9](https://github.com/dosbox-staging/dosbox-staging/commit/32a44a9ed129d333e65c7e588768df32ee452477)
> 
> Good news is this commit was not cherry picked for 0.81.1

Thanks for testing & confirming @weirddan455 . That's good news 😄
