### ISSUE TITLE
MAD TV 2 freezes dosbox

### ISSUE THREAD

**Issue by Max833** [dosbox-staging/dosbox-staging#3675]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Different version than latest?

0.81.1

### What Operating System are you using?

None

### If Other OS, please describe

Windows 10

### Relevant hardware info

i73770k, GTX 1070

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Starting MAD TV 2 freezes DOSBox Staging. The game runs in dosbox 0.74-3.

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Start the game
2. DOSBox freezes

### Your configuration

```ini
Default 0.81.1 settings
```

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by johnnovak** [comment]
@Max833 Could you test in 0.80.0 as well please?

**Comment by Max833** [comment]
@johnnovak: It doesn't work with 0.80.0, but it runs in DOSBo Staging 0.7.8.1.

**Comment by Max833** [comment]
Oh, wait! It is working again with the newest dev build! :D Maybe because of https://github.com/dosbox-staging/dosbox-staging/pull/3673

**Comment by johnnovak** [comment]
> Oh, wait! It is working again with the newest (https://github.com/dosbox-staging/dosbox-staging/actions/runs/9102577280) dev build! :D Maybe because of #3673

Thanks @Max833. So not a recent regression from 0.80.1, and it's already fixed in main. Closing then.
