### ISSUE TITLE
500 USD bounty for DOSBox Staging official Debian package

### ISSUE THREAD

**Issue by Grounded0** [dosbox-staging/dosbox-staging#3677]
Modified: Wed 10 Jul 2024 21:58:13 UTC

Deploy DOSBox Staging into the official Debian package repository with a one-year commitment to being the package maintainer and collect your 500 USD. I will not raise this any further.

I can pay via SWIFT, the cryptos available in Coinbase, or PayPal.

Resolves a long-standing ticket opened in 2020:

- #664

### Links

[Debian ITP for DOSBox Staging](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=973822)
[Debian ITS for DOSBox Staging](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1036708)

### Connected issues and PRs

- #418
- #664
- #3806
- #3809

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by okias** [comment]
I recommend specifying the outcome more precisely.

Do you want to get this into Debian or just external repository.
 - Maintained by who? For how long? etc. etc.
 - Should the person become the maintainer of the package in Debian? etc. etc.

**Comment by Grounded0** [comment]
DOSBox Staging 0.81.1 into Debian repository. Maintain through 2024.

**Comment by kkremitzki** [comment]
As a Debian Developer with only a superficial awareness of DOSBox, I took a look at the package and its open bugs. I can see that Debian would be amenable to replacing the DOSBox package with one of its maintained forks to address longstanding issues (moreso than keeping the package and adding one or more forks.) However, a primary question would be why one fork should be chosen over another. If there were a brief explanation of this available, that would address the main non-technical obstacle to getting this packaged for Debian.

**Comment by runlevel5** [comment]
Packaging would be easy part. The hard part is to get it accepted into Debian. Who's going to be the maintainer moving forward? I highly recommend you bring this up with the Debian community instead.

**Comment by Castor215** [comment]
This was mentioned on the mailing lists but I'm bringing it up here, too. What are the binary blobs in `contrib/resources`? I'm talking about files that end in .com, .sys, .exe and .cpx/cpi. These seem to be already-compiled files and would be a violation of the DFSG (specifically guideline 2 "Inclusion of source code"). As it is, dosbox-staging would need to go in the `contrib` or `non-free` sections. Can dosbox-staging function without these files?

**Comment by FeralChild64** [comment]
1. `*.EXE`, `*.COM` files - these are DOS commands (programs) from the FreeDOS projects, which are not (yet) internally implemented. DOSBox should work without these files - just the commands won’t be available, 99.9% of the time this shouldn’t matter.

2. `KEYBOARD.SYS` and friends - these are keyboard layout files from the FreeDOS project, see https://gitlab.com/FreeDOS/base/keyb_lay. AFAIK they were compiled using some tool from the source .KL files, but I don’t know the details. Expect trouble if you remove these files.

3. `*.CPI` / `*.CPX` files - these are screen font files from the FreeDOS project, see https://gitlab.com/FreeDOS/base/cpidos. CPI are just bitmap font files, there is no source code for them - AFAIK they were created using a specialized bitmap editor. CPX are UPX-compressed versions (these files contain a binary decompressor code). Due to some inconveniences, I got rid of the CPX files recently, see https://github.com/dosbox-staging/dosbox-staging/pull/3413. To create CPI file from the CPX one, just execute `upx -d file.CPX` command, under any OS. Expect trouble if you remove these files.

Regarding points 2. and 3. - I believe every single DOSBox fork has them in some form, even the original DOSBox - see:
- https://sourceforge.net/p/dosbox/code-0/HEAD/tree/dosbox/trunk/src/dos/dos_codepages.h
- https://sourceforge.net/p/dosbox/code-0/HEAD/tree/dosbox/trunk/src/dos/dos_keyboard_layout_data.h
The original DOSBox contains them (well, actually older versions) as embedded binary blobs.

**Comment by Castor215** [comment]
@FeralChild64 Fair enough. It was just that lintian throws up a warning about xcopy.exe and I was trying to predict what a Debian Developer might say when approached for sponsorship.

**Comment by Grounded0** [comment]
Raising this to 300 USD to entice more market demand.

**Comment by Grounded0** [comment]
Raising this to 500 USD to make it more enticing. I will not raise this further so anyone waiting for a higher offer on this would be wasting their time instead of earning money.

**Comment by Grounded0** [comment]
Yeah let's unpin this since no one seems to be interested. If this is the state of Linux community engagement in 2024 we're in trouble.

**Comment by johnnovak** [comment]
Can we close this @Grounded0 now that we've done as much as we could from our side?

**Comment by Grounded0** [comment]
I'm still open to giving 500 USD to anyone who gets this done. I don't see a problem here.

**Comment by johnnovak** [comment]
Well, this is a Debian maintainer's job to get the package we publish into their official repos. And maintain it going forward. We deal with Staging dev here, so now that I think about it, this ticket should live in some Debian issue tracker IMO, not ours.

**Comment by Grounded0** [comment]
Debian-jobs mailing list is totally dead:

https://lists.debian.org/debian-jobs/

My evaluation is that i get more potential traction here than posting into a dead mailing list no one reads anyway.

**Comment by johnnovak** [comment]
Sure, and I don't mind the ticket being in our tracker, don't get me wrong 😄 It's just that none of us from the core team will go and fight it out with the Debian people 😅 But hey, maybe someone will read this ticket and have the fighting spirit in them 🥊 😎

**Comment by Grounded0** [comment]
I'm retired so I got time and money to be Don Quixote of DOSBox Staging. 👊

**Comment by interloper98** [comment]
Can we transplant this ticket into Debian's repo with references back to our [project-generated packages](https://github.com/dosbox-staging/dosbox-staging/actions/workflows/debian-package.yml?query=is%3Asuccess) and [Debian metadata](https://github.com/dosbox-staging/dosbox-staging/tree/main/contrib/linux/debian)?

**Comment by Castor215** [comment]
For those unaware, this is the process for getting a package into Debian:

1. File an Intent to Package (ITP) on the appropriate Debian mailing list
2. After people have had a chance to respond to the ITP, you will need to modify the source to comply with Debian packaging policy
3. Make a Debian Salsa account (the official Git repository for staging packages) and upload the package source there
4. Upload the source to Debian Mentors
5. Find a sponsor for your package (this is the tricky part)
6. If a sponsor agrees to upload it for you, it will need to go through the Debian NEW queue, where the Debian legal team will make sure it's okay to distribute
7. Once your package clears NEW, it will be uploaded to unstable, where it will then propagate to testing and stable*
8. Congratulations! You are now a package maintainer. Any further development will be done by liaising between you and your sponsor

The details of each of these steps are quite involved and I won't go into them here. Here are some starting points:

- [WNPP](https://www.debian.org/devel/wnpp/). You don't generally file an ITP in the mailing list directly. You use the `reportbug` utility to file a bug against the `wnpp` package and fill in the template.
- [Debian Salsa](https://salsa.debian.org/public). This is where you stage the source code for your package.
- [Debian Mentors](https://mentors.debian.net/). This is where you'll upload your package once it's ready for sponsorship.
- [Debian Policy Manual](https://www.debian.org/doc/debian-policy/). Trying to digest this all in one go would be absurdly unfeasible, so just refer to this as needed.
- You may also want to look into tools for actually building the packages such as `dh_make` and `sbuild`, but this "brief" introduction of mine is already long enough.

I hope this helps any prospective DOSBox maintainers. Source: Almost became a maintainer, but didn't (Citra got nuked).

\* Kind of, there's a caveat with brand new packages where an "empty" upload must be made before a package can migrate to testing. I forget the details but your sponsor will know more.

**Comment by johnnovak** [comment]
> For those unaware, this is the process for getting a package into Debian:

Fucking hell; lodging my annual tax papers is a walk in the park compared to this process 🤣 

Thanks for this @Castor215, by the way 👍🏻

**Comment by Grounded0** [comment]
It's obvious no one on the DOSBox Staging team has the appetite to take on that challenge; hence, the bounty was made available.

**Comment by Grounded0** [comment]
<img width="322" alt="Screenshot 2024-07-21 at 23 43 06" src="https://github.com/user-attachments/assets/e765af43-47f9-4b6f-878f-da33f2ac2d2f">

**Comment by hosiet** [comment]
Jokes aside, speaking with my Debian Developer hat on:

The biggest problem is not about the bureaucracy; it's still the unclear file status as stated in https://github.com/dosbox-staging/dosbox-staging/issues/3677#issuecomment-2142105816 . I am slowly sorting out files in the dosbox-staging repo; embedded binary blobs are definitely not going to get in and alternatives are needed. This also applied to the Debian packaging of the original dosbox project.

I will try to spend some of my spare time on this issue but probably not that fast; I am a newbie in the DOS world. I will let you know when I have anything certain.

**Comment by johnnovak** [comment]
> I am slowly sorting out files in the dosbox-staging repo; embedded binary blobs are definitely not going to get in and alternatives are needed.

Not quite sure why they are a problem at all. They're not copyrighted, they're not native executables, so they can be seen as data used by DOSBox. I'm sure lots of packages included in Debian have all sorts of data files which are neither text files nor native executables. PNG is data, WAV files are data, TTF files are surely not plain text files, etc. Then I'm sure you must have programs thar just used some random custom DAT file...

So maybe on way to hammer this through the bureaucrats is to point out similar precedents, the more and the older, the better (well, that's what I would do 😆).

**Comment by Grounded0** [comment]
DOSBox-X Debian package also ships with binary blobs but they're hidden in the source code so I don't see a problem here (`DEVICE.COM` for example):

https://github.com/joncampbell123/dosbox-x/blob/master/src/builtin/device_com.cpp

**Comment by hosiet** [comment]
> > I am slowly sorting out files in the dosbox-staging repo; embedded binary blobs are definitely not going to get in and alternatives are needed.
> 
> DOSBox-X Debian package also ships with binary blobs but they're hidden in the source code so I don't see a problem here (`DEVICE.COM` for example):
> 
> https://github.com/joncampbell123/dosbox-x/blob/master/src/builtin/device_com.cpp

Thanks for pointing out. As you can see from https://sources.debian.org/src/dosbox-x/2024.07.01%2Bdfsg-1/debian/copyright/ , the embedded version has been explicitly handled and removed.

I appreciate the comments above; but executables, native or not, are usually stripped out or rebuilt from source. Even if I let it slip out of my hand, the final package review team will still reject it.

I see that dosbox-x as a reference has been properly treated in Debian; similarly dosbox-staging can be handled as well.

**Comment by johnnovak** [comment]
> I appreciate the comments above; but executables, native or not, are usually stripped out or rebuilt from source.

Sure, the FreeDOS executables can be rebuilt for sure, but we're not interested in doing that as part of our buuld process. They are also non-essential, as pointed out.

**Comment by johnnovak** [comment]
Can we close this @Grounded0 ?

**Comment by Grounded0** [comment]
No because I'm still going to donate 500 USD either to the author or the Debian Project once this is done as per @hosiet:

- https://github.com/dosbox-staging/dosbox-staging/issues/3677#issuecomment-2243773466

This looks like something that could happen in 2025 so we'll keep this open.

**Comment by johnnovak** [comment]
> No, because I'm still going to donate 500 USD either to the packager or the Debian Project once this is done, as per @hosiet:

Sure thing, just wasn't sure what the current situation is with your retirement announcements. Happy to keep this open, no problem.

**Comment by Grounded0** [comment]
I'm closing this since I am saving up for a down payment on a townhouse. 😁

**Comment by johnnovak** [comment]
@hosiet Just wondering, no progress with the Debian bureaucrats? 😆

**Comment by okias** [comment]
> I appreciate the security concerns, but just don't run Staging on server, only on home setups. Problem solved 😆

Well, there are people who would appreciate not having compromised personal computers or phones either :wink:

**Comment by FeralChild64** [comment]
> Debian insists on being self-contained. Anything that is packaged in Debian, by Debian, must be built (compiled) using only dependencies in Debian. Also, everything in Debian must be built by Debian. This can cause a lot of extra work. For example, current programming language tooling often assumes it can download dependencies from online repositories at build time, and that is not acceptable to Debian.

I actually like this approach. In the MEGA65 OpenROMs project I’ve decided to download dependencies in the runtime for two reasons:
- almost no distro was shipping them
- dependencies were being taken from GitHub repositories under the control od our team
If not for point 1, I would have asked users to get the dependencies from the distro repository.

But back to Staging. Do we know the full list of problematic binary blobs?
- The FreeDOS executables can be stripped away and DOSBox Staging will continue functioning, that’s not a problem.
- As for the keyboard SYS files - I intend to rework the code, maybe I could load their source files instead? We’ll see.
- CPI files are simply bitmap fonts, they were not build - they were hand-drawn using a specialized editor.

Is there anything else?
Is there anything else?

**Comment by johnnovak** [comment]
> > I appreciate the security concerns, but just don't run Staging on server, only on home setups. Problem solved 😆
> 
> Well, there are people who would appreciate not having compromised personal computers or phones either 😉

There's always risk vs rewards. Want 100% security? Cut the network cable 😎 

Clearly, "security" is a continuum. It's would be a bit crazy to install random games on servers... On the flipside, gamers and home users don't exactly need military and server grade security either 😏 Reasonable security, yes.

**Comment by FeralChild64** [comment]
There is always an unavoidable risk and an unnecessary risk.

Doing your best to only use binaries compiled by yourself, or by a trusted party with security practices developed over decades, is a perfectly sane approach. It won't protect you every time (vide recent _XZ Utils_ case), but will drastically reduce the risk.

I know the most popular OSes are compiled by parties well known for their anti-consummer practices, they can install you a _Candy Crush Saga_ without your knowledge and consent, they can phone home and tell about every application you run, they can bombard you with ads, etc. I know the most popular software is usually rigged with various crapware, spyware, strange browser plugins, crypto-miners, games quite often install their own shady OS kernel modules, etc.

But in the Linux world this is not tolerated and measures (sometimes painful) has to be taken to ensure distros are free from all this junk.
