### ISSUE TITLE
Add Ghostbusters II to "Game Issues" wiki

### ISSUE THREAD

**Issue by bsmith1702** [dosbox-staging/dosbox-staging#3679]
The game locks up after Vigo speaks during the intro when playing with MT-32 sound.  This is bug with the game and not a DOSBox issue as described here:

[https://www.dosbox.com/comp_list.php?showID=321&letter=G](url)

It's also been mentioned in part in #3096 

The easy solution is to set `sbtype` to `none` in the config file.  Alternatively, patching GB.EXE and SHELL.EXE as described in the link works.  The audio of the dialog also sounds better (less staticy) when patched and `sbtype` is `sb16`.

It might be a good idea to add this to the wiki.

**Comment by MasterO2** [comment]
@bsmith1702 Now added to https://github.com/dosbox-staging/dosbox-staging/wiki/Game-issues#ghostbusters-ii

**Comment by johnnovak** [comment]
Thanks @MasterO2
