### ISSUE TITLE
Flight Simulator 5 Flight Shop Addon fails to install (regression from v0.80.1)

### ISSUE THREAD

**Issue by weirddan455** [dosbox-staging/dosbox-staging#3695]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### What Operating System are you using?

Linux x86_64

### If Other OS, please describe

Debian 12

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

The installer fails because it is unable to remove several files.  The files appear to be created by the installer in read-only mode and it then complains that it is unable to remove them.

I believe read-only mode should not stop a file from being deleted.  v0.80.1 logs a warning to the console but is able to remove them anyway and the installer succeeds.

![image0002](https://github.com/dosbox-staging/dosbox-staging/assets/8128047/2b9af64b-4d42-4aa8-8233-2b3fd7a47f45)

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Install Flight Simulator 5 (can be done from DOS)
2. Attempt to install Flight Shop addon (must be done from Windows 3.1)

### Download URL of affected game or software

https://www.myabandonware.com/game/microsoft-flight-simulator-v5-0-1zs#download
https://archive.org/details/bao-flight-shop

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by weirddan455** [comment]
First bad commit is 16ec5110d197c0a0344b76ea6d4163d684c51097 by @FeralChild64

**Comment by weirddan455** [comment]
Bad commit may actually be 144783113f8f44a5c449ae7737b6ebb625104d84 where a check was added to not allow deleting read-only files

https://github.com/dosbox-staging/dosbox-staging/commit/16ec5110d197c0a0344b76ea6d4163d684c51097 fixed behavior of `allow_write_protected_files` setting which did not exist in v0.80.1.  Setting that to false allows the installer to continue.  It throws an error if a read-only file is opened with write permissions.  Setting the flag to true allows the open operation to succeed, falling back to read-only mode.

Behavior of the game appears to be the following:

1. Copy the file from the CDROM.  Read-only flag is preserved from the CDROM.
2. Attempt to open the new file from the C drive.  If the open fails (with `allow_write_protected_files` set to false), continue on as if nothing happened.  File remains on disk.  If the open succeeds, delete the file.  This delete operation fails on `main` because of the read-only check.  The delete operation succeeds on v0.80.1.

Need to test on 86box to see what real behavior should be.

**Comment by weirddan455** [comment]
OK, tested on real MS-DOS 6.22 plus Windows 3.1.  The files should not be deleted and they should be copied to the hard drive with read-only set.  Behavior on v0.80.1 is not correct so this is not a regression.

`allow_write_protected_files` needs to be set to false though to get correct behavior with this program.  I suppose we should just add that to the wiki.

![flight](https://github.com/dosbox-staging/dosbox-staging/assets/8128047/448273cf-c986-49f8-91ba-52ef509e3cdd)

**Comment by MasterO2** [comment]
> OK, tested on real MS-DOS 6.22 plus Windows 3.1. The files should not be deleted and they should be copied to the hard drive with read-only set. Behavior on v0.80.1 is not correct so this is not a regression.
> 
> `allow_write_protected_files` needs to be set to false though to get correct behavior with this program. I suppose we should just add that to the wiki.
> 
> ![flight](https://private-user-images.githubusercontent.com/8128047/333312061-448273cf-c986-49f8-91ba-52ef509e3cdd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY0OTIyODYsIm5iZiI6MTcxNjQ5MTk4NiwicGF0aCI6Ii84MTI4MDQ3LzMzMzMxMjA2MS00NDgyNzNjZi1jOTg2LTQ5ZjgtOTFiYS01MmVmNTA5ZTNjZGQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MjNUMTkxOTQ2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9N2RiZWMwNTE3ZDI4MWRkODkyNTM2NTMyYjgyMmQwNGU1YTc3ZTgzNDRlNGRiZjcyZmI4NGVlODI0OWE0NGYyMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.DzP7XgCKpXtET3muRKR9vulg0Ny-WmydC-u94s_oTpQ)

https://github.com/dosbox-staging/dosbox-staging/wiki/Game-issues#bao-flight-simulator---flight-shop-addon

**Comment by weirddan455** [comment]
Thanks @MasterO2  Small correction in that it doesn't actually delete the files.  It seems to be expecting the `DOS_OpenFile(... OPEN_READWRITE)` call on the read-only file to fail (which it only does if `allow_write_protected_files` is false).  If it succeeds, I guess it thinks something went wrong and tries to delete the file which ultimately fails thanks to the new code that disallows this for read-only files.

I was testing this program on my PR branch #3687.  Now that I've got the installer sorted, it's still failing to launch with this error.  It's gotten past the initial `SHARE.EXE` check but it looks like I'm still doing something wrong.  Needs more investigation later...

![image0003](https://github.com/dosbox-staging/dosbox-staging/assets/8128047/752ce0a5-a08c-4b50-954f-f3d48ad6886d)

**Comment by MasterO2** [comment]
> Thanks @MasterO2 Small correction in that it doesn't actually delete the files. It seems to be expecting the `DOS_OpenFile(... OPEN_READWRITE)` call on the read-only file to fail (which it only does if `allow_write_protected_files` is false). If it succeeds, I guess it thinks something went wrong and tries to delete the file which ultimately fails thanks to the new code that disallows this for read-only files.

I removed the part about deleting the files from the BAO Flight Game Entries section.

**Comment by weirddan455** [comment]
This program now works with file locking support from #3687

`allow_write_protected_files = false` is required for the install to complete.  Thanks again @MasterO2 for documenting.

**Comment by johnnovak** [comment]
@Python-Exoproject Some useful info on how to get this game to install in Staging:
https://github.com/dosbox-staging/dosbox-staging/wiki/Game-issues#bao-flight-simulator---flight-shop-addon
