### ISSUE TITLE
ES1688 emulation missing ESS Mixer registers

### ISSUE THREAD

**Issue by wbcbz7** [dosbox-staging/dosbox-staging#3700]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### What Operating System are you using?

Windows 10

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Hey there!
I've been recently checking out DOSBox Staging, and noticed that ESS AudioDrive emulation does not support extended ESS mixer registers, in particular Extended FM Volume register (index 0x36). 
For example, koolnESS by The Furnace Posse uses mixer registers to fade out audio during song changing or exit, and seems that this effect is missing in DOSBox Staging (reference capture from real ES1869 with fadeout here: https://youtu.be/i_4dg8xUaBA?si=cMV6Tn63Y4rMLMHs&t=190)

Thanks in advance! :)

### Download URL of affected game or software

https://www.pouet.net/prod.php?which=96920

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by johnnovak** [comment]
Indeed, thanks for reporting @wbcbz7! DOSBox-X has the 0x36 command implemented, so I missed that when I ported the code over. Enjoy Staging 😎

**Comment by johnnovak** [comment]
> I've been recently checking out DOSBox Staging, and noticed that ESS AudioDrive emulation does not support extended ESS mixer registers

@wbcbz7 I've fixed this in the linked ticket. Are you aware of any other programs that exercise the ESS specific mixer registers?

**Comment by wbcbz7** [comment]
I've just checked the latest dev build, and seems like fadeout is almost there, but it sounds like volume curve being too steep; also volume adjustment (using -/+ keys) doesn't work properly (volume drops by ~12dB and locks at that level). Looking in mixer-related commit, I've noticed there is a [typo](https://github.com/dosbox-staging/dosbox-staging/commit/c52451f2647c4be79baaa23fbccdd71a2ea49e61#diff-a7f7250de582823c8296278848d0e29b8a4dbf4a885ef4832e3f8546d270600aR2591) in `ctmixer_read()` function - it uses register index 0x34 instead of 0x36 for extended FM volume read. As volume control in musicdisk reads current volume from the mixer, this can be the issue for now. Nice progress, anyway :)

As for other ESS-enabled applications that are using ESS-specific mixers, apart from Windows 3.x/9x driveres, I am not aware of those.

**Comment by johnnovak** [comment]
@wbcbz7 Thanks for the pointers, this is helpful.

I'll fix the wrong register index for the mixer read port, sure, but fixing the volume ramp would require some reversing (DOSBox-X uses the same wrong ramp, just by looking at the code).

I have a bunch of ESS sound cards so I could reverse it, but frankly I have better things to do 😄 Maybe I'll try a hack to use the SB16 ramp for ESS, maybe that curve is a bit closer.

Overall, the DOSBox-X ESS mixer seems to be shoehorned into the SB mixer implementation, so it's kinda expected to be somewhat wrong if there was no extra validation of the actual hardware behaviour.

**Comment by johnnovak** [comment]
@wbcbz7 Fixed, and this is the extent I'm willing to go. The "proper" fix would involve using "mixed" SB Pro curves for the master volume and the DAC and ESS curves for the FM output (as we only support ESFM at the moment, but not the rest of the ESS card), and the complication is not worth it.

Our supported use case for the ESS card is only ESFM for FM and. SB Pro compatibility for the rest (including the DAC).

**Comment by wbcbz7** [comment]
yup, with the recent dev build FM volume mixer seems to behave as intended, and the difference between emulated and real mixer curve seems to be negligible enough, so I'll leave it as now. thanks for fixing! :)
