### ISSUE TITLE
WBAT misbehaving when calling batch file

### ISSUE THREAD

**Issue by QmwJlHuSg9pa** [dosbox-staging/dosbox-staging#3704]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### What Operating System are you using?

Linux x86_64

### Relevant hardware info

AMD Ryzen 2600X, AMD RX 580

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

[WBAT](https://www.horstmuc.de/ui.htm) is a utility that renders bespoke graphical interfaces. I have been using it to generate configuration dialog menus for games, though have noticed some of its core behaviour has broken after updating to v0.81.

Here's an example regarding the included demo script "colors.bat":

- Expected output (as per v0.80.1):

    Selecting a colour with the corresponding keyboard shortcut results in an immediate update to the example graphic.

    ![dosbox-staging-0 80 1-1](https://github.com/dosbox-staging/dosbox-staging/assets/1274826/55d09c8e-b4e8-4586-842d-3e2a9a42d6d3)
    After pressing "u":
    ![dosbox-staging-0 80 1-2](https://github.com/dosbox-staging/dosbox-staging/assets/1274826/5f70808d-6b36-4d3f-a3bd-cca0f264981e)

- Actual output (v0.81.0, v0.81.1):

    Colour selection appears delayed by an entire round -- a _second_ keyboard shortcut must be pressed before the _first_ selection is reflected by the graphic. This delay seems common to any variables set through "call w.bat".

### Steps to reproduce the behaviour.

1. Download WBAT v2.50 (wbat250.zip, "Dialog boxes for DOS batch") — https://www.horstmuc.de/ui.htm
2. Extract "wbat250" directory to drives/u/
3. Run `dosbox-staging`, enter commands:

    ```
    u:
    cd wbat250
    colors.bat
    ```

### Download URL of affected game or software

https://www.horstmuc.de/ui.htm

### Your configuration

```ini
Default config.
```

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by weirddan455** [comment]
I can reproduce this on 0.81.1 but it appears to have been fixed on `main` (not sure by what commit exactly).

**Comment by johnnovak** [comment]
@QmwJlHuSg9pa Can you confirm this works now as expected with the latest dev build?

**Comment by QmwJlHuSg9pa** [comment]
> @QmwJlHuSg9pa Can you confirm this works now as expected with the latest dev build?

Yes, can confirm this appears fixed in 0.82.0-alpha (7516d). Thank you both.

**Comment by johnnovak** [comment]
> > @QmwJlHuSg9pa Can you confirm this works now as expected with the latest dev build?
> 
> Yes, can confirm this appears fixed in 0.82.0-alpha (7516d). Thank you both.

Thanks @QmwJlHuSg9pa. Closing.
