### ISSUE TITLE
Windows DOSBox Staging does not properly register explorer context menu entries properly since 0.81.0 versions

### ISSUE THREAD

**Issue by MK26849781234968** [dosbox-staging/dosbox-staging#3706]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### What Operating System are you using?

Windows 11

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Once you upgrade from v0.79.1 to any v0.80.x version the context menu entries for .exe and .bat files disappear. There is a context menu created in the folder however but this does not open the folder (as in the v0.79.1 version).
Old version (BAT file):
![explorer_lyfcDK19JZ](https://github.com/dosbox-staging/dosbox-staging/assets/170988771/e045b642-6dc4-47f7-938f-eb57dfaa2898)

### Steps to reproduce the behaviour.

1. Have DOSBox staging v0.79.1 installed
2. Upgrade to v0.81.1 (preferably with the version installed as admin / for all users
3. Right Click any .exe .bat .com file and find the context menu missing
4. Right click in the folder and click the context menu entry and dosbox-staging will open but will not auto mount the folder you are currently in.

As far as I can see the following registry entries are not created at all:
```
Windows Registry Editor Version 5.00

[HKEY_CLASSES_ROOT\SystemFileAssociations\.bat\shell\Run with DOSBox Staging]
"Icon"="\"D:\\Program Files\\DOSBox Staging\\dosbox_with_console.bat\",0"

[HKEY_CLASSES_ROOT\SystemFileAssociations\.bat\shell\Run with DOSBox Staging\command]
@="\"D:\\Program Files\\DOSBox Staging\\dosbox_with_console.bat\" \"%1\""

[HKEY_LOCAL_MACHINE\SOFTWARE\Classes\SystemFileAssociations\.bat\shell\Run with DOSBox Staging]
"Icon"="\"D:\\Program Files\\DOSBox Staging\\dosbox_with_console.bat\",0"

[HKEY_LOCAL_MACHINE\SOFTWARE\Classes\SystemFileAssociations\.bat\shell\Run with DOSBox Staging\command]
@="\"D:\\Program Files\\DOSBox Staging\\dosbox_with_console.bat\" \"%1\""

[HKEY_CLASSES_ROOT\SystemFileAssociations\.com\shell\Run with DOSBox Staging]
"Icon"="\"D:\\Program Files\\DOSBox Staging\\dosbox_with_console.bat\",0"

[HKEY_CLASSES_ROOT\SystemFileAssociations\.com\shell\Run with DOSBox Staging\command]
@="\"D:\\Program Files\\DOSBox Staging\\dosbox_with_console.bat\" \"%1\""

[HKEY_LOCAL_MACHINE\SOFTWARE\Classes\SystemFileAssociations\.com\shell\Run with DOSBox Staging]
"Icon"="\"D:\\Program Files\\DOSBox Staging\\dosbox_with_console.bat\",0"

[HKEY_LOCAL_MACHINE\SOFTWARE\Classes\SystemFileAssociations\.com\shell\Run with DOSBox Staging\command]
@="\"D:\\Program Files\\DOSBox Staging\\dosbox_with_console.bat\" \"%1\""

[HKEY_CLASSES_ROOT\SystemFileAssociations\.exe\shell\Run with DOSBox Staging]
"Icon"="\"D:\\Program Files\\DOSBox Staging\\dosbox_with_console.bat\",0"

[HKEY_CLASSES_ROOT\SystemFileAssociations\.exe\shell\Run with DOSBox Staging\command]
@="\"D:\\Program Files\\DOSBox Staging\\dosbox_with_console.bat\" \"%1\""

[HKEY_LOCAL_MACHINE\SOFTWARE\Classes\SystemFileAssociations\.exe\shell\Run with DOSBox Staging]
"Icon"="\"D:\\Program Files\\DOSBox Staging\\dosbox_with_console.bat\",0"

[HKEY_LOCAL_MACHINE\SOFTWARE\Classes\SystemFileAssociations\.exe\shell\Run with DOSBox Staging\command]
@="\"D:\\Program Files\\DOSBox Staging\\dosbox_with_console.bat\" \"%1\""
```
^ Above where the install location should obviously be the install location of DOSBox Staging.

Furthermore for the shell (Open with / Directory):
v0.79.1
```
[HKEY_CLASSES_ROOT\Directory\Background\shell\dosbox-staging]
@="Open with DOSBox Staging"
"Icon"="\"D:\\Program Files\\DOSBox Staging\\dosbox_with_console.bat\",0"

[HKEY_CLASSES_ROOT\Directory\Background\shell\dosbox-staging\command]
@="\"D:\\Program Files\\DOSBox Staging\\dosbox_with_console.bat\" \"%v\""
```

Changed to:
```
Windows Registry Editor Version 5.00

[HKEY_CLASSES_ROOT\Directory\Background\shell\dosbox-staging]
@="Open with DOSBox Staging"
"Icon"="\"D:\\Program Files\\DOSBox Staging\\dosbox.exe\",0"

[HKEY_CLASSES_ROOT\Directory\Background\shell\dosbox-staging\command]
@="\"D:\\Program Files\\DOSBox Staging\\dosbox.exe\" --working-dir \"%v\""
```
The problem here is that the working dir seems to take priority above the mounting the dir (aka you start in the dosbox staging dir under Z: instead of the mounting happening and transferring to that as C:.
Picture of missing from BAT (is the same from .exe and .com)
![QiMdAOxKJT](https://github.com/dosbox-staging/dosbox-staging/assets/170988771/d853fb67-7408-4b58-a02b-4d880ce00296)

Importing the registry entries from 0.79.1 does fix the problem (or more like workarounds the problem). This however does reset the default open action to DOSBox-Staging with console.

### Your configuration

```ini
(Default 0.81.1 config deleted the %localappdata%\DOSBOX directory after upgrading and let DOSBox Staging create it again).
```

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by johnnovak** [comment]
@MK26849781234968 It's an intentional change. See here:
https://www.dosbox-staging.org/releases/release-notes/0.81.0/#normalise-windows-explorer-context-menus
