### ISSUE TITLE
Extraneous warning printed on switch to protected mode (regression from cycles change)

### ISSUE THREAD

**Issue by weirddan455** [dosbox-staging/dosbox-staging#3710]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### What Operating System are you using?

Linux x86_64

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

I'm getting the following warning on entering protect mode.  I have `core = auto` so I should be getting dynamic core.  I don't think the "try switching to dynamic core" text of the warning is needed.

If this was just an info message, that would be fine but it's showing up in orange on my console like something is wrong.  Maybe this message is only meant to show up if the user is running a normal/simple core with high cycles set?

### Steps to reproduce the behaviour.

Explain how to reproduce
1.  Start any protected mode game

### Provide a Log

```text
2024-05-29 15:51:57.876 | CPU: Setting fixed 60000 cycles. Try setting 'core = dynamic' for increased performance if you need more than 20000 cycles.
```

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by weirddan455** [comment]
Pinging @johnnovak and sorry if my suggestion to add these warnings was wrong.  I didn't actually test how these would look at the time of review.

**Comment by johnnovak** [comment]
> Pinging @johnnovak and sorry if my suggestion to add these warnings was wrong. I didn't actually test how these would look at the time of review.

Nah, I think it was a good suggestion, and I tested the changes, just not all permutation because I was sick of that PR already 😆 Although this is a basic use case... But should be easy to fix.

I'd like to keep these as warnings because otherwise they're not attention grabbing enough.

>  Maybe this message is only meant to show up if the user is running a normal/simple core with high cycles set?

Yes.
