### ISSUE TITLE
Where are these CRTC timings coming from?

### ISSUE THREAD

**Issue by MrMadguy64** [dosbox-staging/dosbox-staging#3715]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### What Operating System are you using?

Windows Other

### Question

As always. I don't have access to real old hardware, so I can't check anything myself. And examining DOSBox's sources has made me think, that it's author is very competent and knows a lot about real hardware.

First of all. Can I use EGA/VGA environment table at 0040:00A8 to produce modified modes? Is it supported by all EGA/VGA hardware? Or it's better not to use it? Overall idea - is that sync pulse position doesn't really matter, because old monitors had picture size/position knobs anyway. Only thing, that matters - is that sync pulse position should match for all modes. And only way to make sure, that it happens - to use timings, provided by BIOS itself.

Main question: can I read somewhere, how DOSBox CRTC timings are calculated? Where are they coming from? What sources can I read to find this info? How picture is positioned via sync pulses? What parameters matter? Leading edge? Trailing edge? Or may be something else? Why half-clock timings are so weird and don't match full-clock ones?

For example VGA:
[VGA 640 mode](https://s1.hostingkartinok.com/uploads/images/2024/05/66d7fcffe631ecad773cc581857a0eda.png)
[VGA 320 mode](https://s1.hostingkartinok.com/uploads/images/2024/05/26f1592393e0794995e8aff9d2ddce96.png)

Problems:
1) Timings don't match [standard VGA](https://pdfslide.us/documents/ibm-vga-xga-technical-reference-manual-may92.html?page=416) ones, because 16 pixel front porch is specified for them, and we see 40 here.
2) Timings don't match [VESA GTF](https://glenwing.github.io/docs/VESA-GTF-1.1.pdf) ones, because 8% sync pulse length (64 pixels) and trailing edge position being midway within blanking period (16 pixels front porch) are specified for them
3) I expected half-clock timings to be simply divided by 2. But they aren't. They aren't even specified in VGA standard, so I expect them to be exactly the same, as full-clock ones in terms of time.
4) Sync pulse end is weird. It overlaps with next active display period. Is it right?

But all of a sudden even real **MODERN** hardware uses these timings:
[Radeon 640 mode](https://s1.hostingkartinok.com/uploads/images/2024/05/4223e7291287abeb238e2223473197db.jpg)
[Radeon 320 mode](https://s1.hostingkartinok.com/uploads/images/2024/05/a2c3566d0e0dd7b96fc4e1a9d4430163.jpg)
[NVidia 640 mode](https://s1.hostingkartinok.com/uploads/images/2024/05/48fbf8e9ec897875bbf1194c544c343a.jpg)
[NVidia 320 mode, color isn't actually green](https://s1.hostingkartinok.com/uploads/images/2024/05/cf9470cf94126cf2de1342109021a0db.jpg)

For EGA things are even weirder:
[EGA 640 mode](https://s1.hostingkartinok.com/uploads/images/2024/05/5aaef4d884abc9f13fe62f9c4426d06f.png)
[EGA 320 mode](https://s1.hostingkartinok.com/uploads/images/2024/05/13a4000d1b74af1eb537c42ee6ee1ace.png)

Timings don't match specified here [IBM EGA](https://minuszerodegrees.net/oa/OA%20-%20IBM%20Enhanced%20Graphics%20Adapter.pdf). Why sync pulse overlaps with active period so much? Are they real? Please note, that EGA CRTC timings for mode 0x0D [here](https://github.com/dosbox-staging/dosbox-staging/blob/main/src/ints/int10_vptable.cpp) are carried from original DOSBox 0.74 and don't look right. First of all horizontal total is +2 for EGA, not +5. Plus 8A for retrace end means it's 0A, i.e. either 0A, 2A or 4A. It's definitely mistake. Should be 3A, I guess, but therefore retrace end should be the same, as blanking end, i.e. 9A, not 8A.

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by johnnovak** [comment]
> Main question: can I read somewhere, how DOSBox CRTC timings are calculated? Where are they coming from? What sources can I read to find this info? How picture is positioned via sync pulses? What parameters matter? Leading edge? Trailing edge? Or may be something else? Why half-clock timings are so weird and don't match full-clock ones?

I have no idea. If you ever figure it out, you tell us 😆 

DOSBox-X added som extra custom modes. I asked @joncampbell123 how he came up with the timings—his answer basically was more or less "I tweaked the numbers until I got a picture" 😆 

So, dunno man 🤷🏻 😎

**Comment by MrMadguy64** [comment]
> 
> But why do you need to know? Do you want to do anything practical here, or you're just curious and wanna know?
> 
Well, my goal - is to target real hardware. Of course I can just hardcode values, DOSBox uses. Everything would work in DOSBox. But will it work on real hardware?

I believe, that DOSBox just doesn't bother about blanking and sync pulses. They aren't actually needed for emulation. What matters: total and active period. Total is needed to calculate FPS. And active period - is what actually displayed on screen. As we emulate things - we can always know, what active period is and fit on to screen. Real monitors - are completely different thing. Only things, they can measure - are hsync and vsync polarity and frequences. And therefore everything else should either be: a) Standard b) Calculable. MDA, CGA, EGA, VGA - are standards. VESA modes are calculated via VESA GTF.

So, sync pulses are needed on real hardware to align picture. Blanking is usually chosen to achieve minimal borders. I.e. blanking is usually Total - Active - 2. And only sync pulse width usually matters. It's position doesn't matter. It should just be almost the same for all modes, so picture wouldn't shift in case of switching to other mode. Specific alignment picture, that matches specific BIOS parameters can be achieved via knobs. Even when monitor itself is digital, CRT is still analog device and should be adjusted manually.

Problem, I have: is that the most compatible modes - are modes provided by BIOS. Because they already work and monitor is already adjusted to them. Hardcoding timings - is bad idea. It can lead to incompatibilities. Another problem - is that only VGA provides read-write access to it's registers. So, it's relatively easy to modify existing modes without touching anything else. Everything else requires reprogramming registers from scratch. Even to change just one bit. So, the best idea here - is to ask BIOS, what timings are used. But it's not always possible. Therefore I need hardcoded timings at least as backup plan.

And I don't know, where to get them. What I assumed - that DOSBox was precise emulator. At least DOSBox-X. So, I could just copy-paste it's timings. But, I guess, it isn't. EGA isn't fully emulated. It's more like VGA with EGA frequences and sync pulses being completely messed up. Lack of GC write mode 3 on EGA isn't emulated. Reprogramming CRT wouldn't work properly either, cuz htot is calculated wrong way. I guess, that's because goal isn't to emulate hardware as precisely, as possible, but to just allow old software to run on it.

So, the best idea - is to just use standard timings from old manuals. But there is just one question here. As I've shown on my screenshots, real hardware uses exactly the same timings, DOSBox and other emulators use. And I don't understand, why? Because they're neither standard VGA ones, nor VESA GTF ones. But picture is shown properly without any shifts. So, may be these modes are hardcoded in all modern monitors? That's why I ask to provide some source. And again. Why difference between 640 and 320 mode? Why 7 for 320 (112 pixels and overlapping with active period), if for 640 it's proper 12 (96 pixels, as in VGA standard)? VGA manual says trailing edge position has special meaning for half-clock modes? What special meaning?

What I'm also curious about - is how picture alignment was performed by real hardware back in old IBM days? Modern hardware can use hardcoded modes or calculated one. But old ones were standard. How they were chosen? What sync pulse parameters mattered? What was done on leading edge and what on trailing one? Why full-clock and half-clock modes don't match? EGA for example. Retrace start for 640 mode is 5E, length is 8. Retrace length is ok for 320 mode, i.e. 4, but start is 30, while I would expect 2F. Why? I guess, it's connected to borders being 2x wider. If so, distance between what and what actually matters? Between leading edge and active period? Or between trailing edge and active period? Or may be even something else?

I just can't calculate my own timings without knowing all that info.

**Comment by joncampbell123** [comment]
If you want register values true to 1990s hardware, perhaps you might make use of the VGA register snapshots I've published on my hackipedia site:

http://hackipedia.org/browse.cgi/Computer/Platform/PC%2c%20IBM%20compatible/Video/VGA/VGA%20register%20snapshots

VGA register reference: http://www.osdever.net/FreeVGA/vga/vga.htm

**Comment by MrMadguy64** [comment]
> If you want register values true to 1990s hardware, perhaps you might make use of the VGA register snapshots I've published on my hackipedia site:
> 
> http://hackipedia.org/browse.cgi/Computer/Platform/PC%2c%20IBM%20compatible/Video/VGA/VGA%20register%20snapshots
> 
> VGA register reference: http://www.osdever.net/FreeVGA/vga/vga.htm
> 
> These settings obviously pre-date the more modern VESA standards but DOSBox (X, staging, etc) is meant to emulate 1980s and 1990s hardware, so it should be fine.

Ok. Even old real hardware uses it. I was confused by all documents googled via "VGA timings" telling me, that standard 640x480x60 VGA mode should have front porch 0.636us, i.e. 2 character clocks. And it's still confusing for me, why sync pulse is longer and overlaps active display period for 320 mode, i.e. gets out of blanking.

But how about EGA? I understand, that EGA registers dumping isn't possible, as they're read only. But how about examining environment table? Can I assume, that all hardware supports it? How about CGA and other adapters? I understand, that it's pointless to add PCjr or Tandy support to 32bit application, but I still want to do it.

**Comment by joncampbell123** [comment]
I think there is a way to determine what registers are written to EGA. There's supposedly a table pointed to from the BIOS data area that lists sets of register values to program in various modes. I think. Maybe that's only a feature of MCGA and VGA BIOSes.

Another idea might be to get a hold of a system with an EGA card and a 386, write a minimalist program to switch the CPU into virtual 8086 mode, have it execute INT 10h and trap and log all I/O, then switch back to real mode and write the log to disk.

**Comment by johnnovak** [comment]
@MrMadguy64 I did not read your while huge block of text because it seemed after the first sentence you're not here to talk about DOSBox development, but gather information from it for your hardware project.

If so, could you please restrict the conversation to DOSBox related topics only, or continue in retro hardware-related forums with fellow hardware enthusiasts?

Thanks.

**Comment by johnnovak** [comment]
Okay, closing because as @MrMadguy64 said, this question is not about DOSBox Staging development or about getting help using DOSBox:

> Well, my goal - is to target real hardware. Of course I can just hardcode values, DOSBox uses. Everything would work in DOSBox. But will it work on real hardware?
