### ISSUE TITLE
keymapper window tiny, and won't scale up on Windows

### ISSUE THREAD

**Issue by madbrain76** [dosbox-staging/dosbox-staging#3717]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### What Operating System are you using?

Windows 10

### Relevant hardware info

AMD 5950X, 64GB RAM, GTX 3060Ti GPU, triple monitors ( 2 x 4K, 1x HD)

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

The keymapper window is very small and unreadable on my multiple 32" 4K monitor. It cannot be resized. Only the magnifying glass helps, but it very tedious to use with that program as there are so many buttons to click

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Open dosbox staging
2. Press CTRL-1 to open keymapper
3. Observe how small the window is, and the lack of resizable border or maximize button

### Your configuration

```ini
N/A
```

### Provide a Log

```text
N/A
```

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by johnnovak** [comment]
@madbrain76 Can you paste a screenshot here, please? If you enlarge the window, the mapper should fill your window completely. Is that not happening?

**Comment by madbrain76** [comment]
Sorry , this works fine , I just have way too many Dosbox forks, sigh. The Windows start menu picks a different one every time when I type dosbox.
Would be a lot simpler if there was a way to just reboot it rather than close with CTRL+F9 and reopen.

**Comment by johnnovak** [comment]
> Sorry , this works fine , I just have way too many Dosbox forks, sigh. The Windows start menu picks a different one every time when I type dosbox. Would be a lot simpler if there was a way to just reboot it rather than close with CTRL+F9 and reopen.

No problem.

You can restart DOSBox Staging with the Ctrl+Alt+Home key combo.

I know you're very far from a beginner when it comes to DOS, but the Getting Started guide I wrote last year contains lots of helpful Staging related tips, so I recommended reading it. It's aimed for absolute beginners so you can skip most parts that relate to DOS itself.

E.g., the restart is described on this page, search for "Making configuration changes":
https://www.dosbox-staging.org/getting-started/enhancing-prince-of-persia/

Closing this ticket as it seems you've figured it out the issue.
