### ISSUE TITLE
Daggerfall: Shop/tavern theme only playing drums

### ISSUE THREAD

**Issue by Castor215** [dosbox-staging/dosbox-staging#3719]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### What Operating System are you using?

Linux x86_64

### If Other OS, please describe

Debian

### Relevant hardware info

AMD 5600X, NVidia 1050Ti

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

When using General Midi (MPU-401) with both system and wrapped fluidsynth, one of the music trakcs doesn't play properly.

Here is what it is supposed to sound like:
[https://www.youtube.com/watch?v=jM8EaL1Zm6w&t=69](url)

When I play it, I only hear drums. Fluidsynth provides the following log:
```
fluidsynth: warning: Instrument not found on channel 9 [bank=128 prog=49], substituted [bank=128 prog=0]
```

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Start Daggerfall
2.Go to a shop or tavern (this is tricky, because the game chooses music randomly and plays the same one until IRL midnight).

### Download URL of affected game or software

https://cdnstatic.bethsoft.com/elderscrolls.com/assets/files/tes/extras/DFInstall.zip

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by Grounded0** [comment]
What soundfont are you using?

**Comment by Castor215** [comment]
> What soundfont are you using?

I have tried default-GM.sf2, FluidR3_GM.sf2 and TimGM6mb.sf2. These three come with the fluidsynth system library. The same issue occurs with all of them.

**Comment by interloper98** [comment]
> Here is what it is supposed to sound like:

@Castor215, did you mean to attach a good recording or maybe a link to a youtube video or something? I'm not able to see/hear what it should sound like.

**Comment by Grounded0** [comment]
Try using the soundfont bundled with out DOSBox Staging Starter Pack:

https://archive.org/details/dosboxstarterpack

This one has full Roland GS support so if its a missing instrument issue that might fix it.

**Comment by Castor215** [comment]
> > Here is what it is supposed to sound like:
> 
> @Castor215, did you mean to attach a good recording or maybe a link to a youtube video or something? I'm not able to see/hear what it should sound like.

Messed up the link, sorry. It's been fixed in OP

I tried the soundfont provided in the starter pack. Unfortunately, it still has the same problem. Oddly, setting both Midi and Digital in Daggerfall's SETUP.EXE causes the music to work fine, albeit not General MIDI quality.

Setting `mididevice = mt32` and `mpu401 = intelligent` and selecting "mpu401" as the midi device in SETUP.EXE has the same problem. Setting the midi device to "MT-32" (the game setting, not dosbox's) with these config settings causes SETUP.EXE to crash to the DOS prompt, unless I set `mpu401 = none`. In this case SETUP.EXE just says the device can't be initalized.

Gravis Ultrasound just _refuses_ to work with SETUP.EXE. I have tried all different port numbers, irqs, etc. and nothing.

**Comment by Castor215** [comment]
I have an update. Using `mididevice = fluidsynth` and `mpu401 = intelligent` but setting Midi device to "Roland Sound Canvas" caused the problem to go away. Now I can set the device back to "MPU-401" with no issue. This a weird ghost-in-the-machine type problem. It may have been a problem with the save, too.

Closing this for now in case it was a save issue. I will reopen it if it comes back. Sorry if I wasted everyone's time.

**Comment by weirddan455** [comment]
Glad you got it working @Castor215 

For what it's worth, I've noticed an issue with Debian's fluidsynth 2.3.1  It caused a weird echoing sound in Doom.  I fixed by removing my `libfluidsynth-dev` package to force Meson to compile the newer version 2.3.3 from source.  You can also compile with `-Dforce_fallback_for=fluidsynth` if you don't want to remove the package.

Note that this is only an issue if you compile from source.  If you're using our binary package, it comes statically linked with the newer version so you shouldn't have issues regardless of what packages you have installed.

Not sure if this is related to your problems but thought I would mention it since you listed Debian as your OS.

**Comment by Grounded0** [comment]
If you want maximum MIDI quality on games you should set them to Roland Sound Canvas if available as it may enable Roland GS features and instruments that FluidSynth at least partially implements.

**Comment by johnnovak** [comment]
Yeah, and many setup utils lie about stuff. "MPU-401" sound option, lol, that can be anything. Probably what they meant is that a regular General MIDI output or something... Maybe they're stripping GS commands on the fly if "MPU-401" is configured, or who knows 🤷🏻 


Checking this list is also recommended; often you can find useful tips on configuring the MIDI output for specific games (and the list is not just about MT-32):

https://www.vogonswiki.com/index.php/List_of_MT-32-compatible_computer_games

Lots of setup utilities are plain wrong, e.g., check out this huge "Games that falsely claim MT-32 compatibility" section:

https://www.vogonswiki.com/index.php/List_of_MT-32-compatible_computer_games#Games_that_falsely_claim_MT-32_compatibility
