### ISSUE TITLE
The Horde CD stopped working in 0.81.0 and 0.81.1

### ISSUE THREAD

**Issue by PoulpSquad** [dosbox-staging/dosbox-staging#3720]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### What Operating System are you using?

Windows 10

### Relevant hardware info

i7 7700K, 32GB RAM, GTX 1070

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

The Horde CD stopped working in 0.81.0 and 0.81.1

0.80.0 (x64): Works fine
0.80.1(x64): Works fine
0.81.0: Black screen
0.81.1: Black screen

I used my current (0.81.1) config for all 4 tests. Config follows:

[dosbox-staging.conf.txt](https://github.com/user-attachments/files/15519294/dosbox-staging.conf.txt)

I'm sorry for my amateurish report!

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Install the Horde CD
2. Run as per usual
3. 0.81.0 and 0.81.1 are stuck at a black screen

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by weirddan455** [comment]
I can't reproduce this.  The game starts fine for me on 0.81.1 and on main.  You've got a bunch of crap in your autoexec running executables and batch files that I don't have though.  Can you try clearing some of this stuff out and see if it runs?

```
[autoexec]
# Lines in this section will be run at startup.
# You can put your MOUNT lines here.
@echo off
cls
date 01/01/1999
time 00:00:00
z:\mount.com c "f:\emus\dosbox\c" -t dir -size 512,16,65534,57893 -label DOSBOX > nul
c:
path c:\;c:\batch\system;c:\dos;z:\;c:\batch\apps;c:\batch\games;c:\batch\demos;
if exist c:\command.com c:\dos\deltree.com /y c:\command.com > nul
c:\dos\xcopy.exe z:\command.com c:\ > nul
set comspec=c:\command.com
c:\dos\deltree.com /y c:\temp > nul
md c:\temp
set temp=c:\temp
set msinput=c:\msinput
set sound=c:\sb16
c:\ultrasnd\ultrinit.exe -dl -dm -dj > nul
set isopath=f:\emus\dosbox\library
set dircmd=/p
call c:\batch\system\reset.bat
ver
echo.
```

**Comment by PoulpSquad** [comment]
Is this better?

mount.com c f:\emus\dosbox\c -t dir
c:
imgmount.com d f:\Emus\DOSBox\library\hordecd.cue -t iso -fs iso
cd c:\horde
horde.exe

I sure hope so, because it works fine with this!

Not sure why it worked with 0.80 and 0.80.1, but I guess I'll do some cleaning up and remove lots of dead wood from that config file.

Thank you for your time!

**Comment by johnnovak** [comment]
Thanks @weirddan455.

Lesson for the future @PoulpSquad: when hitting weird issues, always try with a minimal config, and try narrowing down the problem before raising a ticket.

To put it differently, we will not go and figure out what all these complicated and/or messy random custom configs in people's setups. The most we can do is test the same game with a clean config, starting from scratch, then tell the person who raised the ticket it works for us 🤷🏻

**Comment by PoulpSquad** [comment]
Indeed, I should have started with that before posting, I am sorry.

Nonetheless, I'd like to point out a weirdness related to my issues with Horde.

This time I started with a clean .conf, and I added these lines in the [autoexec] section:

mount c f:\emus\dosbox\c -t dir
c:
imgmount d f:\Emus\dosbox\library\hordecd.cue -t iso -fs iso
cd c:\horde

If I do a vmem_delay=off or a vga_render_per_scanline=true, the Horde will freeze on a black screen.

Notice I used the default values, which I find odd.

I'll just stop wasting your time and start removing dumb stuff from them batches now.

**Comment by johnnovak** [comment]
> If I do a vmem_delay=off or a vga_render_per_scanline=true, the Horde will freeze on a black screen.
> 
> Notice I used the default values, which I find odd.

Are you 100%-absolutely-with-sugar-on-the-top sure? 😄 I don't see how that can happens are those are the defaults, yeah.

Can you test it a few more times to gain confidence? Then if that's there is a weird problem, can you please raise the separate issue?

**Comment by PoulpSquad** [comment]
Yes I am. That's why the Horde froze the first time around when I first posted about my issue.

I have a batch that will set vga_render_per_scanline to false for Ishar 3, and I just happened to run the Horde next, and it froze.

I can reproduce this consistently. Here is my conf:

[dosbox-staging.conf.txt](https://github.com/user-attachments/files/15519728/dosbox-staging.conf.txt)

**Comment by johnnovak** [comment]
Thank you @PoulpSquad, we'll investigate.
