### ISSUE TITLE
Probable bug when checking VGA scanlines

### ISSUE THREAD

**Issue by Arcnor** [dosbox-staging/dosbox-staging#3733]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Different version than latest?

main

### What Operating System are you using?

None

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

The variable at https://github.com/dosbox-staging/dosbox-staging/blob/0979adf7e226feea9aac5bd52d07666c6bf7eda1/src/hardware/vga_draw.cpp#L2308 is a `bool` one, but gets compared as an `int` later. This might not be correct.

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by johnnovak** [comment]
My bad, that was my doing. Works out fine in practice because it's only used in a `num_scanline_repeats > 0` check a few lines further down, but I'll fix it.
