### ISSUE TITLE
Add codepage handing to the filesystem support (local, overlay, ISO, FAT, BIN+CUE)

### ISSUE THREAD

**Issue by Torinde** [dosbox-staging/dosbox-staging#3740]
[Project card](https://github.com/dosbox-staging/dosbox-staging/projects/7#card-71851613)
> Add codepage handing to the filesystem support (local, overlay, iso, fat, bin/que).
@SmilingSpectre noted, "It's not so rare, actually. I've seen several Russian games with this problem. Korean/chinese/japanese games. Hacking groups. And I just started to suspect that this is exactly the reason why Gato's installer doesn't work: it has names with spaces, which is fine in real DOS, it seems, but break DOSBox immediately."
Added by [kcgen](https://github.com/kcgen)

https://github.com/dosbox-staging/dosbox-staging/issues/3646#issuecomment-2135396455
> That is in the pipeline and it will come... one day. Don't expect it soon, it's complex, and it will probably take years.

**Comment by Grounded0** [comment]
Closing as duplicate of:

- #2619

**Comment by Grounded0** [comment]
Dropping https://github.com/dosbox-staging/dosbox-staging/labels/game%20compatibility since GATO (1984) itself runs properly even if the installer fails.
