### ISSUE TITLE
Mortal Kombat 1+2 CD config saving issue

### ISSUE THREAD

**Issue by Silanda** [dosbox-staging/dosbox-staging#3745]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Different version than latest?

0.81.1

### What Operating System are you using?

Windows 11

### Relevant hardware info

Ryzen 3700x, Nvidia RTX 4070ti 

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Saving the options in Mortal Kombat 1 or 2 doesn't work after the first time they're set.

I broadly know what the cause of the problem is: depending on the game, the options are saved to the file CMOS.MK1 or CMOS.MK2. The problem seems to be that the game sets the attributes of the options file to hidden and system, and Dosbox seems to no longer be able to write to the file once those are set.

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Start the game
2. Press F10 to get to the options screen
3. Set options and exit.
4. Go back to the options and change something.
5. Exit the game.
6. Restart the game.
7. The options last set will not have stuck.

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by weirddan455** [comment]
Cannot reproduce on Linux.  It does create `CMOS.MK1` with hidden, system, and archive bits set (which correctly get saved with extended attributes on Linux).

Needs testing on Windows.  Possibly related based on a comment I saw in the Windows code: #3262 #3265

**Comment by weirddan455** [comment]
Confirmed Windows bug and it's a regression from ff90cc5666e2be79e62afe624634c826e51c33f3
