### ISSUE TITLE
use final on non further derived classes

### ISSUE THREAD

**Issue by LowLevelMahn** [dosbox-staging/dosbox-staging#376]
if there are any derives at all
https://devblogs.microsoft.com/cppblog/the-performance-benefits-of-final-classes/

**Comment by dreamer** [comment]
There are some C++ features, that we *don't* want to use, but those are listed in our [Coding Style Guidelines](https://github.com/dosbox-staging/dosbox-staging/blob/master/CONTRIBUTING.md#coding-style). `final` is not listed there.

`final` (alongside other "new" C++ features) is definitely allowed and will be used *when appropriate*.

@LowLevelMahn thanks for the issue, but I find it non-actionable, so I'm closing it.
