### ISSUE TITLE
Magic Candle 2, The - The Four and Forty (1991) - MT32 not working

### ISSUE THREAD

**Issue by Python-Exoproject** [dosbox-staging/dosbox-staging#3760]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Different version than latest?

82a

### What Operating System are you using?

Windows 11

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

In ECE release 4230 and Staging you get no MT32 music during the intro (the cutscene after you start a new game, select a save slot, and name your character).

In ECE 4460 however the cutscene has MT32 music. The scene should have music as evidenced by the same scene having music in all forks when Sound Blaster is used.

There is music during the logo screen in all forks so this can be ignored as not relevant to the issue.

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Start the game
2. Get past the logo screen
3. Select 'New'
4. Select your slot
5. rename the character or not
6. Listen for the music in the cutscene

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by johnnovak** [comment]
@Python-Exoproject Does X play MT-32 music during the cutscene, do you know?

**Comment by interloper98** [comment]
If it works in ECE, then maybe it's a regression in Staging?

My understanding is that Staging is a superset of SVN & ECE:
 - ECE patched on top the latest SVN
 - Staging is based on the latest SVN + (all?) of ECE's patches (in some form or another) + 2200 more GitHub PRs.

**Comment by interloper98** [comment]
Compared old releases (win11) - 0.77 was OK but then in 0.78 it stopped working.

**Comment by johnnovak** [comment]
> If it works in ECE, then maybe it's a regression in Staging?
> 
> My understanding is that Staging is a superset of SVN & ECE:
> 
>     * ECE patched on top the latest SVN
> 
>     * Staging is based on the latest SVN + (all?) of ECE's patches (in some form or another) + 2200 more GitHub PRs.

Kinda true, or was true at some point. But with the constant enhancements, refactorings, additions, fixes, etc., the occasional regression is inevitable and these get only discovered 6+ month or years later... Unless someone tests every DOS program after every single change.

Over time we will converge to the ideal solution, if enough people test enough number of progams and reports bugs. Thst's the only way, and the way of progression is not a straight line.

**Comment by johnnovak** [comment]
> Compared old releases (win11) - 0.77 was OK but then in 0.78 it stopped working.

Thanks. Wanna take a stab at it?

**Comment by interloper98** [comment]
> > Compared old releases (win11) - 0.77 was OK but then in 0.78 it stopped working.
> 
> Thanks. Wanna take a stab at it?

Sure. Will poke around and try bisecting on my retropie box.
