### ISSUE TITLE
VESA 256c line problem in Synthetic Dimensions 1995+ games

### ISSUE THREAD

**Issue by interloper98** [dosbox-staging/dosbox-staging#3762]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Different version than latest?

0.82-alpha

### What Operating System are you using?

Windows 11

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Synthetic Dimensions' games set various 256c VESA modes and hit a bug in DOSBox (SVN, Staging, ECE) VESA handling:

![chronicles-intro](https://github.com/dosbox-staging/dosbox-staging/assets/165201780/5333f83c-d1c5-4d6d-a927-60f9250adc76)
![synthetic-dimensions-logo](https://github.com/dosbox-staging/dosbox-staging/assets/165201780/a347a11d-d2d7-4416-a69e-b802a5621451)
![chronicles-of-the-sword-logo](https://github.com/dosbox-staging/dosbox-staging/assets/165201780/b715343b-61c3-4e1a-989f-32ec5595ccc3)
![druid-logo](https://github.com/dosbox-staging/dosbox-staging/assets/165201780/867b6307-6d83-48f4-b3a7-3a66c99d0262)
![sirtech-logo](https://github.com/dosbox-staging/dosbox-staging/assets/165201780/72d514e1-7fff-487c-9890-a79c87c1865d)
![grolier](https://github.com/dosbox-staging/dosbox-staging/assets/165201780/e2948ceb-07dd-4f62-bb1b-8fcf33f1ea22)
![perfect-assassin-logo](https://github.com/dosbox-staging/dosbox-staging/assets/165201780/87fa5ba1-1c6c-4b20-ae82-c09d655dff68)
![synthetic-dimensions-round-logo](https://github.com/dosbox-staging/dosbox-staging/assets/165201780/efa992f7-a10a-43cf-8965-7180f30d8fb4)

---

The games are:
 - Chronicles of the Sword (1996)
 - Druid - Daemons of the Mind (1995)
 - Perfect Assassin (1997)

ripsaw8080 at https://www.vogons.org has created a TSR to correct this shortcoming:

> Try the attached workaround program, just run it in DOSBox before running the game.

> Other games, particularly those developed by Synthetic Dimensions, have the same issue where the workaround may help.

> BTW, Chronicles of The Sword uses CD-audio channel control for speech, and you'll need an SVN build of DOSBox for that to work as intended.

Attachments:  [vesa32.zip](https://github.com/user-attachments/files/15795791/vesa32.zip)
license: Fair use/fair dealing exception

---

The TSR is a great fix for these games, but ideally it could be fixed in the VESA emulation code to improve its accuracy.

### Steps to reproduce the behaviour.

Explain how to reproduce:
1. Start the games as-is

### Download URL of affected game or software

eXoDOS v6: cotsword, druiddm, passass

### Your configuration

Standalone `cotsword\dosbox.conf`:

```ini
[cpu]
cpu_cycles = 60000

[autoexec]
mount c .
imgmount d cd/csword*.cue -t cdrom
c:
cd cots
call run.bat
```

Standalone `druiddm\dosbox.conf`:

```ini
[cpu]
cpu_cycles = 60000

[autoexec]
@mount c .
imgmount d cd\Druid.cue -t cdrom
c:
cd druiddm
call run
```

Standalone `passass\dosbox.conf`:

```ini
[cpu]
cpu_cycles = 100000

[autoexec]
mount c .
imgmount d cd\perfect.img -t cdrom
c:
call run
```

### Provide a Log

```text
N/A
```

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by Grounded0** [comment]
Does DOSBox-X handle this correctly?

**Comment by interloper98** [comment]
> Does DOSBox-X handle this correctly?

Turns out yes: a user 'torpedo' just added a message to the vogons thread:

> The thegreatcodeholio also provided an alternative fix [Druid: Dæmons of the Mind](https://www.vogons.org/viewtopic.php?t=32153)

thegreatcodeholio's fix is done in the `int10_vesa_map_as_128kb = true` code path in DOSBox-X (int10_modes.cpp and vga.cpp).

**Comment by johnnovak** [comment]
Thanks @interloper98, great find 🏅 I'm gonna incorporate the fix from X today, it seems general enough and it's very simple.

**Comment by johnnovak** [comment]
Pinging @Python-Exoproject as this affects eXoDOS.

**Comment by Python-Exoproject** [comment]
Thanks @johnnovak

**Comment by johnnovak** [comment]
@Python-Exoproject Fixed in the latest dev version, you no longer need the TSR.
