### ISSUE TITLE
MSCDEX additional names similiar official programs

### ISSUE THREAD

**Issue by xga-cga** [dosbox-staging/dosbox-staging#3774]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### What Operating System are you using?

Windows 11

### If Other OS, please describe

May test on: freedos 1.3 original hardware; DOSBOX-X, MSDOS 4.01 ( fixed https://github.com/hharte/MS-DOS/commit/1f506100a818cb9b6c2b29aeda8d4d24d094c477 )--qemu 
### Is your feature request related to a problem? Please describe.

Having speed/timing related errors with World Rally Fever CDROM ISO...  and original disc of X-men Children of the Atom...  (after install xmen game and try to play it can't find cd or related issue)...  It was noted by some that games such as Fade to Black have a cdrom speed check..,. 

### Describe the solution you'd like
Possible features (these are not fixes)- 
better documentation of  mscdex commands...
how to solve naming compatabily issues if any with: MSCDEX.EXE or mscdexnt or SHSUCDX  (maybe give menu option to select one )
Speed Settings:  Set cd drive speed or hard drive speed if necessary for compatability

The following is available in freedos: SHSUCDX https://help.fdos.org/en/hhstndrd/base/mscdex.htm  It's a pointer not driver, it was said in mscdex.h
mscdex or mscdexnt - :https://www.computerhope.com/mscdex.htm
wiki entry: https://en.wikipedia.org/wiki/MSCDEX

thanks for hard work!

### Describe alternatives you've considered

I was going to try freedos for the xmen game. Dosbox-x had/has a harddrive speed limiter setting: dos rate: 

https://github.com/joncampbell123/dosbox-x/issues/2835
2x cdrom is about "dos hard drive data rate limit=307200".

-- Had troubles with WRF having cd errors so will try another soundblaster...  also people have made their own soundcards and can look for drivers...
 
May try copying all install files and cd files in xmen cd to a single directory to avoid using pointer mscdex...  

Looked into adding: https://en.wikipedia.org/wiki/VDMSound  to pc, don't know license or could add to DOSBox_Staging

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by MasterO2** [comment]
@xga-cga Just so you know, regarding X-Men: Children of the Atom, you can also play the original arcade version of that game against human opponents online via [Fightcade](https://www.fightcade.com/), but you will have to find the ROMs yourself, for obvious legal reasons.  

https://github.com/dosbox-staging/dosbox-staging/wiki/Tips-&-tricks#dont-play-the-dos-ports-of-mk-and-sf2-use-fightcade

As far as setting CD speed is concerned, doesn't Dosbox-X have support for something like that?  Anyone want to comment on that?

**Comment by Grounded0** [comment]
X-Men: Children of the Atom was originally a Capcom CPS-2 arcade cabinet game.

I use RetroArch with FinalBurn Neo core to play CPS-2 games like Street Fighter Alpha 3.

Arcade ports should be always avoided when possible.

**Comment by johnnovak** [comment]
@xga-cga 
We won't support MSCDEX.EXE and similar drivers directly. Our MSCDEX equivalent is implemented inside the emulator.

Please raise individual tickets for CD based games that currently don't run in Staging. We might add support for setting the CD-ROM speed via a config setting if necessary.

**Comment by rderooy** [comment]
Instead of a config option, it could also be implemented as a mount option. e.g., `-speed 2x`

**Comment by xga-cga** [comment]
> ### Is your feature request related to a problem? Please describe.

Suggestion: May want to remove this to stay focused on feature adding... or mark as optional in form...

**Comment by MasterO2** [comment]
> > @xga-cga Just so you know, regarding X-Men: Children of the Atom, you can also play the original arcade version of that game against human opponents online via [Fightcade](https://www.fightcade.com/), but you will have to find the ROMs yourself, for obvious legal reasons.
> > https://github.com/dosbox-staging/dosbox-staging/wiki/Tips-&-tricks#dont-play-the-dos-ports-of-mk-and-sf2-use-fightcade
> > besides fightcade there is also official ports to Windows...  but original can be better,
> 
> you can now look into MSDOS 4.01 source https://fabulous.systems/posts/2024/05/a-minor-update-ms-dos-4-1-is-here/ didn't add before
> 
> > As far as setting CD speed is concerned, doesn't Dosbox-X have support for something like that? Anyone want to comment on that?
> > I did briefly, based on what others have said will make new feature request: [joncampbell123/dosbox-x#2835](https://github.com/joncampbell123/dosbox-x/issues/2835)

Steam does sell many of Capcom's fighting games these days as well, though I am not sure what the situation is with regard to the various Marvel fighting games developed by Capcom.

**Comment by xga-cga** [comment]
> @xga-cga We won't support MSCDEX.EXE and similar drivers directly. Our MSCDEX equivalent is implemented inside the emulator.
I had been specifying, MSCDEX.EXE in Autoexec portion of config, seemed to work better.  Will specifying MSCDEX.EXE be required.  I think system boot floppies ask.  Could you peoples document this in a FAQ or somewhere? :-) Maybe non-Admin's are able to?  I can help on guide some.

> 
> Please raise individual tickets for CD based games that currently don't run in Staging. We might add support for setting the CD-ROM speed via a config setting if necessary.
Noted.
> 
> Also, please try to focus on a single issue in future tickets.  
Tried to but I had no idea of the cause of the issues
