### ISSUE TITLE
Set CD-ROM Speed (may help with games that request it)

### ISSUE THREAD

**Issue by xga-cga** [dosbox-staging/dosbox-staging#3776]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### What Operating System are you using?

None

### Is your feature request related to a problem? Please describe.

feature added in DOSBOX-X
https://github.com/joncampbell123/dosbox-x/issues/2835

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by weirddan455** [comment]
It would be nice to confirm what games (f any) actually have problems on Staging due to this.  I'm aware that some games will throw a warning during install when they try to detect the CDROM speed (ex. Wing Commander 3) but whenever I've encountered this, the game installs and plays fine regardless.

There's a lot of features DOSBox-X has that we have no plans to implement.  We have no hard drive speed limiter either that I'm aware of.

At least from my perspective, I would need to see a concrete problem (more than just an installer warning that can be bypassed) before I spend time working on it.  I suppose this ticket can stay up as a feature request if someone else wants to work on it but you still might want to sell it more with a real problem that needs to be solved.

**Comment by Grounded0** [comment]
Yeah i want a list of apps and games impacted directly in a showstopper manner and not as an annoyance like CD speed check throwing a warning on install.

**Comment by johnnovak** [comment]
@xga-cga Please build up a case for this. We don't just implement features and port over stuff if it's not proven to solve a concrete problem.

We need a list of games that work with this X feature, but don't in Staging.

For each game, please specify the value of the X CD-ROM speed setting you've tested with.

**Comment by Burrito78** [comment]
It would be no problem for us to just soak up a lot of "nice" DOSBox-X features but:

It means it takes time/energy to:

1. Integrate it into Staging with our coding standards and practices.
2. Do bug and regression testing after integration.
3. Risk new bugs as a result of integration that aren't found at first.
4. Some Staging contributor has to "own" the feature in the future to keep it working and update the code when necessary, when he leaves, the feature is in there to rot when nobody picks it up to care for it - which most often doesn't happen, if its nothing fundamentally important.

For these reasons, changes to the codebase must have a proper reason, and that reason has to be a games behaving badly or worse than other DOSBox forks.

**Comment by johnnovak** [comment]
Exactly @Burrito78. We won't just start indiscriminately start shovelling over features from otherprojects, lol 😄 That's _not_ how you do software 😆

**Comment by MasterO2** [comment]
> Exactly @Burrito78. We won't just start indiscriminately shoveling over features from other projects, lol 😄 That's _not_ how you do software 😆

Judging by xga-cga's **lack of a response** so far, there must not be very many games at all where setting a specific CD-ROM speed is needed to run them properly.

**Comment by Grounded0** [comment]
They mostly had minimum speed requirements that you had enough data coming per second to display a Smacker video and such:

https://en.wikipedia.org/wiki/Smacker_video

**Comment by johnnovak** [comment]
> They mostly had minimum speed requirements that you had enough data coming per second to display a Smacker video and such:
> 
> https://en.wikipedia.org/wiki/Smacker_video

And some setup utils ask you whether you have a double, triple, etc. speed drive.

**Comment by weirddan455** [comment]
Closing this due to no response.  I don't see anyone jumping to implement this without a concrete use-case.

**Comment by johnnovak** [comment]
> Closing this due to no response. I don't see anyone jumping to implement this without a concrete use-case.

Good call. We want to keep the issue tracker clean and close low-value tickets.
