### ISSUE TITLE
Peachtree for windows v3 installer has trouble removing files

### ISSUE THREAD

**Issue by interloper98** [dosbox-staging/dosbox-staging#3781]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Different version than latest?

0.82-alpha (main)

### What Operating System are you using?

Linux ARM (Raspberry Pi)

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Since @Grounded0 mentioned using 1600x1200 in Windows for Colonization, I had to see how Peachtree looked in similar full glory :drooling_face: :laughing: 

Peachtree's installer reports that can't remove its own installed files: 

![peachree-strange-installer](https://github.com/dosbox-staging/dosbox-staging/assets/165201780/494f122b-721e-4886-b31e-18d20de013bc)

This was the first install too - these aren't existing/old files.

It looks like Peachtree is write protecting these files on the host. I manually switched this problematic `D2HLINK.DLL` back to read+write, which was enough to let me proceed with the install.

Unfortunately this pattern repeats though with other files (copies them to C: in write-protected form then tries to remove them and fails).

@weirddan455 , maybe this is similar to the seek issue (or something like that?)

### Steps to reproduce the behaviour

1. Fresh install of Windows 3.11 for Workgroups

2. Download and extract [peach_v3.zip](https://github.com/user-attachments/files/15907628/peach_v3.zip). 

3. Add imgmount for the install floppies to your `[autoexec]`:

    ```ini
    [autoexec]
    imgmount a peach_v3/disk*.img -t floppy
    ...
    (proceed to start Windows 3.11)
    ```

4. From inside Windows, launch `A:\SETUP.EXE` and proceed with a default/full install. It should fail quickly.

### Download URL of affected game or software

https://winworldpc.com/download/c2b2c592-c389-6265-5611-c3a4c2b1c388

### Your configuration

```ini
[dosbox]
memsize = 32

[cpu]
cycles  = 60000

[autoexec]
imgmount a peach_v3/disk*.img -t floppy
mount c .
c:
PATH C:\WINDOWS;Z:\
SET TEMP=C:\WINDOWS\TEMP
WIN
```

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by MasterO2** [comment]
@interloper98, have you tried setting `allow_write_protected_files = false` in `dosbox-staging.conf`?

**Comment by interloper98** [comment]
I'll try; thanks for the tip @MasterO2.

**Comment by interloper98** [comment]
That's working, thanks @MasterO2!

It looks like the installer is still creating these write-protected, but that setting is some how pacifying the installer:

```
FILESYSTEM: protected from modification: D2HLINK.DLL
FILESYSTEM: protected from modification: SMOLB.DLL
FILESYSTEM: protected from modification: IAUTILS.DLL
FILESYSTEM: protected from modification: PRESENT.EXE

Drive A: disk 2 of 5 now active
FILESYSTEM: protected from modification: PEACHW2.DLL
FILESYSTEM: protected from modification: PEACHAPP.DLL
FILESYSTEM: protected from modification: SMOBUTTN.DLL
FILESYSTEM: protected from modification: LNGPRSNT.DLL
FILESYSTEM: protected from modification: WYSEDIT.DLL
FILESYSTEM: protected from modification: EXTCALL.DLL
FILESYSTEM: protected from modification: SMOGRAPH.DLL
FILESYSTEM: protected from modification: SMOTEXT.DLL
FILESYSTEM: protected from modification: AIMTECH.DLL
FILESYSTEM: protected from modification: ACCUSOFT.DLL

Drive A: disk 3 of 5 now active
FILESYSTEM: protected from modification: WBTRVRES.DLL
FILESYSTEM: protected from modification: WBT32RES.DLL
FILESYSTEM: protected from modification: WBTRCALL.DLL
FILESYSTEM: protected from modification: WBTRLOCL.DLL
FILESYSTEM: protected from modification: PEACHFRM.DLL
FILESYSTEM: protected from modification: PCHWBMP.DLL
FILESYSTEM: protected from modification: SAMPLES.DLL
FILESYSTEM: protected from modification: QCBASED.DLL
FILESYSTEM: protected from modification: WBTR32.EXE
FILESYSTEM: protected from modification: PEACHW.EXE
```

**Comment by MasterO2** [comment]
> That's working, thanks @MasterO2!
> 
> It looks like the installer is still creating these write-protected on the host and then trying to delete them, but that setting is some how pacifying the installer.
> 
> I'm seeing these reported in Staging's console log now:
> 
> ```
> FILESYSTEM: protected from modification: D2HLINK.DLL
> FILESYSTEM: protected from modification: SMOLB.DLL
> FILESYSTEM: protected from modification: IAUTILS.DLL
> FILESYSTEM: protected from modification: PRESENT.EXE
> 
> Drive A: disk 2 of 5 now active
> FILESYSTEM: protected from modification: PEACHW2.DLL
> FILESYSTEM: protected from modification: PEACHAPP.DLL
> FILESYSTEM: protected from modification: SMOBUTTN.DLL
> FILESYSTEM: protected from modification: LNGPRSNT.DLL
> FILESYSTEM: protected from modification: WYSEDIT.DLL
> FILESYSTEM: protected from modification: EXTCALL.DLL
> FILESYSTEM: protected from modification: SMOGRAPH.DLL
> FILESYSTEM: protected from modification: SMOTEXT.DLL
> FILESYSTEM: protected from modification: AIMTECH.DLL
> FILESYSTEM: protected from modification: ACCUSOFT.DLL
> 
> Drive A: disk 3 of 5 now active
> FILESYSTEM: protected from modification: WBTRVRES.DLL
> FILESYSTEM: protected from modification: WBT32RES.DLL
> FILESYSTEM: protected from modification: WBTRCALL.DLL
> FILESYSTEM: protected from modification: WBTRLOCL.DLL
> FILESYSTEM: protected from modification: PEACHFRM.DLL
> FILESYSTEM: protected from modification: PCHWBMP.DLL
> FILESYSTEM: protected from modification: SAMPLES.DLL
> FILESYSTEM: protected from modification: QCBASED.DLL
> FILESYSTEM: protected from modification: WBTR32.EXE
> FILESYSTEM: protected from modification: PEACHW.EXE
> ```

@interloper98, are the files on the `A:` drive **read-only**?  That's something to check.

You can run `ATTRIB -r` on them to fix that.

**Comment by interloper98** [comment]
All the files on the floppy images have the `A` attribute (but are in compressed form):

![floppy-attrib](https://github.com/dosbox-staging/dosbox-staging/assets/165201780/43f3b63c-bf25-43ab-8549-49514c2aca8c)

Looks like the installer extracts these to C: as totally new/unique files - as opposed to just copying them.

**Comment by weirddan455** [comment]
I've run into a similar issue before in #3695

I think the `allow_write_protected_files` setting is somewhat flawed.  Even the name is mis-leading as to what it actually does.  The internal variable name for that setting is `always_open_ro_files` which is more accurate.

What it does is if a program attempts to open a read-only file with write permissions, instead of failing to open, it will fall back to opening with read-only permissions and succeed.  The intent seems to be to allow certain games that open with read/write permissions but don't actually write to the file to work if the user modifies the host files to be read-only.

The problem is that some programs _expect_ this operation to fail.  In the case of these installers, it's saying "Oh I have write access to this file, I'm going to try to delete it now".  Then the delete fails because we lied to about it about what permissions it actually has.

This setting was added as part of this PR #2288 and it even says in the description "while it's more user-friendly it's also inaccurate to real DOS so it should be possible to turn it off"

**Comment by Grounded0** [comment]
We should always emulate default DOS behaviour as a default setting.

**Comment by interloper98** [comment]
Closing; thanks guys. Blew away the old config on my RetroPie box and all-defaults are running fine.

(I also double-checked by commenting out the two `always_open_ro_files` if-blocks in the local drive code, just to be sure - and we're all good).
