### ISSUE TITLE
Retribution (1994)(Gremlin) INSTALL.EXE Division Error

### ISSUE THREAD

**Issue by codengine** [dosbox-staging/dosbox-staging#3792]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Different version than latest?

0.81.1

### What Operating System are you using?

Windows 10

### Relevant hardware info

Ryzen 5950, 4070 Ti

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

When I execute INSTALL.EXE from the mounted ISO, it will crash with a "division error".
I tried messing around with core type, number of cycles, LOADFIX with no luck. There is however a way to make it run in DosBox-X:

- Core Type normal
- Cycles 6075 (386DX 33 MHz)
- Limit Floppy Transfer Speed
- Limit HDD Transfer Speed

The DosBox-X Debugger also shows an "Illegal Unhandled Interrupt Called 6".

As a side-bug, whenever INSTALL.EXE is called twice, DosBox will lockup completely.
As a bonus, the issue does not occur when INSTALL.EXE is run from a mounted folder.

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Mount the ISO
2. Run INSTALL.EXE

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by kklobe** [comment]
I was able to get past this by skipping the CD speed test with `install /c`

**Comment by Grounded0** [comment]
Closing soon as it has been resolved.
