### ISSUE TITLE
moralhardcandy by Blasphemy crashes with `cputype = pentium_mmx`

### ISSUE THREAD

**Issue by johnnovak** [dosbox-staging/dosbox-staging#3793]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Different version than latest?

0.82.0-alpha

### What Operating System are you using?

macOS (Apple Silicon)

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

**moralhardcandy by Blasphemy** hard crashes Staging after the intro screen with `cputype = pentium_mmx`. There are lots of errors in the logs (see below).

`auto` and `pentium_slow` work fine.

Only tested on macOS, but it seems there's a bug in our MMX emulation.

With `core = normal`, there is no hard crash, but the demo exits after the intro with this error:

<img width="921" alt="image" src="https://github.com/dosbox-staging/dosbox-staging/assets/698770/c8972dd7-7091-469b-936b-2ccd2c1e338d">

### Steps to reproduce the behaviour.

Use the repro pack and start with `--noprimaryconf`.

### Download URL of affected game or software

https://www.pouet.net/prod.php?which=11

Recommend using the repro pack
[moralhardcandy.zip](https://github.com/user-attachments/files/16005504/moralhardcandy.zip)

### Your configuration

```ini
[dosbox]
memsize = 31

[cpu]
cputype = pentium_mmx
cpu_cycles = 100000
cpu_cycles_protected = auto
cpu_throttle = off

[gus]
gus = on

[autoexec]
c:
cd moralhc
candyd
```

### Provide a Log

There are shittons of "illegal read/write" log messages before the crash.

```text
2024-06-24 19:35:27.973 | Illegal write to fff96829, CS:IP      868:   75330
2024-06-24 19:35:27.973 | Illegal write to fff9682a, CS:IP      868:   75330
2024-06-24 19:35:27.973 | Illegal write to fff9682b, CS:IP      868:   75330
2024-06-24 19:35:27.973 | Illegal write to fff9682c, CS:IP      868:   75330
2024-06-24 19:35:27.973 | Illegal write to fff9682d, CS:IP      868:   75330
2024-06-24 19:35:27.973 | Illegal write to fff9682e, CS:IP      868:   75330
2024-06-24 19:35:27.973 | Illegal write to fff9682f, CS:IP      868:   75330
2024-06-24 19:35:27.973 | Illegal read from fff96830, CS:IP      868:   75330
2024-06-24 19:35:27.973 | Illegal read from fff96831, CS:IP      868:   75330
2024-06-24 19:35:27.973 | Illegal read from fff96832, CS:IP      868:   75330
2024-06-24 19:35:27.973 | Illegal read from fff96833, CS:IP      868:   75330
2024-06-24 19:35:27.973 | Illegal write to fff96830, CS:IP      868:   75330
2024-06-24 19:35:27.973 | Illegal write to fff96831, CS:IP      868:   75330
2024-06-24 19:35:27.973 | Illegal write to fff96832, CS:IP      868:   75330
2024-06-24 19:35:27.973 | Illegal write to fff96833, CS:IP      868:   75330
Stack trace:
20         0x186c310e0 start + 2360
19         0x1043521bc sdl_main(int, char**) + 5036
18         0x1044a2f48 SHELL_Init() + 3752
17         0x1044a1208 DOS_Shell::Run() + 1184
16         0x1044a0d3c DOS_Shell::RunBatchFile() + 356
15         0x1044a0884 DOS_Shell::ParseLine(char*) + 2252
14         0x1044aa9b0 DOS_Shell::DoCommand(char*) + 292
13         0x1044b8300 DOS_Shell::ExecuteProgram(std::basic_string_view<char, std::char_traits<char>>, std::basic_string_view<char, std::char_traits<char>>) + 2460
12         0x1041c9fd0 CALLBACK_RunRealInt(unsigned char) + 76
11         0x10402cb80 DOSBOX_RunMachine() + 28
10         0x10402c6a4 Normal_Loop() + 84
9          0x104055f90 PROGRAMS_Handler() + 108
8          0x1044a0fbc DOS_Shell::Run() + 596
7          0x1044a0884 DOS_Shell::ParseLine(char*) + 2252
6          0x1044aa9b0 DOS_Shell::DoCommand(char*) + 292
5          0x1044b8300 DOS_Shell::ExecuteProgram(std::basic_string_view<char, std::char_traits<char>>, std::basic_string_view<char, std::char_traits<char>>) + 2460
4          0x1041c9fd0 CALLBACK_RunRealInt(unsigned char) + 76
3          0x10402cb80 DOSBOX_RunMachine() + 28
2          0x10402c680 Normal_Loop() + 48
1          0x10440ce70 PIC_RunQueue() + 252
0          0x10440ca6c PIC_runIRQs() + 592
2024-06-24 19:35:27.983 | ABORT: Illegal descriptor type 0x1e for int 9
```

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by FeralChild64** [comment]
Tested on my AMD64 machine (with my configuration) - it terminates during the startup with:

`PNG error: IHDR: CRC error`

Reverting to https://github.com/dosbox-staging/dosbox-staging/commit/08df9a698fd554f29026d45e2319c3bc181c1922 fixes the problem for me - like with my GTA and Windows 3.11 / Windows 95 issues, https://github.com/dosbox-staging/dosbox-staging/issues/3794

**Comment by interloper98** [comment]
I think there are two issues.

 - New regression caused by my division flag PR; fix is being prepped. Thanks for testing the fix @FeralChild64.

 - Issue when using `cputype = pentium_mmx`, which I think @johnnovak hit.
   @FeralChild64 , try building commit `git checkout 9a6ef4e3c~1`. This pre-dates the division flag PR. On my side, it crashes when the demo tries to progress past the first three gray circles.

**Comment by FeralChild64** [comment]
It went from start to end for me, without crashing, on `9a6ef4e3c~1`:

```ini
[dosbox]
machine                     = svga_s3
memsize                     = 31
mcb_fault_strategy          = allow
vmemsize                    = 4
vmem_delay                  = off
dos_rate                    = default
vesa_modes                  = compatible
vga_8dot_font               = true
vga_render_per_scanline     = true
speed_mods                  = true

[cpu]
core      = dynamic
cputype   = pentium_mmx
cycles    = max limit 100000

[sblaster]
sbtype              = sb16
sbbase              = 220
irq                 = 7
dma                 = 1
hdma                = 5
sbmixer             = true
sbwarmup            = 100
cms                 = auto
oplmode             = auto

[gus]
gus        = true
gusbase    = 240
gusirq     = 5
gusdma     = 3
ultradir   = C:\ULTRASND
```

**Comment by johnnovak** [comment]
@FeralChild64 Still crashes for me with your config too on M1 Mac.

I've extended the top description, with `core = normal` it doesn't hard-crash the emulator, but it exits to DOS after the intro with a register dump. So something might be wrong with the MMX emulation in general, so not just the ARM dynarec.

I could test it on my real MMX box at some point too if that helps.

**Comment by Grounded0** [comment]
I renamed FPU emulation to CPU emulation since we're bound to have more of these since we added MMX support.

**Comment by johnnovak** [comment]
> I renamed FPU emulation to CPU emulation since we're bound to have more of these as we added MMX support. FPU emulation is just way too narrow for a label with little use.
> 
> Added label on the basis of suspicion that this is related to our MMX support.

Sounds ok, good call.

**Comment by kklobe** [comment]
crashes with DOSBox-X on my M3 as well, FWIW.

**Comment by Grounded0** [comment]
https://github.com/dosbox-staging/dosbox-staging/labels/CPU%20emulation is now properly populated both in issue tracker and pull requests.

**Comment by Grounded0** [comment]
Naming it CPU/FPU emulation seems kinda clunky when the FPU has been part of the CPU die since 80486 but whatever. 😁

**Comment by johnnovak** [comment]
> Naming it [ CPU/FPU emulation](https://github.com/dosbox-staging/dosbox-staging/labels/CPU%2FFPU%20emulation) Issues related to CPU or FPU emulation seems kinda clunky when the FPU has been part of the CPU die since 80486 but whatever. 😁

That's quite irrelevant from our point of view. They are two different emulation areas.

**Comment by johnnovak** [comment]
@joncampbell123 You might be interested in this MMX fix.
