### ISSUE TITLE
Grand Theft Auto does not recognize the CD + other breakages

### ISSUE THREAD

**Issue by FeralChild64** [dosbox-staging/dosbox-staging#3794]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### What Operating System are you using?

Linux x86_64

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

The game is no longer playable due to CD not being recognized.

![GTA](https://github.com/dosbox-staging/dosbox-staging/assets/48332137/f063e8d2-cfd1-470e-acd2-85377ecd0083)

Last good commit: 08df9a698fd554f29026d45e2319c3bc181c1922
First bad commit f46b5a731f94fcf8e5f9f3159f21871925cb0b33

Paging @interloper98

### Steps to reproduce the behaviour.

1. Mount the GTA CD image
2. Run the game with `GTA24.EXE -nounivbe` command
3. The game won't recognize the CD

### Your configuration

```ini
[cpu]
core    = dynamic
cputype = pentium_mmx
```

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by FeralChild64** [comment]
It seems not only GTA is affected. I have a beefy Windows 3.11 for Workgroups installation, with a lot of software installed, patches from Microsoft, addons, drivers, etc. - and after the mentioned commit it does not start any more:

![Win311](https://github.com/dosbox-staging/dosbox-staging/assets/48332137/9f722dd9-f4c1-48a3-9de9-1c595e318e4e)

**Comment by FeralChild64** [comment]
Another breakage - I have a Windows 95 installation (first version - not OSR2), with just the IntelliPoint 3.0 software installed (I'm using it for testing PS/2 mouse and Intel 8042 hardware emulation changes) - it does not boot anymore (closing the window does not help - it never starts the Explorer shell):

![Win95-1](https://github.com/dosbox-staging/dosbox-staging/assets/48332137/939b25c2-1609-4c52-a3e6-32273d8457ab)
![Win95-2](https://github.com/dosbox-staging/dosbox-staging/assets/48332137/5f56754a-1039-429b-9b16-9183741e53d2)

**Comment by interloper98** [comment]
@FeralChild64 ; wow - I didn't see any f this testing. Glad you caught and isolated it. 

Does setting "lflags.type = t_UNKNOWN" (instead of t_DIV) fix it?

**Comment by FeralChild64** [comment]
Yes - it fixes all the regressions I know about.

**Comment by interloper98** [comment]
Thank you for the quick tests, @FeralChild64!
