### ISSUE TITLE
Sound issues when using IMGMOUNT on Windows, but Linux is fine

### ISSUE THREAD

**Issue by 8192K** [dosbox-staging/dosbox-staging#3796]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Different version than latest?

0.81.1 (latest)

### What Operating System are you using?

Windows 11

### If Other OS, please describe

Manjaro

### Relevant hardware info

AMD Threadripper 3970 virtualized, AMD Radeon Pro WX4100

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

I created a bin/cue image from an old mixed mode DOS game (Schleichfahrt/Archimedian Dynasty). I call IMGMOUNT D C:\games\dos\SF.CUE -t cdrom to mount the image in Dosbox Staging. In Windows 11, I get crackling sound for most of the sound output (some seems OK). It is too crackling as to still be enjoyable.
When I mount the same image in linux (latest Manjaro stable, same version) using IMGMOUNT D /opt/games/dos/images/SF.CUE -t cdrom the sound is just fine.

On Windows I tried playing with several options in the config, but none of them had an effect. The only effect I noticed was when going down to around 10-15% of max cycles, the crackling got worse.

When running the game directly from the CD, mounting the CD drive in Dosbox Staging, the sound is fine on Windows, too.

So I assume this is a bug with IMGMOUNT on Windows.

I run both Windows and Linux as a VM on a Proxmox system. But as all components are used via PCI passthrough, this should not be an issue. Also, I used sound via Bluetooth as well as through the monitor loudspeakers. No change.

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Create a bin/cue image from a DOS game CD, possibly being mixed-mode
2. Install and run in Dosbox Staging on Windows, get crackling sound
3. Do the same on Linux, no crackling sound

### Your configuration

```ini
The default, unchanged.
```

### Provide a Log

```text
No error in the logs
```

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by johnnovak** [comment]
Try using fixed cycles, e.g. `cycles = 60000`. Any change?

**Comment by 8192K** [comment]
I tried that, high and low values. No change.

**Comment by johnnovak** [comment]
I guess my next question is, is this systemic? Can you try a bunch of other games and report back how the sound behaves in them?

Please also post your logs here as asked. Post it as a https://gist.github.com/ and just put the link in the ticket.

**Comment by 8192K** [comment]
I tried Privateer 2 and Star Trek 25th Anniversary (all other old games I have require Windows). I created bin/cue images for those games as with Schleichfahrt. Star Trek 25th has an audio track while Privateer 2 doesn't.

Star Trek is speech only, I could not find any issues there.
However, Privateer 2 does not crackle per se but as soon as the sound gets louder (opening video), the sound is definitely not as smooth as it is on Linux and you could call those artifacts "crackling".
No issues at all on Linux.

So it seems there is an issue with IMGMOUNT on Windows and it does not relate to the CDs being mixed mode.

**Comment by johnnovak** [comment]
> However, Privateer 2 does not crackle per se but as soon as the sound gets louder (opening video), the sound is definitely not as smooth as it is on Linux and you could call those artifacts "crackling".

Can you create a recording please and upload it? We still can't inspect your log file...

**Comment by 8192K** [comment]
The issue exists with iso files, too.
I might not have listened carefully enough the first time, but Privateer 2 definitely has severe sound clarity issues on Windows.

**Comment by 8192K** [comment]
> > However, Privateer 2 does not crackle per se but as soon as the sound gets louder (opening video), the sound is definitely not as smooth as it is on Linux and you could call those artifacts "crackling".
> 
> Can you create a recording please and upload it? We still can't inspect your log file...

Please tell me how to properly find the log file on Windows and Linux. 
I can create that recording.

**Comment by johnnovak** [comment]
> > > However, Privateer 2 does not crackle per se but as soon as the sound gets louder (opening video), the sound is definitely not as smooth as it is on Linux and you could call those artifacts "crackling".
> > 
> > 
> > Can you create a recording please and upload it? We still can't inspect your log file...
> 
> Please tell me how to properly find the log file on Windows and Linux. I can create that recording.

Sorry, probably I shouldn't have mentioned a "log file" as we don't have one... it's just printed to the terminal.

On Linux, the logs are printed to the terminal you started Staging from.

On Windows, the a separate command Windows opens by default that contains the logs.

**Comment by Grounded0** [comment]
> I run both Windows and Linux as a VM on a Proxmox system. But as all components are used via PCI passthrough, this should not be an issue.

I can see plenty of potential issues with this. 😁

**Comment by Grounded0** [comment]
Since it's the same code running on Linux and Windows and only Windows acts badly i'm fairly certain it has something to do with the VM setup you're running these on.

Linux on Linux has less complexity while Windows on Linux has to do a lot of magic tricks to interface with Windows HAL. This could cause the issues you're having and it's not our concern.

**Comment by 8192K** [comment]
Why is the code the same? You surely will have to use the sound capabilities of the operating system in different ways. Also mounting images could be very different.

I'm a software developer myself, please don't shoot this down too early.

**Comment by Grounded0** [comment]
Try booting your system into Windows running on bare metal and if you can replicate this issue there then that's a problem.

**Comment by 8192K** [comment]
Yeah, that would be a logical step. But PCI passthrough is just like bare metal. Proxmox doesn't touch the hardware that's passed through. 
I'll upload the logs and the recordings later.

**Comment by Grounded0** [comment]
The hypervisor is still running there and we want that out to eliminate cascading complexity.

**Comment by weirddan455** [comment]
I can think of a couple things to try.  Look in the `[mixer]` section of the .conf file.  Try increasing `blocksize` and `prebuffer` values.  If that doesn't work, try setting `negotiate = true` (this is off by default on Windows, on by default on Linux).  From my testing, this over-rides `blocksize` with a small value but maybe it works better for you?  We were just reviewing this setting the other day and need more data as to what works better for users.

You can also try a different SDL audio driver.  It uses WASAPI on Windows by default.  You can do this by setting an environment variable.  Ex:  `SDL_AUDIODRIVER=directsound`.  You should see a log message in Dosbox to confirm this works.  It'll look like `SDL: version 2.26.5 initialised (wayland video and pulseaudio audio)`

I would expect if it were a problem with the mixer or audio driver that you would also experience this with games using other types of sound.  Have you had this problems with games using OPL (Adlib/Soundblaster) for music?

Lastly, I am planning to make some performance improvements to the mixer in the future.  Not sure how long this is going to take me yet but ideally it would let CDROM and MIDI be stutter free even if the CPU emulation is lagging behind.  Right now they're tied to this once per 1ms event in the CPU loop while on real hardware they're "fire and forget" with little synchronization needed.  It's just going to take a bit of re-architecting to get as much as I can off the main thread loop.

**Comment by johnnovak** [comment]
@8192K Oh, I missed that you are running Windows in a VM. Like @Grounded0 said, there is a vast number of things that can go wrong there. In short, we only support OSes running on bare metal. @weirddan455's suggestions are good general tips, but closing this as we don't provide support for any issues stemming from running Staging in a VM-hosted OS.

Feel free to let us know if you ever figure this out, but I recommend running Windows on bare metal. I don't expect any VM solution to fare well with games, emulators, or anything to do with realtime audio; they're meant for "servery" stuff, not entertainment.
