### ISSUE TITLE
Terminator: Skynet crashes

### ISSUE THREAD

**Issue by eehikki** [dosbox-staging/dosbox-staging#3798]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Different version than latest?

origin/main

### What Operating System are you using?

Linux x86_64

### If Other OS, please describe

Debian 12

### Relevant hardware info

Intel i5-7500 CPU, integrated GPU

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

DOS crashes while running *Terminator: Skynet*.  I've tried to compile dosbox-staging with dynx86 and dynrec. The result was the same. The crash can occur at every point during the game play but leaving the Cyberdyne building after accomplishing  the mission goals crashes the game with 100% probability (third mission). I learned thet Skynet v1.0 crashes when the player tries to leave a building, but I've already patched the game with the official patch known to fix the issue.  Leaving other buildings (or leaving the Cyberdyne building without accomplishing the goals) doesn't seem to provoke an inevitable crash.  

### Steps to reproduce the behaviour.

Explain how to reproduce
1. 
2.
3.

### Your configuration

```ini
core = dynamic
cputype = pentium
mem = 16
```

### Provide a Log

```text
2024-06-28 13:50:05.422 | SB16: Resetting DSP
2024-06-28 14:02:17.242 | Illegal read from 1007ddc1, CS:IP      268:1007ddc1
2024-06-28 14:02:17.243 | DYNREC:Can't run code in this page
2024-06-28 14:02:17.243 | Illegal read from 1007ddc1, CS:IP      268:1007ddc1
2024-06-28 14:02:17.243 | Illegal read from 1007ddc2, CS:IP      268:1007ddc1
2024-06-28 14:02:17.243 | Illegal read from 1007ddbf, CS:IP       70:    53db
2024-06-28 14:02:17.243 | Illegal read from 1007ddc0, CS:IP       70:    53db
```

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by johnnovak** [comment]
@eehikki Please don't assume this is a DOSBox problem. Many games are incredibly buggy and crash left, right, centre on real hardware too and/or on different hardware setups.

I've spent 2 minutes looking into it, but itt seems like the game is just a buggy mess. I'm 90% sure these crashes are game issues.

https://www.pcgamingwiki.com/wiki/The_Terminator:_SkyNET
https://www.vogons.org/viewtopic.php?t=56878

As always, test in other DOSBox variants, PCem, etc. before drawing the conclusion this is a Staging bug.

**Comment by eehikki** [comment]
> @eehikki Please don't assume this is a DOSBox problem. Many games are incredibly buggy and crash left, right, centre on real hardware too and/or on different hardware setups.
> 
> I've spent 2 minutes looking into it, and it seems like the game is just a buggy mess. I'm 90% sure these crashes are game issues.
> 
> https://www.pcgamingwiki.com/wiki/The_Terminator:_SkyNET https://www.vogons.org/viewtopic.php?t=56878
> 
> You can find more with a bit of searching. Try the patches recommended in these posts/wikis.
> 
> As always, test in other DOSBox variants, PCem, etc. before drawing the conclusion this is a Staging bug.
> 
> Also set fixed cycles values please. The default `cycles = max` is usually a recipe for disaster...

I've already applied patch 1.01. 
Currently, the setting is set to
```
cycles = 50000
```

**Comment by johnnovak** [comment]
Yeah, patch 1.01 seems not to be enough.

Read this thread:
https://www.vogons.org/viewtopic.php?t=56878

Try the unofficial 2017 patch.

**Comment by johnnovak** [comment]
You can also try `core = normal` and see how that goes, but I doubt this is a dynarec issue.

**Comment by MasterO2** [comment]
@eehikki https://community.pcgamingwiki.com/files/file/931-skynet-unofficial-patch-2017/

**Comment by Grounded0** [comment]
I've successfully played through this game. Use the unofficial patch and even then save often.

Have you heard about the legend of Bethesda and Todd Howard?

Closing soon.

**Comment by eehikki** [comment]
Yes, applying the unofficial patch fixes the problem. Sorry for wasting your time

**Comment by Grounded0** [comment]
@eehikki 

Since you're a Debian user check this and make some money:

- #3677
