### ISSUE TITLE
Does Rise of the Triad (1994) work in dosbox-staging?

### ISSUE THREAD

**Issue by DOOMMARINE117** [dosbox-staging/dosbox-staging#380]
i know there is a 2013 versin, but on teh original version does taht one work very well? 

doe sit incldue a decie or install file to install teh whole game? 

i know the ad on packs have those. 

But, i was wondering how rise of the triad works on dosbox?

**Comment by kcgen** [comment]
Yes, the original 1994 DOS release of Rise of the Triad works very well under dosbox.

https://www.mobygames.com/game/dos/rise-of-the-triad-dark-war

You would use a similar Windows 10 shortcut

**Comment by dreamer** [comment]
Well, yes it works… in general, we don't know about a single DOS game that does *not* work in dosbox-staging (except games for PC98 platform).

Sometimes it requires tweaking, but as far as DOS games are concerned, the answer will be: it works - if it does not work *for you*, then we would like to know about it (what version of the game is being tested, what OS/version/CPU you're using, what dosbox-staging options you tried, etc).

Closed the question, as it's not really actionable item for us.
