### ISSUE TITLE
Feature Request: Win64/Win x86_64 support

### ISSUE THREAD

**Issue by Expack3** [dosbox-staging/dosbox-staging#381]
Given the improvements of the new 64-bit dynarec, not to mention providing a bit of future-proofing, it would be great to see 64-bit support come to Windows.

**Comment by dreamer** [comment]
The support is already there and dosbox-staging can be built on 64-bit on Windows - but unfortunately only when using msys2.

The missing parts are:

- MSVC-specific file `src/platform/visualc/config.h` needs to be reviewed if no 32-bit specific cruft is left behind (I believe I already removed all of it, but someone needs to double-check)
- adding x64 build definitions to Visual Studio solution; right now we have Release and Debug; those will need to be renamed "Release (x86)", "Debug (x64)", and two new added: "Release (x64)", "Debug (x64)".
- these two jobs should be added to CI (which means - two of existing msys2 jobs will need to be removed - we are at our capacity for available job slots) - they will also need their own vcpkg dependency lists to install 64-bit packages, as that's how vcpkg works
- 64-bit release job needs to be tested to make sure it still works; probably some small adjustments to the packaging process will be needed
- documentation about msvc build need to be updated (README.md)

All of these tasks are *easy*. Someone just needs to spend time working on it and testing.

**Comment by dreamer** [comment]
@Expack3 64-bit release builds (#478) just got merged to master (I will backport it to 0.75.x release branch in few minutes, we'll have 64-bit Windows builds for 0.75.1).

Please test - if something does not work correctly feel free to reopen or create a new issue :)
