### ISSUE TITLE
Display Stuck at 24Hz in Fullscreen

### ISSUE THREAD

**Issue by theriverlethe** [dosbox-staging/dosbox-staging#3811]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### What Operating System are you using?

Windows 11

### Relevant hardware info

AMD 5800X CPU, 7900XT GPU, LG C2OLED with 120Hz VRR

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Whenever I switch dosbox-staging to fullscreen, my display switches to fixed-rate 24Hz. After exiting dosbox-staging, the display's refresh rate does not return to its previous value. VRR works fine in everything else. 

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Launch a game in Dosbox-staging
2. Switch to fullscreen mode with alt-enter

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by theriverlethe** [comment]
This was either an AMD driver bug resolved with an update or simply cleared itself when I restarted my computer.

**Comment by johnnovak** [comment]
> This was either an AMD driver bug resolved with an update or simply cleared itself when I restarted my computer.

Just a tip: make sure to never enforce vsync at the driver control panel level globally (or for Staging specifically); that can result in some really weird behaviour.
