### ISSUE TITLE
X-Wing B-Wing Add-On installation corrupts files

### ISSUE THREAD

**Issue by Burrito78** [dosbox-staging/dosbox-staging#3829]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### What Operating System are you using?

macOS (Apple Silicon)

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

When using latest release and DEV versions of Staging, installing the B-Wing Add-On to a fresh X-Wing installation will result in corrupt game files.

The following DOSBox versions are affected (X) or not affected (OK).

DOSBox Staging 0.78.1: OK
DOSBox Staging 0.79.1: OK
DOSBox Staging 0.80.1: OK
DOSBox Staging 0.81.1: X
DOSBox Staging Main: X

DOSBox-X 2024.03.01: OK
DOSBox 0.74 SVN: OK

Floppy disk images from Digitoxins page on Archive.org:
https://archive.org/download/20220917_20220917_0541/Star%20Wars%20-%20X-Wing%20%281993%29%20%28v1.0%29%20%281.44M%29%20%5B%21%5D.zip
https://archive.org/download/20220917_20220917_0541/Star%20Wars%20-%20X-Wing%20-%20B-Wing%20%281993%29%20%28v1.2%29%20%281.44M%29%20%5B%21%5D.zip

### Steps to reproduce the behaviour.

Explain how to reproduce

First install X-Wing from above floppy images to default folder using default settings.
Then install B-Wing into the same folder (default) using default settings.

Launch X-Wing using "XWING".

Find copy protection codes here:
https://archive.org/details/x-wing-handbuch

Select the TOPACE4 pilot and enter the main hall, then go top right to the Tour Desk.

If your installation is corrupt, you will see this screen:
<img width="1056" alt="Bildschirmfoto 2024-07-19 um 18 30 22" src="https://github.com/user-attachments/assets/da8106e9-4708-4331-9dd8-021a3a4b6ad8">

If your installation is OK, you will see this screen:
<img width="752" alt="Bildschirmfoto 2024-07-19 um 11 46 02" src="https://github.com/user-attachments/assets/2e7ef65e-fb37-4488-9f67-62dea35a9b8b">

Installed files that are OK:
[XWING + BWING DOSBox 0.74.zip](https://github.com/user-attachments/files/16314621/XWING.%2B.BWING.DOSBox.0.74.zip)

Installed files that are corrupt:
[Uploading XWING + BWING Staging corrupt.zip…]()

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by interloper98** [comment]
After installing B Wing, during game startup it runs some shell commands to overwrite the old mission and title resource files. There's something wrong in how we're handling redirection in those shell calls. 
Fortunately it looks like there are plenty of unit tests for redirection, so I'll work on a fix, and add more unit tests that match real MS-DOS `command.com` handling.

**Comment by Burrito78** [comment]
Yes, funnily we discovered this issue through DREAMM beta testing in DREAMM and also in Staging!

Aaron Giles has explained what exactly happens here: https://discord.com/channels/1177933143404204052/1263189646633078824/1263986406037127299

I'll include a screenshot for reference here too:
<img width="896" alt="Bildschirmfoto 2024-07-20 um 22 24 30" src="https://github.com/user-attachments/assets/dd46b20c-a380-49b1-9963-0954a86cf07a">

So either 0.81.1/Main isn't runnign XWING.COM when running "XWING" but instead "XWING.EXE" is launched.
Or there are problems for XWING.COM to copy/patch the files correctly.

**Comment by interloper98** [comment]
Thanks for sharing that @Burrito78 !

Yes, it's the lack of robust white space handling that's causing problems with the redirection in the `copy A B >nul:` call made in `XWING.COM`.

**Comment by johnnovak** [comment]
Great work getting to the bottom of this @interloper98, and top-notch problem description and initial testing @Burrito78 🍻

**Comment by Burrito78** [comment]
@interloper98 Thanks for the PR which did much more than only fix this issue!

Very much appreciated!
