### ISSUE TITLE
Windows Installer still shows "Open with" context menu option

### ISSUE THREAD

**Issue by Grounded0** [dosbox-staging/dosbox-staging#3832]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### What Operating System are you using?

macOS (Intel)

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

I believe we've removed "Open with DOSBox Staging" context menu from Windows yet it still exists as an option in the installer:

<img width="609" alt="Screenshot 2024-07-22 at 8 59 59" src="https://github.com/user-attachments/assets/6bb90486-7728-41ca-a9f6-f6b638920772">

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Run DOSBox Staging Windows installer
2. Observe faulty installer screen

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by Grounded0** [comment]
Seems like this feature is still supported by us.

**Comment by johnnovak** [comment]
> Seems like this feature is still supported by us.

That's right.
