### ISSUE TITLE
Launching DOSBox with "-noconsole" parameter makes emulated joystick go crazy

### ISSUE THREAD

**Issue by Amaroq-Clearwater** [dosbox-staging/dosbox-staging#3834]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Different version than latest?

0.81.2

### What Operating System are you using?

Windows 10

### Relevant hardware info

XInput controller

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

I modified my Steam shortcut for launching Slipstream 5000 (via DOSBox) to use the -noconsole parameter. Doing so caused DOSBox to stop responding to inputs from my gamepad, and instead the emulated joystick just started doing whatever it wanted. Removing the "-noconsole" parameter fixed the issue.

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Connect XInput gamepad and Launch DOSBox without the "-noconsole" parameter for baseline results
2. Configure in-game controls to use joystick movement, and then calibrate the joystick.
3. Fly around for a bit to observe how the game is supposed to control.
4. Restart DOSBox **with** the "-noconsole" parameter and observe the madness

### Download URL of affected game or software

https://store.steampowered.com/app/306350/Slipstream_5000/

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by Amaroq-Clearwater** [comment]
(I would have included Zalgo text on step four to increase the drama, but that would've made the whole thing unreadable)

**Comment by Grounded0** [comment]
Anyone able to reproduce this?

**Comment by Grounded0** [comment]
Anyone able to reproduce this?

**Comment by Amaroq-Clearwater** [comment]
If I launch the game directly through DOSBox, it doesn't even launch. This is one of those prepackaged setups.
I haven't been able to test any other games.

**Comment by johnnovak** [comment]
Config please, logs please, etc. Please fill out the form properly, we ask for all those things for a reason.

**Comment by Amaroq-Clearwater** [comment]
I’ll attach the config file in a little bit, on my phone right now.
As for the logs... Where would they be located when the console is disabled?

**Comment by johnnovak** [comment]
> As for the logs... Where would they be located when the console is disabled?

You need to enable the console window and copy the logs from there.

Yeah, we should improve that, I know...

**Comment by Amaroq-Clearwater** [comment]
[SS5000.conf](https://github.com/user-attachments/files/16422162/SS5000.conf.txt)

And here is the console log from when the game is running normally:
[conslog.txt](https://github.com/user-attachments/files/16422213/conslog.txt)

If I launch the game with no console window (which is what seems to trigger the bug), well... can't give you the log from that currently :/

**Comment by weirddan455** [comment]
>  If I launch the game directly through DOSBox, it doesn't even launch. This is one of those prepackaged setups.
I haven't been able to test any other games.

You really need to remove Steam from the equation.  Steam has a whole system for gamepads/joysticks and we have no way of knowing if this is a DOSBox problem or a Steam problem.

Copy the game files to a separate folder outside of your Steam directory, launch DOSBox directly, mount the new folder as your DOSBox C drive, and run the DOS executable.

If it doesn't work, we need more information than "it doesn't launch".  What happens exactly?  Do you get an error message?

**Comment by MasterO2** [comment]
@Amaroq-Clearwater, following what weirddan455 said, download and run Dosbox-Staging, then follow the instructions as specified at https://www.dosbox-staging.org/getting-started/introduction/ to load your game accordingly.  Also make sure that you enabled joystick in `dosbox-staging.conf`.

Then everyone will have a much better picture regarding your issue.

**Comment by Amaroq-Clearwater** [comment]
In the past when I tried launching DOSBox (and DOSBox Staging) by itself, then mounting the directory that the game is in, and finally running SLIP.BAT… it gets as far as the publisher logo and intro FMV before aborting with a message about something not being supported. However, that is outside the scope of this bug report.

I’ll try again later with the standalone installed version of DOSBox Staging, as per the instructions.

**Comment by Grounded0** [comment]
Get a standalone install of DOSBox Staging and a standalone copy of the game. Then we've gained enough isolation from Steam.
