### ISSUE TITLE
Need user testing for USB CDROM Audio on Windows (potential regression)

### ISSUE THREAD

**Issue by weirddan455** [dosbox-staging/dosbox-staging#3836]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### What Operating System are you using?

Windows 10

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

codengine on Discord has reported a regression with CDROM audio on Windows.  I merged a change to the development branch which removes the SDL CDROM dependency and instead uses the Win32 API directly (specifically it uses `DeviceIoControl` calls to read audio data from CDROM and send it to the mixer).  Our latest release (v0.81.2) still uses SDL CDROM and does not contain this change.

I would like to fix this regression for the next release but I need some testing data as I don't have a USB CDROM on hand.  If you are willing, please comment with the following information.

1. Does CDROM audio play on a USB CDROM drive?
2. Is it a regression?  (Broken on a development build and working on v0.81.2)
3. What version of Windows are you using?
4. What game or application did you test with?

If you are a developer, you can do one better and add some log statements to the Win32 CDROM file and let me know what call is failing.  I would start with the `Open` function to see if the drive is able to be opened.  Relevant code is located here:  https://github.com/dosbox-staging/dosbox-staging/blob/main/src/dos/cdrom_win32.cpp

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Mount the CDROM by `mount d d:\ -t cdrom`.  The first letter being the DOS drive and the 2nd being the Windows drive.
2. Launch a game/application which uses CDROM audio.
3. Test on a development build and on v0.81.2.
4. Post your results here as a comment.

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by FeralChild64** [comment]
I definitely have the USB optical drive, just need to find it in my closet - I hope it still works. I should be able to do some testing during the weekend (not sure if I find the time today).

**Comment by FeralChild64** [comment]
OK, found time for some small test:

- **Windows 11**
- **Alone in The Dark 3** (pressed cover CD from the Polish magazine _CD-Action_, 30th November 1998)
- **DOS Navigator OSP 6.4.0** (main menu: Utilities -> CD Player)

-----

### DOSBox Staging 0.81.2

I have used the _-usecd_ parameter to point the emulator to proper drive.

- **Pioneer BDR-2209** (internal, SATA)
- **Pioneer BDR-XD05TB** (USB)
Totally unusable, both of them. Any access to CD audio causes the emulator to stop responding.
- ** Samsung SE-S084** (USB)
Kinda works, but still unusable. I can play audio tracks, but it takes a lot of time to switch tracks.
Game plays the music during the intro (but there is quite a long delay before it starts), but is unplayable. I have started a new game (there is no music at the beginning), entered the bridge, some bad guy blew it up (here the game should start playing the CD music) - and the emulator stops responding at this moment.

### DOSBox Staging alpha 61a08 build

- **Pioneer BDR-2209** (internal, SATA)
Works. The game seems to be functioning properly. CD player works, too.
- **Pioneer BDR-XD05TB** (USB)
- ** Samsung SE-S084** (USB)
CD audio does not play at all. DOS Navigator can't change audio tracks. Same results for both drives.

-----

Unfortunately, it's 10:40 PM here and I'm really sleepy now. My Windows compilation environment (not used since a long time...) got broken for some unknown reason:

> The build tools for ClangCL (Platform Toolset = 'ClangCL') cannot be found. To build using the ClangCL build tools, please install ClangCL build tools.  Alternatively, you may upgrade to the current Visual Studio tools by selecting the Project menu or right-click the solution, and then selecting "Retarget solution".

and I don't have energy to try to fix it today to add some logs. Good night :)

**Comment by weirddan455** [comment]
Thanks for the tests @FeralChild64

Maybe it's not so much of a regression then if 0.81.2 causes an emulator hang.  I still would like to get this issue fixed though.

>  The build tools for ClangCL (Platform Toolset = 'ClangCL') cannot be found. To build using the ClangCL build tools, please install ClangCL build tools. Alternatively, you may upgrade to the current Visual Studio tools by selecting the Project menu or right-click the solution, and then selecting "Retarget solution".

We've switched the Visual Studio build to use Clang.  Solution to this is to run the Visual Studio installer and select the Clang components.  It doesn't require a full re-install of Visual Studio.  You should be able to install additional components.

**Comment by FeralChild64** [comment]
Started _Alone in The Dark 3_, here are the logs (from my SATA and USB Pioneer drives) and the instrumented code:

[logs.zip](https://github.com/user-attachments/files/16393799/logs.zip)
- the USB drive returns just 0's as audio data
- the `GetAudioSub` returns different values for both drives

**Comment by FeralChild64** [comment]
Got it: MaximumFramesPerCall is too large for USB drives :D

We probably need to write the code that will select the proper value to the given drive. Microsoft claims (source: https://learn.microsoft.com/en-us/windows-hardware/drivers/ddi/ntddcdrm/ni-ntddcdrm-ioctl_cdrom_raw_read):

> If the read is successful, the driver sets Status to STATUS_SUCCESS and Information to the number of bytes transferred. If the read is not successful, the driver sets Information to zero and Status to possibly STATUS_INVALID_PARAMETER, STATUS_INSUFFICIENT_RESOURCES, or STATUS_INVALID_DEVICE_REQUEST.

Probably it's the _Status_ that is going to tell us we are using too high value. But how to read this mysterious _Status_?

**Comment by weirddan455** [comment]
>  Got it: MaximumFramesPerCall is too large for USB drives.

Great find!  So simply reducing that value is enough to make your USB drive work?

>  Probably it's the Status that is going to tell us we are using too high value. But how to read this mysterious Status?

I believe that bit about the status block is how it's implemented on the driver side.  From the application side, you should be able to call `GetLastError()` to retrieve that information.

https://learn.microsoft.com/en-us/windows/win32/api/ioapiset/nf-ioapiset-deviceiocontrol

>  Return value
>
> If the operation completes successfully, the return value is nonzero (TRUE).
>
> If the operation fails or is pending, the return value is zero. To get extended error information, call [GetLastError](https://learn.microsoft.com/en-us/windows/desktop/api/errhandlingapi/nf-errhandlingapi-getlasterror).

**Comment by FeralChild64** [comment]
Both my USB drives work with values up to 27:

```C++
	const bool result = DeviceIoControl(cdrom_handle,
	                                    control_code,
	                                    input_buffer,
	                                    input_buffer_size,
	                                    output_buffer,
	                                    output_buffer_size,
	                                    bytes_returned,
	                                    overlapped);

	LOG_ERR("CDROM_Interface_Win32::ReadAudio - MaximumFramesPerCall %d, %s, LastError 0x%08x",
	        MaximumFramesPerCall,
	        result ? "OK" : "FAIL",
	        GetLastError()); 
```

Results:

```
CDROM_Interface_Win32::ReadAudio - MaximumFramesPerCall 27, OK, LastError 0x00000000
CDROM_Interface_Win32::ReadAudio - MaximumFramesPerCall 28, FAIL, LastError 0x00000057
```

Option 1: We reduce the value to 27 and call it a day.
Option 2: We write the code which tries to find the highest possible value.

I believe this Status value is not the same as `GetLastError()` result, it's probably the `NTSTATUS` (see https://learn.microsoft.com/en-us/openspecs/windows_protocols/ms-erref/596a1078-e883-4972-9bbc-49e60bebca55) - but I have no idea how to get the value.

**Comment by FeralChild64** [comment]
The `0x57` is actually `ERROR_INVALID_PARAMETER`, so maybe `GetLastError()` is the correct way...

**Comment by FeralChild64** [comment]
@weirddan455 Here is some prototype `MaximumFramesPerCall `guessing code:

[guessing_code.zip](https://github.com/user-attachments/files/16394860/guessing_code.zip)

Just reducing the value to 27 would be much easier - but won't it increase the probability of audio stutter? You definitely know more than me on this topic (I don't even like Windows, to be honest...) - so you are the one who has to decide :)

**Comment by weirddan455** [comment]
>  Just reducing the value to 27 would be much easier - but won't it increase the probability of audio stutter?

Hmm... I'll look into it.  It would be nice if there was a way to query the device to know its limits.  Who knows where 27 comes from?  It may be lower on some other hardware.  IIRC I tested on my internal SATA drive and used the maximum value that worked for me.  I incorrectly assumed it would be the same on all hardware.

If there was a known safe lower limit, I think it would be fine to always use that.  Audio stutter isn't too much of a concern here.  The `ReadAudio` function is run in a loop on a dedicated reader thread so that it keeps an `RWQueue` buffer filled for the mixer to consume.

>  I don't even like Windows, to be honest...

That makes two of us :laughing: 

Have you tested this in Linux at all?  I have `MaximumFramesPerCall` set to 75 there.  I remember reading the kernel code to find that value.  Hopefully the Linux kernel actually abstracts the hardware and makes multiple low-level calls if needed to fulfill that request.

**Comment by FeralChild64** [comment]
Yes, I have tested it on my Linux - works fine for me, with every drive.

I'll cleanup the guessing code, do some more testing and create a PR.

**Comment by interloper98** [comment]
27 frames is just under 64 KB (2352 bytes/frame * 27 = 63504), where as 28 goes beyond 64 KB. Maybe the hardware has a 64 KB read buffer and it fills requests from it.  Just speculating.

**Comment by FeralChild64** [comment]
Makes sense - but I rather suspect a buffer in the USB controller or the USB driver; all the drives I have tested have burning capability, they surely have much larger internal buffers.

**Comment by Grounded0** [comment]
Even my old Plextor PlexWriter CD-RW from 2000 had a 4 MB buffer.

**Comment by johnnovak** [comment]
Well, there are the write buffers for burning data, but the read buffers are probably sized differently and are much smaller.

**Comment by Grounded0** [comment]
ATAPI truly is a specification from hell but could be useful:

Information technology - ATA/ATAPI Command Set - 3 (ACS-3)

https://people.freebsd.org/~imp/asiabsdcon2015/works/d2161r5-ATAATAPI_Command_Set_-_3.pdf

This is then operated over the USB interface so even more complexity is added.

**Comment by Grounded0** [comment]
Here's some basics about the USB interface so if one frame is started every millisecond and payload is 64 bits then it logically adds up to around 64 KB/s:

https://forums.raspberrypi.com/viewtopic.php?t=5249

- USB congestion:
our devices work in full-speed (USB 1.1 12 Mbit/s) and transmit at max 1 packet of 64 bytes each frame (64 Kb/s). We have analyse the transfer with and USB analyser and ALL packets are correctly transmitted over the wire (no bus reset, no invalid packet, the USB host ack all packet). this mean that the USB Host controller of the raspberry Pi as correctly received and ack the missing USB packet.

https://en.wikipedia.org/wiki/USB_communications

SOF (Start of Frame) Every millisecond (12000 full-bandwidth bit times), the USB host transmits a special SOF (start of frame) token, containing an 11-bit incrementing frame number in place of a device address. This is used to synchronize isochronous and interrupt data transfers. High-speed USB 2.0 devices receive seven additional SOF tokens per frame, each introducing a 125 μs microframe (60000 high-bandwidth bit times each).

**Comment by shermp** [comment]
For reference, _Status_ appears to be [IO_STATUS_BLOCK](https://learn.microsoft.com/en-us/windows-hardware/drivers/ddi/wdm/ns-wdm-_io_status_block), and is part of the [IRP](https://learn.microsoft.com/en-us/windows-hardware/drivers/ddi/wdm/ns-wdm-_irp). I can't seem to find out if this is ever propagated back up to user code though.
