### ISSUE TITLE
Cruise for a Corpse (1991) Sound Issue

### ISSUE THREAD

**Issue by Python-Exoproject** [dosbox-staging/dosbox-staging#3839]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Different version than latest?

81.1

### What Operating System are you using?

Windows 11

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

If you let the first title screen (the one that eventually shows "Delphine Software") play out then when the intro starts you have no sound here or during gameplay.

If you click on the first title screen instead, it skips the sequence and the intro starts. During and after the intro you have sound.

Ive tested X, Daum, ECE, 0.74, Staging 81.1, Staging 82

Everything except Daum and X have the issue. The fact that X and Daum work points to an emulation problem vs a game one.

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Run game
2. let title play out, listen
3. Run game again, skip title, listen

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by Python-Exoproject** [comment]
@interloper98 Pinging you simply because youve taken an interest in other sound issues ive highlighted but all good if you prefer to pass on it

**Comment by interloper98** [comment]
Thanks for the heads up @Python-Exoproject. Will poke around.

**Comment by interloper98** [comment]
@Python-Exoproject , maybe the latest `main` build has it fixed?

I tested the Adlib audio option let the Delphine logo and intro play without touching the keyboard and mouse. Audio plays for the intro and later once I had control of the character.

https://github.com/user-attachments/assets/8fe2c542-de34-49f0-9649-f54ef8d5aebe

**Comment by johnnovak** [comment]
@interloper98 I think MT-32 is affected, just @Python-Exoproject forgot to mention it.

**Comment by interloper98** [comment]
Oh - thanks @johnnovak . Will check that!

**Comment by interloper98** [comment]
Checked MT-32 and also plays music and effects after letting the Delphine logo and intro play through without touching the keyboard and mouse:

https://github.com/user-attachments/assets/5667f845-7683-4330-97ed-8ad7ee7434eb

Probably irrelevant, but I'm using this config for either audio device, which includes the 8k cycle count you suggested @johnnovak (in another ticket by Python) :smile: .

```ini
[dosbox]
memsize = 1
startup_verbosity = quiet

[dos]
xms = off
ems = off
umb = off

[cpu]
cycles = 8000

[sblaster]
sbtype = none
oplmode = opl2

[midi]
mididevice = mt32

[joystick]
joysticktype = disabled

[autoexec]
mount c .
c:
cd cr256
delphine
```

**Comment by johnnovak** [comment]
Thanks @interloper98. Well @Python-Exoproject, looks fine from our side. Could you perhaps retest with the above config both the OPL and MT-32 options?

**Comment by Python-Exoproject** [comment]
Thanks for investigating. Looks like the error was on my side, my conf wasnt clean enough. Really weird situation though.

Turns out that is the GUS is active this game will crash or if it starts give no sound if the intro completes, but skip the intro and you get the sound. Weird. Anyway, alls good and ticket can be closed
