### ISSUE TITLE
Blank window displayed when launching DOSBox Staging on Windows 10

### ISSUE THREAD

**Issue by igghcz** [dosbox-staging/dosbox-staging#3846]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### What Operating System are you using?

Windows 10

### Relevant hardware info

T420 with Nvidia and Intel graphics.

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

New installation of Windows 10 64 bit EN, all updates, no drivers except those from Windows update.
Latest DosBox Staging, default configuration. After starting DosBox Staging, only a black window with no text appears. You can switch to full screen, you can change the cycles, but still only black in the window and full screen. I didn't see any warning in the console. Changing the shaders to none does not change anything.

### Steps to reproduce the behaviour.

Explain how to reproduce
1. 
2.
3.

### Your configuration

```ini
default configuration
```

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by igghcz** [comment]
Here is the log from DosBox Staging with default configuration and output = opengl:
[dosbox-staging.log](https://github.com/user-attachments/files/16424036/dosbox-staging.log)

DosBox Staging with T420 renders well with output=texture and does not render well with output=opengl. 

DosBox 074-3 with T420 renders well with output=surface, overlay, ddraw and does not render well with output=opengl. 

DosBox-X-mingw-win32-lowend SDL1 with T420 renders well with output=surface, overlay, ttf, ddraw, direct3d and renders, but initialisation and switching from fullscreen to window takes 10 seconds (from window to fullscreen immediately) with output=opengl. 

DosBox-X-mingw-win32-lowend SDL2 behaves the same as SDL1.

**Comment by johnnovak** [comment]
@igghcz Broken old OpenGL drivers, nothing to see here 😆 The Thinkpad T420 was released in Feb 2011...

The `texture` backend is for people who don't have a functioning OpenGL driver which is actually a pretty low bar for computers released in the last 10-15 years. So yeah, use `texture`, or buy a better computer 🤷🏻 😄

**Comment by Grounded0** [comment]
You could force that to use Nvidia and see do you get better results with that. Intel iGPU drivers of that era are notoriously bad including the shit silicon that they run on.

**Comment by sergeevabc** [comment]
Windows 7 x64, DOS Staging 0.82.2

It does not work out of the box, period.

![Image](https://github.com/user-attachments/assets/18622f52-82d7-4901-b2ff-0f67e266b808)

<details><summary>Click to see the log</summary>

``` console
$ dosbox.exe --noprimaryconf

LOG: Loguru version 2.1.0 initialised
LANG: Using internal English language messages
SDL: version 2.30.8 initialised (windows video and directsound audio)
DISPLAY: Using 758x569 window size in windowed mode on display-0
OPENGL: Vendor: Microsoft Corporation
OPENGL: Version: 1.1.0
OPENGL: GLSL version: unknown
OPENGL: NPOT textures not supported
RENDER: Using adaptive CRT shader based on the graphics standard of the video mode
RENDER: Auto-switched to shader 'crt/hercules'
VGA: Pixel doubling enabled
VIDEO: Using the DOS video mode's frame rate
MEMORY: Using 4096 DOS memory pages (16 MB) at address: 0000000007050060
VIDEO: Initialised S3 Trio64 VESA 2.0 compatible with 4 MB of FP DRAM supporting 89 modes
VGA: Double scanning VGA video modes enabled
VOODOO: Initialized with 4 MB of RAM, 2 threads, and bilinear filtering
CAPTURE: Image capturer started
MIXER: Initialised stereo 48000 Hz audio with 1024 sample frame buffer
MIXER: Master compressor enabled
MIDI: Opened device: win32
MPU-401: Running in intelligent mode on ports 330h and 331h
OPL: Operating at 49716 Hz and downsampling to the output rate
OPL: Running OPL3 on ports 220h and 388h
OPL: Sound Blaster 16 OPL output filter enabled
DMA: Initialised primary controller
DMA: Initialised secondary controller
SB: Operating at 22050 Hz and upsampling to the output rate
SB16: Modern DAC output filter enabled
SB16: Setting 'BLASTER' environment variable to 'A220 I7 D1 H5 T6'
SB16: Running on port 220h, IRQ 7, DMA 1, and high DMA 5
PCSPEAKER: Operating at 32000 Hz and upsampling to the output rate
PCSPEAKER: Initialised impulse model
PCSPEAKER: High-pass filter enabled (18 dB/oct at 120 Hz)
PCSPEAKER: Low-pass filter enabled (18 dB/oct at 4300 Hz)
MOUSE: Will be captured after the first left or right button click
MOUSE: Middle button will capture/release the mouse (clicks not sent to the game/program)
MOUSE (PS/2): Standard, 3 buttons
DOS: Loaded modern locale for country 1, 'United States'
SLIRP: Slirp version: 4.8.0
SLIRP: Successfully initialized
NE2000: Initialised on port 300h and IRQ 3
CONFIG: Loaded auto-mounted drive config file 'resources\drives\y.conf'
MAPPER: No joysticks found
MAPPER: Loaded default key bindings
RENDER: Auto-switched to shader 'interpolation/sharp'
VGA: Forcing single scanning of double-scanned VGA video modes
VGA: Forcing no pixel doubling
SDL: Using standard SDI (auto) display refresh rate of 50 Hz
OPENGL: Failed getting double buffering status: OpenGL error: GL_INVALID_ENUM
OPENGL: sRGB framebuffer not supported
DISPLAY: VGA 720x400 16-colour text mode 03h at 70.087 Hz throttled VFR, scaled to 758x569 pixels with 1:1.35 (20:27) pixel aspect ratio
OPENGL: Enabled non-adaptive vsync
MOUNT: Path 'resources\drives\y' found
PCSPEAKER: Shutting down impulse model
OPL: Shutting down OPL3
SB16: Shutting down
MPU-401: Shutting down
CAPTURE: Image capturer shutting down
DMA: Shutting down primary controller
DMA: Shutting down secondary controller
atexit
```

</details>

If it's not a bug, then it's clearly a betrayal of DOSBOX core idea to provide access to DOS apps on computers with newer hardware and OSes, but **not** _exclusively with the latest hardware and OSes_. If you go this selfish route, you violate the crucial principle of [backward compatibility](https://en.wikipedia.org/wiki/Backward_compatibility), something recently born coders seem to forget. Your neighbors legacy laptop is able to run 1080p videos and games such as Heroes of Might & Magic, but not this DOSBOX Staging, whereas an original DOSBOX works. Evolution, huh?

**Comment by flawrist** [comment]
DOSBOX Staging does not work out of the box. Blank screen, period.

<details><summary>Click to see the log</summary>

``` console
$ dosbox.exe --noprimaryconf

LOG: Loguru version 2.1.0 initialised
LANG: Using internal English language messages
SDL: version 2.30.8 initialised (windows video and directsound audio)
DISPLAY: Using 758x569 window size in windowed mode on display-0
OPENGL: Vendor: Microsoft Corporation
OPENGL: Version: 1.1.0
OPENGL: GLSL version: unknown
OPENGL: NPOT textures not supported
RENDER: Using adaptive CRT shader based on the graphics standard of the video mode
RENDER: Auto-switched to shader 'crt/hercules'
VGA: Pixel doubling enabled
VIDEO: Using the DOS video mode's frame rate
MEMORY: Using 4096 DOS memory pages (16 MB) at address: 0000000007050060
VIDEO: Initialised S3 Trio64 VESA 2.0 compatible with 4 MB of FP DRAM supporting 89 modes
VGA: Double scanning VGA video modes enabled
VOODOO: Initialized with 4 MB of RAM, 2 threads, and bilinear filtering
CAPTURE: Image capturer started
MIXER: Initialised stereo 48000 Hz audio with 1024 sample frame buffer
MIXER: Master compressor enabled
MIDI: Opened device: win32
MPU-401: Running in intelligent mode on ports 330h and 331h
OPL: Operating at 49716 Hz and downsampling to the output rate
OPL: Running OPL3 on ports 220h and 388h
OPL: Sound Blaster 16 OPL output filter enabled
DMA: Initialised primary controller
DMA: Initialised secondary controller
SB: Operating at 22050 Hz and upsampling to the output rate
SB16: Modern DAC output filter enabled
SB16: Setting 'BLASTER' environment variable to 'A220 I7 D1 H5 T6'
SB16: Running on port 220h, IRQ 7, DMA 1, and high DMA 5
PCSPEAKER: Operating at 32000 Hz and upsampling to the output rate
PCSPEAKER: Initialised impulse model
PCSPEAKER: High-pass filter enabled (18 dB/oct at 120 Hz)
PCSPEAKER: Low-pass filter enabled (18 dB/oct at 4300 Hz)
MOUSE: Will be captured after the first left or right button click
MOUSE: Middle button will capture/release the mouse (clicks not sent to the game/program)
MOUSE (PS/2): Standard, 3 buttons
DOS: Loaded modern locale for country 1, 'United States'
SLIRP: Slirp version: 4.8.0
SLIRP: Successfully initialized
NE2000: Initialised on port 300h and IRQ 3
CONFIG: Loaded auto-mounted drive config file 'resources\drives\y.conf'
MAPPER: No joysticks found
MAPPER: Loaded default key bindings
RENDER: Auto-switched to shader 'interpolation/sharp'
VGA: Forcing single scanning of double-scanned VGA video modes
VGA: Forcing no pixel doubling
SDL: Using standard SDI (auto) display refresh rate of 50 Hz
OPENGL: Failed getting double buffering status: OpenGL error: GL_INVALID_ENUM
OPENGL: sRGB framebuffer not supported
DISPLAY: VGA 720x400 16-colour text mode 03h at 70.087 Hz throttled VFR, scaled to 758x569 pixels with 1:1.35 (20:27) pixel aspect ratio
OPENGL: Enabled non-adaptive vsync
MOUNT: Path 'resources\drives\y' found
PCSPEAKER: Shutting down impulse model
OPL: Shutting down OPL3
SB16: Shutting down
MPU-401: Shutting down
CAPTURE: Image capturer shutting down
DMA: Shutting down primary controller
DMA: Shutting down secondary controller
atexit
```

![Image](https://github.com/user-attachments/assets/a27667d9-fb5b-45ee-945c-ad49ba572b08)
</details>

If it's not a bug, then it's clearly a betrayal of DOSBOX core idea to provide access to DOS apps on computers with newer hardware and OSes in general, not with the latest hardware and OSes exclusively. By following this vicious path, you violate the crucial principle of [backward compatibility](https://en.wikipedia.org/wiki/Backward_compatibility). Your neighbors legacy laptop is able to run 1080p videos and games such as Heroes of Might & Magic, but not this DOSBOX Staging, whereas the original DOSBOX and DOSBOX-X work fine. Evolution, huh?

I'd like to take this opportunity to thank @joncampbell123 and [144](https://github.com/joncampbell123/dosbox-x/graphs/contributors) contributors of DOSBOX-X, as well as the original DOSBOX [team](https://www.dosbox.com/crew.php), for their humanitarian efforts that enable owners of legacy hardware (like IBM X61 laptop without a video card), who care about the environment and aren't in a hurry to dump working stuff, to run DOS apps.

![Image](https://github.com/user-attachments/assets/50266a7b-ecde-46e7-948b-5301233a0126)

**Comment by Grounded0** [comment]
Try `output = texture` as your system seems to fail to initialise OpenGL 2.1 which is a hard requirement (both in terms of hardware capabilities and driver support) for OpenGL in DOSBox Staging.

**Comment by johnnovak** [comment]
@sergeevabc Min requirement is Windows 10 for the latest release.

You've just forfeited any help from the team with that attitude. You don't have any claims on how we use our free time.

Don't like it? Fork the project and make it happen, man.

**Comment by Torinde** [comment]
> OpenGL 2.1 which is a hard requirement (both in terms of hardware capabilities and driver support) for OpenGL in DOSBox Staging.

I suggest we mention that somewhere at [the website](https://www.dosbox-staging.org/releases/windows/#hardware-requirements) or Wiki. Are you sure the version is specifically 2.1?

**Comment by johnnovak** [comment]
> > OpenGL 2.1 which is a hard requirement (both in terms of hardware capabilities and driver support) for OpenGL in DOSBox Staging.
> 
> I suggest we mention that somewhere at [the website](https://www.dosbox-staging.org/releases/windows/#hardware-requirements) or Wiki. Are you sure the version is specifically 2.1?

We don't need to mention it as the min OS version requirements make that happen automatically.

Besides, it will change soon as I'm reworking the OpenGL stuff.

**Comment by flawrist** [comment]
Re: @Grounded0

> Try output = texture as your system seems to fail to initialise OpenGL 2.1

Thank you, sir. It kinda works, but the output is blurry. I found another workaround that makes the output sharper. It's called [Mesa3D](https://fdossena.com/?p=mesa/index.frag) by Federico Dossena @adolfintel. You put the provided `opengl32.dll` into DOSBOX Staging folder and that's all.

<details><summary>Click to see the comparsion</summary>

## dosbox-staging.conf output=texture
![Image](https://github.com/user-attachments/assets/2c0809ad-0264-4370-b404-0fcfa540a8da)

## mesa3d opengl32.dll
![Image](https://github.com/user-attachments/assets/bd70cb90-4c2f-4f39-834f-bd59a1fd5158)

</details>

**Comment by flawrist** [comment]
Re: @johnnovak

> You've just forfeited any help from the team with that attitude. You don't have any claims on how we use our free time. Don't like it? Fork the project and make it happen, man.

Truly, one of the mysteries of life is that when disasters like the Australia's [bushfires](https://www.abc.net.au/news/2020-07-28/3-billion-animals-killed-displaced-in-fires-wwf-study/12497976) happen and ~3 billion animals die, including poor koalas and kangaroos, people who live nearby (like you, John) continue to live and ruin well-working apps like DOSBOX “in their free time”. As if free time allows you to do anything — you know, criminals commit crimes in their free time too. Should I fork the planet if I don't like what they do, huh? No, I always start with the feedback, especially when there's a dedicated place like a public issue tracker and not some private Discord channel. You, supposedly familiar with the demoscene where talented programmers managed to put mesmerizing graphics into less than 100 KB DOS apps that didn't require any fancy video support, require the latest OS and OpenGL to run those apps. What a shame! Now go ahead and hide your 40-year-old head behind “the team”, dislikes and abuse tags, but don't forget to take the word man out of your vocabulary, since a man's gotta have balls and be able to face consequences.

**Comment by johnnovak** [comment]
> since a man's gotta have balls and be able to face consequences.

Indeed. You're banned.

**Comment by Torinde** [comment]
> We don't need to mention it as the min OS version requirements make that happen automatically.

If I understand correctly - the OP here uses Win10 (which doesn't require OpenGL) and as we see - his GPU/driver doesn't support properly OpenGL2.1. And the "texture" option is specifically for such cases (and debugging, I assume).

I think the min OS version requirement guarantees certain OpenGL support only on macOS.

If not on the website, then maybe the version to the .conf description:
- "fallback for buggy or non-existent OpenGL **2.1 support in the** drivers  (this is extremely rare)." (and after your rework that'll become 3.0, etc.)

**Comment by Grounded0** [comment]
You can see from the screenshots the person uses Windows 7 from the title bar of the window. The minimum OS requirement currently being Windows 8 is due to stuff like Slirp not working on Windows 7, but it appears that the binary at least runs on it, but with reduced functionality.

I agree that mentioning the minimum OpenGL version required in .conf seems like a good idea. @Torinde, you should PR that change since it's easy to do, and I think it has a good chance of getting merged.

**Comment by Grounded0** [comment]
As for us "ruining" DOSBox let me respond to that. Even Harekiet (Sjoerd van der Berg) has admitted in public IRC discussions that not migrating DOSBox to SDL2 was an error. That's how we started in 2019, facing a lot of bullying from people who wanted to continue to run DOSBox on Windows NT 4.0 and so on, which migrating to SDL2 broke.

DOSBox remains available for download for anyone who wants to run it on Windows NT 4.0 and so on. We do our own thing here.

**Comment by johnnovak** [comment]
> If not on the website, then maybe the version to the .conf description:
> 
>  * "fallback for buggy or non-existent OpenGL **2.1 support in the** drivers  (this is extremely rare)." (and after your rework that'll become 3.0, etc.)

That's reasonable, I'll just do that in my SDL PR. Btw, after I've fully salvaged GranMinigun's SDL improvements, we'll explicitly ask for OpenGL 2.1 in the init and error out if not found (right now we don't check for it).

**Comment by johnnovak** [comment]
> DOSBox remains available for download for anyone who wants to run it on Windows NT 4.0 and so on. We do our own thing here.

Yeah, also clearly mentioned in the "non-goals" section of our about page:

![Image](https://github.com/user-attachments/assets/ed911049-98ce-4c63-bd47-f293afaaa5da)
