### ISSUE TITLE
Regression in 82 when using echo in a bat script to output to file

### ISSUE THREAD

**Issue by Python-Exoproject** [dosbox-staging/dosbox-staging#3872]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### What Operating System are you using?

Windows 11

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

In eXoDOS we use echo occasionally to output from the launch bat. For example:

In ECE and Staging 81.1 if we have the lines in the game `run.bat`:

```
if %VIDEO%==VGA echo  videoDrv  = VGA320.DRV>>resource.cfg
if %VIDEO%==EGA echo  videoDrv  = EGA640.DRV>>resource.cfg
if %SOUND%==SB echo  soundDrv  = SBPRO.DRV>>resource.cfg
if %SOUND%==SB echo  audioDrv  = AUDBLAST.DRV>>resource.cfg
if %SOUND%==MT32 echo  soundDrv  = MT32.DRV>>resource.cfg
if %SOUND%==MT32 echo  audioDrv  = AUDBLAST.DRV>>resource.cfg
if %SOUND%==SC echo  soundDrv  = GENMIDI.DRV>>resource.cfg
if %SOUND%==SC echo  audioDrv  = AUDBLAST.DRV>>resource.cfg
echo  joyDrv    = NO>>resource.cfg
echo  kbdDrv    = IBMKBD.DRV>>resource.cfg
echo  mouseDrv  = STDMOUSE.DRV>>resource.cfg
echo  memoryDrv = ARM.DRV>>resource.cfg
echo  minHunk   = 204k>>resource.cfg
echo  language  = 1>>resource.cfg
echo  cd        = YES>>resource.cfg
echo  cmd       = FPFPCD>>resource.cfg
echo  audioSize = 16k>>resource.cfg
echo  patchDir  = C:\;D:\freddy\audio>>resource.cfg 
echo  resAUD    = C:\audio>>resource.cfg 
```

we are provided the file `resource.cfg` with:

 ```
 videoDrv  = VGA320.DRV
 soundDrv  = SBPRO.DRV
 audioDrv  = AUDBLAST.DRV
 joyDrv    = NO
 kbdDrv    = IBMKBD.DRV
 mouseDrv  = STDMOUSE.DRV
 memoryDrv = ARM.DRV
 minHunk   = 204k
 language  = 1
 cd        = YES
 cmd       = FPFPCD
 audioSize = 16k
 patchDir  = C:\;D:\freddy\audio
 resAUD    = C:\audio
 ```

yet in Staging 82 the same lines provide a file `resource.cfg` with:

```
 resAUD    = C:\audio
ddy\audio
```

### Steps to reproduce the behaviour.

These lines came from the run.bat found with the game Freddy Pharkas in eXoDOS so this could be used to test

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by interloper98** [comment]
Bisected to d4509f9ff 

@weirddan455 , I skimmed the commit and I'm not seeing any big or scary parsing changes (which I think is a good thing). Just needs to be isolated where this handling has gone wrong in the logic and flow adjustments.

(I'm still working on the audio frame handling tweaks PR; can help when I get through it).

**Comment by weirddan455** [comment]
Thanks for the bisect @interloper98 I'll take a look.
