### ISSUE TITLE
Controller Right Stick Left\Right Axis Not Working (Regression)

### ISSUE THREAD

**Issue by Python-Exoproject** [dosbox-staging/dosbox-staging#3883]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### What Operating System are you using?

Windows 11

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

I am using a PS5 DualSense controller. 

In Staging 75.2 I can load DOOM go into the gameplay, load the dosbox mapper up, and map the keyboard left arrow to right stick left and keyboard right arrow to right stick right and it works no problem.

In 82 RC I can map to the controller for right stick left\right but in game it does nothing

I checked version between 75.2 and 82RC and found that 76 works, but from 77 it does not. 

One item I noted that changed in 77 was that prior to 77 the information in the mapper under "BIND" when I mapped to the right stick left\right axis was "axis2-" for left and "axis2+" for right. As of 77 this changed and both directions now state "axis2+".

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Add joysticktype=4axis to conf
2. Plug in a DualSense PS5 controller
3. Load any game, I used DOOM
4. Get into gameplay and load the dosbox mapper up
5. Map the keyboard left arrow to the right stick left direction and keyboard right arrow to the right stick right direction
6. Test if does anything in game

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by weirddan455** [comment]
Looking into this.  I can confirm axis 2 and 5 are not working correctly on my Xbox controller in Linux as well.  These are the trigger buttons for me.  Pressing and releasing the buttons both map to + and is a regression.  Starting a bisect.

**Comment by weirddan455** [comment]
Found the original issue with some more context #943 particularly this comment where this fix is known to be problematic if the "trigger" axis is actually a stick:  https://github.com/dosbox-staging/dosbox-staging/issues/943#issuecomment-805875578

All this commit does is force axis 2 and 5 to always register positive movement on the axis when adding a binding.  It doesn't change behavior outside of the mapper GUI.

A workaround was mentioned on the original ticket which should also work for you (in kind of the opposite situation) @Python-Exoproject   You can manually edit the mapper file and find the line where you mapped the arrow key to your stick.  It should end with `axis 2 1`.  Change that trailing 1 to a 0.

I'll have to think more about what the real solution to this is.

**Comment by interloper98** [comment]
Nice find @weirddan455 ! Just reading that original ticket and discussion; it would sure be nice if SDL's joystick API was mapped in from the controller database, so we can benefit from that normalisation (without having to migrate to the new  controller API; well, not until we want to re-write the mapping system from the ground up).

**Comment by weirddan455** [comment]
Yeah @interloper98  I don't want to refactor the mess that is `sdl_mapper.cpp` but the newer Gamepad API may be better to use in the long term.  I put in a PR that I think will improve things.  It's simple detection on init to get the axes resting position to label which ones are trigger buttons, rather than assuming it's always axis 2 and 5.
