### ISSUE TITLE
[Documentation / Visuals] Could more examples be added at https://www.dosbox-staging.org/#screenshots ?

### ISSUE THREAD

**Issue by rubyFeedback** [dosbox-staging/dosbox-staging#3884]
Could more examples be added at https://www.dosbox-staging.org/#screenshots ?

For instance, the UFO DOS games; also "Das schwarze Auge" I and II (for those not knowing
the latter, here is one image from "Sternenschweif", I think in english it was called Realms of
Arcania I and II):

https://i.imgur.com/aAEvAbF.png

Not sure how many more examples to be added. Perhaps 3-6, to make it a reasonable list?

I remember some more games, like North and South and so forth. For more ideas perhaps
scummvm could be cited as example, but just for the DOS part of games I suppose, since
that is the objective of dosbox-staging, right?

**Comment by johnnovak** [comment]
I think we have more than enough screenshots. Sometimes I think we have too many of them already.

**Comment by Grounded0** [comment]
Can be closed. Page loading times and browser memory usage should also be taken to a account so we're maxed out currently.

**Comment by johnnovak** [comment]
> Page loading times and browser memory usage should also be taken to account so we're maxed out currently.

I'm loading them lazily for that reason (they only get loaded if you scroll close to them, so loading the front page is always fast), but yeah, I agree otherwise.
