### ISSUE TITLE
Add 256-color tweak mode for text mode

### ISSUE THREAD

**Issue by dxgldotorg** [dosbox-staging/dosbox-staging#3886]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Different version than latest?

0.81.2

### What Operating System are you using?

Windows 11

### Is your feature request related to a problem? Please describe.

Add an obscure tweak mode to allow applying 256 colors to text mode as described at https://github.com/joncampbell123/dosbox-x/issues/4764

### Code of Conduct & Contributing Guidelines

- [x] Yes, I agree.

**Comment by Grounded0** [comment]
Here's the commit:

- https://github.com/joncampbell123/dosbox-x/commit/8393a028127ba148146b208fab9b47c2098b7a45

**Comment by johnnovak** [comment]
Erm, that's a hard no.

<img width="595" alt="image" src="https://github.com/user-attachments/assets/67d258a4-4c1c-4126-93d9-984b8857da3e">

We won't add a `enable_supermegazeux_tweakmode` config setting for a single obscure game.

Unless someone proves this is useful for at least _another_ vaguely significant game, _and_ the change can be made without relying on extra config settings that doesn't conflict with the VGA emulation (so always on).

The VGA emulation is complex enough, we don't wanna add more oil to the fire for no good reason.

**Comment by Grounded0** [comment]
We'll leave this open for a while for discussion since this isn't North Korea.

**Comment by johnnovak** [comment]
Okay, I've looked a bit more into it if adding this is even feasible for us. The short answer is no, it isn't.

This hack mode is not compatible with any of the SVGA cards we're emulating. It's only available on a very few SVGA cards, so I'm closing this.

---

Relevant info from the referenced DOSBox X issue ticket:

> To more accurately explain what is supposed to be going on in VGA terms: for '90s Nvidia, ATi, and possibly some Cirrus Logic and C&T graphics adapters, enabling the mode 13h pixel doubling bit of the VGA mode control register while in 640x350 text mode would result in a 256-color 320x350 text mode with 4 colors per character. 
([source](https://github.com/joncampbell123/dosbox-x/issues/4764#issuecomment-1899676584))

Also see the "Hardware with No SMZX Support" table on the author's (?) website. S3 and Tseng cards are not compatible with this mode:

https://www.digitalmzx.com/wiki/Super_MegaZeux#Compatibility

Here Jon also confirms this hack doesn't appear to work on Paradise cards:

>A 486 laptop with a Paradise/Western Digital SVGA chipset doesn't work this way. You can set the bit and halve the resolution of text mode, but it doesn't allow this hack to work.
[source](https://github.com/joncampbell123/dosbox-x/issues/4764#issuecomment-1916086561)

**Comment by Grounded0** [comment]
If anyone needs this tweak mode use DOSBox-X.
