### ISSUE TITLE
"Tony & Friends in Kellogg's Land" and "Tricky Quicky Games" do not launch and have problems with image flickering and sound stuttering

### ISSUE THREAD

**Issue by gamerlion7** [dosbox-staging/dosbox-staging#3894]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### What Operating System are you using?

Linux ARM (Raspberry Pi)

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

If you start "Tony & Friends in Kellogg's Land" and "Tricky Quicky Games" with DOSBox Staging on RetroPie you immediately come back to the games list. You can launch "Tony Friends in Kellogg's Land" sometimes, but I have not found out why.

You can play the games with DOSBox. With "Tony & Friends in Kellogg's Land" the image is often flickering and the sound often stutters. "Tricky Quicky Games" works way better, but you can notice a bit of image flickering and sound stuttering.

### Steps to reproduce the behaviour.

Explain how to reproduce
1. 
2.
3.

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by Grounded0** [comment]
Can you provide download links for both games since they're both freeware. Thanks.

**Comment by gamerlion7** [comment]
You can get the games from these links for example:
Tony & Friends in Kellogg's Land: https://werbespiel.blogspot.com/2010/07/tony-friends-in-kelloggs-land.html
Tricky Quicky Games: https://archive.org/details/Quicky

These downloads contain more files than other downloads, but they work.

I updated RetroPie and DosBox Staging to the newest versions (before I had versions from April 2024) and now the games launch at least.

**Comment by interloper98** [comment]
I'll give these breakfast cereal-based DOS games a try on my pi 🥣

**Comment by MasterO2** [comment]
> I'll give these breakfast cereal-based DOS games a try on my pi 🥣

Part of a balanced breakfast? :)

**Comment by interloper98** [comment]
@gamerlion7,

These games are working fine on the pi (I'm on a pi4, rasberry pi os bookworm,  aarch64). I'm using the latest DOSBox Staging build.

You can unzip these:
- [quickly.zip](https://github.com/user-attachments/files/16755037/quickly.zip), then launch with `dosbox --working-dir quickly` or simply enter the directory and launch DOSBox Staging: `cd quickly && dosbox`
- [tony_and_friends.zip](https://github.com/user-attachments/files/16755039/tony_and_friends.zip), then launch with `dosbox --working-dir tony_and_friends` or simply enter the directory and launch DOSBox Staging: `cd tony_and_friends && dosbox`

Here's a couple recordings from the pi; I'm not getting any flicking or stuttering:

https://github.com/user-attachments/assets/f4c6c7ae-6cf5-470a-973f-7805fa9b48c2


https://github.com/user-attachments/assets/c3e94265-38d1-4438-8b85-293f8f7d19f0

**Comment by gamerlion7** [comment]
I have a Raspberry Pi 3 B+. Other DOS games work fine on my Pi.

The following config did not fix the image flickering and sound stuttering in both games and the invisible water in "Tony & Friends in Kellogg's Land" on my Pi:
```
[cpu]
core = normal
cycles = 10000
```

@interloper98 what happens without the variables set?

**Comment by interloper98** [comment]
@gamerlion7 ,

Are you using **the latest release**? Run `dosbox --version` to confirm.

Be sure you're using 0.82-alpha or a build from the current `main` branch.

If you're running 0.82-alpha or current `main` build, then trying this on your 3B combined with the conf I provided in the zips above:

```ini
[cpu]
core = dynamic
cpu_cycles_protected = 5000
```

You should have sound, smooth video stuttering, and the water should look transparent (like in the video).

**Comment by Grounded0** [comment]
> I have a Raspberry Pi 3 B+

This means it has rubbish ARM Cortex A53 cores. Hopefully dynamic recompiler improves the situation as @interloper98 proposes above.

**Comment by gamerlion7** [comment]
I updated to a build from August 27, 2024.
Where exactly should I enter `dosbox --version`?

I tested the versions from @interloper98, but it only fixed the invisible water in "Tony & Friends in Kellogg's Land".

"Quicky Tricky Games" runs way better with DOSBox than with DOSBox Staging, but the resolution is different.

Changing `core = normal` to `core = dynamic` made it worse unfortunately.

**Comment by interloper98** [comment]
@gamerlion7, 

> Where exactly should I enter dosbox --version?

From the command line. How are you running these games if you're not even able to run `dosbox` from the command line?

Are you building your own executables? If not, where are you getting them from?

> "Quicky Tricky Games" runs way better with DOSBox than with DOSBox Staging, but the resolution is different.

I suspect you might not be using the conf files I included in the games. In them, I limited the window resolution to 800x600 because the Pi3 and Pi4 have terrible video performance at full desktop resolutions (like 1920p or 4k).

**Comment by interloper98** [comment]
A couple DOSBox Staging settings you can try on the pi3:

```ini
[sdl]
output = texture
```

or

```ini
[sdl]
output = opengl

[render]
glshader = none
```

Combined either with limiting the output resolution:

```
[sdl]
windowresolution = 800x600
```

or if you're running fullscreen:

```
[sdl]
fullscreen = true
fullresolution = 1280x720
```

Also search this issues for "rpi" or "raspberry". There's a lot of older and very detailed discussions that can help improve performance. That's how I learned about a bunch of the settings I'm using now.

**Comment by gamerlion7** [comment]
@interloper98, I go to MS-DOS in RetroPie, open the game and launch the exe file that starts the game.

If I launch "+START DOSBOX" from the games list, the console of DOSBOX opens.
If I launch "+START DOSBOX-STAGING" from the games list, I am redirected to the games list.

The settings you suggested did not fix the image flickering and sound stuttering unfortunately.

**Comment by johnnovak** [comment]
If the Pi3 is too weak for the task, there's nothing we can do. Please play with the above suggested settings, ask fellow RetroPie users, or if all else fails, spend a few bucks to upgrade to a Pi4 or 5 that will perform a lot better.

Please note we do not officially support RetroPie, so as this is not a Staging problem but a weak hardware problem, I'm closing this

**Comment by gamerlion7** [comment]
@johnnovak, the hardware is probably too weak.

"Quicky Tricky Games" runs way better with DOSBox than with DOSBox Staging.

Should DOSBox Staging not be more performant or just as performant as DOSBox?

**Comment by johnnovak** [comment]
> Thank you @interloper98, @Grounded0 and @johnnovak for the input.
> 
> The hardware is probably too weak.
> 
> As written above, "Quicky Tricky Games" runs way better with DOSBox than with DOSBox Staging.
> 
> Should DOSBox Staging not be more performant or just as performant as DOSBox?

Staging emulated the DOS environment and various OC hardware more accurately that legacy DOSBox in many instances -- that comes a cost.

It perform more than well enough on modern desktop hardware released in the last 10 years. Legavmcy DOSBox was optimised for pre 2010 hardware are certain simplifications were made to keep the emulation performant.

We're not interested supporting really old or really weak hardware, so that's your answer I guess :)

**Comment by interloper98** [comment]
I appreciate the thanks, @gamerlion7, even if we're near a dead end.

The pi3 is slow, but when I google for DOSBox Staging, cycles, retropie - I see this thread: https://retropie.org.uk/forum/topic/25041/dosbox-official-thread/36 and there are several mentions of people hitting around `25000` cycles on the pi3.

In the case of Tony and Quiky - my tests show the game only needs 5000 (or even less!); and on top of it you can use the dynamic for for even better performance.

Thanks for explaining how you're launching it. 

For you to diagnose it further, I would suggest learning how to access your command line (exiting RetroPie to the shell), and then read our build instructions to get your own build going - and finally learn how to launch DOSBox directly on the command line.  That's a lot to learn and should keep you busy, but it should be productive in the end.

**Comment by Grounded0** [comment]
We're also working the on-die GPU much harder which eats away from the total power budget of the SoC. We've already had this same ticket basically repeated earlier over and over.

DOSBox Staging basically works any kind of silicon it runs on much harder which can be pretty unforgiving for really low end SoCs or any kind of TDP limited designs.

**Comment by johnnovak** [comment]
> We're also working the on-die GPU much harder which eats away from the total power budget for the CPU. We've already had this same ticket basically repeated earlier over and over.

By default with the CRT shaders, yeah, but `output = texture` should be as lightweight as it gets, and `glshader = sharp` is very lightweight too even on the weakest GPUs.

**Comment by interloper98** [comment]
The Pi 4 has no problems through the 486 era - and even then it plays a bunch of software 3D games at very playable frame rates.

The Pi doesn't have tug-of-war power consumption tricks like Intel's done in recent years, _"Oh, you're using 100% GPU at this moment? Well that's going to cost you a 35% hit to your peak CPU speeds. Oh, now you're using all cores? Fine, we'll take away turbo boost and cut those P-core speeds, too."_ :police_car: :policeman:  

The Pi corporation kinda sold out to commercial and industrial use in recent years. Search for "Raspberry Pi digital signage" :nauseated_face: ; yeah - all those 6-ft tall interactive animated screens in shopping malls and grocery stores are usually powered by a pi grinding 24-7. 

The Pi's GPU doesn't max out with shaders or OpenGL stuff running retro games (search youtube for retropie.. 60 fps all day with shaders). 

Here's a timedemo of Quake 3 (yes, native) just showing CPU+GPU performance  https://www.youtube.com/watch?v=sIsoFmWoJB0

**Comment by johnnovak** [comment]
> The Pi corporation kinda sold out to the commercial and industrial sector in recent years (UK still lets them keep their non profit status 😆 ). Search for "Raspberry Pi digital signage" 🤢 ; yeah - all those 6-ft tall interactive animated screens in shopping malls and grocery stores are usually powered by a pi grinding 24-7.

Isn't it more like people started using their products for commercial purposes, and they don't hate money? 😆 I guess they could curb that a bit by only allowing max say 5 computers to be purchased from them direct in one transaction to prevent people from building Pi datacenters or something, but not sure they do that 😆

**Comment by interloper98** [comment]
> Isn't it more like people started using their products for commercial purposes, and they don't hate money?

It's all good to sell to buyers and compete against knockoffs (Banana Pi, Intel N100, etc..). Buyers gain from economies of scale and a better product.

They're now fully [catering to industrial customers](https://www.raspberrypi.com/news/supporting-raspberry-pis-industrial-customers/) and [even IPO'd](https://www.raspberrypi.com/news/raspberry-pi-ipo/) on the London stock exchange... cool.. but man, it's all getting very far away from their charity and [mission statement](https://www.raspberrypi.org/about/): _"a UK-based charity with the mission to enable young people to realise their full potential through the power of computing and digital technologies."_ 

What would people think if the Red Cross IPO'd. Yo dog, our CEO gotta get those stock options,right? :laughing:  

Definitely a bunch of legal buckets they're playing with like OpenAI. Ohh.. But our LLC is managed under a holding company that's a separate from our charity Org, which are not legally connected in anyway.

**Comment by johnnovak** [comment]
> but man, it's all getting very far away from their charity and [mission statement](https://www.raspberrypi.org/about/): _"a UK-based charity with the mission to enable young people to realise their full potential through the power of computing and digital technologies."_

Haha, fair points @interloper98. To be fair, my use of the 3 Pi boxes I have are:

- torrent box
- Kodi media player box hooked up to the TV
- DOSBox & general Linux dev box

And I'm not exactly young at 45 either 😆 I'm just wondering if their original mission went sideways from the get go, before even the commercial uptake, and their customers are older people like me using the Pi for similar purposes (just look at all those projects, 1541 drive emulation, Amiga VGA upscalers, MT32 emulators, etc.)
