### ISSUE TITLE
i-force device emulation (serial/usb)

### ISSUE THREAD

**Issue by sonik-br** [dosbox-staging/dosbox-staging#3898]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### What Operating System are you using?

None

### Is your feature request related to a problem? Please describe.

How complex would be to add i-force device emulation?
I-force devices can be serial or usb. It provide force feedback for some racing wheels and joysticks.
Serial version would benefit most for DOS games while USB would be for windows games.
The protocol is standard between different devices. There's some documentation on the linux kernel driver for it.

Some links with info:

https://www.kernel.org/doc/Documentation/input/iforce-protocol.txt
https://github.com/torvalds/linux/blob/47ac09b91befbb6a235ab620c32af719f8208399/drivers/input/joystick/iforce

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by sonik-br** [comment]
The Sidewinder devices uses another protocol and uses the gameport connector (mostly it's MIDI data pins) and are for windows only.

I-force is older.
It's a protocol by Immersion and used on some devices from various vendors, including Thrustmaster and Logitech.

From the top of my mind:
Descent 2
Extreme Assault (this one is DOS only)
Need for Speed SE

**Comment by FeralChild64** [comment]
Regarding USB - this is not emulated, and definitely won't be in a foreseeable future :)

As for serial - when comparing the protocol to SDL2 haptic interface, at first glance it looks feasible. I won't do this, unfortunately - too busy with other topics.

**Comment by sonik-br** [comment]
@FeralChild64 , there's a "framework" or something to help implement this via serial or usb? I might give it a shot.
Should I start with something like [this](https://github.com/dosbox-staging/dosbox-staging/blob/main/src/hardware/serialport/serialmouse.h#L27C29-L27C36)?

**Comment by FeralChild64** [comment]
USB - no, there isn't any, we are not emulating any USB controller and have no plans to do so.

Serial - yes, go to `src/hardware/serialport` directory and see how `serialdummy.cpp` is implemented and how it is referenced by `serialport.cpp`. You'll need to make some connection between the serial port _i-force_ implementation and the `src/hardware/joystick.cpp` code.

**Comment by johnnovak** [comment]
@sonik-br USB is out of scope because Win95/98 is out of scope. Please check out our project goals here:

https://www.dosbox-staging.org/about/#goals

USB was a Windows thing. AFAIK USB drivers for DOS appeared retroactively post-2000, mostly by retro-enthusiasts. Back in the real DOS era support was nonexistent.

**Comment by FeralChild64** [comment]
The biggest DOSBox-related challenge I see is that `joystick.cpp` does not tap into SDL joystick subsystem directly, but uses the `sdl_mapper.cpp`, which is not really nice, and _to be replaced with a better solution_ someday in the future.

**Comment by sonik-br** [comment]
My idea is to first get the protocol implemented so a game can talk to the virtual i-force device.
Immersion shared an executable that "emulates" an i-force device via serial, so a game/driver can talk to it from another pc. This was used by developers without access to a real i-force hardware. I can probably just port this "emulator" to act as a virtual device on dosbox.

I-force protocol have a common protocol to report it's axis and buttons.
This should be the starting pointing. Then later on the sdl/ffb stuff can be added on top of it.

Thanks for the reply. And feel free to close the issue.
I'm going to try but it will take a very long time.

**Comment by FeralChild64** [comment]
@sonik-br Well, good luck then!

**Comment by Grounded0** [comment]
> My idea is to first get the protocol implemented so a game can talk to the virtual i-force device.
Immersion shared an executable that "emulates" an i-force device via serial, so a game/driver can talk to it from another pc. This was used by developers without access to a real i-force hardware. I can probably just port this "emulator" to act as a virtual device on dosbox.

Godspeed. Back to cat videos. 😁

**Comment by sonik-br** [comment]
I've got i-force device emulation on dosbox! \o/
Still needs some work. But I can already play NFS:SE with forcefeedback!

Beta version here for testing:
https://github.com/sonik-br/dosbox-staging/releases/tag/iforce

Requires a input device connected and mapped as a joystick.
The i-force device uses `gameport` + `serial`

Can be configured to send real FFB commands to a connected joystick/racing wheel, or even send rumble to common gamepad.
Quick video of it in action.
NSF:SE sends ffb commands even on it's replay
https://youtu.be/Dnc2D71YhwI

**Comment by johnnovak** [comment]
@sonik-br Can you show us the code?

**Comment by sonik-br** [comment]
Let me test it for a few days.
And I need to confirm if it can be released... It's based on some source files that are part of immersion's sdk. It's on the internet but I'm not sure how it was distributed back in the day.
I'm trying to use wayback machine to navigate Immersion's old site.

**Comment by johnnovak** [comment]
> Let me test it for a few days. And I need to confirm if it can be released... It's based on some source files that are part of immersion's sdk. It's on the internet but I'm not sure how it was distributed back in the day. I'm trying to use wayback machine to navigate Immersion's old site.

FYI, this can only be theoretically merged if:

- Whatever you're using (SDK, whatnot) is compatible with the project's GPL 2.0 license
- The solution works on all 3 platform we support: Windows, macOS, and Linux. You are also expected to test it on all 3 platforms, and maintain it going forward (if testing requires special hardware we don't have).

These are the hard minimum requirements.

**Comment by sonik-br** [comment]
That's a no go then. I can only test on windows.

I'm still not sure if source material is compatible with the license.
If not compatible, it will be a problem if I release it on my fork? Or better to keep it to myself?

**Comment by johnnovak** [comment]
> That's a no go then. I can only test on windows.

That's it then.

> I'm still not sure if source material is compatible with the license. If not compatible, it will be a problem if I release it on my fork? Or better to keep it to myself?

Your fork is not our responsibility — it's yours. You'll need to do your research and do what's appropriate for the situation.

**Comment by FeralChild64** [comment]
> I'm still not sure if source material is compatible with the license.

Why not to get rid of the original Immersion SDK then? The Linux Kernel contains both the protocol documentation (https://www.kernel.org/doc/html/v6.2/input/devices/iforce-protocol.html) and a driver (https://github.com/torvalds/linux/tree/master/drivers/input/joystick/iforce) - you probably don't need to include the SDK at all.

**Comment by sonik-br** [comment]
@FeralChild64 The one on linux is for i-force 2.0
Devices that came later, using serial or usb. Probably only used by "modern" games from win95 era.
DOS games seems to use only i-force 1.0. At least it's the one used by The Need For Speed.
I've added i-force 2.0 support too (based on linux docs) but it's untested.
