### ISSUE TITLE
Sound Blaster's DMA mode can request too many frames, leading to overflow

### ISSUE THREAD

**Issue by interloper98** [dosbox-staging/dosbox-staging#3913]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### What Operating System are you using?

Linux ARM (Raspberry Pi)

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

When doing some 0.82 RC1 play testing, I noticed The Rocketeer audio sequences sounded pretty rough:

https://github.com/user-attachments/assets/51ee2202-8e5b-4a72-a760-fd0b77ab8c46

And here's 0.81.2:

https://github.com/user-attachments/assets/3b6ceb55-0f6a-4bd5-993d-0e33c6aaf68e

---

I added some logging in the Sound Blaster's `enqueue_frames(...)` function and plenty of games are fine - the buffer doesn't overflow.  However in the Rocketeer, the buffer steadily get more full until it maxes out. Growing the buffer also doesn't work.. the callback rate is running almost 20% faster than the mixer and SDL is able to drain the buffer, so it's a bit of a runaway train.

I also don't think the issue is in the new threaded code; I just think its helped reveal some aspect of the timers (and book-keeping around them?) that isn't being accounted for correctly.  0.81.2 likely gets it "right" because the non-threaded aspect block at some point, so things that are a bit too fast (or slow) get re-baselined back to zero after some hard blocking.

I suspect if the callback timing (in the emulated DOS time-space) was performed at a rate that matched up with the host's real wall clock, that the buffer would (and should) be maintained at a balanced level.

I did some poking around but haven't found the root cause.

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Setup the game w/ VGA and Sound Blaster effects (music device optional).
2. Default conf should be OK, however I added mine below just incase.
3. It takes a second or two for the audio sequences to start overflowing.

### Download URL of affected game or software

eXoDOS or https://archive.org/details/msdos_The_Rocketeer_1991

### Your configuration

```ini
[sdl]
windowresolution = 800x600

[dosbox]
startup_verbosity = quiet

[cpu]
cycles= 3000

[midi]
mididevice = mt32

[sblaster]
sbtype = sbpro2
oplmode = none

[speaker]
pcspeaker = off

[gus]
gus = off

[voodoo]
voodoo = off

[ipx]
ipx = off

[ethernet]
ne2000 = off

[dos]
xms = off
ems = off
umb = off

[joystick]
joysticktype = disabled

[autoexec]
mount c .
c:
rocket.exe
```

### Provide a Log

```text
Logs only show normal output, no warnings or errors.
```

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by weirddan455** [comment]
>  I suspect if the callback timing (in the emulated DOS time-space) was performed at a rate that matched up with the host's real wall clock, that the buffer would (and should) be maintained at a balanced level.

This PIC callback runs at exactly the same rate of once per emulated ms in the old single-threaded code as it does in the new threaded code.

I just had a bug where it would request too many frames.  Fortunately, the fix is a one-liner that I'm about to a PR in for.

**Comment by interloper98** [comment]
@weirddan455, thanks for the explanation of what was happening. I've fixed the title wording.
