### ISSUE TITLE
DWM window manager support

### ISSUE THREAD

**Issue by Kibiraz** [dosbox-staging/dosbox-staging#3916]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Different version than latest?

0.82.0-alpha

### What Operating System are you using?

Linux x86_64

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

I have installed dosbox-stagging with all dependencies. When trying to launch dosbox via CLI I get following error (see screenshot). I use DWM window manager and st terminal.
 
SDL version 2.30.7 I also tried using 2.30.6 (same problem)
libiir version 1.9.3, I also tried using 1.9.5, got other error something about _ZN3Iir7cascadeC2Ev.

![IMG_0068](https://github.com/user-attachments/assets/6e9de25e-fca3-479b-9245-42d05bbfa403)

### Steps to reproduce the behaviour.

Explain how to reproduce
1. 
2.
3.

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by johnnovak** [comment]
Default config?

**Comment by Kibiraz** [comment]
Thanks for fast response. I got this error with default config. After this I was playing with the various mouse settings. Did not help.
Just now I recompiled and installed dosbox-staging once again. So I should have the default settings, still I get same error.

**Comment by Kibiraz** [comment]
I set option use_xinput2 to false. Is it possible to disable manymouse support? Maybe this is causing the problem?

**Comment by FeralChild64** [comment]
It’s unlikely to be caused by ManyMouse - I rather suspect the window manager, it seems you are using a rather exotic one. Does the problem reproduce also with 0.81.2? Or with our the pre-built binary?

We might need to handle failed `SDL_SetRelativeMouseMode` call, the current version of the documentation claims it returns -1 if the mode is not supported - https://wiki.libsdl.org/SDL2/SDL_SetRelativeMouseMode

**Comment by Kibiraz** [comment]
I tried now with pre-build version 0.81.2. The same bug. Also got some CONFIG: invalid options this time.
![IMG_0069](https://github.com/user-attachments/assets/cf9a8f1a-8bbb-4c15-8177-b79f0fb498b3)

**Comment by FeralChild64** [comment]
These „invalid option” are normal - new version has config option the old one does nog know about.

For now I can only suggest to try some other window manager.

**Comment by Kibiraz** [comment]
Clear, thank you for fast responces. With new version of dosbox-stagging will give you update :)

**Comment by interloper98** [comment]
@Kibiraz , do you have a non-root account you can try from, such as your normal desktop user account?

**Comment by weirddan455** [comment]
In your log it states

```
SDL: Version 2.30.7 initialized (offscreen video and alsa audio)
```

This is very likely the problem.  You probably want SDL's X11 video driver and I'm not sure what the use-case of the offscreen driver is.  You can try forcing it with an environment variable and see if that helps.

```
SDL_VIDEODRIVER=x11 dosbox
```

I took a quick look at SDL's source code and `SDL_SetRelativeMouseMode` should never fail with the X11 driver.  This is the only branch that leads to an error and it only happens if the SDL driver does not implement `WarpMouse` which X11 always does.

```c
/* Fall back to warp mode if native relative mode failed */
if (!mouse->WarpMouse) {
    return SDL_SetError("No relative mode implementation available");
}
```

**Comment by johnnovak** [comment]
@interloper98 @weirddan455 Given the fragmented wild-west nature of Linux windows managers, compositors and whatnot, we should probably document what desktop environments we assume / test on Linux.

What do you guys think? This is related the "no desktop" ticket on RPi from the other day. We could list a few brief notes on the Linux downloads page, e.g., X11 or Wayland is required.

**Comment by weirddan455** [comment]
I don't think it's anything specific to DWM.  DWM runs on top of X11 and should use the same SDL video driver as any other window manager (unless you're running Wayland).

If setting `SDL_VIDEODRIVER=x11` doesn't work, @Kibiraz probably has a configuration issue.  Maybe some X11 environment variables aren't set so SDL can't detect the X server.  Maybe something  needs to be done in `.xinitrc`.  He didn't share what distro or login manager (if any) he's running so I'm only guessing.

I suspect he would be having this issue with any SDL application since I'm guessing offscreen rendering isn't what he's trying to do.

**Comment by interloper98** [comment]
> Given the fragmented wild-west nature of Linux windows managers, compositors and whatnot

![1725471000975](https://github.com/user-attachments/assets/148cd210-0f08-4962-810f-fa1b1f84c7dd)

> we should probably document what desktop environments we assume / test on Linux. What do you guys think? 

Definitely agree; the dev team uses desktops that get work done!

In theory so long as the user has an output supported by SDL (x11, Wayland, or ksmdrm) then it should work -- but there's only so much we can test and help with. Definitely agree that listing the desktops we're using would at least set a known-good baseline.

**Comment by FeralChild64** [comment]
That might be risky - the desktops we are testing change constantly. I used to test mainly on KDE 5.x on X11, sometimes I was switching to Wayland. Now I test on KDE 6.x on Wayland, sometimes I switch to X11. Few months ago I was playing with Hyprland (another crazy desktop) and it worked - but now I have uninstalled it and removed the configuration (it was too much effort for me, too many things to remember) and I don’t test it anymore.

Besides, it works on my machine with Intel Arc GPU and non-VRR monitor - but whether it works equally well on nVidia hardware, I have no idea (I remember what gesture has Linus Torvalds shown to them, and also why I stopped using their cards..). Also, I can’t tell if VRR works correctly, as my display is limited to 60 Hz. I’m also not even familiar with the frame pacing options in [sdl] section (or was it [renderer], I don’t remember now), so it would be hard for me to test them.

**Comment by grapeli** [comment]
https://github.com/libsdl-org/SDL/tree/SDL2/src/video/offscreen

The SDL `offscreen` video driver is in use. An improved version of dummy. Used only for specific purposes,it does not output to the screen.

**Comment by johnnovak** [comment]
> That might be risky - the desktops we are testing change constantly.

How wonderful.

> I used to test mainly on KDE 5.x on X11, sometimes I was switching to Wayland. Now I test on KDE 6.x on Wayland, sometimes I switch to X11. Few months ago I was playing with Hyprland (another crazy desktop) and it worked - but now I have uninstalled it and removed the configuration (it was too much effort for me, too many things to remember) and I don’t test it anymore.
> 
> Besides, it works on my machine with Intel Arc GPU and non-VRR monitor - but whether it works equally well on nVidia hardware, I have no idea (I remember what gesture has Linus Torvalds shown to them, and also why I stopped using their cards..). Also, I can’t tell if VRR works correctly, as my display is limited to 60 Hz. I’m also not even familiar with the frame pacing options in [sdl] section (or was it [renderer], I don’t remember now), so it would be hard for me to test them.

Sounds like the usual Linux desktop dumpster fire 😎

**Comment by johnnovak** [comment]
> Definitely agree; the dev team uses desktops that get work done!
> 
> In theory so long as the user has an output supported by SDL (x11, Wayland, or ksmdrm) then it should work -- but there's only so much we can test and help with. Definitely agree that listing the desktops we're using would at least set a known-good baseline.

Yeah, fuck all the contrarian hipster shit 😎 We should only officially support and test common Linux desktops that normal people use (KDE or Gnome on X or Wayland or somethin), then the 0.1% people on esoteric window managers can maintain their forks with their custom patches or whatever. I guesz for them that should be part of the fun anyway... I guess 😅

**Comment by FeralChild64** [comment]
> Sounds like the usual Linux desktop dumpster fire 

Why? You want the best Windows experience, you stick to nVidia and avoid Intel.
You want the best Linux experience, you stick to AMD or Intel and you avoid nVidia.
Not sure how do you upgrade the GPU on a Mac nowadays, maybe with a soldering iron :P

You use KDE, GNOME, Ubuntu desktop, or Raspberry Pi desktop - just about everything works. You use a niche tiling window manager or a desktopless environments, you are getting surprises.
You use a stock Windows 11 - all the apps work. You use some unofficial privacy-enhancements, you sometimes end up with DOSBox Staging not compiling.

All the OSes are the same here, just the details differ.

**Comment by Kibiraz** [comment]
I want to thank you all, and especially weirddan455, for pointing me in the right direction. The problem was not with dwm or DOSBox but with SDL2 itself. Indeed, it could not initialize X11. At first, I couldn’t understand what the problem was, but it appeared that when you compile SDL2, you explicitly need to enable X11 support. So after recompiling SDL2, this time with ./configure --enable-video-x11 and --enable-x11-shared, it worked! The case is solved and closed. By the way, thanks for developing and supporting this great product.

![IMG_0071](https://github.com/user-attachments/assets/17330cba-f5c5-4ab0-8bcc-b06ef1dd244d)
