### ISSUE TITLE
Corrupted installation screen in Druid: Daemons of the Mind with latest 0.82.0 release candidate

### ISSUE THREAD

**Issue by KainXVIII** [dosbox-staging/dosbox-staging#3917]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Different version than latest?

0.82.0-rc1 (9d55e)

### What Operating System are you using?

Windows 10

### Relevant hardware info

i5-3570, GTX 970

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Druids - Daemons of the Mind has corrupted installation program screen in dosbox 0.82.0-rc1 (9d55e) (all is fine in version 0.81.2)
rc1
![image0002](https://github.com/user-attachments/assets/7ac7fdd0-30e5-47c5-b0b5-d4986afe816f)

0.81.2
![image0001](https://github.com/user-attachments/assets/fd8a4b8b-0f37-4f46-b863-6df9dc27df4b)

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Run install.bat from game cd.
2.
3.

### Your configuration

```ini
default config
```

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by johnnovak** [comment]
Thanks @KainXVIII

**Comment by interloper98** [comment]
Bistected to be3d059469a867623026e6f180a779c547493a64

**Comment by johnnovak** [comment]
> Bistected to [be3d059](https://github.com/dosbox-staging/dosbox-staging/commit/be3d059469a867623026e6f180a779c547493a64)

Loading the font based on the clocking mode register was a reasonable guess on my part. I still think that's generally the correct thing to do, but probably the font switching criteria is a bit more nuanced. Hopefully the VGA programming book holds all the answers 🤞🏻
