### ISSUE TITLE
Batch files - echo" command generates an error

### ISSUE THREAD

**Issue by distantvale** [dosbox-staging/dosbox-staging#3921]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### What Operating System are you using?

Windows 11

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

echo" command results in "Illegal command" error, while on DOS (tested under Win98), it outputs an empty line

### Steps to reproduce the behaviour.

Explain how to reproduce
Simply type echo" in command prompt and observe the issue.

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by interloper98** [comment]
Checked SVN:

![dosbox-svn-echo-quote](https://github.com/user-attachments/assets/46e314aa-ac6c-4802-8db0-bcf2ddfea8f4)

> added regression DOS and removed bug

@johnnovak , was there a time when Staging had this working and I guess we've recently regressed again? (just trying to find the 'good' point where I can start bisecting).
