### ISSUE TITLE
Consider adding `cputype=*slow` due to tight (slow) page privilege checks

### ISSUE THREAD

**Issue by Grounded0** [dosbox-staging/dosbox-staging#3938]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Different version than latest?

0.82.0 RC1

### What Operating System are you using?

macOS (Intel)

### If Other OS, please describe

macOS 12.6.5

### Is your feature request related to a problem? Please describe.

When using `cputype=pentium_mmx` games like SkyNET (1996) and X-COM: Apocalypse (1997) have horrible performance decline against `cputype=auto` due to tight page privilege checks.

In SkyNET (1996) its overall significant FPS drop and in X-COM: Apocalypse (1997) this happens every time in combat when there's explosions (there's a lot of explosions in this game) with the game almost feeling like locking up as tight page privilege checks are done.

### Describe the solution you'd like

We probably need more granularity for the users here. My suggestion:

Loose page privilege checks:

pentium_mmx
pentium
auto
386
386_prefetch

Tight page privilege checks:

pentium_mmx_slow
pentium_slow
486_slow
386_slow

Tight page privilege checks are required by some Windows 3.x games so we can't just chop them off.

Largely matches with DOSBox-X behaviour:

https://dosbox-x.com/wiki/Guide%3ACPU-settings-in-DOSBox%E2%80%90X#_differences_in_emulated_cpu_types

### Describe alternatives you've considered

Just sticking with `auto` but I want my CPU feature level dialled to the max by default. Now I'm doing per-game batch file drops back to `auto`.

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by johnnovak** [comment]
@Grounded0 You seem not to be up to speed with our recent `cpu_type` refactorings. TL;DR for you:

- We got rid of the confusing `*_slow` suffixes in the namings.
- Every CPU type does the privilege checks, except for `386_fast` (maybe we should get rid of `386_fast` too, but we left it for now; not sure if it will get any use by anybody).

`config -h cputype` for more details.

I don't see this change happening, there's not much point to complicating life like this.

> Just sticking with auto but I want my CPU feature level dialled to the max by default.

That's pointless. A handful of demos and less than 5 games use MMX instructions... Leave `cpu_type` on `auto`, and only go higher if needed. Most definitely don't use `cputype = pentium_mmx` by default, there's no reason for paying the performance penalty for 99.999% titles all the time for those less than 10 games + demos that need (or can use) MMX...

**Comment by Grounded0** [comment]
> Every CPU type does the privilege checks, except for 386_fast (maybe we should get rid of 386_fast too, but we left it for now; not sure if it will get any use by anybody).

Granularity is between loose and tight page privilege checks here.

**Comment by Grounded0** [comment]
Protected Mode Software Architecture by Tom Shanley (1996):

https://anttipeltola.eu/docs/tech/protected_mode_software_architecture.pdf

**Comment by johnnovak** [comment]
> > Every CPU type does the privilege checks, except for 386_fast (maybe we should get rid of 386_fast too, but we left it for now; not sure if it will get any use by anybody).
> 
> Granularity is between loose (fast) and tight (slow) page privilege checks.
> 
> I'll leave this open for discussion since I don't have the energy currently to argue my case.

Yeah OK, I get it, but it's a complication still, and for no good reason.

Like I said, MMX emulation is demanding, use it only when you really need it.

Otherwise the tight privilege checks are no problem. The "loose" checks were a performance hacks relevant in the early 2000s — we don't want to carry those.

**Comment by Grounded0** [comment]
Oh so everything except `386_fast` is now doing tight (slow) page privilege checks?

**Comment by johnnovak** [comment]
> > Otherwise the tight privilege checks are no problem. The "loose" checks were a performance hacks relevant in the early 2000s — we don't want to carry those.
> 
> Oh, so everything except `386_fast` is now doing tight (slow) page privilege checks?

Yes. That's what I said.

IMO, keeping `386_fast` was pointless because the tight checks don't add significant overhead on current(ish) hardware at 386 speeds. We might just remove it, then all CPU models have tight checks and that's the end of it.

**Comment by Grounded0** [comment]
Closing since we're already delivering tight (slow) page privilege checks without observable performance penalty.
