### ISSUE TITLE
`keyboardlayout = auto` doesn't work on Linux

### ISSUE THREAD

**Issue by Erlotinib** [dosbox-staging/dosbox-staging#394]
Hello,

not sure if it's a bug or an enhancement request.

On linux when the setting "keyboardlayout" is "auto", it doesn't detect the current layout and default to qwerty.
In https://github.com/dosbox-staging/dosbox-staging/blob/master/src/dos/dos_keyboard_layout.cpp#L1108 
the code seems to be windows only so maybe it's expected.

It would be great if dosbox could detect the current keyboard layout and configure itself accordingly.

Or maybe include a launcher which does something like that (quick & dirty example):
```
Layout = `setxkbmap -query|grep layout|cut -d" " -f6`
if [ ! -e ~/.config/dosbox/$DOSBOXCONF ] || grep -q -E 'keyboardlayout = auto' $HOME/.config/dosbox/$DOSBOXCONF ; then
	dosbox -c "config -set keyboardlayout=$Layout" -c "config -wc"
else
	dosbox
fi
```

thanks
Julien

**Comment by dreamer** [comment]
I consider it a bug. One way or another - dosbox should behave consistently across the operating systems.

**Comment by Erlotinib** [comment]
As a stopgap, here is the script we use in Mageia:

http://svnweb.mageia.org/packages/cauldron/dosbox-staging/current/SOURCES/dosbox?revision=1587129&view=markup

**Comment by rderooy** [comment]
I was thinking about this the other day. I don't think you can depend on `setxkbdmap` to be available, especially with XWayland.

But I think you should be able to check if `/etc/vconsole.conf` exists, and if so, get the default keyboard layout. This should work on most modern distros from what I gathered.

Here is what my config file looks like:
```bash
# cat /etc/vconsole.conf 
KEYMAP="us-euro"
FONT="eurlatgr"
```

You can also check the man page with `man vconsole.conf` and it shows an example for a German config:

```
KEYMAP="de-latin1"
FONT="eurlatgr"
```

So I think if you take the `KEYMAP=` value and take the first 2 characters (or split on the '-'), you should have the keyboard layout.

Obviously it is not ideal, as the user may have multiple layouts and switch between them with a desktop widget. But that is really hard to handle, and I have not found a way to get this information easily.

**Comment by rderooy** [comment]
You can see a list of available keymaps with ``localectl list-keymaps``, and there are quite a few possibilities.

```bash
# localectl list-keymaps | wc -l
565
```
I would only do the more common keyboards and let the rest default to US.

**Comment by Burrito78** [comment]
@kcgen Still an issue after all the locale improvements?

**Comment by kcgen** [comment]
Closing. Yes, keyboard layout `auto` does a best-effort inference based on the set language (or language coming from the system).
