### ISSUE TITLE
Crash when setting high `memsize` values on macOS

### ISSUE THREAD

**Issue by johnnovak** [dosbox-staging/dosbox-staging#3940]
Setting `memsize` to high values (~2500 and above) results in weird recursive exception throwing and an eventual crash, apparently only on macOS:

<img width="862" alt="image" src="https://github.com/user-attachments/assets/c4a6e85b-84a1-47ac-8c3d-88fa63e4a870">

Reproduce with the following config:

```ini
[dosbox]
memsize = 2500
```

This is a regression; values up to 3072 were working fine on 0.81.2.

Well, and very it's low priority because even server-grade Socket 5 and 7 motherboards only support up to 512 or 1024 MB of memory. More than 64 MB for DOS is rather pointless (that's the limitation of MS-DOS 6.22 via HIMEM.SYS).

I was happy with 64 MB of RAM in my first Celeron 350 Win95/98 box I bought in 1999, so... 😄 It was even fine for Windows 2000.

**Comment by FeralChild64** [comment]
Which OS? Which commit?

I have just checked the current main (b1c93b34d281812a8f9368adbc10d4e32812483c) on my Gentoo Linux. Both commands started DOSBox without any crashes:

```bash
./build/dosbox --noprimaryconf --set memsize=3072
./build/dosbox --noprimaryconf --set memsize=2500
```

**Comment by interloper98** [comment]
Could be an overflow? A possible one liner in branch [`il98/pages-per-mb`](https://github.com/dosbox-staging/dosbox-staging/tree/il98/pages-per-mb)

**Comment by johnnovak** [comment]
> Which OS?

macOS on `main`. I kinda assumed it's a general problem.
