### ISSUE TITLE
Bad Cat game - it doesn't work

### ISSUE THREAD

**Issue by SmilingSpectre** [dosbox-staging/dosbox-staging#3941]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Different version than latest?

0.81.0

### What Operating System are you using?

Windows 10

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Game Bad Cat from Total DOS Collection refuses to work at all in any DOSBox, except DOSBox-X. Tried Vanilla, ECE, Daum and Staging. Dosbox-X works, all others says "Missing startup file!"

Can you find the problem and fix this behavior of Staging?

Game archive added.

[Bad Cat (1988)(Rainbow Arts Software GmbH) [Action, Sports].zip](https://github.com/user-attachments/files/17079140/Bad.Cat.1988.Rainbow.Arts.Software.GmbH.Action.Sports.zip)

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Run the game
2. Get (or don't get) "Missing startup file!" message.

### Provide a Log

```text
Nothing suspicious logged.
```

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by interloper98** [comment]
`loadfix -1`

Soak up one KB of base memory before firing up the game.

**Comment by SmilingSpectre** [comment]
Worked. Thank you!

**Comment by MasterO2** [comment]
https://github.com/dosbox-staging/dosbox-staging/wiki/Game-issues#bad-cat now added to Game Issues page.

**Comment by johnnovak** [comment]
> https://github.com/dosbox-staging/dosbox-staging/wiki/Game-issues#bad-cat now added to Game Issues page.

Thanks @MasterO2 🎖️

**Comment by Grounded0** [comment]
Loadfix should be listed in Common issues and fixes at the top at this point.
