### ISSUE TITLE
Update website DEV build installation instructions for macOS Sequoia 15.x

### ISSUE THREAD

**Issue by Burrito78** [dosbox-staging/dosbox-staging#3949]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### What Operating System are you using?

macOS (Apple Silicon)

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Cannot open a DEV or RC version of DOSBox Staging on newest macOS version (Sequoia 15.0).
Only a dialog box with a "Move to trash" button is shown.

The website should be updated to include information how to open such apps on the newest macOS.
Apple has the necessary information here: https://support.apple.com/en-us/102445#openanyway

### Steps to reproduce the behaviour.

see above

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by johnnovak** [comment]
> Cannot open a DEV or RC version of DOSBox Staging on newest macOS version (Sequoia 15.0).

@Burrito78 
Are you sure about that? The RC builds are notarised, while the dev builds aren't. So you shoul only have to do this dance for the dev builds. The RC builds should behave exactly like the notarised final releases.

Could you confirm it please? Then I'll include that link you posted on the dev builds download page as a note for macOS.

**Comment by Burrito78** [comment]
> @Burrito78 Are you sure about that? The RC builds are notarised, while the dev builds aren't. So you should only have to do this dance for the dev builds. The RC builds should behave exactly like the notarised final releases.
> 
> Could you confirm this please? I'm still on Sonoma. Then I'll include that link you posted on the dev builds download page as a note for macOS.

I wasn't clear about the RC part, the official notarised RC builds are no problem, they work as before. But the internal RC builds are direct unnotarised GitHub downloads so they need the new method to circumvent the hardened macOS 15 security settings.

So yes, the link only is needed for the DEV download page of the website.
