### ISSUE TITLE
Regression: DIR command broken

### ISSUE THREAD

**Issue by darkstar** [dosbox-staging/dosbox-staging#395]
I think commit eadd0b0fc4163beff799340612c5b8fe20355dde broke the dir command. It now requires a path, otherwise it bails out with "Illegal Path".

See the attached screenshot
![image](https://user-images.githubusercontent.com/43795/82741573-e51dc000-9d53-11ea-89ad-da6cca4bfc66.png)

**Comment by dreamer** [comment]
@darkstar Ah, I missed this bug report.

You are right, this commit did introduce a regression… Fortunately, we found it during #390 and fixed it. This PR got merged literally a minute ago, so the problem should be now fixed on master branch :)

When you'll have a moment, please confirm it's fixed on your side as well ;)

**Comment by darkstar** [comment]
Yup, it's fixed. Thanks!
