### ISSUE TITLE
Aliasing or bit crushing in GUS mode

### ISSUE THREAD

**Issue by digistorm79** [dosbox-staging/dosbox-staging#3955]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### What Operating System are you using?

macOS (Apple Silicon)

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

When playing music on GUS sound device, the sound is distorted. It sounds like aliasing or bit crushing. You can hear this when you play the module Stranglehold by Jeroen Tel (JT_STRNG.XM, you can find it [here](https://files.scene.org/view/mirrors/hornet/music/songs/1996/j/jt_strng.zip) or [here](https://modarchive.org/index.php?request=view_by_moduleid&query=46508)). The expected behaviour is that you here all pure tones, because this song only uses pure sine waves (that is the gimmick of this song). If you listen to it on real hardware or on the latest release of your "competitors" (like DOSBox-X, 86Box or the PicoGUS) you can hear what I mean. On the code of Dosbox Staging, as far back as 0.77.1, it sounds metallic and sharp. It sounds a bit like aliasing or bit crushing. It may be possible that the very small sample is not linear interpolated, it sounds a bit like that. In fact, when you use Sound Blaster for playback and you disable interpolation, it sounds similar, but on GUS it is actually even worse.

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Download the song JT_STRNG.XM
2. Play it in any playback software, I tested Open Cubic Player and Impulse Tracker
3. Especially from the 0:46 mark it sounds particularly horrible

### Download URL of affected game or software

https://files.scene.org/view/mirrors/hornet/music/songs/1996/j/jt_strng.zip

### Your configuration

```ini
Nothing special on GUS configuration, I tried with both filter on and off, and that didn't change the sound.
```

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by johnnovak** [comment]
Yeah, I'm familiar with that Jeroen Tel tune. One of my favourites 😄 

Well, CubicPlayer is garbage, a total shit-show when it comes to accurate playback, and so is XTC-Play and most other DOS MOD and XM players... Playing XM or MOD files in Impulse Tracker is a bad idea too—that feature was never meant for _accurate_ playback, but for quickly loading your XM tune into the tracker to import the samples and the pattern data. Impulse Tracker was never meant to be an accurate XM replayer. (Same deal with MOD playback in FT2; FT2 is very far from being an accurate Amiga ProTracker MOD replayer, they even say so in the manual; it's only a handy feature for importing MOD sample and pattern data for musicians for further work and nothing else).

I've spent hundreds of hours writing XM tunes in FastTracker II in the 90s, and believe me, there is a reason why most XM musicdiscs contain a warning to _only_ use FT2 to play back XMs (the Maniacs of Noise guys, so Jeroen Tel too, warn users about this—"only use FT2 to play back our stuff, nothing else"). Virtually all "third party" replayers are broken to various degrees (XMPlay on Windows is a honorary mention that gets it _mostly_ right).

Same deal with IT files (only use Impulse Tracker) and S3M files (only use Scream Tracker). The only good 4-channel Amiga ProTracker replayer for DOS is pt4dos by 8bitbubsy (downloadable from [here](https://16-bits.org/other.php)). But trust me, no accurate MOD replayer was written in the whole 90s DOS era—all suck to various degrees. I like CapaMod, it's one of the least bad MOD replayers (it's actually pretty close on more materials), but not perfect. At least not comically wrong like CubicPlayer 😆 

With this out of the way, I've just done a WAV capture of Stranglehold when played back in FT2—sounds pretty much perfect to me (rename the ZIP to MP3—GitHub file upload limitation).

[stranglehold-ft2.zip](https://github.com/user-attachments/files/17111200/stranglehold-ft2.zip)

In fact, we might do _better_ interpolation than the real hardware there, at least when it comes to the panning modulation. I remember the panning modulation resulting in a slight zipper noise sound on my GUS Max back in the day which was not present when I listened to the tune later in XMPlay on Windows (so XMPlay must be doing a linear interpolation of the panning positions like we do, apparently).

PS: For shits and giggles, play back Stranglehold in CapaMod... Yeah, it turns the sine wave samples into a triangle/sawtooth somehow 😆

**Comment by johnnovak** [comment]
@digistorm79 Okay, I made a mistake yesterday—I rendered the WAV file in FT2 with the Sound Blaster driver 😊 

With the GUS driver, the panning position automation (LFO) of the instruments does indeed create a zipper noise effect, but as far as I remember, this is authentic, that's how my real GUS Max behaved (pan positions are not interpolated).

As for the metallic overtones, that's aliasing, yeah. The tune uses 16 tracks, and we emulate the channel number dependent sample rate degradation behaviour of the original GUS models. You only get 44.1 kHz up to 14 channels, above that it progressively gets worse:

![image](https://github.com/user-attachments/assets/8d2e520d-9a83-4c69-b3ac-c1a3de839ca6)

If you reduce the channel count to 14  in Fasttracker II, there is noticeably less aliasing.

Do note that although the PicoGUS is a cool piece of gear, it's just another emulator, so it's not the last word in authenticity and it doesn't _really_ count as hardware. If you created a recording from a _real_ GUS—then we'd be talking 😄 

See the PicoGUS's GUS code here—it's just high-level emulation code, like ours 🤷🏻 They don't accurately emulate the actual GF1 processor on the GUS.
https://github.com/polpo/picogus/blob/main/sw/gus-x.cpp

From [UltraSound Lowlevel ToolKit v2.22 (21 December 1994)](https://www.infania.net/misc1/GUS/SOURCE%20CODE/UltraSound%20Lowlevel%20ToolKit%20v2.22%20(21%20December%201994).pdf) on the varying sample rate behaviour of the GF1 chip (the later AMD Interwave models did away with this, but to me those are not real Ultrasounds; many demos aren't even compatible with the later Interwave chips).

To me from all this follows that the aliasing _is_ authentic and just how a real GF1 chip behaves (now, I'm not saying we're generating the exact same bit-identical aliasing, but it's sure as hell the real GF1 is not aliasing free at higher channel counts).

---

![image](https://github.com/user-attachments/assets/e6e4bbe3-45ac-4256-8b14-933090bec76c)

**Comment by Grounded0** [comment]
I argued before for an option for switching between Gravis GF1 or AMD InterWave behaviour. Looks like johnnovak is even more opposed to adding it than kcgen so I'll leave it at that.

**Comment by johnnovak** [comment]
> I argued before for an option for switching between Gravis GF1 and AMD InterWave behaviour. Looks like johnnovak is even more opposed to adding it than kcgen so I'll leave it at that. If someone delivers an oven-ready PR for it we probably wouldn't reject it as its a genuine hardware target.

Yeah, DOS era GUS -> GF1.

People have been having all sorts of weird compatibility issues with the AMD Interwave chips on GUS, and it does sound different (some think "better"; I just think different and with less character than the original GUS).

We could easily introduce a "gus_model" conf setting or something, but that would only change the dynamic sample rate degradation behaviour as the channel rate goes up.

We're doing high level emulation, making GUS work in as many titles as possible, which is technically closer to the GF1 than to the Interwave. If we _really_ wanted to do "accurate" Interwave emulation, that would mean 30-50% of the demos wouldn't work in with `gus_mode = interwave` (if we'd be chasing hardware accuracy).

So I think I'm leaning towards dropping this Interwave emulation idea and just introduce perhaps a `gus_high_quality = on` setting or something that does "improved sound emulation" similar to the Interwave (but that's inauthentic when compared to a real GF1).

Hope that makes sense.

**Comment by Grounded0** [comment]
Yeah, just chopping off the sample rate drop with over 14 channels and call it for the day. That's good enough for AMD InterWave without all the downsides of the real cards.

**Comment by digistorm79** [comment]
Again, thanks for clarifying all this for me. As a note on the PicoGUS: by default, it actually does decrease the mixing rate to reduce the strain on the already overclocked RP2040 chip (but there is an option to override it) and the DAC is also changed to use those different mixing rates. But I guess a modern DAC does a much better job than perhaps the original one on the GF1 based card.
I also agree that (at least by default) the emulation of the GUS in Dosbox-Staging should stay as it is, because the "distortion" contributes to the sound. Just like you should not interpolate or smooth the output of the Paula chip of an Amiga for example. I do remember that the Interwave made some demos sound more "dull" back in the day when I got it, but I didn't know why.

**Comment by johnnovak** [comment]
> Again, thanks for clarifying all this for me.

No problem, man 😎 

> As a note on the PicoGUS: by default, it actually does decrease the mixing rate to reduce the strain on the already overclocked RP2040 chip (but there is an option to override it) and the DAC is also changed to use those different mixing rates. But I guess a modern DAC does a much better job than perhaps the original one on the GF1 based card.

Oh yeah, that's certain!

> I also agree that (at least by default) the emulation of the GUS in Dosbox-Staging should stay as it is, because the "distortion" contributes to the sound. Just like you should not interpolate or smooth the output of the Paula chip of an Amiga for example.

Yeah, definitely; Amiga emulators just sound wrong without accurate Paula emulation (an, by extension, all MOD players that don't emulate the Paula when playing back 4-channel ProTracker MOD files). Luckily, WinUAE has a very authentic sounding Paula emulation (and 8bitbubsy's ProTracker clone uses the same algorithm).

> I do remember that the Interwave made some demos sound more "dull" back in the day when I got it, but I didn't know why.

Well, glad that I managed to help understand that mystery then 😆

**Comment by Grounded0** [comment]
Good that this was resolved. We probably may have to introduce AMD InterWave behaviour later since everyone who has or had GUS PnP card will think we're doing something wrong here.

I'll expect this to come up again and again until that is a selectable option in the .conf.

**Comment by Grounded0** [comment]
- #3959
