### ISSUE TITLE
Fasttracker II crashes with `gusdma = 7`

### ISSUE THREAD

**Issue by digistorm79** [dosbox-staging/dosbox-staging#3957]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### What Operating System are you using?

macOS (Apple Silicon)

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Fast Tracker II crashes consistently as soon as Ultrasound is chosen as output device. If it was already chosen (because the files came from a real system or were used in a different emulator) it will crash on launch.
I tried Fast Tracker II version 2.08 (latest official) as well as the unofficial updates by 8bitbubsy. They all act in the same way. Of course I checked the same files in another emulator (DOSBox-X) and they are an exact copy of my real system, where it also works as expected.

Because I was just kindly instructed to use Fast Tracker II to play XM files by one of the developers, I wonder if this crash is specific to the Apple Silicon or macOS build.

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Download the latest official version of Fast Tracker II [here](https://files.scene.org/view/resources/music/trackers/ft208.zip), or the latest unofficial version [here](https://16-bits.org/etc/FT213.ZIP)
2. Start the program (FT2.EXE)
3. It is possible the program is configured for Sound Blaster or "None" out of the box. Click on the Config button and chose Ultrasound.
4. It crashes.

### Your configuration

```ini
https://gist.github.com/digistorm79/3841c9fe01b44a97a6b9f17d61691df3
```

### Provide a Log

```text
https://gist.github.com/digistorm79/5fcd805839b6cf88db634aab1a714031
```

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by Grounded0** [comment]
The best way to check is it ARM64 specific issue is by opening up the x86-64 binary in Rosetta since we ship Universal Binary unlike the others:

![344833130-85b293ee-eca5-40eb-b400-7599b3389d67](https://github.com/user-attachments/assets/d25e6fb6-ad14-4736-ad34-76ad6aa70046)

**Comment by digistorm79** [comment]
Thanks for your response. I am in fact running the release candidate for some time, but I also tested the release versions before making a new issue.
I have just tried running it with the Intel binary (verified it in Activity Monitor) but it still crashes as soon as I click Ultrasound as output device or when it is already configured for Ultrasound, as soon as it tries to initialise it.
I also tried with the provided starter pack (great idea by the way) but that did not change anything.
I *am* assuming that other people with Apple Silicon can run it just fine? I think I provided my full configuration with the gist method, so if I have for some reason done something stupid there, you should be able to find it out. I don't know what else could be wrong, because Fast Tracker just runs by itself, it needs nothing.

**Comment by interloper98** [comment]
@digistorm79 , have you tried the latest `main` branch?

I just tried it on my aarch64 system (Raspberry Pi 4) Linux, and it's able to bring up FT208 and 213 with GUS:

FT208 - 

![ft208-aarch64](https://github.com/user-attachments/assets/cbd4fe2c-a9a2-44c4-aad6-06f230845db7)

FT213 - 

![ft213-aarch64](https://github.com/user-attachments/assets/60088ba2-f09a-4232-bdfc-b35e8bf7965e)

And here's my config (nothing special, just disabling a bunch of unecessary features and enabling GUS with default settings):

```ini
[mouse]
dos_mouse_immediate = on
ps2_mouse_model =  standard

[cpu]
core = dynamic
cycles = 30000

[sblaster]
sbtype = none

[midi]
mididevice = none

[gus]
gus = true

[speaker]
pcspeaker = none
lpt_dac = none

[voodoo]
voodoo = off

[ipx]
ipx = off

[ethernet]
ne2000 = off

[dosbox]
startup_verbosity = quiet

[joystick]
joysticktype = disabled

[autoexec]
@echo off
mount c .
c:
ft208.exe
```

**Comment by Grounded0** [comment]
Knowing how people absolutely depend on Scream Tracker, FastTracker 2 and Impulse Tracker just for authentic playback of .S3M, .XM and .IT files people would be absolutely mad if we screwed them up.

**Comment by johnnovak** [comment]
This is not a Mac M1 issue, but a regression from SVN. The regression is present at least since 0.77.1.

The problem is triggered by setting `gusdma = 7` (as per @digistorm79's config). 

With `gusdma = 7`, different FT2 versions behave as follows:

- 2.06 crashes right away (apparently auto-detects the GUS then tries to use it)
- 2.09a starts fine, then the crash happens when manually switching to the GUS in the config screen
- 2.12 (by 8bitbubsy), crash happens when manually switching to the GUS

All other `gusdma` settings work fine in all FT2 versions, and as mentioned, FT2 works fine with `gusdma = 7` in SVN. 

The curious thing is that at least the demo [Inside by CNCD](https://www.pouet.net/prod.php?which=74) works fine with `gusdma = 7` (make sure to configure it in `SETUP.EXE`).

<img width="1840" alt="image" src="https://github.com/user-attachments/assets/38ceff38-a812-4bb6-baa5-196cdeeebbd2">

**Comment by digistorm79** [comment]
Thanks for clarifying this guys. I was using dma=7 for a long time and *assumed* that there are quite a lot of programs that use dma so I never suspected a problem there. It would be great if the bug could be fixed (just because I like to synchronise the drives of Dosbox and my real retro machine) but this resolves a lot of mysteries for me.
