### ISSUE TITLE
Demo scene 64k intro "Mindflow" has playback problems with GUS emulation

### ISSUE THREAD

**Issue by digistorm79** [dosbox-staging/dosbox-staging#3958]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### What Operating System are you using?

macOS (Apple Silicon)

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Something goes wrong with the music playback of the 64k intro "Mindflow".
It only supports GUS as music device. The song uses only sine waves, but unlike real hardware, in Dosbox-Staging there is a metallic distortion, almost as if the sine waves are distorted into triangles. I have listened to this song countless times in all manners of ways, this 64k intro, Fast Tracker II, Cubic Player, modern players on Windows and macOS, you name it. I have never heard a distortion like this. I also cannot reproduce the specific distortion in this specific 64k intro on real hardware. The only other emulator I can run on this Apple Silicon that does the same is 86box.

To clarify, I do not mean the insane clicking that can be heard. That is a problem of the song. I mean the metallic, aliasing like distortion. I create music using synthesizers myself, and this sounds to my ears almost as if the sines get distorted into triangles. But I am not sure and I cannot isolate one voice from this executable.

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Download Mindflow [here](https://files.scene.org/view/mirrors/hornet/demos/1998/m/mindflow.zip).
2. Run the executable. It needs GUS emulation to be on. Type 1 to chose GUS for music playback
3. The tones you hear are (slightly) different then "the real thing".

### Download URL of affected game or software

https://files.scene.org/view/mirrors/hornet/demos/1998/m/mindflow.zip

### Your configuration

```ini
gus        = true
gusbase    = 240
gusirq     = 7
gusdma     = 7
gus_filter = off
ultradir   = C:\DRIVERS\ULTRASND

# I tried with filter on and off...
```

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by interloper98** [comment]
@digistorm79,

I'm just a general user/listening, and not a tracker guru like you and @johnnovak.

But I tried my best to strip away most of Staging's mixer features. Here's a side-by-side, both are roughly -29 dB:

DOSBox Staging (main branch):

https://github.com/user-attachments/assets/0d7c46ba-e31c-4e3d-80b7-f4137a6caf7b

DOSBox SVN (latest):

https://github.com/user-attachments/assets/fb9ea161-aed7-4871-a37a-764423936a09

They at least sound very similar to me (so much so that I couldn't tell them apart with my eyes closed).

Are you hearing problems in the Staging recording?

Here's what I did in Staging, just for the record):
1. Avoid all filtering (commented out the universal highpass filter in the mixer code, set all filters to off in the conf)
2. Avoid resampling (Set the Speex resampler quality to 10, and then tried to avoid the resampler setting `[mixer] rate = 38587` to match Mindflow's GUS channel rate)
3. Avoid volume level adjustments (disabled the compressor in the conf, set the mixer volume level 63 in Staging) 

Here's the conf:

```ini
[dosbox]
machine = svga_s3
memsize = 32

[cpu]
core = dynamic
cpu_cycles_protected = 500000
cpu_throttle = true

[sblaster]
sbtype = none

[midi]
mpu401 = off
mididevice = none

[mixer]
compressor = off
rate = 38587
reverb = off
chorus = off

[gus]
gus = on
gusdma = 3
gusbase = 240
gusirq = 5
gus_filter = off

[speaker]
pcspeaker = none

[dos]
xms = true
ems = false
umb = false

[autoexec]
@echo off
mount c . > NUL
c:
mixer gus 63
mindflow /1 /240
```

**Comment by johnnovak** [comment]
@digistorm79 This sounds as it should—that aliasing and "zipper noise" when rapidly changing panning positions is part of the sound of the original GUS Classic and Max boards that use the GF1 chip. See [this comment of mine](https://github.com/dosbox-staging/dosbox-staging/issues/3955#issuecomment-2372633299) for further details.

> The song uses only sine waves, but **unlike real hardware**, in Dosbox-Staging there is a metallic distortion, almost as if the sine waves are distorted into triangles.

> I have listened to this song countless times in all manners of ways, this 64k intro, Fast Tracker II, Cubic Player, modern players on Windows and macOS, you name it. I have never heard a distortion like this. I also cannot reproduce the specific distortion in this specific 64k intro **on real hardware**.

As explained in my linked comment, if you're using the PicoGUS, that's just another emulator so I don't consider those results "real hardware" results (we'd need a real GUS Classic or Max equipped with the GF1 chip for that).

Having said that, I'm not getting the triangle wave-like distorion with this demo, only if I play back the tune in CapaMod. Maybe create a recording and upload it here?

**Comment by digistorm79** [comment]
I'm sorry, I don't have a real GF1 GUS, only a GUS pnp. It was very very long ago that I heard this demo from a GF1 chip, and I would never have thought that they would mess up like this. The Interwave is a very different chip of course, so it is more or less in the same category as the PicoGUS.
I am not worried about the zipper noise, because I understand why it happens (I did my graduation thesis on programming a synthesizer engine on a DSP a long time ago) and even the Interwave sounds like that so it is authentic. I just really did not expect that the GF1 would have that aliasing effect like Dosbox.
I apologise for the created confusion, but I'm glad I learned something from all of this.

**Comment by johnnovak** [comment]
> it was very very long ago that I heard this demo from a GF1 chip, and I would never have thought that they would mess up like this.

Well, I'd say it's part of the GF1's character 😄 

> I apologise for the created confusion, but I'm glad I learned something from all of this.

No prob, I think we've all learned something 😄

**Comment by Grounded0** [comment]
- #3959
