### ISSUE TITLE
Non ascii filenames aren't readable/executable

### ISSUE THREAD

**Issue by distantvale** [dosbox-staging/dosbox-staging#3961]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### What Operating System are you using?

Windows 11

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Non ascii file names cannot be referenced in DOS command line.
These files can't be typed or executed.

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Extract the attached zip into a mounted folder
2. Run the executable
3. Notice the program fails to run as it can't find FφRCETEN.EXE, even though it's in the same dir

Alternatively, try to type any file with non ascii char in its name.

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by distantvale** [comment]
[F10_PCK1.ZIP](https://github.com/user-attachments/files/17151809/F10_PCK1.ZIP)

**Comment by FeralChild64** [comment]
This is a known missing feature: https://github.com/dosbox-staging/dosbox-staging/issues/2619

**Comment by distantvale** [comment]
sorry, didn't realize it's the same issue, closing this one.
