### ISSUE TITLE
Default values in dosbox.conf not set according to 0.82-RC documentation

### ISSUE THREAD

**Issue by rcblanke** [dosbox-staging/dosbox-staging#3962]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Different version than latest?

0.82.0-RC

### What Operating System are you using?

Windows 11

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

When creating a new dosbox.conf (containing defaults) there are some mismatches to the documentation. Specifically:

[speaker] pcspeaker should be impulse (according to docs), but gets set to discrete
[cpu] cpu_cycles should be 3000, but gets set to empty string
[cpu] cpu_cycles_protected should be 60000, but gets set to empty string

### Steps to reproduce the behaviour.

Explain how to reproduce
1. config -wc dosbox.conf
2.
3.

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by FeralChild64** [comment]
I think we should reconsider whether putting the default value in the config item description is really a good idea - this information tends to get invalid over time, and within translations it is probably even worse.

**Comment by johnnovak** [comment]
This is a user error. @rcblanke Please follow the [config upgrade steps](https://www.dosbox-staging.org/releases/release-notes/0.82.0-rc/#upgrading-your-primary-configuration) from the release notes carefully—it's all described in detail here. 

You must be still using your old config, that's the only explanation.

To be 100% sure, I've just regenerated the default config by starting DOSBox with `--noprimaryconf` then issuing `config -wc defaults.conf`, and as you can see below, the defaults are all correct.

@FeralChild64 Listing the defaults in the descriptions is useful, so it will stay. Values getting out of sync can be greatly mitigated by fprintf'ing the values into the English string in the code (which we started doing), but I personally never found keeping them in sync difficult, and this has never proven to be a big problem. Also, defaults change rarely, so I consider this almost a non-issue.

Keeping the translations in sync is harder, but that's a hard job in general. I'd say this is maybe 5-10% of the total difficulty.

---

Proof:

### pcspeaker

<img width="899" alt="image" src="https://github.com/user-attachments/assets/7a5fc5c6-798b-451e-aebe-3863fddf3f9b">

<img width="265" alt="image" src="https://github.com/user-attachments/assets/301bcfb6-8455-4922-b355-29ccc2e79553">

### cpu_cycles & cpu_cycles_protected

<img width="930" alt="image" src="https://github.com/user-attachments/assets/59099e0e-48c5-4fd0-8ba6-6301a4f58ef6">

<img width="909" alt="image" src="https://github.com/user-attachments/assets/1a622edf-6242-4719-a1c1-06e178938723">

<img width="285" alt="image" src="https://github.com/user-attachments/assets/80a819fd-b156-4433-a9b7-820d7b7886da">

**Comment by johnnovak** [comment]
Okay, I've just checked the config upgrade instructions in the release notes, and I wrote this:

> Start by backing up your existing primary config.

That implies (to me) backing up and also _removing_ the existing primary config (because later I'm talking about Staging writing a brand new primary config when you start the new version for the first time). But, arguably, it can be easily interpreted as "back up the primary config, so make a copy, but otherwise leave the existing primary config there".

I'll clarify this in the instructions and spell out the primary config must be deleted before starting the new version, so thanks for raising this @rcblanke 👍🏻

**Comment by rcblanke** [comment]
Ah, thanks for the feedback, people! Indeed, using -noprimaryconf fixed my configuration, makes sense, thank you!

Regards,
Ronald
