### ISSUE TITLE
Loguru abort/SDL Problem while building OpenWatcom v2 from source when using Dosbox-Staging instead of vanilla Dosbox

### ISSUE THREAD

**Issue by LowLevelMahn** [dosbox-staging/dosbox-staging#3984]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Different version than latest?

0.82.0-alpha (git)

### What Operating System are you using?

Other

### If Other OS, please describe

Linux or Windows

### Relevant hardware info

Standard desktop

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### **FOUND IT !!!**
the open watcom build does `set SDL_VIDEODRIVER=dummy` before calling dosbox

when building Open Watcom v2 from source a DOS exe (source was never release when open sourcing open watcom) is needed for building the documentation - dosbox gets used for that but abort in between building inside loguru (Windows/VS2022) or while initalizing SDL (Fedora and WSL/Tumbleweed)

it this error:
`SDL: Could not initialize video: OpenGL support is either not configured in SDL or not available in current SDL video driver (dummy) or platform
`

i think the Open Watcom build uses dosbox without opening a window or something - maybe > /dev/null redirect

the open-watcom-v2\dosbox.cfg that is used while build

```
[cpu]
core=auto
[mixer]
nosound=true
[midi]
mpu401=none
mididevice=none
[sblaster]
sbtype=none
[gus]
gus=false
[speaker]
pcspeaker=false
[joystick]
joysticktype=none
[serial]
serial1=disabled
serial2=disabled
serial3=disabled
serial4=disabled
[ipx]
ipx=false
[dosbox]
#memsize=64

```

Windows:
![image](https://github.com/user-attachments/assets/627b3a42-b025-416a-9c99-ca0707d4758b)

Linux (Tumbleweed under WSL):
![image](https://github.com/user-attachments/assets/26fa0efb-86d3-4ec7-b771-427d0a5f371f)

Linux: Fedora
![image](https://github.com/user-attachments/assets/09da09d7-e79a-490b-938d-f69a20c9fefb)

vanilla dosbox on Windows/Linux works

### Steps to reproduce the behaviour.

i tried to reproduce the problem more localy without building Open Watcom but it seems to be something with the make environment of Open Watcom v2

reproduce under Windows/VS2022
my system: VS2022 community (17.11.5 from 09/10/2024) on Windows 10

run `"C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build\vcvars64.bat"` in console or
start "x64 Native Tools Command Prompt for VS 2022" from Windows menu

(assuming we are on D:\temp)
1. `mkdir my_ow_build`
2. `cd ow_build`
3. `git clone https://github.com/open-watcom/open-watcom-v2.git`
4. copy open-watcom-v2\setvars.bat to my_setvars.bat
5. change in my_setvars.bat
*`set OWROOT=D:\temp\my_ow_build\open-watcom-v2` 
*`set OWDOSBOX=D:\temp\my_dosbox\vs\x64\Debug\dosbox`
6. `my_setvars.bat`

without building open watcom complete

- `build.bat preboot`

reproduce call to DOSBOX by

- `cd docs\ps`
- `wmake hbook=c_readme`

if need repeat then cleanup docs/ps by

- `wmake clean`

reproduce under Linux

Step by step setup and build instructions for Linux
-----------------

install needed packages on **Fedora** (tested with Fedora 40 - should work exactly like this on older versions)

1. `sudo dnf update`
2. `sudo dnf groupinstall "Development Tools"`
3. `sudo dnf install git`
4. `sudo dnf install glibc-static`
5. `sudo dnf install libstdc++-static`

install needed packages on **Ubuntu** (tested with Ubuntu 24.10 - should work exactly like this on older versions)

1. `sudo apt update`
2. `sudo apt install build-essential`
3. `sudo apt install g++`
4. `sudo apt install git`

**building OpenWatcom v2**

1. `cd ~/`
2. `mkdir my_ow_build`
3. `cd my_ow_build`
4. `git clone https://github.com/open-watcom/open-watcom-v2.git`
5. `cp open-watcom-v2/setvars.sh my_setvars.sh`
open `my_setvars.sh` in editor and change:
* `OWROOT` to the absolute path of `my_ow_build/open-watcom-v2`
example: `export OWROOT=/home/test/my_ow_build/open-watcom-v2`
* `OWDOSBOX` path to your dosbox-staging
6. `. ./my_setvars.sh` - the point in front is needed to keep the environment

without building open watcom complete

- `./build.sh preboot`

reproduce call to DOSBOX by

- `cd docs/ps`
- `wmake hbook=c_readme`

if need repeat then cleanup docs/ps by

- `wmake clean`

### Your configuration

```ini
provided by Open Watcom v2 build
```

### Provide a Log

```text
provided by Open Watcom v2 build
```

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by LowLevelMahn** [comment]
**FOUND IT !!!**
the open watcom build does set `SDL_VIDEODRIVER=dummy` before calling dosbox -SDL1 of dosbox vanilla seems to like that

it don't know if SDL_VIDEODRIVER=offscreen is better suited

**Comment by johnnovak** [comment]
@LowLevelMahn I skimmed this twice and I still have no idea what this us exactlt about 😄 But I have a feeling it's not something we care about 😉 

In any case, you could perhaphs clearly state what you're doing because this infodump is confusing as hell...

**Comment by LowLevelMahn** [comment]
@johnnovak - sorry for the infodumping :)

Open Watcom Compiler **v2** is buildable on DOS/Windows/Linux/Mac

im currently trying building the Open Watcom Compiler from source on Linux:
the build (even under Linux) needs to run a DOS-only-exe (source is long lost :( - which creates docs) for which dosbox is used

it worked with vanilla dosbox unter Ubuntu but aborts with Tumbleweeds or Fedoras dosbox-staging package

but i found out (after posting the issue) that the Open Watcom build is setting `set SDL_VIDEODRIVER=dummy` before calling the dosbox exectuable (to run the DOS-only exe) and that aborts dosbox-staging with the error screenhots in the first post

Open Watcoms build using its own make tool wmake+this configuration to configure dosbox executable start: https://github.com/open-watcom/open-watcom-v2/blob/master/build/mif/wgmlcmd.mif
in line 75 `set SDL_VIDEODRIVER=dummy` is runned

i tried 'SDL_VIDEODRIVER=dummy dosbox` on console and got the same error as with the watcom build - it seems that 'SDL_VIDEODRIVER=offscreen dosbox` could fix the problem - but changing the line in the wgmlcmd.mif doesn't fixed the problem and the author/maintainer of Open Watcom v2 told me that is the only place

**Comment by johnnovak** [comment]
Thanks @LowLevelMahn, now it makes more sense 😄 I'm inclined to say this is an OpenWatcom build system issue and close it -- no action needed on our side. Also, do note the old DOSBox they must assume uses SDL1.
