### ISSUE TITLE
How to avoid Alt-F4 close the Dosbox Staging window? Bug?

### ISSUE THREAD

**Issue by LiquidProj3ct** [dosbox-staging/dosbox-staging#3989]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### What Operating System are you using?

Windows 10

### Whats your question and how can we help?

I'm playing the game "Fleet Defender: The F14 Tomcat simulation" and it uses Alt+function keys to give orders to the wingman. However with Alt-F4 the windows closes. This doesn't happens in other ms-dos emulators. Is any way to avoid this? is this a bug?

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by johnnovak** [comment]
That sucks, and I don't think we have a solution for it. That's hardcoded behaviour in Windows apps, might be tricky to work around it.

**Comment by grapeli** [comment]
Set this variable when starting dosbox-staging for this game.
`set SDL_WINDOWS_NO_CLOSE_ON_ALT_F4=1`

https://github.com/libsdl-org/SDL/blob/SDL2/include/SDL_hints.h#L2672C46-L2672C76

**Comment by johnnovak** [comment]
> Set this variable when starting dosbox-staging for this game. `set SDL_WINDOWS_NO_CLOSE_ON_ALT_F4=1`
> 
> https://github.com/libsdl-org/SDL/blob/SDL2/include/SDL_hints.h#L2672C46-L2672C76

Haha, I _just_ found that and tested it about 2 minutes ago 😆 Yeah, so I did this by executing `set SDL_WINDOWS_NO_CLOSE_ON_ALT_F4=1` in the `cmd.exe` console and then running `dosbox.exe` from the same console. Probably you can set it in a batch file that you can then use to launch the game.

@Python-Exoproject You might be interested in this; eXoDOS doesn't seem to set this variable for the game, which makes it difficult to play, apparently (but the workaround makes it difficult to quit 😆clicking on the top-right close button still works, though).

**Comment by LiquidProj3ct** [comment]
Thank you! It works! I placed it in a .bat file before launching staging and it works!

Would be a way to include this in the .conf file? I'd like to have a primary global config file for all my games, and a secondary one for each game.

**Comment by johnnovak** [comment]
> Thank you! It works! I placed it in a .bat file before launching staging and it works!

Great to hear that! 🎉 
 
> Would be a way to include this in the .conf file? I'd like to have a primary global config file for all my games, and a secondary one for each game.

No, it has to be done from in the .bat file, unfortunately. This is an SDL thing, it reads this setting from the Windows environment.

**Comment by LiquidProj3ct** [comment]
It's ok! No problem, I will place it in a common .bat which I will call. Thanks again!

**Comment by johnnovak** [comment]
Added entry to the game issues wiki page:
https://github.com/dosbox-staging/dosbox-staging/wiki/Game-issues#fleet-defender-the-f14-tomcat-simulation

**Comment by rderooy** [comment]
> Added entry to the game issues wiki page: https://github.com/dosbox-staging/dosbox-staging/wiki/Game-issues#fleet-defender-the-f14-tomcat-simulation

I have augmented it to mention also Linux, since it is also affected, and the same solution does not work for it.

**Comment by shermp** [comment]
Just had a quick look:
1. This appears to be a Windows only hint :(
2. Hints can be set programatically using `SDL_SetHint`. See `include/SDL_hints.h`

**Comment by johnnovak** [comment]
> Just had a quick look:
> 
>     1. This appears to be a Windows only hint :(

🤷🏻 😆 

>     2. Hints can be set programatically using `SDL_SetHint`. See `include/SDL_hints.h`

That takes care of macOS (without doing anything) and Windows (with this hint). We'll make disallowing Alt+F4 configurable in the new mapper one day. Maybe you can do that programmatically on Linux too, no idea.

**Comment by Python-Exoproject** [comment]
Thanks @johnnovak, ticket in eXoDOS created to action Alt-F4 bypass
