### ISSUE TITLE
Minimum windows size?

### ISSUE THREAD

**Issue by LiquidProj3ct** [dosbox-staging/dosbox-staging#3990]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### What Operating System are you using?

Windows 10

### Whats your question and how can we help?

I always play in windowed mode. However I remember you were able to do the windows smaller than 640x480 in any way, but I do not remember how to achieve this. Maybe I'm confused by other MSDOS emulators, but I think it was possible in Staging. 

I ask this because sometimes I feel curiosity about how to play a game with a tiny window (320x200), since everything seems really sharp. Is this possible with Staging?

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by johnnovak** [comment]
640x480 is the minimum, it would be pointless to set the window size smaller than that.
