### ISSUE TITLE
MIXER /LISTMIDI freezes for ~30 seconds

### ISSUE THREAD

**Issue by jester-xbmc** [dosbox-staging/dosbox-staging#3994]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Different version than latest?

dosbox-staging version 0.82.0-alpha (690e5)

### What Operating System are you using?

Windows 10

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

running MIXER /LISTMIDI freezes the sytem for ~30 second before listing the configuration

Downloaded latest 82 alpha (0.82.0-alpha (690e5) running with default settings (using empty dosbox-staging.conf in the main folder and letting dosbox fill it) with mt32-roms folder 

I see you are refactoring the MIDI section in the 2 pull requests for post 0.82 so I though I'd mention this.

### Steps to reproduce the behaviour.

Explain how to reproduce
1. download alpha
2. add empty dosbox-staging.conf in the root
3. add mt32-roms folder in the root with some roms (Valid ones, I checked)
4. start dosbox
5. run MIXER /LISTMIDI

### Your configuration

```ini
default dosbox-staging.conf
```

### Provide a Log

```text
no entries seen in the log
```

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by interloper98** [comment]
I'm not seeing a delay in Windows 11:

I've downloaded and extracted windows-x64-0.82.0-alpha-690e5 (latest), unzipped [these MT32 roms](https://wowroms.com/en/roms/mame/mt32/96557.html) alongside the executable in `mt32-roms`, deleted my main conf, and created an empty `dosbox-staging.conf` alongside the executable.

![2024-10-19 16_07_56-cmd (Admin)](https://github.com/user-attachments/assets/3faa2b2c-878b-4b15-b7aa-8520886c0dd1)

You can see I'm able to launch DOSBox Staging, run the `mixer /listmidi` command, and quit back to the console all within the same second.

If you want to try the same, you can paste these into your console:

```shell
dosbox.exe --eraseconf

echo # > dosbox-staging.conf

time /t & dosbox.exe -c "mount c ." -c "c:" -c "mixer /listmidi > mixer.log" -exit > dosbox.log 2>&1 & time /t

type MIXER.LOG
```

@jester-xbmc, can you see which MIDI device the delay happens on?

Also, do you have any attached HDDs, network storage, or absent network mounts that might be gumming up the Windows drive system? (I remember getting long filesystem in Windows Explorer when it was spinning up USB storage and such).

**Comment by jester-xbmc** [comment]
Thanks,

Ah, thing to note, I'm running the folder off of a network drive, running it on my laptop's c drives gives maybe a 1 second delay.
Is this correct ? I'd expect some delay but not 30 seconds of delay ?
(and before you ask, this is on a wifi6 network off NAS, streaming 4k stuff without issue, so it's not slow...)

Also, the time command (see below) sees off, as i'm waiting 30 second but the diff only says one ?

![image](https://github.com/user-attachments/assets/c9c24b90-47b6-4c6a-b70f-833603093a71)

**Comment by interloper98** [comment]
Interesting; can you try moving your dir all to a local drive?

**Comment by jester-xbmc** [comment]
> Interesting; can you try moving your dir all to a local drive?

Sure, and as said above, this speeds things up, however my use case using the network drive is to have one location to run dosbox from several computers, and nothing during normal usage is "slow" mounting drives with games etc. works pretty fast, except this command for some reason.

Anyway, I understand if you write this off as a "don't use it on a network drive" as you must have bigger fish to fry, but it seemed a little odd to me, hence to ticket...

**Comment by interloper98** [comment]
Network storage usually does add a ton of latency around atomic file transactions.

**Comment by interloper98** [comment]
Network storage usually is much more latent than local store because it's tuned with large, sequential read-ahead buffering.

This makes it ideal for bulk throughput, but means it suffers in small block size + random IO workloads.

What happens if you delete the mt32-roms dir -- does that speed up the mixer /listmidi command?

**Comment by jester-xbmc** [comment]
> Network storage usually is much more latent than local store because it's tuned with large, sequential read-ahead buffering.
> 
> This makes it ideal for bulk throughput, but means it suffers in small block size + random IO workloads.
> 
> What happens if you delete the mt32-roms dir -- does that speed up the mixer /listmidi command?

Indeed, but i'd figure that latency being in the maybe 5 second range, 10 if you go crazy, but not 30 (with the task bar even going "not responding"

when I remove the mt32-roms folder the command is instant.

**Comment by weirddan455** [comment]
Are there a lot of files in that directory?  It reads the contents of every file in the MT32 ROM directory to determine what ROM it is.  I believe it does this with a hash sum.  It should throw a warning for every unknown (non ROM) file.  This is not logged to the DOS prompt but the separate log window so check there.

**Comment by jester-xbmc** [comment]
> Are there a lot of files in that directory? It reads the contents of every file in the MT32 ROM directory to determine what ROM it is. I believe it does this with a hash sum. It should throw a warning for every unknown (non ROM) file. This is not logged to the DOS prompt but the separate log window so check there.

No, indeed this is what I triple checked initially, ROM versions and files, even when I only put 1 ROM set in there it has the same delay

**Comment by johnnovak** [comment]
libmt32 calculates the checksum of the ROM files, this is how we autodetect the correct ROMs. Probably the library does the reading of the files in a weird way? Although not sure what can be screwed up there 😆 I doubt it's our code that causes the delay which just enumerates the files in the directory (similar code enumerates the list of FluidSynth SoundFont files; is that fast?)

**Comment by johnnovak** [comment]
> Downloaded latest 82 alpha (0.82.0-alpha (690e5) running with default settings (using empty dosbox-staging.conf in the main folder and letting dosbox fill it) with mt32-roms folder

Also fixed the version of the `main` branch. New dev builds off `main` will be 0.83.0-alpha from now on. This was a shortcoming of my release process that I haven't been bumping the version of `main` after releasing the RC.

Seeing 0.82.0-alpha confused the hell out of me for a minute when I first saw this? (_"WTF? We're in the 0.82.0-RC phase now, just before the final"_ 😆)

**Comment by jester-xbmc** [comment]
> > Downloaded latest 82 alpha (0.82.0-alpha (690e5) running with default settings (using empty dosbox-staging.conf in the main folder and letting dosbox fill it) with mt32-roms folder
> 
> Also fixed the version of the `main` branch. New dev builds off `main` will be 0.83.0-alpha from now on. This was a shortcoming of my release process that I haven't been bumping the version of `main` after releasing the RC.
> 
> Seeing 0.82.0-alpha confused the hell out of me for a minute when I first saw this 😂 (_"WTF? We're in the 0.82.0-RC phase now, just before the final"_ 😆)

Thanks for that ! and sorry for the confusion :)

Been having a look at the mt32emu implementation, but nothing sticks out yet so far... seems to read the folder, do a hash and compare...
For what concerns FluidSynth, any sf2 file I put in there is super fast, but put one ROM set back in the mt32-roms folder and its back to the 30 seconds delay.

**Comment by shermp** [comment]
It's not reading in small chunks of the file to calculate the checksum is it? That could be problematic over a network drive.

**Comment by interloper98** [comment]
@jester-xbmc ,

If you can try these builds here: https://github.com/dosbox-staging/dosbox-staging/actions/runs/11449699117 (from branch: `il98/cache-mt32-rom-info`). Curious if that helps.

**Comment by jester-xbmc** [comment]
> @jester-xbmc ,
> 
> If you can try this build: https://github.com/dosbox-staging/dosbox-staging/actions/runs/11450560520 from branch: `il98/cache-mt32-rom-info`, curious if that helps.

Thanks, Yep, that fixes it, almost instant output with 1 ROM set and maybe 2 seconds delay if I load up the mt32-roms folder with 7 ROM sets.
