### ISSUE TITLE
320x200 at 60Hz - doesn't produce correct 4:3 aspect ratio

### ISSUE THREAD

**Issue by James-F2** [dosbox-staging/dosbox-staging#4008]
0.82 RC1
Windows 10

Using default aspect+viewport settings most games produce 4:3 aspect ratio but specifically Rayman which uses 320x200 256 60Hz mode does not.

Default settings:
aspect = auto
viewport  = fit

Status window report
![1](https://github.com/user-attachments/assets/e74aa1db-044b-4ad9-a6e4-b0f9ee82930e)

Image in a 1024x768 window, same incorrect aspect ratio in fullscreen.
![2](https://github.com/user-attachments/assets/9c3616fb-9934-43c4-a6a4-74b8f2feac4d)

As a workaround and to always scale to 4:3, I use the following settings:
aspect = stretch
viewport  = relative 100 100

![3](https://github.com/user-attachments/assets/3548a248-ac2d-4a7c-814d-c0fc19f53c69)

**Comment by interloper98** [comment]
I think that's the correct aspect ratio on a real CRT (for mode-x; typically square pixels).

There's a similar topic on vcfed.org about this (_Why do I get black bars at the top and bottom using a 320x200 60 Hz mode?_): https://forum.vcfed.org/index.php?threads/vga-320x200-60hz.1241527/

So it's how the Rayman devs intended; but users could vertically stretch their CRT image and no harm here doing the same w/ the config settings.

**Comment by James-F2** [comment]
Thank you for this information @interloper98.

My LG Flatron 17" CRT monitor can save H/V stretch settings for individual modes, so 320x200@70Hz and 320x200@60Hz modes can be adjusted individually.
I remember back in in the day (early 90s) when we were playing DOS games we adjusted the image to fill the monitor, so everything was 4:3.
Whether that was the correct way to play or not is a different discussion.

**Comment by interloper98** [comment]
> Whether that was the correct way to play or not is a different discussion.

Yup - I think the best DOSBox can do - present an image as close to original aspect ratio as it would have looked on a CRT, because that how the majority of the original staff would have seen it, too (and presumably they released it the art like that).

I guess there's always the possibility that people didn't care, or the artists had their vertical stretch cranked up, or maybe it was a hasty console-to-DOS port.

**Comment by johnnovak** [comment]
Yeah, we do as the hardware does. The close to 1:1 PAR looks better to me. I'm almost certain the artist drew the graphics assuming square pixels (look at the round objects, they look elongated with the 4:3 stretch).

But the it's a game with abstract cartoony graphics so use what you like.

Another method is to look for some logo and compare it to the printed materials, or check the official photos on the back of the box. Of course, neither of these methods are 100% definitive either.

In any case, works as intended.
