### ISSUE TITLE
Deinterlacing shader for FMV games together with CRT shader in 0.82?

### ISSUE THREAD

**Issue by mikesk8** [dosbox-staging/dosbox-staging#4011]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### What Operating System are you using?

None

### Whats your question and how can we help?

Hi, I just wanted to briefly ask if you are planning to add a feature in 0.82 to enable running new deinterlacing shader for FMV games (from 0.81) together with CRT shaders?
Thanks, M.

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by johnnovak** [comment]
The answer is yes 😄
