### ISSUE TITLE
Commander Keen 4 jerky scrolling with "machine=ega" [0.82]

### ISSUE THREAD

**Issue by Diduz** [dosbox-staging/dosbox-staging#4023]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### What Operating System are you using?

Windows 10

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

This is weird. We all know that Commander Keen 4-6 are very sensitive when it comes to video cards. I'm playing the vanilla Commander Keen 4 shareware from Apogee and the game works just fine with "machine=svga_s3". No "fix jerky motion" or "svga compatibility fix" needed. Perfect, so I know I'm nitpicking here.
Now, I was checking out the game with "machine=ega", which should theoretically run the game flawlessy, but the scrolling is literally shaking! This happens with my desktop PC (variable refresh rate) and notebook (fixed 60hz screen): tinkering with DOSBox Staging vsync doesn't change anything. Classic DOSBox 0.74-3 runs the game just fine with "machine=ega", so beats me.
This isn't too important, because - as I said - the game runs ok with "machine=svga_s3" anyway, but I just thought you should be aware of this strange behaviour: Keen was programmed for EGA, after all.
Best!

### Steps to reproduce the behaviour.

Explain how to reproduce
1. 
2.
3.

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by johnnovak** [comment]
Yeah, but we don't wanna dick around with the EGA/VGA emulation unless absolutely necessary. Just use `machine=svga_s3`.

**Comment by interloper98** [comment]
Fortunately this is also hardware-accurate. People [with real EGA hardware complained about jerky scrolling in keen 4+](https://www.vogons.org/viewtopic.php?f=61&t=54291), and it's only really fixed if they switch to a VGA card.

Here's the reason, from [K1n9_Duk3](https://www.vogons.org/memberlist.php?mode=viewprofile&u=34295): .. _might be related to the fact that apparently EGA cards run 320x200 at 60 Hz while VGA card run it at 70 Hz. The Keen 4-6 engine uses multiples of 70 Hz for the internal timers, which means the delays don't align properly with the EGA refresh rate_`

He eventually wrote extensive patches for Keen to fix this stuff here - https://pckf.com/viewtopic.php?f=4&t=6192

**Comment by interloper98** [comment]
@Diduz , here's a little DOS game engine that runs only really slow hardware and does console-like scrolling: https://github.com/mills32/Little-Game-Engine-for-VGA-EGA

I tried it with Staging with `[dosbox] machine = ega`, and yes: the scrolling is super smooth - so EGA gets it right, just like VGA (Jazz Jackrabbit, Pinball Dreams, and more):

https://github.com/user-attachments/assets/76f0402a-6301-449d-911f-231c346d0a6c

**Comment by johnnovak** [comment]
Also, note I'm not being an asshole here, but none of us have real hardware with EGA cards, only late-DOS-era SVGA, which makes confirming the behaviour on hardware impossible. Because of that, and because the VGA code is extremely hairy, I'm taking the "not broken, don't fix it" approach, or if there's a viable workaround (which isn't really a workaround in this case), I'd always just recommend that and leave the code alone.

**Comment by Diduz** [comment]
Got it, you made your point, thanks! ;-)
I was just curious, because another EGA title with smooth scrolling such as Monster Bash works fine in Staging with "machine=ega". Keen 4-6 engine must be a strange beast indeed.
@interloper98 That engine looks great, that kind of framework seems to be kind of rare in the DOS world.
