### ISSUE TITLE
ManyMouse doesn't work in 0.82 anymore

### ISSUE THREAD

**Issue by Torinde** [dosbox-staging/dosbox-staging#4026]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### What Operating System are you using?

Windows 10

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Two problems:
1. Regression in 0.82
0.82 mousectl results in "No physical mice detected"
0.81.2 mousectl asks for left click, etc. and works

2. 0.81.2 mousectl (and also earlier versions) gets the left click if Staging is full screen, but otherwise it responds only to escape/cancel (I tried to capture/uncapture the mouse, but that didn't help)

### Steps to reproduce the behaviour.

Explain how to reproduce
1. 
2.
3.

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by FeralChild64** [comment]
Which OS? Are you using USB mouse, a laptop touchpad, or a Bluetooth mouse?

![Screenshot](https://github.com/user-attachments/assets/93a0bc44-cc81-466a-b14c-87098c38e198)

**Comment by FeralChild64** [comment]
Checked the Windows 0.82.0 official build, on my Windows 11 system, and it has the same error, ManyMouse support was not compiled in. Same if I compile from sources.

I can compile-in the ManyMouse back if I add `C_MANYMOUSE` definition to Windows-specific `config.h` file - but, if I’m not mistaken, this file didn’t contain the definition, so how did it work in the first place?

I can also confirm I can’t map the mouse if the tool wasn’t started when emulator was fullscreen, this I’ll have to investigate too.

**Comment by FeralChild64** [comment]
@Torinde Could you check on 0.81.2 if you can map the mouse in windowed mode after setting `mouse_raw_input = false` in the config file?

**Comment by FeralChild64** [comment]
I have tried to force disabling raw mouse input for the duration of mouse mapping (both probing or mapping in effect) - strangely, this does not fix the issue.

Hard to believe this wasn't discovered for such a long time. What's more interesting - mapping works under Wine :) It's just not useful, as Wine only emulates a single mouse.

**Comment by johnnovak** [comment]
> Hard to believe this wasn't discovered for such a long time.

Well, this is only useful for exactly two games and no more. So, not that hard, actually 😆

**Comment by FeralChild64** [comment]
True.

My workaround to transparently disable raw mouse input when mapping is in effect was actually wrong - a proper one would require a serious redesign of my _ManyMouse_ glue code.
I don't want to spend my time on this - upcoming _SDL_ 3 has built-in support for multiple mice/keyboards, so once we upgrade the proper solution will be to drop _ManyMouse_ and use the _SDL_ API instead.
I intend to block _ManyMouse_ usage for Windows users if they have raw mouse input enabled - and just display appropriate hint.
