### ISSUE TITLE
GitHub taking away macOS 12 workflow machines

### ISSUE THREAD

**Issue by interloper98** [dosbox-staging/dosbox-staging#4037]
Looks like we're using macOS 12 for release builds:

```yaml
build_macos_release:
  runner:
  - host: macos-12
```

Starting in October, [GitHub is phasing out macOS 12](https://github.com/actions/runner-images/issues/10721):

> _"GitHub Actions is starting the deprecation process for macOS 12. While the image is being deprecated, You may experience longer queue times during peak usage hours. Deprecation will begin on 10/7/24 and the image will be fully unsupported by 12/3/24"_

(just did a search for this because I saw a strange error from CI showing that macOS 12 compilers weren't even available on the system -- I suspect this is part of the phase out).

**Comment by johnnovak** [comment]
@interloper98 Thanks for the heads, @kklobe and myself are already aware of this.

This aligns with our quite generous support for the last 3 major OS versions (we certainly don't want to beyond that). The solution is hopefully just bumping the runner version in the CI workflow. Probably should try that a bit before the hard deadline yeah.

**Comment by interloper98** [comment]
Glad it's in hand!
(will leave it open so it can be tagged in the PR)
