### ISSUE TITLE
How can I get a touch screen tablet to work like a mouse? Struggling with Autodesk animator pro 1.3a

### ISSUE THREAD

**Issue by xrheihwh** [dosbox-staging/dosbox-staging#4046]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### What Operating System are you using?

Linux x86_64

### Whats your question and how can we help?

I find art and animation programs on DOS to be fascinating. My current area of interest is autodesk animator pro 1.3a. I can get it to work fine with a USB mouse. But it struggles to get my huion touchscreen tablet to work properly. What happens if it does interface at all, the mouse is way off from where the stylus pointer actually is. Do I need to use very specific mouse drivers? Do I need to tweak a setting? For some reason, it works better with my older wacom tablet than it does with the touchscreen device. Would it just be better to run it in a windows 98/95 virtual machine? Because of how AAP was designed, it failed to run on windows 2000.

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by xrheihwh** [comment]
I have seen and tried that mouse driver, unfortunantely, it causes A: the cursor to be considerably off where the stylus actually is or B: jumping around the screen like a madman wherever I move the stylus. So maybe it's the driver or maybe it's how I configured dosbox-staging. I dunno. But if I run any DOS program under windows 3.1 like AAP or DP, it quits saying there is no mouse available as well.

**Comment by FeralChild64** [comment]
Don't run DOS software on Windows without a real need, it's asking for trouble. Sorry, I have never heard about this software - but I suppose your only option is to set `mouse_capture = seamless` in the config file.

**Comment by johnnovak** [comment]
Supporting touch screens is out of scope for the project. Most DOS games are unusable without mouse and keyboard. Will leave this open for a few days, but it gets the out of scope label from me.

Next time you ask a similar question, can you please do it in "Discusiions" instead of raising an issue ticket? Thanks.
