### ISSUE TITLE
X-COM: Terror from the Deep freezes on launch

### ISSUE THREAD

**Issue by bsmith1702** [dosbox-staging/dosbox-staging#4053]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### What Operating System are you using?

Windows 10

### Relevant hardware info

i7-4820K @3.7 GHz, GeForce GTX 1650

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Immediately after launch, the game freezes and all I see is a black screen.  The game is launched with TERROR.COM, but the title bar says INTRO.COM when it gets stuck.  The game runs fine on 0.81.2 using the same settings.  I've attached both conf files.

[xcom2.zip](https://github.com/user-attachments/files/17705444/xcom2.zip)

### Steps to reproduce the behaviour.

Launch the game.  The game will freeze immediately after the screen clears.

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by interloper98** [comment]
Bisects to 10b1303e554c73ea4dddaf8d1b145b7440e4542d (pinging @johnnovak )

```diff
    Allow running the `INTRO` built-in from subshells

diff --git a/src/dos/program_intro.cpp b/src/dos/program_intro.cpp
index ff557e3fb..c2f52edca 100644
--- a/src/dos/program_intro.cpp
+++ b/src/dos/program_intro.cpp
@@ -75,8 +75,6 @@ void INTRO::Run(void) {
                output.Display();
                return;
        }
-    /* Only run if called from the first shell (Xcom TFTD runs any intro file in the path) */
-    if (DOS_PSP(dos.psp()).GetParent() != DOS_PSP(DOS_PSP(dos.psp()).GetParent()).GetParent()) return;
     if (cmd->FindExist("cdrom",false)) {
 #ifdef WIN32
         WriteOut(MSG_Get("PROGRAM_INTRO_CDROM_WINDOWS"));
```

**Comment by johnnovak** [comment]
> Bisects to [10b1303](https://github.com/dosbox-staging/dosbox-staging/commit/10b1303e554c73ea4dddaf8d1b145b7440e4542d) (pinging @johnnovak )
> 
> ```diff
>     Allow running the `INTRO` built-in from subshells
> 
> diff --git a/src/dos/program_intro.cpp b/src/dos/program_intro.cpp
> index ff557e3fb..c2f52edca 100644
> --- a/src/dos/program_intro.cpp
> +++ b/src/dos/program_intro.cpp
> @@ -75,8 +75,6 @@ void INTRO::Run(void) {
>                 output.Display();
>                 return;
>         }
> -    /* Only run if called from the first shell (Xcom TFTD runs any intro file in the path) */
> -    if (DOS_PSP(dos.psp()).GetParent() != DOS_PSP(DOS_PSP(dos.psp()).GetParent()).GetParent()) return;
>      if (cmd->FindExist("cdrom",false)) {
>  #ifdef WIN32
>          WriteOut(MSG_Get("PROGRAM_INTRO_CDROM_WINDOWS"));
> ```

Thanks man. I just removed it because I assumed it was some legacy cruft. Should have tested it with XCOM... how silly of me! 😅 

Putting it back shortly.

**Comment by interloper98** [comment]
Nice @johnnovak ; this is the kind of regression we should all hope for.
Much more relaxed than digging through the SB and GUS code :laughing:

**Comment by johnnovak** [comment]
> Nice @johnnovak ; this is the kind of regression we should all hope for. Much more relaxed than digging through the SB and GUS code ☺️

Yeah, I'll revert it, but the root cause is that the built-in programs on the Z: drive always take priority. So the better fix would be to allow users to put `Z:` anywhere in your `PATH`, which is not the case now.

**Comment by johnnovak** [comment]
Actually... I did test this, and the eXoDOS version just runs fine. That's the CD version of the game.

I don't have `TERROR.COM` and `INTRO.COM`, but a `TERRORCD.BAT` to launch the game with the following content.

The interesting thing is there is an `INTRO` command invocation, but that file doesn't exist, so the game launches `geoscape` which actually also play some kind of an intro.

So yeah, a bit confused. Can you point me to the version you're using @bsmith1702 or @interloper98 ?

```
@echo off
cls
%1sound\sndstart       %1
%1ufoexe\black
%1intro                %1
%1ufoexe\black
%1ufoexe\geoscape  "0" %1
if errorlevel 2 goto begin
goto end
:begin
%1ufoexe\black
%1ufo2exe\tactical "1" %1
:geo
%1ufoexe\black
%1ufoexe\geoscape  "1" %1
if errorlevel 2 goto begin
:end
%1sound\sndend
```

**Comment by bsmith1702** [comment]
I'm using the GOG version.  I couldn't find a version number for the game itself.  I also have a `TERRORCD.BAT` file which is exactly as the one you posted and I am able to run the game using that.  I also looked through the game files and couldn't find `INTRO.COM` either.  The conf file that GOG provides runs the game with `START.BAT` which literally only has the lines `TERROR.COM` and `exit`.  I was going by this when writing the autoexec portion of my conf file.

**Comment by interloper98** [comment]
@johnnovak , here's my config [conf.zip](https://github.com/user-attachments/files/17740343/x_com_2_terror_from_the_deep.zip).
Luanch main in the unpatched v1.0 game will reproduce the issue.

**Comment by johnnovak** [comment]
Thanks @interloper98, it was user error on my part... 😅  I can reproduce the problem by running `TERRORCD.BAT` which calls the `INTRO` program.

@bsmith1702 
Upon further consideration, I'm not going to revert my change. The workaround for this game is to remove the `INTRO` command from the path by removing the `Z:\` drive from the `PATH` env var.

So setting this prior to running the game does the trick: `SET PATH=Y:\DOS` (or any path string really that doesn't have `Z:\` in it).

As extremely few games would be affected by this issue, I don't think putting back the ugly hack is warranted.

Will add a note about this to the game issues wiki.

**Comment by johnnovak** [comment]
@bsmith1702 
Added note to the game issues wiki:

https://github.com/dosbox-staging/dosbox-staging/wiki/Game-issues#x-com-terror-from-the-deep

**Comment by Nebulus33** [comment]
Just add en empty INTRO.EXE on the root of the game where TERROR.COM is located and it will do the trick
