### ISSUE TITLE
Jetfighter Platinum : 3dfx mode not working

### ISSUE THREAD

**Issue by KalRego** [dosbox-staging/dosbox-staging#4058]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Different version than latest?

No

### What Operating System are you using?

Windows 10

### If Other OS, please describe

Linux: Bazzite distro

### Relevant hardware info

AMD 5800X3D, nVidia 4070, 32DB, Sound blaster ZxR 

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

3dfx mode is not working at all!! The game cannot initiate 3dfx rendering and just reverts back to previous screen!! 

### Steps to reproduce the behaviour.

Explain how to reproduce
1. c:\   -->  _type_ cd JF3 --> _type_ c:\JF3\install --> _select_  SETUP 3D CARD -->_select_ 3DFx Voodoo Card --> _select_ CONTINUE  --> _select_ EXIT AND SAVE

2. _type_ c:\JF3\jf3 --> Proceed to Operations --> _select_  Operations : Free Flight  --> _select_ ACCEPT 

3.   A crackling sound and then returns back to previous screen ( _select_ ACCEPT)

### Your configuration

```ini
[voodoo]

voodoo                    = true
voodoo_memsize            = 4
voodoo_multithreading     = true
voodoo_bilinear_filtering = false
```

### Provide a Log

```text
2024-11-13 20:30:03.650 | DISPLAY: VESA 640x480 256-colour graphics mode 101h at 70.007 Hz throttled VFR, scaled to 1440x1080 pixels with 1:1 (1:1) pixel aspect ratio
2024-11-13 20:30:12.561 | DISPLAY: VESA 640x480 256-colour graphics mode 101h at 70.007 Hz throttled VFR, scaled to 1067x800 pixels with 1:1 (1:1) pixel aspect ratio
2024-11-13 20:30:20.116 | SB16: Resetting DSP
2024-11-13 20:30:21.013 | SB16: Resetting DSP
```

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by johnnovak** [comment]
> 3dfx mode is not working at all!! The game cannot initiate 3dfx rendering and just reverts back to previous screen!!

Thanks for the report, but try without the exclamation marks next time 😉 This might suggest to some that you are demanding a fix , which doesn't go down well with our team of volunteers... 😄 

Does it work in DOSBox X or earlier Staging versions?

**Comment by KalRego** [comment]
>>>Thanks for the report, but try without the exclamation marks next time 😉 This might suggest to some that you are demanding a fix , which doesn't go down well with our team of volunteers... 😄
Will do!! Not demanding a fix!! Just being curious!!!! :D
I got 3dfx mode to work in Dosbox-X (ver. -win32-2022.09.0) using the option of an external glide wrapper (nGlide 2.10)!!  
And the old DosBox fork from Daum (https://github.com/ykhwong/dosbox-svn-daum/releases), also works with nglide.
I could not get the 3dfx mode to work in Linux at all.
Nick K.



    Στις Τετάρτη 13 Νοεμβρίου 2024 στις 11:32:47 μ.μ. EET, ο χρήστης John Novak ***@***.***> έγραψε:  
 
 



3dfx mode is not working at all!! The game cannot initiate 3dfx rendering and just reverts back to previous screen!!


Thanks for the report, but try without the exclamation marks next time 😉 This might suggest to some that you are demanding a fix , which doesn't go down well with our team of volunteers... 😄

Does it work in DOSBox X or earlier Staging versions?

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***>
  

|  | Χωρίς ιούς.www.avast.com |

**Comment by johnnovak** [comment]
Thanks for the extra info @KalRego

**Comment by interloper98** [comment]
@KalRego , you're probably missing the DOS glide driver. 

I'm using a DOSBox Staging drive for stuff like this. You can set it up once, and then you're set to run all voodoo games.

Download and extract [dosbox-staging-voodoo-drive-addon.zip](https://github.com/user-attachments/files/17740827/dosbox-staging-voodoo-drive-addon.zip) in your `C:\USER\AppData\Local\DOSBox\` directory.

A bit hard to see - expand to fullscreen:

https://github.com/user-attachments/assets/0d713684-615b-4ec3-acc1-3c38d8a9106d

**Comment by KalRego** [comment]
Thank you guys!! That did the trick. I had Starfighter 3000 working, without the need of a  DOS glide driver, so I thought it was a bug!! 

By the way I also tested the GoG version of Archimedean Dynasty, and a driver is also needed for this game to work!!

Unless I missed it completely,   a paragraph in the documentation to manually add this driver, would be most helpful.

Thank you again.

**Comment by johnnovak** [comment]
> Unless I missed it completely, a paragraph in the documentation to manually add this driver, would be most helpful.

Glad you got it working. We don't have a manual yet, but it's in the pipeline and we'll mention this.
