### ISSUE TITLE
Cutscenes autoskip when you depress the mouse button.

### ISSUE THREAD

**Issue by Kenny-024** [dosbox-staging/dosbox-staging#4060]
In the Harvester game cutscenes skip when depressing the mouse button.

MacBook Pro. Sequoia 15.1.

**Comment by Kenny-024** [comment]
Theres an update on GOG that fixes it. But the fix does not work on MacOS.

**Comment by johnnovak** [comment]
@Kenny-024 I'm deleting this in a day. Please raise a proper report by filling out our issue template as we ask you to do.
