### ISSUE TITLE
shift dont work if i start with caps enabled

### ISSUE THREAD

**Issue by elcrom** [dosbox-staging/dosbox-staging#4064]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### What Operating System are you using?

Windows 11

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

if i have upercase key enabled, when i start a game shift+x dosent work properly. checked with silmarils games.

### Steps to reproduce the behaviour.

Explain how to reproduce
1. try a shift + key movement 
2.
3.

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by FeralChild64** [comment]
Could you list the games you have tested? At least one of them.

**Comment by johnnovak** [comment]
@elcrom Can you please try harder raising a proper report? You haven't answered the questions we are asking in the issue template very well.

Where are the exact repro steps?

Which exact games are affected? List of names please.

Can you please edit the top post and tyrn this into a proper report?

--- 

@FeralChild64 
Btw, might be a game bug present on hardware. Eye of the Beholder 2 is similarly affected when the Num Lock is turned on before startup (or off, can't remember).

**Comment by johnnovak** [comment]
Please raise a proper ticket next time.
