### ISSUE TITLE
Recent regression breaks keyboard input in Tyrian and Secret of Monkey Island 2

### ISSUE THREAD

**Issue by weirddan455** [dosbox-staging/dosbox-staging#4066]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### What Operating System are you using?

Linux x86_64

### If Other OS, please describe

Debian 12

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Bisected the bug to 3983c4288655f33c54a8915a5c199bcb68a47e46 and tagging @interloper98  Removing the single line `readcache = Ascii::LineFeed;` resolves this issue on `main`

The issue happens only when you manually enter the game executable from the command line.  If you auto-start the game by putting all the commands in the `[autoexec]` section, input works fine.  I'm guessing it's something about the final Enter keystroke from the command line that gums things up.

In Tyrian, you can press Esc or Enter to skip the intro but the main menu does not work at all.

In Secret of Monkey Island 2, at the "Press Enter for lamo copy protection" screen, pressing Enter results in an in-game message that says "recalibrating joystick".  I'm assuming it's registering the enter key as something different.

### Steps to reproduce the behaviour.

Explain how to reproduce
1.  Launch the `monkey2.exe` or `tyrian.exe` by manually typing into the command line.  The bug is not present if the game is launched through autoexec.
2.  In Tyrian, observe that you cannot navigate the main menu by pressing arrow keys or the Enter key.
3. In Secret of Monkey Island 2, observe that you cannot get past the copy protection screen.

### Your configuration

```ini
Default config
```

### Provide a Log

```text
Nothing relevant in the logs
```

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by interloper98** [comment]
Nice find @weirddan455 !
And darn.. 😞 ; I'm not sure now how to make sure the LF always follows CR for keyboard input. From what I read, the MS-DOS "kernel" performs this conversation from CR to LF, so thought this was the right place to add it. 

@FeralChild64 , curious if you have ideas with your knowledge in this input area?

We could revert it or add a conf to fix that Ford driving game. I'm learning toward the first and then wait for a proper fix.

Feel free to revert it @weirddan455 👍

**Comment by FeralChild64** [comment]
Unfortunately, my experience with keyboard emulation is limited to hardware emulation, I haven't touched the scancode processing in BIOS/DOS.
