### ISSUE TITLE
Locale: Country not being auto-detected on Debian

### ISSUE THREAD

**Issue by weirddan455** [dosbox-staging/dosbox-staging#4071]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### What Operating System are you using?

Linux x86_64

### If Other OS, please describe

Debain 12

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

I just built and ran the latest `main` with the locale changes @FeralChild64 made recently.  Sorry I didn't find the time to review that PR before merge.

I noticed in the logs that it's failing to detect my country (US) and falling back to International English.  I took a quick look at the code and it's trying to get it from an environment variable `LC_TELEPHONE` which is not set by default on a standard Debian install.

As a suggestion, would it be possible to parse the `LANG` variable and use that if `LC_TELEPHONE` is not set?  Mine is set to `en_US.UTF-8` and if I do a `export LC_TELEPHONE=en_US.UTF-8`, it works.  I'm sure there's some minutia here (not every language is going to correspond to a country) but if a country can be derived, then maybe we should try it before falling back to the default?

I suppose in some cases, country could also be derived from the keyboard layout (that one is auto-detected as US in my case).

Of course the other workaround is to simply set `country = 1` in the dosbox config and that works as well so it's not exactly a groundbreaking bug but maybe the auto-detection can be improved for Linux users (at least for en_US and other languages that have a country code in the `LANG` string, it seems easy on the surface).

### Steps to reproduce the behaviour.

1.  Set `country = auto` in config
2. `unset LC_TELEPHONE` if it is set in the first place
3.  Look at the logs tagged with `LOCALE` and it should fall back to International English
4. `export LC_TELEPHONE=en_US.UTF-8`
5. The logs state the country is detected as US

### Your configuration

```ini
[dos]
country = auto
```

### Provide a Log

```text
2024-11-27 06:36:03.409 | LOCALE: Country detected from ''
2024-11-27 06:36:03.409 | LOCALE: Loading native locale for country 61 - 'International (English)'
2024-11-27 06:36:03.409 | LOCALE: Using numeric/time/date/currency format detected from host OS
2024-11-27 06:36:03.409 | LOCALE: Loaded code page 437
2024-11-27 06:36:03.409 | LOCALE: Loaded keyboard layout 'us' - 'US (standard, QWERTY/national)'
```

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by weirddan455** [comment]
I don't have any of the LC environment variables set.  However, if I run the `locale` command, it shows the following:

```
LANG=en_US.UTF-8
LANGUAGE=
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
```

I looked up the source code for this command and it just sets everything (minus `LC_ALL` and `LANGUAGE`) to `LANG` if they're not explicitly set.

https://github.com/bminor/glibc/blob/c69e8cccaff8f2d89cee43202623b33e6ef5d24a/locale/programs/locale.c#L794-L824

So falling back to `LANG` is probably fine to do.  This utility is written by the glibc developers.

**Comment by FeralChild64** [comment]
I thought LANG was only used for language (messages) detection. Seems I was wrong. PR: https://github.com/dosbox-staging/dosbox-staging/pull/4072
