### ISSUE TITLE
Setting `country` to `0` (International English) is treated as an invalid value

### ISSUE THREAD

**Issue by johnnovak** [dosbox-staging/dosbox-staging#4078]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Different version than latest?

0.83.0-alpha

### What Operating System are you using?

macOS (Apple Silicon)

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

The `--list-countries` output lists code `0` (International English) as a valid setting:

<img width="663" alt="image" src="https://github.com/user-attachments/assets/32485d4f-5ef6-4b9a-9006-1cb06f60ca68">

But it's treated as an invalid setting:

<img width="851" alt="image" src="https://github.com/user-attachments/assets/2df27c3e-0ed6-4d09-a1ae-8222df3a5f62">

The same defaulting happens if I set it to some bogus value:

<img width="844" alt="image" src="https://github.com/user-attachments/assets/7e0bce60-6e5d-4993-a597-fe5f776cbdac">

### Steps to reproduce the behaviour.

1. Start with `--noprimaryconf`
2. Execute `country 0`

### Provide a Log

Probably not relevant, but these settings are auto-detected on my system (wrongly, because I rarely use my secondary Hungarian keyboard layout, yet Staging chooses it!)

<img width="1099" alt="image" src="https://github.com/user-attachments/assets/15ddd22f-7e8a-4dff-9589-47533a479ca9">

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by FeralChild64** [comment]
This was fixed in PR https://github.com/dosbox-staging/dosbox-staging/pull/4085
