### ISSUE TITLE
How to build 64-bit dosbox with visual studio 2019?

### ISSUE THREAD

**Issue by LEETUMBRA** [dosbox-staging/dosbox-staging#412]
I can't find five dlls below after building with visual studio (x64 with win32 is still ok)

Setting is x64, x64
libpng16d.dll
ogg.dll
opus.dll
SDL2_net.dll
SDL2d.dll

**Comment by dreamer** [comment]
I don't understand your question. What do you mean by "x64, x64" or "x64 with win32"?

x64 builds should have all these dlls copied from vcpkg to your release directory.

**Comment by dreamer** [comment]
@LEETUMBRA Do you still have problems with compiling on Windows? If not, can I close the issue?

**Comment by LEETUMBRA** [comment]
Then close the issue first, possibly that one is just for 32-bit , for the
time being.

Patryk Obara <notifications@github.com> 於 2020年6月22日 週一 下午8:03寫道：

**Comment by kcgen** [comment]
@LEETUMBRA ,

If you've performed the intiall pre-requisites here:

https://github.com/dosbox-staging/dosbox-staging/blob/master/README.md#visual-studio-2019-or-newer

And have the following in your `PATH`:

`C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\amd64'

Then inside your dosbox-staging repo, you can:

``` powershell
cd vs
MSBuild -m dosbox.sln -p:Configuration=Release -p:Platform=x86
```

The build will create a `Win32/Release` directory inside `vs/`, where you should find your binary plus DLLs:
- dosbox.exe
- libpng16.dll
- ogg.dll
- opus.dll
- SDL2.dll
- SDL2_net.dll
- zlib1.dll
- zmbv.dll

**Comment by dreamer** [comment]
@kcgen He does not even need to use terminal/powershell; all our VS build configurations (there are 4) create either Release or Debug directories and copy all needed dlls in there… It all works out-of-the box (as long as correct triplet is installed via vcpkg).

I still don't get what the problem was, perhaps some miscommunication error :)

**Comment by kcgen** [comment]
> It all works out-of-the box (as long as correct triplet is installed via vcpkg).

Right on; even easier!
