### ISSUE TITLE
Mapper crashes with assertion fail (debug) or segfault (release) when mapping an analog stick to a key press

### ISSUE THREAD

**Issue by weirddan455** [dosbox-staging/dosbox-staging#4126]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Different version than latest?

f7ae7dfdaa279ee434f2079b50aa2e562f366182 (latest main at time of writing)

### What Operating System are you using?

Linux x86_64

### If Other OS, please describe

Debian 12

### Relevant hardware info

Xbox One S Controller

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

The mapper crashes when attempting to add a binding for a keyboard key to my right analog joystick on my Xbox One S controller.

The problem seems to be fixed by PR #4122 but thought I would raise this to understand the root cause.  Can be closed once the PR is merged and we're sure this won't pop up again.

### Steps to reproduce the behaviour.

Explain how to reproduce
1.  Start the mapper by dosbox --startmapper
2.  Click on a key to map (ex. the up arrow key)
3.  Click "Add bind"
4.  Press up on the gamepad stick

### Provide a Log

```text
2024-12-28 13:04:03.870 | MAPPER: Found one joystick
2024-12-28 13:04:03.870 | MAPPER: Initialised Xbox One S Controller with 6 axes, 11 buttons, and 1 hat(s)
2024-12-28 13:04:03.874 | MAPPER: Loaded default key bindings
dosbox: ../../src/gui/sdl_mapper.cpp:2053: void drop_other_bound_events(const T *) [T = CKeyBind]: Assertion `new_bind' failed.

Loguru caught a signal: SIGABRT
Stack trace:
14      0x55e95441b3d1 _start + 33
13      0x7fd782a46305 __libc_start_main + 133
12      0x7fd782a4624a /lib/x86_64-linux-gnu/libc.so.6(+0x2724a) [0x7fd782a4624a]
11      0x55e95441b4c2 main + 34
10      0x55e95486bef5 sdl_main(int, char**) + 7877
9       0x55e954840f26 MAPPER_DisplayUI() + 998
8       0x55e9548406fd BIND_MappingEvents() + 1581
7       0x55e954840946 build/debug/dosbox(+0xb62946) [0x55e954840946]
6       0x55e95484819e build/debug/dosbox(+0xb6a19e) [0x55e95484819e]
5       0x7fd782a53eb2 /lib/x86_64-linux-gnu/libc.so.6(+0x34eb2) [0x7fd782a53eb2]
4       0x7fd782a45395 /lib/x86_64-linux-gnu/libc.so.6(+0x26395) [0x7fd782a45395]
3       0x7fd782a45472 abort + 211
2       0x7fd782a5afb2 gsignal + 18
1       0x7fd782aa9ebc /lib/x86_64-linux-gnu/libc.so.6(+0x8aebc) [0x7fd782aa9ebc]
0       0x7fd782a5b050 /lib/x86_64-linux-gnu/libc.so.6(+0x3c050) [0x7fd782a5b050]
2024-12-28 13:04:41.421 | Signal: SIGABRT
Aborted (core dumped)
```

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by weirddan455** [comment]
@arifogel bisected (and I confirmed) that this is a regression from f33cc25e57b7d1b8835f1efae7e43efa4ea7691e

It's fixed in the first commit of #4124 which is a pre-requisit of #4122

This issue can be closed once merged.

**Comment by johnnovak** [comment]
Related:

- https://github.com/dosbox-staging/dosbox-staging/issues/4128

**Comment by weirddan455** [comment]
Fixed by reverting the problematic commits.
