### ISSUE TITLE
Show-stopper mapper regressions

### ISSUE THREAD

**Issue by johnnovak** [dosbox-staging/dosbox-staging#4128]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Different version than latest?

main

### What Operating System are you using?

Windows 10

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

This changes has introduced some show-stopper regressions:

- https://github.com/dosbox-staging/dosbox-staging/pull/4079/commits

This is unfortunate as this would be a good enhancement on paper, but the implementation has unintended side effects.

### Steps to reproduce the behaviour.

1.  Open the mapper with **Ctrl+F1**.
2.  Click on **Left Control** key and observe the following warning/notice:

![image](https://github.com/user-attachments/assets/d8382a7c-8058-49bf-b741-4490aed34745)

A warning is also logged:

```
2024-12-29 12:25:10.941 | MAPPER: Host button 'Left Ctrl' now performs 'key_lctrl' instead of 'mod_1'
```

3. Close the mapper with the Exit button.
4. Try to open the mapper again with **Ctrl+F1** -- it doesn't work anymore.

---

Right Control key, the GUI keys (Left/Righ Windows keys), Left/Right Alt keys, Mod1/Mod2/Mod3 keys are similarly affected. For example.

![image](https://github.com/user-attachments/assets/3a39401f-9159-43d2-a6bb-64bd9fdc7a4e)

The joystick bindings are similarly affected. In main I'm getting crashes when I click on the joystick bindings, the [first commit](https://github.com/dosbox-staging/dosbox-staging/pull/4124/commits/c0f3c546d60811f0139e69a21fa1c858881e7106) in this PR fixes it:

https://github.com/dosbox-staging/dosbox-staging/pull/4124

But even with the fix, I get this semi-random remapping behaviour, making the joystick mapper rather useless (I have an Xbox 360 controller and a digital joystick adapter connected that has support for two digital joysticks).

None of these problems exist prior to @interloper98's rebinding PRs, so it either needs more work and refinement, or it needs to be reverted (I'd prefer the former, but I don't have time to fix it now).

### Your configuration

```ini
Default config
```

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by interloper98** [comment]
Darn; please revert it. I haven't the time (or a dev environment right now) to work on this in the near term.

**Comment by johnnovak** [comment]
> Darn; please revert it. I haven't the time (or a dev environment right now) to work on this in the near term.

Cheers, noted. I'll wait a few days to see if someone has the appetite for fixing this up -- if not, revert time.

**Comment by weirddan455** [comment]
This can be closed now that you've done the revert right?

**Comment by johnnovak** [comment]
> This can be closed now that you've done the revert right?

Yeah, cheers.
