### ISSUE TITLE
IPX support unavailable in macOS build

### ISSUE THREAD

**Issue by acegary** [dosbox-staging/dosbox-staging#416]
This seems to be an odd thing to leave out since it's built into the official Dosbox. I'd love to be able to play some network games. Any chance you'll be putting this back in?

**Comment by GranMinigun** [comment]
What do you mean? It wasn't cut out and works.

**Comment by acegary** [comment]
Sorry if this is a mistake, but the config file had no section at all for ipx. I had to add it in myself. Even with it set to "true" there is still no ipxnet command in the command line. I get the message "illegal command: ipxnet" Is there a different way to setup ipx in dosbox-staging?
![Screen Shot 2020-06-05 at 11 06 18 AM](https://user-images.githubusercontent.com/66460314/83908849-9e00d900-a71c-11ea-8ea2-c21dc414241f.jpg)
![Screen Shot 2020-06-05 at 11 05 58 AM](https://user-images.githubusercontent.com/66460314/83908851-9f320600-a71c-11ea-8153-729974807b28.jpg)

**Comment by GranMinigun** [comment]
Have you built it yourself? If you're on Linux, make sure you have `libSDL2_net` installed, as it's an optional build dependency, IIRC.

**Comment by acegary** [comment]
I haven't. I just downloaded the prebuilt Mac OS version.

**Comment by GranMinigun** [comment]
Calling for @kcgen and @dreamer then. Maybe they could say something.

**Comment by kcgen** [comment]
Thanks for the heads up @GranMinigun and for the report @acegary!

I had to check, and indeed SDL_net-related functionality is knocked out of the macOS prebuilt binary because `brew` does not provided a static library to link against (screenshots are another casualty here for the same reason).

But we can definitely give the build a try.  It's eight commands that you can copy & paste here:

https://github.com/dosbox-staging/dosbox-staging/blob/master/BUILD.md#macos-procedures

For a standard everything-included build, run the commands in these macOS sections:
 - Xcode Installation (you might already have this)
 - Install the Brew Package Manager and Dependencies
 - Skip all of the MacPorts section
 - Build a macOS Binary, and just run the `Clang` command, and nothing else.

At that point, your build should be in the `./src/` directory, called `dosbox`.

**Comment by acegary** [comment]
I don't have xcode currently installed. Do you think the functionality will come to future builds? I can wait and just use standard dosbox for network play in the meantime.

**Comment by kcgen** [comment]
> Do you think the functionality will come to future builds?

The future is now, @acegary! (fingers crossed, anyway :-)

[This new package](**https://github.com/dosbox-staging/dosbox-staging/suites/762438291/artifacts/7928783**) bundles the libraries along side the binary, and then modifies the binary to look for them locally.  Not sure if this will work, but we can try. 

https://github.com/dosbox-staging/dosbox-staging/actions/runs/126597892

Curious how it goes!

**Comment by kcgen** [comment]
@acegary , when you have a chance, can you try this macOS build that includes the SDL2_net library? https://github.com/dosbox-staging/dosbox-staging/suites/762438291/artifacts/7928783

**Comment by acegary** [comment]
Hi, @kcgen. I wasn't able to open the build. I received an error message. I do have Gatekeeper completely disabled at the terminal level. 
![Screen Shot 2020-06-09 at 9 47 12 AM](https://user-images.githubusercontent.com/66460314/84176696-a6b42080-aa36-11ea-929a-c9a1fa7d7eb3.jpg)

**Comment by kcgen** [comment]
Thanks for trying it @acegary .  Are there details you can get from this dialog box? (everything looks greyed out.. so maybe not).

If you can drop to the command prompt and run `otool -L dosbox` in the directory where your dosbox binary exists, that command will print the libraries dependencies and where they exist in the filesystem. If you can paste the output, it might help us figure out what's still needed (or if we have a taken a different approach, like pure static libs).  Thanks!

**Comment by acegary** [comment]
Here is the text from the "report" button.
[report01.txt](https://github.com/dosbox-staging/dosbox-staging/files/4755771/report01.txt)

**Comment by kcgen** [comment]
That report was helpful; thanks @acegary! The new build is underway and will appear here:

https://github.com/dosbox-staging/dosbox-staging/actions/runs/130499038

(should be finished up in ~3 minutes)

**Comment by acegary** [comment]
Qapla! It works. And the ipxnet command is working. Thanks so much!

**Comment by kcgen** [comment]
thank for the confirmation @acegary! Promoting this for PR.

**Comment by kcgen** [comment]
@acegary , I've put together a new package linked statically per @dreamer's suggestion.  I was originally worried this was going to involve some rather nasty work-arounds, but found a workable compromise.

Build is here: https://github.com/dosbox-staging/dosbox-staging/actions/runs/132262677

`otool`'s show no depedencies on `/usr/local/`, so my hunch is this _should_ work!

**Comment by dreamer** [comment]
@acegary can you confirm the new builds have this problem fixed? Can we close the issue?

**Comment by kcgen** [comment]
Tentatively closing this based on the `otool` output showing the release build no longer point to the /usr/local area, and don't link to any SDL2_net shared library (despite being configured with networking enabled).

@acegary , we'd still appreciate your feedback, and can reopen this if there are any issues remaining.
