### ISSUE TITLE
Log address of emulated memory block

### ISSUE THREAD

**Issue by daninthemix** [dosbox-staging/dosbox-staging#428]
Would it be a complete pain to have the emulated memory always start at the same memory location, to make it easier to create cheat tables? In the same way as PCSX2? That always creates its emulated memory region in the same place, so you can find a static memory address for some value, and it will be the same next time you run the emulator.

**Comment by dreamer** [comment]
What have you tried so far? Do you have an example of a specific application you investigated in a dosbox debugger and couldn't rely on memory offsets you had? (compile with --enable-debug option to enable dosbox debugger). What value for `memsize` do you have and did you use `loadfix` command?

**Comment by daninthemix** [comment]
I mean I haven't actually tried with DOSbox Staging, but with previous versions we had to go through this whole song and dance to find the base addresses before we could find in-game values:

https://fearlessrevolution.com/threads/7264/

**Comment by dreamer** [comment]
Do I understand correctly, that you're asking for support for modifying internal dosbox-staging memory from outside of the emulator?

**Comment by daninthemix** [comment]
No - I'm asking if it will be possible to make it so that DOSBox creates its virtual address space in a static location.

**Comment by dreamer** [comment]
@daninthemix no, it's not possible. User can change the emulated memory size, the value is not statically known (it's configurable via `memsize` option in `dosbox` section). Different memory sizes may work better or worse depending on the game (although the default of 16MiB is good for most games). And even if we made it static, the address would change depending on the build configuration, architecture, new features, etc.

I can add logging of the base address of buffer used for emulating memory - so you wouldn't need to debug each dosbox binary to learn base addresses to calculate game-specific offsets - this would alleviate your problem for the immediate future.

*However*, I can't guarantee we'll keep memory allocated as one large buffer forever (although we don't have immediate plans for changing it).

**Comment by daninthemix** [comment]
That would be great - if we could just read where the emulated memory starts from somewhere.

Thanks

**Comment by dreamer** [comment]
@daninthemix I added some logging to indicate what is the base memory address; can you test your usecase using this build: [Linux](https://github.com/dosbox-staging/dosbox-staging/actions/runs/137352288), [Windows](https://github.com/dosbox-staging/dosbox-staging/actions/runs/137352302), or [macOS](https://github.com/dosbox-staging/dosbox-staging/actions/runs/137352294)?

On start, these builds leave the following message in the log:
```
MEMORY: Base address: 0x7fe99efff010
MEMORY: Using 4096 DOS memory pages (16 MiB)
```

Hopefully, this base address should be enough to use Cheat Engine; if it will be enough, I will merge this change and it'll be released in 0.76.0.

*note to myself: branch po/log-mem-base-1*

**Comment by daninthemix** [comment]
That does sound ideal - how do you get the log? I ran the attached but the above wasn't in the console output window, and no logs were generated in the folder.

**Comment by daninthemix** [comment]
Sorry - appears I'm blind as well as a moron. Console outputs this:

MEMORY: Base address: 0CBBF020

**Comment by dreamer** [comment]
Oh, on Windows pointer values are being formatted differently than on Linux (uppercase and without `0x` prefix)? Interesting…

**Comment by dreamer** [comment]
@daninthemix Have you had a chance to test/confirm the logging of base address works for your use-case?

**Comment by daninthemix** [comment]
Yes, thankyou

**Comment by dreamer** [comment]
Whoa, it's not merged to master yet ;) We'll close it after it will be merged-in.

**Comment by daninthemix** [comment]
BTW, if you haven't already can you make sure DOSBox Staging supports shaders? They were added to DOSBox SVN as of r4319 https://github.com/tyrells/dosbox-svn-shaders (means you can directly use e.g. CRT shaders).

**Comment by dreamer** [comment]
dosbox-staging supports shaders already :) you can test them even in [0.75.0 release](https://dosbox-staging.github.io/v0-75-0/#glsl); we're merging new developments from SVN as soon as they appear (unless we find they break stuff).

Also, for 0.76.0 we are going to bundle some of those shaders @tyrells ported (probably not all yet); he was kind enough to help us with cleaning that code area already :)

**Comment by daninthemix** [comment]
Awesome!

All we need now is save states!

**Comment by dreamer** [comment]
Save states are being discussed here: #313; unfortunately, this feature is problematic and we won't include it anytime soon (details in the issue).

**Comment by dreamer** [comment]
@daninthemix This change will be included in upcoming 0.75.1 bugfix release and 0.76.0 stable release (I don't know the timeline yet though).

**Comment by aqrit** [comment]
@daninthemix

Having `MemBase` is useful while developing new cheats.

However...
“Cheat Tables” for mass distribution should be keyed to a known point within the game executable.
This allows cheats to work with any emulator* or emulator revision.

Assuming all memory locations are declared as `base + offset`...
Make `base` the address of some string in the game, rather some emulator specific variable.

For example, take Mortal Kombat 1 (patched UltraTech release),
If we declare `base` as the address of the string "DOUBLE ICE BACKFIRE"
then we know that Player1’s Health value is at `base + 0x1EEB8`.
This cheat should work with all dosbox revisions and ntvdm.


*there is this whole other thing with hot patching game code from an external process,  if the emulator is using some kind of dynamic recompiler...

**Comment by dreamer** [comment]
@aqrit if you have further suggestions on how to make dosbox-staging easier to use for Cheat Engine users, I am all ears, otherwise I think this suggestion would probably work better in CE forums :)

About patching game running inside dosbox-staging using an external process - the only future-proof way to doing that is by disabling dynamic recompiler (use `core = normal`) - but for some games (mostly mid to late 90s) it will result in bad performance.
