### ISSUE TITLE
Deprecate `output = surface`

### ISSUE THREAD

**Issue by MovAX0xDEAD** [dosbox-staging/dosbox-staging#433]
Hi, 
- My CRT Display support hardware resolution 640x400 (added it with Custom Resolution Utility to windows registry) and <= DOSBOX 0.74 versions use it as fullscreen without BSODs
Display also support hardware 640x480, no need to add it manualy, it already report this resolution in EDID

- Appllication: Dungeon Keeper Gold, dkeeper.exe
This game uses three resolution and dynamicaly switch between:
640x480 - first load screen, menu screens
320x200 - cinematics
640x400 - in-game resolution

- no BSOD if game started in Window mode

- BSOD occurs before or when game try to show first load screen, game started from 640x400 fullscreen DOSBOX command prompt:
_MAIN: Draw resolution: 640x400, pixel aspect ratio: 1.20
MAIN: Emulator resolution: 640x480_

- Settings:
fullresolution   = original
output           = surface
texture_renderer = auto
scaler    = none

EDIT: details formerly provided in the title moved there for lisibility:
BSOD at .text:014903C0 (mov [eax], ecx), Windows 7 x64, v0.75.0, FullScreen 640x400

**Comment by dreamer** [comment]
Does it happen with `output = texture` as well? Surface is generally problematic and should not be used (despite it being the default for other versions of dosbox).

**Comment by MovAX0xDEAD** [comment]
> Does it happen with `output = texture` as well? Surface is generally problematic and should not be used (despite it being the default for other versions of dosbox). Also, does your display support 320x200?

1) No BSOD if **output = texture**, you are right, it occurs only with surface mode.
I think 320x200/320x240 is not supported by videocard drivers (nvidia 368.69), minimal available res is 640x400

2) Is .PDB files available for dowloaded (matched with binary Releases)?

**Comment by dreamer** [comment]
@MovAX0xDEAD can you also test `ouput = texture` with `texture_renderer = software`? That's the option we will probably use as fallback in the future if someone decides to use "surface" when the code for handling "surface" will be removed.

We don't offer PDB files for download, but it's really easy to compile dosbox-staging on Windows - you need VS 2019 (some people reported 2017 works as well, but we don't test it) and install build dependencies using vcpkg: https://github.com/dosbox-staging/dosbox-staging#visual-studio-2019-or-newer If you have VS and vcpkg installed, the whole procedure takes fewer than 5 minutes.

**Comment by MovAX0xDEAD** [comment]
> 
> 
> @MovAX0xDEAD can you also test `ouput = texture` with `texture_renderer = software`?
Hi Dreamer,
No BSOD with any combination:
texture_renderer = software
texture_renderer = opengl
ouput = texturepp
ouput = opengl

if surface mode is deprecated, should i close issue ?

**Comment by dreamer** [comment]
@MovAX0xDEAD thank you for testing and confirmation; yes, surface is to be considered deprecated :)

I will close this issue myself - as soon as I'll create a task for myself to actually remove the surface support (because I keep it in the back of my head while it should be in the backlog).

**Comment by johnnovak** [comment]
Do we still want to get rid of `surface` @kcgen? I think the answer is yes, just double checking.

**Comment by kcgen** [comment]
> Do we still want to get rid of `surface` @kcgen? I think the answer is yes, just double checking.

Absolutely. Even though `surface` might be the only output mode usable on obscure platforms (say, like the OpenIndiana or some BSD virtual machines), practically these are often poor performing configuration lacking hardware acceleration and not actually used for gaming.

Staging's SDL2-based video pipeline (in sdlmain.cpp) is in dire need of streamlining and simplification (it's dangererously close to the _"too complex, won't touch it"_ zone, like the mapper), so hopefully unloading surface will help simplify sdlmain and make a rewrite just a tiny bit more doable.

**Comment by GranMinigun** [comment]
SDL2 has software renderer (see `texture_renderer` hint), so there shouldn't be any need for another one. Do you plan some major overhaul of rendering pipeline, windowing, or `sdlmain.cpp` as a whole? Or just some smaller-ish changes?

**Comment by johnnovak** [comment]
> Absolutely. Even though `surface` might be the only output mode usable on obscure platforms (say, like OpenIndiana or some BSD virtual machines), practically these are often poor performing configuration lacking hardware acceleration and not actually used for gaming.

Yeah, I'm not against making the lives of people on obscure/legacy hardware a bit easier _in general_, _ but with the caveat of not complicating the codebase substantially and adding maintenance burder. At the end of the day, you don't want to make your life as a developer harder at the expense of the 99.99% of the user base.

> Staging's SDL2-based video pipeline is in dire need of streamlining and simplification (it's dangererously close to the "too complex, won't touch it" zone, like the mapper), so hopefully unloading surface will help simplify sdlmain and make a rewrite just a tiny bit more doable.

My thoughts exactly. I would like to see all unnecessarily cruft removed first, then focus on the OpenGL (and Vulkan, eventually) shader pipeline myself — I'll leave the non-shader parts to someone else, just to spread the love 😬 

Interesting that you brought up the mapper; that's another area that needs to be burnt to the ground wholesale, and I've been meaning to write up a high-level proposal for the new mapper, so thanks for reminding. Too many ideas! 😅 But here's the TL;DR: just mimic WinUAE, as their approach is top-notch and very flexible.

> Do you plan some major overhaul of rendering pipeline, windowing, or `sdlmain.cpp` as a whole? Or just some smaller-ish changes?

Complete overhaul of the shader pipeline, and it will be a The Nuclear Solution:tm:  😈 The existing single GLSL shader case will be like a 5% specialisation of the full range of possibilities.

**Comment by johnnovak** [comment]
After 3+ years we got there 😎
