### ISSUE TITLE
Emscripten builds being considered?

### ISSUE THREAD

**Issue by necro-nemesis** [dosbox-staging/dosbox-staging#434]
Seemed WebAssembly was the way this was getting reinvigorated and going before it last went into hiatus.

**Comment by dreamer** [comment]
Just to be clear: our upstream does not support emscriptem nor WebAssembly targets at all - all versions of DOSBox working via browser are forks. I've seen several of those forks but I don't know which one (if any) is actively maintained.

If someone is interested in porting changes from those forks to make dosbox-staging builds targetting WebAssembly, then those changes will be welcome here - as long as our quality standards are met. Preferably we would like these targets to be included in CI as well to prevent accidental regressions.

As for viability - I can't comment, I haven't seen those patches myself.

**Comment by necro-nemesis** [comment]
Possibly not the most recent but likely one of the most predominant is: https://github.com/dreamlayers/em-dosbox as a result of it's use here: https://help.archive.org/hc/en-us/articles/360004651032-MS-DOS-Emulation

**Comment by maximilien-noal** [comment]
JS-DOS 7 is on the way.
JS-DOS 6.X was actively maintained before JS-DOS 7 was being developped.
It contains its own fork of DOSBox targeted for WASM, and a lot of typescript/javascript around it.
https://github.com/caiiiycuk/js-dos
From the README, here is the discord: https://discord.com/invite/hMVYEbG
I'm just a user who searched a lot into this topic before setting on JS-DOS.

**Comment by kcgen** [comment]
Emscripten JavaScript builds are not being considered at this time. If someone is serious about this and can commit to working on and supporting this, then please update this ticket. 
Until then, we will close this as it's currently outside the scope of staging.
