### ISSUE TITLE
Hey, its been awhile since installed a dos game. need help with Rise of the tried installation. 

### ISSUE THREAD

**Issue by DOOMMARINE117** [dosbox-staging/dosbox-staging#437]
what is the mount command?

i have the game located in: C:\Program Files(x86)\RTCW\wolf3d\ROTT its the extreme rise of the tried version.

whata re the mount commands again? 

i have dosbox located in: C:\DOS\DOSBOX

**Comment by kcgen** [comment]
Hi @DOOMMARINE117 ,

Here's the post that helped you get Wolf3D running:

https://github.com/dosbox-staging/dosbox-staging/issues/360#issuecomment-628235421

Plus, see the comments following that, as it lead to success on your side.  Good luck!

**Comment by DOOMMARINE117** [comment]
cool, thanks.
