### ISSUE TITLE
[Suggestion] to add an "emergency exit" combo key

### ISSUE THREAD

**Issue by nemo93** [dosbox-staging/dosbox-staging#445]
### Proposed feature
Like on some emulators (ie Retroarch) it's possible to quit the running program by entering a specific combination on the keyboard or joypad. It'd be nice to have such mechanism on Dosbox-staging too. 

To be able to set or even to rely on an existing "retroarch.cfg" file would be nice. So that Dosbox-staging could use the value already set in that file. Today I'm using a combination of Start+Select to exit Retroarch by setting the following:
```
input_enable_hotkey_btn = "6"
input_exit_emulator_btn = "7"
```
### Reason for change
In case some games/programs hang or take forever to get to the in-game menu to have a way to exit Dosbox immediately without having to "kill" it will be helpful.

### Additional context
I'm running Dosbox-staging exclusively on a Pi (no desktop). Whenever a program hangs or for some reason is slow to run the only way I have to exit the game is to SSH to the Pi and kill Dosbox process. I'm extensively testing "Staging" these days and to be honest it's a pain on the Pi :-)

**Comment by kcgen** [comment]
`Ctrl + F9` is the default for quitting; does that work on your Pi? (I know the Pi comes with a UK keyboard layout, which can sometimes mess things up).

**Comment by nemo93** [comment]
Oh my... Ctrl+F9 indeed. Silly me /o\ There might some case(s) where it didn't work but as I'm a bit short of time lately and couldn't reproduce I'll close this ticket. Thanks!
