### ISSUE TITLE
Overlay for better user feedback - e.g. to display cycles on-screen

### ISSUE THREAD

**Issue by nemo93** [dosbox-staging/dosbox-staging#447]
### Proposed feature
Whenever a game/program is being launched to have an overlay somewhere on the screen (say on the lower left) to inform user on how many cycles are currently set would be helpful. Also such overlay would appear anytime the number of cycles is being incremented/decreased by Ctrl+F11/F12.

### Reason for change
This info might be provided if you're running Dosbox from the command-line or from a desktop environment but on a Pi (with say Retropie) you usually run program straight from a frontend and from the framebuffer. The number of cycles doesn't show up.

### Additional context
I'm running Dosbox-staging exclusively on a Pi (no desktop) and with Retropie.

**Comment by dreamer** [comment]
Yes! Excellent suggestion :)

We were planning to introduce such overlay for giving users feedback about re-mounting floppies/CDs (with ctrl-f4), but using it for displaying change in cycles makes sense as well. Putting it straight to accepted/planned features :)

**Comment by GranMinigun** [comment]
Probably could be useful to look at Dolphin's overlay. Network messages and stats, for instance.

**Comment by kcgen** [comment]
Yeah, when displayed on today's wide-screen TVs and monitors, these oldschool 4:3 systems offer a lot of unused screen space. 

I had a crazy idea that you could render a little version of the device (be it a NES, IBM Jr, SNES, Amiga, etc) in the unused screenspace, and have it display any physical characteristics to match what's going on in the emulator.

The IBM would show its little CD drive opening and closing, or floppy being inserted, etc. And perhaps the speed indicator LCD could reflect cycle count.  The HDD led would flicker during read and write operations.  

And perhaps for serial modem operations, a little USR Robotics sportster would be there with its various tx, rx, dsr, dtr, light blicken away on actual events :-)

**Comment by Max833** [comment]
I love this idea.

**Comment by Burrito78** [comment]
@johnnovak Said he would like to work on this recently!
https://github.com/dosbox-staging/dosbox-staging/issues/794

**Comment by johnnovak** [comment]
> @johnnovak Said he would like to work on this recently! #794
> 
> The MT-32 display is one specific use case in the issue above. But the basic functionality would enable other OSDs too.

Yes and I have a half-written proposal with UI mockups, I just need time to finish it and I've been quite busy with work lately.

**Comment by johnnovak** [comment]
See main discussion & plans about the OSD feature here:
https://github.com/dosbox-staging/dosbox-staging/discussions/1953

**Comment by johnnovak** [comment]
Closing because we have a plan how to make this happen: https://github.com/dosbox-staging/dosbox-staging/discussions/1953

Once I start working on it, I'll create individual tickets for each sub-task I'm implementing.
