### ISSUE TITLE
[Alley Cat] gfx glitches

### ISSUE THREAD

**Issue by nemo93** [dosbox-staging/dosbox-staging#458]
**Describe the bug**
Vertical "glitchy" lines appear on almost any screen of this game. Exception being on the menu/difficulty selection where there's only lines of text. Game itself is running fine fullspeed with sound.

**To Reproduce**
Run the game with `cat.exe` (easy given there's just one file :)).

**Expected behaviour**
No glitch on screen (check [this video](https://www.youtube.com/watch?v=uZDG4dlU5uY) as a reference).

**Environment (please complete the following information):**
- Raspberry Pi4 4GB / Buster / 4.19.118-v7l+

**Version of dosbox-staging:**
- `git describe` command:
```
 $ git describe
v0.76.0-alpha-199-g726e60cd
```

**Configuration parameters:**
```
machine  = vesa_nolfb
machine  = cga
```
=> same outcome
Mem settings:
```
xms            = true
ems            = false
umb            = true
```

**Additional context**
Haven't tried on SVN or "Dosbox-core".

**Comment by kcgen** [comment]
This is what I'm using for `cat.exe` and `tandycay.exe`, and both appear perfect. 

``` text
[cpu]
core=dynamic
cycles=fixed 50

[dosbox]
machine=tandy
memsize=1

[render]
aspect=true

[gus]
gus=false

[dos]
xms=false
ems=false
umb=false

[speaker]
pcspeaker=true
tandy=on
disney=false

[sblaster]
sbtype=none
```
![2020-06-23_03-27](https://user-images.githubusercontent.com/1557255/85393693-43c88c00-b502-11ea-94db-1191c642d005.png)

If you change cycles to `5` you can watch its startup animation similar to what you'd experience on a real 8086 or 286. But at `50` cycles (which I use for playing it), goes too fast to really appreciate the layered intro drawing sequences.

**Comment by nemo93** [comment]
Awesome. I'll try that. One of the few games where you could play as a kitty :D

**Comment by kcgen** [comment]
> One of the few games where you could play as a kitty
That's everytime for me :-) It's hard enough as it is!

**Comment by nemo93** [comment]
Just tried your settings @kcgen and I'm afraid those vertical stripes are still there :( Please note I do have only the `cat.exe` version.

**Comment by dreamer** [comment]
@nemo93 does your version have the same checksum?
```
[dreamer_@case ALLEYCAT]$ sha1sum *
77d7b7a613d4fa3e707f3c90d368032745a8405a  CAT.EXE
2bc5622975034ed7e4078a7db230c7f886672c39  TANDYCAT.EXE
```
Tested without any special tweaking, `cat.exe`, noticed no glitches; maybe related to running on the framebuffer?

**Comment by nemo93** [comment]
They differ:
```
$ sha1sum CAT.EXE
db64758c13d7e34546e85bba5aea36b9e0a2e922  CAT.EXE
```
I'll try finding the same exe as yours and give it another try.

**Comment by nemo93** [comment]
Ok definitely it was my version that was corrupt. After finding another executable with same sha1 the game works flawless this time. Yay :)

```
$ sha1sum CAT.EXE
77d7b7a613d4fa3e707f3c90d368032745a8405a  CAT.EXE
```
