### ISSUE TITLE
Change the color and brightness of the monochrome display

### ISSUE THREAD

**Issue by maximus105** [dosbox-staging/dosbox-staging#465]
**Describe the solution you'd like**
Please add the ability to change the color and brightness of the monochrome display in the .conf file as in DOSBox-X:
[dosbox]
machine = cga_mono
[render]
monochrome_pal: Specify the color of monochrome display.
Possible values: green, amber, gray, white
Append 'bright' for a brighter look.
Possible values: green, amber, gray, white.

**Comment by dreamer** [comment]
@maximus105 you know you already can change the CGA monochrome palette using F11?

**Comment by maximus105** [comment]
@dreamer Yes I know. But I wanted it to be possible to configure in the .conf file, as in DOSBox-X.

**Comment by johnnovak** [comment]
This has been implemented in ce533d038654a359, closing.
