### ISSUE TITLE
Add `MODE` command

### ISSUE THREAD

**Issue by maximus105** [dosbox-staging/dosbox-staging#471]
**Describe the solution you'd like**
Add the MODE command and the expanded display of the MEM command as in DOSBox-X:
For example, mode con rate = 32 delay = 1 (to speed up the repetition of keystrokes).

**Additional context**
![command_001](https://user-images.githubusercontent.com/58270614/86144471-60665480-bafe-11ea-9eb1-17e487660413.png)
![command_000](https://user-images.githubusercontent.com/58270614/86144469-5e9c9100-bafe-11ea-856c-413c6bc6af86.png)

**Comment by dreamer** [comment]
MODE - yes, we will probably port it; there are set of utilities (TEXTUTIL) to change modes, but having this functionality built-in makes sense.

MEM - is there any reason to port this command? AFAIK It does not improve game compatibility in any way.

**Comment by dreamer** [comment]
Edited the title, because it should be one feature request per issue.

**Comment by maximus105** [comment]
> MEM - is there any reason to port this command? AFAIK It does not improve game compatibility in any way.

Yes, it makes sense. This gives a more accurate idea of how much memory is available or how much resident programs are in memory. For example, file managers for DOS.

**Comment by dreamer** [comment]
Why does it matter? If you want more memory, configure more memory in .conf file. What file manager?

**Comment by Wengier** [comment]
@maximus105 If you want to use the various extended commands, you can always use DOSBox-X instead. There are much more commands in DOSBox-X's Z drive than DOSBox-staging's Z drive.

**Comment by NicknineTheEagle** [comment]
> 
> 
> Why does it matter? If you want more memory, configure more memory in .conf file. What file manager?

This only matters for apps that use extended memory, you only 640 KB of base memory -which is ought to be enough for everybody-. Because DosBox doesn't need any drivers or memory managers, it has whooping 632 KB of free base memory upon clean boot but running into memory capacity is still not out of the question.

**Comment by dreamer** [comment]
If anyone will come up with a combination of game / TSRs / file manager (I presume it was about something like Norton Commander), that won't work with emulation options currently available in dosbox-staging, then feel free to create a request for adding `mem` command.

This issue is about `mode` command because I don't want to have multiple feature requests in 1 issue.

**Comment by kcgen** [comment]
There are many excellent off the shelf DOS mode settings tools.  Search for 'vmode dos'.  Closing.

**Comment by xyzzy42** [comment]
In case anyone comes across this like I did.

vmode can only set video modes.  Not the keyboard repeat rate or serial port settings, etc.  So if that's what you want, no need to bother finding it.

You can get a DOS binary for mode.com from FreeDOS, here https://www.ibiblio.org/pub/micro/pc-stuff/freedos/files/dos/mode/2015/

**Comment by johnnovak** [comment]
@xyzzy42 You don't need an external MODE command to set the key repeat/delay and the text mode. We already have a quite full-featured built-in MODE command:

<img width="1179" height="940" alt="Image" src="https://github.com/user-attachments/assets/6ae5725a-603a-4a3b-b90b-157f425d6cd3" />

**Comment by xyzzy42** [comment]
Even better answer.  I see the mode command is in the 0.82.0 changelog.  Unfortunately, that just didn't show up in a search, while this issue did.  It appeared to have been closed with a won't implement, so I thought that was it, the only answer is get an external mode command.  I'm still using 0.81.2, from a distro package, which doesn't have the internal mode.

**Comment by MasterO2** [comment]
> Even better answer. I see the mode command is in the 0.82.0 changelog. Unfortunately, that just didn't show up in a search, while this issue did. It appeared to have been closed with a won't implement, so I thought that was it, the only answer is get an external mode command. I'm still using 0.81.2, from a distro package, which doesn't have the internal mode.

So logically speaking, your next course of action is **to upgrade to 82.0** or later.  😄

**Comment by johnnovak** [comment]
>  Unfortunately, that just didn't show up in a search, while this issue did.

Use the awesome search feature on our website 😎 

> I'm still using 0.81.2, from a distro package, which doesn't have the internal mode.

There are only disadvantages to using those distro repackagings of Staging. Just download our statically linked official Linux release from our website.
