### ISSUE TITLE
Audio issues in Wipeout (1995)

### ISSUE THREAD

**Issue by nemo93** [dosbox-staging/dosbox-staging#474]
As far as I recall this game has sfx (sound effects). For every "selection" on the main menu, or in-game while hovering a "bonus pad" or whenever hitting a wall, etc. a sound should be heard. 

Several online videos seem to confirm that fact:
https://www.youtube.com/watch?v=A7WcKRTPz4w
https://www.youtube.com/watch?v=EC2YFqqN5Qk

However I can't hear any sfx currently on Staging (`v0.76.0-alpha-256-gc047d1a1`). Music (CDDA) is playing fine - which is by far the most important in that game :-D I've tried with both SB16 or GUS despite manual says it's not supported. GUS is supported indeed and you even get a nice message on launch to inform you about it! Every time same outcome => only CD music.

There's no install or setup with that game. You just pop the CD in the drive and run it with `WIPEOUT.BAT`.

Do you confirm it's possible to hear sfx for that game in Staging?

**Comment by dreamer** [comment]
Interestingly, other comments under YouTube videos confirm there's no sound effects. I've seen one report saying the game works well in DOSBox 0.72, so perhaps it worked well and then regressed. I'll test in the evening.

**Comment by dreamer** [comment]
@nemo93 Just tested in latest master and SFX in Wipeout works correctly :) (at least in the version of the game, that I tested (eXo).

However, when testing for the first time I was convinced sound effects are not working, but turns out it's was caused by very weird UI in menu:
![Screenshot from 2020-07-01 23-04-36](https://user-images.githubusercontent.com/3967/86291569-6daf3c00-bbef-11ea-8eae-ede5fdc6a57a.png)

This SFX slider is NOT for volume up/volume down! It's balance between SFX and CD audio (very weird solution). Move it all the way left to get loud SFX and no CD audio, move it all the way right to no SFX and loud CD audio.

As a side note, the game works waaay too fast on my laptop - with default settings menu was working so fast, that it was hard to operate menus; after I limited cpu.cycles to fixed 60000, the game seems to be perfectly playable.

**Comment by kcgen** [comment]
> This SFX slider is NOT for volume up/volume down! It's balance between SFX and CD audio (very weird solution). Move it all the way left to get loud SFX and no CD audio, move it all the way right to no SFX and loud CD audio.

![dt190918](https://user-images.githubusercontent.com/1557255/86296951-ee017d00-bbae-11ea-9567-7ba679b421bb.gif)

I'm definitely in the half that need the manual :laughing:

**Comment by nemo93** [comment]
🤦‍♂️ Thanks for that @dreamer and sorry for the time waste. The worst thing is that I tried to get to the left but I really have to go to extreme left to start hearing something. Definitely sfx are there and all is working ok. 

This game remains slow for now on pi4 (~35.000/same as pi3).

**Comment by dreamer** [comment]
@nemo93 it's not a waste of time - we have another reference point in a quest to make the dosbox-staging playable with as many games as possible :)

And yeah, SFX is somewhat quiet in general, it's easily lost with CD audio on… I was hoping `mixer` will solve it (e.g. `mixer cdaudio 50:50` to change CD audio volume to 50%), but it… doesn't work?

@kcgen Any idea where to look about volume? Both 0.74-3 and staging do not seem to behave correctly when changing volume using mixer (or maybe I don't understand how to use this command); changing `sb` channel volume does not work at all; changing `cdaudio` does not work in dosbox-staging either; it "barely" works in 0.74-3 - I could hear the music being quieter only after I ran `mixer cdaudio 1:1` - but it was not 1% of volume, more like 90% (or maybe pure placebo effect).

**Comment by kcgen** [comment]
Yup, it's a bit nuanced: the CDDA subsystem is only initialized when a cdrom image is mounted (cue / bin / iso), so consequently the `CDAUDIO` channel also doesn't exist until that happens. 

So to adjust the CDAUDIO volume, mount first, then mix:

``` text
@echo off
imgmount d cd\cdrom.cue -t cdrom
mixer cdaudio 30
wipeout.exe
mount -u d
exit
```

**Comment by dreamer** [comment]
@kcgen oh, yes - I know `cdaudio` channel appears after mounting; changing volume with mixer does not work after imgmount.

I tried setting `mixer cdaudio 100:1`… we definitely have a regression compared to 0.74-3.

Reopening this issue.

**Comment by dreamer** [comment]
Just tested in SVN - the same bug - mixer does not change the left/right volume; bisecting for commit, that introduced the regression.

**Comment by dreamer** [comment]
OK, this is interesting; the "regression" (not sure if I can still count this as a bug) is introduced with d7597b8dd86b0e861d17edd9fbd1c6d06b6c4a31.

So it's probably not a bug - game overrides dosbox mixer by setting volume via sound blaster; this can be disabled via `sblaster.sbmixer = false`;

@nemo93 can you test with following settings:

```ini
[sblaster]
sbmixer = false

[autoexec]
cls
imgmount D ~/DOS/D/Wipeout/Wipeout.cue -t cdrom
D:
mixer sb 100
mixer cdaudio 30
wipegame.exe
exit
```
For me this results in properly loud, clear sound effects (but that weird slider in the sound menu does not work any more).

**Comment by kcgen** [comment]
@dreamer , you're one step ahead!

I was about to report `mixer cdaudio` works well for me, confirmed in mpxplay and Rayman (both using CDDA). I was preparing a stand-alone attachment w/ mpxplay just so you guys could confirm too.  

But after looking at that bisection code, indeed my working examples above both are with `sbtype = none`; and infact eliminate all of the sound devices just to isolate to CDDA behavior.

Even though I'm not beholden to reproducing hardware behavior when it harms the game authors intentions, my guess is this tethering of sbmixer to the CD audio volume is infact "correct" even with respect to the game authors.

Historically you had two configurations:
 - a CDROM that fed it's CDDA cable into your sound card, and then out to a one set of speakers/headphones.
 - an older CDROM drive without CDDA cable (and perhaps without a sound card), with a front audio jack.

`sbmixer = true` replicates the first setup, and is probably the most likely configuration for most gamers and game developers.

`sbmixer = false` replaces the second.  For a gamer, you would need two sets of speakers (one hooked up to your sound card, another hooked up to your CD player).  Some people definitely /did/ do this, especially in the earlier days fo CDDA and when sound cards were known to add noise or 50Hz/60Hz power-hum (which was sadly very common). 

My take is that this is good solution - but not obvious to map to the historical hardware configurations, even for us old time DOS gamers who actually understand both hardware configurations! Argh.

**Comment by nemo93** [comment]
@dreamer with your settings, it works just as intended. Thanks. I never took time to study this `mixer` command but now it's the time!

```
[sblaster]
sbmixer = false

[autoexec]
cls
imgmount D ~/DOS/D/Wipeout/Wipeout.cue -t cdrom
D:
mixer sb 100
mixer cdaudio 30
wipegame.exe
exit
```

**Comment by kcgen** [comment]
This kind of info would be great for the wiki!
@nemo93 , are you ok with closing this issue?

**Comment by nemo93** [comment]
Definitely an additional entry to the wiki!

**Comment by dreamer** [comment]
BTW, @nemo93 - I added a link to Wiki in the sidebar on https://dosbox-staging.github.io/ :)

**Comment by nemo93** [comment]
Also FYI even if the manual states otherwise, GUS card is actually supported by this game. With the recent [rework on GUS](https://github.com/dosbox-staging/dosbox-staging/pull/541) done by @kcgen and @dreamer Wipeout sounds best with that soundcard :-)
