### ISSUE TITLE
[pi4] Another World running slow

### ISSUE THREAD

**Issue by nemo93** [dosbox-staging/dosbox-staging#485]
Hello, another question as I'm carefully handcrafting specific `.conf` files for each game tested as recommended by @kcgen. I'm facing an issue with _Another World_ (also known as _Out of this World_). 

On a pi4, no matter the number of cycles or parameters I'm passing to the game, it will always run in "slideshow" mode right from the start (including the first screen - the protection check). Setting too few cycles (ie. cycles = fixed 3000) will make the game even slower but increasing it to the current max on pi4 (~35.000) won't fix the slowdown. 

This game worked flawless on pi3. 

**Question**: Is there a specific setting to pass along which could explain why I can't get it fullspeed? I'm not aware of any. Adding EMS will prevent the game from running. Also changing the video card does nothing.

**Side note**: weirdly enough _Blake Stone_ games now require `cycles = fixed 30000` to run smooth on pi4. This is almost the current max number of cycles I could allocate on pi4! Setting `cycles = auto` will have those 2 games run in "slideshow" mode. If I'm correct those are based on Wolfd3D engine which is running very fine with `cycles = auto` or `cycles = fixed 3000`. I could raise a separate ticket for discussing this if required.

**Comment by dreamer** [comment]
I haven't tested Another World yet, but re: to side note.

Wold3D engine works bad with `cycles = auto` on x86_64 as well; it defaults to 3000 cycles, which is not enough to play this game comfortably (on some PCs it works fine with 3000 cycles, on other ones it kind-of works, on some it's a slideshow). We had this issue when handling Steam releases of games using Wolf3D engine (specifically Wolfenstein 3D, Spear of Destiny, and Super 3D Noah's Ark) and the fix was to raise the cycles in Boxtron database.

**Comment by kcgen** [comment]
Here's what I'm using on x86 and the Pi3; for what it's worth. 

Game's configured for Sound Blaster and a "fast" PC with 10 KHz output.

``` ini
[cpu]
core=dynamic
cycles=fixed 4500

[dosbox]
machine=vesa_nolfb

[mixer]
rate=22050

[midi]
mpu401=none
mididevice=none

[sblaster]
sbtype=sbpro1

[dos]
xms=false
ems=false

[speaker]
pcspeaker=no
tandy=off
disney=false

[gus]
gus=false
```

PS - The 10 Khz in the setup menu is a hint that the game likely supports SBPro1 or less (SoundBlaster Pro 1.x 22KHz, 8bit), so we can crank down the mixer rate to 22050 and if you want lower the mixer's buffers for tigher audio latency.

**Comment by nemo93** [comment]
Thanks to both of you once again. With the config provided by @kcgen the game is running again at fullspeed. The change of soundcard apparently helped (sb16 => sbpro1).
