### ISSUE TITLE
The Lost Vikings closes

### ISSUE THREAD

**Issue by daninthemix** [dosbox-staging/dosbox-staging#499]
I downloaded The Lost Vikings (its freeware now) packaged with an older version of DOSBox, and it runs fine.

When I drop a recent DOSBox staging build in there, the game closes as soon as it starts.

How can I troubleshoot this?

**Comment by dreamer** [comment]
@daninthemix can you post a link to The Lost Vikings so I could try to reproduce?

What OS do you use?

**Comment by daninthemix** [comment]
https://drive.google.com/file/d/1p6MRfcHChOJssfRViOx0hYeiRjMDlk1z/view?usp=sharing

Just run the 'Start the Game.bat' and it works. Soon as you replace the DOSbox / SDL files with a newer version (either DOSBox Staging or recent SVN builds), it just closes. At least for me. On Windows 10.

**Comment by daninthemix** [comment]
https://en.wikipedia.org/wiki/The_Lost_Vikings

"In 2014, the game was added to Battle.net as a free download emulated through DOSBox"

**Comment by MasterO2** [comment]
> 
> 
> I downloaded The Lost Vikings (its freeware now) packaged with an older version of DOSBox, and it runs fine.
> 
> When I drop a recent DOSBox staging build in there, the game closes as soon as it starts.
> 
> How can I troubleshoot this?

Can you post the output from the dosbox-staging status window when you run the game?

**Comment by daninthemix** [comment]
> > I downloaded The Lost Vikings (its freeware now) packaged with an older version of DOSBox, and it runs fine.
> > When I drop a recent DOSBox staging build in there, the game closes as soon as it starts.
> > How can I troubleshoot this?
> 
> Can you post the output from the dosbox-staging status window when you run the game? That might reveal why it's crashing.

Thing is the status window disappears as well when the main game closes. Any way to preserve / log it?

**Comment by dreamer** [comment]
I removed the download link to google drive. Yeah, at some point the game was freeware. But seems like it isn't any more; it was removed from classic games offered for download by Blizzard: https://www.blizzard.com/en-sg/download?show=classic and they haven't uploaded it to GOG like they did with their other DOS games.

Thanks, Blizzard! /s

If you were lucky to download it back then, then ok - but I can't host a link to the google drive download here.

I will try to reproduce the issue.

**Comment by MasterO2** [comment]
> 
> 
> > > I downloaded The Lost Vikings (its freeware now) packaged with an older version of DOSBox, and it runs fine.
> > > When I drop a recent DOSBox staging build in there, the game closes as soon as it starts.
> > > How can I troubleshoot this?
> > 
> > 
> > Can you post the output from the dosbox-staging status window when you run the game? That might reveal why it's crashing.
> 
> Thing is the status window disappears as well when the main game closes. Any way to preserve / log it?

Go to the search bar at the lower left hand corner of your screen, type cmd, and press enter.

In the new console window that appears, go into your dosbox folder and try to run Dosbox from there.  

For example:    cd  path\to\dosbox\folder

**Comment by dreamer** [comment]
OK, game is working fine in dosbox-staging, only the .conf file is busted. My guess is: SVN changed handling of current working dir compared to 0.74 version.

Let me clean things out and prepare instructions.

**Comment by dreamer** [comment]
OK, so self-extracting exe has following directory structure:
```
[dreamer_@case The Lost Vikings (1993)]$ tree -d
.
├── dosbox
│   └── Documentation
├── games
│   ├── games
│   │   └── TheLostV
│   └── TheLostV
└── Manual
```

Step 1: unpack download dosbox-staging and unpack it (I recommend without overwriting the files), so the path to executable would be like this: `The Lost Vikings (1993)\dosbox-staging\dosbox.exe`.

Step 2: copy file `games/games/TheLostV/dosbox.conf` to `games/games/TheLostV/dosbox-staging.conf`

Step 3: edit this file and replace the content with these settings:

```
[sdl] 
fullscreen=true
fullresolution=desktop

[dosbox] 
machine=svga_s3 

[render] 
glshader=sharp

[autoexec] 
mount c games
c: 
cd TheLostV 
VIKINGS
#exit 
```

Step 3: open PowerShell (or cmd.exe), cd into "The Lost Vikings (1993)" directory and run `.\dosbox-staging\dosbox.exe -conf games/games/TheLostV/dosbox-staging.conf`

If the game won't start (it didn't for me due to "copyright protection"), then in dosbox shell window run `setup.exe` and keep pressing enter (key seems to be pre-typed).

**Comment by daninthemix** [comment]
Thankyou sir! Just changing this part fixed it:

```
[autoexec] 
mount c games
c: 
cd TheLostV 
VIKINGS
#exit
```

Then as you say I got the "copy protection error", but simply hitting enter got me through that. Now the game runs, and I can use shaders and all the nice stuff with the new version!

Thanks again
