### ISSUE TITLE
No Gravis Ultrasound music in Hocus Pocus

### ISSUE THREAD

**Issue by DromedaryKing** [dosbox-staging/dosbox-staging#501]
**Describe the bug**
In the game Hocus Pocus, when running with Gravis Ultrasound for sound and music, there is no music. Sound effects work fine.

**To Reproduce**
Set up Gravis Ultrasound by enabling it, and pointing to a fully set up ULTRASNDPPL161 folder (I got mine from the VOGONS forum a while back), then set the game to use Gravis Ultrasound for its sounds and music, then run the game from HOCUSG.EXE or __HPGRVS.EXE. You'll know it's worked if you don't hear any music on the title screen and menus.

**Expected behaviour**
I expected there to be music.

**Environment:**
- Windows 10 64-bit.
- Ryzen 5 2600X CPU, AMD R7 370 GPU, three monitors, Ryzen keyboard and mouse, 5.1 surround sound using the analogue audio outputs of the onboard sound of a Aorus B450 Elite motherboard.

**Version of dosbox-staging:**
The latest Windows build, 0.75.

**Configuration parameters:**
[dosbox-staging.conf.txt](https://github.com/dosbox-staging/dosbox-staging/files/4928038/dosbox-staging.conf.txt)

**Additional context**
I've played other games with Gravis Ultrasound, but this is the first one that I believe uses the GUS's MIDI capabilities. I've heard DOSBox has some issues dealing with GUS MIDI, but I'm not very familiar with the ins and outs of it.

**Comment by MasterO2** [comment]
> 
> 
> **Describe the bug**
> In the game Hocus Pocus, when running with Gravis Ultrasound for sound and music, there is no music. Sound effects work fine.
> 
> **To Reproduce**
> Set up Gravis Ultrasound by enabling it, and pointing to a fully set up ULTRASNDPPL161 folder (I got mine from the VOGONS forum a while back), then set the game to use Gravis Ultrasound for its sounds and music, then run the game from HOCUSG.EXE or __HPGRVS.EXE. You'll know it's worked if you don't hear any music on the title screen and menus.
> 
> **Expected behaviour**
> I expected there to be music.
> 
> **Environment:**
> 
>     * Windows 10 64-bit.
> 
>     * Ryzen 5 2600X CPU, AMD R7 370 GPU, three monitors, Ryzen keyboard and mouse, 5.1 surround sound using the analogue audio outputs of the onboard sound of a Aorus B450 Elite motherboard.
> 
> 
> **Version of dosbox-staging:**
> The latest Windows build, 0.75.
> 
> **Configuration parameters:**
> [dosbox-staging.conf.txt](https://github.com/dosbox-staging/dosbox-staging/files/4928038/dosbox-staging.conf.txt)
> 
> **Additional context**
> I've played other games with Gravis Ultrasound, but this is the first one that I believe uses the GUS's MIDI capabilities. I've heard DOSBox has some issues dealing with GUS MIDI, but I'm not very familiar with the ins and outs of it.

Iirc, in your autoexec section, you will need to add the following line and then save your config:

set ultramid=C:\ULTRASNDPPL161\midi

**Comment by DromedaryKing** [comment]
> If I'm not mistaken, in your autoexec section, you will need to add the following line and then save your config:
> 
> set ultramid=C:\ULTRASNDPPL161\midi
> 
> (the above is case insensitive).
> 
> Setting this variable tells GUS where your midi instruments are, so that it can play the music.

Nope, didn't work. Tried changing "midi" to "MIDI" to match the fact that my MIDI folder in ULTRASNDPPL161 is uppercase, still didn't work. Tried running ULTRAMID.EXE before running HOCUSG.EXE, didn't work.

**Comment by dreamer** [comment]
Pinging @kcgen, as he'll likely want to verify this against his branch with GUS improvements :)

I'll try to reproduce the problem on my end in the meantime.

**Comment by DromedaryKing** [comment]
Thanks. :)

A detail I forgot to mention: I've only tried this on the shareware version as I don't own the full game. I think I got my shareware copy from here: https://www.classicdosgames.com/game/Hocus_Pocus.html
I can upload my ULTRASNDPPL161 folder, if you think it might help find the issue.

**Comment by dreamer** [comment]
Hmm, so generally I had no issues with enabling GUIS in this game; steps:

1. Disable SoundBlaster, enable GUS in the .conf file: `sbtype  = none` and `gus = true` (perhaps disabling SB is not needed; I'm not sure).
2. I copied my `ULTRASND` directory directly to the emulated `C:` drive. If the directory is called `ULTRASND` then there's no need for setting any additional env variables in autoexec section. Do not overwrite `ULTRADIR` env variable to point to midi subdirectory.
3. cd into the game directory, run `SETUP.EXE` and select Gravis UltraSound for both music and audio
4. Start game…

**Comment by kcgen** [comment]
Also confirming that the GUS wavetable synth (and SFX) are working well per @dreamer's instructions.
@DromedaryKing - any luck?  

Just be sure to launch the game with the Gravis-specific batch file, which runs `ultramid.exe` first, then the Gravis-specific binary `__hpgrvs.exe`, like this:

``` text
@echo off
ultramid
__hpgrvs
ultramid -q -f
exit
```

**Comment by DromedaryKing** [comment]
Ah! Thanks, guys, it works. :)

I guess disabling the Sound Blaster and putting the ULTRASND in the game directory was what I needed to do. Maybe this slightly unintuitive process should be documented.

**Comment by kcgen** [comment]
Good stuff; and also couldn't agree more regarding the importance of documentation! 

I plan to write up some tips (including wavetable setup) with the small GUS changes I've been tinkering on, and will drop a link here when that lands, for future reference.

Thanks for the report here; it's a good reminder that config nuances are show stoppers:  the vast majority probably just switch back to SB, and forfeit the GUS experience.

**Comment by dreamer** [comment]
I would be very happy if someone wrote a quality tutorial, that we could publish on https://dosbox-staging.github.io/ - we're halfway there already with info prepared by @nemo93 : https://github.com/dosbox-staging/dosbox-staging/wiki/Gravis-Ultrasound-(GUS)

But it would need to contain all the info; e.g. I believe (again, not sure) not all games require the ULTRASND directory  - only the ones using `ULTRAMID.EXE` (Hocus Pocus is one of them). Also, I've never tested installation of improved patch files, so there might something more about that.

**Comment by kcgen** [comment]
> we're halfway there already with info prepared by @nemo93 : https://github.com/dosbox-staging/dosbox-staging/wiki/Gravis-Ultrasound-(GUS)

I didn't even see that; thanks for the ref @dreamer ! @nemo93, very nice work!  I'll add a bit to that page as well :-)
