### ISSUE TITLE
Coverity scan job does not work

### ISSUE THREAD

**Issue by dreamer** [dosbox-staging/dosbox-staging#517]
Not sure if it's a problem with Google Drive, Coverity, gdown, or something else…

https://github.com/dosbox-staging/dosbox-staging/runs/903124785#step:6:29

@kcgen any ideas?

**Comment by kcgen** [comment]
Glad you caught this; I was starting to wonder why I wasn't seeing new Coverity results!

Definitely something broken between the downloader (gdown) and google drive.. perhaps an API change that hasn't been incorporate by gdown (or hasn't been pulled into the apt repos yet), or perhaps there's some new argument(s) I need to feed gdown to keep it happy. 

Similar to clam, we can cache this download; so I will add this too when I look into it later today.  Also, Maybe there's a new Coverity package we can update to as well.

**Comment by kcgen** [comment]
Our version,.2019.03, is still the latest.  So that's one less thing to check:

``` text
Download Coverity Build Tool
Download Coverity Build Tool version for your platform here. Checksums: MD5.

Version: 2019.03
Updated: June 17th, 2019

Linux64
Linux32
Freebsd64
Freebsd32
Netbsd64
Netbsd32
Win64
Win32
MacOSX
Darwin (for Travis CI)
Linux (for Travis CI)
```

https://scan.coverity.com/download
