### ISSUE TITLE
Debugger improvements

### ISSUE THREAD

**Issue by kcgen** [dosbox-staging/dosbox-staging#542]
from Vogon's forum user Akuma:

- Can the debug-window be locked to 80x50 like in the windows version, resizing to a smaller windows breaks debugger on Linux.

- Copy and pasting large text fields hangs the debugger command field (workaround is to press F3, but its still annoying when you copy from the debugger window then accidentally paste that in).

- Focus messaging disabled/muted or in the debugger comment section

**Comment by Akuma-Git** [comment]
I second this :+1:

**Comment by dreamer** [comment]
Just did a brief testing on Linux, and debugger feature seems to be generally broken - UI randomly disappears, sometimes appear again. Perhaps debugger feature is not compatible with logs we write to in debug builds.

**Comment by Akuma-Git** [comment]
> Just did a brief testing on Linux, and debugger feature seems to be generally broken - UI randomly disappears, sometimes appear again. Perhaps debugger feature is not compatible with logs we write to in debug builds.
> 
> _edit_ it seems to be working correctly, with size locked to 80x50 when:
> 
>     * running in xterm
> 
>     * build has NDEBUG defined
> 
> 
> (I haven't tested copy/pasting)

I'll start some testing :smiley:

**Comment by Akuma-Git** [comment]
@joncampbell123: 
> ...I can't force a fixed size console in Linux, sorry.

Np, I think there is a way to trigger a refresh. I did some testing and after resizing the debugger got stuck as expected but 'F5/run' brought me back to DOS.
When I restarted debug.com to see what would happen it worked fine again.

So its reinitialized on start, which means that this function can be triggered when lines != 80.
A refresh just for Linux

**Comment by Akuma-Git** [comment]
> Just did a brief testing on Linux, and debugger feature seems to be generally broken - UI randomly disappears, sometimes appear again. Perhaps debugger feature is not compatible with logs we write to in debug builds.
> 
> _edit_ it seems to be working correctly, with size locked to 80x50 when:
> 
>     * running in xterm
> 
>     * build has NDEBUG defined
> 
> 
> (I haven't tested copy/pasting)

Debugger works fine in xterm, could not find anything on NDEBUG, what is it ?

**Comment by kcgen** [comment]
When you compile, add `-DNDEBUG` as a command line argument to `make`. This injects the preprocessor `#define NDEBUG` into each source file.

 (Also suggest scrubbing with `make clean` or `distclean` before hand just to ensure all objects are rebuilt with that defined)

**Comment by dreamer** [comment]
For the people who might not know `NDEBUG` is the standard C mechanism for disabling `assert` statements in code. We use it also for prevent printing additional logs, that are of interest to developers, but not to users (similar how "debugger" feature prints additional logs, but DOSBox "debugger" is very user-unfriendly and developer unfriendly IMO). We also explicitly mentioned it in [README.md build instructions](https://github.com/dosbox-staging/dosbox-staging#linux-macos).

**Comment by LowLevelMahn** [comment]
there are still features missing 

for example SoftICEs break on memory read/write

extending the debugger to ease reverse engineering could be really a pro argument for staging

**Comment by Burrito78** [comment]
Nobody answers, some fixes are probably there already, too many issues in on ticket.
