### ISSUE TITLE
Regression: non-english ASCII characters in batch files are not processed correctly any more

### ISSUE THREAD

**Issue by dreamer** [dosbox-staging/dosbox-staging#555]
**Describe the bug**
Regression was introduced by commit: ed1d1e1938f715e70e646aed3ee723bd46bd1449

Use this conf file [testpl.conf.txt](https://github.com/dosbox-staging/dosbox-staging/files/5090303/testpl.conf.txt) - it uses cp852 encoding.

**To Reproduce**
Run: `$ dosbox -conf testpl.conf.txt`. It displays "Unexpected control character" two times, and `echo` statement prints nothing.

**Expected behaviour**
This is what should be displayed:
```
Z:\>keyb pl
Keyboard layout pl loaded for codepage 852
Z:\>echo ęą
ęą
```

**Comment by dreamer** [comment]
@kcgen I think you'll want to handle this one? I can revert the commit if you prefer it.

**Comment by kcgen** [comment]
Yes; I will look into it ASAP; thanks for catching this @dreamer and providing reproduction steps.
