### ISSUE TITLE
libfluidsynth-2.dll missing from Windows master-branch packages

### ISSUE THREAD

**Issue by kcgen** [dosbox-staging/dosbox-staging#559]
Latest **master** Windows 64-bit zip was downloaded and run on a windows 10 desktop PC.

![missing_fluidsynth_dll](https://user-images.githubusercontent.com/1557255/90673342-7645eb00-e20c-11ea-9eb9-e4597260f609.PNG)

**Expected behaviour**
The `libfluidsynth-2.dll` should be packages with the executable resulting in successful executable launch.

**Comment by dreamer** [comment]
Doh!

Hopefully it'll work: `po/add-missing-fluid-dll-1` / 0d5d20b15b32efb00870cd126095fb7950170cdd

**Comment by kcgen** [comment]
One step further! It also hit me with missing `libiconv.dll`, `pcre.dll`, and `libintl.dll`

![libiconv dll,libprce dll,libint dll-missingl](https://user-images.githubusercontent.com/1557255/90684635-65ea3c00-e21d-11ea-88d6-fe534ca6c85e.PNG)

**Comment by kcgen** [comment]
Here's output from Dependency Walker when inspecting `libfluidsynth-2.dll`:

![fs_depwalker](https://user-images.githubusercontent.com/1557255/90685266-6505da00-e21e-11ea-9e57-35edaa8a4579.png)

**Comment by dreamer** [comment]
Heh, that's way more dependencies then I expected :( Not unacceptably-bad, but our Windows zip package grew considerably…

BTW, Wine seems better at displaying missing dependencies than Windows - it reports not only the missing .dll, but also which library/exec wants to load it :)

**Comment by kcgen** [comment]
When I saw pcre and friends, I thought we might be in for a dll dependency explosion, but fortunately they were the end of the line :-)
