### ISSUE TITLE
Vulkan support

### ISSUE THREAD

**Issue by fbaier** [dosbox-staging/dosbox-staging#565]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
Is there any chance in the future to see a support of Vulkan as an output renderer.
Perhaps to replace OpenGL.

**Describe alternatives you've considered**

**Additional context**

**Comment by Burrito78** [comment]
Vulkan will be implemented when we need it or when it is better. No need to keep a ticket open for this.

**Comment by Torinde** [comment]
Related:
- https://github.com/joncampbell123/dosbox-x/issues/6065

**Comment by johnnovak** [comment]
Using the new SDL3 GPU API is the way to go to add support for all rendering APIs with a single code path.

https://wiki.libsdl.org/SDL3/CategoryGPU

**Comment by Torinde** [comment]
> Using the new SDL3 GPU API is the way to go

@Grounded0, is that of interest for @GranMinigun?

>> I wouldn't touch SDL's GPU attempts with a ten feet pole. ...
>
> Given the circumstances, I'm left with no choice but to resign.

_Originally posted by @GranMinigun in https://github.com/dosbox-staging/dosbox-staging/issues/2450#issuecomment-1783937183_

**Comment by johnnovak** [comment]
> > Using the new SDL3 GPU API is the way to go
> 
> [@Grounded0](https://github.com/Grounded0), is that of interest for [@GranMinigun](https://github.com/GranMinigun)?
> 
> > > I wouldn't touch SDL's GPU attempts with a ten feet pole. ...
> > 
> > 
> > Given the circumstances, I'm left with no choice but to resign.
> 
> _Originally posted by [@GranMinigun](https://github.com/GranMinigun) in [#2450 (comment)](https://github.com/dosbox-staging/dosbox-staging/pull/2450#issuecomment-1783937183)_

A bit too late for that, isn't it? He's been ignoring us and our mentions for a couple of years now.

The rendering backend is now my area, so I'll do the SDLGPU transition probably later this year. Also, I have a quite firm vision about the future of the GUI and all things rendering related, so it will be probably 90% me. Pretty much one man show type of deal, otherwise we'd get in each others ways 😏
