### ISSUE TITLE
Add a help message for imgmount command

### ISSUE THREAD

**Issue by MasterO2** [dosbox-staging/dosbox-staging#567]
https://github.com/dosbox-staging/dosbox-staging/pull/506

@kcgen @dreamer 

Similarly to the merged pull request above for the DIR command, here's a good help explanation for IMGMOUNT:

```
mounts compact disc image(s) as dosbox-staging optical drive(s). 

Currently supported CD Images: ISO, BIN/CUE, GOG/CUE, GOG/INS, and GOG/INST file pairs.  

Note: CUE Files must be mounted in order to enable CD Audio for games that have it, instead of the BIN / GOG file.  

Examples of games with CD Audio: Quake 1, Redneck Rampage, and Blood.  

Image Mounting Example 1 mounts Doom 1's CD to install the game:  imgmount d c:\games\doom.iso -t iso
Image Mounting Example 2 mounts Quake 1's CD to enable CD Audio:  imgmount d c:\quake\quake1.cue -t iso
```

That part about CUE files in particular would also eliminate a lot of questions from people about how to mount CD Audio correctly.  This should be fairly trivial for dosbox-staging to add.

**Comment by MasterO2** [comment]
@dreamer @kcgen 

I have refined the imgmount extended help message some more, for when you guys get around to adding it to SHELL_CMD_DIR_HELP_LONG:

```
mounts compact disc image(s) as dosbox-staging optical drive(s)

also mounts floppy disk image(s) as dosbox-staging floppy drive(s)

Currently supported CD Images: ISO, CUE/BIN, CUE/GOG, INS/GOG, and INST/GOG file pairs

Currently supported Floppy Disk images: RAW, IMG

Currently supported Audio Files via an imgmounted companion CUE File: CUE/OGG, CUE/MP3, CUE/FLAC, CUE/OPUS and CUE/WAV

Note 1: CUE Files must be mounted in order to enable CD Audio for games that have it, 
instead of the BIN / GOG file. 

Note 2: For best results, make sure that the CUE file is mounted as dosbox-staging's D drive, 
because DOS games that use CD audio will expect to find the CD audio on that drive.

Note 3: A CUE/BIN file pair, or any of the file pairs mentioned above, 
must exist in the same directory in order for imgmount to mount the image properly.  

Examples of games with CD Audio: 

Blood: One Unit Whole Blood
Descent 2
Quake 1
Redneck Rampage  
Shadow Warrior

Imgmounting Examples:

1) Imgmount a CD image of Doom 1's installation CD as dosbox-staging's optical drive
at drive letter D:  

imgmount d c:\games\doom.iso -t iso

2) Imgmount the cue file of a Quake 1 CUE / BIN file pair to enable CD Audio:  

imgmount d c:\quake\quake1.cue -t iso

3) Imgmount a floppy disk image as dosbox-staging's A Drive: 

imgmount a c:\games\game.raw -t floppy

Replace c:\games\doom.iso, c:\quake\quake1.cue, or c:\games\game.raw with the actual location
on your PC's hard drive of the .iso file, .cue file, .raw file etc that you want to imgmount. 

Important: If your file location has any spaces in folder names, make sure that
you use opening and closing quotation marks in the imgmount command:

imgmount d "c:\my games\quake1.cue" -t iso
```

**Comment by dreamer** [comment]
@MasterO2 Thank you, but the commit message should:

1. List and describe all available switches.
2. Not invent yet another format - run `autotype` to see the correctly formatted help page. (BTW, @kcgen `autotype` should have -help switch)
3. Be brief and to the point - people looking for help will not read the help if it's few pages long. We can leave reference to the manual (which already has this info) or wiki page in the end of the help message. We also *do not* want to duplicate info, that is already described in detail in manual.
4. Fit into a single 80x25 screen.
5. (something for us to address outside of help message) Adapt to users' OS - Having example `imgmount C C:\games` is misleading for Linux users while `imgmount C ~/games` is misleading for Windows users.

Overall the comments are not good place to discuss these things - please create a pull request so we could discuss specific lines.

**Comment by kcgen** [comment]
@MasterO2 , do you have a build environment?

 If not, we can help get that setup; this will let you see how your comment looks exactly as rendered in dosbox (which is quite constrained given the 80x25 limitation requires an exacting balance of _spec_ + _description_ + _example invocations._)

**Comment by kcgen** [comment]
Work-in-progress branch here: `https://github.com/dosbox-staging/dosbox-staging/tree/kc/mo/imgmount-help-1`

![2020-08-25_15-10](https://user-images.githubusercontent.com/1557255/91233105-5e2b0b80-e6e5-11ea-915a-36151c3819b4.png)

@MasterO2, I'm happy to drop any further edits (this is using the text you sent me as-is).

**Comment by MasterO2** [comment]
> 
> 
> Work-in-progress branch here: `https://github.com/dosbox-staging/dosbox-staging/tree/kc/mo/imgmount-help-1` using text as provided from @MasterO2.
> 
> ![2020-08-25_15-10](https://user-images.githubusercontent.com/1557255/91233105-5e2b0b80-e6e5-11ea-915a-36151c3819b4.png)
> 
> @MasterO2, I'm happy to drop any further edits.

@kcgen As far as further edits go, the backslashes need to be fixed on the imgmount examples.  Also, where it says "for the drive letter d", it needs a new line there, so that imagefile is on the next line.  The backslashes need to be escaped.

**Comment by MasterO2** [comment]
@kcgen Specific edits:

line 1765:  ` "For example: A for the drive letter a:\ or D for the drive letter d:\\n"`

Remove the 2nd backslash after d:\

line 1767: 	` " For example: c:\games for Windows or ~\games for Linux\n"`

Add a 2nd backslash after c:\ and ~\

line 1779:   ` "imgmount d c:\games\doom.iso -t iso\n"`

Add a 2nd backslash after c:\ and games\

line 1783:    `"imgmount d c:\quake\quake1.cue -t iso\`

Add a 2nd backslash after c:\ and quake\

That should be all of the remaining backslash formatting issues.

I hate backslashes. :)

**Comment by kcgen** [comment]
Updates inbound

![2020-08-26_09-17](https://user-images.githubusercontent.com/1557255/91329442-0344f300-e77d-11ea-9085-84fb5b53f2d8.png)

**Comment by MasterO2** [comment]
@kcgen Move imagefile to the beginning of the line and move "Location of the image files" under "A for the drive letter".  Same idea as how the switches have space between them and their explanations.

Other than that, the formatting looks excellent!

**Comment by kcgen** [comment]
Will do, thanks @MasterO2 !

> Once the above is fixed, it should be mergeable into master.

Indeed; then it will be fit to PR'd where we can review and further tailor it.

**Comment by MasterO2** [comment]
Issue now closed since https://github.com/dosbox-staging/dosbox-staging/commit/8bbc68d8eb58bfd525ad5ce892b5c5971aa9d7df was merged into master.

**Comment by MasterO2** [comment]
Now closed since https://github.com/dosbox-staging/dosbox-staging/commit/8bbc68d8eb58bfd525ad5ce892b5c5971aa9d7df was merged into master.
