### ISSUE TITLE
Expose FluidSynth gain adjustment for users

### ISSUE THREAD

**Issue by kcgen** [dosbox-staging/dosbox-staging#572]
Some soundfonts are quiet and others can be quite loud.  Depending on the sound font used, the fluidsynth stream can accumulate beyond the 16-bit range and wrap - even before the samples are passed to the dosbox mixer.

![2020-08-23_13-35](https://user-images.githubusercontent.com/1557255/90988284-82041b00-e546-11ea-9fa9-8a786d1a8d8f.png)
![2020-08-23_13-38](https://user-images.githubusercontent.com/1557255/90988285-829cb180-e546-11ea-8ef7-b24235ba9e5e.png)

Letting users dial-down the gain will help.  We might also consider using a default gain of 0.1 instead of 0.2, because this wrapping currently happens even with Fluid's default `FluidR3_GM.sf2` soundfont.

Thanks to @GranMinigun for testing and reporting this.

**Comment by kcgen** [comment]
To further protect against wrapping and distortion, we can consider using overage-detection and soft-scaling (with a fast release window) like the GUS emulator now has.

But to do this, we need to use a data-type larger than 16-bit (GUS uses float); maybe fluidsynth has already has a `float` option and will manage this for us?

**Comment by GranMinigun** [comment]
It can render both in 16-bit and float.

**Comment by dreamer** [comment]
Yes, we use `fluid_synth_write_s16` to get 16-bit output, but we can use [`fluid_synth_write_float`](http://www.fluidsynth.org/api/synth_8h.html#ac86a79a943fc5d5d485ccc5a5fcad03d) instead; we can also use `fluid_synth_nwrite_float` if we wanted to separate channels (if it makes any sense for dosbox mixer).

**Comment by kcgen** [comment]
I'll have something for us to try out in the AM 🔈

**Comment by rderooy** [comment]
@kcgen question. How does this deal with the situation where you have not only GM but also FM (e.g. Sound Blaster) at the same time? In various games, such as Dune, the Sound Blaster is used for speech. And if the GM volume is too high, such as the default fluid.gain of 0.6 that DOSBox ECE (and in DOSBox-X until my patch adjusted it to 0.2) uses the speech is inaudible.

**Comment by dreamer** [comment]
*Just a clarification: FluidSynth 2.x has default gain of 0.2, not 0.6; @rderooy probably talks about FS 1.x, which we don't use in dosbox-staging.*

**Comment by rderooy** [comment]
@dreamer I'm aware your using FluidSynth 2.x in staging ;-) That is actually the reason that I have not tried it out yet as my Linux distribution still has 1.x, with an update to 2.1 scheduled in late October.

**Comment by grapeli** [comment]
@rderooy This is interesting. Does your distribution provide dosbox-staging? If not, and you have taken matters into your own hands, why not do the same with fluidsynth-2. Compilation takes approximately 20 seconds. Wait 5 years for "debian stable" to make it available in the repository (even months). It's absurd.
`cmake -DBUILD_SHARED_LIBS=OFF -DCMAKE_BUILD_TYPE=Release -Denable-alsa=OFF -Denable-aufile=OFF -Denable-dbus=OFF -Denable-dsound=OFF -Denable-ipv6=OFF -Denable-jack=OFF -Denable-ladspa=OFF -Denable-lash=OFF -Denable-libinstpatch=OFF -Denable-libsndfile=OFF -Denable-midishare=OFF -Denable-network=OFF -Denable-oss=OFF -Denable-portaudio=OFF -Denable-pulseaudio=OFF -Denable-readline=OFF -Denable-sdl2=OFF -Denable-systemd=OFF -Denable-threads=ON -Denable-waveout=OFF -Denable-winmidi=OFF`

**Comment by kcgen** [comment]
Thanks @rderooy,

I haven't played with Dune music vs. sfx volume levels -- I'm assuming the game doesn't offer configurable volume slides for these?

I'm assuming not, otherwise your own in-game settings would be 20% music, and your SFX level higher than that.  But without those control it makes perfect sense to (externally) withhold the MIDI volume to 20% like you're suggesting is the sweet spot for Dune. 

fluidsynth defaults to `0.2` gain by default because it has not control over sample wrapping in integer space; and yet it can still occur (even at 0.2) like @GranMinigun experienced using Fluid's own default soundfont no less.  So arguably, this would justify pushing the gain even lower to further, to say 0.15 or 0.10.

But withholding MIDI volumes to 20% (or less) is the wrong approach. When a game provides volume controls for SFX and Music volumes, then the music volume should be able to reach between 0% and 100%, and not be held back to 20% or less; meanwhile SB and GUS SFX volumes would thunder overtop of the music - even when set to 100%.

This PR allows clip-free, wrap-free FluidSynth output at all volume levels (so in-game settings really can run the volume at 100% at full-parity with the SFX volumes), and allows exteral control via the `mixer FSYNTH <percent>`  control.

So yes, if Dune isn't properly controlling the MIDI voice volumes itself (and instead running them at 100% volume) and if Dune also doesn't offer user-configurable music and SFX sliders; then yes - this PR would let you set `mixer FSYNTH 20` in your `dune.bat` prior to launch.

**Comment by kcgen** [comment]
@grapeli,

I open a Debian RFP (Request-for-package) for FluidSynth 2.0, however the maintainer(s) seem satisfied that 2.0 is available in their `testing` repository despite `1.x` being unmaintained for over 2 years now.

`` text
--
Looking after bugs assigned against unknown packages
Package: fluidsynth 2.x - stable series

Severity: RFP wishlist

License: LGPL-2.1+
Website: http://www.fluidsynth.org/
Repository: https://github.com/FluidSynth/fluidsynth/releases

Description:

FluidSynth is a real-time software synthesizer based on the SoundFont 2 specifications and has reached widespread distribution. FluidSynth itself does not have a graphical user interface, but due to its powerful API several applications utilize it and it has even found its way onto embedded systems and is used in some mobile apps.

Reason for Request:

Debian only packages the 1.x series, which has been deprecated for 2 years and has not been updated since May 2018.

This RFP pertains to the current stable 2.x release series, which reached stability as of Sept 2018. The 2.x series is continues to be maintained and receive bug and security fixes; 2.1.4 was released July 2020.

regards,

kcgen
```

Which was responded to:

``` text
968678: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=968678
Debian Bug Tracking System
Contact owner@bugs.debian.org with problems
On Mi, 19 aug 20, 16:11:26, kcgen wrote:
> Package: fluidsynth 2.x - stable series

The 'Package:' pseudo-header should generally contain only the package
name. For RFPs this should be 'wnpp' (on the assumption that the package
doesn't exist at all in Debian (not applicable here).

> Severity: RFP wishlist
>
> License: LGPL-2.1+
> Website: http://www.fluidsynth.org/
> Repository: https://github.com/FluidSynth/fluidsynth/releases
>
> Description:
>
> FluidSynth is a real-time software synthesizer based on the SoundFont 2 specifications and has reached widespread distribution. FluidSynth itself does not have a graphical user interface, but due to its powerful API several applications utilize it and it has even found its way onto embedded systems and is used in some mobile apps.
>
> Reason for Request:
>
> Debian only packages the 1.x series, which has been deprecated for 2 years and has not been updated since May 2018.

Are you referring to Debian 10 (codename buster)? If yes, this is by
design. For newer versions you could ask for a backport on the
debian-backports list (preferably with Cc to the package maintainer).

> This RFP pertains to the current stable 2.x release series, which
> reached stability as of Sept 2018. The 2.x series is continues to be
> maintained and receive bug and security fixes; 2.1.4 was released July
> 2020.

According to https://tracker.debian.org/pkg/fluidsynth 2.1.3 is
available in testing (future version 11, codename bullseye) since
06.Jun.

Based on this I'm closing the bug.

Kind regards,
Andrei
```

And then closed in the system:


``` text
This is an automatic notification regarding your Bug report
which was filed against the fluidsynth 2.x - stable series package:

#968678: TAG: FluidSynth 2.x (current stable series) -- a real-time software synthesizer based on the SoundFont 2 specification

It has been closed by Andrei POPESCU <andreimpopescu@gmail.com>.

Their explanation is attached below along with your original report.
If this explanation is unsatisfactory and you have not received a
better one in a separate message then please contact Andrei POPESCU <andreimpopescu@gmail.com> by
replying to this email.
--

**Comment by rderooy** [comment]
@kcgen Thanks for the explanation. Dune was just an example, as I'm sure you know, there are many DOS games from that era that would allow you to select Music and SFX output devices separately.

In any case, Dune does not allow to set separate volume levels. With DOSBox ECE and DOSBox-X I had to set the fluid.gain to 0.2 to be able to hear the speech, since the fluidsynth 1.x implementation they used defaulted to 0.6. I have since changed that in DOSBox-X to 0.2, as that matches the default upstream fluidsynth value.

A few other games where I needed to change the gain:
- Alien Legacy (gain of 0.1)
- Prince of Persia 2
- Dune 2
- Legend of Kyrandia 2
- Lands of Lore - The throne of Chaos (gain of 0.1)
- Terminator 2029

**Comment by rderooy** [comment]
@grapeli I'm using Fedora 32 and the update to 33 should be out in late October, and a Beta by the middle of September. There is already a rawhide package available with FluidSynth 2.1, so I could just grab that, or re-compile it on F32. But I had other things to do and also did not want to break things in the process. In particular I don't know if fluidsynth 1.x compiled applications work with fluidsynth 2.x out-of-the box, or if I need to keep libraries from both versions side by side.

**Comment by kcgen** [comment]
@rderooy - these settings are great.  Yes, it seems many first-generation MIDI games didn't offer volume control; I believe most of them assumes the user had an external hardware player with a volume control (similar to the MT-32).

Similar to our list of GUS-native games, I want us to provide a list of MIDI games and recommended sound-fonts (perhaps amung a handful that excel in various types of instruments), along with "suggested" mixer levels for those games that don't offer in-game settings.

**Comment by rderooy** [comment]
@kcgen In that case I suggest you have a look at https://github.com/joncampbell123/dosbox-x/wiki/Guide%3ASetting-up-MIDI-in-DOSBox%E2%80%90X

And in particular the piece about games with GS support. I have only found a single free GM+GS soundfont, and it is linked on the wiki page.

**Comment by kcgen** [comment]
That's good to know @rderooy, thanks. 

If there are DOS games that expect to use the extended GS instrument set when configured for 'General MIDI' output, then we certainly want to flag those games and recommend Fluid's combined GM+GS soundfont, as this will be critical to experiencing the complete audio score. 

Also important will be flagging which games should be used w/ MT32 vs. MIDI (as some games offer both configuration options, but the composer authored the music on Roland, and when MIDI is configured the music sounds weird or 'off').

I've amassed a list of these distinctions over the years, harvested from vogons threads and other sites, so need to put it in wiki table form.

**Comment by rderooy** [comment]
@kcgen 

As you mentioned, MT-32 has its own set of problems with different ROM sets needed for some games. This is also covered on the dosbox-x Wiki page I linked before.

Generally what I do when I find a solution, is to document it in existing places. Typically one of the following;
- http://pcgamingwiki.com/
- https://www.dosbox.com/comp_list.php?letter=a
- https://en.wikipedia.org/wiki/List_of_MT-32-compatible_computer_games

The wikipedia mt-32 games page also covers if a game is better run with General Midi (or Roland SC-55). The data is far from complete, but the most extensive that I know of. Better than those old Vogons threads.

**Comment by kcgen** [comment]
Thanks for the tips @rderooy ! Indeed; this is the exact info we want to lock-down for the majority of "AAA" DOS games; so every user out there trying to enjoy "game X" doesn't have to become an expert retro-sleuth to figure out to setup the sound for a given game (infact, most people I believe will just use defauls.. whatever those might be!).
