### ISSUE TITLE
Default keybindings conflict with shortucts for changing tty on Linux

### ISSUE THREAD

**Issue by dreamer** [dosbox-staging/dosbox-staging#585]
Bug split out of the discussion in #298 

**Describe the bug**
As in title; the problematic shortcuts are:
- Ctrl+Alt+F5 - Start/stop zmbv movie recording
- Ctrl+Alt+F7 - Start/stop OPL commands recording
- Ctrl+Alt+F8 - Start/stop MIDI commands recording

**To Reproduce**
Press Ctrl+Alt+F5 on Linux ;)

**Comment by dreamer** [comment]
@amak79 @kcgen Continuing discussion from #586 

Hmm, KDE bounding itself to CTRL+Fx keys is not cool :/ `<super>` key exists specifically for desktop environment options.

On Gnome we have no problems - super key is generally reserved shell use, CTRL+Fx keys are free to be used by applications (I need to double check in Gnome HIG though)
On Windows 10 we have no problems either - Windows key is used extensively there, I see no default binds to CTRL+Fx.
On macOS - I don't know, Apple HIG recommends using Command key, but I don't know if CTRL+Fx conflicts with something.
On Sway/i3 - not sure, but I believe CTRL+F1-F4 are extensively used (same as on KDE).

I don't really care about other user environments - they likely follow the same keybindings as the ones listed above.

Suggestion on how to go forward (I believe in a new PR, but we need to consult more users and investigate before writing any code):

1. For all Windows, Linux, macOS users: revise the keys, drop unnecessary ones, bind useful ones to CTRL+Fx
2. Add alternative shortcuts, so every action can be invoked via CTRL+Fx or CTRL+SHIFT+Fx combination - this should be a considerable improvement for KDE and Sway users, but also for other users who might have CTRL+Fx bound to something (e.g. in Steam, or some game overlay)
3. On macOS: we could consider CTRL+CMD+Fx instead (at least for some options - I know some users have problem with discovering ALT+ENTER, as normally on macOS it's CMD+F).

*This is only a suggestion, let's read up platforms HIGs first; once we'll change the default keybindings I don't want to keep revising the new design.*

**Comment by dreamer** [comment]
Results from #591 (6 responses):

Which shortcuts are people actually using? 
<= 1 means not used
\> 1 means used (higher number means how often)
```
Alt+Enter      Toggle Fullscreen: 4

Alt+Pause      Pause emulator: 0
Ctrl+Pause     Raise Debugger UI: 1 # only in debugger builds
Ctrl+Alt+Home  Restart emulator: 0 # not listed in INTRO

Ctrl+F1        Raise Mapper UI: 3
Ctrl+Alt+F2    Switch Layout: 0 # commented-out in code since 2007

Ctrl+F4        Swap CDROM/Floppy Image: 3
Ctrl+F4        Refresh Disk content: 0
??             Refresh Drive listing: 0  # presumably Ctrl+F4 as well? I don't know what's this action action

Ctrl+F5        Take Screenshot: 3  # nemo93 reported a bug TODO follow up
Ctrl+Alt+F5    Capture Video: 1
Ctrl+F6        Capture audio to WAV: 0  # but we use it often during debugging!
Ctrl+F7        Decrease Frame-skip: 1
Ctrl+Alt+F7    Capture OPL music data: 0
Ctrl+F8        Increase Frame-skip: 1
Ctrl+Alt+F8    Capture MIDI music data: 0

Ctrl+F9        Shutdown emulator: 5
Ctrl+F10       Capture/uncapture Mouse: 3
Ctrl+F11       Decrease Cycles: 5
Ctrl+F12       Increase Cycles: 5
Alt+F12        Unlock speed (fast-forward): 0

# machine=cga actions:
F11            Increment CGA Composite Hue: 0
Alt+F11        Decrement CGA Composite Hue: ?  # not asked
Ctrl+Alt+F11   Toggle CGA Model (for Composite): 0
F12            Toggle CGA Composite ON/OFF: ?  # not asked

# machine=hercules and machine=cga_mono actions:
F11            Cycle through mono colours: ? # not asked # broken when sdlmapper file exists! bug mentioned in readme
Alt+F11        Toggle mono contrast: 0 # "Select Mono CGA Bright"

```

**Comment by dreamer** [comment]
My initial idea about new layout:
`=` - no change
`-` - binding removed
`+` - binding added/replaced
`?` - to be discussed

```
= Alt+Enter      Toggle Fullscreen

= Alt+Pause      Pause emulator
= Ctrl+Pause     Raise Debugger UI
= Ctrl+Alt+Home  Restart emulator

= Ctrl+F1        Raise Mapper UI
+ Ctrl+F2        (free)
+ Ctrl+F3        (free)
= Ctrl+F4        Swap CDROM/Floppy Image / Refresh Disk content

= Ctrl+F5        Take Screenshot
= Ctrl+F6        Toggle capture audio (.wav)
+ Ctrl+F7        Toggle capture video (.zmbv)
+ Ctrl+F8        (free)

- (none)         Decrease Frame-skip # was Ctrl+F7
- (none)         Capture OPL music data # was Ctrl+Alt+F7
- (none)         Increase Frame-skip # was Ctrl+F8
- (none)         Capture MIDI music data: 0 # was Ctrl+Alt+F8

= Ctrl+F9        Shutdown emulator
= Ctrl+F10       Capture/uncapture Mouse
= Ctrl+F11       Decrease Cycles
= Ctrl+F12       Increase Cycles
? Alt+F12        Unlock speed (fast-forward) # this action is very useful, but shortcut is terrible

# machine=cga actions:
? F11            Increment CGA Composite Hue
? Alt+F11        Decrement CGA Composite Hue  # not asked
? Ctrl+Alt+F11   Toggle CGA Model (for Composite)
? F12            Toggle CGA Composite ON/OFF: ?  # not asked

# machine=hercules and machine=cga_mono actions:
? F11            Cycle through mono colours
? Alt+F11        Toggle mono contrast
```

**Comment by kcgen** [comment]
Only have thoughts on a couple:

``` text
+ Ctrl+F8        Cycle through: CGA off / CGA early model / CGA late model # replaces F12 and Ctrl+Alt+F11
= F11            Increment CGA Composite Hue
= Alt+F11        Decrement CGA Composite Hue

# machine=hercules and machine=cga_mono actions:
+ Ctrl+F8        Cycle through mono colours # replaces F11
+ F11            Toggle mono contrast # replaces Alt+F11
```

- I like how the same color-related keystroke pattern is used for both machine types; that's intuitive to remember.
- I don't like the key-gap: mixing F8 and F11.  Like cycles and the capture keys, I think they should be adjacent.  One idea is to make all the video settings use `Alt` plus a bank of 3 adjacent F-keys (F6, F7, F8?).
- F11 increment, Alt-F11 decrement is a mental clash with cycles, which uses two F-Keys and the same modifier (Ctrl-F11 decrement, Ctrl-F12 increment).  So I think we need the same pattern.

Possible suggestion:

``` text
Alt-F6       Cycles CGA models or Mono palettes
Alt-F7       Decrease Hue (color) or disable contrast (mono)
Alt+F8      Increase Hue (color) or enable contrast (mono)
```
