### ISSUE TITLE
Which hotkeys do you use the most?

### ISSUE THREAD

**Issue by kcgen** [dosbox-staging/dosbox-staging#591]
We are considering pruning and reassigning some of the lesser-used hotkeys. 

To help figure this out, we'd like to learn which hotkey you use frequently versus those that you rarely or never use.

Copy and paste the text below to a new comment, and update the numbers:

- 0 means you weren't aware of this hotkey/function.
- 1 means you know about it, but don't use it.
- 2 means you use it infrequently.
- 3 means you use it every now and then.
- 4 means you use it frequently.
- 5 means you use it everytime or almost everytime.

I've populated the list with estimated defaults, so you hopefully only have to adjust a handful:

``` text
Shutdown emulator: 5
Pause emulator: 0
Restart emulator: 0

Decrease Cycles: 4
Increase Cycles: 4
Unlock speed (Fast-forward): 0
Decrease Frame-skip: 1
Increase Frame-skip: 1

Raise Mapper UI: 2
Raise Debugger UI: 1

Swap CDROM/Floppy Image: 3
Refresh Disk content: 0
Refresh Drive listing: 0

Capture/uncapture Mouse: 5
Toggle Fullscreen: 4
Increment Hue: 0
Toggle CGA Model: 1
Select Mono CGA Bright: 0

Switch Layout (?): 0

Capture OPL music data: 0
Capture audio to WAV: 2
Capture MIDI music data: 1
Capture Video to AVI: 2
Take Screenshot: 2
```

**Comment by bluddy** [comment]
```
Shutdown emulator: 5
Pause emulator: 0
Restart emulator: 0

Decrease Cycles: 5
Increase Cycles: 5
Unlock speed (Fast-forward): 0
Decrease Frame-skip: 0
Increase Frame-skip: 0

Raise Mapper UI: 3
Raise Debugger UI: 1

Swap CDROM/Floppy Image: 1
Refresh Disk content: 0
Refresh Drive listing: 0

Capture/uncapture Mouse: 1
Toggle Fullscreen: 4
Increment Hue: 0
Toggle CGA Model: 0
Select Mono CGA Bright: 0

Switch Layout (?): 0

Capture OPL music data: 0
Capture audio to WAV: 0
Capture MIDI music data: 0
Capture Video to AVI: 0
Take Screenshot: 0
```

**Comment by amak79** [comment]
```
Shutdown emulator: 5
Pause emulator: 2
Restart emulator: 3

Decrease Cycles: 4
Increase Cycles: 4
Unlock speed (Fast-forward): 0
Decrease Frame-skip: 1
Increase Frame-skip: 1

Raise Mapper UI: 2
Raise Debugger UI: 1

Swap CDROM/Floppy Image: 1
Refresh Disk content: 0
Refresh Drive listing: 0

Capture/uncapture Mouse: 1
Toggle Fullscreen: 4
Increment Hue: 0
Toggle CGA Model: 1
Select Mono CGA Bright: 0

Switch Layout (?): 0

Capture OPL music data: 0
Capture audio to WAV: 1
Capture MIDI music data: 1
Capture Video to AVI: 3
Take Screenshot: 3
```

**Comment by nemo93** [comment]
```
Shutdown emulator: 5
Pause emulator: 0
Restart emulator: 0

Decrease Cycles: 4
Increase Cycles: 4
Unlock speed (Fast-forward): 0
Decrease Frame-skip: 1
Increase Frame-skip: 1

Raise Mapper UI: 2
Raise Debugger UI: 1

Swap CDROM/Floppy Image: 3
Refresh Disk content: 0
Refresh Drive listing: 0

Capture/uncapture Mouse: 5
Toggle Fullscreen: 4
Increment Hue: 0
Toggle CGA Model: 1
Select Mono CGA Bright: 0

Switch Layout (?): 0

Capture OPL music data: 0
Capture audio to WAV: 2
Capture MIDI music data: 1
Capture Video to AVI: 2
Take Screenshot: 2
```

**Comment by dreamer** [comment]
Very interesting results. I just want to double-check - about "Shutdown emulator" - you all use `Ctrl+F9`?
```
Shutdown emulator: 1
Pause emulator: 2
Restart emulator: 1

Decrease Cycles: 4
Increase Cycles: 5
Unlock speed (Fast-forward): 1
Decrease Frame-skip: 1
Increase Frame-skip: 1

Raise Mapper UI: 3
Raise Debugger UI: 0

Swap CDROM/Floppy Image: 3
Refresh Disk content: 1
Refresh Drive listing: 0

Capture/uncapture Mouse: 4
Toggle Fullscreen: 5
Increment Hue: 3
Toggle CGA Model: 3
Select Mono CGA Bright: 3

Switch Layout (?): 0

Capture OPL music data: 1
Capture audio to WAV: 1
Capture MIDI music data: 1
Capture Video to AVI: 2
Take Screenshot: 3
```

**Comment by amak79** [comment]
> Very interesting results. I just want to double-check - about "Shutdown emulator" - you all use `Ctrl+F9`?

I do.

**Comment by nemo93** [comment]
> Very interesting results. I just want to double-check - about "Shutdown emulator" - you all use `Ctrl+F9`?

`Ctrl+F9` indeed. I even added that to the mapper to bind it to my Xbox controller to mimick the Retroarch default (`Start+Select`).

**Comment by Max833** [comment]
Shutdown emulator: 5
Pause emulator: 3
Restart emulator: 3

Decrease Cycles: 5
Increase Cycles: 5
Unlock speed (Fast-forward): 0
Decrease Frame-skip: 0
Increase Frame-skip: 0

Raise Mapper UI: 0
Raise Debugger UI: 0

Swap CDROM/Floppy Image: 5
Refresh Disk content: 0
Refresh Drive listing: 0

Capture/uncapture Mouse: 5
Toggle Fullscreen: 5
Increment Hue: 0
Toggle CGA Model: 0
Select Mono CGA Bright: 0

Switch Layout (?): 0

Capture OPL music data: 0
Capture audio to WAV: 0
Capture MIDI music data: 0
Capture Video to AVI: 0
Take Screenshot: 4

**Comment by kcgen** [comment]
``` text
Shutdown emulator: 5
Pause emulator: 0
Restart emulator: 0

Decrease Cycles: 2
Increase Cycles: 2
Unlock speed (Fast-forward): 0
Decrease Frame-skip: 1
Increase Frame-skip: 1

Raise Mapper UI: 2
Raise Debugger UI: 1

Swap CDROM/Floppy Image: 3
Refresh Disk content: 0
Refresh Drive listing: 0

Capture/uncapture Mouse: 3
Toggle Fullscreen: 3
Increment Hue: 0
Toggle CGA Model: 0
Select Mono CGA Bright: 0

Switch Layout (?): 0

Capture OPL music data: 0
Capture audio to WAV: 3
Capture MIDI music data: 0
Capture Video to AVI: 1
Take Screenshot: 1
```
As a gamer, I prefer to launch via emulation station.  Each game has a delta config (specific cycle count, memsize, sound cards, etc..)  and I launch straight to fullscreen.  Ctrl+F9 as soon as I'm bored and want to try another :-)

**Comment by kcgen** [comment]
> Ctrl+F9 indeed. I even added that to the mapper for my Xbox controller to mimick the Retroarch default (Start+Select).

Very nice @nemo93 !

**Comment by kcgen** [comment]
> Shutdown emulator: 1

@dreamer , wow - you never use Ctrl-F9! 

Can I assume you prefer to use the game's own exit/quit command, followed by `exit`ing dosbox once you're back at the command line; failing that you will use your window-manager GUI close or force-close controls? (Corner window [X], Ctrl-W / F4, etc).

I'm curious.

The responses so far are indeed very interesting!

**Comment by dreamer** [comment]
I never do; I use dosbox exclusively on desktop or laptop, often via Steam (when actually playing and not testing/developing).
- If my hands are on the keyboard and I'm in the shell, I type `exit` (as that's what I do in bash shell, so it's already in my muscle memory)
- If I'm in the game, I exit the game (which usually means my .conf file closes the dosbox as well)
- Sometimes I use Alt+F4 or close the window by pressing X in the window title (depending on the situation)

But seems like I am in the minority here :)

**Comment by bluddy** [comment]
Just to amend my previous feedback, I thought quitting was alt-f4, which is what I use. I didn't know there was a dedicated function for quit, nor do I really see a use for it.

**Comment by dreamer** [comment]
Thank you all for feedback; discussion continues in #585
