### ISSUE TITLE
Compiling on macOS generates excessive fcntl(): Bad file descriptor warnings

### ISSUE THREAD

**Issue by kcgen** [dosbox-staging/dosbox-staging#595]
![2020-09-01_15-24](https://user-images.githubusercontent.com/1557255/91912368-d787a880-ec67-11ea-9fb8-c1562a378f28.png)

These are related to make's`output-sync` option used to keep warning messages distinct. 
Presumably these have always occurred, however the builds were previously so noisy that these were lost in the wash.

Other projects also report this:
- https://jira.appcelerator.org/browse/TIMOB-27776
- https://bugs.openjdk.java.net/browse/JDK-8062020
- https://bugzilla.mozilla.org/show_bug.cgi?id=1386739
- https://github.com/sublimehq/sublime_text/issues/2293

**Comment by nemo93** [comment]
@kcgen is this still true please? otherwise let's close that one too 😄
