### ISSUE TITLE
Support an option for setting default monochrome colour (Hercules)

### ISSUE THREAD

**Issue by leesa49** [dosbox-staging/dosbox-staging#602]
I'm trying to change color in hercules monochrome

I change hercules in dosbox-staging-git.conf
     
  machine = hercules

2. launch dosbox
3. Hercules Mode is OK
    BUT I want to green among green/amber/while
    everytime,. press F11 while green

Can I change color green as Initial value

**Comment by dreamer** [comment]
@leesa49 Thank you for the report!

I just double-checked in code if there's some undocumented option allowing user to decide the default palette… and there's nothing! :( We should definitely fix it - otherwise, the feature of supporting multiple colours would be pointless.

**Comment by dreamer** [comment]
@leesa49 Thank you for the report :) Issue got closed automatically when I merged fix to out master branch.

There's now a new option in `render` section of the .conf file:
```
# monochrome_palette: Select default palette for monochrome display.
#                     Works only when emulating hercules or cga_mono.
#                     You can also cycle through available colours using F11.
#                     Possible values: white, paperwhite, green, amber.
```
With default value:
```
monochrome_palette = white
```
You can also change it in runtime (e.g. if you want to switch games without restarting dosbox and have .bat files to run specific games), example:
```
Z:\> config -set monochrome_palette amber
```

This feature will be released in upcoming 0.76.0 version, but until then you can test it in our development builds: https://dosbox-staging.github.io/downloads/devel/ :)

If something is broken or does not work correctly, I can reopen this issue (or you can create a new one if you prefer). Thanks!

**Comment by ChristianHarmsMhp** [comment]
In hercules the graphics (for example simcity) becomes blue.

**Comment by johnnovak** [comment]
> In hercules the graphics (for example simcity) becomes blue.

Please raise a separate ticket @ChristianHarmsMhp if you found an issue. Also make sure you're using the latest stable release.
