### ISSUE TITLE
exepack integration?

### ISSUE THREAD

**Issue by LowLevelMahn** [dosbox-staging/dosbox-staging#603]
what about adding a exepack unpacker directly into dosbox (like https://www.bamsoftware.com/software/exepack/)

this way it would be possible to get rid of some microsoft exepack bugs (that sometimes needs microsofts loadfix to solve) without involving the user (little bit related to the DOS4GW/DOSA32 integration ideas)

**Comment by dreamer** [comment]
@LowLevelMahn Do you have some specific game, that needs this? Does it solve any specific problem for us?

**Comment by LowLevelMahn** [comment]
Blood:
https://www.vogons.org/viewtopic.php?f=33&t=9715&p=64658&hilit=exepack#p64658
Ultima:
https://www.vogons.org/viewtopic.php?f=7&t=26626&p=204105&hilit=exepack#p204105

but i've tested that while ago maybe is not a real error with dosbox staging anymore

**Comment by dreamer** [comment]
Topic about Blood is from 2005 - I believe I tested Blood few months ago and it was working fine (even in upstream) - my suspicion is that this problem is either fixed, or using builtin `loadfix` is good enough.

In topic about Ultima (from 2010) user confirmed, that `loadfix` resolves the issue.

**Comment by Akuma-Git** [comment]
That's a 'big no' imo, most exepacked files work out of the box,
those that do not can be loaded with loadfix, or otherwise be unpacked using UNP411/412.

You should not want to go down this road, they are too many packers/crypters out there.

**Comment by dreamer** [comment]
Closing this request wit the same rationale as in https://github.com/dosbox-staging/dosbox-staging/issues/392#issuecomment-687617673

If someone needs `exepack` tool, and is willing to volunteer with maintaining it in a collection of DOS tools to be used on utility drive (#601), then please leave a comment in that issue.

**Comment by LowLevelMahn** [comment]
> That's a 'big no' imo, most exepacked files work out of the box,

or even better - Stunts for example works out of the box in dosbox but not on a real dos
-> exepack corruption error

> those that do not can be loaded with loadfix, or otherwise be unpacked using UNP411/412.
> You should not want to go down this road, they are too many packers/crypters out there.

your right

**Comment by LowLevelMahn** [comment]
DOS +5 directly integrates a exepack unpacker directly into its exe loader
according to findings in the leaked DOS 6 source code
