### ISSUE TITLE
Emulate CD drive front panel buttons (play/stop/prev/next)

### ISSUE THREAD

**Issue by Akuma-Git** [dosbox-staging/dosbox-staging#609]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
z:\ drive application, cdplayer, just the most basic commandline cdplayer.
something like: cdplayer drive action [track]
eg: cdplayer e play 5
cdplayer stop
stuff like that

**Describe alternatives you've considered**
Cdplayer v1.0 by Jani Ponkko (1996)
https://www.sac.sk/download/sound/cdplay10.zip

**Additional context**
This was so basic that I thought it was already in there.
But I was just launching the batch files that were in the path.

Edit: just to be clear, this for testing purposes.

**Comment by MasterO2** [comment]
Given that https://github.com/dosbox-staging/dosbox-staging/issues/392 was rejected, your feature request is going to have a similar fate...

**Comment by kcgen** [comment]
Cool suggestion @Akuma-Git!

Given the ability to play music CD's came with the drive back in the DOS days (some offering more bezel buttons than others), it seems like dosbox should provide similar functionality. 

![40626](https://user-images.githubusercontent.com/1557255/92930570-17345a00-f3f7-11ea-9eca-2ae6642f3bd0.jpg)

The big win being that users in the mid and late 90s often played CDs using this features to augment their (non-CDDA) games and application use with their own CD music. 

It also makes sense that we tie the controls into some hotkeys so the CD music can be controlled even when an application is running; although we'd probably programmatically relenquish control if a game performed CDDA commands to prevent conflict.

**Comment by MasterO2** [comment]
> 
> 
> > Given that #392 was rejected, your feature request is going to have a similar fate...
> 
> To me, the distinction is that this is a function of CDROM drive itself; dosbox should provide similar music-control hotkeys just like the bezel buttons on the drive. Infact, that's all I suggest we implement (hotkeys to control audio playback).
> 
> I'm not suggesting we write any form of text GUI CD-DA player; if someone wants that there are lots of nice ones out there.

I can only assume that such a feature is gonna end up on the backlog.

**Comment by kcgen** [comment]
> Would this also work with imgmounted CUE / BIN pairs

Absolutely :-)

**Comment by Akuma-Git** [comment]
I found one in assembler, with source.
It works with cycles=1 ! but starts stuttering with 1000+ or so.
https://www.sac.sk/download/sound/cdp.zip

Defaults in using G: drive for some reason,
but if you hexedit @offset 0x0c from 06 to 03,
then it will play from D:\
(A=0 B=1 C=2 D=3 E=4 F=5 G=6 and so on...)

If reprogrammed with non-essentials removed I think it will be under 999 bytes.
That's a real space consumer ;)

**Comment by MasterO2** [comment]
@kcgen It just occurred to me that in Dosbox-staging 0.75, the following were removed:

```Removed support for CD-DA playback from physical disks. It is still possible to install games distributed on CDs by mounting them as directories. See #260., Removed CD-DA playback support for tracks using the Audio Interchange File Format AIFF audio codec.```

If someone inserts an Audio CD, it won't work with this proposed feature then, right?

**Comment by kcgen** [comment]
That's right @MasterO2; we've gone pure-software for CDROM data and CD-DA support (bin/cue, flac/cue, etc..).

So physical music CDs inserted into the host machines are treated just like any other directory.. 
(their data files can be `mount`ed, but that's as much interaction dosbox will have with it). 

So to play a physical music CD, the user will have to rip the tracks to FLAC or Opus. Couple refs:

- https://moisescardona.me/ripping-audio-cd-opus-eac/
- https://www.techadvisor.co.uk/how-to/audio/how-rip-cds-flac-3690344/

(We have a todo to write up better procedures using more automated tools; but for now EAC is a decent option on windows for pure music CDs).

**Comment by Wengier** [comment]
There is an alternative solution for anyone who would like to play a physical music CD - [DOSBox-X](http://dosbox-x.com/) still and will continue to support the physical music CDs (in addition to the software CD approach supported by dosbox-staging), e.g. 

```mount d: d:\ -t cdrom -usecd 0```

Meanwhile, there is another (and more powerful) CD player for DOS named SJGPLAY, which is freeware and use a text-based GUI interface, so it is probably easier to use than the program suggested in the original post. But I highly appreciate @Akuma-Git's idea to include a CD player, and I have already incorporated the powerful CD player (SJGPLAY) into DOSBox-X (named CDPLAY.EXE for easier use). Perhaps such a CD player may be incorporated to dosbox-staging as well in the future.

**Comment by kcgen** [comment]
When all things are equal, we want to encourage the move toward virtual and digital whenever possible.

For CDs, there comes a point when surface flaws, oxidation and dyes degradation renders a given disc unreadable. 

Likewise there comes a point when every drive's optical alignment worsensen, dust builds up, gear play is added, and pulleys stretch or rot.  

Whenever possible we will encourage digital preservation over sustaining use of aging media. Preserve your collections today! There's no better time ⏳ 💿 👍

**Comment by dreamer** [comment]
@Wengier freeware is not Free software. By bundling non-Free software you cannot distribute DOSBox-X using straight GPL license any more.

**Comment by Wengier** [comment]
@kcgen I think it is not entirely a bad idea to try to encourage the use of virtual and digital software. But the other concern is about the the options for users and usability. Some software for example depreciate the use of certain feature(s), either by giving a warning message or disabling it by default, but it can still be enabled for users who really need them. On the other hand, dosbox-staging disables the feature altogether, which just IMO may not be always the best solution.

**Comment by Wengier** [comment]
@dreamer Thanks for pointing this out. Before doing this I looked at Cdplayer software linked in the first post, which turns out to be a CARDWARE. Then I checked the license of SJGPLAY, which is FREEWARE. FREEWARE is certainly better than CARDWARE mentioned in the first post. But if that still has licensing issue as you mentioned, then I will look for another alternative.

**Comment by kcgen** [comment]
@Wengier , regarding "_Some software for example depreciate the use of certain feature(s), either by giving a warning message or disabling it by default, but it can still be enabled for users who really need them._"

Ok, I'm following. Sure, lots of nasty software companies out there. Such as those that use hardware dongles.

"_On the other hand, dosbox-staging disables the feature altogether, which just IMO may not be always the best solution_".

In the context of supporting physical vs bin/cue CD images, do you have examples where using a virtual mount denies said features that are exclusively provided when using a physical CDROM drive and media?

**Comment by kcgen** [comment]
@Wengier , out of curiosity, I searched all open and closed DOSBox-X issues and PRs for "sjgplay", but both came up without hits to commits or requests.  Can you point me to the commit(s) or PR set? Just curious - thanks.

**Comment by Wengier** [comment]
@kcgen The commit that integrates SJGPLAY is here: https://github.com/joncampbell123/dosbox-x/commit/bf46072d239c9b4771b1eb708e5147a15351cbe9.

Also, speaking of freeware, I noticed that DOSBox-X has several tools bundled for a long time, such as DEVICE and BUFFERS from Quarterdeck, which I am not entirely sure if they are strictly free software.

**Comment by Wengier** [comment]
> In the context of supporting physical vs bin/cue CD images, do you have examples where using a virtual mount denies said features that are exclusively provided when using a physical CDROM drive and media?

@kcgen For example, some physical CDs are copy-protected in some way that may not be ripped easily, and normal users (i.e. non-expert users) may simply have no way to rip them easily by themselves. On the other hand, dosbox-staging is apparently not targeted at expert users, so this may make things harder for a typical user to use their CDs.

**Comment by kcgen** [comment]
Thanks for the link @Wengier . Do you recall the software and features that are revoked when using a virtual bin/cue mount versus physical CDROM? Regards.

**Comment by Wengier** [comment]
@kcgen You have to manually rip data from physical CD first, which is not always feasible for a typical user.

**Comment by kcgen** [comment]
Thanks @Wengier ; I see your point. 

By supporting hardware, users of backup-hostile software can continue using their original media until it fails. 

My understanding is that it's a common legal right of software ownership that one be able to make archivable backups. Often those backups are only possible through the use if a no-CD fix, or a low-level CDROM tool that operates on the block level instead of filesystem (such as Alcohol 120 and Daemon Tools).  In both cases, the result is that media can be virtualized -- and yes, it takes a bit more effort to do so. 

More specifically, are you aware of any **_DOS_** games that can't play from ripped bin/cue?

**Comment by Wengier** [comment]
@kcgen Basically the current dosbox-staging not only *encourages* users to rip their CDs, but it actually *requires* users to do so, or else it will simply not usable for them. The good thing for this as you said is to for users to backup their data, but at the same time by making everyone learn how to rip their media, it is arguable this will encourage software piracy at well - now everyone knows how to rip their media, it can be easily imaged that software piracy will also increase. It is not directly a fault of dosbox-staging of course, but such a requirement can indeed also lead to such a non-negligible side-effect.

As I mentioned earlier I don't play DOS games a lot so cannot give concrete examples of that at this time, but the point is always that you have to rip your media first before everything else, which is clearly not effortless.

**Comment by dreamer** [comment]
This issue is not a place for discussing physical CD-audio support (nobody asked for this feature to be brought back and we had literally 0 users with physical CDs complaining about it). We went over it extensively already in multiple issues, like #29 and #260, explaining the reasons for removal. I am not bringing this feature back without someone stepping forward to port SDL_cdrom to SDL2 and promising to test and maintain it. This is literally 10K LOC of unmaintained, abandoned code to support a feature *nobody ever asked for*.

Now, regarding **this** feature request:

@Akuma-Git 
What's exactly the problem that you want to fix by including a feature for playing virtual CDs? I see no valid reason for bundling it, but maybe I'm missing something.

For testing we were using Free (GPL) [Open Cubic Player](https://www.cubic.org/player/download.html) for DOS - if you need to test something, just use it.

**Comment by Wengier** [comment]
@dreamer I was just trying to answer @kcgen's question, and I was indeed trying to be very honest about that. If you have concern feel free to let me know. If it is more desirable to be discussed elsewhere, it is fine too.

**Comment by dreamer** [comment]
I see no reason to keep having the same discussion about physical CD audio support - it's off-topic, that's all :)

We already explored this in #29 and #260 - read those threads to learn about our findings and design decisions. If situation changed somehow (e.g. someone wants to resurrect and maintain abandoned SDL_cdrom library), then start a new thread.

**Comment by kcgen** [comment]
@dreamer, regarding _" I am not bringing this feature back without someone stepping forward to port SDL_cdrom to SDL2 and promising to test and maintain it. "_ I would add a fourth caveat, and that would be a requirement showing that DOS game(s) x, y, and z do not work properly using digital images.  @Wengier, I was hoping you had such an inventory, but now have deduced that none exists.

**Comment by kcgen** [comment]
Also, as a cleanup for this thread and to focus on what @Akuma-Git has suggested, I recommend  this tangent of off-topic discussion be deleted.

**Comment by Wengier** [comment]
@dreamer It is fine. Because such discussions may be off topic in this thread, I decided to send you an email instead. Not needed to be discussed here.

**Comment by Akuma-Git** [comment]
@dreamer 
> @Akuma-Git
> What's exactly the problem that you want to fix by including a feature for playing virtual CDs? I see no valid reason for bundling it, but maybe I'm missing something.
> 
> For testing we were using Free (GPL) [Open Cubic Player](https://www.cubic.org/player/download.html) for DOS - if you need to test something, just use it.

kcgen did a far better job describing it than me: I'm missing the frontpanel buttons.
And for me this is only play/stop being an additional function in the keymapper.

Do you want me to edit my first post reflecting this ?

**Comment by dreamer** [comment]
@Akuma-Git no need to edit - I changed the title and put the request in the backlog. We went on this tangent about bundling CD player software and I lost track of what is being requested - thanks for clarification :)

**Comment by Burrito78** [comment]
No, not happening probably.
