### ISSUE TITLE
Imgmount ECM-formatted CDROM images

### ISSUE THREAD

**Issue by kcgen** [dosbox-staging/dosbox-staging#612]
ECM CDROM images are equivalant to BIN/CUE in their content and use, however have their per-sector ECC data removed.

Ref: https://github.com/alucryd/ecm-tools, which is an open source tool that runs in GNU/Linux, Windows and Mac OS X.

The ECM format:

- Achieves its size reduction by removing the unused per-sector error correction data thats present in BIN rips.

- The ECM conversion tool supports input formats such as: ISO, NRG, BIN/CUE, CDI, CCD, or any other format that uses Raw sector copying.

- Has two built in tools for compressing and decompressing.

_Originally posted by @Akuma-Git in https://github.com/dosbox-staging/dosbox-staging/issues/99#issuecomment-691638520_ (thank you!)

**Comment by Burrito78** [comment]
I think this format never got any traction. Nice idea though. Close @kcgen ?

**Comment by kcgen** [comment]
Yup; so far down the list, it's in the "I will never have enough time" category. PRs welcome though.
