### ISSUE TITLE
Midi not playing in games when using Timidity

### ISSUE THREAD

**Issue by bradgy** [dosbox-staging/dosbox-staging#616]
Ubuntu 20.04 snap latest/stable 0.75.1 dosbox-staging 

**Alsa errors on startup (midi music not heard in game):**

dosbox-staging -conf dosbox/dosboxDuke3D.conf DUKE3D.EXE 
dosbox-staging version 0.75.1

CONFIG: Loading primary file dosbox/dosboxDuke3D.conf
CONFIG: Unknown option fulldouble
"overlay" is not a valid value for variable: output.
It might now be reset to the default value: opengl
CONFIG: Unknown option autolock
CONFIG: Unknown option usescancodes
OPENGL: Pixel buffer object extension: available
MAIN: Draw resolution: 640x480, pixel aspect ratio: 1.00
MAIN: Emulator resolution: 1920x1080
SDL: Mouse will move seamlessly without being captured.
Memory sizes above 31 MB are NOT recommended.
Stick with the default values unless you are absolutely certain.
MEMORY: Base address: 0x7f27b00ff010
MEMORY: Using 16128 DOS memory pages (63 MiB)
MIXER: Got different values from SDL: freq 44100, blocksize 1024
ALSA lib conf.c:3916:(snd_config_update_r) Cannot access file /usr/share/alsa/alsa.conf
ALSA lib seq.c:935:(snd_seq_open_noupdate) Unknown SEQ hw
ALSA: Can't open sequencer
MIDI: No working MIDI device found/selected.
MIDI: Opened device:none
MAPPER: Found no joysticks
MAPPER: Loaded default key bindings
SDL: Window has been shown
SDL: The window size has changed
SDL: Window has been exposed and should be redrawn
SDL: captured the mouse
SDL: Window has gained mouse focus
SDL: Window has gained keyboard focus
SDL: Window is being offered a focus
MAIN: Draw resolution: 640x400, pixel aspect ratio: 1.00
MAIN: Emulator resolution: 1920x1080
MAIN: Draw resolution: 640x480, pixel aspect ratio: 1.00
MAIN: Emulator resolution: 1920x1080
MAIN: Draw resolution: 640x400, pixel aspect ratio: 1.00
MAIN: Emulator resolution: 1920x1080
MAIN: Draw resolution: 640x400, pixel aspect ratio: 1.00
MAIN: Emulator resolution: 640x400
SDL: released the mouse

**Not present in SVN (midi music heard in game)**
dosbox -conf dosbox/dosboxDuke3D.conf DUKE3D.EXE 
DOSBox version 0.74-3
Copyright 2002-2019 DOSBox Team, published under GNU GPL.

CONFIG:Loading primary settings from config file dosbox/dosboxDuke3D.conf
Memory sizes above 31 MB are NOT recommended.
Stick with the default values unless you are absolutely certain.
MIXER:Got different values from SDL: freq 44100, blocksize 512
ALSA:Client initialised [128:0]
MIDI:Opened device:alsa

**aconnect -o**
client 14: 'Midi Through' [type=kernel]
    0 'Midi Through Port-0'
client 128: 'TiMidity' [type=user,pid=2200]
    0 'TiMidity port 0 '
    1 'TiMidity port 1 '
    2 'TiMidity port 2 '
    3 'TiMidity port 3 '

[dosboxDuke3D.conf.txt](https://github.com/dosbox-staging/dosbox-staging/files/5252908/dosboxDuke3D.conf.txt)

**Comment by kcgen** [comment]
@bradgy , 
I was unable to reproduce. Can you try this package for testing purposes?
http://205.250.146.105:8001/staging/Duke_Nukem_3D-Linux_MIDI.tar.zst

Extract and edit the last line of `start.sh`, updating the `dosbox` path to your specific dosbox-staging binary.
Then launch it by simply running `./start.sh`.  
This will check for an existing timidity instance, and (if none is found), launch it's own instance followed by running the game.

**Comment by dreamer** [comment]
I am using dosbox-staging with Timidity all the time, it definitely does work as far as our project is concerned. But I am not sure about the snap package - so this is the primary suspect if some users have problem with making it work.

**Comment by kcgen** [comment]
Ahh, good catch regarding this being a snap package @dreamer. 

This is absolutely a process scope/access limitation which hasn't been granted in the snap's properties.

@bradgy - can you please:

1. Confirm Timidy MIDI works without issue using the stand-alone binary provided by the dosbox-staging project? (https://github.com/dosbox-staging/dosbox-staging/releases/download/v0.75.1/dosbox-staging-linux-v0.75.1.tar.xz)

1. report this issue to whomever is distributing the snap package?

**Comment by FeignInt** [comment]
@bradgy you may also like to try 
[PPA weekly](https://launchpad.net/~feignint/+archive/ubuntu/dosbox-staging-weekly)
which also has fluidsynth

or, if you prefer [stable release](https://launchpad.net/~feignint/+archive/ubuntu/dosbox-staging), 0.75.1 does not have fluidsynth, but Timidity should be working.

The weekly's default conf is *~/.config/dosbox/dosbox-staging-git.conf*, if it already exists you will need to backup/delete that to get correct defaults ( see comments in the .conf for details )

If the official tarball or the unofficial PPA versions work for you the issue is the snap, probably missing soundfonts or timidity. Just a guess as I don't have any experience with snap packages.

**Comment by bradgy** [comment]
Hi all, thanks for the prompt eyes on this! Regarding @kcgen 's queries:
1. I wasn't able to get the linked dosbox-staging stand-alone to run - libsdl2 not found error. So I uninstalled the snap, as well as SVN, and installed dosbox-staging from @FeignInt's PPA. I realised this had libsdl2 as a dependency. Running either the stand alone and the package dosbox-staging binaries, I can now hear MIDI in game again. So yes, it appears to be a snap permissions/access issue somewhere as @dreamer and @kcgen suspect.
2. I'll drop a link to the snap github page so that they can attend to this.
Thanks again!

**Comment by kcgen** [comment]
Good stuff @bradgy and excellent that @FeignInt's PPA had you covered in terms of dependencies!

I should have linked the full download page here: https://dosbox-staging.github.io/downloads/linux/

If you scroll down to the Ubuntu section, it gives you a copy-and-paste one-liner to grab all the dependencies. 

Glad you're up and running!
