### ISSUE TITLE
Support .KEY files alongside .KL

### ISSUE THREAD

**Issue by dreamer** [dosbox-staging/dosbox-staging#62]
Making this issue, so I won't forget ;) Lack of this feature caused me a little bit of pain while testing #61 and this might prove very useful in the future.

DOSBox supports changing keyboard layout via .KL files https://www.dosbox.com/DOSBoxManual.html#KeyboardLayout which is a minor feature for game emulation, but it is important nonetheless. All fine and dandy, except nowadays it is basically impossible to find .KL files online. FreeDOS stopped shipping them, but keyboard layouts can still be downloaded as .KEY files: http://www.ibiblio.org/pub/micro/pc-stuff/freedos/files/distributions/1.2/repos/pkg-html/keyb_lay.html

KC.EXE is a program, that translates a .KEY file to a .KL file. It was/is shipped with FreeDOS, but it seems not to be part of base system any more (not sure). Can be downloaded e.g. from here: http://www.ibiblio.org/pub/micro/pc-stuff/freedos/files/dos/keyb/2.0/

Fortunately, it can be just dropped inside DOSBox, used for creating a .KL file to be then loaded via built-in `KEYB`. It works.

It would be better if it worked out of the box somehow. FreeDOS includes GPL-compatible implementation of this program (and it's not complicated) - perhaps it should be included as a builtin in DOSBox? Or KEYB updated to work with .KEY files as well?

**Comment by krcroft** [comment]
Given the obscurity of this feature, I think documenting what you did to exercise this KL functionality is very valuable.

Talking about obscurity, I'm guessing modern operating systems hide or translate the keyboard layout relative to the applications and games running within the OS.  Otherwise I suppose every application and game would need their own config for keyboard layout; lest the user's controls be messed up.

What would be the use-case for KL imports today (that DOSBox's "mapper" feature can't provide)?

**Comment by dreamer** [comment]
This feature is needed to fully support typing (not sure about properly displaying) characters, e.g.: by default, DOSBox **won't take input** when I'll try to type in: ąęłźżó. To make it work, I need to set the layout to e.g. builtin `Z:\>keyb pl` (it loads [code page 852](https://en.wikipedia.org/wiki/Code_page_852) for QWERTY keyboard), but if I happen to use [QWERTZ](https://en.wikipedia.org/wiki/QWERTZ) (wiki article has nice map), then I'll need to load PL214.KL.

I think German (based on questions I found when Googling) and French (based on my experience with French speakers) users would be hit by this particularly hard. Also, multilingual users, who might want to switch in runtime (DOSBox documentation says it is supported).

Personally, I never needed to use it - for gaming, this is really niche feature. Might be important for some text adventure games from 80s, or for some old word processors.

Not a priority by any stretch, documented it so it won't slip my mind (or it might help land here via search engine).

**Comment by krcroft** [comment]
Wow - I had no idea! Thanks for explaining what's going on.

Sounds like figuring out your keyboard mapping is a huge **Step 2** (if `keyboardlayout=auto` or `keyb XZ` are sufficient or if a KL file is needed), right after downloading DOSBox. I can imagine some users start DOSBox, it locks their mouse, they're not aware of how to ctrl+F9 yet, and the icing on the cake is they can't even type `exit` property to get back out.

Would it make sense to pre-generate 99% of potential KL files, and deliver those with DOSBox (in a keyboard layout directory, along with notes)? Or are most use-cases going to need customization?

**Comment by dreamer** [comment]
Yeah, bundling more codepages (e.g. all the ones that FreeDOS provides) with the DOSBox might be a better way of addressing this than including KC or changing code. And I double-checked - I was wrong earlier, PL214 is already bundled with the DOSBox.

**Comment by krcroft** [comment]
Would more codepages be this set of `.key` files: https://github.com/joyent/sdcboot/tree/master/freedos/source/keydos (*), versus what DOSBox's `keyb` supports https://www.dosbox.com/wiki/KEYB ?  (https://github.com/dreamer/dosbox-staging/blob/master/src/dos/dos_keyboard_layout_data.h)

(*) Certainly not the official FreeDOS, but just came up first in a search.

**Comment by dreamer** [comment]
Comment in this DOSBox code:
```
/* This file contains data of .KL-files. They have been generated
   by Henrique Peron using FreeDOS KC and are combined into .SYS files. */

/* KC: compiles keyboard descriptors in KEY language to a KeybCB,
   wrapped in a KL file (for use of FD-KEYB 2.X)
   Copyright (C) 2004 by Aitor SANTAMARIA_MERINO */
```
Heh :) (This data dump was updated in 2007)

I think official "package" with key files is zip file here: https://www.ibiblio.org/pub/micro/pc-stuff/freedos/files/distributions/1.2/repos/pkg-html/keyb_lay.html. It includes 103 layouts.

**Comment by krcroft** [comment]
Thanks for digging these up @dreamer ; I think this wraps up the investigation side.

I noticed the keys are in a 200+KB zip, which would probably translate to a many-MB keyboard_data.h; maybe we switch to on-demand file based loading? I suppose this is a radical departure from everything being baked into the executable, which has its pros as well.

**Comment by kcgen** [comment]
@FeralChild64 - with your recent work sync'ing up with the latest FreeDOS 1.3 layout files, does that cover this ticket?

**Comment by FeralChild64** [comment]
No - it just updates the CPX (FreeDOS compressed CPI) and KEYB*.SYS files and performs the necessary adaptations in the code (+ some cleanups).

**Comment by Burrito78** [comment]
@kcgen Add documentation label and close so it can end up being in the new doco (link to it in new Doco issue hat has yet to be created)?

I'm german and never heard of this before.

**Comment by kcgen** [comment]
@FeralChild64, is the need for KL.EXE has been overcome by events, given the latest keyboard layout files from freedos are supported?

@dreamer , see `contrib/resources/freedos-keyboard/` (maybe these already incorporate the tweaks that KL does). 

Worst case, sounds like KL can easily be added to the bundled Y: tools.

**Comment by Grounded0** [comment]
Hopefully this goes somewhere... Not closing this.

**Comment by kcgen** [comment]
We're coming up on the 4-year mark with this ticket.

Closing it for now, as no one has reported it as a missing feature or a hole in functionality.

If it's requested again or if someone wants to implement it - we can always re-open it.

**Comment by Grounded0** [comment]
We're unlike to implement this since there is a tool available to do this and its a niche feature:

http://www.ibiblio.org/pub/micro/pc-stuff/freedos/files/dos/keyb/fdkeyb-2.0/kc200x.zip

GitHub mirror:

[kc200x.zip](https://github.com/dosbox-staging/dosbox-staging/files/13704465/kc200x.zip)

Use the bundled `KC.EXE` to do the conversion.
