### ISSUE TITLE
New files have incorrect timestamp after changing date in dosbox-staging session

### ISSUE THREAD

**Issue by dreamer** [dosbox-staging/dosbox-staging#620]
**Describe the bug**

Files created inside dosbox-staging DOS session have timestamp of OS, not timestamp of DOS session.

**To Reproduce**

    C:\>date 02-02-2011
    C:\>echo x > datefak
    C:\>dir datefak
    ...
    DATEFAK                       3 25-09-2020 12:56
    ...

**Expected behaviour**

DATEFAK should have timestamp indicating 2011, not 2020.

**Additional context**
This is long-standing issue (not a regression), somewhat related to lack of handling of DOS function 5701h (Set file time/date). After #227 will be merged in we'll have no excuse not to support this usecase as well :) That PR implements most of needed functionality to fix *this* issue.

**Comment by Burrito78** [comment]
@dreamer Any updates on this? Still planned?

**Comment by weirddan455** [comment]
I'm seeing several problems with our current timestamp implementation on files.  `fatDrive` appears to be handling this correctly but `localDrive` does not.  I've got a plan to clean this up.

**Comment by johnnovak** [comment]
> I'm seeing several problems with our current timestamp implementation on files. `fatDrive` appears to be handling this correctly but `localDrive` does not. I've got a plan to clean this up.

Out of interest, what actual problems does this cause?

**Comment by weirddan455** [comment]
>  Out of interest, what actual problems does this cause?

Not sure exactly.  I've never had to use that `date` command.  These `DOS_File` classes are kind of a mess in a lot of ways and I wanted to do some general cleanup on them regardless.

**Comment by johnnovak** [comment]
> These `DOS_File` classes are kind of a mess in a lot of ways and I wanted to do some general cleanup on them regardless.

Yeah, it sounds like a good idea. The DOSBox codebase is a refactoring enthusiast's wet dream, no doubt 😆

**Comment by dreamer** [comment]
> Out of interest, what actual problems does this cause?

I vaguely remember that we had problems with some installers (LucasArts maybe? not sure) doing timestamp checks as a form of primitive copyright protection.

**Comment by johnnovak** [comment]
> > Out of interest, what actual problems does this cause?
> 
> I vaguely remember that we had problems with some installers (LucasArts maybe? not sure) doing timestamp checks as a form of primitive copyright protection.

Interesting!
