### ISSUE TITLE
Environment variables not resolved properly in AUTOEXEC

### ISSUE THREAD

**Issue by NicknineTheEagle** [dosbox-staging/dosbox-staging#623]
**Describe the bug**
It seems that environment variables are not resolved properly if used with autoexec section in config file, specifically it doesn't parse slashes properly.

**To Reproduce**
Add the following entry to autoexec section in config:
```
set PATH=%PATH%;C:\TEST\
```
PATH defaults to ``Z:\``  but if you use it here, the command will discard everything after a slash and end up setting PATH to ``Z:``.

**Expected behaviour**
PATH variable is set to ``Z:\;C:\TEST\``.

**Additional context**

- Issue does not happen if I fire this command in the actual DosBox command line after it launched.
- Issue does not happen if I don't use an env var and put this into autoexec instead:
```
set PATH=Z:\;C:\TEST\
```
- Issue does not happen in upstream so this is a regression.

**Comment by dreamer** [comment]
> It seems that environment variables are not resolved properly (…)

True. This is the behaviour we inherited (unfortunately) from DOSBox :(

> (…) if used with autoexec section in config file, specifically it doesn't parse slashes properly.

This is false. The variable expansion is just not there.

And yeah, I would treat this as a bug - we should support environment variable expansion.

I remember investigating this issue once, and even identified the commit where support for expansion was added in DOSBox-X codebase, but the solution in there seemed weirdly over-complicated to me (but I haven't spent too much time).

**Comment by NicknineTheEagle** [comment]
> True. This is the behaviour we inherited (unfortunately) from DOSBox :(

Again, variable expansion does work properly in upstream, at least in lastest in SVN I assumed this is a regression.

**Comment by kcgen** [comment]
I think we're good; testing variable expansion with this PR:

![2020-09-26_08-47](https://user-images.githubusercontent.com/1557255/94344532-e77b7980-ffd4-11ea-995b-bb67a7546872.png)

**Comment by kcgen** [comment]
@dreamer - I will standby on this and suspect you're working on a more global solution w/ the `safe_strncopy` macro.
Let me know otherwise if you'd rather I address the comments here and we continue with this PR.

**Comment by dreamer** [comment]
Yup, in *these* cases it now works well - I was definitely wrong about expansion not working *at all*.

I will create a follow-up bug report, because we want `echo %path%` to work as well - and using env variables in all other contexts (those still do not work).
