### ISSUE TITLE
Environment variable expansion does not work in some contexts

### ISSUE THREAD

**Issue by dreamer** [dosbox-staging/dosbox-staging#628]
**To Reproduce**
```
Z:\>set foo=bar
Z:\>set foo=%foo%baz
Z:\>set foo
FOO=barbaz
Z:\>echo %foo%
%foo%
```

**Expected behaviour**
The same chain of commands should end with:
```
Z:\>echo %foo%
barbaz
```

**Additional context**
Not a regression - this behaviour was inherited from DOSBox.

**Comment by rderooy** [comment]
fyi, dosbox-x handles this properly.

**Comment by dreamer** [comment]
Yes, I know - some time ago I even found the commit that fixed it, but was a bit surprised - it looked overengineered a little bit.

I believe we could simply use C++11 regex instead of doing manual parsing the way that commit does it. I would also prefer to have a solution where env expansion is done in one place in code (and not have separate expansions for `=` expressions as it is done right now… unless there is some difference in how DOS handles variable expansion.

But hey, if someone else wants to save me trouble and port it, then create a PR - perhaps I am overthinking it :)

**Comment by Wengier** [comment]
@dreamer I have already created a PR (#632) by porting the DOSBox-X code. Please check it out.

**Comment by Wengier** [comment]
@dreamer So I tried to show how the ported code looks like in PR #632 (ported from DOSBox-X but it is not written by me). Please let me know if you prefer to port this code, or you want to go with a different approach.

**Comment by kcgen** [comment]
@ripsaw8080's kindly let me know that 

> ... env. var. substitution does not work at the prompt in MS-DOS 5/6, it only works in batch files. However, it does work at the prompt in the Windows command shell; and maybe it works from the prompt in MS-DOS 7, not sure about that, but 5/6 is what DOSBox targets.
> 
> It seems nothing is new under the sun; see this thread for reference: [SET command doesn't work](https://www.vogons.org/viewtopic.php?f=31&t=37678)
> Similarly, the forum gets reports about SET /P not working, but that also is a feature of the Windows command shell and not of DOS.
> 

Testing a batch file in SVN and staging, and indeed variable expansion correctly handled as ripsaw noted:

``` shell
set A=1
echo %A%
%A%
```

![2020-09-28_08-45](https://user-images.githubusercontent.com/1557255/94454733-13c6ff80-0167-11eb-932f-f4f970584d05.png)

**Comment by Wengier** [comment]
@kcgen It always worked in a batch file, but not in the **DOS shell**. Actually DOS 5.x/6.x does not support this either, but DOS 7.x adds support for environment variable expansions in the DOS shell as well.

**Comment by kcgen** [comment]
Given our focus is gaming, are there any DOS games that require DOS 7.x? 

If requiring DOS 7.x is a common theme, then it make sense to start to cataloging the differences between < 7.x and >= 7.x, and adding those behavior changes throughout the code.

**Comment by Wengier** [comment]
@kcgen You will decide for this of course. I just wanted to help @dreamer by showing how the ported code will look like, and I will close the PR if it is decided to not add support for this after all.

**Comment by kcgen** [comment]
Certainly not trying to decide; need more information: **are there any DOS games that require DOS 7.x?**

**Comment by kcgen** [comment]
That said; given we're only discussing the shell at this point (batch processing is already complaint) this becomes a nice-to-have, especially if shell users tend to use and generally but incorrectly expect variable expansion.

In that case, we could forgo this small user-space nuance if if makes users lives a bit better.

**Comment by Wengier** [comment]
DOS 7.x has quite a few nice-to-have small features that can make user lives a bit better (in addition to big ones like FAT32 and LFN support).  For example, REN command can rename directories as well, not just files. And it supports 4-digit years (DIR /4), unlike earlier DOS versions which only supported 2-digit years.

**Comment by dreamer** [comment]
@Wengier don't close the PR, please - thank you for porting this bit of functionality, when I'll have a moment I'll take a deep dive (yesterday I looked at other code, and I think in the code inherited from DOSBox we have code parsing `%varname%` in *two* places already - this would add third one to the mix. If possible I would like to clean this up and have proper tests. Your PR is very helpful here :)

@krc thanks for posting **ripsaw8080**'s insight here. I didn't even know MS-DOS was missing such basic feature even in version 5 or 6... I can't wrap my unixhead around the concept that variable expansion would work in batch files, but not in shell (this is so weird...).

When testing what works in DOS, I usually make a test on FreeDOS (where variable expansion in shell works - of course).

Now, this feature is not related to gaming, this is basic usability improvement in my opinion.

**Comment by kcgen** [comment]
Fixed in https://github.com/dosbox-staging/dosbox-staging/pull/632.
See comments at bottom of PR.

**Comment by Wengier** [comment]
Closing since it is already fixed.
