### ISSUE TITLE
Screenshot key can't be redefined

### ISSUE THREAD

**Issue by dreamer** [dosbox-staging/dosbox-staging#635]
**Describe the bug**
This was off-comment by one of users; haven't confirmed it myself, but we need to look into it.

[Original comment](https://twitter.com/PixelGordo/status/1307661926235766784) (via Google Translate):
> DosBox Staging has a bug and does not allow redefining the screenshot key ... so I still have fun adding two configurations to the keypad and pressing the three buttons at the same time to switch between configs (?)

**Comment by kcgen** [comment]
[mapper-sdl2-git.map.gz](https://github.com/dosbox-staging/dosbox-staging/files/5292898/mapper-sdl2-git.map.gz)

"works fine here"
gunzip attached, run, press `s` to take a screenshot.

**Comment by kcgen** [comment]
I guess the question is: can it be remapped to the buttons on this user's custom input box?

Maybe the box generates key-codes that either aren't being picked up by SDL or aren't part of the hard-coded set defined in the mapper? 

Branch `kc/echo-inputs-1` will log key sym-code numbers and key names; if the user can give this a go. 

![2020-09-28_08-41](https://user-images.githubusercontent.com/1557255/94454294-8daab900-0166-11eb-8728-3f88524d6200.png)

**Comment by kcgen** [comment]
Given the screenshot key _can_ be redefined without issue, I propose we close this in one week unless more information is brought forth.
