### ISSUE TITLE
Handling single % character in batch files results in hard to notice bugs

### ISSUE THREAD

**Issue by dreamer** [dosbox-staging/dosbox-staging#642]
**Describe the bug**

Originally reported as a bug in ECE: [vogons](https://www.vogons.org/viewtopic.php?p=898746#p898746).

In some contexts, users might want to place a single `%` character in a bat file.

For example, when writing a launcher that is supposed to reconfigure dosbox-staging to change CPU cycles setting.

This affects only one setting (`cpu.cycles`); in upstream it affects 2 (also `sdl.windowresolution`). There are also several other settings, that use value meaning percentage, but without parsing % char (`sdl.sensitivity`, `cpu.cycleup`, `cpu.cycledown`, `joystick.deadzone`, ECE `sblaster.fmstrength`) - those might actually benefit from parsing %.

**To Reproduce**

Example file `set50.bat`:

    config -set "cpu cycles=max 50%"

When running, dosbox-staging will ignore `%` character (so the code will behave as if `max` was passed). To make it work, user needs to write `%%`.

To test in other DOS environments following lines will be used:

```
@echo "1%"
@echo "2%%"
```

**Expected behaviour**

It's not clear what should be the desired behaviour. Different DOS shell implementations have different behaviour for this usecase.

**dosbox-staging 0.76.0-alpha, DOSBox 0.74-3, DOSBox ECE**
commands typed in shell print:
```
"1%"
"2%%"
```
.bat file prints:
```
"1"
"2%"
```

**DOSBox-X 0.83.6**
shell:
```
"1%"
"2%"
```
.bat:
```
"1"
"2%"
```
**FreeDOS**
shell: `Bad command or filename - "@echo"`
shell (without `@`):
```
"1%"
"2%"
```
.bat:
```
"1%"
"2%"
```
**MS-DOS 6.22, PC-DOS 5.00**
shell: `Bad command or file name`
shell (without `@`):
```
"1%"
"2%%"
```
.bat:
```
"1"
"2%"
```
### Non-DOS shells
**pwsh**
shell: `ParserError` (+description)
shell (without `@`):
```
1%
2%%
```
.bat (does not work)

**bash**
shell:
```
bash: @echo: command not found...
Similar command is: 'echo'
```
shell (without `@`):
```
1%
2%%
```
.sh script: (without `@`)
```
1%
2%%
```
**Wine (wineconsole)**
shell:
```
"1%"
"2%%"
```
bat:
```
"1"
"2%"
```

Not sure yet if/how we should fix it. Related to #628

**Comment by kcgen** [comment]
> To Reproduce
> `config -set "cpu cycles=max 50%"`
> When running, dosbox-staging will ignore % character (so the code will behave as if max was passed). To make it work, user needs to write %%.

The single percent is now correctly handled inside quotes, and the example given now correctly works:

![Screenshot from 2022-04-28 14-25-50](https://user-images.githubusercontent.com/1557255/165848509-cf429f08-a804-4fa3-a48c-23d769a46607.png)

Closing.
