### ISSUE TITLE
Poor performance on normal core

### ISSUE THREAD

**Issue by NicknineTheEagle** [dosbox-staging/dosbox-staging#643]
Dosbox-staging appears to have much worse performance on normal core compared to upstream, I hit the cap at around 12000 cycles on i5-9600k which doesn't even reach 486 performance before games start lagging while in upstream I can crank cycles all the way up to 77000 (Pentium 100 performance). The only workaround for this is to switch to dynamic core.

**Comment by dreamer** [comment]
What do you use normal core for?

**Comment by kcgen** [comment]
My understanding is that "cycles are cycles", regardless of which core processed them.  It's just that dynamic core is more efficient so tops-out at a higher cycle-count versus the normal core on a given host CPU. 

Will do some comparisons between svn and staging on the normal core. (There should be nothing notably different as we've tracked all the fixes from upstream, plus made small refinements regarding alignment and various warnings and security fixes.)

**Comment by dreamer** [comment]
In my experience - I use normal core to slow the emulation down and make it more predictable performance-wise. Recently I used it e.g. when we were testing Digger (as dynamic core was resulting in random speedups).

**Comment by kcgen** [comment]
Yeah, I can see that happening; within each 1ms-pass the dynamic core can barrel through the limited number of allotted cycles almost instantly versus the normal core which grinds them out slower. (even though at the end of the millisecond, both cores have delivered the same number of cycles).

**Comment by kcgen** [comment]
## Sources Compared
 - DOSBox SVN [r4369](https://sourceforge.net/p/dosbox/code-0/4369/)
 - dosbox-staging commit 1155eec9

## Compilation Flags

Both source trees were built using GCC 9.3.0 with the same flags:

``` shell
AR="gcc-ar"
CC="ccache gcc"
CXX="ccache g++"
LD="gcc"
RANLIB="gcc-ranlib"
ARFLAGS="Dcr"
CFLAGS="-Wall -pipe -fdiagnostics-color=auto -fpch-preprocess -DNDEBUG -O3 -fstrict-aliasing -fno-signed-zeros -fno-trapping-math -fassociative-math -frename-registers -ffunction-sections -fdata-sections -mfpmath=sse -msse4.2 -flto"
CXXONLY=""
LDFLAGS="-Wl,--as-needed -Wall -pipe -fdiagnostics-color=auto -fpch-preprocess -flto=4"
LIBS=""
export AR CC CXX LD RANLIB ARFLAGS CFLAGS CXXONLY LDFLAGS LIBS CXXFLAGS="${CFLAGS} ${CXXONLY}"
```

The above can be copy-and-paste into your terminal so you can reproduce the same binaries.
 - Be sure to include the last `export` line.
 - Perform a fresh build with: `./configure && make clean && make -j8`

## Test Platform

**CPU:** Intel G4400
**OS:** Ubuntu 20.04.1 LTS codename focal
**Kernel: ** Linux hoya 5.7.17-050717-generic #202008211236 SMP Fri Aug 21 12:41:39 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

CPU was locked at a fixed rate of 800 MHz using: `echo 1 | sudo tee /sys/devices/system/cpu/intel_pstate/max_perf_pct` to magnify performance differences.

## Runtime Test

A bare-bones conf file was used having machine type `vgaonly`, `normal` core running at 12000 cycles, and all sound devices disabled. 

**Program:** Quake 1.06
**dosbox configuration:** [dosbox.conf.txt](https://github.com/dosbox-staging/dosbox-staging/files/5322545/dosbox.conf.txt), was placed inside the game's directory.
**Time demo batch file**: [quake.bat.txt](https://github.com/dosbox-staging/dosbox-staging/files/5322544/quake.bat.txt)

Quake's time demo was launched simultaneously using this shell command:
`time -p /usr/src/dosbox-code-0-r4369-dosbox-trunk/src/dosbox  quakem0.bat & \`
`time -p /usr/src/dosbox-staging/src/dosbox-staging quakem0.bat &`

In an adjacent terminal, `top` was used to monitor the realtime usage of both physical CPU cores.

## Results

- During the test, `top` shows both builds using roughly the same CPU usage +/- a couple percent at any given time. 
- As the time demo proceeds, dosbox-staging does pull ahead slightly but the difference is negligible given it doesn't account for enough frames to affect its score.
- Quake reports identical durations and frame-rates for both executables. 
- The process times are also effectively identical coming within less than half of one percent of each other:
    - **SVN**: `real 259.12, user 186.00, sys 4.60`
    - **staging**: `real 259.14, user 184.90, sys 4.24`

**Discussion**: this is expected, and proof that staging's changes to address ~350+ Coverity bugs, hundreds of runtime bugs flagged by Clang's analyzer and GCC's sanitizers, and over 500+ warnings have be performed with care and are not detrimental to performance.

## Appendix

Screenshots from a 13000-cycle run at completing and 12000-cycle run in-progress.

![2020-10-03_18-59](https://user-images.githubusercontent.com/1557255/95005379-7f1c3180-05ac-11eb-9e3d-c9863785b940.png)
![2020-10-03_19-00](https://user-images.githubusercontent.com/1557255/95005380-7fb4c800-05ac-11eb-910e-4be5ad7e3a3e.png)

**Comment by NicknineTheEagle** [comment]
> 
> 
> What do you use normal core for?
> 
> _edit_ Maybe I'll explain why I'm asking :) I consider normal core to be usable only as a fallback in cases for very old games from 286 era, that otherwise will be unplayable due to too fast emulation. But maybe there are some usecases I don't know about.

The thing here is that "core" param defaults to "auto" by default which makes DosBox use normal core in real mode and dynamic mode in protected mode. The problem is that later DOS games require higher-end 386 or 486 level performance which can't be achieved in normal core right now.

**Comment by kcgen** [comment]
@NicknineTheEagle , when compiled with the same compiler and the same flags, both dosbox binaries perform identically. 

Are you running Linux, and can you perform a build using the above flags? (Alternatively, running `./scripts/build.sh -c gcc -t release -m lto` will do exactly the same).

**Comment by NicknineTheEagle** [comment]
Turns out I compiled DosBox-staging on Debug last time. I'm officially an idiot. Closed.

**Comment by dreamer** [comment]
Honestly, happened to me as well some time ago - I spent half an hour testing for performance regression only to discover I forgot to add -DNDEBUG to build flags…

Maybe we should add some indicator in the window title, so it would be clearer when debug build is being run?

e.g. instead of `<program> - <cycles> - dosbox-staging` it could be `<program> - <cycles> - dosbox-staging (debug build)`

**Comment by kcgen** [comment]
Great idea @dreamer ; even if we're not running benchmarks, it's always handy to know what kind of build one is running. 

It would be interesting if we could apply some slight color-shade (red or orange) to either the title bar or title text. 

Kind of like how running as root (usually) gives you a different colored shell prompt.
