### ISSUE TITLE
Window decoration is missing on some Wayland compositors

### ISSUE THREAD

**Issue by dreamer** [dosbox-staging/dosbox-staging#650]
@rderooy accurately summarized the issue:

> Something about wayland. I tested this with both dosbox-x and dosbox staging. And there is a problem... And due to this problem, I have removed the wayland line in the manifest for dosbox-x to disable it.
> 
> The issue is that with Xorg window decorations (title bar, min/max/close buttons, resizing controls) are so-called SSD (Server-Side-Decorations). Meaning we don't need to worry about them, or more accurately that SDL does not need to. And every app, regardless of toolkit used at least has the same window decoration.
> 
> Not so with wayland. Wayland instead uses CSD (Client-Side-Decorations). Meaning that the app is responsible, or the toolkit it uses. Meaning that a QT app will look different from a GTK app, etc. There is an optional extension called XDG-Decoration that allows SSD. This extension is supported by all wayland compatible window managers, except Gnome and Enlightenment. In fact the Gnome team have completely rejected it, and close and lock any bug reports requesting it.
> 
> This means that when you run dosbox-x or dosbox staging in wayland mode on Gnome, you get a borderless window. Try it yourself, if your running wayland how it looks on your system (no need for a flatpak):
> 
> SDL_VIDEODRIVER=wayland dosbox
> 
> The issue is that toolkits like SDL don't want to get into window management...
> 
> The only solution I have found is this library:
> https://gitlab.gnome.org/jadahl/libdecoration

@rderooy Everything you described is correct and it's the reason why dosbox-staging lists Wayland support as *experimental* in README.md (we know there's a number of Wayland-related issues and having reliable decorations is pre-requisite for dealing with them).

KDE and Sway implement Wayland SSD extension (does not magically solve all Wayland-related issues, but can be tested already), Mutter-based compositors do not (and likely won't). Gnome closed the issue because it degenerated into name-calling and there was no productive discussion in there :(

There are several routes to fix this situation:

- Wait for Gnome Mutter to implement SSD extension or send them patches (Mutter devs insist this is very hard; I think it might be possible, but I don't know how much work is needed). *This is a longshot, but if the problem was solved this way it would propagate through the whole ecosystem and perhaps SSD would be accepted in core Wayland protocol, so **the reward is big**.*
- Wait for SDL2 to integrate libdecorate; I think the first version of libdecorate is sort-of workable and first version of SDL2 patches were submitted already, but I don't follow the discussion in there. *Probably the most cost-effective way to solving the issue ATM; SDL2 devs communicated that they are willing to accept this solution.*
- Implement Client Side Decorations in dosbox-staging. I don't want to do it. We already need to deal with window-manager-specific issues (e.g. differences between Gnome and KDE). I don't want to make the situation even more complicated just to have functionality usually provided by a toolkit.
- Migrate away from using SDL2 window on all OSes to using native windows on Windows/Linux/Mac and keep SDL2 window as fallback. We would need to make sure we won't break things for dosbox-staging downstreams (e.g. Boxtron). *This would solve other issues as well, e.g. provide better integration on macOS or allow for embedding multiple icons on Linux*. We'll likely fo this route for dosbox-staging 0.77.0 or 0.78.0 (let's see how libdecorate thing will pan out in SDL2 first).

**Comment by kcgen** [comment]
> Wait for SDL2 to integrate libdecorate

Surely the vast majority of game-like SDL2 applications are doing exactly like dosbox is, and so will be similarly affected. 

Borderless and broken-feeling SDL applications on wayland will act like new-user-repellent who will avoiding it for other frameworks. 

It's Make-or-break time for the SDL team as wayland is already default or very close to being on other major distros.

- 2014 https://bugzilla.libsdl.org/show_bug.cgi?id=2710
- 2018 https://bugzilla.libsdl.org/show_bug.cgi?id=2710
- 2019 https://bugzilla.libsdl.org/show_bug.cgi?id=4845
- 2020 https://bugzilla.libsdl.org/show_bug.cgi?id=5194

**Comment by kcgen** [comment]
> Wait for SDL2 to integrate libdecorate

Surely the vast majority of game-like SDL2 applications are doing exactly like dosbox is, and so will be similarly affected. 

Borderless and broken-feeling SDL applications on wayland will act like new-user-repellent who will avoiding it for other frameworks. 

It's Make-or-break time for the SDL team as wayland is already default or very close to being on other major distros.

- 2014 https://bugzilla.libsdl.org/show_bug.cgi?id=2710
- 2018 https://bugzilla.libsdl.org/show_bug.cgi?id=2710
- 2019 https://bugzilla.libsdl.org/show_bug.cgi?id=4845
- 2020 https://bugzilla.libsdl.org/show_bug.cgi?id=5194

**Comment by dreamer** [comment]
> But.. how do we enable it?

It works out of the box. dosbox-staging with Wayland has decorations on KDE and Sway.

**Comment by rderooy** [comment]
> > But.. how do we enable it?
> 
> It works out of the box. dosbox-staging with Wayland has decorations on KDE and Sway.

That's only because they implemented the *optional* XDG-Decoration extension. Something that Gnome did not for Mutter. And my reading of the gnome bug report for this, is that they have no intention of implementing it, even if someone gave them a working implementation.

**Comment by dreamer** [comment]
@rderooy We all know it and we both mentioned it already :)

Gnome Mutter has no intention of implementing it, but if someone has free time to implement it for Mutter, then I bet they will be willing to discuss the patches (but there are many people demanding implementation, but not many willing to do the actual work).

**Comment by Svadkos** [comment]
From what I've read they don't want parts of toolkits in mutter, which would be a requirement for ssd. And that won't change even if someone would send patches. It would be better to work on libdecoration instead, because it doesn't seem to be actively worked on, and it's the only viable solution beside using a native toolkit.

**Comment by dreamer** [comment]
I don't think putting Gtk in Mutter is a hard requirement for SSD (it's one of possible implementations, yes - but perhaps not the only one). I mean: XWayland windows are decorated via Gtk already, so perhaps Wayland -> Gtk decorator -> Wayland bridge can work in a similar manner. I don't know nearly enough about Mutter internals to say that it's definitely possible or not - just that AFAIK nobody tried.

**Comment by Svadkos** [comment]
https://gitlab.gnome.org/GNOME/mutter/-/issues/217#note_749634

**Comment by okias** [comment]
Try SDL compiled with recently merged https://github.com/libsdl-org/SDL/commit/9e6fcbe72c3550d2007d54bcdab1178f90803eda .

**Comment by kcgen** [comment]
Sdl2 2.0.16 supports libdecorate and it works with Wayland. This is just a matter of time before this makes it way into more stable repo packages and is rolled out for wider user. Closing this.
