### ISSUE TITLE
Adjustable max open files

### ISSUE THREAD

**Issue by Mikaka27** [dosbox-staging/dosbox-staging#656]
**Is your feature request related to a problem? Please describe.**
I have an old program, which relies on adjusting max open files in Windows 95.
It is suggested to set 255 as the limit, program doesn't work with 127.
Program is old and will never be "fixed" to not require this.
Besides this setting, program seems to work fine.

**Describe the solution you'd like**
If possible the best solution seems to expose max open files via dosbox config file.

**Describe alternatives you've considered**
Alternative would be to raise the limit to 255 permanently, however I think there is a reason, why it is lower currently.
Only other possibility I found is to use dosbox-svn-daum version, but it's outdated and no longer maintained.

**Additional context**
Currently as I understand the setting is hardcoded in dos_inc.h file, at line 74
`#define DOS_FILES 127`

**Comment by kcgen** [comment]
@Mikaka27 , are you able to adjust this value and test your own build, and see if that solves it?

I think DOSbox-X might allow this to be configured at runtime; so that might be another option -- @Wengier, can you confirm?

**Comment by Mikaka27** [comment]
Hi,
I did a local compilation, and only changed DOS_FILES to 255. This resolves the issue for me.
So it looks like having it configurable, would help my case.

**Comment by dreamer** [comment]
I took a brief look at places where DOS_FILES is used and simply raising the limit to 255 will result in bugs (e.g. dosbox will hang when creating new file when there are 255 or more files in a directory). Therefore some additional adjustments are needed to raise this limit.

In DOS, max limit of open files per process is 20 (it's defined somewhere else (in PSP) - it's not DOS_FILES). After some searching I found [this](http://info.wsisiz.edu.pl/~bse26236/batutil/help/FILES_S.HTM), which suggests we should be able to safely raise the limit to 255, but I need to dig more.

I suspect me might avoid making this option configurable (unless value 255 breaks some games).

@Mikaka27 out of curiosity - what software has this problem?

**Comment by Wengier** [comment]
@kcgen There is a [config] section in DOSBox-X's configuration to emulate DOS's CONFIG.SYS, so you can for example set FILES=100 so that DOS_FILES will be set to 100 at start. For now it cannot be changed at run-time though.

**Comment by kcgen** [comment]
Thank you @Wengier.

@Mikaka27, [DOSBox-X](https://dosbox-x.com/) is an immediate option to run your Windows 95 application, as X strives to support Windows 95 in a complete sense (large system memory size, bigger HDD partitions, large video mem sizes, etc). 

That said, like @dreamer said if we can crank FILES up to 255 globally without detrimental impact to games, this will be a low risk change we can add to staging as well. 

@dreamer - interesting; I recall programs crashing hard when they attempted to exceed the open-handle limit. Would be interesting to learn of a game that actually requires a lower limit (perhaps if it can query the environment?).

**Comment by Mikaka27** [comment]
@dreamer The software is "subiekt 4", old dos program for accounting, taxes and everything. Funny that is still works fine, however I run it on Windows 95 PC, and would like to remove that from the equation, and use modern linux or windows 10.

@kcgen I've tried dosbox-x and was indeed able to set max files to 255, and program also runs fine there.

I'm wondering which dosbox would be better for this, since dosbox-staging automatically scaled the window correctly, but it was easy to fix in dosbox-x. However I'm also looking for lpt printer support, and don't see options for it in dosbox-staging.
Is dosbox-staging more focused on old games rather than general software?

**Comment by dreamer** [comment]
> Is dosbox-staging more focused on old games rather than general software?

Yes. We make some conscious trade-offs to make game emulation better, at the cost of not supporting various edge-cases required by productivity software. DOSBox-X makes different trade-offs and is generally better suited to run non-gaming software.

In case of this problem (max file limit), I think the fix will be small enough, will improve code (when all places using this limit will be adjusted), and risk of regressions is minimal, so we will likely hardcode new limit to 255 (preferably not configurable though, to avoid adding testing burden).

Regarding LPT printer support - I think DOSBox-X supports it (not sure); for dosbox-staging nobody requested it yet (I am ok with supporting it in a limited capacity - e.g. printing to text file or to pdf), but it will take some time, as we prioritize gaming-related features first. Feel free to make a new feature request if you would like to see this feature in dosbox-staging :)

About simulated floppy drive - can you expand on this point? We do support mounting directories and imgmounting image files as "fake" floppy drive.

**Comment by Mikaka27** [comment]
Hi,

Regarding printer support if possible I would like to use real old style dot matrix printer.
Only other printer I have is wifi connected, so not sure whether it is possible to use it.

Regarding the simulated floppy drive I'm talking about commands I use with dosbox-x: `imgmake` and `imgmount` commands.
Here is a complete script (for linux) to run the software with simulated floppy drive, I'll have to add lpt printer support, and make a windows .bat script.

```
#!/bin/bash

echo "Uruchamia sie Subiekt 4 MEGA. Prosze czekac..."
dir="$(pwd)/.."
resolution=$(xdpyinfo | grep dimensions | sed -r 's/^[^0-9]*([0-9]+x[0-9]+).*$/\1/')

images=ARCHIWUM

name=DYSK
ext=IMG
i=1
while true ; do
    floppy="./$images/$name$i.$ext"
    if [[ ! -e "$floppy" && ! -L "$floppy" ]] ; then
        break
    fi
    let i++
done

dosbox-x -noconsole -c "mount c \"$dir\"" -c "C:" -c "cd SYSTEM" -c "mkdir $images" -c "cd $images" -c "imgmake $floppy -t fd_1440" -c "exit"
begin_sum=$(md5sum "$floppy")

dosbox-x -noconsole -set "sdl fullscreen=true" -set "sdl fulldouble=true" -set "sdl fullresolution=$resolution" -set "sdl windowresolution=$resolution" -set "sdl output=opengl" -set "config files=255" -set "config fcbs=255" -c "mount c \"$dir\"" -c "C:" -c "cd SYSTEM/$images" -c "imgmount A: $floppy -t floppy" -c "cd ../.." -c "SYSTEM\S4CD.COM" -c "SUB4.EXE +X -T" -c "exit"
end_sum=$(md5sum "$floppy")

[ "$begin_sum" == "$end_sum" ] && rm -f "$floppy"
```

**Comment by Wengier** [comment]
@dreamer LPT printer is indeed supported by DOSBox-X for some time. I can confirm this.

@Mikaka27 Since you are talking about usages in DOSBox-X (not dosbox-staging),  you probably want to post your questions/suggestions in the DOSBox-X issue tracker instead (**not** the dosbox-staging issue tracker which is for dosbox-staging):

https://github.com/joncampbell123/dosbox-x/issues/

P.S. You can find printing support in DOSBox-X in this Wiki page: https://dosbox-x.com/wiki/Guide%3ASetting-up-printing-in-DOSBox%E2%80%90X

**Comment by Wengier** [comment]
On the other hand, vanilla DOSBox has refused to add support for LPT printer for a long time. I think the reason they did this is that they believe this feature is not useful for DOS gaming. So whether to add a specific feature indeed depends on the scope of the said project to a large degree.

**Comment by Mikaka27** [comment]
Sorry for wandering off topic :)
I will keep discussion about increasing dos files here only.

**Comment by Wengier** [comment]
@Mikaka27 Yes, for suggestions related to dosbox-staging please post here. For DOSBox-X related questions etc please post them in the DOSBox-X issue tracker.

**Comment by Wengier** [comment]
@Mikaka27 I have opened an issue in DOSBox-X's issue tracker for running your software ("subiekt 4") in DOSBox-X. Please post any issues for running the software in DOSBox-X here: https://github.com/joncampbell123/dosbox-x/issues/1942

This thread on the other hand will be for increasing dos files in dosbox-staging.

**Comment by dreamer** [comment]
@Mikaka27 Tak z ciekawości - drukarka którą masz podłączoną przez USB to do kasy fiskalnej? Niestety nie mogę znaleźć żadnej archiwalnej wersji Subiekta 4 na stronie insertu :(

**Comment by dreamer** [comment]
@Mikaka27 limit raised to 255 was just merged in master; I hope we won't need to revert it before 0.76.0 (I don't think so, it's unlikely to cause regressions).

For printer support - please create a separate feature request for that, thanks! :)
