### ISSUE TITLE
DIR command is broken

### ISSUE THREAD

**Issue by NicknineTheEagle** [dosbox-staging/dosbox-staging#662]
**Describe the bug**
DIR command does not list files, at least when used in a mounted host directory. It says ``File *.* not found`` even though the files are there and can be accessed directly.

**To Reproduce**
Mount a host directory with MOUNT command (e.g. ``MOUNT C D:\DGAMES``), enter the mounted drive and type DIR.

**Environment**
Windows 10 64-bit

**Additional context**
I remember it working fine not that long ago so it must be a recent regression.

**Comment by dreamer** [comment]
@NicknineTheEagle thank you for report and creating the issue.

Bug was introduced by 41d249fb4e81835114ad096992ce851c39bfdbda - I reverted it already.

I see some issues in my commit, but I don't understand why the same code worked on Linux. @kcgen any idea?

**Comment by dreamer** [comment]
(keeping the bug report open, because I want `path_exists` function back in - it's part of refactoring for other tasks)
