### ISSUE TITLE
Add COUNTRY parameter

### ISSUE THREAD

**Issue by NicknineTheEagle** [dosbox-staging/dosbox-staging#663]
**Is your feature request related to a problem? Please describe.**
DosBox currently doesn't support international regional standards. There's a single standards table built into the code which is pretty weird, date format is mm-dd-yyyy and time is 12-hour - this doesn't match any of the existing regional standards to my knowledge. On top of that, DIR command doesn't use said table at all (it's supposed to be fetched using DOS function 38h) and instead uses hardcoded output format which has dd-mm-yyyy date format and 24-hour clock.

**Describe the solution you'd like**
DOS has COUNTRY parameter in CONFIG.SYS where you specify country code, default code page and the file from which to load regional standards for the specified country code. Applications then use DOS function 38h to fetch the loaded standards to determine how to display time, date, numbers etc.
We can implement the first part, country code, as a parameter in [dos] config section which would determine which regional standards to use and then rewrite DIR command to actually use the different standards. This would make DosBox a bit more user-friendly since DIR command would be able to display time and date in user's native format.

**Additional context**
There's a table here but it doesn't include everything (e.g. Russia is missing): https://dos4gw.org/country_codes It also doesn't actually match MS-DOS 6.22 standards but I'm not sure if that's what we want to target. We could simply borrow modern standards from Windows 10 instead.

**Comment by dreamer** [comment]
I agree 100%. Additionally: `date` command uses hardcoded US-style formatting mm/dd/yyyy (and it's even inconsistent with help string in that command, which suggests mm-dd-yyyy). We definitely want to sort-out this mess, because US/UK style dates are confusing for the rest of the world.

This request is a little bit related to #394 (the locale detection part).

**Comment by dreamer** [comment]
It also functionally conflicts with option `language` in section `dosbox`, but we can figure it somehow (e.g. we could make `country` trigger one of built-in translations and `language` additional user setting).

Unfortunately, DOSBox translation files are sort-of out of date; I think I'll dump them in `contrib/` directory anyway, just so we won't need to hunt them down all over the internet and could start making them usable again.

**Comment by NicknineTheEagle** [comment]
> because US/UK style dates are confusing for the rest of the world

I think you got things mixed up, UK date format is dd/mm/yyyy which is the same element order as most of Europe.

**Comment by dreamer** [comment]
Ah, you are right - it's not even english-speaking countries… US is, erhm, "unique" when it comes to date format.

**Comment by kcgen** [comment]
Even though some countries standardized fully ambiguous date formats such as "02-03-04", we certainly don't need to uphold their erroneous traditions.  Ambiguous standards are a form of anti-standard, and we should not follow in their failed footsteps:

![f678bba5ff5ee0a9ade2a696033e4ff1](https://user-images.githubusercontent.com/1557255/95800369-fc7e2b00-0cab-11eb-885b-46f670eca66e.jpg)

I'm all for gentle enforcement of temporally-sortable ISO date standards in full YYYY-MM-DD format, and by extension.. HH:MM:SS if **date + time** are needed.

**Comment by NicknineTheEagle** [comment]
@kcgen AFAIK doesn't actually support full year display.

**Comment by kcgen** [comment]
Right; but we do have control of the emulated shell  commands and how they print dates.

**Comment by NicknineTheEagle** [comment]
Apparently, DosBox-X has already implemented this in some form, we could check their code out for reference.

**Comment by NicknineTheEagle** [comment]
Implemented in https://github.com/dosbox-staging/dosbox-staging/pull/1483.
