### ISSUE TITLE
Debian package

### ISSUE THREAD

**Issue by okias** [dosbox-staging/dosbox-staging#664]
**Is your feature request related to a problem? Please describe.**
Have dosbox-staging packaged for Debian.

**Describe the solution you'd like**

- [x] 1. create some salsa repository and package dosbox-staging
- [x] 2. create [ITP](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=973822) and get dosbox-staging into Debian  (dosbox is already there)
- [ ] 3. wait until it get accepted into Debian
- [ ] 4. Ubuntu will likely just take the package from Debian

**Describe alternatives you've considered**

**Additional context**

Ref: https://github.com/dosbox-staging/dosbox-staging/issues/418

**Comment by dreamer** [comment]
Yes, I would love for dosbox-staging to be packaged for Debian, but we need new contributor - dedicated Debian packager - to accomplish that.

Just the same way we already have dedicated packagers for Gentoo, Homebrew, AUR, FreeBSD (and more in progress).

I hoped @FeignInt will submit [his package](https://github.com/FeignInt/dosbox-staging-deb) for inclusion in official repos.

Keeping this issue open for discussions with potential Debian packagers and communication with Debian project.

**Comment by okias** [comment]
There is "something" https://salsa.debian.org/okias-guest/dosbox-staging 

it's WIP, but I managed to run dosbox-staging on [Librem 5](https://puri.sm/products/librem-5/) devkit.. but it'll need much more love! :smile:

**Comment by FeignInt** [comment]
Hi all

Thanks to @okias I have been inspired to create a Salsa account and begin a package more in line with Debian.

https://salsa.debian.org/Feignint/dosbox-staging

This is much less hacky than the [push to PPA](https://github.com/FeignInt/dosbox-staging-deb) version.

The repo currently holds two branches
- **debian/latest**  debian/* only
- **upstream/release/0.75.x**, 'upstream' src, with tags

salsa CI/CD defaults to using gbp ( git-buildpackage ) for build/test pipelines
I have tweaked the default configuration  slightly to take advantage of gbp's --overlay feature.
( this is how/why I have a debian/ tree only branch )

Assuming all build-deps are met, simply 

```
gbp buildpackage \
    --git-overlay \
    --git-export-dir=../build-area
``` 
should be enough to get a package out of it ( at some point I hope to write a wiki with more detail )

builds are available on salsa, check the [commit history](https://salsa.debian.org/Feignint/dosbox-staging/-/commits/debian/latest/)
look for Tick Icon to the left of the commit sha, click that and then use the download artifact to the right...

alternatively:

https://salsa.debian.org/Feignint/dosbox-staging/-/pipelines
 
and explore the filters

The **debian/copyright** file is what I'm most concerned with at the moment, it was mostly auto-generated, I have fixed obvious errors in it, but really it needs more eyes on it..

As pointed out by the [lintian report](https://feignint.pages.debian.net/-/dosbox-staging/-/jobs/1092408/artifacts/debian/output/lintian.html)
:warning: that link may 404 if this post is old

The debian/control has duplicate description..
Well, yeah, the debugger package is the same with a note about it being the debugger.

still, it reminds me that I simply lifted the text from dosbox-staging.io/about

```
Description: x86 emulator for DOS-era video games
 dosbox-staging is an attempt to revitalize DOSBox's
 development process. It's not a rewrite, but a continuation
 and improvement on the existing DOSBox codebase while
 leveraging modern development tools and practices.
 .
 This package contains the dosbox-staging debugger.
```

If anyone wants to improve that description, please do :)

https://www.debian.org/doc/debian-policy/ch-binary.html#s-descriptions

Regards  the spelling errors reported by lintian, don't worry about those, @okias has already fixed them.

I have listed some initial issues:
https://salsa.debian.org/Feignint/dosbox-staging/-/issues

**Comment by dreamer** [comment]
> If anyone wants to improve that description, please do :)

https://github.com/dosbox-staging/dosbox-staging/pull/680 - waiting for feedback :)

**Comment by arrowgent** [comment]
im not fantastic at deb packaging

but for such a minimal install ive just placed it in:
~/.local/bin
rn dosbox dosbox-staging
create
~/.local/games/dosbox-st
which is a script that calls to ~/.local/bin/dosbox-staging

due to so many dosbox wishing to all be called "dosbox" and all wanting to go into /usr/bin
which is fine too, package and put it as /usr/bin/dosbox-staging

thats the issue i see is the binary conflict with "dosbox"
atleast for now there is only one binary file required for dosbox.

i have dosbox-svn, dosbox-x, and dosbox-staging all installed

i also have a script that firejails dosbox (just incase i dont trust the dos software, or testing)

**Comment by dreamer** [comment]
I will quote myself from 0.75.2 release notes:

> We strongly suggest keeping our default binary name: `dosbox`. DOSBox Staging is a drop-in replacement for older DOSBox versions - some existing and popular programs, such as Wine and GUI frontends, depend on the `dosbox` binary name. It's also the default name of our man page and appears in the documentation.

We have reasons to keep this as our binary name. Users are free to override it on their systems, of course, but packagers should stick to using our default, please.

BTW, I think there's a configure option that allows to change the binary name during the build process? I'll try to find it.

Back to topic of Debian package though: did anyone actually submit the package for review to Debian? Can we get a link to that topic in here?

**Comment by FeignInt** [comment]
> BTW, I think there's a configure option that allows to change the binary name during the build process? I'll try to find it.
> 

it is **--program-suffix=**
it affects two things in dosbox-staging
1. the dosbox binary
2. the dosbox.1 manpage

```
./configure ... --program-suffix=-suffix
```
|without|with|
|- |- |
| ...bin/dosbox | ...bin/dosbox-suffix |
| ...man1/dosbox.1.gz | ...man1/dosbox-suffix.1.gz |

.desktop would need a fixup, but that isn't bundled by default

I did briefly look at it when doing the Push to PPA
FeignInt/dosbox-staging-deb#7
The Debian DOSBox 'manually' moves the binary and symlinks the  manpage, making the *dosbox* package a dependency of *dosbox-debug*
Ultimately I would like to remove that dependency. I have not got round to looking to see if a separate 'debugger' manpage is warranted ( outside of launching I've not used the debugger ), I do recall someone expressing a wish to completely overhaul the debugger UI, but can't find the issue#  

> Back to topic of Debian package though: **Did anyone actually submit the package for review to Debian?** Can we get a link to that topic in here?

I haven't got that far yet, it is all a learning curve for me
But I will read around the subject to figure out what is needed etc.

**Comment by okias** [comment]
IMHO I'd try to rather have **DOSBox Staging** as persistent and strong brand to let people rename it as they want to. Most people will run DOSBox Staging trough launcher. Minority will just write dosbox[tab key] and [enter]. It doesn't matter much, how will be these files named, on other hand it matters a lot to have consistency.

Consistent brand is very important for product and changing name by distribution/packager/user may impose bad experience while bringing advantages close to zero.

**Comment by okias** [comment]
@FeignInt are u up to getting it into Debian, right? I could create [ITP](https://wiki.debian.org/ITP), if you want to and point it to your repo.

**Comment by FeignInt** [comment]
@okias yeah, would be nice... I've not got round to reading what is involved yet.
I opened an issue on my end, so it is on my TODO list.
https://salsa.debian.org/Feignint/dosbox-staging/-/issues

@okias for Debian package, The [alternatives system]( https://wiki.debian.org/DebianAlternatives) should be used.
Which is basically a frontend to symlinks

outside of triage, I don't see why anyone would need both installed, as dosbox-staging is a direct replacement. So using **Conflicts: dosbox** is enough.

I guess a **debian/dosbox-staging.links** which symlinks **dosbox => dosbox-staging** ( and manpage ) would do if you really wanted a dosbox-staging bin

I can see the DebianAlternatives being useful if DOSBox-X is packaged, users my find value in having both packages installed.

**Comment by dreamer** [comment]
> Minority will just write dosbox[tab key] and [enter]. It doesn't matter much, how will be these files named, (…)

That's not true… the normal way of using both DOSBox and DOSBox Staging is to run via game-specific .conf file(s), like this:

    $ dosbox -conf game.conf

or:

    $ dosbox -conf setup.conf -conf game.conf

or:

    $ dosbox -c 'cmd1 -c 'cmd2' -exit

or:

    $ dosbox GAME.EXE   # this is automatically translated to: -c 'mount C .' -c 'C:' -c 'GAME.EXE'

Users are free to come up with various ways to utilize this (creating their own wrapper scripts, desktop entries, making .conf file executable with hashbang - whatever).

This often happens not directly by user action, but rather via GUI frontend or program installing game and conf file (e.g. Lutris, or Steam w. Boxtron, or GameHub, or Minigalaxy, or many, many others). Also, very notably, Wine does this - when user runs DOS executable via `wine`, then Wine-specific parameters are passed to `dosbox`...

*I can list more usecases if needed…*

If you will rename the binary name, you will need to patch the desktop entry, man page, README, and metainfo.xml file as well. Probably also our source code, because our config dir is: `~/.config/dosbox/`, and it will cause user confusion once we'll start uploading tutorials and documentation online. Then you will need to start sending patches to all GUI frontends to recognize dosbox-staging as a separate binary. *Don't do this, please*.

Normal users want just one version of dosbox installed. Testing games in 4 different dosbox client is *not normal* (except during development, and developers will want to compile their own version of DOSBox SVN anyway).

**Comment by dreamer** [comment]
> @okias for Debian package, The [alternatives system](https://wiki.debian.org/DebianAlternatives) should be used.
> Which is basically a frontend to symlinks

Yes! :)

**Comment by okias** [comment]
[ITP](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=973822) created.

**Comment by soredake** [comment]
Any progress on this?

**Comment by dreamer** [comment]
We are waiting for Debian reviewers to do *something* :\

**Comment by kcgen** [comment]
Maintaining repository packages is outside the scope of the project (closing).

**Comment by shmerl** [comment]
What is needed to move this forward? Looks like it's been almost a year since last progress update [here](https://github.com/dosbox-staging/dosbox-staging/issues/664).

**Comment by kcgen** [comment]
@shmerl , thanks for the ping.
My guess is this "long description" is some metadata field in the debian package contribution, however, I didn't see such a field skimming the files here: 

https://salsa.debian.org/okias-guest/dosbox-staging/-/tree/debian/latest/debian

We don't have the cycles to maintain repo packages, but appreciate all contributions to include Staging as another DOSBox choice in various distros. 

The project defers to their judgement for how to package it, describe it, and progress it to meet the needs of the repo mainteners and configured best for their OS/platforms. 

So in this case, if the repo maintener wants a better description, please make it so. 

Perhaps: "DOSBox Staging is a fork of the DOSBox project."

That's just a suggestion; hopefully it can get the ball rolling.

**Comment by shmerl** [comment]
@FeignInt: Can you please add that description update or may be ask Debian maintainers what the "long description" is exactly?

**Comment by okias** [comment]
Note, if anyone wants to update my debian package port, I'll gladly give access to the repository on Salsa.

**Comment by shmerl** [comment]
@okias: I'll try to log-in to Debian Salsa using Gitlab (something isn't working there now). And then may be ask what is needed for the "long description".

**Comment by okias** [comment]
I started [Package Salvaging](https://www.debian.org/doc/manuals/developers-reference/pkgs.en.html#package-salvaging) in the Debian, so we may have gain `dosbox` package (which is abandoned for many years).

See the https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1036708

**Comment by shmerl** [comment]
Nice! Replacing dosbox with dosbox-staging would be very welcome.

For now I ended up using it simply locally.

**Comment by shmerl** [comment]
Either way, I'd like to see dosbox-staging in Debian either as a new package or as a replacement for the original one. Not familiar with dosbox-x.

**Comment by shmerl** [comment]
So what's the current state of this? I'm a bit confused with various Debian tickets like replacing and packaging new one?

**Comment by shmerl** [comment]
Any news on this? https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1036708

**Comment by Grounded0** [comment]
If someone wants to get DOSBox Staging on Debian they need to do it themselves. Asking others to do something while no one is committing to do anything themselves usually doesn't work.

**Comment by johnnovak** [comment]
@shmerl Please ask the Debian maintainers, not us. We don't maintain the DOSBox Staging packages for any Linux distros; that's the repo maintainers job, not ours.

**Comment by Grounded0** [comment]
`dosbox` package is being eliminated on March 30 2024:

https://tracker.debian.org/pkg/dosbox

**Comment by shmerl** [comment]
Since Debian packaging takes forever to materialize, right now I just install it all locally to `$HOME/.local/bin` and $HOME/.config/dosbox`.

**Comment by shmerl** [comment]
> dosbox package is being removed on 30 March 2024:

I wouldn't mind it being removed so maintainers there would switch to dosbox-staging finally, but that's not what's happening. It's just the 64-bit time_t transition hiccup:

[64-bit time_t transition](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1062904)

**Comment by shmerl** [comment]
Side note, not sure why Debian maintainers aren't replacing dosbox with dosbox-staging, but may be they aren't taking the name seriously? The name sort of implies a perpetually incomplete / in-development version that supposed to contribute to the actual release one. But that's not actually the case?

I hope the unfortunate name isn't the misleading factor here.

**Comment by Grounded0** [comment]
Let's just say that i know Debian people hence the reason i got the heads up. None of them is willing to go through the bureaucracy to do this even after i offered them a 300 USD bounty to get it done.

**Comment by shmerl** [comment]
That's weird. There literally is no reason to use "regular" dosbox which is a dead project. How much bureaucracy is there to replace it? Though Debian has all kind of maintainers. It ends up being what kind of people they are more often than not.

**Comment by okias** [comment]
IMHO I'm stuck a bit on motivation, because I haven't found way to add on-screen control to the any dosbox* thing to be able use it without keyboard on phones :(

**Comment by Grounded0** [comment]
Still waiting for someone to get this done in mid 2024 on a software with millions of users.

**Comment by Grounded0** [comment]
There is a 200 USD bounty now to get this done:

- #3677
