### ISSUE TITLE
Add Separate Fsynth Gain Value In Confs

### ISSUE THREAD

**Issue by Zombeaver** [dosbox-staging/dosbox-staging#682]
I know that a certain amount of adjustment can be handled via mixer FSYNTH # but it would be useful to have a separate SF2-specific gain modifier that's configurable in .confs in order to be able to adjust it independently (for normalization).

**Comment by dreamer** [comment]
Related to #262 (but let's keep it as a separate issue).

**Comment by kcgen** [comment]
I tend to have a handful of SF2 entries, and it would be very nice to carry along the SF2's optimal scalar factor on the same line, for example:

``` ini
[fluidsynth]
soundfont = ../aracho-1.0.sf2 0.9
# soundfont = ../chorium-rev-a.sf2
# soundfont = ../compifont-13082016.sf2 1.1
# soundfont = ../fatboy-v0.789.sf2 0.8
# soundfont = ../general-user-gs-1.471.sf2 0.9
# soundfont = ../lau-gm-v1.0.sf2 1.0
# soundfont = ../merlin-silver.sf2 1.0
# soundfont = ../musescore-general.sf2    
# soundfont = ../musyng-kite.sf2 0.7
# soundfont = ../sgm-v2.01-steinway-guit-bass-v2.7.sf2 1.1
# soundfont = ../toh-3.4.sf2 0.2
```

This syntax would make it obvious that the scalar is meant specifically for the SF2 in question.

The upcoming SoftLimit + FluidSynth PR will provide us with a percent-of-max output that will let us dial-in these settings, so we can easily post a wiki table of suggested scalars for the popular soundfounts (the above are just random.. except for Timbers of Heaven ;-).

We could make the second value optional (like I've shown in the second `soundfont =` entry above), and could bound it to a reasonable range, like 0.05 up to 5.

Two questions:
 - What do you think of this paired syntax?
 - Has anyone come across a soundfont requiring even more extreme scaling (up or down)?

**Comment by Zombeaver** [comment]
> What do you think of this paired syntax?

I like it. I think that would work fine, personally.

> Has anyone come across a soundfont requiring even more extreme scaling (up or down)?

I don't believe I ever have. ToH is the only one I've ever had to adjust to any really significant degree, and it was definitely (well) within the sort of range you're proposing.

**Comment by dreamer** [comment]
Before implementing this - @Zombeaver can you test FluidSynth with newly merged SoftLimiter? (just use the newest build from https://dosbox-staging.github.io/downloads/devel/) In practice it adjusts the sound volume automatically - perhaps it removes the need for having a separate control?

My tests in HoMM2 were very positive in this regard (game allows for changing sound in-fly between CD Audio and MIDI) - with SoftLimiter merged, the volume is the same out of the box, no matter what soundfont I tested (Timbres of Heaven included - but this soundfont does not work very well in HoMM2, surprisingly).

**Comment by Zombeaver** [comment]
Is there a difference between the SoftLimiter in 859 and what's in place now? Because 859 is what I'm using and I was under the impression the SoftLimiter was already in place.

I'm not sure that a limiter in and of itself removes the need for a separate control anyway, since you might not necessarily _want_ the volume to be the same as CD.

**Comment by dreamer** [comment]
SoftLimiter was merged to master in v0.76.0-alpha-874-gfcae63cc; before that, we used raw output as coming from FluidSynth.

**Comment by Zombeaver** [comment]
I'm happy to test it out, but as I said I don't think that inherently removes the need for the ability to adjust. Not all games actually have adjustable volume for music.

**Comment by dreamer** [comment]
But we already do have volume adjustment: `mixer`. If SoftLimiter does its job, and you can swap soundfonts without need for adjusting the gain, then we can focus on having single place for volume adjustment instead of few separate user-facing mechanisms.

**Comment by Zombeaver** [comment]
I just did some testing with Betrayal at Krondor with FluidR3 and it sounds basically the same as before which, to my ear, is a bit too loud. There's also no ability to adjust the volume in-game.

**Comment by kcgen** [comment]
@Zombeaver , if you're launching BaK with a batch file or use the [autoexec] block in a local conf, drop in `mixer fsynth 60` and see if that's enough attenuation for you're liking.

**Comment by Zombeaver** [comment]
That _isn't_ the issue. I understand that you can adjust it with mixer.

There's seriously no difference to my ear between 859 and 915 - FluidR3 is too loud and ToH is even louder in my test case _in both versions_. A mixer adjustment doesn't solve the underlying problem that you, yourself, already pointed out in an earlier comment and, as far as I can tell (hear) hasn't changed.

**Comment by Zombeaver** [comment]
And just for further testing, I went ahead and used mixer fsynth 60 and that's closer to what I would want, but again doesn't actually address the underlying issue. The two don't sound the same, even with the updated limiter. ToH is very clearly still louder in my testing.

**Comment by kcgen** [comment]
The `mixer device percent [device percent [..]]` should be used on a per-game basis to customize the loudness of some or all of DOSBox's audio devices. 

The soft limiter magnifies neither MIDI nor GUS; it's just a protective back-stop to prevent clipping without distortion.  It just happens that all prior MIDi patches had to preemptively attenuate MIDI to a fraction of its native amplitude (making it sound much quieter) because they didn't have a way to prevent clipping.

**Comment by kcgen** [comment]
@Zombeaver , @dreamer, I still think an optional SF2-specific scalar (with syntax proposed above) would be valuable, specifically to tackle the issue you mentioned @Zombeaver :

> ToH is very clearly still louder in my testing.

Some sound fonts are just too loud like ToH and Arachno, and other have almost perfect internal amplitudes like SGM.  I recall comming across one SF2 that was excessively quiet too.. so would have liked to apply a bit of a gain to that one. 

This SF2-specific-scalar will let users swap around fonts without having to entangle their per-game `mixer` values to compensate for SF2 differences.

**Comment by kcgen** [comment]
Regarding introducing yet another config option, I like the idea of a steath-scalar that piggybacks on the soundfont path. 

That way, the majority of users who just want to set a single soundfont once (and be done with it) won't even know about this scalar.  But for folks like us who really enjoy dialing in settings (to damn-near-perfection), can use this SF2 scalar (and share out findings).

**Comment by Zombeaver** [comment]
> The `mixer device percent [device percent [..]]` should be used on a per-game basis to customize the loudness of some or all of DOSBox's audio devices.
> 
> The soft limiter magnifies neither MIDI nor GUS; it's just a protective back-stop to prevent clipping without distortion. It just happens that all prior MIDi patches had to preemptively attenuate MIDI to a fraction of its native amplitude (making it sound much quieter) because they didn't have a way to prevent clipping.

Yes, I understand that. My point was that that, in and of itself, doesn't remove the need for adjustment between separate .sf2s.



> @Zombeaver , @dreamer, I still think an optional SF2-specific scalar (with syntax proposed above) would be valuable, specifically to tackle the issue you mentioned @Zombeaver :
> 
> > ToH is very clearly still louder in my testing.
> 
> Some sound fonts are just too loud like ToH and Arachno, and other have almost perfect internal amplitudes like SGM. I recall comming across one SF2 that was excessively quiet too.. so would have liked to apply a bit of a gain to that one.
> 
> This SF2-specific-scalar will let users swap around fonts without having to entangle their per-game `mixer` values to compensate for SF2 differences.

Yes, thank you. This is what I'm on about haha

**Comment by Zombeaver** [comment]
> Regarding introducing yet another config option, I like the idea of a steath-scalar that piggybacks on the soundfont path.
> 
> That way, the majority of users who just want to set a single soundfont once (and be done with it) won't even know about this scalar. But for folks like us who really enjoy dialing in settings (to damn-near-perfection), can use this SF2 scalar (and share out findings).

So long as it's listed/explained as a usable parameter in the fluidsyth's documentation section of the .conf this seems fine to me.

**Comment by kcgen** [comment]
Roger that, @Zombeaver. I'll start working on this next.

For the numerical format, should we stick to DOSBox's percent approach, ie: 60% or a decimal multiplier, ie: 0.6.

To reduce confusion and stay consistent with DOSBox, I suggest we stick to percentages.

**Comment by Zombeaver** [comment]
Hmm. I suppose I don't really have an opinion on that one way or the other. Any time I've seen it done in other forks it's been a decimal multiplier but I have nothing against a percentage so long as it spans the same effective range i.e. something like 1% to 500%

**Comment by kcgen** [comment]
@Zombeaver ,

64-bit Windows build is here to try out:
https://github.com/dosbox-staging/dosbox-staging/suites/1451524488/artifacts/24737143

Syntax in your conf file is exactly 
Just add a percent at the end of your SF2 filename:

`soundfont = /path/my.sf2 50`

dosbox-staging will inform you that it's been applied with this output:

`MIDI: FluidSynth loaded /path/my.sf2 with levels attenuated by 50%.`

**Comment by Zombeaver** [comment]
Did a bit of testing and seems to be working great! Thank you @kcgen ! :heart:
