### ISSUE TITLE
Game Wizard 32 = File Access Denied

### ISSUE THREAD

**Issue by roioros** [dosbox-staging/dosbox-staging#683]
**Describe the bug**
When I want to start looking for cheats, I can't as it gives me this error: File Access Denied.

**To Reproduce**
Run the program and go to the first option which is "Memory Address Search" (it is the option to start a search).

**Expected behaviour**
It doesn't have to give that error and a screen with options should appear to start looking for cheats.

**Version of dosbox-staging:**
With the latest git: v0.76.0-alpha-870-ga3848.
It also did not work with gits prior to the last one, but it does work with version 0.75.1

**Additional context**

![vc_000](https://user-images.githubusercontent.com/26861500/97044778-fa895700-154a-11eb-8ec9-5d677a8107f9.png)

**Comment by dreamer** [comment]
@roioros Thank you for the bug report! I confirm the issue. Ran git-bisect, the regression was caused by 19806508c1597d485e6b9832082a1f4af5bb4102 - it seems like conflict resolution between SVN and earlier fix in master branch caused a regression.

**Comment by roioros** [comment]
You're welcome!

Great that you could find the problem since Game Wizard is a program that I use a lot.

Thanks!!

**Comment by kcgen** [comment]
> @roioros Thank you for the bug report! I confirm the issue. Ran git-bisect, the regression was caused by [1980650](https://github.com/dosbox-staging/dosbox-staging/commit/19806508c1597d485e6b9832082a1f4af5bb4102) - it seems like conflict resolution between SVN and earlier fix in master branch caused a regression.

👍 @dreamer!

@roioros, are you able to see if DOSBox SVN is also affected? I would imagine upstream would also be interested, if there's a file IO related regression lurking in here. 

If you're on Windows, you can get the latest build of SVN (non-ECE build) from https://dosboxece.yesterplay.net/

**Comment by dreamer** [comment]
Upstream is not affected; regression was introduced when I resolved conflict between upstream and our implementation.

**Comment by roioros** [comment]
Hi!, sorry for the late reply, exactly, the problem does not occur on the SVN and neither happen with the latest version of DOSBox Staging (0.75.2), only with the latest GIT versions.

**Comment by dreamer** [comment]
Just a note to myself as preparation for fixing the regression I introduced (or maybe if someone else wants to get a stab at re-doing the merge).

The conflict is between #538 on our side and SVN  0f4a84f47d39e18a10415069e3aaa140d2ff08f2, 326c371a3af5e1d6c0aa6337658ee91254810abe. Both changes on our side and on SVN side are fine, but conflict was fairly non-trivial :( 

BTW, this bug is on a short list of blockers for 0.76.0.

To repeat the merge and see the exact conflict (on a new temporary branch):

    git checkout -b branch-name 1980650~1
    git merge 326c371
