### ISSUE TITLE
Joystick not working with DOS Box Staging version 0.75.1

### ISSUE THREAD

**Issue by WhoDaresMods** [dosbox-staging/dosbox-staging#684]
I am trying to use my joystick to play Falcon 3.0 with DOS Box. My stick is a Saitek ST290 Pro, and when I open DOS Box separete from Falcon it does detect my stick in the status window. However, once I load the game (from the GOG launcher, not DOS Box) my stick doesn't work at all. The buttons still do, and I can still map the joystick axis to the keyboard, but the game just won't detect the analog axis from the stick.

 The game came with an older version of DOS Box. I attempted to fix it (with guidance) by installing version 0.75.1. I was having these problems previously as well. If it is relevant, I must mention that after updating to 0.75.1, my keyboard inputs weren't being registered as well. I fixed this by placing a # in front of the "mapperfile" line, like this:

 _#mapperfile=mapper-0.74-2.map_

I am running Windows 10. I have not modified anything else in the CONF files except the CPU cycles, which I set to 10000 in order to run Falcon at an acceptable framerate.

Please note that this is my first time posting here, and also that I am not literate in programming at all, so I apologize for any mistakes in advance. Any help is appreciated.

**Comment by nemo93** [comment]
@WhoDaresMods hi! Did you get this one sorted? Let's close this issue if you did. Otherwise please provide more information about your problem (full dosbox.conf file + any other conf you may have, version of Staging, if you face similar issue with another game, etc). Thanks.

**Comment by WhoDaresMods** [comment]
Yeah, I got it fixed. Turns out the version of DOS Box that came with my
game wasn't the latest one.

Sorry for not updating the thread.
