### ISSUE TITLE
Reported Pentium CPU stepping

### ISSUE THREAD

**Issue by rderooy** [dosbox-staging/dosbox-staging#690]
**Describe the bug**
You may be interested in this PR: https://github.com/joncampbell123/dosbox-x/pull/1967

Basically the currently reported P5 CPU stepping B1 is the revision with the FDIV bug. So unless you want to emulate this "feature", you should report the fixed D1 stepping.

**Comment by dreamer** [comment]
We definitely don't want to emulate this "feature", thank you @rderooy :)

I don't have time to check at the moment, but Wikipedia article lists simple way to test for presence of FDIV bug: https://en.wikipedia.org/wiki/Pentium_FDIV_bug#Detection_methods

But the result might differ depending on host CPU… (we had a bug with floating point operations generating different results on x86_64 and ARM, triggering a bug in some Windows software).

**Comment by rderooy** [comment]
There is a similar issue with the CPU-ID when emulating a 486. It always reports to be a 486DX, regardless if the FPU emulation is enabled or not.

This PR https://github.com/joncampbell123/dosbox-x/pull/1970 changes it such that if FPU emulation is disabled, it reports a CPU-ID of a 486SX instead.

**Comment by Wengier** [comment]
The said PRs there were both merged, but I believe Staging prefers less config options, so there is probably no need to add new config options for these.

**Comment by rderooy** [comment]
Neither of these PRs adds config options. And I think (did not check) that -staging allows the fpu to be disabled just like vanilla dosbox.

**Comment by Wengier** [comment]
@rderooy I know that for sure. I meant that the comments left there probably will not apply to Staging because of the differences.
