### ISSUE TITLE
Keymapper temporarily breaks input after first save

### ISSUE THREAD

**Issue by dreamer** [dosbox-staging/dosbox-staging#696]
**To Reproduce**

- Start without mapper file present.
- Ctrl+F1
- Select any event, e.g. "Dec Frameskip"
- Remove binding
- Click "Save"
- Click "Exit"
- Start typing
- Garbage is written to the terminal instead of proper input.

**Expected behaviour**

DOS shell should work as normal.

I am able to reproduce this bug only with exact steps as described above; any change and input is still ok. User can invoke keymapper again (Ctrl+F1), and immediately click Exit - this fixes input. After restarting emulator, the problem disappears as well.

**Version of dosbox-staging:**
- v0.76.0-alpha-910-g37f01e17
- 0.75.2
- DOSBox 0.74-3 (!) *I guess nobody noticed this for quite some time…*

**Comment by kcgen** [comment]
Did PR 697 fix this?

**Comment by dreamer** [comment]
No, the bug is still present.

**Comment by Burrito78** [comment]
Keymapper will be redesigned, see #1953.
