### ISSUE TITLE
FWD: Project naming (feedback)

### ISSUE THREAD

**Issue by okias** [dosbox-staging/dosbox-staging#703]
> I think this name is also misleading.  "DOSBox Staging" sounds like a
development branch of the original DOSBox project, not an independent
project.  Are the upstream developers set on using this name or do you
think they could be persuaded to use something more distinctive?

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=973822#20

Personally I'm OK with DOSBox Staging name, but it's possible it may be not accepted well everywhere.
Since I suppose it'll be symlinked to dosbox anyway, so it can be almost anything (and package description has to have keyword dosbox in it, so also searchable)

My list of ideas is for now:
1.`DOSBoxing` - just dropping the `Stag`, on other hand `Boxing` isn't so peaceful sport, not sure if good corelation
2.`DOSunBOX` - little bit weird (DO Sun BOX), but it kinda `unbox -> run DOS apps`
3.`DOSEXE` / `DOSBox EXE` - well, `.EXE` (I know there was also `.COM` :laughing:)

Criteria I'm trying to use to search for good name:
- easy to remember
- minimal occurrences on DuckDuckGo and G**gle Search

If DOSBox Staging is final, feel free to close this issue and share that on debian ML (or I will), if you're open to discussion, probably keep this open until some catchy name will be accepted.

**Comment by kcgen** [comment]
If we could draw a Venn diagram, Staging would be a superset of SVN exactly like ECE is a superset of SVN.
 - One is not better than the other nor does one supersedes the other: I see the relationship similar to the Linux kernel versus distributions.  Staging and ECE add extras deemed valuable _for a subset of users._
 - Eventually Staging will incorporate all of ECE's patches, at which point we will be a functional superset of ECE with the inclusion of our development and CI process.
 - Staging and ECE both pull from SVN; and both projects are thankful for SVN for continued core-emulation improvements.

**Comment by Kekun** [comment]
Just some random ideas:
- DOSTesseract
- DOSHypercube
- VaporDOS
- DOSWave

**Comment by FeignInt** [comment]
Well, DOSunBOX brought forth a "sun microsystems" logo in my mind

If there is an appetite for a new name: 

- **DOSBox PlusPlus**  akin to C -> C++ a hattip to  C++3 vs C++14, and the ecosystem.. think DOSBox Plus ECE Plus DOSBox-X 

- **DOSBox PP**  shorter version of PlusPlus, the PP could also reference **P**lug and **P**lay, i.e. ease of use

**Comment by dreamer** [comment]
We discussed this once already in #217 

I am closing this issue before it will go out of hand via bikeshedding.

No, we are not open for changing the project name *at this time*. We might change the name at some point, but only once we'll have a *really* good reason to do so, and pros of the name change will overweight the cons of doing so.

Such reason might be e.g.:

- Merging development effort with other DOSBox fork
- Major code change, that would make us break backwards compatibility with vanilla DOSBox

Right now, we are fighting to convince users (*and developers*) to move on from using a myriad of tiny DOSBox forks ([link](https://github.com/dosbox-staging/dosbox-staging/wiki/DOSBox-forks) - very incomplete, there are ~50 other dead forks I know of) or maintain their own patchsets based on 10-year old 0.74. We have already certain (hard thought for) recognition and community formed up - changing name *at this point* will only cause confusion and hurt the project's prospects for future.

Suggesting a new name is easy; effective rebranding is hard.
