### ISSUE TITLE
[IMGMOUNT] typo

### ISSUE THREAD

**Issue by nemo93** [dosbox-staging/dosbox-staging#714]
**Describe the bug**
It's not a bug just a typo in `IMGMOUNT` output.

**To Reproduce**
In DOSBox just type in something similar to the following:
```
C:\>IMGMOUNT D MY.ISO -T TEST
```

**Expected behaviour**
To be consistent with that command [help page](https://github.com/dosbox-staging/dosbox-staging/wiki/Imgmount) I'd expect `cdrom` to be listed as supported format instead of `iso`.

**Version of dosbox-staging:**
Current master.

**Additional context**
https://github.com/dosbox-staging/dosbox-staging/pull/577

**Comment by kcgen** [comment]
![2020-11-12_08-35](https://user-images.githubusercontent.com/1557255/98968055-1042ca00-24c2-11eb-8b07-8a402d467239.png)

Thanks @nemo93 , we'll add `cdrom` to the list!
