### ISSUE TITLE
Higher Res Splash Screen

### ISSUE THREAD

**Issue by OpenRift412** [dosbox-staging/dosbox-staging#716]
Now that I'm back home on my desktop, Staging is back to working like a dream ;)

One thing I'd like to suggest though, could we get a higher resolution (like 1080p at least?) DOSBox Staging splash screen for when we start staging in fullscreen? Just a little quality of life thing I guess.

**Comment by kcgen** [comment]
Nice suggestion @OpenRift412 , and glad you've got a nice working setup again.

@dreamer, is it possible to render (from SVG) on the client side, and cache the image based on rendering resolution? (if the DOSBox resolution is set to 1080p, it would look for `logo-1920x1080.png`, and if not found then render and save it).

I suppose we'd have to package the SVG converter to that.. might be a bit cumbersome.

**Comment by dreamer** [comment]
Right now we use pre-rendered bitmap using size 640x480 - to match the default window size in windowed mode, so there's no weird window resizing glitch. 

> @dreamer, is it possible to render (from SVG) on the client side, and cache the image based on rendering resolution?

"it's not as easy as it sounds"

As you mentioned, we don't have SVG renderer integrated. It would be nice to have one, but that's a whole new level of complication. I have not tested nanosvg so I don't know if it's able to handle our logo (it uses Inkscape's 3D-shape, so perhaps we would need to re-do the vector file), but the author mentions in the README page that this renderer is slow.

Caching file on user's machine is not a good idea (what about situation when we'll change the splash or add dynamically rendered text to it?) - it would be much easier to simply render it to texture when needed and show it directly; either way - SVG renderer speed is important. If we'll have SVG renderer, then we will want to use it for more than a splash screen.

Now, the funny part:
- right now our SVG logo is 17.5KB - splash screen after rendering to PNG is 20KB, and after using Gimp to generate run-length encoded bitmap it's 39.1KB.

I'll see what will the size be after making the resolution higher. I can also write a tiny bit of code to avoid excessive black border

**Comment by dreamer** [comment]
After resizing to 1440x1080, the image is 51.2KB as PNG, 114.7KB as RLE bitmap - so not that bad! Our binary is 3.9 MB on Linux - having higher bitmap won't make any difference.

Long term, we do want to have SVG renderer of course, but it's a lot of work.

**Comment by dreamer** [comment]
Ah, as far as SVG renderers, I strongly prefer [librsvg](https://gitlab.gnome.org/GNOME/librsvg) over any alternative - I tested few projects for rendering our icons and it worked the best (it's also written in Rust and provides both Rust and C interface). That being said, decision about what library to use depends on what we're going to decide to use for GUI to replace keymapper.

**Comment by Grounded0** [comment]
Closing as uncompleted as splash screen has been eliminated for now.
