### ISSUE TITLE
Snap package: Snap overrides home dir leaving users confused

### ISSUE THREAD

**Issue by dreamer** [dosbox-staging/dosbox-staging#720]
https://www.reddit.com/r/dosgaming/comments/jtojhi/help_getting_wizardry_6_to_run_on_dis_oxstaging/

When user has Snap package installed and tries to mount a file or image file, e.g.:

`mount C ~/Games/`

The snap package will instead override HOME dir to something like `/home/<username/snap/dosbox-staging/<nr>/`. Leaving users confused...

This means users now need to manually expand ~ whenever they want to mount/imgmount something, which is extremely annoying :(

**Comment by kcgen** [comment]
We might be able to check to see if we're running inside a snap sandbox, and if so we could expand ~ as $HOME but chop off the `/snap/.*` pattern.

Then again, the snap package permissions might mean it only had read and write access inside its own sandbox in `/home/<username/snap/dosbox-staging/`, and attempts to depart it will be denied.

**Comment by dreamer** [comment]
Let's not do workarounds for open source software... perhaps there is some kind of option in Snap package to disable this stupid behaviour - I have no idea about Snap packages, hence why I added tag "help wanted" :)

I *suspect* the Snap package for dosbox-staging was based on DOSBox package, which did not respect XDG_CONFIG_DIR, hence why HOME was overriden (to avoid creation of `~/.dosbox` dir).

**Comment by kcgen** [comment]
We absolutely want all repos providing users with the best experience possible - however the project does not manage repo builds (for any repository, Snap included). Therefore we ask that these issues be brought up with the folks maintaining the problematic repo package. (Closing).

**Comment by popey** [comment]
Apologies for this being broken in the snap. I've made a fix  for `$HOME` mapping which will be in the next build:

![Screenshot_20220130_211324](https://user-images.githubusercontent.com/1841272/151718181-665ffe7e-78d4-462e-ab01-8e123145018f.png)
