### ISSUE TITLE
How to enable sound?

### ISSUE THREAD

**Issue by DOOMMARINE117** [dosbox-staging/dosbox-staging#728]
i had to restore my computer cause of stupid elder scrolls 3 morrowind keeps givign me issues when installing it. 

but, back to topic.

is nosound suppose to be false? 

im assuming i can change that to true? 

i have overlay on as output. 

so would nosound be changed to true?

**Comment by kcgen** [comment]
> is nosound suppose to be false?

Right. If you want sound, then leave `nosound = false` as-is. It's unfortunately a double-negative.

> i have overlay on as output.

`output = overlay` is not a setting used by DOSBox Staging. 

You can try:
- `output = opengl` , or
- `output = openglnb`

To see if you prefer either of those.

**Comment by DOOMMARINE117** [comment]
> 
> 
> > is nosound suppose to be false?
> 
> Right. If you want sound, then leave `nosound = false` as-is. It's unfortunately a double-negative.
> 
> > i have overlay on as output.
> 
> `output = overlay` is not a setting used by DOSBox Staging.
> 
> You can try:
> 
>     * `output = opengl` , or
> 
>     * `output = openglnb`
> 
> 
> To see if you prefer either of those.

ok so i change output to opengl.

still have no sound?

**Comment by kcgen** [comment]
> still have no sound?

If you're starting with a new system, then you might have to configure your DOS game again as well.

Launch your game's `setup.exe`, `setsound.exe`, or `install.exe` inside dosbox.

Configure the game with default Sound Blaster 16 or SB Pro setting, save the settings.

Relaunch your game - hopefully you now have sound.

**Comment by DOOMMARINE117** [comment]
> 
> 
> > still have no sound?
> 
> If you're starting with a new system, then you might have to configure your DOS game again as well.
> 
> Launch your game's `setup.exe`, `setsound.exe`, or `install.exe` inside dosbox.
> 
> Configure the game with default Sound Blaster 16 or SB Pro setting, save the settings.
> 
> Relaunch your game - hopefully you now have sound.

i was going to mention im using dosbox x. but imagine there are all the same forks. 

i forgot to check the project name before posting, lol. 

so far it has already enabled sb16 an etc on. 

what about enable speaker?

**Comment by dreamer** [comment]
> i was going to mention im using dosbox x. but imagine there are all the same forks

Please report an issue in DOSBox-X project then. Thanks.
