### ISSUE TITLE
Improve readability of help messages for built-in commands and programs

### ISSUE THREAD

**Issue by dreamer** [dosbox-staging/dosbox-staging#729]
Help messages for various built-in commands are annoying mish-mash of styles and formatting. Plenty of documentation is simply missing (and users usually don't know where to find our manual file).

In #608 and #577 we improved the help messages for `mount` and `imgmount`. In the process, we established a nice, readable style for our help commands - now it's time to expand help for all remaining commands to use the same style, so users could rely on these help messages.

This issue exists to track progress in improving all commands across the board:

Anyone: feel free to start working on any of these - leave a comment or send a PR :)
Tip: places in code are: `DOS_SetupPrograms()` in `src/dos/dos_programs.cpp`, `SHELL_Init()` in `src/shell/shell.cpp`.

| Command | Help switches | Issue | Status | From MS-DOS | Comments
|-  |- |- |- |- |-
| `attrib` | `/?` | | TODO | Yes |   
| `call` | `/?` | #1365  | **Done** | Yes |     
| `cd`, `chdir` | `/?` | #1503 | **Done** | Yes |    
| `choice` | `/?` | #1392 | **Done** | Yes |   
| `cls` | `/?` | #1368  | **Done** | Yes |      
| `copy` | `/?` | #1356 | **Done** | Yes |     
| `date` | `/?` | #1377 | **Done** | Yes |     
| `del`, `delete`, `erase` | `/?` | #1143  | **Done** | Yes |   
| `dir` | `/?` | #1383 | **Done** | Yes |      
| `echo` | `/?` | #1356 | **Done** | Yes |     
| `exit` | `/?` | #1365  | **Done** | Yes |     
| `goto` | `/?` | #1366  | **Done** | Yes |     
| `help` | `/?` | #1359 | **Done** | No |     
| `if` | `/?` | #1368  | **Done** | Yes |       
| `lh`, `loadhigh` | `/?` | #1377 | **Done** | Yes | 
| `md`, `mkdir` | `/?` | #1359 | **Done** | Yes |    
| `path` | `/?` | #1353 | **Done** | Yes |     
| `pause` | `/?` | #1375 | **Done** | Yes |    
| `rd`, `rmdir` | `/?` | #1356 | **Done** | Yes |    
| `rem` | `/?` | #1370 | **Done** | Yes |      
| `ren`, `rename` | `/?` | #1358 | **Done** | Yes |   
| `set` | `/?` | #1353 | **Done** | Yes |      
| `shift` | `/?` | #1368  | **Done** | Yes |    
| `subst` | `/?` | #1358 | **Done** | Yes |    
| `time` | `/?` | #1377 | **Done** | Yes |     
| `type` | `/?` | #1358 | **Done** | Yes |     
| `ver` | `/?` | #872 | **Done** | Yes |      
| `autotype` | *none* | #1383 | **Done** | No |
| `boot` | *missing* | #1366  | **Done** | No |
| `biostest` | *missing* | | TBD | No | *This command is available only in debugger builds.*
| `command.com` | *missing* | #1375 | **Done** | Yes | 
| `config` | *none* | | TBD | No | Contains an excessive number of options. Unsure how to handle.
| `imgmount` | `/?`, `--help`, `-h` | #577 | **Done** | No | 
| `intro` | *missing* | #1392 | **Done** | No |
| `keyb` | `/?` (broken) | #1383 | **Done** | No |
| `loadfix` | *missing* | #1370 | **Done** | No |
| `loadrom` | *missing* | #1375 | **Done** | No |
| `ls` | `/?` | #1365  | **Done** | No |
| `mem` | *missing* | #1366  | **Done** | No |
| `mixer` | *missing* | #1370 | **Done** | No |
| `mount` | `/?`, `--help`, `-h` | #608 | **Done** | No |
| `rescan` | *missing* | #1359 | **Done** | No |
| `serial` | `/?` | #1503 | **Done** | No |  

Rules: 

- Follow exactly the same style as for  `mount`, `imgmount`
- Use colours to correlate important parameters, exactly the same style as in `mount` and `imgmount`
- Every command should print message when passed arguments: `/?` (DOS style), `-help`, `--help` (GNU style). Some commands might print help if no parameters are passed (if there is nothing better to do).
- This is short help, needs to fit into one standard DOS screen - max 80 columns, 23 lines (so user can see the whole help while typing the command)
- It does *not* need to cover all possible parameters and usages, only the most common ones.

**Comment by Draky50110** [comment]
command.com is documented.

Here is french version : 
![image](https://user-images.githubusercontent.com/1558487/102900178-37e76380-446c-11eb-97b4-4e5cfdb54d41.png)

It launches another shell... in the shell :)

**Comment by dreamer** [comment]
I updated the table in the first commit: `ver /?` was converted in #872, I made a separate column listing help switches per command.

**Comment by kcgen** [comment]
The table has gone from a mere 6% complete a year ago, to now being over 93% complete, all  thanks to @Wengier's authoring 38 help screens! 

Amazing contributions, @Wengier :rocket:

**Comment by kcgen** [comment]
Closing. All non-debug-related programs have unified help screens.
