### ISSUE TITLE
DOSBox' default .conf file needs tweaking

### ISSUE THREAD

**Issue by dreamer** [dosbox-staging/dosbox-staging#73]
ATM, DOSBox appens version name to the configuration file, e.g. `~/.dosbox/dosbox-0.74.conf`. This is not a common practice (configuration files are rarely versioned this way) and it's rather user-unfriendly, however hard to spot when running SVN version-less build for long time.

To mitigate this a little bit, dosbox-staging uses fixed configuration file (atm it's `~/.dosbox/dosbox-staging-git.conf` - for debug and development releases - introduced in #72). This makes the default config more usable, but it triggers a different issue: now it will be practically impossible to upgrade users to changed default configuration.

There are several ways to approach this, the easiest solution would be to *not* dump whole default config in a new .conf file and let user decide what should go there. Perhaps also store defaults, with better documentation in the package or in `/etc/`.

**Comment by krcroft** [comment]
Thanks for making this an issue @dreamer ; there are some nice options for improvement here!

**Comment by es20490446e** [comment]
Likely DosBox should just use the same file location for all versions, have a version number in them, and translate any change to new versions among consecutive releases.

**Comment by dreamer** [comment]
Right now, upstream project just creates `~/dosbox/dosbox-<version>.conf` from scratch with every new major/minor/patch release - this is really annoying to deal with, except upstream basically does not do stable releases any more (3 public releases in last 10 years?). I think we will stick to only 2 files:

- `dosbox-staging-git.conf` - for our development releases and ongoing work
- `dosbox-staging.conf` - for all stable releases

But as time will go by, we will need to move things OUT of default settings file TO proper documentation - my model for doing so is Git, with plenty of settings documented in [git-config](https://git-scm.com/docs/git-config), but no settings injected to user configuration file by default.

So maybe…

How about when creating a new (non-development) configuration file, we created an empty file with a single comment only:

```
# Run "man dosbox-staging-conf" to learn about all configuration options
# or visit <our-future-URL-describing-configuration>
```

**Comment by es20490446e** [comment]
I think the transition should be automatic, and handled in one single configuration file.

**Comment by dreamer** [comment]
I think we can safely close this issue now :)
