### ISSUE TITLE
GUS regression in Epic Pinball

### ISSUE THREAD

**Issue by dreamer** [dosbox-staging/dosbox-staging#730]
**Describe the bug**
Music in Epic Pinball breaks after unpausing or using the keymapper.

**To Reproduce**
1. Using following .conf files, run setup and select GUS music:
[dosbox_epin.conf.txt](https://github.com/dosbox-staging/dosbox-staging/files/5580698/dosbox_epin.conf.txt)
[dosbox_epin_single.conf.txt](https://github.com/dosbox-staging/dosbox-staging/files/5580699/dosbox_epin_single.conf.txt)
(these are default .conf files distributed by GOG, but with an adjustment to enable GUS)
2. Start Epic Pinball (you can even stay in the menu, entering table is not necessary for bug reproduction)
3. Press Ctrl+F1 to open keymapper, Press Exit button to go back to game

Alternative step (3): Press Alt+Pause to pause the emulator, press it again to unpause.

**Expected behaviour**
- The music stops on pausing emulator and restarts cleanly after unpausing.
- The music stops on entering keymapper and restarts cleanly after leaving keymapper.

**Environment (please complete the following information):**
- OS and version: Fedora 33

**Version of dosbox-staging:**

Bisect results:

Regression was introduced either in  9692835d96bd9f118ec06773093b57af52d4104e (or in af8a9c229239cde5cac56b32ce8cf6dcf52b9730, but I can't tell for sure because it does not compile).

When testing earlier commits, there is bad sound artefact (extremely loud screetch) when leaving the keymapper (but music goes back to normal in a fraction of a second). That artefact is *not* present in 0926b0609cd7ca71accde15c046e8e2f873ff459 (v0.76.0-alpha), so it was introduced somewhere between 0926b0609cd7ca71accde15c046e8e2f873ff459 and 21b7e42bbf48d29c429a6208b1b0a08bf3025d62 (last good commit before this regression).

*My working hypothesis is: sometime after 0.76.0-alpha we introduced a tiny regression that leaves broken samples somewhere in GUS implementation. Then in  9692835 these broken samples break some expectations of soft limiter and leave it in an inconsistent state. @kcgen should I run bisect to detect which commit introduced this sound artefact?*

**Comment by kcgen** [comment]
Thanks for this detailed write up @dreamer. I wasn't unable to reproduce it until I dropped your GOG `.conf` files in place. 

GOG's conf file wants an 80ms prebuffer (which is quite a bit; almost 4 video-frames). When unpausing, the requested audio frames in the callback briefly spikes up beyond what we will generate.

A simple work around was to reduce the prebuffer to our default value (or delete the setting). But I added a loop to handle these overages.
