### ISSUE TITLE
Odd Deep Path Error

### ISSUE THREAD

**Issue by sduensin** [dosbox-staging/dosbox-staging#736]
**Describe the bug**
Unable to access files in deeply nested paths.

**To Reproduce**
Unsure.  See screenshot.

**Expected behaviour**
To be able to access the files.

**Environment (please complete the following information):**
Linux Mint 19

**Version of dosbox-staging:**
0.75.2, Reported DOS 5.00

**Additional context**
![image](https://user-images.githubusercontent.com/98645/100488302-054b8480-30d3-11eb-974c-832654eed9f9.png)

DOSBox-X is able to handle this, so I don't believe it to be a problem with the host filesystem.

**Comment by kcgen** [comment]
If you launch dosbox in the CODE directory, and mount CLIENT as C:, does it then let you type the file?

If not, try progressively stepping in one more directory and mounting that as C: (and so on), to check if it's a path-length limit being hit. 

It looks like the length should be fine (80x25), so you're maybe around 76 or in length. But will be interesting none-the-less!

**Comment by sduensin** [comment]
Launching from CODE and mounting CODE as C is enough to make it work.

**Comment by grapeli** [comment]
You are not within the limit. The total length of the path and file name is 80 characters. Shorten it by excess `code\client`.

**Comment by MasterO2** [comment]
Can the total length of the path and file name be extended for Dosbox Staging?

**Comment by sduensin** [comment]
All this time using DOS (I go back to 2.11) and I never knew the 80 character limit.

**Comment by kcgen** [comment]
Indeed; it's something that DOS programs and games, when left to their own installed trees, never hit. 

So these boundaries were typically hit by users trying to make too many levels in a tree.. but fortunately they hit the limit in realtime and were blocked inside DOS.  They didn't have a more powerful OS outside DOS that could handle deeper trees (well.. atleast until OS/2 and VFAT came along :-))

> Can the total length of the path and file name be extended for Dosbox Staging?

The length could be extended, but it's then arbitrary where we should 'stop'; maybe we'd ultimately want to handle the longest paths possible on all supported filesystems (to rid of us this problem for good).

But those giant string buffers would bloat DOSBox to handle a vanishingly rare scenario.  Worse, it would conflict with DOS programs' own length checks and their own expectatations of error code responses from the OS. So it's an allowance that provides little value with greater risk.

Conveniently the 80 char limit is also right at the screens edge.. so it's both a logical but visual/physical "end of the line".  If you path wraps..then you're literally out of bounds :-)

**Comment by sduensin** [comment]
I've adjusted my paths to stay within 80 characters.  Thanks for educating me about the original DOS limit!  I totally agree that DOSBox Staging should do what DOS would have done.
