### ISSUE TITLE
Mess with titles, define either dosbox or dosbox-staging.

### ISSUE THREAD

**Issue by IlyaIndigo** [dosbox-staging/dosbox-staging#737]
The project is a mess with names. One is called dosbox (executable file, man, "~ /.config/dosbox" config), the other is called dosbox-staging (icon, desktop-file, splash screen at startup).
It is not right!
If your project is a dosbox fork, then it should be named dosbox-staging by default for everything.
If you want your fork to replace the original dosbox and be like its continuation, then everything should be called dosbox.
But you can't be in the middle, as is done by default now!

Even if I specify "./configure --program-suffix=-staging", I still have to change via sed Exec to dosbox-staging in the desktop file.
Also, I didn’t find an option to change the config file "~/.config/dosbox" to "~/.config/dosbox-staging".

**Comment by dreamer** [comment]
DOSBox Staging is a drop-in replacement for DOSBox, period. `dosbox` is our program name, "DOSBox Staging" is our project name.

We use name `dosbox` for our binary to preserve backwards-compatibility - if we decided not to do that, it would break countless user scripts, hashbangs, GUI frontends, game store frontends, made it harder for users to replace outdated dosbox binaries bundled with DOS games, and harder for us to perform testing and bisecting regressions. In all places where we can safely avoid conflicts without introducing regressions (e.g. icon name or the default .conf name) - we do so, but we won't send patches to the whole ecosystem of applications relying on dosbox binary name.

For those reasons we ***very strongly recommend*** packagers to keep the binary name simply as `dosbox` - consequently keeping this name for man page, default XDG config dir, and (future) bash completion script. Some packagers decide to ignore our advice (notably Snap packagers) - *it only makes user's life harder for no good reason*.

BTW, using `~/.config/dosbox/` does not risk any conflict with DOSBox SVN (for multiple reasons - e.g. upstream declared they will not follow XDG spec, but also they append their version name and generate new .conf file for every new minor release).

If you care about supporting `--program-suffix`, then send us PR to fix the areas that are problematic to you - but if you would like to be thorough, then here's a non-exhaustive list of places that would need adjustment:

- desktop entry -*right now it is a simple text file, not generated template and we like it this way*
- metainfo - *right now it is a simple text file, not generated template and we like it this way*
- content of man page - *right now it is a simple text file, not generated template and we like it this way*
- content of manual file (aka README) - *right now it is a simple text file, not generated template and we like it this way*
- our help strings
- likely both buildsystems, meta files for macOS and Windows, etc, etc

**Comment by dreamer** [comment]
> If you want your fork to replace the original dosbox and be like its continuation, then everything should be called dosbox.

We would very much prefer to contribute to the official DOSBox project, but we tried and it was impossible. As of 2020 it's unlikely that DOSBox Team will agree to merging the projects, but hopefully it will happen at one point (the last major DOSBox release was more than 10 years ago at this point…).
