### ISSUE TITLE
DOSBox Staging fails to enter protected mode with a crash after build v0.76.0-alpha-851-g51489 (19 Oct 2020) on macOS

### ISSUE THREAD

**Issue by Grounded0** [dosbox-staging/dosbox-staging#742]
**Describe the bug**
DOSBox Staging fails to enter protected mode with a crash on builds post v0.76.0-alpha-851-g5148919 (19 October 2020) including 0.76.0 release at least on macOS 10.15.7 (19H15) on x86-64.

Here's a screenshot of build v0.76.0-alpha-851-g51489 running protected mode program nicely:
https://anttipeltola.eu/pics/dn2

Here's a screenshot of 0.76.0 release crashing with Bus Error: 10 while executing a protected mode program:
https://anttipeltola.eu/pics/dosbox_dpmi

**To Reproduce**
Reproducible at least on macOS 10.15.7 (19H15) on x86-64 at this point. Crashes on default config file after mounting C drive and executing any protected mode program. Broke down post v0.76.0-alpha-851-g51489 (19 October 2020) build. Been too depressed to isolate the problem earlier.

**Expected behaviour**
Expected behaviour is for protected mode programs such as DOS Navigator 2 to execute normally without crashing.

**Environment (please complete the following information):**
macOS 10.15.7 (19H15) on x86-64. 15" MacBook Pro 2017 model with Radeon Pro 560 GPU.

**Version of dosbox-staging:**
Anything post v0.76.0-alpha-851-g51489 (19 October 2020) 0.76 alpha build or maybe maximum few days later including 0.76.0 release build. Haven't able yet to track the exact breakdown build.

**Configuration parameters:**
Default config file, mount drive C and execute any protected mode program on macOS.

**Additional context**
Bus Error: 10 is the only error output i have gathered at the moment.

**Comment by dreamer** [comment]
This sure sounds like W^X issue, but it's rather impossible, because it wouldn't have worked even in older builds…

I'll try to reproduce the problem, but in the meantime @Grounded0 do you know how to create a build and run git-bisect?

**Comment by Grounded0** [comment]
Not exactly and feeling kind of bummed out at the moment. Not the most cheerful of times. I gladly test anything thrown at me but it should be something easily executable at this point.

**Comment by dreamer** [comment]
Understood :) I will try to reproduce it on my side first, and if it won't work I'll do some GitHub API magic to extract links to older builds. Thank you!

**Comment by Grounded0** [comment]
I would like to add that DOS Navigator 2 has some priority in DOS World as it is part of FreeDOS distribution.

**Comment by Diduz** [comment]
I've just run 0.76 release version on Windows 64bit, I got the same problem: Jazz Jackrabbit and Doom crash the emulator (I remember they're protected mode games, if I'm not mistaken).

**Comment by Diduz** [comment]
Sorry, I forgot to even say hello. So rude. First time poster. I really like your version of DosBox! Keep up the good work, Dom

**Comment by kcgen** [comment]
> I've just run 0.76 release version on Windows 64bit, I got the same problem: Jazz Jackrabbit and Doom crash the emulator (I remember they're protected mode games, if I'm not mistaken).

@Diduz , can you open a command prompt and run DOSBox Staging from there and report any console/text output (or take a screenshot) of any error messages?

**Comment by kcgen** [comment]
@Grounded0 , would you be able to try this build? It fully-links FluidSynth statically. 

https://github.com/dosbox-staging/dosbox-staging/suites/1607000380/artifacts/29372821

**Comment by Grounded0** [comment]
@kcgen Test build runs protected mode programs beautifully.

**Comment by Diduz** [comment]
> > I've just run 0.76 release version on Windows 64bit, I got the same problem: Jazz Jackrabbit and Doom crash the emulator (I remember they're protected mode games, if I'm not mistaken).
> 
> @Diduz , can you open a command prompt and run DOSBox Staging from there and report any console/text output (or take a screenshot) of any error messages?

That's what I get, no error messages, just a plain crash.
![076_prot_mode_bug](https://user-images.githubusercontent.com/39902698/101144203-3fa7ab00-3618-11eb-9af6-a24547c76942.jpg)

**Comment by dreamer** [comment]
@Diduz can you confirm that on Windows 32-bit build still works without crashing?

**Comment by Diduz** [comment]
> @Diduz can you confirm that on Windows 32-bit build still works without crashing?

Yes! Looks like the problem is in the 64bit version indeed! 32-bit build works fine.

**Comment by dreamer** [comment]
@Diduz Thank you! Windows problem seems to be different than this crash on macOS: #746

**Comment by kcgen** [comment]
Still early AM hours but woke up to check. There is a bit more pruning we can try regarding cutting down glib's optional (and unnecessary for us) via meson's option toggles. Will give this a go when I up in about 3 hrs. Back to 😴 for now.
