### ISSUE TITLE
DOSBox Staging crashes when attempting to run Pinball Illusions

### ISSUE THREAD

**Issue by warpdesign** [dosbox-staging/dosbox-staging#747]
**Describe the bug**
DOSBox Staging crashes when attempting to run Pinball Illusions.

**To Reproduce**
- download `ILLUSIONS.ZIP` from [archive.org](https://archive.org/details/PinballIllusions_1020) and uncompress it
- mount the directory by typing `mount c /path/to/illusions/`
- goto directory and start `ILLUSIONS.EXE`

**Expected behaviour**
The game should run.

**Environment (please complete the following information):**
- OS and version macOS bigSur 11.0.1 (x64)
- Relevant hardware info: MacBook (2017 / Core m3)

**Version of dosbox-staging:**
DOSBox Staging version 0.76.0 (same thing happens on latest development build)

**Configuration parameters:**
Not sure where to find it: didn't create one.

**Additional context**
[crashlog.txt](https://github.com/dosbox-staging/dosbox-staging/files/5642023/crashlog.txt)

**Comment by dreamer** [comment]
There's a test build in here: https://github.com/dosbox-staging/dosbox-staging/issues/742#issuecomment-738556706

Direct link to build: https://github.com/dosbox-staging/dosbox-staging/suites/1607000380/artifacts/29372821

Can you confirm if it works?

**Comment by dreamer** [comment]
The same fix is now also released in macOS build 0.76.0-3: https://dosbox-staging.github.io/downloads/macos/

**Comment by warpdesign** [comment]
I can confirm it works with build 0.76.0-3.

**Comment by dreamer** [comment]
@warpdesign Thank you :)
