### ISSUE TITLE
Fallback to default language instead of quitting when specified language file not present

### ISSUE THREAD

**Issue by Draky50110** [dosbox-staging/dosbox-staging#768]
Hello.

If a language file is specifed in .conf file but not present in config directory, DOSBox-staging is quitting saying it does not find the language file,
Same if a missing language file is specified with -lang parameter.

Would if be possible to not quit DOSBox and launch it with default language (builtin is english), like when launching without language file specified ?

It would behave like if a missing conf file is specified or missing (even default one) : launching with default and create one if missing.

**Comment by kcgen** [comment]
@Draky50110 , this is a valuable suggestion for cross-compatibility with other `dosbox` binaries that might support the language (and we certainly wouldn't want them to have to mass-edit their launch scripts just to pacify DOSBox Staging into launching).
