### ISSUE TITLE
Touchscreen inputs for windows 3.1

### ISSUE THREAD

**Issue by rmmh** [dosbox-staging/dosbox-staging#779]
**Is your feature request related to a problem? Please describe.**
I want to play old point-and-click adventure or educational games with a touchscreen. Currently, only relative movements on the screen and clicks are translated-- you can't tap directly on a target and get a click there. Supposedly, this is due to PS/2 mouse interface transmitting relative motions.

**Describe the solution you'd like**
I'd like touchscreen inputs to cause an absolute mouse movement and an appropriate click.

**Additional context**
More discussion here, including new mouse drivers supporting absoluter positioning: joncampbell123/dosbox-x#1003

**Comment by dreamer** [comment]
In this case I suspect DOSBox-X stuff is largely irrelevant to use - they have mixed SDL1/SDL2 support with some older version of SDL2 kept with the code (I think).

We use SDL2 only, and always in the newest available version - so I hope we only need to react to [SDL_TouchFingerEvent](https://wiki.libsdl.org/SDL_TouchFingerEvent) and interpret it as a mouse movement/click - and that should be all. SDL2 version of this event reports relative movement calculated by SDL2 for us.

The big hurdle is: none of developers from the core team has access to touchscreen display… so when we'll get around to implementing it - I hope we can rely on the community for testing :)

**Comment by FeralChild64** [comment]
@rmmh: Although there is still no real touchscreen support yet, you might try with the following setting (for Staging version 0.80.0) 

```ini
[mouse]
mouse_capture = seamless
```

and Windows 3.1x mouse driver by @javispedro:
- [download](https://git.javispedro.com/cgit/vbados.git/about/) from the author's web site
- step-by-step installation [guide](https://github.com/dosbox-staging/dosbox-staging/wiki/Windows-3.1x#improved-mouse-driver) at our Wiki

**Comment by Burrito78** [comment]
Thread author didn't reply. I think we've got this covered.
