### ISSUE TITLE
Consider using $XDG_DATA_HOME or  $HOME/.local/share for roms

### ISSUE THREAD

**Issue by bmunger** [dosbox-staging/dosbox-staging#780]
**Is your feature request related to a problem? Please describe.**
No functional problem.  This is in response to the commit e73b18b46566327ad52039ba7620b93db9b8cb45

**Describe the solution you'd like**
The XDG Base Directory Specification has a solution for placement of data files.  Using the configuration location is not the correct place for anything but configuration files.
Dosbox should fully support the various directory specifications that are useful and available.
https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html

**Describe alternatives you've considered**
Alternative is to ignore the specification and use anything else.

**Additional context**
N/A

**Comment by dreamer** [comment]
@bmunger Not sure if I understand correctly... The commit you linked *does* look in XDG_DATA_HOME for ROM files… 

https://github.com/dosbox-staging/dosbox-staging/commit/e73b18b46566327ad52039ba7620b93db9b8cb45#diff-d0ef2b8596284791dc2171f4bc3c3973ef48b02f24384364e3d8c550d5292409R107-R109

We do not respect XDG_DATA_DIRS though (and we probably should - we only lookup directories for as if XDG_DATA_DIRS was not defined - it affects both FluidSynth and mt32emu).

Is there something we should differently regarding XDG_DATA_HOME?

**Comment by kcgen** [comment]
Thanks, @bmunger.  

Looking at the code, it appears the specification for XDG_DATA_HOME is fully provided. That is, it looks for the ROMs in `$XDG_DATA_HOME/{mt32-roms, or mt32-rom-data}` if the variable exists and otherwise fallback to `~/.local/share/{mt32-roms, or mt32-rom-data}` with further fallback to `usr/local/share/mt32-rom-data/` and `/usr/share/mt32-rom-data/`.

In that last fallback to /usr/.., I see we should additionally check `$XDG_DATA_DIRS` and use those (however many are provided) before falling back to the /usr/.. areas.

So I can fix that; but I believe the code meets the title of the issue ticket already. 

However, I do see you've mentioned "_Using the configuration location is not the correct place for anything but configuration files."_, and so the concern is would prefer not to allow users to _also_ place the ROMs in 
`CROSS_GetPlatformConfigDir() + "mt32-roms/"`?

Personally, I like having all of my DOSBox records in one tidy area (including my soundfonts). So this extra allowance is provided for convenience to users with the same preference. 

Of course, users who prefer to strictly separate their dosbox conf files versus data files per the specification are perfectly capable of doing so.

**Comment by bmunger** [comment]
I should have checked closer before creating this issue.  However what I was getting at is that dosbox-staging should probably have it's own $XDG_DATA_HOME for any non-configuration file as well.  In this case, for the MT-32 roms, but also for anything else.  What I saw was the commit comment implying it looks only in the configuration directory for roms and the places where munt looks for roms.  Adding other lookup paths outside of XDG specification is probably fine too.  Thanks for having a look and explaining the methods further!

You all have been on the path to fixing long standing issues and doing things the right way for a while.  It's why when I see some area where there might be an improvement, I bring up an issue and I know it will be given intelligent thought.

**Comment by kcgen** [comment]
Right on @bmunger. Yes, we certainly want to get this right!

> dosbox-staging should probably have it's own $XDG_DATA_HOME for any non-configuration file as well. In this case, for the MT-32 roms, but also for anything else

You mentioned that again, so we might might not seeing something(?)

To help clarify, are you saying that we should have `$XDG_DATA_HOME/dosbox/...`, similar how we have `$XDG_CONFIG_HOME/dosbox/...`? So for example:

 - `$XDG_DATA_HOME/dosbox/mt32-roms`
 - `$XDG_DATA_HOME/dosbox/soundfonts`
 - `$XDG_DATA_HOME/dosbox/...`
 
These two specific use-cases (mt32-roms and soundfonts) involve agnostic multi-application binary data merely used by dosbox-staging, but aren't specifically "dosbox-staging data" files.

But I agree in general: if we started to write out memory-save snapshots, or had some dosbox-staging specific cheat-database, then absolutely: those would deserve to be in `XDG_DATA_HOME/dosbox/...our-blobs-..`.

**Comment by bmunger** [comment]
> To help clarify, are you saying that we should have $XDG_DATA_HOME/dosbox/..., similar how we have $XDG_CONFIG_HOME/dosbox/...?
> 
> For example:
> 
>     $XDG_DATA_HOME/dosbox/mt32-roms
>     $XDG_DATA_HOME/dosbox/soundfonts
>     $XDG_DATA_HOME/dosbox/...

This is what I mean yes.  In the case of mt-32 it's current sharing with locations munt stores it's own binary/rom data.  However it may be a case where munt standalone isn't in use in the system and those directories were never created.  A user may want to contain all dosbox related data into a single data directory in this case.  Generally I think it should, for every multi-application binary file, check local data directory (For example: `$XDG_DATA_HOME/dosbox/mt32-roms`), then check the external directories (For example: `$XDG_DATA_HOME/mt32-roms`).  This also has the side effect that if you want to run modified roms or binary data that you don't want other applications necessarily sharing, it can coexist.  This is probably not going to be the case here, but for setting up a standard for future binary data, it could help.

**Comment by kcgen** [comment]
Thanks for describing this further @bmunger ; looks perfectly reasonable and dosbox-staging is indeed missing the `$XDG_DATA_HOME/dosbox/*` path check.

@dreamer, to drop this in, I'm guessing we should similarly `mkdir $XDG_DATA_HOME/dosbox/{soundfonts, mt32-roms}` (like we currently do in sdlmain.cpp for $XDG_CONF_HOME/dosbox/{soundfonts, mt32-roms}`).  

I'll also add the `$XDG_DATA_HOME/dosbox/mt32-roms` and `$XDG_DATA_HOME/dosbox/soundfonts` paths to the corresponding MT-32 and FluidSynth directory checks; and leave the existing ones as-is.

**Comment by kcgen** [comment]
@bmunger , 

When you have a chance, can you give branch `kc/xdg-data-1` a test run and let us know if it's doing what you expect? Our CI-generated binary don't include MT-32 support, so you will need to compile this with the `--enable-mt32` configure option. 

Much thanks!

**Comment by bmunger** [comment]
Apologies for being late, was busy with the holiday.  Also took me a bit today to get mt32emu linked in, but it's now working.  I have tested the roms in various directories and the behavior of $XDG_DATA_HOME works as expected.  Thanks for all the effort here, it's much appreciated!

**Comment by kcgen** [comment]
Thanks @bmunger!
