### ISSUE TITLE
Choosing date format in config file

### ISSUE THREAD

**Issue by Draky50110** [dosbox-staging/dosbox-staging#782]
Hello.

Would it be possible to add an option in conf file to choose date format ?

MM-DD-YYYY is US format.
For example, French uses DD-MM-YYYY

And why not, choosing other formats like YYYY-DD-MM or MM-YYYY-DD and so...
Something like "dateformat=" + value

That would change strings in help command because instead of "type 'date MM-DD-YYYY' to change date" it should be "type 'date %s' to change date"... or something like that.

**Comment by kcgen** [comment]
We can likely tie this to the users preferred locale, and would be implemented with the larger translation effort.

So if a user specifies Canadian english (and/or keyboard layout) they would similarly get the ISO-standard date ordering.

**Comment by Draky50110** [comment]
Ok, I understand but this will need language change for help strings.

**Comment by Draky50110** [comment]
I close because date format is language dependant...
Tested with MSDOS 6.22 on DOSBox : keyb fr = French date/time format, while keyb us gives US date/time format.
