### ISSUE TITLE
Mouse cursor drifts in Tie Fighter (1995 CD)

### ISSUE THREAD

**Issue by Rugaliz** [dosbox-staging/dosbox-staging#784]
The mouse cursor drifts away in a random direction in the game Tie Fighter 1995 CD version while having game-pads plugged in and Joystick set to anything other than none.

I'm running this on a Fedora 33 with dosbox-staging 0.76 but it also happens on my brothers laptop with Linux mint 19.3 and a gamepad pullged.
 I can remedy the issue by disabling the joystick in the settings but...well this is a flight sim and even the analogue stick in a controller is better than a mouse.

**Comment by dreamer** [comment]
Have you tried adjusting `deadzone` option in `joystick` section?

**Comment by kcgen** [comment]
Also try setting the `timed=false` joystick option.

Another thing to try: when the game starts, skip the initial joystick calibration by clicking past with your mouse.  When you start a mission, press Alt+C to calibrate your joystick then.

(This was a problem that affected me on real hardware using a gravis joystick. Was super frustrating and unfortunately didn't have work around back then!)

**Comment by Rugaliz** [comment]
Hi
Thanks for the fast response.
So I tried @kcgen  solution and set `timed=false` and that solved the issue.  With controllers connected the mouse doesn't drift anymore.
