### ISSUE TITLE
DOS fonts are broken for non-english languages for Hercules, CGA, and Tandy modes

### ISSUE THREAD

**Issue by dreamer** [dosbox-staging/dosbox-staging#785]
**Describe the bug**
As the title says. The issue is a little bit visible in French (e.g. normally using `keyb fr` fixes letter É, but not in Hercules mode) and visible in Polish a lot (in VGA type `keyb pl` and font will correct immediately, but not when using Hercules).

**To Reproduce**
Change the language in .conf file (e.g. `language=fr_FR.lng`, using appropriate lng file (see `contrib/translations/`).
Then change the `machine` setting or alternatively:

    $ dosbox -machine hercules
    $ dosbox -machine cga
    $ dosbox -machine cga_mono
    $ dosbox -machine tandy
    $ dosbox -machine pcjr

**Expected behaviour**
As with the text for VGA/SVGA text modes.

**Comment by kcgen** [comment]
Interesting @dreamer! 
Under the hood, does dosbox contain some kind of raster representation of all the potential language characters? Or does it get font characters from the OS via some underlying font API?

**Comment by dreamer** [comment]
Fonts are hardcoded in binary blobs in `src/ints/int10_memory.cpp` (AFAIK glyph data is simple 1BPP matrix - I guess if we replaced hex literals with binary 0b literals, then glypsh would be clearly visible and editable by hand).

Not sure about codepages, I suspect they are hardcoded in binary blobs in `src/dos/dos_codepages.h`.

There's a chance that old DOS versions from CGA or Hercules times simply did not support alternative codepages, but I find it unlikely.

**Comment by dreamer** [comment]
Another case where fonts are broken: switch mode to 132x50, run `keyb fr`. Surprisingly, `keyb pl` is not broken in this case.

**Comment by Grounded0** [comment]
I can type French accented characters both in VGA and Tandy mode but need more people to verify this before closing.

**Comment by Grounded0** [comment]
Notifying @IPeluchito @Kappa971 @Burrito78

**Comment by Grounded0** [comment]
Closing as fixed after initial testing by couple people. If you find any issues you can reopen this.

**Comment by Kappa971** [comment]
There is actually a problem with some letters in the hercules, cga, cga_mono, tandy and pcjr machines (even if the correct codepage is set, i.e. 858 for Italian):
-machine svga_s3
![svga_s3](https://user-images.githubusercontent.com/62349018/182970347-1f5618bc-868c-4b7b-96d3-9977e07c82a4.png)
-machine hercules (and others):
![hercules](https://user-images.githubusercontent.com/62349018/182970389-c66b9a5c-27e6-4d4c-b4be-8433a23db6af.png)

I tested on Debian 11, I don't know if the same thing happens on Windows.

**Comment by Grounded0** [comment]
I pulled CP850 codepage table from Columbia University's Kermit Project. It's zipped so the CP850 content is preserved:

[cp850.zip](https://github.com/dosbox-staging/dosbox-staging/files/9264222/cp850.zip)

**Comment by Grounded0** [comment]
Tandy character ROM indeed does not have A grave at that codepoint:

<img width="1392" alt="Screenshot 2022-08-05 at 3 22 52" src="https://user-images.githubusercontent.com/48192273/182976668-0a2c8477-5c4e-41e4-8b8c-f220925d3f35.png">

**Comment by Grounded0** [comment]
I pulled CP437 codepage table from Columbia University's Kermit Project. It's zipped so the CP437 content is preserved:

[cp437.zip](https://github.com/dosbox-staging/dosbox-staging/files/9264342/cp437.zip)

**Comment by Grounded0** [comment]
At least Tandy character ROM is hardcoded for CP437:

<img width="1392" alt="Screenshot 2022-08-05 at 3 53 13" src="https://user-images.githubusercontent.com/48192273/182979208-b70f9740-9abb-4554-8ca5-81e8d6612c70.png">

**Comment by kcgen** [comment]
Right now, the codepage EGA files are universal and aren't tied to video mode.

I suppose to solve this, we'd have to have a separate bank(s) of tandy-specific (or perhaps low-res) codepage files?

**Comment by Grounded0** [comment]
Since no Tandy 1000 system was sold outside of North America i'm steering into do nothing camp. No software was written in Europe with Tandy in mind unless it was games with international releases.

This also only impacts text modes and almost all games enter into bitmap modes and use their own text engines. CGA/EGA/VGA/SVGA can be accessed in a universal way from S3 Trio. So i'm proposing to close this as it tries to fix a problem that has no historical basis.

**Comment by kcgen** [comment]
> no Tandy 1000 system was sold outside of North America
> also only impacts text modes and almost all games enter into bitmap modes and use their own text engines
> CGA/EGA/VGA/SVGA can be accessed in a universal way from S3 Trio
> it tries to fix a problem that has no historical basis 

Thanks for all those points, @Grounded0.  On the maintenance side, this would add more complexity (even if we figured out how to address it) for what appears to be no tangible value. 

Closing as wont-fix.

**Comment by Kappa971** [comment]
> Since no Tandy 1000 system was sold outside of North America i'm steering into do nothing camp. No software was written in Europe with Tandy in mind unless it was games with international releases.
> 
> This also only impacts text modes and almost all games enter into bitmap modes and use their own text engines. CGA/EGA/VGA/SVGA can be accessed in a universal way from S3 Trio. So i'm proposing to close this as it tries to fix a problem that has no historical basis or can be accessed in a universal way through superset standard like SVGA in S3 Trio device.

We are not talking about localized games but to correctly display the localized DOSBox texts. I think it is correct that every machine displays the text strings the same way, with no missing characters. Obviously if all of this doesn't take too much work.

**Comment by Grounded0** [comment]
Can someone post screenshots how DOSBox-X behaves under similar situations.

**Comment by kcgen** [comment]
> Can someone post screenshots how DOSBox-X behaves under similar conditions.

![2022-08-05_09-54](https://user-images.githubusercontent.com/1557255/183124841-c17c9feb-8640-4fb6-a441-8f3c20fc68fe.png)

**Comment by Grounded0** [comment]
I looked into it and we would have to construct our own character sets from extended character sets in here to fit into each codepage:

https://int10h.org/oldschool-pc-fonts/

**Comment by Kappa971** [comment]
> I looked into it and we would have to construct our own character sets from extended character sets in here to fit into each codepage:
> 
> https://int10h.org/oldschool-pc-fonts/ https://www.vogons.org/viewtopic.php?t=27615 http://web.archive.org/web/20131001094941/http://www.geocities.ws/ivan_llanas/software/fontedit2.html
> 
> Anyone is of course welcome to start such undertaking and post progress here.

What exactly would need to be done?

**Comment by Grounded0** [comment]
I did some extensive digging on this and Tandy 1000 is hardwired at CP437 and does not support:
<img width="673" alt="Screenshot 2022-08-24 at 17 28 41" src="https://user-images.githubusercontent.com/48192273/186449659-72c0e68b-8ad9-4d52-9386-89c01c835b27.png">

This makes it impossible to do easy workarounds like loading EGA fonts into Tandy 1000.
