### ISSUE TITLE
All protected mode apps crash DosBox

### ISSUE THREAD

**Issue by NicknineTheEagle** [dosbox-staging/dosbox-staging#791]
**Describe the bug**
Starting any app using protected mode via DOS/4GW causes DosBox to crash. Tested with Doom, Quake, Duke Nukem 3D, Descent.

**Environment:**
- Windows 10 64-bit
- Intel Core i5-9600KF @ 3.7 GHz
- 16 GB RAM (DDR4-3000)
- GeForce RTX 2060 Super (8 GB VRAM)

**Version of dosbox-staging:**
v0.77.0-alpha-127-g74b6

**Configuration parameters:**
[Config file](https://github.com/dosbox-staging/dosbox-staging/files/5744779/dosbox.zip)

**Comment by kcgen** [comment]
Thanks @NicknineTheEagle,  Tagged as duplicate and closing this only because it's been already been reported here: https://github.com/dosbox-staging/dosbox-staging/issues/746

**Comment by kcgen** [comment]
For ref, two workarounds noted by @sarahwhitman here: https://github.com/dosbox-staging/dosbox-staging/issues/746#issuecomment-738706577

**Comment by NicknineTheEagle** [comment]
Ah, apologies, I searched for "protected mode" and got nothing, didn't think to try "memory extenders".

**Comment by kcgen** [comment]
> Ah, apologies, I searched for "protected mode" and got nothing, didn't think to try "memory extenders".

I would be in the same boat! No need for apologies, @NicknineTheEagle  -- appreciate you adding the issue!
