### ISSUE TITLE
Implement NE2000 Ethernet emulation with libvdeslirp TCP/IP handling

### ISSUE THREAD

**Issue by kcgen** [dosbox-staging/dosbox-staging#797]
This will allow native TCP/IP based DOS games (Quake, DOOM, and others) to join TCP/IP servers. It will additionally allow DOS and Win 3.11 TCP/IP access over modern layer-2 hardware (WiFi, WiLAN, and cellular data) without elevated rights, as `libslirp` operates as software TCP/IP client at layer-3 level (TCP/IP). 

We will ideally support and use the code-base from @jookia's DOSBox-X PR: https://github.com/joncampbell123/dosbox-x/pull/1863, as suggested in [this comment](https://github.com/joncampbell123/dosbox-x/pull/1863#issuecomment-753485703).

@jookia's PR has been imported to DOSBox Staging on [this branch](https://github.com/dosbox-staging/dosbox-staging/tree/kc/ethernet-1), which can be compiled and run with this half-working demo, [staging-jookia-slirp-demo.zip](https://github.com/dosbox-staging/dosbox-staging/files/5760516/staging-jookia-slirp-demo.zip). Just launch your compiled `dosbox` executable inside the `ethernet`, directory where `[autoexec]` will run the demo.

![2020-12-30_12-15](https://user-images.githubusercontent.com/1557255/103461525-d7f68580-4cd3-11eb-9fd1-a221bb1f28b0.png)
![2020-12-30_12-15_1](https://user-images.githubusercontent.com/1557255/103461529-da58df80-4cd3-11eb-84c4-8b3a5495b1be.png)
![2020-12-30_12-16](https://user-images.githubusercontent.com/1557255/103461533-df1d9380-4cd3-11eb-8038-2aa26f572f04.png)

**Comment by Jookia** [comment]
I've just done a major patch update that's almost final, I'd like to know how it goes in this codebase and if there's anything I need to do to avoid massive git conflicts. You'll also want to update build instructions to include libslirp-dev.

**Comment by kcgen** [comment]
@Jookia - that's great news. 

I had started the import (before you resumed work on the patch), on this branch: https://github.com/dosbox-staging/dosbox-staging/compare/kc/ethernet-1, which includes some of the tie into regarding `configure.ac` and documentation update.

We would be extremely grateful if you'd like to push a PR.  When you push it, our CI system will build it on all platforms, and we will additionally review the code and make any suggestions. 

Alternatively, if time is limited, then I would be happy to pull your work from your ongoing DOSBox-X branch with yourself as the commit `--author`. Even then, I will have to do the same process here in terms of pushing the PR, having CI process it, and pass the code through review process - all of which you can be involved in.  Whatever suits you best.

**Comment by Jookia** [comment]
I'll try and do a PR for here after I'm done with the DOSBox-X one, or when I feel the code is ready for that. I would heavily appreciate if you reviewed the code/made suggestions on the DOSBox-X branch first since that's where I'm doing active development.

**Comment by kcgen** [comment]
Will post review feedback on the X forum, thanks @Jookia.

For the Staging PR, you can remove all of pcap stuff and config. Same with most of the libslirp config. Only critical/necessary functionality (ie, for an application/game to work) should be exposed.  I believe this will be the general port forwarding rules.

All the slirp backend IP settings can be hidden and hardcoded (as a block of `constexpr`s), as even two dosbox slirp processes on the same host can communicate with eachother without conflict, as they do so via the host interface and connect to the others' inbound port forward.

(Ahead of myself; lets progress the -X PR first!)

**Comment by Jookia** [comment]
I don't have any port forwarding rules in my PR ... yet?
Regarding pcap stuff, don't you have pcap in Staging? If so, what would happen with that?

**Comment by Wengier** [comment]
@Jookia DOSBox Staging (current version) does not have NE2000 or pcap support. It is designed to be a DOS game-oriented emulator, which is different from DOSBox-X in its scope.

**Comment by Jookia** [comment]
Hmm. What would slirp hook in to then?

**Comment by kcgen** [comment]
Right; port forwarding can be a follow on after your PR.

We don't currently have NE2000 support (or pcap). The advent of a working slirp solution makes adding TCP/IP support fall inline with the project goals.

**Comment by Wengier** [comment]
@Jookia As mentioned above, NE2000 + slirp will be desired for DOSBox Staging. In such case no pcap or other things that may be deemed unnecessary.

**Comment by Jookia** [comment]
Makes sense. How close is NE2000 support to being added? Did you want it to be copied from my branch, though the code there is fairly untidy. It would be hard to test this code without NE2000 or some other adapter support.

**Comment by Wengier** [comment]
@Jookia I don't think there is any NE2000 support code in the DOSBox Staging repository yet. It will be implemented however, after a code review, since DOSBox Staging features a code review system.

**Comment by Jookia** [comment]
It sounds like the NE2000 code and this code would have to be merged and reviewed at the same time in order to test things. Unless this could somehow be merged without it actually running or tested?

**Comment by Wengier** [comment]
@Jookia Depending on the size of the code - if the code is not too large, it can be submitted as one PR; otherwise, it may be submitted as multiple PRs - first the basic stuff, then more cleanups, etc.

**Comment by arrowgent** [comment]
how will this effect ipx/tcpip emulation with ipxnet server and ipxnet connect?
supposedly mutually exclusive?  if one is enabled in settings then the other cannot be used?

**Comment by dreamer** [comment]
To the best of my knowledge, IPX emulator should be totally independent of TCP-IP emulator via libslirp. I don't think there is any usecase for having them both enabled at the same time though.

**Comment by Jookia** [comment]
Yes, having them both enabled should be fine. Is there a NE2000 issue open that I can mark this as a blocker?

Does Dosbox-Staging require Windows XP support? Right now the big issue in DoOSBox-X is vendoring glib and libslirp, partially to provide WinXP compat.

**Comment by kcgen** [comment]
Hi @Jookia,

NE2000 will be a new feature added to DOSBox Staging as part of your PR.  Just include the NE2000 source file file as-is with your slirp code.

(I don't think we need an issue to mark it as a blocker.) 

We only supports modern OSes that are also supported by their maintaners.  When and OS goes EOL  we also stop supporting it.

So you can assume a current glib version will be available.  We've recently switched to meson, so @dreamer can add both glib and libslirp dependencies, so for staging's PR you can avoid vendoring these in.

**Comment by dreamer** [comment]
Hmm, maybe I should prepare the ground by importing relevant commits with old NE2000 implementation… I'll look into this.

We don't require Windows XP support; as for dependencies: we do it differently than DOSBox-X - we try to depend on libraries in well-known repositories (vcpkg or MSYS2 on Windows, brew on macOS, and any native repository on Linux and other systems). libslirp is already widely packaged, so the majority of users will have no problem here.

libslirp is missing from vcpkg, but it's not a blocker - this library already uses Meson like we do :) Adding Meson WrapDB entry will be trivial (I'll do it if it will be necessary). The feature will probably be initially disabled in our Visual Studio-based builds, but that will "fix itself" once we'll have Meson-generated VS solution.

@Jookia which OS do you use for development?

**Comment by Jookia** [comment]
We'll probably need a vcpkg of sorts for glib/libslirp.

**Comment by Jookia** [comment]
Oops, I didn't see your second email. That answers my question.

I'm a full time Linux user that mainly does embedded Linux development.
I've been using mxe to cross-compile the program and Wine to test.
I also have a Windows 10 machine I use for testing, but it's very
inconvenient for me to use.

**Comment by dreamer** [comment]
@Jookia that's great - we are all Linux users in here :)

Don't worry about Windows - we'll figure it out, and it's ok if the feature will be disabled in Visual Studio initially. Right now I am working on importing old NE2000 patch and importing some fixes from DOSBox-X - so far it's going ok - once I'm finished you will  have good starting point for rebasing your changes on top of dosbox-staging history. Stay tuned :)

**Comment by dreamer** [comment]
@Jookia try this branch: [`po/import-ne2000-1`](https://github.com/dosbox-staging/dosbox-staging/tree/po/import-ne2000-1). If this branch is good enough for you to start work on introducing libslirp backend for NE2000, then I will simply merge it to master (considering it's legacy code), so you could start targeting master with your PRs. If you prefer to work with a feature-branch workflow - let me know :)

Goal for us it not to resurrect pcap-based, ifdef-ridden, windows-centric implementation, but rather to have modern, cross-platform, libslirp-based solution *only*.

On top of original ne2000 code I applied several patches from DOSBox-X, to make conflicts with your existing code less likely (but not all DOSBox-X changes - some made no sense for our project). On top of that I fixed some trivial stuff and added `slirp` dependency to our buildsystem - but it's disabled by default - code does not build because it expects pcap library.

To build:

    meson setup -Duse_slirp=true builddir
    ninja -C builddir

Feel free to remove any remains of pcap library that will be in your way :)

Based on what I see in PR in DOSBox-X I think you'll know what to do ;) When talking about new code, please note that we have a bit different commit message style compared to DOSBox-X (no "ne2000:" or "dosbox:" prefix in message subject), and somewhat stricter rules about formatting (just use clang-format when adding new code).

I *strongly* recommend going 1-2 patches per PR. 10 small reviews will go much faster than 1 review with 10x size.

**Comment by Jookia** [comment]
libslirp *only*? What about interfacing with actual hardware, such as
using a tun/tap device?

**Comment by Jookia** [comment]
I mainly ask because I've written an abstraction layer for DOSBox-X. Do
you want that thrown away?

**Comment by dreamer** [comment]
> libslirp *only*? What about interfacing with actual hardware, such as using a tun/tap device?

I don't understand the question. TUN/TAP is not a hardware device. Is there a usecase where pcap provides some feature that's not provided by slirp? Does this feature require users to run as root/administrator?

If *you* think pcap backend is useful, then I am ok with keeping it. I would need to know more to decide if it should be enabled by default in our release builds or not. But that's a discussion for later, I guess.

> I mainly ask because I've written an abstraction layer for DOSBox-X. Do you want that thrown away?

Keep the abstraction layer, of course :) Don't throw it away!

**Comment by Jookia** [comment]
It was discussed in the other DOSBox-X thread, but pcap/tun/tap are very useful for connecting a guest to an actual network.

**Comment by dreamer** [comment]
I am not yet convinced we should support pcap-based backend, but - just to make your work easier - I added the dependency to the branch: 10067a7801c702f442d140694a0fcd838ee306bb.

The NE2000 feature is buildable now:

    meson setup -Duse_pcap=true build
    ninja -C build

@Jookia Tell me if this branch is good enough for you to start work on this feature - if it's ok, then I will merge this code to master (but the feature will stay disabled by default for now).

**Comment by Jookia** [comment]
I've abandoned my branch, someone else will have to do this.

**Comment by Jookia** [comment]
Well, I planned to abandon this but then did the opposite and finished it for DOSBox-X. I'm going to make an attempt to port it to DOSBox-Staging now.

**Comment by kcgen** [comment]
Three up votes in < 20 minutes!

**Comment by dreamer** [comment]
@Jookia I merged `po/import-ne2000-1` to the master branch, so you can base your work off master.

NE2000 feature is disabled for now, as I really don't like some stuff as was implemented in old ne2000 code for pcap, but I noticed you fixed some of that stuff in your new PR in DOSBox-X.

If you need any help with Meson, or our CI - ask away :)

**Comment by kcgen** [comment]
Thanks for merging the NE2000 scaffolding to minimize all potential obstacles with this PR @dreamer!

**Comment by Jookia** [comment]
Would it be okay if I just removed the pcap code? It would save me a lot of time with this.

**Comment by kcgen** [comment]
> Would it be okay if I just removed the pcap code? It would save me a lot of time with this.

Yes, please do so!

If you search this thread for "remove", you will find both @dreamer and myself on-board with removing pcap.

**Comment by dreamer** [comment]
If someone will have a realistic use-case for it, then maybe we'll bring it back in the future - but I find it rather unlikely anyone actually needs it.

Removal of pcap will also save us the trouble of documenting, translating, and explaining why the feature is implemented but disabled in our official builds. And it probably would not work at all in sandboxed packages (Snap, Flatpak).

**Comment by Jookia** [comment]
Gotcha. My PR plan will just be to implement the Ethernet backend abstraction, plug it in to NE2000, then add slirp. This should remove at least a dozen patches and make it around 3 to 5. I already had to add one to fix pcap building, and I'm going to include that (it's a one liner) just for the sake of history and if anyone wants to know down the track how it was initially implemented.

**Comment by Jookia** [comment]
PR at https://github.com/dosbox-staging/dosbox-staging/pull/929
