### ISSUE TITLE
Alt-Enter fullscreen no longer works on Linux GNOME x11

### ISSUE THREAD

**Issue by rekaerst** [dosbox-staging/dosbox-staging#803]
**Describe the bug**
Enter fullscreen mode not working properly on Linux with GNOME(x11) desktop.
after press alt-enter
![image](https://user-images.githubusercontent.com/52642831/103705336-d1bf1c80-4fe5-11eb-82b6-6d351ec0ff71.png)

**To Reproduce**
install latest dosbox-staging on Linux with gnome(x11) desktop via github or package manger
press alt-enter to enter fullscreen mode and notice it's not working properly

**Expected behaviour**
Alt-enter should enter fullscreen mode

**Environment (please complete the following information):**
- OS and version: Ubuntu 20.10 x86_64
- Relevant hardware info: 
  - CPU: Ryzen 5 4600H
  - GPU: AMD 05:00.0 Renoir
  - Display:  1920x1080

**Version of dosbox-staging:**
v0.75.0, v0.75.1, v0.75.2, v0.76.0, v0.77.0

**Configuration parameters:**
default

**Additional context**
SDL2 version 2.0.12+dfsg1-4
GNOME version 3.38

**Comment by GranMinigun** [comment]
It turned out to be a bug on Gnome's side: #755
Which version of Gnome you are using?

**Comment by kcgen** [comment]
For the time being, I'm using out-of-the-box XFCE on Ubuntu 20.10; `alt + enter` in there works perfectly.

**Comment by rekaerst** [comment]
I am using Gnome 3.38.1. This seems to be a duplication of #755, sorry.

**Comment by kcgen** [comment]
No worries @rekaerst; thanks for the dupe-reference @GranMinigun.
(closing)
