### ISSUE TITLE
Investigate compatibility with games currently only runnable with DOSBox Daum 

### ISSUE THREAD

**Issue by kcgen** [dosbox-staging/dosbox-staging#804]
The following games are currently work best with DOSBox Daum for various reasons.

 - 4thgen
 - Abaron
 - airball
 - AirLSim
 - AMattero
 - Arrakis
 - brany
 - BRdRace
 - Chicken
 - City89
 - CrazBrix
 - Dactylus
 - DCCTenis
 - DiePirat
 - Dism95
 - DREAMSto
 - Elkinlor
 - EuroRace
 - EXP
 - eyeotyp
 - FalconAT
 - frontier
 - FStein94
 - Hardline
 - HauChil
 - Hopang
 - HostageR
 - houndb
 - Hugo
 - IceKiss
 - Jackal (thanks @smilingspectre): 
    > *DOSBox Staging shows the same behavior: non-interrupted noise instead any sound in the game. While there is sound. I tested (with Daum, BTW), and I can get sound occasionally, if I make EGA version run somewhere above 2000 cycles but below 5000 (anything above it mute sound totally). In that case there is no "drilling" sound, but exist distinct sound of throwing bombs and blasts from the weapon. But it unstable, and also, I suspect, it's not all the game capable of.*

 - KarkKeep
 - Katapult
 - KingSyr3
 - MoleFest
 - Monmalli
 - OpAirSto
 - P47FF
 - PacMan82
 - Paddle02
 - Panic02
 - PBTime2
 - PCFutB3
 - PCFutB5
 - PilgrimQ
 - PoDtSoCL
 - psychokl
 - purptit
 - PuzBob
 - rarkani1
 - Rocks97
 - RS2
 - SC2Plus
 - SDogStry
 - seawar
 - ShootL2
 - SootySwe
 - SpearEn
 - Speedway
 - Spong93
 - twnoname
 - UpPerisc
 - VidBJak
 - VirtualP
 - VirtualS
 - Vroom
 - WarWiz94

Thank you to **parricc** for providing this list.

**Comment by kcgen** [comment]
| Game  | Conf  | Screenshots  | Comments  |
|---|---|---|---|
| 4thgen.pc  | [dosbox.conf.txt](https://github.com/dosbox-staging/dosbox-staging/files/5773799/dosbox.conf.txt) | ![2021-01-05_17-03](https://user-images.githubusercontent.com/1557255/103726911-dc01fc00-4f8e-11eb-81cb-fd10979e1ac1.png)  |   |
|  Abaron.pc | [dosbox.conf.txt](https://github.com/dosbox-staging/dosbox-staging/files/5773800/dosbox.conf.txt) | ![2021-01-05_17-24](https://user-images.githubusercontent.com/1557255/103727059-2aaf9600-4f8f-11eb-9cbb-fca44f6446ef.png)  |  Mouse not detected, need to use keyboard |
|  airball.pc | [dosbox.conf.txt](https://github.com/dosbox-staging/dosbox-staging/files/5773801/dosbox.conf.txt) | ![2021-01-05_17-26](https://user-images.githubusercontent.com/1557255/103727159-72ceb880-4f8f-11eb-85d9-c71d3e1031f6.png) | Unsure CMS audio is working; PC speaker works |
| AirLSim.pc  | [dosbox.conf.txt](https://github.com/dosbox-staging/dosbox-staging/files/5773802/dosbox.conf.txt) | ![2021-01-05_18-51](https://user-images.githubusercontent.com/1557255/103727228-a01b6680-4f8f-11eb-8ba7-8c2e29ce16a0.png) |  |
|  AMattero.pc |  [dosbox.conf.txt](https://github.com/dosbox-staging/dosbox-staging/files/5773804/dosbox.conf.txt) | ![2021-01-05_17-48](https://user-images.githubusercontent.com/1557255/103727266-b7f2ea80-4f8f-11eb-832b-f28096765858.png)  |   |
| Arrakis.pc  | [dosbox.conf.txt](https://github.com/dosbox-staging/dosbox-staging/files/5773805/dosbox.conf.txt)  | ![2021-01-05_17-46](https://user-images.githubusercontent.com/1557255/103727289-c4774300-4f8f-11eb-83c3-4256a33b8caa.png) |   |
|  brany.pc | [dosbox.conf.txt](https://github.com/dosbox-staging/dosbox-staging/files/5773806/dosbox.conf.txt)  |   ![2021-01-05_17-58](https://user-images.githubusercontent.com/1557255/103727338-e7095c00-4f8f-11eb-8949-569514a4adff.png)  | |
| BRdRace.pc  |   |   | Needs HDD-image containing CDROM image mounted w/ SHSUCDX (See [1](https://www.vogons.org/viewtopic.php?t=34767) and [2](http://adoxa.altervista.org/shsucdx/index.htm))  |
|  Chicken.pc |  [dosbox.conf.txt](https://github.com/dosbox-staging/dosbox-staging/files/5773807/dosbox.conf.txt) |  ![2021-01-05_18-21](https://user-images.githubusercontent.com/1557255/103727550-60a14a00-4f90-11eb-9ca9-a041c9bbc546.png) |   |
| City89.pc  | [dosbox.conf.txt](https://github.com/dosbox-staging/dosbox-staging/files/5773808/dosbox.conf.txt)  |    ![2021-01-05_18-23](https://user-images.githubusercontent.com/1557255/103727573-70209300-4f90-11eb-9860-159fca167eb8.png) | |
|  CrazBrix.pc | [dosbox.conf.txt](https://github.com/dosbox-staging/dosbox-staging/files/5773810/dosbox.conf.txt)  | ![2021-01-05_20-00](https://user-images.githubusercontent.com/1557255/103727698-bf66c380-4f90-11eb-9e51-df80d4917bbb.png) | DAC audio, slight 'fizz' sound  |

**Comment by kcgen** [comment]
Pro Pinball: Timeshock! (1997)

- Higher resolutions can be set if 8 MiB of video memory is available.
- A hissing/screeching sound is heard when the table is loading, but does not occur on Daum

Thanks to  discord user **Xavier_Velo** for discovering this and @Python-Exoproject for informing the project.

**Comment by kcgen** [comment]
From Xavier_Velo regarding stuttering in Pro Pinball when using opengl and texture outputs:

> Ok I tried as you said @kcgen. And there's no stuttering on both outputs in staging, thank you.

**Comment by Burrito78** [comment]
@kcgen Maybe that list could be shoved in a Google Doc and testing distributed to several people. The create individual tickets for fixing remaining bugs per game all under one tag.

**Comment by johnnovak** [comment]
> @kcgen Maybe that list could be shoved in a Google Doc and testing distributed to several people. Then create individual tickets for fixing remaining bugs per game all under one tag.

Agreed, should be systematically trialed and found issues separated out into tickets.

**Comment by kcgen** [comment]
Added Jackal to the list. Thanks @smilingspectre.

**Comment by kcgen** [comment]
> @kcgen Maybe that list could be shoved in a Google Doc and testing distributed to several people. Then create individual tickets for fixing remaining bugs per game all under one tag.

> Agreed, should be systematically trialed and found issues separated out into tickets.

@Burrito78, @johnnovak : good idea; splitting out into separate issues, with some write up to help testers isolate which Daum release actually fixed it.

@ebenbruyns, nice work in getting Daum built on Linux! 

See the write up in any of the following tickets:

https://github.com/dosbox-staging/dosbox-staging/issues?q=is%3Aissue+is%3Aopen+label%3A%22game+compatibility%22

Assuming you can apply your build fix to all of Daum's 51 Windows releases, this will expand the team who can test releases to include Linux and macOS users.

**Comment by kcgen** [comment]
@ebenbruyns, nice work in getting Daum built on Linux! 

See the write up in any of the tickets here: https://github.com/dosbox-staging/dosbox-staging/issues?q=is%3Aissue+is%3Aopen+label%3A%22game+compatibility

Assuming you can apply your build fix to all of Daum's 51 Windows releases, this will expand the team who can test releases to include Linux and macOS users.

**Comment by ebenbruyns** [comment]
> @ebenbruyns, nice work in getting Daum built on Linux!
> 
> See the write up in any of the tickets here: https://github.com/dosbox-staging/dosbox-staging/issues?q=is%3Aissue+is%3Aopen+label%3A%22game+compatibility%22
> 
> Assuming you can apply your build fix to all of Daum's 51 Windows releases, this will expand the team who can test releases to include Linux and macOS users.

Thank you, I didn't think anybody was paying attention or actually cared.

**Comment by kcgen** [comment]
@ebenbruyns - do you have access to the Daum commit history, either SVN / CVS / (or even git) or the source tree at each releases?

![2023-09-15_18-12](https://github.com/dosbox-staging/dosbox-staging/assets/1557255/225fb037-906f-412b-8ec2-e70a2655bfdc)

http://ykhwong.x-y.net/subpages/old.php

I'm not sure where the repo history is. @ykhwong, do you have a copy anywhere?

If your linux-build fix can be applied to each code release, we could reconstruct a git repository of the releases, and then bisect out fixed from there.

**Comment by ebenbruyns** [comment]
There's only one commit in the github repo, if there was access to the history I could have a crack

**Comment by kcgen** [comment]
> There's only one commit in the github repo, if there was access to the history I could have a crack

Yup.. it's tracking down the code at each release that trickier.. maybe a zip of the source was provided somewhere (maybe the wayback machine has some prior snapshots of http://ykhwong.x-y.net with zips of the code?) These /should/ exist for for GPL compliance.. I sure hope they're not lost.

**Comment by ebenbruyns** [comment]
I'll have a scope around, honestly you've made my day, I've been so down trodden by the flathub submission process of this damn thing. I can't promise quick turn around, but considering that I've slayed the big dragon it might be possible to have a way forward from here. Flathub has kinda screwed with the cleanliness of the patch, it was very simple code changes to get it to build.

**Comment by kcgen** [comment]
My fear is Daum's point fixes remain forever intombed in a "one-commit-repo" and a series of blobs.

With your build fix being (likely) applicable down the entire Daum commit history (if you can find it!) - then we have new hope to actually bisect out the fixes and give them wings over to SVN (as .patch), X, Pure, and Staging as PRs.

>  I will also caution strongly against building this outside of a flatpak, it patches gl.h in order to build and it's also got a mangled and patched version of sdl 1.2.15 that it relies on.

Absolutely - and it's a brilliant move to package up Daum's SDL-level hacks inside a FlatPak, which is the perfect containment system for such a beast :rocket:

**Comment by ebenbruyns** [comment]
Not according to the flathub guy... but hey, we can't all be right ;)

**Comment by kcgen** [comment]
> Not according to the flathub guy... but hey, we can't all be right ;)

SDL-level lib hacks? Not a problem baby; FlatPak is the perfect containment system:

![1582820232908](https://github.com/dosbox-staging/dosbox-staging/assets/1557255/ffb47cd5-47ac-4b2d-89ad-668d866d8525)

**Comment by Grounded0** [comment]
Connected issues and PRs:

- #2945

**Comment by Grounded0** [comment]
I'm closing this as its duplication of #2945.

**Comment by Grounded0** [comment]
We just hit 100 % completion rate on this ticket. Thanks for everyone who helped out!
