### ISSUE TITLE
Eye of the Beholder II Adlib-resume after Sfx

### ISSUE THREAD

**Issue by kcgen** [dosbox-staging/dosbox-staging#809]
At a point in the game after playing the four horns, the Adlib music fails to play.

See attached zip for video comparison of working vs broken audio. 

Reproduce using the attached save game: [EOB2.sound.issue.zip](https://github.com/exoscoriae/eXoDOS/files/5782713/EOB2.sound.issue.zip)

1. Load the **"ST** save game. 
1. Drag the horn from the ground, place it in a free hand, right-click to play.
1. Drag the horn back out of your hand to the ground and do the same for the next horn.
1. Repeat using all four horns until the door opens.

All DOSBox forks are affected, except for DOSBox-X when used with the following `dosbox.conf` file:

``` ini
[mixer]
sample accurate = true
```

Initial investigation into a rote-form of porting the sample accurate found that the solution is not self-contained, as the sample accurate feature involves keeping track of whole and fractional sample counts throughout the mixer and channel code (essentially DOSBox's entire audio back-end), as well as having ties into the adlib and pcspeaker code.

Thank you to @Python-Exoproject  for reporting this!

**Comment by kcgen** [comment]
Tested latest in eXoDOS v6, which uses ripsaw's `SLOWREAD` tool to slow disk rates (more in line with a floppy).

Three-for-three:

https://github.com/dosbox-staging/dosbox-staging/assets/1557255/fd7bea56-3f32-43ac-b5c9-e8469d1165e2

**Comment by johnnovak** [comment]
> Tested latest in eXoDOS v6, which uses ripsaw's `SLOWREAD` tool to slow disk rates (more in line with a floppy).

I'm confused. What does `SLOWREAD` actually solve here? I don't think it was expected to play EoB II from floppies at the time of release in 1991, and even if you could, surely playing from HDD was the preferred method.

Don't get the sample accurate thing either; NukedOPL is sample accurate, isn't it? Is DOSBox-X "more sample accurate" in some way?

I'm glad that it works (with glitches though, there are annoying audio crackles at the start of the horn sounds), but maybe it's just a fluke and something completely else we did earlies fixed this?

**Comment by kcgen** [comment]
In this specific case, the game itself seems to need some extra delay to get this door-opening chime working reliability. 

If you test dosbox-x (without using slowread), it misses it quite a few times. And SVN and Staging /will/ play it correctly some of the time too, also without using slowread. It just takes a bunch of tries. 

We know that all the other adlib music and effects play OK in all the EOB games (without slowread). So there's something very timing-specific about this particular door chime where IO rates have a influence on it.

So on one hand.. maybe we could inject PIC timer delays around the IO code, or introduce a conf setting to make it configurable (given controllers and media all had their own rates and latencies.. and these changed dramatically with caches in hardware, software, and the devices). 

If this were a common problem then it might warrant it: but these if extremely specific.. so figured "it works, let's let it be"😅.

**Comment by johnnovak** [comment]
Thanks for the explanation @kcgen, and I agree, we should be very cautious when applying broad fixes to improve something for a single game.

Okay, so some weird timing issue that we kinda fudge with `SLOWREAD`. Wouldn't be surprised if the issue manifested on later 90s hardware too, like Pentium MMX class gear (given that even some Sound Blaster models / clones have issues with faster late 90s bus speeds).

I'm just super curious about anything EoB related, that's all 😎

**Comment by kcgen** [comment]
In this specific case, the game itself seems to need some extra delay to get this door-opening chime working reliability. 

If you test dosbox-x (without using slowread), it misses it quite a few times. And SVN and Staging /will/ play it correctly some of the time too, also without using slowread. It just takes a bunch of tries. 

We know that all the other adlib music and effects play OK in all the EOB games (without slowread). So there's something very timing-specific about this particular door chime where IO rates have a influence on it.

So on one hand.. maybe we could inject PIC timer delays around the IO code, or introduce a conf setting to make it configurable (given controllers and media all had their own rates and latencies.. and these changed dramatically with caches in hardware, software, and the devices). 

If this were a common problem then it might warrant it: but these if extremely specific.. so figured "it works, let's let it be"😅.

**Comment by kcgen** [comment]
Found the wall of the four winds here.. https://m.youtube.com/watch?v=CNJcB2mr7e4

That was ~5 years ago. Not sure if it's captured on real HW or DOSBox.

**Comment by kcgen** [comment]
Found the wall of the four winds here.. https://m.youtube.com/watch?v=CNJcB2mr7e4

That was ~5 years ago. Not sure if it's captured on real HW or DOSBox.
