### ISSUE TITLE
Data-race when Splash image is shown

### ISSUE THREAD

**Issue by kcgen** [dosbox-staging/dosbox-staging#810]
Reported from current stable `master` branch:
 - Build: `./scripts/build.sh -c gcc -t tsan`
 - Launch: `./src/dosbox`
 - Manually exit

Race during splash display (see yellow section **"as if synchronized"** `sdlmain.cpp:2305`:
- ![2021-01-10_17-57](https://user-images.githubusercontent.com/1557255/104141883-c49b8800-536d-11eb-8ff5-a54447cc7550.png)

**Comment by nemo93** [comment]
@kcgen is this still happening please?

**Comment by kcgen** [comment]
I've tried to address this a couple times.
I will make a PR that disables the splash screen as a work-around.
