### ISSUE TITLE
Crash on start when building with --enable-debug on macOS 10.15.6

### ISSUE THREAD

**Issue by zakgi** [dosbox-staging/dosbox-staging#815]
**Describe the bug**
Trying to build from scratch on macOs Catalina with debugging enabled.
Build successfully but crashes when trying to run. Building without debugging seems to work (didn't go through the first screen though).

**To Reproduce**
clone the repo
./autogen.sh
./configure --enable-debug
make

then execute dosbox without parameters from the src folder

**Expected behaviour**
shouldn't crash?

**Environment (please complete the following information):**
macOS Catalina 10.15.6

**Version of dosbox-staging:**
0.76.0, also applies to latest master

**Configuration parameters:**
N/A

**Additional context**

``` text
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x20)
  * frame #0: 0x00007fff70017f53 libncurses.5.4.dylib`___lldb_unnamed_symbol74$$libncurses.5.4.dylib + 120
    frame #1: 0x00007fff700179ec libncurses.5.4.dylib`doupdate + 811
    frame #2: 0x00007fff7000f0b9 libncurses.5.4.dylib`wrefresh + 63
    frame #3: 0x000000010009678e dosbox`DEBUG_ShowMsg(format=<unavailable>) at debug_gui.cpp:85:2 [opt]
    frame #4: 0x000000010027cadb dosbox`Config::ParseConfigFile(this=0x00007ffeefbff568, configfilename="/Users/gzacheo/Library/Preferences/DOSBox/dosbox-staging.conf") at setup.cpp:917:2 [opt]
    frame #5: 0x00000001001ab7db dosbox`main(argc=<unavailable>, argv=<unavailable>) at sdlmain.cpp:3339:12 [opt]
    frame #6: 0x00007fff71828cc9 libdyld.dylib`start + 1
```

**Comment by kcgen** [comment]
Confirmed, thanks @zakgi.

![2021-01-10_19-47](https://user-images.githubusercontent.com/1557255/104145879-8c03aa80-537d-11eb-8dd1-75b29914046b.png)

**Comment by nemo93** [comment]
@kcgen sorry me again. Is this still a current issue?

**Comment by kcgen** [comment]
Closing.
This crash regression no longer occurs (fixed with prior SAN* related memory fixes).
