### ISSUE TITLE
`fullresolution=original` + `scaler=hq2x` leads to cropped display and crashes

### ISSUE THREAD

**Issue by jwrdegoede** [dosbox-staging/dosbox-staging#830]
**Describe the bug**
When setting the following in dosbox.conf:

```
[sdl]
fullscreen=true
fullresolution=original

[render]
scaler=hq2x
```

Then any games started will only show the center quarter of their normal display. I believe that the issue is that the used resolution in this case is the original resolution of the game, e.g. 320x200, without taking the scaling from hq2x into account (so it should be 640x400).

And combing this with setting output=surface:

```
[sdl]
fullscreen=true
fullresolution=original
output=surface

[render]
scaler=hq2x
```

Leads to a segfault. I expect the segfault to go away once the issue with the selected resolution not taking the scaling into account is resolved.

**To Reproduce**
Use a dosbox.conf from the bug description and then run either master of orion (version 1.3) or bomb.exe from bomb32.zip .

**Expected behaviour**
fullresolution=original should take double the game resolution for the fullscreen resolution when combined with scaler=hq2x, this used to work with the original (non staging) dosbox.

**Environment (please complete the following information):**
- Fedora 33, running GNOME3 in Wayland mode
- Lenovo Thinkpad X1 carbon gen 8, with Intel integrated gfx

**Version of dosbox-staging:**
0.76.0

**Configuration parameters:**
See above.

**Additional context**
 - I'm working on packaging dosbox-staging for Fedora, since the original dosbox project is stagnant. And I hit this while trying to play Master of Orion with the old dosbox.conf which I used with the original dosbox
 - When not setting "output=surface" so that I get the "only showing quarter of screen centered issue" instead of a segfault, then the problem goes away when I alt-tab away from dosbox and back again...

**Comment by dreamer** [comment]
> I'm working on packaging dosbox-staging for Fedora, since the original dosbox project is stagnant. And I hit this while trying to play Master of Orion with the old dosbox.conf which I used with the original dosbox

https://bugzilla.redhat.com/show_bug.cgi?id=1884608

Are you already a Fedora packager or can you sponsor new packagers by any chance? 

> When setting the following in dosbox.conf:

True… well, logically it does not make sense to have `fullresolution=original` and `scaler=hq2x` (any scaler) enabled at the same time - these two settings contradict each other.

I'm not sure if we can change the behaviour of `original` to automatically multiply the resolution - that would break for resolutions such as 1024x768. Option `original` is really very troublesome - it's purpose is mostly to support users with old CRT displays, who want to enjoy games using native resolutions...

Not sure what's the best way to deal with this problem yet - but we definitely can't allow emulator to crash.

BTW, `surface` output is in semi-deprecated state - I intend to remove it in the future versions, as it's existence blocks implementation of new improvements… How does `output=texture`, `texture_renderer=software` behave?

**Comment by jwrdegoede** [comment]
> Are you already a Fedora packager or can you sponsor new packagers by any chance?

Yes, I'm already a packager (since 2005-ish) and I can sponsor. I did not know that you already submitted a review-req for dosbox-staging. I should have guessed though, since the .spec file in contrib looks pretty good :)

I do see that this intends to replace the original dosbox, so we need to coordinate this with the maintainer of the original dosbox package. I already has mailing the original dosbox pkg-maintainer on my TODO list. Which is François Cami, who has already been reviewing your package. I guess he is just really busy with $stuff. I assume that like most FOSS devs he has too much stuff on his plate.

I will reach out to François and ask him if he is ok with me taking over the review. It would prefer to do this coordination bit over email, with you in the Cc so that we are all on the same plate. Can I use your dreamer.tan@... email address from the dosbox-staging.spec file for the Cc ?

> > When setting the following in dosbox.conf:
> 
> True… well, logically it does not make sense to have `fullresolution=original` and `scaler=hq2x` (any scaler) enabled at the same time - these two settings contradict each other.
> 
> I'm not sure if we can change the behaviour of `original` to automatically multiply the resolution - that would break for resolutions such as 1024x768. Option `original` is really very troublesome - it's purpose is mostly to support users with old CRT displays, who want to enjoy games using native resolutions...
> 
> Not sure what's the best way to deal with this problem yet - but we definitely can't allow emulator to crash.

So if resolution=original is troublesome, how about ignoring it when combined with scaler=hq2x ?  

> BTW, `surface` output is in semi-deprecated state - I intend to remove it in the future versions, as it's existence blocks implementation of new improvements… How does `output=texture`, `texture_renderer=software` behave?

I don't get a crash (which I also do not get when I do not specify any output, so just relying on the default). I do still only get a quarter of the game's screen. But this time it is the top left quarter instead of a centered quarter of the screen.

Note I only used output=surface because I had some crashed with the original dosbox with some of the other output methods (I don't remember the details, but I do remember that that is why I added output=surface). In general the old dosbox seemed to not like "Master of Orion" version 1.3, it took me some fiddling to get it to work.

**Comment by kcgen** [comment]
> I do still only get a quarter of the game's screen. But this time it is the top left quarter instead of a centered quarter of the screen.

@dreamer, sounds similar to what @ant-222 reported in #808 .

**Comment by jwrdegoede** [comment]
> Sounds similar to what @ant-222 reported in #808:
> 
> > the scale factors were not decreased, so I got a small window displaying the top-left corner of the larger image.

Actually in my case after alt-tabbing away and then back, or using alt+enter to toggle to windowed-mode and then bakc, then the cropping of the display issue goes away. I only have the cropping issue at startup (when starting in fullscreen mode). What is similar is that besides the cropping issue, I also get no scaling so I get a small (almost tiny) image in the top-left corner of my monitor, showing only a quarter of the games display. Both issues (only showing a quarter of the screen as well as the image not being stretched to fill my monitor)  go away after doinf alt+tab or alt+enter 2 times.

**Comment by dreamer** [comment]
OK, the way I see this could be responsibly fixed:

1. Remove `fullresolution=original`; if we find it in a .conf file, then fallback to `desktop` and leave a warning in the log.
2. Introduce a new fullresolution mode: `fullresolution=dos-mode` (or maybe `dos-program-picked`? or maybe `crt-mode`?) Some value to convey the information: "this resolution represents original resolution picked by DOS program".
3. This new mode would cause following settings to be overridden: `aspect` to `false`, `scaler` to `none`, `glshader` to `none`.

This way users who have .conf value `original` (usually inherited from some old .conf file) will be safely upgraded to `desktop` (which is beneficial in almost all cases). Users who own old CRT displays and actually benefit from this setting (which is a tiny, tiny minority) could use new mode, and benefit from automatic overrides of other settings.

**Comment by jwrdegoede** [comment]
> OK, the way I see this could be responsibly fixed:

Sounds good to me.

**Comment by kcgen** [comment]
> Some value to convey the information: "this resolution represents original resolution picked by DOS program"

I also agree. Coming up with a nice value for this is tricky!   I like the **dos** prefix, because without it any generic description is ambiguous because it can equally apply to the host side. 

`dos-native` is the best I can come up with for now 😅

**Comment by ghderty** [comment]
>`scaler` to `none`

Not all CRT setups support lower resolutions like 320x200 and fallback to desktop resolution. It makes sense to have a scaler with `fullresolution=original` in such cases.

**Comment by dreamer** [comment]
Then users of those displays should not use `original` at all, in my opinion. That's why custom resolution option exists.

**Comment by ghderty** [comment]
Custom resolution and scaler settings are appropriate for the settings per application, but in case of several games, they cannot be changed inside the running dosbox via batch file. Also, in some cases, games use different resolutions ingame and in the menu.

**Comment by kcgen** [comment]
@dreamer , I know we want to significantly de-spaghettify the video mode and resolution handling code, and disentangle it from the SDLmain and setup code.

@exoscoriae did a thorough investigation into resolution and output nuances and inconsistencies, which ideally could be taken into account either in part or in full:

https://github.com/exoscoriae/eXoWin3x/issues/59

**Comment by kcgen** [comment]
Tested and confirmed working without issue.
