### ISSUE TITLE
DOS input redirection attempts are not passed into DOSBox temporary config file

### ISSUE THREAD

**Issue by es20490446e** [dosbox-staging/dosbox-staging#834]
Please, could you give feedback on the following [bug report](https://bugs.winehq.org/show_bug.cgi?id=46125)?

**Comment by dreamer** [comment]
Thanks for the report @es20490446e!

I can't get into detail ATM, but we definitely want WineVDM to work exactly the same way as NTVDM in regards to output redirects. If Wine does not do this and parses/escapes commands incorrectly, that would be a problem in Wine.

However, I am "moderately sure" there are bugs in dosbox when it comes to file redirection - it works ok when redirecting between files, but I think it's buggy when redirecting stdin/out between DOS programs and piping - this is something I need to investigate more. However I'll do this only after Meson work will be done (as I need sane environment for recording regression tests).

I plan to make some unrelated improvements in WineVDM, so I will look at the redirection problem while at it.

**Comment by Burrito78** [comment]
@dreamer Keep this open, it's pretty old?

**Comment by kcgen** [comment]
Closing this. The wine ticket shows DOSBox as being used as some kind of sub-shell underneath wine's `cmd.exe` and expects wine to append `< stuff` to the end of DOSBox's `[autoexec]` section.

None of this is supported directly in DOSBox Staging. But maybe the wine-devs can "wrap it" and hack the conf prior to launch.  Closing.
