### ISSUE TITLE
[BUG][ARM][MT32] Games hang at splash screen if MT32 is used / Fluidsynth is fine.

### ISSUE THREAD

**Issue by SupervisedThinking** [dosbox-staging/dosbox-staging#858]
**Describe the bug**
When your start DF on a RockPro64 with MT32 enabled DOSBox freezes at the "DB Staging" splash screen. The dynarec cores *is not used*

**To Reproduce**
Well just start the game on this specific platform with the attached conf file.

**Expected behaviour**
The game should boot as it does with a fluidsynth config.

**Environment (please complete the following information):**
LibreELEC 10-dev

**Version of dosbox-staging:**
https://github.com/dosbox-staging/dosbox-staging/commit/e131d5624021e6afe088507f7c7526d404f60be9
https://github.com/SupervisedThinking/LibreELEC-RR/blob/master-rr/packages/supervisedthinking/emulation/standalone/dosbox/dosbox-staging/package.mk#L5

**Configuration parameters:**
https://pastebin.com/zrVMXjt2

**Additional context**
Strace
https://pastebin.com/hPHsBz3g

**Comment by dreamer** [comment]
@SupervisedThinking https://www.pine64.org/rockpro64/ is Aarch64, right? Can you try to reproduce the issue with older version, so we could pinpoint if we inherited the problem from the original patch or a change in dosbox-staging caused a regression? I suggest building version fd28a403cd7b31ed3cab38f748402a558eca4ffc - it's very early, close to the original patch.

Also, for initial investigations output from stdout/stderr is usually more helpful. Can you easily get the stdout/stderr log?

@kcgen can you try to reproduce this issue on your 64-bit ARM device?

**Comment by SupervisedThinking** [comment]
It's a 64bit kernel + 32bit userspace since there are no Widevine CDM on Linux for ARM64 based devices (https://bugzilla.mozilla.org/show_bug.cgi?id=1679354) and LibreELEC is focused on Kodi and media playback. 

I'll https://github.com/dosbox-staging/dosbox-staging/commit/fd28a403cd7b31ed3cab38f748402a558eca4ffc give a try and report back.

**Comment by kcgen** [comment]
> @kcgen can you try to reproduce this issue on your 64-bit ARM device?

Unfortunately the Pi's kernels and user-spaces (on RetroPie and OpenElec) only support 32bit binaries. I think there are 64-bit Pi distros though, so will look into burning that to a spare SD card and see if I can reproduce it. 

@SupervisedThinking , is this with any build type and optimization level, or should I be building with some specific flags?

**Comment by kcgen** [comment]
Can you try a build without LTO? 

It may not be related, but in `build.md` we specifically ask Rpi4 users to [not build with LTO](https://github.com/dosbox-staging/dosbox-staging/blob/master/BUILD.md#build-a-linux-binary) due to issues.

**Comment by SupervisedThinking** [comment]
@kcgen these are the flags for RK3399:
https://github.com/LibreELEC/LibreELEC.tv/blob/master/projects/Rockchip/devices/RK3399/options#L13-L20
https://github.com/LibreELEC/LibreELEC.tv/blob/master/config/arch.arm#L44-L48

Otherwise LTO was set, I disable it for the tests.

**Comment by SupervisedThinking** [comment]
https://github.com/dosbox-staging/dosbox-staging/commit/fd28a403cd7b31ed3cab38f748402a558eca4ffc & disabled lto but still hangs at boot

Strace:
https://pastebin.com/Zwi68844

**Comment by kcgen** [comment]
It's stuck in SDL threading (poll loop), waiting on a condition to release the mutex.
As a quick check, I tested pointing my conf's `romdir =` at:
 - At a file instead of a directory
 - A non-existing directory
 - An empty directory
 - At a directory holding ROMs with correct names but zero-bytes in size
 - At a directory holding ROMS with correct names and sizes, but junk content
    - `dd if=/dev/random bs=1 count=65536 of=CM32L_CONTROL.ROM`
    - `dd if=/dev/random bs=1 count=1048576 of=CM32L_PCM.ROM`

Alas.. all of these are properly handled with MIDI ultimately rejecting the device (`MIDI: Can't open device: mt32 with config: ''`).

Will keep pursuing the 64-bit OS for my Pi.

**Comment by SupervisedThinking** [comment]
conf file: https://pastebin.com/bznNtLBN
path to MT32: `romdir = /storage/roms/bios`

files in path:
```
rockpro64:~ # ls -l /storage/roms/bios | grep MT32*
-rwxrwxrwx    1 505      500          65536 Jan 12  2005 MT32_CONTROL.ROM
-rwxrwxrwx    1 505      500         524288 Jan  9  2005 MT32_PCM.ROM
```

**Comment by kcgen** [comment]
@SupervisedThinking, 

Unfortunately I can't reproduce this using an Aarch64 kernel on my RPi3 using the current openSUSE Tumbleweed, which is perhaps as up-to-date as they come in terms of kernel and 64-bit user-space (it makes **RetroPie** and the ***bian**'s feel years behind in progress).

**Kernel**:
   `Linux 5.10.9-1-default #1 SMP Wed Jan 20 07:26:11 UTC 2021 (b7732a5) aarch64 GNU/Linux`

**Packages**:
   `zypper se -i -s libpng16-devel libtool opusfile-devel fluidsynth-devel libmt32emu-devel libSDL2-devel libSDL2_net-devel gcc g++ clang`

``` text
^C~/dosbox-staging(master U:1 ✗) zypper se -i -s libpng16-devel libtool opusfile-devel fluidsynth-devel libmt32emu-devel libSDL2-devel libSDL2_net-devel gcc g++ clang
Loading repository data...
Reading installed packages...

S  | Name                   | Type    | Version            | Arch    | Repository
---+------------------------+---------+--------------------+---------+------------------------
i+ | clang                  | package | 11.0.1-1.1         | aarch64 | openSUSE-Tumbleweed-Oss
i  | clang-tools            | package | 11.0.1-1.1         | aarch64 | openSUSE-Tumbleweed-Oss
i  | clang11                | package | 11.0.1-1.1         | aarch64 | openSUSE-Tumbleweed-Oss
i  | clang11-doc            | package | 11.0.1-1.1         | noarch  | openSUSE-Tumbleweed-Oss
i+ | fluidsynth-devel       | package | 2.1.6-1.1          | aarch64 | openSUSE-Tumbleweed-Oss
i+ | gcc                    | package | 10-3.1             | aarch64 | openSUSE-Tumbleweed-Oss
i  | gcc-c++                | package | 10-3.1             | aarch64 | openSUSE-Tumbleweed-Oss
i  | gcc-info               | package | 10-3.1             | aarch64 | openSUSE-Tumbleweed-Oss
i  | gcc10                  | package | 10.2.1+git1030-1.2 | aarch64 | openSUSE-Tumbleweed-Oss
i  | gcc10-c++              | package | 10.2.1+git1030-1.2 | aarch64 | openSUSE-Tumbleweed-Oss
i  | gcc10-info             | package | 10.2.1+git1030-1.2 | noarch  | openSUSE-Tumbleweed-Oss
i+ | libSDL2-devel          | package | 2.0.14-1.1         | aarch64 | openSUSE-Tumbleweed-Oss
i+ | libSDL2_net-devel      | package | 2.0.1-1.10         | aarch64 | openSUSE-Tumbleweed-Oss
i  | libclang11             | package | 11.0.1-1.1         | aarch64 | openSUSE-Tumbleweed-Oss
i+ | libgcc_s1              | package | 10.2.1+git1030-1.2 | aarch64 | openSUSE-Tumbleweed-Oss
i+ | libmt32emu-devel       | package | 2.4.1-2.1          | aarch64 | openSUSE-Tumbleweed-Oss
i+ | libpng16-devel         | package | 1.6.37-1.7         | aarch64 | openSUSE-Tumbleweed-Oss
i  | libstdc++6-devel-gcc10 | package | 10.2.1+git1030-1.2 | aarch64 | openSUSE-Tumbleweed-Oss
i+ | libtool                | package | 2.4.6-8.11         | aarch64 | openSUSE-Tumbleweed-Oss
i+ | opusfile-devel         | package | 0.12-1.2           | aarch64 | openSUSE-Tumbleweed-Oss
```

![Screenshot_2021-02-04_00-24-06](https://user-images.githubusercontent.com/1557255/106826748-64ca9100-663c-11eb-8879-9afe3e78a534.png)

**Comment by SupervisedThinking** [comment]
Thx for testing - well your packages look quite up-to-date & on-par with LibreELEC ones which are basically the same versions. Still LE only has a 64bit Linux kernel while all other programs are 32bit & a RPi3 with BCM2837 is quite different since it's Cortex A53 & not A72.A53 / A73.A53 like the RK3399 & A311D SoC 🤔

**Comment by kcgen** [comment]
> your packages look quite up-to-date & on-par with LibreELEC ones which are basically the same

:+1: 

>  Btw. does the dynarec work for you with gcc10 & 64bit?

Yes; it confirmed it in the `config.h` and works with it explicitly set in the `conf`

``` C++
/* Define to 1 to use x86/x64 dynamic cpu core */
/* #undef C_DYNAMIC_X86 */

/* Define to 1 to use recompiling cpu core. Can not be used together with the
   dynamic-x86 core */
#define C_DYNREC 1
```


> Still LE only has a 64bit Linux kernel while all other programs are 32bit & a RPi3 with BCM2837 is quite different since it's Cortex A53 & not A72.A53 / A73.A53 like the RK3399 & A311D SoC

Indeed (and unfortunately); a lot of differences despite as much as we tried to overlap.

``` ini
[cpu]
core=dynamic
cycles=fixed 12000

[dosbox]
machine=vesa_nolfb

[mixer]
rate = 48000

[midi]
mididevice = mt32

[mt32]
romdir = ../roms

[speaker]
pcspeaker=false
tandy=off
disney=false

[gus]
gus=false

[autoexec]
imgmount d cd/swdf104.cue -t cdrom
mount c .
c:
cd dark
dark.exe
mount -u d
exit
```

**Comment by kcgen** [comment]
@SupervisedThinking -- do you know anyone in the PINE64 company or community? 

If there's some kind of mail-and-return program for developers wanting to support the board, then I'm all for trying to debug the issue further on actual hardware, and then sending the device back to the company once we've figured it out.

Or it might be that PINE64's HQ might be closer to @dreamer, in which case that mail-loop would be better. But without hardware, I'm probably nearing the end of what I can do on this.

**Comment by SupervisedThinking** [comment]
I've reached out to someone at PINE64, IIRC he's the founder 🤔 maybe there is an solution for dev purposes.

**Comment by SupervisedThinking** [comment]
I ran some tests on my VIM3 (Amlogic A311D) which has a quite similar configuration as the RK3399 & I have the same mutex lockup at the same point although it doesn't shows the splash screen ^^ so it's most likely not linked to a specific board but the 32bit userspace stuff.

**Comment by kcgen** [comment]
This bodes well; maybe we can reproduce it on existing hardware.

I'm using LibreELEC on my Pi as a family media player, but I can certainly write a second USB stick to test with - however I'll need help "unlocking" it and installing all the build stack and/or repo (the off-the-shelf image  is stripped of a repo and user-space tools; all for good reason of-course!).

**Comment by kcgen** [comment]
@SupervisedThinking ,

I've just pushed a change that I've been working on for a while. It flips the MT32 code over to using the industrial-strength and[ low-latency Moody ring buffer](https://github.com/dosbox-staging/dosbox-staging/pull/862) to manage rendering and playback in the MT32 code.

This does away with the SDL mutexes, locks, and position coordination in favour of using back-pressure from the ring buffer to entirely pace the threads.

If you `git pull` in your `master` branch, then `git checkout remotes/origin/kc/queue-control-mt32-1` to grab the branch and build. The `meson` branch doesn't have this change, so build w/ auto-tools or the build script. 

Curious if you see any changes!

**Comment by SupervisedThinking** [comment]
Winner Winner Chicken Dinner! 👍🏻🥇 

```
rockpro64:~ # dosbox -conf /storage/roms/dos/testARM/Dark_Forces_MT32.conf
dosbox-staging version git
---
CONFIG: Loading primary file /storage/roms/dos/testARM/Dark_Forces_MT32.conf
CONFIG: Unknown option glshader
MAIN: Draw resolution: 640x480, pixel aspect ratio: 1.00
SDL: Using driver "opengles2" for texture renderer
SDL: Mouse will move seamlessly without being captured.
MEMORY: Base address: 0xf0225008
MEMORY: Using 4096 DOS memory pages (16 MiB)
MIXER: Negotiated 2-channel 44100-Hz audio in 1024-frame blocks
MT32: Found ROM pair in /storage/.config/dosbox/mt32-roms/
MT32: Initialized MT-32 Control v1.07 with MT-32 PCM ROM
MIXER: MT32 channel operating at 44100 Hz without resampling
MIDI: Opened device: mt32
MIXER: FM channel operating at 44100 Hz without resampling
MIXER: SB channel operating at 22050 Hz and upsampling to the output rate
MIXER: GUS channel operating at 1 Hz and upsampling to the output rate
GUS: @SET ULTRASND=240,3,3,5,5
MIXER: SPKR channel operating at 18939 Hz and upsampling to the output rate
MIXER: DISNEY channel operating at 10000 Hz and upsampling to the output rate
MAPPER: Found no joysticks
MAPPER: Loaded default key bindings
MOUNT: Path '/storage/roms/dos' found
SDL: Window has gained keyboard focus
SDL: captured the mouse
SDL: Window has been shown
MAIN: Draw resolution: 640x400, pixel aspect ratio: 1.20
SDL: Using driver "opengles2" for texture renderer
DOSBox has switched to max cycles, because of the setting: cycles=auto.
If the game runs too fast, try a fixed cycles amount in DOSBox's options.
MT32: LCD-Message: LucasArts Games     
SB16: DSP was reset
SB16: Speaker-output has been toggled on
MAIN: Draw resolution: 320x200, double-width, double-height, pixel aspect ratio: 1.20
SDL: Using driver "opengles2" for texture renderer
ENVELOPE: SB done after 108691 frames, peak sample was 14200
ENVELOPE: MT32 done after 441001 frames, peak sample was 21550
MT32: L��9: Attempted to play unmapped key 2173124 (velocity 46053964)
MT32: L��4: Attempted to play unmapped key 2173124 (velocity 46053964)
MT32: L��4: Attempted to play unmapped key 2173124 (velocity 46053964)
MT32: L��4: Attempted to play unmapped key 2173124 (velocity 46053964)
MT32: L��4: Attempted to play unmapped key 2173124 (velocity 46053964)
MT32: L��7: Attempted to play unmapped key 2173124 (velocity 46053964)
MT32: L��7: Attempted to play unmapped key 2173124 (velocity 46053964)
MT32: L��7: Attempted to play unmapped key 2173124 (velocity 46053964)
MT32: L��7: Attempted to play unmapped key 2173124 (velocity 46053964)
MT32: L��7: Attempted to play unmapped key 2173124 (velocity 46053964)
MT32: L��7: Attempted to play unmapped key 2173124 (velocity 46053964)
MT32: L��7: Attempted to play unmapped key 2173124 (velocity 46053964)
MT32: L��7: Attempted to play unmapped key 2173124 (velocity 46053964)
MT32: L��7: Attempted to play unmapped key 2173124 (velocity 46053964)
MT32: L��7: Attempted to play unmapped key 2173124 (velocity 46053964)
MT32: L��7: Attempted to play unmapped key 2173124 (velocity 46053964)
MT32: L��7: Attempted to play unmapped key 2173124 (velocity 46053964)
SB16: DSP was reset
MT32: LCD-Message: LucasArts Games     
MAIN: Draw resolution: 640x400, pixel aspect ratio: 1.20
SDL: Using driver "opengles2" for texture renderer
DISNEY: Shutting down
GUS: Shutting down
IOBUS: Releasing 56 read and 50 write 8-bit port handlers
IOBUS: Releasing 33 read and 38 write 16-bit port handlers
IOBUS: Releasing 33 read and 35 write 32-bit port handlers
IOBUS: Handlers consumed 4088 total bytes
MAIN: Draw resolution: 640x400, pixel aspect ratio: 1.20
SDL: Using driver "opengles2" for texture renderer
SDL: released the mouse
```

Btw: just guide me to the git branch ^^ the LE package buildsystem is able to pull straight the commit or apply patches generated by github and else. Since it's a RO embedded image I have to rebuild the whole thing anyway ^^

**Comment by kcgen** [comment]
Thanks for giving it a go, @SupervisedThinking!

If you can also run an optimized release build (without the debug symbols and asserts enabled above, would be a good for us to confirm all is well when the guard rails are off :-)

Hey.. might as well throw LTO back in the mix while we're at it 👍

**Comment by SupervisedThinking** [comment]
Works with the Amlogic SoC too:

```
vim3:~ # dosbox -conf /storage/roms/dos/testARM/Dark_Forces_MT32.conf
dosbox-staging version git
---
CONFIG: Loading primary file /storage/roms/dos/testARM/Dark_Forces_MT32.conf
CONFIG: Unknown option glshader
MAIN: Draw resolution: 640x480, pixel aspect ratio: 1.00
SDL: Using driver "opengles2" for texture renderer
SDL: Mouse will move seamlessly without being captured.
MEMORY: Base address: 0xf02b3008
MEMORY: Using 4096 DOS memory pages (16 MiB)
MIXER: Negotiated 2-channel 44100-Hz audio in 1024-frame blocks
MT32: Found ROM pair in /storage/.config/dosbox/mt32-roms/
MT32: Initialized MT-32 Control v1.07 with MT-32 PCM ROM
MIXER: MT32 channel operating at 44100 Hz without resampling
MIDI: Opened device: mt32
MIXER: FM channel operating at 44100 Hz without resampling
MIXER: SB channel operating at 22050 Hz and upsampling to the output rate
MIXER: GUS channel operating at 1 Hz and upsampling to the output rate
GUS: @SET ULTRASND=240,3,3,5,5
MIXER: SPKR channel operating at 18939 Hz and upsampling to the output rate
MIXER: DISNEY channel operating at 10000 Hz and upsampling to the output rate
MAPPER: Found no joysticks
MAPPER: Loaded default key bindings
MOUNT: Path '/storage/roms/dos' found
SDL: Window has gained keyboard focus
SDL: captured the mouse
SDL: Window has been shown
MAIN: Draw resolution: 640x400, pixel aspect ratio: 1.20
SDL: Using driver "opengles2" for texture renderer
DOSBox has switched to max cycles, because of the setting: cycles=auto.
If the game runs too fast, try a fixed cycles amount in DOSBox's options.
MT32: LCD-Message: LucasArts Games     
SB16: DSP was reset
SB16: Speaker-output has been toggled on
MAIN: Draw resolution: 320x200, double-width, double-height, pixel aspect ratio: 1.20
SDL: Using driver "opengles2" for texture renderer
ENVELOPE: SB done after 108691 frames, peak sample was 14200
ENVELOPE: MT32 done after 441001 frames, peak sample was 21500
MT32: ��9: Attempted to play unmapped key 2172436 (velocity 52361164)
^[^CSDL: Exit requested
DISNEY: Shutting down
GUS: Shutting down
IOBUS: Releasing 56 read and 50 write 8-bit port handlers
IOBUS: Releasing 33 read and 36 write 16-bit port handlers
IOBUS: Releasing 33 read and 35 write 32-bit port handlers
IOBUS: Handlers consumed 4056 total bytes
MAIN: Draw resolution: 320x200, double-width, double-height, pixel aspect ratio: 1.20
SDL: Using driver "opengles2" for texture renderer
SDL: released the mouse
```

**Comment by SupervisedThinking** [comment]
LTO was enabled on both systems so at least for them it *should* work, I know from the past that the RPi3 struggled sometimes with LTO, no clue if the RPi4 toolchain handles it properly now but this often changes with the compiler afaik. Qt5 & LTO was fine with GCC9 but was broken with GCC10 ^^

Btw: https://github.com/SupervisedThinking/LibreELEC-RR/tree/master-rr I have no RPi3 in use anymore nor a RPi4 but basically all you have to do to build your own LE image with emulators is following the steps. But right now it's still Kodi 19 RC & LE10-dev so I wouldn't exactly use it for a "productive" system unless its a x86_64 system.

**Comment by SupervisedThinking** [comment]
Should be fixed by https://github.com/dosbox-staging/dosbox-staging/commits/kc/queue-control-mt32-1

**Comment by kcgen** [comment]
> Works with the Amlogic SoC 
That Amlogic A311D is a little beast of a board like the Pine64! Wasn't aware of it. For others curious, specs are here: https://www.khadas.com/vim3.

> LTO was enabled on both systems

Excellent!

> The LE build system always builds "release" and stripps off all debug stuff

Ahh, makes sense. The log output tells me the branching is still following the debug code-paths.  Add `#define NDEBUG` or make `-DNDEBUG`, will drop the `assert`s checks from the code and also strip the `DEBUG_LOG()` console output. (https://stackoverflow.com/questions/5354314/how-can-i-completely-disable-calls-to-assert)

**Comment by kcgen** [comment]
(re-opening until the fix lands in the main branch)

**Comment by SupervisedThinking** [comment]
Indeed the A311D is basically a higher clocked S922X have a look at: https://github.com/ThomasKaiser/sbc-bench/blob/master/Results.md
Mainproblem is of course the mainline kernel support but there is steady progress http://linux-meson.com/ & the panfrost driver still needs fixes and optimizations: https://www.phoronix.com/scan.php?page=news_item&px=Panfrost-Mesa-21.0-Bifrost-AFBC

https://www.youtube.com/watch?v=0WMSJCpxxL8 - keep in mind that they used blob drivers & bsp/blob/hacked vendor kernel 🙈

**Comment by kcgen** [comment]
Thanks for the link to Thomas's benchmarks; that's the most thorough (and up-to-date) comparison I've seen.
Looks like the A311D ARM core type is very similar to Amazon's a1.xlarge.  That's quite a bit of performance per core; even handily beating Apple's M1 on a core-for-core basis.  

Poor memory latency across the majority of these ARM systems really jump out at me. Almost all of the "latest" SBCs lag the x86-64 desktop (Pentium G4600 at the bottom) by 5x, and even prior gen SBC are 10x slower. 

Only Apple M1's and Amazon's 32-core 128GiB RAM system really stands up to it. 

When it comes to DOSBox performance, this might explain why ARM SBCs only achieve 1/5th the cycle-count that even low-end x86 desktop PCs enjoy -- it also feels like performance linearly scales with latency.

Another data-point: a Discord user with an Apple M1 was able to run a native ARM (debug!) build of staging with a very high cycle count; right on par with an x86-64 (running the dynamic core). Up till now the theory was that either ARM itself or DOSBox's dynrec implementation was just slower vs x86 dynamic core, but this was one scenario that proved otherwise.

Would be interesting to test DOSBox on other high-memory-performance ARMs. 

> keep in mind that they used blob drivers & bsp/blob/hacked vendor kernel

I hope these vendors eventually open up a bit more. We've seen how AMD's GPU openness has improved life for Linux users versus NVidia's blobs, and AMD's not given up any trade secrets. :shrug:

Oh - just want to double check that you're builds are still humming along w/  **NDEBUG** defined?

**Comment by SupervisedThinking** [comment]
Well the main problem is most SBCs used A53 cores which are in-line-order designs IIRC and they also tend to clock lower because most manufactures used dated nodes like 28nm while the A311D uses 16nm which allows higher freqencies while staying somewhat cool.

The M1 is a league of it's own since it probably exceeds the performance of even the A78 cores & 5nm node is the best you can get.

LE hanldes the debug stuff like this: https://github.com/LibreELEC/LibreELEC.tv/blob/master/scripts/build#L131-L138 just have a look at everything related to `BUILD_WITH_DEBUG`

**Comment by kcgen** [comment]
>  In the end they have to be cheap because nobody would pay hundreds of $ just for a highend SoC with crappy support.
true , :laughing:

> LE hanldes the debug stuff like ... have a look at everything related to `BUILD_WITH_DEBUG`

It's the release build that's the problem.  You're running a release build, but I'm seeing debug log message in your output, which indicates debug pathways are still enabled:

``` text
DISNEY: Shutting down
GUS: Shutting down
IOBUS: Releasing 56 read and 50 write 8-bit port handlers
IOBUS: Releasing 33 read and 36 write 16-bit port handlers
IOBUS: Releasing 33 read and 35 write 32-bit port handlers
IOBUS: Handlers consumed 4056 total bytes
```

And sure enough, that entire file doesn't mentioned **NDEBUG** (ie: "Not debug") anywhere.. such as passing `-DNDEBUG` via command-line arg (common for `make`) or inserting the `#define NDEBUG` inside the `config.h`. (just want to be sure you get this nailed down or fixed upstream :sweat_smile:).

**Comment by SupervisedThinking** [comment]
Normally meson should handle it, currently I'm testing the meson branch, this way: https://mesonbuild.com/Builtin-options.html#core-options

So usually I expect packages to build without debug stuff if `BUILD_WITH_DEBUG` is not set because then the build type should be "plain" 🤔

**Comment by dreamer** [comment]
@SupervisedThinking we use `b_ndebug=if-release` option - this instructs Meson to define NDEBUG for build type `release` (which doesn't concern you, I think) AND for build type `plain` (which majority of packagers will depend on).

Recently I discovered that meson < 0.51.0 was not handling `plain` builds this way, but I guess you use newer Meson already :)

**Comment by kcgen** [comment]
Interesting @dreamer -- I guess `plain` also sets `if-release` to true, then `plain` is a type of release build.

> So usually I expect packages to build without debug stuff if BUILD_WITH_DEBUG is not set because then the build type should be "plain" thinking

Yup - and that's a logical assumption I would make too. @dreamer's solution looks perfect, but perhaps this is something meson could do behind the scene. 

![2021-02-05_08-34](https://user-images.githubusercontent.com/1557255/107061766-68b9f880-678d-11eb-91d5-36c376fb8d09.png)

**Comment by dreamer** [comment]
About NDEBUG confusion: https://github.com/mesonbuild/meson/issues/8308
