### ISSUE TITLE
Tyrian 2000 crash on start (macOS 11.2)

### ISSUE THREAD

**Issue by dixius99** [dosbox-staging/dosbox-staging#871]
**Describe the bug**
When I try to launch Tyrian 2000, DOSBox Staging 0.76.0 completely crashes, and I get the macOS Problem Report window. This is with the default config. I can get the game to run fine in both vanilla DOSBox (0.74-3-3) and DOSBox-X (0.83.9), both also with default configurations.

**To Reproduce**
1. cd TYRIAN
2. TYRIAN.EXE

**Expected behaviour**
The game to launch and play, the way it does with DOSBox and DOSBox-X

**Environment (please complete the following information):**
- macOS 11.2
- Relevant hardware info: 13" MacBook Pro with Touch Bar, 2.7 GHz Intel i7, 16 GB 2133 MHz LPDDR3, Intel Iris Plus Graphics 655

**Version of dosbox-staging:**
0.76

**Configuration parameters:**
Default configuration

**Additional context**
I can paste the Problem Report if that is helpful.

**Comment by kcgen** [comment]
Thanks for the heads up @dixius99!

This _might_ be the new R^X memory protection in the latest mac (reference #253).

To test, try launching with `core = normal` set in your conf file. You can launch dosbox staging with the `-editconf` argument to quick-edit your dosbox-staging.conf.

**Comment by dreamer** [comment]
@dixius99 Do you have dosbox-staging installed via brew or an app bundle (or some other way?).

If app bundle, then make sure it's 0.76.0-3: https://dosbox-staging.github.io/downloads/macos/ (the first macOS build of 0.76.0 version had an issue).

**Comment by dixius99** [comment]
@dreamer Downloading 0.76.0-3 fixed the issue. Thank you both!
