### ISSUE TITLE
No support for the Russian language without KeyRus

### ISSUE THREAD

**Issue by IlyaIndigo** [dosbox-staging/dosbox-staging#881]
**Describe the bug**
DOSBox has always supported Russian, possibly other languages as well, out of the box without resorting to the KeyRus utility as in the original DOS.
http://old-dos.ru/index.php?page=files&mode=files&do=show&id=328
The line from stdout:
`DOS keyboard layout loaded with main language code RU for layout ru`

DOSBox Staging does not support it and outputs short languages instead of Cyrillic, like in original DOS, if you don't run KeyRus before.
But at least you can't run the KeyRus utility before the welcome screen to get an informative output, and the compatibility with DOSBox will be broken, so I think this is a bug and not a feature.
Screenshots and necessary files I have attached.

**To Reproduce**
1 Download the file with the Russian language russian.txt from the attachment or website dosbox and put it in the directory with the config.
2 In the config file write:
```
language = russian.txt
startup_verbosity = medium
```
3 Run a clean dosbox-staging (You will see short Russian characters on the welcome screen instead of Cyrillic).
4 Download russian game "Hocus Pocus" from attachment.
5 Run setup.com (there will be short letters instead of Cyrillic)
6 Run KeyRus.com, then type sutup.com (will be normal Cyrillic characters)
7 Do the same with dosbox.

**Expected behaviour**
The behavior of dosbox-staging should be similar to that of dosbox, that is, it should display Cyrillic.

**Environment (please complete the following information):**
- OS and version openSUSE Tumbleweed
- Relevant hardware info: Notebook Intel i3/Intel HD

**Version of dosbox-staging:**
0.76.0

**Configuration parameters:**
language = russian.txt
startup_verbosity = medium
[russian.txt](https://github.com/dosbox-staging/dosbox-staging/files/5971947/russian.txt)
[Hocus.zip](https://github.com/dosbox-staging/dosbox-staging/files/5971948/Hocus.zip)
![dosbox-welcome](https://user-images.githubusercontent.com/2612812/107772095-c8e00a00-6d4c-11eb-9c3e-b601150a341c.png)
![dosbox-staging-welcome](https://user-images.githubusercontent.com/2612812/107772097-ca113700-6d4c-11eb-8478-0f14f7fe8c48.png)

**Comment by dreamer** [comment]
I presume the text "fixes itself" after typing `keyb ru` (no additional software required)?

That's how 0.74-3 works for me with the same file (without using additional utilities):

![2021-02-12-150333_682x479_scrot](https://user-images.githubusercontent.com/3967/107777821-a269a100-6d43-11eb-9847-0d0316a84061.png)

And DOSBox Staging has the same behaviour as 0.74-3 for me.

We literally changed nothing in this regard when compared to DOSBox SVN, so we'll need to dig in how it actually works.

Anyway, two additional points:

1. DOSBox language files are not compatible between various versions… Yeah, I know - it's stupid - but every version needs it's own translation (so you can't reliably use the same file for 0.74-3 and 0.76.0 :( it will "work" but some strings will be missing while others will be outdated).
2. But we do have a plan to address that already :) After #854 will be finished, I'll start migrating translation strings to `gettext` - this way we'll be able to involve translator communities, test, and bundle the translation directly with the emulator (so no external "language files" will be required). If we have someone willing to work on Russian translation already (with old system), I can set up the translation work the same way we already do for French translation in #776.

So - confirmed - something is broken in here. It's broken in old DOSBox as well, just different users experience the breakage differently :(

**Comment by IlyaIndigo** [comment]
> keyb ru
Yes, it's work! :-)

Well, I can help with the Russian translation if needed. :-)

**Comment by kcgen** [comment]
Addressed; Russian is available.
