### ISSUE TITLE
Operate the PC Speaker at the mixer's rate and low-pass filter its stream

### ISSUE THREAD

**Issue by kcgen** [dosbox-staging/dosbox-staging#882]
**Is your feature request related to a problem? Please describe.**

Some mono-tones played by the PC Speaker are prone to harmonics at the default `pcrate`. 

The speaker is producing 18939 samples per second, which is up-sampled in DOSBox's mixer (typically to 44,100 samples per second) and passed to SDL2, whose output is typically up-sampled to 48000 samples per second in the audio driver or physical audio chip.

Overlapping and differing sampling rates can cause harmonics, new tones either at higher or lower volumes depending how they accumulate, for some frequencies.

Steps to reproduce: 
 here: https://github.com/dosbox-staging/dosbox-staging/issues/876#issuecomment-778059560

**Describe the solution you'd like**

A better solution would be to run the PC speaker at the mixer's negotiated rate to eliminate risk of harmonics while additionally applying a low-pass or band-pass filter to the PC speakers output stream.

Processing overhead would have to be kept to a minimum such we could run this as the default configuration.

Some C++ filters:
 - https://github.com/jimmyberg/DigitalFilters
 - https://github.com/dimtass/DSP-Cpp-filters
 - https://github.com/berndporr/iir1
 - (or using a Fourier transform library)

**Comment by johnnovak** [comment]
Can this ticket be closed now @kcgen, given that my [PC speaker filtering](
https://github.com/dosbox-staging/dosbox-staging/issues/1676) ticket has been merged and you've integrated Ripa's PC speaker patch?

**Comment by kcgen** [comment]
Absolutely :+1:
