### ISSUE TITLE
Add hq4x and 4xBRZ GLshaders

### ISSUE THREAD

**Issue by IlyaIndigo** [dosbox-staging/dosbox-staging#894]
![4xBRZ](https://user-images.githubusercontent.com/2612812/107925458-88b79c00-6f85-11eb-9119-65bdb5bd0a84.png)

**Comment by dreamer** [comment]
As for hq4x - I made a quick test if https://github.com/CrossVR/hqx-shader/blob/master/glsl/hq4x.glsl works - it does **not** (shader fails to compile on my Intel GPU).

If someone has free time to adapt this shader for DOSBox Staging usage, I will be happy to include it out of the box.

As for 4xBRZ - I don't know for sure, but I believe it is a multi-pass shader, and we don't support those now (we need to rewrite graphics pipeline to support those).

**Comment by kcgen** [comment]
Tyrells' XBR level 2 and 3 shaders are similar:

https://github.com/tyrells/dosbox-svn-shaders/tree/master/xbr

To try them, use fullscreen at your screen's maximum resolution, and use `output = openglnb`.

**Comment by tyrells** [comment]
Both the hq4x and hq4x shaders require multiple shader passes and/or additional reference textures, which, unfortunately, the DOSBox shader engine, doesn't currently support.

**Comment by Burrito78** [comment]
Currently out-of-scope until graphics pipeline gets modernized. Can be reopened again after multi pass shader support is available or created new if interest is raised again.
