### ISSUE TITLE
Ability to set and disable quickly in-game inversion of the vertical axis of the mouse.

### ISSUE THREAD

**Issue by IlyaIndigo** [dosbox-staging/dosbox-staging#895]
I came across a very interesting game - Alpha Storm.
This game is clearly inspired by science fiction and the Star Trek and Babylon 5 universes, and I don't know of another like it.
Our Russian "Space Rangers" is a very good space game, but it's still a little bit different.

But to my regret, TAG did not succeed in realizing this idea well and the game is clearly unfinished and full of problems and very silly, as if made on purpose, decisions.

The dumbest one is the inverted vertical mouse axis control in First Person Shooter mode.
But that's only 1 of the game modes!
When you go to the menu, and go to save and boot should be very often! Quick saves, of course, no and even the menu itself is called by F1, not Escape.
So, when entering the menu the mouse control becomes normal, just like in search/route, navigation and space combat modes.
Playing with inverted mouse in FPS mode is very uncomfortable, but to make a permanent inversion is also impossible, it must be constantly, often and quickly and conveniently change in the game, for example by clicking on the middle mouse button.

I don't know if the middle mouse button is used anywhere in DOS games but this option "midle_click_invert_mouse" can be disabled by default "false" and when activated "true" the middle mouse button will invert and bring back the vertical axis.

If you need, I can attach an archive with the game, so you can feel what it's like to constantly quickly switch between FPS mode and menu, mentally invert the control in your head.
[AlphaStorm.zip](https://github.com/dosbox-staging/dosbox-staging/files/5980677/AlphaStorm.zip)
https://disk.yandex.ru/d/izQE6btmVaaxUA Disk image in cue / bin format. (The game starts without it, ln is needed only for videos, music and animations.)

**Comment by dreamer** [comment]
This is a very good idea…

The way about it would be:

1. Implement new mapper action to flip the vertical axis - I think it's possible already, but only by manually editing the conf like this:
```
[sdl]
sensitivity = 100,-100
```
… so it's not good enough for @IlyaIndigo usecase here.

2. Change our handling of middle mouse button to be bindable to any action user needs (instead of being hardcoded to capture/uncapture window)

As for handling of middle-mouse in games - it does happen, but it's extremely rare. We already have an option to force middle mouse button into the games, so we can change the behaviour for games that use middle mouse button themselves.

@kcgen what do you think?

**Comment by kcgen** [comment]
I think it's a great idea, exactly as you've described.  With 1 and 2 in place, we would then add to our existing mouse behaviors in:

`capture_mouse = onstart middle(behavior)` setting. 

With a new `middleflipaxis` or `middleflipvertical` (something like that)?

**Comment by dreamer** [comment]
I don't want `middleflipaxis` option - if we go this route, we'll need to soon replicate every single mappable action as users will keep asking for more and more.

I am suggesting:
1. Add new mappable action for flipping vertical axis (unbound by default)
2. Changing: `middlegame`/`middlerelease` into `middlegame`/`middleaction` with default action bound to "capture/lock window" action (so users can re-bind the action to anything they want).

*Now that I look at it… there is no UI in mapper to re-bind capture/lock window action!*

**Comment by kcgen** [comment]
Ahh yes - thanks for describing it further @dreamer - that sounds perfect!

I especially like how the middle-button setting in `mouse_control = ` will becoome _more_ flexible and powerful.

Game integrators will now be able to provide extended "default functionality" to the middle button, for the (thousands!?) of dead-middle mouse games.

There a so many games that could benefit from having some common key action mapped into the middle mouse botton (especially when there's a modern equivalent that gamers might expect).  Like "open door" or "use" or "reload-weapon".  

Hmm.. this is actually very exciting, and could be another sleeper-hit feature :-)

**Comment by Burrito78** [comment]
This will be implemented in the new mapper, it's a must have for a modern mapper. Also disable axis quickly.
