### ISSUE TITLE
Donkey Kong (1983)

### ISSUE THREAD

**Issue by dreamer** [dosbox-staging/dosbox-staging#909]
**Describe the bug**
Original report here: https://www.reddit.com/r/dosbox/comments/lovzb0/is_it_possible_to_achieve_the_correct_picture_in/
user's original issue was resolved by turning on CGA composite emulation, but I think this game has enough issues to warrant a bug report and improvements are necessary.

Problems:

Here's the recording of the game on real hardware: https://www.youtube.com/watch?v=P4V0y7aaTnA&feature=youtu.be - and here are few screenshots I made: https://imgur.com/a/WpbMvUt

- Recording from hardware seems to be much sharper than CGA composite would be (?) - also - did IBM XT CGA monitor actually had Composite mode? Or do we need to improve Composite emulation?
- User reported the sound issue (*I cannot reproduce it - for me PC speaker sounds are emulated OK*)
- The emulation runs waaaay too fast! Even with 200 cycles and normal core it seems to be too fast… We need to pinpoint timings for really old hardware better - or maybe design some special mode to have exact timings for games from 1980-~1984 era.
- We probably should introduce a mode to start in CGA/composite the same way we allow to start in CGA/mono.

**Comment by kcgen** [comment]
Let's retest this with reengine's newer composite-mode.

**Comment by Jkapp76** [comment]
I just played through the game in CGA composite mode. (alpha 410 version)
I tried PCJr machine and the man fell through the floor at the top level and then the graphics messed up. But CGA composite mode worked.

I had no sound, but didn't have enough time to change up the sound settings. I thought it should have had sound with current settings. I'm sure this game should have sound.

**Comment by Jkapp76** [comment]
This game looks best with Tandy1000 machine using the new Composite CGA graphics. Best colors overall and gameplay is great.

![boot_000](https://user-images.githubusercontent.com/89743985/134229300-d765c9ac-219b-4302-a270-ec451208e4dc.png)

**Comment by kcgen** [comment]
This is really nice to hear and I'm positive the developers of the composite could would be happy - NewRisingSun and reengine, from the vogons.org forums.  The best I can do is be a good steward of their excellent code.

Feel free to run the very latest build too - it has some improvements and regression fixes in a couple areas too.
<https://dosbox-staging.github.io/downloads/devel/>

As for adjusting CGA (non-composite) colors: there are some color palette arrays, and likely we can fine-tune them.

**Comment by Burrito78** [comment]
@Jkapp76 Can you test Donkey Kong again with newest development build please and report back?

**Comment by Jkapp76** [comment]
Yes. I'll be happy to test soon.

**Comment by kcgen** [comment]
Thanks @Jkapp76.

Looks OK so far. I'm using:

```ini
[sdl]
windowresolution = small
output = opengl

[dosbox]
machine = cga

[render]
glshader = crt/aperture.vga-retina

[cpu]
cycles = 300

[speaker]
pcspeaker = impulse
```

https://github.com/dosbox-staging/dosbox-staging/assets/1557255/d52ce006-5529-4d4e-af17-263802e842de

![dk_000](https://github.com/dosbox-staging/dosbox-staging/assets/1557255/175f7729-2f3e-4caf-9097-5830cf353bbf)

Maybe a custom `pcspeaker_filter` could make it sounds a bit more muffled and "lofi" :-)

**Comment by Jkapp76** [comment]
I'm not sure what I'm looking for, but the game seems to work fine. The sound has always been rough, but not too bad. The graphics all look great.

![boot_000](https://github.com/dosbox-staging/dosbox-staging/assets/89743985/b2104cf3-7ecc-484c-9ef1-6c5db04b5b6c)
![boot_002](https://github.com/dosbox-staging/dosbox-staging/assets/89743985/5c7cdbd3-e0dc-43f5-95cc-cd4b695b42b9)
![boot_007](https://github.com/dosbox-staging/dosbox-staging/assets/89743985/f5e6f904-46b4-4c55-9cb9-b808a004eff6)

**Comment by Burrito78** [comment]
Thanks for your feedback @kcgen and @Jkapp76, closing this as completed.
