### ISSUE TITLE
Dosbox should stop midi output on exit.

### ISSUE THREAD

**Issue by BPaden** [dosbox-staging/dosbox-staging#913]
**Describe the bug**
If the user is using the system synth (or at least alsa) and closes dosbox rather than cleanly exiting the game, whatever notes were playing will play indefinitely.

**To Reproduce**
If DOSBOX is using the system synth, hit alt+f4 to close it.

**Expected behaviour**
I have a script that uses [mido](https://github.com/mido/mido) to reset everything, but it's probably not reasonably to expect every user to be able to do that. I think turning off the notes should be part of the cleanup and shutdown behavior of dosbox.

Grepping around the mido source, it looks like you do this by sending the all notes off and reset all controllers message to every channel. A google search points to that translating to "00 B(0-F) 7B 00" and "00 B(0-F) 79 00" in midi's native language.

Actually just the first one works fine in a test I did with amidi, but mido sends both so that's probably the correct thing to do for whatever reason I don't understand.

**Environment (please complete the following information):**
Arch Linux with alsa.

**Version of dosbox-staging:**

0.77.0-alpha-566-g761cb2db

Though this has been an issue since the beginning of time afaik

**Configuration parameters:**
[midi]
mididevice = alsa
midiconfig = 130:0
mpu401     = intelligent

**Comment by kcgen** [comment]
Brilliant @BPaden!  

This has also happened to me every now, also going back to my early years w/ DOSBox.  

Thanks for finding the exact sysex sequence to get the job done.   I'll drop in the equvalent, and we'll see if it takes care of it!

``` python
def reset_messages():
    """Yield "All Notes Off" and "Reset All Controllers" for all channels"""
    ALL_NOTES_OFF = 123
    RESET_ALL_CONTROLLERS = 121
    for channel in range(16):
        for control in [ALL_NOTES_OFF, RESET_ALL_CONTROLLERS]:
            yield Message('control_change', channel=channel, control=control)
```

(PS - If this works, we can pass along the small patch upstream too).

**Comment by dreamer** [comment]
Ahh, I totally forgot about this bug - thanks @BPaden!

This bug was one of motivators for me to start dosbox-staging project! https://github.com/dreamer/boxtron/issues/21

**Comment by kcgen** [comment]
@BPaden , does https://github.com/dosbox-staging/dosbox-staging/pull/914 (branch ` kc/stop-midi-1`) close MIDI playback for you?

**Comment by BPaden** [comment]
You made quick work of that, @kcgen! Yep it's working for me.

**Comment by kcgen** [comment]
Thanks for the verification test, @BPaden !

**Comment by AaronBPaden** [comment]
Heads up, I just noticed this regressed. Bisect points to d8934f378fd5e891bceb643277e02d1819d7bd46

**Comment by kcgen** [comment]
> Heads up, I just noticed this regressed. Bisect points to [d8934f3](https://github.com/dosbox-staging/dosbox-staging/commit/d8934f378fd5e891bceb643277e02d1819d7bd46)

Thanks @AaronBPaden!

When you have a change, can you try branch `kc/fix-midi-regression-1` (or PR: https://github.com/dosbox-staging/dosbox-staging/pull/1362).

**Comment by AaronBPaden** [comment]
Yup, that works for me

**Comment by kcgen** [comment]
Thanks for bisecting and the quick test!  
That's some first issue reporting -- thanks again @AaronBPaden.
