### ISSUE TITLE
Add per axis scaling

### ISSUE THREAD

**Issue by setiawanj** [dosbox-staging/dosbox-staging#915]
**Is your feature request related to a problem? Please describe.**
I'm using a 15KHz CRT monitor with a Raspberry Pi 4 B. Given the specifics of my system/display configuration, the lowest resolution that I can display 'properly' is 640x200. When I play most DOS games in this configuration, the picture takes up only the left half of the screen, squished.

**Describe the solution you'd like**
If Dosbox could be configured to scale the output horizontally at 200%, in combination with my monitor stretching the 640x240 signal to 4:3 ratio, this should effectively display a 'correct' picture. What I imagine this would look like in terms of configurable settings would be two settings (one for horizontal scaling and one for vertical scaling), that would take either a pixel value to scale to (this would probably also benefit from an additional setting for preferred scaling algorithm), or an integer multiplier (nearest neighbour). E.g.:

```
# Scale the image to fit 640px wide and 200px high
scalehorizontal=640
scalevertical=200
```

or
```
# Scale the image horizontally 2x and vertically 1x (no vertical scaling)
scalehorizontal=2
scalevertical=1
```

**Describe alternatives you've considered**
It doesn't look like any combination of Dosbox configurations (that I've tried at least) will do what I'm looking to do. Ideally I would be able to output 320x240 to my monitor, but under my current setup it looks like that may not be possible (and not for a lack of trying).

**Additional context**
[Further details about my display configuration](https://www.reddit.com/r/dosbox/comments/lr9kx9/can_you_scale_along_only_one_axis/)

Photos of the monitor displaying 320x200 games at 640x200. Some overscan and underscan to be adjusted on the monitor, but it should get the idea across:
[Photo 1](https://i.imgur.com/dyKHr0C.jpg)
[Photo 2](https://i.imgur.com/1hG2Zde.jpg)

**Comment by setiawanj** [comment]
If this does come to pass, it might also be worth adding settings for offsetting in x and y directions. For example, if someone chooses to scale to a lower height than the screen's output resolution, a y offset could be used to center the image (it could perhaps also accept a value 'center', that will automatically calculate the offset to center it, given the scaled height and the screen resolution height).

**Comment by kcgen** [comment]
I think this is best accomplished with a stretching shader, as this would work for any source video mode too. I would assume a 2x horizontal stretcher would be a pretty simple shader, and would be portable to all DOSBoxes. @tyrells, is this something you could help with?

**Comment by tyrells** [comment]
@setiawanj can you try the `pixel_perfect.glsl` shader from https://github.com/tyrells/dosbox-svn-shaders and post a photo of what that looks like? Instructions are provided in the repo, and you should be able to confirm that the correct shader is being loaded in the DOSBox Status Window.

**Comment by Burrito78** [comment]
@kcgen I think this will come with the demise of PP, right?

**Comment by johnnovak** [comment]
> @kcgen I think this will come with the demise of PP, right?

No we don't allow _arbitrary_ scaling per each axis, probably never will. The 2x horizontal stretch shader seems to be a viable workaround (if someone writes that).

Closing, very niche feature and would only complicate things.
