### ISSUE TITLE
688 Attack Sub modem connection

### ISSUE THREAD

**Issue by emanuelepulcidoria** [dosbox-staging/dosbox-staging#916]
Hi All,

I have done some work in the past with @rderooy and @kcgen on both dosbox-x and dosbox-staging on this topic.

Summary of the issue up to July 2020 was that for the multiplayer mode the modem connection is working thanks to the phonebook feature but the nullmodem connection is not working. The question here is still focused on the modem connection though. 
Links to the work completed are the following:
https://github.com/joncampbell123/dosbox-x/issues/1668
https://github.com/dosbox-staging/dosbox-staging/issues/486
As mentioned few times in the past even if the modem connection works the initial process to create the connection is temprimental: sometimes works, sometimes does not work repeating exactly the same process.
When the connection is created on the same machine between 2 instances of Dosbox-staging through 127.0.0.1 it works 9 times out of 10 but when 2 people try to create the connection through the web using the router IP address the connection works rarely: 1 time out of 5 in the best case scenario or never in the worst case scenario.
Trying this with friends we noticed that the reliability of the initial connection process is strongly improved setting:
priority          = normal,normal 
instead of the default setting
priority          = higher,normal
In cases where it was actually impossible to create the connection with the default setting it is now possible to create a connection 1 out of 3 times.
Can someone explain why this is the case and potentially understand why this connection tends to be so temprimental?

**Comment by kcgen** [comment]
One notable difference between DOSBox and a physical modem is that a physical modem is capable of sending and receiving data asynchronously in the strongest sense of the word  For example, the analog pattern for an inbound byte could be received within .000001 nanoseconds of your modem also modulating an analog signal to send a byte. 

The modem used physical analog (de)modulators attached to two hardware FIFOs (tx-fifo, tx-fifo) on the sending and receiving sides, behind which the digital side could comfortably read and write digital bytes to and from the FIFOs.

DOSBox's sending and receiving code is not multithreaded and therefore true asynchronous behavior can't be emulated.  It can alternative between sending or receiving in 1-millisecond time increments, and never simultaneously.

We're making progress on a thread-safe datastructure that would allow it's use in place of the FIFOs. It would allow the sending and receiving sides to operate asynchronously, without any mandatory timing between those two flows, and permitting receiving and sending not bound to the 1ms timer. (Instead, the FIFOs' mutexs would unlock the moment a byte is received or ready for sending). 

That's would be a generic improvement. However, if there is something broken in the actual handing or sending of the data - then that's a separate issue, and we could try to look at the difference between the nullmodem vs softmodem and why one works and the other is unreliable.

**Comment by emanuelepulcidoria** [comment]
Ok, understood a bit better the difference between a real modem and the emulated one in Dosbox. But how the priority setting plays a role in whole this?

**Comment by kcgen** [comment]
The priority settings affects the balance of fairness and timeliness your operating system grants to DOSBox versus your other processes running.  

So for example, a higher-priority task will be granted more CPU cycles than a low-priority task if both are attempting to perform the same amount of work.

It's also possible that higher priority tasks are made less latent, timing wise, when they interact with device drivers - like video, audio, network, and so on.  However, that's more a function of your operating system.

What could be happening when set to a higher priority, is that some expected event is actually occuring before 688 can achieve some other prior state, which it would normally be able to achieve on a real circa late 80s machine and 2400 baud modem physical modem.

**Comment by emanuelepulcidoria** [comment]
Thanks @kcgen, this could explain the role of the priority setting but it sounds against the fact that the connection works so much more reliably when connecting 2 instances on the same machine under 127.0.0.1...

**Comment by emanuelepulcidoria** [comment]
Anyway I will close this one out, it was just to let you know that for this temprimental connection the priority settings can play an important role on some Windows machines.

**Comment by kcgen** [comment]
@emanuelepulcidoria , I'd like to keep this open.

Your report indicates that something might not be quite right in the serial port-related code, and 688 may be able to act a test case for it - give 90% of the time its connection will fail.

The alternative is 688 itself is buggy. To answer that, we need to know if 688 can reliably establish a connection running on two real hardware machines connected via nullmodem link. do you know, or can find retro videos showing this?

**Comment by emanuelepulcidoria** [comment]
@kcgen , If you remeber what was discussed in #486 we found out that probably 688 works with an old type nullmodem cable not supported in Dosbox. There are evidence of people talking about this type of connection working at the time, I do not know with what level of reliability:
https://www.vogons.org/viewtopic.php?f=31&t=15454&p=107674#p107674
But why are you interested in the nullmodem cable connection when I am discussing the modem connection?

**Comment by kcgen** [comment]
> why are you interested in the nullmodem cable connection when I am discussing the modem connection?

I was going on your wording: "**_the modem connection is working_** thanks to the phonebook feature **_but the nullmodem connection is not_** working."

Sorry if I misunderstood @emanuelepulcidoria. 

> There are evidence of people talking about this type of connection working at the time, I do not know with what level of reliability: https://www.vogons.org/viewtopic.php?f=31&t=15454&p=107674#p107674

Thanks for that link. Ut's a good sign that we can (hopefully) use 688 as a correctness indicator.

To really tackle this though, I think we need some kind of "serial-port line tester" application that runs on both sides of the connection.  The tester steadily steps through all the the legal characters, then timings/baud-rates, and any other notable patterns or corner cases. 

A tool like would immediately flag the problematic areas, and would also be a big help in fixing them - and additionally ensure that new regressions aren't introduced.

If anyone out there knows of a DOS tool that does such a thing (or can write one), please drop a note!

**Comment by kcgen** [comment]
Suggested by @granminigun: https://github.com/zpl-c/enet

**Comment by emanuelepulcidoria** [comment]
Thanks @kcgen for trying to find a solution for the nullmodem connection problem that never works. I honestly had no hope that this could have been fixed without rewriting the code around the nullmodem connection to incorporate older types of nullmodem cables with different number of pins compared to the one modelled in Dosbox now.
But what I was trying to say here is purely around the MODEM connection and how it could be very temprimental on some machines mainly if the priority is set to priority = higher,normal, while if it set to priority = normal,normal the MODEM connection is still temprimental but works much more often than with the priority settings at priority = higher,normal.
Hope I have been clearer this time

**Comment by Burrito78** [comment]
@kcgen Pretty old ticket, should it stay open?

**Comment by kcgen** [comment]
Yes, with the addition of Enet (and the fact it was working at least OK in local testing) - I think we should close it.

If someone finds this ticket in the future, please retry with DOSBox Staging's Enet support (which guarantees correct data stream order) and ensure both sides are running the game in high-priority (or using `gamemoderun` on Linux), as @emanuelepulcidoria suggestions.
