### ISSUE TITLE
I can't use AUTOTYPE command for skipping game intro and logos

### ISSUE THREAD

**Issue by maxigaz** [dosbox-staging/dosbox-staging#940]
**Describe the bug**
I've been trying to use `AUTOTYPE` for skipping the intro and logos in various games, namely Astérix & Obélix, Conspiracy (aka KGB), and Crusader: No Remorse, by simulating pressing ENTER several times in a row. Out of these three games, I could partially make it work in Astérix & Obelix only (only four key presses seem to be simulated instead of five).

**To Reproduce**
Run `dosbox -conf dosbox-staging.conf`. (I created three local instances of `dosbox-staging.conf` with an `[autexec]` section for each game, placed in their respective folders. See their contents below.)

**Expected behaviour**
All intro sequences and logos are skipped.

**Environment (please complete the following information):**
- Manjaro Linux x86-64
- Relevant hardware info: Dual Core Intel Celeron G1610, Radeon HD 6670 with Mesa 20.3.4, 4 GB of RAM

**Version of dosbox-staging:**
v0.76.0

**Configuration parameters:**
<details>
<summary>Asterix config</summary>
<p>

```
[sdl]
output=opengl
fullresolution=desktop
fullscreen=true
windowresolution=1600x1000
mapperfile=~/.config/dosbox/mapper-0.75.sdl2.map
raw_mouse_input = true
priority = higher,pause

[dosbox]
memsize=32

[cpu]
cycles=25000

[render]
aspect=true
scaler=none

[gus]
gus = true
ultradir = c:\ultrasnd

[autoexec]
mount C "/media/kis/Games/DOS-games/" -t dir
C:
cd ASTERIX
autotype -w 3 -p 3 enter enter enter enter enter
obelix.exe
exit
```
</p>
</details>

<details>
<summary>Conspiracy config</summary>
<p>

```conf
[sdl]
output=opengl
fullresolution=desktop
fullscreen=true
windowresolution=1600x1000
raw_mouse_input = true
priority = higher,pause

[dosbox]
memsize=32

[cpu]
cycles=26800

[render]
aspect=true
scaler=none

[autoexec]
mount C "/media/kis/Games/DOS-games/" -t dir
imgmount D "/media/kis/Games/DOS-games/CONSPIRACY.iso" -t iso
C:
cd CONSPCD
autotype -w 3 -p 3 enter enter enter enter enter enter enter enter enter enter
call CONSP.BAT
exit
```
</p>
</details>

**Additional context**
I mentioned above that I managed to partially make it work in Astérix & Obélix. That was after *a lot* of trial and error in the command prompt, typing the commands manually. In that case, the sound card was set to Gravis Ultrasound in the game’s `INSTALL.EXE` (so the loading time was much longer) and I also changed the number of CPU cycles with CTRL-F12, as well as the values of `-w` and `-p` of `AUTOTYPE`. I don’t remember the details, though.

**Comment by dreamer** [comment]
Weird… I'll try to reproduce it. Pinging @kcgen so he's aware of this problem.

**Comment by kcgen** [comment]
Thanks @maxigaz.

Yes - some subset of games gets input through a different mechanism that doesn't follow the normal SDL route. During their startup, they switch to an alternate input mechanism after which those inbound keystrokes from the autotyper are ignored.

My guess is Astérix & Obelix does that switch-over many seconds after its startup (which allows you to get some keystrokes in, but eventually it switches).

Hopefully someone more knowledgeable about the internals of DOS and interrupts can help.

@Wengier , @joncampbell123  -- do you know what could cause this, and how we might be able to "tap into" their input feeds using SDL and the autotyper? (DOSBox-X also has the autotyper).

**Comment by Wengier** [comment]
@kcgen I have tried the game Astérix & Obelix, and I think the reason that it does not work with the current AUTOTYPE command (shared by DOSBox-X and Staging) is that the game expects a delay (even very small delays) between the key down and up states. So you can try change the following in the sdl_mapper.cpp file:

```
MAPPER_TriggerEvent(event, true);
```

To:

```
event->Active(true);
SDL_Delay(10);
event->Active(false);
```

Tested in both DOSBox-X and DOSBox Staging.

**Comment by maxigaz** [comment]
Thank you for your replies!

@Wengier I have just tried your suggestion in DOSBox Staging (I cloned the git repo and manually changed `sdl_mapper.cpp` before building). Here are my findings so far:

## Astérix & Obelix

Calling the following before `obelix.exe` takes me straight to the main menu.

```
autotype -w 3 -p 7 enter enter enter enter enter
```

If I reduce `-p` to `5` or `6`, the cutscene before the menu is not skipped. (Here, the loading time is the longest compared to previous screen changes.) So, while `-p 7` feels too long for me, it works at least.

## Crusader: No Remorse

The following now works perfectly!

```
autotype -w 4 -p 2 enter enter
CRUSADER.EXE
```

## Conspiracy

This one proved to be the most problematic. At first, the results were only marginally better than last time: instead of skipping 2-3 sequences (logos, cutscenes etc.), now it could skip 4-5—which still wouldn’t take me to the point I could start a new game or load a saved one. Then I thought, “How about simulating `esc` instead of `enter`?” And sure enough, pressing `esc` skips multiple sequences at certain points, which also makes `autotype` more reliable.

So, after more trial and error, I could make it skip all the sequences by using the following:

```
autotype -w 3 -p 5 esc esc esc esc esc esc
call CONSP.BAT
```

Here, just like in Astérix & Obelix, the given value of `-p` feels too long, but if I decrease it to, for example, 4, the last sequence (some narration text) still isn’t skipped. If I use `-p 3`, nothing is skipped.

Another observation is that during the first sequence (which is a full-motion video with the publisher’s logo), I have to wait about 13 seconds before the first keypress is simulated, which is much more than what is set for `-w`. If I use `-w 2` or less, nothing is skipped.

**Comment by grapeli** [comment]
@maxigaz 
For the KGB game (Conspiracy) use the external program [scancode](http://bretjohnson.us/programs/scncd590.zip). With `cycles=26800`,
started like this
```
scancode D2.61 Escape D1.61 Enter D4.44 Enter Enter
call CONSP.BAT
```
will do much better than `autotype`.

**Comment by kcgen** [comment]
Fantastic info here!
Thank you for this solution @Wengier and testing this @maxigaz.
Very handy tool @grapeli!
We should add this to the `autotype` Wiki so users have lots of options to blast-through these initials screens :robot:
 I will get a PR (attributed to you @Wengier later today).

**Comment by maxigaz** [comment]
> @maxigaz
> For the KGB game (Conspiracy) use the external program [scancode](http://bretjohnson.us/programs/scncd590.zip). With `cycles=26800`,
> started like this
> 
> ```
> scancode D2.61 Escape D1.61 Enter D4.44 Enter Enter
> call CONSP.BAT
> ```
> 
> will do much better than `autotype`.

Thank you for the suggestion! I can confirm that it works wonderfully in Conpiracy, even with DOSBox Staging v0.76.0.

**Comment by kcgen** [comment]
PR inbound. Increased the inter-keystroke delay to 50ms and now works nicely w/ KGB as well:

`autotype -w 2.8 -p 0.8 esc , enter , , , enter enter`

50ms is still pretty tight, timing wise - that's 20 keystrokes per second, which is still a bit faster than the round-trip time for Takahashi Meijin's famous 16-presses-per-second :-)

 https://www.youtube.com/watch?v=oJ4lmAFB7d4
