### ISSUE TITLE
Enter "tilde" on german macOS

### ISSUE THREAD

**Issue by Burrito78** [dosbox-staging/dosbox-staging#948]
After "a little bit" of frustration i found out the hotkeys needed to enter the "tilde" symbol in DOSBox-staging with a german Macbook/macOS.
At first i enter "keyb gr" to get a correct keyboard mapping for germany (character z is on my z-key etc.).

After that to enter the tilde symbol i have to press "right alt" + "+".
Without loading "keyb gr" its a different combination that i don't know yet!
To enter tilde in macOS i have to press "alt" + "n" and then "space".

My question is: Is this expected behavior? Will this behavior change soon anyway or does it make sense to edit the wiki accordingly?

Regards,
Burrito78

**Comment by dreamer** [comment]
@Burrito78 Honestly, I'm not sure… on my keyboard I can type tilde simply by pressing `Shift + <tick>` - both for Polish and English layouts. 

When using German layout (`keyb de` in dosbox-staging), the tilde can by typed in by pressing `Right Alt + ]` - which is the same shortcut as for default German layout on Linux… Does it work for you? Arguably, I am testing this on Linux, so there might be a difference compared to Apple keyboard…

**Comment by Burrito78** [comment]
Hi @dreamer! Sorry for the late reply! 

Without `keyb gr` i too can type tilde easily using `Shift + ^`.

The Macbook Pro doesn't have keys with the `[`and `]` characters. In macOS itself `[`and `]` are entered by pressing `Alt + 5`and `Alt + 6`.

So on a german Macbook Pro i have to type `Right Alt + *` to enter tilde in Dosbox. This might be no bug and expected but maybe should be documented because it's very weird.

Best regards,
Burrito78

**Comment by adriangligor** [comment]
On my setup (`keyb gr` and german Apple keyboard), pressing `Option + *` does the trick.

**Comment by Burrito78** [comment]
In addition what is meant by "Right Alt". This is the key text on german apple keyboards. The key is usually called "Option" on Apple systems.

**Comment by adriangligor** [comment]
To me it looks like the keyboard mapping on MacOS is influenced by the german layout for PC keyboards. See: https://en.wikipedia.org/wiki/German_keyboard_layout .

"~" is located on the "+" button and can be typed in via "AltGr - +". On Apple keyboards this translates into "Right Option - +". The behaviour is similar for "\" (backspace), braces and brackets. I never thought about it, but it feels quite natural this way even typing on my german Mac keyboard. My muscle memory built up back in the day still works.

MacOS recognises PC and Apple keyboard layouts and treats them differently. So does Linux. I think it can be reasonably expected for DosBox to support different mappings based on the physical keyboard layout.
