### ISSUE TITLE
Output set to any opengl results in blank screen

### ISSUE THREAD

**Issue by ozatomic** [dosbox-staging/dosbox-staging#950]
**Describe the bug**
When the output mode is set to any of the opengl modes when the screen changes it throws an opengl error.
Enabling debug with `DB_OPENGL_ERROR` throws the following errors.

```
errors from End of setsize
502
502
502
502
502
```

`GL_INVALID_OPERATION, 0x0502`

Have been working with krc via discord to debug the issue

**To Reproduce**
***Method 1***
- Set `output           = opengl`
- Load application
- Application shows splash screen
- Blank window after splash screen
- Console is actually there but the screen is blank as you can type `exit` and it will close

***Method 2***
- Set `output           = opengl`
- Set `startup_verbosity = quiet`
- Load application
- Application shows the `z:` prompt
- Attempt to load a game results in blank screen

***Method 3***
- Set `output           = texture` and `texture_renderer = direct3d11`
- Load application
- Application shows splash screen
- Splash screen doesn't disapear
- Can type exit like prompt is actually there and application closes.

**Expected behaviour**
***Method 1***
Would expect the prompt to be displayed and visible
***Method 2***
The game application being loaded should be visible 
***Method 3***
Would expect the prompt to be displayed and visible

**Environment (please complete the following information):**
- Windows 10 Enterprise 64-Bit (10.0, Build 19041)
- i7-9700k
- RTX 2080 Super
- Resolution: 3x 2560x1440 (tried switching to sinlge monitor as well)

**Version of dosbox-staging:**
git

**Configuration parameters:**
Default with output changed

**Extra Information**
- Also tried uninstall video drivers (with DDU) and re installing fresh

**Comment by kcgen** [comment]
@ozatomic , 

A very similar issue involving full drop-out of SDL's accelerated backend (this time on macOS) has appeared in #952.

@dreamer's added even more OpenGL debugging output under branch: `po/opengl-investigation-2`.

When you have a chance to build and test, it would be much appreciated!

**Comment by ozatomic** [comment]
@kcgen,

Good to see im not the only one. I haved taken the debug output and placed in a pastebin for you https://pastebin.com/ZeY27qYW 

Config Below I put verbosity back onto high as it has the same affect as when loading a game.

```
[sdl]
fullscreen       = false
display          = 0
fullresolution   = 1024x768
windowresolution = 1024x768
output           = openglpp
texture_renderer = auto
capture_mouse    = seamless middlerelease
sensitivity      = 100
raw_mouse_input  = false
waitonerror      = true
priority         = higher,normal
mapperfile       = mapper-sdl2-0.77.0.map
screensaver      = auto
[dosbox]
language          = 
machine           = svga_s3
captures          = capture
memsize           = 16
startup_verbosity = high
```

I will be running some linux distros to see if it happens on them as well for my hardware. I tried to make a windows to go USB but it was taking way toooo long to boot. I have a space HDD so on the weekend I may try a Pro/Home windows install.

**Comment by kcgen** [comment]
@dreamer - you're branch revealed:

```
OPENGL: Pixel buffer object (PBO) extension: missing
...
OPENGL: maybe PBO found after all? yup
```

> I will be running some linux distros to see if it happens on them as well for my hardware.
> I have a space HDD so on the weekend I may try a Pro/Home windows install.

Great to hear; and no small feat -- thank you!

This will hold both the hardware and DOSBox Staging constant, while only changing the OS stack and drivers.  It's not often we get to see those side-by-side comparisons. Looking forward to it!

**Comment by ozatomic** [comment]
@kcgen Here are the results from a Ubuntu live CD and it worked fine and was able to load a program

https://pastebin.com/ZsTAA417

**Comment by ozatomic** [comment]
*Update*
After getting another ssd to install `windows 10 pro` to try and isolate the issue. It appears now what opengl and openglpp modes are working great, with no other changes to hardware.

Thanks for the help @kcgen and @dreamer. 

Also if need any other testing I wont be formatting the old ssd so can put back in the system to test if needed.

**Comment by kcgen** [comment]
Closing as it's now working from the last report.
