### ISSUE TITLE
make breakpoint work with different seg:ofs locating the same 32 bit offset

### ISSUE THREAD

**Issue by LowLevelMahn** [dosbox-staging/dosbox-staging#960]
https://www.vogons.org/viewtopic.php?p=336691#p336691

the BP-Command in Debugger does not detect a breakpoint at 
1ED3:0025 if dosbox IP-Register is 1ED5:0005 at that point - seg/seg and ofs/ofs getting compared not
the linear adress (which is same for the above BPs)

> ripsaw8080: 
> Physical breakpoints look for an exact match of the specified segment and offset.

the 2 line patch worked for me that time - i don't know if everything changed since then

the patch wasn't integrated due to protected/real mode switch concerns

> ripsaw8080: 
> I've noticed one drawback with this change to the debugger: breakpoints intended for when the processor is in protected mode won't work if set while the processor is in real mode, and vice versa. Before the change it didn't matter if a segment or a selector was specified. This could be resolved by adding something like BPR (real) and BPP (protected) commands in the debugger that aren't based on the current processor mode, but the BP command and F9 key would still use the current processor mode. Not sure if it's worth the trouble, though.
> 

maybe the world changed or the feature could be integrated with a define or something

**Comment by dreamer** [comment]
@LowLevelMahn thanks for creating this issue and your past investigation :)

As far as I can tell, this should've been merged to SVN in 2014 (considering there was no stable release still)… In Staging, we haven't really started improving the debugger (yet) - I think it's not a big deal to merge this in. Worst case scenario we'll revert it.

@LowLevelMahn please confirm this change is still working on your end - if it works, then I'll simply merge it in. What OS are you going to test it on? I'm asking because debugger should work fine on Linux and macOS with our new buildsystem, but on Windows there are issues on MSYS2.

As for https://www.vogons.org/viewtopic.php?p=346416#p346416
> ripsaw:
> I've noticed one drawback with this change to the debugger: breakpoints intended for when the processor is in protected mode won't work if set while the processor is in real mode, and vice versa. Before the change it didn't matter if a segment or a selector was specified. This could be resolved by adding something like BPR (real) and BPP (protected) commands in the debugger that aren't based on the current processor mode, but the BP command and F9 key would still use the current processor mode. Not sure if it's worth the trouble, though.

Personally I don't think it is a problem during normal debugging session, but I am not experienced in using the debugger feature so am open to feedback.

**Comment by LowLevelMahn** [comment]
> @LowLevelMahn please confirm this change is still working on your end - if it works, then I'll simply merge it in. What OS are you going to test it on? I'm asking because debugger should work fine on Linux and macOS with our new buildsystem, but on Windows there are issues on MSYS2.

on Windows S2017/VS2019, but i can use my playground Ubuntu 20.10 VM if that is better

**Comment by dreamer** [comment]
VS builds should work fine (only MSYS2 build have problem), but it will be troublesome to enable the feature (you need to edit `src/platform/visualc/config.h`, install vcpkg and probably edit the solution file).

On Linux build you only need to:
```
meson setup --buildtype=release -Denable_debugger=normal builddir
ninja -C builddir
```

**Comment by LowLevelMahn** [comment]
> On Linux build you only need to:

i choose linux :)

**Comment by LowLevelMahn** [comment]
error while running meson
```
un-time dependency opusfile found: NO (tried pkgconfig and cmake)
meson.build:163:0: ERROR: Dependency "opusfile" not found, tried pkgconfig and cmake

```

**Comment by kcgen** [comment]
> error while running meson
> 
> ```
> un-time dependency opusfile found: NO (tried pkgconfig and cmake)
> meson.build:163:0: ERROR: Dependency "opusfile" not found, tried pkgconfig and cmake
> ```

https://github.com/dosbox-staging/dosbox-staging/blob/master/README.md#linux-macos

**Comment by LowLevelMahn** [comment]
builds! 

but the debugger behavior is strange under my VMWare/Ubuntu 20.10 / german keyboard layout - sometimes function keys do not work F5 etc. and dosbox uses an english keyboard layout

**Comment by LowLevelMahn** [comment]
skipped the linux build (debugger, keybmapping etc. feels strange) but the VS2019 build just worked out of the box - much better compared to svn-mainline
