### ISSUE TITLE
DIET compression utility doesn't work under dosbox

### ISSUE THREAD

**Issue by kfdf** [dosbox-staging/dosbox-staging#961]
It does uncompress files, but refuses to compress them. Apparently, the issue is not new, I found it first mentioned here: http://pre2.mine.nu/cgi-bin/showmsg.cgi#msg_1232344152 (slow link) However, in this prehistorik 2 related discussion it was mentioned that it works: https://github.com/dosbox-staging/dosbox-staging/issues/407#issuecomment-647073048
The utility seems to be working fine in freedos on virtualbox, but no matter what I do in dosbox, it always responses with "No files to be processed!" Maybe it is possible to tweak some dosbox settings to make it work? 

The utility is available here: http://www.vector.co.jp/soft/dl/dos/util/se000305.html

**Comment by dreamer** [comment]
@kfdf thank you for the report. Can you share how to use `diet` command to compress a file? The program has weird set of switches, and the manual is in japanese - I can't figure out how am I supposed to compress a file. I downloaded version 1.45f.

**Comment by kcgen** [comment]
@kfdf ,

I was able to use `diet` in Staging to investigate Prehistorik's music, in this post: https://github.com/dosbox-staging/dosbox-staging/issues/407#issuecomment-647073048

I was able to extract stuff, modify files, and repack them; and have Prehistorik use them.  I'll see if I have those old work-directories still around and get back to you.

**Comment by LowLevelMahn** [comment]
> The utility seems to be working fine in freedos on virtualbox, but no matter what I do in dosbox, it always responses with "No files to be processed!"

can you attach the binary exact version of DIET you are using (maybe the japanese/englisch versions behave different) and a fixed set of files(or a file) that works under Free/Real-DOS and not under Dosbox - could be subtile detail why it seems to work for kcgen

**Comment by kfdf** [comment]
> @kfdf thank you for the report. Can you share how to use `diet` command to compress a file? The program has weird set of switches, and the manual is in japanese - I can't figure out how am I supposed to compress a file. I downloaded version 1.45f.

`diet <filename>` compresses a file, also you can use wildcards, so `diet *.*` compresses all the files in the directory
`diet -r <filename>` uncompresses file(s)
`diet -l` lists all the files in the folder and highlightes those of them that were compressed

> can you attach the binary exact version of DIET you are using (maybe the japanese/englisch versions behave different) and a fixed set of files(or a file) that works under Free/Real-DOS and not under Dosbox - could be subtile detail why it seems to work for kcgen

I used those versions that I linked. I experimented more now, and it seems that `diet` ignores files that are 2 kb or less in size, as soon the file size hits 2049 bytes it becomes compressible. So it seems that when run in dosbox it thinks that the files are too small.

**Comment by LowLevelMahn** [comment]
the DIET.exe is itself DIET packed - result is 42kb and the error message comes very early - could be easy to find the place in the code where the error and printing of the message occures

**Comment by kcgen** [comment]
Test pack: [diet_tests.tar.gz](https://github.com/dosbox-staging/dosbox-staging/files/6229418/diet_tests.tar.gz)
Extract to a **diet_tests** directory with contents:
```
diet_tests
├── 16kplus1.txt
├── 16k.txt
├── diet.exe
└── original.trk
```

Tests

1. Enter the test directory
    `cd diet_tests`

1. Extract from original archive
    `dosbox -c "mount c ." -c "c:" -c "diet.exe -Oextract1 -R original.trk"`

1. Compress extracted to new archive
    `dosbox -c "mount c ." -c c: -c "diet.exe -Onewpack.trk -D extract1"

1. Compare original and new archives (should be identical)
    `diff -s NEWPACK.TRK original.trk`

1. Extract from the new archive
    `dosbox -c "mount c ." -c "c:" -c "diet.exe -Oextract2 -R newpack.trk"`

1. Compare original and new extracted content (should be identical)
    `diff -s EXTRACT1 EXTRACT2`

1. Try compressing a file 16 kilobytes in size (16384 bytes):
    `dosbox -c "mount c ." -c c: -c "diet.exe -Onewpack.trk -D 16k.txt" `

1. Try compressing a file  one-byte-greater than 16 kilobytes in size (16385 bytes):
    `dosbox -c "mount c ." -c "c:" -c "diet.exe -Onewpack.trk -D 16kplus1.txt"`

My guess is DIET's compression block size if 16 KiB; at least for the initial block.

**Comment by LowLevelMahn** [comment]
what've found so far (using IDA and dosbox debugger):

1. using Heavy Debug Build of (sorry, vanilla dosbox svn)
2. two runs with "debug diet small.txt" and "debug diet big.txt"
both with CPU Log "LOG 10000"
and compared that at when instruction the execution goes different routes
the point of interrest is at unpacked exe-file-offset: 0x43B7

dosbox debugger-line:
`01F0:00004187  ja   00004196 ($+d)   `

if the jump is take to offset 4196h the files gets compressed else the "No files to process" msg comes up

few opcodes before is a call to Turbo/Borland C/Pascal L_DIV (a long div helper)
`01F0:0000417F  call 00006F18 ($+2d96)`

that gets called this way - the JA-Instruction above is the > 1

```
if( ((16384 + filesize-1)/16384) > 1)
{
  compress...
}
else
{
  exit...
}
```

so it seems that files smaller than 16384 getting ignored in my small test, could be that the divider changes with floppy images or the other strange conditions

**Comment by LowLevelMahn** [comment]
@kfdf 
> EDIT: More experimenting. It now seems to work in dosbox if the folder is mounted as a floppy disk. Also, the size threshold then drops to 512 bytes.

can you provide a zip or something with the files and this test-case - like kcgen did using the -c command line of dosbox?

**Comment by LowLevelMahn** [comment]
[fspace.zip](https://github.com/dosbox-staging/dosbox-staging/files/6231823/fspace.zip)

attached is this small Borland C++ 3.1 program (source and exe)
that shows the free space parameter of the default drive

```
#include <stdio.h>

int main()
{
  /*
  INT 21H

  Call with: AH = 36H
  DL = drive code (0 default, 1 = A, etc.)

  Returns: If function successful
  AX = sector per cluster
  BX = number of available cluster
  CX = bytes per sector
  DX = cluster per drive
  
  If function unsuccessful (drive invalid)
  AX = FFFFH  
  */
  
  unsigned int sectors_per_cluster = 0;
  unsigned int number_of_available_cluster = 0;
  unsigned int bytes_per_sector = 0;
  unsigned int cluster_per_drive = 0;

  printf("DOS-func: 36h, using default_driver 0\n");
  asm mov ah,36h
  asm mov dl,0
  asm int 21h

  asm mov [sectors_per_cluster],ax
  asm mov [number_of_available_cluster],bx
  asm mov [bytes_per_sector],cx
  asm mov [cluster_per_drive],dx
  
  if( sectors_per_cluster == 0xffff)
  {
    printf("invalid drive\n");
    return 1;
  }
  
  printf("AX = sectors_per_cluster: %u\n", sectors_per_cluster);
  printf("BX = number_of_available_cluster: %u\n", number_of_available_cluster);
  printf("CX = bytes_per_sector: %u\n", bytes_per_sector);
  printf("DX = cluster_per_drive: %u\n", cluster_per_drive);
  
  return 0;
}
```

my dosbox installation giving me

```
DOS-func: 36h, using default_driver 0
AX = sectors_per_cluster: 32
BX = number_of_available_cluster: 16000
CX = bytes_per_sector: 512
DX = cluster_per_drive: 32765
```

and sectors_per_cluster*bytes_per_sector = 32*512 = 16384

@kfdf 

can you try the fspace.exe with your Free-DOS, real DOS, dosbox floppy image?

**Comment by kfdf** [comment]
```
// dosbox floppy mount
DOS-func: 36h, using default_driver 0
AX = sectors_per_cluster: 1
BX = number_of_available_cluster: 2880
CX = bytes_per_sector: 512
DX = cluster_per_drive: 2880

// dosbox regular mount
DOS-func: 36h, using default_driver 0
AX = sectors_per_cluster: 127
BX = number_of_available_cluster: 4031
CX = bytes_per_sector: 512
DX = cluster_per_drive: 16383

// virtualbox freedos
DOS-func: 36h, using default_driver 0
AX = sectors_per_cluster: 4
BX = number_of_available_cluster: 37769
CX = bytes_per_sector: 512
DX = cluster_per_drive: 51040
```

Well, all numbers seem to match the expectations. So `-t floppy` is the solution, then?

**Comment by LowLevelMahn** [comment]
sadly the "bytes per sector" and "sectors per clusters" are checked a second point in the code - my current patch can only compress filesize >0 and < ~150kb or something

need to fix that too :/

**Comment by dreamer** [comment]
Perhaps instead of patching the binary, we could make sector size configurable during `mount` command. AFAIK when mounting a directory, the sector size is completely dummy information, hardcoded for compatibility. (Of course sector size would not be totally configurable - we can't allow sector size 0 or 1 for example - we would provide only sizes that were actually supported by some hardware).

**Comment by LowLevelMahn** [comment]
i won't  do that - there could be other apps/games that rely on these values - even when there a currently just some values

**Comment by LowLevelMahn** [comment]
btw: the parameter /^ or -^ gives debug output :)

compress
```
operation=0  tmppath=''
options $ Z P W E N S X D K C O J B I A all emsmode
        0 0 0 0 0 0 0 0 0 0 0 0 0 0 0  0    0
<<<< Dr. Teddy's 'DIET' program for files - version 1.45f >>>>
     .... copyright(c) 1992,6/25  by Teddy Matsumoto ....

dietpsp=0192 dietpsz=0B66 heapseg=0CF9 heappsz=9306
tsrflag=0000 pspseg=0000 tsrseg=0000 tsrworkseg=0000
tsroptions=0000 emmflag=0 emmh=0 emmseg=0000

filename='FAIL.BIN'  filesize=031790
filetype=00  dlzflag=00  packsize=000000  packcrc=0000  unpacksize=000000
Compress 'FAIL.BIN' ....................................................
origsize=031790 packsize=01C705 packcrc=9BD9 dlzflag=00
cluster size: 000D to 0008
Success! (202640 to 116502 bytes)

exitcode=0001
```

decompress
```
operation=1  tmppath=''
options $ Z P W E N S X D K C O J B I A all emsmode
        0 0 0 0 0 0 0 0 0 0 0 0 0 0 0  0    0
<<<< Dr. Teddy's 'DIET' program for files - version 1.45f >>>>
     .... copyright(c) 1992,6/25  by Teddy Matsumoto ....

dietpsp=0192 dietpsz=0B66 heapseg=0CF9 heappsz=9306
tsrflag=0000 pspseg=0000 tsrseg=0000 tsrworkseg=0000
tsroptions=0000 emmflag=0 emmh=0 emmseg=0000

filename='FAIL.BIN'  filesize=01C716
filetype=01  dlzflag=00  packsize=01C705  packcrc=9BD9  unpacksize=031790
Retrieve 'FAIL.BIN'
Success! (116502 to 202640 bytes)

exitcode=0001

```

**Comment by kcgen** [comment]
I believe we can close this issue given the thorough analysis by @LowLevelMahn shows the limitation that lead to opening this issue is due to DIET's own internal constraints.   

But I realize this is currently the only point to discuss this - so we can keep it open until everyone's OK with the resolution. 

@LowLevelMahn , your modification changes the `sectors_per_cluster x bytes_per_sector` calculation to `1` in the size threshold check: `((1 + filesize-1)/1 >= 1)`

Perhaps the DIET author realized that the lowest-allocation unit on FAT-filesystems was `bytes_per_sector`.  So it makes no sense to compress a file that's only 512-bytes in size.. given the result (however small it might be), will still effectively consume 512-bytes _worth_ of disk space.

(The concept of storing one or more tiny files inside a single filesystem metadata record, called [sub-allocation](https://en.wikipedia.org/wiki/Block_suballocation) or tail-packing,  hadn't been invented at the time)

Given this - maybe you can relax your modification to retain the original bytes-per-sector values, and only shrink the `sectors-per-cluster` to 1:

`(( bytes-per-sector + filesize-1)/ bytes-per-sector >=  bytes-per-sector)`

This might allow the filesize extents to grow from `filesize >0 to < ~150kb`  to 512-fold greater.

**Comment by LowLevelMahn** [comment]
could be a solution, but i think i just didn't patched the correct place - would be better to override the results of function that calls the DOS-API  for the sector/cluster size etc. i've only patched the part where the information is used

i really hope to fix that later this week

**Comment by dreamer** [comment]
I think we should investigate the solution with adding `--sector-size` parameter to `mount` command, so user could override the value for edge cases like this one.

**Comment by LowLevelMahn** [comment]
also a good idea

**Comment by kcgen** [comment]
Going back through the original posts, I see @kfdf mentioned:

> It now seems to work in dosbox if the folder is mounted as a floppy disk. Also, the size threshold then drops to 512 bytes.

Given 512-bytes is the smallest "quantum" of storage (even on modern filesystems), it makes no sense to compress a file that's already 512 bytes or smaller and it seems @kfdf already has everything needed to carry on using DIET.

Regarding:

> I think we should investigate the solution with adding `--sector-size` parameter to `mount` command, so user could override the value for edge cases like this one.

Besides this DIET corner-case which already has a working solution (ie: `-t floppy`), are there other in-demand uses where a configurable sector-size would be valuable?

**Comment by LowLevelMahn** [comment]
> I think we should investigate the solution with adding `--sector-size` parameter to `mount` command, so user could override the value for edge cases like this one.

without patching DIET,  `--sector-size` would not be enough because its `sectors_per_cluster x bytes_per_sector` so also the sectors_per_cluster are also relevant for the smallest filesize

**Comment by kcgen** [comment]
This turned out to be quite a tangent, and unrelated to gaming or specifically being inscope of Staging's goals. Closing this for now.
