### ISSUE TITLE
Support MT-32 model versions via MAME ROM sets

### ISSUE THREAD

**Issue by kcgen** [dosbox-staging/dosbox-staging#964]
Game musicians sometimes used bugs (or features) in early MT-32 ROM versions to create specific sounds that were changed or removed in later ROM versions. 

Currently, Staging supports unversioned ROMs using a single fixed filename (such as `MT32_CONTROL.ROM` and `MT32_PCM.ROM`), which can be error prone and ambiguous for those who want to use specific versions of ROMs in their games collection. 

@sergm recently added support for interleaved bitwise IC ROM dumps in libmt32emu (to-be-tagged `2.5.0`).  These ROMs are readily available in the consistently-named MAME MT-32 and CM-32L sets, as follows:

| model | supporting ROMs |
| --- | --- |
| mt32_1_04 | mt32_1.0.4.ic26.bin<br>mt32_1.0.4.ic27.bin |
| mt32_1_05 | mt32_1.0.5.ic26.bin<br>mt32_1.0.5.ic27.bin |
| mt32_1_06 | mt32_1.0.6.ic26.bin<br>mt32_1.0.6.ic27.bin |
| mt32_1_07 | mt32_1.0.7.ic26.bin<br>mt32_1.0.7.ic27.bin |
| mt32_bluer | blue_ridge__mt32a.bin<br>blue_ridge__mt32b.bin |
| cm32l_1_00 | lapc-i.v1.0.0.ic3.bin |
| cm32l_1_02 | cm32l_control.rom |

Because each ROM filename is unique and versioned, users will be able to have all their Roland ROMs in a single directory, and then set `model = ` accordingly in the games' conf files.

This issue tracks the work to support these versioned `model`s, in addition to the existing `mt32` and `cm32l` models.  Because we want all OSes supported, this also tracks the tasks to add libmt32emu support under Windows.

**Windows support:**
1. [x] add to vcpkg (upstream)
1. [ ] add to CI nodes (GitHub upstream)
1. [ ] add to Staging [`kc/mt32-for-windows-1`](https://github.com/dosbox-staging/dosbox-staging/tree/)

**Versioned MAME ROM set support:**
1. [x] add to libmt32emu (upstream)
1. [x] tag and release 2.5.0 (upstream)
1. [x] draft support in Staging [` kc/versioned-mt32-2`](https://github.com/dosbox-staging/dosbox-staging/tree/kc/versioned-mt32-1)
1. [x] bump Meson wrap to use 2.5.0
1. [x] bump vcpkg repo to use 2.5.0

**Support MIDI listing:**
1. [x] draft support in Staging [ `kc/midi-list-mt32-1`](https://github.com/dosbox-staging/dosbox-staging/tree/kc/midi-list-mt32-1)

**Comment by dreamer** [comment]
Nice :) can't wait for Munt 2.5.0 release.

**Comment by kcgen** [comment]
>  add to CI nodes (GitHub upstream)

1. Last week, [Microsoft merged](https://github.com/microsoft/vcpkg/pull/16816) `libmt32emu` to vcpkg `master`.

    ![2021-04-02_06-57](https://user-images.githubusercontent.com/1557255/113422014-e4e14e80-9380-11eb-9c04-9cc3b3932517.png)

2. This week, a [CI test run](https://github.com/dosbox-staging/dosbox-staging/runs/2233656041?check_suite_focus=true) git-pulled vcpkg's latest and confirmed `libmt32emu` was part of that. (The CI job went on to build and link Staging with MT-32 support without issues).

    ![2021-04-02_06-49](https://user-images.githubusercontent.com/1557255/113421820-903dd380-9380-11eb-9a82-25791ca20af0.png)

3. Every Sunday GitHub's infrastructure team rolls out their latest VMs (or container images) to the CI nodes, so I'll retry without `git pull` and see if `libmt32emu` made it in.

    I also checked that the CI nodes are using `vcpkg::master` as opposed to vcpkg::last-tagged` -- so that bodes well that we'll see it land soon.

    ![2021-04-02_06-52](https://user-images.githubusercontent.com/1557255/113421794-86b46b80-9380-11eb-9a5b-933dc44a8def.png)

**Comment by kcgen** [comment]
**tag and release 2.5.0 (upstream)**

In progress - https://github.com/munt/munt/issues/44#issuecomment-812587262

**Comment by dreamer** [comment]
Update to 2.5.0 from our POV: #967, https://github.com/mesonbuild/mt32emu/pull/5

**Comment by kcgen** [comment]
Re: **bump vcpkg repo to use 2.5.0**

Request has been submitted to the VCPKG team: https://github.com/microsoft/vcpkg/issues/17069

**Comment by kcgen** [comment]
The vcpkg PR for `libmt32emu` 2.5.0 has passed its review: https://github.com/microsoft/vcpkg/pull/17070

Next up is merging, then we wait for it to the hit the CI nodes.

**Comment by BPaden** [comment]
There were a few minutes of confusion for me after making the transition to the mame set for configs that explicitly set `model`, and I think there's some room for improvement there. At least cm32l and I assume mt32 are exclusive to the old sets. This will break configs. Ideally cm32l would translate to e.g. cm32l_102 in the presence of a mame set and a similar translation should be made for configs with mt32 as the model.

**Comment by kcgen** [comment]
Thanks for testing, @BPaden , and this excellent suggestion.
Will add it shortly.

**Comment by kcgen** [comment]
@BPaden , 
When you have a chance, curious if `kc/midi-list-mt32-1` does what you've suggested.

I've also adjusted the automatic loading sequences (details in [the commit](https://github.com/dosbox-staging/dosbox-staging/commit/3e135f05b009214a123f383b3553446ff4df0b2c))

Thank you for the help!

**Comment by BPaden** [comment]
Tested TES: Arena with `auto` `mt32` and `cm32l` on both the old set and the new set. Everything checks out!
