### ISSUE TITLE
"Try static libs" should include FluidSynth

### ISSUE THREAD

**Issue by Ajaja** [dosbox-staging/dosbox-staging#968]
Could you expand ```try_static_libs``` option to fluidsynth library also, please?
I prefer a static version of fluidsynth and  now I have to add  ```static: true``` each time to ```fluid_dep = dependency('fluidsynth',...)``` in ```meson.build``` to avoid unnecessary dll dependencies.

**Comment by kcgen** [comment]
This makes sense to me. 

If _"try static libs"_ is passed to our build system, then we should build-and-link static libs (whenever possible).

@dreamer , is this possible w/ FluidSynth?

**Comment by dreamer** [comment]
@Ajaja fluidsynth dependency was not included in the list because we provide an option for rebuilding it via Meson wrap dependency - this way it's possible to cut down even more dependencies compared to static lib provided by the repo. Also, I had no idea any repo actually provided static lib for fluidsynth - I presume you're using MSYS2, right?

Anyway - try ddf73bea27c9077ba0ead46bb4795179527c7907 (branch `po/try-static-fluidsynth` and tell us if it works for you :) ).

**Comment by Ajaja** [comment]
@dreamer 
Thanks, I'll try it, I think it will work.
I build static fluidsynth package by myself using default MSYS2 script  ( https://github.com/msys2/MINGW-packages/blob/master/mingw-w64-fluidsynth/PKGBUILD ) but with ```-DBUILD_SHARED_LIBS=OFF```
There are also small fixes to some pkgconfig\*.pc and full set of ```try_static_libs```.  In result dosbox.exe does not depend on any additional *.dll

**Comment by kcgen** [comment]
Thanks for sharing your use case, @Ajaja. Our CI "config heavy" workflow builds with MSYS2, but with FluidSynth disabled. 

Is there a reason you prefer the MSYS2 package over the Meson-provided wrap? Just out of curiosity.

In the context of Staging, the MSY2 package includes support for portaudio and the readline interface, neither of which are used (by Staging). 

In comparison, the Meson wrap builds as-lean-a-library as possible, uses 32-bit floats for audio samples (making your SSE and AVX registers twice as effective), and uses the same release optimization flags used to build the Staging sources.

**Comment by Ajaja** [comment]
> Anyway - try [ddf73be](https://github.com/dosbox-staging/dosbox-staging/commit/ddf73bea27c9077ba0ead46bb4795179527c7907) (branch `po/try-static-fluidsynth`) and tell us if it works for you :).
Yes, it works fine for me.

> Is there a reason you prefer the MSYS2 package over the Meson-provided wrap? Just out of curiosity.
I haven't tried the Meson-provided  wrap yet.  I had been building with pre-build static FluidSynth  before Staging switched to Meson and I just follow this way with Meson.

>In comparison, the Meson wrap builds as-lean-a-library as possible, uses 32-bit floats for audio samples (making your SSE and AVX registers twice as effective), and uses the same release optimization flags used to build the Staging sources.
Interesting. Thank you, I'll try it.

**Comment by kcgen** [comment]
> I had been building with pre-built static FluidSynth before Staging switched to Meson

(Thanks; and makes perfect sense!)

**Comment by dreamer** [comment]
@Ajaja Thanks for the confirmation - I pushed that commit to the master branch :)
