### ISSUE TITLE
date time should be set to UTC, not local time

### ISSUE THREAD

**Issue by expnkx** [dosbox-staging/dosbox-staging#971]
The DOSBox sets its date time to the local date-time of the computer, instead of using the UTC time, leading to incorrect apis return for gettimeofday in DJGPP.

**Comment by dreamer** [comment]
Hmm, @expnkx can you share program that shows the date incorrectly?

To the best of my knowledge, old MS-DOS was picking the date straight from BIOS, and time was calculated based on 16-bit tick counter, that rolled over in roughly 24hours. DOS definitely had no built-in notion feature of changing timezones. Programs that deal with date (e.g. Clock in Windows 3.11) work correctly out of the box in current implementation, and I see no reason to change it.

**Comment by kcgen** [comment]
I think we can close this?

@dreamer explained DOS did not support timezones, and therefore files are given timestamps directly from the BIOS, which itself had no record of timezone: 

![PF-Bios-62xx-Standard-CMOS-Features2](https://user-images.githubusercontent.com/1557255/114420436-2b952c80-9b69-11eb-9d03-5b28ae76903f.png)
![03fig07](https://user-images.githubusercontent.com/1557255/114420437-2c2dc300-9b69-11eb-82bb-496acdf8fdfd.gif)
![BIOS-Main](https://user-images.githubusercontent.com/1557255/114420440-2c2dc300-9b69-11eb-834a-b2da74260548.png)
![2021-04-12_08-31](https://user-images.githubusercontent.com/1557255/114420841-8c246980-9b69-11eb-9ac5-609abceed4ac.png)

DOSBox therefore also reads and writes files using the "local" time as provided by the OS.

We can see this if we create a new file both locally in the operating system:

``` shell`
`touch test`
`stat test`

``` text
  File: test
  Size: 0         	Blocks: 0          IO Block: 4096   regular empty file
Device: 1ah/26d	Inode: 38813       Links: 1
Access: (0644/-rw-r--r--)  Uid: ( 1000)   Gid: ( 1000)
Access: 2021-04-12 08:15:15.873881837 -0700
Modify: 2021-04-12 08:15:15.873881837 -0700
Change: 2021-04-12 08:15:15.873881837 -0700
```

As well as in DOSBox:

``` shell
C:\> echo test > dos_test
```

``` shell
stat DOS_TEST
```

  File: DOS_TEST
  Size: 4         	Blocks: 8          IO Block: 4096   regular file
Device: 1ah/26d	Inode: 38821       Links: 1
Access: (0644/-rw-r--r--)  Uid: ( 1000)   Gid: ( 1000)
Access: 2021-04-12 08:15:39.855821665 -0700
Modify: 2021-04-12 08:15:39.855821665 -0700
Change: 2021-04-12 08:15:39.855821665 -0700
```
