### ISSUE TITLE
dosbox-staging buid on RPi4

### ISSUE THREAD

**Issue by jlopezvil** [dosbox-staging/dosbox-staging#974]
I have tried to compile last version os dosbox-staggin on a pi4 with all updated to last version.

I cant get compile ends ok

I attach the script used (from the wiki) and the log file of the complile.

[dosbox-staging.sh.txt](https://github.com/dosbox-staging/dosbox-staging/files/6300265/dosbox-staging.sh.txt)
[rps_2021-04-12_235939.log.txt](https://github.com/dosbox-staging/dosbox-staging/files/6300266/rps_2021-04-12_235939.log.txt)

**Comment by dreamer** [comment]
Uhm, this script seems a bit outdated:

- it uses old static fluidsynth builder (which is not needed any more)
- does some weird by avoiding static linking of mt32emu (which I think ultimately fails the build? we upgraded mt32emu to 2.5.0, but the script has hardcoded path for 2.4.2 - I think this causing the build to fail)

@jlopezvil by wiki I think you mean RetroPie wiki?

@nemo93 I guess the script needs a small adaptation :)

**Comment by jlopezvil** [comment]
> Uhm, this script seems a bit outdated:
> 
> * it uses old static fluidsynth builder (which is not needed any more)
> * does some weird by avoiding static linking of mt32emu (which I think ultimately fails the build? we upgraded mt32emu to 2.5.0, but the script has hardcoded path for 2.4.2 - I think this causing the build to fail)
> 
> @jlopezvil by wiki I think you mean RetroPie wiki?

Sorry, script is from here, dosbox-staging wiki ...

> @nemo93 I guess the script needs a small adaptation :)

I dont know how code this adaption ... :)

**Comment by dreamer** [comment]
Ah, my ad blocker hid the script content from me on this wiki page - that's why I haven't seen it :)

**Comment by nemo93** [comment]
@jlopezvil @dreamer my bad :-( I forgot to update the script from the wiki. I've made the changes now and you should be able to compile Staging no problem on your Pi4 + Retropie. Just in case you could find a raw version of the script [here](https://raw.githubusercontent.com/RetroPie/RetroPie-Setup/3511d08c283f83873f7a5cbdea6245dd0aaf494e/scriptmodules/emulators/dosbox-staging.sh) as well (right-click to download).

**Note:** this script will compile the `master branch` directly. It's planned to move to a `tag` in the future to stick to a specific version. Also if you're willing to try a specific branch (let's say it's in "**beta**" status) especially optimized for Pi4 then change the line from:

`rp_module_repo="git https://github.com/dosbox-staging/dosbox-staging.git master"`
to 
`rp_module_repo="git https://github.com/dosbox-staging/dosbox-staging.git kc/fps-pacing-1"`

**Comment by jlopezvil** [comment]
Solved. Thanks
