### ISSUE TITLE
[Feature Request] Support IBM PS/1 Audio Card

### ISSUE THREAD

**Issue by trembyle** [dosbox-staging/dosbox-staging#975]
This card includes a clone of the Texas Instruments SN76489 (3 square wave, 1 noise channel) and an 8-bit DAC. There was also a MIDI/joystick port, although no Dosbox features need to be added to support these functions.

There were games that supported this, a large portion of them from Sierra, which mostly just reused the tracks composed for Tandy 3-voice. However, it runs at a higher frequency (11.74% higher) than Tandy's PSSJ. You can listen to a comparison from Prince of Persia here:
http://nerdlypleasures.blogspot.com/2015/10/the-journey-of-pcjrtandy-sound-chip.html

Special versions of Silpheed and Carmen Sandiego came bundled along with a joystick. Here is an incomplete list of games that support this card:
https://www.mobygames.com/attribute/sheet/attributeId,86/

You might also like to see Jon Campbell's "test suite" from when this feature was added to Dosbox-X:
https://github.com/joncampbell123/dosbox-x/issues/200#issuecomment-210897773

**Comment by trembyle** [comment]
Another list of games:
https://github.com/barotto/IBMulator/wiki/List-of-games-with-PS-1-Audio-Card-support

**Comment by kcgen** [comment]
@trembyle , 

When you have a minute, can you test this [Windows 64-bit binary](https://github.com/dosbox-staging/dosbox-staging/suites/2568951134/artifacts/55985009
) with your PS/1 games? 

To turn on the IBM PS/1 Audio card, set `psaudio = true` in your conf's `[speaker]` section.
