### ISSUE TITLE
using more final on virtuals or finalize classes

### ISSUE THREAD

**Issue by LowLevelMahn** [dosbox-staging/dosbox-staging#980]
every virtual that does not get further derived should use final for methods or the whole class

`class CodePageHandler final : public PageHandler {`

to give the compiler more strong hints to reduce vtables (i don't know if dosboxs inlining is good enough so it wont' have a effect)

**Comment by LowLevelMahn** [comment]
no every class can be finalized - only the one that don't get derived, or virtual that don't get overriden later

**Comment by kcgen** [comment]
> no every class can be finalized - only the one that don't get derived, or virtual that don't get overriden later

Right, that's exactly what this code does.  Infact, in cases where a `final` class is later derived, then a compiler error occurs.  If you apply this to the current `master` repo, it will produce a working executable.

**Comment by LowLevelMahn** [comment]
> Can you tell if the resulting binary is improved?

sadly i've got no benchmark for this - i just saw this virtual function in PageHandler::readb that gets nearly call by every byte read

**Comment by kcgen** [comment]
I just read the benefits of `final` here: https://devblogs.microsoft.com/cppblog/the-performance-benefits-of-final-classes/, and indeed it does avoid loading the vtable for each derived call. 

>  i just saw this virtual function in PageHandler::readb that gets nearly call by every byte read

`PageHandler::readb(PhysPt addr)` will hard-exit DOSBox:

``` c++
	E_Exit("No byte handler for read from %d",addr);	
	return 0;
```

Maybe you're seeing calls to its derived child classes? 

``` text
src/cpu/dyn_cache.h:class CodePageHandler : public PageHandler {
src/cpu/paging.cpp:class InitPageHandler : public PageHandler {
src/cpu/paging.cpp:class InitPageUserROHandler : public PageHandler {
src/debug/debug.cpp:class DebugPageHandler : public PageHandler {
src/hardware/memory.cpp:class IllegalPageHandler : public PageHandler {
src/hardware/memory.cpp:class RAMPageHandler : public PageHandler {
src/hardware/vga_memory.cpp:class VGA_UnchainedRead_Handler : public PageHandler {
src/hardware/vga_memory.cpp:class VGA_ChainedEGA_Handler : public PageHandler {
src/hardware/vga_memory.cpp:class VGA_ChainedVGA_Handler : public PageHandler {
src/hardware/vga_memory.cpp:class VGA_TEXT_PageHandler : public PageHandler {
src/hardware/vga_memory.cpp:class VGA_Map_Handler : public PageHandler {
src/hardware/vga_memory.cpp:class VGA_Changes_Handler : public PageHandler {
src/hardware/vga_memory.cpp:class VGA_LFBChanges_Handler : public PageHandler {
src/hardware/vga_memory.cpp:class VGA_LFB_Handler : public PageHandler {
src/hardware/vga_memory.cpp:class VGA_MMIO_Handler : public PageHandler {
src/hardware/vga_memory.cpp:class VGA_TANDY_PageHandler : public PageHandler {
src/hardware/vga_memory.cpp:class VGA_PCJR_Handler : public PageHandler {
src/hardware/vga_memory.cpp:class VGA_HERC_Handler : public PageHandler {
src/hardware/vga_memory.cpp:class VGA_Empty_Handler : public PageHandler {
```

The branch `kc/finalize-dangling-children-1` marks all of the above as final. 

If you try this branch, can you see if these `readb` calls avoid the vtable load for ` PageHandler::readb`?

**Comment by LowLevelMahn** [comment]
I think the best would be building the final branch with assembler listing and comparing that to the non final version, better ideas?

Yes i talked about the derives,
and the PageHandler::readb(PhysPt addr) should be a pure abstract in my opinion

**Comment by kcgen** [comment]
I dumped annotated assembly from both builds using: 

`objdump -S --no-show-raw-insn --disassemble -w -l --no-addresses <binary>`

The `final` version has 243 fewer lines of assembly. 

I've zipped the two sets of here: [staging-asm.tar.gz](https://github.com/dosbox-staging/dosbox-staging/files/6339699/staging-asm.tar.gz).

`tar xvf staging-asm.tar.gz` will give you two files:
 - `dangling.dump`
 - `finalized.dump`

I've cleaned them up by removing hex addresses, to make them as `diff`-able as possible.

I'm hoping you can see what's improved.  I don't know assembly, so I'm not sure what to look for. 

If you can describe what's been removed, then we can put this change forward for PR (as co-authors) :+1:

**Comment by LowLevelMahn** [comment]
243 lines "could" be fewer vtables accesses,  can only read x86 32bit code more or less fluent but i will have a look later

I don't know if objdump disassemble ist just a simple streamline disassembler acting as there was no source code at all, oer if is it same as gcc -S which commands the compiler to put out annotated assembler, could be the the "disassembled" code contains misinterpreted instructions etc.

**Comment by kcgen** [comment]
Yes, it's annotated line-by-line of source code; you see the somewhF mangled class and function names followed by roughly each line of c++ and assembly blocks underneath.

> can only read x86 32bit code more or less fluent

Happy to run x86 builds tomorrow and generate the same output, if you would prefer.

**Comment by LowLevelMahn** [comment]
> Yes, it's annotated line-by-line of source code; you see the somewhat mangled class and function names followed by roughly each line of c++ and assembly blocks underneath.

Perfect

> > can only read x86 32bit code more or less fluent
> 
> Happy to run x86 builds tomorrow and generate the same output, if you would prefer.

Lets see what i get out of it

**Comment by LowLevelMahn** [comment]
i can't unpack your  staging-asm.tar.gz, not under linux nor severals packers under windows

**Comment by kcgen** [comment]
> i can't unpack your staging-asm.tar.gz, not under linux nor severals packers under windows - seems not to be a gz or tar at all

Sorry @LowLevelMahn - it's zstandard compressed (~100 MB -> 2 MiB!), with the extension set to `.gz` to allow the attachment under GitHub.

Modern `tar` versions handle it naively (as a `gz`), however try pushing it through manually:

`zstd -dc ~/Downloads/staging-asm.tar.gz | tar -xv`

**Comment by kcgen** [comment]
I've hit a wall in trying to give you 32-bit assembly. Unfortunately it appears I would have to convert my system (Ubuntu 21.04) to multilib or 32-bit native; and that's a non-trivial undertaking. 

``` text
-debug/meson-logs/meson-log.txt
Build started at 2021-04-20T06:35:43.289620
Main binary: /usr/bin/python3
Build Options: -Dbuildtype=debug -Dc_args=-m32 -Dcpp_args=-m32 -Dc_link_args=-m32 -Dcpp_link_args=-m32 -Ddefault_library=static -Dfluidsynth:enable-floats=true -Dfluidsynth:try-static-deps=true
Python system: Linux
The Meson build system
Version: 0.57.1
Source dir: /home/kcroft/dosbox-staging
Build dir: /home/kcroft/dosbox-staging/build/clang-debug
Build type: native build
Project name: dosbox-staging
Project version: 0.77.0
Sanity testing C compiler: ccache clang -fcolor-diagnostics
Is cross compiler: False.
Sanity check compiler command line: ccache clang -fcolor-diagnostics /usr/src/dosbox-staging/build/clang-debug/meson-private/sanitycheckc.c -o /usr/src/dosbox-staging/build/clang-debug/meson-private/sanitycheckc.exe -m32 -pipe -D_FILE_OFFSET_BITS=64
Sanity check compile stdout:

-----
Sanity check compile stderr:
/usr/bin/ld: cannot find crt1.o: No such file or directory
/usr/bin/ld: cannot find crti.o: No such file or directory
/usr/bin/ld: cannot find crtbegin.o: No such file or directory
/usr/bin/ld: cannot find -lgcc
/usr/bin/ld: cannot find -lgcc_s
/usr/bin/ld: skipping incompatible /usr/lib/x86_64-linux-gnu/libc.so when searching for -lc
/usr/bin/ld: skipping incompatible /usr/lib/x86_64-linux-gnu/libc.a when searching for -lc
/usr/bin/ld: cannot find -lc
/usr/bin/ld: skipping incompatible /usr/lib/x86_64-linux-gnu/libc.so when searching for -lc
/usr/bin/ld: cannot find -lgcc
/usr/bin/ld: cannot find -lgcc_s
/usr/bin/ld: cannot find crtend.o: No such file or directory
/usr/bin/ld: cannot find crtn.o: No such file or directory
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by LowLevelMahn** [comment]
non-finalized: load function-ptr from vtable and call

```
   mov    (%rdi),%rax
   call   *(%rax)

```  
finalized: direct call without using vtable

	`call   <_ZN15CodePageHandler13GetHostReadPtEm>`
  
another thing:

there are many tiny functions that get not inlined

for example

many calls to <_Z10host_readbPKh>

call   <_Z10host_readbPKh>

this is the function

```
<_Z10host_readbPKh>:
_Z10host_readbPKh():
/usr/src/dosbox-staging/build/clang-debug/../../include/mem_host.h:51
{
	push   %rbp
	mov    %rsp,%rbp
	mov    %rdi,-(%rbp)
/usr/src/dosbox-staging/build/clang-debug/../../include/mem_host.h:52
	return *arr;
	mov    -(%rbp),%rax
	movzbl (%rax),%eax
	pop    %rbp
	ret    
	cs nopw (%rax,%rax,1)
	nopl   (%rax,%rax,1) 

```

which is this function in C++

```
// every real memory byte read using this function

constexpr uint8_t host_readb(const uint8_t *arr) noexcept
{
	return *arr;
}
```

i don't understand why this doesn't get inlined

**Comment by LowLevelMahn** [comment]
there are 861 calls to host_readb in the assembler listing 

why is clang trading call performance reduction for these (relevant) lines of asm in the function?

```
mov    -(%rbp),%rax
movzbl (%rax),%eax
```

something is wrong with the inlining - or its a compiler/cache/magic thing that i don't understand :)

**Comment by LowLevelMahn** [comment]
> This should show smarter inline behavior for tiny functions, but perhaps will still have the vtable loads in the baseline/dangling-children version.

what did you changed to get smarter?

and i think LTO could be also a thing for dosbox - if you do not already tried that feature :)

**Comment by LowLevelMahn** [comment]
i see you used clang before - the inlining shouldn't be that bad using clang

**Comment by kcgen** [comment]
Updated package, this time built with gcc 10.3 using release flags (optimization + LTO), however with symbols-included to produce annotated output: [staging-x64-release-asm.tar.zst.gz](https://github.com/dosbox-staging/dosbox-staging/files/6344983/staging-x64-release-asm.tar.zst.gz)

Steps to reproduce:

``` shell
# Configure a release build with symbols but without extra features
meson setup \
     -Dbuildtype=release \
     -Dc_args=-g -Dcpp_args=-g \
     -Db_asneeded=true -Dstrip=false \
     -Db_lto=true --wrap-mode=nofallback \
     -Dunit_tests=disabled -Duse_fluidsynth=false \
     -Duse_sdl2_net=false -Duse_opengl=false \
     -Duse_fluidsynth=false -Duse_mt32emu=false \
     -Duse_png=false -Duse_alsa=false \
     build/gcc-relsyms

# Build
meson compile -C build/gcc-relsyms

# Print annotated assemby
objdump -S --no-show-raw-insn --disassemble \
     -w -l --no-addresses build/gcc-relsyms/dosbox \
      > assembly.dump

# Replace hex addresses between 3 and 8
#  digits in length with `0x###` to reduce differences:
for i in {3..8}; do sed -i "s/\b0x[0-9a-f]\{$i\}\b/0x###/g" *.dump; done

# Strip directory prefix
sed -i "s^$PWD^^g" *.dump

# Compress
tar c *.dump | zstd -v -22 --ultra -T0 > staging-x64-release-asm.tar.zst.gz
```

Here's the overall build profile:

![2021-04-20_08-49](https://user-images.githubusercontent.com/1557255/115428364-2eba9900-a1b7-11eb-89a6-aec25a9717b9.png)

**Comment by kcgen** [comment]
> and i think LTO could be also a thing for dosbox - if you do not already tried that feature :)

Absolutely :-) We've been LTO's since the first release (when using autotools + build-script).

Meson very nicely takes care of this for us, which we enable in all release builds: 

![2021-04-20_08-44](https://user-images.githubusercontent.com/1557255/115428367-2f532f80-a1b7-11eb-8271-0efd8ee8d3ed.png)

https://github.com/dosbox-staging/dosbox-staging/blob/master/.github/workflows/linux.yml#L197

**Comment by LowLevelMahn** [comment]
that build is much better inlined

**Comment by LowLevelMahn** [comment]
both builds are nearly identical - hard to see any difference - but i think the final ist still valid to use and does no harm

**Comment by kcgen** [comment]
https://github.com/dosbox-staging/dosbox-staging/commit/422ddf374850bed82976d2eeebe0f494f7bfadd7

![2021-04-20_10-24](https://user-images.githubusercontent.com/1557255/115438815-b35ee480-a1c2-11eb-9bfc-4f9ede82bcc3.png)
