### ISSUE TITLE
debugger on mac/linux fully broken?

### ISSUE THREAD

**Issue by LowLevelMahn** [dosbox-staging/dosbox-staging#985]
according to:

https://github.com/dosbox-staging/dosbox-staging/pull/983#issue-619379800

from kcgen:

> I made the conscious decide /not/ to include the various ncurses-devel libs on the Linux and macOS side **because we consider the debugger feature fully broken and unusable on those platforms.**

is the debugger on those platforms only broken in staging or also in svn-mainline?

**Comment by kcgen** [comment]
The two problem I know of are:
 - The TUI can get clobbered with non-TUI console output
 - Unable to provide keyboard input into the debugger's TUI

These existed in SVN upstream (the last time I tried it), as well as downstream forks.

**Comment by LowLevelMahn** [comment]
that happend to me while testing the new break point stuff, now im under VS2019 and its just seems to work

thx for the info

a small info section on the front page with this information would help alot

like use the internal debugger

known bugs under linux,windows etc.

**Comment by dreamer** [comment]
AFAIK debugger is broken on all OSes when build is configured as debug, and it rather works when build is configured to release.

However, on Windows sometimes log output is being redirected to a separate file, so maybe it makes debugger work more reliably? (not sure but worth investigating).

Overall I really, really don't like ncurses-based TUI…

**Comment by kcgen** [comment]
Thanks for clarifying this @dreamer - and pointing out the key is to perform a release build to prevent excessive stdout from clobbering the TUI.
