### ISSUE TITLE
Extend imgmount to support directories in place of the BINARY track in cues

### ISSUE THREAD

**Issue by i30817** [dosbox-staging/dosbox-staging#99]
So basically extend both the cue format and imgmount to 'emulate' a cd from files in a dir for the binary track, like mount -t cdrom.

**Why**
It saves some space, because the iso fileformat mandates Error Correction Codes (ECC).

This would also allow the ability to mount multiple host filesystem dirs as cds and 'change' them with the CTRL+F4 mechanism, as well as use cd audio mechanism, that imgmount already has.

As for why this good, it's a very nice way to share files between dos games used in dosbox and engine recreations that need different names or organization for the files, like scummvm or openlara.

By having the files in the host filesystem, you can simply use hardlinks or symlinks to duplicate or rename them elsewhere, and if you have filesystem compression, like squash, they are already deduplicated; which is not the case if the files exist as a iso and a extracted directory; because compression is not that smart.

The alternative if you want to use the data for both cases is either to find or create a nocd for the particular game and use a directory mount (doesn't work if the game has cd audio), use mount -t cdrom (doesn't work if the game has cd audio or multiple cds) or just duplicate files, which can get problematic for large collections.

**How**
Use the code in `mount -t cdrom` that can mount the host dirs, to mount a path as a track in the imgmount code after the cue parser recognizes that path (probably with a extension of the format, for instance 'DIRECTORY' instead of 'BINARY' on the track affected).

**Comment by i30817** [comment]
I opened a bug report with considerably less detail (because i don't expect anything to happen there) on upstream that is basically the same request here https://sourceforge.net/p/dosbox/feature-requests/142/

You can try to upstream this if you end implementing it and say it closes this one.

**Comment by i30817** [comment]
BTW, there is another case where the host and the guest are opaque to eachother that causes problems in sharing data between scummvm and dosbox; windows 95 and up games, where the guest has to put the games into fat16/32 images.

That case has no good solution in the dosbox realm, since the windows filesystem is controlled by the OS, and no one did a windows 95 to host bridge filesystem driver; for good reasons.

**Comment by dreamer** [comment]
I don't think I've ever seen a game that definitely *needed* to be stored in fat16/32 image to work… Do you mean a situation when Windows 95 is running inside DOSBox and a game is started inside it? Personally, I would prefer to use Wine for such situations… but I haven't tried running Window 95 inside dosbox yet (I plan to investigate it when importing relevant patches from ECE).

**Comment by i30817** [comment]
>  Do you mean a situation when Windows 95 is running inside DOSBox and a game is started inside it

Yes



> Personally, I would prefer to use Wine for such situations

I do, except for a certain era of games (where the games are logically related to their prequels or era, things like Discworld Noir - which doesn't work on wine too), or when i want the game to be portable to ARM, to play on a raspberry pi 4 for instance.

**Comment by i30817** [comment]
Also needless to say, the copy on write drive works much much better if the game you're playing is on host filesystem like normal DOS games. In the case where the (often large, the largest game i have doing this is `Black Dahlia` which is 8 gb) game is on a FAT hdd image, the copy-on-write is of the whole hdd image...

**Comment by krcroft** [comment]
@i30817, very cool! I've done something very similar for my rpi3+ DOSBox collection: custom kernel w/ squashfs + zstd and overlay FS.  Each game is squashfs'd plus a writable overlay mount.  ISOs are part of the squash (usually compress nicely) while the Opus audio tracks ride alongside in a subdirectory.  

It makes for a very tidy host layout, having a one directory per game with a config file, squash file, subdir of writes, and optionally a subdir with audio tracks.

One of the challenges I noticed was in dealing with games that sloppily open every file 'rw' even if they never write to it; such has huge .dat files and such.  In this case, overlayFS saves a copy of these files simply based on the 'rw' open flag (cluttering the 'writes' directory and wasting space); so I have a patch for DOSBox that tolerates read-only permissions on host files and only throws and error if the game actually attempts to write to the file.  

This lets me write-protect almost every file except for the handful of config/savegame/high score files.  Itnwas pretty tedious though working through each game.

Great suggestion to allow a "Directory" type in the CUE file for all the reasons you mentioned.

**Comment by i30817** [comment]
> One of the challenges I noticed was in dealing with games that sloppily open every file 'rw' even if they never write to it; such as huge .dat files and such. In this case, overlayFS

I didn't end up using overlayfs, from what i remember because it needs root, which unionfs-fuse didn't. 
FUSE is the only linux framework that didn't put itself in my way with a 'password required please'. It kind of turned me off from using the kernel stuff.

I don't think unionfs-fuse (which is what i used) has that problem of 'every file opened r+w is copied' or at least i didn't notice that on the few i tried (I spent more time thinking about the config than actually replaying, getting old).

**Comment by dreamer** [comment]
@i30817 so many good ideas in this thread, thanks for sharing :) Me and @krcroft discussed some ideas about implementing ROM-like files for DOS game distribution (I think at some point we'll need to distill those thoughts into an RFC document and start test implementations to see what works).

Regarding FAT32 filesystem corruption - I would need to investigate more, but I wonder if properly integrating patches with long filenames support would solve large chunk of issues…

> though dosbox not treating / and \ the same on conf files host paths already does that (something that shouldn't happen imo).

I agree! I solved this problem once already in [Boxtron](https://github.com/dreamer/boxtron/) and intend to port my solution to dosbox-staging; I talked about this with upstream maintainers once already, and they blatantly refused to fix it.

**Comment by i30817** [comment]
> I agree! I solved this problem once already in Boxtron and intend to port my solution to dosbox-staging; I talked about this with upstream maintainers once already, and they blatantly refused to fix it.

It's just stupid... the *only* thing that makes conf files habitually non-portable (if you use relative paths) is that.

**Comment by dreamer** [comment]
For cross-platform .conf files I created #102 - discussion about this topic let's move there.

**Comment by dreamer** [comment]
Seems relevant to our discussion here: https://www.vogons.org/viewtopic.php?f=41&t=34642

**Comment by BPaden** [comment]
@i30817 
> It's actually quite a lot of trouble to run a dosbox win95 setup, trouble which i'd prefer not to do and just use wine always, especially because of file corruption of FAT or the trouble of making and mounting raw hdd images.

This is probably obvious, but have you tried a more general purpose pc emulator like pcem for this? Once you get into having to deal with drivers and hdd images, a lot of the advantages of dosbox get thrown out. I don't think Windows 9x ever worked well on dosbox. I seem remember having to do at least some of the installation on dosbox-x because dosbox just didn't emulate enough of the hardware to get through it?

There are definitely reasons to use an emulator over wine for this era of games. Some of them use ddraw in weird ways that aren't supported in wine, for example. Some distros might disable 16-bit support, as well, for whatever security reasons.

**Comment by i30817** [comment]
> Seems relevant to our discussion here: https://www.vogons.org/viewtopic.php?f=41&t=34642

This patch (and it's 2 alternatives, including the 'very simple one') are currently broken in upstream.

> This is probably obvious, but have you tried a more general purpose pc emulator like pcem for this? 

I don't like the complexity of pcem, so no i didn't. I wanted a 'run the game automatically' and challenged myself to make it happen in dosbox. I did, though there are definitely problems (like upstream refusing to extend images to > 2 gb for no reason but stubbornness to increase some variables from 16 bits).

**Comment by krcroft** [comment]
Quick brain dump after looking through the code.  

- **directories** are handled by the `cdromDrive` class, which adds some thin file IO functions and dummy MSCDEX audio functions around the `localDrive` class, which is a simple pass-through to the local filesystem (allowing the DOS-side to read and write files on the host-side). 
- **images/ISOs/CUEs** are handled by the `IsioImage` and `CDROM_Image` classes, which operate on sectors, frames,  and provide genuine MSCDEX audio functions that tie into raw binary data (if cue+img) or to audio decode rountines (if cue+iso+oggs/flac/opus). 

Also, only the iso_image class actually performs the cue parsing.

So to fluidly handle either a directory or an ISO file as the 'data portion' (first track) of a CD mount, followed by zero or more audio tracks, will require these two deeply divided class trees be refactored. 

First, their data handling needs to be split off from their MSCDEX audio handling (which right now are entangled). 
This way, bonafide audio tracks can be freely added to either the cdromdrive or isoimage classes, both of which will then only handle their data portion.

Finally, the cue handling needs to be lifted out of the isoimage class and moved earlier in the `imgmount` call tree, so it can determine how to construct the necessary object (dir or iso? fake-mscdex or real audio mscdex?)

**Comment by i30817** [comment]
As a question of 'separation of concerns', should this interface be user accessible only from 'imgmount' for cues or with yet another mounting mode for cds in 'mount'?

My bet with this is that you want to use imgmount, but then there is that extra command mount has that imgmount doesn't because it doesn't need it (-label).

**Comment by dreamer** [comment]
Yes, they are defined in the same file, but they are written… ekhm… without reusability in mind (to put it mildly) :(

Also, just a heads up: we had a code conflict in this area recently, I suspect upstream might be planning some development in mount/imgmount implementations.

Recently I tried to implement #92 and reduce code complexity in that area, but this code is so [tightly coupled](https://en.wikipedia.org/wiki/Coupling_(computer_programming)), that it's hard to finish this work without introducing code duplication :(

**Comment by i30817** [comment]
Absolutely ask if there are plans for anything and delay as long as something is in the works first. I've waited several years with duplicate data for scummvm on the few games affected, i can wait a bit more.

**Comment by dreamer** [comment]
I think I am *persona non grata* at Vogons forum, DOSBox maintainers generally stopped talking to me.

**Comment by Akuma-Git** [comment]
If space saving is most important you should look into ECM files.
These have their ECC data removed .
https://github.com/alucryd/ecm-tools

*. It an open source tool that runs in GNU/Linux, Windows and Mac OS X.

*. It achieves the size reduction by removing those error correction data from your disc images.

*. Supports a lot of popular disc image formats such as: ISO, NRG, BIN/CUE, CDI, CCD or any format that uses the Raw sector copying.

*. Has two built in tools for compressing and decompressing.

**Comment by i30817** [comment]
This is not about that. It's about sharing data between DOS and scummvm and other engines when the DOS game engines can tolerate it.

**Comment by kcgen** [comment]
@Akuma-Git , awesome suggestion regarding ECM.  I've spun this out into it's own issue. 

I'm a huge fan of ECM because it's reversible (ie: back to original BIN format), saves a considerable amount of disk space without any codec or algorithm needed, and permits efficient 2nd level compression (say, at the filesystem level) that's otherwise squandered due to ECC portion of each sector being virtual incompressible.

**Comment by kcgen** [comment]
@i30817 , agreed.  In cases where the ECC portion is unused in a BIN/CIE pair (such as is the case in some forms of copy protection), then it makes little sense in retaining it. Being able to lift out track 1 as a flat directory and subsequent tracks as FLACs would be the most transparent end state for a CDROM and allow for compatibility with Scummvm.

**Comment by Burrito78** [comment]
@kcgen I mean, in reality games are archived as BIN/CUE and thats it. I think until we get further requests for this functionality it's safe to close.
