### ISSUE TITLE
Keyboard not working on Rpi4 when running dosbox-staging in fullscreen mode via xinit

### ISSUE THREAD

**Issue by ectorhga** [dosbox-staging/dosbox-staging#994]
**Describe the bug**
I want to run dosbox-staging on my RetroPie (RPi4 with full kms/drm) using ```xinit```. Dosbox-staging performs much better for me that way. Without ```xinit``` I get crackling audio when I move the mouse and generally poor performance on SVGA games (Wing Commander 3+4, XCom3, The Settlers etc.) This might be another issue, but the best work around for me was using ```xinit```.
Whenever I'm in fullscreen mode, dosbox doesn't register any input from the keyboard and the joystick. I have to stop dosbox externally.
The mouse still works.

**To Reproduce**
Start dosbox-staging with ```xinit``` with either ```fullscreen=true``` or by pressing ```alt-enter``` in windowed mode. Dosbox-staging then doesn't register any input from keyboard or joystick.
This problem doen't exist in ```dosbox-svn```

**Expected behaviour**
Dosbox-staging runs flawless in fullscreen mode using xinit. :D

**Environment (please complete the following information):**
RetroPie 4.7.11 / ```Linux retropie 5.10.31-v7l+ #1412 SMP Wed Apr 21 15:45:18 BST 2021 armv7l GNU/Linux```
 KMS is enabled:
```
dtparam=audio=on
dtoverlay=vc4-kms-v3d,noaudio
```

**Version of dosbox-staging:**
dosbox (dosbox-staging), version 0.77.0

**Configuration parameters:**
My ```dosbox-staging.conf``` with which dosbox-staging registers no keyboard input when running with ```xinit```:
https://pastebin.com/6n1RShSM

**My semi-good workaround**
I've now set
```
[sdl]
fullscreen       = false
display          = 0
fullresolution   = desktop
windowresolution = 1920x1080
```
and that quasi-works. Performance is top-notch, Keyboard and Joystick works, but the screen is flushed to the top-left part of the screen, which is expected. Maybe there is a way to center the window on the screen, but I'm not that knowledgeable.

All the best! Dosbox-staging is honestly a god-send!

**Comment by kcgen** [comment]
Thanks for the detailed report, @ectorhga!  Glad to have another Pi user drop by :-)

When you have a chance, can you try the `**kc/capture-input-1**` branch?

@nemo93's and myself typically run Staging from the console using the texture renderer and the OpenGLES2 backend rendering to the Pi's framebuffer. @nemo93 has a thorough write-up and steps here: https://github.com/dosbox-staging/dosbox-staging/wiki/retropie-integration

The idea of wrapping DOSBox inside an Xorg session is very interesting. I see from your configuration that this also permits using GLShaders - so this is another bonus, especially if performance is excellent!

If you can run this configuration with a fixed fixed-cycle count,  how high can you take your cycles before overload (stuffering, etc)? Just curious - so we can compare against the framebuffer mode!   On my Pi3B (non-plus), I can get ~30k. 

You can see more Pi4 discussion here too: https://github.com/dosbox-staging/dosbox-staging/issues/420

**Comment by ectorhga** [comment]
Hey, thanks for getting back so soon!
I will try that branch as soon as I can! Probably tomorrow. 

Nemo93 was the one on the RetroPie forums who helped me a lot getting ```staging```to run in the first place and getting the grips with it.

The idea to wrap dosbox into Xorg, was also someone else's at the RetroPie forum. There, it was used to get ```dosbox-svn```to run in fullscreen without using ```dispmanx```. So I thought: why not try ```staging``` with this trick, too! Before, I had many problems with crackling sound related to mouse movement, and that went away instantly with ```xinit```.

Before I had set fixed cycles in the ```dosbox-staging.conf``` (around 25000 seemed like a sweet spot) More than 30000 usually lead to overloading the cpu. I have read a lot about optimizing ```staging``` and fixed cycles was one of the most important tricks. 

But just now I found out another great thing while I was comparing ```staging```with ```svn```. With ```svn``` I found that ```cycles=auto``` yielded the best results, as many of the later games (those later than 1995; usually with SVGA support) are running well with 70000 cycles (!?) ingame. But then the sound in any menu is totally broken and I have to lower the cycles again to saner counts. This is solved by setting cycles to ```auto```: Menus and ingame both play fluently.
 
So I tried the ```cycles=auto``` with ```staging```, and suddenly those games ran a lot better, too! No distortion, or slowdowns so far I can see. I tried Crusader: No Remorse, Wing Commander 3+4, Syndicate Wars, Terminal Velocity and Fallout (and maybe others, I can't remember). All are running with good speed and enabled shaders! I'm totally blown away! Maybe KMS really only shines when using Xorg?

There are now only a couple of games left, that run better with```svn```than with ```staging```: Pro Pinball Timeshock! and Dungeon Keeper (in SVGA). All the others are so close, that ```staging```with all it's benefits clearly wins!

**Comment by kcgen** [comment]
Very interesting experiments; sounds like you've found a new sweet-spot on the Pi :-)

The branch will focus the input and prevent the session from becoming stranded (it works on my Pi3; hopefully it works for you too).

I did find that without a window manger, hitting "alt + enter" two more times caused the session to go black, despite SDL internally believing that the Window is active and in-focus; no amount of SDL calls were able to bring the window back. I suspect this is partly due to SDL2, because the branch behaves fine when run inside a Window manager (like icewm).

```
sudo apt install icewm
ln -s $(which icewm-session) ~/.xinitrc
mkdir ~/.icewm
```

**~/.icewm/startup**
``` shell
#!/bin/sh
/usr/src/dosbox-staging/build/gcc-release/dosbox &
```

make it executable: `chmod +x ~/.icewm/startup`

then `startx`.

**Comment by ectorhga** [comment]
Hi, just did a quick test of the brach. It works as promised: Fullscreen, pixel-perfect scaling with inputs working.
Thanks for this quick bug squashing! Staging FTW!
