### ISSUE TITLE
Display current active mounted image while using IMGMOUNT mount swapping

### ISSUE THREAD

**Issue by Burrito78** [dosbox-staging/dosbox-staging#997]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when i have guess what disk i'm currently on while installing a game.

**Describe the solution you'd like**
Number of current active disk image vs. total loaded images. E.g. "Disk 7/12" or "CD 2/3" shown in title bar or Dosbox-Staging (future) overlay feature.

**Comment by dreamer** [comment]
> **Is your feature request related to a problem? Please describe.**
> I'm always frustrated when i have guess what disk i'm currently on while installing a game.
> 
> **Describe the solution you'd like**
> Number of current active disk image vs. total loaded images. E.g. "Disk 7/12" or "CD 2/3" shown in title bar or Dosbox-Staging (future) overlay feature.

What

**Comment by dreamer** [comment]
(closed by misclick)

Yup, identifying the currently inserted disk image is a usability problem… I tried to fit this information in the title bar in the past, but it didn't work well - the info was too cramped, and title bar is not visible in fullscreen anyway.

**Comment by arrowgent** [comment]
if not on the title bar then possibly in (linux) terminal output?

when you press the swap-disk keyboard shortcut it could report in stdout the required parameters?

i dont think im the only person in the world that launches certain tools from the terminal to see stdout
and keep that terminal open in the background

**Comment by kcgen** [comment]
From @Burrito78 : 

> IMGMOUNT should load all subsequent files after the first file is specified. Naming convention should be filenameNN.img or filenameN.img. That is easy and gets the job done.

**Comment by kcgen** [comment]
From @Grounded0:
> Status line should display currently loaded disk image filename

**Comment by johnnovak** [comment]
See main discussion & plans about the OSD feature here:
https://github.com/dosbox-staging/dosbox-staging/discussions/1953

**Comment by Burrito78** [comment]
Continued in #447 .

**Comment by johnnovak** [comment]
Covered in https://github.com/dosbox-staging/dosbox-staging/discussions/1953
