### ISSUE TITLE
Is there a way to run it directly in a linux terminal?

### ISSUE THREAD

**Issue by Toadfield** [dosbox-staging/dosbox-staging#999]
So that I can use dos tui programs directly in the terminal.

**Comment by kcgen** [comment]
Hi @Toadfield ,

I know it appears that the dosbox text prompt is sitting inside an unnecessary extra window, and that it should be able to run just any other Linux shell like bash or zsh. 

But DOSBox is actually emulating the original 80x25 video mode, drawing line by line, and even maintaining the expected framerate of that original DOS video mode.  It just happens to be showing a text prompt, which makes it appear deceiving trivial (but in actuality, it's not). 

If you've run virtual box or other VM software, then you can think of DOSBox as essentially the same: it's a virtualized x86 processor and hardware running a simulated DOS environment on-top of it; all in a little executable.

**Comment by Toadfield** [comment]
Yea,that explains it.
